cap label var B1GQ "Gross domestic product at market prices"
cap label var B1G "Value added, gross"
cap label var P1 "Output"
cap label var P2 "Intermediate consumption"
cap label var P3 "Final consumption expenditure"
cap label var P31 "Individual consumption expenditure"
cap label var P32 "Collective consumption expenditure"
cap label var P4 "Actual final consumption"
cap label var P3_S13 "Final consumption expenditure of general government"
cap label var P31_S13 "Individual consumption expenditure of general government"
cap label var P32_S13 "Collective consumption expenditure of general government"
cap label var P31_S14_S15 "Household and NPISH final consumption expenditure"
cap label var P31_S14 "Final consumption expenditure of households"
cap label var P31_S15 "Final consumption expenditure of NPISH"
cap label var P41 "Actual individual consumption"
cap label var P5G "Gross capital formation"
cap label var P5 "Gross capital formation"
cap label var P51G "Gross fixed capital formation"
cap label var P51G_S14_S15 "Gross fixed capital formation of households and NPISH"
cap label var P52_P53 "Changes in inventories and acquisitions less disposals of valuables"
cap label var P52 "Changes in inventories"
cap label var P53 "Acquisitions less disposals of valuables"
cap label var P6 "Exports of goods and services"
cap label var P61 "Exports of goods"
cap label var P62 "Exports of services"
cap label var P7 "Imports of goods and services"
cap label var P71 "Imports of goods"
cap label var P72 "Imports of services"
cap label var B11 "External balance of goods and services"
cap label var B111 "External balance - Goods"
cap label var B112 "External balance - Services"
cap label var D1 "Compensation of employees"
cap label var D11 "Wages and salaries"
cap label var D12 "Employers' social contributions"
cap label var D1_D61NET "Compensation of employees and Net social contributions (RECV-PAID)"
cap label var B2A3G "Operating surplus and mixed income, gross"
cap label var D2X3 "Taxes on production and imports less subsidies"
cap label var D2 "Taxes on production and imports"
cap label var TRF_CUR_D9 "Current and capital transfers (including subsidies)"
cap label var TRF_CUR "Current transfers (including subsidies)"
cap label var D3 "Subsidies"
cap label var TRF_CUR_XD3 "Current transfers (excluding subsidies)"
cap label var D21X31 "Taxes less subsidies on products"
cap label var D21 "Taxes on products"
cap label var D31 "Subsidies on products"
cap label var P2_D29_D5_D8 "Intermediate consumption; other taxes on production; current taxes on income, wealth, etc.; adjustment for the change in pension entitlements"
cap label var D29_D5_D8 "Other taxes on production; current taxes on income, wealth, etc; adjustment for the change in pension entitlements"
cap label var D4 "Property income"
cap label var D4_S1311 "Property income, of which payable to subsector S1311"
cap label var D4_S1312 "Property income, of which payable to subsector S1312"
cap label var D4_S1313 "Property income, of which payable to subsector S1313"
cap label var D4_S1314 "Property income, of which payable to subsector S1314"
cap label var D62_D632 "Social benefits other than social transfers in kind and social transfers in kind - purchased market production"
cap label var D62 "Social benefits other than social transfers in kind"
cap label var D632 "Social transfers in kind - purchased market production"
cap label var D7 "Other current transfers"
cap label var D7_S1311 "Other current transfers,of which payable to subsector S1311"
cap label var D7_S1312 "Other current transfers,of which payable to subsector S1312"
cap label var D7_S1313 "Other current transfers,of which payable to subsector S1313"
cap label var D7_S1314 "Other current transfers,of which payable to subsector S1314"
cap label var D9 "Capital transfers"
cap label var D92 "Investment grants"
cap label var D9_S1311 "Capital transfers, of which payable to subsector S1311"
cap label var D9_S1312 "Capital transfers, of which payable to subsector S1312"
cap label var D9_S1313 "Capital transfers, of which payable to subsector S1313"
cap label var D9_S1314 "Capital transfers, of which payable to subsector S1314"
cap label var OP5ANP "Gross capital formation and acquisitions less disposals of non-financial non-produced assets"
cap label var NP "Acquisitions less disposals of non-financial non-produced assets"
cap label var IN "Primary incomes and current transfers"
cap label var IN1 "Primary income"
cap label var IN2 "Secondary income"
cap label var IN21 "Secondary income: current transfers"
cap label var TE "Total general government expenditure"
cap label var P51C "Consumption of fixed capital"
cap label var B2A3N "Operating surplus and mixed income, net"
cap label var D29X39 "Other taxes less other subsidies on production"
cap label var YA1 "Statistical discrepancy (production approach)"
cap label var YA0 "Statistical discrepancy (expenditure approach)"
cap label var YA2 "Statistical discrepancy (income approach)"
cap label var P311_S14 "Final consumption expenditure of households, durable goods"
cap label var P312_S14 "Final consumption expenditure of households, semi-durable goods"
cap label var P313_S14 "Final consumption expenditure of households, non-durable goods"
cap label var P314_S14 "Final consumption expenditure of households, services"
cap label var P312N_S14 "Final consumption expenditure of households, semi-durable goods, non-durable goods and services"
cap label var P6_S21 "Exports of goods and services to the European Union"
cap label var P6_S211 "Exports of goods and services to the EU Member States"
cap label var P6_S2111 "Exports of goods and services to members of the Monetary Union"
cap label var P6_S2112 "Exports of goods and services to non-members of the Monetary Union"
cap label var P6_S212 "Exports of goods and services to the institutions of the EU"
cap label var P6_S22 "Exports of goods and services to third countries and international organisations"
cap label var P7_S21 "Imports of goods and services from the European Union"
cap label var P7_S211 "Imports of goods and services from the EU Member States"
cap label var P7_S2111 "Imports of goods and services from members of the Monetary Union"
cap label var P7_S2112 "Imports of goods and services from non-members of the Monetary Union"
cap label var P7_S212 "Imports of goods and services from the institutions of the EU"
cap label var P7_S22 "Imports of goods and services from third countries and international organisations"
cap label var P31_S14_NC "Final consumption expenditure of households (national concept)"
cap label var P33 "Final consumption expenditure of resident households in the rest of the world - total"
cap label var P34 "Final consumption expenditure of non-resident households on the economic territory - total"
cap label var P31_S14_DC "Final consumption expenditure of households (domestic concept)"
cap label var EMP_NC "Total employment national concept"
cap label var POP_NC "Total population national concept"
cap label var SAL_NC "Employees national concept"
cap label var SELF_NC "Self-employed national concept"
cap label var EMP_DC "Total employment domestic concept"
cap label var SAL_DC "Employees domestic concept"
cap label var SELF_DC "Self-employed domestic concept"
cap label var F "Total financial assets/liabilities"
cap label var F_TR "Net acquisition of financial assets/ Net incurrence of liabilities"
cap label var F1 "Monetary gold and special drawing rights (SDRs)"
cap label var F11 "Monetary gold"
cap label var F12 "Special drawing rights (SDRs)"
cap label var F2 "Currency and deposits"
cap label var F2_NAC "Currency and deposits, of which in national currency"
cap label var F21 "Currency"
cap label var F22 "Transferable deposits"
cap label var F221 "Interbank positions"
cap label var F229 "Other transferable deposits"
cap label var F29 "Other deposits"
cap label var F2_F8 "Total financial sector liabilities (excluding SDRs)"
cap label var F3 "Debt securities"
cap label var F3_NAC "Debt securities, of which in national currency"
cap label var F31 "Short-term debt securities"
cap label var F32 "Long-term debt securities"
cap label var F32_LESSY "Long-term debt securities - With remaining maturity of one year or less"
cap label var F32_OVERY "Long-term debt securities - With remaining maturity of more than one year"
cap label var F3_F4 "Securities other than shares, loans"
cap label var F4 "Loans"
cap label var F4_NAC "Loans, of which in national currency"
cap label var F41 "Short-term - Loans"
cap label var F41D "Short-term Loans - Of which: Repurchase agreement, securities lending & margin lending"
cap label var F42 "Long-term - Loans"
cap label var F42_LESSY "Long-term Loans - With remaining maturity of one year or less"
cap label var F42_OVERY "Long-term Loans - With remaining maturity of more than one year"
cap label var F5 "Equity and investment fund shares"
cap label var F51 "Equity"
cap label var F511 "Listed shares"
cap label var F512_F519 "Unlisted shares; other equity"
cap label var F512 "Unlisted shares"
cap label var F519 "Other equity"
cap label var F52 "Investment fund shares/ units"
cap label var F521 "Money market fund shares /units"
cap label var F522 "Non-Money market fund shares /units"
cap label var F6 "Insurance, pensions and standardised guarantees"
cap label var F61 "Non-life insurance technical reserves"
cap label var F61_F66 "Non life insurance technical reserves, and provisions for calls under standardised guarantees"
cap label var F62 "Life insurance and annuity entitlements"
cap label var F63 "Pension entitlements"
cap label var F63_LS "Pension entitlements in opening balance sheet"
cap label var F63_F64_F65 "Pension entitlements, claims of pension funds on pension managers and entitlements to non-pension benefits"
cap label var F64 "Claims of pension funds on pension managers"
cap label var F65 "Entitlements to non-pension benefits"
cap label var F64_F65 "Claims of pension funds on pension managers and entitlements to non-pension benefits"
cap label var F66 "Provisions for calls under standardised guarantees"
cap label var F7 "Financial derivatives and employee stock options"
cap label var F71 "Financial derivatives"
cap label var F711 "Options"
cap label var F712 "Forwards"
cap label var F72 "Employee stock options"
cap label var F8 "Other accounts receivable / payable"
cap label var F8_NAC "Other accounts receivable / payable, of which in national currency"
cap label var F81 "Trade credits and advances"
cap label var F89 "Other accounts receivable/payable, excluding trade credits and advances"
cap label var B9F "Net financial transactions"
cap label var B9FX9 "Discrepancy with the financial net lending/net borrowing (B9F-B9)"
cap label var BF90 "Financial net worth"
cap label var B102 "Changes in net worth due to other changes in volume of assets"
cap label var B103 "Changes in net worth due to nominal holding gains and losses"
cap label var D1_SAL_PER "Compensation per employee"
cap label var D1_SAL_HW "Compensation of employees per hour worked"
cap label var NLPR_PER "Nominal labour productivity per person"
cap label var NLPR_HW "Nominal labour productivity per hour worked"
cap label var RLPR_PER "Real labour productivity per person"
cap label var RLPR_HW "Real labour productivity per hour worked"
cap label var NULC_PER "Nominal unit labour cost based on persons"
cap label var NULC_HW "Nominal unit labour cost based on hours worked"
cap label var RULC_PER "Real unit labour cost based on persons"
cap label var RULC_HW "Real unit labour cost based on hours worked"
cap label var B1N "Value added, net"
cap label var B2N "Net operating surplus"
cap label var B5N "Balance of primary incomes/National income, net"
cap label var B6N "Disposable income, net"
cap label var B8G "Saving, gross"
cap label var B8N "Saving, net"
cap label var B9 "Net lending (+) /net borrowing (-)"
cap label var D1PAY "Compensation of employees, payable"
cap label var D2_D5_D91 "Total tax receipts"
cap label var D2_D5_D91_D61_M_D611V_D612_M_M_D "Total receipts from taxes and compulsory social contributions after deduction of amounts assessed but unlikely to be collected"
cap label var D2_D5_D91_D61_M_D612_M_D614_M_D9 "Total receipts from taxes and social contributions after deduction of amounts assessed but unlikely to be collected"
cap label var D2_D5_D91_D61_M_D995 "Total receipts from taxes and social contributions (including imputed social contributions) after deduction of amounts assessed but unlikely to be collected"
cap label var D211 "Value added type taxes (VAT)"
cap label var D211REC "VAT, receivable"
cap label var D212 "Taxes and duties on imports excluding VAT"
cap label var D2121 "Import duties"
cap label var D2122 "Taxes on imports excluding VAT and import duties"
cap label var D2122A "Levies on imported agricultural products"
cap label var D2122B "Monetary compensatory amounts on imports"
cap label var D2122C "Excise duties"
cap label var D2122D "General sales taxes"
cap label var D2122E "Taxes on specific services"
cap label var D2122F "Profits of import monopolies"
cap label var D214 "Taxes on products, except VAT and import taxes"
cap label var D214A "Excise duties and consumption taxes"
cap label var D214B "Stamp taxes"
cap label var D214C "Taxes on financial and capital transactions"
cap label var D214D "Car registration taxes"
cap label var D214E "Taxes on entertainment"
cap label var D214F "Taxes on lotteries, gambling and betting"
cap label var D214G "Taxes on insurance premiums"
cap label var D214H "Other taxes on specific services"
cap label var D214I "General sales or turnover taxes"
cap label var D214J "Profits of fiscal monopolies"
cap label var D214K "Export duties and monetary compensatory amounts on exports"
cap label var D214L "Other taxes on products n.e.c."
cap label var D21REC "Taxes on products, receivable"
cap label var D29 "Other taxes on production"
cap label var D29A "Taxes on land, buildings and other structures"
cap label var D29B "Taxes on the use of fixed assets"
cap label var D29C "Total wage bill and payroll taxes"
cap label var D29D "Taxes on international transactions"
cap label var D29E "Business and professional licences"
cap label var D29F "Taxes on pollution"
cap label var D29G "Under-compensation of VAT (flat rate system)"
cap label var D29H "Other taxes on production n.e.c."
cap label var D29PAY "Other taxes on production, payable"
cap label var D29REC "Other taxes on production, receivable"
cap label var D2REC "Taxes on production and imports, receivable"
cap label var D31PAY "Subsidies on products, payable"
cap label var D39PAY "Other subsidies on production, payable"
cap label var D39REC "Other subsidies on production, receivable"
cap label var D3PAY "Subsidies, payable"
cap label var D41PAY "Interest, payable"
cap label var D41REC "Interest, receivable"
cap label var D42_TO_D45PAY "Other property income, payable"
cap label var D42_TO_D45REC "Other property income, receivable"
cap label var D4CO "Property income, consolidated"
cap label var D4PAY "Property income, payable"
cap label var D4PAY_S1311 "Property income payable, of which payable to subsector S1311"
cap label var D4PAY_S1312 "Property income payable, of which payable to subsector S1312"
cap label var D4PAY_S1313 "Property income, payable, of which payable to subsector S1313"
cap label var D4PAY_S1314 "Property income, payable, of which payable to subsector S1314"
cap label var D4REC "Property income, receivable"
cap label var D5 "Current taxes on income, wealth, etc."
cap label var D51 "Taxes on income"
cap label var D51A "Taxes on individual or household income"
cap label var D51A_C1 "Taxes on individual or household income including holding gains"
cap label var D51B "Taxes on the income or profits of corporations"
cap label var D51B_C2 "Taxes on the income or profits of corporations including holding gains"
cap label var D51C "Taxes on holding gains"
cap label var D51C1 "Taxes on individual or household holding gains"
cap label var D51C2 "Taxes on holding gains of corporations"
cap label var D51C3 "Other taxes on holding gains"
cap label var D51D "Taxes on winnings from lottery or gambling"
cap label var D51E "Other taxes on income n.e.c."
cap label var D51REC "Taxes on income, receivable"
cap label var D59 "Other current taxes"
cap label var D59A "Current taxes on capital"
cap label var D59B "Poll taxes"
cap label var D59C "Expenditure taxes"
cap label var D59D "Payments by households for licences"
cap label var D59E "Taxes on international transactions"
cap label var D59F "Other current taxes n.e.c."
cap label var D59REC "Other current taxes, receivable"
cap label var D5PAY "Current taxes on income, wealth, etc., payable"
cap label var D5REC "Current taxes on income, wealth, etc., receivable"
cap label var D61 "Net social contributions"
cap label var D61_P "Net pension contributions"
cap label var D611 "Employers' actual social contributions"
cap label var D6111 "Employers' actual pension contributions"
cap label var D6112 "Employers' actual non-pension contributions"
cap label var D611C "Compulsory employers' actual social contributions"
cap label var D611REC "Employers' actual social contributions, receivable"
cap label var D611V "Voluntary employers' actual social contributions"
cap label var D612 "Employers' imputed social contributions"
cap label var D6121 "Employers' imputed pension contributions"
cap label var D6122 "Employers' imputed non-pension contributions"
cap label var D612REC "Imputed social contributions, receivable"
cap label var D6131 "Households' actual pension contributions"
cap label var D6132 "Households' actual non-pension contributions"
cap label var D613CE "Compulsory employees' actual social contributions"
cap label var D613CN "Compulsory actual social contributions by the non-employed"
cap label var D613C "Compulsory households' actual social contributions"
cap label var D613CS "Compulsory actual social contributions by the self-employed"
cap label var D613REC "Households' actual social contributions, receivable"
cap label var D613V "Voluntary households' actual social contributions"
cap label var D6141 "Households' pension contributions supplements"
cap label var D6142 "Households' non-pension contributions supplements"
cap label var D614REC "Households' social contributions supplements"
cap label var D61REC "Net social contributions, receivable"
cap label var D61SC "Social insurance scheme service charges"
cap label var D61SC_P "Minus: Pension insurance scheme service charges"
cap label var D619 "Other (actuarial) change of pension entitlements in social security pension schemes"
cap label var D62_P "Social insurance pension benefits"
cap label var D62_D632PAY "Social benefits other than social transfers in kind and social transfers in kind ? purchased market production, payable"
cap label var D62PAY "Social benefits other than social transfers in kind, payable"
cap label var D632PAY "Social transfers in kind ? purchased market production, payable"
cap label var D7CO "Other current transfers, consolidated"
cap label var D7PAY "Other current transfers, payable"
cap label var D7PAY_S1311 "Other current transfers, payable, of which payable to subsector S1311"
cap label var D7PAY_S1312 "Other current transfers, payable, of which payable to subsector S1312"
cap label var D7PAY_S1313 "Other current transfers, payable, of which payable to subsector S1313"
cap label var D7PAY_S1314 "Other current transfers, payable, of which payable to subsector S1314"
cap label var D7REC "Other current transfers, receivable"
cap label var D4_D7 "Property income and Other current transfers"
cap label var D8 "Adjustment for the change in pension entitlements"
cap label var D81 "Transfers of pension entitlements between scheme"
cap label var D82 "Change in pension entitlements due to negotiated changes in scheme structure"
cap label var D91 "Capital taxes"
cap label var D91A "Taxes on capital transfers"
cap label var D91B "Capital levies"
cap label var D91C "Other capital taxes n.e.c."
cap label var D91REC "Capital taxes, receivable"
cap label var D92_D99REC "Other capital transfers and investment grants, receivable"
cap label var D92AREC "Investment grants, receivable from EU institutions"
cap label var D92PAY "Investment grants, payable"
cap label var D995 "Capital transfers from general government to relevant sectors representing taxes and social contributions assessed but unlikely to be collected"
cap label var D995A "Taxes on products assessed but unlikely to be collected"
cap label var D995B "Other taxes on production assessed but unlikely to be collected"
cap label var D995C "Taxes on income assessed but unlikely to be collected"
cap label var D995D "Other current taxes assessed but unlikely to be collected"
cap label var D995E "Employers'actual social contributions assessed but unlikely to be collected"
cap label var D995F "Households'actual social contributions assessed but unlikely to be collected"
cap label var D995FE "Employees'actual social contributions assessed but unlikely to be collected"
cap label var D995FN "Actual social contributions by non-employed persons assessed but unlikely to be collected"
cap label var D995FS "Actual social contributions by self-employed persons assessed but unlikely to be collected"
cap label var D995G "Capital taxes assessed but unlikely to be collected"
cap label var D995REC "Capital transfers from general government to relevant sectors representing taxes and social contributions assessed but unlikely to be collected"
cap label var D9CO "Capital transfers,Consolidated"
cap label var D9PAY "Capital transfers, payable"
cap label var D9PAY_S1311 "Capital transfers, payable, of which payable to subsector S1311"
cap label var D9PAY_S1312 "Capital transfers, payable, of which payable to subsector S1312"
cap label var D9PAY_S1313 "Capital transfers, payable, of which payable to subsector S1313"
cap label var D9PAY_S1314 "Capital transfers, payable, of which payable to subsector S1314"
cap label var D9REC "Capital transfers, receivable"
cap label var K5 "Changes due to other changes in volume"
cap label var K7 "Changes due to revaluations"
cap label var F22_F29 "Transferable deposits; other deposits"
cap label var F63_LE "Pension entitlements in closing balance sheet"
cap label var GD "Government consolidated gross debt"
cap label var IGL_F4_EA19 "Intergovernmental lending within EA19 (from 2015)"
cap label var IGL_F4_EA18 "Intergovernmental lending within EA18 (2014)"
cap label var IGL_F4_EA17 "Intergovernmental lending within EA17 (2011-2013)"
cap label var IGL_F4_EA16 "Intergovernmental lending within EA16 (2009-2010)"
cap label var IGL_F4_EU27_2020 "Intergovernmental lending within EU27 (from 2020)"
cap label var IGL_F4_EU28 "Intergovernmental lending within EU28 (2013-2020)"
cap label var IGL_F4_EU27_2007 "Intergovernmental lending within EU27 (2007-2013)"
cap label var IGL_F4_EU25 "Intergovernmental lending within EU25 (2004-2006)"
cap label var ITR_CAP_INC "Implicit tax rate on capital, of which on capital and business income"
cap label var ITR_CAP_INCO "Implicit tax rate on capital, of which on capital and business income of corporations"
cap label var ITR_CAP_INHOSE "Implicit tax rate on capital, of which on capital and business income of households and self-employed"
cap label var ITR_CAP_TOT "Implicit tax rate on capital -  total"
cap label var ITR_CONS "Implicit tax rate on consumption"
cap label var ITR_LAB_EMPD "Implicit tax rate on labour"
cap label var P11_P12 "Market output and output for own final use"
cap label var P11_P12_P131 "Market output, output for own final use and payments for non-market output"
cap label var P13 "Other non-market output"
cap label var P131 "Payments for non-market output"
cap label var P132 "Other non-market output,other"
cap label var PTC "Total payable tax credits"
cap label var TC "Payable tax credits that exceed the taxpayer's liability"
cap label var TR "Total general government revenue"
cap label var TX_CAP_INC "Taxes on capital, of which on capital and business income"
cap label var TX_CAP_INCO "Taxes on capital, of which on capital and business income of corporations"
cap label var TX_CAP_INHO "Taxes on capital, of which on capital and business income of households"
cap label var TX_CAP_INSE "Taxes on capital, of which on capital and business income of self-employed"
cap label var TX_CAP_STO "Taxes on capital, of which on stock of capital (wealth)"
cap label var TX_CAP_TOT "Taxes on capital -Total"
cap label var TX_CONS "Taxes on consumption"
cap label var TX_LAB_EMPE "Taxes on labour, of which on employed paid by employees"
cap label var TX_LAB_EMPR "Taxes on labour, of which on employed paid by employers"
cap label var TX_LAB_NEMP "Taxes on labour, of which on non-employed"
cap label var TX_LAB_TOT "Taxes on labour - Total"
cap label var TX_X_AT "Taxes by economic function - taxes on alcohol and tobacco"
cap label var TX_X_T "Taxes by economic function - taxes on transport"
cap label var TX_X_E "Taxes by economic function - taxes on energy"
cap label var TX_X_P "Taxes by economic function - recurrent taxes on pollution"
cap label var TX_X_RS "Taxes by economic function - taxes on resources"
cap label var TX_X_RP "Taxes by economic function - recurrent taxes on immovable property"
cap label var TX_X_O "Taxes by economic function - other taxes on property"
cap label var B1NQ "Net domestic product at market prices"
cap label var B3G "Mixed income, gross"
cap label var B4G "Entrepreneurial income, gross"
cap label var B4N "Entrepreneurial income, net"
cap label var B5G "National income/Balance of primary incomes, gross"
cap label var B6G "Disposable income, gross"
cap label var B7G "Adjusted disposable income, gross"
cap label var B7G_EU27_2020_HAB "Adjusted disposable income per capita, gross (EU27_2020=100)"
cap label var B7G_N_HAB "Adjusted gross disposable income of households in nominal terms per capita"
cap label var B7G_N_HAB_GR "Adjusted gross disposable income of households in nominal terms per capita (percentage change on previous period)"
cap label var B7N "Adjusted disposable income, net"
cap label var B12 "Current external balance"
cap label var B101 "Change in net worth due to saving and capital transfers"
cap label var P1O "Market output, output for final use and payments for other non-market output"
cap label var P3F "Final consumption expenditure"
cap label var P62F "Exports of FISIM"
cap label var P72F "Imports of FISIM"
cap label var D39 "Other subsidies on production"
cap label var D4_R "Property income, received (resources)"
cap label var D4_U "Property income, paied (uses)"
cap label var D41 "Interest"
cap label var D41G "Total interest before FISIM allocation"
cap label var D42_TO_D45 "Property income other than interest"
cap label var D42 "Distributed income of corporations"
cap label var D43 "Reinvested earnings on direct foreign investment"
cap label var D43S2I "Reinvested earnings of Intra-EA F.D.I."
cap label var D43S2X "Reinvested earnings of Extra-EA F.D.I."
cap label var D43S21 "Reinvested earnings of Intra-EU F.D.I."
cap label var D43S22 "Reinvested earnings of Extra-EU F.D.I."
cap label var D44 "Other investment income"
cap label var D45 "Rents"
cap label var D5_U "Current taxes on income, wealth, etc. (uses)"
cap label var D6 "Social contributions and benefits"
cap label var D61NET "Net social contributions (RECV-PAID)"
cap label var D62NET "Net social benefits other than social transfers in kind (RECV-PAID)"
cap label var D63 "Social transfers in kind"
cap label var D631 "Social transfers in kind - non-market production"
cap label var D63NET "Net social transfer in kind (RECV-PAID)"
cap label var D7_R "Other current transfers, received (ressources)"
cap label var D7_U "Other crrent transfers, paied (uses)"
cap label var D71 "Net non-life insurance premiums"
cap label var D72 "Non-life insurance claims"
cap label var D74_TO_D76 "Other current transfers, n.e.c. (excl. transfers within general government)"
cap label var D74 "Current international cooperation"
cap label var D74_EUI "Current international cooperation paid to / received by European institutions"
cap label var D75 "Miscellaneous current transfers"
cap label var D76 "VAT and GNI - based EU own resources"
cap label var D8NET "Net adjustment for the change in pension entitlements (RECV-PAID)"
cap label var D92_TO_D99 "Investment grants and other capital transfers"
cap label var D99 "Other capital transfers"
cap label var OTE "Total general government expenditure"
cap label var OTR "Total general government revenue"
cap label var P31_CLV2000 "Final consumption expenditure - Chain linked volumes reference year 2000"
cap label var P51G_CLV2000 "Gross fixed capital formation - Chain linked volumes reference year 2000"
cap label var B1G_CLV2000 "Value added, gross - Chain linked volumes reference year 2000"
cap label var P31_CLV2010 "Final consumption expenditure - Chain linked volumes reference year 2010"
cap label var P51G_CLV2010 "Gross fixed capital formation - Chain linked volumes reference year 2010"
cap label var B1G_CLV2010 "Value added, gross - Chain linked volumes reference year 2010"
cap label var EMP_PS_DC "Total employment (thousands of persons) domestic concept"
cap label var EMP_HW_DC "Total employment (thousands of hours worked) domestic concept"
cap label var N111G "Assets, gross - Dwellings"
cap label var N211G "Assets, gross - Land"
cap label var P51G_N111G "Assets, gross - dwellings"
cap label var P51G_N112G "Assets, gross - other buildings and structures"
cap label var P51G_N1121G "Assets, gross - buildings other than dwellings"
cap label var P51G_N1122G "Assets, gross - other structures"
cap label var P51G_N11G_CLV2010 "Assets, gross - fixed assets by type of asset - chain linked volumes reference year 2010"
cap label var P51G_N111G_CLV2010 "Assets, gross - dwellings - chain linked volumes reference year 2010"
cap label var P51G_N112G_CLV2010 "Assets, gross - other buildings and structures - chain linked volumes reference year 2010"
cap label var P51G_N1121G_CLV2010 "Assets, gross - buildings other than dwellings - chain linked volumes reference year 2010"
cap label var P51G_N1122G_CLV2010 "Assets, gross - other structures - chain linked volumes reference year 2010"
cap label var B6G_R_HAB "Gross disposable income of households in real terms per capita"
cap label var B6G_R_HAB_2008 "Gross disposable income of households in real terms per capita (2008=100)"
cap label var B7G_R_HAB "Adjusted gross disposable income of households in real terms per capita (units of currency)"
cap label var B7G_R_HAB_2008 "Adjusted gross disposable income of households in real terms per capita (2008=100)"
cap label var B7G_R_HAB_GR "Adjusted gross disposable income of households in real terms per capita (percentage change on previous period)"
cap label var P4_R_HAB "Actual final consumption in real terms per capita"
cap label var P4_R_HAB_GR "Actual final consumption in real terms per capita (percentage change on previous period)"
cap label var SRG_S14_S15 "Gross household saving rate (B8G/(B6G+D8Net)*100)"
cap label var IRG_S14_S15 "Gross investment rate of households (P51/(B6G+D8Net)*100)"
cap label var IRG_S11 "Gross investment rate of non-financial corporations (P51/B1G*100)"
cap label var B2G_B3G_RAT_S11 "Gross profit share of non-financial corporations (B2G_B3G/B1Q*100)"
cap label var P51G_RAT_GDP_S1 "Total investment to GDP ratio (S1_P51G/B1GQ*100)"
cap label var P51G_RAT_GDP_BUS "Business investment to GDP ratio (S11_S12_P51G/B1GQ*100)"
cap label var P51G_RAT_GDP_S13 "Government investment to GDP ratio (S13_P51G/B1GQ*100)"
cap label var P51G_RAT_GDP_S1M "Households investment to GDP ratio (S14_S15_P51G/B1GQ*100)"
cap label var ROCE_S11 "Gross return on capital employed, before taxes, of non-financial corporations: B2G_B3G/(AF2+AF3+AF4+AF5, liab - assets)"
cap label var DIR_S11 "Net debt-to-income ratio, after taxes, of non-financial corporations: (AF2+AF3+AF4, liab - assets)/(B4N-D5PAY)"
cap label var ROE_S11 "Net return on equity, after taxes, of non-financial corporations: (B4N-D5PAY)/(AF5, liab - assets)"
cap label var DIR_S14_S15 "Gross debt-to-income ratio of households: (AF4, liab)/(B6G+D8net)"
cap label var NFW_S14_S15 "Household net financial assets ratio (BF90/(B6G+D8net))"
cap label var B2G "Operating surplus, gross"
cap label var B5GQ "Gross national income at market prices"
cap label var B5NQ "Net national income at market prices"
cap label var P11 "Market output"
cap label var P12 "Output for own final use"
cap label var D11PAY "Wages and salaries, payable"
cap label var D12PAY "Employers' social contributions, payables"
cap label var D3REC_S212 "Subsidies, receivable from the EU institutions"
cap label var D51A_C1REC "Taxes on individual or household income including holding gains, receivable"
cap label var D51B_C2REC "Taxes on the income or profits of corporations including holding gains, receivable"
cap label var D7REC_S212 "Other current transfers, receivable from the EU institutions"
cap label var D71REC "Net non-life insurance premiums, receivable"
cap label var D72REC "Non-life insurance claims, receivable"
cap label var D73REC "Current transfers within general government, receivable"
cap label var D74REC "Current international cooperation, receivable"
cap label var D74REC_S212 "Current international cooperation, receivable from the EU institutions"
cap label var D75REC "Miscellaneous current transfers, receivable"
cap label var D76REC "VAT- and GNI-based EU own resources, receivable"
cap label var D71PAY "Net non-life insurance premiums payable"
cap label var D72PAY "Non-life insurance claims payable"
cap label var D73PAY "Current transfers within general government payable"
cap label var D74PAY "Current international cooperation, payable"
cap label var D74PAY_S212 "Current international cooperation, payable to the EU institutions"
cap label var D75PAY "Miscellaneous current transfers payable"
cap label var D76PAY "VAT- and GNI-based EU own resources payable"
cap label var D9PAY_S2 "Capital transfers, payable to the EU institutions"
cap label var D9REC_S2 "Capital transfers, receivable to the EU institutions"
cap label var D9PAY_S212 "Capital transfers, payable to the EU institutions"
cap label var D9REC_S212 "Capital transfers, receivable from the EU institutions"
cap label var D92REC "Investment grants, receivable"
cap label var D99REC "Other capital transfers, receivable"
cap label var D99PAY "Other capital transfers, payable"
cap label var D41GREC "Interest before FISIM allocation, receivable"
cap label var D42REC "Distributed income of corporations, receivable"
cap label var D43REC "Reinvested earnings on foreign direct investment, receivable"
cap label var D44REC "Other investment income, receivable"
cap label var D45REC "Rent, receivable"
cap label var D41GPAY "Interest before FISIM allocation, payable"
cap label var D42PAY "Distributed income of corporations, payable"
cap label var D43PAY "Reinvested earnings on foreign direct investment, payable"
cap label var D44PAY "Other investment income, payable"
cap label var D45PAY "Rent, payable"
cap label var D62PAY_GF1002 "Social benefits other than social transfers in kind, payable, of which COFOG 10.2 old age"
cap label var D62PAY_GF1003 "Social benefits other than social transfers in kind, payable, of which COFOG 10.3 survivors"
cap label var D62PAY_GF1005 "Social benefits other than social transfers in kind, payable, of which COFOG 10.5 unemployment"
cap label var P3_P5 "Final consumption expenditure and gross capital formation"
cap label var P3_P6 "Final consumption expenditure, gross capital formation and exports of goods and services"
cap label var D421 "Dividends"
cap label var D422 "Withdrawals from the income of quasi-corporations"
cap label var D441 "Investment income attributable to insurance policy holders"
cap label var D442 "Investment income payable on pensions entitlements"
cap label var D443 "Investment income attributable to collective investment fund shareholders"
cap label var D613 "Households' actual social contributions"
cap label var D614 "Households' social contributions supplements"
cap label var B6G_R "Gross disposable income of households in real terms (percentage change on previous period)"
cap label var GD_F2 "Government consolidated gross debt at face value - Currency and deposits"
cap label var GD_F3 "Government consolidated gross debt at face value - Debt securities"
cap label var GD_F31 "Government consolidated gross debt at face value - Short-term debt securities"
cap label var GD_F32 "Government consolidated gross debt at face value - Long-term debt securities"
cap label var GD_F4 "Government consolidated gross debt at face value - Loans"
cap label var GD_F41 "Government consolidated gross debt at face value - Short-term loans"
cap label var GD_F42 "Government consolidated gross debt at face value - Long-term loans"
cap label var AF_81L "Trade credits and advances - liabilities"
cap label var ORWB "Working balance"
cap label var FT "Financial transactions included in the working balance"
cap label var F4_ORWB "Financial transactions included in the working balance - Loans (+/-)"
cap label var F5_ORWB "Financial transactions included in the working balance -  Equity and investment fund shares (+/-)"
cap label var F4_ACQ_ORWB "Financial transactions included in the working balance - Loans; acquisition/increase (+)"
cap label var F4_DIS_ORWB "Financial transactions included in the working balance - Loans; disposal/reduction (-)"
cap label var F5_ACQ_ORWB "Financial transactions included in the working balance - Equity and investment fund shares; acquisition/increase (+)"
cap label var F5_DIS_ORWB "Financial transactions included in the working balance - Equity and investment fund shares; disposal/reduction (-)"
cap label var FNDX_ORWB "Financial transactions included in the working balance - Other financial transactions (+/-)"
cap label var FNDL_ORWB "Financial transactions included in the working balance - Other financial transactions (+/-), of which: transactions in debt liabilities (+/-)"
cap label var F71K_ORWB "Financial transactions included in the working balance - Other financial transactions (+/-), of which: net settlements under swap contracts (+/-)"
cap label var ORNF_ORWB "Non-financial transactions not included in the working balance"
cap label var ORD41A_ORWB "Difference between interest (D.41) paid (+) and accrued (-) included in the working balance"
cap label var F8_ASS_ORWB "Other accounts receivable (+) included in the working balance"
cap label var F8_LIAB_ORWB "Other accounts payable (-) included in the working balance"
cap label var ORWB_E "Working balance (+/-) of entities not part of the subsector"
cap label var B9_OB "Net lending (+) /net borrowing (-) of other bodies of the subsector  included in the working balance"
cap label var OROA_ORWB "Other adjustments (+/-)  included in the working balance"
cap label var B9_T3 "Net lending (-)/Net borrowing (+) (reversed sign)"
cap label var F_ASS "Net acquisition (+) of financial assets"
cap label var F2_ASS "Net acquisition (+) of financial assets - Currency and deposits"
cap label var F3_ASS "Net acquisition (+) of financial assets - Debt securities"
cap label var F4_ASS "Net acquisition (+) of financial assets - Loans"
cap label var F4_ACQ_ASS "Net acquisition (+) of financial assets - Loans - acquisition/increase (+)"
cap label var F4_DIS_ASS "Net acquisition (+) of financial assets - Loans; disposal/reduction (-)"
cap label var F41_ASS "Net acquisition (+) of financial assets - Short-term - Loans"
cap label var F42_ASS "Net acquisition (+) of financial assets - Long-term - Loans"
cap label var F42_ACQ_ASS "Net acquisition (+) of financial assets - Long-term loans; acquisition/increase (+)"
cap label var F42_DIS_ASS "Net acquisition (+) of financial assets - Long-term loans; disposal/reduction (-)"
cap label var F5_ASS "Net acquisition (+) of financial assets - Equity and investment fund shares/units"
cap label var F5PN_ASS "Net acquisition (+) of financial assets - Equity and investment fund shares/units - Portfolio investments, net"
cap label var F5OP_ASS "Net acquisition (+) of financial assets - Equity and investment fund shares/units other than portfolio investments"
cap label var F5OP_ACQ_ASS "Net acquisition (+) of financial assets - Equity and investment fund shares/units other than portfolio investments; acquisition/increase (+)"
cap label var F5OP_DIS_ASS "Net acquisition (+) of financial assets - Equity and investment fund shares/units other than portfolio investments; disposal/reduction (-)"
cap label var F71_ASS "Net acquisition (+) of financial assets - Financial derivatives"
cap label var F8_ASS "Net acquisition (+) of financial assets - Other accounts receivable (+)"
cap label var FN_ASS "Net acquisition (+) of financial assets - Other financial assets (F.1, F.6)"
cap label var ORADJ "Total adjustments"
cap label var F71_ADJ_LIAB "Adjustments: net incurrence (-) of liabilities in financial derivatives"
cap label var F8_ADJ_LIAB "Adjustments: Net incurrence (-) of other accounts payable"
cap label var FV_ADJ_LIAB "Adjustments: Net incurrence (-) of other liabilities (F.1, F.5, F.6  and F.72)"
cap label var ORINV "Adjustments: issuances above (-)/below (+) nominal value"
cap label var ORD41A_ADJ "Adjustments: difference between interest expenditure (D.41) accrued (-) and paid (+)"
cap label var ORRNV "Adjustments: redemptions/repurchase of debt above (+)/below (-) nominal value"
cap label var ORFCD "Adjustments: appreciation (+)/depreciation (-) of foreign currency debt"
cap label var K61 "Changes in sector classification and structure (+/-)"
cap label var KX "Adjustments: other volume changes in financial liabilities (-)"
cap label var YA3 "Total statistical discrepancies"
cap label var YA3O "Statistical discrepancies: other statistical discrepancies (+/-)"
cap label var GD_CH "Change in consolidated gross debt"
cap label var GD_CTB "Subsector contribution to general government gross debt"
cap label var GD_HOLD "Holdings of other subsectors' debt"
cap label var FGT "Total stock of government guarantees"
cap label var FGO_T "One-off guarantees - Total stock of guarantees, excluding debt assumed by government"
cap label var FGO_PC "One-off guarantees - Total stock of guarantees, excluding debt assumed by government, of which: public corporations"
cap label var FGO_FC "One-off guarantees - Total stock of guarantees, excluding debt assumed by government, Memo item: financial corporations"
cap label var FGST "Standardised guarantees - Total stock of government guarantees"
cap label var TLGCE "Total outstanding liabilities of  government controlled entities classified outside general government"
cap label var LIFA "Total outstanding liabilities of  government controlled entities classified outside general government, of which: Liabilities of units involved in financial activities"
cap label var LIOA "Total outstanding liabilities of  government controlled entities classified outside general government, of which: Liabilities of units involved in other activities"
cap label var LIOALM "Total outstanding liabilities of  government controlled entities classified outside general government, of which: Liabilities of units involved in other activities, of which loss-making non-financial units"
cap label var OFF_PPP "Adjusted capital value of off-balance private-public partnerships (PPPs)"
cap label var F4M2 "Stock of non-performing loans provided by government"
cap label var PPP_EU27_2020 "Purchasing power parities (EU27_2020=1)"
cap label var PPP_EU28 "Purchasing power parities (EU28=1)"
cap label var PPP_EU27_2007 "Purchasing power parities (EU27_2007=1)"
cap label var PPP_EU15 "Purchasing power parities (EU15=1)"
cap label var PLI_EU27_2020 "Price level indices (EU27_2020=100)"
cap label var PLI_EU28 "Price level indices (EU28=100)"
cap label var PLI_EU27_2007 "Price level indices (EU27_2007=100)"
cap label var PLI_EU15 "Price level indices (EU15=100)"
cap label var EXP_NAC "Nominal expenditure in national currency"
cap label var EXP_NAC_PC_GDP "Nominal expenditure as a percentage of GDP (GDP=100)"
cap label var EXP_EUR "Nominal expenditure (in euro)"
cap label var EXP_EUR_HAB "Nominal expenditure per inhabitant (in euro)"
cap label var EXP_PPS_EU27_2020 "Real expenditure (in PPS_EU27_2020)"
cap label var EXP_PPS_EU28 "Real expenditure (in PPS_EU28)"
cap label var EXP_PPS_EU27_2007 "Real expenditure (in PPS_EU27_2007)"
cap label var EXP_PPS_EU15 "Real expenditure (in PPS_EU15)"
cap label var EXP_PPS_EU27_2020_HAB "Real expenditure per capita (in PPS_EU27_2020)"
cap label var EXP_PPS_EU28_HAB "Real expenditure per capita (in PPS_EU28)"
cap label var EXP_PPS_EU27_2007_HAB "Real expenditure per capita (in PPS_EU27_2007)"
cap label var EXP_PPS_EU15_HAB "Real expenditure per capita (in PPS_EU15)"
cap label var VI_PPS_EU27_2020_HAB "Volume indices of real expenditure per capita (in PPS_EU27_2020=100)"
cap label var VI_PPS_EU28_HAB "Volume indices of real expenditure per capita (in PPS_EU28=100)"
cap label var VI_PPS_EU27_2007_HAB "Volume indices of real expenditure per capita (in PPS_EU27_2007=100)"
cap label var VI_PPS_EU15_HAB "Volume indices of real expenditure per capita (in PPS_EU15=100)"
cap label var CV_VI_HAB "Coefficient of variation of volume indices of expenditure per capita (percentage)"
cap label var GD_NAC "General government gross debt, of which in national currency"
cap label var GD_FOR "General government gross debt, of which in foreign currency"
cap label var GD_S1 "General government gross debt, of which domestic counterparts"
cap label var GD_S2 "General government gross debt, of which non-domestic counterparts"
cap label var GD_LL "General government gross debt, long-term original maturity, of which payment due in more than one year"
cap label var GD_TS "General government gross debt, short-term remaining maturity"
cap label var SRG_S14 "Gross household saving rate (B8G/(B6G+D8Net)*100)"
cap label var IRG_S14 "Gross investment rate of households (P51G/(B6G+D8Net)*100)"
cap label var P51G_RAT_GDP_S14 "Households investment to GDP ratio (S14_S15_P51/B1GQ*100)"
cap label var DIR_S14 "Gross debt-to-income ratio of households: (AF4, liab)/(B6G+D8net)"
cap label var NFW_S14 "Household net financial assets ratio (BF90/(B6G+D8net)"
cap label var TAXABT "Tax abatements"
cap label var EMP_HAB "Total employment (employed persons) per capita"
cap label var HW_HAB "Hours worked per capita"
cap label var HW_EMP "Hours worked per employed person"
cap label var HW_SELF "Hours worked per self-employed person"
cap label var HW_SAL "Hours worked per employee"
cap label var NCS_EMP "Net fixed assets per employed person"
cap label var NCS_HW "Net fixed assets per hour worked"
cap label var GVA_NCS "Gross value added per unit of net fixed assets"
cap label var NCS_GVA "Net fixed assets to gross value added"
