cap label var TOTAL "Total"
cap label var CREA "Job creation"
cap label var CREA_HS "Job creation - high skilled"
cap label var CREA_NHS "Job creation - not high skilled"
cap label var CREA_OTH "Job creation - other"
cap label var CREA_NAP "Job creation - not applicable"
cap label var CREA_UNK "Job creation - unknown"
cap label var MOV_HS "Moving jobs abroad - high skilled"
cap label var MOV_OTH "Moving jobs abroad - other"
cap label var LOSS "Job losses"
cap label var LOSS_HS "Job losses - high skilled"
cap label var LOSS_NHS "Job losses - not high skilled"
cap label var LOSS_NAP "Job losses - not applicable"
cap label var LOSS_UNK "Job losses - unknown"
cap label var MOB "Job mobility"
cap label var NMOB "No job mobility"
cap label var UNK "Unknown"
