cap label var TOTAL "Total"
cap label var LIFE "Life insurance enterprises"
cap label var NLIFE "Non-life insurance enterprises"
cap label var CMP "Composite insurance enterprises"
cap label var RINS "Specialist reinsurance enterprises"
cap label var CMP_LIFE "Life insurance business of composite insurance enterprises"
cap label var CMP_NLIFE "Non-life insurance business of composite insurance enterprises (including business accepted)"
cap label var AVIA "Aviation enterprises"
cap label var AIRP "Airport enterprises"
cap label var RL_OPER "Railway transport operator"
cap label var RL_INFR "Infrastructure manager"
cap label var RL_INTG "Integrated company"
cap label var DOM "Enterprises with domestic sourcing"
cap label var DOMC "Enterprises controlled by domestic owners"
cap label var DOMC_ABR "Enterprises controlled by domestic owners, with own affiliates abroad"
cap label var DOMC_NABR "Enterprises controlled by domestic owners, without own affiliates abroad"
cap label var FORC "Enterprises controlled by foreign owners"
cap label var INTL "Enterprises with international sourcing"
cap label var NINTL_PL "Enterprises with no current international sourcing but with future plans to do so"
cap label var NINTL_NPL "Enterprises with no current international sourcing and no future plans to do so"
cap label var BACK "Enterprises with backsourcing"
cap label var NBACK "Enterprises with no backsourcing"
cap label var RLC "Enterprises that relocated activities"
cap label var NRLC "Enterprises that did not relocate activities"
cap label var CTRL "Enterprises that controlled foreign affiliates"
cap label var NCTRL "Enterprises that did not control foreign affiliates"
cap label var CCLOSE_ABR "Enterprises that completely closed the activity abroad"
cap label var PCLOSE_ABR "Enterprises that moved the function while partially closing the activity abroad"
cap label var SAME_ABR "Enterprises that moved the function while leaving the activity abroad the same"
cap label var INCR_ABR "Enterprises that moved the function while increasing the activity abroad"
cap label var SPEC "Specialised enterprises"
cap label var NSPEC "Non-specialised enterprises"
cap label var HG "High-growth enterprises"
cap label var YHG "Young high-growth enterprises (gazelles)"
cap label var INN "Innovative enterprises"
cap label var INN_ITR "Entreprises that have introduced an innovation (all types)"
cap label var INN_ACT "Enterprises that have innovation activity, regardless of whether they have introduced an innovation (including enterprises with abandoned/suspended or on-going innovation activities)"
cap label var PRDPCS_ONL "Product and/or process innovative enterprises only (including enterprises with abandoned/suspended or on-going innovation activities)"
cap label var PRDPCS_ORGMKTG_ONL "Product and/or process and organisation and/or marketing innovative enterprises only (including enterprises with abandoned/suspended or on-going innovation activities)"
cap label var PRDPCSXABDONGO "Product and/or process innovative enterprises excluding enterprises with only on-going and/or abandoned activities"
cap label var PRDPCS "Product and/or process innovative enterprises (including enterprises with abandoned/suspended innovation activities)"
cap label var PRD_ONL "Product innovative enterprises only"
cap label var PRD "Product innovative enterprises (regardless of any other type of innovation)"
cap label var PRD_PCS_ONL "Product and process innovative enterprises only"
cap label var PCS_ONL "Process innovative enterprises only"
cap label var PCS "Process innovative enterprises (regardless of any other type of innovation)"
cap label var PRDBPCS "Product and/or business process innovative enterprises (including enterprises with completed/abandoned/suspended innovation activities regardless R&D)"
cap label var PRDBPCS_ONL "Product and/or business process innovative enterprises only (regardless of any other innovation activities)"
cap label var BPCS_ONL "Business process innovative enterprises only"
cap label var PRD_BPCS_ONL "Product and business process innovative enterprises only"
cap label var END "Enterprises with completed (implemented or not) innovation activities"
cap label var END_IMPL "Enterprises with completed and implemented innovation activities"
cap label var END_NIMPL "Enterprises with completed but not yet implemented innovation activities"
cap label var ABD "Enterprises with abandoned/suspended innovation activities"
cap label var ABD_ONL "Enterprises with abandoned/suspended innovation activities only"
cap label var ONGO "Enterprises with on-going innovation activities"
cap label var ONGO_ONL "Enterprises with on-going innovation activities only"
cap label var ABD_ONGO "Enterprises with abandoned/suspended and on-going innovation activities"
cap label var ABD_ONGO_ONL "Enterprises with abandoned/suspended and on-going innovation activities only"
cap label var ORGMKTG_ONL "Organisation and/or marketing innovative enterprises only"
cap label var ORGMKTG "Organisation and/or marketing innovative enterprises, regardless of product or process innovation"
cap label var ORG_MKTG_ONL "Organisation and marketing innovative enterprises only"
cap label var ORG_ONL "Organisation innovative enterprises only"
cap label var ORG "Organisation innovative enterprises (regardless of any other type of innovation)"
cap label var MKTG_ONL "Marketing innovative enterprises only"
cap label var MKTG "Marketing innovative enterprises (regardless of any other type of innovation)"
cap label var NINN "Non innovative enterprises"
cap label var NINN_ITR "Entreprises that have not introduced any innovation (regardless of whether they had any innovation activity)"
cap label var NINN_ACT "Enterprises that have no innovation activity (regardless of whether they have introduced an innovation)"
cap label var INN_PF1 "Enterprises that have developed product innovations themselves, with market novelties (profile I)"
cap label var INN_PF1_RND "Enterprises that have developed product innovations themselves, with market novelties, with R&D activities (profile I.A)"
cap label var INN_PF1_NRND "Enterprises that have developed product innovations themselves, with market novelties, without R&D activities (profile I.B)"
cap label var INN_PF2 "Enterprises that have developed product innovations themselves, without market novelties (profile II)"
cap label var INN_PF2_RND "Enterprises that have developed product innovations themselves, without market novelties, with R&D activities (profile II.A)"
cap label var INN_PF2_NRND "Enterprises that have developed product innovations themselves, without market novelties, without R&D activities (profile II.B)"
cap label var INN_PF3 "Enterprises that have developed business process innovations themselves, without product innovation (profile III)"
cap label var INN_PF3_RND "Enterprises that have developed business process innovations themselves, without product innovation, with R&D activities (profile III.A)"
cap label var INN_PF3_NRND "Enterprises that have developed business process innovations themselves, without product innovation, without R&D activities (profile III.B)"
cap label var INN_PF4 "Enterprises that have introduced but not themselves developed innovations (profile IV)"
cap label var INN_PF4_RND "Enterprises that have introduced but not themselves developed innovations, with R&D activities (profile IV.A)"
cap label var INN_PF4_NRND "Enterprises that have introduced but not themselves developed innovations, without R&D activities (profile IV.B)"
cap label var INN_PF5 "Enterprises that have innovation activities but not introduced any innovation (ongoing or abandoned innovation activities) (profile V)"
cap label var INN_PF5_RND "Enterprises that have (ongoing or abandoned) innovation activities but not introduced any innovation, with R&D activities (profile V.A)"
cap label var INN_PF5_NRND "Enterprises that have (ongoing or abandoned) innovation activities but not introduced any innovation, without R&D activities (profile V.B)"
cap label var NINN_PF6 "Enterprises that have no innovation activities but potential to innovate (profile VI)"
cap label var NINN_PF7 "Enterprises that have no innovation activities and no potential to innovate (profile VII)"
cap label var OTH "Other enterprises"
cap label var UNK "Unknown"
