cap label var TOTAL "Total"
cap label var F "Fungicides and bactericides"
cap label var F01 "Inorganic fungicides"
cap label var F01_01 "Copper compounds"
cap label var F01_02 "Inorganic sulfur"
cap label var F01_99 "Other inorganic fungicides"
cap label var F02 "Fungicides based on carbamates and dithiocarbamates"
cap label var F02_01 "Carbanilate fungicides"
cap label var F02_02 "Carbamate fungicides"
cap label var F02_03 "Dithiocarbamate fungicides"
cap label var F02_99 "Other fungicides based on carbamates and dithiocarbamates"
cap label var F03 "Fungicides based on benzimidazoles"
cap label var F03_01 "Benzimidazole fungicides"
cap label var F03_99 "Other fungicides based on benzimidazoles"
cap label var F04 "Fungicides based on imidazoles and triazoles"
cap label var F04_01 "Conazole fungicides"
cap label var F04_02 "Imidazole fungicides"
cap label var F04_99 "Other fungicides based on imidazoles and triazoles"
cap label var F05 "Fungicides based on morpholines"
cap label var F05_01 "Morpholine fungicides"
cap label var F05_99 "Other fungicides based on morpholines"
cap label var F06 "Fungicides of microbiological or botanical origin"
cap label var F06_01 "Microbiological fungicides"
cap label var F06_02 "Botanical fungicides"
cap label var F06_99 "Other fungicides of microbiological or botanical origin"
cap label var F07 "Bactericides"
cap label var F07_01 "Inorganic bactericides"
cap label var F99 "Other fungicides and bactericides"
cap label var F99_01 "Aliphatic nitrogen fungicides"
cap label var F99_02 "Amide fungicides"
cap label var F99_03 "Anilide fungicides"
cap label var F99_05 "Aromatic fungicides"
cap label var F99_06 "Dicarboximide fungicides"
cap label var F99_07 "Dinitroaniline fungicides"
cap label var F99_08 "Dinitrophenol fungicides"
cap label var F99_09 "Organophosphorus fungicides"
cap label var F99_10 "Oxazole fungicides"
cap label var F99_11 "Phenylpyrrole fungicides"
cap label var F99_12 "Phthalimide fungicides"
cap label var F99_13 "Pyrimidine fungicides"
cap label var F99_14 "Quinoline fungicides"
cap label var F99_15 "Quinone fungicides"
cap label var F99_16 "Strobilurine fungicides"
cap label var F99_17 "Urea fungicides"
cap label var F99_99 "Unclassified fungicides"
cap label var H "Herbicides, haulm destructors and moss killers"
cap label var H01 "Herbicides based on phenoxy-phytohormones"
cap label var H01_01 "Phenoxy herbicides"
cap label var H01_99 "Other herbicides based on phenoxy-phytohormones"
cap label var H02 "Herbicides based on triazines and triazinones"
cap label var H02_02 "Triazine herbicides"
cap label var H02_03 "Triazinone herbicides"
cap label var H02_99 "Other herbicides based on triazines and triazinones"
cap label var H03 "Herbicides based on amides and anilides"
cap label var H03_01 "Amide herbicides"
cap label var H03_02 "Anilide herbicides"
cap label var H03_03 "Chloroacetanilide herbicides"
cap label var H03_99 "Other herbicides based on amides and anilides"
cap label var H04 "Herbicides based on carbamates and bis-carbamates"
cap label var H04_01 "Bis-carbamate herbicides"
cap label var H04_02 "Carbamate herbicides"
cap label var H04_99 "Other herbicides based on carbamates and bis-carbamates"
cap label var H05 "Herbicides based on dinitroaniline derivatives"
cap label var H05_01 "Dinitroaniline herbicides"
cap label var H05_99 "Other herbicides based on dinitroaniline derivatives"
cap label var H06 "Herbicides based on derivatives of urea, of uracil or of sulfonylurea"
cap label var H06_01 "Sulfonylurea herbicides"
cap label var H06_02 "Uracil herbicides"
cap label var H06_03 "Urea herbicides"
cap label var H06_99 "Other herbicides based on derivatives of urea, of uracil or of sulfonylurea"
cap label var H99 "Other herbicides"
cap label var H99_01 "Aryloxyphenoxy- propionic herbicides"
cap label var H99_02 "Benzofurane herbicides"
cap label var H99_03 "Benzoic-acid herbicides"
cap label var H99_04 "Bipyridylium herbicides"
cap label var H99_05 "Cyclohexanedione herbicides"
cap label var H99_06 "Diazine herbicides"
cap label var H99_07 "Dicarboximide herbicides"
cap label var H99_08 "Diphenyl ether herbicides"
cap label var H99_09 "Imidazolinone herbicides"
cap label var H99_10 "Inorganic herbicides"
cap label var H99_11 "Isoxazole herbicides"
cap label var H99_13 "Nitrile herbicides"
cap label var H99_14 "Organophosphorus herbicides"
cap label var H99_15 "Phenylpyrazole herbicides"
cap label var H99_16 "Pyridazinone herbicides"
cap label var H99_17 "Pyridinecarboxamide herbicides"
cap label var H99_18 "Pyridinecarboxylic-acid herbicides"
cap label var H99_19 "Pyridyloxyacetic-acid herbicides"
cap label var H99_20 "Quinoline herbicides"
cap label var H99_21 "Thiadiazine herbicides"
cap label var H99_22 "Thiocarbamate herbicides"
cap label var H99_23 "Triazole herbicides"
cap label var H99_24 "Triazolinone herbicides"
cap label var H99_25 "Triazolone herbicides"
cap label var H99_26 "Triketone herbicides"
cap label var H99_99 "Unclassified herbicides"
cap label var I "Insecticides and acaricides"
cap label var I01 "Insecticides based on pyrethroids"
cap label var I01_01 "Pyrethroid insecticides"
cap label var I01_99 "Other insecticides based on pyrethroids"
cap label var I02 "Insecticides based on chlorinated hydrocarbons"
cap label var I02_01 "Anthranilic diamide insecticides"
cap label var I02_99 "Other insecticides based on chlorinated hydrocarbons"
cap label var I03 "Insecticides based on carbamates and oxime-carbamate"
cap label var I03_01 "Oxime-carbamate insecticides"
cap label var I03_02 "Carbamate insecticides"
cap label var I03_99 "Other insecticides based on carbamate and oxime-carbamate"
cap label var I04 "Insecticides based on organophosphates"
cap label var I04_01 "Organophosphorus insecticides"
cap label var I04_99 "Other insecticides based on organophosphates"
cap label var I05 "Insecticides of microbiological or botanical origin"
cap label var I05_01 "Microbiological insecticides"
cap label var I05_02 "Botanical insecticides"
cap label var I05_99 "Other insecticides of microbiological or botanical origin"
cap label var I06 "Acaricides"
cap label var I06_01 "Pyrazole acaricides"
cap label var I06_02 "Tetrazine acaricides"
cap label var I06_99 "Other acaricides"
cap label var I99 "Other insecticides"
cap label var I99_01 "Insecticides produced by fermentation"
cap label var I99_03 "Benzoylurea insecticides"
cap label var I99_04 "Carbazate insecticides"
cap label var I99_05 "Diazylhydrazine insecticides"
cap label var I99_06 "Insect growth regulators"
cap label var I99_08 "Nitroguanidine insecticides"
cap label var I99_09 "Organotin insecticides"
cap label var I99_10 "Oxadiazine insecticides"
cap label var I99_11 "Phenyl-ether insecticides"
cap label var I99_12 "Pyrazole (phenyl-) insecticides"
cap label var I99_13 "Pyridine insecticides"
cap label var I99_14 "Pyridylmethylamine insecticides"
cap label var I99_15 "Sulfite ester insecticides"
cap label var I99_17 "Tetronic acid insecticides"
cap label var I99_18 "Insect attractants straight chain lepidopteran pheromones (sclps)"
cap label var I99_19 "Other insect attractants"
cap label var I99_99 "Unclassified insecticides-acaricides"
cap label var M "Molluscicides"
cap label var M01 "Molluscicides"
cap label var M01_01 "Molluscicides"
cap label var PGR "Plant growth regulators"
cap label var PGR01 "Physiological plant growth regulators"
cap label var PGR01_01 "Physiological plant growth regulators"
cap label var PGR01_99 "Other physiological plant growth regulators"
cap label var PGR02 "Anti-sprouting products"
cap label var PGR02_02 "Anti-sprouting products"
cap label var PGR02_99 "Other anti-sprouting products"
cap label var PGR03 "Other plant growth regulators"
cap label var PGR03_99 "Other plant growth regulators"
cap label var ZR "Other plant protection products"
cap label var ZR01 "Mineral oils"
cap label var ZR01_01 "Mineral oils"
cap label var ZR02 "Vegetal oils"
cap label var ZR02_01 "Vegetal oils"
cap label var ZR03 "Soil sterilants (incl. nematicides)"
cap label var ZR03_01 "Methyl bromide"
cap label var ZR03_02 "Biological nematicides"
cap label var ZR03_03 "Organophosphorous nematicides"
cap label var ZR03_99 "Other soil sterilants"
cap label var ZR04 "Rodenticides"
cap label var ZR04_01 "Rodenticides"
cap label var ZR99 "All other plant protection products"
cap label var ZR99_01 "Disinfectants"
cap label var ZR99_02 "Repellents"
cap label var ZR99_99 "Other plant protection products"
