cap label var PSY "Psychological"
cap label var PHY_THRT "Physical (including threats)"
cap label var PHY_THRT_NSX "Physical (including threats and not sexual)"
cap label var SX "Sexual"
cap label var RAPE "Rape"
cap label var PHY_THRT_SX "Physical (including threats) or sexual"
cap label var PSY_PHY_THRT_SX "Psychological, physical (including threats) or sexual"
