cap label var TOT_FS "All revenues of financing schemes"
cap label var FS1 "Transfers from government domestic revenue"
cap label var FS11 "Internal transfers and grants"
cap label var FS12 "Transfers by government on behalf of specific groups"
cap label var FS13 "Subsidies"
cap label var FS14 "Other transfers from government domestic revenue"
cap label var FS2 "Transfers distributed by government from foreign origin"
cap label var FS3 "Social insurance contributions"
cap label var FS31 "Social insurance contributions from employees"
cap label var FS32 "Social insurance contributions from employers"
cap label var FS33 "Social insurance contributions from self-employed"
cap label var FS34 "Other social insurance contributions"
cap label var FS4 "Compulsory prepayment (other than FS.3)"
cap label var FS41 "Compulsory prepayment from individuals/households"
cap label var FS42 "Compulsory prepayment from employers"
cap label var FS43 "Other compulsory prepaid revenues"
cap label var FS5 "Voluntary prepayment"
cap label var FS51 "Voluntary prepayment from individuals/households"
cap label var FS52 "Voluntary prepayment from employers"
cap label var FS53 "Other voluntary prepaid revenues"
cap label var FS6 "Other domestic revenues n.e.c."
cap label var FS61 "Other revenues from households n.e.c."
cap label var FS62 "Other revenues from corporations n.e.c."
cap label var FS63 "Other revenues from NPISH n.e.c."
cap label var FS7 "Direct foreign transfers"
