cap label var AGRAREA_HA "Utilised agricultural area (ha)"
cap label var LFD_AWU "AWU:Labour force - directly employed by the holding"
cap label var HOLD_HOLD "hold:No. of holdings"
cap label var HOLD "No. of holdings"
cap label var HOLDSL_HOLD "hold:Sole holder holdings"
cap label var HOLDLEG_GRP_HOLD "hold:Legal persons or group holdings"
cap label var SGM_ESU "ESU:SGM of the holding"
cap label var TOTAREA_HA "ha:Total area"
cap label var TOTAREA "Total area"
cap label var AGRAREA "Utilised agricultural area"
cap label var CC01_HA "ha:Farming by owner:Agricultural area"
cap label var CC01 "Farming by owner:Agricultural area"
cap label var CC02_HA "ha:Farming by tenant:Agricultural area"
cap label var CC02 "Farming by tenant:Agricultural area"
cap label var CC03_HA "ha:Shared farming or other modes::Agricultural area"
cap label var CC03 "Shared farming or other modes::Agricultural area"
cap label var CC05 "Holdings with organic or low-input farming"
cap label var D "Arable land"
cap label var D01_09_13D1 "Cereals, oilseeds, protein crops"
cap label var D01_08 "Cereals"
cap label var D01 "Common wheat and spelt"
cap label var D02 "Durum wheat"
cap label var D03 "Rye"
cap label var D04 "Barley"
cap label var D05 "Oats"
cap label var D06 "Grain maize"
cap label var D07 "Rice"
cap label var D08 "Other cereals"
cap label var D09 "Pulses - total"
cap label var D09C "Pulses - fodder peas"
cap label var D09D "Pulses - fodder field beans"
cap label var D10_12 "Root crops"
cap label var D10 "Potatoes"
cap label var D11 "Sugar beet"
cap label var D12_18_F "Fodder crops and grass"
cap label var D12 "Fodder roots and brassicas"
cap label var D13 "Industrial plants"
cap label var D13A "Tobacco"
cap label var D13B "Hops"
cap label var D13C "Cotton"
cap label var D13D "Other industrial plants"
cap label var D13D1 "Total:Other oil-seed or fibre plants"
cap label var D13D1A "Rape and turnip:Other oil-seed or fibre plants"
cap label var D13D1B "Sunflower:Other oil-seed or fibre plants"
cap label var D13D1C "Soya:Other oil-seed or fibre plants"
cap label var D13D1D "Others:Other oil-seed or fibre plants"
cap label var TEXT_CRP "Textile crops (including cotton, flax, hemp)"
cap label var D13D2 "Aromatic-, medicinal and culinary plants"
cap label var D13D3 "Industrial plants - Others"
cap label var D14_15 "Fresh vegetables, melons, strawberries"
cap label var D14 "Outdoor:Fresh vegetables, melons, strawberries"
cap label var D14A "Open field:Outdoor:Fresh vegetables, melons, strawberries"
cap label var D14B "Market gardening:Outdoor:Fresh vegetables, melons, strawberries"
cap label var D15_17_G07 "Under glass:Vegetables, flowers and permanent crops"
cap label var D15 "Under glass:Fresh vegetables, melons, strawberries"
cap label var D16_17 "Flowers and ornemental plants"
cap label var D16 "Outdoor:Flowers and ornemental plants"
cap label var D17 "Under glass:Flowers and ornemental plants"
cap label var D18 "Forage plants - total"
cap label var D18A "Forage plants - temporary grass"
cap label var D18B "Total:Other green fodder:Forage plants"
cap label var D18B1 "Green maize:Other green fodder:Forage plants"
cap label var D18B2 "Leguminous plants:Other green fodder:Forage plants"
cap label var D19_20 "Seeds, seedlings and other crops on arable land"
cap label var D19 "Seeds and seedlings"
cap label var D20 "Other crops"
cap label var D21_22 "Fallow land"
cap label var D21 "Fallow land without subsidies"
cap label var D22 "Non-productive arable land, eligible for support"
cap label var E "Kitchen gardens"
cap label var F "Total:Permanent grassland and meadow"
cap label var F01 "Pasture and meadow:Permanent grassland and meadow"
cap label var F02 "Rough grazings:Permanent grassland and meadow"
cap label var F03 "Non-productive grassland, eligible for support"
cap label var G "Permanent crops"
cap label var G01 "Fruit and berry plantations - total"
cap label var G01A "Temperate climate:Fruit and berry plantations"
cap label var G01B "Subtropical climate:Fruit and berry plantations"
cap label var G01C "Nuts:Fruit and berry plantations"
cap label var G02 "Citrus plantations"
cap label var G03 "Olive plantations - total"
cap label var G03A "Olive plantations - table olives"
cap label var G03B "Olive plantations - oil production"
cap label var G04 "Vineyards - total"
cap label var G04A "Vineyards - quality wine"
cap label var G04B "Vineyards - other wines"
cap label var G04C "Vineyards - table grapes"
cap label var G04D "Vineyards - raisins"
cap label var G05 "Nurseries"
cap label var G06 "Other permanent crops"
cap label var G07 "Permanent crops under glass"
cap label var H "Other land"
cap label var H0103 "Unutilised land and other areas"
cap label var H02 "Wooded area"
cap label var H02F "Wooded area - for selling wood"
cap label var H02G "Wooded area - with short rotation"
cap label var I01 "Total:Successive secondary crops"
cap label var I01A "Non fodder cereals:Successive secondary crops"
cap label var I01B "Non fodder pulses:Successive secondary crops"
cap label var I01C "Non fodder oil-seed plants:Successive secondary crops"
cap label var I01D "Other:Successive secondary crops"
cap label var I02 "Mushrooms"
cap label var I03A "Total irrigable area"
cap label var I03B "Irrigated once a year:Total"
cap label var I03B1 "Irrigated once a year:Durum wheat"
cap label var I03B2 "Irrigated once a year:Maize"
cap label var I03B3 "Irrigated once a year:Potatoes"
cap label var I03B4 "Irrigated once a year:Sugar beet"
cap label var I03B5 "Irrigated once a year:Sunflower"
cap label var I03B6 "Irrigated once a year:Soya"
cap label var I03B7 "Irrigated once a year:Fodder plants"
cap label var I03B8 "Irrigated once a year:Fruit and berry orchards"
cap label var I03B9 "Irrigated once a year:Citrus fruit"
cap label var I03B10 "Irrigated once a year:Vines"
cap label var I04 "Area covered by greenhouses in use"
cap label var I05 "Combined crops"
cap label var I05A "Combined:Agricultural crops - forestry"
cap label var I05B "Combined:Permanent - annual crops"
cap label var I05C "Combined:Permanent - permanent crops"
cap label var I05D "Combined crops:Others"
cap label var I08 "Set-aside areas under incentive schemes - total"
cap label var I08A "Non-productive land, eligible for support"
cap label var I08AD22 "Fallow land with no economic use: Set-aside areas under incentive schemes"
cap label var I08B "Raw material for non-food purposes:Set-aside areas under incentive schemes"
cap label var I08C "Converted into permanent pasture: Set aside areas under incentive schemes"
cap label var I08D "Converted into wooded areas: Set aside areas under incentive schemes"
cap label var I08E "Others:Set aside areas under incentive schemes"
cap label var I09A_HA "ha:Crops for winter soil cover: Nutrients management"
cap label var I09A_HOLD "hold:Crops for winter soil cover: Nutrients management"
cap label var I09B_HA "ha:Crops for nitrogen fixing: Nutrients management"
cap label var I09B_HOLD "hold:Crops for nitrogen fixing: Nutrients management"
cap label var J_LSU "LSU:Livestock"
cap label var J "Livestock"
cap label var J01 "Equidae"
cap label var J01_10_LSU "LSU:Grazing"
cap label var J02_08 "Cattle"
cap label var J02 "Bovine <1 year old - total"
cap label var J02A "Bovine <1 year old - males"
cap label var J02B "Bovine <1 year old - females"
cap label var J03 "Bovine 1-<2 years - males"
cap label var J04 "Bovine 1-<2 years - females"
cap label var J05 "Bovine 2 years and older - males"
cap label var J06 "Heifers, 2 years and older"
cap label var J07 "Dairy cows"
cap label var J08 "Other cows, bovine 2 years old and over"
cap label var J09 "Sheep"
cap label var J09A "Sheep - breeding ewes"
cap label var J09B "Sheep - others"
cap label var J10 "Goats"
cap label var J10A "Goats - breeding females"
cap label var J10B "Goats - others"
cap label var J11_13_HEADS "head:Pigs"
cap label var J11_13 "Pigs"
cap label var J11 "Pigs - piglets under 20 kg"
cap label var J12 "Pigs - breeding sows over 50 kg"
cap label var J13 "Pigs - others"
cap label var J14_16_1000_HEADS "1000:Poultry"
cap label var J14_16 "Poultry (1000 heads)"
cap label var J14 "Poultry - broilers (1000 heads)"
cap label var J15 "Laying hens (1000 heads)"
cap label var J16 "Poultry - others (1000 heads)"
cap label var J17 "Rabbits (breeding females)"
cap label var J18 "Beehives"
cap label var J19A "Deer"
cap label var K01A "Four-wheel tractors, track-laying tractors, tool carriers belonging exclusively to the holding"
cap label var K01A0 "Tractors etc.< 40 kw belonging exclusively to the holding"
cap label var K01A3 "Tractors etc.40 - <60 kw belonging exclusively to the holding"
cap label var K01A41 "Tractors etc. 60 - <100 kw belonging exclusively to the holding"
cap label var K01A42 "Tractors etc. >=100 kw belonging exclusively to the holding"
cap label var K02A "Cultivators etc. belonging exclusively to the holding"
cap label var K03A_MACH "mach:Combine harvesters belonging exclusively to the holding"
cap label var K03 "Combine harvesters"
cap label var K03A "Combine harvesters belonging exclusively to the holding"
cap label var K09A "Other fully mechanised harvesters belonging exclusively to the holding"
cap label var B04_EQ_Y_HOLD "hold:Farm accounts are kept"
cap label var CC05B_EQ_Y_HOLD "hold:Other low-input farming practiced"
cap label var CC05C_EQ_Y_HOLD "hold:Agri-environmental premium is received"
cap label var CC05C1_EQ_Y_HOLD "hold:Payment for landscape included in the agri-environmental premium received"
cap label var J19_EQ_Y "Other livestock"
cap label var K01B_EQ_Y "Use in last 12 mths:Tractors etc. not belonging the holding"
cap label var K02B_EQ_Y "Use in last 12 mths:Cultivators etc. not belonging the holding"
cap label var K03B_EQ_Y "Use in last 12 mths:Combined harvestors not belonging the holding"
cap label var K09B_EQ_Y "Use in last 12 mths:Other fully mechanised harvestors not belonging the holding"
cap label var K10_EQ_M "Mobile irrigation equipment"
cap label var K10_EQ_F "Fixed irrigation equipment"
cap label var K10_EQ_I "Irrigation equipment, but not known if fixed or mobile"
cap label var K10_EQ_0 "No irrigation equipment"
cap label var L07_EQ_M_HOLD "hold:Sole holder-manager - major other gainful activity"
cap label var L07_EQ_M_AGRAREA_HA "ha AA:Sole holder-manager - major other gainful activity"
cap label var L07_EQ_S_HOLD "hold:Sole holder-manager - subsidiary other gainful activity"
cap label var L07_EQ_S_AGRAREA_HA "ha AA:Sole holder-manager - subsidiary other gainful activity"
cap label var L07_EQ_N_HOLD "hold:Sole holder-manager - no other gainful activity (L07=x)"
cap label var L07_EQ_N_AGRAREA_HA "ha AA:Sole holder-manager - no other gainful activity (L07=x)"
cap label var L08_EQ_M_HOLD "hold:Major other gainful activity:Spouse of the sole holder working on the holding"
cap label var L08_EQ_S_HOLD "hold:Subsidiary other gainful activity:Spouse of the sole holder"
cap label var L08_EQ_N_HOLD "hold:No other gainful activity:Spouse of the sole holder working on the holding(L08=n)"
cap label var L09A_PERS "pers:Major other gainful activity:Other family members of sole holder"
cap label var L09B_PERS "pers:Subsidiary other gainful activity:Other family members of sole holder"
cap label var LFH_M "Male:Sole holders"
cap label var LFH_F "Female:Sole holders"
cap label var LFH "Sole holders"
cap label var LFS_M "Male:Spouses of sole holders"
cap label var LFS_F "Female:Spouses of sole holders"
cap label var LFS "Spouses of sole holders"
cap label var LFROF_M "Male:Other family members of sole holders"
cap label var LFROF_F "Female:Other family members of sole holders"
cap label var LFROF "Other family members of sole holders:Labour force"
cap label var LFRF_M "Male:Family members of sole holders:Labour force"
cap label var LFRF_F "Female:Family members of sole holders:Labour force"
cap label var LFRF "Family members of sole holders"
cap label var LFRNF_M "Male:Regular non family labour force"
cap label var LFRNF_F "Female:Regular non family labour force"
cap label var LFRNF "Regular non family labour force"
cap label var LFNR "Labour force - non regular non family"
cap label var LFGH_PERS "pers:Group-holdings:Holders"
cap label var LFGH "Group-holdings:Holders"
cap label var LFR_PERS "pers:Labour force - regular"
cap label var LFR "Labour force - regular"
cap label var LFR_M_PERS "pers:Male:Regular labour force"
cap label var LFR_M "Male:Regular labour force"
cap label var LFR_F_PERS "pers:Female:Regular labour force"
cap label var LFR_F "Female:Regular labour force"
cap label var LFD "Labour force - directly employed by the holding"
cap label var LFND "Labour force - not directly employed by the holding"
cap label var M01 "Holdings with another gainful activity"
cap label var M01A "Holdings with tourism as other gainful activity"
cap label var M01B "Holdings with handicraft as other gainful activity"
cap label var M01C "Holdings with processing of farm products as other gainful activity"
cap label var M01D "Holdings with wood processing as other gainful activity"
cap label var M01E "Holdings with aquaculture as other gainful activity"
cap label var M01F "Holdings with renewable energy production as other gainful activity"
cap label var M01G "Holdings with contractual work as other gainful activity"
cap label var M01H "Holdings with other gainful activities n.a.e. as other gainful activity"
