cap label var TOTAL "Total"
cap label var DZ_AZW "Algeria - Arzew"
cap label var DZ_HME "Algeria - Hassi Messaoud"
cap label var DZ_ZRZ "Algeria - Zarzaitine"
cap label var DZ_ALG "Algeria - Algerian"
cap label var DZ_SKI "Algeria - Skikda"
cap label var DZ_SAH_BLN "Algeria - Saharan Blend"
cap label var DZ_RME "Algeria - Hassi Ramal"
cap label var DZ_ALG_CNDS "Algeria - Algerian Condensate"
cap label var DZ_ALG_MIX "Algeria - Algerian Mix"
cap label var DZ_ALG_CNDS_AZW "Algeria - Algerian Condensate (Arzew)"
cap label var DZ_ALG_CNDS_BJA "Algeria - Algerian Condensate (Bejaia)"
cap label var DZ_TOP "Algeria - Top Algerian"
cap label var DZ_MSC "Algeria - Miscellaneous"
cap label var AO_CAB "Angola - Cabinda"
cap label var AO_TAK "Angola - Takula"
cap label var AO_SZA_BLN "Angola - Soyo Blend"
cap label var AO_MDJ "Angola - Mandji"
cap label var AO_MAL_W "Angola - Malongo (West)"
cap label var AO_CVL1 "Angola - Cavala-1"
cap label var AO_SLL_SO1 "Angola - Sulele (South-1)"
cap label var AO_PA "Angola - Palanca"
cap label var AO_MAL_NO "Angola - Malongo (North)"
cap label var AO_MAL_SO "Angola - Malongo (South)"
cap label var AO_NMB "Angola - Nemba"
cap label var AO_GIR "Angola - Girassol"
cap label var AO_SVP "Angola - Kuito"
cap label var AO_HGO "Angola - Hungo"
cap label var AO_KSJ "Angola - Kissinje"
cap label var AO_DAL "Angola - Dalia"
cap label var AO_GIM "Angola - Gimboa"
cap label var AO_MDO "Angola - Mondo"
cap label var AO_PLO "Angola - Plutonio"
cap label var AO_SBT_BLN "Angola - Saxi Batuque Blend"
cap label var AO_XKB "Angola - Xikomba"
cap label var AO_MSC "Angola - Miscellaneous"
cap label var BJ_SEM "Benin - Seme"
cap label var BJ_MSC "Benin - Miscellaneous"
cap label var CM_KOL_MAR_BLN "Cameroon - Kole Marine Blend"
cap label var CM_LKL "Cameroon - Lokele"
cap label var CM_MOU_LGHT "Cameroon - Moudi Light"
cap label var CM_MOU_HVY "Cameroon - Moudi Heavy"
cap label var CM_EBT "Cameroon - Ebome"
cap label var CM_MSC "Cameroon - Miscellaneous"
cap label var TD_DOB_BLN_EPRD "Chad - Doba Blend (Early Production)"
cap label var TD_DOB_BLN_LPRD "Chad - Doba Blend (Later Production)"
cap label var TD_MSC "Chad - Miscellaneous"
cap label var CG_EMR "Congo (Brazzaville) - Emeraude"
cap label var CG_DJE_BLN "Congo (Brazzaville) - Djeno Blend"
cap label var CG_VDO_MA1 "Congo (Brazzaville) - Viodo Marina-1"
cap label var CG_NKO "Congo (Brazzaville) - Nkossa"
cap label var CG_MND "Congo (Brazzaville) - Muanda"
cap label var CG_ZRE "Congo (Brazzaville) - Congo/Zaire"
cap label var CG_CCO "Congo (Brazzaville) - Coco"
cap label var CG_BZV_MSC "Congo (Brazzaville) - Miscellaneous"
cap label var CI_ESP "Côte d'Ivoire - Espoir"
cap label var CI_LNC "Côte d'Ivoire - Lion Cote"
cap label var CI_MSC "Côte d'Ivoire - Miscellaneous"
cap label var EG_BLM "Egypt - Belayim"
cap label var EG_MGN "Egypt - El Morgan"
cap label var EG_RAG "Egypt - Rhas Gharib"
cap label var EG_GS_MIX "Egypt - Gulf of Suez Mix"
cap label var EG_GEI "Egypt - Geysum"
cap label var EG_EGRB_J1 "Egypt - East Gharib (J-1)"
cap label var EG_MGO1 "Egypt - Mango-1"
cap label var EG_RAB "Egypt - Rhas Budran"
cap label var EG_ZTB "Egypt - Zeit Bay"
cap label var EG_EZT_MIX "Egypt - East Zeit Mix"
cap label var EG_MSC "Egypt - Miscellaneous"
cap label var GQ_ZAF "Equatorial Guinea - Zafiro"
cap label var GQ_ABA_CNDS "Equatorial Guinea - Alba Condensate"
cap label var GQ_CBA "Equatorial Guinea - Ceiba"
cap label var GQ_MSC "Equatorial Guinea - Miscellaneous"
cap label var GA_GAX "Gabon - Gamba"
cap label var GA_MDJ "Gabon - Mandji"
cap label var GA_LUC_MAR "Gabon - Lucina Marine"
cap label var GA_OGU "Gabon - Oguendjo"
cap label var GA_RBI_KGA "Gabon - Rabi-Kouanga"
cap label var GA_TCT "Gabon - T'Catamba"
cap label var GA_RBI "Gabon - Rabi"
cap label var GA_RBI_BLN "Gabon - Rabi Blend"
cap label var GA_RBI_LGHT "Gabon - Rabi Light"
cap label var GA_ETA_MAR "Gabon - Etame Marin"
cap label var GA_OLD "Gabon - Olende"
cap label var GA_MSC "Gabon - Miscellaneous"
cap label var GH_BNU "Ghana - Bonsu"
cap label var GH_SPD "Ghana - Salt Pond"
cap label var GH_MSC "Ghana - Miscellaneous"
cap label var LY_BAT "Libya - Bu Attifel"
cap label var LY_AMN_HP "Libya - Amna (high pour)"
cap label var LY_BRG "Libya - Brega"
cap label var LY_STC "Libya - Sirtica"
cap label var LY_ZUE "Libya - Zueitina"
cap label var LY_BHT "Libya - Bunker Hunt"
cap label var LY_HFR "Libya - El Hofra"
cap label var LY_DHR "Libya - Dahra"
cap label var LY_SRR "Libya - Sarir"
cap label var LY_ZUE_CNDS "Libya - Zueitina Condensate"
cap label var LY_SHR "Libya - El Sharara"
cap label var LY_MSC "Libya - Miscellaneous"
cap label var MR_CGT "Mauritania - Chinguetti"
cap label var MR_MSC "Mauritania - Miscellaneous"
cap label var NG_FOR_BLN "Nigeria - Forcados Blend"
cap label var NG_ESC "Nigeria - Escravos"
cap label var NG_BSR "Nigeria - Brass River"
cap label var NG_QIB "Nigeria - Qua Iboe"
cap label var NG_BON_MED "Nigeria - Bonny Medium"
cap label var NG_PEN "Nigeria - Pennington"
cap label var NG_BMU "Nigeria - Bomu"
cap label var NG_BON_LGHT "Nigeria - Bonny Light"
cap label var NG_BRA_BLN "Nigeria - Brass Blend"
cap label var NG_GLL "Nigeria - Gilli Gilli"
cap label var NG_ADG "Nigeria - Adanga"
cap label var NG_IYK "Nigeria - Iyak-3"
cap label var NG_ANA "Nigeria - Antan"
cap label var NG_OSO "Nigeria - Oso"
cap label var NG_UKP "Nigeria - Ukpokiti"
cap label var NG_YHO "Nigeria - Yoho"
cap label var NG_OKW "Nigeria - Okwori"
cap label var NG_BOT "Nigeria - Bonga"
cap label var NG_ERHA "Nigeria - Erha"
cap label var NG_ANM_BLN "Nigeria - Amenam Blend"
cap label var NG_AKP "Nigeria - Akpo"
cap label var NG_EA "Nigeria - EA"
cap label var NG_ABM "Nigeria - Agbami"
cap label var NG_MSC "Nigeria - Miscellaneous"
cap label var TN_ZRZ "Tunisia - Zarzaitine"
cap label var TN_ASH "Tunisia - Ashtart"
cap label var TN_EBM "Tunisia - El Borma"
cap label var TN_EZZ2 "Tunisia - Ezzaouia-2"
cap label var TN_MSC "Tunisia - Miscellaneous"
cap label var AFR_OTH "Africa - Other"
cap label var BN_SER_LGHT "Brunei - Seria Light"
cap label var BN_CHP "Brunei - Champion"
cap label var BN_CHP_CNDS "Brunei - Champion Condensate"
cap label var BN_LGHT_SW_BLN "Brunei - Light Sweet Blend"
cap label var BN_CNDS "Brunei - Condensate"
cap label var BN_CHP_EXP "Brunei - Champion Export"
cap label var BN_MSC "Brunei - Miscellaneous"
cap label var CN_TCS_DQG "China - Taching (Daqing)"
cap label var CN_SHG "China - Shengli"
cap label var CN_BBU "China - Beibu"
cap label var CN_CHB "China - Chengbei"
cap label var CN_LFN "China - Lufeng"
cap label var CN_XIJ "China - Xijiang"
cap label var CN_WZU "China - Wei Zhou"
cap label var CN_LHA "China - Liu Hua"
cap label var CN_BZG "China - Boz Hong"
cap label var CN_PLI "China - Peng Lai"
cap label var CN_XXN "China - Xi Xiang"
cap label var CN_MSC "China - Miscellaneous"
cap label var IN_BOM_H "India - Bombay High"
cap label var IN_MSC "India - Miscellaneous"
cap label var ID_MNS_TRA_LGHT "Indonesia - Minas (Sumatron Light)"
cap label var ID_ANT "Indonesia - Ardjuna"
cap label var ID_ATK "Indonesia - Attaka"
cap label var ID_SUR "Indonesia - Suri"
cap label var ID_SNG "Indonesia - Sanga Sanga"
cap label var ID_SPG "Indonesia - Sepinggan"
cap label var ID_WLO "Indonesia - Walio"
cap label var ID_ARB "Indonesia - Arimbi"
cap label var ID_POL "Indonesia - Poleng"
cap label var ID_HDL "Indonesia - Handil"
cap label var ID_JBG "Indonesia - Jatibarang"
cap label var ID_CIN "Indonesia - Cinta"
cap label var ID_BEK "Indonesia - Bekapai"
cap label var ID_KTP "Indonesia - Katapa"
cap label var ID_SWT "Indonesia - Salawati"
cap label var ID_DUR_TRA_HVY "Indonesia - Duri (Sumatran Heavy)"
cap label var ID_SBK "Indonesia - Sembakung"
cap label var ID_BDK "Indonesia - Badak"
cap label var ID_AUN_CNDS "Indonesia - Arun Condensate"
cap label var ID_UDG "Indonesia - Udang"
cap label var ID_KMN "Indonesia - Klamono"
cap label var ID_BNA "Indonesia - Bunya"
cap label var ID_PMS "Indonesia - Pamusian"
cap label var ID_KDN "Indonesia - Kerindigan"
cap label var ID_MLN "Indonesia - Melahin"
cap label var ID_BYQ "Indonesia - Bunyu"
cap label var ID_CMT "Indonesia - Camar"
cap label var ID_CIN_HVY "Indonesia - Cinta Heavy"
cap label var ID_LAT "Indonesia - Lalang"
cap label var ID_KKP "Indonesia - Kakap"
cap label var ID_SSI1 "Indonesia - Sisi-1"
cap label var ID_GTI1 "Indonesia - Giti-1"
cap label var ID_AYU1 "Indonesia - Ayu-1"
cap label var ID_BMU "Indonesia - Bima"
cap label var ID_PDG_I "Indonesia - Padang Isle"
cap label var ID_ITN "Indonesia - Intan"
cap label var ID_SPG_YKN_MIX "Indonesia - Sepinggan -Yakin Mixed"
cap label var ID_WID "Indonesia - Widuri"
cap label var ID_BET "Indonesia - Belida"
cap label var ID_SZH "Indonesia - Senipah"
cap label var ID_MSC "Indonesia - Miscellaneous"
cap label var MY_MYY_LGHT "Malaysia - Miri Light"
cap label var MY_TGO "Malaysia - Tembungo"
cap label var MY_LBU_BLN "Malaysia - Labuan Blend"
cap label var MY_TAT "Malaysia - Tapis"
cap label var MY_BTU "Malaysia - Bintulu"
cap label var MY_BKK "Malaysia - Bekok"
cap label var MY_PLI "Malaysia - Pulai"
cap label var MY_DTL "Malaysia - Dulang"
cap label var MY_MSC "Malaysia - Miscellaneous"
cap label var PH_NID "Philippines - Nido"
cap label var PH_MSC "Philippines - Miscellaneous"
cap label var SG_RNT "Singapore - Rantau"
cap label var SG_MSC "Singapore - Miscellaneous"
cap label var TH_ERA_CNDS "Thailand - Erawan Condensate"
cap label var TH_SKT "Thailand - Sirikit"
cap label var TH_NGN "Thailand - Nang Nuan"
cap label var TH_BLG "Thailand - Bualuang"
cap label var TH_BEN "Thailand - Benchamas"
cap label var TH_MSC "Thailand - Miscellaneous"
cap label var UZ_MSC "Uzbekistan - Miscellaneous"
cap label var VN_BHO "Vietnam - Bach Ho (White Tiger)"
cap label var VN_DHG "Vietnam - Dai Hung (Big Bear)"
cap label var VN_RDG "Vietnam - Rang Dong"
cap label var VN_RUB "Vietnam - Ruby"
cap label var VN_STD "Vietnam - Su Tu Den (Black Lion)"
cap label var VN_MSC "Vietnam - Miscellaneous"
cap label var ASI_OTH "Asia - Other"
cap label var AU_JAB "Australia - Jabiru"
cap label var AU_KRP_J "Australia - Kooroopa (Jurassic)"
cap label var AU_TGY_J "Australia - Talgeberry (Jurassic)"
cap label var AU_TGY_UPK "Australia - Talgeberry (Up Cretaceous)"
cap label var AU_WIE_CNDS "Australia - Woodside Condensate"
cap label var AU_SMT3_BW_TOP "Australia - Saladin-3 (Top Barrow)"
cap label var AU_HRT "Australia - Harriet"
cap label var AU_SKA3_CHF "Australia - Skua-3 (Challis Field)"
cap label var AU_BWB "Australia - Barrow Island"
cap label var AU_NWSH_CNDS "Australia - Northwest Shelf Condensate"
cap label var AU_JAC_BLN "Australia - Jackson Blend"
cap label var AU_CPB "Australia - Cooper Basin"
cap label var AU_GRF "Australia - Griffin"
cap label var AU_BUF_C "Australia - Buffalo Crude"
cap label var AU_COP "Australia - Cossack"
cap label var AU_ELG "Australia - Elang"
cap label var AU_EFD "Australia - Enfield"
cap label var AU_GIP_BSS "Australia - Gippsland (Bass Strait)"
cap label var AU_MSC "Australia - Miscellaneous"
cap label var PG_KTB "Papua New Guinea - Kutubu"
cap label var PG_MSC "Papua New Guinea - Miscellaneous"
cap label var AU_OCE_OTH "Australia and Oceania - Other"
cap label var AL_MSC "Albania - Miscellaneous"
cap label var AM_MSC "Armenia - Miscellaneous"
cap label var AT_MSC "Austria - Miscellaneous"
cap label var AZ_AZR_LGHT "Azerbaijan - Azeri Light"
cap label var AZ_MSC "Azerbaijan - Miscellaneous"
cap label var BY_MSC "Belarus - Miscellaneous"
cap label var BG_MSC "Bulgaria - Miscellaneous"
cap label var HR_MSC "Croatia - Miscellaneous"
cap label var CZ_MSC "Czechia - Miscellaneous"
cap label var DE_MSC "Germany – Miscellaneous"
cap label var DK_DAN "Denmark - Dan"
cap label var DK_GRM "Denmark - Gorm"
cap label var DK_DNS "Denmark - Danish North Sea"
cap label var DK_MSC "Denmark - Miscellaneous"
cap label var FR_COT "France - Continental"
cap label var FR_OVS "France - Overseas"
cap label var FR_MSC "France - Miscellaneous"
cap label var GE_MSC "Georgia - Miscellaneous"
cap label var GR_MSC "Greece - Miscellaneous"
cap label var HU_MSC "Hungary - Miscellaneous"
cap label var IT_MSC "Italy - Miscellaneous"
cap label var KZ_KKL "Kazakhstan - Kumkol"
cap label var KZ_CPC_BLN "Kazakhstan - Caspian Pipeline Consortium (CPC) Blend"
cap label var KZ_MSC "Kazakhstan - Miscellaneous"
cap label var LT_MSC "Lithuania - Miscellaneous"
cap label var MD_MSC "Moldova - Miscellaneous"
cap label var NL_ABA "Netherlands - Alba"
cap label var NL_MSC "Netherlands - Miscellaneous"
cap label var NO_EFK "Norway - Ekofisk"
cap label var NO_TOR "Norway - Tor"
cap label var NO_STD "Norway - Statfjord"
cap label var NO_HEI "Norway - Heidrun"
cap label var NO_FTI "Norway - Norwegian Forties"
cap label var NO_GLS "Norway - Gullfaks"
cap label var NO_OBG "Norway - Oseberg"
cap label var NO_NNE "Norway - Norne"
cap label var NO_TLL "Norway - Troll"
cap label var NO_DRA "Norway - Draugen"
cap label var NO_SPR_CNDS "Norway - Sleipner Condensate"
cap label var NO_MSC "Norway - Miscellaneous"
cap label var PL_MSC "Poland - Miscellaneous"
cap label var RO_MSC "Romania - Miscellaneous"
cap label var RU_URL "Russia - Urals"
cap label var RU_EXP_BLN "Russia - Russian Export Blend"
cap label var RU_M100 "Russia - M100"
cap label var RU_M100_HVY "Russia - M100 Heavy"
cap label var RU_SIB_LGHT "Russia - Siberian Light"
cap label var RU_E4_G "Russia - E4 (Gravenshon)"
cap label var RU_E4_HVY "Russia - E4 Heavy"
cap label var RU_PVY_CNDS "Russia - Purovsky Condensate"
cap label var RU_SOL "Russia - Sokol"
cap label var RU_MSC "Russia - Miscellaneous"
cap label var RS_MSC "Serbia - Miscellaneous"
cap label var SK_MSC "Slovakia - Miscellaneous"
cap label var ES_AZPMA_NO "Spain - Amposta Marina North"
cap label var ES_CSA "Spain - Casablanca"
cap label var ES_DRD "Spain - El Dorado"
cap label var ES_MSC "Spain - Miscellaneous"
cap label var TR_MSC "Turkey - Miscellaneous"
cap label var UA_MSC "Ukraine - Miscellaneous"
cap label var UK_AUK "United Kingdom - Auk"
cap label var UK_BEA "United Kingdom - Beatrice"
cap label var UK_BRE "United Kingdom - Brae"
cap label var UK_UCN "United Kingdom - Buchan"
cap label var UK_CLM "United Kingdom - Claymore"
cap label var UK_SV_ENT "United Kingdom - S.V. (Brent)"
cap label var UK_TTN "United Kingdom - Tartan"
cap label var UK_TRN "United Kingdom - Tern"
cap label var UK_MGS "United Kingdom - Magnus"
cap label var UK_DNN "United Kingdom - Dunlin"
cap label var UK_FMR "United Kingdom - Fulmar"
cap label var UK_HUX "United Kingdom - Hutton"
cap label var UK_NW_HTQ "United Kingdom - North West (N.W.) Hutton"
cap label var UK_MRN "United Kingdom - Maureen"
cap label var UK_MCS "United Kingdom - Murchison"
cap label var UK_NNN_BLN "United Kingdom - Ninian Blend"
cap label var UK_MON "United Kingdom - Montrose"
cap label var UK_BRL "United Kingdom - Beryl"
cap label var UK_PPR "United Kingdom - Piper"
cap label var UK_FTI "United Kingdom - Forties"
cap label var UK_ENT_BLN "United Kingdom - Brent Blend"
cap label var UK_FLH "United Kingdom - Flotta"
cap label var UK_THF "United Kingdom - Thistle"
cap label var UK_SV_NNN "United Kingdom - S.V. (Ninian)"
cap label var UK_GYL "United Kingdom - Argyle"
cap label var UK_HTR "United Kingdom - Heather"
cap label var UK_SBC "United Kingdom - South Birch"
cap label var UK_WYF "United Kingdom - Wytch Farm"
cap label var UK_CTNO "United Kingdom - Cormorant North"
cap label var UK_CTSO_CTA "United Kingdom - Cormorant South (Cormorant ‘A’)"
cap label var UK_ABA "United Kingdom - Alba"
cap label var UK_FNV "United Kingdom - Foinhaven"
cap label var UK_SHL "United Kingdom - Schiehallion"
cap label var UK_CPT "United Kingdom - Captain"
cap label var UK_HDG "United Kingdom - Harding"
cap label var UK_MSC "United Kingdom - Miscellaneous"
cap label var EUR_OTH "Europe - Other"
cap label var AG_TDF "Argentina - Tierra del Fuego"
cap label var AG_RZA "Argentina - Santa Cruz"
cap label var AG_ECL "Argentina - Escalante"
cap label var AG_CDS "Argentina - Canadon Seco"
cap label var AG_HDR "Argentina - Hidra"
cap label var AG_MED "Argentina - Medanito"
cap label var AR_MSC "Argentina - Miscellaneous"
cap label var BZ_LGHT_C "Belize - Light Crude"
cap label var BZ_MSC "Belize - Miscellaneous"
cap label var BO_CNDS "Bolivia - Bolivian Condensate"
cap label var BO_AZ_MSC "Bolivia - Azerbaijan Miscellaneous"
cap label var BR_GRP "Brazil - Garoupa"
cap label var BR_SGI "Brazil - Sergipano"
cap label var BR_CMB "Brazil - Campos Basin"
cap label var BR_URU_AMZ_UP "Brazil - Urucu (Upper Amazon)"
cap label var BR_MLM "Brazil - Marlim"
cap label var BR_PLV "Brazil - Brazil Polvo"
cap label var BR_RCR "Brazil - Roncador"
cap label var BR_RCR_HVY "Brazil - Roncador Heavy"
cap label var BR_ACE "Brazil - Albacora East"
cap label var BR_MSC "Brazil - Miscellaneous"
cap label var CL_MSC "Chile - Miscellaneous"
cap label var CO_ONT "Colombia - Onto"
cap label var CO_PTO "Colombia - Putamayo"
cap label var CO_RZL "Colombia - Rio Zulia"
cap label var CO_ORT "Colombia - Orito"
cap label var CO_CLM "Colombia - Cano-Limon"
cap label var CO_LSM "Colombia - Lasmo"
cap label var CO_CDY1 "Colombia - Cano Duya-1"
cap label var CO_CRR1 "Colombia - Corocora-1"
cap label var CO_SSU1 "Colombia - Suria Sur-1"
cap label var CO_TNN1 "Colombia - Tunane-1"
cap label var CO_CSR "Colombia - Casanare"
cap label var CO_CSN "Colombia - Cusiana"
cap label var CO_VCN "Colombia - Vasconia"
cap label var CO_CST_BLN "Colombia - Castilla Blend"
cap label var CO_CPA "Colombia - Cupiaga"
cap label var CO_SO_BLN "Colombia - South Blend"
cap label var CO_MSC "Colombia - Miscellaneous"
cap label var EC_ORT "Ecuador - Oriente"
cap label var EC_UIO "Ecuador - Quito"
cap label var EC_SEL "Ecuador - Santa Elena"
cap label var EC_LNA1 "Ecuador - Limoncoha-1"
cap label var EC_FRT1 "Ecuador - Frontera-1"
cap label var EC_BGI1 "Ecuador - Bogi-1"
cap label var EC_NPO "Ecuador - Napo"
cap label var EC_NPO_LGHT "Ecuador - Napo Light"
cap label var EC_MSC "Ecuador - Miscellaneous"
cap label var GT_CBV "Guatemala - Coban"
cap label var GT_RUV "Guatemala - Rubelsanto"
cap label var GT_MSC "Guatemala - Miscellaneous"
cap label var MX_IST "Mexico - Isthmus"
cap label var MX_MYA "Mexico - Maya"
cap label var MX_OLC "Mexico - Olmeca"
cap label var MX_ATM "Mexico - Altamira"
cap label var MX_IST_TPD "Mexico - Topped Isthmus"
cap label var MX_MSC "Mexico - Miscellaneous"
cap label var PE_LRT "Peru - Loreto"
cap label var PE_TYL "Peru - Talara"
cap label var PE_HCT "Peru - High Cold Test"
cap label var PE_PUB "Peru - Bayovar"
cap label var PE_LCT "Peru - Low Cold Test"
cap label var PE_CMC5 "Peru - Carmen Central-5"
cap label var PE_SVU23 "Peru - Shiviyacu-23"
cap label var PE_MYN "Peru - Mayna"
cap label var PE_MSC "Peru - Miscellaneous"
cap label var TT_GAL_MIX "Trinidad and Tobago - Galeota Mix"
cap label var TT_TRC "Trinidad and Tobago - Trintopec"
cap label var TT_LAND_TRM "Trinidad and Tobago - Land/Trinmar"
cap label var TT_CPO_MSC "Trinidad and Tobago - Calypso Miscellaneous"
cap label var TT_MSC "Trinidad and Tobago - Miscellaneous"
cap label var VE_JBO_MON "Venezuela - Jobo (Monagas)"
cap label var VE_LML "Venezuela - Lama Lamar"
cap label var VE_MRG "Venezuela - Mariago"
cap label var VE_RUZ "Venezuela - Ruiz"
cap label var VE_TPO "Venezuela - Tucipido"
cap label var VE_VE17 "Venezuela - Venez Lot 17"
cap label var VE_MRA16_18 "Venezuela - Mara 16/18"
cap label var VE_TJV_LGHT "Venezuela - Tia Juana Light"
cap label var VE_TJV_MED26 "Venezuela - Tia Juana Medium 26"
cap label var VE_OFF "Venezuela - Officina"
cap label var VE_BAV "Venezuela - Bachaquero"
cap label var VE_CLG "Venezuela - Cento Lago"
cap label var VE_LGY "Venezuela - Lagunillas"
cap label var LRS_MED "Venezuela - La Rosa Medium"
cap label var VE_SJQ "Venezuela - San Joaquin"
cap label var VE_LGT "Venezuela - Lagotreco"
cap label var VE_LGC "Venezuela - Lagocinco"
cap label var VE_BCN "Venezuela - Boscan"
cap label var VE_LON "Venezuela - Leona"
cap label var VE_BNS "Venezuela - Barinas"
cap label var VE_SLY "Venezuela - Sylvestre"
cap label var VE_MSA "Venezuela - Mesa"
cap label var VE_CEU "Venezuela - Ceuta"
cap label var VE_LG_MED "Venezuela - Lago Medio"
cap label var VE_TGR "Venezuela - Tigre"
cap label var VE_AAO_WAX "Venezuela - Anaco Wax"
cap label var VE_SRS "Venezuela - Santa Rosa"
cap label var VE_BOM "Venezuela - Bombai"
cap label var VE_AGY "Venezuela - Aguasay"
cap label var VE_AAO "Venezuela - Anaco"
cap label var VE_BCF_BH_L17 "Venezuela - BCF-Bach/Lag17"
cap label var VE_BCF_BH_L21 "Venezuela - BCF-Bach/Lag21"
cap label var VE_BCF21P9 "Venezuela - BCF-21,9"
cap label var VE_BCF24 "Venezuela - BCF-24"
cap label var VE_BCF31 "Venezuela - BCF-31"
cap label var VE_BCF_BLN "Venezuela - BCF Blend"
cap label var VE_BOC "Venezuela - Bolival Coast"
cap label var VE_CEU_BH18 "Venezuela - Ceuta/Bach 18"
cap label var VE_COR_BCK "Venezuela - Corridor Block"
cap label var VE_K "Venezuela - Cretaceous"
cap label var VE_GNP "Venezuela - Guanipa"
cap label var VE_LG_MIX_MED "Venezuela - Lago Mix Medium"
cap label var VE_LRS_LGN "Venezuela - Larosa/Lagun"
cap label var VE_MMT "Venezuela - Menemoto"
cap label var VE_CBS "Venezuela - Cabimas"
cap label var VE_BCF23 "Venezuela - BCF-23"
cap label var VE_OFC_MSA "Venezuela - Oficina/Mesa"
cap label var VE_PLN "Venezuela - Pilon"
cap label var VE_RCN "Venezuela - Recon (Venez)"
cap label var VE_102TJ_25 "Venezuela - 102 Tj (25)"
cap label var VE_TJL_K "Venezuela - Tjl Cretaceous"
cap label var VE_TJVP_HVY "Venezuela - Tia Juana Pesado (Heavy)"
cap label var VE_MSA_RCN "Venezuela - Mesa-Recon"
cap label var VE_OTP "Venezuela - Oritupano"
cap label var VE_HPD "Venezuela - Hombre Pintado"
cap label var VE_MRY "Venezuela - Merey"
cap label var VE_LG_LGHT "Venezuela - Lago Light"
cap label var VE_LGN "Venezuela - Laguna"
cap label var VE_BH_CUE_MIX "Venezuela - Bach/Cueta Mix"
cap label var VE_BAV13 "Venezuela - Bachaquero 13"
cap label var VE_CEU28 "Venezuela - Ceuta - 28"
cap label var VE_TBD "Venezuela - Temblador"
cap label var VE_LGM "Venezuela - Lagomar"
cap label var VE_TPR "Venezuela - Taparito"
cap label var VE_BCF_HVY "Venezuela - BCF - Heavy"
cap label var VE_BCF_MED "Venezuela - BCF - Medium"
cap label var VE_CAR_BLN "Venezuela - Caripito Blend"
cap label var VE_LGN_CEU_MIX "Venezuela - Laguna/Ceuta Mix"
cap label var VE_MHF "Venezuela - Morichal"
cap label var VE_PDZ "Venezuela - Pedenales"
cap label var VE_QRQ "Venezuela - Quiriquire"
cap label var VE_TUV "Venezuela - Tucupita"
cap label var VE_FRR2_E "Venezuela - Furrial-2 (E. Venezuela)"
cap label var VE_CUR_BLN "Venezuela - Curazao Blend"
cap label var VE_SBB "Venezuela - Santa Barbara"
cap label var VE_CRN "Venezuela - Cerro Negro"
cap label var VE_BCF22 "Venezuela - BCF22"
cap label var VE_HAM "Venezuela - Hamaca"
cap label var VE_ZUA10 "Venezuela - Zuata 10"
cap label var VE_ZUA20 "Venezuela - Zuata 20"
cap label var VE_ZUA30 "Venezuela - Zuata 30"
cap label var VE_MNG "Venezuela - Monogas"
cap label var VE_CRC "Venezuela - Corocoro"
cap label var VE_PTZ "Venezuela - Petrozuata"
cap label var VE_MHF16 "Venezuela - Morichal 16"
cap label var VE_GFI "Venezuela - Guafita"
cap label var VE_MSC "Venezuela - Miscellaneous"
cap label var LA_OTH "Latin America - Other"
cap label var AUH_BDQ "Abu Dhabi - Al Bunduq"
cap label var AUH_MBS "Abu Dhabi - Mubarraz"
cap label var AUH_MRB "Abu Dhabi - Murban"
cap label var AUH_ZKM_LW_MAR "Abu Dhabi - Zakum (Lower Zakum/Abu Dhabi Marine)"
cap label var AUH_USH_MAR "Abu Dhabi - Umm Shaif (Abu Dhabi Marine)"
cap label var AUH_ARZ "Abu Dhabi - Arzanah"
cap label var AUH_ABU "Abu Dhabi - Abu Al Bu Khoosh"
cap label var AUH_MRB_BTM "Abu Dhabi - Murban Bottoms"
cap label var AUH_MRB_TOP "Abu Dhabi - Top Murban"
cap label var AUH_ZKM_UP "Abu Dhabi - Upper Zakum"
cap label var AUH_MSC "Abu Dhabi - Miscellaneous"
cap label var BH_MSC "Bahrain - Miscellaneous"
cap label var DXB_FAT "Dubai - Dubai (Fateh)"
cap label var DXB_MRG_LGHT "Dubai - Margham Light"
cap label var DXB_MSC "Dubai - Miscellaneous"
cap label var IR_LGHT "Iran - Iranian Light"
cap label var IR_HVY "Iran - Iranian Heavy"
cap label var IR_SOR "Iran - Soroosh (Cyrus)"
cap label var IR_DRR "Iran - Dorrood (Darius)"
cap label var IR_RTM "Iran - Rostam"
cap label var IR_SAL "Iran - Salmon (Sassan)"
cap label var IR_FRZ "Iran - Foroozan (Fereidoon)"
cap label var IR_ABZ "Iran - Aboozar (Ardeshir)"
cap label var IR_SXI "Iran - Sirri"
cap label var IR_BRG_SIRIP_BLN "Iran - Bahrgansar/Nowruz (SIRIP Blend)"
cap label var IR_BR "Iran - Bahr/Nowruz"
cap label var IR_MSC "Iran - Miscellaneous"
cap label var IQ_MAB_LGHT_PG "Iraq - Basrah Light (Persian Gulf)"
cap label var IQ_KIK_PG "Iraq - Kirkuk (Persian Gulf)"
cap label var IQ_MSH_PG "Iraq - Mishrif (Persian Gulf)"
cap label var IQ_BHS_PG "Iraq - Bai Hasson (Persian Gulf)"
cap label var IQ_MAB_MED_PG "Iraq - Basrah Medium (Persian Gulf)"
cap label var IQ_MAB_HVY_PG "Iraq - Basrah Heavy (Persian Gulf)"
cap label var IQ_KIK_BLN_PG "Iraq - Kirkuk Blend (Persian Gulf)"
cap label var IQ_NO_RML_PG "Iraq - North Rumalia (Persian Gulf)"
cap label var IQ_RLB "Iraq - Ras el Behar"
cap label var IQ_MAB_LGHT_RED "Iraq - Basrah Light (Red Sea)"
cap label var IQ_KIK_RED "Iraq - Kirkuk (Red Sea)"
cap label var IQ_MSH_RED "Iraq - Mishrif (Red Sea)"
cap label var IQ_BHS_RED "Iraq - Bai Hasson (Red Sea)"
cap label var IQ_MAB_MED_RED "Iraq - Basrah Medium (Red Sea)"
cap label var IQ_MAB_HVY_RED "Iraq - Basrah Heavy (Red Sea)"
cap label var IQ_KIK_BLN_RED "Iraq - Kirkuk Blend (Red Sea)"
cap label var IQ_NO_RML_RED "Iraq - North Rumalia (Red Sea)"
cap label var IQ_RTM "Iraq - Ratawi"
cap label var IQ_MAB_LGHT_TR "Iraq - Basrah Light (Turkey)"
cap label var IQ_KIK_TR "Iraq - Kirkuk (Turkey)"
cap label var IQ_MSH_TR "Iraq - Mishrif (Turkey)"
cap label var IQ_BHS_TR "Iraq - Bai Hasson (Turkey)"
cap label var IQ_MAB_MED_TR "Iraq - Basrah Medium (Turkey)"
cap label var IQ_MAB_HVY_TR "Iraq - Basrah Heavy (Turkey)"
cap label var IQ_KIK_BLN_TR "Iraq - Kirkuk Blend (Turkey)"
cap label var IQ_NO_RML_TR "Iraq - North Rumalia (Turkey)"
cap label var IQ_FAO_BLN "Iraq - Fao Blend"
cap label var IQ_MSC "Iraq - Miscellaneous"
cap label var KW_MEA_EXP "Kuwait - Mina al Ahmadi (Kuwait Export)"
cap label var KW_MG_LW_J "Kuwait - Magwa (Lower Jurassic)"
cap label var KW_BG_WF "Kuwait - Burgan (Wafra)"
cap label var KW_MSC "Kuwait - Miscellaneous"
cap label var NZ_ECN_WF "Neutral Zone - Eocene (Wafra)"
cap label var NZ_HOU "Neutral Zone - Hout"
cap label var NZ_RAR "Neutral Zone - Khafji"
cap label var NZ_BG_WF "Neutral Zone - Burgan (Wafra)"
cap label var NZ_RTM "Neutral Zone - Ratawi"
cap label var NZ_MIX "Neutral Zone - Mix"
cap label var NZ_RAR_BLN "Neutral Zone - Khafji Blend"
cap label var NZ_MSC "Neutral Zone - Miscellaneous"
cap label var OM_EXP "Oman - Export"
cap label var OM_MSC "Oman - Miscellaneous"
cap label var QA_DHN "Qatar - Dukhan"
cap label var QA_MAR "Qatar - Qatar Marine"
cap label var QA_LAND "Qatar - Qatar Land"
cap label var QA_MSC "Qatar - Miscellaneous"
cap label var AE_RAK_CNDS "Ras Al Khaimah - Rak Condensate"
cap label var AE_RKT_MSC "Ras Al Khaimah - Miscellaneous"
cap label var SA_LGHT_PG "Saudi Arabia - Light (Persian Gulf)"
cap label var SA_HVY_PG_SAF "Saudi Arabia - Heavy (Persian Gulf) (Safaniya)"
cap label var SA_MED_PG_KH "Saudi Arabia - Medium (Persian Gulf) (Khursaniyah)"
cap label var SA_XLGHT_PG_BRR "Saudi Arabia - Extra Light (Persian Gulf) (Berri)"
cap label var SA_LGHT_YN "Saudi Arabia - Light (Yanbu)"
cap label var SA_HVY_YN "Saudi Arabia - Heavy (Yanbu)"
cap label var SA_MED_YN "Saudi Arabia - Medium (Yanbu)"
cap label var SA_BRR_YN "Saudi Arabia - Berri (Yanbu)"
cap label var SA_MED_ZLF_MRJ "Saudi Arabia - Medium (Zuluf/Marjan)"
cap label var SA_MSC "Saudi Arabia - Miscellaneous"
cap label var SHJ_MUB "Sharjah - Mubarek Sharjah"
cap label var SHJ_CNDS "Sharjah - Condensate"
cap label var SHJ_MSC "Sharjah - Miscellaneous"
cap label var SY_STR "Syria - Syrian Straight"
cap label var SY_THY "Syria - Thayyem"
cap label var SY_OMR_BLN "Syria - Omar Blend"
cap label var SY_OMR "Syria - Omar"
cap label var SY_LGHT "Syria - Syrian Light"
cap label var SY_SOU "Syria - Souedie"
cap label var SY_MSC "Syria - Miscellaneous"
cap label var YE_YAR_BLN "Yemen - North Yemeni Blend"
cap label var YE_ALF "Yemen - Alif"
cap label var YE_MIB_LGHT "Yemen - Maarib Lt."
cap label var YE_MSL_BLN "Yemen - Masila Blend"
cap label var YE_SBW_BLN "Yemen - Shabwa Blend"
cap label var YE_MSC "Yemen - Miscellaneous"
cap label var ME_OTH "Middle East - Other"
cap label var CA_YPE_LGHT "Canada - Peace River Light"
cap label var CA_YPE_MED "Canada - Peace River Medium"
cap label var CA_YPE_HVY "Canada - Peace River Heavy"
cap label var CA_MBR "Canada - Manyberries"
cap label var CA_RB_LGHT_MED "Canada - Rainbow Light and Medium"
cap label var CA_PBN "Canada - Pembina"
cap label var CA_BHLK "Canada - Bells Hill Lake"
cap label var CA_FTN_CNDS "Canada - Fosterton Condensate"
cap label var CA_RGL_CNDS "Canada - Rangeland Condensate"
cap label var CA_RWA "Canada - Redwater"
cap label var CA_LMR "Canada - Lloydminster"
cap label var CA_WWI "Canada - Wainwright-Kinsella"
cap label var CA_BWR_HVY "Canada - Bow River Heavy"
cap label var CA_FTN "Canada - Fosterton"
cap label var CA_SCV "Canada - Smiley-Coleville"
cap label var CA_MDL "Canada - Midale"
cap label var CA_MKR_PIPE "Canada - Milk River Pipeline"
cap label var CA_IPL_MIX_SW "Canada - Ipl-Mix Sweet"
cap label var CA_IPL_MIX_SU "Canada - Ipl-Mix Sour"
cap label var CA_IPL_CNDS "Canada - Ipl Condensate"
cap label var CA_AUR_LGHT "Canada - Aurora Light"
cap label var CA_AUR_CNDS "Canada - Aurora Condensate"
cap label var CA_RGF "Canada - Reagan Field"
cap label var CA_SYN "Canada - Synthetic Canada"
cap label var CA_YOD "Canada - Cold Lake"
cap label var CA_YOD_BLN "Canada - Cold Lake Blend"
cap label var CA_FDR "Canada - Canadian Federated"
cap label var CA_CHV "Canada - Chauvin"
cap label var CA_GCS "Canada - Gcos"
cap label var CA_GAB_LGHT_MED "Canada - Gulf Alberta Light and Medium"
cap label var CA_LGHT_SU_BLN "Canada - Light Sour Blend"
cap label var CA_LLY_BLN "Canada - Lloyd Blend"
cap label var CA_YPE_CNDS "Canada - Peace River Condensate"
cap label var CA_SAR_CNDS "Canada - Sarnium Condensate"
cap label var CA_SK_LGHT "Canada - Saskatchewan Light"
cap label var CA_SW_MIX_BLN "Canada - Sweet Mixed Blend"
cap label var CA_SCR "Canada - Syncrude"
cap label var CA_RGL_SO_LGHT_MED "Canada - Rangeland - South Light and Medium"
cap label var CA_NOBLN_NVS "Canada - Northblend Nevis"
cap label var CA_CO_CNDS "Canada - Canadian Common Condensate"
cap label var CA_CO "Canada - Canadian Common"
cap label var CA_WTT_CNDS "Canada - Waterton Condensate"
cap label var CA_PNK_CNDS "Canada - Panuke Condensate"
cap label var CA_FDR_LGHT_MED "Canada - Federated Light and Medium"
cap label var CA_WAB "Canada - Wabasca"
cap label var CA_HIB "Canada - Hibernia"
cap label var CA_BC_LGHT "Canada - BC Light"
cap label var CA_BDY "Canada - Boundary"
cap label var CA_A_HVY "Canada - Albian Heavy"
cap label var CA_KAB "Canada - Koch Alberta"
cap label var CA_TER "Canada - Terra Nova"
cap label var CA_EC_BLN "Canada - Echo Blend"
cap label var CA_W_BLN "Canada - Western Canadian Blend"
cap label var CA_W_SEL "Canada - Western Canadian Select"
cap label var CA_WRS "Canada - White Rose"
cap label var CA_ACC "Canada - Access"
cap label var CA_PAS_HVY "Canada - Premium Albian Synthetic Heavy"
cap label var CA_ARB "Canada - Albian Residuum Blend (ARB)"
cap label var CA_CLK "Canada - Christina Lake"
cap label var CA_CNRL "Canada - CNRL"
cap label var CA_HSB "Canada - Husky Synthetic Blend"
cap label var CA_PAS "Canada - Premium Albian Synthetic (PAS)"
cap label var CA_SH "Canada - Seal Heavy (SH)"
cap label var CA_OSA "Canada - Suncor Synthetic A (OSA)"
cap label var CA_OSH "Canada - Suncor Synthetic H (OSH)"
cap label var CA_PE_SU "Canada - Peace Sour"
cap label var CA_WCR "Canada - Western Canadian Resid"
cap label var CA_CDB "Canada - Christina Dilbit Blend"
cap label var CA_CLD "Canada - Christina Lake Dilbit"
cap label var CA_MSC "Canada - Miscellaneous"
cap label var US_AK_ANS "United States Alaska - Alaskan North Slope (ANS)"
cap label var US_CO_N5B "United States Colorado - Niobrara"
cap label var US_NM_FRC "United States New Mexico - Four Corners"
cap label var US_ND_BKK "United States North Dakota - Bakken"
cap label var US_ND_SW "United States North Dakota - North Dakota Sweet"
cap label var US_TXA_WTI "United States Texas - West Texas Intermediate (WTI)"
cap label var US_TXA_EGF "United States Texas - Eagle Ford"
cap label var US_UT_CVN "United States Utah - Covenant"
cap label var US_FOCS_BET "United States Federal OCS - Beta"
cap label var US_FOCS_CRP "United States Federal OCS - Carpinteria"
cap label var US_FOCS_DCD "United States Federal OCS - Dos Cuadras"
cap label var US_FOCS_HDO "United States Federal OCS - Hondo"
cap label var US_FOCS_NTD "United States Federal OCS - Hueneme"
cap label var US_FOCS_PCD "United States Federal OCS - Pescado"
cap label var US_FOCS_PAG "United States Federal OCS - Point Arguello"
cap label var US_FOCS_PPD "United States Federal OCS - Point Pedernales"
cap label var US_FOCS_SCT "United States Federal OCS - Sacate"
cap label var US_FOCS_SCL "United States Federal OCS - Santa Clara"
cap label var US_FOCS_SKY "United States Federal OCS - Sockeye"
cap label var US_MSC "United States - Miscellaneous"
cap label var US_NA_OTH "North America - Other"
cap label var UNK "Unknown"
