cap label var SPPC "Product safety, consumer protection"
cap label var EMPSWAS "Employment, worker safety or social affairs"
cap label var OWS "Operational and worker safety"
cap label var ENV "Environment"
cap label var IP "Intellectual property"
cap label var TAX "Tax"
cap label var EMPAS "Employment or social affairs"
cap label var DPR "Data protection regulation"
cap label var OTH "Other"
