cap label var TOTAL "Total - all species"
cap label var CONIF "Coniferous"
cap label var C_FIR "Coniferous: Fir/Spruce (Abies alba, Picea abies)"
cap label var C_PIN "Coniferous: Pine (Pinus sylvestris)"
cap label var C_NSP "Coniferous: non specified"
cap label var NCONIF "Non-coniferous"
cap label var NC_OAK "Non-coniferous: Oak (Quercus spp.)"
cap label var NC_BEE "Non-coniferous: Beech (Fagus spp.)"
cap label var NC_BIR "Non-coniferous: Birch (Betula spp.)"
cap label var NC_MAP "Non-coniferous: Maple (Acer spp.)"
cap label var NC_CHE "Non-coniferous: Cherry (Prunus spp.)"
cap label var NC_ASH "Non-coniferous: Ash (Fraxinus spp.)"
cap label var NC_POP "Non-coniferous: Poplar (Populus spp.)"
cap label var NC_EUC "Non-coniferous: Eucalyptus (Eucalyptus spp.)"
cap label var NC_TRO "Non-coniferous: Tropical species"
