cap label var TOTAL "Total"
cap label var ATH "Aerothermal"
cap label var ATH_AA "Aerothermal - air-air"
cap label var ATH_AA_EC "Aerothermal - air-air electrical - cold climate"
cap label var ATH_AA_EA "Aerothermal - air-air electrical - average climate"
cap label var ATH_AA_EW "Aerothermal - air-air electrical - warm climate"
cap label var ATH_AA_TC "Aerothermal - air-air thermal - cold climate"
cap label var ATH_AA_TA "Aerothermal - air-air thermal - average climate"
cap label var ATH_AA_TW "Aerothermal - air-air thermal - warm climate"
cap label var ATH_AW "Aerothermal - air-water"
cap label var ATH_AW_EC "Aerothermal - air-water electrical - cold climate"
cap label var ATH_AW_EA "Aerothermal - air-water electrical - average climate"
cap label var ATH_AW_EW "Aerothermal - air-water electrical - warm climate"
cap label var ATH_AW_TC "Aerothermal - air-water thermal - cold climate"
cap label var ATH_AW_TA "Aerothermal - air-water thermal - average climate"
cap label var ATH_AW_TW "Aerothermal - air-water thermal - warm climate"
cap label var ATH_RAA "Aerothermal - reversible air-air"
cap label var ATH_RAA_EC "Aerothermal - reversible air-air electrical - cold climate"
cap label var ATH_RAA_EA "Aerothermal - reversible air-air electrical - average climate"
cap label var ATH_RAA_EW "Aerothermal - reversible air-air electrical - warm climate"
cap label var ATH_RAA_TC "Aerothermal - reversible air-air thermal - cold climate"
cap label var ATH_RAA_TA "Aerothermal - reversible air-air thermal - average climate"
cap label var ATH_RAA_TW "Aerothermal - reversible air-air thermal - warm climate"
cap label var ATH_RAW "Aerothermal - reversible air-water"
cap label var ATH_RAW_EC "Aerothermal - reversible air-water electrical - cold climate"
cap label var ATH_RAW_EA "Aerothermal - reversible air-water electrical - average climate"
cap label var ATH_RAW_EW "Aerothermal - reversible air-water electrical - warm climate"
cap label var ATH_RAW_TC "Aerothermal - reversible air-water thermal - cold climate"
cap label var ATH_RAW_TA "Aerothermal - reversible air-water thermal - average climate"
cap label var ATH_RAW_TW "Aerothermal - reversible air-water thermal - warm climate"
cap label var ATH_EAA "Aerothermal - exhaust air-air"
cap label var ATH_EAA_EC "Aerothermal - exhaust air-air electrical - cold climate"
cap label var ATH_EAA_EA "Aerothermal - exhaust air-air electrical - average climate"
cap label var ATH_EAA_EW "Aerothermal - exhaust air-air electrical - warm climate"
cap label var ATH_EAA_TC "Aerothermal - exhaust air-air thermal - cold climate"
cap label var ATH_EAA_TA "Aerothermal - exhaust air-air thermal - average climate"
cap label var ATH_EAA_TW "Aerothermal - exhaust air-air thermal - warm climate"
cap label var ATH_EAW "Aerothermal - exhaust air-water"
cap label var ATH_EAW_EC "Aerothermal - exhaust air-water electrical - cold climate"
cap label var ATH_EAW_EA "Aerothermal - exhaust air-water electrical - average climate"
cap label var ATH_EAW_EW "Aerothermal - exhaust air-water electrical - warm climate"
cap label var ATH_EAW_TC "Aerothermal - exhaust air-water thermal - cold climate"
cap label var ATH_EAW_TA "Aerothermal - exhaust air-water thermal - average climate"
cap label var ATH_EAW_TW "Aerothermal - exhaust air-water thermal - warm climate"
cap label var ATH_EC "Aerothermal - electrical - cold climate"
cap label var ATH_EA "Aerothermal - electrical - average climate"
cap label var ATH_EW "Aerothermal - electrical - warm climate"
cap label var ATH_TC "Aerothermal - thermal - cold climate"
cap label var ATH_TA "Aerothermal - thermal - average climate"
cap label var ATH_TW "Aerothermal - thermal - warm climate"
cap label var GTH "Geothermal"
cap label var GTH_GA "Geothermal - ground-air"
cap label var GTH_GA_EC "Geothermal - ground-air electrical - cold climate"
cap label var GTH_GA_EA "Geothermal - ground-air electrical - average climate"
cap label var GTH_GA_EW "Geothermal - ground-air electrical - warm climate"
cap label var GTH_GA_TC "Geothermal - ground-air thermal - cold climate"
cap label var GTH_GA_TA "Geothermal - ground-air thermal - average climate"
cap label var GTH_GA_TW "Geothermal - ground-air thermal - warm climate"
cap label var GTH_GW "Geothermal - ground-water"
cap label var GTH_GW_EC "Geothermal - ground-water electrical - cold climate"
cap label var GTH_GW_EA "Geothermal - ground-water electrical - average climate"
cap label var GTH_GW_EW "Geothermal - ground-water electrical - warm climate"
cap label var GTH_GW_TC "Geothermal - ground-water thermal - cold climate"
cap label var GTH_GW_TA "Geothermal - ground-water thermal - average climate"
cap label var GTH_GW_TW "Geothermal - ground-water thermal - warm climate"
cap label var GTH_EC "Geothermal - electrical - cold climate"
cap label var GTH_EA "Geothermal - electrical - average climate"
cap label var GTH_EW "Geothermal - electrical - warm climate"
cap label var GTH_TC "Geothermal - thermal - cold climate"
cap label var GTH_TA "Geothermal - thermal - average climate"
cap label var GTH_TW "Geothermal - thermal - warm climate"
cap label var HTH "Hydrothermal"
cap label var HTH_WA "Hydrothermal - water-air"
cap label var HTH_WA_EC "Hydrothermal - water-air electrical - cold climate"
cap label var HTH_WA_EA "Hydrothermal - water-air electrical - average climate"
cap label var HTH_WA_EW "Hydrothermal - water-air electrical - warm climate"
cap label var HTH_WA_TC "Hydrothermal - water-air thermal - cold climate"
cap label var HTH_WA_TA "Hydrothermal - water-air thermal - average climate"
cap label var HTH_WA_TW "Hydrothermal - water-air thermal - warm climate"
cap label var HTH_WW "Hydrothermal - water-water"
cap label var HTH_WW_EC "Hydrothermal - water-water electrical - cold climate"
cap label var HTH_WW_EA "Hydrothermal - water-water electrical - average climate"
cap label var HTH_WW_EW "Hydrothermal - water-water electrical - warm climate"
cap label var HTH_WW_TC "Hydrothermal - water-water thermal - cold climate"
cap label var HTH_WW_TA "Hydrothermal - water-water thermal - average climate"
cap label var HTH_WW_TW "Hydrothermal - water-water thermal - warm climate"
cap label var HTH_EC "Hydrothermal - electrical - cold climate"
cap label var HTH_EA "Hydrothermal - electrical - average climate"
cap label var HTH_EW "Hydrothermal - electrical - warm climate"
cap label var HTH_TC "Hydrothermal - thermal - cold climate"
cap label var HTH_TA "Hydrothermal - thermal - average climate"
cap label var HTH_TW "Hydrothermal - thermal - warm climate"
cap label var OTH "Other"
