cap label var TOTAL "Total"
cap label var TOTXDUR "Total excluding durables and valuable goods"
cap label var TRA "Expenditure on transport"
cap label var REST "Expenditure on restaurants/cafés"
cap label var ACC "Expenditure on accommodation"
cap label var PACK_ARR "Expenditure on package arrangement"
cap label var DUR "Expenditure on durables and valuable goods"
cap label var IW_VES "Expenditure on vessels in goods inland waterways transport enterprises"
cap label var IW_INF "Expenditure on inland waterways transport infrastructure"
cap label var RD_VEH "Expenditure on road transport vehicles"
cap label var RD_INF "Expenditure on road infrastructure"
cap label var RL_RSTK "Expenditure on rolling stock in principal railway enterprises"
cap label var RL_INF "Expenditure on infrastructure in principal railway enterprises"
cap label var ASERV "Expenditure on ancillary services"
cap label var RD "Expenditure on R&D activities"
cap label var INIT "Expenditure of government before intergovernmental transfers"
cap label var FINL "Expenditure of government after intergovernmental transfers"
cap label var AVG_TRP "Average expenditure per trip"
cap label var AVG_NGT "Average expenditure per night"
cap label var ADJ "Adjustments for changes in fund balances"
cap label var INV "Investment"
cap label var INV_IW_VES "Investment in vessels in goods inland waterways transport enterprises"
cap label var INV_IW_INF "Investment in inland waterways transport infrastructure"
cap label var INV_RD_VEH "Investment in road transport vehicles"
cap label var INV_RD_INF "Investment in road infrastructure"
cap label var INV_RL_RSTK "Investment in rolling stock in principal railway enterprises"
cap label var INV_RL_INF "Investment in infrastructure in principal railway enterprises"
cap label var TRF_PAY "Transfers and payments"
cap label var TRF "Subsidies/transfers"
cap label var TRF_NET "Net transfers"
cap label var MNT "Maintenance"
cap label var MNT_IW_VES "Maintenance in vessels in goods inland waterways transport enterprises"
cap label var MNT_IW_INF "Maintenance in inland waterways transport infrastructure"
cap label var MNT_RD_VEH "Maintenance in road transport vehicles"
cap label var MNT_RD_INF "Maintenance in road infrastructure"
cap label var MNT_RL_RSTK "Maintenance in rolling stock in principal railway enterprises"
cap label var MNT_RL_INF "Maintenance in infrastructure in principal railway enterprises"
cap label var CUR "Current expenditure"
cap label var CUR_LC "Current - labour cost"
cap label var CUR_COMP "Expenditure for compensation of personnel"
cap label var CUR_COMPT "Expenditure for compensation of teachers (with active teaching responsibilities)"
cap label var CUR_COMPO "Expenditure for compensation of other pedagogical, administrative, professional, and support personnel"
cap label var CUR_RET "Expenditure for retirement pensions"
cap label var CUR_NLC "Expenditure for other non-salary compensation"
cap label var CUR_OTH "Current - other expenditure"
cap label var CAP "Capital expenditure"
cap label var CAP_LAND "Capital - land and buildings"
cap label var CAP_INSTRM "Capital - instruments and equipment"
cap label var FA "Financial aid to households and students"
cap label var FA_GRNT "Scholarships and other grants to students/households"
cap label var FA_LOAN "Student loans"
cap label var DIR "Direct expenditure"
cap label var PAY "Payments"
cap label var PAY_NET "Net payments"
cap label var PAY_SEA "Payments for specific educational activities"
cap label var DW_ACQ "Acquisitions of dwellings"
cap label var DW_ACQ_NEW "New dwellings"
cap label var DW_ACQ_NEWP "Purchases of new dwellings"
cap label var DW_ACQ_NEWSB "Self-build dwellings and major renovations"
cap label var DW_ACQ_EXST "Existing dwellings new to the households"
cap label var DW_ACQ_OTH "Other services related to the acquisition of dwellings"
cap label var DW_OWN "Ownership of dwellings"
cap label var DW_OWN_RMNT "Major repairs and maintenance"
cap label var DW_OWN_INS "Insurance connected with dwellings"
cap label var DW_OWN_OTH "Other services related to ownership of dwellings"
cap label var INN "Expenditure on innovation (including R&D)"
cap label var INNXRND_CONTR_OUT "Expenditure on innovation excluding expenditure on R&D contracted out"
cap label var RND "Expenditure on R&D activities"
cap label var RND_IH "Expenditure on R&D performed in-house"
cap label var RND_CONTR_OUT "Expenditure on R&D contracted out"
cap label var INNXRND "Expenditure on innovation (excluding R&D)"
cap label var INNXRND_OWN_PER "Own personnel working on innovation"
cap label var INNXRND_CAP_GD "Capital goods for innovation (acquisition of machinery, equipment, software, intellectual property rights (IPRs), buildings, etc.)"
cap label var INNXRND_SMSP "Services, materials, supplies purchased for innovation"
cap label var ACQ_MEBTA "Acquisition of machinery, equipment, buildings and other tangible assets"
cap label var ACQ_MES "Acquisition of machinery, equipment and software"
cap label var SOFT_DBA_DA "Software development, database work and data analysis (include in-house costs and purchased services)"
cap label var RFM_IPR_PUR_LIC "Registering, filing and monitoring own Intellectual Property Rights (IPRs) and purchasing or licensing IPRs from others"
cap label var ACQ_EKNOW "Acquisition of other external knowledge"
cap label var MKTG_BB_ADV "Marketing, brand building, advertising (include in-house costs and purchased services)"
cap label var TNG_STAFF "Training own staff (include all in-house costs including wages and salaries of staff while being trained, and costs of purchased services from others)"
cap label var PRD_DESG "Product design (include in-house costs and purchased services)"
cap label var INN_OTH "Other expenditure on innovation (including design, training, marketing and other)"
cap label var OTH "Other expenditure"
