cap label var BEAAB "Aalst"
cap label var BEAAL "Aalter"
cap label var BEABK "Albertkanaal ports"
cap label var BEAMY "Amay"
cap label var BEAPS "Ampsin"
cap label var BEAND "Andenne"
cap label var BEANL "Anderlecht/Brussel (Bruxelles)"
cap label var BEANB "Angleur"
cap label var BEANH "Anhee"
cap label var BEAVE "Annevoie"
cap label var BEASR "Anseremme"
cap label var BEAHE "Antheit"
cap label var BEATO "Antoing"
cap label var BEANR "Antwerpen"
cap label var BEAPL "Appels"
cap label var BEAEJ "Arendonk"
cap label var BEAGT "Argenteau"
cap label var BEASP "Asper"
cap label var BEATH "Ath"
cap label var BEAVS "Auvelais"
cap label var BEAVL "Avelgem"
cap label var BEBSR "Baasrode"
cap label var BEBLE "Balen"
cap label var BEBTS "Bassenge (Bitsingen)"
cap label var BEBDU "Baudour"
cap label var BEBRM "Beernem"
cap label var BEBER "Beerse"
cap label var BEBEZ "Beez"
cap label var BEBCR "Bellecourt"
cap label var BEBLO "Beloeil"
cap label var BEBAN "Ben-Ahin"
cap label var BEBRT "Berendrecht"
cap label var BERIN "Beringen"
cap label var BEBWS "Beveren-Waas"
cap label var BEBLZ "Bilzen (Eigenbilzen)"
cap label var BEBLT "Blaton"
cap label var BEBHR "Bleharies"
cap label var BEBOC "Bocholt"
cap label var BEBOM "Boom"
cap label var BEBMB "Boortmeerbeek"
cap label var BEBON "Bornem"
cap label var BEBSU "Bossuit"
cap label var BEBRC "Brecht"
cap label var BEBRE "Bree"
cap label var BEBGS "Brugge (Bruges)"
cap label var BEBRU "Bruxelles (Brussel)"
cap label var BEBRY "Bruyelle"
cap label var BEBHU "Buggenhout"
cap label var BEBUD "Burcht"
cap label var BECRL "Charleroi"
cap label var BECHA "Chatelet"
cap label var BECRA "Cheratte"
cap label var BECRQ "Chercq"
cap label var BECTA "Chertal"
cap label var BECHI "Chièvres"
cap label var BECBQ "Clabecq"
cap label var BECOM "Comines"
cap label var BECCS "Courcelles"
cap label var BEDPY "Dampremy"
cap label var BEDEZ "Deinze"
cap label var BEDDR "Dendermonde"
cap label var BEDSE "Dessel"
cap label var BEDSL "Desselgem"
cap label var BEDEG "Deurne"
cap label var BEDPK "Diepenbeek"
cap label var BEDIK "Diksmuide"
cap label var BEDLS "Dilsen"
cap label var BEDIA "Dinant"
cap label var BEDEL "Doel"
cap label var BEDUF "Duffel"
cap label var BEEHT "Eindhout"
cap label var BEEIN "Eine"
cap label var BEESD "Eisden"
cap label var BEEQE "Eke"
cap label var BEENG "Engis"
cap label var BEREQ "Erquelinnes"
cap label var BEEQM "Esquelmes"
cap label var BEEVM "Evergem"
cap label var BEFCS "Farciennes"
cap label var BEFEY "Feluy"
cap label var BEFWI "Flawinne"
cap label var BEFMA "Flémalle"
cap label var BEFLH "Flémalle-Haute"
cap label var BEFLO "Floreffe"
cap label var BEFFX "Floriffoux"
cap label var BEFVT "Fontaine-Valmont"
cap label var BEGVR "Gavere"
cap label var BEGEL "Geel"
cap label var BEGNK "Genk"
cap label var BEGNE "Gent (Ghent)"
cap label var BEGEA "Geraardsbergen"
cap label var BEGHL "Ghlin"
cap label var BEGOS "Gosselies"
cap label var BEGZE "Gozee"
cap label var BEGRB "Grimbergen"
cap label var BEGBB "Grobbendonk"
cap label var BEHCT "Haccourt"
cap label var BEHFB "Halle"
cap label var BEHMM "Hamme"
cap label var BEHBE "Hansbeke"
cap label var BEHEJ "Harelbeke"
cap label var BEHAR "Haren"
cap label var BEHSS "Hasselt"
cap label var BEHTJ "Hautrage"
cap label var BEHRE "Havre"
cap label var BEHEX "Hemiksem"
cap label var BEHNS "Hensies"
cap label var BEHER "Herentals"
cap label var BEHSA "Hermalle-sous-Argenteau"
cap label var BEHRS "Herstal"
cap label var BEHZO "Heusden-Zolder"
cap label var BEHBN "Hoboken"
cap label var BEHSD "Hofstade"
cap label var BEHOL "Hollain"
cap label var BEHGG "Houdeng-Goegnies"
cap label var BEHUM "Humbeek"
cap label var BEHUN "Hun"
cap label var BEHUY "Huy"
cap label var BEIPR "Ieper (Ypres)"
cap label var BEIGE "Ingelmunster"
cap label var BEITR "Ittre (Itter)"
cap label var BEYRT "Ivoz-Ramet"
cap label var BEIZG "Izegem"
cap label var BEJAM "Jambes"
cap label var BEJPS "Jemeppe-sur-Sambre"
cap label var BEKAI "Kain"
cap label var BEKOU "Kallo"
cap label var BEKMH "Kampenhout"
cap label var BEKAN "Kanne (Canne)"
cap label var BEKPB "Kapelle-op-den-Bos"
cap label var BEKHN "Kerkhove"
cap label var BEKRO "Kinrooi"
cap label var BEKSR "Kluisbergen"
cap label var BEKJK "Kortrijk"
cap label var BEKEK "Kruibeke"
cap label var BEKHM "Kruishoutem"
cap label var BEKUU "Kuurne"
cap label var BEKWA "Kwaadmechelen"
cap label var BELDA "Laakdal (Meerhout)"
cap label var BELLO "La Louvière"
cap label var BELAN "Lanaken"
cap label var BELDS "Landelies"
cap label var BELRG "Ledeberg"
cap label var BELBE "Lembeek"
cap label var BELEU "Leuven"
cap label var BELHK "Liefkenshoek"
cap label var BELGG "Liege"
cap label var BELIE "Lier"
cap label var BELIL "Lillo"
cap label var BELSG "Lissewege"
cap label var BELIX "Lixhe"
cap label var BELBS "Lobbes"
cap label var BELOK "Lokeren"
cap label var BELML "Lommel"
cap label var BELOT "Lot"
cap label var BELVO "Lovendegem"
cap label var BELUM "Lummen"
cap label var BEMSK "Maaseik"
cap label var BEMCN "Machelen"
cap label var BEMAN "Manage"
cap label var BEMAP "Marchienne-au-Pont"
cap label var BEMCL "Marcinelle"
cap label var BEMHN "Massenhoven"
cap label var BEMMN "Maasmechelen"
cap label var BEECH "Mechelen"
cap label var BEMEH "Meerhout"
cap label var BEMEN "Menen"
cap label var BEMCA "Merbes-le-Chateau"
cap label var BEMRL "Merelbeke"
cap label var BEMRM "Merkem"
cap label var BEMRK "Merksem"
cap label var BEMNO "Moen"
cap label var BEMEW "Moerbeke-Waas"
cap label var BEMLO "Mol"
cap label var BEMSS "Monceau-sur-Sambre"
cap label var BEMQS "Mons"
cap label var BEMSI "Monsin"
cap label var BEMGS "Montignies-sur-Sambre"
cap label var BENMC "Namêche"
cap label var BENAM "Namur"
cap label var BENRP "Neerpelt"
cap label var BENIL "Niel"
cap label var BENIE "Nieuwpoort"
cap label var BENBA "Nimy"
cap label var BENNV "Ninove"
cap label var BENVN "Noeveren"
cap label var BEOBR "Obourg"
cap label var BEOQC "Oisquercq"
cap label var BEOLN "Olen"
cap label var BEOOG "Ooigem"
cap label var BEOST "Oostende (Ostend)"
cap label var BEOSH "Oostham "
cap label var BEOKP "Oostkamp"
cap label var BEOUD "Oudenaarde"
cap label var BEOBG "Oudenburg"
cap label var BEOPY "Oupeye"
cap label var BEOVE "Overpelt"
cap label var BEPCQ "Pecq"
cap label var BEPES "Peronnes"
cap label var BEPWZ "Peruwelz"
cap label var BEPLY "Petit-Lanaye"
cap label var BEPTP "Pijp Tabak"
cap label var BEPME "Pommeroeul"
cap label var BEPCL "Pont-a-Celles"
cap label var BEPLO "Pont-de-Loup"
cap label var BEPFE "Profondeville"
cap label var BEPUU "Puurs"
cap label var BERAS "Ranst"
cap label var BERVS "Ravels"
cap label var BERTI "Retie"
cap label var BERIS "Riemst"
cap label var BERIJ "Rijkevorsel"
cap label var BERVE "Riviere"
cap label var BEROE "Roeselare"
cap label var BERQS "Ronquieres"
cap label var BERCT "Roucourt"
cap label var BEROX "Roux"
cap label var BERUE "Ruien"
cap label var BESVG "Ruisbroek "
cap label var BERUI "Ruisbroek"
cap label var BERUS "Rumst"
cap label var BERPM "Rupelmonde"
cap label var BESGS "Saint-Georges"
cap label var BESPE "Scheepsdale"
cap label var BESHL "Schelle"
cap label var BESHB "Schellebelle"
cap label var BESNE "Schoonaarde"
cap label var BESCT "Schoten"
cap label var BESLY "Sclayn"
cap label var BESEN "Seneffe"
cap label var BEZER "Seraing"
cap label var BESAS "Sint Amands"
cap label var BESAN "Sint Andries"
cap label var BESTV "Sint-Baafs-Vijve"
cap label var BESEV "Sint-Eloois-Vijve"
cap label var BEMSJ "Sint Jans-Molenbeek (Molenbeek-Saint Jean)"
cap label var BESLN "Sint Lenaarts"
cap label var BESML "Sint Martens-Latem"
cap label var BESPT "Sint Pieters-Leeuw"
cap label var BESMM "Smeermaas"
cap label var BESDT "Soudromont"
cap label var BESPI "Spiere (Espierres)"
cap label var BESGM "Stasegem"
cap label var BESTB "Strepy-Bracquegnies"
cap label var BETMS "Tamines"
cap label var BETSE "Temse"
cap label var BETGE "Tergnee"
cap label var BETGN "Terhagen"
cap label var BETET "Tertre"
cap label var BETES "Tessenderlo"
cap label var BETHE "Thieu"
cap label var BETHU "Thuin"
cap label var BETHG "Tihange"
cap label var BETIS "Tisselt"
cap label var BETRN "Tournai (Doornik)"
cap label var BETUR "Turnhout"
cap label var BEVLX "Vaulx"
cap label var BEVSH "Ville-sur-Haine"
cap label var BEVIL "Vilvoorde"
cap label var BEVGL "Virginal-Samme"
cap label var BEVIS "Vise"
cap label var BEWND "Wandre"
cap label var BEWAN "Wanze"
cap label var BEWCG "Warcoing"
cap label var BEWAR "Waregem"
cap label var BEBWN "Warneton"
cap label var BEWLT "Waulsort"
cap label var BEWIP "Wepion"
cap label var BEWER "Wervik"
cap label var BEWES "Westerlo (Oevel)"
cap label var BEWET "Wetteren"
cap label var BEWEV "Wevelgem"
cap label var BEWIH "Wichelen"
cap label var BEWIR "Wiers"
cap label var BEWGL "Wijgmaal"
cap label var BEWJG "Wijnegem"
cap label var BEWLB "Willebroek"
cap label var BEWSL "Wilsele"
cap label var BEWTH "Wintham"
cap label var BEWDG "Wondelgem"
cap label var BEYVO "Yvoir"
cap label var BEZAN "Zandhoven"
cap label var BEZVT "Zandvliet"
cap label var BEZVD "Zandvoorde"
cap label var BEZEE "Zeebrugge"
cap label var BEZLE "Zele"
cap label var BEZEL "Zelzate"
cap label var BEZET "Zemst"
cap label var BEZGM "Zingem"
cap label var BEZOD "Zolder"
cap label var BEZRM "Zomergem"
cap label var BEZUL "Zulte"
cap label var BEZTL "Zutendaal"
cap label var BEZWE "Zwevegem"
cap label var BEZWN "Zwijnaarde"
cap label var BEZWL "Zwijndrecht"
cap label var BE888 "Belgium - other ports"
cap label var BGBLE "Belene"
cap label var BGKOZ "Kozloduj "
cap label var BGLOM "Lom"
cap label var BGNPO "Nikopol"
cap label var BGORE "Oryahovo"
cap label var BGRDU "Ruse"
cap label var BGSLS "Silistra"
cap label var BGSOM "Somovit"
cap label var BGSVI "Svishtov"
cap label var BGTRP "Tutrakan"
cap label var BGVID "Vidin"
cap label var CZCHV "Chvaletice"
cap label var CZDCB "Decín"
cap label var CZHVI "Hnevice"
cap label var CZKLN "Kolin"
cap label var CZKSL "Kostelec nad Labem "
cap label var CZLIC "Libochovany"
cap label var CZLTC "Litomerice"
cap label var CZLVC "Lovosice"
cap label var CZMEL "Melník"
cap label var CZNLH "Nelahozeves"
cap label var CZNRT "Neratovice"
cap label var CZNMB "Nymburk "
cap label var CZPRG "Praha"
cap label var CZRNL "Roudnice nad Labem "
cap label var CZSTE "Štechovice"
cap label var CZSTT "Steti"
cap label var CZTYL "Týnec nad Labem "
cap label var CZULN "Ústí nad Labem"
cap label var DEACM "Achim"
cap label var DEAKE "Aken"
cap label var DEAGM "Algermissen"
cap label var DEABC "Altbach"
cap label var DEAND "Andernach"
cap label var DEANK "Anklam"
cap label var DEASC "Aschaffenburg"
cap label var DEAUR "Aurich"
cap label var DEBES "Bad Essen"
cap label var DEBFA "Bad Freienwalde"
cap label var DEBFH "Bad Friedrichshall"
cap label var DEBWF "Bad Wimpfen"
cap label var DEBAM "Bamberg"
cap label var DEBBY "Barby"
cap label var DEBEI "Beidenfleth"
cap label var DEIGN "Beihingen"
cap label var DEBDF "Bendorf/Rhein"
cap label var DEBGK "Benningen am Neckar"
cap label var DEBCB "Berenbusch"
cap label var DEBKN "Bergkamen"
cap label var DEBER "Berlin"
cap label var DEPRL "Besch"
cap label var DEBEV "Beverungen"
cap label var DEBIN "Bingen"
cap label var DE8BO "Bischberg"
cap label var DEBKH "Bockhorst"
cap label var DEBON "Bonn"
cap label var DEBTA "Bortfeld"
cap label var DEBOT "Bottrop"
cap label var DEBKE "Brake"
cap label var DEBRM "Bramsche"
cap label var DEBBG "Brandenburg "
cap label var DEBWE "Braunschweig"
cap label var DEBSH "Breisach am Rhein"
cap label var DEBRE "Bremen"
cap label var DEBRV "Bremerhaven"
cap label var DEBRB "Brunsbüttel"
cap label var DEBUD "Budenheim"
cap label var DELYY "Bullay"
cap label var DEBYN "Bülstringen"
cap label var DEBUR "Burg bei Magdeburg"
cap label var DEBTD "Bürgstadt"
cap label var DECRL "Castrop-Rauxel"
cap label var DECUX "Cuxhaven"
cap label var DEDAT "Datteln"
cap label var DELNL "Daverden"
cap label var DEDEG "Deggendorf"
cap label var DEDMN "Demmin"
cap label var DEDES "Dessau Leopoldshafen"
cap label var DEDTB "Dettelbach"
cap label var DEDNH "Dettenheim "
cap label var DEMDD "Diedesheim/Mosbach "
cap label var DEDTF "Dietfurt"
cap label var DEDOZ "Döberitz"
cap label var DEDTZ "Dömitz"
cap label var DEDMG "Dormagen"
cap label var DEDRP "Dörpen"
cap label var DEDON "Dorsten"
cap label var DEDTM "Dortmund"
cap label var DEDRS "Dresden-Friedrichstadt"
cap label var DEWEY "Dreye"
cap label var DEDRO "Drochtersen"
cap label var DEDUI "Duisburg"
cap label var DEDUS "Düsseldorf"
cap label var DEFRE "Düthe (Fresenburg-Düthe)"
cap label var DEEBB "Eberbach"
cap label var DEEBW "Eberswalde"
cap label var DEEM2 "Edewechterdamm"
cap label var DEEDI "Edingen"
cap label var DEEGL "Eggenstein-Leopoldshafen"
cap label var DEECI "Eich"
cap label var DEEHS "Eisenhüttenstadt"
cap label var DEELF "Elsenfeld"
cap label var DEELS "Elsfleth"
cap label var DEEME "Emden"
cap label var DEESU "Emmelsum"
cap label var DEEMM "Emmerich"
cap label var DEEDO "Ensdorf (Umschlagstelle Kraftwerk VSE)"
cap label var DEERL "Erlangen"
cap label var DEEAM "Erlenbach am Main"
cap label var DEESP "Espelkamp"
cap label var DEESS "Essen"
cap label var DEFLO "Flörsheim am Main"
cap label var DEFOH "Forchheim"
cap label var DEFRA "Frankfurt am Main"
cap label var DEFFO "Frankfurt/Oder "
cap label var DEFEG "Freiberg am Neckar"
cap label var DE76C "Freiburg"
cap label var DEFRH "Freudenberg"
cap label var DEFRI "Friedrichstadt"
cap label var DEFUB "Fürstenberg"
cap label var DEFTE "Fürstenwalde"
cap label var DEFUE "Fürth"
cap label var DEGET "Geesthacht"
cap label var DEGEI "Geisenheim"
cap label var DEGEK "Gelsenkirchen"
cap label var DEGGM "Gemmrigheim"
cap label var DEGEM "Gemünden am Main"
cap label var DEGNT "Genthin"
cap label var DEGER "Germersheim"
cap label var DEGHM "Gernsheim"
cap label var DEPOL "Getmold"
cap label var DEGIG "Ginsheim-Gustavsburg"
cap label var DEGLU "Glückstadt"
cap label var DE53P "Göttin"
cap label var DELCT "Grauelsbaum"
cap label var DEGWY "Grenzach-Wyhlen "
cap label var DEGVN "Greven"
cap label var DEVER "Gross Hutbergen"
cap label var DEZUZ "Groß Kreutz"
cap label var DEGKG "Großkrotzenburg"
cap label var DEHLH "Haldensleben"
cap label var DEHAL "Halle-Trotha"
cap label var DEHTN "Haltern am See"
cap label var DEHAM "Hamburg"
cap label var DEHAN "Hameln"
cap label var DEHMM "Hamm"
cap label var DEHAU "Hanau"
cap label var DEHAJ "Hannover"
cap label var DEHMU "Hannoversch Münden "
cap label var DEHRN "Haren"
cap label var DEHRS "Harsum"
cap label var DEHAS "Haßfurt"
cap label var DEHXX "Haßmersheim"
cap label var DEHDA "Heidenau"
cap label var DEHEN "Heilbronn"
cap label var DEHNF "Hennigsdorf"
cap label var DEHEE "Herne"
cap label var DEHIL "Hildesheim"
cap label var DEHIE "Hille"
cap label var DEHHN "Hirschhorn"
cap label var DEHOD "Hochdonn"
cap label var DEHHS "Hohenhörn"
cap label var DEHOY "Hoya"
cap label var DEIBB "Ibbenbüren"
cap label var DECIH "Ichenheim"
cap label var DEIFF "Iffezheim"
cap label var DEILG "Illingen"
cap label var DEINM "Ingelheim"
cap label var DEITZ "Itzehoe"
cap label var DEJMN "Jarmen"
cap label var DEKAE "Karlsruhe"
cap label var DEKSD "Karlstadt"
cap label var DEKEH "Kehl"
cap label var DEKEM "Kelheim"
cap label var DEKEB "Kelsterbach"
cap label var DEKT2 "Ketzin"
cap label var DEKEL "Kiel"
cap label var DEKNC "Kirchheim am Neckar"
cap label var DEKIT "Kitzingen"
cap label var DEKTM "Kleinostheim"
cap label var DEKLE "Kleve"
cap label var DEKOB "Koblenz"
cap label var DECGN "Köln"
cap label var DEKWH "Königs Wusterhausen"
cap label var DEKRE "Krefeld"
cap label var DELDB "Ladbergen"
cap label var DELRG "Ladenburg"
cap label var DELHD "Lahde"
cap label var DELAH "Lahnstein"
cap label var DELAM "Lampertheim"
cap label var DELJN "Landesbergen"
cap label var DELAT "Lathen"
cap label var DELNU "Lauenburg"
cap label var DELFN "Lauffen am Neckar"
cap label var DELEE "Leer"
cap label var DELEX "Leese"
cap label var DELSN "Leeseringen"
cap label var DELEV "Leverkusen"
cap label var DELIB "Liebenau"
cap label var DELIG "Lingen"
cap label var DELRN "Linz am Rhein"
cap label var DELBE "Lübbecke"
cap label var DELBC "Lübeck"
cap label var DELBM "Lubmin"
cap label var DELWG "Ludwigsburg"
cap label var DELUH "Ludwigshafen"
cap label var DELLS "Lülsdorf"
cap label var DELBG "Lüneburg (Esk)"
cap label var DELUE "Lünen"
cap label var DEMAG "Magdeburg"
cap label var DEMAI "Mainz"
cap label var DEMHG "Mannheim"
cap label var DEMNC "Marbach am Neckar"
cap label var DEMKT "Marktbreit"
cap label var DEMAD "Marktheidenfeld"
cap label var DEMAL "Marl"
cap label var DEMRU "Mehrum"
cap label var DE5ME "Meißenheim"
cap label var DEMEP "Meppen"
cap label var DEMER "Merzig"
cap label var DEMIL "Miltenberg"
cap label var DEMID "Minden"
cap label var DEMOE "Mölln"
cap label var DEMUH "Mülheim an der Ruhr"
cap label var DE79P "Mundelsheim"
cap label var DEMSR "Münster"
cap label var DENUQ "Nauen/Wustermark"
cap label var DENMD "Neckargemünd"
cap label var DE78R "Neckargerach"
cap label var DENST "Neckarsteinach"
cap label var DENEH "Neuhaus an der Oste"
cap label var DENSS "Neuss"
cap label var DENED "Neuwied"
cap label var DE75D "Niedernwöhren"
cap label var DEZCX "Nienburg (Saale)"
cap label var DENIE "Nienburg (Weser)"
cap label var DENIN "Nierstein"
cap label var DENHA "Nordenham"
cap label var DETRD "Nord-Ostsee-Kanal"
cap label var DENUE "Nürnberg"
cap label var DEOBE "Oberhausen"
cap label var DEORN "Oberhausen-Rheinhausen"
cap label var DEOBG "Obernburg am Main"
cap label var DEOEE "Oberwesel"
cap label var DEOGH "Obrigheim"
cap label var DEOCF "Ochsenfurt"
cap label var DEOFF "Offenbach am Main"
cap label var DEHHM "Okriftel - Hattersheim"
cap label var DEOLO "Oldenburg"
cap label var DEORA "Oranienburg"
cap label var DEOSN "Osnabrück"
cap label var DEOCP "Ostercappeln"
cap label var DEOHI "Ottenheim"
cap label var DEOTS "Otterstadt"
cap label var DEPAP "Papenburg"
cap label var DEPAS "Passau"
cap label var DEPZI "Pautzfeld"
cap label var DEPEI "Peine"
cap label var DEPEL "Pellworm Insel"
cap label var DEPSW "Petershagen/Weser"
cap label var DEPHG "Philippsburg"
cap label var DEPSR "Piesteritz"
cap label var DEPLO "Plochingen"
cap label var DEPLL "Pollhagen"
cap label var DEPOT "Potsdam"
cap label var DEPUB "Putbus"
cap label var DERNW "Rathenow"
cap label var DERAU "Raunheim"
cap label var DERCK "Recke"
cap label var DEREC "Recklinghausen"
cap label var DERES "Rees"
cap label var DEREG "Regensburg"
cap label var DERNK "Remseck am Neckar "
cap label var DEREN "Rendsburg"
cap label var DERHI "Rheinau"
cap label var DERHB "Rheinberg-Ossenberg"
cap label var DERHL "Rheinbrohl"
cap label var DERHE "Rheine"
cap label var DERFN "Rheinfelden"
cap label var DERHR "Rheinmünster"
cap label var DE5RI "Riedenburg"
cap label var DERDS "Riedstadt"
cap label var DERSA "Riesa"
cap label var DERIN "Rinteln"
cap label var DERGZ "Rogätz"
cap label var DEROG "Römerberg"
cap label var DERSK "Rostock"
cap label var DERTH "Roth"
cap label var DERDO "Rüdersdorf bei Berlin"
cap label var DERUE "Rüdesheim am Rhein"
cap label var DESCN "Saarbrücken"
cap label var DESAA "Saarlouis-Dillingen"
cap label var DE75F "Sachsenhagen"
cap label var DESAR "Salzgitter"
cap label var DEYDC "Sand am Main"
cap label var DEMHA "Schmedehausen"
cap label var DEOKE "Schönebeck"
cap label var DESDT "Schwedt"
cap label var DESCW "Schweinfurt"
cap label var DESRI "Schweringen"
cap label var DESBG "Sedelsberg"
cap label var DESZE "Seelze"
cap label var DESNE "Sehnde"
cap label var DESLE "Spelle"
cap label var DESPE "Speyer"
cap label var DESPH "Spreenhagen"
cap label var DEPYK "Spyck"
cap label var DESTA "Stade"
cap label var DESIU "Steinmauern"
cap label var DESYS "Stockstadt am Main"
cap label var DEAMU "Stolpe an der Oder"
cap label var DESLJ "Stolzenau"
cap label var DESTL "Stralsund"
cap label var DESTB "Straubing-Sand"
cap label var DESTR "Stuttgart"
cap label var DETAE "Tangermünde"
cap label var DETOU "Torgau"
cap label var DETRH "Trechtingshausen"
cap label var DETFS "Triefenstein"
cap label var DETRI "Trier"
cap label var DEUCK "Ueckermünde"
cap label var DEUEL "Uelzen"
cap label var DEUET "Uetersen"
cap label var DENQB "Vahldorf"
cap label var DEVLT "Velten"
cap label var DEVNA "Venhaus"
cap label var DEVT9 "Viereth-Trunstadt "
cap label var DEVIW "Vierow"
cap label var DEVOG "Vogtsburg im Kaiserstuhl"
cap label var DEVOL "Volkach"
cap label var DEVOE "Völklingen"
cap label var DEWLE "Walheim"
cap label var DEWTP "Waltrop"
cap label var DEANE "Wanne-Eickel"
cap label var DEWED "Wedel-Schulau"
cap label var DEWLR "Weil am Rhein"
cap label var DEWNU "Weissenthurm"
cap label var DEWLX "Wellen"
cap label var DEWTM "Wertheim"
cap label var DEWES "Wesel"
cap label var DEWLG "Wesseling"
cap label var DEWEW "Wewelsfleth"
cap label var DEWIB "Wiesbaden"
cap label var DEWVN "Wilhelmshaven"
cap label var DEWTG "Wittenberg"
cap label var DETNR "Wittenberge"
cap label var DEWTN "Wittingen"
cap label var DEWOB "Wolfsburg (Volkswagenwerk)"
cap label var DEWOL "Wolgast"
cap label var DEWOR "Worms"
cap label var DEWOE "Wörth am Rhein"
cap label var DEWUN "Wunstorf"
cap label var DE77H "Wyhl am Kaiserstuhl"
cap label var DEWUE "Würzburg"
cap label var DEZEI "Zeil am Main "
cap label var DEZZN "Zeitlarn"
cap label var DEZEL "Zell/Mosel"
cap label var DEZEN "Zellingen"
cap label var DE888 "Germany - other ports"
cap label var DE88O "Germany (Baltic Sea) - other ports"
cap label var DE88N "Germany (North Sea) - other ports"
cap label var DE88I "Germany - other inland ports"
cap label var FRBYW "Balloy"
cap label var FRBEH "Beinheim "
cap label var FRIUS "Bernières-sur-Seine"
cap label var FRBSM "Bonneuil-sur-Marne "
cap label var FRBFL "Bouafles"
cap label var FRCMR "Colmar "
cap label var FRDKK "Dunkerque"
cap label var FRFOS "Fos-sur-Mer "
cap label var FROXA "Frouard"
cap label var FRGVL "Gennevilliers"
cap label var FRHUN "Huningue"
cap label var FRIVS "Ivry-sur-Seine "
cap label var FRLAU "Lauterbourg"
cap label var FRLAV "Lavéra"
cap label var FRLEH "Le Havre"
cap label var FRLMY "Limay"
cap label var FRLIO "Lyon"
cap label var FRMQS "Marolles-sur-Seine "
cap label var FRMZM "Metz"
cap label var FRMDG "Mondelange "
cap label var FRMUN "Mulhouse-Nord "
cap label var FRNAN "Nanterre"
cap label var FRNEM "Neuves-Maisons "
cap label var FROTM "Ottmarsheim"
cap label var FRPAR "Paris"
cap label var FRPET "Petit-Couronne "
cap label var FRURO "Rouen"
cap label var FRRVO "Rouvignies"
cap label var FRTEN "Stattmatten "
cap label var FRSXB "Strasbourg"
cap label var FRTVL "Thionville "
cap label var FRVSS "Villefranche-sur-Saône "
cap label var FR888 "France - other ports"
cap label var HROSI "Osijek"
cap label var HRSIS "Sisak"
cap label var HRSBD "Slavonski Brod"
cap label var HRVUK "Vukovar"
cap label var HUADY "Adony"
cap label var HUBAA "Baja"
cap label var HUBUD "Budapest"
cap label var HUDUU "Dunaújváros"
cap label var HUGYO "Gyor-Gönyü"
cap label var HUKOM "Komárom"
cap label var HUMOH "Mohács"
cap label var HUPAK "Paks"
cap label var HUSZE "Szeged"
cap label var NLAAM "Aalsmeer"
cap label var NLARI "Aarle Rixtel"
cap label var NLABC "Abcoude"
cap label var NLAKL "Akersloot"
cap label var NLABL "Alblasserdam"
cap label var NLALK "Alkmaar"
cap label var NLALM "Almelo"
cap label var NLAER "Almere"
cap label var NLAPN "Alphen aan den Rijn"
cap label var NLAML "Ameland"
cap label var NLAMR "Amerongen"
cap label var NLAME "Amersfoort"
cap label var NLAMZ "Ammerzoden"
cap label var NLAMV "Amstelveen"
cap label var NLAMS "Amsterdam"
cap label var NLAIJ "Andijk"
cap label var NLANP "Anna Paulowna"
cap label var NLAPP "Appingedam"
cap label var NLARC "Arcen"
cap label var NLARN "Arnhem"
cap label var NLASS "Assen"
cap label var NLAXL "Axel"
cap label var NLBAA "Baarn"
cap label var NLBRR "Barendrecht"
cap label var NLBFD "Belfeld"
cap label var NLBEM "Bemmel"
cap label var NLBGB "Bergambacht"
cap label var NLBEG "Bergen"
cap label var NLBZM "Bergen op Zoom"
cap label var NLBST "Best"
cap label var NLBNN "Beuningen"
cap label var NLBEV "Beverwijk"
cap label var NLBOG "Bodegraven"
cap label var NLBON "Born"
cap label var NLBOR "Borsele"
cap label var NLBSK "Boskoop"
cap label var NLBOX "Boxmeer"
cap label var NLBRK "Brakel"
cap label var NLBRD "Breda"
cap label var NLBRS "Breskens"
cap label var NLRUK "Breukelen"
cap label var NLBRI "Brielle"
cap label var NLBRO "Brouwershaven"
cap label var NLBSE "Bruinisse"
cap label var NLBRM "Brummen"
cap label var NLBUD "Budel"
cap label var NLBUN "Bunschoten"
cap label var NLCPI "Capelle a/d IJssel"
cap label var NLCOE "Coevorden"
cap label var NLCUY "Cuijk"
cap label var NLCUB "Culemborg"
cap label var NLDLR "De Lier"
cap label var NLDEL "Delden"
cap label var NLDFT "Delft"
cap label var NLDZL "Delfzijl"
cap label var NLDHR "Den Helder"
cap label var NLDEV "Deventer"
cap label var NLDIM "Diemen"
cap label var NLDIN "Dinteloord"
cap label var NLDWA "Dodewaard"
cap label var NLDOE "Doesburg"
cap label var NLDOI "Doetinchem"
cap label var NLDON "Dongen"
cap label var NLDOR "Dordrecht"
cap label var NLDRO "Dronten"
cap label var NLDRU "Druten"
cap label var NLDUI "Duiven"
cap label var NLECH "Echt"
cap label var NLECD "Echteld"
cap label var NLEDM "Edam"
cap label var NLEES "Eemnes"
cap label var NLEEM "Eemshaven"
cap label var NLEYS "Eijsden"
cap label var NLEIN "Eindhoven"
cap label var NLELB "Elburg"
cap label var NLQCU "Elst"
cap label var NLEMM "Emmen"
cap label var NLENK "Enkhuizen"
cap label var NLENS "Enschede"
cap label var NLETT "Etten-Leur"
cap label var NLFAR "Farmsum"
cap label var NLGTB "Geertruidenberg"
cap label var NLGDM "Geldermalsen"
cap label var NLGET "Gendt"
cap label var NLGNM "Genemuiden"
cap label var NLGEN "Gennep"
cap label var NLGSM "Giessendam"
cap label var NLGDR "Goedereede"
cap label var NLGOE "Goes"
cap label var NLGOO "Goor"
cap label var NLGOR "Gorinchem"
cap label var NLGOU "Gouda"
cap label var NLGBG "Gramsbergen"
cap label var NLGRQ "Groningen"
cap label var NLHAA "Haarlem"
cap label var NLHAE "Haelen"
cap label var NLHAN "Hansweert"
cap label var NLHBG "Hardenberg"
cap label var NLHRD "Harderwijk"
cap label var NLHAR "Harlingen"
cap label var NLHAS "Hasselt"
cap label var NLHTM "Hattem"
cap label var NLHDL "Hedel"
cap label var NLHEE "Heel"
cap label var NLHMS "Heemstede"
cap label var NLHRV "Heerenveen"
cap label var NLHRW "Heerewaarden"
cap label var NLHHW "Heerhugowaard"
cap label var NLHKF "Heerjansdam"
cap label var NLHEJ "Heijen"
cap label var NLHLO "Heiloo"
cap label var NLHEL "Helden"
cap label var NLHSL "Hellevoetsluis"
cap label var NLHLM "Helmond"
cap label var NLHIA "Hendrik-Ido-Ambacht"
cap label var NLHGL "Hengelo"
cap label var NLHTR "Heteren"
cap label var NLHUM "Heumen"
cap label var NLHES "Heusden"
cap label var NLHIL "Hillegom"
cap label var NLHVS "Hilversum"
cap label var NLHOV "Hoogeveen"
cap label var NLHZD "Hoogezand"
cap label var NLHRN "Hoorn"
cap label var NLHOU "Houten"
cap label var NLHUI "Huizen"
cap label var NLIJM "Ijmuiden"
cap label var NLKAM "Kampen"
cap label var NLKPL "Kapelle"
cap label var NLKWK "Katwijk"
cap label var NLKSL "Kessel"
cap label var NLKST "Kesteren"
cap label var NLKAI "Krimpen a/d IJssel"
cap label var NLLAW "Lage Weide"
cap label var NLLEE "Leek"
cap label var NLLRD "Leerdam"
cap label var NLLWR "Leeuwarden"
cap label var NLLID "Leiden"
cap label var NLLDD "Leiderdorp"
cap label var NLLDS "Leidschendam"
cap label var NLLEY "Lelystad"
cap label var NLLXM "Lexmond"
cap label var NLLIE "Lienden"
cap label var NLQDG "Lisse"
cap label var NLLIT "Lith"
cap label var NLLCH "Lochem"
cap label var NLLAV "Loenen aan de Vecht"
cap label var NLLPK "Lopik"
cap label var NLMSS "Maarssen"
cap label var NLMSB "Maasbracht"
cap label var NLMSL "Maassluis"
cap label var NLMST "Maastricht"
cap label var NLQDJ "Made"
cap label var NLMAR "Markelo"
cap label var NLMAU "Maurik"
cap label var NLMDM "Medemblik"
cap label var NLMEP "Meppel"
cap label var NLMID "Middelburg"
cap label var NLMIH "Middelharnis"
cap label var NLMLR "Millingen aan de Rijn"
cap label var NLMOE "Moerdijk"
cap label var NLMON "Monster"
cap label var NLMOK "Mook"
cap label var NLMOO "Moordrecht"
cap label var NLMUD "Muiden"
cap label var NLNAW "Naaldwijk"
cap label var NLNAA "Naarden"
cap label var NLNDB "Nederhorst den Berg"
cap label var NLNRW "Nederweert"
cap label var NLNWG "Nieuwegein"
cap label var NLNIE "Nieuwerkerk aan de Ijssel"
cap label var NLNLK "Nieuw-Lekkerland"
cap label var NLNKK "Nijkerk"
cap label var NLNIJ "Nijmegen"
cap label var NLOGE "Oegstgeest"
cap label var NLOIH "Oirschot"
cap label var NLOOS "Oosterhout"
cap label var NLOSS "Oss"
cap label var NLOBL "Oud-Beijerland"
cap label var NLODR "Ouderkerk aan de Amstel"
cap label var NLOAI "Ouderkerk aan den Ijssel"
cap label var NLPAP "Papendrecht"
cap label var NLPUM "Purmerend"
cap label var NLPTN "Putten"
cap label var NLRAS "Ravenstein"
cap label var NLRNK "Renkum"
cap label var NLRHD "Rheden"
cap label var NLRHE "Rhenen"
cap label var NLRID "Ridderkerk"
cap label var NLRBG "Rijnsburg"
cap label var NLRYS "Rijswijk"
cap label var NLOMD "Roermond"
cap label var NLROO "Roosendaal"
cap label var NLRTM "Rotterdam"
cap label var NLROZ "Rozenburg"
cap label var NLSVG "Sas van Gent"
cap label var NLSAS "Sassenheim"
cap label var NLSCH "Schagen"
cap label var NLSMD "Scheemda"
cap label var NLSCI "Schiedam"
cap label var NLSMG "Schiermonnikoog"
cap label var NLSND "Schijndel"
cap label var NLSHH "Schoonhoven"
cap label var NLGRA "s-Gravendeel"
cap label var NLHAG "s-Gravenhage (Den Haag)"
cap label var NLGRZ "s-Gravenzande"
cap label var NLHTB "s-Hertogenbosch"
cap label var NLSLD "Sliedrecht"
cap label var NLSLU "Sluiskil"
cap label var NLSNK "Sneek"
cap label var NLSOM "Someren"
cap label var NLSON "Son"
cap label var NLSPI "Spijkenisse"
cap label var NLSTE "Steenbergen"
cap label var NLSDN "Steenderen"
cap label var NLSTW "Steenwijk"
cap label var NLSTI "Stein"
cap label var NLTRJ "Strijen"
cap label var NLSWM "Swalmen"
cap label var NLTNZ "Terneuzen"
cap label var NLWTE "Terschelling"
cap label var NLTEX "Texel"
cap label var NLTHO "Tholen"
cap label var NLTIE "Tiel"
cap label var NLTLB "Tilburg"
cap label var NLUIT "Uithoorn"
cap label var NLURK "Urk"
cap label var NLUTC "Utrecht"
cap label var NLVLK "Valkenburg"
cap label var NLVDM "Veendam"
cap label var NLVER "Veere"
cap label var NLVEG "Veghel"
cap label var NLVEL "Velzen"
cap label var NLVEN "Venlo"
cap label var NLVAN "Vianen"
cap label var NLVLA "Vlaardingen"
cap label var NLVLL "Vlieland"
cap label var NLVLI "Vlissingen"
cap label var NLVOB "Voorburg"
cap label var NLVOS "Voorschoten"
cap label var NLWLK "Waalwijk"
cap label var NLWAD "Waddinxveen"
cap label var NLWGW "Wageningen"
cap label var NLWRM "Warmond"
cap label var NLWRT "Weert"
cap label var NLWSP "Weesp"
cap label var NLWKD "Werkendam"
cap label var NLWRG "Wieringen"
cap label var NLWCH "Wijchen"
cap label var NLWWR "Wijhe"
cap label var NLWBD "Wijk bij Duurstede"
cap label var NLWSC "Winschoten"
cap label var NLWNS "Winsum"
cap label var NLWOR "Woerden"
cap label var NLWCM "Woudrichem"
cap label var NLZAA "Zaandam"
cap label var NLZLB "Zaltbommel"
cap label var NLZEW "Zeewolde"
cap label var NLZVB "Zevenbergen"
cap label var NLZUL "Zuidland"
cap label var NLZUT "Zutphen"
cap label var NLZWS "Zwartsluis"
cap label var NLZWI "Zwijndrecht"
cap label var NLZWO "Zwolle"
cap label var NL888 "Netherlands - other ports"
cap label var ATENA "Enns"
cap label var ATKAN "Krems an der Donau"
cap label var ATKRE "Krems"
cap label var ATLNZ "Linz"
cap label var ATVIE "Wien"
cap label var ATA01 "Austria - Danube East area"
cap label var ATA02 "Austria - Danube Middle area"
cap label var ATA03 "Austria - Danube West area"
cap label var AT888 "Austria - other ports"
cap label var PLBEK "Bielinek"
cap label var PLBZG "Bydgoszcz"
cap label var PLCGA "Cigacice"
cap label var PLELB "Elblag"
cap label var PLGDN "Gdansk"
cap label var PLGDY "Gdynia"
cap label var PLGWC "Gliwice"
cap label var PLGLW "Glogów"
cap label var PLKEK "Kedzierzyn-Kozle"
cap label var PLKZY "Kostrzyn"
cap label var PLKRK "Kraków"
cap label var PLOPO "Opole"
cap label var PLPLO "Plock"
cap label var PLPLC "Police"
cap label var PLSMA "Sandomierz"
cap label var PLSPA "Stepnica"
cap label var PLSWI "Swinoujscie"
cap label var PLSZZ "Szczecin"
cap label var PLURD "Urad"
cap label var PLWLI "Wolin"
cap label var PLWRO "Wroclaw"
cap label var ROBAB "Basarabi"
cap label var ROBCT "Bechet"
cap label var ROBRA "Braila"
cap label var ROCAF "Calafat"
cap label var ROCAS "Calarasi"
cap label var ROCEV "Cernavoda"
cap label var ROCHL "Chilia Veche "
cap label var ROCHI "Chiselet"
cap label var ROCND "Constanta"
cap label var ROCOB "Corabia"
cap label var RODTS "Drobeta-Turnu Severin "
cap label var ROFET "Fetesti"
cap label var ROGAL "Galati"
cap label var ROGRG "Giurgiu"
cap label var RORVA "Hârsova"
cap label var ROISC "Isaccea"
cap label var ROLUM "Luminita"
cap label var ROMAC "Macin"
cap label var ROMAH "Mahmudia"
cap label var ROMED "Medgidia"
cap label var ROMID "Midia"
cap label var ROMOV "Moldova Veche"
cap label var ROPAL "Poarta Alba"
cap label var ROOLT "Oltenita"
cap label var ROORV "Orsova"
cap label var ROOVI "Ovidiu"
cap label var ROSUL "Sulina"
cap label var ROTCE "Tulcea"
cap label var ROTRC "Turcoaia"
cap label var ROTUM "Turnu Magurele"
cap label var ROZIC "Zimnicea"
cap label var ROA01 "Braila area"
cap label var ROA02 "Calarasi area"
cap label var ROA03 "Cernavoda area"
cap label var ROA04 "Danube Delta area"
cap label var ROA05 "Fetesti area"
cap label var ROA06 "Galati area"
cap label var ROA07 "Giurgiu area"
cap label var ROA08 "Hârsova area"
cap label var ROA09 "Macin area"
cap label var SKBAB "Bratislava"
cap label var SK001 "Kližská Nemá"
cap label var SKKNA "Komárno"
cap label var SKSRA "Štúrovo"
cap label var SK888 "Slovakia - other ports"
cap label var FIAHK "Ahkiolahti"
cap label var FIENK "Savonranta"
cap label var FIIIS "Iisalmi"
cap label var FIIMA "Imatra"
cap label var FIJOE "Joensuu"
cap label var FIJOU "Joutseno"
cap label var FIJUU "Juuka"
cap label var FIKUO "Kuopio"
cap label var FILPP "Lappeenranta (Villmanstrand)"
cap label var FINUR "Nurmes"
cap label var FIRIS "Ristiina"
cap label var FISAI "Saimaa Muut"
cap label var FIVRK "Varkaus"
