cap label var S1 "Total economy"
cap label var S11 "Non-financial corporations"
cap label var S121 "Central Bank"
cap label var S12T "Monetary Financial Institutions (MFI) other than central bank"
cap label var S122 "Deposit-taking corporations except the central bank"
cap label var S123 "Money market funds"
cap label var S124 "Non-MMF investment funds"
cap label var S13 "General Government"
cap label var S1P "Other sectors than MFIs and general government"
cap label var S12M "Financial corporations other than MFIs"
cap label var S1V "Non-financial corporations, households and non-profit institutions serving households"
cap label var S1M "Households and non-profit institutions serving households"
cap label var S1A "Affiliates"
cap label var S1W "Other sectors than General Government"
cap label var S1Z "Sectors other than deposit-taking corporations and general government"
cap label var S1X "Monetary authorities"
cap label var S12R "Other financial corporations"
cap label var S1N "Not sectorised"
cap label var S12K "Monetary financial institutions (MFI)"
cap label var S12Q "Insurance corporations and pension funds"
cap label var S12O "Other financial institutions"
