cap label var INST_NAT "National institutions"
cap label var PARL_NAT "National parliament"
cap label var GOV_NAT "National government"
cap label var ORG_INTL "International Organizations"
cap label var EUI "Institutions and bodies of the European Union"
cap label var EUI_X_EAI "EU institutions except the institutions of the euro area (aggregate changing according to the context)"
cap label var EUI_X_ECB "EU institutions except the ECB"
cap label var PARL "European Parliament"
cap label var COUNCIL "European Council"
cap label var CONS "Council of the European Union"
cap label var COMM "European Commission"
cap label var ESTAT "Eurostat"
cap label var CURIA "Court of Justice of the European Union"
cap label var ECB "European Central Bank (ECB)"
cap label var ECA "European Court of Auditors"
cap label var EESC "European Economic and Social Committee (EESC)"
cap label var COR "European Committee of the Regions (CoR)"
cap label var EIB "European Investment Bank (EIB)"
cap label var EIF "European Investment Fund"
cap label var ESM "European Stability Mechanism"
cap label var EFSF "European Financial Stability Facility"
cap label var EDF "European Development Fund"
cap label var SRB "Single Resolution Board (SRB)"
cap label var EU_BDG "All EU institutions financed via the EU Budget"
cap label var EUB_MNR "Other small EU institutions financed via the EU Budget"
cap label var EUB_OTH "Other EU institutions financed via the EU Budget"
cap label var EUI_NBDG "EU institutions not financed via the EU Budget"
cap label var ECSC "European Coal and Steel Community"
cap label var EMI "European Monetary Institute"
cap label var EMCF "European Monetary Cooperation Fund"
cap label var EURATOM "European Atomic Energy Community"
cap label var UNO "United Nations Organization"
cap label var UNICEF "United Nations Children's Fund (UNICEF)"
cap label var UNHCR "United Nations High Commissioner for Refugees, Office of the (UNHCR)"
cap label var UNRWA "United Nations Relief and Works Agency for Palestine Refugees in the Near East (UNRWA)"
cap label var ILO "International Labour Organization (ILO)"
cap label var FAO "Food and Agricultural Organization (FAO)"
cap label var UNESCO "United Nations Educational, Scientific and Cultural Organization (UNESCO)"
cap label var WHO "World Health Organization (WHO)"
cap label var IBRD "International Bank for Reconstruction and Development"
cap label var IDA "International Development Association"
cap label var IFC "International Finance Corporation (IFC)"
cap label var MIGA "Multilateral Investment Guarantee Agency (MIGA)"
cap label var IMF "International Monetary Fund"
cap label var ITU "International Telecommunication Union (ITU)"
cap label var IFAD "International Fund for Agricultural Development (IFAD)"
cap label var WTO "World Trade Organization"
cap label var IAEA "International Atomic Energy Agency (IAEA)"
cap label var UNO_OTH "United Nations Organization except IMF, WTO, IBRD, IDA"
cap label var ORG_OTH "Other International Organizations"
cap label var ACP "African, Caribbean and Pacific Group of States, signatories of the Partnership Agreement"
cap label var ACP_AFR "African ACP states"
cap label var ACP_CRB "Caribbean ACP states"
cap label var ACP_PAC "Pacific ACP states"
cap label var AFDB "African Development Bank"
cap label var ALA "Partner Countries in Asia and Latin America"
cap label var APEC "Asia-Pacific Economic Cooperation"
cap label var ASDB "Asian Development Bank"
cap label var ASEAN "Association of Southeast Asian Nations"
cap label var BIS "Bank for International Settlements"
cap label var BRIC "BRIC countries"
cap label var BRICS "BRICS countries"
cap label var CAN "Andean Community of Nations"
cap label var CARICOM "Caribbean Community"
cap label var CEMAC "Central African Economic and Monetary Community"
cap label var COMESA "Common Market for Eastern and Southern Africa"
cap label var DAC "Development assistance committee (DAC)"
cap label var EASA "European Aviation Safety Agency (EASA)"
cap label var NEASA "Non-EASA member countries"
cap label var EBRD "European Bank for Reconstruction and Development"
cap label var ECCAS "Economic Community of Central African States"
cap label var ECOWAS "Economic Community of West African States"
cap label var EHEA "European Higher Education Area (Bologna Process)"
cap label var ESA "European Space Agency"
cap label var EURMED "Mediterranean countries in the Euro-Mediterranean Partnership"
cap label var FEMIP "Facility for Euro-Mediterranean Investment and Partnership"
cap label var FZ "Franc Zone"
cap label var G20 "Group of Twenty"
cap label var G20_X_EU27_2020 "Group of Twenty except the EU27 countries (from 2020)"
cap label var IDB "Inter-American Development Bank"
cap label var IF "Investment Facility"
cap label var MACR "Mashrek"
cap label var MAGR "Maghreb"
cap label var MED "Mediterranean Basin Countries"
cap label var MED_X_HR "Mediterranean Basin Countries except Croatia"
cap label var MERCOSUR "Southern Common Market"
cap label var NAFTA "North American Free Trade Agreement"
cap label var NIB "Nordic Investment Bank"
cap label var ODA "Countries and territories receiving Official Development Assistance"
cap label var OECD "Organisation for Economic Co-operation and Development (OECD)"
cap label var OECD34 "Organisation for Economic Co-operation and Development (OECD - 34 countries)"
cap label var OECD_NEU "OECD non-EU countries"
cap label var NOECD "Non-OECD countries"
cap label var OPEC "Organization of Petroleum Exporting Countries (OPEC)"
cap label var OPEC12 "Organization of Petroleum Exporting Countries (OPEC - 12 countries)"
cap label var PALOP "Portuguese-speaking African Countries"
cap label var SADC "Southern African Development Community"
cap label var SNTL_EU27_2020 "Supranational organizations based in EU27 (from 2020)"
cap label var SNTL_OTH_EU27_2020 "Other supranational organizations based in EU27 (from 2020)"
cap label var SNTL_EFTA "Supranational organizations based in EFTA countries"
cap label var SNTL_UK "Supranational organizations based in the United Kingdom"
cap label var UEMOA "West African Economic and Monetary Union"
cap label var USMCA "United States-Mexico-Canada Agreement (USMCA)"
cap label var ORG_NEUR "Non European International Organizations"
cap label var OTH "Others"
cap label var NAL "Not allocated"
cap label var NAP "Not applicable"
cap label var NRP "No response"
cap label var NSP "Not specified"
cap label var UNK "Unknown"
