cap label var TOTAL "Total"
cap label var _1 "1 vessel"
cap label var _2_3 "2 or 3 vessels"
cap label var _4_5 "4 or 5 vessels"
cap label var _6_9 "From 6 to 9 vessels"
cap label var _10_19 "From 10 to 19 vessels"
cap label var GE20 "20 vessels or more"
