cap label var TOTAL "Total"
cap label var RDEV15 "Advisory services, farm management and farm relief services (article 15)"
cap label var RDEV16 "Quality schemes for agricultural products, and foodstuffs (article 16)"
cap label var RDEV17 "Investment in physical assets (article 17)"
cap label var RDEV18 "Restoring agricultural production potential damaged by natural disasters and catastrophic events and introduction of appropriate prevention actions (article 18)"
cap label var RDEV19 "Farm and business development (article 19)"
cap label var RDEV19A1 "Farm and business development - business start-up support for young farmers (article 19A1)"
cap label var RDEV19A3 "Farm and business development - business start-up support for development of micro- and small- enterprises and natural persons in rural areas (article 19A3)"
cap label var RDEV21 "Investments in forest area development and improvement of the viability of forests (article 21)"
cap label var RDEV21A "Afforestation and creation of woodland (article 21A)"
cap label var RDEV21B "Establishment of agroforestry systems (article 21B)"
cap label var RDEV21C "Prevention and restoration of damage to forests from forest fires, natural disasters and catastrophic events, including pest and disease outbreaks, and climate related threats (article 21C)"
cap label var RDEV21D "Investments improving the resilience and environmental value as well as the mitigation potential of forest ecosystems (article 21D)"
cap label var RDEV21E "Investments in forestry technologies and in the processing, the mobilising and the marketing of forest products (article 21E)"
cap label var RDEV28 "Agri-environment-climate (article 28)"
cap label var RDEV29 "Organic farming (article 29)"
cap label var RDEV30 "Natura 2000 and water framework directive payments (article 30)"
cap label var RDEV31 "Payments to areas facing natural or other specific constraints (article 31)"
cap label var RDEV33 "Animal welfare (article 33)"
cap label var RDEV34 "Forest-environmental and climate services and forest conservation (article 34)"
cap label var RDEV36 "Risk management (article 36)"
cap label var RDEV40 "Financing of complementary national direct payments for Croatia (article 40)"
