cap label var TOTAL "Total"
cap label var CMI00 "No information"
cap label var CMI10 "Contact with electrical voltage, temperature, hazardous substances - not specified"
cap label var CMI20 "Drowned, buried, enveloped - not specified"
cap label var CMI30 "Horizontal or vertical impact with or against a stationary object (the victim is in motion) - not specified"
cap label var CMI40 "Struck by object in motion, collision with - not specified"
cap label var CMI50 "Contact with sharp, pointed, rough, coarse Material Agent - not specified"
cap label var CMI60 "Trapped, crushed, etc. - not specified"
cap label var CMI70 "Physical or mental stress - not specified"
cap label var CMI80 "Bite, kick, etc. (animal or human) - not specified"
cap label var CMI90 "Other Contacts - modes of Injury not listed in this classification"
