cap label var _001 "Total number of holdings"
cap label var _002 "Total Agricultural area (AA)"
cap label var _003 "Total standard gross margin (ESU)"
cap label var _004 "Number of holdings in less favoured area"
cap label var _005 "Agricultural area in less favoured area"
cap label var _006 "Number of holdings in mountain area"
cap label var _007 "Agricultural area in mountain area"
cap label var _008 "Number of holdings with less than 5 ha AA"
cap label var _009 "Number of holdings with 5 to 10 ha AA"
cap label var _010 "Number of holdings with 10 to 20 ha AA"
cap label var _011 "Number of holdings with 20 to 30 ha AA"
cap label var _012 "Number of holdings with 30 to 50 ha AA"
cap label var _013 "Number of holdings with >=50 ha AA"
cap label var _014 "Total AA (in ha) of holdings with less than 5 ha AA"
cap label var _015 "Total AA (in ha) of holdings with 5 to 10 ha AA"
cap label var _016 "Total AA (in ha) of holdings with 10 to 20 ha AA"
cap label var _017 "Total AA (in ha) of holdings with 20 to 30 ha AA"
cap label var _018 "Total AA (in ha) of holdings with 30 to 50 ha AA"
cap label var _019 "Total AA (in ha) of holdings with >=50 ha AA"
cap label var _020 "Number of holdings with less than 2 ESU"
cap label var _021 "Number of holdings with 2 to 4 ESU"
cap label var _022 "Number of holdings with 4 to 8 ESU"
cap label var _023 "Number of holdings with 8 to 16 ESU"
cap label var _024 "Number of holdings with 16 to 40 ESU"
cap label var _025 "Number of holdings with 40 to 100 ESU"
cap label var _026 "Number of holdings with 100 ESU and over"
cap label var _027 "Total AA of holdings with less than 2 ESU"
cap label var _028 "Total AA of holdings with 2 to 4 ESU"
cap label var _029 "Total AA of holdings with 4 to 8 ESU"
cap label var _030 "Total AA of holdings with 8 to 16 ESU"
cap label var _031 "Total AA of holdings with 16 to 40 ESU"
cap label var _032 "Total AA of holdings with 40 to 100 ESU"
cap label var _033 "Total AA of holdings with 100 ESU and over"
cap label var _034 "AA owner farmed"
cap label var _035 "AA tenant farmed"
cap label var _036 "AA share farmed or in other modes of tenure"
cap label var _037 "Total area (D,E,F,G,H) in ha"
cap label var _038 "Number of holdings with arable land (D)"
cap label var _039 "Arable land (in ha)"
cap label var _040 "AA of holdings with arable land (in ha)"
cap label var _041 "Number of holdings with cereals (D/01-D/08)"
cap label var _042 "Cereals (D/01-D/08) (in ha)"
cap label var _043 "Number of holdings with common wheat and spelt (D/01)"
cap label var _044 "Common wheat and spelt (in ha)"
cap label var _045 "Number of holdings with durum wheat (D/02)"
cap label var _046 "Durum wheat (D/02) (in ha)"
cap label var _047 "Number of holdings with rye (D/03)"
cap label var _048 "Rye (D/03) (in ha)"
cap label var _049 "Number of holdings with barley (D/04)"
cap label var _050 "Barley (D/04) (in ha)"
cap label var _051 "Number of holdings with oats (D/05)"
cap label var _052 "Oats (D/05) (in ha)"
cap label var _053 "Number of holdings with grain maize (D/06)"
cap label var _054 "Grain maize (D/06) (in ha)"
cap label var _055 "Number of holdings with rice (D/07)"
cap label var _056 "Rice (D/07) (in ha)"
cap label var _057 "Number of holdings with other cereal (D/08)"
cap label var _058 "Other cereal (D/08) (in ha)"
cap label var _059 "Number of holdings with dried vegetables (D/09)"
cap label var _060 "Dried vegetables (D/09 (in ha)"
cap label var _061 "Number of holdings with root crops (D/10-D/12)"
cap label var _062 "Root crops (D/10-D/12) (in ha)"
cap label var _063 "Number of holdings with potatoes (D/10)"
cap label var _064 "Potatoes (D/10) (in ha)"
cap label var _065 "Number of holdings with sugar-beet (D/11)"
cap label var _066 "Sugar-beet (D/11) (in ha)"
cap label var _067 "Number of holdings with fodder roots and brassica (D/12)"
cap label var _068 "fodder roots and brassica (D/12) (in ha)"
cap label var _069 "Number of holdings with industrial plants (D/13)"
cap label var _070 "Industrial plants (D/13) (in ha)"
cap label var _071 "Number of holdings with fresh vegetables, melons and strawberries (D/14 + D/15)"
cap label var _072 "Fresh vegetables, melons and strawberries (D/14 + D/15) (in ha)"
cap label var _073 "Number of holdings with flowers and ornamental plants (D/16 + D/17)"
cap label var _074 "flowers and ornamental plants (D/16 + D/17) (in ha)"
cap label var _075 "Number of holdings with forage plants (D/18)"
cap label var _076 "Forage plants (D/18 (in ha)"
cap label var _077 "Number of holdings with permanent pasture and meadows (F)"
cap label var _078 "permanent pasture and meadows (F) (in ha)"
cap label var _079 "Number of holdings with permanent crops (G)"
cap label var _080 "Permanent crops (G) (in ha)"
cap label var _081 "Number of holdings with vineyards (G/04)"
cap label var _082 "Vineyards (G/04) (in ha)"
cap label var _083 "Number of holdings with woodland (H/02)"
cap label var _084 "Woodland (H/02) (in ha)"
cap label var _085 "Total number of holdings with livestock (J/01-J/19)"
cap label var _086 "Number of holdings with bovine animals (J/02-J/08)"
cap label var _087 "Bovine animals (J/02-J/08), number"
cap label var _088 "Number of holdings with bovine animals under 1 year old (J/02)"
cap label var _089 "Bovine animals under 1 year old (J/02), number"
cap label var _090 "Number of holdings with bovine animals 1 year or over but under 2 years, male (J/03)"
cap label var _091 "Bovine animals 1 year or over but under 2 years, male (J/03), number"
cap label var _092 "Number of holdings with bovine animals 1 year or over but under 2 years, female (J/04)"
cap label var _093 "Bovine animals 1 year or over but under 2 years, female (J/04), number"
cap label var _094 "Number of holdings with bovine animals 2 year old and over, male (J/05)"
cap label var _095 "Bovine animals 2 year old and over, male (J/05), number"
cap label var _096 "Number of holdings with bovine animals 2 year old and over, heifers (J/06)"
cap label var _097 "Bovine animals 2 year old and over, heifers (J/06)"
cap label var _098 "Number of holdings with dairy cows (J/07)"
cap label var _099 "Dairy cows (J/07), number"
cap label var _100 "Number of holdings with other cows (J/08)"
cap label var _101 "Other cows (J/08), number"
cap label var _102 "Number of holdings with sheep (J/09)"
cap label var _103 "Sheep (J/09), number"
cap label var _104 "Number of holdings with goats (J/10)"
cap label var _105 "Goats (J/10), number"
cap label var _106 "Number of holdings with pigs (J/11-J/13)"
cap label var _107 "Pigs (J/11-J/13), number"
cap label var _108 "Number of holdings with poultry (J/14-J/16)"
cap label var _109 "Poultry (J/14-J/16), number"
cap label var _110 "Total labour force (L/01-L/06) in AWU"
cap label var _111 "Labour force excluding non-family labour force employed on a non-regular basis (L/01-L/04) (persons)"
cap label var _112 "Labour force excluding non-family labour force employed on a non-regular basis (L/01-L/04), in AWU"
cap label var _113 "Total family labour force (L/01-L/03) (person)"
cap label var _114 "Total family labour force (L/01-L/03) in AWU"
cap label var _115 "Total family labour force full-time employed (L/01-L/03) (person)"
cap label var _116 "Holder's being a natural person (persons)"
cap label var _117 "Holder's being a natural person (AWU)"
cap label var _118 "Holder's being a natural person: age < 35 years (persons)"
cap label var _119 "Holder's being a natural person: age < 35 years (AWU)"
cap label var _120 "Holder's being a natural person: age 35 to 44 years (persons)"
cap label var _121 "Holder's being a natural person: age 35 to 44 years (AWU)"
cap label var _122 "Holder's being a natural person: age 45 to 54 years (persons)"
cap label var _123 "Holder's being a natural person: age 45 to 54 years (AWU)"
cap label var _124 "Holder's being a natural person: age 55 to 64 years (persons)"
cap label var _125 "Holder's being a natural person: age 55 to 64 years (AWU)"
cap label var _126 "Holder's being a natural person: age 65 years and over (persons)"
cap label var _127 "Holder's being a natural person: age 65 years and over(AWU)"
cap label var _128 "Holder's being a natural person: sex = male (persons)"
cap label var _129 "Holder's being a natural person: sex = female (persons)"
cap label var _130 "Holder's being a natural person: work time > 0 to < 25% (persons)"
cap label var _131 "Holder's being a natural person: work time > 0 to < 25% (AWU)"
cap label var _132 "Holder's being a natural person: work time > 25 to < 50% (persons)"
cap label var _133 "Holder's being a natural person: work time > 25 to < 50% (AWU)"
cap label var _134 "Holder's being a natural person: work time > 50 to < 75% (persons)"
cap label var _135 "Holder's being a natural person: work time > 50 to < 75% (AWU)"
cap label var _136 "Holder's being a natural person: work time > 75 to < 100% (persons)"
cap label var _137 "Holder's being a natural person: work time > 75 to < 100% (AWU)"
cap label var _138 "Holder's being a natural person: work time 100% (persons)"
cap label var _139 "Holder's being a natural person: work time 100% (AWU)"
cap label var _140 "Number of holdings with: Specialist field crops"
cap label var _141 "Number of holdings with: Specialist horticulture"
cap label var _142 "Number of holdings with: Specialist permanent crops"
cap label var _143 "Number of holdings with: Specialist grazing livestock"
cap label var _144 "Number of holdings with: Specialist granivores"
cap label var _145 "Number of holdings with: Mixed cropping"
cap label var _146 "Number of holdings with: Mixed livestock holdings"
cap label var _147 "Number of holdings with: Mixed crops - livestock"
cap label var _148 "Total AA of holdings with: Specialist field crops"
cap label var _149 "Total AA of holdings with: Specialist horticulture"
cap label var _150 "Total AA of holdings with: Specialist permanent crops"
cap label var _151 "Total AA of holdings with: Specialist grazing livestock"
cap label var _152 "Total AA of holdings with: Specialist granivores"
cap label var _153 "Total AA of holdings with: Mixed cropping"
cap label var _154 "Total AA of holdings with: Mixed livestock holdings"
cap label var _155 "Total AA of holdings with: Mixed crops - livestock"
