cap label var B_MD40 "Below 40% of median equivalised income"
cap label var A_MD40 "Above 40% of median equivalised income"
cap label var B_MD50 "Below 50% of median equivalised income"
cap label var A_MD50 "Above 50% of median equivalised income"
cap label var B_MD60 "Below 60% of median equivalised income"
cap label var A_MD60 "Above 60% of median equivalised income"
cap label var B_MD70 "Below 70% of median equivalised income"
cap label var A_MD70 "Above 70% of median equivalised income"
cap label var B_M40 "Below 40% of mean equivalised income"
cap label var A_M40 "Above 40% of mean equivalised income"
cap label var B_M50 "Below 50% of mean equivalised income"
cap label var A_M50 "Above 50% of mean equivalised income"
cap label var B_M60 "Below 60% of mean equivalised income"
cap label var A_M60 "Above 60% of mean equivalised income"
cap label var Q0_20 "First quintile of equivalised income"
cap label var Q20_40 "Second quintile of equivalised income"
cap label var Q40_60 "Third quintile of equivalised income"
cap label var Q60_80 "Fourth quintile of equivalised income"
cap label var Q80_100 "Fifth quintile of equivalised income"
cap label var TOTAL "Total"
