cap label var CLC1 "Artificial surfaces"
cap label var CLC11 "Urban fabric"
cap label var CLC111 "Continuous urban fabric"
cap label var CLC112 "Discontinuous urban fabric"
cap label var CLC12 "Industrial, commercial and transport units"
cap label var CLC121 "Industrial or commercial units and public facilities"
cap label var CLC122 "Road and rail networks and associated land"
cap label var CLC123 "Port areas"
cap label var CLC124 "Airports"
cap label var CLC13 "Mine, dump and construction sites"
cap label var CLC131 "Mineral extraction sites"
cap label var CLC132 "Dump sites"
cap label var CLC133 "Construction sites"
cap label var CLC14 "Artificial, non-agricultural vegetated areas"
cap label var CLC141 "Green urban areas"
cap label var CLC142 "Sport and leisure facilities"
cap label var CLC2 "Agricultural areas"
cap label var CLC21 "Arable land"
cap label var CLC211 "Non-irrigated arable land"
cap label var CLC212 "Permanently irrigated arable land"
cap label var CLC213 "Rice fields"
cap label var CLC22 "Permanent crops"
cap label var CLC221 "Vineyards"
cap label var CLC222 "Fruit trees and berry plantations"
cap label var CLC223 "Olive groves"
cap label var CLC23 "Pastures"
cap label var CLC231 "Pastures, meadows and other permanent grasslands under agricultural use"
cap label var CLC24 "Heterogeneous agricultural areas"
cap label var CLC241 "Annual crops associated with permanent crops"
cap label var CLC242 "Complex cultivation patterns"
cap label var CLC243 "Land principally occupied by agriculture, with significant areas of natural vegetation"
cap label var CLC244 "Agro-forestry areas"
cap label var CLC3 "Forest and semi-natural areas"
cap label var CLC31 "Forests"
cap label var CLC311 "Broad-leaved forest"
cap label var CLC312 "Coniferous forest"
cap label var CLC313 "Mixed forest"
cap label var CLC32 "Scrub and/or herbaceous vegetation associations"
cap label var CLC321 "Natural grassland"
cap label var CLC322 "Moors and heathland"
cap label var CLC323 "Sclerophyllous vegetation"
cap label var CLC324 "Transitional woodland/shrub"
cap label var CLC33 "Open spaces with little or no vegetation"
cap label var CLC331 "Beaches, dunes, and sand plains"
cap label var CLC332 "Bare rock"
cap label var CLC333 "Sparsely vegetated areas"
cap label var CLC334 "Burnt areas"
cap label var CLC335 "Glaciers and perpetual snow"
cap label var CLC4 "Wetlands"
cap label var CLC41 "Inland wetlands"
cap label var CLC411 "Inland marshes"
cap label var CLC412 "Peatbogs"
cap label var CLC42 "Coastal wetlands"
cap label var CLC421 "Coastal salt marshes"
cap label var CLC422 "Salines"
cap label var CLC423 "Intertidal flats"
cap label var CLC5 "Water bodies"
cap label var CLC51 "Inland waters"
cap label var CLC511 "Water courses"
cap label var CLC512 "Water bodies"
cap label var CLC52 "Marine waters"
cap label var CLC521 "Coastal lagoons"
cap label var CLC522 "Estuaries"
cap label var CLC523 "Sea and ocean"
cap label var CLC2_3X331_332_335 "Agricultural areas, forest and semi natural areas (excluding beaches, dunes, sand plains, bare rock and glaciers and perpetual snow)"
cap label var CLC2_321 "Agricultural areas and natural grassland"
cap label var CLC2X23 "Agricultural areas (excluding pastures)"
cap label var CLC23_321 "Pastures and natural grassland"
