cap label var _6000 "Input total (I+II)"
cap label var _7000 "Total, goods and services currently consumed in agriculture"
cap label var _7100 "Seeds"
cap label var _7490 "Animals for rearing and production"
cap label var _7500 "Energy and lubricants"
cap label var _7520 "Fuels for heating"
cap label var _7530 "Motor fuels"
cap label var _7540 "Electricity"
cap label var _7550 "Lubricants"
cap label var _7600 "Fertilizers, soil improvers"
cap label var _7620 "Straight fertilizers"
cap label var _7630 "Nitrogenous fertilizers"
cap label var _7650 "Phosphatic fertilizers"
cap label var _7680 "Potassic fertilizers"
cap label var _7700 "Compound fertilizers"
cap label var _7710 "NP fertilizers"
cap label var _7720 "PK fertilizers"
cap label var _7740 "NPK fertilizers"
cap label var _7850 "Other fertilizers, soil improvers"
cap label var _7900 "Plant protection products"
cap label var _7910 "Fungicides"
cap label var _7930 "Insecticides"
cap label var _7950 "Herbicides"
cap label var _7970 "Other protection products"
cap label var _8000 "Animal feedingstuffs"
cap label var _8010 "Straight feedingstuffs"
cap label var _8030 "Cereals and milling by-products"
cap label var _8070 "Oil-cakes"
cap label var _8100 "Products of animal origin"
cap label var _8130 "Other straight feedingstuffs"
cap label var _8210 "Compound feedingstuffs"
cap label var _8230 "Compound feedingstuffs for calves"
cap label var _8240 "Compound feedingstuffs for cattle (excluding calves)"
cap label var _8280 "Compound feedingstuffs for pigs"
cap label var _8300 "Compound feedingstuffs for poultry"
cap label var _8350 "Other compound feedingstuffs"
cap label var _8410 "Material and small tools"
cap label var _8510 "Maintenance and repair of plant"
cap label var _8610 "Maintenance and repair of agricultural buildings and other buildings"
cap label var _8730 "Veterinary services"
cap label var _8790 "General expenses"
cap label var _9000 "Total goods and services contributing to agricultural investment"
cap label var _9300 "Machinery and other equipment"
cap label var _9310 "Rotovator and other 2 wheel equipment"
cap label var _9320 "Machinery and plant for cultivation"
cap label var _9360 "Machinery and plant for harvesting"
cap label var _9400 "Farm machinery and installations"
cap label var _9410 "Machinery and installations for crop production"
cap label var _9450 "Machinery and installations for animal production"
cap label var _9480 "Other farm machinery and installations"
cap label var _9510 "Tractors"
cap label var _9550 "Other vehicles"
cap label var _9600 "Buildings"
cap label var _9610 "Farm buildings"
cap label var _9700 "Engineering and soil improvement operations"
