cap label var TOTAL "Total"
cap label var GEN "Generally possible"
cap label var RAR "Rarely possible"
cap label var PER_ARR "Person can decide under flexible working time arrangements"
cap label var PER_FUL "Person can fully decide"
cap label var PER_RSTR "Person can decide with certain restrictions"
cap label var EMPL_MAIN "Employer or organisation mainly decides"
cap label var EMPL_CL "Employer, organisation, or client(s) decide"
cap label var OTH_DEC "Others decide"
cap label var NONE "No working time flexibility"
cap label var NAP "Not applicable"
cap label var NRP "No response"
