cap label var TOTAL "Total"
cap label var SIN "Single persons (never in legal union)"
cap label var LUN "Persons in legal union (married or in registered partnership)"
cap label var MAR "Married persons"
cap label var MARO "Persons in an opposite-sex married couple"
cap label var MARS "Persons in an same-sex married couple"
cap label var REP "Persons in registered partnership"
cap label var REPO "Persons in an opposite-sex registered partnership"
cap label var REPS "Persons in a same-sex registered partnership"
cap label var MAR_REP "Married persons or in registered partnership"
cap label var MARO_REPO "Persons in an opposite-sex married couple or registered partnership"
cap label var MARS_REPS "Persons in an same-sex married couple or registered partnership"
cap label var CSU "Persons in consensual union"
cap label var DTHLUN "Persons whose legal union ended with the death of the partner"
cap label var WID "Widowed persons"
cap label var DTHREP "Persons whose registered partnership ended with the death of the partner"
cap label var WID_DTHREP "Widowed persons or registered partnership ended with the death of the partner"
cap label var DISLUN "Persons whose legal union was legally dissolved"
cap label var DIV "Divorced persons"
cap label var DISREP "Persons whose registered partnership was legally dissolved"
cap label var DIV_DISREP "Divorced persons or registered partnership was legally dissolved"
cap label var SEP "Separated persons"
cap label var NLUN "Persons neither in registered partnership nor married"
cap label var ENDLUN "Persons whose legal union ended"
cap label var NMAR "Not married persons"
cap label var NLUN_NCSU "Persons neither in legal nor in consensual union"
cap label var UNK "Persons with unknown marital status"
cap label var NRP "No response"
