cap label var TOTAL "Total"
cap label var SELF "Self-employed persons"
cap label var CLIENT "Clients"
cap label var OTH "Others"
cap label var NAP "Not applicable"
cap label var NRP "No response"
