cap label var TOTAL "Total"
cap label var MCM_LT15 "Less than 15 microns"
cap label var MCM15_49 "From 15 to 49 microns"
cap label var MCM_LT50 "Less than 50 microns"
cap label var MCM_GE50 "50 microns or over"
