cap label var TOTAL "All types of co-operation"
cap label var PRV "Private business enterprises"
cap label var PRV_IN "Enterprises within the enterprise group"
cap label var PRV_OUT "Private business enterprise outside the enterprise group"
cap label var PRV_OUT_CN_PRV_RI "Consultants, commercial labs, private research institute"
cap label var PRV_RI "Private research institutes"
cap label var PRV_OUT_CN "Consultants or commercial labs"
cap label var PRV_OUT_SUPPL "Suppliers of equipment, materials, components or software"
cap label var CLCU "Clients or customers"
cap label var PRV_OUT_CLCU "Clients or customers from the private sector"
cap label var PRV_OUT_COMP "Competitors or other enterprises of the same sector"
cap label var PRV_OUT_OTH "Other private business enterprises outside the enterprise group"
cap label var UNIV_GOV_RI "Universities or other higher education institutions, government and public or private research institutes"
cap label var UNIV "Universities or other higher education institutions"
cap label var PUB "Public sector organisations"
cap label var PUB_GOV_RI "Government or public research institutes"
cap label var GOV_RI "Government, public or private research institutes"
cap label var PUB_CLCU "Clients or customers from the public sector"
cap label var IND_HH "Individual households"
cap label var NPO "Non-profit organisations"
cap label var NAT "National partner"
cap label var FOR "Foreign partner"
cap label var EU_EFTA "Partner in EU or EFTA countries"
cap label var NEU_NEFTA "Partner outside EU or EFTA countries"
cap label var EU_EFTA_CC_FOR "Partner in EU, EFTA or EU candidate countries (except a national partner)"
cap label var EU_EFTA_CC_NAT "Partner in EU, EFTA or EU candidate countries (including a national partner)"
cap label var EU_ONL "Partner only in the EU"
cap label var CN_IN "China or India"
cap label var US_OTH "United States and other countries"
cap label var US "United States"
cap label var COOP_RND "On R&D"
cap label var COOP_INN_XRND "On other innovation activities (excluding R&D)"
cap label var COOP_INNXRND "On other innovation activities (excluding R&D)"
cap label var COOP_OTH "On any other business activity"
cap label var APPL "Applicant"
cap label var INVT "Inventor"
cap label var OTH "Others"
