cap label var TOT_REF "Persons refused entry"
cap label var REF_LAND "Refused at the land border"
cap label var REF_SEA "Refused at the sea border"
cap label var REF_AIR "Refused at the air border"
cap label var TOTDECISION "Third country nationals, who are subject to an obligation to leave (article 7.1.a of Regulation 862/2007)"
cap label var TOT_RET "Total number of persons returned"
cap label var VOLUNT "Voluntary return"
cap label var ENFORCE "Enforced return"
cap label var ASSIST "Assisted return"
cap label var N_ASSIST "Non-assisted return"
cap label var RET_THRD "Persons returned to a third country"
cap label var EURA "Returned under EURA"
cap label var OTH_READM "Returned under other readmission agreement"
cap label var N_READM "Returned without existing a readmission agreement"
cap label var FOR_P_HHAB "Share of foreign citizens who have acquired citizenship"
cap label var NEU27_2020_P_HHAB "Share of non-EU27 citizens (from 2020) who have acquired citizenship"
cap label var NEU28_P_HHAB "Share of non-EU28 citizens (2013-2020) who have acquired citizenship"
cap label var NEU_P_HHAB "Share of non-EU citizens who have acquired citizenship"
cap label var EU_P_HHAB "Share of EU citizens who have acquired citizenship"
cap label var CITIZ "Country of Citizenship"
cap label var TRANSIT "Transit country"
cap label var OTH_THRD "Other third country"
cap label var OTH "Other"
cap label var UNK "Unknown"
