cap label var TOTAL "Total"
cap label var LEG_ADM "Legal or administrative"
cap label var CBT_NRLV "Cross border trade not relevant"
cap label var C41 "Cross border trade not relevant (products not exportable)"
cap label var E_COM_ABR "Establishing a commercial presence abroad"
cap label var C42 "Establishing a commercial presence abroad"
cap label var MV_STAF_TEMP "Movement of staff on a temporary basis"
cap label var C43 "Movement of personnel on a temporary basis"
cap label var TAX "Tax barriers"
cap label var C44 "Taxation issues"
cap label var INS_GAR "Insurance, guarantee systems and other barriers"
cap label var C45 "Insurance, guarantee systems, etc. issues"
cap label var LINTLSTD "Lack of international standards"
cap label var C46 "Lack of international standards for services"
cap label var DIF_IDF_CLABR "Difficulty in identifying potential clients abroad"
cap label var C47 "Difficulties in identifying potential clients abroad"
cap label var LANG_CLT "Language and culture"
cap label var C48 "Language and cultural barriers"
cap label var TAR_TRD "Tariffs and other trade barriers"
cap label var UNC_INTLSTD "Uncertainty of international standards"
cap label var CNC_SAL "Concerns of employees (including trade unions)"
cap label var CNC_VLPAT_IPR "Concern of violation of patents and/or intellectual property rights"
cap label var CNF_SOCVAL "Conflicting with social values of your enterprise (e.g. corporate social responsibility issues)"
cap label var DST_PRR "Distance to producers"
cap label var DST_CL "Distance to existing clients"
cap label var DIF_IDF_PROVABR "Difficulty in identifying suitable providers abroad"
cap label var CNC_SRCOP_BEN "Concerns of the sourcing operation exceeding expected benefits"
cap label var FIN "Financial barriers"
cap label var UNC_QUALPRD_ABR "Uncertainty of the quality of the products/services to be supplied abroad"
cap label var LMNG_KH "Lack of management resources and know-how"
cap label var LMGMT_KH "Lack of management resources and know-how"
cap label var MSSDOC_PRD "Missing documentation of own products and processes"
cap label var MOB "Mobility"
cap label var TRA "Transportation"
cap label var ACS_BLD "Accessing buildings"
cap label var EDUC_TNG "Education and training"
cap label var EMP "Employment"
cap label var U_INET "Using the internet"
cap label var SOC "Social contact"
cap label var LEIS "Leisure"
cap label var P_ESS "Paying for essentials"
cap label var PERC_DCRIM "Perceived discrimination"
cap label var PTP_LD1 "Participating in 1 life domain"
cap label var PTP_LD2_3 "Participating in 2 to 3 life domains"
cap label var PTP_LD_GE4 "Participating in 4 or more life domains"
cap label var LQCFOJ_OTH "Language skills, qualifications, citizenship, foreign origin, job and other barriers"
cap label var LLANG "Lack of language skills"
cap label var LREC_QLF "Lack of recognition of qualifications"
cap label var CTZ_RPRM "Citizenship or residence permit"
cap label var ORI_REL_SOC "Origin, religion or social background"
cap label var DCRIM_ORI_FOR "Discrimination due to foreign origin"
cap label var NSJOB_AVL "No suitable job available"
cap label var NVR_WRK "Never sought work or never worked"
cap label var LQLFLAB_ABR "Lack of qualified labour abroad"
cap label var ACS_FIN_OTH "Access to finance or other financial barriers"
cap label var LFIN "Lack of finance"
cap label var LFIN_IN "Lack of internal finance"
cap label var LFIN_EXT "Lack of external finance (credit or private equity)"
cap label var LFUND_IN "Lack of funds within the enterprise or group"
cap label var HCOST "High costs"
cap label var HCOST_ACS_NEWMKT "High costs of access to new markets"
cap label var HCOST_MT_REGL "High costs of meeting regulations"
cap label var LQLFSAL_IN "Lack of qualified employees within enterprise"
cap label var LCOLLPTN "Lack of collaboration partners"
cap label var DIF_SUB "Difficulties in obtaining public grants or subsidies"
cap label var MKTDM_UNC "Uncertain market demand"
cap label var MKTDM_LW "Low market demand"
cap label var HCOMP "High competition"
cap label var PRCCOMP_STR "Strong price competition"
cap label var INN_COMP "Innovations introduced by competitors"
cap label var MKTCOMP_LTL "Little market competition"
cap label var STRCOMP_PRDQUAL "Strong competition on product quality"
cap label var LINFO_TEC "Lack of information on technology"
cap label var LINFO_MKT "Lack of information on markets"
cap label var LGIDEA "Lack of good ideas"
cap label var MKT_EENT "Markets dominated by established enterprises"
cap label var NND "No need"
cap label var PREINN "Previous innovations"
cap label var NDM "No demand"
cap label var ABD_CNC "Abandoned at the concept stage"
cap label var ABD_BG "Abandoned after it began"
cap label var D_SRL "Seriously delayed"
cap label var NCMPG "No compelling barrier"
cap label var BRR_TL "Too large barriers"
cap label var BUR_REGL "Burden due to legislation/regulation"
cap label var UNC_REGL "Uncertainty due to legislation/regulation"
cap label var LCSI_EU_REGL "Lack of consistency across the EU in legislation/regulation"
cap label var LACS_KNOW "Lack of access to external knowledge"
cap label var DIFFPRIOR_IN "Different priorities within the enterprise"
cap label var BRR_GE1 "One or more barriers"
cap label var OUTSRC_LOG "Outsourced logistics to another enterprise"
cap label var REGL "Regulatory barriers"
cap label var TECH "Technical barriers"
cap label var WRKHR_LG "Long working hours"
cap label var DIF_WRKSCD "Unpredictable or difficult work schedules"
cap label var COM_LG "Long commute"
cap label var DMJOB "Demanding or exhausting job"
cap label var LSUPP_EMPL "Lack of support from employers and colleagues"
cap label var DIF_ACQ_RM_DOM "Difficulty in acquiring raw materials/intermediate products from suppliers domestically"
cap label var DIF_ACQ_RM_ABR "Difficulty in acquiring raw materials/intermediate products from suppliers abroad"
cap label var DIF_ACS_SERV_DOM "Difficulty accessing services from suppliers domestically"
cap label var DIF_ACS_SERV_ABR "Difficulty accessing services from suppliers abroad"
cap label var DIF_TRA_GD_BK_FCUS "Difficulty to transport goods produced in another country back to enterprise or to transport goods to final customers"
cap label var DIF_RECV_EXPT_ABR "Difficulty to receive experts or other professionals from abroad"
cap label var DIF_SEND_EXPT_ABR "Difficulty to send experts or other employees abroad"
cap label var CANC_ORD_DOM "Cancellation of orders or decline in incoming orders, from domestic customers"
cap label var CANC_ORD_ABR "Cancellation of orders or decline in incoming orders, from customers abroad"
cap label var CHG_SLS_CHAN "Change in sales channels"
cap label var COV19 "COVID-19 related concerns and issues"
cap label var OTH "Other"
cap label var OTHER "Other barriers"
cap label var NONE "None"
cap label var NAP "Not applicable"
cap label var NRP "No response"
cap label var UNK "Unknown"
