cap label var TOTAL "Total"
cap label var ACT "Persons in the labour force (former name: active persons)"
cap label var EMP_LFS "Total employment (resident population concept - LFS)"
cap label var EMP_CLT "Cultural employment"
cap label var UNE "Unemployment (ILO)"
cap label var UEMP "Underemployed part-time workers"
cap label var SEEK_NAV "Persons seeking work but not immediately available"
cap label var NSEE_AV "Persons available to work but not seeking"
cap label var LTU "Long-term unemployment"
cap label var VLTU "Very long-term unemployment"
cap label var JOBVAC "Number of job vacancies"
cap label var JOBOCC "Number of occupied jobs"
cap label var JOBRATE "Job vacancy rate"
cap label var CH_Q_Q "Job vacancy rate quarter on quarter change"
cap label var CH_Y_Y "Job vacancy rate year on year change"
cap label var SLACK "Labour market slack"
cap label var SC071 "Children aged 0-17 living in jobless households: share of persons aged 0-17 who are living in households where no-one is working"
cap label var SC072 "People aged 18-59 living in jobless households: share of persons aged 18-59 who are living in households where no-one works"
cap label var SC073 "Women aged 18-59 living in jobless households: share of women aged 18-59 who are living in households where no-one works"
cap label var SC074 "Men aged 18-59 living in jobless households: share of men aged 18-59 who are living in households where no-one works"
cap label var E_E "Transition employment - employment"
cap label var E_U "Transition employment - unemployment"
cap label var E_I "Transition employment -inactivity"
cap label var U_E "Transition unemployment - employment"
cap label var U_U "Transition unemployment - unemployment"
cap label var U_I "Transition unemployment - inactivity"
cap label var I_E "Transition inactive -employment"
cap label var I_U "Transition inactive - unemployment"
cap label var I_I "Transition inactive - inactive"
cap label var INAC "Persons outside the labour force"
cap label var WANTW "Not seeking or available, but wanting to work"
cap label var OTH "Others"
