cap label var S1P "Pension schemes (core and not core accounts)"
cap label var S12P "Private pension schemes"
cap label var S12PC "Private defined contribution schemes"
cap label var S12PB "Private defined benefit schemes"
cap label var S12PBI "Defined benefit schemes for general government employees classified in financial corporations"
cap label var S13PC "Defined contribution schemes of general government (core accounts)"
cap label var S13PBI "Defined benefit schemes for general government employees classified in general government (core accounts)"
cap label var S13PBX "Defined benefit schemes for general government employees classified in general government (not in core accounts)"
cap label var S13PS "Social security pension schemes (not in core accounts)"
cap label var S14R "Counterparts: resident households"
cap label var S14NR "Counterparts: non-resident households"
