cap label var CH "Chicks hatched"
cap label var EP "Eggs placed in incubation"
cap label var EI "Exports intra-EU"
cap label var ET "Exports - Total"
cap label var EX "Exports extra-EU"
cap label var II "Imports intra-EU"
cap label var IT "Imports - Total"
cap label var IX "Imports extra-EU"
cap label var CP "Chicks placed"
