cap label var TOTAL "Total"
cap label var VH_H "Very high or high"
cap label var VHIGH "Very high"
cap label var GRT_MOD_SOME "Great, moderate or some"
cap label var GRT "Great"
cap label var HIGH "High"
cap label var MOD "Moderate"
cap label var SOME "Some"
cap label var LTD "Limited"
cap label var L_VL "Low or very low"
cap label var LOW "Low"
cap label var VLOW "Very low"
cap label var SEV "Severe"
cap label var FDIF_VDIF "Fairly difficult or very difficult"
cap label var VDIF "Very difficult"
cap label var DIF "Difficult"
cap label var FDIF "Fairly difficult"
cap label var FEASY_EASY_VEASY "Fairly easy, easy or very easy"
cap label var FEASY_VEASY "Fairly easy or very easy"
cap label var FEASY "Fairly easy"
cap label var EASY "Easy"
cap label var VEASY "Very easy"
cap label var NONE "None"
cap label var NAP "Not applicable"
cap label var NRP "No response"
