cap label var TOTAL "Total"
cap label var _0 "No clients"
cap label var _1 "1 client"
cap label var _2_9_D0 "From 2 to 9 clients, no client is dominant"
cap label var _2_9_D1 "From 2 to 9 clients, 1 client is dominant"
cap label var GT9_D0 "More than 9 clients, no client is dominant"
cap label var GT9_D1 "More than 9 clients, 1 client is dominant"
cap label var NAP "Not applicable"
cap label var NRP "No response"
