cap label var TOTAL "Total"
cap label var UNI "Universe"
cap label var SPL "Sample"
cap label var SRC "Survey data source"
cap label var AVG "Average"
cap label var AVG_3Y "Three-year average"
cap label var AVG_30Y "Thirty-year average"
cap label var MMEAN "Measured mean"
cap label var CMEAN "Calculated mean"
cap label var MEAN_EI "Mean equivalised income"
cap label var MED_EI "Median equivalised income"
cap label var MED "Median"
cap label var SD "Standard deviation"
cap label var SE "Standard error"
cap label var CV "Coefficient of variation"
cap label var CVA "Coefficient of variation for absolute value"
cap label var CVR "Coefficient of variation for relative value"
cap label var CV_PLI "Coefficient of variation of price level indices"
cap label var CV_VI_HAB "Coefficient of variation of volume indices of expenditure per capita"
cap label var CUM "Cumulative series"
cap label var VAL "Value"
cap label var VAL_A "Annual value"
cap label var RV "Relative value"
cap label var END "Value at the end of the period"
cap label var MAX "Maximum value within period"
cap label var MIN "Minimum value within period"
cap label var DISP_NUTS2 "Dispersion at NUTS level 2"
cap label var DISP_NUTS3 "Dispersion at NUTS level 3"
cap label var SUM3Y "Sum of the last 3 years"
cap label var SUM4Y "Sum of the last 4 years"
cap label var SUM6Y "Sum of the last 6 years"
cap label var NSME "Unsmoothed estimate"
cap label var SME "Smoothed estimate"
cap label var SME_UP95 "Smoothed estimate - upper boundary of the 95% confidence interval"
cap label var SME_LW95 "Smoothed estimate - lower boundary of the 95% confidence interval"
cap label var UP95 "Upper boundary of the 95% confidence interval"
cap label var LW95 "Lower boundary of the 95% confidence interval"
cap label var STA "Status"
cap label var WT "Weight"
cap label var COWEU "Country weights for European Union (EU6-1958, EU9-1973, EU10-1981, EU12-1986, EU15-1995, EU25-2004, EU27-2007, EU28-2013, EU27-2020)"
cap label var COWEU27_2020 "Country weights for EU27 (from 2020)"
cap label var COWEU28 "Country weights for EU28 (2013-2020)"
cap label var COWEU27_2007 "Country weights for EU27 (2007-2013)"
cap label var COWEU25 "Country weights for EU25 (2004-2006)"
cap label var COWEU15 "Country weights for EU15 (1995-2004)"
cap label var COWEA "Country weights for the euro area (EA11-1999, EA12-2001, EA13-2007, EA15-2008, EA16-2009, EA17-2011, EA18-2014, EA19-2015)"
cap label var COWEA19 "Country weights for EA19 (euro area from 2015)"
cap label var COWEA18 "Country weights for EA18 (euro area - 2014)"
cap label var COWEA17 "Country weights for EA17 (euro area - 2011-2013)"
cap label var COWEA16 "Country weights for EA16 (euro area - 2009-2010)"
cap label var COWEA15 "Country weights for EA15 (euro area - 2008)"
cap label var COWEA13 "Country weights for EA13 (euro area - 2007)"
cap label var COWEA12 "Country weights for EA12 (euro area - 2001-2006)"
cap label var COWEEA "Country weights for EEA (European Economic Area)"
cap label var IWBS "Item weights for industry, construction and services (except activities of households as employers and extra-territorial organisations and bodies) - NACE rev.2, B to S"
cap label var NONE "No income"
cap label var Q1 "First quartile"
cap label var Q2 "Second quartile"
cap label var Q3 "Third quartile"
cap label var Q4 "Fourth quartile"
cap label var QU1 "First quintile"
cap label var QU2 "Second quintile"
cap label var QU3 "Third quintile"
cap label var QU4 "Fourth quintile"
cap label var QU5 "Fifth quintile"
cap label var D1 "First decile"
cap label var D2 "Second decile"
cap label var D3 "Third decile"
cap label var D4 "Fourth decile"
cap label var D5 "Fifth decile"
cap label var D6 "Sixth decile"
cap label var D7 "Seventh decile"
cap label var D8 "Eighth decile"
cap label var D9 "Ninth decile"
cap label var D10 "Tenth decile"
cap label var P1 "First percentile"
cap label var P2 "Second percentile"
cap label var P3 "Third percentile"
cap label var P4 "Fourth percentile"
cap label var P5 "Fifth percentile"
cap label var P10 "Tenth percentile"
cap label var P25 "Twenty-fifth percentile"
cap label var S2 "Second sextile"
cap label var P75 "Seventy-fifth percentile"
cap label var P90 "Ninetieth percentile"
cap label var P95 "Ninety-fifth percentile"
cap label var P96 "Ninety-sixth percentile"
cap label var P97 "Ninety-seventh percentile"
cap label var P98 "Ninety-eighth percentile"
cap label var P99 "Ninety-ninth percentile"
cap label var P100 "Hundredth percentile"
cap label var UNK "Unknown"
cap label var AVG_TRP "Average per trip"
cap label var AVG_NGT "Average per night"
