cap label var GCV "Gross calorific value"
cap label var GCV_AVG "Gross calorific value - average"
cap label var GCV_PRD "Gross calorific value - production"
cap label var GCV_PRD_AG "Gross calorific value - production - associated gas"
cap label var GCV_PRD_NAG "Gross calorific value - production - non-associated gas"
cap label var GCV_PRD_CG "Gross calorific value - production - colliery gas"
cap label var GCV_TOS "Gross calorific value - transfer from other sources"
cap label var GCV_TOS_OIL "Gross calorific value - transfer from other sources - oil"
cap label var GCV_TOS_COAL "Gross calorific value - transfer from other sources - coal"
cap label var GCV_TOS_REN "Gross calorific value - transfer from other sources - renewables"
cap label var GCV_IMP "Gross calorific value - imports"
cap label var GCV_EXP "Gross calorific value - exports"
cap label var GCV_INTMARB "Gross calorific value - international marine bunkers"
cap label var GCV_STK_CHG_MG "Gross calorific value - change in stock - as defined in MOS GAS"
cap label var GCV_STK_CHG_NAT "Gross calorific value - change in stock - national territory"
cap label var GCV_STK_OP_NAT "Gross calorific value - opening stock - national territory"
cap label var GCV_STK_CL_NAT "Gross calorific value - closing stock - national territory"
cap label var GCV_STK_OP_ABR "Gross calorific value - opening stock - held abroad"
cap label var GCV_STK_CL_ABR "Gross calorific value - closing stock - held abroad"
cap label var GCV_IC_CAL "Gross calorific value - inland consumption - calculated"
cap label var GCV_IC_CAL_MG "Gross calorific value - inland consumption - calculated as defined in MOS GAS"
cap label var GCV_IC_OBS "Gross calorific value - inland consumption - observed"
cap label var GCV_CO "Gross calorific value - coke ovens"
cap label var GCV_BF "Gross calorific value - blast furnaces"
cap label var GCV_MAP "Gross calorific value - main activity plants"
cap label var GCV_IND "Gross calorific value - industry"
cap label var GCV_STATDIFF "Gross calorific value - statistical difference"
cap label var GCV_DL "Gross calorific value - distribution losses"
cap label var GCV_TI_EHG_MAP "Gross calorific value - Transformation input - electricity and heat generation - main activity producers"
cap label var GCV_OTH "Gross calorific value - other"
cap label var NCV "Net calorific value"
cap label var NCV_AVG "Net calorific value - average"
cap label var NCV_PRD "Net calorific value - production"
cap label var NCV_PRD_AG "Net calorific value - production - associated gas"
cap label var NCV_PRD_NAG "Net calorific value - production - non-associated gas"
cap label var NCV_PRD_CG "Net calorific value - production - colliery gas"
cap label var NCV_TOS "Net calorific value - transfer from other sources"
cap label var NCV_TOS_OIL "Net calorific value - transfer from other sources - oil"
cap label var NCV_TOS_COAL "Net calorific value - transfer from other sources - coal"
cap label var NCV_TOS_REN "Net calorific value - transfer from other sources - renewables"
cap label var NCV_IMP "Net calorific value - imports"
cap label var NCV_EXP "Net calorific value - exports"
cap label var NCV_INTMARB "Net calorific value - international marine bunkers"
cap label var NCV_STK_CHG_NAT "Net calorific value - change in stock - national territory"
cap label var NCV_STK_OP_NAT "Net calorific value - opening stock - national territory"
cap label var NCV_STK_CL_NAT "Net calorific value - closing stock - national territory"
cap label var NCV_STK_OP_ABR "Net calorific value - opening stock - held abroad"
cap label var NCV_STK_CL_ABR "Net calorific value - closing stock - held abroad"
cap label var NCV_IC_CAL "Net calorific value - inland consumption - calculated"
cap label var NCV_IC_OBS "Net calorific value - inland consumption - observed"
cap label var NCV_CO "Net calorific value - coke ovens"
cap label var NCV_BF "Net calorific value - blast furnaces"
cap label var NCV_MAP "Net calorific value - main activity plants"
cap label var NCV_IND "Net calorific value - industry"
cap label var NCV_OTH "Net calorific value - other"
