cap label var D1_7 "All days of the week"
cap label var D1_5 "Monday to Friday"
cap label var D1 "Monday"
cap label var D2 "Tuesday"
cap label var D3 "Wednesday"
cap label var D4 "Thursday"
cap label var D5 "Friday"
cap label var D6_7 "Saturday to Sunday"
cap label var D6 "Saturday"
cap label var D7 "Sunday"
