cap label var TOTAL "Total"
cap label var PER_SUSP "Suspected person"
cap label var PER_PRSC "Prosecuted person"
cap label var PER_CNV "Convicted person"
cap label var PER_PRIS "Prisoner"
cap label var PER_VICT "Victim"
cap label var TRI_PRE "Pre-trial"
cap label var TRI_SPSD "Sentence passed"
cap label var CRT_BGHT "Brought to court"
cap label var CRT_CNV "Convicted"
cap label var CRT_ACQT "Acquitted"
cap label var CRT_RESL "Resolved"
cap label var CRT_PEN "Pending"
cap label var UNK "Unknown"
