cap label var TOTAL "Total"
cap label var ADV "Advertisements"
cap label var RFA "Relatives, friends or acquaintances"
cap label var PES "Public employment service"
cap label var PEA "Private employment agency"
cap label var EDUC_TNG "Education or training provider"
cap label var PER_EMPL "Person contacted employer directly"
cap label var EMPL_PER "Employer contacted person directly"
cap label var OTH "Other method"
cap label var NAP "Not applicable"
cap label var NRP "No response"
cap label var UNK "Unknown"
