cap label var USUAL "Resumption of usual work activities"
cap label var CHANGE_W "Change of work or workplace because of the accidental injury"
cap label var PT "Part time work or on reduced hours because of the accidental injury"
cap label var NOT_RECO "Person has not yet recovered from the accidental injury at the date of the interview"
cap label var PERM_INC "Permanent incapacity to work"
cap label var OTHER "Other not elsewhere mentioned"
cap label var UNK "Unknown"
cap label var TOTAL "Total"
