cap label var HRST "Persons with tertiary education (ISCED) and/or employed in science and technology"
cap label var HRSTE "Persons with tertiary education (ISCED)"
cap label var HRSTO "Persons employed in science and technology"
cap label var HRSTC "Persons with tertiary education (ISCED) and employed in science and technology"
cap label var HRSTU "Unemployed persons with tertiary education (ISCED)"
cap label var SE "Scientists and engineers"
cap label var NON_HRSTU "Unemployed persons with non-tertiary education (ISCED)"
cap label var APPL "Applicant"
cap label var INVT "Inventor"
