cap label var TOTAL "Total"
cap label var FS01 "Owner(s)/director(s) of the business"
cap label var FS02 "Other employees of the business"
cap label var FS03 "Family, friends or other individuals outside the business"
cap label var FS04 "Other businesses"
cap label var FS05 "Banks"
cap label var FS06 "Other loan sources"
cap label var FS07 "Existing shareholders"
cap label var FS08 "Potential new shareholders"
cap label var FS09 "Directors not previously shareholders"
cap label var FS10 "Venture capital funds"
cap label var FS11 "Business angels"
cap label var FS12 "Family, friends or other individuals, not any of the above"
cap label var FS13 "Initial public offering or other stock market offerings"
cap label var FS14 "Other financial institutions"
cap label var FS15 "Government/other equity finance sources"
cap label var FS16 "Leasing"
cap label var FS17 "Factoring"
cap label var FS18 "Bank overdraft or credit line"
cap label var FS19 "Subsidised loans"
cap label var FS20 "Subsidies by [your country's] government"
cap label var FS21 "Foreign government bodies or international organisations"
cap label var FS22 "Trade credit (by suppliers)"
cap label var FS23 "Advanced payments (by customers)"
cap label var FS24 "International trade or export finance facilities"
cap label var FS25 "Mezzanine or hybrid financing"
cap label var FS26 "Other finance types and sources"
cap label var FS27 "Family, friends or other individuals outside the business, excluding business angels"
cap label var FS29 "Local government body"
cap label var FS30 "Other lenders"
cap label var FS31 "Business"
cap label var ODA "Official development assistance"
cap label var GRNT_NGO "Grants by non-governmental organisations"
cap label var FLOW_PRV "Private flows"
cap label var OFLOW_OTH "Other official flows"
cap label var EXPCRED_OSUP "Officially supported export credits"
