cap label var TOTAL "Total"
cap label var SP_WPL "Study period and/or work placement"
cap label var SP_SWP "Study period or study period combined with work placement"
cap label var WPL "Work placement"
cap label var MOV_NAT "Moved residence or willing to move residence for a job within their country"
cap label var MOV_EU_FOR "Moved residence or willing to move residence for a job to another EU country"
cap label var MOV_EXT_EU "Moved residence or willing to move residence for a job outside the EU"
cap label var NMOV "Not moved residence or would not be willing to move residence for a job"
cap label var NRP "No response"
cap label var UNK "Unknown"
