cap label var BE "Belgium"
cap label var BE_CBE "RBD Belgian coastal zone (BE)"
cap label var BE_SCH_BR "RBD Scheldt (BE-Brussels)"
cap label var BE_SCH_B "Scheldt/Escaut - RBD (BE-Brussels)"
cap label var BE_MEU_FL "RBD Meuse (BE-Flemish region)"
cap label var BE_MAA_V "Maas/Meuse - RBD (BE-Flemish region)"
cap label var BE_SCH_FL "RBD Scheldt (BE-Flemish region)"
cap label var BE_SCH_V "Schelde/Escaut - RBD (BE-Flemish region)"
cap label var BE_MEU_WA "RBD Meuse (BE-Walloon region)"
cap label var BE_MAA_W "Meuse/Maas - RBD (BE-Walloon region)"
cap label var BE_RHI_WA "RBD Rhine (BE-Walloon region)"
cap label var BE_RHI_W "Rhine - RBD (BE-Walloon region)"
cap label var BE_SCH_WA "RBD Scheldt (BE-Walloon region)"
cap label var BE_SCH_W "Escaut/Schelde - RBD (BE-Walloon region)"
cap label var BE_SEI_WA "RBD Seine (BE-Walloon region)"
cap label var BE_SEI_W "Seine - RBD (BE-Walloon region)"
cap label var BG "Bulgaria"
cap label var BG_BKS "RBD Black Sea (BG)"
cap label var BG_DAN "RBD Danube (BG)"
cap label var BG_DAN_RBD "Danube - RBD (BG)"
cap label var BG_AEG_E "RBD East Aegean (BG)"
cap label var BG_AEE "East Aegean - RBD (BG)"
cap label var BG_AEG_W "RBD West Aegean (BG)"
cap label var BG_AEW "West Aegean - RBD (BG)"
cap label var CZ "Czechia"
cap label var CZ_DAN "RBD Danube (CZ)"
cap label var CZ_DYJ "SU Dyje/Thaya (CZ)"
cap label var CZ_MOR "SU Morava and tributaries of the Váh (CZ)"
cap label var CZ_DAN_OTH "SU Other tributaries of the Danube (CZ)"
cap label var CZ_ELB "RBD Elbe (CZ)"
cap label var CZ_BRK "SU Berounka (CZ)"
cap label var CZ_ELB_UM "SU Upper and Middle Elbe (CZ)"
cap label var CZ_OHR "SU Ohře, Lower Elbe and other tributaries of the Elbe (CZ)"
cap label var CZ_VLT_L "SU Lower Vltava (CZ)"
cap label var CZ_MOL_L "Lower Vltava / Moldau"
cap label var CZ_VLT_U "SU Upper Vltava (CZ)"
cap label var CZ_MOL_U "Upper Vltava / Moldau"
cap label var CZ_ODR "RBD Oder (CZ)"
cap label var CZ_LNO "SU Lusatian Neisse and other tributaries of the Oder (CZ)"
cap label var CZ_ODR_U "SU Upper Oder (CZ)"
cap label var DK "Denmark"
cap label var DK_BOR "RBD Bornholm (DK)"
cap label var DK_JTL "RBD Jutland and Funen (DK)"
cap label var DK_VID "RBD Vidaa-Krusaa (DK)"
cap label var DK_ZEA "RBD Zealand (DK)"
cap label var DE "Germany (until 1990 former territory of the FRG)"
cap label var DE_DAN "RBD Danube (DE)"
cap label var DE_EID "RBD Eider (DE)"
cap label var DE_ELB "RBD Elbe (DE)"
cap label var DE_ELB_M "SU Middle Elbe/Elde (DE)"
cap label var DE_HAV "SU Havel (DE)"
cap label var DE_MUL "SU Mulde-Elbe-Schwarze Elster (DE)"
cap label var DE_SAA "SU Saale, Upper Vltava, Berounka, Ohře and Lower Elbe (DE)"
cap label var DE_ELB_T "SU Tide-Elbe (DE)"
cap label var DE_EMS "RBD Ems (DE)"
cap label var DE_LED "SU Leda-Jümme, lower Ems, Ems estuary (DE)"
cap label var DE_EMS_U "SU Upper Ems, Ems/Nordradde, Hase (DE)"
cap label var DE_EMS_O "Upper Ems, Ems-Nordradde, Hase"
cap label var DE_MEU "RBD Meuse (DE)"
cap label var DE_MAA "Maas / Meuse - RBD (DE)"
cap label var DE_ODR "RBD Oder (DE)"
cap label var DE_RHI "RBD Rhine (DE)"
cap label var DE_MAI "SU Main (DE)"
cap label var DE_MSL_SAR "SU Moselle/Saar (DE)"
cap label var DE_NEC "SU Neckar (DE)"
cap label var DE_RHI_CO "SU Alpine Rhine/Lake Constance (DE)"
cap label var DE_RHI_C "Lake Constance/Alpine Rhine"
cap label var DE_RHI_H "SU High Rhine (DE)"
cap label var DE_RHI_L "SU Lower Rhine (DE)"
cap label var DE_RHI_N "Lower Rhine"
cap label var DE_RHI_M "SU Middle Rhine (DE)"
cap label var DE_RHI_D "SU Rhine delta (DE)"
cap label var DE_RHI_U "SU Upper Rhine (DE)"
cap label var DE_RHI_O "Oberrhein"
cap label var DE_SLE "RBD Schlei/Trave (DE)"
cap label var DE_WAR "RBD Warnow/Peene (DE)"
cap label var DE_WES_RBD "RBD Weser (DE)"
cap label var DE_ALR "SU Aller (DE)"
cap label var DE_FUL "SU Fulda (DE)"
cap label var DE_LEI "SU Leine (DE)"
cap label var DE_TID "SU Tide-Weser (DE)"
cap label var DE_WER "SU Werra (DE)"
cap label var DE_WES_SU "SU Weser (DE)"
cap label var DE_WES "Weser"
cap label var EE "Estonia"
cap label var EE_E "RBD East Estonia (EE)"
cap label var EE_E_RBD "East Estonia - RBD"
cap label var EE_W "RBD West Estonia (EE)"
cap label var EE_KOI "RBD Koiva (EE)"
cap label var EE_GAU "Koiva /Gauja - RBD (EE)"
cap label var IE "Ireland"
cap label var IE_NBA "RBD Neagh Bann (IE)"
cap label var IE_NW "RBD North Western (IE)"
cap label var IE_REP "RBD Republic of Ireland (IE)"
cap label var EL "Greece"
cap label var EL_AEG "RBD Aegean Islands (EL)"
cap label var EL_ATT "RBD Attica (EL)"
cap label var EL_CRE "RBD Crete (EL)"
cap label var EL_EPI "RBD Epirus (EL)"
cap label var EL_CTL_E "RBD Eastern Central Greece (EL)"
cap label var EL_STE_E "Eastern Central Greece - RBD"
cap label var EL_CTL_W "RBD Western Central Greece (EL)"
cap label var EL_STE_W "Western Central Greece - RBD"
cap label var EL_PEL_E "RBD Eastern Peloponnese (EL)"
cap label var EL_PEL_N "RBD Northern Peloponnese (EL)"
cap label var EL_PEL_W "RBD Western Peloponnese (EL)"
cap label var EL_MAC_E "RBD Eastern Macedonia (EL)"
cap label var EL_MAC_C "RBD Central Macedonia (EL)"
cap label var EL_MAC_W "RBD Western Macedonia (EL)"
cap label var EL_THE "RBD Thessaly (EL)"
cap label var EL_THR "RBD Thrace (EL)"
cap label var ES "Spain"
cap label var ES_ADL "RBD Andalusian Mediterranean Basins (ES)"
cap label var ES_BAI "RBD Balearic islands (ES)"
cap label var ES_CAN_E "RBD Eastern Cantabrian (ES)"
cap label var ES_CAN_W "RBD Western Cantabrian (ES)"
cap label var ES_CEU "RBD Ceuta (ES)"
cap label var ES_DRO "RBD Douro (ES)"
cap label var ES_DUE "RBD Duero (ES)"
cap label var ES_EBR "RBD Ebro (ES)"
cap label var ES_EHI "RBD El Hierro (ES)"
cap label var ES_FUE "RBD Fuerteventura (ES)"
cap label var ES_GAL "RBD Galician Coast (ES)"
cap label var ES_GRC "RBD Gran Canaria (ES)"
cap label var ES_GUA "RBD Guadalete and Barbate (ES)"
cap label var ES_GUL "RBD Guadalquivir (ES)"
cap label var ES_GUD "RBD Guadiana (ES)"
cap label var ES_CAT "RBD Internal basins of Catalonia (ES)"
cap label var ES_JUC "RBD Júcar (ES)"
cap label var ES_LGM "RBD La Gomera (ES)"
cap label var ES_LPA "RBD La Palma (ES)"
cap label var ES_LAN "RBD Lanzarote (ES)"
cap label var ES_MEL "RBD Melilla (ES)"
cap label var ES_MIS "RBD Minho (ES)"
cap label var ES_SEG "RBD Segura (ES)"
cap label var ES_TAG "RBD Tagus (ES)"
cap label var ES_TNR "RBD Tenerife (ES)"
cap label var ES_TIN "RBD Tinto, Odiel and Piedras (ES)"
cap label var FR "France"
cap label var FR_SCH "RBD Escaut, Somme and the coastal rivers of the English Channel and the North Sea (FR)"
cap label var FR_ADO_OTH "RBD Garonne, Adour, Dordogne, Charente and Charente and Aquitaine coastal streams (FR)"
cap label var FR_ADO "SU Adour (FR)"
cap label var FR_TAR "SU Aveyron (FR)"
cap label var FR_CHA "SU Charente (FR)"
cap label var FR_CAQ "SU Charente and Aquitaine coastal streams (FR)"
cap label var FR_DOR "SU Dordogne (FR)"
cap label var FR_GAR "SU Garonne (FR)"
cap label var FR_LOT "SU Lot (FR)"
cap label var FR_LOI "RBD Loire, the coastal rivers of Vendée and Bretagne (FR)"
cap label var FR_ALL "SU Allier - Upper Loire (FR)"
cap label var FR_LOI_L "SU Lower Loire and coastal rivers of Vendée (FR)"
cap label var FR_LOI_A "Lower Loire and coastal rivers of Vendée"
cap label var FR_LOI_M "SU Middle Loire (FR)"
cap label var FR_MSL "SU Mayenne - Sarthe - Loire (FR)"
cap label var FR_MAY "Mayenne-Sarthe-Loir"
cap label var FR_VIE "SU Vienne - Creuse (FR)"
cap label var FR_VIL "SU Vilaine and Brittany coastal streams (FR)"
cap label var FR_MEU "RBD Meuse (FR)"
cap label var FR_MAA_C "Meuse-Chiers - RBD (FR)"
cap label var FR_RHI "RBD Rhine (FR)"
cap label var FR_MSL_SAR "SU Moselle - Saar (FR)"
cap label var FR_RHI_IL "SU Upper Rhine and Ill (FR)"
cap label var FR_RHI_I "Upper Rhine and Ill"
cap label var FR_RHO_CM "RBD Rhône and the mediterranean coastal rivers (FR)"
cap label var FR_ARD "SU Ardèche - Gard (FR)"
cap label var FR_CAZ "SU Coastal streams of the Côte d'Azur (FR)"
cap label var FR_DOU "SU Doubs (FR)"
cap label var FR_DUR "SU Durance (FR)"
cap label var FR_ISR "SU Isère - Drôme (FR)"
cap label var FR_CLR "SU Coastal streams of the Languedoc-Roussillon (FR)"
cap label var FR_RHO_U "SU Upper Rhône (FR)"
cap label var FR_RHO_H "Haut-Rhône"
cap label var FR_RHO_M "SU Middle Rhône (FR)"
cap label var FR_SAO "SU Saône (FR)"
cap label var FR_GUI "RBD Rivers and coastal streams of French Guiana (FR)"
cap label var FR_GUY "Guyane - RBD"
cap label var FR_SAM "RBD Sambre (FR)"
cap label var FR_SEI_CN "RBD Seine and the Normandy coastal streams (FR)"
cap label var FR_CNO "SU Coastal streams of Normandy (FR)"
cap label var FR_MRN "SU Marne (FR)"
cap label var FR_OIS "SU Oise (FR)"
cap label var FR_SEI_D "SU Seine downstream Paris (FR)"
cap label var FR_SEI_V "Seine downstream Paris (FR)"
cap label var FR_SEI_U "SU Seine upstream Paris (FR)"
cap label var FR_SEI_A "Seine upstream Paris (FR)"
cap label var FR_COR "RBD Streams of Corsica (FR)"
cap label var FR_GDL "RBD Streams of Guadeloupe (FR)"
cap label var FR_MAR "RBD Streams of Martinique (FR)"
cap label var FR_MYT "RBD Streams of Mayotte (FR)"
cap label var FR_REU "RBD Streams of Réunion (FR)"
cap label var HR "Croatia"
cap label var HR_ADR "RBD Adriatic (HR)"
cap label var HR_DAN "RBD Danube (HR)"
cap label var HR_DRA "SU Drava and Danube (HR)"
cap label var HR_DRA_SB "Drava and Danube - sub-basin"
cap label var HR_SAV "SU Sava (HR)"
cap label var HR_SAV_SB "Sava - sub-basin"
cap label var IT "Italy"
cap label var IT_ALP_E "RBD Eastern Alps (IT)"
cap label var IT_APE_C "RBD Central Apennines (IT)"
cap label var IT_APP_C "RBD Central Appenines (IT)"
cap label var IT_APE_M "RBD Middle Apennines (IT)"
cap label var IT_APP_M "RBD Middle Apennines (IT)"
cap label var IT_APE_N "RBD Northern Apennines (IT)"
cap label var IT_APP_N "RBD Northern Appenines (IT)"
cap label var IT_APE_S "RBD Southern Apennines (IT)"
cap label var IT_APP_S "RBD Southern Appenines (IT)"
cap label var IT_PO "RBD Po river (IT)"
cap label var IT_SAR "RBD Sardinia (IT)"
cap label var IT_SER "RBD Serchio (IT)"
cap label var IT_SIC "RBD Sicily (IT)"
cap label var CY "Cyprus"
cap label var CY_RBD "RBD Cyprus (CY)"
cap label var LV "Latvia"
cap label var LV_DAU "RBD Daugava (LV)"
cap label var LV_GAU "RBD Gauja (LV)"
cap label var LV_LIE "RBD Lielupe (LV)"
cap label var LV_VEN "RBD Venta (LV)"
cap label var LV_VEN_RBD "Venta - RBD (LV)"
cap label var LT "Lithuania"
cap label var LT_DAU_RBD "RBD Daugava (LT)"
cap label var LT_LIE "RBD Lielupe (LT)"
cap label var LT_NEM "RBD Nemunas (LT)"
cap label var LT_VEN_RBD "RBD Venta (LT)"
cap label var LU "Luxembourg"
cap label var LU_MEU "RBD Meuse (LU)"
cap label var LU_MAA "Meuse / Maas - RBD (LU)"
cap label var LU_RHI "RBD Rhine (LU)"
cap label var HU "Hungary"
cap label var HU_DAN_RBD "RBD Danube (HU)"
cap label var HU_BAT "SU Balaton (HU)"
cap label var HU_DAN_SU "SU Danube (HU)"
cap label var HU_DAN "Danube (HU)"
cap label var HU_DRA "SU Drava (HU)"
cap label var HU_TIS "SU Tisza (HU)"
cap label var MT "Malta"
cap label var MT_RBD "RBD Malta (MT)"
cap label var NL "Netherlands"
cap label var NL_EMS "RBD Ems (NL)"
cap label var NL_MEU "RBD Meuse (NL)"
cap label var NL_MAA "Maas / Meuse - RBD (NL)"
cap label var NL_RHI "RBD Rhine (NL)"
cap label var NL_SCH "RBD Scheldt (NL)"
cap label var AT "Austria"
cap label var AT_DAN "RBD Danube (AT)"
cap label var AT_ELB "RBD Elbe (AT)"
cap label var AT_RHI "RBD Rhine (AT)"
cap label var PL "Poland"
cap label var PL_DAN "RBD Danube (PL)"
cap label var PL_DNI "RBD Dniester (PL)"
cap label var PL_JAR "RBD Jarft (PL)"
cap label var PL_ELB "RBD Elbe (PL)"
cap label var PL_NEM "RBD Nemunas (PL)"
cap label var PL_ODR "RBD Oder (PL)"
cap label var PL_ODR_L "SU Lower Oder and western coast (PL)"
cap label var PL_ODR_M "SU Middle Oder (PL)"
cap label var PL_ODR_U "SU Upper Oder (PL)"
cap label var PL_WRT "SU Warta (PL)"
cap label var PL_PRE "RBD Pregolya (PL)"
cap label var PL_PRI "Pregolya / Prieglius - RBD (PL)"
cap label var PL_SWI "RBD Swieza (PL)"
cap label var PL_UCK "RBD Ücker (PL)"
cap label var PL_VIS "RBD Vistula (PL)"
cap label var PL_BUG "SU Bug and Narew (PL)"
cap label var PL_VIS_LI "SU Little Vistula (PL)"
cap label var PL_VIS_S "Little Vistula"
cap label var PL_VIS_M "SU Middle Vistula without Bug and Narew (PL)"
cap label var PL_VIS_L "SU Lower Vistula (PL)"
cap label var PL_VIS_U "SU Upper Vistula (PL)"
cap label var PT "Portugal"
cap label var PT_ALG "RBD Algarve rivers (PT)"
cap label var PT_AZO "RBD Azores (PT)"
cap label var PT_CAV "RBD Cavado, Ave and Leça (PT)"
cap label var PT_DRO "RBD Douro (PT)"
cap label var PT_GUD "RBD Guadiana (PT)"
cap label var PT_RIB_SU "SU Tejo and Ribeiras do Oeste (PT)"
cap label var PT_RIB_SB "Tejo and Ribeiras do Oeste - sub-basin"
cap label var PT_MAD "RBD Madeira (PT)"
cap label var PT_MIH "RBD Minho and Lima (PT)"
cap label var PT_SAD "RBD Sado and Mira (PT)"
cap label var PT_TAG "RBD Tagus and West rivers (PT)"
cap label var PT_VOU "RBD Vouga, Mondego and Lis (PT)"
cap label var PT_VOU_SU "SU Vouga, Mondego and Lis (PT)"
cap label var PT_VOU_SB "Vouga, Mondego and Lis - sub-basin"
cap label var RO "Romania"
cap label var RO_DAN "RBD Danube (RO)"
cap label var RO_DAN_RBD "Danube - RBD (RO)"
cap label var RO_ARV "SU Arges-Vedea (RO)"
cap label var RO_BAN "SU Banat (RO)"
cap label var RO_IAL "SU Buzau-Ialomita (RO)"
cap label var RO_CRI "SU Crisuri (RO)"
cap label var RO_DOB "SU Dobrogea-Litoral (RO)"
cap label var RO_JIU "SU Jiu (RO)"
cap label var RO_MRS "SU Mures (RO)"
cap label var RO_OLT "SU Olt (RO)"
cap label var RO_PRU "SU Prut-Barlad (RO)"
cap label var RO_SIR "SU Siret (RO)"
cap label var RO_SOM "SU Somes-Tisza (RO)"
cap label var SI "Slovenia"
cap label var SI_ADR "RBD Adriatic (SI)"
cap label var SI_ADR_N "North Adriatic - RBD"
cap label var SI_DAN "RBD Danube (SI)"
cap label var SK "Slovakia"
cap label var SK_DAN_RBD "RBD Danube (SK)"
cap label var SK_BOD "SU Bodrog (SK)"
cap label var SK_BOV "SU Bodva (SK)"
cap label var SK_DAN_SU "SU Danube (SK)"
cap label var SK_DAN "Danube (SK)"
cap label var SK_HOR "SU Hornád (SK)"
cap label var SK_HRO "SU Hron (SK)"
cap label var SK_IPE "SU Ipel (SK)"
cap label var SK_MOR "SU Morava (SK)"
cap label var SK_SLA "SU Slana (SK)"
cap label var SK_VAH "SU Vah (SK)"
cap label var SK_VIS "RBD Vistula (SK)"
cap label var SK_DUN "Dunajec and Poprad (SK)"
cap label var FI "Finland"
cap label var FI_ALD "RBD Åland (FI)"
cap label var FI_KEM "RBD Kemijoki (FI)"
cap label var FI_KOK "RBD Kokemäenjoki-Archipelago sea-Bothnian sea (FI)"
cap label var FI_KYM "RBD Kymijoki-Gulf of Finland (FI)"
cap label var FI_OUL "RBD Oulujoki-Iijoki (FI)"
cap label var FI_TEN "RBD Teno, Näätämöjoki and Paatsjoki (FI)"
cap label var FI_TON "RBD Torne (FI)"
cap label var FI_TOR_RBD "Tornionjoki - RBD"
cap label var FI_VUO "RBD Vuoksi (FI)"
cap label var SE "Sweden"
cap label var SE_BAL_N "RBD North Baltic sea (SE)"
cap label var SE_BAL_S "RBD South Baltic sea (SE)"
cap label var SE_BBY "RBD Bothnian Bay (SE)"
cap label var SE_BBY_TO "RBD Bothnian Bay, international district Torne river (SE)"
cap label var SE_BBY_NL "RBD Bothnian Bay, international drainage basin Nordland (SE)"
cap label var SE_BBY_TR "RBD Bothnian Bay, international drainage basin Troms (SE)"
cap label var SE_BSE "RBD Bothnian sea (SE)"
cap label var SE_BSE_TD "RBD Bothnian sea, international drainage basin Trondelagsfylkene (SE)"
cap label var SE_SKK "RBD Skagerrak and Kattegat (SE)"
cap label var SE_SGL "RBD Skagerrak and Kattegat, international drainage basin Glomma (SE)"
cap label var IS "Iceland"
cap label var LI "Liechtenstein"
cap label var LI_RBD "RBD Liechtenstein (LI)"
cap label var NO "Norway"
cap label var NO_AGD "RBD Agder (NO)"
cap label var NO_BBY "RBD Bothnian Bay (NO)"
cap label var NO_BBY_TO "RBD Bothnian Bay, international district Torne river (NO)"
cap label var NO_TOR "Torne (Torniojoki) - RBD (NO)"
cap label var NO_BSE "RBD Bothnian sea (NO)"
cap label var NO_FMK "RBD Finnmark (NO)"
cap label var NO_GLM "RBD Glomma (NO)"
cap label var NO_HDA "RBD Hordaland (NO)"
cap label var NO_KEM "RBD Kemijoki (NO)"
cap label var NO_MRD "RBD Moere and Romsdal (NO)"
cap label var NO_GLO "Glomma, Møre and Romsdal - RBD"
cap label var NO_NRL "RBD Nordland (NO)"
cap label var NO_NFI "RBD Norwegian-Finnish (NO)"
cap label var NO_NFI_SB "Norway-Finland - sub-basin"
cap label var NO_ROL "RBD Rogaland (NO)"
cap label var NO_SKK "RBD Skagerrak and Kattegat (NO)"
cap label var NO_SFJ "RBD Sogn and Fjordane (NO)"
cap label var NO_TON "RBD Torne (NO)"
cap label var NO_TOR_FI "Tornionjoki - RBD (FI)"
cap label var NO_TRD "RBD Troendelag (NO)"
cap label var NO_TRO "RBD Troms (NO)"
cap label var NO_WBA "RBD West-Bay (NO)"
cap label var CH "Switzerland"
cap label var CH_ADI "RBD Adige (CH)"
cap label var CH_DAN "RBD Danube (CH)"
cap label var CH_PO "RBD Po (CH)"
cap label var CH_RHI "RBD Rhine (CH)"
cap label var CH_RHO "RBD Rhône (CH)"
cap label var UK "United Kingdom"
cap label var UK_ANG "RBD Anglian (UK)"
cap label var UK_DEE "RBD Dee (UK)"
cap label var UK_HUM "RBD Humber (UK)"
cap label var UK_NBA "RBD Neagh Bann (UK)"
cap label var UK_NOE "RBD North Eastern Northern Ireland (UK)"
cap label var UK_NOW "RBD North West England (UK)"
cap label var UK_NWN "RBD North Western Northern Ireland (UK)"
cap label var UK_NTH "RBD Northumbria (UK)"
cap label var UK_SCO "RBD Scotland (UK)"
cap label var UK_ARG "SU Argyll (UK)"
cap label var UK_CLY "SU Clyde (UK)"
cap label var UK_FOR "SU Forth (UK)"
cap label var UK_HIG_N "SU North Highland (UK)"
cap label var UK_HIG_W "SU West Highland (UK)"
cap label var UK_ORK "SU Orkney and Shetland (UK)"
cap label var UK_SCO_NE "SU North East Scotland (UK)"
cap label var UK_TAY "SU Tay (UK)"
cap label var UK_SEV "RBD Severn (UK)"
cap label var UK_SOL "RBD Solway Tweed (UK)"
cap label var UK_SOE "RBD South East England (UK)"
cap label var UK_SOW "RBD South West England (UK)"
cap label var UK_THA "RBD Thames (UK)"
cap label var UK_WAL_W "RBD Western Wales (UK)"
cap label var UK_GIB "RBD Gibraltar (UK)"
cap label var GI_RBD "Gibraltar - RBD"
cap label var ME "Montenegro"
cap label var MK "North Macedonia"
cap label var AL "Albania"
cap label var AL_DRI "RBD Drin (AL)"
cap label var AL_JON "RBD Ionian zone (AL)"
cap label var AL_ISH "RBD Ishem (AL)"
cap label var AL_MAT "RBD Mat (AL)"
cap label var AL_SHK "RBD Shkumbin (AL)"
cap label var AL_SEM "RBD Seman (AL)"
cap label var AL_VJO "RBD Vjosa (AL)"
cap label var RS "Serbia"
cap label var RS_DAN "RBD Danube (RS)"
cap label var RS_MOR "RBD Morava (RS)"
cap label var RS_SAV "RBD Sava (RS)"
cap label var TR "Turkey"
cap label var BA "Bosnia and Herzegovina"
cap label var XK "Kosovo (under United Nations Security Council Resolution 1244/99)"
