cap label var TOTAL "Total"
cap label var PAS "Passengers"
cap label var EMP "Employed persons"
cap label var SAL "Employees"
cap label var DRIV "Drivers"
cap label var PED "Pedestrians"
cap label var LV_USR "Level crossing users"
cap label var UA_PER "Unauthorised persons"
cap label var CREW "Crew"
cap label var OTH "Others"
cap label var UNK "Unknown"
