cap label var TOTAL "Total"
cap label var SKI "Snow-skis and other snow-ski equipment, ski-boots, cross-country ski footwear and snowboard boots"
cap label var SKATE "Ice skates and roller skates, including skating boots with skates attached"
cap label var WATER "Vessels, sailboats, other water-sport boats and water-sport equipment"
cap label var GOLF "Golf clubs and other golf equipment"
cap label var RACKET "Articles and equipment for table tennis; tennis, badminton and similar rackets"
cap label var BALL "Tennis balls, inflatable balls, other balls (excl. golf balls, and table-tennis balls)"
cap label var GYMSWIM "Articles and equipment for general physical exercise, gymnastics or athletics, sport and outdoor games, swimming and paddling pools"
cap label var FISHING "Fishing rods, fish-hooks, fishing reels and other fishing equipment"
cap label var CYCLE "Bicycles and other cycles (including delivery tricycles), not motorised"
cap label var CHUTE "Parachutes (including dirigible parachutes and paragliders) and rotochutes; parts thereof and accessories thereto"
cap label var SPWEAR "Swimwear, ski-suits, gloves designed for use in sports"
cap label var FTWEAR "Sports footwear"
cap label var SHOTGUN "Sporting, hunting or target-shooting shotguns"
