cap label var IT_GEN "General IT skills"
cap label var IT_PROF "Professional IT skills"
cap label var MGMT "Management skills"
cap label var TEAM "Team working skills"
cap label var CUS_HDL "Customer handling skills"
cap label var PB_SOLV "Problem solving skills"
cap label var ADMIN "Office administration skills"
cap label var FOR_LANG "Foreign language skills"
cap label var SPEC "Technical, practical or job-specific skills"
cap label var COMM "Oral or written communication skills"
cap label var NUM_LIT "Numeracy and/or literacy skills"
cap label var OTH "Other skills and competences"
cap label var UNK "Unknown"
