cap label var TOTAL "Total"
cap label var _0 "No-one"
cap label var _1 "First"
cap label var _2 "Second"
cap label var _3 "Third"
cap label var _4 "Fourth"
cap label var _5 "Fifth"
cap label var GE4 "Fourth and following"
cap label var GE6 "Sixth and following"
cap label var UNK "Unknown"
