cap label var STR "Strong"
cap label var VG_FG "Very good or fairly good"
cap label var VGOOD "Very good"
cap label var GOOD "Good"
cap label var VG_G "Very good or good"
cap label var FGOOD "Fairly good"
cap label var FAIR "Fair"
cap label var INT "Intermediate"
cap label var MOD "Moderate"
cap label var VMILD "Very mild"
cap label var MILD "Mild"
cap label var M_VM "Mild or very mild"
cap label var NONE_MIN "None or minimum"
cap label var POOR "Poor"
cap label var BAD "Bad"
cap label var VB_FB "Very bad or fairly bad"
cap label var VBAD "Very bad"
cap label var FBAD "Fairly bad"
cap label var B_VB "Bad or very bad"
cap label var SEV "Severe"
cap label var MODS "Moderately severe"
cap label var MOD_MODS_SEV "Moderate, moderately severe or severe"
cap label var S_VS "Severe or very severe"
cap label var NONE "None"
cap label var UNK "Unknown"
