cap label var TOTAL "Total"
cap label var HIGH "High"
cap label var MED "Medium"
cap label var LOW "Low"
cap label var NONE "None"
cap label var NAP "Not applicable"
cap label var NRP "No response"
cap label var UNK "Unknown"
