cap label var TOTAL "Total"
cap label var EU "European Union (EU6-1958, EU9-1973, EU10-1981, EU12-1986, EU15-1995, EU25-2004, EU27-2007, EU28-2013, EU27-2020)"
cap label var EU27_2020 "European Union - 27 countries (from 2020)"
cap label var EU28 "European Union - 28 countries (2013-2020)"
cap label var EU27_2007 "European Union - 27 countries (2007-2013)"
cap label var EU25 "European Union - 25 countries (2004-2006)"
cap label var EU15 "European Union - 15 countries (1995-2004)"
cap label var EA "Euro area (EA11-1999, EA12-2001, EA13-2007, EA15-2008, EA16-2009, EA17-2011, EA18-2014, EA19-2015)"
cap label var BE "Belgium"
cap label var BG "Bulgaria"
cap label var CZ "Czechia"
cap label var DK "Denmark"
cap label var DK01 "Denmark"
cap label var DK02 "Denmark (DIS)"
cap label var DK09 "Denmark - unspecified register"
cap label var DE "Germany (until 1990 former territory of the FRG)"
cap label var EX_DD "Former German Democratic Republic (until 1990) / new Länder (from 1991)"
cap label var EE "Estonia"
cap label var IE "Ireland"
cap label var EL "Greece"
cap label var ES "Spain"
cap label var ES01 "Spain"
cap label var ES02 "Spain (Rebeca)"
cap label var ES03 "Ceuta"
cap label var ES04 "Melilla"
cap label var ES09 "Spain - unspecified register"
cap label var FR "France"
cap label var FR01 "France"
cap label var FR02 "French Antarctic territory (incl. Kerguelen Island)"
cap label var FR03 "France (RIF)"
cap label var FR09 "France - unspecified register"
cap label var HR "Croatia"
cap label var IT "Italy"
cap label var IT01 "Italy - first register"
cap label var IT02 "Italy - international register"
cap label var IT09 "Italy - unspecified register"
cap label var CY "Cyprus"
cap label var LV "Latvia"
cap label var LT "Lithuania"
cap label var LU "Luxembourg"
cap label var HU "Hungary"
cap label var MT "Malta"
cap label var NL "Netherlands"
cap label var AT "Austria"
cap label var PL "Poland"
cap label var PT "Portugal"
cap label var PT01 "Portugal"
cap label var PT02 "Portugal (MAR)"
cap label var PT09 "Portugal - unspecified register"
cap label var RO "Romania"
cap label var SI "Slovenia"
cap label var SK "Slovakia"
cap label var FI "Finland"
cap label var SE "Sweden"
cap label var EXT_EU25 "Extra EU25"
cap label var EXT_EU15 "Extra-EU15"
cap label var EEA "European Economic Area (EEA18-1995, EEA28-2004, EEA30-2007, EEA31-2013, EEA30-2020)"
cap label var EFTA "European Free Trade Association (IS, LI, NO, CH)"
cap label var IS "Iceland"
cap label var LI "Liechtenstein"
cap label var NO "Norway"
cap label var NO01 "Norway"
cap label var NO02 "Norway (NIS)"
cap label var NO09 "Norway - unspecified register"
cap label var CH "Switzerland"
cap label var UK "United Kingdom"
cap label var UK01 "United Kingdom"
cap label var UK02 "Isle Of Man"
cap label var UK03 "Channel Islands"
cap label var UK04 "Gibraltar"
cap label var UK09 "United Kingdom - unspecified register"
cap label var ME "Montenegro"
cap label var MK "North Macedonia"
cap label var AL "Albania"
cap label var RS "Serbia"
cap label var TR "Turkey"
cap label var EUR_OTH "Other european countries (AD, CY, FO, GI, MT, MC, SM, VA, TR)"
cap label var IM "Isle of Man"
cap label var THIRD "Third countries"
cap label var AF "Afghanistan"
cap label var DZ "Algeria"
cap label var OCE_AM "American Oceania  (US) (AS, GU, UM)"
cap label var AS "American Samoa"
cap label var AD "Andorra"
cap label var AO "Angola"
cap label var AI "Anguilla"
cap label var AQ "Antarctica"
cap label var AG "Antigua and Barbuda"
cap label var AR "Argentina"
cap label var AM "Armenia"
cap label var AW "Aruba"
cap label var AU "Australia"
cap label var AZ "Azerbaijan"
cap label var BS "Bahamas"
cap label var BH "Bahrain"
cap label var BD "Bangladesh"
cap label var BB "Barbados"
cap label var BY "Belarus"
cap label var BZ "Belize"
cap label var BJ "Benin"
cap label var BL "Saint-Barthélemy (FR)"
cap label var BM "Bermuda"
cap label var BT "Bhutan"
cap label var BO "Bolivia"
cap label var BQ "Bonaire, Saint Eustatius and Saba"
cap label var BA "Bosnia and Herzegovina"
cap label var BW "Botswana"
cap label var BV "Bouvet Island (NO)"
cap label var BR "Brazil"
cap label var IO "British Indian Ocean Territory"
cap label var VG "British Virgin islands (UK)"
cap label var BN "Brunei Darussalam"
cap label var BF "Burkina Faso"
cap label var BI "Burundi"
cap label var KH "Cambodia"
cap label var CM "Cameroon"
cap label var CA "Canada"
cap label var CV "Cape Verde"
cap label var KY "Cayman Islands"
cap label var CF "Central African Republic"
cap label var TD "Chad"
cap label var CL "Chile"
cap label var CX "Christmas Islands (AU)"
cap label var CC "Cocos (Keeling) Islands (AU)"
cap label var CO "Colombia"
cap label var KM "Comoros"
cap label var CG "Congo"
cap label var CD "Democratic Republic of the Congo"
cap label var CK "Cook Islands"
cap label var CR "Costa Rica"
cap label var CU "Cuba"
cap label var DJ "Djibouti"
cap label var CW "Curaçao"
cap label var DM "Dominica"
cap label var DO "Dominican Republic"
cap label var TL "East Timor"
cap label var EC "Ecuador"
cap label var EG "Egypt"
cap label var SV "El Salvador"
cap label var GQ "Equatorial Guinea"
cap label var ER "Eritrea"
cap label var ET "Ethiopia"
cap label var FK "Falkland Islands (Malvinas)  (UK)"
cap label var FO "Faroe Islands"
cap label var GI "Gibraltar (UK)"
cap label var FM "Federated States Of Micronesia"
cap label var FJ "Fiji"
cap label var EX_CS "Former Czechoslovakia (before 1992)/Total components of former Czechoslovakia"
cap label var EX_SU "Former Soviet Union (before 1991)/Total components of the former Soviet Union"
cap label var EX_YU "Former Yugoslavia (before 1992)/Total components of the former republic of Yugoslavia"
cap label var PF "French Polynesia"
cap label var TF "French southern territories"
cap label var GA "Gabon"
cap label var GM "Gambia"
cap label var GE "Georgia"
cap label var GH "Ghana"
cap label var GL "Greenland"
cap label var GD "Grenada"
cap label var GU "Guam"
cap label var GT "Guatemala"
cap label var GN "Guinea"
cap label var GW "Guinea Bissau"
cap label var GY "Guyana"
cap label var HT "Haiti"
cap label var HM "Heard and McDonald Islands (AU)"
cap label var VA "Vatican City State"
cap label var HN "Honduras"
cap label var HK "Hong Kong"
cap label var IN "India"
cap label var ID "Indonesia"
cap label var IR "Iran"
cap label var IQ "Iraq"
cap label var IL "Israel"
cap label var CI "Ivory Coast"
cap label var JM "Jamaica"
cap label var JP "Japan"
cap label var JO "Jordan"
cap label var KZ "Kazakhstan"
cap label var KE "Kenya"
cap label var KI "Kiribati"
cap label var KP "North Korea"
cap label var KR "South Korea"
cap label var KW "Kuwait"
cap label var KG "Kyrgyzstan"
cap label var LA "Laos"
cap label var LB "Lebanon"
cap label var LS "Lesotho"
cap label var LR "Liberia"
cap label var LY "Libya"
cap label var MO "Macao"
cap label var MG "Madagascar"
cap label var MW "Malawi"
cap label var MY "Malaysia"
cap label var MV "Maldives"
cap label var ML "Mali"
cap label var MH "Marshall Islands"
cap label var MR "Mauritania"
cap label var MU "Mauritius"
cap label var YT "Mayotte"
cap label var MX "Mexico"
cap label var MD "Moldova"
cap label var MN "Mongolia"
cap label var MS "Montserrat"
cap label var MA "Morocco"
cap label var MZ "Mozambique"
cap label var MM "Myanmar"
cap label var NA "Namibia"
cap label var NR "Nauru"
cap label var NP "Nepal"
cap label var AN "Netherland Antilles (NL)"
cap label var NC "New Caledonia"
cap label var NZ "New Zealand"
cap label var OCE_NZ "New Zealand Oceania (CK, NU, TK)"
cap label var NI "Nicaragua"
cap label var NE "Niger"
cap label var NG "Nigeria"
cap label var NU "Niue  (NZ)"
cap label var NF "Norfolk Island"
cap label var MP "Northern Mariana Islands"
cap label var PS "Palestine"
cap label var OM "Oman"
cap label var OTH_POLAR "Other polar region"
cap label var PK "Pakistan"
cap label var PW "Palau"
cap label var PA "Panama"
cap label var PG "Papua New Guinea"
cap label var PY "Paraguay"
cap label var CN_X_HK "China except Hong Kong"
cap label var PE "Peru"
cap label var PH "Philippines"
cap label var PN "Pitcairn"
cap label var PR "Puerto Rico"
cap label var QA "Qatar"
cap label var RU "Russian Federation"
cap label var RW "Rwanda"
cap label var LC "Saint Lucia"
cap label var VC "Saint Vincent and the Grenadines"
cap label var SM "San Marino"
cap label var ST "Sao Tome and Principe"
cap label var SA "Saudi Arabia"
cap label var SN "Senegal"
cap label var CS "Serbia and Montenegro"
cap label var SC "Seychelles"
cap label var SL "Sierra Leone"
cap label var SG "Singapore"
cap label var SB "Solomon Islands"
cap label var SO "Somalia"
cap label var ZA "South Africa"
cap label var GS "South Georgia and the South Sandwichs Islands (UK)"
cap label var LK "Sri Lanka"
cap label var KN "St. Christopher (St. Kitts) and Nevis"
cap label var SH "St. Helena  (UK)"
cap label var PM "St. Pierre and Miquelon  (FR)"
cap label var SD "Sudan"
cap label var SR "Suriname"
cap label var SZ "Eswatini"
cap label var SY "Syria"
cap label var TW "Taiwan"
cap label var TJ "Tajikistan"
cap label var TZ "Tanzania"
cap label var TH "Thailand"
cap label var TG "Togo"
cap label var TK "Tokelau (NZ)"
cap label var TO "Tonga"
cap label var SX "Sint Maarten"
cap label var TT "Trinidad and Tobago"
cap label var TN "Tunisia"
cap label var TM "Turkmenistan"
cap label var TC "Turks and Caicos Islands (UK)"
cap label var TV "Tuvalu"
cap label var UG "Uganda"
cap label var UA "Ukraine"
cap label var AE "United Arab Emirates"
cap label var US01 "United States"
cap label var US02 "Puerto Rico (USA)"
cap label var US09 "United States - unspecified register"
cap label var UM "United States Minor Outlying Islands (US)"
cap label var UY "Uruguay"
cap label var US "USA"
cap label var UZ "Uzbekistan"
cap label var VU "Vanuatu"
cap label var VE "Venezuela"
cap label var VN "Vietnam"
cap label var VI "US Virgin Islands (US)"
cap label var WF "Wallis and Futuna Islands (FR)"
cap label var WS "American Samoa (US)"
cap label var YE "Yemen"
cap label var ZM "Zambia"
cap label var ZW "Zimbabwe"
cap label var OTHER "Other countries"
cap label var UNK "Unknown"
cap label var WORLD "All countries of the world"
