cap label var TOTAL "Total"
cap label var CROC "Aggregates - crushed rock, other sands (not silica), pebbles, gravel, bitumen additives"
cap label var RUB_NTL "Rubber - natural"
cap label var WD_SAPE "Sapele wood"
cap label var WD_TEAK "Natural teak wood"
cap label var AL "Aluminium"
cap label var SB "Antimony"
cap label var BRT "Baryte"
cap label var BAUX "Bauxite"
cap label var BENT "Bentonite"
cap label var BE "Beryllium"
cap label var BI "Bismuth"
cap label var BOR "Borate"
cap label var CE "Cerium"
cap label var CR "Chromium"
cap label var CO "Cobalt"
cap label var COCO "Coking coal"
cap label var CU "Copper"
cap label var DIAT "Diatomite"
cap label var DY "Dysprosium"
cap label var ER "Erbium"
cap label var EU "Europium"
cap label var FSP "Feldspar"
cap label var FL "Fluorspar"
cap label var GD "Gadolinium"
cap label var GA "Gallium"
cap label var GE "Germanium"
cap label var AU "Gold"
cap label var GP "Gypsum"
cap label var HF "Hafnium"
cap label var HE "Helium"
cap label var HO "Holmium"
cap label var IN "Indium"
cap label var IR "Iridium"
cap label var FEOR "Iron ore"
cap label var FE "Iron"
cap label var KAOL "Kaolin clay"
cap label var LA "Lanthanum"
cap label var PB "Lead"
cap label var LST "Limestone"
cap label var LI "Lithium"
cap label var LU "Lutetium"
cap label var MGS "Magnesite"
cap label var MG "Magnesium"
cap label var MN "Manganese"
cap label var MO "Molybdenum"
cap label var CORK "Natural cork"
cap label var GR "Natural graphite"
cap label var RUBB "Natural rubber"
cap label var TEAK "Natural teak wood"
cap label var ND "Neodymium"
cap label var NI "Nickel"
cap label var NB "Niobium"
cap label var PD "Palladium"
cap label var PERL "Perlite"
cap label var PHOR "Phosphate rock"
cap label var P "Phosphorus"
cap label var PT "Platinum"
cap label var PTSH "Potash"
cap label var K "Potassium"
cap label var PR "Praseodymium"
cap label var RE "Rhenium"
cap label var RH "Rhodium"
cap label var RU "Ruthenium"
cap label var SM "Samarium"
cap label var SAPE "Sapele wood"
cap label var SC "Scandium"
cap label var SE "Selenium"
cap label var SLCA "Silica sand"
cap label var SIME "Silicon metal"
cap label var SI "Silicon"
cap label var AG "Silver"
cap label var S "Sulphur"
cap label var TALC "Talc"
cap label var TA "Tantalum"
cap label var TE "Tellurium"
cap label var TB "Terbium"
cap label var TM "Thulium"
cap label var SN "Tin"
cap label var TI "Titanium"
cap label var W "Tungsten"
cap label var V "Vanadium"
cap label var YB "Ytterbium"
cap label var Y "Yttrium"
cap label var ZN "Zinc"
