cap label var ASS "Assets"
cap label var LIAB "Liabilities"
cap label var NET "Net position"
cap label var CIA "Credit institutions, assets"
cap label var CIL "Credit institutions, liabilities"
cap label var CIN "Credit institutions, net position"
cap label var GGN "General government, net postion"
cap label var GGA "General government, assets"
cap label var GGL "General government, liabilities"
cap label var NEN "National economy, net position"
cap label var NEA "National economy, assets"
cap label var NEL "National economy, liabilities"
cap label var NFPA "Non-financial private sector, assets"
cap label var NFPL "non-financial private sector, liabilities"
cap label var NFPN "Non-financial private sector, net position"
cap label var FINTRA "Financial transactions (net accuisitions of financial assets/net incurrence of liabilities)"
cap label var OTA "Other, assets"
cap label var OTL "Other, liabilities"
cap label var OTN "Other, net position"
