cap label var TOTAL "Total"
cap label var BIRTH "Born with it or birth injury"
cap label var WRK_DIS "Work-related diseases"
cap label var WRK_ACC "Work-related accident or injury including traffic accidents at work"
cap label var NWRK_DIS "Non-work related diseases"
cap label var NWRK_ACC "Household, leisure and sports accident or injury (non-work related)"
cap label var TRF_ACC "Traffic accident or injury (not work related)"
cap label var NRP "No response"
cap label var UNK "Unknown"
