cap label var HRI1 "Pesticides - harmonised risk indicator 1 (all active substances)"
cap label var GRP1 "Group 1 - low-risk active substances"
cap label var GRP1_CAT_A "Group 1, category A - low-risk micro-organisms"
cap label var GRP1_CAT_B "Group 1, category B - low-risk chemical active substances"
cap label var GRP2 "Group 2 - active substances"
cap label var GRP2_CAT_C "Group 2, category C - micro-organisms"
cap label var GRP2_CAT_D "Group 2, category D - chemical active substances"
cap label var GRP3 "Group 3 - active substances candidates for substitution"
cap label var GRP3_CAT_E "Group 3, category E - active substances candidates for substitution not classified as carcinogenic category 1A or 1B and/or toxic for reproduction category 1A or 1B and/or endocrine disruptors"
cap label var GRP3_CAT_F "Group 3, category F - active substances candidates for substitution classified as carcinogenic category 1A or 1B and/or toxic for reproduction category 1A or 1B and/or endocrine disruptors, where exposure of humans is negligible"
cap label var GRP4 "Group 4 - non-approved active substances"
cap label var GRP4_CAT_G "Group 4, category G - non-approved active substances"
cap label var NCHAS "Categories A and C - non-chemical active substances"
cap label var CHAS "Categories B, D, E and F - chemical active substances"
