cap label var NGDP "Net balance at current prices (in % of GDP)"
cap label var NMLD "Net balance (in 1 000 million ECU/EUR)"
cap label var COVR "Cover rates (in %)"
cap label var CA1 "Credits by geographical zone (credits as % of partner World credits)"
cap label var DA1 "Debits by geographical zone (debits as % of partner World debits)"
cap label var CMLD "Exports (in 1 000 million ECU/EUR)"
cap label var DMLD "Imports (in 1 000 million ECU/EUR)"
cap label var STOCKS "Direct investment stocks - Million ECU/EUR"
cap label var FLOWS "Direct investment flows - Million ECU/EUR"
cap label var INCOME "Direct investment income - Million ECU/EUR"
cap label var FGDP "GDP (flows in % of GDP)"
cap label var SGDP "GDP (stocks in % of GDP)"
cap label var IPOS "Rate of return on direct investment (FDI income / FDI stocks)"
cap label var PCPOS "FDI stocks (in % of extra EU FDI stocks)"
cap label var TI100 "Market integration - Trade integration of goods"
cap label var TI200 "Market integration - Trade integration of services"
cap label var TIFDI "Market integration - Foreign Direct Investment intensity - Average value of inward and outward Foreign Direct Investment flows divided by GDP, multiplied by 100"
cap label var TUR "Turnover - Million ECU/EUR"
cap label var EMP "Number of persons employed"
cap label var ENT "Number of enterprises"
cap label var PEC "Personnel costs - Million ECU/EUR"
cap label var GIT "Gross investments in tangible goods - Million ECU/EUR"
cap label var VAC "Value added at factor cost - Million ECU/EUR"
