cap label var T "Total"
cap label var M "Males"
cap label var F "Females"
cap label var DIFF "Absolute difference between males and females"
cap label var NAP "Not applicable"
cap label var NRP "No response"
cap label var UNK "Unknown"
