cap label var TOTAL "Total"
cap label var NAT "National"
cap label var FOR "Foreign country"
cap label var EU_EFTA "EU or EFTA countries"
cap label var NEU_NEFTA "Outside EU or EFTA countries"
cap label var LOC_REG "Local or regional"
cap label var NAT_ONL "National only"
cap label var EU "European Union"
cap label var EU_OTH "Other EU countries"
cap label var EU_EFTA_OTH "Other EU or EFTA countries"
cap label var EU_EFTA_CC_OTH "Other EU, EFTA and Candidate countries"
cap label var EXT "Countries other than EU, EFTA and Candidate countries"
cap label var ROW "Rest of the world"
cap label var UNK "Unknown"
