cap label var TOTAL "Total"
cap label var INN_GE1 "At least one innovation activity"
cap label var INN_XRND_CONTR_OUT "All innovation activities except contracted-out research and development (R&D) (external R&D activities)"
cap label var INNXRND_CONTR_OUT "All innovation activities except contracted-out research and development (R&D) (external R&D activities)"
cap label var RND "Research and development (R&D)"
cap label var RNDINN "Research and development (R&D) or other innovation activities"
cap label var INN_XRND "Other innovation activities excluding research and development (R&D)"
cap label var INNXRND "Other innovation activities excluding research and development (R&D)"
cap label var RND_IH "In-house research and development (R&D)"
cap label var RND_IH_CONT "In-house research and development (R&D) - continously"
cap label var RND_IH_OCC "In-house research and development (R&D) - occasionally"
cap label var RND_IH_CONTR_OUT "In-house or contracted-out research and development (R&D)"
cap label var RND_CONTR_OUT "Contracted-out research and development (R&D)"
cap label var RND_CONTR_OUT_NIH "Contracted-out research and development (R&D), no in-house R&D"
cap label var ACQ_MEBTA "Acquisition of machinery, equipment, buildings and other tangible assets"
cap label var ACQ_MEBS "Acquisition of machinery, equipment, buildings and software"
cap label var ACQ_EKNOW_OTH "Acquisition of existing knowledge from other enterprises or organisations"
cap label var ACQ_TKNOW "Acquisition of technical knowledge"
cap label var ACQ_FINRES "Acquisition of financial resources"
cap label var ACQ_PER "Acquisition of personnel"
cap label var ACQ_BACT "Acquisition of business activities"
cap label var TRF_TKNOW "Transfer of technical knowledge"
cap label var TRF_FINRES "Transfer of financial resources"
cap label var TRF_PER "Transfer of personnel"
cap label var TRF_BACT "Transfer of business activities"
cap label var TNG_MKT_DESG_OTH "Enterprises, engaged in training, market introduction, design or other innovation activities"
cap label var TNG "Training for innovative activities"
cap label var INN_MKT "Market introduction of innovations"
cap label var DESG_SHP "Design activities to alter the shape, appearance or usability of goods or services"
cap label var BACT_OTH "Other business activities"
cap label var OTH "Other innovation activities"
