cap label var TOTAL "Total"
cap label var NSM "Non-smoker"
cap label var NVSM "Never smoked"
cap label var DSM_GE20 "Daily cigarette smoker - 20 or more per day"
cap label var DSM_LT20 "Daily cigarette smoker - less than 20 per day"
cap label var SM_DAY "Daily smoker"
cap label var FSM_DAY "Former daily smoker"
cap label var NVSM_DAY "Never daily smoker"
cap label var SM_LT20D "Less than 20 cigarettes per day"
cap label var SM_GE20D "20 or more cigarettes per day"
cap label var SM_OCC "Occasional smoker"
cap label var SM_CUR "Current smoker"
cap label var NRP "No response"
