cap label var TOTAL "Total"
cap label var INCR "Increase"
cap label var SAME "Same"
cap label var DECR "Decrease"
cap label var SUBS "Substantial change"
cap label var VPOS "Very positive change"
cap label var POS "Positive change"
cap label var MOD "Moderate change"
cap label var NONE "No change"
cap label var NEG "Negative change"
cap label var VNEG "Very negative change"
cap label var NWRK "Did not work"
cap label var NAP "Not applicable"
cap label var NRP "No response"
cap label var UNK "Unknown"
