cap label var IPR "All intellectual property rights (IPRs)"
cap label var PAT_IDESG "Patent or industrial design"
cap label var PAT_TRDM "Patent or trademark"
cap label var PAT "Patent"
cap label var TRDM "Trademark"
cap label var MDL_UTL "Utility model"
cap label var MDL_UTL_EU "European utility model"
cap label var IDESG "Industrial design"
cap label var TRDS "Trade secret"
cap label var CPR "Copyright"
cap label var LIC_INOUT_PURSELL "Licensing-in/out or selling/purchasing"
cap label var LIC_OUT_SELL "Licensing out or selling"
cap label var LIC_OUT "Licensing out"
cap label var SELL "Selling"
cap label var EXCH "Exchanging"
cap label var LIC_IN_PUR "Licensing-in or purchasing"
cap label var LIC_IN_PUR_PRV "Licensing-in or purchasing from private business enterprises"
cap label var LIC_IN_PUR_PUB "Licensing-in or purchasing from public research organisations, universities or other higher education institutions"
