cap label var TOTAL "Total transport"
cap label var NAT_INTL_IEU27_2020 "National transport and international transport intra-EU27 (from 2020)"
cap label var NAT_INTL_IEU28 "National transport and international transport intra-EU28 (2013-2020)"
cap label var NAT "National transport"
cap label var NAT_OCC "National transport - occasional"
cap label var NAT_REG "National transport - regular"
cap label var NAT_URB "National transport - urban"
cap label var NAT_IURB "National transport - interurban"
cap label var INTL "International transport"
cap label var INTL_LD "International transport - loaded"
cap label var INTL_NLD "International transport - unloaded"
cap label var INTL_CTRD "International transport - cross-trade"
cap label var INTL_CAB "International transport - cabotage"
cap label var INTL_IN "International transport - incoming"
cap label var INTL_OUT "International transport - outgoing"
cap label var INTL_OCC "International transport - occasional"
cap label var INTL_REG "International transport - regular"
cap label var INTL_IEU "International transport Intra-EU"
cap label var INTL_IEU27_2020 "International transport Intra-EU27 (from 2020)"
cap label var INTL_IEU28 "International transport Intra-EU28 (2013-2020)"
cap label var INTL_IEU27_2007 "International transport Intra-EU27 (2007-2013)"
cap label var INTL_IEU25 "International transport Intra-EU25 (2004-2006)"
cap label var INTL_IEU15 "International transport Intra-EU15 (1995-2004)"
cap label var INTL_XEU "International transport Extra-EU"
cap label var INTL_XEU27_2020 "International transport Extra-EU27 (from 2020)"
cap label var INTL_XEU28 "International transport Extra-EU28 (2013-2020)"
cap label var INTL_XEU27_2007 "International transport Extra-EU27 (2007-2013)"
cap label var INTL_XEU25 "International transport Extra-EU25 (2004-2006)"
cap label var INTL_XEU15 "International transport Extra-EU15 (1995-2004)"
cap label var TRS "Transit"
cap label var OVFL "Overflown"
cap label var UNK "Unknown"
