cap label var TOTAL "Total - all NACE activities"
cap label var TOT "Total (aggregate changing according to the context)"
cap label var A_F_H_U "All NACE activities (except industry; wholesale and retail trade; repair of motor vehicles and motorcycles)"
cap label var A_T "All NACE activities (except extra-territorial organisations and bodies)"
cap label var A_S "All NACE activities (except activities of households as employers and as own use producers; activities of extra-territorial organisations and bodies)"
cap label var TOT_X_H491_H492 "All NACE activities (except railways)"
cap label var NAFT "All NACE activities (except agriculture, fishing and transport) - Non AFT"
cap label var A_EP_OTH "Agriculture, forestry and fishing; other business sectors (mainly A, E38.3, F41 to U except O)"
cap label var A_B "Agriculture, forestry and fishing; mining and quarrying"
cap label var A_C_N "Agriculture; industry and construction (except mining); services of the business economy"
cap label var A "Agriculture, forestry and fishing"
cap label var A01_A03_FOOD "Primary production of food - agriculture, fishing and aquaculture"
cap label var A01_A02 "Agriculture and forestry"
cap label var AFT "Agriculture, fishing and transport (except railways) - AFT"
cap label var A01_A02_X_A017 "Agriculture and forestry (except hunting)"
cap label var A01 "Crop and animal production, hunting and related service activities"
cap label var A01_IRR "Irrigation in agriculture"
cap label var A011 "Growing of non-perennial crops"
cap label var A0111 "Growing of cereals (except rice), leguminous crops and oil seeds"
cap label var A0112 "Growing of rice"
cap label var A0113 "Growing of vegetables and melons, roots and tubers"
cap label var A0114 "Growing of sugar cane"
cap label var A0115 "Growing of tobacco"
cap label var A0116 "Growing of fibre crops"
cap label var A0119 "Growing of other non-perennial crops"
cap label var A012 "Growing of perennial crops"
cap label var A0121 "Growing of grapes"
cap label var A0122 "Growing of tropical and subtropical fruits"
cap label var A0123 "Growing of citrus fruits"
cap label var A0124 "Growing of pome fruits and stone fruits"
cap label var A0125 "Growing of other tree and bush fruits and nuts"
cap label var A0126 "Growing of oleaginous fruits"
cap label var A0127 "Growing of beverage crops"
cap label var A0128 "Growing of spices, aromatic, drug and pharmaceutical crops"
cap label var A0129 "Growing of other perennial crops"
cap label var A013 "Plant propagation"
cap label var A0130 "Plant propagation"
cap label var A014 "Animal production"
cap label var A0141 "Raising of dairy cattle"
cap label var A0142 "Raising of other cattle and buffaloes"
cap label var A0143 "Raising of horses and other equines"
cap label var A0144 "Raising of camels and camelids"
cap label var A0145 "Raising of sheep and goats"
cap label var A0146 "Raising of swine/pigs"
cap label var A0147 "Raising of poultry"
cap label var A0149 "Raising of other animals"
cap label var A015 "Mixed farming"
cap label var A0150 "Mixed farming"
cap label var A016 "Support activities to agriculture and post-harvest crop activities"
cap label var A0161 "Support activities for crop production"
cap label var A0162 "Support activities for animal production"
cap label var A0163 "Post-harvest crop activities"
cap label var A0164 "Seed processing for propagation"
cap label var A017 "Hunting, trapping and related service activities"
cap label var A0170 "Hunting, trapping and related service activities"
cap label var A02 "Forestry and logging"
cap label var A021 "Silviculture and other forestry activities"
cap label var A0210 "Silviculture and other forestry activities"
cap label var A022 "Logging"
cap label var A0220 "Logging"
cap label var A023 "Gathering of wild growing non-wood products"
cap label var A0230 "Gathering of wild growing non-wood products"
cap label var A024 "Support services to forestry"
cap label var A0240 "Support services to forestry"
cap label var A03 "Fishing and aquaculture"
cap label var A031 "Fishing"
cap label var A0311 "Marine fishing"
cap label var A0312 "Freshwater fishing"
cap label var A032 "Aquaculture"
cap label var A0321 "Marine aquaculture"
cap label var A0322 "Freshwater aquaculture"
cap label var B_U "Industry, construction and services"
cap label var B_T "Industry, construction and services (except extra-territorial organisations and bodies)"
cap label var B_S "Industry, construction and services (except activities of households as employers and extra-territorial organisations and bodies)"
cap label var B_S_X_O "Industry, construction and services (except public administration, defense, compulsory social security)"
cap label var B_S_X_O_S94 "Industry, construction and market services (except public administration and defence; compulsory social security; activities of membership organisations)"
cap label var B_S_X_K642 "Industry, construction and services except insurance activities of holding companies"
cap label var B_N_R_S "Business economy; arts, entertainment and recreation; other service activities"
cap label var B_N "Business economy"
cap label var B_N_S95 "Total business economy; repair of computers, personal and household goods"
cap label var B_N_S95_X_K "Total business economy; repair of computers, personal and household goods; except financial and insurance activities"
cap label var B_N_X_K "Total business economy except financial and insurance activities"
cap label var B_N_X_K642 "Business economy except activities of holding companies"
cap label var B_M71_INN "Innovation core activities (Com.Reg. 1450/2004)"
cap label var B_M73_INN "Innovation core activities (Com.Reg. 995/2012)"
cap label var B_F "Industry and construction"
cap label var B_F_X_C "Industry and construction (except manufacturing)"
cap label var B_F_X_D "Industry and construction (except electricity, gas, steam and air conditioning supply)"
cap label var B_E36_F "Industry and construction (except sewerage, waste management and remediation activities)"
cap label var B_E "Industry (except construction)"
cap label var B_E36 "Industry (except construction, sewerage, waste management and remediation activities)"
cap label var B_E36_X_FOOD "Industry (except construction, sewerage, waste management and remediation activities), except food, beverages and tobacco"
cap label var B_D_F "Mining and quarrying; manufacturing; electricity, gas, steam and air conditioning supply; construction"
cap label var B_D_F_XB0721 "Mining and quarrying, electricity, gas, water supply, construction (except mining of uranium)"
cap label var B_D_E "Mining and quarrying; electricity, gas, steam and air conditioning supply; water supply, sewerage, waste management and remediation activities"
cap label var B_D "Mining and quarrying; manufacturing; electricity, gas, steam and air conditioning supply"
cap label var B_D_X_FOOD "Mining and quarrying; manufacturing; electricity, gas, steam and air conditioning supply (except food, beverages and tobacco)"
cap label var B_C "Mining and quarrying; manufacturing"
cap label var B_C_X_FOOD "Mining and quarrying; manufacturing (except food, beverages and tobacco)"
cap label var B_C_X_MIG_NRG "Mining and quarrying; manufacturing (except MIG energy)"
cap label var B_C_X_FD_MIG_NRG "Mining and quarrying; manufacturing (except MIG energy), except food, beverages and tobacco"
cap label var KIA "Total knowledge-intensive activities"
cap label var KIABI "Knowledge-intensive activities - business industries"
cap label var KIABI_X_K_R90 "Non-financial knowledge-intensive activities - business industries"
cap label var MIG_ING_CAG "MIG - intermediate and capital goods"
cap label var MIG_ING_ORD "MIG - intermediate goods, for new orders"
cap label var MIG_ING "MIG - intermediate goods"
cap label var MIG_NRG "MIG - energy"
cap label var MIG_NRG_X_E "MIG - energy (except section E)"
cap label var MIG_NRG_X_D_E "MIG - energy (except sections D and E)"
cap label var MIG_CAG "MIG - capital goods"
cap label var MIG_CAG_ORD "MIG - capital goods, for new orders"
cap label var MIG_COG "MIG - consumer goods"
cap label var MIG_COG_X_FOOD "MIG - consumer goods (except food, beverages and tobacco)"
cap label var MIG_COG_ORD "MIG - consumer goods, for new orders"
cap label var MIG_DCOG "MIG - durable consumer goods"
cap label var MIG_DCOG_ORD "MIG - durable consumer goods, for new orders"
cap label var MIG_NDCOG "MIG - non-durable consumer goods"
cap label var MIG_NDCOG_ORD "MIG - non-durable consumer goods, for new orders"
cap label var B "Mining and quarrying"
cap label var B05 "Mining of coal and lignite"
cap label var B051 "Mining of hard coal"
cap label var B0510 "Mining of hard coal"
cap label var B052 "Mining of lignite"
cap label var B0520 "Mining of lignite"
cap label var B06__B09 "Mining and quarrying, except mining of coal and lignite"
cap label var B06_B09 "Extraction of crude petroleum and natural gas; mining support service activities"
cap label var B06 "Extraction of crude petroleum and natural gas"
cap label var B061 "Extraction of crude petroleum"
cap label var B0610 "Extraction of crude petroleum"
cap label var B062 "Extraction of natural gas"
cap label var B0620 "Extraction of natural gas"
cap label var B07_B09_X_EPRD "Mining, quarrying and mining support service activities except those related to energy products (uranium and thorium ores, peat, petroleum and natural gas)"
cap label var B07 "Mining of metal ores"
cap label var B07_X_B0721 "Mining of metal ores except mining of uranium and thorium ores"
cap label var B071 "Mining of iron ores"
cap label var B0710 "Mining of iron ores"
cap label var B072 "Mining of non-ferrous metal ores"
cap label var B0721 "Mining of uranium and thorium ores"
cap label var B0729 "Mining of other non-ferrous metal ores"
cap label var B08 "Other mining and quarrying"
cap label var B08_X_B0892 "Other mining and quarrying except extraction of peat"
cap label var B081 "Quarrying of stone, sand and clay"
cap label var B0811 "Quarrying of ornamental and building stone, limestone, gypsum, chalk and slate"
cap label var B0812 "Operation of gravel and sand pits; mining of clays and kaolin"
cap label var B089 "Mining and quarrying n.e.c."
cap label var B0891 "Mining of chemical and fertiliser minerals"
cap label var B0892 "Extraction of peat"
cap label var B0893 "Extraction of salt"
cap label var B0899 "Other mining and quarrying n.e.c."
cap label var B09 "Mining support service activities"
cap label var B091 "Support activities for petroleum and natural gas extraction"
cap label var B0910 "Support activities for petroleum and natural gas extraction"
cap label var B099 "Support activities for other mining and quarrying"
cap label var B0990 "Support activities for other mining and quarrying"
cap label var C_F "Manufacturing, electricity, gas, steam and air conditioning supply; water supply and construction"
cap label var C_E "Manufacturing, electricity, gas, steam and air conditioning; water supply, sewerage, waste management and remediation activities"
cap label var C_D "Manufacturing; electricity, gas, steam and air conditioning supply"
cap label var HTC "High-technology sectors (high-technology manufacturing and knowledge-intensive high-technology services)"
cap label var C "Manufacturing"
cap label var C_CL "Manufacturing - for cooling purposes"
cap label var C_HTC_MH "High and medium high-technology manufacturing"
cap label var C_HTC_M "Medium high-technology manufacturing"
cap label var C_HTC "High-technology manufacturing"
cap label var C_LTC_LM "Low and medium low-technology manufacturing"
cap label var C_LTC_M "Medium low-technology manufacturing"
cap label var C_LTC "Low-technology manufacturing"
cap label var C_ORD "Manufacturing, for new orders"
cap label var C_ORD_X_C30 "Manufacturing, for new orders (except heavy transport equipment)"
cap label var C_X_STEEL "Manufacturing (except steel and building of ships and boats)"
cap label var C10_S951_X_K "All activities, without financial sector"
cap label var C10_C18 "Manufacture of products based on: food, beverages, tobacco, textile, leather, wood, pulp and paper; publishing and printing"
cap label var C10_C12 "Manufacture of food products; beverages and tobacco products"
cap label var C10_C11 "Manufacture of food products and beverages"
cap label var C10 "Manufacture of food products"
cap label var C101 "Processing and preserving of meat and production of meat products"
cap label var C101_PRC "Processing of meat and production of meat products"
cap label var C101_PRS "Preserving of meat and production of meat products"
cap label var C1011 "Processing and preserving of meat"
cap label var C1012 "Processing and preserving of poultry meat"
cap label var C1013 "Production of meat and poultry meat products"
cap label var C102 "Processing and preserving of fish, crustaceans and molluscs"
cap label var C1020 "Processing and preserving of fish, crustaceans and molluscs"
cap label var C102_PRC "Processing of fish, crustaceans and molluscs"
cap label var C102_PRS "Preserving of fish, crustaceans and molluscs"
cap label var C103 "Processing and preserving of fruit and vegetables"
cap label var C103_PRC "Processing of fruit and vegetables"
cap label var C103_PRS "Preserving of fruit and vegetables"
cap label var C1031 "Processing and preserving of potatoes"
cap label var C1032 "Manufacture of fruit and vegetable juice"
cap label var C1039 "Other processing and preserving of fruit and vegetables"
cap label var C104 "Manufacture of vegetable and animal oils and fats"
cap label var C104_PRC "Manufacture of vegetable and animal oils and fats (processing)"
cap label var C104_PRS "Manufacture of vegetable and animal oils and fats (preserving)"
cap label var C1041 "Manufacture of oils and fats"
cap label var C1042 "Manufacture of margarine and similar edible fats"
cap label var C105 "Manufacture of dairy products"
cap label var C105_PRC "Manufacture of dairy products (processing)"
cap label var C105_PRS "Manufacture of dairy products (preserving)"
cap label var C1051 "Operation of dairies and cheese making"
cap label var C1052 "Manufacture of ice cream"
cap label var C106 "Manufacture of grain mill products, starches and starch products"
cap label var C106_PRC "Manufacture of grain mill products, starches and starch products (processing)"
cap label var C106_PRS "Manufacture of grain mill products, starches and starch products (preserving)"
cap label var C1061 "Manufacture of grain mill products"
cap label var C1062 "Manufacture of starches and starch products"
cap label var C107 "Manufacture of bakery and farinaceous products"
cap label var C1071 "Manufacture of bread; manufacture of fresh pastry goods and cakes"
cap label var C1072 "Manufacture of rusks and biscuits; manufacture of preserved pastry goods and cakes"
cap label var C1073 "Manufacture of macaroni, noodles, couscous and similar farinaceous products"
cap label var C108 "Manufacture of other food products"
cap label var C108_PRC "Manufacture of other food products (processing)"
cap label var C108_PRS "Manufacture of other food products (preserving)"
cap label var C1081 "Manufacture of sugar"
cap label var C1082 "Manufacture of cocoa, chocolate and sugar confectionery"
cap label var C1083 "Processing of tea and coffee"
cap label var C1084 "Manufacture of condiments and seasonings"
cap label var C1085 "Manufacture of prepared meals and dishes"
cap label var C1086 "Manufacture of homogenised food preparations and dietetic food"
cap label var C1089 "Manufacture of other food products n.e.c."
cap label var C109 "Manufacture of prepared animal feeds"
cap label var C109_PRC "Manufacture of prepared animal feeds (processing)"
cap label var C109_PRS "Manufacture of prepared animal feeds (preserving)"
cap label var C1091 "Manufacture of prepared feeds for farm animals"
cap label var C1092 "Manufacture of prepared pet foods"
cap label var C11 "Manufacture of beverages"
cap label var C110 "Manufacture of beverages"
cap label var C1101 "Distilling, rectifying and blending of spirits"
cap label var C1102 "Manufacture of wine from grape"
cap label var C1103 "Manufacture of cider and other fruit wines"
cap label var C1104 "Manufacture of other non-distilled fermented beverages"
cap label var C1105 "Manufacture of beer"
cap label var C1106 "Manufacture of malt"
cap label var C1107 "Manufacture of soft drinks; production of mineral waters and other bottled waters"
cap label var C12 "Manufacture of tobacco products"
cap label var C120 "Manufacture of tobacco products"
cap label var C1200 "Manufacture of tobacco products"
cap label var C_TXW "Manufacture of textiles, wearing apparel, wood and paper products; printing and reproduction"
cap label var C13_C16_C18_C31_C33 "Manufacture of textiles, wearing apparel, leather and related products, wood, printing and reproduction, furniture; jewellery, musical instruments, toys; repair and installation of machinery and equipment"
cap label var C13_C15 "Manufacture of textiles, wearing apparel, leather and related products"
cap label var C13_C14 "Manufacture of textiles and wearing apparel"
cap label var C13 "Manufacture of textiles"
cap label var C131 "Preparation and spinning of textile fibres"
cap label var C1310 "Preparation and spinning of textile fibres"
cap label var C132 "Weaving of textiles"
cap label var C1320 "Weaving of textiles"
cap label var C133 "Finishing of textiles"
cap label var C1330 "Finishing of textiles"
cap label var C139 "Manufacture of other textiles"
cap label var C1391 "Manufacture of knitted and crocheted fabrics"
cap label var C1392 "Manufacture of made-up textile articles, except apparel"
cap label var C1393 "Manufacture of carpets and rugs"
cap label var C1394 "Manufacture of cordage, rope, twine and netting"
cap label var C1395 "Manufacture of non-wovens and articles made from non-wovens, except apparel"
cap label var C1396 "Manufacture of other technical and industrial textiles"
cap label var C1399 "Manufacture of other textiles n.e.c."
cap label var C14 "Manufacture of wearing apparel"
cap label var C141 "Manufacture of wearing apparel, except fur apparel"
cap label var C1411 "Manufacture of leather clothes"
cap label var C1412 "Manufacture of workwear"
cap label var C1413 "Manufacture of other outerwear"
cap label var C1414 "Manufacture of underwear"
cap label var C1419 "Manufacture of other wearing apparel and accessories"
cap label var C142 "Manufacture of articles of fur"
cap label var C1420 "Manufacture of articles of fur"
cap label var C143 "Manufacture of knitted and crocheted apparel"
cap label var C1431 "Manufacture of knitted and crocheted hosiery"
cap label var C1439 "Manufacture of other knitted and crocheted apparel"
cap label var C15 "Manufacture of leather and related products"
cap label var C151 "Tanning and dressing of leather; manufacture of luggage, handbags, saddlery and harness; dressing and dyeing of fur"
cap label var C1511 "Tanning and dressing of leather; dressing and dyeing of fur"
cap label var C1512 "Manufacture of luggage, handbags and the like, saddlery and harness"
cap label var C152 "Manufacture of footwear"
cap label var C1520 "Manufacture of footwear"
cap label var C16_C18 "Manufacture of wood, paper, printing and reproduction"
cap label var C16 "Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials"
cap label var C161 "Sawmilling and planing of wood"
cap label var C1610 "Sawmilling and planing of wood"
cap label var C162 "Manufacture of products of wood, cork, straw and plaiting materials"
cap label var C1621 "Manufacture of veneer sheets and wood-based panels"
cap label var C1622 "Manufacture of assembled parquet floors"
cap label var C1623 "Manufacture of other builders' carpentry and joinery"
cap label var C1624 "Manufacture of wooden containers"
cap label var C1629 "Manufacture of other products of wood; manufacture of articles of cork, straw and plaiting materials"
cap label var C17_C18 "Manufacture of paper and paper products; printing and reproduction of recorded media"
cap label var C17 "Manufacture of paper and paper products"
cap label var C17_X_C1711 "Manufacture of paper and paper products except pulp"
cap label var C171 "Manufacture of pulp, paper and paperboard"
cap label var C1711 "Manufacture of pulp"
cap label var C1712 "Manufacture of paper and paperboard"
cap label var C172 "Manufacture of articles of paper and paperboard"
cap label var C1721 "Manufacture of corrugated paper and paperboard and of containers of paper and paperboard"
cap label var C1722 "Manufacture of household and sanitary goods and of toilet requisites"
cap label var C1723 "Manufacture of paper stationery"
cap label var C1724 "Manufacture of wallpaper"
cap label var C1729 "Manufacture of other articles of paper and paperboard"
cap label var C18 "Printing and reproduction of recorded media"
cap label var C181 "Printing and service activities related to printing"
cap label var C1811 "Printing of newspapers"
cap label var C1812 "Other printing"
cap label var C1813 "Pre-press and pre-media services"
cap label var C1814 "Binding and related services"
cap label var C182 "Reproduction of recorded media"
cap label var C1820 "Reproduction of recorded media"
cap label var C19_C23 "Manufacture of coke, refined petroleum, chemical and basic pharmaceutical products, rubber and plastics, other non-metallic mineral products"
cap label var C19_C22 "Manufacture of petroleum, chemical, pharmaceutical, rubber and plastic products"
cap label var C19_C21 "Manufacture of coke and refined petroleum product; chemicals and chemical products; basic pharmaceutical products and pharmaceutical preparations"
cap label var C19_C20 "Manufacture of coke and refined petroleum products, chemicals and chemical products"
cap label var C19 "Manufacture of coke and refined petroleum products"
cap label var C191 "Manufacture of coke oven products"
cap label var C1910 "Manufacture of coke oven products"
cap label var C192_C20 "Manufacture of refined petroleum products, chemicals and chemical products"
cap label var C192 "Manufacture of refined petroleum products"
cap label var C1920 "Manufacture of refined petroleum products"
cap label var C20_C22 "Manufacture of chemical, pharmaceutical, rubber and plastic products"
cap label var C20_C21 "Manufacture of chemicals and chemical products; basic pharmaceutical products and pharmaceutical preparations"
cap label var C20 "Manufacture of chemicals and chemical products"
cap label var C201 "Manufacture of basic chemicals, fertilisers and nitrogen compounds, plastics and synthetic rubber in primary forms"
cap label var C2011 "Manufacture of industrial gases"
cap label var C2012 "Manufacture of dyes and pigments"
cap label var C2013 "Manufacture of other inorganic basic chemicals"
cap label var C2014 "Manufacture of other organic basic chemicals"
cap label var C2015 "Manufacture of fertilisers and nitrogen compounds"
cap label var C2016 "Manufacture of plastics in primary forms"
cap label var C2017 "Manufacture of synthetic rubber in primary forms"
cap label var C202 "Manufacture of pesticides and other agrochemical products"
cap label var C2020 "Manufacture of pesticides and other agrochemical products"
cap label var C203 "Manufacture of paints, varnishes and similar coatings, printing ink and mastics"
cap label var C2030 "Manufacture of paints, varnishes and similar coatings, printing ink and mastics"
cap label var C204 "Manufacture of soap and detergents, cleaning and polishing preparations, perfumes and toilet preparations"
cap label var C2041 "Manufacture of soap and detergents, cleaning and polishing preparations"
cap label var C2042 "Manufacture of perfumes and toilet preparations"
cap label var C205 "Manufacture of other chemical products"
cap label var C2051 "Manufacture of explosives"
cap label var C2052 "Manufacture of glues"
cap label var C2053 "Manufacture of essential oils"
cap label var C2059 "Manufacture of other chemical products n.e.c."
cap label var C206 "Manufacture of man-made fibres"
cap label var C2060 "Manufacture of man-made fibres"
cap label var C21_C23 "Manufacture of basic pharmaceutical products and pharmaceutical preparations, rubber and plastic products and other non-metallic mineral products"
cap label var C21 "Manufacture of basic pharmaceutical products and pharmaceutical preparations"
cap label var C211 "Manufacture of basic pharmaceutical products"
cap label var C2110 "Manufacture of basic pharmaceutical products"
cap label var C212 "Manufacture of pharmaceutical preparations"
cap label var C2120 "Manufacture of pharmaceutical preparations"
cap label var C22_C31_C32 "Manufacture of rubber, plastic products, furniture and other manufacturing"
cap label var C22_C23 "Manufacture of rubber and plastic products and other non-metallic mineral products"
cap label var C22 "Manufacture of rubber and plastic products"
cap label var C221 "Manufacture of rubber products"
cap label var C2211 "Manufacture of rubber tyres and tubes; retreading and rebuilding of rubber tyres"
cap label var C2219 "Manufacture of other rubber products"
cap label var C222 "Manufacture of plastics products"
cap label var C2221 "Manufacture of plastic plates, sheets, tubes and profiles"
cap label var C2222 "Manufacture of plastic packing goods"
cap label var C2223 "Manufacture of builders' ware of plastic"
cap label var C2229 "Manufacture of other plastic products"
cap label var C23 "Manufacture of other non-metallic mineral products"
cap label var C23_X_C231_C235 "Manufacture of other non-metallic mineral products except glass, glass products, cement, lime and plaster"
cap label var C231 "Manufacture of glass and glass products"
cap label var C2311 "Manufacture of flat glass"
cap label var C2312 "Shaping and processing of flat glass"
cap label var C2313 "Manufacture of hollow glass"
cap label var C2314 "Manufacture of glass fibres"
cap label var C2319 "Manufacture and processing of other glass, including technical glassware"
cap label var C232 "Manufacture of refractory products"
cap label var C2320 "Manufacture of refractory products"
cap label var C233 "Manufacture of clay building materials"
cap label var C2331 "Manufacture of ceramic tiles and flags"
cap label var C2332 "Manufacture of bricks, tiles and construction products, in baked clay"
cap label var C234 "Manufacture of other porcelain and ceramic products"
cap label var C2341 "Manufacture of ceramic household and ornamental articles"
cap label var C2342 "Manufacture of ceramic sanitary fixtures"
cap label var C2343 "Manufacture of ceramic insulators and insulating fittings"
cap label var C2344 "Manufacture of other technical ceramic products"
cap label var C2349 "Manufacture of other ceramic products"
cap label var C235 "Manufacture of cement, lime and plaster"
cap label var C2351 "Manufacture of cement"
cap label var C2352 "Manufacture of lime and plaster"
cap label var C236 "Manufacture of articles of concrete, cement and plaster"
cap label var C2361 "Manufacture of concrete products for construction purposes"
cap label var C2362 "Manufacture of plaster products for construction purposes"
cap label var C2363 "Manufacture of ready-mixed concrete"
cap label var C2364 "Manufacture of mortars"
cap label var C2365 "Manufacture of fibre cement"
cap label var C2369 "Manufacture of other articles of concrete, plaster and cement"
cap label var C237 "Cutting, shaping and finishing of stone"
cap label var C2370 "Cutting, shaping and finishing of stone"
cap label var C239 "Manufacture of abrasive products and non-metallic mineral products n.e.c."
cap label var C2391 "Production of abrasive products"
cap label var C2399 "Manufacture of other non-metallic mineral products n.e.c."
cap label var C_MET "Manufacture of metal and machinery products, except electrical equipment"
cap label var C24_C25 "Manufacture of basic metals and fabricated metal products, except machinery and equipment"
cap label var C24 "Manufacture of basic metals"
cap label var C24_FER "Manufacture of basic iron and steel and of ferro-alloys; of tubes, pipes, hollow profiles, related fittings and other products of first processing of steel; casting of iron and steel"
cap label var C241_C243_C2451_C2452 "Manufacturing activities related to iron and steel"
cap label var C241 "Manufacture of basic iron and steel and of ferro-alloys"
cap label var C2410 "Manufacture of basic iron and steel and of ferro-alloys"
cap label var C241_C2452 "Steel"
cap label var C242 "Manufacture of tubes, pipes, hollow profiles and related fittings, of steel"
cap label var C2420 "Manufacture of tubes, pipes, hollow profiles and related fittings, of steel"
cap label var C243 "Manufacture of other products of first processing of steel"
cap label var C2431 "Cold drawing of bars"
cap label var C2432 "Cold rolling of narrow strip"
cap label var C2433 "Cold forming or folding"
cap label var C2434 "Cold drawing of wire"
cap label var C24_NFER "Manufacture of basic precious and other non-ferrous metals; casting of light metals and other non-ferrous metals"
cap label var C244_C2453_C2454 "Manufacture of basic precious and other non-ferrous metals, casting of light metals and of other non-ferrous metals"
cap label var C244 "Manufacture of basic precious and other non-ferrous metals"
cap label var C244_X_C2442 "Manufacture of basic precious and other non-ferrous metals except aluminium production"
cap label var C2441 "Precious metals production"
cap label var C2442 "Aluminium production"
cap label var C2443 "Lead, zinc and tin production"
cap label var C2444 "Copper production"
cap label var C2445 "Other non-ferrous metal production"
cap label var C2446 "Processing of nuclear fuel"
cap label var C245 "Casting of metals"
cap label var C2451 "Casting of iron"
cap label var C2452 "Casting of steel"
cap label var C2453 "Casting of light metals"
cap label var C2454 "Casting of other non-ferrous metals"
cap label var C25_C33 "Manufacture of metal products and other equipment"
cap label var C25_C28 "Manufacture of fabricated metal products, computer, electronic and optical products, electrical equipment, machinery and equipment n.e.c."
cap label var C25 "Manufacture of fabricated metal products, except machinery and equipment"
cap label var C25_X_C254 "Manufacture of fabricated metal products, except weapons and ammunition, machinery and equipment"
cap label var C251 "Manufacture of structural metal products"
cap label var C2511 "Manufacture of metal structures and parts of structures"
cap label var C2512 "Manufacture of doors and windows of metal"
cap label var C252 "Manufacture of tanks, reservoirs and containers of metal"
cap label var C2521 "Manufacture of central heating radiators and boilers"
cap label var C2529 "Manufacture of other tanks, reservoirs and containers of metal"
cap label var C253 "Manufacture of steam generators, except central heating hot water boilers"
cap label var C2530 "Manufacture of steam generators, except central heating hot water boilers"
cap label var C254 "Manufacture of weapons and ammunition"
cap label var C2540 "Manufacture of weapons and ammunition"
cap label var C255 "Forging, pressing, stamping and roll-forming of metal; powder metallurgy"
cap label var C2550 "Forging, pressing, stamping and roll-forming of metal; powder metallurgy"
cap label var C256 "Treatment and coating of metals; machining"
cap label var C2561 "Treatment and coating of metals"
cap label var C2562 "Machining"
cap label var C257 "Manufacture of cutlery, tools and general hardware"
cap label var C2571 "Manufacture of cutlery"
cap label var C2572 "Manufacture of locks and hinges"
cap label var C2573 "Manufacture of tools"
cap label var C259 "Manufacture of other fabricated metal products"
cap label var C2591 "Manufacture of steel drums and similar containers"
cap label var C2592 "Manufacture of light metal packaging"
cap label var C2593 "Manufacture of wire products, chain and springs"
cap label var C2594 "Manufacture of fasteners and screw machine products"
cap label var C2599 "Manufacture of other fabricated metal products n.e.c."
cap label var C25_C30 "Manufacture of fabricated metal products, computer, electronic and optical products, electrical equipment, machinery, motor vehicles and other transport equipment"
cap label var C26_C33 "Manufacture of computers, electric and optical products, electrical equipment, machinery and equipment n.e.c, motor vehicles, other transport equipment, furniture, other manufacturing, repair and installation of machinery and equipment"
cap label var C26_C30 "Manufacture of computer, electronic and optical products, electrical equipment, motor vehicles and other transport equipment"
cap label var C26_C28 "Manufacture of computer, electronic and optical products, electrical equipment, machinery and equipment n.e.c."
cap label var C26_C27 "Manufacture of computer, electronic and optical products; manufacture of electrical equipment"
cap label var C26 "Manufacture of computer, electronic and optical products"
cap label var C261 "Manufacture of electronic components and boards"
cap label var C2611 "Manufacture of electronic components"
cap label var C2612 "Manufacture of loaded electronic boards"
cap label var C262 "Manufacture of computers and peripheral equipment"
cap label var C2620 "Manufacture of computers and peripheral equipment"
cap label var C263_C264 "Manufacture of communication equipment and consumer electronics"
cap label var C263 "Manufacture of communication equipment"
cap label var C2630 "Manufacture of communication equipment"
cap label var C264 "Manufacture of consumer electronics"
cap label var C2640 "Manufacture of consumer electronics"
cap label var C265_C266 "Manufacture of instruments and appliances for measuring, testing and navigation; watches and clocks; manufacture of irradiation, electromedical and electrotherapeutic equipment"
cap label var C265 "Manufacture of instruments and appliances for measuring, testing and navigation; watches and clocks"
cap label var C2651 "Manufacture of instruments and appliances for measuring, testing and navigation"
cap label var C2652 "Manufacture of watches and clocks"
cap label var C266 "Manufacture of irradiation, electromedical and electrotherapeutic equipment"
cap label var C2660 "Manufacture of irradiation, electromedical and electrotherapeutic equipment"
cap label var C267 "Manufacture of optical instruments and photographic equipment"
cap label var C2670 "Manufacture of optical instruments and photographic equipment"
cap label var C268 "Manufacture of magnetic and optical media"
cap label var C2680 "Manufacture of magnetic and optical media"
cap label var C27_C28 "Manufacture of electrical equipment, machinery and equipment n.e.c."
cap label var C27 "Manufacture of electrical equipment"
cap label var C271 "Manufacture of electric motors, generators, transformers and electricity distribution and control apparatus"
cap label var C2711 "Manufacture of electric motors, generators and transformers"
cap label var C2712 "Manufacture of electricity distribution and control apparatus"
cap label var C272 "Manufacture of batteries and accumulators"
cap label var C2720 "Manufacture of batteries and accumulators"
cap label var C273 "Manufacture of wiring and wiring devices"
cap label var C2731 "Manufacture of fibre optic cables"
cap label var C2732 "Manufacture of other electronic and electric wires and cables"
cap label var C2733 "Manufacture of wiring devices"
cap label var C274 "Manufacture of electric lighting equipment"
cap label var C2740 "Manufacture of electric lighting equipment"
cap label var C275 "Manufacture of domestic appliances"
cap label var C2751 "Manufacture of electric domestic appliances"
cap label var C2752 "Manufacture of non-electric domestic appliances"
cap label var C279 "Manufacture of other electrical equipment"
cap label var C2790 "Manufacture of other electrical equipment"
cap label var C28 "Manufacture of machinery and equipment n.e.c."
cap label var C281 "Manufacture of general-purpose machinery"
cap label var C2811 "Manufacture of engines and turbines, except aircraft, vehicle and cycle engines"
cap label var C2812 "Manufacture of fluid power equipment"
cap label var C2813 "Manufacture of other pumps and compressors"
cap label var C2814 "Manufacture of other taps and valves"
cap label var C2815 "Manufacture of bearings, gears, gearing and driving elements"
cap label var C282 "Manufacture of other general-purpose machinery"
cap label var C2821 "Manufacture of ovens, furnaces and furnace burners"
cap label var C2822 "Manufacture of lifting and handling equipment"
cap label var C2823 "Manufacture of office machinery and equipment (except computers and peripheral equipment)"
cap label var C2824 "Manufacture of power-driven hand tools"
cap label var C2825 "Manufacture of non-domestic cooling and ventilation equipment"
cap label var C2829 "Manufacture of other general-purpose machinery n.e.c."
cap label var C283 "Manufacture of agricultural and forestry machinery"
cap label var C2830 "Manufacture of agricultural and forestry machinery"
cap label var C284 "Manufacture of metal forming machinery and machine tools"
cap label var C2841 "Manufacture of metal forming machinery"
cap label var C2849 "Manufacture of other machine tools"
cap label var C289 "Manufacture of other special-purpose machinery"
cap label var C2891 "Manufacture of machinery for metallurgy"
cap label var C2892 "Manufacture of machinery for mining, quarrying and construction"
cap label var C2893 "Manufacture of machinery for food, beverage and tobacco processing"
cap label var C2894 "Manufacture of machinery for textile, apparel and leather production"
cap label var C2895 "Manufacture of machinery for paper and paperboard production"
cap label var C2896 "Manufacture of plastics and rubber machinery"
cap label var C2899 "Manufacture of other special-purpose machinery n.e.c."
cap label var C29_C30 "Manufacture of motor vehicles, trailers, semi-trailers and of other transport equipment"
cap label var C29 "Manufacture of motor vehicles, trailers and semi-trailers"
cap label var C291 "Manufacture of motor vehicles"
cap label var C2910 "Manufacture of motor vehicles"
cap label var C292 "Manufacture of bodies (coachwork) for motor vehicles; manufacture of trailers and semi-trailers"
cap label var C2920 "Manufacture of bodies (coachwork) for motor vehicles; manufacture of trailers and semi-trailers"
cap label var C293 "Manufacture of parts and accessories for motor vehicles"
cap label var C2931 "Manufacture of electrical and electronic equipment for motor vehicles"
cap label var C2932 "Manufacture of other parts and accessories for motor vehicles"
cap label var C30 "Manufacture of other transport equipment"
cap label var C301 "Building of ships and boats"
cap label var C3011 "Building of ships and floating structures"
cap label var C3012 "Building of pleasure and sporting boats"
cap label var C302 "Manufacture of railway locomotives and rolling stock"
cap label var C3020 "Manufacture of railway locomotives and rolling stock"
cap label var C303 "Manufacture of air and spacecraft and related machinery"
cap label var C3030 "Manufacture of air and spacecraft and related machinery"
cap label var C304 "Manufacture of military fighting vehicles"
cap label var C3040 "Manufacture of military fighting vehicles"
cap label var C309 "Manufacture of transport equipment n.e.c."
cap label var C3091 "Manufacture of motorcycles"
cap label var C3092 "Manufacture of bicycles and invalid carriages"
cap label var C3099 "Manufacture of other transport equipment n.e.c."
cap label var C31_C33 "Manufacture of furniture; jewellery, musical instruments, toys; repair and installation of machinery and equipment"
cap label var C31_C32 "Manufacture of furniture; other manufacturing"
cap label var C31 "Manufacture of furniture"
cap label var C310 "Manufacture of furniture"
cap label var C3101 "Manufacture of office and shop furniture"
cap label var C3102 "Manufacture of kitchen furniture"
cap label var C3103 "Manufacture of mattresses"
cap label var C3109 "Manufacture of other furniture"
cap label var C32 "Other manufacturing"
cap label var C32_X_C325 "Other manufacturing except medical and dental instruments and supplies"
cap label var C321 "Manufacture of jewellery, bijouterie and related articles"
cap label var C3211 "Striking of coins"
cap label var C3212 "Manufacture of jewellery and related articles"
cap label var C3213 "Manufacture of imitation jewellery and related articles"
cap label var C322 "Manufacture of musical instruments"
cap label var C3220 "Manufacture of musical instruments"
cap label var C323 "Manufacture of sports goods"
cap label var C3230 "Manufacture of sports goods"
cap label var C324 "Manufacture of games and toys"
cap label var C3240 "Manufacture of games and toys"
cap label var C325 "Manufacture of medical and dental instruments and supplies"
cap label var C3250 "Manufacture of medical and dental instruments and supplies"
cap label var C329 "Manufacturing n.e.c."
cap label var C3291 "Manufacture of brooms and brushes"
cap label var C3299 "Other manufacturing n.e.c."
cap label var C33 "Repair and installation of machinery and equipment"
cap label var C331 "Repair of fabricated metal products, machinery and equipment"
cap label var C3311 "Repair of fabricated metal products"
cap label var C3312 "Repair of machinery"
cap label var C3313 "Repair of electronic and optical equipment"
cap label var C3314 "Repair of electrical equipment"
cap label var C3315 "Repair and maintenance of ships and boats"
cap label var C3316 "Repair and maintenance of aircraft and spacecraft"
cap label var C3317 "Repair and maintenance of other transport equipment"
cap label var C3319 "Repair of other equipment"
cap label var C332 "Installation of industrial machinery and equipment"
cap label var C3320 "Installation of industrial machinery and equipment"
cap label var C_OTH "Other manufacturing (C15, C23, C27, C31, C32, C33)"
cap label var D_F "Electricity, gas, steam and air conditioning supply; water supply and construction"
cap label var D_E "Electricity, gas, steam and air conditioning supply; water supply; sewerage, waste management and remediation activities"
cap label var D "Electricity, gas, steam and air conditioning supply"
cap label var D35_E36 "Electricity, gas, steam and air conditioning supply; water collection, treatment and supply"
cap label var D35 "Electricity, gas, steam and air conditioning supply"
cap label var D351 "Electric power generation, transmission and distribution"
cap label var D3511_D3513 "Production and distribution of electricity"
cap label var D3511_D3513_CL "Production and distribution of electricity - for cooling purposes"
cap label var D3511 "Production of electricity"
cap label var D3512 "Transmission of electricity"
cap label var D3513 "Distribution of electricity"
cap label var D3514 "Trade of electricity"
cap label var D352 "Manufacture of gas; distribution of gaseous fuels through mains"
cap label var D3521 "Manufacture of gas"
cap label var D3522 "Distribution of gaseous fuels through mains"
cap label var D3523 "Trade of gas through mains"
cap label var D353 "Steam and air conditioning supply"
cap label var D3530 "Steam and air conditioning supply"
cap label var EP_GOV "General government"
cap label var EP_BSN "Business sector total (mainly all NACE activities except E37, E38.1, E38.2, E39 and O)"
cap label var EP_BUS "Business sector total (mainly all NACE activities except E37, E38.1, E38.2, E39 and O)"
cap label var EP_OTH "Other business sectors (mainly E38.3, F41 to U except O)"
cap label var EP_SPE "Private and public specialist and secondary producers of environmental protection services (mainly E37, E38.1, E38.2 and E39)"
cap label var E "Water supply; sewerage, waste management and remediation activities"
cap label var E36_E37_E39 "Water collection, treatment and supply; sewerage; remediation activities and other waste management services"
cap label var E36_E37 "Water collection, treatment and supply; sewerage"
cap label var E36 "Water collection, treatment and supply"
cap label var E360 "Water collection, treatment and supply"
cap label var E3600 "Water collection, treatment and supply"
cap label var E37_E39 "Sewerage, waste management, remediation activities"
cap label var E37 "Sewerage"
cap label var E370 "Sewerage"
cap label var E3700 "Sewerage"
cap label var E38_E39 "Waste collection, treatment and disposal activities; materials recovery; remediation activities and other waste management services"
cap label var E38 "Waste collection, treatment and disposal activities; materials recovery"
cap label var E381 "Waste collection"
cap label var E3811 "Collection of non-hazardous waste"
cap label var E3812 "Collection of hazardous waste"
cap label var E382 "Waste treatment and disposal"
cap label var E3821 "Treatment and disposal of non-hazardous waste"
cap label var E3822 "Treatment and disposal of hazardous waste"
cap label var E383 "Materials recovery"
cap label var E3831 "Dismantling of wrecks"
cap label var E3832 "Recovery of sorted materials"
cap label var E39 "Remediation activities and other waste management services"
cap label var E390 "Remediation activities and other waste management services"
cap label var E3900 "Remediation activities and other waste management services"
cap label var F_N_X_K "Construction, services of the business economy except financial and insurance activities"
cap label var F "Construction"
cap label var F41 "Construction of buildings"
cap label var F411 "Development of building projects"
cap label var F4110 "Development of building projects"
cap label var F412 "Construction of residential and non-residential buildings"
cap label var F4120 "Construction of residential and non-residential buildings"
cap label var F42 "Civil engineering"
cap label var F421 "Construction of roads and railways"
cap label var F4211 "Construction of roads and motorways"
cap label var F4212 "Construction of railways and underground railways"
cap label var F4213 "Construction of bridges and tunnels"
cap label var F422 "Construction of utility projects"
cap label var F4221 "Construction of utility projects for fluids"
cap label var F4222 "Construction of utility projects for electricity and telecommunications"
cap label var F429 "Construction of other civil engineering projects"
cap label var F4291 "Construction of water projects"
cap label var F4299 "Construction of other civil engineering projects n.e.c."
cap label var F43 "Specialised construction activities"
cap label var F431 "Demolition and site preparation"
cap label var F4311 "Demolition"
cap label var F4312 "Site preparation"
cap label var F4313 "Test drilling and boring"
cap label var F432 "Electrical, plumbing and other construction installation activities"
cap label var F4321 "Electrical installation"
cap label var F4322 "Plumbing, heat and air-conditioning installation"
cap label var F4329 "Other construction installation"
cap label var F433 "Building completion and finishing"
cap label var F4331 "Plastering"
cap label var F4332 "Joinery installation"
cap label var F4333 "Floor and wall covering"
cap label var F4334 "Painting and glazing"
cap label var F4339 "Other building completion and finishing"
cap label var F439 "Other specialised construction activities"
cap label var F4391 "Roofing activities"
cap label var F4399 "Other specialised construction activities n.e.c."
cap label var F_CC1 "Buildings"
cap label var F_CC11 "Residential buildings"
cap label var F_CC11_X_CC113 "Residential buildings, except residences for communities"
cap label var F_CC111 "One-dwelling buildings"
cap label var F_CC112 "Two- and more dwelling buildings"
cap label var F_CC113 "Residences for communities"
cap label var F_CC12 "Non-residential buildings"
cap label var F_CC12_X_CC122 "Non-residential buildings, except office buildings"
cap label var F_CC122 "Office buildings"
cap label var F_CC2 "Civil engineering works"
cap label var G_U "Services"
cap label var G_U_HTC "High-technology services"
cap label var G_U_X_H "Services (except transportation and storage)"
cap label var G_U_X_H49_H51 "Services (except land transport and transport via pipelines; water transport; air transport)"
cap label var G_U_X_G4677 "Services (except wholesale of waste and scrap)"
cap label var G_T "Services (except extra-territorial organisations and bodies)"
cap label var G_S "Services (except activities of households as employers and extra-territorial organisations and bodies)"
cap label var G_S_X_O "Services (except public administration, defense, compulsory social security, activities of households as employers and extra-territorial organisations and bodies)"
cap label var G_N "Services of the business economy"
cap label var G_N_X_K642 "Services of the business economy except activities of holding companies"
cap label var G_N_STS "Services required by STS regulation"
cap label var G_N_STS_X_G47 "Services required by STS regulation (except retail trade and repair)"
cap label var G_J "Wholesale and retail trade; transport; accommodation and food service activities; information and communication"
cap label var G_I_K_L_N_Q_U "Services (except information and communication, professional, scientific and technical activities, public administration and defence; compulsory social security and education)"
cap label var G_I_L_N "Wholesale and retail trade; transport, accommodation and food service, real estate and administrative activities"
cap label var G_I "Wholesale and retail trade, transport, accommodation and food service activities"
cap label var G_I_T "Wholesale and retail trade; accommodation and food service activities; activities of households as employers"
cap label var G_A017_B0721 "Wholesale and retail trade (including hunting, mining of uranium)"
cap label var G "Wholesale and retail trade; repair of motor vehicles and motorcycles"
cap label var G45_S951_X_K "Services, without financial sector"
cap label var G45 "Wholesale and retail trade and repair of motor vehicles and motorcycles"
cap label var G45_X_G452 "Sale of motor vehicles; sale and repair of motorcycles"
cap label var G451 "Sale of motor vehicles"
cap label var G4511 "Sale of cars and light motor vehicles"
cap label var G4519 "Sale of other motor vehicles"
cap label var G452 "Maintenance and repair of motor vehicles"
cap label var G4520 "Maintenance and repair of motor vehicles"
cap label var G453 "Sale of motor vehicle parts and accessories"
cap label var G4531 "Wholesale trade of motor vehicle parts and accessories"
cap label var G4532 "Retail trade of motor vehicle parts and accessories"
cap label var G454 "Sale, maintenance and repair of motorcycles and related parts and accessories"
cap label var G4540 "Sale, maintenance and repair of motorcycles and related parts and accessories"
cap label var G46_M71_INN "Innovation core services activities (Com.Reg. 1450/2004)"
cap label var G46_M73_INN "Innovation core services activities (Com.Reg. 995/2012)"
cap label var G46_G47_FOOD "Retail and other distribution of food"
cap label var G46 "Wholesale trade, except of motor vehicles and motorcycles"
cap label var G461 "Wholesale on a fee or contract basis"
cap label var G4611 "Agents involved in the sale of agricultural raw materials, live animals, textile raw materials and semi-finished goods"
cap label var G4612 "Agents involved in the sale of fuels, ores, metals and industrial chemicals"
cap label var G4613 "Agents involved in the sale of timber and building materials"
cap label var G4614 "Agents involved in the sale of machinery, industrial equipment, ships and aircraft"
cap label var G4615 "Agents involved in the sale of furniture, household goods, hardware and ironmongery"
cap label var G4616 "Agents involved in the sale of textiles, clothing, fur, footwear and leather goods"
cap label var G4617 "Agents involved in the sale of food, beverages and tobacco"
cap label var G4618 "Agents specialised in the sale of other particular products"
cap label var G4619 "Agents involved in the sale of a variety of goods"
cap label var G462 "Wholesale of agricultural raw materials and live animals"
cap label var G4621 "Wholesale of grain, unmanufactured tobacco, seeds and animal feeds"
cap label var G4622 "Wholesale of flowers and plants"
cap label var G4623 "Wholesale of live animals"
cap label var G4624 "Wholesale of hides, skins and leather"
cap label var G463 "Wholesale of food, beverages and tobacco"
cap label var G4631 "Wholesale of fruit and vegetables"
cap label var G4632 "Wholesale of meat and meat products"
cap label var G4633 "Wholesale of dairy products, eggs and edible oils and fats"
cap label var G4634 "Wholesale of beverages"
cap label var G4635 "Wholesale of tobacco products"
cap label var G4636 "Wholesale of sugar and chocolate and sugar confectionery"
cap label var G4637 "Wholesale of coffee, tea, cocoa and spices"
cap label var G4638 "Wholesale of other food, including fish, crustaceans and molluscs"
cap label var G4639 "Non-specialised wholesale of food, beverages and tobacco"
cap label var G464 "Wholesale of household goods"
cap label var G4641 "Wholesale of textiles"
cap label var G4642 "Wholesale of clothing and footwear"
cap label var G4643 "Wholesale of electrical household appliances"
cap label var G4644 "Wholesale of china and glassware and cleaning materials"
cap label var G4645 "Wholesale of perfume and cosmetics"
cap label var G4646 "Wholesale of pharmaceutical goods"
cap label var G4647 "Wholesale of furniture, carpets and lighting equipment"
cap label var G4648 "Wholesale of watches and jewellery"
cap label var G4649 "Wholesale of other household goods"
cap label var G465 "Wholesale of information and communication equipment"
cap label var G4651 "Wholesale of computers, computer peripheral equipment and software"
cap label var G4652 "Wholesale of electronic and telecommunications equipment and parts"
cap label var G466 "Wholesale of other machinery, equipment and supplies"
cap label var G4661 "Wholesale of agricultural machinery, equipment and supplies"
cap label var G4662 "Wholesale of machine tools"
cap label var G4663 "Wholesale of mining, construction and civil engineering machinery"
cap label var G4664 "Wholesale of machinery for the textile industry and of sewing and knitting machines"
cap label var G4665 "Wholesale of office furniture"
cap label var G4666 "Wholesale of other office machinery and equipment"
cap label var G4669 "Wholesale of other machinery and equipment"
cap label var G467 "Other specialised wholesale"
cap label var G4671 "Wholesale of solid, liquid and gaseous fuels and related products"
cap label var G4672 "Wholesale of metals and metal ores"
cap label var G4673 "Wholesale of wood, construction materials and sanitary equipment"
cap label var G4674 "Wholesale of hardware, plumbing and heating equipment and supplies"
cap label var G4675 "Wholesale of chemical products"
cap label var G4676 "Wholesale of other intermediate products"
cap label var G4677 "Wholesale of waste and scrap"
cap label var G469 "Non-specialised wholesale trade"
cap label var G4690 "Non-specialised wholesale trade"
cap label var G47 "Retail trade, except of motor vehicles and motorcycles"
cap label var G47_X_G473 "Retail trade, except of motor vehicles, motorcyles and fuel"
cap label var G47_FOOD "Retail sale of food, beverages and tobacco"
cap label var G47_NFOOD "Retail sale of non-food products (including fuel)"
cap label var G47_NFOOD_X_G473 "Retail sale of non-food products (except fuel)"
cap label var G47_NF_CLTH "Retail sale of textiles, clothing, footware and leather goods in specialised stores"
cap label var G47_NF_HLTH "Dispensing chemist; retail sale of medical and orthopaedic goods, cosmetic and toilet articles in specialised stores"
cap label var G47_NF_OTH "Retail sale of information and communication equipment; other household equipment (except textiles); cultural and recreation goods, etc. in specialised stores"
cap label var G47_NF_OTH1 "Retail sale of computers, peripheral units and software; telecommunications equipment, etc. in specialised stores"
cap label var G47_NF_OTH2 "Retail sale of audio and video equipment; hardware, paints and glass; electrical household appliances, etc. in specialised stores"
cap label var G471 "Retail sale in non-specialised stores"
cap label var G4711 "Retail sale in non-specialised stores with food, beverages or tobacco predominating"
cap label var G4719 "Other retail sale in non-specialised stores"
cap label var G472 "Retail sale of food, beverages and tobacco in specialised stores"
cap label var G4721 "Retail sale of fruit and vegetables in specialised stores"
cap label var G4722 "Retail sale of meat and meat products in specialised stores"
cap label var G4723 "Retail sale of fish, crustaceans and molluscs in specialised stores"
cap label var G4724 "Retail sale of bread, cakes, flour confectionery and sugar confectionery in specialised stores"
cap label var G4725 "Retail sale of beverages in specialised stores"
cap label var G4726 "Retail sale of tobacco products in specialised stores"
cap label var G4729 "Other retail sale of food in specialised stores"
cap label var G473 "Retail sale of automotive fuel in specialised stores"
cap label var G4730 "Retail sale of automotive fuel in specialised stores"
cap label var G474 "Retail sale of information and communication equipment in specialised stores"
cap label var G4741 "Retail sale of computers, peripheral units and software in specialised stores"
cap label var G4742 "Retail sale of telecommunications equipment in specialised stores"
cap label var G4743 "Retail sale of audio and video equipment in specialised stores"
cap label var G475 "Retail sale of other household equipment in specialised stores"
cap label var G4751 "Retail sale of textiles in specialised stores"
cap label var G4752 "Retail sale of hardware, paints and glass in specialised stores"
cap label var G4753 "Retail sale of carpets, rugs, wall and floor coverings in specialised stores"
cap label var G4754 "Retail sale of electrical household appliances in specialised stores"
cap label var G4759 "Retail sale of furniture, lighting equipment and other household articles in specialised stores"
cap label var G476 "Retail sale of cultural and recreation goods in specialised stores"
cap label var G4761 "Retail sale of books in specialised stores"
cap label var G4762 "Retail sale of newspapers and stationery in specialised stores"
cap label var G4763 "Retail sale of music and video recordings in specialised stores"
cap label var G4764 "Retail sale of sporting equipment in specialised stores"
cap label var G4765 "Retail sale of games and toys in specialised stores"
cap label var G477 "Retail sale of other goods in specialised stores"
cap label var G4771 "Retail sale of clothing in specialised stores"
cap label var G4772 "Retail sale of footwear and leather goods in specialised stores"
cap label var G4773 "Dispensing chemist in specialised stores"
cap label var G4774 "Retail sale of medical and orthopaedic goods in specialised stores"
cap label var G4775 "Retail sale of cosmetic and toilet articles in specialised stores"
cap label var G4776 "Retail sale of flowers, plants, seeds, fertilisers, pet animals and pet food in specialised stores"
cap label var G4777 "Retail sale of watches and jewellery in specialised stores"
cap label var G4778 "Other retail sale of new goods in specialised stores"
cap label var G4779 "Retail sale of second-hand goods in stores"
cap label var G478 "Retail sale via stalls and markets"
cap label var G4781 "Retail sale via stalls and markets of food, beverages and tobacco products"
cap label var G4782 "Retail sale via stalls and markets of textiles, clothing and footwear"
cap label var G4789 "Retail sale via stalls and markets of other goods"
cap label var G479 "Retail trade not in stores, stalls or markets"
cap label var G4791 "Retail sale via mail order houses or via Internet"
cap label var G4799 "Other retail sale not in stores, stalls or markets"
cap label var TI "Total tourism industries"
cap label var TIM "Tourism industries - mainly tourism"
cap label var TIP "Tourism industries - partially tourism"
cap label var TI_H4931 "Total tourism industries; urban and suburban passenger land transport"
cap label var TI_WTO "Total tourism industries; other accommodation and food service activities; real estate activities"
cap label var TI_TR "Total tourism industries - transport"
cap label var TI_LTR "Tourism industries - land transport"
cap label var TI_WTR "Tourism industries - water transport"
cap label var PTR "Passenger transport"
cap label var PLTR "Passenger land transport"
cap label var PRTR "Passenger road transport"
cap label var PWTR "Passenger water transport"
cap label var PLWTR "Passenger land and water transport"
cap label var H_N_STS "Services required by STS regulation (except section G)"
cap label var H_N "Services of the business economy (except trade)"
cap label var H_N_X_K "Services of the business economy (except trade and financial and insurance activities)"
cap label var H_J "Transportation and storage; information and communication"
cap label var H "Transportation and storage"
cap label var H_X_H53 "Transportation and storage except postal and courier activities"
cap label var H_X_H491_H492 "Transport (except railways)"
cap label var H491_H492 "Railways"
cap label var H49_H52_N79 "Land transport, transport via pipelines, water transport, air transport, warehousing and support activities for transportation; travel agency, tour operator and other reservation service and related activities"
cap label var H49_H51 "Land transport and transport via pipelines; water transport; air transport"
cap label var H49 "Land transport and transport via pipelines"
cap label var H491 "Passenger rail transport, interurban"
cap label var H4910 "Passenger rail transport, interurban"
cap label var H492 "Freight rail transport"
cap label var H4920 "Freight rail transport"
cap label var H493 "Other passenger land transport"
cap label var H4931 "Urban and suburban passenger land transport"
cap label var H4932 "Taxi operation"
cap label var H4939 "Other passenger land transport n.e.c."
cap label var H494_N812_STS "Services required by STS regulation (for the service producer prices indicator)"
cap label var H494 "Freight transport by road and removal services"
cap label var H4941 "Freight transport by road"
cap label var H4942 "Removal services"
cap label var H493_H494 "Other passenger land transport; freight transport by road and removal services"
cap label var H495 "Transport via pipeline"
cap label var H4950 "Transport via pipeline"
cap label var H50 "Water transport"
cap label var H501_H502 "Sea and coastal water transport"
cap label var H501 "Sea and coastal passenger water transport"
cap label var H5010 "Sea and coastal passenger water transport"
cap label var H502 "Sea and coastal freight water transport"
cap label var H5020 "Sea and coastal freight water transport"
cap label var H503 "Inland passenger water transport"
cap label var H5030 "Inland passenger water transport"
cap label var H504 "Inland freight water transport"
cap label var H5040 "Inland freight water transport"
cap label var H503_H504 "Inland passenger and freight water transport"
cap label var H51_I55_N79 "Air transport; accommodation; travel agency, tour operator and other reservation service and related activities"
cap label var H51 "Air transport"
cap label var H511 "Passenger air transport"
cap label var H5110 "Passenger air transport"
cap label var H512 "Freight air transport and space transport"
cap label var H5121 "Freight air transport"
cap label var H5122 "Space transport"
cap label var H52_H53 "Warehousing and support activities for transportation; postal and courier activities"
cap label var H52 "Warehousing and support activities for transportation"
cap label var H521 "Warehousing and storage"
cap label var H5210 "Warehousing and storage"
cap label var H522 "Support activities for transportation"
cap label var H5221 "Service activities incidental to land transportation"
cap label var H5222 "Service activities incidental to water transportation"
cap label var H5223 "Service activities incidental to air transportation"
cap label var H5224 "Cargo handling"
cap label var H5229 "Other transportation support activities"
cap label var H53 "Postal and courier activities"
cap label var H531 "Postal activities under universal service obligation"
cap label var H5310 "Postal activities under universal service obligation"
cap label var H532 "Other postal and courier activities"
cap label var H5320 "Other postal and courier activities"
cap label var H_OTH "Other transport"
cap label var I_U "Services (except wholesale and retail trade, transportation and storage)"
cap label var I_L_O_U "Accommodation and food service activities; real estate activities; public administration, defence; compulsory social security; education; human health and social work activities; other services"
cap label var I "Accommodation and food service activities"
cap label var I_X_I559_I562 "Hotels; holiday and other short-stay accommodation; camping grounds, recreational vehicle parks and trailer parks; restaurants and mobile food and beverage service activities"
cap label var I55_I56_N_S_FOOD "Restaurants and food services"
cap label var I55 "Accommodation"
cap label var I551_I553 "Hotels; holiday and other short-stay accommodation; camping grounds, recreational vehicle parks and trailer parks"
cap label var I551 "Hotels and similar accommodation"
cap label var I5510 "Hotels and similar accommodation"
cap label var I552_I553 "Holiday and other short-stay accommodation; camping grounds, recreational vehicle parks and trailer parks"
cap label var I552 "Holiday and other short-stay accommodation"
cap label var I5520 "Holiday and other short-stay accommodation"
cap label var I553 "Camping grounds, recreational vehicle parks and trailer parks"
cap label var I5530 "Camping grounds, recreational vehicle parks and trailer parks"
cap label var I559 "Other accommodation"
cap label var I5590 "Other accommodation"
cap label var I56 "Food and beverage service activities"
cap label var I561_I563 "Restaurants and mobile food and beverage service activities"
cap label var I561 "Restaurants and mobile food service activities"
cap label var I5610 "Restaurants and mobile food service activities"
cap label var I562 "Event catering and other food service activities"
cap label var I5621 "Event catering activities"
cap label var I5629 "Other food service activities"
cap label var I563 "Beverage serving activities"
cap label var I5630 "Beverage serving activities"
cap label var KIS "Total knowledge-intensive services"
cap label var KIS_HTC "Knowledge-intensive high-technology services"
cap label var KIS_HTC_X_M72 "Knowledge-intensive high-technology services required by STS regulation"
cap label var KIS_MKT "Knowledge-intensive market services"
cap label var KIS_MKT_OTH "Knowledge-intensive market services (except financial intermediation and high-technology services)"
cap label var KIS_OTH "Other knowledge-intensive services"
cap label var LKIS "Total less knowledge-intensive services"
cap label var LKIS_MKT "Less knowledge-intensive market services"
cap label var LKIS_MKT_STS "Less knowledge-intensive market services required by STS regulation"
cap label var LKIS_OTH "Other less knowledge-intensive services"
cap label var J_N "Information and communication; financial and insurance activities; real estate activities; professional, scientific and technical activities; administrative and support service activities"
cap label var J_K "Information and communication; financial and insurance activities"
cap label var J "Information and communication"
cap label var J58_J62_J63 "Publishing, computer programming and consultancy, information service activities"
cap label var J58_J60 "Publishing, motion picture, video, television programme production; sound recording, programming and broadcasting activities"
cap label var J58 "Publishing activities"
cap label var J581 "Publishing of books, periodicals and other publishing activities"
cap label var J5811 "Book publishing"
cap label var J5812 "Publishing of directories and mailing lists"
cap label var J5813 "Publishing of newspapers"
cap label var J5814 "Publishing of journals and periodicals"
cap label var J5819 "Other publishing activities"
cap label var J582 "Software publishing"
cap label var J5821 "Publishing of computer games"
cap label var J5829 "Other software publishing"
cap label var J59_J60 "Motion picture, video, television programme production; programming and broadcasting activities"
cap label var J59 "Motion picture, video and television programme production, sound recording and music publishing activities"
cap label var J591 "Motion picture, video and television programme activities"
cap label var J5911 "Motion picture, video and television programme production activities"
cap label var J5912 "Motion picture, video and television programme post-production activities"
cap label var J5913 "Motion picture, video and television programme distribution activities"
cap label var J5914 "Motion picture projection activities"
cap label var J592 "Sound recording and music publishing activities"
cap label var J5920 "Sound recording and music publishing activities"
cap label var J60 "Programming and broadcasting activities"
cap label var J601 "Radio broadcasting"
cap label var J6010 "Radio broadcasting"
cap label var J602 "Television programming and broadcasting activities"
cap label var J6020 "Television programming and broadcasting activities"
cap label var J61_J63 "Telecommunications; computer programming, consultancy and related activities; information service activities"
cap label var J61 "Telecommunications"
cap label var J611 "Wired telecommunications activities"
cap label var J6110 "Wired telecommunications activities"
cap label var J612 "Wireless telecommunications activities"
cap label var J6120 "Wireless telecommunications activities"
cap label var J613 "Satellite telecommunications activities"
cap label var J6130 "Satellite telecommunications activities"
cap label var J619 "Other telecommunications activities"
cap label var J6190 "Other telecommunications activities"
cap label var J62_J63 "Computer programming, consultancy, and information service activities"
cap label var J62 "Computer programming, consultancy and related activities"
cap label var J620 "Computer programming, consultancy and related activities"
cap label var J6201 "Computer programming activities"
cap label var J6202 "Computer consultancy activities"
cap label var J6203 "Computer facilities management activities"
cap label var J6209 "Other information technology and computer service activities"
cap label var J63 "Information service activities"
cap label var J631 "Data processing, hosting and related activities; web portals"
cap label var J6311 "Data processing, hosting and related activities"
cap label var J6312 "Web portals"
cap label var J639 "Other information service activities"
cap label var J6391 "News agency activities"
cap label var J6399 "Other information service activities n.e.c."
cap label var K_U "Financial and insurance activities, real estate activities, professional, scientific and technical activities, administrative and support service activities, public administration and defence; compulsory social security, education, human health and social work activities, arts, entertainment and recreation, other service activities, activities of households as employers; undifferentiated goods- and services-producing activities of households for own use, activities of extraterritorial organisations and bodies"
cap label var K_N "Financial and insurance activities; real estate activities; professional, scientific and technical activities; administrative and support service activities"
cap label var K_L "Financial and insurance activities; real estate activities"
cap label var K_L_X_K642 "Financial and insurance activities; real estate activities except activities of holding companies"
cap label var K "Financial and insurance activities"
cap label var K_X_K642 "Financial and insurance activities except activities of holding companies"
cap label var K64_K65 "Financial service activities, insurance, reinsurance and pension funding, except compulsory social security"
cap label var K64 "Financial service activities, except insurance and pension funding"
cap label var K64_X_K642 "Financial service activities, except insurance, pension funding, activities of holding companies"
cap label var K641 "Monetary intermediation"
cap label var K6411 "Central banking"
cap label var K64CRED "Total credit institutions"
cap label var K6419 "Other monetary intermediation"
cap label var K642 "Activities of holding companies"
cap label var K6420 "Activities of holding companies"
cap label var K643 "Trusts, funds and similar financial entities"
cap label var K6430 "Trusts, funds and similar financial entities"
cap label var K649 "Other financial service activities, except insurance and pension funding"
cap label var K6491 "Financial leasing"
cap label var K6492 "Other credit granting"
cap label var K6499 "Other financial service activities, except insurance and pension funding n.e.c."
cap label var K65 "Insurance, reinsurance and pension funding, except compulsory social security"
cap label var K651 "Insurance"
cap label var K6511 "Life insurance"
cap label var K6512 "Non-life insurance"
cap label var K652 "Reinsurance"
cap label var K6520 "Reinsurance"
cap label var K653 "Pension funding"
cap label var K6530 "Pension funding"
cap label var K66 "Activities auxiliary to financial services and insurance activities"
cap label var K661 "Activities auxiliary to financial services, except insurance and pension funding"
cap label var K6611 "Administration of financial markets"
cap label var K6612 "Security and commodity contracts brokerage"
cap label var K6619 "Other activities auxiliary to financial services, except insurance and pension funding"
cap label var K662 "Activities auxiliary to insurance and pension funding"
cap label var K6621 "Risk and damage evaluation"
cap label var K6622 "Activities of insurance agents and brokers"
cap label var K6629 "Other activities auxiliary to insurance and pension funding"
cap label var K663 "Fund management activities"
cap label var K6630 "Fund management activities"
cap label var L_N_R_S "Real estate activities; professional, scientific and technical activities; administrative and support service activities; arts, entertainment and recreation; other service activities"
cap label var L_M "Real estate activities; professional, scientific and technical activities"
cap label var L "Real estate activities"
cap label var L68 "Real estate activities"
cap label var L68A "Imputed rents of owner-occupied dwellings"
cap label var L681 "Buying and selling of own real estate"
cap label var L6810 "Buying and selling of own real estate"
cap label var L682 "Renting and operating of own or leased real estate"
cap label var L6820 "Renting and operating of own or leased real estate"
cap label var L683 "Real estate activities on a fee or contract basis"
cap label var L6831 "Real estate agencies"
cap label var L6832 "Management of real estate on a fee or contract basis"
cap label var M_N "Professional, scientific and technical activities; administrative and support service activities"
cap label var M "Professional, scientific and technical activities"
cap label var M_STS "Professional, scientific and technical activities required by STS regulation"
cap label var M69_M74 "Legal and accounting activities; activities of head offices; management consultancy activities; architectural and engineering activities; technical testing and analysis; scientific research and development; advertising and market research; other professional, scientific and technical activities"
cap label var M69_M71 "Legal and accounting activities; activities of head offices; management consultancy activities; architectural and engineering activities; technical testing and analysis"
cap label var M69_M70 "Legal and accounting activities; activities of head offices; management consultancy activities"
cap label var M69_M702 "Legal, accounting and management consultancy activities"
cap label var M69 "Legal and accounting activities"
cap label var M691 "Legal activities"
cap label var M6910 "Legal activities"
cap label var M692 "Accounting, bookkeeping and auditing activities; tax consultancy"
cap label var M6920 "Accounting, bookkeeping and auditing activities; tax consultancy"
cap label var M70 "Activities of head offices; management consultancy activities"
cap label var M701 "Activities of head offices"
cap label var M7010 "Activities of head offices"
cap label var M702 "Management consultancy activities"
cap label var M7021 "Public relations and communication activities"
cap label var M7022 "Business and other management consultancy activities"
cap label var M71_M73 "Architectural and engineering activities; technical testing and analysis; scientific research and development; advertising and market research"
cap label var M71 "Architectural and engineering activities; technical testing and analysis"
cap label var M711 "Architectural and engineering activities and related technical consultancy"
cap label var M7111 "Architectural activities"
cap label var M7112 "Engineering activities and related technical consultancy"
cap label var M712 "Technical testing and analysis"
cap label var M7120 "Technical testing and analysis"
cap label var M72 "Scientific research and development"
cap label var M721 "Research and experimental development on natural sciences and engineering"
cap label var M7211 "Research and experimental development on biotechnology"
cap label var M7219 "Other research and experimental development on natural sciences and engineering"
cap label var M722 "Research and experimental development on social sciences and humanities"
cap label var M7220 "Research and experimental development on social sciences and humanities"
cap label var M73_M75 "Advertising and market research; other professional, scientific and technical activities; veterinary activities"
cap label var M73 "Advertising and market research"
cap label var M731 "Advertising"
cap label var M7311 "Advertising agencies"
cap label var M7312 "Media representation"
cap label var M732 "Market research and public opinion polling"
cap label var M7320 "Market research and public opinion polling"
cap label var M74_M75 "Other professional, scientific and technical activities; veterinary activities"
cap label var M74 "Other professional, scientific and technical activities"
cap label var M741 "Specialised design activities"
cap label var M7410 "Specialised design activities"
cap label var M742 "Photographic activities"
cap label var M7420 "Photographic activities"
cap label var M743 "Translation and interpretation activities"
cap label var M7430 "Translation and interpretation activities"
cap label var M749 "Other professional, scientific and technical activities n.e.c."
cap label var M7490 "Other professional, scientific and technical activities n.e.c."
cap label var M75 "Veterinary activities"
cap label var M750 "Veterinary activities"
cap label var M7500 "Veterinary activities"
cap label var N77_N82_X_N79 "Activities for rental and leasing, employment, security and investigation, services to buildings and landscape, office administrative, office support and other business support"
cap label var N "Administrative and support service activities"
cap label var N_STS "Administrative and support service activities required by STS regulation"
cap label var N77 "Rental and leasing activities"
cap label var N771_N7721 "Renting and leasing of motor vehicles, recreational and sports goods"
cap label var N771 "Renting and leasing of motor vehicles"
cap label var N7711 "Renting and leasing of cars and light motor vehicles"
cap label var N7712 "Renting and leasing of trucks"
cap label var N772 "Renting and leasing of personal and household goods"
cap label var N7721 "Renting and leasing of recreational and sports goods"
cap label var N7722 "Renting of video tapes and disks"
cap label var N7729 "Renting and leasing of other personal and household goods"
cap label var N773 "Renting and leasing of other machinery, equipment and tangible goods"
cap label var N7731 "Renting and leasing of agricultural machinery and equipment"
cap label var N7732 "Renting and leasing of construction and civil engineering machinery and equipment"
cap label var N7733 "Renting and leasing of office machinery and equipment (including computers)"
cap label var N7734 "Renting and leasing of water transport equipment"
cap label var N7735 "Renting and leasing of air transport equipment"
cap label var N7739 "Renting and leasing of other machinery, equipment and tangible goods n.e.c."
cap label var N774 "Leasing of intellectual property and similar products, except copyrighted works"
cap label var N7740 "Leasing of intellectual property and similar products, except copyrighted works"
cap label var N78_N82 "Employment, travel agency, security and investigation, service and landscape, office administrative and support activities"
cap label var N78 "Employment activities"
cap label var N781 "Activities of employment placement agencies"
cap label var N7810 "Activities of employment placement agencies"
cap label var N782 "Temporary employment agency activities"
cap label var N7820 "Temporary employment agency activities"
cap label var N783 "Other human resources provision"
cap label var N7830 "Other human resources provision"
cap label var N79 "Travel agency, tour operator and other reservation service and related activities"
cap label var N791 "Travel agency and tour operator activities"
cap label var N7911 "Travel agency activities"
cap label var N7912 "Tour operator activities"
cap label var N799 "Other reservation service and related activities"
cap label var N7990 "Other reservation service and related activities"
cap label var N80_N82 "Security and investigation, service and landscape, office administrative and support activities"
cap label var N80 "Security and investigation activities"
cap label var N801 "Private security activities"
cap label var N8010 "Private security activities"
cap label var N802 "Security systems service activities"
cap label var N8020 "Security systems service activities"
cap label var N803 "Investigation activities"
cap label var N8030 "Investigation activities"
cap label var N81 "Services to buildings and landscape activities"
cap label var N811 "Combined facilities support activities"
cap label var N8110 "Combined facilities support activities"
cap label var N812 "Cleaning activities"
cap label var N8121 "General cleaning of buildings"
cap label var N8122 "Other building and industrial cleaning activities"
cap label var N8129 "Other cleaning activities"
cap label var N813 "Landscape service activities"
cap label var N8130 "Landscape service activities"
cap label var N82 "Office administrative, office support and other business support activities"
cap label var N821 "Office administrative and support activities"
cap label var N8211 "Combined office administrative service activities"
cap label var N8219 "Photocopying, document preparation and other specialised office support activities"
cap label var N822 "Activities of call centres"
cap label var N8220 "Activities of call centres"
cap label var N823 "Organisation of conventions and trade shows"
cap label var N8230 "Organisation of conventions and trade shows"
cap label var N829 "Business support service activities n.e.c."
cap label var N8291 "Activities of collection agencies and credit bureaus"
cap label var N8292 "Packaging activities"
cap label var N8299 "Other business support service activities n.e.c."
cap label var O__U "Public administration and defence; compulsory social security; education; human health and social work activities; arts, entertainment and recreation, repair of household goods and other services"
cap label var O_S "Public administration and defence; compulsory social security; education; human health and social work activities; arts, entertainment and recreation; other service activities"
cap label var O_Q "Public administration, defence, education, human health and social work activities"
cap label var O_T_U "Public administration; activities of households and of extraterritorial organisations"
cap label var O_P "Public administration and defence; compulsory social security and education"
cap label var O_R_U "Public administration, defence, education, human health and social work activities; arts, entertainment and recreation; activities of extraterritorial organisations and bodies"
cap label var O_U "Public administration; activities of extraterritorial organisations and bodies"
cap label var O "Public administration and defence; compulsory social security"
cap label var O84 "Public administration and defence; compulsory social security"
cap label var O841 "Administration of the State and the economic and social policy of the community"
cap label var O8411 "General public administration activities"
cap label var O8412 "Regulation of the activities of providing health care, education, cultural services and other social services, except social security"
cap label var O8413 "Regulation of and contribution to more efficient operation of businesses"
cap label var O842 "Provision of services to the community as a whole"
cap label var O8421 "Foreign affairs"
cap label var O8422 "Defence activities"
cap label var O8423 "Justice and judicial activities"
cap label var O8424 "Public order and safety activities"
cap label var O8425 "Fire service activities"
cap label var O843 "Compulsory social security activities"
cap label var O8430 "Compulsory social security activities"
cap label var P_S "Education; human health and social work activities; arts, entertainment and recreation; other service activities"
cap label var P_S_X_S94 "Education; human health and social work activities; except activities of membership organisations"
cap label var P_Q "Education; human health and social work activities"
cap label var P "Education"
cap label var P85 "Education"
cap label var P851 "Pre-primary education"
cap label var P8510 "Pre-primary education"
cap label var P852 "Primary education"
cap label var P8520 "Primary education"
cap label var P853 "Secondary education"
cap label var P8531 "General secondary education"
cap label var P8532 "Technical and vocational secondary education"
cap label var P854 "Higher education"
cap label var P8541 "Post-secondary non-tertiary education"
cap label var P8542 "Tertiary education"
cap label var P855 "Other education"
cap label var P8551 "Sports and recreation education"
cap label var P8552 "Cultural education"
cap label var P8553 "Driving school activities"
cap label var P8559 "Other education n.e.c."
cap label var P856 "Educational support activities"
cap label var P8560 "Educational support activities"
cap label var Q "Human health and social work activities"
cap label var Q86 "Human health activities"
cap label var Q861 "Hospital activities"
cap label var Q8610 "Hospital activities"
cap label var Q862 "Medical and dental practice activities"
cap label var Q8621 "General medical practice activities"
cap label var Q8622 "Specialist medical practice activities"
cap label var Q8623 "Dental practice activities"
cap label var Q869 "Other human health activities"
cap label var Q8690 "Other human health activities"
cap label var Q87_Q88 "Residential care activities and social work activities without accommodation"
cap label var Q87 "Residential care activities"
cap label var Q871 "Residential nursing care activities"
cap label var Q8710 "Residential nursing care activities"
cap label var Q872 "Residential care activities for mental retardation, mental health and substance abuse"
cap label var Q8720 "Residential care activities for mental retardation, mental health and substance abuse"
cap label var Q873 "Residential care activities for the elderly and disabled"
cap label var Q8730 "Residential care activities for the elderly and disabled"
cap label var Q879 "Other residential care activities"
cap label var Q8790 "Other residential care activities"
cap label var Q88 "Social work activities without accommodation"
cap label var Q881 "Social work activities without accommodation for the elderly and disabled"
cap label var Q8810 "Social work activities without accommodation for the elderly and disabled"
cap label var Q889 "Other social work activities without accommodation"
cap label var Q8891 "Child day-care activities"
cap label var Q8899 "Other social work activities without accommodation n.e.c."
cap label var R_U "Arts, entertainment and recreation; other service activities; activities of household and extra-territorial organizations and bodies"
cap label var R_S "Arts, entertainment and recreation; other service activities"
cap label var R "Arts, entertainment and recreation"
cap label var R90_R92 "Creative, arts and entertainment activities; libraries, archives, museums and other cultural activities; gambling and betting activities"
cap label var R90 "Creative, arts and entertainment activities"
cap label var R900 "Creative, arts and entertainment activities"
cap label var R9001 "Performing arts"
cap label var R9002 "Support activities to performing arts"
cap label var R9003 "Artistic creation"
cap label var R9004 "Operation of arts facilities"
cap label var R91 "Libraries, archives, museums and other cultural activities"
cap label var R910 "Libraries, archives, museums and other cultural activities"
cap label var R9101 "Library and archives activities"
cap label var R9102 "Museums activities"
cap label var R9103 "Operation of historical sites and buildings and similar visitor attractions"
cap label var R9104 "Botanical and zoological gardens and nature reserves activities"
cap label var R92_R93 "Gambling and betting activities; sporting and other recreational activities"
cap label var R92 "Gambling and betting activities"
cap label var R920 "Gambling and betting activities"
cap label var R9200 "Gambling and betting activities"
cap label var R93 "Sports activities and amusement and recreation activities"
cap label var R931 "Sports activities"
cap label var R9311 "Operation of sports facilities"
cap label var R9312 "Activities of sport clubs"
cap label var R9313 "Fitness facilities"
cap label var R9319 "Other sports activities"
cap label var R932 "Amusement and recreation activities"
cap label var R9321 "Activities of amusement parks and theme parks"
cap label var R9329 "Other amusement and recreation activities"
cap label var S_U "Other service activities; activities of households as employers and extraterritorial organisations and bodies"
cap label var S_T "Other service activities, activities of households as employers"
cap label var S "Other service activities"
cap label var S94 "Activities of membership organisations"
cap label var S941 "Activities of business, employers and professional membership organisations"
cap label var S9411 "Activities of business and employers membership organisations"
cap label var S9412 "Activities of professional membership organisations"
cap label var S942 "Activities of trade unions"
cap label var S9420 "Activities of trade unions"
cap label var S949 "Activities of other membership organisations"
cap label var S9491 "Activities of religious organisations"
cap label var S9492 "Activities of political organisations"
cap label var S9499 "Activities of other membership organisations n.e.c."
cap label var S95_S96 "Repair of computers, personal and household goods; other personal service activities"
cap label var S95 "Repair of computers and personal and household goods"
cap label var S951 "Repair of computers and communication equipment"
cap label var S9511 "Repair of computers and peripheral equipment"
cap label var S9512 "Repair of communication equipment"
cap label var S952 "Repair of personal and household goods"
cap label var S9521 "Repair of consumer electronics"
cap label var S9522 "Repair of household appliances and home and garden equipment"
cap label var S9523 "Repair of footwear and leather goods"
cap label var S9524 "Repair of furniture and home furnishings"
cap label var S9525 "Repair of watches, clocks and jewellery"
cap label var S9529 "Repair of other personal and household goods"
cap label var S96 "Other personal service activities"
cap label var S960 "Other personal service activities"
cap label var S9601 "Washing and (dry-)cleaning of textile and fur products"
cap label var S9602 "Hairdressing and other beauty treatment"
cap label var S9603 "Funeral and related activities"
cap label var S9604 "Physical well-being activities"
cap label var S9609 "Other personal service activities n.e.c."
cap label var T "Activities of households as employers; undifferentiated goods- and services-producing activities of households for own use"
cap label var T97 "Activities of households as employers of domestic personnel"
cap label var T970 "Activities of households as employers of domestic personnel"
cap label var T9700 "Activities of households as employers of domestic personnel"
cap label var T98 "Undifferentiated goods- and services-producing activities of private households for own use"
cap label var T981 "Undifferentiated goods-producing activities of private households for own use"
cap label var T9810 "Undifferentiated goods-producing activities of private households for own use"
cap label var T982 "Undifferentiated service-producing activities of private households for own use"
cap label var T9820 "Undifferentiated service-producing activities of private households for own use"
cap label var T98_U "Undifferentiated goods- and services-producing activities of private households for own use and activities of extraterritorial organisations and bodies"
cap label var U "Activities of extraterritorial organisations and bodies"
cap label var U99 "Activities of extraterritorial organisations and bodies"
cap label var U990 "Activities of extraterritorial organisations and bodies"
cap label var U9900 "Activities of extraterritorial organisations and bodies"
cap label var KIBS "Knowledge intensive business services"
cap label var ICT "Information and Communication Technology - Total"
cap label var C_ICT "ICT manufacturing"
cap label var G_U_ICT "ICT services"
cap label var G46_ICT "ICT wholesale"
cap label var INF "Information sector"
cap label var CRA "Computer related services"
cap label var EP_HH "Households"
cap label var EP_NRES "Non-residents"
cap label var TOTAL_HH_NRES "All NACE activities plus households, non-residents and not allocated"
cap label var TOTAL_HH "All NACE activities plus households"
cap label var MU_WST "Municipal waste"
cap label var HH_WST "Waste from households"
cap label var HH "Total activities by households"
cap label var HH_HEAT "Heating/cooling activities by households"
cap label var HH_HEAT_OTH "Heating/cooling and other activities by households"
cap label var HH_TRA "Transport activities by households"
cap label var HH_OTH "Other activities by households"
cap label var CH_INV_PA "Changes in inventories and produced assets"
cap label var SD_SU "Statistical discrepancy between supply and use of energy for total activities"
cap label var ROW_ACT "Economic activities of the rest of the world"
cap label var ENV "Environment"
cap label var NRG_FLOW "Energy flows over all activities"
cap label var PRV_RE "Private real estate activities"
cap label var SERV_OTH "Construction, services of the business economy except knowledge-intensive market services, financial and insurance activities"
cap label var FDI "All FDI activities"
cap label var OTH "Other NACE activities"
cap label var NAL "Not allocated"
cap label var NAP "Not applicable"
cap label var NRP "No response"
cap label var NSP "Not specified"
cap label var UNK "Unknown NACE activity"
