cap label var TOTAL "Total"
cap label var PAPER "Paper and cardboard"
cap label var PLAST_RUB "Plastics including rubber"
cap label var PLAST "Plastics"
cap label var PLAST_SYN "Plastics - synthetic"
cap label var PLAST_NTL "Plastics - natural"
cap label var RUB "Rubber"
cap label var RUB_SYN "Rubber - synthetic"
cap label var RUB_NTL "Rubber - natural"
cap label var WD "Wood"
cap label var WD_SAPE "Sapele wood"
cap label var WD_TEAK "Natural teak wood"
cap label var TEXT "Textiles"
cap label var TEXT_SYN "Textiles - synthetic"
cap label var TEXT_NTL "Textiles - natural"
cap label var GLAS "Glass"
cap label var ORG "Organic"
cap label var ORG_ANI "Organic - animal origin"
cap label var ORG_VEG "Organic - vegetal origin"
cap label var MIN "Mineral"
cap label var MT "Metal"
cap label var MT_FER "Metal - ferrous"
cap label var MT_NFER "Metal - non ferrous"
cap label var MT_NFER_PRE "Metal - non ferrous - precious metals"
cap label var MT_NFER_CAN "Metal - non ferrous - copper, aluminium and nickel"
cap label var MT_NFER_OTH "Metal - non ferrous - other"
cap label var NSP "Not specified"
