cap label var D01_ECU_PER_HA "Common wheat and spelt"
cap label var D02_ECU_PER_HA "Durum wheat"
cap label var D03_ECU_PER_HA "Rye"
cap label var D04_ECU_PER_HA "Barley"
cap label var D05_ECU_PER_HA "Oats"
cap label var D06_ECU_PER_HA "Grain maize"
cap label var D07_ECU_PER_HA "Rice"
cap label var D08_ECU_PER_HA "Other cereals"
cap label var D09_ECU_PER_HA "Pulses - total"
cap label var D09A_ECU_PER_HA "Pulses - fodder"
cap label var D09B_ECU_PER_HA "Pulses - other"
cap label var D09C_ECU_PER_HA "Pulses - fodder peas"
cap label var D09D_ECU_PER_HA "Pulses - fodder field beans"
cap label var D09E_ECU_PER_HA "Pulses - other than fodder peas and field beans"
cap label var D09E_1_ECU_PER_HA "Peas, field beans and sweet lupines"
cap label var D09F_ECU_PER_HA "Lentils, chick peas and vetches"
cap label var D09G_ECU_PER_HA "Other protein crops harvested dry"
cap label var D10_ECU_PER_HA "Potatoes"
cap label var D11_ECU_PER_HA "Sugar beet"
cap label var D12_ECU_PER_HA "Fodder roots and brassicas"
cap label var D13_ECU_PER_HA "Industrial plants"
cap label var D13A_ECU_PER_HA "Tobacco"
cap label var D13B_ECU_PER_HA "Hops"
cap label var D13C_ECU_PER_HA "Cotton"
cap label var D13D_ECU_PER_HA "Other industrial plants"
cap label var D13D1_ECU_PER_HA "Other oil-seed or fibre plants"
cap label var D13D1A_ECU_PER_HA "Rape and turnip"
cap label var D13D1B_ECU_PER_HA "Sunflower"
cap label var D13D1C_ECU_PER_HA "Soya"
cap label var D13D1D_ECU_PER_HA "Other oil-seed or fibre plants - others"
cap label var D13D2_ECU_PER_HA "Aromatic-, medicinal and culinary plants"
cap label var D13D3_ECU_PER_HA "Industrial plants - Others"
cap label var D13D3A_ECU_PER_HA "Sugar cane"
cap label var D13D3B_ECU_PER_HA "Industrial plants - Other- except sugar cane"
cap label var D14_ECU_PER_HA "Fresh vegetables, melons, strawberries - outdoor"
cap label var D14A_ECU_PER_HA "Fresh vegetables, melons, strawberries - outdoor - open field"
cap label var D14B_ECU_PER_HA "Fresh vegetables, melons, strawberries - outdoor - market garden"
cap label var D15_ECU_PER_HA "Fresh vegetables, melons, strawberries - under glass"
cap label var D16_ECU_PER_HA "Flowers - outdoor"
cap label var D17_ECU_PER_HA "Flowers - under glass"
cap label var D18_ECU_PER_HA "Forage plants - total"
cap label var D18A_ECU_PER_HA "Forage plants - temporary grass"
cap label var D18B_ECU_PER_HA "Forage plants - other green fodder - total"
cap label var D18B1_ECU_PER_HA "Forage plants - other green fodder - green maize"
cap label var D18B2_ECU_PER_HA "Forage plants - other green fodder - leguminous plants"
cap label var D18B2_3_ECU_PER_HA "Other forage plants"
cap label var D18B3_ECU_PER_HA "Forage plants - other green fodder - others"
cap label var D19_ECU_PER_HA "Seeds and seedlings"
cap label var D20_ECU_PER_HA "Other crops"
cap label var D21_ECU_PER_HA "Fallow land without subsidies"
cap label var D22_ECU_PER_HA "Non-productive arable land, eligible for support"
cap label var D23_ECU_PER_HA "Tobacco"
cap label var D24_ECU_PER_HA "Hops"
cap label var D25_ECU_PER_HA "Cotton"
cap label var D26_ECU_PER_HA "Rape and turnip"
cap label var D27_ECU_PER_HA "Sunflower"
cap label var D28_ECU_PER_HA "Soya"
cap label var D29_ECU_PER_HA "Linseed (oil flax)"
cap label var D30_ECU_PER_HA "Other oil seed crops"
cap label var D31_ECU_PER_HA "Flax"
cap label var D32_ECU_PER_HA "Hemp"
cap label var D33_ECU_PER_HA "Other textile crops"
cap label var D34_ECU_PER_HA "Aromatic, medicinal and culinary plants (same as previous D13D2)"
cap label var D35_ECU_PER_HA "Industrial plants not mentioned elsewhere"
cap label var E_ECU_PER_HA "Kitchen gardens"
cap label var F_ECU_PER_HA "Permanent grassland and meadow - total"
cap label var F01_ECU_PER_HA "Permanent grassland and meadow - pasture and meadow"
cap label var F02_ECU_PER_HA "Permanent grassland and meadow - rough grazings"
cap label var F03_ECU_PER_HA "Permanent grassland and meadow - no used for production, eligible for subsidies"
cap label var G01_ECU_PER_HA "Fruit and berry plantations - total"
cap label var G01A_ECU_PER_HA "Fruit and berry plantations - temperate climate"
cap label var G01B_ECU_PER_HA "Fruit and berry plantations - subtropical climate"
cap label var G01C_ECU_PER_HA "Fruit and berry plantations - nuts"
cap label var G02_ECU_PER_HA "Citrus plantations"
cap label var G03_ECU_PER_HA "Olive plantations - total"
cap label var G03A_ECU_PER_HA "Olive plantations - table olives"
cap label var G03B_ECU_PER_HA "Olive plantations - oil production"
cap label var G04_ECU_PER_HA "Vineyards - total"
cap label var G04A_ECU_PER_HA "Vineyards - quality wine"
cap label var G04B_ECU_PER_HA "Vineyards - other wines"
cap label var G04C_ECU_PER_HA "Vineyards - table grapes"
cap label var G04D_ECU_PER_HA "Vineyards - raisins"
cap label var G05_ECU_PER_HA "Nurseries"
cap label var G06_ECU_PER_HA "Other permanent crops"
cap label var G07_ECU_PER_HA "Permanent crops under glass"
cap label var I01_ECU_PER_HA "Successive secondary crops - total"
cap label var I01A_ECU_PER_HA "Successive secondary crops - non fodder cereals"
cap label var I01B_ECU_PER_HA "Successive secondary crops - non fodder pulses"
cap label var I01C_ECU_PER_HA "Successive secondary crops - non fodder oil-seed plants"
cap label var I01D_ECU_PER_HA "Successive secondary crops - others total"
cap label var I01D1_ECU_PER_HA "Successive secondary crops - others non fodder"
cap label var I01D2_ECU_PER_HA "Successive secondary crops - others fodder"
cap label var I02_ECU_PER_100_M2 "Mushrooms"
cap label var I03B1_ECU_PER_HA "Irrigated once a year - Durum wheat"
cap label var I03B10_ECU_PER_HA "Irrigated once a year - Vines"
cap label var I03B2_ECU_PER_HA "Irrigated once a year - Maize"
cap label var I03B3_ECU_PER_HA "Irrigated once a year - Potatoes"
cap label var I03B4_ECU_PER_HA "Irrigated once a year - Sugar beet"
cap label var I03B5_ECU_PER_HA "Irrigated once a year - Sunflower"
cap label var I03B6_ECU_PER_HA "Irrigated once a year - Soya"
cap label var I03B7_ECU_PER_HA "Irrigated once a year - fodder plants"
cap label var I03B8_ECU_PER_HA "Irrigated once a year - fruit and berry orchards"
cap label var I03B9_ECU_PER_HA "Irrigated once a year - Citrus fruit"
cap label var I06_ECU_PER_HA "Set aside land - total"
cap label var I06A_ECU_PER_HA "Set aside land - left fallow"
cap label var I06B_ECU_PER_HA "Set aside land - grazing"
cap label var I06C_ECU_PER_HA "Set aside land - lentils, chick peas and vetches"
cap label var I08AD22_ECU_PER_HA "Set-aside areas under incentive schemes - fallow land with no economic use"
cap label var J01_ECU_PER_HEAD "Equidae"
cap label var J01_ECU_PER_HEAD_D "Equidae"
cap label var J02_ECU_PER_HEAD "Bovine under one year old - total"
cap label var J02_ECU_PER_HEAD_D "Bovine under one year old - total"
cap label var J02A_ECU_PER_HEAD "Bovine under one year old - males"
cap label var J02A_ECU_PER_HEAD_D "Bovine under one year old - males"
cap label var J02B_ECU_PER_HEAD "Bovine under one year old - females"
cap label var J02B_ECU_PER_HEAD_D "Bovine under one year old - females"
cap label var J03_ECU_PER_HEAD "Bovine under 2 years - males"
cap label var J03_ECU_PER_HEAD_D "Bovine under 2 years - males"
cap label var J04_ECU_PER_HEAD "Bovine under 2 years - females"
cap label var J04_ECU_PER_HEAD_D "Bovine under 2 years - females"
cap label var J05_ECU_PER_HEAD "Bovine 2 years and older - males"
cap label var J05_ECU_PER_HEAD_D "Bovine 2 years and older - males"
cap label var J06_ECU_PER_HEAD "Heifers, 2 years and older"
cap label var J06_ECU_PER_HEAD_D "Heifers, 2 years and older"
cap label var J07_ECU_PER_HEAD "Dairy cows"
cap label var J07_ECU_PER_HEAD_D "Dairy cows"
cap label var J08_ECU_PER_HEAD "Bovine 2 years old and over - other cows"
cap label var J08_ECU_PER_HEAD_D "Bovine 2 years old and over - other cows"
cap label var J09_ECU_PER_HEAD "Sheep - total"
cap label var J09_ECU_PER_HEAD_D "Sheep - total"
cap label var J09A_ECU_PER_HEAD "Sheep - breeding females"
cap label var J09A_ECU_PER_HEAD_D "Sheep - breeding females"
cap label var J09B_ECU_PER_HEAD "Sheep, others"
cap label var J09B_ECU_PER_HEAD_D "Sheep, others"
cap label var J10_ECU_PER_HEAD "Goats"
cap label var J10_ECU_PER_HEAD_D "Goats"
cap label var J10A_ECU_PER_HEAD "Goats - breeding females"
cap label var J10A_ECU_PER_HEAD_D "Goats - breeding females"
cap label var J10B_ECU_PER_HEAD "Goats - others"
cap label var J10B_ECU_PER_HEAD_D "Goats - others"
cap label var J11_ECU_PER_HEAD "Pigs - piglets under 20 kg"
cap label var J12_ECU_PER_HEAD "Pigs - breeding sows over 50 kg"
cap label var J13_ECU_PER_HEAD "Pigs - others"
cap label var J14_ECU_PER_100_HDS "Poultry - broilers"
cap label var J15_ECU_PER_100_HDS "Laying hens"
cap label var J16_ECU_PER_100_HDS "Poultry - others"
cap label var J16A_ECU_PER_100_HDS "Turkeys"
cap label var J16B_ECU_PER_100_HDS "Ducks"
cap label var J16C_ECU_PER_100_HDS "Goose"
cap label var J16D_ECU_PER_100_HDS "Other poultry"
cap label var J17_ECU_PER_HEAD "Rabbits (breeding females)"
cap label var J18_ECU_PER_HEAD "Beehives"
cap label var J19_ECU_PER_HEAD "Other livestock"
cap label var R132_ECU_PER_HA "Herbaceous oil-seed plants"
cap label var R135_ECU_PER_HA "Other industrial plants"
cap label var R139_ECU_PER_HARVEST "Mushrooms"
cap label var R334_ECU_PER_HA "Other oil seed"
cap label var MSH_HRV_Y "Mushrooms: average number of harvests per year"
cap label var EXCHG_RT "National currency for 1 Euro/ECU"
cap label var RD "RD: Threshold for SGMH/SGMF (fodder deficit)"
cap label var RS "RS: Threshold for SGMH/SGMF (fodder surpluse)"
cap label var RV "RV: Coefficient for fodder area valuation"
cap label var B_1_1_1_ECU_PER_HA "Common wheat and spelt"
cap label var B_1_1_2_ECU_PER_HA "Durum wheat"
cap label var B_1_1_3_ECU_PER_HA "Rye"
cap label var B_1_1_4_ECU_PER_HA "Barley"
cap label var B_1_1_5_ECU_PER_HA "Oats"
cap label var B_1_1_6_ECU_PER_HA "Grain maize"
cap label var B_1_1_7_ECU_PER_HA "Rice"
cap label var B_1_1_99_ECU_PER_HA "Other cereals"
cap label var B_1_2_ECU_PER_HA "Pulses - total"
cap label var B_1_2_1_ECU_PER_HA "Peas, field beans and sweet lupines"
cap label var B_1_2_2_ECU_PER_HA "Pulses other than peas, field beans and sweet lupines"
cap label var B_1_3_ECU_PER_HA "Potatoes"
cap label var B_1_4_ECU_PER_HA "Sugar beet"
cap label var B_1_5_ECU_PER_HA "Fodder roots and brassicas"
cap label var B_1_6_1_ECU_PER_HA "Tobacco"
cap label var B_1_6_2_ECU_PER_HA "Hops"
cap label var B_1_6_3_ECU_PER_HA "Cotton"
cap label var B_1_6_4_ECU_PER_HA "Rape and turnip"
cap label var B_1_6_5_ECU_PER_HA "Sunflower"
cap label var B_1_6_6_ECU_PER_HA "Soya"
cap label var B_1_6_7_ECU_PER_HA "Linseed (oil flax)"
cap label var B_1_6_8_ECU_PER_HA "Other oil seed crops"
cap label var B_1_6_9_ECU_PER_HA "Flax"
cap label var B_1_6_10_ECU_PER_HA "Hemp"
cap label var B_1_6_11_ECU_PER_HA "Other textile crops"
cap label var B_1_6_12_ECU_PER_HA "Aromatic, medicinal and culinary plants (same as previous D13D2)"
cap label var B_1_6_99_ECU_PER_HA "Industrial plants not mentioned elsewhere"
cap label var B_1_7_ECU_PER_HA "Fresh vegetables, melons, strawberries"
cap label var B_1_7_1_ECU_PER_HA "Fresh vegetables, melons, strawberries - outdoor"
cap label var B_1_7_1_1_ECU_PER_HA "Fresh vegetables, melons, strawberries - outdoor - open field"
cap label var B_1_7_1_2_ECU_PER_HA "Fresh vegetables, melons, strawberries - outdoor - market garden"
cap label var B_1_7_2_ECU_PER_HA "Fresh vegetables, melons, strawberries - under glass"
cap label var B_1_8_1_ECU_PER_HA "Flowers - outdoor"
cap label var B_1_8_2_ECU_PER_HA "Flowers - under glass"
cap label var B_1_9_ECU_PER_HA "Forage plants - total"
cap label var B_1_9_1_ECU_PER_HA "Forage plants - temporary grass"
cap label var B_1_9_2_ECU_PER_HA "Forage plants - other green fodder - total"
cap label var B_1_9_2_1_ECU_PER_HA "Forage plants - other green fodder - green maize"
cap label var B_1_9_2_2_ECU_PER_HA "Forage plants - other green fodder - leguminous plants"
cap label var B_1_9_2_99_ECU_PER_HA "Forage plants - other green fodder - other than green maize and leguminous"
cap label var B_1_10_ECU_PER_HA "Seeds and seedlings"
cap label var B_1_11_ECU_PER_HA "Other crops"
cap label var B_1_12_1_ECU_PER_HA "Fallow land without subsidies"
cap label var B_1_12_2_ECU_PER_HA "Fallow land subject to payment of subsidies with no economic use"
cap label var B_2_ECU_PER_HA "Kitchen gardens"
cap label var B_3_ECU_PER_HA "Permanent grassland and meadow - total"
cap label var B_3_1_ECU_PER_HA "Permanent grassland and meadow - pasture and meadow"
cap label var B_3_2_ECU_PER_HA "Permanent grassland and meadow - rough grazings"
cap label var B_3_3_ECU_PER_HA "Permanent grassland and meadow - no used for production, eligible for subsidies"
cap label var B_4_1_ECU_PER_HA "Fruit and berry plantations - total"
cap label var B_4_1_1_ECU_PER_HA "Fruit species"
cap label var B_4_1_1_1_ECU_PER_HA "Fruit species of temperate climate zones"
cap label var B_4_1_1_2_ECU_PER_HA "Fruit species of subtropical climate zones"
cap label var B_4_1_2_ECU_PER_HA "Berry species"
cap label var B_4_1_3_ECU_PER_HA "Fruit and berry plantations - nuts"
cap label var B_4_2_ECU_PER_HA "Citrus plantations"
cap label var B_4_3_ECU_PER_HA "Olive plantations - total"
cap label var B_4_3_1_ECU_PER_HA "Olive plantations - table olives"
cap label var B_4_3_2_ECU_PER_HA "Olive plantations - oil production"
cap label var B_4_4_ECU_PER_HA "Vineyards - total"
cap label var B_4_4_1_ECU_PER_HA "Vineyards - quality wine"
cap label var B_4_4_2_ECU_PER_HA "Vineyards - other wines"
cap label var B_4_4_3_ECU_PER_HA "Vineyards - table grapes"
cap label var B_4_4_4_ECU_PER_HA "Vineyards - raisins"
cap label var B_4_5_ECU_PER_HA "Nurseries"
cap label var B_4_6_ECU_PER_HA "Other permanent crops"
cap label var B_4_7_ECU_PER_HA "Permanent crops under glass"
cap label var B_6_1_ECU_PER_100_M2 "Mushrooms"
cap label var B_6_1_ECU_PER_HARVEST "Mushrooms: average number of harvests per year"
cap label var C_1_ECU_PER_HEAD "Equidae"
cap label var C_2_1_ECU_PER_HEAD "Bovine under one year old - total"
cap label var C_2_2_ECU_PER_HEAD "Bovine between 1 and 2 years - males"
cap label var C_2_3_ECU_PER_HEAD "Bovine between 1 and 2 years - females"
cap label var C_2_4_ECU_PER_HEAD "Bovine 2 years and older - males"
cap label var C_2_5_ECU_PER_HEAD "Heifers, 2 years and older"
cap label var C_2_6_ECU_PER_HEAD "Dairy cows"
cap label var C_2_99_ECU_PER_HEAD "Bovine 2 years old and over - other cows"
cap label var C_3_1_ECU_PER_HEAD "Sheep - total"
cap label var C_3_1_1_ECU_PER_HEAD "Sheep - breeding females"
cap label var C_3_1_99_ECU_PER_HEAD "Sheep, others"
cap label var C_3_2_ECU_PER_HEAD "Goats"
cap label var C_3_2_1_ECU_PER_HEAD "Goats - breeding females"
cap label var C_3_2_99_ECU_PER_HEAD "Goats - others"
cap label var C_4_1_ECU_PER_HEAD "Pigs - piglets under 20 kg"
cap label var C_4_2_ECU_PER_HEAD "Pigs - breeding sows over 50 kg"
cap label var C_4_99_ECU_PER_HEAD "Pigs - others"
cap label var C_5_1_ECU_PER_100_HDS "Poultry - broilers"
cap label var C_5_2_ECU_PER_100_HDS "Laying hens"
cap label var C_5_3_ECU_PER_100_HDS "Poultry - others"
cap label var C_5_3_1_ECU_PER_100_HDS "Poultry - others-Turkeys"
cap label var C_5_3_2_ECU_PER_100_HDS "Poultry - others - Ducks"
cap label var C_5_3_3_ECU_PER_100_HDS "Poultry - others - Geese"
cap label var C_5_3_4_ECU_PER_100_HDS "Poultry - others -Ostriches"
cap label var C_6_ECU_PER_HEAD "Rabbits (breeding females)"
cap label var C_7_ECU_PER_HIVE "Beehives"
cap label var ANI "Animal products"
cap label var VEG "Vegetal products"
cap label var TOTAL "Total"
