cap label var UNE_BEN "Unemployed receiving benefits/assistance"
cap label var UNE_NBEN "Unemployed not receiving benefits/assistance"
cap label var REG "Registered jobseekers"
cap label var REG_UNE "Registered unemployed"
cap label var REG_UNE_LT "Registered long-term unemployed (>12 months)"
cap label var REG_UNE_BEN "Registered unemployed receiving benefits/assistance"
cap label var REG_UNE_NBEN "Registered unemployed not receiving benefits/assistance"
cap label var REG_OTH "Other registered jobseekers"
cap label var NREG_UNE_BEN "Not registered unemployed but receiving benefits/assistance"
cap label var NREG_UNE_NBEN "Not registered unemployed and not receiving benefits/assistance"
cap label var UNK "Unknown"
