cap label var TOTAL "Total"
cap label var TOT_X_CP041_042 "Total except actual rents"
cap label var CP00_X_042 "All items HICP excluding imputed rentals for housing"
cap label var CP00 "All-items HICP"
cap label var CP01 "Food and non-alcoholic beverages"
cap label var CP011 "Food"
cap label var CP0111 "Bread and cereals"
cap label var CP01111 "Rice"
cap label var CP01111A "Long-grain rice (1 kg)"
cap label var CP01112 "Flours and other cereals"
cap label var CP01112A "Wheat flour (1 kg)"
cap label var CP01112B "Cornflakes (1 kg)"
cap label var CP01113 "Bread"
cap label var CP01113A "White bread, loaf (1 kg)"
cap label var CP01114 "Other bakery products"
cap label var CP01115 "Pizza and quiche"
cap label var CP01115A "Pizza, frozen (500 g)"
cap label var CP01116 "Pasta products and couscous"
cap label var CP01116A "Pasta, without eggs (1 kg)"
cap label var CP01117 "Breakfast cereals"
cap label var CP01118 "Other cereal products"
cap label var CP0112 "Meat"
cap label var CP01121 "Beef and veal"
cap label var CP01121A "Beef, minced (1 kg)"
cap label var CP01122 "Pork"
cap label var CP01122A "Pork, cutlet ("escalope") (1 kg)"
cap label var CP01122B "Pork, loin chop (B2) (1 kg)"
cap label var CP01123 "Lamb and goat"
cap label var CP01124 "Poultry"
cap label var CP01124A "Whole chicken (1 kg)"
cap label var CP01124B "Chicken breast, fillets (1 kg)"
cap label var CP01125 "Other meats"
cap label var CP01126_01127 "Dried, salted or smoked meat and edible meat offal"
cap label var CP01126 "Edible offal"
cap label var CP01127 "Dried, salted or smoked meat"
cap label var CP01127A "Sausage, Frankfurter/Wiener (1 kg)"
cap label var CP01127B "Sausage, salami type (1 kg)"
cap label var CP01128 "Other meat preparations"
cap label var CP01128A "Other preserved or processed meat and meat preparations"
cap label var CP01128B "Other fresh, chilled or frozen edible meat"
cap label var CP0113 "Fish and seafood"
cap label var CP01131_01132 "Fresh, chilled or frozen fish"
cap label var CP01131 "Fresh or chilled fish"
cap label var CP01131A "Salmon, steak (1 kg)"
cap label var CP01132 "Frozen fish"
cap label var CP01133_01134 "Fresh, chilled or frozen seafood"
cap label var CP01133 "Fresh or chilled seafood"
cap label var CP01134 "Frozen seafood"
cap label var CP01135 "Dried, smoked or salted fish and seafood"
cap label var CP01136 "Other preserved or processed fish and seafood and fish and seafood preparations"
cap label var CP01136A "Tinned pink tuna (1 kg/net)"
cap label var CP01136B "Fish fingers (500 g)"
cap label var CP0114 "Milk, cheese and eggs"
cap label var CP01141 "Fresh whole milk"
cap label var CP01141A "Milk, fresh, unskimmed (1 l)"
cap label var CP01142 "Fresh low fat milk"
cap label var CP01143 "Preserved milk"
cap label var CP01144 "Yoghurt"
cap label var CP01144A "Natural yoghurt (1 kg/l)"
cap label var CP01144B "Fruit yoghurt (1 kg/l)"
cap label var CP01145 "Cheese and curd"
cap label var CP01145A "Cheese, Camembert type (1 kg)"
cap label var CP01145B "Cheese, Gouda type (1 kg)"
cap label var CP01145C "Cream cheese (200 g)"
cap label var CP01146 "Other milk products"
cap label var CP01147 "Eggs"
cap label var CP01147A "Chicken eggs (10 eggs)"
cap label var CP0115 "Oils and fats"
cap label var CP01151 "Butter"
cap label var CP01151A "Butter, unsalted (250 g)"
cap label var CP01152 "Margarine and other vegetable fats"
cap label var CP01152A "Margarine (250 g)"
cap label var CP01153 "Olive oil"
cap label var CP01153A "Olive oil (1 l)"
cap label var CP01154 "Other edible oils"
cap label var CP01154A "Vegetable oil (1 l)"
cap label var CP01155 "Other edible animal fats"
cap label var CP0116 "Fruit"
cap label var CP0116A "Citrus fruits (fresh, chilled or frozen)"
cap label var CP0116B "Bananas (fresh, chilled or frozen)"
cap label var CP0116C "Apples (fresh, chilled or frozen)"
cap label var CP0116D "Pears (fresh, chilled or frozen)"
cap label var CP0116E "Stone fruits (fresh, chilled or frozen)"
cap label var CP0116F "Berries (fresh, chilled or frozen)"
cap label var CP0116G "Other fresh, chilled or frozen fruits"
cap label var CP01161 "Fresh or chilled fruit"
cap label var CP01161A "Apples (1 kg)"
cap label var CP01161B "Fresh bananas (1 kg)"
cap label var CP01162 "Frozen fruit"
cap label var CP01163 "Dried fruit and nuts"
cap label var CP01164 "Preserved fruit and fruit-based products"
cap label var CP01164A "Canned fruit (1 kg/net)"
cap label var CP0117 "Vegetables"
cap label var CP0117A "Leaf and stem vegetables (fresh, chilled or frozen)"
cap label var CP0117B "Cabbages (fresh or chilled)"
cap label var CP0117C "Vegetable grown for their fruit (fresh, chilled or frozen)"
cap label var CP0117D "Root crops, non-starchy bulbs and mushrooms (fresh, chilled or frozen)"
cap label var CP01171 "Fresh or chilled vegetables other than potatoes and other tubers"
cap label var CP01171A "Fresh carrots (1 kg)"
cap label var CP01171B "Fresh tomatoes, round (1 kg)"
cap label var CP01172 "Frozen vegetables other than potatoes and other tubers"
cap label var CP01173 "Dried vegetables, other preserved or processed vegetables"
cap label var CP01173A "Tinned sweet corn (500 g/net)"
cap label var CP01173B "Dried vegetables"
cap label var CP01173C "Other preserved or processed vegetables"
cap label var CP01174 "Potatoes"
cap label var CP01174A "Potatoes (1 kg)"
cap label var CP01174B "Frozen French fries (1 kg)"
cap label var CP01175 "Crisps"
cap label var CP01175A "Potato crisps, single pack (200 g)"
cap label var CP01176 "Other tubers and products of tuber vegetables"
cap label var CP0118 "Sugar, jam, honey, chocolate and confectionery"
cap label var CP01181 "Sugar"
cap label var CP01181A "White sugar (1 kg)"
cap label var CP01182 "Jams, marmalades and honey"
cap label var CP01182A "Jam (1 kg)"
cap label var CP01183 "Chocolate"
cap label var CP01183A "Chocolate, milk (1 kg)"
cap label var CP01184 "Confectionery products"
cap label var CP01184A "Chewing gum (1 package)"
cap label var CP01185 "Edible ices and ice cream"
cap label var CP01185A "Ice cream (1 l)"
cap label var CP01186 "Artificial sugar substitutes"
cap label var CP01186A "Other sugar products"
cap label var CP0119 "Food products n.e.c."
cap label var CP01191 "Sauces, condiments"
cap label var CP01191A "Tomato ketchup (1 kg)"
cap label var CP01192 "Salt, spices and culinary herbs"
cap label var CP01192A "Mineral salt (1 kg)"
cap label var CP01192B "Black pepper (100 g)"
cap label var CP01193 "Baby food"
cap label var CP01193A "Baby food, meat base (500 g)"
cap label var CP01194 "Ready-made meals"
cap label var CP01199 "Other food products n.e.c."
cap label var CP01199A "Baker's yeast, dessert preparations, soups"
cap label var CP012 "Non-alcoholic beverages"
cap label var CP0121 "Coffee, tea and cocoa"
cap label var CP01211 "Coffee"
cap label var CP01211A "Coffee (1 kg)"
cap label var CP01212 "Tea"
cap label var CP01212A "Black tea (25 bags)"
cap label var CP01213 "Cocoa and powdered chocolate"
cap label var CP01213A "Cocoa instant drink, powder (1 kg)"
cap label var CP0122 "Mineral waters, soft drinks, fruit and vegetable juices"
cap label var CP01221 "Mineral or spring waters"
cap label var CP01221A "Mineral water, carbonated (1 l)"
cap label var CP01221B "Mineral water, still (1 l)"
cap label var CP01222 "Soft drinks"
cap label var CP01222A "Carbonated drink, orange flavoured (1 l)"
cap label var CP01223 "Fruit and vegetables juices"
cap label var CP01223A "Fruit juices"
cap label var CP01223B "Orange juice (1 l)"
cap label var CP01223C "Vegetable juices"
cap label var CP02 "Alcoholic beverages, tobacco and narcotics"
cap label var CP021 "Alcoholic beverages"
cap label var CP0211 "Spirits"
cap label var CP02111 "Spirits and liqueurs"
cap label var CP02111A "Vodka (1 l)"
cap label var CP02112 "Alcoholic soft drinks"
cap label var CP0212 "Wine"
cap label var CP02121 "Wine from grapes"
cap label var CP02121A "Red wine (0.75 l)"
cap label var CP02121B "White wine (0.75 l)"
cap label var CP02122 "Wine from other fruits"
cap label var CP02123 "Fortified wines"
cap label var CP02124 "Wine-based drinks"
cap label var CP0213 "Beer"
cap label var CP02131 "Lager beer"
cap label var CP02131A "Beer (1 l)"
cap label var CP02132 "Other alcoholic beer"
cap label var CP02133 "Low and non-alcoholic beer"
cap label var CP02134 "Beer-based drinks"
cap label var CP022 "Tobacco"
cap label var CP0220 "Tobacco"
cap label var CP02201 "Cigarettes"
cap label var CP02201A "Cigarettes (20 cigarettes)"
cap label var CP02202 "Cigars"
cap label var CP02203 "Other tobacco products"
cap label var CP023 "Narcotics"
cap label var CP0230 "Narcotics"
cap label var CP02300 "Narcotics"
cap label var CP03 "Clothing and footwear"
cap label var CP031 "Clothing"
cap label var CP0311 "Clothing materials"
cap label var CP03110 "Clothing materials"
cap label var CP03110A "Cotton (1 m2)"
cap label var CP0312 "Garments"
cap label var CP03121 "Garments for men"
cap label var CP03121A "Men's suit, wool (1 suit)"
cap label var CP03121B "Men's trousers (1 piece)"
cap label var CP03121C "Men's blue jeans (1 piece)"
cap label var CP03121D "Men's shirt (1 piece)"
cap label var CP03121E "Men's T-shirt, short sleeves (1 piece)"
cap label var CP03121F "Men's boxer briefs (1 piece)"
cap label var CP03122 "Garments for women"
cap label var CP03122A "Ladies' top coat (1 piece)"
cap label var CP03122B "Ladies' blazer, woolmix (1 piece)"
cap label var CP03122C "Ladies' straight trousers, synthetic (1 piece)"
cap label var CP03122D "Ladies' jeans (1 piece)"
cap label var CP03122E "Ladies' skirt (1 piece)"
cap label var CP03122F "Ladies' blouse (1 piece)"
cap label var CP03122G "Ladies' T-shirt (1 piece)"
cap label var CP03122H "Ladies' pullover (1 piece)"
cap label var CP03122I "Brassiere, push-up (1 piece)"
cap label var CP03122J "Tights (1 piece)"
cap label var CP03122K "Ladies bikini (1 set)"
cap label var CP03123 "Garments for infants (0 to 2 years) and children (3 to 13 years)"
cap label var CP03123A "Children' s jeans trousers (1 piece)"
cap label var CP03123B "Children' T-shirt, long sleeves (1 piece)"
cap label var CP03123C "Girls' skirt (1 piece)"
cap label var CP03123D "Girls' tights (1 piece)"
cap label var CP03123E "Boys' socks (1 pair)"
cap label var CP03123F "Children' socks (1 pair)"
cap label var CP0313 "Other articles of clothing and clothing accessories"
cap label var CP03131 "Other articles of clothing"
cap label var CP03132 "Clothing accessories"
cap label var CP0314 "Cleaning, repair and hire of clothing"
cap label var CP03141 "Cleaning of clothing"
cap label var CP03141A "Dry cleaning (1 service)"
cap label var CP03142 "Repair and hire of clothing"
cap label var CP032 "Footwear"
cap label var CP0321_0322 "Shoes and other footwear; repair and hire of footwear"
cap label var CP0321 "Shoes and other footwear"
cap label var CP03211 "Footwear for men"
cap label var CP03211A "Men's lace-up shoes (1 pair)"
cap label var CP03211B "Men's street shoes (1 pair)"
cap label var CP03212 "Footwear for women"
cap label var CP03212A "Ladies' conventional court shoes (1 pair)"
cap label var CP03212B "Ladies' long boots (1 pair)"
cap label var CP03213 "Footwear for infants and children"
cap label var CP03213A "Children's sport shoes (1 pair)"
cap label var CP0322 "Repair and hire of footwear"
cap label var CP03220 "Repair and hire of footwear"
cap label var CP03220A "Services, Cobbler (1 service)"
cap label var CP04 "Housing, water, electricity, gas and other fuels"
cap label var CP041 "Actual rentals for housing"
cap label var CP0411_0412 "Actual rentals paid by tenants; other actual rentals"
cap label var CP0411 "Actual rentals paid by tenants"
cap label var CP04110 "Actual rentals paid by tenants"
cap label var CP0412 "Other actual rentals"
cap label var CP04121 "Actual rentals paid by tenants for secondary residences"
cap label var CP04122 "Garage rentals and other rentals paid by tenants"
cap label var CP042 "Imputed rentals for housing"
cap label var CP0421 "Imputed rentals of owner-occupiers"
cap label var CP04210 "Imputed rentals of owner-occupiers"
cap label var CP0422 "Other imputed rentals"
cap label var CP04220 "Other imputed rentals"
cap label var CP043 "Maintenance and repair of the dwelling"
cap label var CP0431 "Materials for the maintenance and repair of the dwelling"
cap label var CP04310 "Materials for the maintenance and repair of the dwelling"
cap label var CP04310A "Paint, indoor use (10 l)"
cap label var CP04310B "Silicone (300 ml)"
cap label var CP04310C "Cement (25 kg)"
cap label var CP0432 "Services for the maintenance and repair of the dwelling"
cap label var CP04321 "Services of plumbers"
cap label var CP04322 "Services of electricians"
cap label var CP04323 "Maintenance services for heating systems"
cap label var CP04324 "Services of painters"
cap label var CP04325 "Services of carpenters"
cap label var CP04329 "Other services for maintenance and repair of the dwelling"
cap label var CP044_X_0444 "Water supply and miscellaneous services except other services relating to the dwelling n.e.c. (water and sanitation)"
cap label var CP044 "Water supply and miscellaneous services relating to the dwelling"
cap label var CP0441 "Water supply"
cap label var CP04410 "Water supply"
cap label var CP0442 "Refuse collection"
cap label var CP04420 "Refuse collection"
cap label var CP0443 "Sewerage collection"
cap label var CP04430 "Sewerage collection"
cap label var CP0444 "Other services relating to the dwelling n.e.c."
cap label var CP04441 "Maintenance charges in multi-occupied buildings"
cap label var CP04442 "Security services"
cap label var CP04449 "Other services related to dwelling"
cap label var CP045 "Electricity, gas and other fuels"
cap label var CP0451 "Electricity"
cap label var CP04510 "Electricity"
cap label var CP0452 "Gas"
cap label var CP04521 "Natural gas and town gas"
cap label var CP04522 "Liquefied hydrocarbons (butane, propane, etc.)"
cap label var CP0453 "Liquid fuels"
cap label var CP04530 "Liquid fuels"
cap label var CP0454 "Solid fuels"
cap label var CP04541 "Coal"
cap label var CP04549 "Other solid fuels"
cap label var CP0455 "Heat energy"
cap label var CP04550 "Heat energy"
cap label var CP05 "Furnishings, household equipment and routine household maintenance"
cap label var CP051 "Furniture and furnishings, carpets and other floor coverings"
cap label var CP0511 "Furniture and furnishings"
cap label var CP05111 "Household furniture"
cap label var CP05111A "Double bed frame, pressboard (1 piece)"
cap label var CP05111B "Sofa set (1 set)"
cap label var CP05111C "Kitchen table (1 piece)"
cap label var CP05111D "Kitchen chair (1 piece)"
cap label var CP05111E "Pocket spring mattress (1 piece)"
cap label var CP05111F "Wardrobe (1 piece)"
cap label var CP05111G "Armchair (1 piece)"
cap label var CP05111H "Coffee table (1 piece)"
cap label var CP05111I "Bookcase (1 piece)"
cap label var CP05112 "Garden furniture"
cap label var CP05113 "Lighting equipment"
cap label var CP05113A "Table lamp (1 piece)"
cap label var CP05119 "Other furniture and furnishings"
cap label var CP0512 "Carpets and other floor coverings"
cap label var CP05121 "Carpet and rugs"
cap label var CP05122 "Other floor coverings"
cap label var CP05123 "Services of laying of fitted carpets and floor coverings"
cap label var CP0513 "Repair of furniture, furnishings and floor coverings"
cap label var CP05130 "Repair of furniture, furnishings and floor coverings"
cap label var CP052 "Household textiles"
cap label var CP0520 "Household textiles"
cap label var CP05201 "Furnishings fabrics and curtains"
cap label var CP05201A "Curtain material (1 m2)"
cap label var CP05202 "Bed linen"
cap label var CP05202A "Duvet (1 piece)"
cap label var CP05202B "Bedlinen (1 set)"
cap label var CP05202C "Blanket (1 piece)"
cap label var CP05203 "Table linen and bathroom linen"
cap label var CP05203A "Towel (1 piece)"
cap label var CP05204 "Repair of household textiles"
cap label var CP05209 "Other household textiles"
cap label var CP053 "Household appliances"
cap label var CP0531_0532 "Major household appliances whether electric or not and small electric household appliances"
cap label var CP0531 "Major household appliances whether electric or not"
cap label var CP05311 "Refrigerators, freezers and fridge-freezers"
cap label var CP05311A "Refrigerator, undercounter, with freezer (1 piece)"
cap label var CP05311A1 "Refrigerator, undercounter, with freezer, energy efficiency A/A+ (1 piece)"
cap label var CP05311A2 "Refrigerator, undercounter, with freezer, energy efficiency A+/A++ (1 piece)"
cap label var CP05311B1 "Fridge-freezer, energy efficiency A (1 piece)"
cap label var CP05311B2 "Fridge-freezer, energy efficiency A+ (1 piece)"
cap label var CP05312 "Clothes washing machines, clothes drying machines and dish washing machines"
cap label var CP05312A1 "Washing machine, 4.5-5 kg (1 piece)"
cap label var CP05312A2 "Washing machine, 6-7 kg, energy efficiency A/A+ (1 piece)"
cap label var CP05312A3 "Washing machine, 6-7 kg, energy efficiency A++/A+++ (1 piece)"
cap label var CP05313 "Cookers"
cap label var CP05313A "Microwave oven (1 piece)"
cap label var CP05314 "Heaters, air conditioners"
cap label var CP05315 "Cleaning equipment"
cap label var CP05315A1 "Vacuum cleaner, 1400-1600 W (1 piece)"
cap label var CP05315A2 "Vacuum cleaner, 1600-2000 W (1 piece)"
cap label var CP05315A3 "Vacuum cleaner, 1600-2200 W (1 piece)"
cap label var CP05315A4 "Vacuum cleaner, 1400 W (1 piece)"
cap label var CP05319 "Other major household appliances"
cap label var CP0532 "Small electric household appliances"
cap label var CP05321 "Food processing appliances"
cap label var CP05322 "Coffee machines, tea-makers and similar appliances"
cap label var CP05322A1 "Kettle, 1.5l (1 piece)"
cap label var CP05322A2 "Kettle, 1.7l (1 piece)"
cap label var CP05323 "Irons"
cap label var CP05324 "Toasters and grills"
cap label var CP05329 "Other small electric household appliances"
cap label var CP0533 "Repair of household appliances"
cap label var CP05330 "Repair of household appliances"
cap label var CP054 "Glassware, tableware and household utensils"
cap label var CP0540 "Glassware, tableware and household utensils"
cap label var CP05401 "Glassware, crystal-ware, ceramic ware and chinaware"
cap label var CP05401A "Glass for water (1 piece)"
cap label var CP05401B "Flat plate (1 piece)"
cap label var CP05401C "Cup and saucer (1 set)"
cap label var CP05402 "Cutlery, flatware and silverware"
cap label var CP05403 "Non-electric kitchen utensils and articles"
cap label var CP05403A "Cooking pot, stainless steel (1 set)"
cap label var CP05404 "Repair of glassware, tableware and household utensils"
cap label var CP055 "Tools and equipment for house and garden"
cap label var CP0551_0552 "Major tools and equipment; small tools and miscellaneous accessories"
cap label var CP0551 "Major tools and equipment"
cap label var CP05511 "Motorized major tools and equipment"
cap label var CP05512 "Repair, leasing and rental of major tools and equipment"
cap label var CP0552 "Small tools and miscellaneous accessories"
cap label var CP05521 "Non-motorised small tools"
cap label var CP05522 "Miscellaneous small tool accessories"
cap label var CP05522A "Battery (1 piece)"
cap label var CP05522B "Light bulb, standard (1 piece)"
cap label var CP05522C "Light bulb energy saving type (1 piece)"
cap label var CP05523 "Repair of non-motorised small tools and miscellaneous accessories"
cap label var CP056 "Goods and services for routine household maintenance"
cap label var CP0561 "Non-durable household goods"
cap label var CP05611 "Cleaning and maintenance products"
cap label var CP05611A "Dish washer tablets (10 tablets)"
cap label var CP05611B "Detergent for washing machine, concentrated (1 kg)"
cap label var CP05611C "Detergent for washing machine, unconcentrated (1 kg)"
cap label var CP05611D "All-purposes household cleaner (1 l)"
cap label var CP05611E "Cleaner for WC (1 l)"
cap label var CP05611F "Cleaning liquid for windows (1 l)"
cap label var CP05611G1 "Detergent for washing machine, powder, 70-90 g/wash (1 kg)"
cap label var CP05611G2 "Detergent for washing machine, powder, > 90 g/wash (1 kg)"
cap label var CP05612 "Other non-durable small household articles"
cap label var CP05612A "Scourer sponge (1 piece)"
cap label var CP0562 "Domestic services and household services"
cap label var CP05621 "Domestic services by paid staff"
cap label var CP05622 "Cleaning services"
cap label var CP05623 "Hire of furniture and furnishings"
cap label var CP05629 "Other domestic services and household services"
cap label var CP06 "Health"
cap label var CP061 "Medical products, appliances and equipment"
cap label var CP0611 "Pharmaceutical products"
cap label var CP06110 "Pharmaceutical products"
cap label var CP06110A "Acetylsalicylic acid (10 tablets)"
cap label var CP06110B "Aciclovir (2 g)"
cap label var CP06110C "Alprazolam (10 tablets)"
cap label var CP06110D "Atorvastatin (10 tablets)"
cap label var CP06110E "Cetirizine (10 tablets)"
cap label var CP06110F "Ciprofloxacin (10 tablets)"
cap label var CP06110G "Clopidogrel (10 tablets)"
cap label var CP06110H "Diclofenac (100 g)"
cap label var CP06110I "Enalapril-Hydrochlorothiazide/HCTZ (10 tablets)"
cap label var CP06110J "Esomeprazole (10 tablets)"
cap label var CP06110K "Latanoprost (10 ml)"
cap label var CP06110L "Montelukast (10 tablets)"
cap label var CP06110M "Paracetamol (10 tablets)"
cap label var CP06110N "Risedronate (10 tablets)"
cap label var CP0612_0613 "Other medical products, therapeutic appliances and equipment"
cap label var CP0612 "Other medical products"
cap label var CP06121 "Pregnancy tests and mechanical contraceptive devices"
cap label var CP06121A "Pregnancy test (1 piece)"
cap label var CP06121B "Condoms (3 pieces)"
cap label var CP06129 "Other medical products n.e.c."
cap label var CP06129A "Plaster strips (10 strips)"
cap label var CP06129B "Joint bandage (1 m)"
cap label var CP06129C "Knee support (1 piece)"
cap label var CP06129D "Digital stick thermometer (1 piece)"
cap label var CP0613 "Therapeutic appliances and equipment"
cap label var CP06131 "Corrective eye-glasses and contact lenses"
cap label var CP06132 "Hearing aids"
cap label var CP06133 "Repair of therapeutic appliances and equipment"
cap label var CP06139 "Other therapeutic appliances and equipment"
cap label var CP062 "Out-patient services"
cap label var CP0621_0623 "Medical services and paramedical services"
cap label var CP0621 "Medical services"
cap label var CP06211 "General practice"
cap label var CP06211A "General practioner (1 service)"
cap label var CP06212 "Specialist practice"
cap label var CP06212A "Eye specialist, Ophthalmologist (1 service)"
cap label var CP0622 "Dental services"
cap label var CP06220 "Dental services"
cap label var CP06220A "Dentist, plastic filling (1 service)"
cap label var CP0623 "Paramedical services"
cap label var CP06231 "Services of medical analysis laboratories and X-ray centres"
cap label var CP06231A "Thorax X-ray (1 service)"
cap label var CP06232 "Thermal-baths, corrective-gymnastic therapy, ambulance and hire of therapeutic equipment"
cap label var CP06239 "Other paramedical services"
cap label var CP063 "Hospital services"
cap label var CP0630 "Hospital services"
cap label var CP06300 "Hospital services"
cap label var CP07 "Transport"
cap label var CP071 "Purchase of vehicles"
cap label var CP0711 "Motor cars"
cap label var CP07111 "New motor cars"
cap label var CP07112 "Second-hand motor cars"
cap label var CP0712_0714 "Motor cycles, bicycles and animal drawn vehicles"
cap label var CP0712 "Motor cycles"
cap label var CP07120 "Motor cycles"
cap label var CP0713 "Bicycles"
cap label var CP07130 "Bicycles"
cap label var CP0714 "Animal drawn vehicles"
cap label var CP07140 "Animal drawn vehicles"
cap label var CP072 "Operation of personal transport equipment"
cap label var CP0721 "Spare parts and accessories for personal transport equipment"
cap label var CP07211 "Tyres"
cap label var CP07211A "Summer tyres (4 tyres)"
cap label var CP07211B "Winter tyres (4 tyres)"
cap label var CP07212 "Spare parts for personal transport equipment"
cap label var CP07212A "Car battery (1 piece)"
cap label var CP07213 "Accessories for personal transport equipment"
cap label var CP0722 "Fuels and lubricants for personal transport equipment"
cap label var CP07221 "Diesel"
cap label var CP07222 "Petrol"
cap label var CP07223 "Other fuels for personal transport equipment"
cap label var CP07224 "Lubricants"
cap label var CP0723 "Maintenance and repair of personal transport equipment"
cap label var CP07230 "Maintenance and repair of personal transport equipment"
cap label var CP07230A "Replacement of brake pads (1 hour)"
cap label var CP07230B "Change of oil (1 service)"
cap label var CP07230C "Car wash (1 service)"
cap label var CP0724 "Other services in respect of personal transport equipment"
cap label var CP07241 "Hire of garages, parking spaces and personal transport equipment"
cap label var CP07241A "Car hire (7 days)"
cap label var CP07242 "Toll facilities and parking meters"
cap label var CP07243 "Driving lessons, tests, licences and road worthiness tests"
cap label var CP073_X_0733_0734 "Transport services except passenger transport by air, sea and inland waterway"
cap label var CP073 "Transport services"
cap label var CP0731 "Passenger transport by railway"
cap label var CP07311 "Passenger transport by train"
cap label var CP07311A "Rail travel, single ticket (1 ticket)"
cap label var CP07312 "Passenger transport by underground and tram"
cap label var CP0732 "Passenger transport by road"
cap label var CP07321 "Passenger transport by bus and coach"
cap label var CP07321A "Urban bus transport, single ticket (1 ticket)"
cap label var CP07322 "Passenger transport by taxi and hired car with driver"
cap label var CP07322A "Taxi (1 trip)"
cap label var CP0733 "Passenger transport by air"
cap label var CP07331 "Domestic flights"
cap label var CP07332 "International flights"
cap label var CP0734 "Passenger transport by sea and inland waterway"
cap label var CP07341 "Passenger transport by sea"
cap label var CP07342 "Passenger transport by inland waterway"
cap label var CP0735 "Combined passenger transport"
cap label var CP07350 "Combined passenger transport"
cap label var CP0736 "Other purchased transport services"
cap label var CP07361 "Funicular, cable-car and chair-lift transport"
cap label var CP07362 "Removal and storage services"
cap label var CP07369 "Other purchased transport services n.e.c."
cap label var CP08 "Communications"
cap label var CP081 "Postal services"
cap label var CP0810 "Postal services"
cap label var CP08101 "Letter handling services"
cap label var CP08109 "Other postal services"
cap label var CP082_083 "Telephone and telefax equipment and services"
cap label var CP082 "Telephone and telefax equipment"
cap label var CP0820_0830 "Telephone and telefax equipment and services"
cap label var CP0820 "Telephone and telefax equipment"
cap label var CP08201 "Fixed telephone equipment"
cap label var CP08202 "Mobile telephone equipment"
cap label var CP08203 "Other equipment of telephone and telefax equipment"
cap label var CP08204 "Repair of telephone or telefax equipment"
cap label var CP083 "Telephone and telefax services"
cap label var CP0830 "Telephone and telefax services"
cap label var CP08301 "Wired telephone services"
cap label var CP08302 "Wireless telephone services"
cap label var CP08303 "Internet access provision services"
cap label var CP08304 "Bundled telecommunication services"
cap label var CP08305 "Other information transmission services"
cap label var CP09 "Recreation and culture"
cap label var SPRT "Sports goods and services"
cap label var CLT "Cultural goods and services"
cap label var CP091 "Audio-visual, photographic and information processing equipment"
cap label var CP0911 "Equipment for the reception, recording and reproduction of sound and picture"
cap label var CP09111 "Equipment for the reception, recording and reproduction of sound"
cap label var CP09112_09119 "Equipment for the reception, recording and reproduction of sound, vision and picture"
cap label var CP09112 "Equipment for the reception, recording and reproduction of sound and vision"
cap label var CP09112A1 "Television, screen size 32'' (1 piece)"
cap label var CP09112A2 "Television, screen size 42'' (1 piece)"
cap label var CP09112B "DVD player (1 piece)"
cap label var CP09112C1 "DVD recorder with hard disc, 160-250 GB (1 piece)"
cap label var CP09112C2 "DVD recorder with hard disc, 200-300 GB (1 piece)"
cap label var CP09112D "Blu-ray disc player (1 piece)"
cap label var CP09113 "Portable sound and vision devices"
cap label var CP09113A1 "Portable MP3 player, 4 GB (1 piece)"
cap label var CP09113A2 "Portable MP3 player, 16 GB (1 piece)"
cap label var CP09119 "Other equipment for the reception, recording and reproduction of sound and picture"
cap label var CP0912 "Photographic and cinematographic equipment and optical instruments"
cap label var CP09121_09122 "Cameras and accessories for photographic and cinematographic equipment"
cap label var CP09121 "Cameras"
cap label var CP09121A "Compact digital camera, 12 Mpx (1 piece)"
cap label var CP09121B "Camcorder, HDD (1 piece)"
cap label var CP09122 "Accessories for photographic and cinematographic equipment"
cap label var CP09123 "Optical instruments"
cap label var CP0913 "Information processing equipment"
cap label var CP09131 "Personal computers"
cap label var CP09131A1 "Laptop, Hard Disc 320 GB, RAM 4 GB (1 piece)"
cap label var CP09131A2 "Laptop, Hard Disc 640 GB, RAM 4 GB (1 piece)"
cap label var CP09131A3 "Laptop, Hard Disc 750 GB, RAM 8 GB (1 piece)"
cap label var CP09131A4 "Laptop, Hard Disc 750 GB - 1 TB, RAM 8 GB (1 piece)"
cap label var CP09131B "Monitor, Full HD (1 piece)"
cap label var CP09132 "Accessories for information processing equipment"
cap label var CP09133 "Software"
cap label var CP09134 "Calculators and other information processing equipment"
cap label var CP0914 "Recording media"
cap label var CP09141 "Pre-recorded recording media"
cap label var CP09141A "Music CD - Pop Chart (1 piece)"
cap label var CP09141B "Movie DVD (1 piece)"
cap label var CP09142 "Unrecorded recording media"
cap label var CP09142A1 "Blank compact disc (CD-R) (1 piece)"
cap label var CP09142A2 "Blank compact disc (CD-R) (10 pieces)"
cap label var CP09142B "Blank DVDs (R), slim cases (10 pieces)"
cap label var CP09149 "Other recording media"
cap label var CP0915 "Repair of audio-visual, photographic and information processing equipment"
cap label var CP09150 "Repair of audio-visual, photographic and information processing equipment"
cap label var CP092 "Other major durables for recreation and culture"
cap label var CP0921_0922 "Major durables for indoor and outdoor recreation including musical instruments"
cap label var CP0921 "Major durables for outdoor recreation"
cap label var CP09211 "Camper vans, caravans and trailers"
cap label var CP09212 "Aeroplanes, microlight aircraft, gliders, hang-gliders and hot-air balloons"
cap label var CP09213 "Boats, outboard motors and fitting out of boats"
cap label var CP09214 "Horses, ponies and accessories"
cap label var CP09215 "Major items for games and sport"
cap label var CP0922 "Musical instruments and major durables for indoor recreation"
cap label var CP09221_09429 "Musical instruments (incl. rental and leasing services)"
cap label var CP09221 "Musical instruments"
cap label var CP09222 "Major durables for indoor recreation"
cap label var CP0923 "Maintenance and repair of other major durables for recreation and culture"
cap label var CP09230 "Maintenance and repair of other major durables for recreation and culture"
cap label var CP093 "Other recreational items and equipment, gardens and pets"
cap label var CP0931 "Games, toys and hobbies"
cap label var CP09311 "Games and hobbies"
cap label var CP09311A "Board game, Monopoly (1 piece)"
cap label var CP09311B "Video game, PlayStation 3 (1 piece)"
cap label var CP09312 "Toys and celebration articles"
cap label var CP0932 "Equipment for sport, camping and open-air recreation"
cap label var CP09321 "Equipment for sport"
cap label var CP09322 "Equipment for camping and open-air recreation"
cap label var CP09323 "Repair of equipment for sport, camping and open-air recreation"
cap label var CP0933 "Gardens, plants and flowers"
cap label var CP09331 "Garden products"
cap label var CP09331A "Potting soil (10 l)"
cap label var CP09332 "Plants and flowers"
cap label var CP0934_0935 "Pets and related products; veterinary and other services for pets"
cap label var CP0934 "Pets and related products"
cap label var CP09341 "Purchase of pets"
cap label var CP09342 "Products for pets"
cap label var CP09342A "Dog food, meat (1 kg)"
cap label var CP09342B "Dog food dry (1 kg)"
cap label var CP0935 "Veterinary and other services for pets"
cap label var CP09350 "Veterinary and other services for pets"
cap label var CP094 "Recreational and cultural services"
cap label var CP0941 "Recreational and sporting services"
cap label var CP09411 "Recreational and sporting services - Attendance"
cap label var CP09412 "Recreational and sporting services - Participation"
cap label var CP0942 "Cultural services"
cap label var CP09421 "Cinemas, theatres, concerts"
cap label var CP09421A "Cinema ticket (1 ticket)"
cap label var CP09422 "Museums, libraries, zoological gardens"
cap label var CP09423_09424 "Television and radio licence fees, subscriptions, hire of equipment and accessories for culture"
cap label var CP09423 "Television and radio licence fees, subscriptions"
cap label var CP09424 "Hire of equipment and accessories for culture"
cap label var CP09425 "Photographic services"
cap label var CP09425A "Digital photo print service (30 photos)"
cap label var CP09429 "Other cultural services"
cap label var CP0943 "Games of chance"
cap label var CP09430 "Games of chance"
cap label var CP095 "Newspapers, books and stationery"
cap label var CP0951 "Books"
cap label var CP09511 "Fiction books"
cap label var CP09511A "Novel, Top 5 (1 book)"
cap label var CP09512 "Educational text books"
cap label var CP09513 "Other non-fiction books"
cap label var CP09514 "Binding services and E-book downloads"
cap label var CP0952 "Newspapers and periodicals"
cap label var CP09521 "Newspapers"
cap label var CP09521A "Daily newspaper (1 piece)"
cap label var CP09522 "Magazines and periodicals"
cap label var CP09522A "Magazine, weekly, gossip (1 copy)"
cap label var CP0953_0954 "Miscellaneous printed matter; stationery and drawing materials"
cap label var CP0953 "Miscellaneous printed matter"
cap label var CP09530 "Miscellaneous printed matter"
cap label var CP0954 "Stationery and drawing materials"
cap label var CP09541 "Paper products"
cap label var CP09541A "Paper, DIN A4 (500 sheets)"
cap label var CP09541B "Pencil (1 piece)"
cap label var CP09549 "Other stationery and drawing materials"
cap label var CP096 "Package holidays"
cap label var CP0960 "Package holidays"
cap label var CP09601 "Package domestic holidays"
cap label var CP09602 "Package international holidays"
cap label var CP10 "Education"
cap label var CP101_105 "Pre-primary and primary, secondary, post-secondary non-tertiary, tertiary education, and education not definable by level"
cap label var CP101 "Pre-primary and primary education"
cap label var CP1010_1050 "Pre-primary and primary, secondary, post-secondary non-tertiary, tertiary education, and education not definable by level"
cap label var CP1010 "Pre-primary and primary education"
cap label var CP10101 "Pre-primary education"
cap label var CP10102 "Primary education"
cap label var CP102 "Secondary education"
cap label var CP1020 "Secondary education"
cap label var CP10200 "Secondary education"
cap label var CP103 "Post-secondary non-tertiary education"
cap label var CP1030 "Post-secondary non-tertiary education"
cap label var CP10300 "Post-secondary non-tertiary education"
cap label var CP104 "Tertiary education"
cap label var CP1040 "Tertiary education"
cap label var CP10400 "Tertiary education"
cap label var CP105 "Education not definable by level"
cap label var CP1050 "Education not definable by level"
cap label var CP10500 "Education not definable by level"
cap label var CP11 "Restaurants and hotels"
cap label var CP111 "Catering services"
cap label var CP1111 "Restaurants, cafés and the like"
cap label var CP11111 "Restaurants, cafés and dancing establishments"
cap label var CP11111A "Menu of the day (1 menu)"
cap label var CP11111B1 "Red house wine, 0.12 l (1 glass)"
cap label var CP11111B2 "Red house wine, 0.10 l (1 glass)"
cap label var CP11111C1 "Beer (lager), domestic, 0.2-0.35 l (1 glass)"
cap label var CP11111C2 "Beer (lager), domestic, 0.5 l (1 glass)"
cap label var CP11111D "Cup of coffee (1 cup)"
cap label var CP11112 "Fast food and take away food services"
cap label var CP1112 "Canteens"
cap label var CP11120 "Canteens"
cap label var CP112 "Accommodation services"
cap label var CP1120 "Accommodation services"
cap label var CP11201 "Hotels, motels, inns and similar accommodation services"
cap label var CP11201A "Hotel weekend (1 service)"
cap label var CP11202 "Holiday centres, camping sites, youth hostels and similar accommodation services"
cap label var CP11203 "Accommodation services of other establishments"
cap label var CP12 "Miscellaneous goods and services"
cap label var CP121 "Personal care"
cap label var CP1211 "Hairdressing salons and personal grooming establishments"
cap label var CP12111 "Hairdressing for men and children"
cap label var CP12111A "Men's scissors cuts, wet (1 service)"
cap label var CP12112 "Hairdressing for women"
cap label var CP12112A "Ladies - haircut (1 service)"
cap label var CP12113 "Personal grooming treatments"
cap label var CP1212_1213 "Electrical appliances for personal care; other appliances, articles and products for personal care"
cap label var CP1212 "Electrical appliances for personal care"
cap label var CP12121 "Electric appliances for personal care"
cap label var CP12121A "Electric razor (1 piece)"
cap label var CP12121B "Electric toothbrush (1 set)"
cap label var CP12122 "Repair of electric appliances for personal care"
cap label var CP1213 "Other appliances, articles and products for personal care"
cap label var CP12131 "Non-electrical appliances"
cap label var CP12131A "Cartridges for safety razor, men (5 cartridges)"
cap label var CP12132 "Articles for personal hygiene and wellness, esoteric products and beauty products"
cap label var CP12132A "Shampoo (400 ml)"
cap label var CP12132B "Tooth paste (100 ml)"
cap label var CP12132C "Toilet soap, liquid (200 ml)"
cap label var CP12132D "Shower gel (300 ml)"
cap label var CP12132E "Deodorant (50 ml)"
cap label var CP12132F "Tampons (10 pieces)"
cap label var CP12132G "Disposable nappies (50 pieces)"
cap label var CP12132H "Cotton buds (100 pieces)"
cap label var CP12132I "Manual toothbrush (1 piece)"
cap label var CP12132J "Toilet paper (10 rolls)"
cap label var CP122_127 "Prostitution; other services n.e.c."
cap label var CP122 "Prostitution"
cap label var CP1220 "Prostitution"
cap label var CP12200 "Prostitution"
cap label var CP123 "Personal effects n.e.c."
cap label var CP1231 "Jewellery, clocks and watches"
cap label var CP12311 "Jewellery"
cap label var CP12312 "Clocks and watches"
cap label var CP12313 "Repair of jewellery, clocks and watches"
cap label var CP1232 "Other personal effects"
cap label var CP12321 "Travel goods"
cap label var CP12322 "Articles for babies"
cap label var CP12323 "Repair of other personal effects"
cap label var CP12329 "Other personal effects n.e.c."
cap label var CP124 "Social protection"
cap label var CP1240 "Social protection"
cap label var CP12401 "Child care services"
cap label var CP12402 "Retirement homes for elderly persons and residences for disabled persons"
cap label var CP12403 "Services to maintain people in their private homes"
cap label var CP12404 "Counselling"
cap label var CP125 "Insurance"
cap label var CP1251 "Life insurance"
cap label var CP12510 "Life insurance"
cap label var CP1252 "Insurance connected with the dwelling"
cap label var CP12520 "Insurance connected with the dwelling"
cap label var CP1253 "Insurance connected with health"
cap label var CP12531 "Public insurance connected with health"
cap label var CP12532 "Private insurance connected with health"
cap label var CP1254 "Insurance connected with transport"
cap label var CP12541 "Motor vehicle insurance"
cap label var CP12542 "Travel insurance"
cap label var CP1255 "Other insurance"
cap label var CP12550 "Other insurance"
cap label var CP126 "Financial services n.e.c."
cap label var CP1261 "FISIM"
cap label var CP12610 "FISIM"
cap label var CP1262 "Other financial services n.e.c."
cap label var CP12621 "Charges by banks and post offices"
cap label var CP12622 "Fees and service charges of brokers, investment counsellors"
cap label var CP127 "Other services n.e.c."
cap label var CP1270 "Other services n.e.c."
cap label var CP12701 "Administrative fees"
cap label var CP12702 "Legal services and accountancy"
cap label var CP12703 "Funeral services"
cap label var CP12704 "Other fees and services"
cap label var GD "Goods (overall index excluding services)"
cap label var FOOD "Food including alcohol and tobacco"
cap label var FOOD_P "Processed food including alcohol and tobacco"
cap label var FOOD_P_X_ALC_TBC "Processed food excluding alcohol and tobacco"
cap label var FOOD_NP "Unprocessed food"
cap label var FOOD_S "Seasonal food"
cap label var IGD "Industrial goods"
cap label var IGD_NNRG "Non-energy industrial goods"
cap label var IGD_NNRG_D "Non-energy industrial goods, durables only"
cap label var IGD_NNRG_SD "Non-energy industrial goods, semi-durables only"
cap label var IGD_NNRG_ND "Non-energy industrial goods, non-durables only"
cap label var NRG "Energy"
cap label var ELC_GAS "Electricity, gas, solid fuels and heat energy"
cap label var FUEL "Liquid fuels and fuels and lubricants for personal transport equipment"
cap label var SERV_ESS "Essential services (excluding financial services)"
cap label var SERV "Services (overall index excluding goods)"
cap label var SERV_COM "Services related to communication"
cap label var SERV_HOUS "Services related to housing"
cap label var SERV_MSC "Services - miscellaneous"
cap label var SERV_REC "Services related to recreation, including repairs and personal care"
cap label var SERV_REC_X_HOA "Services related to recreation and personal care, excluding package holidays and accommodation"
cap label var SERV_REC_HOA "Services related to package holidays and accommodation"
cap label var SERV_TRA "Services related to transport"
cap label var NRG_FOOD_NP "Energy and unprocessed food"
cap label var NRG_FOOD_S "Energy and seasonal food"
cap label var EDUC_HLTH_SPR "Education, health and social protection"
cap label var FROOPP "Frequent out-of-pocket purchases"
cap label var TOT_X_FOOD_S "Overall index excluding seasonal food"
cap label var TOT_X_ALC_TBC "Overall index excluding alcohol and tobacco"
cap label var TOT_X_TBC "Overall index excluding tobacco"
cap label var TOT_X_NRG "Overall index excluding energy"
cap label var TOT_X_NRG_FOOD "Overall index excluding energy, food, alcohol and tobacco"
cap label var TOT_X_NRG_FOOD_NP "Overall index excluding energy and unprocessed food"
cap label var TOT_X_NRG_FOOD_S "Overall index excluding energy and seasonal food"
cap label var TOT_X_FUEL "Overall index excluding liquid fuels and lubricants for personal transport equipment"
cap label var TOT_X_HOUS "Overall index excluding housing, water, electricity, gas and other fuels"
cap label var TOT_X_EDUC_HLTH_SPR "Overall index excluding education, health and social protection"
cap label var TOT_X_FROOPP "Overall index excluding frequent out-of-pocket purchases"
cap label var AP "Administered prices"
cap label var AP_NRG "Administered prices, energy"
cap label var AP_NNRG "Administered prices, non-energy"
cap label var APF "Fully administered prices"
cap label var APM "Mainly administered prices"
cap label var TOT_X_AP "Overall index excluding administered prices"
cap label var TOT_X_APF "Overall index excluding fully administered prices"
cap label var TOT_X_APM "Overall index excluding mainly administered prices"
cap label var EQ_SOUND "Equipment for the reception, recording and reproduction of sound (including earphones)"
cap label var CI_TH_CO "Cinemas, theatres, concerts (excluding services of musicians, clowns, performers for private entertainments)"
cap label var PERF_PHOT "Services of musicians, clowns, performers for private entertainers, and photographers"
