cap label var TOT_HF "All financing schemes"
cap label var HF1 "Government schemes and compulsory contributory health care financing schemes"
cap label var HF11 "Government schemes"
cap label var HF12_13 "Compulsory contributory health insurance schemes and compulsory medical saving accounts (CMSA)"
cap label var HF121 "Social health insurance schemes"
cap label var HF122 "Compulsory private insurance scheme"
cap label var HF13 "Compulsory medical savings accounts (CMSA)"
cap label var HF2 "Voluntary health care payment schemes"
cap label var HF21 "Voluntary health insurance schemes"
cap label var HF22 "NPISH financing schemes"
cap label var HF23 "Enterprise financing schemes"
cap label var HF3 "Household out-of-pocket payment"
cap label var HF31 "Out-of-pocket excluding cost-sharing"
cap label var HF32 "Cost sharing with third-party payers"
cap label var HF4 "Rest of the world financing schemes (non-resident)"
cap label var HF41 "Compulsory schemes (non-resident)"
cap label var HF42 "Voluntary schemes (non-resident)"
cap label var HF_UNK "Financing schemes unknown"
cap label var HFRI1 "Institutional units managing financing schemes"
cap label var HFRI11 "Government"
cap label var HFRI12_14 "Corporations, households and NPISH"
cap label var HFRI15 "Rest of the world"
cap label var HFRI2 "Government schemes and compulsory contributory health insurance schemes together with cost-sharing (HF.1 + HF.3.2.1)"
cap label var HFRI3 "Voluntary health insurance schemes together with cost-sharing (HF.2.1 + HF.3.2.2)"
