cap label var BE_EBAW "ANTWERPEN/DEURNE airport"
cap label var BE_EBBR "BRUSSELS airport"
cap label var BE_EBCI "CHARLEROI/BRUSSELS SOUTH airport"
cap label var BE_EBLG "LIEGE airport"
cap label var BE_EBOS "OOSTENDE/BRUGGE airport"
cap label var BE_OTH "Other airport - BELGIUM"
cap label var BG_LBBG "BURGAS airport"
cap label var BG_LBPD "PLOVDIV airport"
cap label var BG_LBSF "SOFIA airport"
cap label var BG_LBWN "VARNA airport"
cap label var BG_OTH "Other airport - BULGARIA"
cap label var CZ_LKKV "KARLOVY VARY airport"
cap label var CZ_LKMT "OSTRAVA/MOSNOV airport"
cap label var CZ_LKPD "PARDUBICE airport"
cap label var CZ_LKPR "PRAHA/RUZYNE airport"
cap label var CZ_LKTB "BRNO/TURANY airport"
cap label var CZ_OTH "Other airport - CZECHIA"
cap label var DK_EKAE "AERO airport"
cap label var DK_EKAH "AARHUS airport"
cap label var DK_EKBI "BILLUND airport"
cap label var DK_EKCH "KOBENHAVN/KASTRUP airport"
cap label var DK_EKEB "ESBJERG airport"
cap label var DK_EKKA "KARUP airport"
cap label var DK_EKKM "ARHUS/KIRSTINESMINDE airport"
cap label var DK_EKOD "ODENSE airport"
cap label var DK_EKRK "KOBENHAVN/ROSKILDE airport"
cap label var DK_EKRN "BORNHOLM/RONNE airport"
cap label var DK_EKSB "SONDERBORG airport"
cap label var DK_EKSP "VOJENS/SKRYDSTRUP airport"
cap label var DK_EKSV "SKIVE airport"
cap label var DK_EKTS "THISTED airport"
cap label var DK_EKVG "VAGAR airport"
cap label var DK_EKVH "VESTHIMMERLAND airport"
cap label var DK_EKVJ "STAUNING airport"
cap label var DK_EKVL "VAERSLOSE airport"
cap label var DK_EKYT "AALBORG airport"
cap label var DK_EK99 "Unknown airport - DENMARK"
cap label var DK_OTH "Other airport - DENMARK"
cap label var DE_EDAC "LEIPZIG-ALTENBURG airport"
cap label var DE_EDAH "HERINGSDORF airport"
cap label var DE_EDAM "MERSEBURG airport"
cap label var DE_EDBC "MAGDEBURG/COCHSTEDT airport"
cap label var DE_EDBF "RUPPINER LAND airport"
cap label var DE_EDBH "BARTH airport"
cap label var DE_EDBM "MAGDEBURG/CITY airport"
cap label var DE_EDCG "RUEGEN airport"
cap label var DE_EDDB "BERLIN-BRANDENBURG airport"
cap label var DE_EDDC "DRESDEN airport"
cap label var DE_EDDE "ERFURT-WEIMAR airport"
cap label var DE_EDDF "FRANKFURT/MAIN airport"
cap label var DE_EDDG "MUENSTER/OSNABRUECK airport"
cap label var DE_EDDH "HAMBURG airport"
cap label var DE_EDDI "BERLIN/TEMPELHOF airport"
cap label var DE_EDDK "KOELN/BONN airport"
cap label var DE_EDDL "DUESSELDORF airport"
cap label var DE_EDDM "MUENCHEN airport"
cap label var DE_EDDN "NUERNBERG airport"
cap label var DE_EDDP "LEIPZIG/HALLE airport"
cap label var DE_EDDR "SAARBRUECKEN airport"
cap label var DE_EDDS "STUTTGART airport"
cap label var DE_EDDT "BERLIN-TEGEL airport"
cap label var DE_EDDV "HANNOVER airport"
cap label var DE_EDDW "BREMEN airport"
cap label var DE_EDFE "FRANKFURT-EGELSBACH airport"
cap label var DE_EDFH "FRANKFURT-HAHN airport"
cap label var DE_EDFM "MANNHEIM CITY airport"
cap label var DE_EDFV "WORMS airport"
cap label var DE_EDFZ "MAINZ/FINTHEN airport"
cap label var DE_EDGS "SIEGERLAND airport"
cap label var DE_EDHE "UETERSEN/HEIST airport"
cap label var DE_EDHI "HAMBURG-FINKENWERDER airport"
cap label var DE_EDHK "KIEL-HOLTENAU airport"
cap label var DE_EDHL "LUEBECK-BLANKENSEE airport"
cap label var DE_EDJA "MEMMINGEN airport"
cap label var DE_EDKA "AACHEN-MERZBRUECK airport"
cap label var DE_EDKB "BONN-HANGELAR airport"
cap label var DE_EDLE "ESSEN/MUELHEIM airport"
cap label var DE_EDLF "GREFRATH/NIERSHORST airport"
cap label var DE_EDLN "MOENCHENGLADBACH airport"
cap label var DE_EDLP "PADERBORN/LIPPSTADT airport"
cap label var DE_EDLV "NIEDERRHEIN airport"
cap label var DE_EDLW "DORTMUND airport"
cap label var DE_EDMA "AUGSBURG airport"
cap label var DE_EDML "LANDSHUT airport"
cap label var DE_EDMO "OBERPFAFFENHOFEN airport"
cap label var DE_EDMS "STRAUBING airport"
cap label var DE_EDNL "LEUTKIRCH-UNTERZEIL airport"
cap label var DE_EDNY "FRIEDRICHSHAFEN airport"
cap label var DE_EDOG "TORGAU-BEILRODE airport"
cap label var DE_EDOR "STOELLN/RHINOW airport"
cap label var DE_EDQD "BAYREUTH airport"
cap label var DE_EDQM "HOF-PLAUEN airport"
cap label var DE_EDRK "KOBLENZ-WINNINGEN airport"
cap label var DE_EDRT "TRIER-FOEHREN airport"
cap label var DE_EDRZ "ZWEIBRUECKEN airport"
cap label var DE_EDSB "KARLSRUHE/BADEN-BADEN airport"
cap label var DE_EDTB "BADEN-OOS airport"
cap label var DE_EDTD "DONAUESCHINGEN-VILLINGEN airport"
cap label var DE_EDTF "FREIBURG I.BR. airport"
cap label var DE_EDTK "SINSHEIM airport"
cap label var DE_EDTO "OFFENBURG airport"
cap label var DE_EDTZ "KONSTANZ airport"
cap label var DE_EDVE "BRAUNSCHWEIG-WOLFSBURG airport"
cap label var DE_EDVK "KASSEL-CALDEN airport"
cap label var DE_EDVM "HILDESHEIM airport"
cap label var DE_EDVV "HANNOVER UIR airport"
cap label var DE_EDWB "BREMERHAVEN airport"
cap label var DE_EDWD "LEMWERDER airport"
cap label var DE_EDWE "EMDEN airport"
cap label var DE_EDWG "WANGEROOGE airport"
cap label var DE_EDWI "WILHELMSHAVEN JADEWESER airport"
cap label var DE_EDWJ "JUIST airport"
cap label var DE_EDWL "LANGEOOG airport"
cap label var DE_EDWR "BORKUM airport"
cap label var DE_EDWS "NORDEN-NORDDEICH airport"
cap label var DE_EDWY "NORDERNEY airport"
cap label var DE_EDXB "HEIDE-BUESUM airport"
cap label var DE_EDXF "FLENSBURG-SCHAEFERHAUS airport"
cap label var DE_EDXH "HELGOLAND-DUENE airport"
cap label var DE_EDXO "ST. PETER-ORDING airport"
cap label var DE_EDXP "HARLE airport"
cap label var DE_EDXW "SYLT airport"
cap label var DE_EDXY "WYK AUF FOEHR airport"
cap label var DE_ED00 "Other airport - GERMANY"
cap label var DE_ED99 "Unknown airport - GERMANY"
cap label var DE_ETIE "HEIDELBERG HEL airport"
cap label var DE_ETMN "NORDHOLZ airport"
cap label var DE_ETNL "LAAGE airport"
cap label var DE_ETNU "NEUBRANDENBURG airport"
cap label var DE_ETSI "INGOLSTADT/MANCHING airport"
cap label var DE_ETUO "GUETERSLOH airport"
cap label var DE_OTH "Other airport - GERMANY"
cap label var EE_EECL "TALLINN/CITY HALL airport"
cap label var EE_EEKA "KARDLA airport"
cap label var EE_EEKE "KURESSAARE airport"
cap label var EE_EEPU "PARNU airport"
cap label var EE_EETN "LENNART MERI TALLINN airport"
cap label var EE_EETU "TARTU airport"
cap label var EE_OTH "Other airport - ESTONIA"
cap label var IE_EICA "CONNEMARA airport"
cap label var IE_EICK "CORK airport"
cap label var IE_EICM "GALWAY airport"
cap label var IE_EIDL "DONEGAL airport"
cap label var IE_EIDW "DUBLIN airport"
cap label var IE_EIIM "INISHMORE airport"
cap label var IE_EIKN "IRELAND WEST airport"
cap label var IE_EIKY "KERRY airport"
cap label var IE_EINN "SHANNON airport"
cap label var IE_EISG "SLIGO airport"
cap label var IE_EIWF "WATERFORD airport"
cap label var IE_OTH "Other airport - IRELAND"
cap label var EL_LG03 "THIRA airport"
cap label var EL_LG04 "NAXOS airport"
cap label var EL_LGAL "ALEXANDROUPOLIS/DIMOKRITOS airport"
cap label var EL_LGAT "ATHINAI airport"
cap label var EL_LGAV "ATHINAI/ELEFTHERIOS VENIZELOS airport"
cap label var EL_LGBL "ALMIROS/NEA ANCHIALOS airport"
cap label var EL_LGEL "ELEFSIS airport"
cap label var EL_LGHI "CHIOS/OMIROS airport"
cap label var EL_LGIK "IKARIA/IKAROS airport"
cap label var EL_LGIO "IOANNINA/KING PYRROS airport"
cap label var EL_LGIR "IRAKLION/NIKOS KAZANTZAKIS airport"
cap label var EL_LGKA "KASTORIA/ARISTOTELIS airport"
cap label var EL_LGKC "KITHIRA/ALEXANDROS ARISTOTELOUS ONASSIS airport"
cap label var EL_LGKF "KEFALLINIA/ANNA POLLATOU airport"
cap label var EL_LGKJ "KASTELORIZO airport"
cap label var EL_LGKL "KALAMATA airport"
cap label var EL_LGKO "KOS/IPPOKRATIS airport"
cap label var EL_LGKP "KARPATHOS airport"
cap label var EL_LGKR "KERKIRA/IOANNIS KAPODISTRIAS airport"
cap label var EL_LGKS "KASSOS airport"
cap label var EL_LGKV "KAVALA/MEGAS ALEXANDROS airport"
cap label var EL_LGKY "KALYMNOS airport"
cap label var EL_LGKZ "KOZANI/FILIPPOS airport"
cap label var EL_LGLE "LEROS airport"
cap label var EL_LGLM "LIMNOS/IFAISTOS airport"
cap label var EL_LGLR "LARISSA airport"
cap label var EL_LGMK "MIKONOS airport"
cap label var EL_LGML "MILOS airport"
cap label var EL_LGMT "MITILINI/ODYSSEAS ELYTIS airport"
cap label var EL_LGNX "NAXOS airport"
cap label var EL_LGPA "PAROS airport"
cap label var EL_LGPL "ASTYPALAIA airport"
cap label var EL_LGPZ "PREVEZA/AKTION airport"
cap label var EL_LGRD "RODOS/MARITSA airport"
cap label var EL_LGRP "RODOS/DIAGORAS airport"
cap label var EL_LGRX "ARAXOS airport"
cap label var EL_LGSA "CHANIA/IOANNIS DASKALOGIANNIS airport"
cap label var EL_LGSK "SKIATHOS/ALEXANDROS PAPADIAMANDIS airport"
cap label var EL_LGSM "SAMOS/ARISTARCHOS OF SAMOS airport"
cap label var EL_LGSO "SYROS/DIMITRIOS VIKELAS airport"
cap label var EL_LGSR "SANTORINI airport"
cap label var EL_LGST "SITIA/VITSENTZOS KORNAROS airport"
cap label var EL_LGSY "SKIROS airport"
cap label var EL_LGTS "THESSALONIKI/MAKEDONIA airport"
cap label var EL_LGVO "VOLOS airport"
cap label var EL_LGZA "ZAKINTHOS/DIONISIOS SOLOMOS airport"
cap label var EL_LG99 "Unknown airport - GREECE"
cap label var EL_OTH "Other airport - GREECE"
cap label var ES_GCFV "FUERTEVENTURA airport"
cap label var ES_GCGM "LA GOMERA airport"
cap label var ES_GCHI "HIERRO airport"
cap label var ES_GCLA "LA PALMA airport"
cap label var ES_GCLP "GRAN CANARIA airport"
cap label var ES_GCRR "LANZAROTE airport"
cap label var ES_GCTS "TENERIFE SUR/REINA SOFIA airport"
cap label var ES_GCXO "TENERIFE NORTE airport"
cap label var ES_GECE "CEUTA (HEL CIVIL) airport"
cap label var ES_GECT "CEUTA airport"
cap label var ES_GEML "MELILLA airport"
cap label var ES_LE06 "OVIEDO airport"
cap label var ES_LEAB "ALBACETE airport"
cap label var ES_LEAG "ALGECIRAS (CADIZ) airport"
cap label var ES_LEAL "ALICANTE airport"
cap label var ES_LEAM "ALMERIA airport"
cap label var ES_LEAP "AMPURIABRAVA (GIRONA) airport"
cap label var ES_LEAS "ASTURIAS airport"
cap label var ES_LEAT "ASTORGA (LEON) airport"
cap label var ES_LEBA "CORDOBA airport"
cap label var ES_LEBB "BILBAO airport"
cap label var ES_LEBG "BURGOS airport"
cap label var ES_LEBL "BARCELONA/EL PRAT airport"
cap label var ES_LEBZ "BADAJOZ airport"
cap label var ES_LECN "CASTELLON (CASTELLON) airport"
cap label var ES_LECO "A CORUNA airport"
cap label var ES_LECT "EL CASTANO (CIUDAD REAL) airport"
cap label var ES_LECU "MADRID/CUATRO VIENTOS airport"
cap label var ES_LECV "MADRID-COLMENAR VIEJO airport"
cap label var ES_LEFA "ROTA airport"
cap label var ES_LEGC "ALTAREJOS-GUADALCANAL (SEVILLA) airport"
cap label var ES_LEGE "GIRONA airport"
cap label var ES_LEGR "GRANADA/FEDERICO GARCIA LORCA GRANADA-JAEN airport"
cap label var ES_LEHC "HUESCA/PIRINEOS airport"
cap label var ES_LEIB "IBIZA airport"
cap label var ES_LEJR "JEREZ airport"
cap label var ES_LEJU "LA JULIANA (SEVILLA) airport"
cap label var ES_LELC "MURCIA/SAN JAVIER airport"
cap label var ES_LELL "SABADELL airport"
cap label var ES_LELN "LEON airport"
cap label var ES_LELO "LOGRONO/AGONCILLO airport"
cap label var ES_LELU "MILUCE (NAVARRA) airport"
cap label var ES_LEMD "ADOLFO SUAREZ MADRID-BARAJAS airport"
cap label var ES_LEMG "MALAGA/COSTA DEL SOL airport"
cap label var ES_LEMH "MENORCA airport"
cap label var ES_LEMI "MURCIA/AEROPUERTO DE LA REGION DE MURCIA AIRPORT"
cap label var ES_LEMR "LA MORGAL (ASTURIAS) airport"
cap label var ES_LEMU "MUCHAMIEL (ALICANTE) airport"
cap label var ES_LEOC "OCANA (TOLEDO) airport"
cap label var ES_LEPA "PALMA DE MALLORCA airport"
cap label var ES_LEPI "CASAS DE LOS PINOS (CUENCA) airport"
cap label var ES_LEPP "PAMPLONA airport"
cap label var ES_LERJ "LOGRONO airport"
cap label var ES_LERM "ROBLEDILLO DE MOHERNANDO (GUADALAJARA) airport"
cap label var ES_LERS "REUS airport"
cap label var ES_LESA "SALAMANCA airport"
cap label var ES_LESB "MALLORCA/SON BONET airport"
cap label var ES_LESJ "PALMA/SON SAN JUAN airport"
cap label var ES_LESO "SAN SEBASTIAN airport"
cap label var ES_LEST "SANTIAGO airport"
cap label var ES_LETO "MADRID/TORREJON airport"
cap label var ES_LEVC "VALENCIA airport"
cap label var ES_LEVD "VALLADOLID airport"
cap label var ES_LEVI "VILLARALBO (ZAMORA) airport"
cap label var ES_LEVS "CUATRO VIENTOS airport"
cap label var ES_LEVT "VITORIA airport"
cap label var ES_LEVX "VIGO airport"
cap label var ES_LEXJ "SEVE BALLESTEROS-SANTANDER airport"
cap label var ES_LEZG "ZARAGOZA airport"
cap label var ES_LEZL "SEVILLA airport"
cap label var ES_LE00 "Other airport - SPAIN"
cap label var ES_OTH "Other airport - SPAIN"
cap label var FR_FMCZ "DZAOUDZI airport"
cap label var FR_FMEE "LA REUNION-ROLAND GARROS airport"
cap label var FR_FMEP "SAINT PIERRE PIERREFONDS airport"
cap label var FR_LFAB "DIEPPE-SAINT-AUBIN airport"
cap label var FR_LFAC "CALAIS-DUNKERQUE airport"
cap label var FR_LFAQ "ALBERT-BRAY airport"
cap label var FR_LFAT "LE TOUQUET-COTE D'OPALE airport"
cap label var FR_LFAV "VALENCIENNES-DENAIN airport"
cap label var FR_LFAY "AMIENS-GLISY airport"
cap label var FR_LFBA "AGEN-LA GARENNE airport"
cap label var FR_LFBD "BORDEAUX-MERIGNAC airport"
cap label var FR_LFBE "BERGERAC-ROUMANIERE airport"
cap label var FR_LFBH "LA ROCHELLE-ILE DE RE airport"
cap label var FR_LFBI "POITIERS-BIARD airport"
cap label var FR_LFBK "MONTLUCON-GUERET airport"
cap label var FR_LFBL "LIMOGES-BELLEGARDE airport"
cap label var FR_LFBN "NIORT-MARAIS POITEVIN airport"
cap label var FR_LFBO "TOULOUSE/BLAGNAC airport"
cap label var FR_LFBP "PAU-PYRENEES airport"
cap label var FR_LFBS "BISCARROSSE-PARENTIS airport"
cap label var FR_LFBT "TARBES LOURDES PYRENEES airport"
cap label var FR_LFBU "ANGOULEME-BRIE-CHAMPNIERS airport"
cap label var FR_LFBV "BRIVE/LA ROCHE airport"
cap label var FR_LFBX "PERIGEUX-BASSILLAC airport"
cap label var FR_LFBZ "BIARRITZ-PAYS BASQUE airport"
cap label var FR_LFCC "CAHORS-LALBENQUE airport"
cap label var FR_LFCH "ARCACHON-LA TESTE DE BUCH airport"
cap label var FR_LFCI "ALBI-LE SEQUESTRE airport"
cap label var FR_LFCK "CASTRES MAZAMET airport"
cap label var FR_LFCR "RODEZ-AVEYRON airport"
cap label var FR_LFCY "ROYAN-MEDIS airport"
cap label var FR_LFDN "ROCHEFORT-CHARENTE-MARITIME airport"
cap label var FR_LFEA "BELLE-ILE airport"
cap label var FR_LFEC "OUESSANT airport"
cap label var FR_LFEY "ILE D YEU airport"
cap label var FR_LFFI "ANCENIS airport"
cap label var FR_LFGA "COLMAR HOUSSEN airport"
cap label var FR_LFGJ "DOLE-TAVAUX airport"
cap label var FR_LFHB "MOULINS/AVERMES airport"
cap label var FR_LFHO "AUBENAS-ARDECHE MERIDIONALE airport"
cap label var FR_LFHP "LE PUY-LOUDES airport"
cap label var FR_LFJL "METZ NANCY-LORRAINE airport"
cap label var FR_LFJR "ANGERS MARCE airport"
cap label var FR_LFKB "BASTIA-PORETTA airport"
cap label var FR_LFKC "CALVI-SAINTE-CATHERINE airport"
cap label var FR_LFKF "FIGARI-SUD-CORSE airport"
cap label var FR_LFKJ "AJACCIO-NAPOLEON-BONAPARTE airport"
cap label var FR_LFLA "AUXERRE-BRANCHES airport"
cap label var FR_LFLB "CHAMBERY-AIX-LES-BAINS airport"
cap label var FR_LFLC "CLERMONT-FERRAND-AUVERGNE airport"
cap label var FR_LFLD "BOURGES airport"
cap label var FR_LFLG "GRENOBLE-LE VERSOUD airport"
cap label var FR_LFLH "CHALON-CHAMPFORGEUIL airport"
cap label var FR_LFLJ "COURCHEVEL airport"
cap label var FR_LFLL "LYON SAINT-EXUPERY airport"
cap label var FR_LFLM "MACON CHARNAY airport"
cap label var FR_LFLN "SAINT-YAN airport"
cap label var FR_LFLO "ROANNE airport"
cap label var FR_LFLP "ANNECY-MEYTHET airport"
cap label var FR_LFLS "GRENOBLE-ISERE airport"
cap label var FR_LFLU "VALENCE-CHABEUIL airport"
cap label var FR_LFLV "VICHY-CHARMEIL airport"
cap label var FR_LFLW "AURILLAC airport"
cap label var FR_LFLX "CHATEAUROUX-DEOLS airport"
cap label var FR_LFLY "LYON-BRON airport"
cap label var FR_LFMD "CANNES-MANDELIEU airport"
cap label var FR_LFMH "SAINT-ETIENNE-LOIRE airport"
cap label var FR_LFMK "CARCASSONNE-SALVAZA airport"
cap label var FR_LFML "MARSEILLE-PROVENCE airport"
cap label var FR_LFMN "NICE-COTE D AZUR airport"
cap label var FR_LFMP "PERPIGNAN RIVESALTES airport"
cap label var FR_LFMQ "LE CASTELLET airport"
cap label var FR_LFMT "MONTPELLIER MEDITERRANEE airport"
cap label var FR_LFMU "BEZIERS-VIAS airport"
cap label var FR_LFMV "AVIGNON-CAUMONT airport"
cap label var FR_LFNA "GAP-TALLARD airport"
cap label var FR_LFOB "BEAUVAIS-TILLE airport"
cap label var FR_LFOD "SAUMUR SAINT FLORENT airport"
cap label var FR_LFOH "LE HAVRE-OCTEVILLE airport"
cap label var FR_LFOK "CHALONS-VATRY airport"
cap label var FR_LFOP "ROUEN-VALLEE DE SEINE airport"
cap label var FR_LFOQ "BLOIS-LE BREUIL airport"
cap label var FR_LFOT "TOURS VAL DE LOIRE airport"
cap label var FR_LFOU "CHOLET-LE PONTREAU airport"
cap label var FR_LFOV "LAVAL-ENTRAMMES airport"
cap label var FR_LFOZ "ORLEANS SAINT DENIS DE L HOTEL airport"
cap label var FR_LFPB "PARIS-LE BOURGET airport"
cap label var FR_LFPG "PARIS-CHARLES DE GAULLE airport"
cap label var FR_LFPM "MELUN-VILLAROCHE airport"
cap label var FR_LFPO "PARIS-ORLY airport"
cap label var FR_LFPT "PONTOISE-CORMEILLES-EN-VEXIN airport"
cap label var FR_LFQA "REIMS-PRUNAY airport"
cap label var FR_LFQB "TROYES-BARBEREY airport"
cap label var FR_LFQD "ARRAS-ROCLINCOURT airport"
cap label var FR_LFQG "NEVERS-FOURCHAMBAULT airport"
cap label var FR_LFQJ "MAUBEUGE-ELESMES airport"
cap label var FR_LFQM "BESANCON-LA VEZE airport"
cap label var FR_LFQQ "LILLE-LESQUIN airport"
cap label var FR_LFQT "MERVILLE-CALONNE airport"
cap label var FR_LFQV "CHARLEVILLE-MEZIERES airport"
cap label var FR_LFRA "ANGERS/AVRILLE airport"
cap label var FR_LFRB "BREST-BRETAGNE airport"
cap label var FR_LFRC "CHERBOURG-MAUPERTUS airport"
cap label var FR_LFRD "DINARD PLEURTUIT SAINT MALO airport"
cap label var FR_LFRE "LA BAULE-ESCOUBLAC airport"
cap label var FR_LFRG "DEAUVILLE-NORMANDIE airport"
cap label var FR_LFRH "LORIENT-LANN-BIHOUE airport"
cap label var FR_LFRI "LA ROCHE SUR YON LES AJONCS airport"
cap label var FR_LFRK "CAEN-CARPIQUET airport"
cap label var FR_LFRM "LE MANS-ARNAGE airport"
cap label var FR_LFRN "RENNES SAINT JACQUES airport"
cap label var FR_LFRO "LANNION airport"
cap label var FR_LFRQ "QUIMPER-PLUGUFFAN airport"
cap label var FR_LFRS "NANTES ATLANTIQUE airport"
cap label var FR_LFRT "SAINT BRIEUC ARMOR airport"
cap label var FR_LFRU "MORLAIX PLOUJEAN airport"
cap label var FR_LFRV "VANNES-MEUCON airport"
cap label var FR_LFRZ "SAINT-NAZAIRE-MONTOIR airport"
cap label var FR_LFSB "BALE-MULHOUSE airport"
cap label var FR_LFSD "DIJON-LONGVIC airport"
cap label var FR_LFSG "EPINAL-MIRECOURT airport"
cap label var FR_LFSL "BRIVE SOUILLAC airport"
cap label var FR_LFSM "MONTBELIARD-COURCELLES airport"
cap label var FR_LFSN "NANCY-ESSEY airport"
cap label var FR_LFSR "REIMS/CHAMPAGNE airport"
cap label var FR_LFST "STRASBOURG-ENTZHEIM airport"
cap label var FR_LFTG "CANNES/PALM BEACH airport"
cap label var FR_LFTH "HYERES-LE PALYVESTRE airport"
cap label var FR_LFTL "CANNES-QUAI DU LARGE airport"
cap label var FR_LFTW "NIMES-GARONS airport"
cap label var FR_LFTZ "LA MOLE airport"
cap label var FR_LFVM "MIQUELON airport"
cap label var FR_LFVP "SAINT PIERRE airport"
cap label var FR_LFXR "GROSTENQUIN airport"
cap label var FR_LF35 "DIVERS STATION airport"
cap label var FR_LF90 "PARIS airport system"
cap label var FR_LF95 "NANCY airport system"
cap label var FR_LF96 "STRASBOURG airport System"
cap label var FR_LF99 "Unknown airport - FRANCE"
cap label var FR_SOCA "CAYENNE-FELIX-EBOUE airport"
cap label var FR_SOOA "MARIPASOULA airport"
cap label var FR_SOOG "SAINT-GEORGES-DE-L OYAPOCK airport"
cap label var FR_SOOM "SAINT-LAURENT-DU-MARONI airport"
cap label var FR_SOOS "SAUL airport"
cap label var FR_SO99 "Unknown airport - GUYANE/FRANCE"
cap label var FR_TFFB "BASSETERRE/FRENCH ANTILLES airport"
cap label var FR_TFFC "SAINT FRANÇOIS/FRENCH ANTILLES airport"
cap label var FR_TFFF "AIME CESAIRE/MARTINIQUE airport"
cap label var FR_TFFG "SAINT MARTIN, GRAND CASE, GUADELOUPE airport"
cap label var FR_TFFJ "SAINT BARTHELEMY/FRENCH ANTILLES airport"
cap label var FR_TFFM "MARIE GALANTE airport"
cap label var FR_TFFR "POINTE-A-PITRE/LE RAIZET/GUADELOUPE airport"
cap label var FR_TFFS "LES SAINTES/TERRE DE HAUT/FRENCH ANTILLES airport"
cap label var FR_OTH "Other airport - FRANCE"
cap label var HR_LDDD "ZAGREB (AFTN) airport"
cap label var HR_LDDU "DUBROVNIK/CILIPI airport"
cap label var HR_LDLO "LOSINJ/LOSINJ I. airport"
cap label var HR_LDOS "OSIJEK/KLISA airport"
cap label var HR_LDPL "PULA airport"
cap label var HR_LDRI "RIJEKA/KRK airport"
cap label var HR_LDSB "BRAC airport"
cap label var HR_LDSP "SPLIT/KASTELA airport"
cap label var HR_LDZA "ZAGREB/FRANJO TUDJMAN airport"
cap label var HR_LDZD "ZADAR/ZEMUNIK airport"
cap label var HR_OTH "Other airport - CROATIA"
cap label var IT_LIBC "CROTONE airport"
cap label var IT_LIBD "BARI/PALESE airport"
cap label var IT_LIBF "FOGGIA/GINO LISA airport"
cap label var IT_LIBG "TARANTO/GROTTAGLIE airport"
cap label var IT_LIBP "PESCARA airport"
cap label var IT_LIBR "BRINDISI/CASALE airport"
cap label var IT_LICA "LAMEZIA TERME airport"
cap label var IT_LICB "COMISO airport"
cap label var IT_LICC "CATANIA/FONTANAROSSA airport"
cap label var IT_LICD "LAMPEDUSA airport"
cap label var IT_LICG "PANTELLERIA airport"
cap label var IT_LICJ "PALERMO/PUNTA RAISI airport"
cap label var IT_LICR "REGGIO CALABRIA airport"
cap label var IT_LICT "TRAPANI/BIRGI airport"
cap label var IT_LIEA "ALGHERO/FERTILIA airport"
cap label var IT_LIEE "CAGLIARI/ELMAS airport"
cap label var IT_LIEO "OLBIA/COSTA SMERALDA airport"
cap label var IT_LIET "TORTOLI/ARBATAX airport"
cap label var IT_LIGC "PANTELLERIA airport"
cap label var IT_LIMC "MILANO/MALPENSA airport"
cap label var IT_LIME "BERGAMO/ORIO AL SERIO airport"
cap label var IT_LIMF "TORINO/CASELLE airport"
cap label var IT_LIMG "ALBENGA airport"
cap label var IT_LIMJ "GENOVA/SESTRI airport"
cap label var IT_LIML "MILANO/LINATE airport"
cap label var IT_LIMP "PARMA airport"
cap label var IT_LIMW "AOSTA airport"
cap label var IT_LIMZ "CUNEO/LEVALDIGI airport"
cap label var IT_LIPB "BOLZANO airport"
cap label var IT_LIPE "BOLOGNA/BORGO PANIGALE airport"
cap label var IT_LIPH "TREVISO/S.ANGELO airport"
cap label var IT_LIPK "FORLI airport"
cap label var IT_LIPN "VERONA/BOSCOMANTICO airport"
cap label var IT_LIPO "BRESCIA/MONTICHIARI airport"
cap label var IT_LIPQ "TRIESTE/RONCHI DEI LEGIONARI airport"
cap label var IT_LIPR "RIMINI/MIRAMARE airport"
cap label var IT_LIPX "VERONA/VILLAFRANCA airport"
cap label var IT_LIPY "ANCONA/FALCONARA airport"
cap label var IT_LIPZ "VENEZIA/TESSERA airport"
cap label var IT_LIRA "ROMA/CIAMPINO airport"
cap label var IT_LIRF "ROMA/FIUMICINO airport"
cap label var IT_LIRJ "MARINA DI CAMPO airport"
cap label var IT_LIRN "NAPOLI/CAPODICHINO airport"
cap label var IT_LIRP "PISA/S. GIUSTO airport"
cap label var IT_LIRQ "FIRENZE/PERETOLA airport"
cap label var IT_LIRS "GROSSETO airport"
cap label var IT_LIRZ "PERUGIA/S. FRANCESCO airport"
cap label var IT_LIVT "TRIESTE airport"
cap label var IT_LI99 "Unknown airport - ITALY"
cap label var IT_OTH "Other airport - ITALY"
cap label var CY_LCLK "LARNAKA/INTL airport"
cap label var CY_LCPH "PAFOS/INTL airport"
cap label var CY_OTH "Other airport - CYPRUS"
cap label var LV_EVLA "LIEPAJA airport"
cap label var LV_EVRA "RIGA airport"
cap label var LV_OTH "Other airport - LATVIA"
cap label var LT_EYKA "KAUNAS INTL airport"
cap label var LT_EYPA "PALANGA/INTERNATIONAL airport"
cap label var LT_EYSA "SIAULIAI/INTERNATIONAL airport"
cap label var LT_EYVI "VILNIUS/INTERNATIONAL airport"
cap label var LT_OTH "Other airport - LITHUANIA"
cap label var LU_ELLX "LUXEMBOURG airport"
cap label var LU_OTH "Other airport - LUXEMBOURG"
cap label var HU_LHBP "BUDAPEST/LISZT FERENC INTERNATIONAL airport"
cap label var HU_LHDC "DEBRECEN airport"
cap label var HU_LHPR "GYOR/PER airport"
cap label var HU_LHSM "HEVIZ/BALATON airport"
cap label var HU_OTH "Other airport - HUNGARY"
cap label var MT_LMML "LUQA airport"
cap label var MT_OTH "Other airport - MALTA"
cap label var NL_EHAM "AMSTERDAM/SCHIPHOL airport"
cap label var NL_EHBK "MAASTRICHT/AACHEN airport"
cap label var NL_EHEH "EINDHOVEN airport"
cap label var NL_EHGG "GRONINGEN/EELDE airport"
cap label var NL_EHRD "ROTTERDAM airport"
cap label var NL_OTH "Other airport - NETHERLANDS"
cap label var AT_LOWG "GRAZ airport"
cap label var AT_LOWI "INNSBRUCK airport"
cap label var AT_LOWK "KLAGENFURT airport"
cap label var AT_LOWL "LINZ airport"
cap label var AT_LOWS "SALZBURG airport"
cap label var AT_LOWW "WIEN-SCHWECHAT airport"
cap label var AT_OTH "Other airport - AUSTRIA"
cap label var PL_EPBD "BYDGOSZCZ/BIEDASZKOWO airport"
cap label var PL_EPBY "BYDGOSZCZ/SZWEDEROWO airport"
cap label var PL_EPGD "GDANSK IM LECHA WALESY airport"
cap label var PL_EPKK "KRAKOW/BALICE airport"
cap label var PL_EPKT "KATOWICE/PYRZOWICE airport"
cap label var PL_EPLB "LUBLIN airport"
cap label var PL_EPLL "LODZ/LUBLINEK airport"
cap label var PL_EPMO "WARSZAWA/MODLIN airport"
cap label var PL_EPPO "POZNAN/LAWICA airport"
cap label var PL_EPRZ "RZESZOW/JASIONKA airport"
cap label var PL_EPSC "SZCZECIN/GOLENIOW airport"
cap label var PL_EPSY "OLSZTYN-MAZURY airport"
cap label var PL_EPWA "WARSZAWA/CHOPINA airport"
cap label var PL_EPWR "WROCLAW/STRACHOWICE airport"
cap label var PL_EPZG "ZIELONA GORA/BABIMOST airport"
cap label var PL_EP99 "Unknown airport - POLAND"
cap label var PL_OTH "Other airport - POLAND"
cap label var PT_LPAZ "SANTA MARIA airport"
cap label var PT_LPBG "BRAGANCA airport"
cap label var PT_LPBJ "BEJA airport"
cap label var PT_LPCR "CORVO airport"
cap label var PT_LPCS "CASCAIS airport"
cap label var PT_LPFL "FLORES airport"
cap label var PT_LPFR "FARO airport"
cap label var PT_LPFU "FUNCHAL/MADEIRA I. airport"
cap label var PT_LPGR "GRACIOSA airport"
cap label var PT_LPHR "HORTA airport"
cap label var PT_LPLA "LAJES airport"
cap label var PT_LPMA "MADEIRA airport"
cap label var PT_LPPD "PONTA DELGADA airport"
cap label var PT_LPPI "PICO airport"
cap label var PT_LPPM "PORTIMAO airport"
cap label var PT_LPPO "SANTA MARIA OAC/FIC airport"
cap label var PT_LPPR "PORTO airport"
cap label var PT_LPPS "PORTO SANTO airport"
cap label var PT_LPPT "LISBOA airport"
cap label var PT_LPSJ "SAO JORGE airport"
cap label var PT_LPVR "VILA REAL airport"
cap label var PT_LPVZ "VISEU airport"
cap label var PT_OTH "Other airport - PORTUGAL"
cap label var RO_LRAR "ARAD airport"
cap label var RO_LRBC "BACAU/GEORGE ENESCU airport"
cap label var RO_LRBM "BAIA MARE airport"
cap label var RO_LRBS "BUCURESTI/BANEASA-AUREL VLAICU airport"
cap label var RO_LRCK "CONSTANTA/MIHAIL KOGALNICEANU airport"
cap label var RO_LRCL "CLUJ NAPOCA/AVRAM IANCU airport"
cap label var RO_LRCS "CARANSEBES airport"
cap label var RO_LRCV "CRAIOVA airport"
cap label var RO_LRIA "IASI airport"
cap label var RO_LROD "ORADEA airport"
cap label var RO_LROP "BUCURESTI/HENRI COANDA airport"
cap label var RO_LRSB "SIBIU airport"
cap label var RO_LRSM "SATU MARE airport"
cap label var RO_LRSV "SUCEAVA/STEFAN CEL MARE airport"
cap label var RO_LRTC "TULCEA/DELTA DUNARII airport"
cap label var RO_LRTM "TARGU MURES/TRANSILVANIA airport"
cap label var RO_LRTR "TIMISOARA/TRAIAN VUIA airport"
cap label var RO_OTH "Other airport - ROMANIA"
cap label var SI_LJLJ "LJUBLJANA/BRNIK airport"
cap label var SI_OTH "Other airport - SLOVENIA"
cap label var SK_LZIB "BRATISLAVA/M.R.STEFANIK airport"
cap label var SK_LZKZ "KOSICE airport"
cap label var SK_LZPP "PIESTANY airport"
cap label var SK_LZSL "SLIAC airport"
cap label var SK_LZTT "POPRAD-TATRY airport"
cap label var SK_LZZI "ZILINA airport"
cap label var SK_LZ99 "Unknown airport - SLOVAKIA"
cap label var SK_OTH "Other airport - SLOVAKIA"
cap label var FI_EFES "TAMPERE ACC/RCC airport"
cap label var FI_EFET "ENONTEKIO airport"
cap label var FI_EFHA "HALLI airport"
cap label var FI_EFHE "HERNESAARI airport"
cap label var FI_EFHF "HELSINKI-MALMI airport"
cap label var FI_EFHK "HELSINKI-VANTAA airport"
cap label var FI_EFHN "HANKO airport"
cap label var FI_EFHV "HYVINKAA airport"
cap label var FI_EFIM "IMMOLA airport"
cap label var FI_EFIV "IVALO airport"
cap label var FI_EFJO "JOENSUU airport"
cap label var FI_EFJY "JYVASKYLA airport"
cap label var FI_EFKA "KAUHAVA airport"
cap label var FI_EFKE "KEMI-TORNIO airport"
cap label var FI_EFKI "KAJAANI airport"
cap label var FI_EFKK "KOKKOLA-PIETARSAARI airport"
cap label var FI_EFKS "KUUSAMO airport"
cap label var FI_EFKT "KITTILA airport"
cap label var FI_EFKU "KUOPIO airport"
cap label var FI_EFLA "LAHTI-VESIVEHMAA airport"
cap label var FI_EFLN "LIEKSA-NURMES airport"
cap label var FI_EFLP "LAPPEENRANTA airport"
cap label var FI_EFMA "MARIEHAMN airport"
cap label var FI_EFMI "MIKKELI airport"
cap label var FI_EFOU "OULU airport"
cap label var FI_EFPO "PORI airport"
cap label var FI_EFPY "PYHASALMI airport"
cap label var FI_EFRO "ROVANIEMI airport"
cap label var FI_EFSA "SAVONLINNA airport"
cap label var FI_EFSI "SEINAJOKI airport"
cap label var FI_EFSO "SODANKYLA airport"
cap label var FI_EFTP "TAMPERE-PIRKKALA airport"
cap label var FI_EFTU "TURKU airport"
cap label var FI_EFUT "UTTI airport"
cap label var FI_EFVA "VAASA airport"
cap label var FI_EFVR "VARKAUS airport"
cap label var FI_EFYL "YLIVIESKA airport"
cap label var FI_EF99 "Unknown airport - FINLAND"
cap label var FI_OTH "Other airport - FINLAND"
cap label var SE_ESDB "ANGELHOLM airport"
cap label var SE_ESDF "RONNEBY airport"
cap label var SE_ESGG "GOTEBORG/LANDVETTER airport"
cap label var SE_ESGJ "JONKOPING airport"
cap label var SE_ESGP "GOTEBORG/SAVE airport"
cap label var SE_ESGT "TROLLHATTAN-VANERSBORG airport"
cap label var SE_ESKM "MORA/SILJAN airport"
cap label var SE_ESKN "STOCKHOLM/SKAVSTA airport"
cap label var SE_ESMK "KRISTIANSTAD airport"
cap label var SE_ESMO "OSKARSHAMN airport"
cap label var SE_ESMQ "KALMAR airport"
cap label var SE_ESMS "MALMO airport"
cap label var SE_ESMT "HALMSTAD airport"
cap label var SE_ESMX "VAXJO/KRONOBERG airport"
cap label var SE_ESND "SVEG airport"
cap label var SE_ESNG "GALLIVARE airport"
cap label var SE_ESNK "KRAMFORS-SOLLEFTEA airport"
cap label var SE_ESNL "LYCKSELE airport"
cap label var SE_ESNN "SUNDSVALL-TIMRA airport"
cap label var SE_ESNO "ORNSKOLDSVIK airport"
cap label var SE_ESNQ "KIRUNA airport"
cap label var SE_ESNS "SKELLEFTEA airport"
cap label var SE_ESNU "UMEA airport"
cap label var SE_ESNV "VILHELMINA airport"
cap label var SE_ESNX "ARVIDSJAUR airport"
cap label var SE_ESNZ "ARE OSTERSUND airport"
cap label var SE_ESOE "OREBRO airport"
cap label var SE_ESOH "HAGFORS airport"
cap label var SE_ESOK "KARLSTAD airport"
cap label var SE_ESOW "STOCKHOLM/VASTERAS airport"
cap label var SE_ESPA "LULEA/KALLAX airport"
cap label var SE_ESPC "OESTERSUND airport"
cap label var SE_ESSA "STOCKHOLM/ARLANDA airport"
cap label var SE_ESSB "STOCKHOLM/BROMMA airport"
cap label var SE_ESSD "BORLANGE airport"
cap label var SE_ESSF "HULTSFRED-VIMMERBY airport"
cap label var SE_ESSL "LINKOPING/SAAB airport"
cap label var SE_ESSP "NORRKOPING/KUNGSANGEN airport"
cap label var SE_ESSQ "KARLSTAD airport"
cap label var SE_ESST "TORSBY airport"
cap label var SE_ESSV "VISBY airport"
cap label var SE_ESTA "ANGELHOLM airport"
cap label var SE_ESUD "STORUMAM airport"
cap label var SE_ESUP "PAJALA airport"
cap label var SE_ESUT "HEMAVAN TARNABY airport"
cap label var SE_OTH "Other airport - SWEDEN"
cap label var IS_BIAR "AKUREYRI airport"
cap label var IS_BIBA "BAKKI airport"
cap label var IS_BIBD "BILDUDALUR airport"
cap label var IS_BIEG "EGILSSTADIR airport"
cap label var IS_BIGJ "GJOGUR airport"
cap label var IS_BIGR "GRIMSEY airport"
cap label var IS_BIHK "HOLMAVIK airport"
cap label var IS_BIHN "HOFN HORNAFIRDI airport"
cap label var IS_BIHU "HUSAVIK airport"
cap label var IS_BIIS "ISAFJORDUR airport"
cap label var IS_BIKF "KEFLAVIK airport"
cap label var IS_BIKP "KOPASKER airport"
cap label var IS_BIKR "SAUDARKROKUR airport"
cap label var IS_BINF "NORDFJORDUR airport"
cap label var IS_BIPA "PATREKSFJORDUR airport"
cap label var IS_BIPN "PATREKSFJORDUR airport"
cap label var IS_BIRG "RAUFARHOFN airport"
cap label var IS_BIRK "REYKJAVIK airport"
cap label var IS_BIRL "REYKJAHLID airport"
cap label var IS_BISI "SIGLUFJORDUR airport"
cap label var IS_BIST "STYKKISHOLMUR airport"
cap label var IS_BITE "THINGEYRI airport"
cap label var IS_BITN "THORSHOFN airport"
cap label var IS_BIVM "VESTMANNAEYJAR airport"
cap label var IS_BIVO "VOPNAFJORDUR airport"
cap label var IS_OTH "Other airport - ICELAND"
cap label var NO_ENAE "OSTRE AERA airport"
cap label var NO_ENAH "AL/HALLINGDAL SJUKESTUGU airport"
cap label var NO_ENAL "ALESUND/VIGRA airport"
cap label var NO_ENAN "ANDOYA/ANDENES airport"
cap label var NO_ENAS "NY-ALESUND/HAMNERABBEN airport"
cap label var NO_ENAT "ALTA airport"
cap label var NO_ENBA "BARENTSBURG airport"
cap label var NO_ENBD "NORWAY ACC, BODO airport"
cap label var NO_ENBE "BALDER airport"
cap label var NO_ENBG "BERGEN/GRONNEVIKSOREN airport"
cap label var NO_ENBJ "BJORNOYA airport"
cap label var NO_ENBL "FORDE/BRINGELAND airport"
cap label var NO_ENBM "BOMOEN airport"
cap label var NO_ENBN "BRONNOYSUND/BRONNOY airport"
cap label var NO_ENBO "BODO airport"
cap label var NO_ENBR "BERGEN/FLESLAND airport"
cap label var NO_ENBS "BATSFJORD airport"
cap label var NO_ENBV "BERLEVAG airport"
cap label var NO_ENCN "KRISTIANSAND/KJEVIK airport"
cap label var NO_ENDB "DOMBAS/BRUNSHAGEN airport"
cap label var NO_ENDH "DRAMMEN/SYKEHUSET BUSKERUD airport"
cap label var NO_ENDI "GEILO/DAGALI airport"
cap label var NO_ENDO "DOKKA/THOMLEVOLD airport"
cap label var NO_ENDP "DRAUPNER airport"
cap label var NO_ENDR "DRAUGEN airport"
cap label var NO_ENDU "BARDUFOSS airport"
cap label var NO_ENEG "EGGEMOEN airport"
cap label var NO_ENEK "EKOFISK airport"
cap label var NO_ENEL "ELVERUM/SYKEHUSET INNLANDET airport"
cap label var NO_ENEV "HARSTAD/NARVIK/EVENES airport"
cap label var NO_ENFA "FROYA/FLATVAL airport"
cap label var NO_ENFB "STATFJORD B airport"
cap label var NO_ENFD "FORDE/SENTRALSJUKEHUSET airport"
cap label var NO_ENFG "FAGERNES/LEIRIN airport"
cap label var NO_ENFJ "FEDJE airport"
cap label var NO_ENFL "FLORO airport"
cap label var NO_ENFO "FORUS airport"
cap label var NO_ENFR "FRIGG airport"
cap label var NO_ENFY "FYRESDAL airport"
cap label var NO_ENGA "GULLFAKS A airport"
cap label var NO_ENGB "GULLFAKS B (OIL RIG) airport"
cap label var NO_ENGC "GULLFAKS C airport"
cap label var NO_ENGK "GULLKNAPP airport"
cap label var NO_ENGM "OSLO/GARDERMOEN airport"
cap label var NO_ENGN "GRIMSMOEN airport"
cap label var NO_ENGS "SNASA/GRONORA airport"
cap label var NO_ENHA "HAMAR/STAFSBERG airport"
cap label var NO_ENHD "HAUGESUND/KARMOY airport"
cap label var NO_ENHE "HEIDRUN airport"
cap label var NO_ENHF "HAMMERFEST airport"
cap label var NO_ENHK "HASVIK airport"
cap label var NO_ENHM "HEIMDAL airport"
cap label var NO_ENHN "HORNMOEN airport"
cap label var NO_ENHO "HOPEN airport"
cap label var NO_ENHS "HOKKSUND airport"
cap label var NO_ENHT "HATTFJELLDAL/VOLLEN airport"
cap label var NO_ENHV "HONNINGSVAG/VALAN airport"
cap label var NO_ENHX "HAUGESUND/SJUKEHUS airport"
cap label var NO_ENIS "ISFJORD airport"
cap label var NO_ENJA "JAN MAYEN airport"
cap label var NO_ENJB "JARLSBERG airport"
cap label var NO_ENKA "KAUTOKEINO airport"
cap label var NO_ENKB "KRISTIANSUND/KVERNBERGET airport"
cap label var NO_ENKJ "KJELLER airport"
cap label var NO_ENKL "GOL/KLANTEN airport"
cap label var NO_ENKR "KIRKENES/HOYBUKTMOEN airport"
cap label var NO_ENLA "ULA airport"
cap label var NO_ENLH "LILLEHAMMER/SYKEHUSET INNLANDET airport"
cap label var NO_ENLI "FARSUND/LISTA airport"
cap label var NO_ENLK "LEKNES airport"
cap label var NO_ENLU "LUNDE airport"
cap label var NO_ENLX "LORENSKOG/AKERSHUS UNIVERSITETSSYKEHUS airport"
cap label var NO_ENMH "MEHAMN airport"
cap label var NO_ENML "MOLDE/ARO airport"
cap label var NO_ENMS "MOSJOEN/KJAERSTAD airport"
cap label var NO_ENNA "LAKSELV/BANAK airport"
cap label var NO_ENNE "NORNE airport"
cap label var NO_ENNJ "NJORD A airport"
cap label var NO_ENNK "NARVIK/FRAMNES airport"
cap label var NO_ENNM "NAMSOS airport"
cap label var NO_ENNO "NOTODDEN/TUVEN airport"
cap label var NO_ENOA "OSEBERG A airport"
cap label var NO_ENOC "OSEBERG C airport"
cap label var NO_ENOL "ORLAND airport"
cap label var NO_ENOP "OPPDAL/FAGERHAUG airport"
cap label var NO_ENOS "NORWAY ACC, OSLO airport"
cap label var NO_ENOV "ORSTA-VOLDA/HOVDEN airport"
cap label var NO_ENPA "AASEGARDEN airport"
cap label var NO_ENPB "TANA BRU (TANA BRIDGE) airport"
cap label var NO_ENPF "HAMMERFEST, FUGLENES airport"
cap label var NO_ENPH "HATTFJELLDAL airport"
cap label var NO_ENPT "REGIONSYKEHUSET TC airport"
cap label var NO_ENPY "PYRAMIDEN airport"
cap label var NO_ENQA "TROLL A airport"
cap label var NO_ENQB "TROLL B airport"
cap label var NO_ENQC "TROLL C airport"
cap label var NO_ENQD "BRAGE airport"
cap label var NO_ENQE "OSEBERG OST airport"
cap label var NO_ENQF "VESLEFRIKK A airport"
cap label var NO_ENQG "GULLFAKS B airport"
cap label var NO_ENQH "GULLFAKS A SPM1 airport"
cap label var NO_ENQI "GULLFAKS A SPM2 airport"
cap label var NO_ENQK "KVITEBJORN airport"
cap label var NO_ENQO "OSEBERG SOR airport"
cap label var NO_ENQR "SNORRE B airport"
cap label var NO_ENQS "STATFJORD C airport"
cap label var NO_ENQU "HULDRA airport"
cap label var NO_ENQV "VISUND airport"
cap label var NO_ENRA "MO I RANA/ROSSVOLL airport"
cap label var NO_ENRG "ROGNAN airport"
cap label var NO_ENRI "RINGEBU/FRYA airport"
cap label var NO_ENRK "RAKKESTAD airport"
cap label var NO_ENRM "RORVIK/RYUM airport"
cap label var NO_ENRO "ROROS airport"
cap label var NO_ENRS "ROST airport"
cap label var NO_ENRT "TRONDHEIM/ROSTEN airport"
cap label var NO_ENRV "REINSVOLL airport"
cap label var NO_ENRY "MOSS/RYGGE airport"
cap label var NO_ENSA "SVEA airport"
cap label var NO_ENSB "SVALBARD/LONGYEAR airport"
cap label var NO_ENSD "SANDANE/ANDA airport"
cap label var NO_ENSE "SNORRE A airport"
cap label var NO_ENSF "STATFJORD A airport"
cap label var NO_ENSG "SOGNDAL/HAUKASEN airport"
cap label var NO_ENSH "SVOLVAER/HELLE airport"
cap label var NO_ENSI "SKI/SONDRE SKI GARD airport"
cap label var NO_ENSK "STOKMARKNES/SKAGEN airport"
cap label var NO_ENSL "SLEIPNER A airport"
cap label var NO_ENSN "SKIEN/GEITERYGGEN airport"
cap label var NO_ENSO "STORD/SORSTOKKEN airport"
cap label var NO_ENSR "SORKJOSEN airport"
cap label var NO_ENSS "VARDO/SVARTNES airport"
cap label var NO_ENST "SANDNESSJOEN/STOKKA airport"
cap label var NO_ENSU "SUNNDALSORA airport"
cap label var NO_ENSV "NORWAY ACC, STAVANGER airport"
cap label var NO_ENSX "STAVANGER/UNIVERSITETSSYKEHUS airport"
cap label var NO_ENTC "TROMSO/LANGNES airport"
cap label var NO_ENTO "SANDEFJORD/TORP airport"
cap label var NO_ENTR "TRONDHEIM/ST. OLAVS HOSPITAL airport"
cap label var NO_ENTS "TRYSIL/SAETERASEN airport"
cap label var NO_ENTY "TYNSET airport"
cap label var NO_ENUA "ASGARD A airport"
cap label var NO_ENUB "ASGARD B airport"
cap label var NO_ENUC "ASGARD C airport"
cap label var NO_ENUD "DRAUGEN FLP airport"
cap label var NO_ENUH "OSLO/ULLEVAL UNIVERSITETSSYKEHUS airport"
cap label var NO_ENUI "KONGSVINGER airport"
cap label var NO_ENUK "KRISTIN airport"
cap label var NO_ENUL "OS/VAKSINEN airport"
cap label var NO_ENUN "NJORD B airport"
cap label var NO_ENUR "RAKKESTAD/RYGGE airport"
cap label var NO_ENUU "OST ADER/GULLKNALL airport"
cap label var NO_ENVA "TRONDHEIM/VAERNES airport"
cap label var NO_ENVD "VADSO airport"
cap label var NO_ENVE "VALLE/ARAKSOYENE airport"
cap label var NO_ENVF "VESLEFRIKK B airport"
cap label var NO_ENVH "VALHALL A airport"
cap label var NO_ENVR "VAEROY airport"
cap label var NO_ENWG "GUDRUN airport"
cap label var NO_ENWP "PETROJARL 1 airport"
cap label var NO_ENWS "ELDFISK airport"
cap label var NO_ENWV "VALLHALL PH airport"
cap label var NO_ENWY "YME airport"
cap label var NO_ENXA "EKOFISK A airport"
cap label var NO_ENXB "ELDFISK B airport"
cap label var NO_ENXC "COD airport"
cap label var NO_ENXD "EKOFISK D airport"
cap label var NO_ENXE "EDDA airport"
cap label var NO_ENXF "ALBUSKJELL F airport"
cap label var NO_ENXG "GYDA airport"
cap label var NO_ENXH "HOD airport"
cap label var NO_ENXK "EKOFISK K airport"
cap label var NO_ENXL "ELDFISK A airport"
cap label var NO_ENXN "JOTUN A airport"
cap label var NO_ENXO "RINGHORNE airport"
cap label var NO_ENXP "PETROJARL VARG airport"
cap label var NO_ENXQ "FRIGG DP2 airport"
cap label var NO_ENXR "TAMBAR airport"
cap label var NO_ENXS "ALBUSKJELL A airport"
cap label var NO_ENXT "TOR airport"
cap label var NO_ENXU "JOTUN B airport"
cap label var NO_ENXV "VARG airport"
cap label var NO_ENXW "GRANE airport"
cap label var NO_ENXZ "SLEIPNER B airport"
cap label var NO_ENYF "SOGN OG FJORDANE airport"
cap label var NO_ENYM "MANDAL airport"
cap label var NO_ENYR "ROGALAND/ORRE airport"
cap label var NO_ENYV "HORDALAND airport"
cap label var NO_ENZV "STAVANGER/SOLA airport"
cap label var NO_EN99 "Unknown airport - NORWAY"
cap label var NO_OTH "Other airport - NORWAY"
cap label var CH_LSAW "SWITZERLAND MET airport"
cap label var CH_LSER "RARON airport"
cap label var CH_LSEZ "ZERMATT airport"
cap label var CH_LSGB "BEX airport"
cap label var CH_LSGC "LES EPLATURES airport"
cap label var CH_LSGE "ECUVILLENS airport"
cap label var CH_LSGG "GENEVA airport"
cap label var CH_LSGK "SAANEN airport"
cap label var CH_LSGL "LAUSANNE-LA BLECHERETTE airport"
cap label var CH_LSGN "NEUCHATEL airport"
cap label var CH_LSGP "LA COTE airport"
cap label var CH_LSGR "REICHENBACH airport"
cap label var CH_LSGS "SION airport"
cap label var CH_LSGT "GRUYERES airport"
cap label var CH_LSGY "YVERDON-LES-BAINS airport"
cap label var CH_LSHA "GSTAAD-INN GRUND airport"
cap label var CH_LSHC "COLLOMBEY-MURAZ airport"
cap label var CH_LSHG "GAMPEL airport"
cap label var CH_LSMD "DUBENDORF airport"
cap label var CH_LSMF "MOLLIS airport"
cap label var CH_LSMU "BUOCHS airport"
cap label var CH_LSPA "AMLIKON airport"
cap label var CH_LSPD "DITTINGEN airport"
cap label var CH_LSPF "SCHAFFHAUSEN airport"
cap label var CH_LSPG "KAGISWIL airport"
cap label var CH_LSPH "WINTERTHUR airport"
cap label var CH_LSPK "HASENSTRICK airport"
cap label var CH_LSPL "LANGENTHAL airport"
cap label var CH_LSPM "AMBRI airport"
cap label var CH_LSPN "TRIENGEN airport"
cap label var CH_LSPO "OLTEN airport"
cap label var CH_LSPU "MUNSTER airport"
cap label var CH_LSPV "WANGEN-LACHEN airport"
cap label var CH_LSTA "RARON airport"
cap label var CH_LSTB "BELLECHASSE airport"
cap label var CH_LSTO "MOTIERS airport"
cap label var CH_LSTR "MONTRICHER airport"
cap label var CH_LSTS "ST.STEPHAN airport"
cap label var CH_LSTZ "ZWEISIMMEN airport"
cap label var CH_LSZA "LUGANO airport"
cap label var CH_LSZB "BERN-BELP airport"
cap label var CH_LSZE "BAD RAGAZ airport"
cap label var CH_LSZF "BIRRFELD airport"
cap label var CH_LSZG "GRENCHEN airport"
cap label var CH_LSZH "ZURICH airport"
cap label var CH_LSZI "FRICKTAL-SCHUPFART airport"
cap label var CH_LSZJ "COURTELARY airport"
cap label var CH_LSZK "SPECK-FEHRALTORF airport"
cap label var CH_LSZL "LOCARNO airport"
cap label var CH_LFSB "BALE-MULHOUSE airport"
cap label var CH_LSZM "BASEL airport"
cap label var CH_LSZN "HAUSEN AM ALBIS airport"
cap label var CH_LSZO "LUZERN-BEROMUNSTER airport"
cap label var CH_LSZP "BIEL-KAPPELEN airport"
cap label var CH_LSZR "ST. GALLEN-ALTENRHEIN airport"
cap label var CH_LSZS "SAMEDAN airport"
cap label var CH_LSZT "LOMMIS airport"
cap label var CH_LSZU "BUTTWIL airport"
cap label var CH_LSZV "SITTERDORF airport"
cap label var CH_LSZW "THUN airport"
cap label var CH_LSZX "SCHANIS airport"
cap label var CH_LSZY "PORRENTRUY airport"
cap label var CH_LSZZ "COLLECTIVE ADDRESS FOR NOTAM AND SNOWTAM airport"
cap label var CH_LS99 "Unknown airport - SWITZERLAND"
cap label var CH_OTH "Other airport - SWITZERLAND"
cap label var UK_EG14 "SOUTH MARSTON airport"
cap label var UK_EG19 "ST KILDA airport"
cap label var UK_EGAA "BELFAST/ALDERGROVE airport"
cap label var UK_EGAC "BELFAST/CITY airport"
cap label var UK_EGAE "LONDONDERRY/EGLINTON airport"
cap label var UK_EGBB "BIRMINGHAM airport"
cap label var UK_EGBE "COVENTRY airport"
cap label var UK_EGBJ "GLOUCESTERSHIRE airport"
cap label var UK_EGCC "MANCHESTER airport"
cap label var UK_EGCD "MANCHESTER WOODFORD airport"
cap label var UK_EGCN "DONCASTER SHEFFIELD airport"
cap label var UK_EGDG "NEWQUAY airport"
cap label var UK_EGDL "LYNEHAM airport"
cap label var UK_EGDR "CULDROSE airport"
cap label var UK_EGEC "CAMPBELTOWN airport"
cap label var UK_EGEN "NORTH RONALDSAY airport"
cap label var UK_EGER "STRONSAY airport"
cap label var UK_EGET "LERWICK/TINGWALL airport"
cap label var UK_EGFE "HAVERFORDWEST airport"
cap label var UK_EGFF "CARDIFF airport"
cap label var UK_EGFH "SWANSEA airport"
cap label var UK_EGGD "BRISTOL airport"
cap label var UK_EGGP "LIVERPOOL airport"
cap label var UK_EGGW "LONDON LUTON airport"
cap label var UK_EGHC "LANDS END airport"
cap label var UK_EGHD "PLYMOUTH airport"
cap label var UK_EGHE "SCILLY ISLES/ST MARYS airport"
cap label var UK_EGHH "BOURNEMOUTH airport"
cap label var UK_EGHI "SOUTHAMPTON airport"
cap label var UK_EGHJ "BEMBRIDGE airport"
cap label var UK_EGHK "PENZANCE airport"
cap label var UK_EGHQ "NEWQUAY airport"
cap label var UK_EGHR "CHICHESTER/GOODWOOD airport"
cap label var UK_EGHT "TRESCO airport"
cap label var UK_EGJA "ALDERNEY airport"
cap label var UK_EGJB "GUERNSEY airport"
cap label var UK_EGJJ "JERSEY airport"
cap label var UK_EGKA "SHOREHAM airport"
cap label var UK_EGKB "BIGGIN HILL airport"
cap label var UK_EGKK "LONDON GATWICK airport"
cap label var UK_EGKR "REDHILL airport"
cap label var UK_EGLC "LONDON/CITY airport"
cap label var UK_EGLF "FARNBOROUGH airport"
cap label var UK_EGLK "BLACKBUSHE airport"
cap label var UK_EGLL "LONDON HEATHROW airport"
cap label var UK_EGLW "LONDON HELIPORT airport"
cap label var UK_EGMC "SOUTHEND airport"
cap label var UK_EGMD "LYDD airport"
cap label var UK_EGMH "MANSTON airport"
cap label var UK_EGNC "CARLISLE airport"
cap label var UK_EGNE "RETFORD/GAMSTON airport"
cap label var UK_EGNH "BLACKPOOL airport"
cap label var UK_EGNJ "HUMBERSIDE airport"
cap label var UK_EGNL "BARROW/WALNEY ISLAND airport"
cap label var UK_EGNM "LEEDS BRADFORD airport"
cap label var UK_EGNO "WARTON airport"
cap label var UK_EGNR "HAWARDEN airport"
cap label var UK_EGNS "ISLE OF MAN airport"
cap label var UK_EGNT "NEWCASTLE airport"
cap label var UK_EGNV "DURHAM TEES VALLEY airport"
cap label var UK_EGNX "EAST MIDLANDS airport"
cap label var UK_EGPA "KIRKWALL airport"
cap label var UK_EGPB "SUMBURGH airport"
cap label var UK_EGPC "WICK airport"
cap label var UK_EGPD "ABERDEEN/DYCE airport"
cap label var UK_EGPE "INVERNESS airport"
cap label var UK_EGPF "GLASGOW airport"
cap label var UK_EGPH "EDINBURGH airport"
cap label var UK_EGPI "ISLAY airport"
cap label var UK_EGPK "PRESTWICK airport"
cap label var UK_EGPL "BENBECULA airport"
cap label var UK_EGPM "SCATSTA airport"
cap label var UK_EGPN "DUNDEE airport"
cap label var UK_EGPO "STORNOWAY airport"
cap label var UK_EGPR "BARRA airport"
cap label var UK_EGPU "TIREE airport"
cap label var UK_EGPW "UNST airport"
cap label var UK_EGSC "CAMBRIDGE airport"
cap label var UK_EGSD "GREAT YARMOUTH/NORTH DENES airport"
cap label var UK_EGSH "NORWICH airport"
cap label var UK_EGSS "LONDON STANSTED airport"
cap label var UK_EGSY "SHEFFIELD CITY airport"
cap label var UK_EGTC "CRANFIELD airport"
cap label var UK_EGTE "EXETER airport"
cap label var UK_EGTG "BRISTOL FILTON airport"
cap label var UK_EGTH "OLD WARDEN airport"
cap label var UK_EGTK "OXFORD/KIDLINGTON airport"
cap label var UK_EGTO "ROCHESTER airport"
cap label var UK_EGUN "MILDENHALL airport"
cap label var UK_EGVN "BRIZE NORTON airport"
cap label var UK_EGVP "MIDDLE WALLOP airport"
cap label var UK_EGWU "NORTHOLT airport"
cap label var UK_EGWZ "ALCONBURY airport"
cap label var UK_EGXW "WADDINGTON airport"
cap label var UK_OTH "Other airport - UNITED KINGDOM"
cap label var ME_LYPG "PODGORICA airport"
cap label var ME_LYTV "TIVAT airport"
cap label var ME_OTH "Other airport - MONTENEGRO"
cap label var MK_LWOH "OHRID airport"
cap label var MK_LWSK "SKOPJE airport"
cap label var MK_OTH "Other airport - NORTH MACEDONIA"
cap label var AL_LATI "TIRANA airport"
cap label var AL_OTH "Other airport - ALBANIA"
cap label var RS_LYBE "BEOGRAD/NIKOLA TESLA airport"
cap label var RS_LYNI "NIS airport"
cap label var RS_OTH "Other airport - SERBIA"
cap label var TR_LTAC "ANKARA/ESENBOGA airport"
cap label var TR_LTAF "ADANA airport"
cap label var TR_LTAI "ANTALYA airport"
cap label var TR_LTAJ "GAZIANTEP airport"
cap label var TR_LTAK "HATAY/ISKENDERUN airport"
cap label var TR_LTAL "KASTAMONU airport"
cap label var TR_LTAN "KONYA airport"
cap label var TR_LTAP "AMASYA/MERZIFON airport"
cap label var TR_LTAR "SIVAS/NURI DEMIRAG airport"
cap label var TR_LTAS "ZONGULDAK/CAYCUMA airport"
cap label var TR_LTAT "MALATYA airport"
cap label var TR_LTAU "KAYSERI airport"
cap label var TR_LTAW "TOKAT airport"
cap label var TR_LTAY "DENIZLI/CARDAK airport"
cap label var TR_LTAZ "KAPADOKYA airport"
cap label var TR_LTBA "ISTANBUL/ATATURK airport"
cap label var TR_LTBD "AYDIN/CILDIR airport"
cap label var TR_LTBF "BALIKESIR/MERKEZ airport"
cap label var TR_LTBH "CANAKKALE airport"
cap label var TR_LTBJ "IZMIR/ADNAN MENDERES airport"
cap label var TR_LTBO "USAK airport"
cap label var TR_LTBQ "KOCAELI/CENGIZ TOPEL airport"
cap label var TR_LTBR "BURSA/YENISEHIR airport"
cap label var TR_LTBS "MUGLA/DALAMAN airport"
cap label var TR_LTBU "TEKIRDAG/CORLU airport"
cap label var TR_LTBY "ESKISEHIR/HASAN POLATKAN airport"
cap label var TR_LTBZ "ZAFER airport"
cap label var TR_LTCA "ELAZIG airport"
cap label var TR_LTCB "AGRI airport"
cap label var TR_LTCC "DIYARBAKIR airport"
cap label var TR_LTCD "ERZINCAN airport"
cap label var TR_LTCE "ERZURUM airport"
cap label var TR_LTCF "KARS/HARAKANI airport"
cap label var TR_LTCG "TRABZON airport"
cap label var TR_LTCH "SANLIURFA airport"
cap label var TR_LTCI "VAN/FERIT MELEN airport"
cap label var TR_LTCJ "BATMAN airport"
cap label var TR_LTCK "MUS airport"
cap label var TR_LTCL "SIIRT airport"
cap label var TR_LTCM "SINOP airport"
cap label var TR_LTCN "KAHRAMANMARAS airport"
cap label var TR_LTCO "AGRI/AHMED-I HANI airport"
cap label var TR_LTCP "ADIYAMAN airport"
cap label var TR_LTCR "MARDIN airport"
cap label var TR_LTCS "SANLIURFA/GAP airport"
cap label var TR_LTCT "IGDIR airport"
cap label var TR_LTCU "BINGOL airport"
cap label var TR_LTCV "SIRNAK/SERAFETTIN ELCI airport"
cap label var TR_LTCW "HAKKARI/YUKSEKOVA SELAHADDIN EYYUBI airport"
cap label var TR_LTDA "HATAY airport"
cap label var TR_LTFC "ISPARTA/S.DEMIREL airport"
cap label var TR_LTFD "BALIKESIR/KOCA SEYIT airport"
cap label var TR_LTFE "MUGLA/MILAS-BODRUM airport"
cap label var TR_LTFG "GAZIPASA-ALANYA airport"
cap label var TR_LTFH "SAMSUN/CARSAMBA airport"
cap label var TR_LTFJ "ISTANBUL/SABIHA GOKCEN airport"
cap label var TR_LTFK "GOKCEADA airport"
cap label var TR_LTFM "ISTANBUL/ISTANBUL HAVALIMANI airport"
cap label var TR_OTH "Other airport - TURKEY"
