cap label var TOTAL "Total"
cap label var FORD1_4 "Natural sciences, Engineering and technology, Medical and health sciences, Agricultural sciences"
cap label var FORD1 "Natural sciences"
cap label var FORD101 "Mathematics"
cap label var FORD102 "Computer and information sciences"
cap label var FORD103 "Physical sciences"
cap label var FORD104 "Chemical sciences"
cap label var FORD105 "Earth and related environmental sciences"
cap label var FORD106 "Biological sciences"
cap label var FORD107 "Other natural sciences"
cap label var FORD2 "Engineering and technology"
cap label var FORD201 "Civil engineering"
cap label var FORD202 "Electrical engineering, electronic engineering, information engineering"
cap label var FORD203 "Mechanical engineering"
cap label var FORD204 "Chemical engineering"
cap label var FORD205 "Materials engineering"
cap label var FORD206 "Medical engineering"
cap label var FORD207 "Environmental engineering"
cap label var FORD208 "Environmental biotechnology"
cap label var FORD209 "Industrial biotechnology"
cap label var FORD210 "Nano-technology"
cap label var FORD211 "Other engineering and technologies"
cap label var FORD3 "Medical and health sciences"
cap label var FORD301 "Basic medicine"
cap label var FORD302 "Clinical medicine"
cap label var FORD303 "Health sciences"
cap label var FORD304 "Medical biotechnology"
cap label var FORD305 "Other medical sciences"
cap label var FORD4 "Agricultural sciences"
cap label var FORD401 "Agriculture, forestry, and fisheries"
cap label var FORD402 "Animal and dairy science"
cap label var FORD403 "Veterinary science"
cap label var FORD404 "Agricultural biotechnology"
cap label var FORD405 "Other agricultural sciences"
cap label var FORD5_6 "Social sciences and Humanities"
cap label var FORD5 "Social sciences"
cap label var FORD501 "Psychology and cognitive sciences"
cap label var FORD502 "Economics and business"
cap label var FORD503 "Education"
cap label var FORD504 "Sociology"
cap label var FORD505 "Law"
cap label var FORD506 "Political science"
cap label var FORD507 "Social and economic geography"
cap label var FORD508 "Media and communications"
cap label var FORD509 "Other social sciences"
cap label var FORD6 "Humanities"
cap label var FORD601 "History and archaeology"
cap label var FORD602 "Languages and literature"
cap label var FORD603 "Philosophy, ethics and religion"
cap label var FORD604 "Art (arts, history of arts, performing arts, music)"
cap label var FORD605 "Other humanities"
cap label var NSP "Not specified"
