cap label var TOTAL "Total"
cap label var ENT "Enterprise itself"
cap label var ENT_RND "Enterprise itself (R&D performers)"
cap label var ENT_NRND "Enterprise itself (non R&D performers)"
cap label var ENT_OTH "Enterprise together with other enterprises or organisations"
cap label var ENT_OTH_RND "Enterprise together with other enterprises or organisations (R&D performers)"
cap label var ENT_OTH_NRND "Enterprise together with other enterprises or organisations (non R&D performers)"
cap label var ENTOTH "Enterprise itself and/or together with other enterprises or organisations"
cap label var ENT_ADP_OTH "Enterprise by adapting or modifying products and/or process originally developed by other enterprises or organisations"
cap label var ENT_ADP_OTH_RND "Enterprise by adapting or modifying products and/or process originally developed by other enterprises or organisations (R&D performers)"
cap label var ENT_ADP_OTH_NRND "Enterprise by adapting or modifying products and/or process originally developed by other enterprises or organisations (non R&D performers)"
cap label var OTH "Other enterprises or organisations"
cap label var OTH_RND "Other enterprises or organisations (R&D performers)"
cap label var OTH_NRND "Other enterprises or organisations (non R&D performers)"
