cap label var O_GDS "Forestry goods output"
cap label var O_NAI "Net annual increment of standing timber"
cap label var O_SL "Sawlogs and veneer logs"
cap label var OC_SL_TI "Coniferous timber for industrial uses"
cap label var OC_SL_LTI "Coniferous long timber"
cap label var OC_SL_STA "Coniferous stackwood"
cap label var OC_SL_TIO "Coniferous timber for industrial uses: other"
cap label var ON_SL_TI "Non-coniferous timber for industrial uses"
cap label var ON_SL_LTI "Long timber (non-coniferous)"
cap label var ON_SL_STA "Stackwood (non-coniferous)"
cap label var ON_SL_TIO "Non-coniferous timber for industrial uses: other"
cap label var O_FUEL "Fuelwood"
cap label var O_PULP "Pulpwood"
cap label var O_SMALL "Small-diameter timber and stumps"
cap label var O_OWNREV "Own-account planting for regular income"
cap label var O_OTH "Other forest products"
cap label var O_OCORK "Cork"
cap label var O_OPLAN "Forestry and nursery plants"
cap label var O_OOTH "Other products"
cap label var O_SER "Forestry services output"
cap label var O_SREV "Planting of trees for regular income"
cap label var O_STREE "Other services including tree planting for wood"
cap label var O_BP "Forestry output at basic prices"
cap label var O_NFS "Non-forestry secondary activities (inseparable)"
cap label var O_NFST "Products from the transformation of forestry products"
cap label var O_NFSO "Other non-separable secondary activities (goods and services)"
cap label var O_TOT "Total output of forestry at basic prices"
cap label var C_TOT "Total intermediate consumption"
cap label var C_REM "Timber removed by logging"
cap label var C_PLAN "Plants"
cap label var C_NRG "Energy, lubricants"
cap label var C_NRGE "Energy, lubricants - electricity"
cap label var C_NRGG "Energy, lubricants - gas"
cap label var C_NRGF "Energy, lubricants - other fuels and propellants"
cap label var C_NRGO "Energy, lubricants - other"
cap label var C_FERT "Fertilisers and soil improvers"
cap label var C_PPP "Plant protection products and pesticides"
cap label var C_MAT "Maintenance of materials"
cap label var C_BLD "Maintenance of buildings"
cap label var C_SER "Forestry services"
cap label var C_FISIM "Financial intermediation services indirectly measured (FISIM)"
cap label var C_OTH "Other goods and services"
cap label var GVA "Gross value added at basic prices"
cap label var FCC "Fixed capital consumption"
cap label var F_TRE "Fixed capital consumption in trees"
cap label var F_EQBLD "Fixed capital consumption in equipment and buildings"
cap label var F_EQ "Fixed capital consumption: equipment"
cap label var F_BLD "Fixed capital consumption: buildings"
cap label var F_OTH "Other fixed capital consumption"
cap label var NVA "Net value added at basic prices"
cap label var TAX_PDN "Other taxes on production"
cap label var SUB_PDN "Other subsidies on production"
cap label var CE "Compensation of employees"
cap label var OS "Operating surplus / mixed income"
cap label var R_PA "Rents and other real estate rental charges payable"
cap label var INT_PA "Interest payable"
cap label var INT_RE "Interest receivable"
cap label var EI "Entrepreneurial income (net)"
cap label var GFCF "Gross fixed capital formation (excluding deductible VAT)"
cap label var G_NF "GFCF in non-forestry products"
cap label var G_MAT "GFCF in materials"
cap label var G_MAC "GFCF in machines and other equipment"
cap label var G_TRA "GFCF in transport equipment"
cap label var G_BLD "GFCF in forestry buildings (non-residential)"
cap label var G_OFIX "GFCF in intangible fixed assets (e.g. computer software)"
cap label var G_ONON "Addition to the value of non-financial non-produced assets"
cap label var G_OIMP "GFCF in major land improvements"
cap label var G_OCOS "Costs linked to the purchase of land and production rights"
cap label var NFCF "Net fixed capital formation (excluding deductible VAT)"
cap label var CI "Changes in inventories"
cap label var CI_PRO "Changes in inventories of which work in progress"
cap label var CT "Capital transfers"
cap label var CT_INV "Investment grants"
cap label var CT_OTH "Other capital transfers"
cap label var P1_TOT "Output"
cap label var P2_TOT "Intermediate consumption"
cap label var B1G_GVA "Gross value added"
cap label var P51C_FCC "Consumption of fixed capital"
cap label var B1N_NVA "Net value added"
cap label var D29_TAX_PDN "Other taxes on production"
cap label var D39_SUB_PDN "Other subsidies on production"
cap label var D1_CE "Compensation of employees"
cap label var B2A3N_OS "Net operating surplus and Mixed income"
cap label var D4_PI_RE "Property income received"
cap label var D41_INT_RE "Interest received"
cap label var D42_CPIN_RE "Distributed income of corporations"
cap label var D43_IV_RE "Reinvested earnings on foreign direct investment"
cap label var D44_IVO_RE "Other investment income"
cap label var D45_R_RE "Rent received"
cap label var D4_PI_PA "Property income paid"
cap label var D41_INT_PA "Interest paid"
cap label var D45_R_PA "Rent paid"
cap label var B4N_EI "Net entrepreneurial income"
cap label var P51G_GFCF "Gross fixed capital formation"
cap label var G_TRE "Planting of trees to provide regular income"
cap label var G_EQBLD "Equipment and buildings"
cap label var G_OTH "Other gross fixed capital formation"
cap label var P51N_NFCF "Net fixed capital formation"
cap label var P52_CI "Changes in inventories"
cap label var AN1221_CI_PRO "Addition to work-in-progress on cultivated biological assets"
cap label var CI_OTH "Other changes in inventories"
cap label var D9_CT "Capital transfers"
cap label var P1 "Output of forestry and connected secondary activities"
cap label var P11 "Market output"
cap label var P12 "Output for own final use"
cap label var P13 "Other non-market output"
cap label var P1_S14 "Output of households"
cap label var P1_GD_SERV "Goods and services output characteristic of forestry"
cap label var P1_GD "Goods characteristic of forestry"
cap label var P1_TR_PL "Trees, tree plants and forest tree seeds"
cap label var P1_PL "Live forest tree plants and tree seeds"
cap label var P1_TR "Forest trees"
cap label var P1_RW "Roundwood (wood in the rough)"
cap label var P1_RWFW "Fuel wood"
cap label var P1_RWFW_C "Fuel wood - coniferous"
cap label var P1_RWFW_NC "Fuel wood - non-coniferous"
cap label var P1_RWIN "Industrial roundwood"
cap label var P1_RWIN_C "Industrial roundwood - coniferous"
cap label var P1_RWIN_LT_C "Industrial roundwood - long timber, coniferous"
cap label var P1_RWIN_ST_C "Industrial roundwood - stackwood, coniferous"
cap label var P1_RWIN_O_C "Industrial roundwood - other timber, coniferous"
cap label var P1_RWIN_NC "Industrial roundwood - non-coniferous"
cap label var P1_RWIN_LT_NC "Industrial roundwood - long timber, non-coniferous"
cap label var P1_RWIN_ST_NC "Industrial roundwood - stackwood, non-coniferous"
cap label var P1_RWIN_O_NC "Industrial roundwood - other timber, non-coniferous"
cap label var P1_RWIN_TNC "Industrial roundwood - tropical, non-coniferous"
cap label var P1_NW "Non-wood products"
cap label var P1_NW_CO "Non-wood products - cork"
cap label var P1_NW_FN "Non-wood products - forestry and nursery plants"
cap label var P1_NW_O "Non-wood products - other products"
cap label var P1_SERV "Services output characteristic of forestry"
cap label var P1_PTR "Planting of trees for regular income"
cap label var P1_SEC "Products from connected secondary activities in the local KAU"
cap label var P1_SECTRF "Transformation of products from connected secondary activities"
cap label var P1_OSEC "Other non-separable secondary activities (goods and services)"
cap label var P1_O "Other products"
cap label var P2 "Intermediate consumption"
cap label var P2_GD "Goods input"
cap label var P2_TR_PL "Trees, tree plants and forest tree seeds"
cap label var P2_NRG "Energy, lubricants"
cap label var P2_NRG_E "Energy, lubricants - electricity"
cap label var P2_NRG_G "Energy, lubricants - gas"
cap label var P2_NRG_OFP "Energy, lubricants - other fuels and propellants"
cap label var P2_NRG_O "Energy, lubricants - other"
cap label var P2_FERT "Fertilisers and soil improvers"
cap label var P2_PPP "Plant protection products and pesticides"
cap label var P2_SERV "Services input"
cap label var P2_FL "Input of services characteristic of forestry and logging"
cap label var P2_MREQ "Regular maintenance and repair of equipment"
cap label var P2_MBL "Maintenance of buildings"
cap label var P2_FISIM "Financial intermediation services indirectly measured (FISIM)"
cap label var P2_O "Other products used as inputs"
cap label var B1G "Gross value added"
cap label var P51C "Consumption of fixed capital"
cap label var P51C_EQ "Fixed capital consumption - equipment"
cap label var P51C_BL "Fixed capital consumption - buildings"
cap label var B1N "Net value added"
cap label var D29 "Other taxes on production"
cap label var D39 "Other subsidies on production"
cap label var FI "Factor income"
cap label var D1 "Compensation of employees"
cap label var B2A3N "Net operating surplus and mixed income"
cap label var D4 "Net property income"
cap label var D4_RENT_PA "Rents and other real estate rental charges payable"
cap label var D4_INT_PA "Interest payable"
cap label var D4_INT_RE "Interest receivable"
cap label var B4N "Net entrepreneurial income"
cap label var P51G "Gross fixed capital formation (excluding deductible VAT)"
cap label var P51G_PRP "GFCF - plant resources yielding repeat products"
cap label var P51G_PTR "GFCF - planting of trees for regular income"
cap label var P51G_NF "GFCF - non-forestry products"
cap label var P51G_EQBL "GFCF - machinery and equipment; buildings, structures and land improvements"
cap label var P51G_EQ "GFCF - machinery and equipment"
cap label var P51G_MAT "GFCF - materials"
cap label var P51G_MAC "GFCF - machines and other equipment"
cap label var P51G_TRA "GFCF - transport equipment"
cap label var P51G_BL "GFCF - buildings, structures and land improvements"
cap label var P51G_IMP "GFCF - major land improvements"
cap label var P51G_COS "GFCF - costs linked to the purchase of land and production rights"
cap label var P51G_FIX "GFCF - intangible fixed assets (e.g. computer software)"
cap label var P51G_NFP "GFCF - addition to the value of non-financial non-produced assets"
cap label var P51G_O "Other gross fixed capital formation"
cap label var P51N "Net fixed capital formation (excluding deductible VAT)"
cap label var P52 "Changes in inventories"
cap label var P52_PRO "Work-in-progress on cultivated biological assets"
cap label var P52_O "Other changes in inventories"
cap label var D9 "Capital transfers (net)"
cap label var D9_INV "Investment grants"
cap label var D9_O "Other capital transfers"
cap label var NAP "Not applicable"
