cap label var TOTAL "Total"
cap label var FIN "Financial reasons"
cap label var NINT "No interest"
cap label var NTIME_FAM "No time due to family commitments"
cap label var NTIME_WRK_STU "No time due to work or study commitments"
cap label var PERS "Personal reasons"
cap label var PER "Personal reasons"
cap label var PER_HOL "Holidays, leisure and recreation"
cap label var PER_VFR "Visits to friends and relatives"
cap label var PER_OTH "Other personal reasons"
cap label var PROF "Professional, business"
cap label var HLTH "Health reasons"
cap label var SAFE "Safety reasons"
cap label var PERS_HOL "Holidays, leisure and recreation"
cap label var PERS_VFR "Visits to friends and relatives"
cap label var PERS_OTH "Other personal reasons"
cap label var OTH "Other reason"
