cap label var DPH "During paid hours"
cap label var ODPH "Only during paid hours"
cap label var MDPH "Mostly during paid hours"
cap label var OPH "Outside paid hours"
cap label var MOPH "Mostly outside paid hours"
cap label var OOPH "Only outside paid hours"
cap label var NOJB "No job at that time"
cap label var NRESP "No answer"
