cap label var TOTAL "Total"
cap label var WEN_00 "No information"
cap label var WEN_01 "Industrial site"
cap label var WEN_02 "Construction site, construction, opencast quarry, opencast mine"
cap label var WEN_03 "Farming, breeding, fish farming, forest zone"
cap label var WEN_04 "Tertiary activity area, office, amusement area, miscellaneous"
cap label var WEN_05 "Health establishment"
cap label var WEN_06 "Public area"
cap label var WEN_07 "In the home"
cap label var WEN_08 "Sports area"
cap label var WEN_09 "In the air, elevated, excluding construction sites"
cap label var WEN_10 "Underground, excluding construction sites"
cap label var WEN_11 "On /over water, excluding construction sites"
cap label var WEN_12 "In high pressure environments, excluding construction sites"
cap label var WEN_99 "Other Working Environments not listed in the classification"
