cap label var TOTAL "Total"
cap label var _1 "1 room"
cap label var _2 "2 rooms"
cap label var _3 "3 rooms"
cap label var _4 "4 rooms"
cap label var _5 "5 rooms"
cap label var _6 "6 rooms"
cap label var _7 "7 rooms"
cap label var GE7 "7 rooms or more"
cap label var _8 "8 rooms"
cap label var GE8 "8 rooms or more"
cap label var _9 "9 rooms"
cap label var GE9 "9 rooms or more"
cap label var GE10 "10 rooms or more"
cap label var LT25 "Less than 25 rooms"
cap label var _25_99 "From 25 to 99 rooms"
cap label var GE100 "100 rooms or more"
cap label var _100_249 "From 100 to 249 rooms"
cap label var GE250 "250 rooms or more"
cap label var UNK "Unknown"
cap label var TOT_HH "Total number of households"
