cap label var TA1 "Assistance with kind of work"
cap label var TA2 "Assistance with amount of work"
cap label var TA3 "Assistance with mobility to get to and from work"
cap label var TA4 "Assistance with mobility at work"
cap label var TA5 "Support and understanding by superiors and colleagues"
cap label var TA6 "Other"
