cap label var ASS "Any assessment"
cap label var MAN "For managers and supervisors"
cap label var OTHEMPL "For other employees (e.g. production, sales and office workers)"
cap label var ALLEMPL "For all employees"
cap label var NOASS "No assessment"
