cap label var TOTAL "Total"
cap label var DAY "Every day"
cap label var DAY_GE1HD "At least 1 hour every day"
cap label var DAY_LT1HD "Less than 1 hour every day"
cap label var _1D "Once a day"
cap label var GE1D "At least once a day"
cap label var GE2D "At least twice a day"
cap label var WEEK "Every week"
cap label var _1W "Once a week"
cap label var LT10HW "Less than 10 hours per week"
cap label var _10_19HW "From 10 to 19 hours per week"
cap label var GE20HW "20 hours per week or over"
cap label var LT1W "Less than once a week"
cap label var GE1W "At least once a week"
cap label var _1_3W "From 1 to 3 times a week"
cap label var _4_6W "From 4 to 6 times a week"
cap label var MTH "Every month"
cap label var LT1M "Less than once a month"
cap label var _1M "Once a month"
cap label var GE1M "At least once a month"
cap label var SEV_M "Several times a month"
cap label var NM12 "Not in the last 12 months"
cap label var GE1Y "At least once a year"
cap label var ALW_NREG "Always or not regularly"
cap label var ALW "Always"
cap label var MOST "Most of the time"
cap label var REG "Regularly"
cap label var NREG "Not regularly"
cap label var OFT_ALW "Often or always"
cap label var OFT "Often"
cap label var SEV "Several times"
cap label var SEV_ACT "Several times with direct action required"
cap label var SEV_NACT "Several times without direct actions required"
cap label var SMT_OFT "Sometimes or often"
cap label var SMT "Sometimes"
cap label var USU "Usually"
cap label var RAR_NVR "Rarely or never"
cap label var RAR "Rarely"
cap label var FMR "Formerly"
cap label var NVR_SMT "Never or sometimes"
cap label var NVR_OCC "Never or occasionally"
cap label var OCC "Occasionally"
cap label var NVR "Never"
cap label var NVR_NM12 "Never or not in the last 12 months"
cap label var _1_2 "From 1 to 2 times"
cap label var _1_3 "From 1 to 3 times"
cap label var _1_6 "From 1 to 6 times"
cap label var GE1 "At least once"
cap label var _3_5 "From 3 to 5 times"
cap label var _4_6 "From 4 to 6 times"
cap label var _6_9 "From 6 to 9 times"
cap label var GE4 "At least 4 times"
cap label var GT6 "More than 6 times"
cap label var _7_12 "From 7 to 12 times"
cap label var GE10 "10 times or more"
cap label var GT12 "More than 12 times"
cap label var ALPS "All positives"
cap label var NBINGE "No binge drinking"
cap label var NAP "Not applicable"
cap label var NRP "No response"
cap label var UNK "Unknown"
