cap label var TOTAL "Total"
cap label var OWN "Owner"
cap label var OWN_L "Owner, with mortgage or loan"
cap label var OWN_NL "Owner, no outstanding mortgage or housing loan"
cap label var RENT "Tenant"
cap label var RENT_MKT "Tenant, rent at market price"
cap label var RENT_FR "Tenant, rent at reduced price or free"
cap label var CML "Common land"
cap label var SHR_OTH "Shared or other tenure modes"
cap label var OTH "Other"
cap label var UNK "Unknown"
