cap label var BEC_SERV "Services"
cap label var BEC_SERV_IC "Services - intermediate consumption"
cap label var BEC_SERV_FC "Services - final consumption"
cap label var BEC1 "Agriculture, forestry, fishing, food, beverages, tobacco"
cap label var BEC11 "Agriculture, forestry, fishing, food, beverages, tobacco - goods"
cap label var BEC111 "Agriculture, forestry, fishing, food, beverages, tobacco - goods - intermediate consumption"
cap label var BEC1111 "Agriculture, forestry, fishing, food, beverages, tobacco - goods - intermediate consumption - primary"
cap label var BEC1112 "Agriculture, forestry, fishing, food, beverages, tobacco - goods - intermediate consumption - processed"
cap label var BEC111210 "Agriculture, forestry, fishing, food, beverages, tobacco - goods - intermediate consumption - processed - generic"
cap label var BEC111220 "Agriculture, forestry, fishing, food, beverages, tobacco - goods - intermediate consumption - processed - specified"
cap label var BEC112 "Agriculture, forestry, fishing, food, beverages, tobacco - goods - gross fixed capital formation"
cap label var BEC112010 "Agriculture, forestry, fishing, food, beverages, tobacco - goods - gross fixed capital formation - generic"
cap label var BEC112020 "Agriculture, forestry, fishing, food, beverages, tobacco - goods - gross fixed capital formation - specified"
cap label var BEC113 "Agriculture, forestry, fishing, food, beverages, tobacco - goods - final consumption"
cap label var BEC1131 "Agriculture, forestry, fishing, food, beverages, tobacco - goods - final consumption - primary"
cap label var BEC113101 "Agriculture, forestry, fishing, food, beverages, tobacco - goods - final consumption - primary - non-durable"
cap label var BEC113102 "Agriculture, forestry, fishing, food, beverages, tobacco - goods - final consumption - primary - durable"
cap label var BEC1132 "Agriculture, forestry, fishing, food, beverages, tobacco - goods - final consumption - processed"
cap label var BEC113201 "Agriculture, forestry, fishing, food, beverages, tobacco - goods - final consumption - processed - non-durable"
cap label var BEC113202 "Agriculture, forestry, fishing, food, beverages, tobacco - goods - final consumption - processed - durable"
cap label var BEC12 "Agriculture, forestry, fishing, food, beverages, tobacco - services"
cap label var BEC121 "Agriculture, forestry, fishing, food, beverages, tobacco - services - intermediate consumption"
cap label var BEC121010 "Agriculture, forestry, fishing, food, beverages, tobacco - services - intermediate consumption - generic"
cap label var BEC121020 "Agriculture, forestry, fishing, food, beverages, tobacco - services - intermediate consumption - specified"
cap label var BEC123 "Agriculture, forestry, fishing, food, beverages, tobacco - services - final consumption"
cap label var BEC2 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment"
cap label var BEC21 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment - goods"
cap label var BEC211 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment - goods - intermediate consumption"
cap label var BEC2111 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment - goods - intermediate consumption - primary"
cap label var BEC2112 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment - goods - intermediate consumption - processed"
cap label var BEC211210 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment - goods - intermediate consumption - processed - generic"
cap label var BEC211220 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment - goods - intermediate consumption - processed - specified"
cap label var BEC212 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment - goods - gross fixed capital formation"
cap label var BEC212010 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment - goods - gross fixed capital formation - generic"
cap label var BEC212020 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment - goods - gross fixed capital formation - specified"
cap label var BEC213 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment - goods - final consumption"
cap label var BEC2131 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment - goods - final consumption - primary"
cap label var BEC213101 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment - goods - final consumption - primary - non-durable"
cap label var BEC213102 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment - goods - final consumption - primary - durable"
cap label var BEC2132 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment - goods - final consumption - processed"
cap label var BEC213201 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment - goods - final consumption - processed - non-durable"
cap label var BEC213202 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment - goods - final consumption - processed - durable"
cap label var BEC22 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment - services"
cap label var BEC221 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment - services - intermediate consumption"
cap label var BEC221010 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment - services - intermediate consumption - generic"
cap label var BEC221020 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment - services - intermediate consumption - specified"
cap label var BEC223 "Mining, quarrying, refinery, fuels, chemicals, electricity, water, waste treatment - services - final consumption"
cap label var BEC3 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture"
cap label var BEC31 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture - goods"
cap label var BEC311 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture - goods - intermediate consumption"
cap label var BEC3111 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture - goods - intermediate consumption - primary"
cap label var BEC3112 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture - goods - intermediate consumption - processed"
cap label var BEC311210 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture - goods - intermediate consumption - processed - generic"
cap label var BEC311220 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture - goods - intermediate consumption - processed - specified"
cap label var BEC312 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture - goods - gross fixed capital formation"
cap label var BEC312010 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture - goods - gross fixed capital formation - generic"
cap label var BEC312020 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture - goods - gross fixed capital formation - specified"
cap label var BEC313 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture - goods - final consumption"
cap label var BEC3131 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture - goods - final consumption - primary"
cap label var BEC313101 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture - goods - final consumption - primary - non-durable"
cap label var BEC313102 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture - goods - final consumption - primary - durable"
cap label var BEC3132 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture - goods - final consumption - processed"
cap label var BEC313201 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture - goods - final consumption - processed - non-durable"
cap label var BEC313202 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture - goods - final consumption - processed - durable"
cap label var BEC32 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture - services"
cap label var BEC321 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture - services - intermediate consumption"
cap label var BEC321010 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture - services - intermediate consumption - generic"
cap label var BEC321020 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture - services - intermediate consumption - specified"
cap label var BEC323 "Construction, wood, glass, stone, basic metals, housing, electrical appliances, furniture - services - final consumption"
cap label var BEC4 "Textile, apparel, shoes"
cap label var BEC41 "Textile, apparel, shoes - goods"
cap label var BEC411 "Textile, apparel, shoes - goods - intermediate consumption"
cap label var BEC4111 "Textile, apparel, shoes - goods - intermediate consumption - primary"
cap label var BEC4112 "Textile, apparel, shoes - goods - intermediate consumption - processed"
cap label var BEC411210 "Textile, apparel, shoes - goods - intermediate consumption - processed - generic"
cap label var BEC411220 "Textile, apparel, shoes - goods - intermediate consumption - processed - specified"
cap label var BEC412 "Textile, apparel, shoes - goods - gross fixed capital formation"
cap label var BEC412010 "Textile, apparel, shoes - goods - gross fixed capital formation - generic"
cap label var BEC412020 "Textile, apparel, shoes - goods - gross fixed capital formation - specified"
cap label var BEC413 "Textile, apparel, shoes - goods - final consumption"
cap label var BEC4131 "Textile, apparel, shoes - goods - final consumption - primary"
cap label var BEC413101 "Textile, apparel, shoes - goods - final consumption - primary - non-durable"
cap label var BEC413102 "Textile, apparel, shoes - goods - final consumption - primary - durable"
cap label var BEC4132 "Textile, apparel, shoes - goods - final consumption - processed"
cap label var BEC413201 "Textile, apparel, shoes - goods - final consumption - processed - non-durable"
cap label var BEC413202 "Textile, apparel, shoes - goods - final consumption - processed - durable"
cap label var BEC42 "Textile, apparel, shoes - services"
cap label var BEC421 "Textile, apparel, shoes - services - intermediate consumption"
cap label var BEC421010 "Textile, apparel, shoes - services - intermediate consumption - generic"
cap label var BEC421020 "Textile, apparel, shoes - services - intermediate consumption - specified"
cap label var BEC423 "Textile, apparel, shoes - services - final consumption"
cap label var BEC5 "Transport equipment and services, travel, postal services"
cap label var BEC51 "Transport equipment and services, travel, postal services - goods"
cap label var BEC511 "Transport equipment and services, travel, postal services - goods - intermediate consumption"
cap label var BEC5111 "Transport equipment and services, travel, postal services - goods - intermediate consumption - primary"
cap label var BEC5112 "Transport equipment and services, travel, postal services - goods - intermediate consumption - processed"
cap label var BEC511210 "Transport equipment and services, travel, postal services - goods - intermediate consumption - processed - generic"
cap label var BEC511220 "Transport equipment and services, travel, postal services - goods - intermediate consumption - processed - specified"
cap label var BEC512 "Transport equipment and services, travel, postal services - goods - gross fixed capital formation"
cap label var BEC512010 "Transport equipment and services, travel, postal services - goods - gross fixed capital formation - generic"
cap label var BEC512020 "Transport equipment and services, travel, postal services - goods - gross fixed capital formation - specified"
cap label var BEC513 "Transport equipment and services, travel, postal services - goods - final consumption"
cap label var BEC5131 "Transport equipment and services, travel, postal services - goods - final consumption - primary"
cap label var BEC513101 "Transport equipment and services, travel, postal services - goods - final consumption - primary - non-durable"
cap label var BEC513102 "Transport equipment and services, travel, postal services - goods - final consumption - primary - durable"
cap label var BEC5132 "Transport equipment and services, travel, postal services - goods - final consumption - processed"
cap label var BEC513201 "Transport equipment and services, travel, postal services - goods - final consumption - processed - non-durable"
cap label var BEC513202 "Transport equipment and services, travel, postal services - goods - final consumption - processed - durable"
cap label var BEC52 "Transport equipment and services, travel, postal services - services"
cap label var BEC521 "Transport equipment and services, travel, postal services - services - intermediate consumption"
cap label var BEC521010 "Transport equipment and services, travel, postal services - services - intermediate consumption - generic"
cap label var BEC521020 "Transport equipment and services, travel, postal services - services - intermediate consumption - specified"
cap label var BEC523 "Transport equipment and services, travel, postal services - services - final consumption"
cap label var BEC6 "ICT, media, computers, business and financial services"
cap label var BEC61 "ICT, media, computers, business and financial services - goods"
cap label var BEC611 "ICT, media, computers, business and financial services - goods - intermediate consumption"
cap label var BEC6111 "ICT, media, computers, business and financial services - goods - intermediate consumption - primary"
cap label var BEC6112 "ICT, media, computers, business and financial services - goods - intermediate consumption - processed"
cap label var BEC611210 "ICT, media, computers, business and financial services - goods - intermediate consumption - processed - generic"
cap label var BEC611220 "ICT, media, computers, business and financial services - goods - intermediate consumption - processed - specified"
cap label var BEC612 "ICT, media, computers, business and financial services - goods - gross fixed capital formation"
cap label var BEC612010 "ICT, media, computers, business and financial services - goods - gross fixed capital formation - generic"
cap label var BEC612020 "ICT, media, computers, business and financial services - goods - gross fixed capital formation - specified"
cap label var BEC613 "ICT, media, computers, business and financial services - goods - final consumption"
cap label var BEC6131 "ICT, media, computers, business and financial services - goods - final consumption - primary"
cap label var BEC613101 "ICT, media, computers, business and financial services - goods - final consumption - primary - non-durable"
cap label var BEC613102 "ICT, media, computers, business and financial services - goods - final consumption - primary - durable"
cap label var BEC6132 "ICT, media, computers, business and financial services - goods - final consumption - processed"
cap label var BEC613201 "ICT, media, computers, business and financial services - goods - final consumption - processed - non-durable"
cap label var BEC613202 "ICT, media, computers, business and financial services - goods - final consumption - processed - durable"
cap label var BEC62 "ICT, media, computers, business and financial services - services"
cap label var BEC621 "ICT, media, computers, business and financial services - services - intermediate consumption"
cap label var BEC621010 "ICT, media, computers, business and financial services - services - intermediate consumption - generic"
cap label var BEC621020 "ICT, media, computers, business and financial services - services - intermediate consumption - specified"
cap label var BEC623 "ICT, media, computers, business and financial services - services - final consumption"
cap label var BEC7 "Health, pharmaceuticals, education, cultural, sport"
cap label var BEC71 "Health, pharmaceuticals, education, cultural, sport - goods"
cap label var BEC711 "Health, pharmaceuticals, education, cultural, sport - goods - intermediate consumption"
cap label var BEC7111 "Health, pharmaceuticals, education, cultural, sport - goods - intermediate consumption - primary"
cap label var BEC7112 "Health, pharmaceuticals, education, cultural, sport - goods - intermediate consumption - processed"
cap label var BEC711210 "Health, pharmaceuticals, education, cultural, sport - goods - intermediate consumption - processed - generic"
cap label var BEC711220 "Health, pharmaceuticals, education, cultural, sport - goods - intermediate consumption - processed - specified"
cap label var BEC712 "Health, pharmaceuticals, education, cultural, sport - goods - gross fixed capital formation"
cap label var BEC712010 "Health, pharmaceuticals, education, cultural, sport - goods - gross fixed capital formation - generic"
cap label var BEC712020 "Health, pharmaceuticals, education, cultural, sport - goods - gross fixed capital formation - specified"
cap label var BEC713 "Health, pharmaceuticals, education, cultural, sport - goods - final consumption"
cap label var BEC7131 "Health, pharmaceuticals, education, cultural, sport - goods - final consumption - primary"
cap label var BEC713101 "Health, pharmaceuticals, education, cultural, sport - goods - final consumption - primary - non-durable"
cap label var BEC713102 "Health, pharmaceuticals, education, cultural, sport - goods - final consumption - primary - durable"
cap label var BEC7132 "Health, pharmaceuticals, education, cultural, sport - goods - final consumption - processed"
cap label var BEC713201 "Health, pharmaceuticals, education, cultural, sport - goods - final consumption - processed - non-durable"
cap label var BEC713202 "Health, pharmaceuticals, education, cultural, sport - goods - final consumption - processed - durable"
cap label var BEC72 "Health, pharmaceuticals, education, cultural, sport - services"
cap label var BEC721 "Health, pharmaceuticals, education, cultural, sport - services - intermediate consumption"
cap label var BEC721010 "Health, pharmaceuticals, education, cultural, sport - services - intermediate consumption - generic"
cap label var BEC721020 "Health, pharmaceuticals, education, cultural, sport - services - intermediate consumption - specified"
cap label var BEC723 "Health, pharmaceuticals, education, cultural, sport - services - final consumption"
cap label var BEC8 "Government, military and other"
cap label var BEC81 "Government, military and other - goods"
cap label var BEC811 "Government, military and other - goods - intermediate consumption"
cap label var BEC8111 "Government, military and other - goods - intermediate consumption - primary"
cap label var BEC8112 "Government, military and other - goods - intermediate consumption - processed"
cap label var BEC811210 "Government, military and other - goods - intermediate consumption - processed - generic"
cap label var BEC811220 "Government, military and other - goods - intermediate consumption - processed - specified"
cap label var BEC812 "Government, military and other - goods - gross fixed capital formation"
cap label var BEC812010 "Government, military and other - goods - gross fixed capital formation - generic"
cap label var BEC812020 "Regierung, Militär und sonstiges - Waren - Bruttoanlageinvestitionen - generisch"
cap label var BEC813 "Government, military and other - goods - final consumption"
cap label var BEC8131 "Government, military and other - goods - final consumption - primary"
cap label var BEC813101 "Government, military and other - goods - final consumption - primary - non-durable"
cap label var BEC813102 "Government, military and other - goods - final consumption - primary - durable"
cap label var BEC8132 "Government, military and other - goods - final consumption - processed"
cap label var BEC813201 "Government, military and other - goods - final consumption - processed - non-durable"
cap label var BEC813202 "Government, military and other - goods - final consumption - processed - durable"
cap label var BEC82 "Government, military and other - services"
cap label var BEC821 "Government, military and other - services - intermediate consumption"
cap label var BEC821010 "Government, military and other - services - intermediate consumption - generic"
cap label var BEC821020 "Government, military and other - services - intermediate consumption - specified"
cap label var BEC823 "Government, military and other - services - final consumption"
