cap label var TOTAL "Total connected to wastewater treatment"
cap label var WWT_GE2 "Urban, independent and other wastewater treatment - at least secondary treatment"
cap label var URB_CS "Urban wastewater collecting system"
cap label var URB_OTH "Urban and other wastewater treatment plants - total"
cap label var URB_OTH_CS "Urban and other wastewater treatment plants - total"
cap label var URB_OTH_T1 "Urban and other wastewater treatment plants - primary treatment"
cap label var URB_OTH_CS_T1 "Urban and other wastewater treatment plants - primary treatment"
cap label var URB_OTH_T2 "Urban and other wastewater treatment plants - secondary treatment"
cap label var URB_OTH_CS_T2 "Urban and other wastewater treatment plants - secondary treatment"
cap label var URB_OTH_T3 "Urban and other wastewater treatment plants - tertiary treatment"
cap label var URB_OTH_CS_T3 "Urban and other wastewater treatment plants - tertiary treatment"
cap label var URB_OTH_GE2 "Urban and other wastewater treatment plants - at least secondary treatment"
cap label var URB_OTH_NSP "Urban and other wastewater treatment plants - treatment not specified"
cap label var URB_OTH_CS_NSP "Urban and other wastewater treatment plants - treatment not specified"
cap label var URB_OTH_NC "Percentage of resident population not connected to urban and other wastewater treatment plants"
cap label var URB_OTH_CS_NC "Urban and other wastewater treatment plants - not connected"
cap label var URB "Urban wastewater treatment plants - total"
cap label var URB_TP "Urban wastewater treatment plants - total"
cap label var IND "Independent wastewater treatment - total"
cap label var IND_T_GE2 "Independent wastewater treatment - at least secondary treatment"
cap label var IND_TANK "Wastewater transported from independent storage tanks to wastewater treatment plants by means of trucks"
cap label var OTH "Other wastewater treatment plants - total"
cap label var OTH_TP "Other wastewater treatment plants - total"
