cap label var TOTAL "Total"
cap label var CNL "Navigable canals"
cap label var RIV_LAK "Navigable rivers and lakes"
cap label var RIV "Navigable rivers"
cap label var MWAY "Motorways"
cap label var RD_EUR "E-roads"
cap label var RD_STA "State roads"
cap label var RD_PRO "Provincial roads"
cap label var RD_COM "Communal roads"
cap label var RD_URB "Urban roads"
cap label var RD_RUR "Rural roads"
cap label var RD_TEN "Roads on Trans-European Networks"
cap label var RD_NTEN "Roads not on Trans-European Networks"
cap label var RD_INB "Other roads within built-up areas"
cap label var RD_OUTB "Other roads outside built-up areas"
cap label var RD_PAV "Paved roads"
cap label var RD_NPAV "Unpaved roads"
cap label var RD_OTH "Other roads"
cap label var RL "Total railway lines"
cap label var RL_ELC "Electrified railway lines"
cap label var RL_NELC "Non-electrified railway lines"
cap label var RL_HSPD "High speed railway lines"
cap label var RL_TGE2 "Railway lines with double and more tracks"
cap label var RL_DHSPD "Dedicated high speed railway lines"
cap label var RL_UHSPD "Upgraded high speed railway lines"
cap label var RL_CV "Conventional railway lines"
cap label var RL_OTH "Other railway lines"
cap label var RT_ELC "Electrified railway tracks"
cap label var RT_NELC "Non-electrified railway tracks"
cap label var MET "Metro/Underground lines"
cap label var IURB "Interurban and city line buses"
cap label var IMOD "Intermodal freight area (in square meters)"
cap label var AIRP "Airports"
cap label var AIRP_MAIN "Main airports"
cap label var AIRP_SML "Small airports"
cap label var AIRP_OTH "Other airports"
cap label var RWAY "Airport runways"
cap label var RWAY_M_GT2438 "Paved airport runways longer than 2 438 metres"
cap label var CKIN "Check-in facilities"
cap label var CKIN_CV "Check-in facilities - conventional desks"
cap label var CKIN_SELF "Check-in facilities - self service kiosks"
cap label var PAS_GATE "Passenger gates"
cap label var PAS_GATE_BB "Gates with passenger boarding bridges"
cap label var PAS_GATE_OTH "Other passenger gates"
cap label var PARK_CAR "Car parking places"
cap label var PARK_CAR_SH "Car parking places - short stay"
cap label var PARK_CAR_ML "Car parking places - medium and long stay"
cap label var UNK "Unknown"
