cap label var TOTAL "Total"
cap label var CHG_INCR_INC "Any change to increase income"
cap label var CHG_JOB "Change of job or employer"
cap label var LS_DTSK "Less demanding tasks in job"
cap label var FAM_LEAV "Family leave"
cap label var WRKINTR "Work interruption"
cap label var NWRKINTR "No work interruption"
cap label var RED_WRKTIME "Reduction of working time"
cap label var NWRKINTR_NRED_WRKTIME "No work interruption or reduction of working time"
cap label var NVR_WRK_CHCARE "Never worked for childcare reasons"
cap label var NVR_WRK_OTH "Never worked for other reasons"
cap label var NVR_CH "Never had children"
cap label var NVR_CARE "Never had care responsibilities"
cap label var OTH "Other"
cap label var NONE "No effects"
cap label var NAP "Not applicable"
cap label var NRP "No response"
