cap label var HOLD_HOLD "hold: Total number of holdings"
cap label var HOLDSL_HOLD "hold: Sole holder holdings"
cap label var HOLDLEG_GRP_HOLD "hold: Legal persons or group holdings"
cap label var AGRAREA_HA "ha: Utilised agricultural area"
cap label var AGRAREA_HOLD "hold with Utilised agricultural area"
cap label var B_1_HA "ha: Arable land"
cap label var B_1_HOLD "hold: Arable land"
cap label var B_1_1_HA "ha: Cereals"
cap label var B_1_1_HOLD "hold: Cereals"
cap label var B_1_1_1_HA "ha: Common wheat and spelt"
cap label var B_1_1_1_HOLD "hold: Common wheat and spelt"
cap label var B_1_1_2_HA "ha: Durum wheat"
cap label var B_1_1_2_HOLD "hold: Durum wheat"
cap label var B_1_1_3_HA "ha: Rye"
cap label var B_1_1_3_HOLD "hold: Rye"
cap label var B_1_1_4_HA "ha: Barley"
cap label var B_1_1_4_HOLD "hold: Barley"
cap label var B_1_1_5_HA "ha: Oats"
cap label var B_1_1_5_HOLD "hold: Oats"
cap label var B_1_1_6_HA "ha: Grain maize"
cap label var B_1_1_6_HOLD "hold: Grain maize"
cap label var B_1_1_7_HA "ha: Rice"
cap label var B_1_1_7_HOLD "hold: Rice"
cap label var B_1_1_99_HA "ha: Other cereals"
cap label var B_1_1_99_HOLD "hold: Other cereals"
cap label var B_1_2_HA "ha: Pulses - total"
cap label var B_1_2_HOLD "hold: Pulses - total"
cap label var B_1_345_HA "ha: Root crops"
cap label var B_1_345_HOLD "hold: Root crops"
cap label var B_1_3_HA "ha: Potatoes"
cap label var B_1_3_HOLD "hold: Potatoes"
cap label var B_1_4_HA "ha: Sugar beet"
cap label var B_1_4_HOLD "hold: Sugar beet"
cap label var B_3_99_HA "ha: Fodder crops and grass"
cap label var B_3_99_HOLD "hold: Fodder crops and grass"
cap label var B_1_5_HA "ha: Fodder roots and brassicas"
cap label var B_1_5_HOLD "hold: Fodder roots and brassicas"
cap label var B_1_6_HA "ha: Industrial crops - total"
cap label var B_1_6_HOLD "hold: Industrial crops - total"
cap label var B_1_6_1_HA "ha: Tobacco"
cap label var B_1_6_1_HOLD "hold: Tobacco"
cap label var B_1_6_2_HA "ha: Hops"
cap label var B_1_6_2_HOLD "hold: Hops"
cap label var B_1_6_3_HA "ha: Cotton"
cap label var B_1_6_3_HOLD "hold: Cotton"
cap label var B_1_6_4_HA "ha: Rape and turnip"
cap label var B_1_6_4_HOLD "hold: Rape and turnip"
cap label var B_1_6_5_HA "ha: Sunflower"
cap label var B_1_6_5_HOLD "hold: Sunflower"
cap label var B_1_6_6_HA "ha: Soya"
cap label var B_1_6_6_HOLD "hold: Soya"
cap label var B_1_6_7_11_HA "ha:  Other oil-seed or fibre crops"
cap label var B_1_6_7_11_HOLD "hold:  Other oil-seed or fibre crops"
cap label var B_1_6_12_HA "ha: Aromatic, medicinal and culinary plants"
cap label var B_1_6_12_HOLD "hold: Aromatic, medicinal and culinary plants"
cap label var B_1_6_99_HA "ha: Industrial crops not mentioned elsewhere"
cap label var B_1_6_99_HOLD "hold: Industrial crops not mentioned elsewhere"
cap label var B_4_7_7_2_8_2_HA "ha: Under glass:Vegetables, flowers and permanent crops"
cap label var B_4_7_7_2_8_2_HOLD "hold: Under glass:Vegetables, flowers and permanent crops"
cap label var B_1_7_HA "ha: Fresh vegetables, melons, strawberries"
cap label var B_1_7_HOLD "hold: Fresh vegetables, melons, strawberries"
cap label var B_1_7_1_HA "ha: Outdoor: Fresh vegetables, melons, strawberries"
cap label var B_1_7_1_HOLD "hold: Outdoor: Fresh vegetables, melons, strawberries"
cap label var B_1_7_1_1_HA "ha: Open field: Outdoor: Fresh vegetables, melons, strawberries"
cap label var B_1_7_1_1_HOLD "hold: Open field: Outdoor: Fresh vegetables, melons, strawberries"
cap label var B_1_7_1_2_HA "ha: Market gardening: Outdoor: Fresh vegetables, melons, strawberries"
cap label var B_1_7_1_2_HOLD "hold: Market gardening: Outdoor: Fresh vegetables, melons, strawberries"
cap label var B_1_7_2_HA "ha: Under glass: Fresh vegetables, melons, strawberries"
cap label var B_1_7_2_HOLD "hold: Under glass: Fresh vegetables, melons, strawberries"
cap label var B_1_8_HA "ha: Flowers and ornemental plants"
cap label var B_1_8_HOLD "hold: Flowers and ornemental plants"
cap label var B_1_8_1_HA "ha: Outdoor: Flowers and ornemental plants"
cap label var B_1_8_1_HOLD "hold: Outdoor: Flowers and ornemental plants"
cap label var B_1_8_2_HA "ha: Under glass: Flowers and ornemental plants"
cap label var B_1_8_2_HOLD "hold: Under glass: Flowers and ornemental plants"
cap label var B_1_9_HA "ha: Fodder crops - total"
cap label var B_1_9_HOLD "hold: Fodder crops - total"
cap label var B_1_9_1_HA "ha: Fodder crops - temporary grass"
cap label var B_1_9_1_HOLD "hold: Fodder crops - temporary grass"
cap label var B_1_9_2_HA "ha: Total: Other green fodder: Fodder crops"
cap label var B_1_9_2_HOLD "hold: Total: Other green fodder: Fodder crops"
cap label var B_1_9_2_1_HA "ha: Green maize: Other green fodder: Fodder crops"
cap label var B_1_9_2_1_HOLD "hold: Green maize: Other green fodder: Fodder crops"
cap label var B_1_9_2_2_HA "ha: Other fodder crops: leguminous plants: Fodder crops"
cap label var B_1_9_2_2_HOLD "hold: Other fodder crops: leguminous plants: Fodder crops"
cap label var B_1_9_2_99_HA "ha: Other green fodder - other than green maize and leguminous"
cap label var B_1_9_2_99_HOLD "hold: Other green fodder - other than green maize and leguminous"
cap label var B_1_10_11_HA "ha: Seeds, seedlings and other crops on arable land"
cap label var B_1_10_11_HOLD "hold: Seeds, seedlings and other crops on arable land"
cap label var B_1_10_HA "ha: Seeds and seedlings"
cap label var B_1_10_HOLD "hold: Seeds and seedlings"
cap label var B_1_11_HA "ha: Other crops on arable land"
cap label var B_1_11_HOLD "hold: Other crops on arable land"
cap label var B_1_12_HA "ha: Fallow land - total (with and w/o subsidies)"
cap label var B_1_12_HOLD "hold: Fallow land - total (with and w/o subsidies)"
cap label var B_2_HA "ha: Kitchen gardens"
cap label var B_2_HOLD "hold: Kitchen gardens"
cap label var B_3_HA "ha: Total: Permanent grassland and meadow"
cap label var B_3_HOLD "hold: Total: Permanent grassland and meadow"
cap label var B_3_1_HA "ha: Pasture and meadow: Permanent grassland and meadow"
cap label var B_3_1_HOLD "hold: Pasture and meadow: Permanent grassland and meadow"
cap label var B_3_2_HA "ha: Rough grazings: Permanent grassland and meadow"
cap label var B_3_2_HOLD "hold: Rough grazings: Permanent grassland and meadow"
cap label var B_3_3_HA "ha: Permanent grassland and meadow - not used for production, eligible for subsidies"
cap label var B_3_3_HOLD "hold: Permanent grassland and meadow - not used for production, eligible for subsidies"
cap label var B_4_HA "ha: Permanent crops"
cap label var B_4_HOLD "hold: Permanent crops"
cap label var B_4_1_HA "ha: Fruit and berry plantations - total"
cap label var B_4_1_HOLD "hold: Fruit and berry plantations - total"
cap label var B_4_1_1_HA "ha: Fruit species: Fruit and berry plantations"
cap label var B_4_1_1_HOLD "hold: Fruit species: Fruit and berry plantations"
cap label var B_4_1_1_1_HA "ha: Fruit species of temperate climate zones"
cap label var B_4_1_1_1_HOLD "hold: Fruit species of temperate climate zones"
cap label var B_4_1_1_2_HA "ha: Fruit species of subtropical climate zones"
cap label var B_4_1_1_2_HOLD "hold: Fruit species of subtropical climate zones"
cap label var B_4_1_2_HA "ha: Berry species : Fruit and berry plantations"
cap label var B_4_1_2_HOLD "hold: Berry species: Fruit and berry plantations"
cap label var B_4_1_99_1_HA "ha: Temperate climate: Fruit and berry plantations - until 2007"
cap label var B_4_1_99_1_HOLD "hold: Temperate climate: Fruit and berry plantations - until 2007"
cap label var B_4_1_99_2_HA "ha: Subtropical climate :Fruit and berry plantations - until 2007"
cap label var B_4_1_99_2_HOLD "hold: Subtropical climate: Fruit and berry plantations - until 2007"
cap label var B_4_1_3_HA "ha: Nuts: Fruit and berry plantations"
cap label var B_4_1_3_HOLD "hold:  Nuts: Fruit and berry plantations"
cap label var B_4_2_HA "ha: Citrus plantations"
cap label var B_4_2_HOLD "hold: Citrus plantations"
cap label var B_4_3_HA "ha: Olive plantations - total"
cap label var B_4_3_HOLD "hold: Olive plantations - total"
cap label var B_4_3_1_HA "ha: Olive plantations - table olives"
cap label var B_4_3_1_HOLD "hold: Olive plantations - table olives"
cap label var B_4_3_2_HA "ha: Olive plantations - oil production"
cap label var B_4_3_2_HOLD "hold: Olive plantations - oil production"
cap label var B_4_4_HA "ha: Vineyards - total"
cap label var B_4_4_HOLD "hold: Vineyards - total"
cap label var B_4_4_1_HA "ha: Vineyards - quality wine"
cap label var B_4_4_1_HOLD "hold: Vineyards - quality wine"
cap label var B_4_4_2_HA "ha: Vineyards - other wines"
cap label var B_4_4_2_HOLD "hold: Vineyards - other wines"
cap label var B_4_4_3_HA "ha: Vineyards - table grapes"
cap label var B_4_4_3_HOLD "hold: Vineyards - table grapes"
cap label var B_4_4_4_HA "ha: Vineyards - raisins"
cap label var B_4_4_4_HOLD "hold: Vineyards - raisins"
cap label var B_4_5_HA "ha: Nurseries"
cap label var B_4_5_HOLD "hold: Nurseries"
cap label var B_4_6_HA "ha: Other permanent crops"
cap label var B_4_6_HOLD "hold: Other permanent crops"
cap label var B_4_7_HA "ha: Permanent crops under glass"
cap label var B_4_7_HOLD "hold: Permanent crops under glass"
cap label var B_5_HA "ha: Other land - Total"
cap label var B_5_HOLD "hold: Other land - Total"
cap label var B_5_1_5_3_HA "ha: Unutilised agricultural land and other areas"
cap label var B_5_1_5_3_HOLD "hold: Unutilised agricultural land and other areas"
cap label var B_5_1_HA "ha: Unutilised agricultural land"
cap label var B_5_1_HOLD "hold: Unutilised agricultural land"
cap label var B_5_2_HA "ha: Wooded area"
cap label var B_5_2_HOLD "hold: Wooded area"
cap label var B_5_2_1_HA "ha: Wooded area - with short rotation"
cap label var B_5_2_1_HOLD "hold: Wooded area - with short rotation"
cap label var B_5_3_HA "ha: Other land"
cap label var B_5_3_HOLD "hold: Other land"
cap label var B_6_1_HA "ha: Mushrooms"
cap label var B_6_1_HOLD "hold: Mushrooms"
cap label var B_6_3_HA "ha: Energy crops"
cap label var B_6_3_HOLD "hold: Energy crops"
cap label var B_6_3_1_HA "ha: Energy crops on set-aside area"
cap label var B_6_3_1_HOLD "hold: Energy crops on set-aside area"
cap label var B_6_4_HA "ha: Genetically modified crops"
cap label var B_6_4_HOLD "hold: Genetically modified crops"
cap label var B_6_2_1_HA "ha: Total irrigable area"
cap label var B_6_2_1_HOLD "hold: Total irrigable area"
cap label var B_6_2_2_HA "ha: Irrigated at least once a year : Total (excl. kitchen gardens and area under glass)"
cap label var B_6_2_2_HOLD "hold with area irrigated at least once a year: Total (excl. kitchen gardens and area under glass)"
cap label var B_6_2_2_99_HOLD "hold with area irrigated at least once a year: Total (incl. kitchen gardens and area under glass)"
cap label var C_LIVESTOCK_HOLD "hold: Number of holdings with livestock"
cap label var C_LIVESTOCK_LSU "LSU of the holdings with livestock"
cap label var C_1_HEADS "head: Equidae"
cap label var C_1_HOLD "hold: Equidae"
cap label var C_2_HEADS "head: Cattle - total"
cap label var C_2_HOLD "hold: Cattle - total"
cap label var C_2_1_HEADS "head: Bovine <1 year old - total"
cap label var C_2_1_HOLD "hold: Bovine <1 year old - total"
cap label var C_2_2_HEADS "head: Bovine 1-<2 years - males"
cap label var C_2_2_HOLD "hold: Bovine 1-<2 years - males"
cap label var C_2_3_HEADS "head: Bovine 1-<2 years - females"
cap label var C_2_3_HOLD "hold: Bovine 1-<2 years - females"
cap label var C_2_4_HEADS "head: Bovine 2 years and older - males"
cap label var C_2_4_HOLD "hold: Bovine 2 years and older - males"
cap label var C_2_5_HEADS "head: Heifers, 2 years and older"
cap label var C_2_5_HOLD "hold: Heifers, 2 years and older"
cap label var C_2_6_HEADS "head: Dairy cows"
cap label var C_2_6_HOLD "hold: Dairy cows"
cap label var C_2_99_HEADS "head: Other cows, bovine 2 years old and over"
cap label var C_2_99_HOLD "hold: Other cows, bovine 2 years old and over"
cap label var C_3_1_HEADS "head: Sheep - total"
cap label var C_3_1_HOLD "hold: Sheep - total"
cap label var C_3_1_1_HEADS "head: Sheep - breeding females"
cap label var C_3_1_1_HOLD "hold: Sheep - breeding females"
cap label var C_3_1_99_HEADS "head: Sheep - others"
cap label var C_3_1_99_HOLD "hold: Sheep - others"
cap label var C_3_2_HEADS "head: Goats"
cap label var C_3_2_HOLD "hold: Goats"
cap label var C_3_2_1_HEADS "head: Goats - breeding females"
cap label var C_3_2_1_HOLD "hold: Goats - breeding females"
cap label var C_3_2_99_HEADS "head: Goats - others"
cap label var C_3_2_99_HOLD "hold: Goats - others"
cap label var C_4_HEADS "head: Pigs"
cap label var C_4_HOLD "hold: Pigs"
cap label var C_4_1_HEADS "head: Pigs - piglets under 20 kg"
cap label var C_4_1_HOLD "hold: Pigs - piglets under 20 kg"
cap label var C_4_2_HEADS "head: Pigs - breeding sows over 50 kg"
cap label var C_4_2_HOLD "hold: Pigs - breeding sows over 50 kg"
cap label var C_4_99_HEADS "head: Pigs - others"
cap label var C_4_99_HOLD "hold: Pigs - others"
cap label var C_5_1000_HEADS "1000 heads: Poultry"
cap label var C_5_HOLD "hold: Poultry"
cap label var C_5_1_1000_HEADS "1000 heads: Poultry - broilers"
cap label var C_5_1_HOLD "hold: Poultry - broilers"
cap label var C_5_2_1000_HEADS "1000 heads: Laying hens"
cap label var C_5_2_HOLD "hold: Laying hens"
cap label var C_5_3_1000_HEADS "1000 heads: Poultry - others"
cap label var C_5_3_HOLD "hold: Poultry - others"
cap label var C_6_HEADS "head: Rabbits (breeding females)"
cap label var C_6_HOLD "hold: Rabbits (breeding females)"
cap label var C_7_HIVE "Nb: Beehives"
cap label var C_7_HOLD "hold: Beehives"
cap label var C_99_EQ_Y_HOLD "Holdings with other livestock"
cap label var A_3_2_1_HOLD "hold:Organic farming - certified"
cap label var A_3_2_1_HA "ha:Organic farming - certified"
cap label var A_3_2_2_HOLD "hold:Farming system - Conversion to organic farming"
cap label var A_3_2_2_HA "ha:Farming system - Conversion to organic farming"
cap label var A_3_2_3_HOLD "hold:Organic farming (incl. in conversion)"
cap label var A_3_2_3_HA "ha:Organic farming (incl. in conversion)"
cap label var A_3_2_3_1_HOLD "hold:Organic farming - cereals"
cap label var A_3_2_3_1_HA "ha:Organic farming - cereals"
cap label var A_3_2_3_2_HOLD "hold:Organic farming - dried pulses"
cap label var A_3_2_3_2_HA "ha:Organic farming - dried pulses"
cap label var A_3_2_3_3_HOLD "hold:Organic farming - potatoes"
cap label var A_3_2_3_3_HA "ha:Organic farming - potatoes"
cap label var A_3_2_3_4_HOLD "hold:Organic farming - sugar beet"
cap label var A_3_2_3_4_HA "ha:Organic farming - sugar beet"
cap label var A_3_2_3_5_HOLD "hold:Organic farming - oil seed crops"
cap label var A_3_2_3_5_HA "ha:Organic farming - oil crops"
cap label var A_3_2_3_6_HOLD "hold:Organic farming - fresh vegetables, melons, strawberries"
cap label var A_3_2_3_6_HA "ha:Organic farming - fresh vegetables, melons, strawberries"
cap label var A_3_2_3_7_HOLD "hold:Organic farming - pasture and meadow, excl. rough grazings"
cap label var A_3_2_3_7_HA "ha:Organic farming - pasture and meadow, excl. rough grazings"
cap label var A_3_2_3_8_HOLD "hold:Organic farming - fruit and berry"
cap label var A_3_2_3_8_HA "ha:Organic farming - fruit and berry"
cap label var A_3_2_3_9_HOLD "hold:Organic farming - citrus fruit"
cap label var A_3_2_3_9_HA "ha:Organic farming - citrus fruit"
cap label var A_3_2_3_10_HOLD "hold:Organic farming - olives"
cap label var A_3_2_3_10_HA "ha:Organic farming - olives"
cap label var A_3_2_3_11_HOLD "hold:Organic farming - vineyards"
cap label var A_3_2_3_11_HA "ha:Organic farming - vineyards"
cap label var A_3_2_3_99_HOLD "hold:Organic farming - other crops"
cap label var A_3_2_3_99_HA "ha:Organic farming - other crops"
cap label var A_3_2_4_1_HOLD "hold: Organic farming - bovine animals"
cap label var A_3_2_4_1_HEADS "head:Organic farming - bovine animals"
cap label var A_3_2_4_2_HOLD "hold: Organic farming - pigs"
cap label var A_3_2_4_2_HEADS "head:Organic farming - pigs"
cap label var A_3_2_4_3_HOLD "hold: Organic farming - sheep and goats"
cap label var A_3_2_4_3_HEADS "head:Organic farming - sheep and goats"
cap label var A_3_2_4_4_HOLD "hold: Organic farming - poultry"
cap label var A_3_2_4_4_HEADS "head:Organic farming - poultry"
cap label var A_3_2_4_5_EQ_Y_HOLD "hold: Organic farming - with other animals"
cap label var E_1_2_4B_EQ_Y_HOLD "Hold. with vocational training by manager in last 12 months"
cap label var M_8_1_1_HA "ha: Average area irrigated in the last 3 years"
cap label var M_8_1_1_HOLD "hold: Average area irrigated in the last 3 years"
cap label var M_8_1_2_1_HA "ha: Area irrigated in the previous 12 months: cereals (excl. maize and rice)"
cap label var M_8_1_2_1_HOLD "hold: Area irrigated in the previous 12 months: cereals (excl. maize and rice)"
cap label var M_8_1_2_2_HA "ha: Area irrigated in the previous 12 months: maize (grain and green)"
cap label var M_8_1_2_2_HOLD "hold: Area irrigated in the previous 12 months: maize (grain and green)"
cap label var M_8_1_2_3_HA "ha: Area irrigated in the previous 12 months: rice"
cap label var M_8_1_2_3_HOLD "hold: Area irrigated in the previous 12 months: rice"
cap label var M_8_1_2_4_HA "ha: Area irrigated in the previous 12 months: pulses"
cap label var M_8_1_2_4_HOLD "hold: Area irrigated in the previous 12 months: pulses"
cap label var M_8_1_2_5_HA "ha: Area irrigated in the previous 12 months: potatoes"
cap label var M_8_1_2_5_HOLD "hold: Area irrigated in the previous 12 months: potatoes"
cap label var M_8_1_2_6_HA "ha: Area irrigated in the previous 12 months: sugar beet"
cap label var M_8_1_2_6_HOLD "hold: Area irrigated in the previous 12 months: sugar beet"
cap label var M_8_1_2_7_HA "ha: Area irrigated in the previous 12 months: rape and turnip rape"
cap label var M_8_1_2_7_HOLD "hold: Area irrigated in the previous 12 months: rape and turnip rape"
cap label var M_8_1_2_8_HA "ha: Area irrigated in the previous 12 months: sunflower"
cap label var M_8_1_2_8_HOLD "hold: Area irrigated in the previous 12 months: sunflower"
cap label var M_8_1_2_9_HA "ha: Area irrigated in the previous 12 months: textile crops"
cap label var M_8_1_2_9_HOLD "hold: Area irrigated in the previous 12 months: textile crops"
cap label var M_8_1_2_10_HA "ha: Area irrigated in the previous 12 months: Fresh vegetables, melons, strawberries - open field"
cap label var M_8_1_2_10_HOLD "hold: Area irrigated in the previous 12 months: Fresh vegetables, melons, strawberries - open field"
cap label var M_8_1_2_11_HA "ha: Area irrigated in the previous 12 months: Temporary and permanent grass grass"
cap label var M_8_1_2_11_HOLD "hold: Area irrigated in the previous 12 months: Temporary and permanent grass grass"
cap label var M_8_1_2_12_HA "ha: Area irrigated in the previous 12 months: other crops on arable land"
cap label var M_8_1_2_12_HOLD "hold: Area irrigated in the previous 12 months: other crops on arable land"
cap label var M_8_1_2_13_HA "ha: Area irrigated in the previous 12 months: fruit and berry plantations"
cap label var M_8_1_2_13_HOLD "hold: Area irrigated in the previous 12 months: fruit and berry plantations"
cap label var M_8_1_2_14_HA "ha: Area irrigated in the previous 12 months: citrus plantations"
cap label var M_8_1_2_14_HOLD "hold: Area irrigated in the previous 12 months: citrus plantations"
cap label var M_8_1_2_15_HA "ha: Area irrigated in the previous 12 months: olive plantations"
cap label var M_8_1_2_15_HOLD "hold: Area irrigated in the previous 12 months: olive plantations"
cap label var M_8_1_2_16_HA "ha: Area irrigated in the previous 12 months: vineyards"
cap label var M_8_1_2_16_HOLD "hold: Area irrigated in the previous 12 months: vineyards"
cap label var M_8_2_1_EQ_Y_HOLD "hold: Holdings with: Irrigation method: Surface irrigation"
cap label var M_8_2_2_EQ_Y_HOLD "hold: Holdings with: Irrigation method: Sprinkler irrigation"
cap label var M_8_2_3_EQ_Y_HOLD "hold: Holdings with: Irrigation method: Drop irrigation"
cap label var M_8_3_1_EQ_Y_HOLD "hold: Holdings with: Source of water: on-farm ground water"
cap label var M_8_3_2_EQ_Y_HOLD "hold: Holdings with: Source of water: on-farm surface water"
cap label var M_8_3_3_EQ_Y_HOLD "hold: Holdings with: Source of water: off-farm surface water"
cap label var M_8_3_4_EQ_Y_HOLD "hold: Holdings with: Source of water: off-farm water from water supply networks"
cap label var M_8_3_99_EQ_Y_HOLD "hold: Holdings with: Source of water: other sources"
cap label var M_8_4_M3 "Volume of water used for irrigation per year - in m3"
cap label var LFH_W_PERS "pers: Sole holders working on the farm"
cap label var LFH_W_F_PERS "pers: Female: Sole holders working on the farm"
cap label var LFH_W_M_PERS "pers: Male: Sole holders working on the farm"
cap label var LFRMF_PERS "pers: Labour force - members of sole holders' family"
cap label var LFRMF_M_PERS "pers: Male: Labour force: members of sole holders' family"
cap label var LFRMF_F_PERS "pers: Female: Labour force: members of sole holders' family"
cap label var LFRF_PERS "pers: Family labour force"
cap label var LFRF_M_PERS "pers: Male: Family labour force"
cap label var LFRF_F_PERS "pers: Female: Family labour force"
cap label var LFRNF_PERS "pers: Regular non family labour force"
cap label var LFRNF_M_PERS "pers: Male: Regular non family labour force"
cap label var LFRNF_F_PERS "pers: Female: Regular non family labour force"
cap label var LFR_PERS "pers: Regular Labour force"
cap label var LFR_M_PERS "pers: Male: Regular labour force"
cap label var LFR_F_PERS "pers: Female: Regular labour force"
cap label var LFH_AWU "AWU: Sole holders"
cap label var LFH_W_F_AWU "AWU: Female: Sole holders working on the farm"
cap label var LFH_W_M_AWU "AWU: Male: Sole holders working on the farm"
cap label var LFRMF_AWU "AWU: Labour force : members of sole holders' family"
cap label var LFRMF_M_AWU "AWU: Male: Labour force: members of sole holders' family - calculated"
cap label var LFRMF_F_AWU "AWU: Female: Labour force: members of sole holders' family-calculated"
cap label var LFRF_AWU "AWU: Family labour force"
cap label var LFRF_M_AWU "AWU: Male: Family labour force"
cap label var LFRF_F_AWU "AWU: Females: Family labour force"
cap label var LFRNF_AWU "AWU: Regular non family labour force"
cap label var LFRNF_M_AWU "AWU: Male: Regular non family labour force"
cap label var LFRNF_F_AWU "AWU: Female: Regular non family labour force"
cap label var LFR_AWU "AWU: Regular Labour force"
cap label var LFR_M_AWU "AWU: Male: Regular labour force"
cap label var LFR_F_AWU "AWU: Female: Regular labour force"
cap label var LFNRNF_AWU "AWU: Non-family labour force working on non-regular basis"
cap label var LFD_AWU "AWU: Total: Labour force directly employed by the holding"
cap label var LFND_AWU "AWU: Labour force  not directly employed by the holding"
cap label var SO_EURO "Euro: Standard output (SO)"
cap label var A_3_1_1_HA "ha: Farming by owner: Agricultural area"
cap label var A_3_1_1_HOLD "hold: Farming by owner: Agricultural area"
cap label var A_3_1_2_HA "ha: Farming by tenant: Agricultural area"
cap label var A_3_1_2_HOLD "hold: Farming by tenant: Agricultural area"
cap label var A_3_1_3_HA "ha: Shared farming or other modes: Agricultural area"
cap label var A_3_1_3_HOLD "hold: Shared farming or other modes: Agricultural area"
cap label var TOTAREA_HA "ha: Total area"
cap label var TOTAREA_HOLD "hold: Total area"
cap label var A_3_3_1_EQ_Y_HOLD "hold: More than 50% of producion self-consumed by the holder"
cap label var D_2_1_1_Y_HOLD "Holdings with equipment for energy production: wind"
cap label var D_2_1_1_Y_HA "ha: UAA of holdings with equipment for energy production: wind"
cap label var D_2_1_2_Y_HOLD "Holdings with equipment for energy production: biomass"
cap label var D_2_1_2_Y_HA "ha: UAA of holdings with equipment for energy production: biomass"
cap label var D_2_1_2_1_Y_HOLD "Holdings with equipment for energy production: bio- methane from biomass"
cap label var D_2_1_2_1_Y_HA "ha: UAA of holdings with equipment for energy production: bio- methane from biomass"
cap label var D_2_1_3_Y_HOLD "Holdings with equipment for energy production: solar energy"
cap label var D_2_1_3_Y_HA "ha: UAA of holdings with equipment for energy production: solar energy"
cap label var D_2_1_4_Y_HOLD "Holdings with equipment for energy production: hydro- energy"
cap label var D_2_1_4_Y_HA "ha: UAA of holdings with equipment for energy production: hydro- energy"
cap label var D_2_1_99_Y_HOLD "Holdings with equipment for energy production: other sources"
cap label var D_2_1_99_Y_HA "ha: UAA of holdings with equipment for energy production: other sources"
cap label var OGA_H_D_Y_HOLD "hold. with OGA of the sole holder-manager related directly to the holding"
cap label var OGA_H_N_Y_HOLD "hold. with OGA of the sole holder-manager not related directly to the holding"
cap label var OGA_S_D_Y_HOLD "hold. with OGA of the spouse of the sole holder-manager related directly to the holding"
cap label var OGA_S_N_Y_HOLD "hold. with OGA of the spouse of the sole holder-manager not related directly to the holding"
cap label var OGA_F_M_PERS "pers: other family members of sole holder with major OGA"
cap label var OGA_F_M_HOLD "hold: other family members of sole holder with major OGA"
cap label var OGA_F_S_PERS "pers: other family members of sole holder with subsidiary OGA"
cap label var OGA_F_S_HOLD "hold: other family members of sole holder with subsidiary OGA"
cap label var OGA_F_D_PERS "pers: other family members of sole holder with OGA related to the holding"
cap label var OGA_F_D_HOLD "hold: other family members of sole holder with OGA related to the holding"
cap label var OGA_F_N_PERS "pers:other family members of sole holder with OGA not related to the holding"
cap label var OGA_F_N_HOLD "hold:other family members of sole holder with OGA not related to the holding"
cap label var OGA_N_D_M_PERS "pers:non-family workers with major OGA related to the holding"
cap label var OGA_N_D_M_HOLD "hold: non-family workers with major OGA related to the holding"
cap label var OGA_N_D_S_PERS "pers:non-family workers with subsidiary OGA related to the holding"
cap label var OGA_N_D_S_HOLD "hold:non-family workers with subsidiary OGA related to the holding"
cap label var OGA_F_1_Y_HOLD "Holdings with OGA"
cap label var OGA_F_1_Y_HA "ha: UAA of hold. with OGA"
cap label var OGA_F_1_Y_EUR "Euro: SO of hold. with OGA"
cap label var OGA_F_1_Y_LSU "LSU of hold. with OGA"
cap label var OGA_F_1_1_Y_HOLD "hold:Tourism as OGA"
cap label var OGA_F_1_1_Y_HA "ha: UAA of hold. with tourism as OGA"
cap label var OGA_F_1_1_Y_EUR "Euro: SO of hold. with tourism as OGA"
cap label var OGA_F_1_1_Y_LSU "LSU of hold. with tourism as OGA"
cap label var OGA_F_1_2_Y_HOLD "hold: Handicraft as OGA"
cap label var OGA_F_1_2_Y_HA "ha: UAA of hold. with handcraft as OGA"
cap label var OGA_F_1_2_Y_EUR "Euro: SO of hold. with handcraft as OGA"
cap label var OGA_F_1_2_Y_LSU "LSU of hold. with handcraft as OGA"
cap label var OGA_F_1_3_Y_HOLD "hold:Processing of farm products as OGA"
cap label var OGA_F_1_3_Y_HA "ha: UAA of hold with processing of farm products as OGA"
cap label var OGA_F_1_3_Y_EUR "Euro: SO of hold with processing of farm products as OGA"
cap label var OGA_F_1_3_Y_LSU "LSU of hold with processing of farm products as OGA"
cap label var OGA_F_1_4_Y_HOLD "hold:Renewable energy production as OGA"
cap label var OGA_F_1_4_Y_HA "ha: UAA of hold. with renewable energy production as OGA"
cap label var OGA_F_1_4_Y_EUR "Euro: SO of hold. with renewable energy production as OGA"
cap label var OGA_F_1_4_Y_LSU "LSU of hold. with renewable energy production as OGA"
cap label var OGA_F_1_5_Y_HOLD "hold: Wood processing as OGA"
cap label var OGA_F_1_5_Y_HA "ha: UAA of hold. with wood processing as OGA"
cap label var OGA_F_1_5_Y_EUR "Euro: SO of hold. with wood processing as OGA"
cap label var OGA_F_1_5_Y_LSU "LSU of hold. with wood processing as OGA"
cap label var OGA_F_1_6_Y_HOLD "hold: Aquaculture as OGA"
cap label var OGA_F_1_6_Y_HA "ha: UAA of hold. with aquaculture as OGA"
cap label var OGA_F_1_6_Y_EUR "Euro: SO of hold. with aquaculture as OGA"
cap label var OGA_F_1_6_Y_LSU "LSU of hold. with aquaculture as OGA"
cap label var OGA_F_1_7_Y_HOLD "hold: Contractual work as OGA"
cap label var OGA_F_1_7_Y_HA "ha: UAA of hold. with contractual work as OGA"
cap label var OGA_F_1_7_Y_EUR "Euro: SO of hold. with contractual work as OGA"
cap label var OGA_F_1_7_Y_LSU "LSU of hold. with contractual work as OGA"
cap label var OGA_F_1_7_1_Y_HOLD "hold:Contractual agricultural work as OGA"
cap label var OGA_F_1_7_1_Y_HA "ha: UAA of hold. with contractual agricultural work as OGA"
cap label var OGA_F_1_7_1_Y_EUR "Euro: SO of hold. with contractual agricultural work as OGA"
cap label var OGA_F_1_7_1_Y_LSU "LSU of hold. with contractual agricultural work as OGA"
cap label var OGA_F_1_7_2_Y_HOLD "hold:Contractual non-agricultural work as OGA"
cap label var OGA_F_1_7_2_Y_HA "ha: UAA of hold. with contractual non-agricultural work as OGA"
cap label var OGA_F_1_7_2_Y_EUR "Euro:SO of hold. with contractual non-agricultural work as OGA"
cap label var OGA_F_1_7_2_Y_LSU "LSU of hold. with contractual non-agricultural work as OGA"
cap label var OGA_F_1_8_Y_HOLD "hold: Forestry-work as OGA"
cap label var OGA_F_1_8_Y_HA "ha: UAA of hold. with forestry-work as OGA"
cap label var OGA_F_1_8_Y_EUR "Euro: SO of hold. with forestry-work as OGA"
cap label var OGA_F_1_8_Y_LSU "LSU of hold. with forestry-work as OGA"
cap label var OGA_F_1_99_Y_HOLD "hold: OGA not mentioned elsewhere"
cap label var OGA_F_1_99_Y_HA "ha: UAA of hold. with OGA n.m.e."
cap label var OGA_F_1_99_Y_EUR "Euro: SO of hold. with OGA n.m.e."
cap label var OGA_F_1_99_Y_LSU "LSU of hold. with OGA n.m.e."
cap label var OGA_F_2_1_0_HOLD "Holdings with up to 10% of turnover coming from OGA"
cap label var OGA_F_2_1_0_HA "ha: UAA of hold. with up to 10% of turnover coming from OGA"
cap label var OGA_F_2_1_0_EUR "Euro: SO of hold. with up to 10% of turnover coming from OGA"
cap label var OGA_F_2_1_0_LSU "LSU of hold. with up to 10% of turnover coming from OGA"
cap label var OGA_F_2_1_11_HOLD "Holdings with 10% to 50% of turnover coming from OGA"
cap label var OGA_F_2_1_11_HA "ha: UAA of hold. with 10% to 50% of turnover coming from OGA"
cap label var OGA_F_2_1_11_EUR "Euro: SO of hold. with 10% to 50% of turnover coming from OGA"
cap label var OGA_F_2_1_11_LSU "LSU: of hold. with 10% to 50% of turnover coming from OGA"
cap label var OGA_F_2_1_51_HOLD "Holdings with more than 50% of turnover coming from OGA"
cap label var OGA_F_2_1_51_HA "ha: UAA of hold. with more than 50% of turnover coming from OGA"
cap label var OGA_F_2_1_51_EUR "Euro: SO of hold. with more than 50% of turnover coming from OGA"
cap label var OGA_F_2_1_51_LSU "LSU of hold. with more than 50% of turnover coming from OGA"
cap label var RD_G_1_Y_HOLD "holdings benefiting from listed measures of rural development support"
cap label var RD_G_1_Y_HA "ha: UAA of hold. benefiting from listed measures of rural development support"
cap label var RD_G_1_Y_EUR "Euro: SO of hold. benefiting from listed measures of rural development support"
cap label var RD_G_1_Y_LSU "LSU of of hold. benefiting from listed measures of rural development support"
cap label var RD_G_1_1_Y_HOLD "holdings benefiting advisory services (Rural development support)"
cap label var RD_G_1_1_Y_HA "ha: UAA of hold. benefiting advisory services (Rural development support)"
cap label var RD_G_1_1_Y_EUR "Euro: SO of hold. benefiting advisory services (Rural development support)"
cap label var RD_G_1_1_Y_LSU "LSU of hold. benefiting advisory services (Rural development support)"
cap label var RD_G_1_2_Y_HOLD "holdings benefiting measures for modernisation (Rural development support)"
cap label var RD_G_1_2_Y_HA "ha: UAA of hold. benefiting measures for modernisation (Rural development support)"
cap label var RD_G_1_2_Y_EUR "Euro: SO of hold. benefiting measures for modernisation (Rural development support)"
cap label var RD_G_1_2_Y_LSU "LSU of hold. benefiting measures for modernisation (Rural development support)"
cap label var RD_G_1_3_Y_HOLD "holdings benefiting measures adding value to products (Rural development support)"
cap label var RD_G_1_3_Y_HA "ha: UAA of hold. benefiting measures adding value to products (Rural development support)"
cap label var RD_G_1_3_Y_EUR "Euro:SO of hold. benefiting measures adding value to products (Rural development support)"
cap label var RD_G_1_3_Y_LSU "LSU of hold. benefiting measures adding value to products (Rural development support)"
cap label var RD_G_1_4_Y_HOLD "holdings benefiting measures Community standards (Rural development support)"
cap label var RD_G_1_4_Y_HA "ha: UAA of hold. benefiting measures Community standards (Rural development support)"
cap label var RD_G_1_4_Y_EUR "Euro: SO of hold. benefiting measures Community standards (Rural development support)"
cap label var RD_G_1_4_Y_LSU "LSU of hold. benefiting measures Community standards (Rural development support)"
cap label var RD_G_1_5_Y_HOLD "holdings benefiting measures Food quality scheme (Rural development support)"
cap label var RD_G_1_5_Y_HA "ha: UAA of hold. benefiting measures Food quality scheme (Rural development support)"
cap label var RD_G_1_5_Y_EUR "Euro: SO of hold. benefiting measures Food quality scheme (Rural development support)"
cap label var RD_G_1_5_Y_LSU "LSU of hold. benefiting measures Food quality scheme (Rural development support)"
cap label var RD_G_1_6_Y_HOLD "holdings benefiting measures Natura 2000 payments (Rural development support)"
cap label var RD_G_1_6_Y_HA "ha: UAA of hold. benefiting measures Natura 2000 payments (Rural development support)"
cap label var RD_G_1_6_Y_EUR "Euro: SO of hold. benefiting measures Natura 2000 payments (Rural development support)"
cap label var RD_G_1_6_Y_LSU "LSU of hold. benefiting measures Natura 2000 payments (Rural development support)"
cap label var RD_G_1_7_Y_HOLD "holdings benefiting measures for payments under Water Framework Directive (Rural development support)"
cap label var RD_G_1_7_Y_HA "ha: UAA of hold. benefiting measures for payments under Water Framework Directive (Rural development support)"
cap label var RD_G_1_7_Y_EUR "Euro: SO of hold. benefiting measures for payments under Water Framework Directive (Rural development support)"
cap label var RD_G_1_7_Y_LSU "LSU of hold. benefiting measures for payments under Water Framework Directive (Rural development support)"
cap label var RD_G_1_8_Y_HOLD "holdings benefiting measures for Agri-environment payments (Rural development support)"
cap label var RD_G_1_8_Y_HA "ha: UAA of hold. benefiting measures for Agri-environment payments (Rural development support)"
cap label var RD_G_1_8_Y_EUR "Euro: SO of hold. benefiting measures for Agri-environment payments (Rural development support)"
cap label var RD_G_1_8_Y_LSU "LSU of hold. benefiting measures for Agri-environment payments (Rural development support)"
cap label var RD_G_1_8_1_Y_HOLD "holdings benefiting measures for Agri-environment payments for organic farming (Rural development support)"
cap label var RD_G_1_8_1_Y_HA "ha: UAA of hold. benefiting measures for Agri-environment payments for organic farming (Rural development support)"
cap label var RD_G_1_8_1_Y_EUR "Euro: SO of hold. benefiting measures for Agri-environment payments for organic farming (Rural development support)"
cap label var RD_G_1_8_1_Y_LSU "LSU of hold. benefiting measures for Agri-environment payments for organic farming (Rural development support)"
cap label var RD_G_1_9_Y_HOLD "holdings benefiting measures for Animal welfare payments (Rural development support)"
cap label var RD_G_1_9_Y_HA "ha: UAA of hold. benefiting measures for Animal welfare payments (Rural development support)"
cap label var RD_G_1_9_Y_EUR "Euro: SO of hold. benefiting measures for Animal welfare payments (Rural development support)"
cap label var RD_G_1_9_Y_LSU "LSU of hold. benefiting measures for Animal welfare payments (Rural development support)"
cap label var RD_G_1_10_Y_HOLD "holdings benefiting measures for Diversification into non-agricultural activities (Rural development support)"
cap label var RD_G_1_10_Y_HA "ha: UAA of hold. benefiting measures for Diversification into non-agricultural activities (Rural development support)"
cap label var RD_G_1_10_Y_EUR "Euro: SO of hold. benefiting measures for Diversification into non-agricultural activities (Rural development support)"
cap label var RD_G_1_10_Y_LSU "LSU of hold. benefiting measures for Diversification into non-agricultural activities (Rural development support)"
cap label var RD_G_1_11_Y_HOLD "holdings benefiting measures for Encouragement of tourism activities (Rural development support)"
cap label var RD_G_1_11_Y_HA "ha: UAA of hold. benefiting measures for Encouragement of tourism activities (Rural development support)"
cap label var RD_G_1_11_Y_EUR "Euro: SO of hold. benefiting measures for Encouragement of tourism activities (Rural development support)"
cap label var RD_G_1_11_Y_LSU "LSU of hold. benefiting measures for Encouragement of tourism activities (Rural development support)"
cap label var D_1_1_A "Four-wheel tractors, track-laying tractors, tool carriers belonging exclusively to the holding"
cap label var D_1_1_B "Cultivators etc. belonging exclusively to the holding"
cap label var D_1_1_C "Combine harvesters belonging exclusively to the holding"
cap label var D_1_1_D "Other fully mechanised harvesters belonging exclusively to the holding"
cap label var D_1_2_A_EQ_Y "Use in the last 12 months of four-wheel tractors etc. used by several holdings"
cap label var D_1_2_B_EQ_Y "Use in the last 12 months of cultivators etc. used by several holdings"
cap label var D_1_2_C_EQ_Y "Use in the last 12 months of combine harvesters used by several holdings"
cap label var D_1_2_D_EQ_Y "Use in the last 12 months of other fully mechanised harvesters used by several holdings"
