cap label var TOTAL "Total"
cap label var RES "Residential buildings"
cap label var RES1 "One-dwelling residential buildings"
cap label var RES2 "Two-dwelling residential buildings"
cap label var RES_GE3 "Three or more dwelling residential buildings"
cap label var HOUSE "House"
cap label var HOUSE_ND "Non-detached house"
cap label var HOUSE_D "Detached house"
cap label var HOUSE_SD "Semi-detached house"
cap label var FLAT "Flat"
cap label var FLAT_LT10 "Flat in a building with less than ten dwellings"
cap label var FLAT_GE10 "Flat in a building with ten or more dwellings"
cap label var FLAT3 "3-bedroom flats"
cap label var FLAT2 "2-bedroom flats"
cap label var FLAT1 "1-bedroom flats"
cap label var NRES "Non-residential buildings"
cap label var OTH "Others"
cap label var UNK "Unknown"
