cap label var TOTAL "Total"
cap label var CONT_ORD "Content and order of tasks"
cap label var CONT "Content of tasks"
cap label var ORD "Order of tasks"
cap label var SOMECONT_SOMEORD "Some or large on content and order of tasks"
cap label var LTLCONT_SOMEORD "Little or none on content and some or large on order of tasks"
cap label var SOMECONT_LTLORD "Some or large on content and little or none on order of tasks"
cap label var LTLCONT_LTLORD "Little or none on content and order of tasks"
cap label var NONE "None"
cap label var NAP "Not applicable"
cap label var NRP "No response"
