cap label var b "break in time series"
cap label var bc "break in time series, confidential"
cap label var bcd "break in time series, confidential, definition differs (see metadata)"
cap label var bd "break in time series, definition differs (see metadata)"
cap label var bde "break in time series, definition differs (see metadata), estimated"
cap label var bdep "break in time series, definition differs (see metadata), estimated, provisional"
cap label var bder "break in time series, definition differs (see metadata), estimated, revised"
cap label var bdf "break in time series, definition differs (see metadata), forecast"
cap label var bdn "break in time series, definition differs (see metadata), not significant"
cap label var bdp "break in time series, definition differs (see metadata), provisional"
cap label var bdps "break in time series, definition differs (see metadata), provisional, Eurostat estimate"
cap label var bdr "break in time series, definition differs (see metadata), revised"
cap label var bdrs "break in time series, definition differs (see metadata), revised, Eurostat estimate"
cap label var bds "break in time series, definition differs (see metadata), Eurostat estimate"
cap label var bdu "break in time series, definition differs (see metadata), low reliability"
cap label var bdz "break in time series, definition differs (see metadata), not applicable"
cap label var be "break in time series, estimated"
cap label var bep "break in time series, estimated, provisional"
cap label var ber "break in time series, estimated, revised"
cap label var bf "break in time series, forecast"
cap label var bn "break in time series, not significant"
cap label var bp "break in time series, provisional"
cap label var bps "break in time series, provisional, Eurostat estimate"
cap label var bpu "break in time series, provisional, low reliability"
cap label var br "break in time series, revised"
cap label var brs "break in time series, revised, Eurostat estimate"
cap label var bs "break in time series, Eurostat estimate"
cap label var bu "break in time series, low reliability"
cap label var bz "break in time series, not applicable"
cap label var c "confidential"
cap label var cd "confidential, definition differs (see metadata)"
cap label var d "definition differs (see metadata)"
cap label var de "definition differs (see metadata), estimated"
cap label var dep "definition differs (see metadata), estimated, provisional"
cap label var der "definition differs (see metadata), estimated, revised"
cap label var df "definition differs (see metadata), forecast"
cap label var dn "definition differs (see metadata), not significant"
cap label var dp "definition differs (see metadata), provisional"
cap label var dps "definition differs (see metadata), provisional, Eurostat estimate"
cap label var dpu "definition differs (see metadata), provisional, low reliability"
cap label var dr "definition differs (see metadata), revised"
cap label var drs "definition differs (see metadata), revised, Eurostat estimate"
cap label var ds "definition differs (see metadata), Eurostat estimate"
cap label var du "definition differs (see metadata), low reliability"
cap label var dz "definition differs (see metadata), not applicable"
cap label var e "estimated"
cap label var ep "estimated, provisional"
cap label var er "estimated, revised"
cap label var f "forecast"
cap label var n "not significant"
cap label var p "provisional"
cap label var ps "provisional, Eurostat estimate"
cap label var pu "provisional, low reliability"
cap label var r "revised"
cap label var rs "revised, Eurostat estimate"
cap label var s "Eurostat estimate"
cap label var u "low reliability"
cap label var z "not applicable"
