cap label var TOTAL "Total"
cap label var INN_PF1 "Enterprises that have developed product innovations themselves, with market novelties (profile I)"
cap label var INN_PF1_RND "Enterprises that have developed product innovations themselves, with market novelties, with R&D activities (profile I.A)"
cap label var INN_PF1_NRND "Enterprises that have developed product innovations themselves, with market novelties, without R&D activities (profile I.B)"
cap label var INN_PF2 "Enterprises that have developed product innovations themselves, without market novelties (profile II)"
cap label var INN_PF2_RND "Enterprises that have developed product innovations themselves, without market novelties, with R&D activities (profile II.A)"
cap label var INN_PF2_NRND "Enterprises that have developed product innovations themselves, without market novelties, without R&D activities (profile II.B)"
cap label var INN_PF3 "Enterprises that have developed business process innovations themselves, without product innovation (profile III)"
cap label var INN_PF3_RND "Enterprises that have developed business process innovations themselves, without product innovation, with R&D activities (profile III.A)"
cap label var INN_PF3_NRND "Enterprises that have developed business process innovations themselves, without product innovation, without R&D activities (profile III.B)"
cap label var INN_PF4 "Enterprises that have introduced but not themselves developed innovations (profile IV)"
cap label var INN_PF4_RND "Enterprises that have introduced but not themselves developed innovations, with R&D activities (profile IV.A)"
cap label var INN_PF4_NRND "Enterprises that have introduced but not themselves developed innovations, without R&D activities (profile IV.B)"
cap label var INN_PF5 "Enterprises that have innovation activities but not introduced any innovation (ongoing or abandoned innovation activities) (profile V)"
cap label var INN_PF5_RND "Enterprises that have (ongoing or abandoned) innovation activities but not introduced any innovation, with R&D activities (profile V.A)"
cap label var INN_PF5_NRND "Enterprises that have (ongoing or abandoned) innovation activities but not introduced any innovation, without R&D activities (profile V.B)"
cap label var NINN_PF6 "Enterprises that have no innovation activities but potential to innovate (profile VI)"
cap label var NINN_PF7 "Enterprises that have no innovation activities and no potential to innovate (profile VII)"
