cap label var C1040 "Cereals for the production of grain (including rice and seed)"
cap label var C1050 "Cereals (excluding rice)"
cap label var C1100 "Wheat (including spelt)"
cap label var C1120 "Common wheat and spelt"
cap label var C1123 "Common winter wheat"
cap label var C1124 "Common spring wheat"
cap label var C1130 "Durum wheat"
cap label var C1133 "Winter durum wheat"
cap label var C1134 "Spring durum wheat"
cap label var C1140 "Rye and maslin"
cap label var C1150 "Rye"
cap label var C1151 "Winter rye"
cap label var C1152 "Spring rye"
cap label var C1155 "Maslin"
cap label var C1160 "Barley"
cap label var C1163 "Winter barley"
cap label var C1164 "Spring barley"
cap label var C1170 "Oats and mixed grain other than maslin"
cap label var C1180 "Oats"
cap label var C1185 "Mixed grain other than maslin"
cap label var C1201 "Grain maize and corn-cob-mix"
cap label var C1200 "Grain maize"
cap label var C1202 "Corn-cob-mix"
cap label var C1211 "Sorghum"
cap label var C1212 "Triticale"
cap label var C1213 "Winter triticale"
cap label var C1219 "Millet, buckwheat, canary seed (other cereals)"
cap label var C1250 "Rice"
cap label var C1251 "Rice Indica"
cap label var C1252 "Rice Japonica"
cap label var C1300 "Dried pulses and protein crops for the production of grain (including seed and mixtures of cereals and pulses)"
cap label var C1320 "Field peas"
cap label var C1335 "Broad and field beans"
cap label var C1343 "Sweet lupins"
cap label var C1345 "Other dried pulses n.e.c."
cap label var C1350 "Root crops"
cap label var C1360 "Potatoes (including early potatoes and seed potatoes)"
cap label var C1362 "Early potatoes"
cap label var C1363 "Other potatoes"
cap label var C1370 "Sugar beet (excluding seed)"
cap label var C1380 "Other root crops n.e.c."
cap label var C1381 "Fodder beet"
cap label var C1400 "Industrial crops"
cap label var C1410 "Oilseeds"
cap label var C1415 "Main oil seed crops"
cap label var C1420 "Rape and turnip rape"
cap label var C1430 "Rape"
cap label var C1431 "Winter rape"
cap label var C1432 "Spring rape"
cap label var C1440 "Turnip rape"
cap label var C1450 "Sunflower seed"
cap label var C1460 "Linseed (oil flax)"
cap label var C1470 "Soya"
cap label var C1490 "Cotton seed"
cap label var C1480 "Other oil seed crops n.e.c."
cap label var C1500 "Fibre crops"
cap label var C1520 "Fibre flax"
cap label var C1530 "Hemp"
cap label var C1540 "Cotton fibre"
cap label var C1510 "Other fibre crops n.e.c."
cap label var C1550 "Tobacco"
cap label var C1560 "Hops"
cap label var C1570 "Other industrial crops"
cap label var C1571 "Chicory"
cap label var C1572 "Chicory for inulin"
cap label var C1580 "Aromatic plants, medicinal and culinary plants"
cap label var C1582 "Caraway"
cap label var C1589 "Other industrial crops n.e.c."
cap label var C2600 "Fodder - Total"
cap label var C2610 "Plants harvested green"
cap label var C2611 "Annual plants harvested green"
cap label var C2625 "Green maize"
cap label var C2626 "Cereals harvested green"
cap label var C2612 "Other annual plants harvested green n.e.c."
cap label var C2670 "Leguminous plants"
cap label var C2671 "Clover and mixtures"
cap label var C2672 "Lucerne"
cap label var C2673 "Other leguminous plants n.e.c."
cap label var C2680 "Temporary grasses and grazing"
cap label var C2681 "Temporary grasses"
cap label var C2682 "Temporary grazings"
cap label var C0002 "Permanent grassland (pastures and meadows)"
cap label var C2710 "Permanent meadows"
cap label var C2720 "Permanent pasture"
cap label var C2721 "Grassland"
cap label var C2722 "Common pasture, heathland, rough grazings"
cap label var C1590 "Energy crops n.e.c."
cap label var C1600 "Vegetables, melons and strawberries (excluding  kitchen gardens)"
cap label var C1609 "Vegetables - Total"
cap label var C1610 "Brassicas"
cap label var C1620 "Cauliflower and broccoli"
cap label var C1631 "Brussels sprouts"
cap label var C1635 "Cabbage (white)"
cap label var C1650 "Kohlrabi"
cap label var C1655 "Other brassicas n.e.c."
cap label var C1660 "Leafy or stalked vegetables (excluding brassicas)"
cap label var C1670 "Celeriac and celery"
cap label var C1672 "Celery"
cap label var C1675 "Leeks"
cap label var C1680 "Lettuces"
cap label var C1681 "Lettuces under glass or high accessible cover"
cap label var C1685 "Endives"
cap label var C1690 "Spinach"
cap label var C1700 "Asparagus"
cap label var C1710 "Chicory"
cap label var C1720 "Artichokes"
cap label var C1725 "Other leafy or stalked vegetables n.e.c."
cap label var C1740 "Vegetables cultivated for fruit"
cap label var C1750 "Tomatoes"
cap label var C1751 "Tomatoes for fresh consumption"
cap label var C1752 "Tomatoes for fresh consumption under glass or high accessible cover"
cap label var C1761 "Cucumbers"
cap label var C1762 "Cucumbers under glass or high accessible cover"
cap label var C1766 "Gherkins"
cap label var C1780 "Eggplants, gourds, marrows, courgettes, pumpkins"
cap label var C1781 "Eggplants"
cap label var C1786 "Gourds, marrows and pumpkins"
cap label var C1785 "Gourds"
cap label var C1787 "Courgettes"
cap label var C1790 "Red pepper, capsicum"
cap label var C1791 "Red pepper, capsicum under glass or high accessible cover"
cap label var C1799 "Other vegetables cultivated for fruit n.e.c."
cap label var C1800 "Root and tuber vegetables"
cap label var C1810 "Kohl-Rabi"
cap label var C1820 "Turnips"
cap label var C1830 "Carrots"
cap label var C1840 "Garlic"
cap label var C1851 "Onions"
cap label var C1855 "Shallots"
cap label var C1860 "Beetroot"
cap label var C1870 "Salsify and scorzonera"
cap label var C1872 "Celeriac"
cap label var C1877 "Radishes"
cap label var C1884 "Other root and tuber vegetables n.e.c"
cap label var C1885 "Pulses"
cap label var C1890 "Peas"
cap label var C1901 "Beans"
cap label var C1905 "Other pulses n.e.c."
cap label var C1920 "Other fresh vegetables n.e.c."
cap label var C1771 "Melons"
cap label var C1770 "Melons and Strawberries"
cap label var C1777 "Watermelons"
cap label var C2260 "Strawberries"
cap label var C2261 "Strawberries under glass or high accessible cover"
cap label var C1910 "Cultivated mushrooms"
cap label var C2992 "Vegetables from kitchen gardens"
cap label var C1601 "Vegetables, melons and strawberries (including kitchen gardens)"
cap label var C2696 "Fallow and green manures"
cap label var C2002 "Fresh fruit (supply balance sheets)"
cap label var C2007 "Permanent crops"
cap label var C2008 "Dessert fruit (do not include olives, raisins, grapes for juice and wine , wild products, fruits from kitchen gardens and apples and pears for other uses than dessert)"
cap label var C2040 "Fruit trees (excluding olives and citrus fruit)"
cap label var C2090 "Apples"
cap label var C2110 "Apples for fresh consumption"
cap label var C2112 "Golden Delicious"
cap label var C2113 "Other apples for fresh consumption"
cap label var C2095 "Pears"
cap label var C2130 "Pears for fresh consumption"
cap label var C2132 "Summer pears"
cap label var C2170 "Stone fruits"
cap label var C2180 "Peaches"
cap label var C2221 "Nectarines"
cap label var C2190 "Apricots"
cap label var C2200 "Cherries"
cap label var C2201 "Sour cherries"
cap label var C2210 "Plums"
cap label var C9000 "Dates"
cap label var C2229 "Other stone fruits n.e.c."
cap label var C2270 "Berries (exluding strawberries)"
cap label var C2271 "Currants"
cap label var C2272 "Black currants"
cap label var C2275 "Red currants"
cap label var C2278 "Raspberries"
cap label var C2281 "Gooseberries"
cap label var C2290 "Other berries n.e.c."
cap label var C2230 "Nuts"
cap label var C2231 "Walnuts"
cap label var C2232 "Hazelnuts"
cap label var C2233 "Almonds"
cap label var C2236 "Chestnuts"
cap label var C2240 "Other nuts n.e.c."
cap label var C2250 "Other fruits from fruit trees"
cap label var C2251 "Figs"
cap label var C2285 "Kiwis"
cap label var C2253 "Avocados"
cap label var C2254 "Bananas"
cap label var C2252 "Quinces"
cap label var C2259 "Other fruits from fruit trees n.e.c."
cap label var C2300 "Citrus fruits"
cap label var C2380 "Pomelos and grapefruit"
cap label var C2370 "Lemons and acid limes"
cap label var C2371 "Yellow lemons"
cap label var C2372 "Limes"
cap label var C2321 "Oranges with non-sanguin pulp, belonging to the Navel Group"
cap label var C2322 "Oranges with non-sanguin pulp, other than Navel Group"
cap label var C2323 "Blood and semi-blood and other sweet oranges"
cap label var C2324 "Other sweet oranges"
cap label var C2320 "Oranges"
cap label var C2340 "Small citrus fruits"
cap label var C2350 "Mandarins"
cap label var C2352 "Satsumas"
cap label var C2360 "Clementines"
cap label var C2390 "Other citrus fruits n.e.c."
cap label var C2410 "Vineyards"
cap label var C2420 "Vineyards for table grapes"
cap label var C2415 "Fresh grapes"
cap label var C2416 "Vineyards for raisins"
cap label var C2417 "Table grapes (for fermentation)"
cap label var C2440 "Vineyards for wine"
cap label var C2441 "Vineyards for wines with protected designation of origin (PDO)"
cap label var C2442 "Vineyards for wines with protected geographical indication (PGI)"
cap label var C2443 "Vineyards for other wines"
cap label var C2445 "Vineyards for other grape production n.e.c."
cap label var C2447 "Wine grapes (for table use)"
cap label var C2450 "Olive trees"
cap label var C2460 "Olive trees for table olives"
cap label var C2470 "Olive trees for olive oil"
cap label var C2810 "Nurseries"
cap label var C2960 "Weaving plants : osier willows, bamboo, rush, rattan, Canada poplar"
cap label var C2480 "Other permanent crops n.e.c."
cap label var C2993 "Fruits from kitchen gardens"
cap label var C2009 "Permanent crops (including kitchen gardens)"
cap label var C3718 "Wild products"
cap label var C3719 "Wild products"
