cap label var TOTAL "Total"
cap label var FORC "Forced return"
cap label var VOLU "Voluntary return"
cap label var ASSI "Assisted return"
cap label var ASSI_VOLU "Assisted voluntary return"
cap label var ASSI_FORC "Assisted forced return"
cap label var NASSI "Non-assisted return"
cap label var NASSI_VOLU "Non-assisted voluntary return"
cap label var ENFORC "Enforced return"
cap label var ASSIST "Assisted return"
cap label var NASSIST "Non-assisted return"
cap label var THRD "Returned to a third country"
cap label var EURA "Returned under EU Readmission Agreement (EURA)"
cap label var RA_OTH "Returned under other readmission agreement"
cap label var NRA "Returned without existing a readmission agreement"
cap label var OTH "Other"
cap label var UNK "Unknown"
