cap label var PC_TOT_IMP "Share of imports by partner in total imports (%)"
cap label var PC_TOT_EXP "Share of exports by partner in total exports (%)"
cap label var RT_EXP_IMP "Export/Import ratio"
cap label var IVOL_IMP "Import volume index (2015=100)"
cap label var IVOL_EXP "Export volume index (2015=100)"
cap label var RT_IVOL "Volume Ratio (Export/Import)"
cap label var PC_IMP_EU "Share of imports from EU in total imports (%)"
cap label var PC_EXP_EU "Share of exports to EU in total exports (%)"
cap label var PC_IMP_WRL "Share of national imports in world imports (%)"
cap label var PC_EXP_WRL "Share of national exports in world exports (%)"
cap label var TRD_VAL "Trade value in million ECU/EURO"
cap label var TRD_VAL_RT12 "Growth rate M/M-12 of the trade value"
cap label var TRD_VAL_SCA "Seasonally and calendar adjusted trade value in million ECU/EURO"
cap label var TRD_VAL_SCA_RT1 "Growth rate M/M-1 of the seasonally and calendar adjusted trade value"
cap label var IVU "Unit value index (2015=100)"
cap label var IVU_EXP "Export unit value index (2015=100)"
cap label var IVU_IMP "Import unit value index (2015=100)"
cap label var RT_IVU "Terms of trade (Export/import)"
cap label var IVU_RT1 "Growth rate M/M-1 of the unit-value indices"
cap label var IVU_RT12 "Growth rate M/M-12 of the unit-value indices"
cap label var IVOLU "Unit volume index (2015=100)"
cap label var IVOL_NSA "Volume indices - unadjusted data (2015=100)"
cap label var IVOL_NSA_RT12 "Growth rate M/M-12 of the volume Indices - unadjusted data"
cap label var IVOL_SCA "Seasonally and calendar adjusted volume indices (2015=100)"
cap label var IVOL_SCA_RT1 "Growth rate M/M-1 of the seasonally and calendar adjusted volume Indices"
cap label var CONT_IMP_EU "Share of imports by Member State (%)"
cap label var CONT_EXP_EU "Share of exports by Member State (%)"
cap label var MIO_BAL_VAL "Trade balance in million ECU/EURO"
cap label var MIO_EXP_VAL "Exports in million of ECU/EURO"
cap label var MIO_IMP_VAL "Imports in million of ECU/EURO"
cap label var PC_IMP_PROD "Share of imports by product (%)"
cap label var PC_EXP_PROD "Share of exports by product (%)"
cap label var PC_IMP_PART "Share of imports by partner (%)"
cap label var PC_EXP_PART "Share of exports by partner (%)"
cap label var ENT_NR "Number of enterprises"
cap label var AVG_IMP_VAL "Average import value"
cap label var AVG_EXP_VAL "Average export value"
cap label var IMP_VAL "Import value"
cap label var EXP_VAL "Export value"
cap label var PC_IMP_SZCL "Percentage of imports by sizeclas (%)"
cap label var PC_EXP_SZCL "Percentage of exports by sizeclas (%)"
