cap label var TOTAL "Total"
cap label var S "Services"
cap label var SA "Services: Manufacturing services on physical inputs owned by others"
cap label var SB "Services: Maintenance and repair services n.i.e."
cap label var SBG "Services: Maintenance and repair services n.i.e. (of which goods)"
cap label var SC "Services: Transport"
cap label var SC1 "Services: Sea transport"
cap label var SC2 "Services: Air transport"
cap label var SC3 "Services: Other modes of transport"
cap label var SC4 "Services: Postal and courier services"
cap label var SCB "Services: All modes of transport; Freight"
cap label var SD "Services: Travel"
cap label var SDG "Services: Travel (of which goods)"
cap label var SE "Services: Construction"
cap label var SEG "Services: Construction (of which goods)"
cap label var SF "Services: Insurance and pension services"
cap label var SG "Services: Financial services"
cap label var SH "Services: Charges for the use of intellectual property n.i.e."
cap label var SI "Services: Telecommunications, computer, and information services"
cap label var SI1 "Services: Telecommunications services"
cap label var SI2 "Services: Computer services"
cap label var SI3 "Services: Information services"
cap label var SJ "Services: Other business services"
cap label var SJ1 "Services: Research and development services"
cap label var SJ2 "Services: Professional and management consulting services"
cap label var SJ21 "Services: Legal, accounting, management consulting, and public relations services"
cap label var SJ22 "Services: Advertising, market research, and public opinion polling services"
cap label var SJ3 "Services: Technical, trade-related, and other business services"
cap label var SJ31 "Services: Architectural, engineering, scientific, and other technical services"
cap label var SJ32 "Services: Waste treatment and de-pollution, agricultural and mining services"
cap label var SJ33 "Services: Operating leasing services"
cap label var SJ34T "Services: Total trade related transactions"
cap label var SJ34 "Services: Trade-related services"
cap label var SJ34D "Services: Distribution services"
cap label var SJ35 "Services: Other business services n.i.e."
cap label var SK "Services: Personal, cultural, and recreational services"
cap label var SK1 "Services: Audiovisual and related services"
cap label var SK2 "Services: Personal, cultural, and recreational services other than audiovisual and related services"
cap label var SL "Services: Government goods and services n.i.e."
cap label var SLG "Services: Government goods and services n.i.e. (of which goods)"
cap label var SN "Services: Services not allocated"
