cap label var HARS_BULLY "Harassment or bullying"
cap label var TPR_OLWRK "Time pressure or overload of work"
cap label var VLN_THRT "Violence or threat of violence"
cap label var CHM_SMO_GAS "Chemicals, dusts, fumes, smoke or gases"
cap label var ACT_SVCONC "Activities involving strong visual concentration"
cap label var H_HVYLOAD "Handling of heavy loads"
cap label var NOIS_VIB "Noise or vibration"
cap label var DIF_WPST_WMV "Difficult work postures, work movements"
cap label var RSK_ACC "Risk of accident"
cap label var LCOMM_ORG "Lack of communication or cooperation within the organisation"
cap label var DEAL_DIFCUS "Dealing with difficult customers, patients, pupils, etc."
cap label var NSECU_JOB "Job insecurity"
cap label var LAUTN_WPACE "Lack of autonomy, or lack of influence over the work pace or work processes"
cap label var TIR_PFPSN "Tiring or painful positions"
cap label var RPTMOV "Repetitive hand or arm movements"
cap label var SLP_TRP_FAL "Slips, trips and falls"
cap label var U_MAC_HNTL "Use of machines or hand tools (excluding vehicles)"
cap label var U_VEH "Use of vehicles (in the course of work, excluding on the way to and from work)"
cap label var SGN_OTH "Another significant risk factor"
cap label var GOV_PLCY_MEAS "Government policies or measures"
cap label var INCR_CUSDM "Increasing customer demand"
cap label var INCR_COST_PRC "Increasing costs or input prices"
cap label var IMPC_WTHR "Impacts of extreme weather conditions"
cap label var REG "Existing regulations"
cap label var TAX_CHRG_FEE "Existing taxes, charges or fees"
cap label var REG_TAX_FU "Regulations or taxes expected in the future"
cap label var GRNT_S_FINOTH "Government grants, subsidies or other financial incentive"
cap label var MKTDM "Current or expected market demand"
cap label var I_ENTREPUT "Improving enterprise's reputation"
cap label var VA_INIT "Voluntary actions or initiatives within the sector"
cap label var HCOST_EWM "High cost of energy, water or materials"
cap label var PUB_PROC "Need to meet requirements for public procurement"
