cap label var HBEDT "Available beds in hospitals (HP.1)"
cap label var HBEDT_CUR "Curative care beds in hospitals (HP.1)"
cap label var HBEDT_REH "Rehabilitative care beds in hospitals (HP.1)"
cap label var HBEDT_LT "Long-term care beds in hospitals (HP.1)"
cap label var HBEDT_OTH "Other beds in hospitals (HP.1)"
cap label var HBEDI_PSY "Psychiatric care beds in hospitals (HP.1)"
cap label var NRCBED "Available beds in nursing and residential care facilities (HP.2)"
cap label var CT_SCAN "Computed Tomography Scanners"
cap label var MRI "Magnetic Resonance Imaging Units"
cap label var GAMMA "Gamma cameras"
cap label var DSA "Angiography units"
cap label var LSI "Lithotriptors"
cap label var PET_SCAN "PET scanners"
cap label var RAD "Radiation therapy equipment"
cap label var MAMMO "Mammographs"
cap label var OPER "Operation theatres in hospital"
cap label var DAY "Day care places altogether"
cap label var DAY_SUR "Surgical day care places"
cap label var DAY_ONC "Oncological day care place"
cap label var DAY_PSY "Psychiatric day care place"
cap label var DAY_GER "Geriatric day care places"
