cap label var TOTAL "Total"
cap label var GINI_HND "Gini coefficient (scale from 0 to 100)"
cap label var S80_S20 "Inequality of income distribution (income quintile share ratio)"
cap label var A97_MD60 "At risk of poverty rate anchored at 1997 (cut-off point: 60% of median equivalised income)"
cap label var A98_MD40 "At risk of poverty rate anchored at 1998 (cut-off point: 40% of median equivalised income)"
cap label var A98_MD50 "At risk of poverty rate anchored at 1998 (cut-off point: 50% of median equivalised income)"
cap label var A98_MD60 "At risk of poverty rate anchored at 1998 (cut-off point: 60% of median equivalised income)"
cap label var A98_MD70 "At risk of poverty rate anchored at 1998 (cut-off point: 70% of median equivalised income)"
cap label var A98_M40 "At risk of poverty rate anchored at 1998 (cut-off point: 40% of mean equivalised income)"
cap label var A98_M50 "At risk of poverty rate anchored at 1998 (cut-off point: 50% of mean equivalised income)"
cap label var A98_M60 "At risk of poverty rate anchored at 1998 (cut-off point: 60% of mean equivalised income)"
cap label var A99_MD60 "At risk of poverty rate anchored at 1999 (cut-off point: 60% of median equivalised income)"
cap label var A00_MD60 "At risk of poverty rate anchored at 2000 (cut-off point: 60% of median equivalised income)"
cap label var MEI_E "Mean equivalised net income"
cap label var MED_E "Median equivalised net income"
cap label var TC "Top cut-off point"
cap label var SHARE "Share of national equivalised income"
cap label var LI_R_MD40 "At risk of poverty rate (cut-off point: 40% of median equivalised income)"
cap label var LI_R_MD50 "At risk of poverty rate (cut-off point: 50% of median equivalised income)"
cap label var LI_R_MD60 "At risk of poverty rate (cut-off point: 60% of median equivalised income after social transfers)"
cap label var LI_R_MD70 "At risk of poverty rate (cut-off point: 70% of median equivalised income)"
cap label var LI_R_M40 "At risk of poverty rate (cut-off point: 40% of mean equivalised income)"
cap label var LI_R_M50 "At risk of poverty rate (cut-off point: 50% of mean equivalised income)"
cap label var LI_R_M60 "At risk of poverty rate (cut-off point: 60% of mean equivalised income)"
cap label var LI_R_MD40BTP "At risk of poverty rate before social transfers (pensions included in social transfers) (cut-off point: 40% of median equivalised income after social transfers)"
cap label var LI_R_MD50BTP "At risk of poverty rate before social transfers (pensions included in social transfers) (cut-off point: 50% of median equivalised income after social transfers)"
cap label var LI_R_MD60BTP "At risk of poverty rate before social transfers (pensions included in social transfers) (cut-off point: 60% of median equivalised income after social transfers)"
cap label var LI_R_MD70BTP "At risk of poverty rate before social transfers (pensions included in social transfers) (cut-off point: 70% of median equivalised income after social transfers)"
cap label var LI_R_M40BTP "At risk of poverty rate before social transfers (pensions included in social transfers) (cut-off point: 40% of mean equivalised income after social transfers)"
cap label var LI_R_M50BTP "At risk of poverty rate before social transfers (pensions included in social transfers) (cut-off point: 50% of mean equivalised income after social transfers)"
cap label var LI_R_M60BTP "At risk of poverty rate before social transfers (pensions included in social transfers) (cut-off point: 60% of mean equivalised income after social transfers)"
cap label var LI_R_MD40BT "At risk of poverty rate before social transfers (pensions excluded from social transfers) (cut-off point: 40% of median equivalised income after social transfers)"
cap label var LI_R_MD50BT "At risk of poverty rate before social transfers (pensions excluded from social transfers) (cut-off point: 50% of median equivalised income after social transfers)"
cap label var LI_R_MD60BT "At risk of poverty rate before social transfers (pensions excluded from social transfers) (cut-off point: 60% of median equivalised income after social transfers)"
cap label var LI_R_MD70BT "At risk of poverty rate before social transfers (pensions excluded from social transfers) (cut-off point: 70% of median equivalised income after social transfers)"
cap label var LI_R_M40BT "At risk of poverty rate before social transfers (pensions excluded from social transfers) (cut-off point: 40% of mean equivalised income after social transfers)"
cap label var LI_R_M50BT "At risk of poverty rate before social transfers (pensions excluded from social transfers) (cut-off point: 50% of mean equivalised income after social transfers)"
cap label var LI_R_M60BT "At risk of poverty rate before social transfers (pensions excluded from social transfers) (cut-off point: 60% of mean equivalised income after social transfers)"
cap label var LI_GAP_MD40 "Relative poverty gap (cut-off point: 40% of median equivalised income)"
cap label var LI_GAP_MD50 "Relative poverty gap (cut-off point: 50% of median equivalised income)"
cap label var LI_GAP_MD60 "Relative poverty gap (cut-off point: 60% of median equivalised income)"
cap label var LI_GAP_MD70 "Relative poverty gap (cut-off point: 70% of median equivalised income)"
cap label var LI_GAP_M40 "Relative poverty gap (cut-off point: 40% of mean equivalised income)"
cap label var LI_GAP_M50 "Relative poverty gap (cut-off point: 50% of mean equivalised income)"
cap label var LI_GAP_M60 "Relative poverty gap (cut-off point: 60% of mean equivalised income)"
cap label var LI_C_MD40 "At risk of poverty threshold (40% of median equivalised income)"
cap label var LI_C_MD50 "At risk of poverty threshold (50% of median equivalised income)"
cap label var LI_C_MD60 "At risk of poverty threshold (60% of median equivalised income)"
cap label var LI_C_MD70 "At risk of poverty threshold (70% of median equivalised income)"
cap label var LI_C_M40 "At risk of poverty threshold (40% of mean equivalised income)"
cap label var LI_C_M50 "At risk of poverty threshold (50% of mean equivalised income)"
cap label var LI_C_M60 "At risk of poverty threshold (60% of mean equivalised income)"
cap label var LIP_MD40 "At persistent risk of poverty rate by age and gender (cut-off point: 40% of median equivalised income)"
cap label var LIP_MD50 "At persistent risk of poverty rate by age and gender (cut-off point: 50% of median equivalised income)"
cap label var LIP_MD60 "At persistent risk of poverty rate by age and gender (cut-off point: 60% of median equivalised income)"
cap label var LIP_MD70 "At persistent risk of poverty rate by age and gender (cut-off point: 70% of median equivalised income)"
cap label var LIP_M40 "At persistent risk of poverty rate by age and gender (cut-off point: 40% of mean equivalised income)"
cap label var LIP_M50 "At persistent risk of poverty rate by age and gender (cut-off point: 50% of mean equivalised income)"
cap label var LIP_M60 "At persistent risk of poverty rate by age and gender (cut-off point: 60% of mean equivalised income)"
cap label var LI_GE130MD "Having income of 130% of median income or more"
cap label var LI_GE140MD "Having income of 140% of median income or more"
cap label var LI_GE150MD "Having income of 150% of median income or more"
cap label var LI_GE160MD "Having income of 160% of median income or more"
cap label var LI_GE130M "Having income of 130% of mean income or more"
cap label var LI_GE140M "Having income of 140% of mean income or more"
cap label var LI_GE150M "Having income of 150% of mean income or more"
cap label var R_GE65_LT65 "Persons aged 65 years and over compared to persons aged less than 65 years"
cap label var R_GE75_LT75 "Persons aged 75 years and over compared to persons aged less than 75 years"
cap label var R_GE60_LT60 "Persons aged 60 years and over compared to persons aged less than 60 years"
cap label var R_PN_WK "Ratio of income from pensions of persons aged between 65 and 74 years and income from work of persons aged between 50 and 59 years"
cap label var SC101 "Less than 3 years - no formal childcare"
cap label var SC102 "Less than 3 years - childcare from 1 to 29 hours weekly"
cap label var SC103 "Less than 3 years - childcare 30 hours or more weekly"
cap label var SC111 "Between 3 years and compulsory school age - no formal childcare"
cap label var SC112 "Between 3 years and compulsory school age - childcare from 1 to 29 hours weekly"
cap label var SC113 "Between 3 years and compulsory school age - childcare 30 hours or more weekly"
cap label var R_NDEP_NLOW "Population at risk of poverty but not severely materially deprived and not living in a household with low work intensity"
cap label var R_NDEP_LOW "Population at risk of poverty, not severely materially deprived but living in a household with low work intensity"
cap label var R_DEP_NLOW "Population at risk of poverty, severely materially deprived but not living in a household with low work intensity"
cap label var R_DEP_LOW "Population at risk of poverty, severely materially deprived and living in a household with low work intensity"
cap label var NR_NDEP_LOW "Population not at risk of poverty, not severely materially deprived but living in a household with low work intensity"
cap label var NR_DEP_NLOW "Population not at risk of poverty but severely materially deprived and not living in a household with low work intensity"
cap label var NR_DEP_LOW "Population not at risk of poverty but severely materially deprived and living in a household with low work intensity"
cap label var NR_NDEP_NLOW "Population neither at risk of poverty, nor severely materially deprived nor living in a household with low work intensity"
cap label var GAP_LT18TOT "Gap between people aged less than 18 years and total population"
cap label var GAP_18_24TOT "Gap between people aged 18 - 24 and total population"
cap label var INC_EMP "Income from employment"
cap label var INC_PEN "Income from pensions"
cap label var INC_BEN "Income from benefits and allowances"
cap label var INC_OTH "Income from other sources"
cap label var A25DI "Housing cost burden over 25 % of disposable household income"
cap label var A40DI "Housing cost burden over 40 % of disposable household income"
cap label var A50DI "Housing cost burden over 50 % of disposable household income"
cap label var A60DI "Housing cost burden over 60 % of disposable household income"
cap label var A75DI "Housing cost burden over 75 % of disposable household income"
cap label var AVG "Average"
cap label var MED "Median"
cap label var HH "Household"
cap label var INC_DISP "Disposable income"
cap label var EXPN_CONS "Consumption expenditure"
cap label var WLTH_NET "Net wealth"
cap label var POV_INC_CONS "Income poverty and consumption poverty"
cap label var POV_INC_LFA "Income poverty and liquid financial assets poverty"
cap label var POV_CONS_LFA "Consumption poverty and liquid financial assets poverty"
cap label var QUANT_WLTH "Wealth quantile"
