cap label var TOTAL "Total"
cap label var GF01 "General public services"
cap label var GF0101 "Executive and legislative organs, financial and fiscal affairs, external affairs"
cap label var GF0102 "Foreign economic aid"
cap label var GF0103 "General services"
cap label var GF0104 "Basic research"
cap label var GF0105 "R&D General public services"
cap label var GF0106 "General public services n.e.c."
cap label var GF0107 "Public debt transactions"
cap label var GF0108 "Transfers of a general character between different levels of government"
cap label var GF02 "Defence"
cap label var GF0201 "Military defence"
cap label var GF0202 "Civil defence"
cap label var GF0203 "Foreign military aid"
cap label var GF0204 "R&D Defence"
cap label var GF0205 "Defence n.e.c."
cap label var GF03 "Public order and safety"
cap label var GF0301 "Police services"
cap label var GF0302 "Fire-protection services"
cap label var GF0303 "Law courts"
cap label var GF0304 "Prisons"
cap label var GF0305 "R&D Public order and safety"
cap label var GF0306 "Public order and safety n.e.c."
cap label var GF04 "Economic affairs"
cap label var GF0401 "General economic, commercial and labour affairs"
cap label var GF0402 "Agriculture, forestry, fishing and hunting"
cap label var GF0403 "Fuel and energy"
cap label var GF0404 "Mining, manufacturing and construction"
cap label var GF0405 "Transport"
cap label var GF0406 "Communication"
cap label var GF0407 "Other industries"
cap label var GF0408 "R&D Economic affairs"
cap label var GF0409 "Economic affairs n.e.c."
cap label var GF05 "Environmental protection"
cap label var GF0501 "Waste management"
cap label var GF0502 "Waste water management"
cap label var GF0503 "Pollution abatement"
cap label var GF0504 "Protection of biodiversity and landscape"
cap label var GF0505 "R&D Environmental protection"
cap label var GF0506 "Environmental protection n.e.c."
cap label var GF06 "Housing and community amenities"
cap label var GF0601 "Housing development"
cap label var GF0602 "Community development"
cap label var GF0603 "Water supply"
cap label var GF0604 "Street lighting"
cap label var GF0605 "R&D Housing and community amenities"
cap label var GF0606 "Housing and community amenities n.e.c."
cap label var GF07 "Health"
cap label var GF0701 "Medical products, appliances and equipment"
cap label var GF0702 "Outpatient services"
cap label var GF0703 "Hospital services"
cap label var GF0704 "Public health services"
cap label var GF0705 "R&D Health"
cap label var GF0706 "Health n.e.c."
cap label var GF08 "Recreation, culture and religion"
cap label var GF0801 "Recreational and sporting services"
cap label var GF0802 "Cultural services"
cap label var GF0803 "Broadcasting and publishing services"
cap label var GF0804 "Religious and other community services"
cap label var GF0805 "R&D Recreation, culture and religion"
cap label var GF0806 "Recreation, culture and religion n.e.c."
cap label var GF09 "Education"
cap label var GF0901 "Pre-primary and primary education"
cap label var GF0902 "Secondary education"
cap label var GF0903 "Post-secondary non-tertiary education"
cap label var GF0904 "Tertiary education"
cap label var GF0905 "Education not definable by level"
cap label var GF0906 "Subsidiary services to education"
cap label var GF0907 "R&D Education"
cap label var GF0908 "Education n.e.c."
cap label var GF10 "Social protection"
cap label var GF1001 "Sickness and disability"
cap label var GF1002 "Old age"
cap label var GF1003 "Survivors"
cap label var GF1004 "Family and children"
cap label var GF1005 "Unemployment"
cap label var GF1006 "Housing"
cap label var GF1007 "Social exclusion n.e.c."
cap label var GF1008 "R&D Social protection"
cap label var GF1009 "Social protection n.e.c."
