cap label var TOTAL "Total requests (requests and re-examination requests)"
cap label var REQ "Requests"
cap label var RX_REQ "Re-examination requests"
cap label var INFO "Requests for information"
cap label var INFO_GEN "Requests for information: general reasons (Article 34.5)"
cap label var INFO_UAM "Requests for information: family of unaccompanied minors (Articles 6.5 and 8.6)"
cap label var INFO_DEP "Requests for information: family of dependent persons (Article 16.4)"
cap label var RESP "Responses to requests for information"
cap label var RESP_GEN "Responses to requests for information: general reasons (Article 34.5)"
cap label var RG_W1_5 "Responses to requests for information received within 5 weeks: general reasons (Article 34.5)"
cap label var RG_W_GT5 "Responses to requests for information received in more than 5 weeks: general reasons (Article 34.5)"
cap label var RESP_UAM "Responses to requests for information: family of unaccompanied minors (Articles 6.5 and 8.6)"
cap label var RU_W1_5 "Responses to requests for information received within 5 weeks: family of unaccompanied minors (Articles 6.5 and 8.6)"
cap label var RU_W_GT5 "Responses to requests for information received in more than 5 weeks: family of unaccompanied minors (Articles 6.5 and 8.6)"
cap label var RESP_DEP "Responses to requests for information: family of dependent persons (Article 16.4)"
cap label var RD_W1_5 "Responses to requests for information received within 5 weeks: family of dependent persons (Article 16.4)"
cap label var RD_W_GT5 "Responses to requests for information received in more than 5 weeks: family of dependent persons (Article 16.4)"
