cap label var TOTAL "Total"
cap label var POP "Population"
cap label var ACT_INAC "Persons in- and outside the labour force (former name: active and inactive persons)"
cap label var ACT "Persons in the labour force (former name: active persons)"
cap label var EMP_W "Persons employed or previously employed"
cap label var EMP "Employed persons"
cap label var EMP_FT "Employed persons working full-time"
cap label var EMP_PT "Employed persons working part-time"
cap label var EMP_TEMP "Employed persons with temporary contract"
cap label var LEAV "Employed persons on temporary leave from work"
cap label var SAL_SCTR "Employees and subcontractors"
cap label var SAL "Employees"
cap label var SAL_PERM "Employees with a permanent job"
cap label var SAL_TEMP "Employees with a temporary job"
cap label var MW_IS "Manual workers in industry and services"
cap label var NMW_IS "Non-manual workers in industry and services"
cap label var NSAL "Employed persons except employees"
cap label var SELF_COWN "Self-employed persons and co-owner"
cap label var SELF "Self-employed persons"
cap label var SELF_S "Self-employed persons with employees (employers)"
cap label var SELF_NS "Self-employed persons without employees (own-account workers)"
cap label var SELF_I_NS "Independent self-employed without employees (own-account workers)"
cap label var SELF_D_NS "Dependent self-employed without employees (own-account workers)"
cap label var SELF_NS_D_UNK "Self-employed without employees (own-account workers), dependency not known"
cap label var CFAM_COOP "Contributing family workers and members of producers' cooperatives"
cap label var CFAM "Contributing family workers"
cap label var NCFAM "Employed persons except contributing family workers"
cap label var COOP "Members of producers' cooperatives"
cap label var EMP_OTH "Other employed persons"
cap label var EMP_UNK "Employed persons - unknown"
cap label var FLF_D "Farm labour force, directly employed by the farm on a regular or non-regular basis"
cap label var FLF_D_R "Farm labour force, directly employed by the farm on a regular basis"
cap label var FLF_D_RFAM "Family farm labour force directly employed by the farm"
cap label var FLF_D_RFAM_HLD "Sole holder directly employed by the farm"
cap label var FLF_D_RFAMXHLD "Members of sole holders' family, excluding the holder, directly employed by the farm"
cap label var FLF_D_RFAM_SPOU "Spouse of sole holder directly employed by the farm"
cap label var FLF_D_RFAM_OTH "Other members of sole holder's family directly employed by the farm"
cap label var FLF_D_RNFAM "Non-family farm labour force, directly employed by the farm on a regular basis"
cap label var FLF_D_NR "Farm labour force, directly employed by the farm on a non-regular basis"
cap label var FLF_ND "Farm labour force, not directly employed by the farm"
cap label var FLF_GRP "Group holders"
cap label var FLF_MANXGRP "Farm managers, excluding group holding"
cap label var NEMP "Not employed persons"
cap label var UEMP_PT "Underemployed persons working part-time"
cap label var UNE "Unemployed persons"
cap label var ACT_UNK "Persons in the labour force (former name: active population) - unknown"
cap label var INAC "Persons outside the labour force (former name: inactive persons)"
cap label var SLACK "Labour market slack"
cap label var EDUC "Students"
cap label var HOME "Homemakers"
cap label var B_AGE_MIN "Persons below the national minimum age for economic activity"
cap label var INC "Retired persons and capital income recipients"
cap label var RET "Retired persons"
cap label var INAC_OTH "Other persons outside the labour force (former name: inactive persons)"
cap label var INAC_UNK "Persons outside the labour force (former name: inactive persons) - unknown"
cap label var COWN "Co-owner"
cap label var CLIENT "Clients"
cap label var SCTR "Subcontractors"
cap label var NONE "None"
cap label var NCHG "No change"
cap label var WANT "Persons would like to work (seeking employment or not)"
cap label var NWANT "Persons do not want to work"
cap label var WANTW "Persons want to work but not seeking or available"
cap label var SEEK_NAVL "Persons seeking work but not immediately available"
cap label var NSEEK_AVL "Persons available to work but not seeking"
cap label var PRACT "Practising"
cap label var PACT "Professionally active"
cap label var LIC "Licensed to practice"
cap label var OTH "Others"
cap label var NAP "Not applicable"
cap label var NRP "No response"
cap label var UNK "Unknown"
