cap label var REDLC "Reduction of labour costs"
cap label var REDOC "Reduction of other costs than labour costs"
cap label var LOG "Logistics"
cap label var ANM "Access to new markets"
cap label var QUAL "Improved quality or introduction of new products"
cap label var COMP "Competitiveness"
cap label var IHKH "In-house know-how"
cap label var KNOW "Access to specialized knowledge/technologies"
cap label var OTHER "Others"
