cap label var TOTAL "Total"
cap label var MF1 "Biomass"
cap label var MF11 "Crops (excluding fodder crops)"
cap label var MF111 "Cereals"
cap label var MF112 "Roots, tubers"
cap label var MF113 "Sugar crops"
cap label var MF114 "Pulses"
cap label var MF115 "Nuts"
cap label var MF116 "Oil-bearing crops"
cap label var MF117 "Vegetables"
cap label var MF118 "Fruits"
cap label var MF119 "Fibres"
cap label var MF11A "Other crops (excluding fodder crops) n.e.c."
cap label var MF1110 "Other crops n.e.c."
cap label var MF12 "Crop residues (used), fodder crops and grazed biomass"
cap label var MF121 "Crop residues (used)"
cap label var MF1211 "Straw"
cap label var MF1212 "Other crop residues (sugar and fodder beet leaves, etc.)"
cap label var MF122 "Fodder crops and grazed biomass"
cap label var MF1221 "Fodder crops (including biomass harvest from grassland)"
cap label var MF1222 "Grazed biomass"
cap label var MF13 "Wood"
cap label var MF131 "Timber (industrial roundwood)"
cap label var MF132 "Wood fuel and other extraction"
cap label var MF13MEMO "Net increment of timber stock (memo item)"
cap label var MF14 "Wild fish catch, aquatic plants and animals, hunting and gathering"
cap label var MF141 "Wild fish catch"
cap label var MF142 "All other aquatic animals and plants"
cap label var MF143 "Hunting and gathering"
cap label var MF15 "Live animals and animal products (excluding wild fish, aquatic plants and animals, hunted and gathered animals)"
cap label var MF151 "Live animals (excluding wild fish, aquatic plants and animals, hunted and gathered animals)"
cap label var MF152 "Meat and meat preparations"
cap label var MF153 "Dairy products, birds' eggs, and honey"
cap label var MF154 "Other products from animals (animal fibres, skins, furs, leather, etc.)"
cap label var MF16 "Products mainly from biomass"
cap label var MF2 "Metal ores (gross ores)"
cap label var MF21 "Iron"
cap label var MF22 "Non-ferrous metal"
cap label var MF221 "Copper"
cap label var MF221MEMO "Copper - metal content"
cap label var MF222 "Nickel"
cap label var MF222MEMO "Nickel - metal content"
cap label var MF223 "Lead"
cap label var MF223MEMO "Lead - metal content"
cap label var MF224 "Zinc"
cap label var MF224MEMO "Zinc - metal content"
cap label var MF225 "Tin"
cap label var MF225MEMO "Tin - metal content"
cap label var MF226 "Gold, silver, platinum and other precious metals"
cap label var MF2261 "Gold"
cap label var MF2262 "Silver"
cap label var MF2263 "Platinum and other precious metal ores"
cap label var MF227 "Bauxite and other aluminium"
cap label var MF228 "Uranium and thorium"
cap label var MF229 "Other non-ferrous metals"
cap label var MF2291 "Tungsten"
cap label var MF2292 "Tantalum"
cap label var MF2293 "Magnesium ores"
cap label var MF2294 "Titanium"
cap label var MF2295 "Manganese"
cap label var MF2296 "Chromium"
cap label var MF2297 "Other non-ferrous metals n.e.c."
cap label var MF23 "Products mainly from metals"
cap label var MF3 "Non-metallic minerals"
cap label var MF31 "Marble, granite, sandstone, porphyry, basalt, other ornamental or building stone (excluding slate)"
cap label var MF32 "Chalk and dolomite"
cap label var MF33 "Slate"
cap label var MF34 "Chemical and fertiliser minerals"
cap label var MF35 "Salt"
cap label var MF36 "Limestone and gypsum"
cap label var MF37 "Clays and kaolin"
cap label var MF38 "Sand and gravel"
cap label var MF39 "Other non-metallic minerals n.e.c."
cap label var MF3A "Excavated earthen materials (including soil), only if used (optional reporting)"
cap label var MF3B "Products mainly from non metallic minerals"
cap label var MF4 "Fossil energy materials/carriers"
cap label var MF41 "Coal and other solid energy materials/carriers"
cap label var MF411 "Lignite (brown coal)"
cap label var MF412 "Hard coal"
cap label var MF413 "Oil shale and tar sands"
cap label var MF414 "Peat"
cap label var MF42 "Liquid and gaseous energy materials/carriers"
cap label var MF421 "Crude oil, condensate and natural gas liquids (NGL)"
cap label var MF422 "Natural gas"
cap label var MF423 "Fuels bunkered (Imports: by resident units abroad); (Exports: by non-resident units domestically)"
cap label var MF4231 "Fuel for land transport"
cap label var MF4232 "Fuel for water transport"
cap label var MF4233 "Fuel for air transport"
cap label var MF43 "Products mainly from fossil energy products"
cap label var MF5 "Other products"
cap label var MF6 "Waste for final treatment and disposal"
cap label var MF71 "Emissions to air"
cap label var MF711 "Carbon dioxide (CO2)"
cap label var MF7111 "Carbon dioxide (CO2) from biomass combustion"
cap label var MF7112 "Carbon dioxide (CO2) excluding biomass combustion"
cap label var MF712 "Methane (CH4)"
cap label var MF713 "Dinitrogen oxide (N2O)"
cap label var MF714 "Nitrous oxides (NOx)"
cap label var MF715 "Hydroflourcarbons (HFCs)"
cap label var MF716 "Perflourocarbons (PFCs)"
cap label var MF717 "Sulfur hexaflouride"
cap label var MF718 "Carbon monoxide (CO)"
cap label var MF719 "Non-methane volatile organic compounds (NMVOC)"
cap label var MF71A "Sulfur dioxide (SO2)"
cap label var MF71B "Ammonia (NH3)"
cap label var MF71C "Heavy metals"
cap label var MF71D "Persistent organic pollutants (POPs)"
cap label var MF71E "Particles (e.g. PM10, Dust)"
cap label var MF71F "Other emissions to air"
cap label var MF72 "Waste disposal to the environment"
cap label var MF72MEMO "Waste disposal to controlled landfills (memo item)"
cap label var MF721 "Disposal of municipal waste to the environment"
cap label var MF721MEMO "Disposal of municipal waste to controlled landfills (memo item)"
cap label var MF722 "Disposal of industrial waste to the environment"
cap label var MF722MEMO "Disposal of industrial waste to controlled landfills (memo item)"
cap label var MF73 "Emissions to water"
cap label var MF731 "Nitrogen (N)"
cap label var MF732 "Phosphorus (P)"
cap label var MF733 "Heavy metals"
cap label var MF734 "Other substances and (organic) materials"
cap label var MF735 "Dumping of materials at sea"
cap label var MF74 "Dissipative use of products"
cap label var MF741 "Organic fertiliser (manure)"
cap label var MF742 "Mineral fertiliser"
cap label var MF743 "Sewage sludge"
cap label var MF744 "Compost"
cap label var MF745 "Pesticides"
cap label var MF746 "Seeds"
cap label var MF747 "Salt and other thawing materials spread on roads (including grit)"
cap label var MF748 "Solvents, laughing gas and other"
cap label var MF75 "Dissipative losses"
cap label var MF81 "Balancing items: input side"
cap label var MF811 "Oxygen for combustion processes"
cap label var MF812 "Oxygen for respiration of humans and livestock; bacterial respiration from solid waste and wastewater"
cap label var MF813 "Nitrogen for Haber-Bosch process"
cap label var MF814 "Water requirements for the domestic production of exported beverages"
cap label var MF82 "Balancing items: output side"
cap label var MF821 "Water vapour from combustion"
cap label var MF8211 "Water vapour from moisture content of fuels"
cap label var MF8212 "Water vapour from the oxidised hydrogen components of fuels"
cap label var MF822 "Gases from respiration of humans and livestock (CO2 and H2O), and from bacterial respiration from solid waste and wastewater (H2O)"
cap label var MF8221 "Carbon dioxide (CO2)"
cap label var MF8222 "Water vapour (H2O)"
cap label var MF823 "Excorporated water from biomass products"
cap label var SM_FIN "Stage of Manufacturing - finished products"
cap label var SM_SFIN "Stage of Manufacturing - semi-finished products"
cap label var SM_RAW "Stage of Manufacturing - raw products"
cap label var CROC "Aggregates - crushed rock, other sands (not silica), pebbles, gravel, bitumen additives"
cap label var AL "Aluminium"
cap label var SB "Antimony"
cap label var BRT "Baryte"
cap label var BAUX "Bauxite"
cap label var BENT "Bentonite"
cap label var BE "Beryllium"
cap label var BI "Bismuth"
cap label var BOR "Borate"
cap label var CE "Cerium"
cap label var CR "Chromium"
cap label var CO "Cobalt"
cap label var COCO "Coking coal"
cap label var CU "Copper"
cap label var DIAT "Diatomite"
cap label var DY "Dysprosium"
cap label var ER "Erbium"
cap label var EU "Europium"
cap label var FSP "Feldspar"
cap label var FL "Fluorspar"
cap label var GD "Gadolinium"
cap label var GA "Gallium"
cap label var GE "Germanium"
cap label var AU "Gold"
cap label var GP "Gypsum"
cap label var HF "Hafnium"
cap label var HE "Helium"
cap label var HO "Holmium"
cap label var IN "Indium"
cap label var IR "Iridium"
cap label var FEOR "Iron ore"
cap label var FE "Iron"
cap label var KAOL "Kaolin clay"
cap label var LA "Lanthanum"
cap label var PB "Lead"
cap label var LST "Limestone"
cap label var LI "Lithium"
cap label var LU "Lutetium"
cap label var MGS "Magnesite"
cap label var MG "Magnesium"
cap label var MN "Manganese"
cap label var MO "Molybdenum"
cap label var CORK "Natural cork"
cap label var GR "Natural graphite"
cap label var RUBB "Natural rubber"
cap label var TEAK "Natural teak wood"
cap label var ND "Neodymium"
cap label var NI "Nickel"
cap label var NB "Niobium"
cap label var PD "Palladium"
cap label var PERL "Perlite"
cap label var PHOR "Phosphate rock"
cap label var P "Phosphorus"
cap label var PT "Platinum"
cap label var PTSH "Potash"
cap label var K "Potassium"
cap label var PR "Praseodymium"
cap label var RE "Rhenium"
cap label var RH "Rhodium"
cap label var RU "Ruthenium"
cap label var SM "Samarium"
cap label var SAPE "Sapele wood"
cap label var SC "Scandium"
cap label var SE "Selenium"
cap label var SLCA "Silica sand"
cap label var SIME "Silicon metal"
cap label var SI "Silicon"
cap label var AG "Silver"
cap label var S "Sulphur"
cap label var TALC "Talc"
cap label var TA "Tantalum"
cap label var TE "Tellurium"
cap label var TB "Terbium"
cap label var TM "Thulium"
cap label var SN "Tin"
cap label var TI "Titanium"
cap label var W "Tungsten"
cap label var V "Vanadium"
cap label var YB "Ytterbium"
cap label var Y "Yttrium"
cap label var ZN "Zinc"
