cap label var TIPSBP10 "Current account balance - % of GDP, 3 years average"
cap label var TIPSBP20 "Current account balance - % of GDP"
cap label var TIPSII10 "Net international investment position - % of GDP"
cap label var TIPSER10_1 "Real effective exchange rate, 42 trading partners - 1 year % change"
cap label var TIPSER10_2 "Real effective exchange rate, 42 trading partners - 3 years % change"
cap label var TIPSEX10 "Export market shares - 5 years % change"
cap label var TIPSEX20 "Export market shares - 1 year % change"
cap label var TIPSLM10 "Nominal unit labour cost index - 3 years % change"
cap label var TIPSLM20 "Nominal unit labour cost index - 1 year % change"
cap label var TIPSHO10 "House price index, deflated - 1 year % change"
cap label var TIPSPC20 "Private sector credit flow, consolidated - % of GDP"
cap label var TIPSPC10 "Private sector credit flow, non-consolidated - % of GDP"
cap label var TIPSPD20 "Private sector debt, consolidated - % of GDP"
cap label var TIPSGO10 "General government sector debt - % of GDP"
cap label var TIPSFS10_1 "Total financial sector liabilities, non-consolidated - 1 year % change"
cap label var TIPSFS10_2 "Total financial sector liabilities, non-consolidated - million of national currency"
cap label var TIPSUN10 "Unemployment rate - 3 years average"
cap label var TIPSUN20 "Unemployment rate - %"
cap label var TIPSNA10 "Real gross domestic product (GDP) - 1 year % change"
cap label var TIPSNA20 "Gross fixed capital formation - % of GDP"
cap label var TIPSST10 "Gross domestic expenditure on R&D - % of GDP"
cap label var TIPSBP70 "Net Lending / Borrowing - % of GDP"
cap label var TIPSII20 "Net external debt - % of GDP"
cap label var TIPSBP90 "Direct investment in the reporting economy (flows) - % of GDP"
cap label var TIPSBP100 "Direct investment in the reporting economy (stocks) - % of GDP"
cap label var TIPSEN10 "Net trade balance of energy products - % of GDP"
cap label var TIPSER20 "Real effective exchange rate, euro area trading partners - 3 years % change"
cap label var TIPSBP60 "Share of OECD export - 5 years % change"
cap label var TIPSNA30 "Terms of trade - 5 years % change"
cap label var TIPSEX_V "Export market share, volumes - 1 year % change"
cap label var TIPSNA70 "Labour productivity - 1 year % change"
cap label var TIPSNA40 "Nominal unit labour cost index - 10 years % change"
cap label var TIPSLM50 "Unit labour cost performance relative to euro area - 10 years % change"
cap label var TIPSHO20 "Nominal house price index - 3 years % change"
cap label var TIPSNA50 "Residential construction - % of GDP"
cap label var TIPSPD10 "Private sector debt, non-consolidated - % of GDP"
cap label var TIPSFS20 "Financial sector leverage (debt-to-equity) - %"
cap label var TIPSNA60 "Employment - 1 year % change"
cap label var TIPSLM60_1 "Activity rate (15-64 years) - % of the total population of the same age group"
cap label var TIPSLM60_2 "Activity rate (15-64 years) - % point change (t, t-3)"
cap label var TIPSLM70_1 "Long-term unemployment rate - % of active population in the same age group"
cap label var TIPSLM70_2 "Long-term unemployment rate - % of active population in the same age group, % point change (t, t-3)"
cap label var TIPSLM80_1 "Youth unemployment rate - % of active population in the same age group"
cap label var TIPSLM80_2 "Youth unemployment rate - % of active population in the same age group, % point change (t, t-3)"
cap label var TIPSLM90_1 "Young people neither in employment nor in education and training - % of total population"
cap label var TIPSLM90_2 "Young people neither in employment nor in education and training - % of total population, % point change (t, t-3)"
cap label var TIPSLC10_1 "People at risk of poverty or social exclusion - % of total population"
cap label var TIPSLC10_2 "People at risk of poverty or social exclusion - % of total population, % point change (t, t-3)"
cap label var TIPSLC20_1 "People at risk of poverty after social transferes - % of total population"
cap label var TIPSLC20_2 "People at risk of poverty after social transferes - % of total population, % point change (t, t-3)"
cap label var TIPSLC30_1 "Severely materially deprived people - % of total population"
cap label var TIPSLC30_2 "Severely materially deprived people - % of total population, % point change (t, t-3)"
cap label var TIPSLC40_1 "People living in households with very low work Intensity - % of population aged 0-59"
cap label var TIPSLC40_2 "People living in households with very low work intensity - % of population aged 0-59, % point change (t, t-3)"
cap label var TIPSBD10 "Gross non-performing loans, domestic and foreign entities - % of gross loans"
cap label var TIPSBD20 "Consolidated banking leverage, domestic and foreign entities (asset-to-equity multiple)"
cap label var TIPSII50 "Net international investment position excluding non-defaultable instruments - % of GDP"
cap label var TIPSPD22 "Household debt, consolidated including Non-profit institutions serving households - % of GDP"
