cap label var TOTAL "Total - total transport"
cap label var LOADED "Loaded - total transport"
cap label var LNAT "Loaded - national transport"
cap label var LINTL "Loaded - international transport - total"
cap label var LINTL_LD "Loaded - international - goods loaded in reporting country"
cap label var LINTL_NLD "Loaded - international - goods unloaded in reporting country"
cap label var LINTL_CTRD "Loaded - international - cross-trade"
cap label var LINTL_CAB "Loaded - international - cabotage"
cap label var EMPTY "Empty - total transport"
cap label var ENAT "Empty - national transport"
cap label var EINTL "Empty - international transport - total"
