cap label var _101_A "Number of employees in the year of enterprise birth"
cap label var _101_N "Number of units having survived from 2002 to 2005"
cap label var _201_A "Start-up type - new enterprise"
cap label var _201_C "Start-up type - reactivation after more than 2 years"
cap label var _201_T "Start-up type - Total"
cap label var _202_A "Start-up motivation - desire for new challenges"
cap label var _202_B "Start-up motivation - desire to be one's own boss"
cap label var _202_C "Start-up motivation - desire to make a living from a hobby activity"
cap label var _202_D "Start-up motivation - tradition for self-employment in the family"
cap label var _202_E "Start-up motivation - combining work and private life"
cap label var _202_F "Start-up motivation - children are big enough"
cap label var _202_G "Start-up motivation - prospect of making more money"
cap label var _202_H "Start-up motivation - realising an idea for an new product or service"
cap label var _202_I "Start-up motivation - reaching an international market"
cap label var _202_J "Start-up motivation - avoiding unemployment"
cap label var _202_K "Start-up motivation - getting away from unsatisfactory work situation"
cap label var _202_L "Start-up motivation - working as sub-contractor exclusively for former employer"
cap label var _202_M "Start-up motivation - only possibility to carry out profession"
cap label var _202_T "Start-up motivation - Total"
cap label var _203_A "Start-up financing - own funds or savings"
cap label var _203_B "Start-up financing - financial assistance from family or friends"
cap label var _203_C "Start-up financing - bank loan without collateral"
cap label var _203_D "Start-up financing - bank loan with collateral"
cap label var _203_E "Start-up financing - capital contribution from other enterprises"
cap label var _203_F "Start-up financing - venture capital"
cap label var _203_G "Start-up financing - financial support from public authorities"
cap label var _203_T "Start-up financing - Total"
cap label var _204_A "Start-up difficulties - to get financing"
cap label var _204_B "Start-up difficulties - to establish contacts with customers"
cap label var _204_C "Start-up difficulties - to obtain payment for outstanding invoices"
cap label var _204_D "Start-up difficulties - to price goods or services"
cap label var _204_E "Start-up difficulties - to find suitable premises"
cap label var _204_F "Start-up difficulties - to find suppliers"
cap label var _204_G "Start-up difficulties - to get suitable personnel"
cap label var _204_H "Start-up difficulties - to use information technology effectively"
cap label var _204_I "Start-up difficulties - to deal with legal / governmental / administrative matters"
cap label var _204_J "Start-up difficulties - to be alone as an entrepreneur"
cap label var _204_K "Start-up difficulties - to get backing from spouse or family"
cap label var _204_T "Start-up difficulties - Total"
cap label var _205_A "Previous occupation - employee"
cap label var _205_B "Previous occupation - running another enterprise"
cap label var _205_C "Previous occupation - student"
cap label var _205_D "Previous occupation - unemployed and available to labour market"
cap label var _205_E "Previous occupation - no gainful activity and not available to labour market"
cap label var _205_T "Previous occupation - Total"
cap label var _206_A "Previous branch experience - yes"
cap label var _206_B "Previous branch experience - no"
cap label var _206_T "Previous branch experience - total"
cap label var _207_A "Previous experience running an enterprise - no"
cap label var _207_B "Previous experience running an enterprise - once"
cap label var _207_C "Previous experience running an enterprise - more than once"
cap label var _207_T "Previous experience running an enterprise - Total"
cap label var _208_A "Training received to help start-up - yes, on own initiative"
cap label var _208_B "Training received to help start-up - yes, upon request of public authorities"
cap label var _208_C "Training received to help start-up - none"
cap label var _208_T "Training received to help start-up - Total"
cap label var _209_A "Sources of advice - family and friends"
cap label var _209_B "Sources of advice - training course for entrepreneurs"
cap label var _209_C "Sources of advice - professional acquaintances"
cap label var _209_D "Sources of advice - professional consultants"
cap label var _209_E "Sources of advice - unemployment administration"
cap label var _209_F "Sources of advice - organisations specialising in business start-ups"
cap label var _209_G "Sources of advice - financial institution"
cap label var _209_H "Sources of advice - no access to any relevant advice"
cap label var _209_I "Sources of advice - no advice needed"
cap label var _209_T "Sources of advice - Total"
cap label var _210_A "Other current gainful activity - yes"
cap label var _210_B "Other current gainful activity - no"
cap label var _210_T "Other current gainful activity - Total"
cap label var _211_A "Age group - below 30 years"
cap label var _211_B "Age group - 30 to 39 years"
cap label var _211_C "Age group - 40 years or older"
cap label var _211_T "Age group - Total"
cap label var _212_A "Gender - female"
cap label var _212_B "Gender - male"
cap label var _212_T "Gender - Total"
cap label var _213_A "Citizenship - domestic"
cap label var _213_B "Citizenship - foreign - within EU"
cap label var _213_C "Citizenship - foreign - outside EU"
cap label var _213_T "Citizenship - Total"
cap label var _214_A "Educational background - ISCED 1 or 2"
cap label var _214_B "Educational background - ISCED 3"
cap label var _214_C "Educational background - ISCED 4"
cap label var _214_D "Educational background - ISCED 5 or 6"
cap label var _214_T "Educational background - Total"
cap label var _301_A "Current management - alone"
cap label var _301_B "Current management - with someone else"
cap label var _301_C "Current management - paid managers only"
cap label var _301_T "Current management - Total"
cap label var _302_A "Persons employed - unpaid or self-employed"
cap label var _302_B "Persons employed - paid employees"
cap label var _303_A "Turnover in 2004"
cap label var _304_A "Turnover in 2005"
cap label var _305_A "Origin of turnover - 1 customer"
cap label var _305_B "Origin of turnover - 2 to 4 customers"
cap label var _305_C "Origin of turnover - 5 or more customers"
cap label var _305_T "Origin of turnover - Total"
cap label var _306_A "Sales markets - local/regional"
cap label var _306_B "Sales markets - national"
cap label var _306_C "Sales markets - within EU"
cap label var _306_D "Sales markets - outside EU"
cap label var _306_T "Sales markets - Total"
cap label var _307_A "Judgement of profitability - very good"
cap label var _307_B "Judgement of profitability - good"
cap label var _307_C "Judgement of profitability - barely sufficient"
cap label var _307_D "Judgement of profitability - poor"
cap label var _307_T "Judgement of profitability - Total"
cap label var _308_A "Cooperation with other enterprises - in a network"
cap label var _308_B "Cooperation with other enterprises - as subcontractor"
cap label var _308_C "Cooperation with other enterprises - as a franchisee or licensee"
cap label var _308_D "Cooperation with other enterprises - in a joint venture"
cap label var _308_E "Cooperation with other enterprises - none / not relevant"
cap label var _308_T "Cooperation with other enterprises - Total"
cap label var _309_A "Innovation in the enterprise - product innovation"
cap label var _309_B "Innovation in the enterprise - process innovation"
cap label var _309_C "Innovation in the enterprise - organisational innovation"
cap label var _309_D "Innovation in the enterprise - marketing innovation"
cap label var _309_T "Innovation in the enterprise - Total"
cap label var _310_A "Impediments to selling products or services - competition too vigorous"
cap label var _310_B "Impediments to selling products or services - too little demand"
cap label var _310_C "Impediments to selling products or services - difficult pricing"
cap label var _310_D "Impediments to selling products or services - lack of marketing skills"
cap label var _310_T "Impediments to selling products or services - Total"
cap label var _311_A "Impediments to developing the business activity - profitability"
cap label var _311_B "Impediments to developing the business activity - availability of bank loans"
cap label var _311_C "Impediments to developing the business activity - availability of risk capital"
cap label var _311_D "Impediments to developing the business activity - availability of short term credit"
cap label var _311_E "Impediments to developing the business activity - availability of qualified personnel"
cap label var _311_F "Impediments to developing the business activity - staff costs"
cap label var _311_G "Impediments to developing the business activity - regulatory and administrative burden"
cap label var _311_H "Impediments to developing the business activity - adapting to new technical standards"
cap label var _311_I "Impediments to developing the business activity - availability of managerial competences"
cap label var _311_J "Impediments to developing the business activity - combining family and work"
cap label var _311_K "Impediments to developing the business activity - finding partners"
cap label var _311_L "Impediments to developing the business activity - non or late paying customers"
cap label var _311_T "Impediments to developing the business activity - Total"
cap label var _401_A "Strategic plans - continuing the enterprise"
cap label var _401_B "Strategic plans - affiliation"
cap label var _401_C "Strategic plans - close and start new enterprise in the same activity"
cap label var _401_D "Strategic plans - close and start new enterprise in another activity"
cap label var _401_E "Strategic plans - close without starting new enterprise"
cap label var _401_T "Strategic plans - Total"
cap label var _402_A "Expected development of business activity - increase of turnover"
cap label var _402_B "Expected development of business activity - increase of number of employees"
cap label var _402_C "Expected development of business activity - increase of variety of goods and services for sale"
cap label var _402_D "Expected development of business activity - increase of profitability"
cap label var _402_T "Expected development of business activity - Total"
cap label var _403_A "Highest priority if earnings increase - hire more employees"
cap label var _403_B "Highest priority if earnings increase - increase remuneration of employees"
cap label var _403_C "Highest priority if earnings increase - invest in the activity of the enterprise"
cap label var _403_D "Highest priority if earnings increase - pay off loans or credits"
cap label var _403_E "Highest priority if earnings increase - increase own salary from the enterprise"
cap label var _403_F "Highest priority if earnings increase - reduce own working time"
cap label var _403_G "Highest priority if earnings increase - none / not relevant"
cap label var _403_T "Highest priority if earnings increase - Total"
