cap label var TOTAL "Total"
cap label var A_R_V_Y "All causes of death (A00-Y89) excluding S00-T98"
cap label var A_T_Z "All causes of diseases (A00-Z99) excluding V00-Y98"
cap label var A_T_Z_XNB "All causes of diseases (A00-Z99) excluding V00-Y98 and Z38"
cap label var A_B "Certain infectious and parasitic diseases (A00-B99)"
cap label var INFECT "Certain infectious diseases (A00-A40, A42-B99)"
cap label var BAC_PRO "Selected invasive bacterial and protozoal infections (A38-A41, A46, A481, B50-B54, G00, G03, J02, L03)"
cap label var A15_A19_B90_J65 "Tuberculosis (incl. sequelae of tuberculosis)"
cap label var A15_A19_B90 "Tuberculosis"
cap label var A00_A08 "Intestinal infectious diseases except diarrhoea"
cap label var A00_A09 "Intestinal infectious diseases"
cap label var A00 "Cholera"
cap label var A01 "Typhoid and paratyphoid fevers"
cap label var A02 "Other salmonella infections"
cap label var A03 "Shigellosis"
cap label var A06 "Amoebiasis"
cap label var A09 "Diarrhoea and gastroenteritis of presumed infectious origin"
cap label var A15 "Respiratory tuberculosis bacteriologically and histologically confirmed"
cap label var A21 "Tularaemia"
cap label var A22 "Anthrax"
cap label var A23 "Brucellosis"
cap label var A26 "Erysipeloid"
cap label var A27 "Leptospirosis"
cap label var A33 "Tetanus neonatorum"
cap label var A34 "Obstetrical tetanus"
cap label var A35_A36_A80 "Diphtheria, Tetanus, Poliomyelitis"
cap label var A35 "Other tetanus"
cap label var A36 "Diphtheria"
cap label var A37 "Whooping cough"
cap label var A38 "Scarlet fever"
cap label var A39 "Meningococcal infection"
cap label var A403_A413 "Sepsis due to streptococcus pneumoniae and sepsis due to hemophilus influenzae"
cap label var SEPSIS "Sepsis (A40 (excl. A403), A41 (excl. A413))"
cap label var A40_A41 "Septicaemia"
cap label var A41 "Other sepsis"
cap label var A46_L03 "Cellulitis"
cap label var A46 "Erysipelas"
cap label var A481 "Legionnaires disease"
cap label var A491 "Streptococcal and enterococcal infection, unspecified site"
cap label var A492 "Haemophilus influenzae infections, unspecified site"
cap label var A50_A60_A63_A64 "Sexually transmitted infections (except HIV/AIDS)"
cap label var A70 "Chlamydia psittaci infections"
cap label var A78 "Q fever"
cap label var A79 "Other rickettsioses"
cap label var A80 "Acute poliomyelitis"
cap label var A82 "Rabies"
cap label var B01 "Varicella [chickenpox]"
cap label var B05 "Measles"
cap label var B06 "Rubella"
cap label var B15_B19_B942 "Viral hepatitis and sequelae of viral hepatitis"
cap label var B15_B19 "Viral hepatitis"
cap label var B15 "Acute hepatitis A"
cap label var B16 "Acute hepatitis B"
cap label var B171_B182 "Hepatitis C"
cap label var B180_B182 "Chronic viral hepatitis B and C"
cap label var B20_B24 "Human immunodeficiency virus [HIV] disease"
cap label var B24 "Unspecified human immunodeficiency virus [HIV] disease"
cap label var B26 "Mumps"
cap label var B50_B54 "Malaria"
cap label var B54 "Unspecified malaria"
cap label var A_B_OTH "Other infectious and parasitic diseases (remainder of A00-B99)"
cap label var C00_D48 "Neoplasms"
cap label var C "Malignant neoplasms (C00-C97)"
cap label var C00_C14 "Malignant neoplasm of lip, oral cavity, pharynx"
cap label var C15 "Malignant neoplasm of oesophagus"
cap label var C16 "Malignant neoplasm of stomach"
cap label var C18_C21 "Malignant neoplasm of colon, rectosigmoid junction, rectum, anus and anal canal"
cap label var C18 "Malignant neoplasm of colon"
cap label var C19_C21 "Malignant neoplasm of rectosigmoid junction, rectum, anus and anal canal"
cap label var C22 "Malignant neoplasm of liver and intrahepatic bile ducts"
cap label var C25 "Malignant neoplasm of pancreas"
cap label var C31 "Malignant neoplasm of accessory sinuses"
cap label var C32_C34 "Malignant neoplasm of larynx, trachea, bronchus and lung"
cap label var C32 "Malignant neoplasm of larynx"
cap label var C33_C34 "Malignant neoplasm of trachea, bronchus and lung"
cap label var C33 "Malignant neoplasm of trachea"
cap label var C34 "Malignant neoplasm of bronchus and lung"
cap label var C34_C45 "Selected occupational cancers"
cap label var C43_C44 "Malignant neoplasms of skin"
cap label var C43 "Malignant melanoma of skin"
cap label var C44 "Other malignant neoplasms of skin"
cap label var C45 "Mesothelioma"
cap label var C50 "Malignant neoplasm of breast"
cap label var C50_FEM_ONL "Malignant neoplasm of breast (female only)"
cap label var C53_C55 "Malignant neoplasm of uterus"
cap label var C53 "Malignant neoplasm of cervix uteri"
cap label var C54_C55 "Malignant neoplasm of other parts of uterus"
cap label var C54__C55 "Malignant neoplasm of corpus uteri or of uterus, part unspecified"
cap label var C54 "Malignant neoplasm of corpus uteri"
cap label var C56 "Malignant neoplasm of ovary"
cap label var C61 "Malignant neoplasm of prostate"
cap label var C62 "Malignant neoplasm of testis"
cap label var C64 "Malignant neoplasm of kidney, except renal pelvis"
cap label var C67 "Malignant neoplasm of bladder"
cap label var C70_C72 "Malignant neoplasm of brain and central nervous system"
cap label var C71 "Malignant neoplasm of brain"
cap label var C73 "Malignant neoplasm of thyroid gland"
cap label var C81_C96 "Malignant neoplasms, stated or presumed to be primary, of lymphoid, haematopoietic and related tissue"
cap label var C81_C86 "Hodgkin disease and lymphomas"
cap label var C81 "Hodgkin disease"
cap label var C88_C90_C96 "Other malignant neoplasm of lymphoid, haematopoietic and related tissue"
cap label var C91_C95 "Leukaemia"
cap label var C910_911 "Acute lymphoblastic leukaemia [ALL] and chronic lymphocytic leukaemia of B-cell type"
cap label var C91_C920 "Lymphoid and acute myeloblastic leukaemia"
cap label var C95 "Leukaemia of unspecified cell type"
cap label var C_OTH "Other malignant neoplasms (remainder of C00-C97)"
cap label var D00_D48 "Non-malignant neoplasms (benign and uncertain)"
cap label var D00_D09 "In situ neoplasms"
cap label var D04 "Carcinoma in situ of skin"
cap label var D10_D36 "Benign neoplasms"
cap label var D12 "Benign neoplasm of colon, rectum, anus and anal canal"
cap label var D25 "Leiomyoma of uterus"
cap label var D00_D48_OTH "Other in situ neoplasms, benign neoplasms and neoplasms of uncertain or unknown behaviour (remainder of D00-D48)"
cap label var D50_D53 "Nutritional deficiency anaemias"
cap label var D50_D89 "Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism"
cap label var D50_D64 "Anaemias"
cap label var D59 "Acquired haemolytic anaemia"
cap label var D64 "Other anaemias"
cap label var D65_D89 "Other diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism"
cap label var D70 "Agranulocytosis"
cap label var E "Endocrine, nutritional and metabolic diseases (E00-E90)"
cap label var E00_E07 "Thyroid disorders"
cap label var E10_E14 "Diabetes mellitus"
cap label var ADR "Adrenal disorders"
cap label var E_OTH "Other endocrine, nutritional and metabolic diseases (remainder of E00-E90)"
cap label var ALC_POIS "Alcohol-specific disorders and poisonings (E244, F10, G312, G621, G721, I426, K292, K70,K852, K860, Q860, R780, X45, X65, Y15)"
cap label var ALC_XEXT "Alcohol related diseases, excluding external causes (F10, G312, G621, I426, K292, K70, K73, K740-K742, K746, K860)"
cap label var ALC_OTH "Other alcohol-related disorders (K73, K740-K742, K746)"
cap label var F01_F03_G30 "Dementia including Alzheimer disease"
cap label var DRUG_POIS "Drug disorders and poisonings (F11-F16, F18-F19, X40-X44, X85, Y10-Y14)"
cap label var F "Mental and behavioural disorders (F00-F99)"
cap label var F00__F03 "Dementia"
cap label var F00_F03 "Dementia"
cap label var F01_F03 "Dementia"
cap label var F10 "Mental and behavioural disorders due to use of alcohol"
cap label var F11_F19 "Mental and behavioural disorders due to psychoactive substance use"
cap label var TOXICO "Drug dependence, toxicomania (F11-F16, F18-F19)"
cap label var F20_F29 "Schizophrenia, schizotypal and delusional disorders"
cap label var F20 "Schizophrenia"
cap label var F30_F39 "Mood [affective] disorders"
cap label var F31 "Bipolar affective disorder"
cap label var F32_F33 "Depressive disorders"
cap label var F_OTH "Other mental and behavioural disorders (remainder of F00-F99)"
cap label var INFECT_OTH "Other infectious diseases (G00, G03-G04, G06, G08-G09, H00-H01, H10, H16, H20, H30, H46, H60, H65-H66, H68, H70, I00-I02, I30, I33, I38, I40, I80, J00-J16, J20-J22, J31-J32, J36-J37, J40-J42, J85-J86, K04-K05, K20, K29, K35-K37, K61, K65, K73, K75, K81, K85, L00-L08, M00, M02, N10-N12, N15, N30, N34, N39, N41, N45, N49, N61, N70-N73, N75-N76, O23, O85-O86, O91, O98, P35-P39, R50)"
cap label var G_H "Diseases of the nervous system and the sense organs (G00-H95)"
cap label var G "Diseases of the nervous system (G00-G99)"
cap label var G000_G001 "Haemophilus and pneumococcal meningitis"
cap label var G00_G03 "Meningitis"
cap label var G03 "Meningitis due to other and unspecified causes"
cap label var MENING_OTH "Other meningitis"
cap label var G20 "Parkinson disease"
cap label var G30 "Alzheimer disease"
cap label var G35 "Multiple sclerosis"
cap label var G40_G41 "Epilepsy, status epilepticus"
cap label var G40__G41 "Epilepsy and status epilepticus"
cap label var G40 "Epilepsy"
cap label var G45 "Transient cerebral ischaemic attacks and related syndromes"
cap label var G50 "Disorders of trigeminal nerve"
cap label var G56 "Mononeuropathies of upper limb"
cap label var G92 "Toxic encephalopathy"
cap label var G_OTH "Other diseases of the nervous system (remainder of G00-G99)"
cap label var H "Diseases of sensory organs (H00-H95)"
cap label var H00_H59 "Diseases of the eye and adnexa"
cap label var H10 "Conjunctivitis"
cap label var H25_H26_H28 "Cataract"
cap label var H00_H59_OTH "Other diseases of the eye and adnexa (remainder of H00-H59)"
cap label var H60_H95 "Diseases of the ear and mastoid process"
cap label var H83 "Other diseases of inner ear"
cap label var G_H_OTH "Other diseases of the nervous system and the sense organs (remainder of G00-H95)"
cap label var I "Diseases of the circulatory system (I00-I99)"
cap label var I00_I09 "Acute rheumatic fever and chronic rheumatic heart diseases"
cap label var I01_I09 "Rheumatic and other valvular heart disease"
cap label var I10_I15 "Hypertensive diseases"
cap label var I10_I13_I15 "Hypertensive diseases"
cap label var I20_I25 "Ischaemic heart diseases"
cap label var I20 "Angina pectoris"
cap label var I21_I22 "Acute myocardial infarction including subsequent myocardial infarction"
cap label var I21 "Acute myocardial infarction"
cap label var I20_I23_I25 "Other ischaemic heart diseases"
cap label var I23_I25 "Other ischaemic heart disease"
cap label var THROM_PU_EMB "Thrombosis with pulmonary embolism (I26, I801-I803, I809, I829)"
cap label var I26_I28 "Pulmonary heart disease and diseases of pulmonary circulation"
cap label var I26_I80_I829 "Venous thromboembolism"
cap label var I30_I51 "Other heart diseases"
cap label var HEART_OTH "Other heart diseases (I30-I33, I39-I52)"
cap label var I44_I49 "Conduction disorders and cardiac arrhythmias"
cap label var I50 "Heart failure"
cap label var I60_I69 "Cerebrovascular diseases"
cap label var I70 "Atherosclerosis"
cap label var I70_I739 "Other atherosclerosis"
cap label var I71 "Aortic aneurysm and dissection"
cap label var I73 "Other peripheral vascular diseases"
cap label var I83 "Varicose veins of lower extremities"
cap label var I_OTH "Other diseases of the circulatory system (remainder of I00-I99)"
cap label var J "Diseases of the respiratory system (J00-J99)"
cap label var J00_J06_J30_J39 "Upper respiratory infections"
cap label var LUNG_EXT "Lung diseases due to external agents"
cap label var J00_J11 "Acute upper respiratory infections and influenza"
cap label var J09_J11 "Influenza (including swine flu)"
cap label var J10_J11 "Influenza"
cap label var J12_J18 "Pneumonia"
cap label var J12_J15_J18 "Pneumonia, not elsewhere classified or organism unspecified"
cap label var J13_J14 "Pneumonia due to streptococcus pneumonia or haemophilus influenzae"
cap label var J18 "Pneumonia, organism unspecified"
cap label var J20_J22 "Other acute lower respiratory infections"
cap label var J35 "Chronic diseases of tonsils and adenoids"
cap label var UPRESPIR_OTH "Other diseases of upper respiratory tract (J30-J34, J36-J39)"
cap label var J40_J44 "Chronic obstructive pulmonary disorder"
cap label var J41_J44 "Chronic bronchitis, emphysema, other chronic obstructive pulmonary disease"
cap label var J40_J47 "Chronic lower respiratory diseases"
cap label var J44 "Other chronic obstructive pulmonary disease"
cap label var J45_J46 "Asthma and status asthmaticus"
cap label var J45_J47 "Asthma and bronchiectasis"
cap label var J45 "Asthma"
cap label var J40_J44_J47 "Other lower respiratory diseases"
cap label var J60_J99 "Other diseases of the respiratory system"
cap label var J60 "Coalworker's pneumoconiosis"
cap label var J61_J62 "Pneumoconiosis"
cap label var J61 "Pneumoconiosis due to asbestos and other mineral fibres"
cap label var J62 "Pneumoconiosis due to dust containing silica"
cap label var J65 "Pneumoconiosis associated with tuberculosis"
cap label var J67 "Hypersensitivity pneumonitis due to organic dust"
cap label var J80 "Adult respiratory distress syndrome"
cap label var J81 "Pulmonary oedema"
cap label var J85_J86 "Abscess of lung and mediastinum, pyothorax"
cap label var J90_J93_J94 "Other pleural disorders"
cap label var J90 "Pleural effusion, not elsewhere classified"
cap label var J92 "Pleural plaque"
cap label var J_OTH "Other diseases of the respiratory system (remainder of J00-J99)"
cap label var K "Diseases of the digestive system (K00-K93)"
cap label var K00_K08 "Disorders of teeth and supporting structures"
cap label var K09_K14 "Other diseases of oral cavity, salivary glands and jaws"
cap label var K20_K23 "Diseases of oesophagus"
cap label var K25_K28 "Ulcer of stomach, duodenum and jejunum"
cap label var K29_K31 "Dyspepsia and other diseases of stomach and duodenum"
cap label var ACUTE_INTEST "Acute abdomen, appendicitis, intestinal obstruction, cholecystitis/lithiasis, pancreatitis, hernia (K35-K38, K40-K46, K80-K83, K85, K861-K869, K915)"
cap label var K35_K38 "Diseases of appendix"
cap label var K40 "Inguinal hernia"
cap label var K40_K46 "Hernia"
cap label var K41_K46 "Other abdominal hernia"
cap label var K50_K51 "Crohn disease and ulcerative colitis"
cap label var K52 "Other noninfective gastroenteritis and colitis"
cap label var K56 "Paralytic ileus and intestinal obstruction without hernia"
cap label var K57 "Diverticular disease of intestine"
cap label var K60_K62 "Diseases of anus and rectum"
cap label var INTESTINE_OTH "Other diseases of intestine (K55,K58-K59,K63)"
cap label var K70_K73_K74 "Chronic liver disease"
cap label var K70 "Alcoholic liver disease"
cap label var K71_K77 "Other diseases of liver"
cap label var K71 "Toxic liver disease"
cap label var K72_K75 "Chronic liver disease (excluding alcoholic and toxic liver disease)"
cap label var K80 "Cholelithiasis"
cap label var K80_K81 "Cholelithiasis and cholecystitis"
cap label var K81_K83 "Other diseases of gallbladder and biliary tract"
cap label var K82_K83 "Other diseases of gallbladder or biliary tract"
cap label var K85_K87 "Diseases of pancreas"
cap label var K_OTH "Other diseases of the digestive system (remainder of K00-K93)"
cap label var ACUTE_PANC "Acute pancreatitis"
cap label var PANC_OTH "Other diseases of pancreas"
cap label var L "Diseases of the skin and subcutaneous tissue (L00-L99)"
cap label var L00_L08 "Infections of the skin and subcutaneous tissue"
cap label var L20_L45 "Dermatitis, eczema and papulosquamous disorders"
cap label var L23_L24 "Contact dermatitis"
cap label var L23 "Allergic contact dermatitis"
cap label var L24 "Irritant contact dermatitis"
cap label var L_OTH "Other diseases of the skin and subcutaneous tissue (remainder of L00-L99)"
cap label var M "Diseases of the musculoskeletal system and connective tissue (M00-M99)"
cap label var RHEUM_ARTHRO "Rheumatoid arthritis and arthrosis (M05-M06,M15-M19)"
cap label var M16 "Coxarthrosis [arthrosis of hip]"
cap label var M17 "Gonarthrosis [arthrosis of knee]"
cap label var M23 "Internal derangement of knee"
cap label var ARTHROPAT_OTH "Other arthropathies (M00-M15, M18-M22 ,M24-M25)"
cap label var M30_M36 "Systemic connective tissue disorders"
cap label var M40_M49 "Deforming dorsopathies and spondylopathies"
cap label var M50_M51 "Cervical disc disorders, other intervertebral disc disorders"
cap label var MSK "Selected musculoskeletal disorders (M51, M65, M70, M75, M77, G56, I73)"
cap label var M51 "Other intervertebral disc disorders"
cap label var M54 "Dorsalgia"
cap label var M60_M79 "Soft tissue disorders"
cap label var M53_M80_M99 "Other disorders of the musculoskeletal system and connective tissue"
cap label var M65 "Synovitis and tenosynovitis"
cap label var M70 "Soft tissue disorders related to use, overuse and pressure"
cap label var M75 "Shoulder lesions"
cap label var M77 "Other enthesopathies"
cap label var M_OTH "Other diseases of the musculoskeletal system and connective tissue (remainder of M00-M99)"
cap label var N "Diseases of the genitourinary system (N00-N99)"
cap label var N00_N07 "Nephritis and nephrosis"
cap label var N00_N29 "Diseases of kidney and ureter"
cap label var N00_N16 "Glomerular and renal tubulo-interstitial diseases"
cap label var NEPHR "Nephritis and nephrosis (N00-N07, N17-N19, N25-N27)"
cap label var URO_PROST "Obstructive uropathy and prostatic hyperplasia (N13, N20-N21, N35, N40, N991)"
cap label var N13_N20_N21_N35 "Obstructive uropathy"
cap label var N14 "Drug- and heavy-metal-induced tubulo-interstitial and tubular conditions"
cap label var N17_N19 "Renal failure"
cap label var N18 "Chronic renal failure"
cap label var N20_N23 "Urolithiasis"
cap label var N25_N39 "Other diseases of the urinary system"
cap label var N23 "Unspecified renal colic"
cap label var N25 "Disorders resulting from impaired renal tubular function"
cap label var N26_N27 "Unspecified contracted kidney, small kidney of unknown cause"
cap label var N40 "Hyperplasia of prostate"
cap label var N41_N51 "Other diseases of male genital organs"
cap label var N60_N64 "Disorders of breast"
cap label var N70_N77 "Inflammatory diseases of female pelvic organs"
cap label var N91_N95 "Menstrual, menopausal and other female genital conditions"
cap label var INFLM_GENITUR "Inflammatory diseases of genitourinary system"
cap label var N_OTH "Other diseases of the genitourinary system (remainder of N00-N99)"
cap label var O "Pregnancy, childbirth and the puerperium (O00-O99)"
cap label var O04 "Medical abortion"
cap label var ABORT_OTH "Other pregnancy with abortive outcome (O00-O03,O05-O08)"
cap label var O10_O48 "Complications of pregnancy predominantly in the antenatal period"
cap label var O60_O75 "Complications of labour and delivery"
cap label var O80 "Single spontaneous delivery"
cap label var O81_O84 "Other delivery"
cap label var O85_O92 "Complications predominantly related to the puerperium"
cap label var O95_O99 "Other obstetric conditions"
cap label var P "Certain conditions originating in the perinatal period (P00-P96)"
cap label var P00_P96_A33 "Complications of perinatal period"
cap label var P00_P04 "Fetus and newborn affected by maternal factors and by complications of pregnancy, labour and delivery"
cap label var P05_P08 "Disorders related to length of gestation and fetal growth"
cap label var P07 "Disorders related to short gestation and low birth weight, not elsewhere classified"
cap label var PERINAT_OTH "Other perinatal conditions (P10-P15, P70-P74, P76-P78, P80-P83, P90-P96)"
cap label var P20_P29 "Respiratory and cardiovascular disorders specific to the perinatal period"
cap label var P20_P21 "Intrauterine hypoxia and birth asphyxia"
cap label var P22 "Respiratory distress of newborn"
cap label var P23_P29 "Other respiratory disorders originating in the perinatal period"
cap label var P35_P39 "Infections specific to the perinatal period"
cap label var P50_P61 "Haemorrhagic and haematological disorders of fetus and newborn"
cap label var P_OTH "Other conditions originating in the perinatal period (remainder of P00-P96)"
cap label var Q "Congenital malformations, deformations and chromosomal abnormalities (Q00-Q99)"
cap label var Q00_Q01_Q05 "Certain congenital malformations (neural tube defects)"
cap label var Q00_Q07 "Congenital malformations of the nervous system"
cap label var MALFORM_OTH "Other malformations (Q10-Q18, Q30-Q89)"
cap label var Q20_Q28 "Congenital malformations of the circulatory system"
cap label var Q30_Q34 "Congenital malformations of the respiratory system"
cap label var Q60_Q64 "Congenital malformations of the urinary system"
cap label var Q65_Q79 "Congenital malformations and deformations of the musculoskeletal system"
cap label var Q90_Q99 "Chromosomal abnormalities, not elsewhere classified"
cap label var Q_OTH "Other congenital malformations and chromosomal abnormalities"
cap label var R "Symptoms, signs and abnormal clinical and laboratory findings, not elsewhere classified (R00-R99)"
cap label var R07 "Pain in throat and chest"
cap label var R10 "Abdominal and pelvic pain"
cap label var R69 "Unknown and unspecified causes of morbidity"
cap label var R95 "Sudden infant death syndrome"
cap label var R96_R99 "Ill-defined and unknown causes of mortality"
cap label var R_OTH "Other symptoms, signs and abnormal clinical and laboratory findings (remainder of R00-R99)"
cap label var S_T "Injury, poisoning and certain other consequences of external causes (S00-T98)"
cap label var INJ_OTH "Other injuries (S10-S51, S53-S71, S73-S81, S83-T14, T79)"
cap label var S06 "Intracranial injury"
cap label var INJ_HEAD_OTH "Other injuries to the head (S00-S05, S07-S09)"
cap label var S52 "Fracture of forearm"
cap label var S72 "Fracture of femur"
cap label var S82 "Fracture of lower leg, including ankle"
cap label var S93 "Dislocation, sprain and strain of joints and ligaments at ankle and foot level"
cap label var T20_T32 "Burns and corrosions"
cap label var T36_T65 "Poisonings by drugs, medicaments and biological substances and toxic effects"
cap label var T80_T88 "Complications of surgical and medical care, not elsewhere classified"
cap label var T90_T98 "Sequelae of injuries, of poisoning and of other consequences of external causes"
cap label var S_T_OTH "Other and unspecified effects of external causes (remainder of S00-T98)"
cap label var U071 "COVID-19, virus identified"
cap label var U072 "COVID-19, virus not identified"
cap label var U_COV19 "COVID-19, virus identified and not identified (U071, U072)"
cap label var U_COV19_OTH "COVID-19, other"
cap label var V01_Y89 "External causes of morbidity and mortality (V01-Y89)"
cap label var ACC "Accidents (V01-X59, Y85, Y86)"
cap label var V_Y85 "Transport accidents (V01-V99, Y85)"
cap label var V01_X59 "Accidents"
cap label var V "Transport accidents (V01-V99)"
cap label var V01_V09 "Pedestrian injured in transport accident"
cap label var V10_V19 "Pedal cyclist injured in transport accident"
cap label var V20_V29 "Motorcycle rider injured in transport accident"
cap label var V30_V39 "Occupant of three-wheeled motor vehicle injured in transport accident"
cap label var V40_V49 "Car occupant injured in transport accident"
cap label var V50_V59 "Occupant of pick-up truck or van injured in transport accident"
cap label var V60_V69 "Occupant of heavy transport vehicle injured in transport accident"
cap label var V70_V79 "Bus occupant injured in transport accident"
cap label var ACC_TRA_OTH "Other land transport accidents, other and unspecified transport accidents (V80-V89, V98-V99)"
cap label var ACC_TRNS_OTH "Other land transport accidents, other and unspecified transport accidents (V80-V89, V98-V99)"
cap label var W00_X59 "Other external causes of accidental injury"
cap label var ACC_OTH "Other accidents (W20-W64, W75-X39, X50-X59, Y86)"
cap label var W00_W19 "Falls"
cap label var W65_W74 "Accidental drowning and submersion"
cap label var W00_X39_X46_X59 "Accidental injuries"
cap label var SUIC_SELFINJ "Suicide and self-inflicted injuries (X60-X84, Y10-Y34)"
cap label var X60_X84_Y870 "Intentional self-harm"
cap label var X40_X49 "Accidental poisoning by and exposure to noxious substances"
cap label var X60_X64 "Intentional self-poisoning by drugs"
cap label var X60_X84 "Intentional self-harm"
cap label var X66_X84 "Intentional self-harm (not relating to alcohol and drugs)"
cap label var X85_Y09_Y871 "Assault"
cap label var X85_Y09 "Assault"
cap label var X86_Y09 "Assault (except by drugs, medicaments and biological substances)"
cap label var Y10_Y34_Y872 "Event of undetermined intent"
cap label var Y10_Y34 "Event of undetermined intent"
cap label var Y16_Y34 "Event of undetermined intent (not relating to alcohol and drugs)"
cap label var Y40_Y59 "Drugs, medicaments and biological substances causing adverse effects in therapeutic use"
cap label var Y60_Y69_Y83_Y84 "Misadventures to patients during surgical and medical care"
cap label var Y70_Y82 "Medical devices associated with adverse incidents in diagnostic and therapeutic use"
cap label var SURG_MED_MIS "Misadventures to patients during surgical and medical care (Y60-Y69, Y83-Y84)"
cap label var V01_Y89_OTH "Other external causes of morbidity and mortality (remainder of V01-Y89)"
cap label var Z "Factors influencing health status and contact with health services (Z00-Z99)"
cap label var Z03 "Medical observation and evaluation for suspected diseases and conditions"
cap label var Z30 "Contraceptive management"
cap label var Z38 "Liveborn infants according to place of birth"
cap label var Z51 "Other medical care"
cap label var Z_OTH "Other factors influencing health status and contact with health services (remainder of Z00-Z99)"
cap label var U "Codes for special purposes (U00-U99)"
cap label var OTH "All categories not elsewhere classified"
cap label var UNK "Unknown"
