cap label var MF000 "Total whole milk (availabilities = utilization)"
cap label var MF001 "Cows' milk - Total"
cap label var MF002 "Ewes' milk"
cap label var MF003 "Goats' milk"
cap label var MF004 "Buffalo milk"
cap label var MF008 "Milk from non-dairy cows"
cap label var MF009 "Dairy cows' milk"
cap label var COWYI "Milk yield per dairy cow (kg of milk per year)"
cap label var MF010 "Total skimmed milk and buttermilk (availabilities = utilization)"
cap label var MF011 "Skimmed milk and buttermilk returned by dairies"
cap label var MF012 "Skimmed milk and buttermilk : Balance of cream deliveries"
cap label var MF013 "Skimmed milk and buttermilk from butter and cream production"
cap label var MF030 "Farm butter and cream"
cap label var MF110 "Drinking milk - Total"
cap label var MF118 "Drinking milk - Direct sales"
cap label var MF119 "Drinking milk - Home consumption"
cap label var MF130 "Farm cream"
cap label var MF131 "Farm cream delivered to dairies"
cap label var MF230 "Farm butter"
cap label var MF231 "Farm butter delivered to dairies"
cap label var MF240 "Farm cheese"
cap label var MF241 "Farm cheese delivered to dairies"
cap label var MF290 "Other products"
cap label var MF291 "Other products delivered to dairies (products obtained)"
cap label var MF400 "Delivered to dairies"
cap label var MF410 "Milk delivered to dairies"
cap label var MF430 "Cream delivered to dairies (in milk equivalent)"
cap label var MF490 "Other products delivered to dairies (utilization)"
cap label var MF520 "Feed"
cap label var MF600 "Differences and losses"
cap label var MC000 "Availabilities (total)"
cap label var MC001 "Cows' milk collection"
cap label var MC002 "Ewes' collection milk"
cap label var MC003 "Goats' collection milk"
cap label var MC004 "Buffalos' collection milk"
cap label var MC005 "Cream collection (in milk equivalent)"
cap label var MC009 "Other products collected from farm"
cap label var MC006 "Skimmed milk and buttermilk"
cap label var MC010 "Imports of whole milk (including raw milk)"
cap label var MC020 "Imports (intra-EU) of whole milk (including raw milk)"
cap label var MC014 "Imports of skimmed milk"
cap label var MC024 "Imports (intra-EU) of skimmed milk"
cap label var MC015 "Imports of cream (in milk equivalent)"
cap label var MC025 "Imports (intra-EU) of cream (in milk equivalent)"
cap label var MC019 "Imports of other products"
cap label var MC029 "Imports (intra-EU) of other products"
cap label var MC100 "Fresh products"
cap label var MC110 "Drinking milk"
cap label var MC111 "Raw milk"
cap label var MC112 "Whole milk"
cap label var MC922 "Whole milk pasteurised"
cap label var MC932 "Whole milk sterilised"
cap label var MC942 "Whole milk uperised"
cap label var MC113 "Semi-skimmed milk"
cap label var MC923 "Semi-skimmed milk pasteurised"
cap label var MC933 "Semi-skimmed milk sterilised"
cap label var MC943 "Semi-skimmed milk uperised"
cap label var MC114 "Skimmed milk"
cap label var MC924 "Skimmed milk pasteurised"
cap label var MC934 "Skimmed milk sterilised"
cap label var MC944 "Skimmed milk uperised"
cap label var MC120 "Buttermilk"
cap label var MC130 "Cream for direct consumption"
cap label var MC135 "Cream of fat content by weight not exceeding 29 %"
cap label var MC136 "Cream of fat content by weight over 29 %"
cap label var MC140 "Acidified milk (yoghurts and other)"
cap label var MC141 "Acidified milk with additives"
cap label var MC142 "Acidified milk without additives"
cap label var MC150 "Drinks with a milk base"
cap label var MC160 "Other fresh products (milk jelly and others)"
cap label var MC200 "Manufactured products"
cap label var MC210 "Concentrated milk"
cap label var MC211 "Concentrated milk not sweetened"
cap label var MC212 "Concentrated milk sweetened"
cap label var MC220 "Milk powder"
cap label var MC221 "Cream milk powder"
cap label var MC222 "Whole milk powder"
cap label var MC223 "Partly skimmed milk powder"
cap label var MC226 "Whole milk powder total (MC221+MC222+MC223)"
cap label var MC224 "Skimmed milk powder"
cap label var MC225 "Buttermilk powder"
cap label var MC229 "Other powder products"
cap label var MC203 "Butter and other yellow fat dairy products (MC230+MC239)"
cap label var MC230 "Butter - Total (MC231+MC232)"
cap label var MC231 "Butter"
cap label var MC2311 "Traditional butter"
cap label var MC2312 "Recombined butter"
cap label var MC2313 "Whey butter"
cap label var MC232 "Rendered butter and butteroil"
cap label var MC239 "Other yellow fat dairy products"
cap label var MC2391 "Reduced-fat butter"
cap label var MC2392 "Other yellow fat dairy products (without Reduced-fat butter)"
cap label var MC240 "Cheese =(MC241+MC242+MC243+MC249) or (MC291+MC292+MC293+MC294+MC295+MC296)"
cap label var MC241 "Cheese from cows'milk (pure)"
cap label var MC242 "Cheese from ewes milk (pure)"
cap label var MC243 "Cheese from goats milk (pure)"
cap label var MC249 "Others (cheese from buffalos'milk (pure) or mixed cheese)"
cap label var MC291 "Soft cheese"
cap label var MC292 "Medium soft cheese"
cap label var MC293 "Medium hard cheese"
cap label var MC294 "Hard cheese"
cap label var MC295 "Extra hard cheese"
cap label var MC296 "Fresh cheese"
cap label var MC250 "Processed cheese"
cap label var MC260 "Caseins and caseinates"
cap label var MC270 "Whey"
cap label var MC271 "Whey used in the liquid state"
cap label var MC272 "Whey used in the concentrated state"
cap label var MC273 "Whey in powder or in block"
cap label var MC274 "Lactose (milk sugar)"
cap label var MC275 "Lactalbumin"
cap label var MC280 "Chocolate crumb"
cap label var MC310 "Skimmed milk - remaining on the farm"
cap label var MC320 "Skimmed milk - returned to the farm"
cap label var MC330 "Skimmed milk - balance of cream imports"
cap label var MC340 "Skimmed milk, buttermilk and whey: imports"
cap label var MC341 "Skimmed milk, buttermilk and whey: imports intra-EU"
cap label var MC390 "Skimmed milk, buttermilk and whey: other sources"
cap label var MC400 "Skimmed milk, buttermilk and whey: exports"
cap label var MC410 "Skimmed milk, buttermilk and whey: exports intra-EU"
cap label var MC500 "Skimmed milk, buttermilk and whey: other uses"
cap label var MC510 "Skimmed milk, buttermilk and whey: human consumption"
cap label var MC520 "Skimmed milk, buttermilk and whey: feed"
cap label var MC600 "Difference = availabilities - uses"
cap label var MM001 "Cows' milk collected"
cap label var MM002 "Cream from farms"
cap label var MM024 "Stock of skimmed-milk powder"
cap label var MM030 "Stock of butter"
cap label var MM110 "Drinking milk"
cap label var MM130 "Cream for direct consumption"
cap label var MM140 "Acidified milk"
cap label var MM210 "Concentrated milk"
cap label var MM224 "Skimmed-milk powder"
cap label var MM225 "Buttermilk powder"
cap label var MM226 "Milk powder cream, whole milk powder and partly skimmed milk powder"
cap label var MM230 "Butter"
cap label var MM241 "Cheese"
cap label var MM260 "Caseins and caseinates"
