cap label var TOTAL "Total - all maturities"
cap label var SHORT "Short-term maturity"
cap label var LONG "Long-term maturity"
cap label var LONG_FX "Long-term maturity, fixed rate"
cap label var LONG_FL "Long-term maturity, floating rate"
cap label var M_LT1 "Maturity: less than 1 month"
cap label var M1_3 "Maturity: from 1 to 3 months"
cap label var M_LT3 "Maturity: less than 3 months"
cap label var M3 "Maturity: 3 months"
cap label var M3_12 "Maturity: from 3 to 12 months"
cap label var M_GT3 "Maturity: over 3 months"
cap label var M4 "Maturity: 4 months"
cap label var M5 "Maturity: 5 months"
cap label var M6 "Maturity: 6 months"
cap label var M7 "Maturity: 7 months"
cap label var M8 "Maturity: 8 months"
cap label var M9 "Maturity: 9 months"
cap label var M10 "Maturity: 10 months"
cap label var M11 "Maturity: 11 months"
cap label var Y_LT1 "Maturity: less than 1 year"
cap label var Y_LE1 "Maturity: 1 year or less"
cap label var Y1 "Maturity: 1 year"
cap label var Y1_M1 "Maturity: 1 year and 1 month"
cap label var Y1_M2 "Maturity: 1 year and 2 months"
cap label var Y1_M3 "Maturity: 1 year and 3 months"
cap label var Y1_M4 "Maturity: 1 year and 4 months"
cap label var Y1_M5 "Maturity: 1 year and 5 months"
cap label var Y1_M6 "Maturity: 1 year and 6 months"
cap label var Y1_M7 "Maturity: 1 year and 7 months"
cap label var Y1_M8 "Maturity: 1 year and 8 months"
cap label var Y1_M9 "Maturity: 1 year and 9 months"
cap label var Y1_M10 "Maturity: 1 year and 10 months"
cap label var Y1_M11 "Maturity: 1 year and 11 months"
cap label var Y1_2 "Maturity: from 1 to 2 years"
cap label var Y1_3 "Maturity: from 1 to 3 years"
cap label var Y1_5 "Maturity: from 1 to 5 years"
cap label var Y_GT1 "Maturity: over 1 year"
cap label var Y_LT2 "Maturity: less than 2 years"
cap label var Y2 "Maturity: 2 years"
cap label var Y2_M1 "Maturity: 2 years and 1 month"
cap label var Y2_M2 "Maturity: 2 years and 2 months"
cap label var Y2_M3 "Maturity: 2 years and 3 months"
cap label var Y2_M4 "Maturity: 2 years and 4 months"
cap label var Y2_M5 "Maturity: 2 years and 5 months"
cap label var Y2_M6 "Maturity: 2 years and 6 months"
cap label var Y2_M7 "Maturity: 2 years and 7 months"
cap label var Y2_M8 "Maturity: 2 years and 8 months"
cap label var Y2_M9 "Maturity: 2 years and 9 months"
cap label var Y2_M10 "Maturity: 2 years and 10 months"
cap label var Y2_M11 "Maturity: 2 years and 11 months"
cap label var Y_GT2 "Maturity: over 2 years"
cap label var Y3 "Maturity: 3 years"
cap label var Y3_M1 "Maturity: 3 years and 1 month"
cap label var Y3_M2 "Maturity: 3 years and 2 months"
cap label var Y3_M3 "Maturity: 3 years and 3 months"
cap label var Y3_M4 "Maturity: 3 years and 4 months"
cap label var Y3_M5 "Maturity: 3 years and 5 months"
cap label var Y3_M6 "Maturity: 3 years and 6 months"
cap label var Y3_M7 "Maturity: 3 years and 7 months"
cap label var Y3_M8 "Maturity: 3 years and 8 months"
cap label var Y3_M9 "Maturity: 3 years and 9 months"
cap label var Y3_M10 "Maturity: 3 years and 10 months"
cap label var Y3_M11 "Maturity: 3 years and 11 months"
cap label var Y3_5 "Maturity: from 3 to 5 years"
cap label var Y4 "Maturity: 4 years"
cap label var Y4_M1 "Maturity: 4 years and 1 month"
cap label var Y4_M2 "Maturity: 4 years and 2 months"
cap label var Y4_M3 "Maturity: 4 years and 3 months"
cap label var Y4_M4 "Maturity: 4 years and 4 months"
cap label var Y4_M5 "Maturity: 4 years and 5 months"
cap label var Y4_M6 "Maturity: 4 years and 6 months"
cap label var Y4_M7 "Maturity: 4 years and 7 months"
cap label var Y4_M8 "Maturity: 4 years and 8 months"
cap label var Y4_M9 "Maturity: 4 years and 9 months"
cap label var Y4_M10 "Maturity: 4 years and 10 months"
cap label var Y4_M11 "Maturity: 4 years and 11 months"
cap label var Y_LT5 "Maturity: less than 5 years"
cap label var Y5 "Maturity: 5 years"
cap label var Y5_M1 "Maturity: 5 years and 1 month"
cap label var Y5_M2 "Maturity: 5 years and 2 months"
cap label var Y5_M3 "Maturity: 5 years and 3 months"
cap label var Y5_M4 "Maturity: 5 years and 4 months"
cap label var Y5_M5 "Maturity: 5 years and 5 months"
cap label var Y5_M6 "Maturity: 5 years and 6 months"
cap label var Y5_M7 "Maturity: 5 years and 7 months"
cap label var Y5_M8 "Maturity: 5 years and 8 months"
cap label var Y5_M9 "Maturity: 5 years and 9 months"
cap label var Y5_M10 "Maturity: 5 years and 10 months"
cap label var Y5_M11 "Maturity: 5 years and 11 months"
cap label var Y5_7 "Maturity: from 5 to 7 years"
cap label var Y5_10 "Maturity: from 5 to 10 years"
cap label var Y_GT5 "Maturity: over 5 years"
cap label var Y6 "Maturity: 6 years"
cap label var Y6_M1 "Maturity: 6 years and 1 month"
cap label var Y6_M2 "Maturity: 6 years and 2 months"
cap label var Y6_M3 "Maturity: 6 years and 3 months"
cap label var Y6_M4 "Maturity: 6 years and 4 months"
cap label var Y6_M5 "Maturity: 6 years and 5 months"
cap label var Y6_M6 "Maturity: 6 years and 6 months"
cap label var Y6_M7 "Maturity: 6 years and 7 months"
cap label var Y6_M8 "Maturity: 6 years and 8 months"
cap label var Y6_M9 "Maturity: 6 years and 9 months"
cap label var Y6_M10 "Maturity: 6 years and 10 months"
cap label var Y6_M11 "Maturity: 6 years and 11 months"
cap label var Y7 "Maturity: 7 years"
cap label var Y7_M1 "Maturity: 7 years and 1 month"
cap label var Y7_M2 "Maturity: 7 years and 2 months"
cap label var Y7_M3 "Maturity: 7 years and 3 months"
cap label var Y7_M4 "Maturity: 7 years and 4 months"
cap label var Y7_M5 "Maturity: 7 years and 5 months"
cap label var Y7_M6 "Maturity: 7 years and 6 months"
cap label var Y7_M7 "Maturity: 7 years and 7 months"
cap label var Y7_M8 "Maturity: 7 years and 8 months"
cap label var Y7_M9 "Maturity: 7 years and 9 months"
cap label var Y7_M10 "Maturity: 7 years and 10 months"
cap label var Y7_M11 "Maturity: 7 years and 11 months"
cap label var Y7_10 "Maturity: from 7 to 10 years"
cap label var Y8 "Maturity: 8 years"
cap label var Y8_M1 "Maturity: 8 years and 1 month"
cap label var Y8_M2 "Maturity: 8 years and 2 months"
cap label var Y8_M3 "Maturity: 8 years and 3 months"
cap label var Y8_M4 "Maturity: 8 years and 4 months"
cap label var Y8_M5 "Maturity: 8 years and 5 months"
cap label var Y8_M6 "Maturity: 8 years and 6 months"
cap label var Y8_M7 "Maturity: 8 years and 7 months"
cap label var Y8_M8 "Maturity: 8 years and 8 months"
cap label var Y8_M9 "Maturity: 8 years and 9 months"
cap label var Y8_M10 "Maturity: 8 years and 10 months"
cap label var Y8_M11 "Maturity: 8 years and 11 months"
cap label var Y9 "Maturity: 9 years"
cap label var Y9_M1 "Maturity: 9 years and 1 month"
cap label var Y9_M2 "Maturity: 9 years and 2 months"
cap label var Y9_M3 "Maturity: 9 years and 3 months"
cap label var Y9_M4 "Maturity: 9 years and 4 months"
cap label var Y9_M5 "Maturity: 9 years and 5 months"
cap label var Y9_M6 "Maturity: 9 years and 6 months"
cap label var Y9_M7 "Maturity: 9 years and 7 months"
cap label var Y9_M8 "Maturity: 9 years and 8 months"
cap label var Y9_M9 "Maturity: 9 years and 9 months"
cap label var Y9_M10 "Maturity: 9 years and 10 months"
cap label var Y9_M11 "Maturity: 9 years and 11 months"
cap label var Y10 "Maturity: 10 years"
cap label var Y10_M1 "Maturity: 10 years and 1 month"
cap label var Y10_M2 "Maturity: 10 years and 2 months"
cap label var Y10_M3 "Maturity: 10 years and 3 months"
cap label var Y10_M4 "Maturity: 10 years and 4 months"
cap label var Y10_M5 "Maturity: 10 years and 5 months"
cap label var Y10_M6 "Maturity: 10 years and 6 months"
cap label var Y10_M7 "Maturity: 10 years and 7 months"
cap label var Y10_M8 "Maturity: 10 years and 8 months"
cap label var Y10_M9 "Maturity: 10 years and 9 months"
cap label var Y10_M10 "Maturity: 10 years and 10 months"
cap label var Y10_M11 "Maturity: 10 years and 11 months"
cap label var Y10_15 "Maturity: from 10 to 15 years"
cap label var Y10_20 "Maturity: from 10 to 20 years"
cap label var Y_GT10 "Maturity: over 10 years"
cap label var Y11 "Maturity: 11 years"
cap label var Y11_M1 "Maturity: 11 years and 1 month"
cap label var Y11_M2 "Maturity: 11 years and 2 months"
cap label var Y11_M3 "Maturity: 11 years and 3 months"
cap label var Y11_M4 "Maturity: 11 years and 4 months"
cap label var Y11_M5 "Maturity: 11 years and 5 months"
cap label var Y11_M6 "Maturity: 11 years and 6 months"
cap label var Y11_M7 "Maturity: 11 years and 7 months"
cap label var Y11_M8 "Maturity: 11 years and 8 months"
cap label var Y11_M9 "Maturity: 11 years and 9 months"
cap label var Y11_M10 "Maturity: 11 years and 10 months"
cap label var Y11_M11 "Maturity: 11 years and 11 months"
cap label var Y12 "Maturity: 12 years"
cap label var Y12_M1 "Maturity: 12 years and 1 month"
cap label var Y12_M2 "Maturity: 12 years and 2 months"
cap label var Y12_M3 "Maturity: 12 years and 3 months"
cap label var Y12_M4 "Maturity: 12 years and 4 months"
cap label var Y12_M5 "Maturity: 12 years and 5 months"
cap label var Y12_M6 "Maturity: 12 years and 6 months"
cap label var Y12_M7 "Maturity: 12 years and 7 months"
cap label var Y12_M8 "Maturity: 12 years and 8 months"
cap label var Y12_M9 "Maturity: 12 years and 9 months"
cap label var Y12_M10 "Maturity: 12 years and 10 months"
cap label var Y12_M11 "Maturity: 12 years and 11 months"
cap label var Y13 "Maturity: 13 years"
cap label var Y13_M1 "Maturity: 13 years and 1 month"
cap label var Y13_M2 "Maturity: 13 years and 2 months"
cap label var Y13_M3 "Maturity: 13 years and 3 months"
cap label var Y13_M4 "Maturity: 13 years and 4 months"
cap label var Y13_M5 "Maturity: 13 years and 5 months"
cap label var Y13_M6 "Maturity: 13 years and 6 months"
cap label var Y13_M7 "Maturity: 13 years and 7 months"
cap label var Y13_M8 "Maturity: 13 years and 8 months"
cap label var Y13_M9 "Maturity: 13 years and 9 months"
cap label var Y13_M10 "Maturity: 13 years and 10 months"
cap label var Y13_M11 "Maturity: 13 years and 11 months"
cap label var Y14 "Maturity: 14 years"
cap label var Y14_M1 "Maturity: 14 years and 1 month"
cap label var Y14_M2 "Maturity: 14 years and 2 months"
cap label var Y14_M3 "Maturity: 14 years and 3 months"
cap label var Y14_M4 "Maturity: 14 years and 4 months"
cap label var Y14_M5 "Maturity: 14 years and 5 months"
cap label var Y14_M6 "Maturity: 14 years and 6 months"
cap label var Y14_M7 "Maturity: 14 years and 7 months"
cap label var Y14_M8 "Maturity: 14 years and 8 months"
cap label var Y14_M9 "Maturity: 14 years and 9 months"
cap label var Y14_M10 "Maturity: 14 years and 10 months"
cap label var Y14_M11 "Maturity: 14 years and 11 months"
cap label var Y15 "Maturity: 15 years"
cap label var Y15_M1 "Maturity: 15 years and 1 month"
cap label var Y15_M2 "Maturity: 15 years and 2 months"
cap label var Y15_M3 "Maturity: 15 years and 3 months"
cap label var Y15_M4 "Maturity: 15 years and 4 months"
cap label var Y15_M5 "Maturity: 15 years and 5 months"
cap label var Y15_M6 "Maturity: 15 years and 6 months"
cap label var Y15_M7 "Maturity: 15 years and 7 months"
cap label var Y15_M8 "Maturity: 15 years and 8 months"
cap label var Y15_M9 "Maturity: 15 years and 9 months"
cap label var Y15_M10 "Maturity: 15 years and 10 months"
cap label var Y15_M11 "Maturity: 15 years and 11 months"
cap label var Y15_30 "Maturity: from 15 to 30 years"
cap label var Y16 "Maturity: 16 years"
cap label var Y16_M1 "Maturity: 16 years and 1 month"
cap label var Y16_M2 "Maturity: 16 years and 2 months"
cap label var Y16_M3 "Maturity: 16 years and 3 months"
cap label var Y16_M4 "Maturity: 16 years and 4 months"
cap label var Y16_M5 "Maturity: 16 years and 5 months"
cap label var Y16_M6 "Maturity: 16 years and 6 months"
cap label var Y16_M7 "Maturity: 16 years and 7 months"
cap label var Y16_M8 "Maturity: 16 years and 8 months"
cap label var Y16_M9 "Maturity: 16 years and 9 months"
cap label var Y16_M10 "Maturity: 16 years and 10 months"
cap label var Y16_M11 "Maturity: 16 years and 11 months"
cap label var Y17 "Maturity: 17 years"
cap label var Y17_M1 "Maturity: 17 years and 1 month"
cap label var Y17_M2 "Maturity: 17 years and 2 months"
cap label var Y17_M3 "Maturity: 17 years and 3 months"
cap label var Y17_M4 "Maturity: 17 years and 4 months"
cap label var Y17_M5 "Maturity: 17 years and 5 months"
cap label var Y17_M6 "Maturity: 17 years and 6 months"
cap label var Y17_M7 "Maturity: 17 years and 7 months"
cap label var Y17_M8 "Maturity: 17 years and 8 months"
cap label var Y17_M9 "Maturity: 17 years and 9 months"
cap label var Y17_M10 "Maturity: 17 years and 10 months"
cap label var Y17_M11 "Maturity: 17 years and 11 months"
cap label var Y18 "Maturity: 18 years"
cap label var Y18_M1 "Maturity: 18 years and 1 month"
cap label var Y18_M2 "Maturity: 18 years and 2 months"
cap label var Y18_M3 "Maturity: 18 years and 3 months"
cap label var Y18_M4 "Maturity: 18 years and 4 months"
cap label var Y18_M5 "Maturity: 18 years and 5 months"
cap label var Y18_M6 "Maturity: 18 years and 6 months"
cap label var Y18_M7 "Maturity: 18 years and 7 months"
cap label var Y18_M8 "Maturity: 18 years and 8 months"
cap label var Y18_M9 "Maturity: 18 years and 9 months"
cap label var Y18_M10 "Maturity: 18 years and 10 months"
cap label var Y18_M11 "Maturity: 18 years and 11 months"
cap label var Y19 "Maturity: 19 years"
cap label var Y19_M1 "Maturity: 19 years and 1 month"
cap label var Y19_M2 "Maturity: 19 years and 2 months"
cap label var Y19_M3 "Maturity: 19 years and 3 months"
cap label var Y19_M4 "Maturity: 19 years and 4 months"
cap label var Y19_M5 "Maturity: 19 years and 5 months"
cap label var Y19_M6 "Maturity: 19 years and 6 months"
cap label var Y19_M7 "Maturity: 19 years and 7 months"
cap label var Y19_M8 "Maturity: 19 years and 8 months"
cap label var Y19_M9 "Maturity: 19 years and 9 months"
cap label var Y19_M10 "Maturity: 19 years and 10 months"
cap label var Y19_M11 "Maturity: 19 years and 11 months"
cap label var Y20 "Maturity: 20 years"
cap label var Y20_M1 "Maturity: 20 years and 1 month"
cap label var Y20_M2 "Maturity: 20 years and 2 months"
cap label var Y20_M3 "Maturity: 20 years and 3 months"
cap label var Y20_M4 "Maturity: 20 years and 4 months"
cap label var Y20_M5 "Maturity: 20 years and 5 months"
cap label var Y20_M6 "Maturity: 20 years and 6 months"
cap label var Y20_M7 "Maturity: 20 years and 7 months"
cap label var Y20_M8 "Maturity: 20 years and 8 months"
cap label var Y20_M9 "Maturity: 20 years and 9 months"
cap label var Y20_M10 "Maturity: 20 years and 10 months"
cap label var Y20_M11 "Maturity: 20 years and 11 months"
cap label var Y_GT20 "Maturity: over 20 years"
cap label var Y21 "Maturity: 21 years"
cap label var Y21_M1 "Maturity: 21 years and 1 month"
cap label var Y21_M2 "Maturity: 21 years and 2 months"
cap label var Y21_M3 "Maturity: 21 years and 3 months"
cap label var Y21_M4 "Maturity: 21 years and 4 months"
cap label var Y21_M5 "Maturity: 21 years and 5 months"
cap label var Y21_M6 "Maturity: 21 years and 6 months"
cap label var Y21_M7 "Maturity: 21 years and 7 months"
cap label var Y21_M8 "Maturity: 21 years and 8 months"
cap label var Y21_M9 "Maturity: 21 years and 9 months"
cap label var Y21_M10 "Maturity: 21 years and 10 months"
cap label var Y21_M11 "Maturity: 21 years and 11 months"
cap label var Y22 "Maturity: 22 years"
cap label var Y22_M1 "Maturity: 22 years and 1 month"
cap label var Y22_M2 "Maturity: 22 years and 2 months"
cap label var Y22_M3 "Maturity: 22 years and 3 months"
cap label var Y22_M4 "Maturity: 22 years and 4 months"
cap label var Y22_M5 "Maturity: 22 years and 5 months"
cap label var Y22_M6 "Maturity: 22 years and 6 months"
cap label var Y22_M7 "Maturity: 22 years and 7 months"
cap label var Y22_M8 "Maturity: 22 years and 8 months"
cap label var Y22_M9 "Maturity: 22 years and 9 months"
cap label var Y22_M10 "Maturity: 22 years and 10 months"
cap label var Y22_M11 "Maturity: 22 years and 11 months"
cap label var Y23 "Maturity: 23 years"
cap label var Y23_M1 "Maturity: 23 years and 1 month"
cap label var Y23_M2 "Maturity: 23 years and 2 months"
cap label var Y23_M3 "Maturity: 23 years and 3 months"
cap label var Y23_M4 "Maturity: 23 years and 4 months"
cap label var Y23_M5 "Maturity: 23 years and 5 months"
cap label var Y23_M6 "Maturity: 23 years and 6 months"
cap label var Y23_M7 "Maturity: 23 years and 7 months"
cap label var Y23_M8 "Maturity: 23 years and 8 months"
cap label var Y23_M9 "Maturity: 23 years and 9 months"
cap label var Y23_M10 "Maturity: 23 years and 10 months"
cap label var Y23_M11 "Maturity: 23 years and 11 months"
cap label var Y24 "Maturity: 24 years"
cap label var Y24_M1 "Maturity: 24 years and 1 month"
cap label var Y24_M2 "Maturity: 24 years and 2 months"
cap label var Y24_M3 "Maturity: 24 years and 3 months"
cap label var Y24_M4 "Maturity: 24 years and 4 months"
cap label var Y24_M5 "Maturity: 24 years and 5 months"
cap label var Y24_M6 "Maturity: 24 years and 6 months"
cap label var Y24_M7 "Maturity: 24 years and 7 months"
cap label var Y24_M8 "Maturity: 24 years and 8 months"
cap label var Y24_M9 "Maturity: 24 years and 9 months"
cap label var Y24_M10 "Maturity: 24 years and 10 months"
cap label var Y24_M11 "Maturity: 24 years and 11 months"
cap label var Y25 "Maturity: 25 years"
cap label var Y25_M1 "Maturity: 25 years and 1 month"
cap label var Y25_M2 "Maturity: 25 years and 2 months"
cap label var Y25_M3 "Maturity: 25 years and 3 months"
cap label var Y25_M4 "Maturity: 25 years and 4 months"
cap label var Y25_M5 "Maturity: 25 years and 5 months"
cap label var Y25_M6 "Maturity: 25 years and 6 months"
cap label var Y25_M7 "Maturity: 25 years and 7 months"
cap label var Y25_M8 "Maturity: 25 years and 8 months"
cap label var Y25_M9 "Maturity: 25 years and 9 months"
cap label var Y25_M10 "Maturity: 25 years and 10 months"
cap label var Y25_M11 "Maturity: 25 years and 11 months"
cap label var Y26 "Maturity: 26 years"
cap label var Y26_M1 "Maturity: 26 years and 1 month"
cap label var Y26_M2 "Maturity: 26 years and 2 months"
cap label var Y26_M3 "Maturity: 26 years and 3 months"
cap label var Y26_M4 "Maturity: 26 years and 4 months"
cap label var Y26_M5 "Maturity: 26 years and 5 months"
cap label var Y26_M6 "Maturity: 26 years and 6 months"
cap label var Y26_M7 "Maturity: 26 years and 7 months"
cap label var Y26_M8 "Maturity: 26 years and 8 months"
cap label var Y26_M9 "Maturity: 26 years and 9 months"
cap label var Y26_M10 "Maturity: 26 years and 10 months"
cap label var Y26_M11 "Maturity: 26 years and 11 months"
cap label var Y27 "Maturity: 27 years"
cap label var Y27_M1 "Maturity: 27 years and 1 month"
cap label var Y27_M2 "Maturity: 27 years and 2 months"
cap label var Y27_M3 "Maturity: 27 years and 3 months"
cap label var Y27_M4 "Maturity: 27 years and 4 months"
cap label var Y27_M5 "Maturity: 27 years and 5 months"
cap label var Y27_M6 "Maturity: 27 years and 6 months"
cap label var Y27_M7 "Maturity: 27 years and 7 months"
cap label var Y27_M8 "Maturity: 27 years and 8 months"
cap label var Y27_M9 "Maturity: 27 years and 9 months"
cap label var Y27_M10 "Maturity: 27 years and 10 months"
cap label var Y27_M11 "Maturity: 27 years and 11 months"
cap label var Y28 "Maturity: 28 years"
cap label var Y28_M1 "Maturity: 28 years and 1 month"
cap label var Y28_M2 "Maturity: 28 years and 2 months"
cap label var Y28_M3 "Maturity: 28 years and 3 months"
cap label var Y28_M4 "Maturity: 28 years and 4 months"
cap label var Y28_M5 "Maturity: 28 years and 5 months"
cap label var Y28_M6 "Maturity: 28 years and 6 months"
cap label var Y28_M7 "Maturity: 28 years and 7 months"
cap label var Y28_M8 "Maturity: 28 years and 8 months"
cap label var Y28_M9 "Maturity: 28 years and 9 months"
cap label var Y28_M10 "Maturity: 28 years and 10 months"
cap label var Y28_M11 "Maturity: 28 years and 11 months"
cap label var Y29 "Maturity: 29 years"
cap label var Y29_M1 "Maturity: 29 years and 1 month"
cap label var Y29_M2 "Maturity: 29 years and 2 months"
cap label var Y29_M3 "Maturity: 29 years and 3 months"
cap label var Y29_M4 "Maturity: 29 years and 4 months"
cap label var Y29_M5 "Maturity: 29 years and 5 months"
cap label var Y29_M6 "Maturity: 29 years and 6 months"
cap label var Y29_M7 "Maturity: 29 years and 7 months"
cap label var Y29_M8 "Maturity: 29 years and 8 months"
cap label var Y29_M9 "Maturity: 29 years and 9 months"
cap label var Y29_M10 "Maturity: 29 years and 10 months"
cap label var Y29_M11 "Maturity: 29 years and 11 months"
cap label var Y30 "Maturity: 30 years"
cap label var Y_GT30 "Maturity: over 30 years"
