cap label var TOTAL "Total"
cap label var LHC_DIF_BACT "Both a longstanding health condition and a basic activity difficulty"
cap label var LHC_ILL "Longstanding health condition, illness or disease"
cap label var NLHC_ILL "No longstanding health condition, illness or disease"
cap label var LHC_ONL "Only a longstanding health condition"
cap label var DIF_BACT "Difficulty in basic activities"
cap label var DIF_BACT_ONL "Only a basic activity difficulty"
cap label var NDIF_BACT "No difficulty in basic activities"
cap label var NLHC_DIF_BACT "No longstanding health condition or basic activity difficulty"
cap label var LTD_LHC_DIF_BACT "Limited by both a longstanding health condition and a basic activity difficulty"
cap label var LTD_LHC "Limited only by a longstanding health condition"
cap label var LTD_DIF_BACT "Limited only by a basic activity difficulty"
cap label var MUSC_SKE "Musculo-skeletal disorders"
cap label var ARMS_HANDS "Problems with arms or hands"
cap label var LEGS_FEET "Problems with legs or feet"
cap label var ARTHRO "Arthrosis"
cap label var BACK_NECK "Problems with back or neck"
cap label var LW_CHR_BACK "Low back disorder or other chronic back defect"
cap label var NECK "Neck disorder or other chronic neck defect"
cap label var SEE "Seeing"
cap label var HEAR "Hearing"
cap label var SPCH_IMPED "Speech impediment"
cap label var SKIN "Skin problems"
cap label var CHST_BRTH "Chest or breathing problems"
cap label var ASTHMA "Asthma"
cap label var CHR_LW_RES "Chronic lower respiratory diseases (excluding asthma)"
cap label var CARDIO_VASC "Cardiovascular disorders"
cap label var HRT_BLPR "Heart, blood pressure or circulation problems"
cap label var HRT_CHR_ATK "Heart attack or chronic consequences of heart attack"
cap label var CHRT_ANGPEC "Coronary heart disease or angina pectoris"
cap label var PULMO "Pulmonary disorders"
cap label var HBLPR "High blood pressure"
cap label var HBLLIP "High blood lipids"
cap label var STRK_CHR "Stroke or chronic consequences of stroke"
cap label var STOMACH "Stomach, liver, kidney or digestive problems"
cap label var CIRRHOSIS "Cirrhosis of the liver"
cap label var URIN "Urinary incontinence, problems in controlling the bladder"
cap label var KIDNEY "Kidney problems"
cap label var INFECT "Infectious diseases"
cap label var DIAB "Diabetes"
cap label var ALLGY "Allergy"
cap label var EPILEP "Epilepsy"
cap label var MENT_NRV_EMO "Mental, nervous or emotional problems"
cap label var CHR_ANX "Chronic anxiety"
cap label var DPR "Depressive symptoms"
cap label var DPR_CHR "Chronic depression"
cap label var DPR_MJR "Major depressive symptoms"
cap label var DPR_OTH "Other depressive symptoms"
cap label var STRESS "Stress, depression, anxiety"
cap label var LEARN "Learning difficulties"
cap label var MNE_OTH "Other mental, nervous or emotional problems"
cap label var PILL_OTH "Other progressive illnesses"
cap label var HEAD_EYE "Headaches, eyestrains, migraines"
cap label var SHEAD "Severe headaches (such as migraine)"
cap label var CANCER "Cancer"
cap label var LH_OTH "Other longstanding health problems"
cap label var WALK "Walking"
cap label var CLMB "Climbing steps"
cap label var REME_CONC "Remembering or concentrating"
cap label var COMM "Communicating"
cap label var TBTL "Raising a 2 litre bottle of water from waist to eye level"
cap label var HLD_GRP_TRN "Holding, gripping or turning"
cap label var SITT_STD "Sitting or standing"
cap label var REAC_STRT "Reaching or stretching"
cap label var LI_CARY "Lifting and carrying"
cap label var BND "Bending"
cap label var VIDIF_COR_NREH "Vision difficulty corrected with no remaining eye health problem"
cap label var COR_VDIF_NEPB "Vision difficulty corrected with no remaining eye health problem"
cap label var VIDIF_COR_REH "Vision difficulty corrected with remaining eye health problem"
cap label var COR_VDIF_EPB "Vision difficulty corrected with remaining eye health problem"
cap label var VIDIFXCOR "Vision difficulty without correction"
cap label var NCOR_VDIF "Vision difficulty without correction"
cap label var NVIDIF "No vision difficulty"
cap label var NVDIF "No vision difficulty"
cap label var U_VIAID "Using vision aids"
cap label var U_VAID "Using vision aids"
cap label var NU_VIAID "Not using vision aids"
cap label var NU_VAID "Not using vision aids"
cap label var FD_OSELF "Feeding oneself"
cap label var IN_OUT_G_BED "Getting in and out of a bed or chair"
cap label var DRS_UNDRS "Dressing and undressing"
cap label var USE_TOIL "Using toilets"
cap label var BATH_SHOW "Bathing or showering"
cap label var PRPM "Preparing meals"
cap label var USE_TLF "Using the telephone"
cap label var SHOP "Shopping"
cap label var MNG_MED "Managing medication"
cap label var LGHT_HWRK "Light housework"
cap label var OH_HWRK "Occasional heavy housework"
cap label var TCF_EADM "Taking care of finances and everyday administrative tasks"
cap label var OTH "Other"
cap label var NRP "No response"
cap label var NSP "Unspecified"
cap label var PB0000 "Disabled"
cap label var PB0001 "Not disabled"
cap label var PB1000 "Long-standing health condition, illness or disease"
cap label var PB1001 "No long-standing health condition, illness or disease"
cap label var PB1010 "Only a longstanding health condition"
cap label var PB1020 "Only a basic activity difficulty"
cap label var PB1030 "Both a longstanding health condition and a basic activity difficulty"
cap label var PB1031 "No longstanding health condition or basic activity difficulty"
cap label var PB1040 "Difficulty in basic activities"
cap label var PB1041 "No difficulty in basic activities"
cap label var PB1050 "Difficulty in personal care"
cap label var PB1051 "No difficulty in personal care"
cap label var PB1060 "Difficulty in household care"
cap label var PB1061 "No difficulty in household care"
cap label var PB1070 "Limitation in work caused by a health condition or difficulty in a basic activity"
cap label var PB1071 "No limitation in work caused by a health condition or difficulty in basic activities"
cap label var PB1080 "Limited only by a longstanding health condition"
cap label var PB1090 "Limited only by a basic activity difficulty"
cap label var PB1100 "Limited by both a longstanding health condition and a basic activity difficulty"
cap label var PB2010 "Problems with arms or hands"
cap label var PB2020 "Problems with legs or feet"
cap label var PB2021 "Arthrosis"
cap label var PB2030 "Problems with back or neck"
cap label var PB2031 "Low back disorder or other chronic back defect"
cap label var PB2032 "Neck disorder or other chronic neck defect"
cap label var PB2110 "Seeing"
cap label var PB2120 "Hearing"
cap label var PB2121 "Hearing in a quiet room"
cap label var PB2122 "Hearing in a noisier room"
cap label var PB2130 "Speech impediment"
cap label var PB2210 "Skin conditions"
cap label var PB2310 "Chest or breathing problems"
cap label var PB2311 "Asthma"
cap label var PB2312 "Chronic lower respiratory diseases (excluding asthma)"
cap label var PB2410 "Heart, blood pressure or circulation problems"
cap label var PB2411 "Heart attack or chronic consequences of heart attack"
cap label var PB2412 "Coronary heart disease or angina pectoris"
cap label var PB2413 "High blood pressure"
cap label var PB2414 "Stroke or chronic consequences of stroke"
cap label var PB2420 "Stomach, liver, kidney or digestive problems"
cap label var PB2421 "Cirrhosis of the liver"
cap label var PB2422 "Urinary incontinence, problems in controlling the bladder"
cap label var PB2423 "Kidney problems"
cap label var PB2430 "Diabetes"
cap label var PB2440 "Allergy"
cap label var PB2510 "Epilepsy"
cap label var PB2610 "Mental, nervous or emotional problems"
cap label var PB2620 "Chronic anxiety"
cap label var PB2630 "Chronic depression"
cap label var PB2640 "Learning difficulties"
cap label var PB2690 "Other mental, nervous or emotional problems"
cap label var PB2710 "Other progressive illnesses"
cap label var PB2720 "Severe headaches (such as migraine)"
cap label var PB2730 "Cancer"
cap label var PB2790 "Other longstanding health problems"
cap label var PB3010 "Walking"
cap label var PB3011 "Walking or climbing steps"
cap label var PB3012 "Climbing steps"
cap label var PB3110 "Remembering or concentrating"
cap label var PB3120 "Communicating"
cap label var PB3210 "Raising a 2 litre bottle of water from waist to eye level"
cap label var PB3310 "Holding, gripping or turning"
cap label var PB3320 "Sitting or standing"
cap label var PB3330 "Reaching or stretching"
cap label var PB3340 "Lifting and carrying"
cap label var PB3350 "Bending"
cap label var PB4010 "Feeding oneself"
cap label var PB4020 "Getting in and out of a bed or chair"
cap label var PB4030 "Dressing and undressing"
cap label var PB4040 "Using toilets"
cap label var PB4050 "Bathing or showering"
cap label var PB5010 "Preparing meals"
cap label var PB5020 "Using the telephone"
cap label var PB5030 "Shopping"
cap label var PB5040 "Managing medication"
cap label var PB5050 "Housework"
cap label var PB5051 "Light housework"
cap label var PB5052 "Occasional heavy housework"
cap label var PB5060 "Taking care of finances and everyday administrative tasks"
cap label var ALLERGIC "Allergic effects"
cap label var CARDIO_V "Cardiovascular disorders"
cap label var DENTAL "Dental disorders"
cap label var EYE "Eye disorders"
cap label var GASTROIN "Gastrointestinal disorders"
cap label var HEMATOLO "Hematological disorders"
cap label var HEARING "Hearing disorders"
cap label var HEPATIC "Hepatic disorders"
cap label var IRRI_SKI "Irritant effects of the skin or mucous membranes"
cap label var NEUROLOG "Neurological disorders"
cap label var PULMONAR "Pulmonary disorders"
cap label var INFECTIO "Infectious diseases"
cap label var SKIN_DIS "Skin problems"
cap label var OTHER "Other not elsewhere mentioned"
cap label var UNK "Unspecified"
cap label var NDPR "No depressive symptoms"
