cap label var P "Pluri-annual"
cap label var A "Annual"
cap label var S "Half-yearly, semesterly"
cap label var Q "Quarterly"
cap label var M "Monthly"
cap label var W "Weekly"
cap label var B "Daily - business week"
cap label var D "Daily"
cap label var H "Hourly"
cap label var I "Irregular / A-periodic"
