cap label var TOTAL "Total"
cap label var LBK "Liquid bulk goods"
cap label var LBK_LGAS "Liquid bulk - liquified gas"
cap label var LBK_COIL "Liquid bulk - crude oil"
cap label var LBK_ROIL "Liquid bulk - refined oil products"
cap label var LBK_CHM "Liquid bulk - chemicals"
cap label var LBK_OTH "Liquid bulk - other"
cap label var LBK_NSP "Liquid bulk - unspecified"
cap label var DBK "Dry bulk goods"
cap label var DBK_ORES "Dry bulk - ores"
cap label var DBK_COAL "Dry bulk - coal"
cap label var DBK_PAGR "Dry bulk - agricultural products"
cap label var DBK_CON "Dry bulk - construction materials"
cap label var DBK_OTH "Dry bulk - other"
cap label var DBK_NSP "Dry bulk - unspecified"
cap label var CNT_SWP "Containers and swap bodies"
cap label var LCNT "Large containers"
cap label var LCNT_20 "Large containers - 20-ft freight units"
cap label var LCNT_40 "Large containers - 40-ft freight units"
cap label var LCNT_21_39 "Large containers - freight units over 20-ft and less than 40-ft"
cap label var LCNT_GT40 "Large containers - freight units > 40-ft"
cap label var LCNT_LD "Large containers (excluded swap bodies) - loaded"
cap label var LCNT_EMP "Large containers (excluded swap bodies) - empty"
cap label var LCNT_NSP "Large containers - unspecified size"
cap label var CNT_OTH "Other containers"
cap label var SWP "Swap bodies"
cap label var PAL "Palletised goods"
cap label var PSLG "Pre-slung goods"
cap label var WRVEH "Railway wagons loaded with road vehicles"
cap label var MSP "Mobile self-propelled units"
cap label var RMSP "Road mobile self-propelled units"
cap label var WMSP "Mobile self-propelled units transported on railway wagons"
cap label var RVEH "Road vehicles (accompanied)"
cap label var RO_TOT "Ro-Ro - mobile self-propelled and non-self-propelled units"
cap label var RO_MSP "Ro-Ro - mobile self-propelled units"
cap label var RO_RVEH "Ro-Ro - road goods vehicles and accompanying trailers"
cap label var RO_CM "Ro-Ro - passenger cars, motorcycles and accompanying trailers/caravans"
cap label var RO_PBUS "Ro-Ro - passenger buses"
cap label var RO_TVEH "Ro-Ro - trade vehicles (incl. import/export motor vehicles)"
cap label var RO_LANI "Ro-Ro - live animals on the hoof"
cap label var RO_MSP_OTH "Ro-Ro - other mobile self-propelled units"
cap label var RO_MSP_NSP "Ro-Ro - unspecified mobile self-propelled units"
cap label var MNSP "Mobile non-self-propelled units"
cap label var RMNSP "Road mobile non-self-propelled units"
cap label var WMNSP "Mobile non-self-propelled units transported on railway wagons"
cap label var STRL "Semi-trailers (unaccompanied)"
cap label var RO_MNSP "Ro-Ro - mobile non-self-propelled units"
cap label var RO_TRL_STRL "Ro-Ro - unaccompanied road goods trailers and semi-trailers"
cap label var RO_CVAN_OTH "Ro-Ro - unaccompanied caravans and other road agricultural and industrial vehicles"
cap label var RO_RWS "Ro-Ro - rail wagons, shipborne port-to-port trailers, and shipborne barges engaged in goods transport"
cap label var RO_RW "Ro-Ro - rail wagons engaged in goods transport"
cap label var RO_SPP "Ro-Ro - shipborne port-to-port trailers engaged in goods transport"
cap label var RO_SB "Ro-Ro - shipborne barges engaged in goods transport"
cap label var RO_MNSP_OTH "Ro-Ro - other mobile non-self-propelled units"
cap label var RO_MNSP_NSP "Ro-Ro - unspecified mobile non-self-propelled units"
cap label var RES "Reserved"
cap label var OTH "Other cargo not elsewhere specified"
cap label var OTH_FOR "Other cargo - forestry products"
cap label var OTH_IS "Other cargo - iron and steel products"
cap label var OTH_GN "Other cargo - other general cargo"
cap label var OTH_UNK "Other cargo - unknown"
cap label var UNK "Unknown"
cap label var NSP "Unspecified non unit-load"
