cap label var B1003 "Total utilised agricultural area (UAA) (ha)"
cap label var B1004 "Total irrigated agricultural land (ha)"
cap label var B1001 "Number of agricultural holdings (Number)"
cap label var D1301 "Frequency of ozone peaks (Number)"
cap label var D2204 "Municipal waste per capita (Kg/inhab)"
cap label var D5101 "Total surface of the protected areas (ha)"
cap label var D5102 "Share of protected national territory (%)"
cap label var D5201 "Mammals (Number)"
cap label var D5202 "Birds (Number)"
cap label var D5203 "Reptiles (Number)"
cap label var D5204 "Amphibians (Number)"
cap label var D5205 "Fish (Number)"
cap label var D5206 "Invertebrates (Number)"
cap label var D5207 "Vascular plants (Number)"
cap label var D5301 "Mammals (%)"
cap label var D5302 "Birds (%)"
cap label var D5303 "Reptiles (%)"
cap label var D5304 "Amphibians (%)"
cap label var D5305 "Fish (%)"
cap label var D5306 "Invertebrates (%)"
cap label var D5307 "Vascular plants (%)"
cap label var F1001 "GDP at current market prices (Million Euro)"
cap label var F1002 "Annual growth rate of GDP at current market prices (%)"
cap label var F1003 "GDP per capita at current market prices (Euro)"
cap label var F1004 "GDP in volume (Constant Price) (Million Euro)"
cap label var F1005 "Annual growth rate of GDP in volume (Constant Price) (%)"
cap label var F1006 "GDP in volume per capita (Constant Price) (Euro)"
cap label var F1007 "Final consumption expenditure, as a share of GDP (%)"
cap label var F1008 "Final consumption expenditure of Households & NPISHs, as a share of GDP (%)"
cap label var F1009 "Final consumption expenditure of General Government, as a share of GDP (%)"
cap label var F1010 "Gross capital formation, as a share of GDP (%)"
cap label var F1011 "Annual growth rate of gross capital formation (%)"
cap label var F1012 "Gross fixed  capital formation, as a share of GDP (%)"
cap label var F1013 "Annual growth rate of gross fixed  capital formation (%)"
cap label var F1014 "Change in stocks, as a share of GDP (%)"
cap label var F1021 "Gross fixed capital formation, as a share of GDP - Non-financial corporations sector (%)"
cap label var F1022 "Gross fixed capital formation, as a share of GDP - Financial corporations sector (%)"
cap label var F2002 "Gross fixed capital formation, as a share of GDP - General government sector (%)"
cap label var F1023 "Gross fixed capital formation, as a share of GDP - Households sector (%)"
cap label var F1015 "Imports of goods & services, as a share of GDP (%)"
cap label var F1016 "Exports of goods & services, as a share of GDP (%)"
cap label var F1017 "Value Added of Agriculture, as a share of total VA (%)"
cap label var F1018 "Value Added of Manufacturing, water and electricity, as a share of total VA (%)"
cap label var F1019 "Value Added of Construction, as a share of total VA (%)"
cap label var F1020 "Value Added of Services, as a share of total VA (%)"
cap label var F2009 "Total economy deficit (-) / surplus (+), as a share of GDP - total economy (ESA95 balancing item B.9) (%)"
cap label var F2010 "Households sector deficit (-) / surplus (+), as a share of GDP (%)"
cap label var F2001 "General government sector deficit (-) / surplus (+), as a share of GDP (%)"
cap label var F2006 "Total general goverment expenditures (Million Euro)"
cap label var F2007 "Total general government receipts (Million Euro)"
cap label var F2004 "Gross external debt, as a share of GDP (%)"
cap label var F2011 "Gross external private debt, as a share of GDP (%)"
cap label var F2003 "Gross external public debt, as a share of GDP (%)"
cap label var F2012 "Gross public debt, as a share of GDP (%)"
cap label var I0001 "Consumer price index (2000 = 100)"
cap label var I0003 "Consumer price index (2015 = 100)"
cap label var I0002 "Industrial production index (2000=100 Index)"
cap label var G0001 "Total area (km²)"
cap label var G1004 "Population density (Inhab / Km²)"
cap label var G2101 "Adult literacy rate, male (%)"
cap label var G2102 "Adult literacy rate, female (%)"
cap label var G2103 "Adult literacy rate, total (%)"
cap label var G2104 "Youth literacy rate, male (%)"
cap label var G2105 "Youth literacy rate, female (%)"
cap label var G2106 "Youth literacy rate, total (%)"
cap label var G2107 "Ratio of young literate women to men (Ratio)"
cap label var G2201 "Number of compulsory schooling years (Year)"
cap label var G2217 "Net enrolment rate at ISCED 1, male (%)"
cap label var G2218 "Net enrolment rate at ISCED 1, female (%)"
cap label var G2219 "Net enrolment rate at ISCED 1, total (%)"
cap label var G2220 "Net enrolment rate at ISCED 2, male (%)"
cap label var G2221 "Net enrolment rate at ISCED 2, female (%)"
cap label var G2222 "Net enrolment rate at ISCED 2, total (%)"
cap label var G2223 "Gender parity index at ISCED 1 (Ratio)"
cap label var G2224 "Gender parity index at ISCED 2 (Ratio)"
cap label var G2209 "School completion rate at ISCED 1, male (%)"
cap label var G2210 "School completion rate at ISCED 1, female (%)"
cap label var G2211 "School completion rate at ISCED 1, total (%)"
cap label var G2B01 "Gross enrolment rate in TVET, male, ISCED 3 (%)"
cap label var G2B02 "Gross enrolment rate in TVET, female, ISCED 3 (%)"
cap label var G2B03 "Gross enrolment rate in TVET, total, ISCED 3 (%)"
cap label var G2B09 "Cost per student in TVET (National Currency)"
cap label var G3111 "Poverty line, urban (National Currency)"
cap label var G3112 "Poverty line, rural (National Currency)"
cap label var G3101 "Poverty line, total (National Currency)"
cap label var G3113 "Poverty headcount ratio, urban (%)"
cap label var G3114 "Poverty headcount ratio, rural (%)"
cap label var G3102 "Poverty headcount ratio, total (%)"
cap label var G3115 "Inequality of income or expenditure distribution (Gini coefficient), urban (Index)"
cap label var G3116 "Inequality of income or expenditure distribution (Gini coefficient), rural (Index)"
cap label var G3105 "Inequality of income or expenditure distribution (Gini coefficient), total (Index)"
cap label var G3104 "Income (or expenditure) distribution: S80/S20 quintile share ratio, total (Ratio)"
cap label var G3117 "Share of poorest household quintile in national consumption, total (%)"
cap label var G3106 "Proportion of persons living in jobless households, total (%)"
cap label var G3301 "Proportion of households with sustainable access to an improved water source, urban (%)"
cap label var G3302 "Proportion of households with sustainable access to an improved water source, rural (%)"
cap label var G3303 "Proportion of households with sustainable access to an improved water source, total (%)"
cap label var G3304 "Proportion of households with sustainable access to improved sanitation, urban (%)"
cap label var G3305 "Proportion of households with sustainable access to improved sanitation, rural (%)"
cap label var G3306 "Proportion of households with sustainable access to improved sanitation, total (%)"
cap label var G3307 "Proportion of households with access to secure tenure, urban (%)"
cap label var G3308 "Proportion of households with access to secure tenure, rural (%)"
cap label var G3309 "Proportion of households with access to secure tenure, total (%)"
cap label var G3310 "Proportion of households according to the source of energy, urban, electricity (%)"
cap label var G3311 "Proportion of households according to the source of energy, rural, electricity (%)"
cap label var G3312 "Proportion of households according to the source of energy, total, electricity (%)"
cap label var G3201 "Number of main telephone lines per 1,000 inhabitants (Per 1000 Inhab)"
cap label var G3202 "Number of subscriptions to cellular mobile telephone services per 1,000 inhabitants (Per 1000 Inhab)"
cap label var G3203 "Share of households owning a personal computer (%)"
cap label var G3204 "Number of subscribers to Internet network per 100,000 inhabitants (Per 100 000 Inhab)"
cap label var G4104 "Total employment, male, 15+ (Number)"
cap label var G4105 "Total employment, female, 15+ (Number)"
cap label var G4106 "Total employment, total, 15+ (Number)"
cap label var G4101 "Crude economic activity rate, male, 15+ (%)"
cap label var G4102 "Crude economic activity rate, female, 15+ (%)"
cap label var G4103 "Crude economic activity rate, total, 15+ (%)"
cap label var G4109 "Gross employment-to-Population ratio, male, 15-64 (%)"
cap label var G4110 "Gross employment-to-Population ratio, female, 15-64 (%)"
cap label var G4111 "Gross employment-to-Population ratio, total, 15-64 (%)"
cap label var G4112 "Employment status, wage worker (%)"
cap label var G4113 "Employment status, self-employed (%)"
cap label var G4114 "Employment status, family worker (%)"
cap label var G4201 "Unemployment rate, male (%)"
cap label var G4202 "Unemployment rate, female (%)"
cap label var G4203 "Unemployment rate, total (%)"
cap label var G4204 "Youth unemployment rate, male (%)"
cap label var G4205 "Youth unemployment rate, female (%)"
cap label var G4206 "Youth unemployment rate, total (%)"
cap label var G4209 "Long-term unemployment rate, male (%)"
cap label var G4210 "Long-term unemployment rate, female (%)"
cap label var G4211 "Long-term unemployment rate, total (%)"
cap label var G4312 "Legal minimum hourly wage (National Currency)"
cap label var G4313 "Proportion of women in wage employment in the non-agriculture sector (%)"
cap label var D1302 "Total number of gasoline fueled vehicles (Number)"
cap label var D1303 "Total number of Diesel powered engines (Number)"
cap label var D1304 "Total number of other vehicles (Number)"
cap label var D1305 "Total number of vehicles (Number)"
cap label var D1306 "Urban population exposure to air pollution by particulate matter (%)"
cap label var D1307 "Urban population exposure to air pollution by ozone (%)"
cap label var D2504 "Percentage of total population served by municipal waste collection (%)"
cap label var D2505 "Percentage of urban population served by municipal waste collection (%)"
cap label var D2506 "Percentage of rural population served by municipal waste collection (%)"
cap label var F8001 "GDP in PPS (Million PPS)"
cap label var F8002 "GDP in PPS, per capita (PPS)"
cap label var F8003 "Government Budget as a share of GDP (%)"
cap label var F8004 "Total annual public expenditure in regular education (current and capital) as a percentage of  GDP (ISCED levels 0-1, 2, 3-4, 5-6) (%)"
cap label var F8005 "Total annual public expenditure in Vocational Training (current and capital) as a percentage of GDP (ISCED levels 3-4 Vocational Training) (%)"
cap label var F8006 "Total annual public expenditure in regular education (current and capital) as a percentage of  total Government Expenditure (ISCED levels 0-1, 2, 3-4, 5-6) (%)"
cap label var F8007 "Total annual public expenditure in Vocational Training (current and capital) as a percentage of total Government Expenditure (ISCED levels 3-4 Vocational Training) (%)"
cap label var F8008 "Public investment in education as a share of GDP (%)"
cap label var G2225 "Gross enrolment rate at ISCED 1, male (%)"
cap label var G2226 "Gross enrolment rate at ISCED 1, female (%)"
cap label var G2227 "Gross enrolment rate at ISCED 1, total (%)"
cap label var G2228 "Gross enrolment rate at ISCED 2, male (%)"
cap label var G2229 "Gross enrolment rate at ISCED 2, female (%)"
cap label var G2230 "Gross enrolment rate at ISCED 2, total (%)"
cap label var G25101 "Proportion of youth (20-24 years) having attained ISCED 3 level, male (%)"
cap label var G25102 "Proportion of youth (20-24 years) having attained ISCED 3 level, female (%)"
cap label var G25103 "Proportion of youth (20-24 years) having attained ISCED 3 level, total (%)"
cap label var G25201 "Educational attainment at age 25 and above, male, Illiterate (%)"
cap label var G25202 "Educational attainment at age 25 and above, male, ISCED 0-1 (%)"
cap label var G25203 "Educational attainment at age 25 and above, male, ISCED 2 (%)"
cap label var G25204 "Educational attainment at age 25 and above, male, ISCED 3-4 (%)"
cap label var G25205 "Educational attainment at age 25 and above, male, ISCED 5-6 (%)"
cap label var G25206 "Educational attainment at age 25 and above, female, Illiterate (%)"
cap label var G25207 "Educational attainment at age 25 and above, female, ISCED 0-1 (%)"
cap label var G25208 "Educational attainment at age 25 and above, female, ISCED 2 (%)"
cap label var G25209 "Educational attainment at age 25 and above, female, ISCED 3-4 (%)"
cap label var G25210 "Educational attainment at age 25 and above, female, ISCED 5-6 (%)"
cap label var G25211 "Educational attainment at age 25 and above, total, Illiterate (%)"
cap label var G25212 "Educational attainment at age 25 and above, total, ISCED 0-1 (%)"
cap label var G25213 "Educational attainment at age 25 and above, total, ISCED 2 (%)"
cap label var G25214 "Educational attainment at age 25 and above, total, ISCED 3-4 (%)"
cap label var G25215 "Educational attainment at age 25 and above, total, ISCED 5-6 (%)"
cap label var G25216 "Early school leavers not in education or training, male (%)"
cap label var G25217 "Early school leavers not in education or training, female (%)"
cap label var G25218 "Early school leavers not in education or training, total (%)"
cap label var G25301 "Ratio of persons with low educational attainment, male, 25-34 (%)"
cap label var G25302 "Ratio of persons with low educational attainment, male, 35-44 (%)"
cap label var G25303 "Ratio of persons with low educational attainment, male, 45-54 (%)"
cap label var G25304 "Ratio of persons with low educational attainment, male, 55-64 (%)"
cap label var G25305 "Ratio of persons with low educational attainment, male, 65+ (%)"
cap label var G25306 "Ratio of persons with low educational attainment, male, 25-64 (%)"
cap label var G25307 "Ratio of persons with low educational attainment, female, 25-34 (%)"
cap label var G25308 "Ratio of persons with low educational attainment, female, 35-44 (%)"
cap label var G25309 "Ratio of persons with low educational attainment, female, 45-54 (%)"
cap label var G25310 "Ratio of persons with low educational attainment, female, 55-64 (%)"
cap label var G25311 "Ratio of persons with low educational attainment, female, 65+ (%)"
cap label var G25312 "Ratio of persons with low educational attainment, female, 25-64 (%)"
cap label var G25313 "Ratio of persons with low educational attainment, total, 25-34 (%)"
cap label var G25314 "Ratio of persons with low educational attainment, total, 35-44 (%)"
cap label var G25315 "Ratio of persons with low educational attainment, total, 45-54 (%)"
cap label var G25316 "Ratio of persons with low educational attainment, total, 55-64 (%)"
cap label var G25317 "Ratio of persons with low educational attainment, total, 65+ (%)"
cap label var G25318 "Ratio of persons with low educational attainment, total, 25-64 (%)"
cap label var G25401 "Ratio of students enrolled in tertiary education at ISCED 5-6, male (Per 100 000 Inhab)"
cap label var G25402 "Ratio of students enrolled in tertiary education at ISCED 5-6, female (Per 100 000 Inhab)"
cap label var G25403 "Ratio of students enrolled in tertiary education at ISCED 5-6, total (Per 100 000 Inhab)"
cap label var G25404 "Number of tertiary education (ISCED 5-6) graduates in mathematics, science and technology, male (Number)"
cap label var G25405 "Number of tertiary education (ISCED 5-6) graduates in mathematics, science and technology, female (Number)"
cap label var G25406 "Number of tertiary education (ISCED 5-6) graduates in mathematics, science and technology, total (Number)"
cap label var G25501 "Teachers qualification, male, ISCED 3 (%)"
cap label var G25502 "Teachers qualification, male, ISCED 4 (%)"
cap label var G25503 "Teachers qualification, male, ISCED 5 A&B (%)"
cap label var G25504 "Teachers qualification, male, ISCED 6 (%)"
cap label var G25505 "Teachers qualification, female, ISCED 3 (%)"
cap label var G25506 "Teachers qualification, female, ISCED 4 (%)"
cap label var G25507 "Teachers qualification, female, ISCED 5 A&B (%)"
cap label var G25508 "Teachers qualification, female, ISCED 6 (%)"
cap label var G25509 "Teachers qualification, total, ISCED 3 (%)"
cap label var G25510 "Teachers qualification, total, ISCED 4 (%)"
cap label var G25511 "Teachers qualification, total, ISCED 5 A&B (%)"
cap label var G25512 "Teachers qualification, total, ISCED 6 (%)"
cap label var G25601 "Public expenditure on education as % of total government spending, ISCED 0-1 (%)"
cap label var G25602 "Public expenditure on education as % of total government spending, ISCED 2 (%)"
cap label var G25603 "Public expenditure on education as % of total government spending, ISCED 3-4 (%)"
cap label var G25604 "Public expenditure on education as % of total government spending, ISCED 5-6 (%)"
cap label var G25605 "Public expenditure on education as % of total government spending (%)"
cap label var G2B10 "Gross enrolment rate in TVET, male, ISCED 4 (%)"
cap label var G2B11 "Gross enrolment rate in TVET, female, ISCED 4 (%)"
cap label var G2B12 "Gross enrolment rate in TVET, total, ISCED 4 (%)"
cap label var G2B13 "Share of TVET graduates in the overall graduates at ISCED 3 and above, male (%)"
cap label var G2B14 "Share of TVET graduates in the overall graduates at ISCED 3 and above, female (%)"
cap label var G2B15 "Share of TVET graduates in the overall graduates at ISCED 3 and above, total (%)"
cap label var G2B16 "Life-long learning, male (%)"
cap label var G2B17 "Life-long learning, female (%)"
cap label var G2B18 "Life-long learning, total (%)"
cap label var G2B19 "Public Expenditure on vocational training as % of total government spending (%)"
cap label var G31A1 "Extreme poverty line, urban (National Currency)"
cap label var G31A2 "Extreme poverty Line, rural (National Currency)"
cap label var G31A3 "Extreme poverty Line, total (National Currency)"
cap label var G31B11 "At-Risk-of poverty rate, male, urban (%)"
cap label var G31B111 "At-Risk-of poverty rate, male, urban, 0-17 (%)"
cap label var G31B112 "At-Risk-of poverty rate, male, urban,18-64 (%)"
cap label var G31B113 "At-Risk-of poverty rate, male, urban, 65+ (%)"
cap label var G31B12 "At-Risk-of poverty rate, male, rural (%)"
cap label var G31B121 "At-Risk-of poverty rate, male, rural, 0-17 (%)"
cap label var G31B122 "At-Risk-of poverty rate, male, rural,18-64 (%)"
cap label var G31B123 "At-Risk-of poverty rate, male, rural, 65+ (%)"
cap label var G31B13 "At-Risk-of poverty rate, male, total (%)"
cap label var G31B131 "At-Risk-of poverty rate, male, total, 0-17 (%)"
cap label var G31B132 "At-Risk-of poverty rate, male, total,18-64 (%)"
cap label var G31B133 "At-Risk-of poverty rate, male, total, 65+ (%)"
cap label var G31B21 "At-Risk-of poverty rate, female, urban (%)"
cap label var G31B211 "At-Risk-of poverty rate, female, urban, 0-17 (%)"
cap label var G31B212 "At-Risk-of poverty rate, female, urban, 18-64 (%)"
cap label var G31B213 "At-Risk-of poverty rate, female, urban, 65+ (%)"
cap label var G31B22 "At-Risk-of poverty rate, female, rural (%)"
cap label var G31B221 "At-Risk-of poverty rate, female, rural, 0-17 (%)"
cap label var G31B222 "At-Risk-of poverty rate, female, rural, 18-64 (%)"
cap label var G31B223 "At-Risk-of poverty rate, female, rural, 65+ (%)"
cap label var G31B23 "At-Risk-of poverty rate, female, total (%)"
cap label var G31B231 "At-Risk-of poverty rate, female, total, 0-17 (%)"
cap label var G31B232 "At-Risk-of poverty rate, female, total, 18-64 (%)"
cap label var G31B233 "At-Risk-of poverty rate, female, total, 65+ (%)"
cap label var G31B31 "At-Risk-of poverty rate, total, urban (%)"
cap label var G31B311 "At-Risk-of poverty rate, total, urban, 0-17 (%)"
cap label var G31B312 "At-Risk-of poverty rate, total, urban, 18-64 (%)"
cap label var G31B313 "At-Risk-of poverty rate, total, urban, 65+ (%)"
cap label var G31B32 "At-Risk-of poverty rate, total, rural (%)"
cap label var G31B321 "At-Risk-of poverty rate, total, rural, 0-17 (%)"
cap label var G31B322 "At-Risk-of poverty rate, total, rural, 18-64 (%)"
cap label var G31B323 "At-Risk-of poverty rate, total, rural, 65+ (%)"
cap label var G31B33 "At-Risk-of poverty rate, total (%)"
cap label var G31B331 "At-Risk-of poverty rate, total, 0-17 (%)"
cap label var G31B332 "At-Risk-of poverty rate, total, 18-64 (%)"
cap label var G31B333 "At-Risk-of poverty rate, total, 65+ (%)"
cap label var G31C1 "Income (or expenditure) distribution: S80/S20 quintile share ratio, urban (Ratio)"
cap label var G31C2 "Income (or expenditure) distribution: S80/S20 quintile share ratio, rural (Ratio)"
cap label var G31C3 "Share of poorest household quintile in national consumption, urban (%)"
cap label var G31C4 "Share of poorest household quintile in national consumption, rural (%)"
cap label var G31D11 "Prevalence of underweight children under 5 years of age, male, urban (%)"
cap label var G31D12 "Prevalence of underweight children under 5 years of age, male, rural (%)"
cap label var G31D13 "Prevalence of underweight children under 5 years of age, male, total (%)"
cap label var G31D21 "Prevalence of underweight children under 5 years of age, female, urban (%)"
cap label var G31D22 "Prevalence of underweight children under 5 years of age, female, rural (%)"
cap label var G31D23 "Prevalence of underweight children under 5 years of age, female, total (%)"
cap label var G31D31 "Prevalence of underweight children under 5 years of age, total, urban (%)"
cap label var G31D32 "Prevalence of underweight children under 5 years of age, total, rural (%)"
cap label var G31D33 "Prevalence of underweight children under 5 years of age, total (%)"
cap label var G3313 "Proportion of households according to the source of energy, urban, Petroleum products  (%)"
cap label var G3314 "Proportion of households according to the source of energy, urban, Natural Gas (%)"
cap label var G3315 "Proportion of households according to the source of energy, urban, Renewable energies  (%)"
cap label var G3316 "Proportion of households according to the source of energy, rural, Petroleum products  (%)"
cap label var G3317 "Proportion of households according to the source of energy, rural, Natural Gas (%)"
cap label var G3318 "Proportion of households according to the source of energy, rural, Renewable energies  (%)"
cap label var G3319 "Proportion of households according to the source of energy, total, Petroleum products  (%)"
cap label var G3320 "Proportion of households according to the source of energy, total, Natural Gas (%)"
cap label var G3321 "Proportion of households according to the source of energy, total, Renewable energies  (%)"
cap label var G41A01 "Total employment, male, 15-64 (Number)"
cap label var G41A02 "Total employment, female, 15-64 (Number)"
cap label var G41A03 "Total employment, total, 15-64 (Number)"
cap label var G41A04 "Total paid employment, male, 15-64 (Number)"
cap label var G41A05 "Total paid employment, male, 15+ (Number)"
cap label var G41A06 "Total paid employment, female, 15-64 (Number)"
cap label var G41A07 "Total paid employment, female, 15+ (Number)"
cap label var G41A08 "Total paid employment, total, 15-64 (Number)"
cap label var G41A09 "Total paid employment, total, 15+ (Number)"
cap label var G41A10 "Total un-paid employment, male, 15-64 (Number)"
cap label var G41A11 "Total un-paid employment, male, 15+ (Number)"
cap label var G41A12 "Total un-paid employment, female, 15-64 (Number)"
cap label var G41A13 "Total un-paid employment, female, 15+ (Number)"
cap label var G41A14 "Total un-paid employment, total, 15-64 (Number)"
cap label var G41A15 "Total un-paid employment, total, 15+ (Number)"
cap label var G41B01 "Crude economic activity rate, male, 15-64 (%)"
cap label var G41B02 "Crude economic activity rate, female, 15-64 (%)"
cap label var G41B03 "Crude economic activity rate, total, 15-64 (%)"
cap label var G41B04 "Net economic activity rate, male, 15-24 (%)"
cap label var G41B05 "Net economic activity rate, male, 25-64 (%)"
cap label var G41B06 "Net economic activity rate, male, 15-64 (%)"
cap label var G41B07 "Net economic activity rate, female, 15-24 (%)"
cap label var G41B08 "Net economic activity rate, female, 25-64 (%)"
cap label var G41B09 "Net economic activity rate, female, 15-64 (%)"
cap label var G41B10 "Net economic activity rate, total, 15-24 (%)"
cap label var G41B11 "Net economic activity rate, total, 25-64 (%)"
cap label var G41B12 "Net economic activity rate, total, 15-64 (%)"
cap label var G41C01 "Gross employment-to-Population ratio, male, 15+ (%)"
cap label var G41C02 "Gross employment-to-Population ratio, female, 15+ (%)"
cap label var G41C03 "Gross employment-to-Population ratio, total, 15+ (%)"
cap label var G41C04 "Net employment-to-population ratio, male (%)"
cap label var G41C05 "Net employment-to-population ratio, female (%)"
cap label var G41C06 "Net employment-to-population ratio, total (%)"
cap label var G41D01 "Employment status, Employer (%)"
cap label var G41D02 "Employment status, Worker in a cooperative (%)"
cap label var G41D03 "Employment by economic activity, ( A+B ) (%)"
cap label var G41D04 "Employment by economic activity, ( C ) (%)"
cap label var G41D05 "Employment by economic activity, ( D+E ) (%)"
cap label var G41D06 "Employment by economic activity, ( F ) (%)"
cap label var G41D07 "Employment by economic activity, ( G ) (%)"
cap label var G41D08 "Employment by economic activity, ( I ) (%)"
cap label var G41D09 "Employment by economic activity, ( H+J+K ) (%)"
cap label var G41D10 "Employment by economic activity, ( L+M+N+O+P+Q ) (%)"
cap label var G42B01 "Unemployment rate by education level, male, Illiterate (%)"
cap label var G42B02 "Unemployment rate by education level, male, ISCED 0-1 (%)"
cap label var G42B03 "Unemployment rate by education level, male, ISCED 2 (%)"
cap label var G42B04 "Unemployment rate by education level, male, ISCED 3-4 (%)"
cap label var G42B05 "Unemployment rate by education level, male, ISCED 5-6 (%)"
cap label var G42B06 "Unemployment rate by education level, female, Illiterate (%)"
cap label var G42B07 "Unemployment rate by education level, female, ISCED 0-1 (%)"
cap label var G42B08 "Unemployment rate by education level, female, ISCED 2 (%)"
cap label var G42B09 "Unemployment rate by education level, female, ISCED 3-4 (%)"
cap label var G42B10 "Unemployment rate by education level, female, ISCED 5-6 (%)"
cap label var G42B11 "Unemployment rate by education level, total, Illiterate (%)"
cap label var G42B12 "Unemployment rate by education level, total, ISCED 0-1 (%)"
cap label var G42B13 "Unemployment rate by education level, total, ISCED 2 (%)"
cap label var G42B14 "Unemployment rate by education level, total, ISCED 3-4 (%)"
cap label var G42B15 "Unemployment rate by education level, total, ISCED 5-6 (%)"
cap label var G42C01 "Proportion of persons living in jobless households, male, 0-17 (%)"
cap label var G42C02 "Proportion of persons living in jobless households, male, 18-64 (%)"
cap label var G42C03 "Proportion of persons living in jobless households, male, total (%)"
cap label var G42C04 "Proportion of persons living in jobless households, female, 0-17 (%)"
cap label var G42C05 "Proportion of persons living in jobless households, female, 18-64 (%)"
cap label var G42C06 "Proportion of persons living in jobless households, female, total (%)"
cap label var G42C07 "Proportion of persons living in jobless households, total, 0-17 (%)"
cap label var G42C08 "Proportion of persons living in jobless households, total, 18-64 (%)"
cap label var G4314 "Nominal wage index, ( A+B ) (Index)"
cap label var G4315 "Nominal wage index, ( C ) (Index)"
cap label var G4316 "Nominal wage index, ( D+E ) (Index)"
cap label var G4317 "Nominal wage index, ( F ) (Index)"
cap label var G4318 "Nominal wage index, ( G ) (Index)"
cap label var G4319 "Nominal wage index, ( I ) (Index)"
cap label var G4320 "Nominal wage index, ( H+J+K ) (Index)"
cap label var G4321 "Nominal wage index, ( L+M+N+O ) (Index)"
cap label var G4322 "Proportion of employees earning less than 50% of the median salary, male (%)"
cap label var G4323 "Proportion of employees earning less than 50% of the median salary, female (%)"
cap label var G4324 "Proportion of employees earning less than 50% of the median salary, total (%)"
