cap label var TOTAL "Total"
cap label var F00 "Generic programmes and qualifications"
cap label var F000 "Generic programmes and qualifications not further defined"
cap label var F0000 "Generic programmes and qualifications not further defined"
cap label var F001 "Basic programmes and qualifications"
cap label var F0011 "Basic programmes and qualifications"
cap label var F002 "Literacy and numeracy"
cap label var F0021 "Literacy and numeracy"
cap label var F003 "Personal skills and development"
cap label var F0031 "Personal skills and development"
cap label var F009 "Generic programmes and qualifications not elsewhere classified"
cap label var F0099 "Generic programmes and qualifications not elsewhere classified"
cap label var F01 "Education"
cap label var F011 "Education"
cap label var F0110 "Education not further defined"
cap label var F0111 "Education science"
cap label var F0112 "Training for pre-school teachers"
cap label var F0113_0114 "Teacher trainigng without and with subject specialisation"
cap label var F0113 "Teacher training without subject specialisation"
cap label var F0114 "Teacher training with subject specialisation"
cap label var F0119 "Education not elsewhere classified"
cap label var F018 "Inter-disciplinary programmes and qualifications involving education"
cap label var F0188 "Inter-disciplinary programmes and qualifications involving education"
cap label var F02 "Arts and humanities"
cap label var F020 "Arts and humanities not further defined"
cap label var F0200 "Arts and humanities not further defined"
cap label var F021 "Arts"
cap label var F0210 "Arts not further defined"
cap label var F0211 "Audio-visual techniques and media production"
cap label var F0212 "Fashion, interior and industrial design"
cap label var F0213 "Fine arts"
cap label var F0214 "Handicrafts"
cap label var F0215 "Music and performing arts"
cap label var F0219 "Arts not elsewhere classified"
cap label var F022_023 "Humanities"
cap label var F022 "Humanities (except languages)"
cap label var F0220 "Humanities (except languages) not further defined"
cap label var F0221 "Religion and theology"
cap label var F0222 "History and archaeology"
cap label var F0223 "Philosophy and ethics"
cap label var F0229 "Humanities (except languages) not elsewhere classified"
cap label var F023 "Languages"
cap label var F0230 "Languages not further defined"
cap label var F0231 "Language acquisition"
cap label var F0232 "Literature and linguistics"
cap label var F0239 "Languages not elsewhere classified"
cap label var F028 "Inter-disciplinary programmes and qualifications involving arts and humanities"
cap label var F0288 "Inter-disciplinary programmes and qualifications involving arts and humanities"
cap label var F029 "Arts and humanities not elsewhere classified"
cap label var F0299 "Arts and humanities not elsewhere classified"
cap label var F03_04 "Social sciences, journalism, information, business, administration and law"
cap label var F03 "Social sciences, journalism and information"
cap label var F030 "Social sciences, journalism and information not further defined"
cap label var F0300 "Social sciences, journalism and information not further defined"
cap label var F031 "Social and behavioural sciences"
cap label var F0310 "Social and behavioural sciences not further defined"
cap label var F0311 "Economics"
cap label var F0312 "Political sciences and civics"
cap label var F0313 "Psychology"
cap label var F0314 "Sociology and cultural studies"
cap label var F0319 "Social and behavioural sciences not elsewhere classified"
cap label var F032 "Journalism and information"
cap label var F0320 "Journalism and information not further defined"
cap label var F0321 "Journalism and reporting"
cap label var F0322 "Library, information and archival studies"
cap label var F0329 "Journalism and information not elsewhere classified"
cap label var F038 "Inter-disciplinary programmes and qualifications involving social sciences, journalism and information"
cap label var F0388 "Inter-disciplinary programmes and qualifications involving social sciences, journalism and information"
cap label var F039 "Social sciences, journalism and information not elsewhere classified"
cap label var F0399 "Social sciences, journalism and information not elsewhere classified"
cap label var F04 "Business, administration and law"
cap label var F040 "Business, administration and law not further defined"
cap label var F0400 "Business, administration and law not further defined"
cap label var F041 "Business and administration"
cap label var F0410 "Business and administration not further defined"
cap label var F0411 "Accounting and taxation"
cap label var F0412 "Finance, banking and insurance"
cap label var F0413 "Management and administration"
cap label var F0414 "Marketing and advertising"
cap label var F0415 "Secretarial and office work"
cap label var F0416 "Wholesale and retail sales"
cap label var F0417 "Work skills"
cap label var F0419 "Business and administration not elsewhere classified"
cap label var F042 "Law"
cap label var F0421 "Law"
cap label var F048 "Inter-disciplinary programmes and qualifications involving business, administration and law"
cap label var F0488 "Inter-disciplinary programmes and qualifications involving business, administration and law"
cap label var F049 "Business, administration and law not elsewhere classified"
cap label var F0499 "Business, administration and law not elsewhere classified"
cap label var F05 "Natural sciences, mathematics and statistics"
cap label var F050 "Natural sciences, mathematics and statistics not further defined"
cap label var F0500 "Natural sciences, mathematics and statistics not further defined"
cap label var F051 "Biological and related sciences"
cap label var F0510 "Biological and related sciences not further defined"
cap label var F0511_0512 "Biology and biochemistry"
cap label var F0511 "Biology"
cap label var F0512 "Biochemistry"
cap label var F0519 "Biological and related sciences not elsewhere classified"
cap label var F052 "Environment"
cap label var F0520 "Environment not further defined"
cap label var F0521 "Environmental sciences"
cap label var F0522 "Natural environments and wildlife"
cap label var F0529 "Environment not elsewhere classified"
cap label var F053 "Physical sciences"
cap label var F0530 "Physical sciences not further defined"
cap label var F0531 "Chemistry"
cap label var F0532 "Earth sciences"
cap label var F0533 "Physics"
cap label var F0539 "Physical sciences not elsewhere classified"
cap label var F054 "Mathematics and statistics"
cap label var F0540 "Mathematics and statistics not further defined"
cap label var F0541 "Mathematics"
cap label var F0542 "Statistics"
cap label var F058 "Inter-disciplinary programmes and qualifications involving natural sciences, mathematics and statistics"
cap label var F0588 "Inter-disciplinary programmes and qualifications involving natural sciences, mathematics and statistics"
cap label var F059 "Natural sciences, mathematics and statistics not elsewhere classified"
cap label var F0599 "Natural sciences, mathematics and statistics not elsewhere classified"
cap label var F06 "Information and Communication Technologies"
cap label var F061 "Information and Communication Technologies"
cap label var F0610 "Information and Communication Technologies not further defined"
cap label var F0611 "Computer use"
cap label var F0612_0613 "Database and network design and administration, software and applications development and analysis"
cap label var F0612 "Database and network design and administration"
cap label var F0613 "Software and applications development and analysis"
cap label var F0619 "Information and Communication Technologies not elsewhere classified"
cap label var F068 "Inter-disciplinary programmes and qualifications involving information and Communication Technologies"
cap label var F0688 "Inter-disciplinary programmes and qualifications involving information and Communication Technologies"
cap label var F07 "Engineering, manufacturing and construction"
cap label var F070 "Engineering, manufacturing and construction not further defined"
cap label var F0700 "Engineering, manufacturing and construction not further defined"
cap label var F071 "Engineering and engineering trades"
cap label var F0710 "Engineering and engineering trades not further defined"
cap label var F0711 "Chemical engineering and processes"
cap label var F0712 "Environmental protection technology"
cap label var F0713 "Electricity and energy"
cap label var F0714 "Electronics and automation"
cap label var F0715 "Mechanics and metal trades"
cap label var F0716 "Motor vehicles, ships and aircraft"
cap label var F0719 "Engineering and engineering trades not elsewhere classified"
cap label var F072 "Manufacturing and processing"
cap label var F0720 "Manufacturing and processing not further defined"
cap label var F0721 "Food processing"
cap label var F0722 "Materials (glass, paper, plastic and wood)"
cap label var F0723 "Textiles (clothes, footwear and leather)"
cap label var F0724 "Mining and extraction"
cap label var F0729 "Manufacturing and processing not elsewhere classified"
cap label var F073 "Architecture and construction"
cap label var F0730 "Architecture and construction not further defined"
cap label var F0731 "Architecture and town planning"
cap label var F0732 "Building and civil engineering"
cap label var F078 "Inter-disciplinary programmes and qualifications involving engineering, manufacturing and construction"
cap label var F0788 "Inter-disciplinary programmes and qualifications involving engineering, manufacturing and construction"
cap label var F079 "Engineering, manufacturing and construction not elsewhere classified"
cap label var F0799 "Engineering, manufacturing and construction not elsewhere classified"
cap label var F08 "Agriculture, forestry, fisheries and veterinary"
cap label var F080 "Agriculture, forestry, fisheries and veterinary not further defined"
cap label var F0800 "Agriculture, forestry, fisheries and veterinary not further defined"
cap label var F081_083_088 "Agriculture, forestry and fishery"
cap label var F081 "Agriculture"
cap label var F0810 "Agriculture not further defined"
cap label var F0811 "Crop and livestock production"
cap label var F0812 "Horticulture"
cap label var F0819 "Agriculture not elsewhere classified"
cap label var F082 "Forestry"
cap label var F0821 "Forestry"
cap label var F083 "Fisheries"
cap label var F0831 "Fisheries"
cap label var F084 "Veterinary"
cap label var F0841 "Veterinary"
cap label var F088 "Inter-disciplinary programmes and qualifications involving agriculture, forestry, fisheries and veterinary"
cap label var F0888 "Inter-disciplinary programmes and qualifications involving agriculture, forestry, fisheries and veterinary"
cap label var F089 "Agriculture, forestry, fisheries and veterinary not elsewhere classified"
cap label var F0899 "Agriculture, forestry, fisheries and veterinary not elsewhere classified"
cap label var F09 "Health and welfare"
cap label var F090 "Health and welfare not further defined"
cap label var F0900 "Health and welfare not further defined"
cap label var F091 "Health"
cap label var F0910 "Health not further defined"
cap label var F0911 "Dental studies"
cap label var F0912_0915_0917 "Medicine, therapy and rehabilitation"
cap label var F0912 "Medicine"
cap label var F0913_0921 "Nursing, midwifery and caringcare of the elderly and of disabled adults"
cap label var F0913 "Nursing and midwifery"
cap label var F0914 "Medical diagnostic and treatment technology"
cap label var F0915 "Therapy and rehabilitation"
cap label var F0916 "Pharmacy"
cap label var F0917 "Traditional and complementary medicine and therapy"
cap label var F0919 "Health not elsewhere classified"
cap label var F092 "Welfare"
cap label var F0920 "Welfare not further defined"
cap label var F0921 "Care of the elderly and of disabled adults"
cap label var F0922 "Child care and youth services"
cap label var F0923 "Social work and counselling"
cap label var F0929 "Welfare not elsewhere classified"
cap label var F098 "Inter-disciplinary programmes and qualifications involving health and welfare"
cap label var F0988 "Inter-disciplinary programmes and qualifications involving health and welfare"
cap label var F099 "Health and welfare not elsewhere classified"
cap label var F0999 "Health and welfare not elsewhere classified"
cap label var F10 "Services"
cap label var F100 "Services not further defined"
cap label var F1000 "Services not further defined"
cap label var F101 "Personal services"
cap label var F1010 "Personal services not further defined"
cap label var F1011 "Domestic services"
cap label var F1012 "Hair and beauty services"
cap label var F1013 "Hotel, restaurants and catering"
cap label var F1014 "Sports"
cap label var F1015 "Travel, tourism and leisure"
cap label var F1019 "Personal services not elsewhere classified"
cap label var F102 "Hygiene and occupational health services"
cap label var F1020 "Hygiene and occupational health services not further defined"
cap label var F1021 "Community sanitation"
cap label var F1022 "Occupational health and safety"
cap label var F1029 "Hygiene and occupational health services not elsewhere classified"
cap label var F103 "Security services"
cap label var F1030 "Security services not further defined"
cap label var F1031 "Military and defence"
cap label var F1032 "Protection of persons and property"
cap label var F1039 "Security services not elsewhere classified"
cap label var F104 "Transport services"
cap label var F1041 "Transport services"
cap label var F108 "Inter-disciplinary programmes and qualifications involving services"
cap label var F1088 "Inter-disciplinary programmes and qualifications involving services"
cap label var F109 "Services not elsewhere classified"
cap label var F1099 "Services not elsewhere classified"
cap label var OTH "Other"
cap label var NSP "Not specified"
cap label var NRP "No response"
cap label var UNK "Unknown"
