cap label var ENT_INT "Enterprises within the enterprise group"
cap label var MKT_SUPPL "Suppliers of equipment, materials, components or software"
cap label var MKT_CLCU "Clients or customers"
cap label var MKT_PRV_CLCU "Clients or customers from the private sector"
cap label var MKT_PUB_CLCU "Clients or customers from the public sector"
cap label var MKT_COMP "Competitors or other enterprises of the same sector"
cap label var MKT_CN_PRV_RI "Consultants, commercial labs, private research institute"
cap label var MKT_CN "Consultants or commercial labs"
cap label var UNIV "Universities or other higher education institutions"
cap label var GOV_PUB_RI "Government or public research institutes"
cap label var PRV_RI "Private research institutes"
cap label var CONF_TRDF_EXHIB "Conferences, trade fairs or exhibitions"
cap label var JRNST_TRDP "Scientific/technical journals or trade publications"
cap label var ASS_PROF_IND "Professional or industry associations"
cap label var PAT_PUBL "Published patents"
cap label var DOC_STD_COM "Standardisation documents or committees"
cap label var WEB_NET_CDS "Social web-based networks or crowd-sourcing"
cap label var B2B_OS "Open business-to-business platforms or open-source software"
cap label var RE "Reverse engineering"
