cap label var TOTAL "Total"
cap label var TOT_X_TM "All vehicles (except trailers and motorcycles)"
cap label var PUB "Public transportation vehicles"
cap label var TRN_BUS_TOT_AVD "Trains, motor coaches, buses and trolley buses - sum of available data"
cap label var TRN "Trains"
cap label var TRN_HSPD "High speed trains"
cap label var TRN_THSPD "Tilting high speed trains"
cap label var TRN_CV "Conventional trains"
cap label var TST_HSPD "High speed trainsets"
cap label var TST_THSPD "Tilting high speed trainsets"
cap label var TST_CV "Conventional trainsets"
cap label var LOC "Locomotives"
cap label var LOC_ELC "Electric locomotives"
cap label var LOC_DIE "Diesel locomotives"
cap label var LOC_STM "Steam locomotives"
cap label var RCA "Railcars"
cap label var RCA_ELC "Electric railcars"
cap label var RCA_DIE "Diesel railcars"
cap label var RL_PAS "Passenger railway vehicles"
cap label var COA_RCA_TRL "Coaches and railcar trailers"
cap label var RCA_PAS "Passenger railcars"
cap label var COU "Couchette coaches, sleeping cars"
cap label var DIN "Dining cars"
cap label var COA "Coaches"
cap label var VAN "Vans"
cap label var WAG "Wagons"
cap label var WAG_GD "Goods wagons - total"
cap label var WAG_GD_LD "Goods wagons - loaded"
cap label var WAG_GD_EMP "Goods wagons - empty"
cap label var WAG_COV "Covered wagons"
cap label var WAG_HIS "High sided wagons"
cap label var WAG_FLT "Flat wagons"
cap label var WAG_IMOD "Wagons for intermodal transport"
cap label var WAG_OTH "Other wagons"
cap label var RDVEH "Road vehicles"
cap label var RDVEH_PAS "Passenger road vehicles"
cap label var RDVEH_GD "Goods road vehicles"
cap label var UTL "Total utility vehicles"
cap label var LOR_RTRN "Lorries and road trains"
cap label var LOR_TRL21 "Lorries and trailers - 2+1 axles"
cap label var LOR_TRL22 "Lorries and trailers - 2+2 axles"
cap label var LOR_TRL23 "Lorries and trailers - 2+3 axles"
cap label var LOR_TRL32 "Lorries and trailers - 3+2 axles"
cap label var LOR_TRL33 "Lorries and trailers - 3+3 axles"
cap label var LOR_TRL_OTH "Lorries and trailers - other"
cap label var LOR "Lorries"
cap label var LOR2 "Lorries - 2 axles"
cap label var LOR3 "Lorries - 3 axles"
cap label var LOR4 "Lorries - 4 axles"
cap label var LOR_LE3P5 "Lorries <= 3.5 tonnes"
cap label var LOR_LE3P5_PET "Lorries <= 3.5 tonnes - petrol"
cap label var LOR_LE3P5_DIE "Lorries <= 3.5 tonnes - diesel"
cap label var LOR_LE3P5_OTH "Lorries <= 3.5 tonnes - other fuel"
cap label var LOR_GT3P5_6 "Lorries from > 3.5 to <= 6 tonnes"
cap label var LOR_GT3P5_6_DIE "Lorries from > 3.5 to <= 6 tonnes - diesel"
cap label var LOR_GT3P5_6_OTH "Lorries from > 3.5 to <= 6 tonnes - other fuel"
cap label var LOR_GT6 "Lorries > 6 tonnes"
cap label var LOR_GT6_DIE "Lorries > 6 tonnes - diesel"
cap label var LOR_GT6_OTH "Lorries > 6 tonnes - other fuel"
cap label var LOR_LE3P5_CNG "Lorries <= 3.5 tonnes - bi-fuel: petrol or CNG"
cap label var LOR_LE3P5_LPG "Lorries <= 3.5 tonnes - bi-fuel: petrol or LPG"
cap label var LOR_OTH "Lorries - other"
cap label var TRC "Road tractors"
cap label var TRC_AGR "Agricultural tractors"
cap label var TRC_AV "Road tractors and articulated vehicles"
cap label var TRC_STRL21 "Road tractors and semi-trailers - 2+1 axles"
cap label var TRC_STRL22 "Road tractors and semi-trailers - 2+2 axles"
cap label var TRC_STRL23 "Road tractors and semi-trailers - 2+3 axles"
cap label var TRC_STRL32 "Road tractors and semi-trailers - 3+2 axles"
cap label var TRC_STRL33 "Road tractors and semi-trailers - 3+3 axles"
cap label var TRC_STRL_OTH "Road tractors and semi-trailers - other"
cap label var TRL_STRL "Trailers and semi-trailers"
cap label var TRL "Trailers"
cap label var STRL "Semi-trailers"
cap label var VEH_GD "Goods road vehicles"
cap label var VG_LE3P5 "Goods vehicles <= 3.5 tonnes"
cap label var VG_LE3P5_PET "Goods vehicles <= 3.5 tonnes - petrol"
cap label var VG_LE3P5_DIE "Goods vehicles <= 3.5 tonnes - diesel"
cap label var VG_LE3P5_OTH "Goods vehicles <= 3.5 tonnes - other fuel"
cap label var VG_GT3P5 "Goods vehicles > 3.5 tonnes"
cap label var VG_GT3P5_PET "Goods vehicles > 3.5 tonnes - petrol"
cap label var VG_GT3P5_DIE "Goods vehicles > 3.5 tonnes - diesel"
cap label var VG_GT3P5_OTH "Goods vehicles > 3.5 tonnes - other fuel"
cap label var VG_GT3P5_6 "Goods vehicles from > 3.5 to <= 6 tonnes"
cap label var VG_GT3P5_6_PET "Goods vehicles from > 3.5 to <= 6 tonnes - petrol"
cap label var VG_GT3P5_6_DIE "Goods vehicles from > 3.5 to <= 6 tonnes - diesel"
cap label var VG_GT3P5_6_OTH "Goods vehicles from > 3.5 to <= 6 tonnes - other fuel"
cap label var VG_GT6 "Goods vehicles > 6 tonnes"
cap label var VG_GT6_12 "Goods vehicles from > 6 to <= 12 tonnes"
cap label var VG_GT12 "Goods vehicles > 12 tonnes"
cap label var MOTO_MOP "Motorcycles and mopeds"
cap label var MOP "Mopeds"
cap label var MOTO "Motorcycles"
cap label var MOTO_GT50 "Motorcycles > 50cm3"
cap label var MOTO_LE125 "Motorcycles <= 125cm3"
cap label var MOTO_GT125 "Motorcycles > 125cm3"
cap label var MOTO_NSP "Motorcycles not specified"
cap label var MOTO_2WH "Two-wheeled road motor vehicles (motorcycles)"
cap label var QUA_LE50 "Quads <= 50cm3"
cap label var QUA_GT50 "Quads > 50cm3"
cap label var CAR "Passenger cars"
cap label var CAR_PET "Passenger cars - petrol"
cap label var CAR_PET_HYB "Passenger cars - petrol hybrid (plug-in or not)"
cap label var CAR_DIE "Passenger cars - diesel"
cap label var CAR_DIE_HYB "Passenger cars - diesel hybrid (plug-in or not)"
cap label var CAR_ELC "Passenger cars - electric"
cap label var CAR_HG "Passenger cars - hydrogen"
cap label var CAR_LPG "Passenger cars - LPG"
cap label var CAR_MULTI "Passenger cars - multi-fuel and other fuel (excluding fuel with designated coding)"
cap label var CAR_CNG "Passenger cars - CNG"
cap label var CAR_PET_FLX "Passenger cars - flex-fuel: petrol/ethanol (E85)"
cap label var CAR_DIE_FLX "Passenger cars - flex-fuel: diesel/bio-diesel"
cap label var CAR_PET_HYD "Passenger cars - bi-fuel: petrol or hydrogen"
cap label var CAR_PET_LPG "Passenger cars - bi-fuel: petrol or LPG"
cap label var CAR_PET_CNG "Passenger cars - bi-fuel: petrol or CNG"
cap label var CAR_OTH "Passenger cars - other fuel"
cap label var BUS_TOT "Motor coaches, buses and trolley buses"
cap label var BUS_MCO "Buses and motor coaches"
cap label var BUS_MCO_DIE "Buses and motor coaches - diesel"
cap label var BUS_MCO_PET "Other buses and motor coaches - petrol"
cap label var BUS_MCO_LPG "Other buses and motor coaches - LPG"
cap label var BUS_MCO_CNG "Other buses and motor coaches - LNG or CNG"
cap label var BUS_MCO_MIN "Mini-buses and mini-coaches"
cap label var BUS_MIN "Mini-buses"
cap label var BUS_MCO_OTH "Other buses and motor coaches"
cap label var BUS "Buses"
cap label var BUS_DIE "Buses - diesel"
cap label var BUS_DIE_HYB "Buses - diesel-hybrid"
cap label var BUS_ELC "Buses - electric"
cap label var BUS_LPG "Buses - LPG"
cap label var BUS_CNG "Buses - CNG"
cap label var BUS_OTH "Buses - other fuel"
cap label var BUS_TRO "Trolley buses"
cap label var TRM_LR "Trams and light rail vehicles"
cap label var MCO "Motor coaches"
cap label var MCO_DIE "Motor coaches - diesel"
cap label var MCO_OTH "Motor coaches - other fuel"
cap label var BIKE "Bicycles"
cap label var SPE "Special vehicles"
cap label var MTZ_OTH "Other motorized vehicles"
cap label var MTZ_OTH_PET "Other motorized vehicles - petrol"
cap label var MTZ_OTH_DIE "Other motorized vehicles - diesel"
cap label var MTZ_OTH_LPG "Other motorized vehicles - LPG"
cap label var MTZ_OTH_CNG "Other motorized vehicles - CNG"
cap label var MTZ_OTH_OTH "Other motorized vehicles - other fuel"
cap label var NMTZ_OTH "Other non-motorized vehicles"
cap label var ANI_RD "Riding animals"
cap label var OTH "Other"
cap label var UNK "Unknown"
