cap label var TOTAL "Total"
cap label var OP "All operators"
cap label var PRD "Producers"
cap label var PRR "Producers"
cap label var PRR_MAIN "Main activity producers"
cap label var PRR_AUTO "Autoproducers"
cap label var PRD_AGRI "Agricultural producers"
cap label var PRR_AGRI "Agricultural producers"
cap label var PRD_AGRI_PRC "Agricultural producers which are also processors"
cap label var PRR_AGRI_PRC "Agricultural producers which are also processors"
cap label var PRD_AGRI_IMP "Agricultural producers which are also importers"
cap label var PRR_AGRI_IMP "Agricultural producers which are also importers"
cap label var PRD_AGRI_HM "Agricultural producers of eggs according to harmonised methodology"
cap label var PRR_AGRI_HM "Agricultural producers of eggs according to harmonised methodology"
cap label var PRD_AGRI_HEN350_5000_HM "Agricultural producers of eggs with 350 to 5 000 laying hens according to harmonised methodology"
cap label var PRR_AGRI_HEN350_5000_HM "Agricultural producers of eggs with 350 to 5 000 laying hens according to harmonised methodology"
cap label var PRD_AGRI_HEN_GT5000_HM "Agricultural producers of eggs with more than 5 000 laying hens according to harmonised methodology"
cap label var PRR_AGRI_HEN_GT5000_HM "Agricultural producers of eggs with more than 5 000 laying hens according to harmonised methodology"
cap label var PRD_AGRI_NHM "Agricultural producers of eggs outside harmonised methodology"
cap label var PRR_AGRI_NHM "Agricultural producers of eggs outside harmonised methodology"
cap label var PRD_AGRI_OTH "Agricultural producers - others (n.e.c.)"
cap label var PRR_AGRI_OTH "Agricultural producers - others (n.e.c.)"
cap label var PRD_AQUA "Aquaculture producers"
cap label var PRR_AQUA "Aquaculture producers"
cap label var PRD_AQUA_PL "Aquaculture producers of aquatic plants"
cap label var PRR_AQUA_PL "Aquaculture producers of aquatic plants"
cap label var PRD_ONL "Producers only"
cap label var PRR_ONL "Producers only"
cap label var PRD_PRC "Producers which are also processors"
cap label var PRR_PRC "Producers which are also processors"
cap label var PRD_IMP "Producers which are also importers"
cap label var PRR_IMP "Producers which are also importers"
cap label var PRD_PRC_IMP "Producers which are also processors and importers"
cap label var PRR_PRC_IMP "Producers which are also processors and importers"
cap label var PRC "Processors"
cap label var PRC_IMP "Processors which are also importers"
cap label var PRC_OTH "Processors - other (n.e.c.)"
cap label var PRC_ONL "Processors only"
cap label var IMP "Importers"
cap label var IMP_ONL "Importers only"
cap label var IMP_NAL "Importers not allocated"
cap label var EXP "Exporters"
cap label var EXP_ONL "Exporters only"
cap label var EXP_NAL "Exporters not allocated"
cap label var OWT "One-way trader"
cap label var TWT "Two-way traders"
cap label var PCK_EGG_PRD_AGRI "Packers receiving eggs from agricultural producers"
cap label var PCK_EGG_PRR_AGRI "Packers receiving eggs from agricultural producers"
cap label var OTH_EGG_PRD_AGRI "Other operators receiving eggs from agricultural producers"
cap label var OTH_EGG_PRR_AGRI "Other operators receiving eggs from agricultural producers"
cap label var OTH "Other operators"
cap label var OTH_TRD "Other operators - traders"
cap label var OTH_TRD_WHLS "Other operators - traders - wholesalers"
cap label var OTH_TRD_RTL "Other operators - traders - retailers"
cap label var OTH_NEC "Other operators n.e.c."
cap label var NAL "Not allocated"
