cap label var TOTAL "Total"
cap label var OC1_5 "Non manual workers"
cap label var OC1_3 "Managers, professionals, technicians and associate professionals"
cap label var OC1 "Managers"
cap label var OC11 "Chief executives, senior officials and legislators"
cap label var OC111 "Legislators and senior officials"
cap label var OC1111 "Legislators"
cap label var OC1112 "Senior government officials"
cap label var OC1113 "Traditional chiefs and heads of village"
cap label var OC1114 "Senior officials of special-interest organizations"
cap label var OC112 "Managing directors and chief executives"
cap label var OC1120 "Managing directors and chief executives"
cap label var OC12 "Administrative and commercial managers"
cap label var OC121 "Business services and administration managers"
cap label var OC1211 "Finance managers"
cap label var OC1212 "Human resource managers"
cap label var OC1213 "Policy and planning managers"
cap label var OC1219 "Business services and administration managers not elsewhere classified"
cap label var OC122 "Sales, marketing and development managers"
cap label var OC1221 "Sales and marketing managers"
cap label var OC1222 "Advertising and public relations managers"
cap label var OC1223 "Research and development managers"
cap label var OC13 "Production and specialised services managers"
cap label var OC131 "Production managers in agriculture, forestry and fisheries"
cap label var OC1311 "Agricultural and forestry production managers"
cap label var OC1312 "Aquaculture and fisheries production managers"
cap label var OC132 "Manufacturing, mining, construction, and distribution managers"
cap label var OC1321 "Manufacturing managers"
cap label var OC1322 "Mining managers"
cap label var OC1323 "Construction managers"
cap label var OC1324 "Supply, distribution and related managers"
cap label var OC133 "Information and communications technology service managers"
cap label var OC1330 "Information and communications technology service managers"
cap label var OC134 "Professional services managers"
cap label var OC1341 "Child care services managers"
cap label var OC1342 "Health services managers"
cap label var OC1343 "Aged care services managers"
cap label var OC1344 "Social welfare managers"
cap label var OC1345 "Education managers"
cap label var OC1346 "Financial and insurance services branch managers"
cap label var OC1349 "Professional services managers not elsewhere classified"
cap label var OC14 "Hospitality, retail and other services managers"
cap label var OC141 "Hotel and restaurant managers"
cap label var OC1411 "Hotel managers"
cap label var OC1412 "Restaurant managers"
cap label var OC142 "Retail and wholesale trade managers"
cap label var OC1420 "Retail and wholesale trade managers"
cap label var OC143 "Other services managers"
cap label var OC1431 "Sports, recreation and cultural centre managers"
cap label var OC1439 "Services managers not elsewhere classified"
cap label var OC2 "Professionals"
cap label var OC21 "Science and engineering professionals"
cap label var OC211 "Physical and earth science professionals"
cap label var OC2111 "Physicists and astronomers"
cap label var OC2112 "Meteorologists"
cap label var OC2113 "Chemists"
cap label var OC2114 "Geologists and geophysicists"
cap label var OC212 "Mathematicians, actuaries and statisticians"
cap label var OC2120 "Mathematicians, actuaries and statisticians"
cap label var OC213 "Life science professionals"
cap label var OC2131 "Biologists, botanists, zoologists and related professionals"
cap label var OC2132 "Farming, forestry and fisheries advisers"
cap label var OC2133 "Environmental protection professionals"
cap label var OC214 "Engineering professionals (excluding electrotechnology)"
cap label var OC2141 "Industrial and production engineers"
cap label var OC2142 "Civil engineers"
cap label var OC2143 "Environmental engineers"
cap label var OC2144 "Mechanical engineers"
cap label var OC2145 "Chemical engineers"
cap label var OC2146 "Mining engineers, metallurgists and related professionals"
cap label var OC2149 "Engineering professionals not elsewhere classified"
cap label var OC215 "Electrotechnology engineers"
cap label var OC2151 "Electrical engineers"
cap label var OC2152 "Electronics engineers"
cap label var OC2153 "Telecommunications engineers"
cap label var OC216 "Architects, planners, surveyors and designers"
cap label var OC2161 "Building architects"
cap label var OC2162 "Landscape architects"
cap label var OC2163 "Product and garment designers"
cap label var OC2164 "Town and traffic planners"
cap label var OC2165 "Cartographers and surveyors"
cap label var OC2166 "Graphic and multimedia designers"
cap label var OC22 "Health professionals"
cap label var OC221 "Medical doctors"
cap label var OC2211 "Generalist medical practitioners"
cap label var OC2212 "Specialist medical practitioners"
cap label var OC222_322_5321_5322 "Nurses, midewives, health care assistants and home-based personal care workers"
cap label var OC222_322_5321 "Nurses, midewives and health care assistants"
cap label var OC222_322 "Nurses and midwives"
cap label var OC222_3222 "Nursing professionals and midwives"
cap label var OC222 "Nursing and midwifery professionals"
cap label var OC2221_3221 "Nurses"
cap label var OC2221 "Nursing professionals"
cap label var OC2222_3222 "Midwives"
cap label var OC2222 "Midwifery professionals"
cap label var OC223 "Traditional and complementary medicine professionals"
cap label var OC2230 "Traditional and complementary medicine professionals"
cap label var OC224 "Paramedical practitioners"
cap label var OC2240 "Paramedical practitioners"
cap label var OC225 "Veterinarians"
cap label var OC2250 "Veterinarians"
cap label var OC226 "Other health professionals"
cap label var OC2261 "Dentists"
cap label var OC2262 "Pharmacists"
cap label var OC2263 "Environmental and occupational health and hygiene professionals"
cap label var OC2264 "Physiotherapists"
cap label var OC2265 "Dieticians and nutritionists"
cap label var OC2266 "Audiologists and speech therapists"
cap label var OC2267 "Optometrists and ophthalmic opticians"
cap label var OC2269 "Health professionals not elsewhere classified"
cap label var OC23 "Teaching professionals"
cap label var OC231 "University and higher education teachers"
cap label var OC2310 "University and higher education teachers"
cap label var OC232 "Vocational education teachers"
cap label var OC2320 "Vocational education teachers"
cap label var OC233 "Secondary education teachers"
cap label var OC2330 "Secondary education teachers"
cap label var OC234 "Primary school and early childhood teachers"
cap label var OC2341 "Primary school teachers"
cap label var OC2342 "Early childhood educators"
cap label var OC235 "Other teaching professionals"
cap label var OC2351 "Education methods specialists"
cap label var OC2352 "Special needs teachers"
cap label var OC2353 "Other language teachers"
cap label var OC2354 "Other music teachers"
cap label var OC2355 "Other arts teachers"
cap label var OC2356 "Information technology trainers"
cap label var OC2359 "Teaching professionals not elsewhere classified"
cap label var OC24 "Business and administration professionals"
cap label var OC241 "Finance professionals"
cap label var OC2411 "Accountants"
cap label var OC2412 "Financial and investment advisers"
cap label var OC2413 "Financial analysts"
cap label var OC242 "Administration professionals"
cap label var OC2421 "Management and organization analysts"
cap label var OC2422 "Policy administration professionals"
cap label var OC2423 "Personnel and careers professionals"
cap label var OC2424 "Training and staff development professionals"
cap label var OC243 "Sales, marketing and public relations professionals"
cap label var OC2431 "Advertising and marketing professionals"
cap label var OC2432 "Public relations professionals"
cap label var OC2433 "Technical and medical sales professionals (excluding ICT)"
cap label var OC2434 "Information and communications technology sales professionals"
cap label var OC25 "Information and communications technology professionals"
cap label var OC251 "Software and applications developers and analysts"
cap label var OC2511 "Systems analysts"
cap label var OC2512 "Software developers"
cap label var OC2513 "Web and multimedia developers"
cap label var OC2514 "Applications programmers"
cap label var OC2519 "Software and applications developers and analysts not elsewhere classified"
cap label var OC252 "Database and network professionals"
cap label var OC2521 "Database designers and administrators"
cap label var OC2522 "Systems administrators"
cap label var OC2523 "Computer network professionals"
cap label var OC2529 "Database and network professionals not elsewhere classified"
cap label var OC26 "Legal, social and cultural professionals"
cap label var OC261 "Legal professionals"
cap label var OC2611 "Lawyers"
cap label var OC2612 "Judges"
cap label var OC2612A "Professional judges"
cap label var OC2612B "Non professional judges and magistrates"
cap label var OC2619 "Legal professionals not elsewhere classified"
cap label var OC262 "Librarians, archivists and curators"
cap label var OC2621 "Archivists and curators"
cap label var OC2622 "Librarians and related information professionals"
cap label var OC263 "Social and religious professionals"
cap label var OC2631 "Economists"
cap label var OC2632 "Sociologists, anthropologists and related professionals"
cap label var OC2633 "Philosophers, historians and political scientists"
cap label var OC2634_2212PSY "Psychologists, psychotherapists or psychiatrists"
cap label var OC2634 "Psychologists"
cap label var OC2635 "Social work and counselling professionals"
cap label var OC2636 "Religious professionals"
cap label var OC264_265 "Authors, journalists, linguists and creative and performing artists"
cap label var OC264 "Authors, journalists and linguists"
cap label var OC2641 "Authors and related writers"
cap label var OC2642 "Journalists"
cap label var OC2643 "Translators, interpreters and other linguists"
cap label var OC265 "Creative and performing artists"
cap label var OC2651 "Visual artists"
cap label var OC2652 "Musicians, singers and composers"
cap label var OC2653 "Dancers and choreographers"
cap label var OC2654 "Film, stage and related directors and producers"
cap label var OC2655 "Actors"
cap label var OC2656 "Announcers on radio, television and other media"
cap label var OC2659 "Creative and performing artists not elsewhere classified"
cap label var OC3 "Technicians and associate professionals"
cap label var OC31 "Science and engineering associate professionals"
cap label var OC311 "Physical and engineering science technicians"
cap label var OC3111 "Chemical and physical science technicians"
cap label var OC3112 "Civil engineering technicians"
cap label var OC3113 "Electrical engineering technicians"
cap label var OC3114 "Electronics engineering technicians"
cap label var OC3115 "Mechanical engineering technicians"
cap label var OC3116 "Chemical engineering technicians"
cap label var OC3117 "Mining and metallurgical technicians"
cap label var OC3118 "Draughtspersons"
cap label var OC3119 "Physical and engineering science technicians not elsewhere classified"
cap label var OC312 "Mining, manufacturing and construction supervisors"
cap label var OC3121 "Mining supervisors"
cap label var OC3122 "Manufacturing supervisors"
cap label var OC3123 "Construction supervisors"
cap label var OC313 "Process control technicians"
cap label var OC3131 "Power production plant operators"
cap label var OC3132 "Incinerator and water treatment plant operators"
cap label var OC3133 "Chemical processing plant controllers"
cap label var OC3134 "Petroleum and natural gas refining plant operators"
cap label var OC3135 "Metal production process controllers"
cap label var OC3139 "Process control technicians not elsewhere classified"
cap label var OC314 "Life science technicians and related associate professionals"
cap label var OC3141 "Life science technicians (excluding medical)"
cap label var OC3142 "Agricultural technicians"
cap label var OC3143 "Forestry technicians"
cap label var OC315 "Ship and aircraft controllers and technicians"
cap label var OC3151 "Ships' engineers"
cap label var OC3152 "Ships' deck officers and pilots"
cap label var OC3153 "Aircraft pilots and related associate professionals"
cap label var OC3154 "Air traffic controllers"
cap label var OC3155 "Air traffic safety electronics technicians"
cap label var OC32 "Health associate professionals"
cap label var OC321 "Medical and pharmaceutical technicians"
cap label var OC3211 "Medical imaging and therapeutic equipment technicians"
cap label var OC3212 "Medical and pathology laboratory technicians"
cap label var OC3213 "Pharmaceutical technicians and assistants"
cap label var OC3214 "Medical and dental prosthetic technicians"
cap label var OC322 "Nursing and midwifery associate professionals"
cap label var OC3221 "Nursing associate professionals"
cap label var OC3222 "Midwifery associate professionals"
cap label var OC323 "Traditional and complementary medicine associate professionals"
cap label var OC3230 "Traditional and complementary medicine associate professionals"
cap label var OC324 "Veterinary technicians and assistants"
cap label var OC3240 "Veterinary technicians and assistants"
cap label var OC325 "Other health associate professionals"
cap label var OC3251 "Dental assistants and therapists"
cap label var OC3252 "Medical records and health information technicians"
cap label var OC3253 "Community health workers"
cap label var OC3254 "Dispensing opticians"
cap label var OC3255 "Physiotherapy technicians and assistants"
cap label var OC3256 "Medical assistants"
cap label var OC3257 "Environmental and occupational health inspectors and associates"
cap label var OC3258 "Ambulance workers"
cap label var OC3259 "Health associate professionals not elsewhere classified"
cap label var OC33 "Business and administration associate professionals"
cap label var OC331 "Financial and mathematical associate professionals"
cap label var OC3311 "Securities and finance dealers and brokers"
cap label var OC3312 "Credit and loans officers"
cap label var OC3313 "Accounting associate professionals"
cap label var OC3314 "Statistical, mathematical and related associate professionals"
cap label var OC3315 "Valuers and loss assessors"
cap label var OC332 "Sales and purchasing agents and brokers"
cap label var OC3321 "Insurance representatives"
cap label var OC3322 "Commercial sales representatives"
cap label var OC3323 "Buyers"
cap label var OC3324 "Trade brokers"
cap label var OC333 "Business services agents"
cap label var OC3331 "Clearing and forwarding agents"
cap label var OC3332 "Conference and event planners"
cap label var OC3333 "Employment agents and contractors"
cap label var OC3334 "Real estate agents and property managers"
cap label var OC3339 "Business services agents not elsewhere classified"
cap label var OC334 "Administrative and specialised secretaries"
cap label var OC3341 "Office supervisors"
cap label var OC3342 "Legal secretaries"
cap label var OC3343 "Administrative and executive secretaries"
cap label var OC3344 "Medical secretaries"
cap label var OC335 "Regulatory government associate professionals"
cap label var OC3351 "Customs and border inspectors"
cap label var OC3352 "Government tax and excise officials"
cap label var OC3353 "Government social benefits officials"
cap label var OC3354 "Government licensing officials"
cap label var OC3355 "Police inspectors and detectives"
cap label var OC3359 "Regulatory government associate professionals not elsewhere classified"
cap label var OC34 "Legal, social, cultural and related associate professionals"
cap label var OC341 "Legal, social and religious associate professionals"
cap label var OC3411 "Legal and related associate professionals"
cap label var OC3412 "Social work associate professionals"
cap label var OC3413 "Religious associate professionals"
cap label var OC342 "Sports and fitness workers"
cap label var OC3421 "Athletes and sports players"
cap label var OC3422 "Sports coaches, instructors and officials"
cap label var OC3423 "Fitness and recreation instructors and program leaders"
cap label var OC343 "Artistic, cultural and culinary associate professionals"
cap label var OC3431 "Photographers"
cap label var OC3432 "Interior designers and decorators"
cap label var OC3433 "Gallery, museum and library technicians"
cap label var OC3434 "Chefs"
cap label var OC3435 "Other artistic and cultural associate professionals"
cap label var OC35 "Information and communications technicians"
cap label var OC351 "Information and communications technology operations and user support technicians"
cap label var OC3511 "Information and communications technology operations technicians"
cap label var OC3512 "Information and communications technology user support technicians"
cap label var OC3513 "Computer network and systems technicians"
cap label var OC3514 "Web technicians"
cap label var OC352 "Telecommunications and broadcasting technicians"
cap label var OC3521 "Broadcasting and audio-visual technicians"
cap label var OC3522 "Telecommunications engineering technicians"
cap label var OC4_5 "Clerical support workers, service and sales workers"
cap label var OC4 "Clerical support workers"
cap label var OC41 "General and keyboard clerks"
cap label var OC411 "General office clerks"
cap label var OC4110 "General office clerks"
cap label var OC412 "Secretaries (general)"
cap label var OC4120 "Secretaries (general)"
cap label var OC413 "Keyboard operators"
cap label var OC4131 "Typists and word processing operators"
cap label var OC4132 "Data entry clerks"
cap label var OC42 "Customer services clerks"
cap label var OC421 "Tellers, money collectors and related clerks"
cap label var OC4211 "Bank tellers and related clerks"
cap label var OC4212 "Bookmakers, croupiers and related gaming workers"
cap label var OC4213 "Pawnbrokers and money-lenders"
cap label var OC4214 "Debt-collectors and related workers"
cap label var OC422 "Client information workers"
cap label var OC4221 "Travel consultants and clerks"
cap label var OC4222 "Contact centre information clerks"
cap label var OC4223 "Telephone switchboard operators"
cap label var OC4224 "Hotel receptionists"
cap label var OC4225 "Enquiry clerks"
cap label var OC4226 "Receptionists (general)"
cap label var OC4227 "Survey and market research interviewers"
cap label var OC4229 "Client information workers not elsewhere classified"
cap label var OC43 "Numerical and material recording clerks"
cap label var OC431 "Numerical clerks"
cap label var OC4311 "Accounting and bookkeeping clerks"
cap label var OC4312 "Statistical, finance and insurance clerks"
cap label var OC4313 "Payroll clerks"
cap label var OC432 "Material-recording and transport clerks"
cap label var OC4321 "Stock clerks"
cap label var OC4322 "Production clerks"
cap label var OC4323 "Transport clerks"
cap label var OC44 "Other clerical support workers"
cap label var OC441 "Other clerical support workers"
cap label var OC4411 "Library clerks"
cap label var OC4412 "Mail carriers and sorting clerks"
cap label var OC4413 "Coding, proof-reading and related clerks"
cap label var OC4414 "Scribes and related workers"
cap label var OC4415 "Filing and copying clerks"
cap label var OC4416 "Personnel clerks"
cap label var OC4419 "Clerical support workers not elsewhere classified"
cap label var OC5 "Service and sales workers"
cap label var OC51 "Personal service workers"
cap label var OC511 "Travel attendants, conductors and guides"
cap label var OC5111 "Travel attendants and travel stewards"
cap label var OC5112 "Transport conductors"
cap label var OC5113 "Travel guides"
cap label var OC512 "Cooks"
cap label var OC5120 "Cooks"
cap label var OC513 "Waiters and bartenders"
cap label var OC5131 "Waiters"
cap label var OC5132 "Bartenders"
cap label var OC514 "Hairdressers, beauticians and related workers"
cap label var OC5141 "Hairdressers"
cap label var OC5142 "Beauticians and related workers"
cap label var OC515 "Building and housekeeping supervisors"
cap label var OC5151 "Cleaning and housekeeping supervisors in offices, hotels and other establishments"
cap label var OC5152 "Domestic housekeepers"
cap label var OC5153 "Building caretakers"
cap label var OC516 "Other personal services workers"
cap label var OC5161 "Astrologers, fortune-tellers and related workers"
cap label var OC5162 "Companions and valets"
cap label var OC5163 "Undertakers and embalmers"
cap label var OC5164 "Pet groomers and animal care workers"
cap label var OC5165 "Driving instructors"
cap label var OC5169 "Personal services workers not elsewhere classified"
cap label var OC52 "Sales workers"
cap label var OC521 "Street and market salespersons"
cap label var OC5211 "Stall and market salespersons"
cap label var OC5212 "Street food salespersons"
cap label var OC522 "Shop salespersons"
cap label var OC5221 "Shop keepers"
cap label var OC5222 "Shop supervisors"
cap label var OC5223 "Shop sales assistants"
cap label var OC523 "Cashiers and ticket clerks"
cap label var OC5230 "Cashiers and ticket clerks"
cap label var OC524 "Other sales workers"
cap label var OC5241 "Fashion and other models"
cap label var OC5242 "Sales demonstrators"
cap label var OC5243 "Door to door salespersons"
cap label var OC5244 "Contact centre salespersons"
cap label var OC5245 "Service station attendants"
cap label var OC5246 "Food service counter attendants"
cap label var OC5249 "Sales workers not elsewhere classified"
cap label var OC53 "Personal care workers"
cap label var OC531 "Child care workers and teachers' aides"
cap label var OC5311 "Child care workers"
cap label var OC5312 "Teachers' aides"
cap label var OC532 "Personal care workers in health services"
cap label var OC5321_5322 "Health care assistants and home-based personal care workers"
cap label var OC5321 "Health care assistants"
cap label var OC5322 "Home-based personal care workers"
cap label var OC5329 "Personal care workers in health services not elsewhere classified"
cap label var OC54 "Protective services workers"
cap label var OC541 "Protective services workers"
cap label var OC5411 "Fire-fighters"
cap label var OC5412 "Police officers"
cap label var OC5413 "Prison guards"
cap label var OC5414 "Security guards"
cap label var OC5419 "Protective services workers not elsewhere classified"
cap label var OC6_8 "Skilled manual workers"
cap label var OC6_7 "Skilled agricultural, forestry and fishery workers, craft and related trades workers"
cap label var OC6 "Skilled agricultural, forestry and fishery workers"
cap label var OC61 "Market-oriented skilled agricultural workers"
cap label var OC611 "Market gardeners and crop growers"
cap label var OC6111 "Field crop and vegetable growers"
cap label var OC6112 "Tree and shrub crop growers"
cap label var OC6113 "Gardeners, horticultural and nursery growers"
cap label var OC6114 "Mixed crop growers"
cap label var OC612 "Animal producers"
cap label var OC6121 "Livestock and dairy producers"
cap label var OC6122 "Poultry producers"
cap label var OC6123 "Apiarists and sericulturists"
cap label var OC6129 "Animal producers not elsewhere classified"
cap label var OC613 "Mixed crop and animal producers"
cap label var OC6130 "Mixed crop and animal producers"
cap label var OC62 "Market-oriented skilled forestry, fishery and hunting workers"
cap label var OC621 "Forestry and related workers"
cap label var OC6210 "Forestry and related workers"
cap label var OC622 "Fishery workers, hunters and trappers"
cap label var OC6221 "Aquaculture workers"
cap label var OC6222 "Inland and coastal waters fishery workers"
cap label var OC6223 "Deep-sea fishery workers"
cap label var OC6224 "Hunters and trappers"
cap label var OC63 "Subsistence farmers, fishers, hunters and gatherers"
cap label var OC631 "Subsistence crop farmers"
cap label var OC6310 "Subsistence crop farmers"
cap label var OC632 "Subsistence livestock farmers"
cap label var OC6320 "Subsistence livestock farmers"
cap label var OC633 "Subsistence mixed crop and livestock farmers"
cap label var OC6330 "Subsistence mixed crop and livestock farmers"
cap label var OC634 "Subsistence fishers, hunters, trappers and gatherers"
cap label var OC6340 "Subsistence fishers, hunters, trappers and gatherers"
cap label var OC7_9 "Manual workers"
cap label var OC7 "Craft and related trades workers"
cap label var OC71 "Building and related trades workers, excluding electricians"
cap label var OC711 "Building frame and related trades workers"
cap label var OC7111 "House builders"
cap label var OC7112 "Bricklayers and related workers"
cap label var OC7113 "Stonemasons, stone cutters, splitters and carvers"
cap label var OC7114 "Concrete placers, concrete finishers and related workers"
cap label var OC7115 "Carpenters and joiners"
cap label var OC7119 "Building frame and related trades workers not elsewhere classified"
cap label var OC712 "Building finishers and related trades workers"
cap label var OC7121 "Roofers"
cap label var OC7122 "Floor layers and tile setters"
cap label var OC7123 "Plasterers"
cap label var OC7124 "Insulation workers"
cap label var OC7125 "Glaziers"
cap label var OC7126 "Plumbers and pipe fitters"
cap label var OC7127 "Air conditioning and refrigeration mechanics"
cap label var OC713 "Painters, building structure cleaners and related trades workers"
cap label var OC7131 "Painters and related workers"
cap label var OC7132 "Spray painters and varnishers"
cap label var OC7133 "Building structure cleaners"
cap label var OC72 "Metal, machinery and related trades workers"
cap label var OC721 "Sheet and structural metal workers, moulders and welders, and related workers"
cap label var OC7211 "Metal moulders and coremakers"
cap label var OC7212 "Welders and flamecutters"
cap label var OC7213 "Sheet-metal workers"
cap label var OC7214 "Structural-metal preparers and erectors"
cap label var OC7215 "Riggers and cable splicers"
cap label var OC722 "Blacksmiths, toolmakers and related trades workers"
cap label var OC7221 "Blacksmiths, hammersmiths and forging press workers"
cap label var OC7222 "Toolmakers and related workers"
cap label var OC7223 "Metal working machine tool setters and operators"
cap label var OC7224 "Metal polishers, wheel grinders and tool sharpeners"
cap label var OC723 "Machinery mechanics and repairers"
cap label var OC7231 "Motor vehicle mechanics and repairers"
cap label var OC7232 "Aircraft engine mechanics and repairers"
cap label var OC7233 "Agricultural and industrial machinery mechanics and repairers"
cap label var OC7234 "Bicycle and related repairers"
cap label var OC73 "Handicraft and printing workers"
cap label var OC731 "Handicraft workers"
cap label var OC7311 "Precision-instrument makers and repairers"
cap label var OC7312 "Musical instrument makers and tuners"
cap label var OC7313 "Jewellery and precious-metal workers"
cap label var OC7314 "Potters and related workers"
cap label var OC7315 "Glass makers, cutters, grinders and finishers"
cap label var OC7316 "Sign writers, decorative painters, engravers and etchers"
cap label var OC7317 "Handicraft workers in wood, basketry and related materials"
cap label var OC7318 "Handicraft workers in textile, leather and related materials"
cap label var OC7319 "Handicraft workers not elsewhere classified"
cap label var OC732 "Printing trades workers"
cap label var OC7321 "Pre-press technicians"
cap label var OC7322 "Printers"
cap label var OC7323 "Print finishing and binding workers"
cap label var OC74 "Electrical and electronic trades workers"
cap label var OC741 "Electrical equipment installers and repairers"
cap label var OC7411 "Building and related electricians"
cap label var OC7412 "Electrical mechanics and fitters"
cap label var OC7413 "Electrical line installers and repairers"
cap label var OC742 "Electronics and telecommunications installers and repairers"
cap label var OC7421 "Electronics mechanics and servicers"
cap label var OC7422 "Information and communications technology installers and servicers"
cap label var OC75 "Food processing, wood working, garment and other craft and related trades workers"
cap label var OC751 "Food processing and related trades workers"
cap label var OC7511 "Butchers, fishmongers and related food preparers"
cap label var OC7512 "Bakers, pastry-cooks and confectionery makers"
cap label var OC7513 "Dairy-products makers"
cap label var OC7514 "Fruit, vegetable and related preservers"
cap label var OC7515 "Food and beverage tasters and graders"
cap label var OC7516 "Tobacco preparers and tobacco products makers"
cap label var OC752 "Wood treaters, cabinet-makers and related trades workers"
cap label var OC7521 "Wood treaters"
cap label var OC7522 "Cabinet-makers and related workers"
cap label var OC7523 "Woodworking-machine tool setters and operators"
cap label var OC753 "Garment and related trades workers"
cap label var OC7531 "Tailors, dressmakers, furriers and hatters"
cap label var OC7532 "Garment and related pattern-makers and cutters"
cap label var OC7533 "Sewing, embroidery and related workers"
cap label var OC7534 "Upholsterers and related workers"
cap label var OC7535 "Pelt dressers, tanners and fellmongers"
cap label var OC7536 "Shoemakers and related workers"
cap label var OC754 "Other craft and related workers"
cap label var OC7541 "Underwater divers"
cap label var OC7542 "Shotfirers and blasters"
cap label var OC7543 "Product graders and testers (excluding foods and beverages)"
cap label var OC7544 "Fumigators and other pest and weed controllers"
cap label var OC7549 "Craft and related workers not elsewhere classified"
cap label var OC8_9 "Plant and machine operators and assemblers, elementary occupations"
cap label var OC8 "Plant and machine operators and assemblers"
cap label var OC81 "Stationary plant and machine operators"
cap label var OC811 "Mining and mineral processing plant operators"
cap label var OC8111 "Miners and quarriers"
cap label var OC8112 "Mineral and stone processing plant operators"
cap label var OC8113 "Well drillers and borers and related workers"
cap label var OC8114 "Cement, stone and other mineral products machine operators"
cap label var OC812 "Metal processing and finishing plant operators"
cap label var OC8121 "Metal processing plant operators"
cap label var OC8122 "Metal finishing, plating and coating machine operators"
cap label var OC813 "Chemical and photographic products plant and machine operators"
cap label var OC8131 "Chemical products plant and machine operators"
cap label var OC8132 "Photographic products machine operators"
cap label var OC814 "Rubber, plastic and paper products machine operators"
cap label var OC8141 "Rubber products machine operators"
cap label var OC8142 "Plastic products machine operators"
cap label var OC8143 "Paper products machine operators"
cap label var OC815 "Textile, fur and leather products machine operators"
cap label var OC8151 "Fibre preparing, spinning and winding machine operators"
cap label var OC8152 "Weaving and knitting machine operators"
cap label var OC8153 "Sewing machine operators"
cap label var OC8154 "Bleaching, dyeing and fabric cleaning machine operators"
cap label var OC8155 "Fur and leather preparing machine operators"
cap label var OC8156 "Shoemaking and related machine operators"
cap label var OC8157 "Laundry machine operators"
cap label var OC8159 "Textile, fur and leather products machine operators not elsewhere classified"
cap label var OC816 "Food and related products machine operators"
cap label var OC8160 "Food and related products machine operators"
cap label var OC817 "Wood processing and papermaking plant operators"
cap label var OC8171 "Pulp and papermaking plant operators"
cap label var OC8172 "Wood processing plant operators"
cap label var OC818 "Other stationary plant and machine operators"
cap label var OC8181 "Glass and ceramics plant operators"
cap label var OC8182 "Steam engine and boiler operators"
cap label var OC8183 "Packing, bottling and labelling machine operators"
cap label var OC8189 "Stationary plant and machine operators not elsewhere classified"
cap label var OC82 "Assemblers"
cap label var OC821 "Assemblers"
cap label var OC8211 "Mechanical machinery assemblers"
cap label var OC8212 "Electrical and electronic equipment assemblers"
cap label var OC8219 "Assemblers not elsewhere classified"
cap label var OC83 "Drivers and mobile plant operators"
cap label var OC831 "Locomotive engine drivers and related workers"
cap label var OC8311 "Locomotive engine drivers"
cap label var OC8312 "Railway brake, signal and switch operators"
cap label var OC832 "Car, van and motorcycle drivers"
cap label var OC8321 "Motorcycle drivers"
cap label var OC8322 "Car, taxi and van drivers"
cap label var OC833 "Heavy truck and bus drivers"
cap label var OC8331 "Bus and tram drivers"
cap label var OC8332 "Heavy truck and lorry drivers"
cap label var OC834 "Mobile plant operators"
cap label var OC8341 "Mobile farm and forestry plant operators"
cap label var OC8342 "Earthmoving and related plant operators"
cap label var OC8343 "Crane, hoist and related plant operators"
cap label var OC8344 "Lifting truck operators"
cap label var OC835 "Ships' deck crews and related workers"
cap label var OC8350 "Ships' deck crews and related workers"
cap label var OC9 "Elementary occupations"
cap label var OC91 "Cleaners and helpers"
cap label var OC911 "Domestic, hotel and office cleaners and helpers"
cap label var OC9111 "Domestic cleaners and helpers"
cap label var OC9112 "Cleaners and helpers in offices, hotels and other establishments"
cap label var OC912 "Vehicle, window, laundry and other hand cleaning workers"
cap label var OC9121 "Hand launderers and pressers"
cap label var OC9122 "Vehicle cleaners"
cap label var OC9123 "Window cleaners"
cap label var OC9129 "Other cleaning workers"
cap label var OC92 "Agricultural, forestry and fishery labourers"
cap label var OC921 "Agricultural, forestry and fishery labourers"
cap label var OC9211 "Crop farm labourers"
cap label var OC9212 "Livestock farm labourers"
cap label var OC9213 "Mixed crop and livestock farm labourers"
cap label var OC9214 "Garden and horticultural labourers"
cap label var OC9215 "Forestry labourers"
cap label var OC9216 "Fishery and aquaculture labourers"
cap label var OC93 "Labourers in mining, construction, manufacturing and transport"
cap label var OC931 "Mining and construction labourers"
cap label var OC9311 "Mining and quarrying labourers"
cap label var OC9312 "Civil engineering labourers"
cap label var OC9313 "Building construction labourers"
cap label var OC932 "Manufacturing labourers"
cap label var OC9321 "Hand packers"
cap label var OC9329 "Manufacturing labourers not elsewhere classified"
cap label var OC933 "Transport and storage labourers"
cap label var OC9331 "Hand and pedal vehicle drivers"
cap label var OC9332 "Drivers of animal-drawn vehicles and machinery"
cap label var OC9333 "Freight handlers"
cap label var OC9334 "Shelf fillers"
cap label var OC94 "Food preparation assistants"
cap label var OC941 "Food preparation assistants"
cap label var OC9411 "Fast food preparers"
cap label var OC9412 "Kitchen helpers"
cap label var OC95 "Street and related sales and service workers"
cap label var OC951 "Street and related service workers"
cap label var OC9510 "Street and related service workers"
cap label var OC952 "Street vendors (excluding food)"
cap label var OC9520 "Street vendors (excluding food)"
cap label var OC96 "Refuse workers and other elementary workers"
cap label var OC961 "Refuse workers"
cap label var OC9611 "Garbage and recycling collectors"
cap label var OC9612 "Refuse sorters"
cap label var OC9613 "Sweepers and related labourers"
cap label var OC962 "Other elementary workers"
cap label var OC9621 "Messengers, package deliverers and luggage porters"
cap label var OC9622 "Odd job persons"
cap label var OC9623 "Meter readers and vending-machine collectors"
cap label var OC9624 "Water and firewood collectors"
cap label var OC9629 "Elementary workers not elsewhere classified"
cap label var OC0 "Armed forces occupations"
cap label var OC01 "Commissioned armed forces officers"
cap label var OC011 "Commissioned armed forces officers"
cap label var OC0110 "Commissioned armed forces officers"
cap label var OC02 "Non-commissioned armed forces officers"
cap label var OC021 "Non-commissioned armed forces officers"
cap label var OC0210 "Non-commissioned armed forces officers"
cap label var OC03 "Armed forces occupations, other ranks"
cap label var OC031 "Armed forces occupations, other ranks"
cap label var OC0310 "Armed forces occupations, other ranks"
cap label var OTH "Other occupations"
cap label var NAP "Not applicable"
cap label var NAP_NEMP_Y1 "Not applicable - no employment in the last year"
cap label var NAP_NEMP_Y8 "Not applicable - no employment in the last 8 years"
cap label var NRP "No response"
cap label var UNK "Unknown"
cap label var PRISA "Personnel in adult prison"
cap label var PRISJ "Personnel in juvenile prison"
cap label var HOSP "Hospital employment"
cap label var OTH_SERV "Other health service providers employed by hospital"
cap label var OTH_HOSP "Other staff employed by hospital"
