cap label var TOTAL "Total area under vines (in/not yet in production)"
cap label var WI "Vines for wine grapes - total"
cap label var WI_PDO "Vines for grapes for PDO wines"
cap label var WI_PGI "Vines for grapes for PGI wines"
cap label var WI_NP "Vines for grapes for wines with neither PDO nor PGI"
cap label var WI_DP "Vines for dual purpose grapes"
cap label var DRI "Vines for raisins"
cap label var NEC "Vines not elsewhere classified"
cap label var IN "Vines in production - total"
cap label var IN_WI "Vines in production - wine grapes - total"
cap label var IN_WI_PDO "Vines in production - grapes for PDO wines"
cap label var IN_WI_PGI "Vines in production - grapes for PGI wines"
cap label var IN_WI_NP "Vines in production - grapes for wines with neither PDO nor PGI"
cap label var IN_WI_DP "Vines in production - dual purpose grapes"
cap label var IN_DRI "Vines in production - raisins"
cap label var NIN "Vines not yet in production - total"
cap label var NIN_WI "Vines not yet in production - wine grapes - total"
cap label var NIN_WI_PDO "Vines not yet in production - grapes for PDO wines"
cap label var NIN_WI_PGI "Vines not yet in production - grapes for PGI wines"
cap label var NIN_WI_NP "Vines not yet in production - grapes for wines with neither PDO nor PGI"
cap label var NIN_WI_DP "Vines not yet in production - dual purpose grapes"
cap label var NIN_DRI "Vines not yet in production - raisins"
cap label var MAT_VP "Vines intended to produce material for the vegetative propagation of vines"
cap label var OTH "Other vines n.e.c."
