cap label var BE "Belgium"
cap label var BE001MC "Bruxelles / Brussel"
cap label var BE001MC_10 "Bruxelles / Brussel (NUTS 2010)"
cap label var BE002M "Antwerpen"
cap label var BE003M "Gent"
cap label var BE004M "Charleroi"
cap label var BE005M "Liège"
cap label var BE005M_10 "Liège (NUTS 2010)"
cap label var BE007M "Namur"
cap label var BE_NM "Non-metropolitan regions in Belgium"
cap label var BG "Bulgaria"
cap label var BG001MC "Sofia"
cap label var BG002M "Plovdiv"
cap label var BG003M "Varna"
cap label var BG004M "Burgas"
cap label var BG_NM "Non-metropolitan regions in Bulgaria"
cap label var CZ "Czechia"
cap label var CZ001MC "Praha"
cap label var CZ002M "Brno"
cap label var CZ003M "Ostrava"
cap label var CZ004M "Plzen"
cap label var CZ007M "Liberec"
cap label var CZ_NM "Non-metropolitan regions in Czech Republic"
cap label var DK "Denmark"
cap label var DK001MC "København"
cap label var DK002M "Århus"
cap label var DK003M "Odense"
cap label var DK004M "Aalborg"
cap label var DK_NM "Non-metropolitan regions in Denmark"
cap label var DE "Germany (until 1990 former territory of the FRG)"
cap label var DE001MC "Berlin"
cap label var DE002M "Hamburg"
cap label var DE003M "München"
cap label var DE004M "Köln"
cap label var DE005M "Frankfurt am Main"
cap label var DE007M "Stuttgart"
cap label var DE008M "Leipzig"
cap label var DE009M "Dresden"
cap label var DE011M "Düsseldorf"
cap label var DE012M "Bremen"
cap label var DE013M "Hannover"
cap label var DE014M "Nürnberg"
cap label var DE017M "Bielefeld"
cap label var DE018M "Halle an der Saale"
cap label var DE019M "Magdeburg"
cap label var DE020M "Wiesbaden"
cap label var DE021M "Göttingen"
cap label var DE025M "Darmstadt"
cap label var DE027M "Freiburg im Breisgau"
cap label var DE028M "Regensburg"
cap label var DE031M "Schwerin"
cap label var DE032M "Erfurt"
cap label var DE033M "Augsburg"
cap label var DE034M "Bonn"
cap label var DE035M "Karlsruhe"
cap label var DE036M "Mönchengladbach"
cap label var DE037M "Mainz"
cap label var DE038M "Ruhrgebiet"
cap label var DE039M "Kiel"
cap label var DE040M "Saarbrücken"
cap label var DE042M "Koblenz"
cap label var DE043M "Rostock"
cap label var DE044M "Kaiserslautern"
cap label var DE045M "Iserlohn"
cap label var DE052M "Flensburg"
cap label var DE053M "Marburg"
cap label var DE054M "Konstanz"
cap label var DE057M "Gießen"
cap label var DE059M "Bayreuth"
cap label var DE061M "Aschaffenburg"
cap label var DE063M "Plauen"
cap label var DE064M "Neubrandenburg"
cap label var DE064M_10 "Neubrandenburg (NUTS 2010)"
cap label var DE069M "Rosenheim"
cap label var DE073M "Offenburg"
cap label var DE074M "Görlitz"
cap label var DE077M "Schweinfurt"
cap label var DE079M "Wetzlar"
cap label var DE083M "Braunschweig-Salzgitter-Wolfsburg"
cap label var DE084M "Mannheim-Ludwigshafen"
cap label var DE084M_10 "Mannheim-Ludwigshafen (NUTS 2010)"
cap label var DE502M "Mannheim"
cap label var DE504M "Münster"
cap label var DE505M "Chemnitz"
cap label var DE506M "Braunschweig"
cap label var DE507M "Aachen"
cap label var DE510M "Lübeck"
cap label var DE512M "Rostock"
cap label var DE513M "Kassel"
cap label var DE517M "Osnabrück"
cap label var DE520M "Oldenburg (Oldenburg)"
cap label var DE522M "Heidelberg"
cap label var DE522M_10 "Heidelberg (NUTS 2010)"
cap label var DE523M "Paderborn"
cap label var DE524M "Würzburg"
cap label var DE526M "Wolfsburg"
cap label var DE527M "Bremerhaven"
cap label var DE529M "Heilbronn"
cap label var DE532M "Ulm"
cap label var DE533M "Pforzheim"
cap label var DE534M "Ingolstadt"
cap label var DE537M "Reutlingen"
cap label var DE539M "Cottbus"
cap label var DE540M "Siegen"
cap label var DE542M "Hildesheim"
cap label var DE544M "Zwickau"
cap label var DE546M "Wuppertal"
cap label var DE548M "Düren"
cap label var DE549M "Bocholt"
cap label var DE_NM "Non-metropolitan regions in Germany"
cap label var EE "Estonia"
cap label var EE001MC "Tallinn"
cap label var EE_NM "Non-metropolitan regions in Estonia"
cap label var IE "Ireland"
cap label var IE001MC "Dublin"
cap label var IE002M "Cork"
cap label var IE_NM "Non-metropolitan regions in Ireland"
cap label var EL "Greece"
cap label var EL001MC "Athina"
cap label var EL002M "Thessaloniki"
cap label var EL_NM "Non-metropolitan regions in Greece"
cap label var ES "Spain"
cap label var ES001MC "Madrid"
cap label var ES002M "Barcelona"
cap label var ES003M "Valencia"
cap label var ES004M "Sevilla"
cap label var ES005M "Zaragoza"
cap label var ES006M "Málaga - Marbella"
cap label var ES007M "Murcia - Cartagena"
cap label var ES008M "Las Palmas"
cap label var ES009M "Valladolid"
cap label var ES010M "Palma de Mallorca"
cap label var ES012M "Vitoria/Gasteiz"
cap label var ES013M "Oviedo - Gijón"
cap label var ES014M "Pamplona/Iruña"
cap label var ES015M "Santander"
cap label var ES019M "Bilbao"
cap label var ES020M "Córdoba"
cap label var ES021M "Alicante/Alacant - Elche/Elx"
cap label var ES022M "Vigo"
cap label var ES025M "Santa Cruz de Tenerife"
cap label var ES026M "A Coruña"
cap label var ES501M "Granada"
cap label var ES502M "Coruña (A)"
cap label var ES510M "Guipúzcoa"
cap label var ES522M "Cádiz"
cap label var ES_NM "Non-metropolitan regions in Spain"
cap label var FR "France"
cap label var FR001MC "Paris"
cap label var FR003M "Lyon"
cap label var FR004M "Toulouse"
cap label var FR006M "Strasbourg"
cap label var FR007M "Bordeaux"
cap label var FR008M "Nantes"
cap label var FR009M "Lille - Dunkerque - Valenciennes"
cap label var FR010M "Montpellier"
cap label var FR011M "Saint-Etienne"
cap label var FR013M "Rennes"
cap label var FR014M "Amiens"
cap label var FR015M "Rouen"
cap label var FR016M "Nancy"
cap label var FR017M "Metz"
cap label var FR018M "Reims"
cap label var FR019M "Orléans"
cap label var FR020M "Dijon"
cap label var FR021M "Poitiers"
cap label var FR022M "Clermont-Ferrand"
cap label var FR023M "Caen"
cap label var FR024M "Limoges"
cap label var FR025M "Besançon"
cap label var FR026M "Grenoble"
cap label var FR030M "Fort-de-France"
cap label var FR032M "Toulon"
cap label var FR035M "Tours"
cap label var FR036M "Angers"
cap label var FR037M "Brest"
cap label var FR038M "Le Mans"
cap label var FR039M "Avignon"
cap label var FR040M "Mulhouse"
cap label var FR043M "Perpignan"
cap label var FR044M "Nimes"
cap label var FR045M "Pau"
cap label var FR048M "Annecy (FR) / Genève (CH)"
cap label var FR203M "Marseille"
cap label var FR203M_10 "Marseille (NUTS 2010)"
cap label var FR205M "Nice"
cap label var FR207M "Lens - Liévin"
cap label var FR520M "Les Abymes"
cap label var FR_NM "Non-metropolitan regions in France"
cap label var HR "Croatia"
cap label var HR001MC "Zagreb"
cap label var HR001MC_10 "Zagreb (NUTS 2010)"
cap label var HR005M "Split"
cap label var HR_NM "Non-metropolitan regions in Croatia"
cap label var IT "Italy"
cap label var IT001MC "Roma"
cap label var IT002M "Milano"
cap label var IT003M "Napoli"
cap label var IT004M "Torino"
cap label var IT005M "Palermo"
cap label var IT006M "Genova"
cap label var IT007M "Firenze"
cap label var IT008M "Bari"
cap label var IT009M "Bologna"
cap label var IT010M "Catania"
cap label var IT011M "Venezia"
cap label var IT012M "Verona"
cap label var IT016M "Perugia"
cap label var IT019M "Pescara"
cap label var IT021M "Caserta"
cap label var IT022M "Taranto"
cap label var IT027M "Cagliari"
cap label var IT028M "Padova"
cap label var IT029M "Brescia"
cap label var IT030M "Modena"
cap label var IT032M "Salerno"
cap label var IT501M "Messina"
cap label var IT502M "Prato"
cap label var IT503M "Parma"
cap label var IT505M "Reggio nell Emilia"
cap label var IT511M "Bergamo"
cap label var IT513M "Latina"
cap label var IT514M "Vicenza"
cap label var IT_NM "Non-metropolitan regions in Italy"
cap label var CY "Cyprus"
cap label var CY001MC "Lefkosia"
cap label var CY_NM "Non-metropolitan regions in Cyprus"
cap label var LV "Latvia"
cap label var LV001MC "Riga"
cap label var LV_NM "Non-metropolitan regions in Latvia"
cap label var LT "Lithuania"
cap label var LT001MC "Vilnius"
cap label var LT002M "Kaunas"
cap label var LT_NM "Non-metropolitan regions in Lithuania"
cap label var LU "Luxembourg"
cap label var LU001MC "Luxembourg"
cap label var LU_NM "Non-metropolitan regions in Luxembourg"
cap label var HU "Hungary"
cap label var HU001MC "Budapest"
cap label var HU002M "Miskolc"
cap label var HU004M "Pécs"
cap label var HU005M "Debrecen"
cap label var HU009M "Székesfehérvár"
cap label var HU_NM "Non-metropolitan regions in Hungary"
cap label var MT "Malta"
cap label var MT001MC "Valletta"
cap label var MT_NM "Non-metropolitan regions in Malta"
cap label var NL "Netherlands"
cap label var NL001M "s' Gravenhage"
cap label var NL002MC "Amsterdam"
cap label var NL002MC_10 "Amsterdam (NUTS 2010)"
cap label var NL003M "Rotterdam"
cap label var NL004M "Utrecht"
cap label var NL005M "Eindhoven"
cap label var NL006M "Tilburg"
cap label var NL007M "Groningen"
cap label var NL007M_10 "Groningen (NUTS 2010)"
cap label var NL008M "Enschede"
cap label var NL009M "Arnhem - Nijmegen"
cap label var NL010M "Heerlen"
cap label var NL012M "Breda"
cap label var NL015M "Leeuwarden"
cap label var NL503M "s-Hertogenbosch"
cap label var NL507M "Leiden"
cap label var NL511M "Zwolle"
cap label var NL_NM "Non-metropolitan regions in Netherlands"
cap label var AT "Austria"
cap label var AT001MC "Wien"
cap label var AT002M "Graz"
cap label var AT003M "Linz"
cap label var AT004M "Salzburg"
cap label var AT005M "Innsbruck"
cap label var AT_NM "Non-metropolitan regions in Austria"
cap label var PL "Poland"
cap label var PL001MC "Warszawa"
cap label var PL002M "Lódz"
cap label var PL003M "Kraków"
cap label var PL004M "Wroclaw"
cap label var PL005M "Poznan"
cap label var PL006M "Gdansk"
cap label var PL007M "Szczecin"
cap label var PL008M "Bydgoszcz - Torún"
cap label var PL009M "Lublin"
cap label var PL010M "Katowice"
cap label var PL011M "Bialystok"
cap label var PL012M "Kielce"
cap label var PL014M "Olsztyn"
cap label var PL015M "Rzeszów"
cap label var PL016M "Opole"
cap label var PL024M "Czestochowa"
cap label var PL025M "Radom"
cap label var PL027M "Kalisz"
cap label var PL506M "Bielsko-Biala"
cap label var PL511M "Walbrzych"
cap label var PL513M "Wloclawek"
cap label var PL514M "Tarnów"
cap label var PL_NM "Non-metropolitan regions in Poland"
cap label var PT "Portugal"
cap label var PT001MC "Lisboa"
cap label var PT002M "Porto"
cap label var PT002M_10 "Porto (NUTS 2010)"
cap label var PT005M "Coimbra"
cap label var PT_NM "Non-metropolitan regions in Portugal"
cap label var RO "Romania"
cap label var RO001MC "Bucuresti"
cap label var RO001MC_10 "Bucuresti (NUTS 2010)"
cap label var RO002M "Cluj-Napoca"
cap label var RO003M "Timisoara"
cap label var RO004M "Craiova"
cap label var RO501M "Constanta"
cap label var RO502M "Iasi"
cap label var RO503M "Galati"
cap label var RO504M "Brasov"
cap label var RO505M "Ploiesti"
cap label var RO_NM "Non-metropolitan regions in Romania"
cap label var SI "Slovenia"
cap label var SI001MC "Ljubljana"
cap label var SI001MC_10 "Ljubljana (NUTS 2010)"
cap label var SI002M "Maribor"
cap label var SI_NM "Non-metropolitan regions in Slovenia"
cap label var SK "Slovakia"
cap label var SK001MC "Bratislava"
cap label var SK002M "Kosice"
cap label var SK_NM "Non-metropolitan regions in Slovakia"
cap label var FI "Finland"
cap label var FI001MC "Helsinki"
cap label var FI002M "Tampere"
cap label var FI002M_10 "Tampere (NUTS 2010)"
cap label var FI003M "Turku"
cap label var FI_NM "Non-metropolitan regions in Finland"
cap label var SE "Sweden"
cap label var SE001MC "Stockholm"
cap label var SE002M "Göteborg"
cap label var SE003M "Malmö"
cap label var SE006M "Uppsala"
cap label var SE_NM "Non-metropolitan regions in Sweden"
cap label var IS "Iceland"
cap label var IS_NM "Non-metropolitan regions in Iceland"
cap label var LI "Liechtenstein"
cap label var LI_NM "Non-metropolitan regions in Liechtenstein"
cap label var NO "Norway"
cap label var NO001MC "Oslo"
cap label var NO002M "Bergen"
cap label var NO003M "Trondheim"
cap label var NO004M "Stavanger"
cap label var NO_NM "Non-metropolitan regions in Norway"
cap label var CH "Switzerland"
cap label var CH001M "Zürich"
cap label var CH002M "Genève"
cap label var CH003M "Basel"
cap label var CH004MC "Bern"
cap label var CH005M "Lausanne"
cap label var CH006M "St. Gallen"
cap label var CH007M "Lucerne"
cap label var CH_NM "Non-metropolitan regions in Switzerland"
cap label var UK "United Kingdom"
cap label var UK001MC "London"
cap label var UK001MC_10 "London (NUTS 2010)"
cap label var UK002M "West Midlands urban area"
cap label var UK003M "Leeds"
cap label var UK004M "Glasgow"
cap label var UK005M "Bradford"
cap label var UK006M "Liverpool"
cap label var UK007M "Edinburgh"
cap label var UK008M "Manchester"
cap label var UK008M_10 "Manchester (NUTS 2010)"
cap label var UK009M "Cardiff"
cap label var UK010M "Sheffield"
cap label var UK011M "Bristol"
cap label var UK012M "Belfast"
cap label var UK013M "Newcastle upon Tyne"
cap label var UK014M "Leicester"
cap label var UK016M "Aberdeen"
cap label var UK017M "Cambridge"
cap label var UK018M "Exeter"
cap label var UK019M "Lincoln"
cap label var UK022M "Wrexham"
cap label var UK023M "Portsmouth"
cap label var UK023M_10 "Portsmouth (NUTS 2010)"
cap label var UK024M "Worcester"
cap label var UK025M "Coventry"
cap label var UK026M "Kingston upon Hull"
cap label var UK027M "Stoke-on-Trent"
cap label var UK029M "Nottingham"
cap label var UK201M "Bradford-Leeds"
cap label var UK501M "Kirklees"
cap label var UK506M "Doncaster"
cap label var UK510M "Sunderland"
cap label var UK513M "Medway"
cap label var UK515M "Brighton and Hove"
cap label var UK516M "Plymouth"
cap label var UK517M "Swansea"
cap label var UK518M "Derby"
cap label var UK520M "Southampton"
cap label var UK528M "Northampton"
cap label var UK532M "Luton"
cap label var UK535M "Swindon"
cap label var UK536M "Stockton-on-Tees"
cap label var UK539M "Bournemouth"
cap label var UK546M "Colchester"
cap label var UK550M "Dundee"
cap label var UK552M "Reading"
cap label var UK553M "Blackburn - Blackpool - Preston"
cap label var UK553M_10 "Blackburn - Blackpool - Preston (NUTS 2010)"
cap label var UK559M "Middlesbrough"
cap label var UK560M "Oxford"
cap label var UK561M "Milton Keynes"
cap label var UK566M "Norwich"
cap label var UK566M_10 "Norwich (NUTS 2010)"
cap label var UK568M "Cheshire West and Chester"
cap label var UK569M "Ipswich"
cap label var UK_NM "Non-metropolitan regions in United Kingdom"
cap label var ME "Montenegro"
cap label var ME_NM "Non-metropolitan regions in Montenegro"
cap label var MK "North Macedonia"
cap label var MK_NM "Non-metropolitan regions in North Macedonia"
cap label var AL "Albania"
cap label var AL_NM "Non-metropolitan regions in Albania"
cap label var RS "Serbia"
cap label var RS_NM "Non-metropolitan regions in Serbia"
cap label var TR "Turkey"
cap label var TR_NM "Non-metropolitan regions in Turkey"
