cap label var ACTAES_MISS "Missing information for given variable"
cap label var ACTAES_NO "No, significant changes in aesthetic appearance"
cap label var ACTAES_YES "Significant changes in aesthetic appearance"
cap label var ACTMAN_MISS "Missing information for given variable"
cap label var ACTMAN_NO "No, undertake implementation of advanced management techniques"
cap label var ACTMAN_YES "Undertake implementation of advanced management techniques"
cap label var ACTMAR_MISS "Missing information for given variable"
cap label var ACTMAR_NO "No, undertake changing enterprise's marketing concepts/strategies"
cap label var ACTMAR_YES "Undertake changing enterprise's marketing concepts/strategies"
cap label var ACTORG_MISS "Missing information for given variable"
cap label var ACTORG_NO "No, undertake implementation of changed organisational structures"
cap label var ACTORG_YES "Undertake implementation of changed organisational structures"
cap label var ACTSTR_MISS "Missing information for given variable"
cap label var ACTSTR_NO "No, undertake implementation of new corporate strategies"
cap label var ACTSTR_YES "Undertake implementation of new corporate strategies"
cap label var C01 "Enterprises co-operating with other enterprises within the enterprise group"
cap label var C01_VAL "Enterprises for which cooperation with other enterprises within the enterprise group is the most valuable method"
cap label var C02 "Enterprises co-operating with competitors or other enterprises of the same sector"
cap label var C02_VAL "Enterprises for which cooperation with competitors or other enterprises of the same sector is the most valuable method"
cap label var C03 "Enterprises co-operating with clients or customers"
cap label var C03_VAL "Enterprises for which cooperation with clients or customers is the most valuable method"
cap label var C031 "Enterprises co-operating with clients or customers from the private sector"
cap label var C031_VAL "Enterprises for which cooperation with clients or customers from the private sector"
cap label var C032 "Enterprises co-operating with clients or customers from the public sector"
cap label var C032_VAL "Enterprises for which cooperation with clients or customers from the public sector is the most valuable method"
cap label var C05 "Enterprises co-operating with suppliers of equipment, materials, components or software"
cap label var C05_VAL "Enterprises for which cooperation with suppliers of equipment, materials, components or software is the most valuable method"
cap label var C06 "Enterprises co-operating with universities or other higher education institutions"
cap label var C06_VAL "Enterprises for which cooperation with universities or other higher education institutions is the most valuable method"
cap label var C07 "Enterprises co-operating with Government or public research institutes"
cap label var C07_VAL "Enterprises for which cooperation with Government or public research institutes is the most valuable method"
cap label var C08 "Enterprises co-operating with consultants, commercial labs, or private R&D institutes"
cap label var C08_VAL "Enterprises for which cooperation with consultants, commercial labs, or private R&D institutes is the most valuable method"
cap label var C09 "Enterprises co-operating with Government, public or private research institutes"
cap label var C09_VAL "Enterprises for which cooperation with Government, public or private research institutes is the most valuable method"
cap label var C10 "Enterprises co-operating with consultants or commercial labs"
cap label var C10_VAL "Enterprises for which cooperation with consultants or commercial labs is the most valuable method"
cap label var CMCO_HIGH "Enterprises considering copyright highly effective"
cap label var CMCO_NU "Enterprises that don't use copyright as a method"
cap label var CMCPX_HIGH "Enterprises considering the complexity of goods / services highly effective"
cap label var CMCPX_NU "Enterprises that don't use the complexity of goods / services as a method"
cap label var CMCTM_HIGH "Enterprises considering trademarks highly effective"
cap label var CMCTM_NU "Enterprises that don't use trademarks as a method"
cap label var CMLTAD_HIGH "Enterprises considering lead time advantages highly effective"
cap label var CMLTAD_NU "Enterprises that don't use lead time advantages as a method"
cap label var CMPAT_HIGH "Enterprises considering patents highly effective"
cap label var CMPAT_NU "Enterprises that don't use patents as a method"
cap label var CMRCD_HIGH "Enterprises considering design registration highly effective"
cap label var CMRCD_NU "Enterprises that don't use design registration as a method"
cap label var CMSEC_HIGH "Enterprises considering the secrecy highly effective"
cap label var CMSEC_NU "Enterprises that don't use the secrecy as a method"
cap label var CMUPAT_HIGH "Enterprises considering utility patents highly effective"
cap label var CMUPAT_NU "Enterprises that don't use utility patents as a method"
cap label var CO "Innovating enterprises with cooperation"
cap label var CO_ALL "Enterprises engaged in any type of co-operation"
cap label var CO_MISS "Missing information for given variable"
cap label var CO_NO "No cooperation arrangements on innovation activities"
cap label var CO_YES "Cooperation arrangements on innovation activities"
cap label var CO1 "Other enterprises(s) within the group"
cap label var CO11_MISS "Missing information for given variable"
cap label var CO11_NO "No cooperation within national enterprise group"
cap label var CO11_YES "Cooperation within national enterprise group"
cap label var CO12_MISS "Missing information for given variable"
cap label var CO12_NO "No cooperation within EU/EFTA enterprise group"
cap label var CO12_YES "Cooperation within EU/EFTA enterprise group"
cap label var CO13_MISS "Missing information for given variable"
cap label var CO13_NO "No cooperation within EU/CC enterprise group"
cap label var CO13_YES "Cooperation within EU/CC enterprise group"
cap label var CO14_MISS "Missing information for given variable"
cap label var CO14_NO "No cooperation within US enterprise group"
cap label var CO14_YES "Cooperation within US enterprise group"
cap label var CO15_MISS "Missing information for given variable"
cap label var CO15_NO "No cooperation within Japan enterprise group"
cap label var CO15_YES "Cooperation within Japan enterprise group"
cap label var CO16_MISS "Missing information for given variable"
cap label var CO16_NO "No cooperation within Japan enterprise group"
cap label var CO16_YES "Cooperation within Other enterprise group"
cap label var CO2 "Competitor(s)"
cap label var CO2_MISS "Missing information for given variable"
cap label var CO2_NO "No cooperation arrangements on innovation activities"
cap label var CO2_YES "Cooperation arrangements on innovation activities"
cap label var CO21_MISS "Missing information for given variable"
cap label var CO21_NO "No, cooperation with national suppliers of equipment etc."
cap label var CO21_YES "Cooperation with national suppliers of equipment etc."
cap label var CO22_MISS "Missing information for given variable"
cap label var CO22_NO "No, Cooperation with EU/EFTA suppliers of equipment etc."
cap label var CO22_YES "Cooperation with EU/EFTA suppliers of equipment etc."
cap label var CO23_MISS "Missing information for given variable"
cap label var CO23_NO "No, Cooperation with EU/CC suppliers of equipment etc."
cap label var CO23_YES "Cooperation with EU/CC suppliers of equipment etc."
cap label var CO24_MISS "Missing information for given variable"
cap label var CO24_NO "No, Cooperation with US suppliers of equipment etc."
cap label var CO24_YES "Cooperation with US suppliers of equipment etc."
cap label var CO25_MISS "Missing information for given variable"
cap label var CO25_NO "No, Cooperation with Japan suppliers of equipment etc."
cap label var CO25_YES "Cooperation with Japan suppliers of equipment etc."
cap label var CO26_MISS "Missing information for given variable"
cap label var CO26_NO "No, Cooperation with Other suppliers of equipment etc."
cap label var CO26_YES "Cooperation with Other suppliers of equipment etc."
cap label var CO3 "Clients or customers"
cap label var CO31_MISS "Missing information for given variable"
cap label var CO31_NO "No, Cooperation with national clients or customers"
cap label var CO31_YES "Cooperation with National clients or customers"
cap label var CO32_MISS "Missing information for given variable"
cap label var CO32_NO "No, Cooperation with EU/EFTA clients or customers"
cap label var CO32_YES "Cooperation with EU/EFTA clients or customers"
cap label var CO33_MISS "Missing information for given variable"
cap label var CO33_NO "No, Cooperation with EU-CC clients or customers"
cap label var CO33_YES "Cooperation with EU-CC clients or customers"
cap label var CO34_MISS "Missing information for given variable"
cap label var CO34_NO "No, Cooperation with US clients or customers"
cap label var CO34_YES "Cooperation with US clients or customers"
cap label var CO35_MISS "Missing information for given variable"
cap label var CO35_NO "No, Cooperation with Japan clients or customers"
cap label var CO35_YES "Cooperation with Japan clients or customers"
cap label var CO36_MISS "Missing information for given variable"
cap label var CO36_NO "No, Cooperation with Other clients or customers"
cap label var CO36_YES "Cooperation with Other clients or customers"
cap label var CO4 "Consultancy enterprises"
cap label var CO41_MISS "Missing information for given variable"
cap label var CO41_NO "No, Cooperation with national competitors or other firms"
cap label var CO41_YES "Cooperation with National competitors or other firms"
cap label var CO42_MISS "Missing information for given variable"
cap label var CO42_NO "No, Cooperation with EU/EFTA competitors or other firms"
cap label var CO42_YES "Share of cooperation with EU/EFTA competitors or other firms"
cap label var CO43_MISS "Missing information for given variable"
cap label var CO43_NO "No, Cooperation with EU-CC competitors or other firms"
cap label var CO43_YES "Cooperation with EU-CC competitors or other firms"
cap label var CO44_MISS "Missing information for given variable"
cap label var CO44_NO "No, Cooperation with US competitors or other firms"
cap label var CO44_YES "Cooperation with US competitors or other firms"
cap label var CO45_MISS "Missing information for given variable"
cap label var CO45_NO "No, Cooperation with Japan competitors or other firms"
cap label var CO45_YES "Cooperation with Japan competitors or other firms"
cap label var CO46_MISS "Missing information for given variable"
cap label var CO46_NO "No, Cooperation with Other competitors or other firms"
cap label var CO46_YES "Cooperation with Other competitors or other firms"
cap label var CO5 "Suppliers of equipment, materials, components of software"
cap label var CO51_MISS "Missing information for given variable"
cap label var CO51_NO "No, Cooperation with national consultants"
cap label var CO51_YES "Cooperation with National consultants"
cap label var CO52_MISS "Missing information for given variable"
cap label var CO52_NO "No, Cooperation with EU/EFTA, consultants"
cap label var CO52_YES "Cooperation with EU/EFTA, consultants"
cap label var CO53_MISS "Missing information for given variable"
cap label var CO53_NO "No, Cooperation with EU-CC, consultants"
cap label var CO53_YES "Cooperation with EU-CC, consultants"
cap label var CO54_MISS "Missing information for given variable"
cap label var CO54_NO "No, Cooperation with US consultants"
cap label var CO54_YES "Cooperation with US, consultants"
cap label var CO55_MISS "Missing information for given variable"
cap label var CO55_NO "No, Cooperation with Japan consultants"
cap label var CO55_YES "Cooperation with Japan, consultants"
cap label var CO56_MISS "Missing information for given variable"
cap label var CO56_NO "No, Cooperation with Other consultants"
cap label var CO56_YES "Cooperation with Other, consultants"
cap label var CO6 "Universities or other higher education institutes"
cap label var CO61_MISS "Missing information for given variable"
cap label var CO61_NO "No, Cooperation with Commercial laboratories /R&D enter. : No national"
cap label var CO61_YES "Cooperation with Commercial laboratories /R&D enter. : National"
cap label var CO62_MISS "Missing information for given variable"
cap label var CO62_NO "No, Cooperation with Commercial laboratories /R&D enter. : No EU/EFTA"
cap label var CO62_YES "Cooperation with Commercial laboratories /R&D enter. : EU/EFTA"
cap label var CO63_MISS "Missing information for given variable"
cap label var CO63_NO "No, Cooperation with Commercial laboratories /R&D enter. : No EU-CC"
cap label var CO63_YES "Cooperation with Commercial laboratories /R&D enter. : EU-CC"
cap label var CO64_MISS "Missing information for given variable"
cap label var CO64_NO "No, Cooperation with Commercial laboratories /R&D enter. : No US"
cap label var CO64_YES "Cooperation with Commercial laboratories /R&D enter. : US"
cap label var CO65_MISS "Missing information for given variable"
cap label var CO65_NO "No, Cooperation with Commercial laboratories /R&D enter. : No Japan"
cap label var CO65_YES "Cooperation with Commercial laboratories /R&D enter. : Japan"
cap label var CO66_MISS "Missing information for given variable"
cap label var CO66_NO "No, Cooperation with Commercial laboratories /R&D enter. : No Other"
cap label var CO66_YES "Cooperation with Commercial laboratories /R&D enter. : Other"
cap label var CO7 "Government or private non-profit research institutes"
cap label var CO71_MISS "Missing information for given variable"
cap label var CO71_NO "No, Cooperation with Universities or other ... : No national"
cap label var CO71_YES "Cooperation with Universities or other ... : National"
cap label var CO72_MISS "Missing information for given variable"
cap label var CO72_NO "No, Cooperation with Universities or other ... : no EU/EFTA"
cap label var CO72_YES "Cooperation with Universities or other ... : EU/EFTA"
cap label var CO73_MISS "Missing information for given variable"
cap label var CO73_NO "No, Cooperation with Universities or other ... : no EU-CC"
cap label var CO73_YES "Cooperation with Universities or other ... : EU-CC"
cap label var CO74_MISS "Missing information for given variable"
cap label var CO74_NO "No, Cooperation with Universities or other ... : no US"
cap label var CO74_YES "Cooperation with Universities or other ... : US"
cap label var CO75_MISS "Missing information for given variable"
cap label var CO75_NO "No, Cooperation with Universities or other ... : no Japan"
cap label var CO75_YES "Cooperation with Universities or other ... : Japan"
cap label var CO76_MISS "Missing information for given variable"
cap label var CO76_NO "No, Cooperation with Universities or other ... : No other"
cap label var CO76_YES "Cooperation with Universities or other ... : Other"
cap label var CO81_MISS "Missing information for given variable"
cap label var CO81_NO "No, Cooperation with Government or PNP research inst. : No national"
cap label var CO81_YES "Cooperation with Government or PNP research inst. : National"
cap label var CO82_MISS "Missing information for given variable"
cap label var CO82_NO "No, Cooperation with Government or PNP research inst. : No EU/EFTA"
cap label var CO82_YES "Cooperation with Government or PNP research inst. : EU/EFTA"
cap label var CO83_MISS "Missing information for given variable"
cap label var CO83_NO "No, Cooperation with Government or PNP research inst. : No EU-CC"
cap label var CO83_YES "Cooperation with Government or PNP research inst. : EU-CC"
cap label var CO84_MISS "Missing information for given variable"
cap label var CO84_NO "No, Cooperation with Government or PNP research inst. : No US"
cap label var CO84_YES "Cooperation with Government or PNP research inst. : US"
cap label var CO85_MISS "Missing information for given variable"
cap label var CO85_NO "No, Cooperation with Government or PNP research inst. : No Japan"
cap label var CO85_YES "Cooperation with Government or PNP research inst. : Japan"
cap label var CO86_MISS "Missing information for given variable"
cap label var CO86_NO "No, Cooperation with Government or PNP research inst. : No other"
cap label var CO86_YES "Cooperation with Government or PNP research inst. : Other"
cap label var COALL_INNO "Product and/or process (PP) innovative enterprises engaged in any type of cooperation as a % of PP innovative enterprises"
cap label var COCNIN_YES "Enterprises engaged in any type of innovation co-operation with a partner in China or India"
cap label var COEU "Partner inside the EU"
cap label var COEUC_MISS "Missing information for any type of innovation co-operation, within EU and the Candidate Countries"
cap label var COEUC_NO "Enterprise not engaged in any type of innovation co-operation, within EU and the Candidate Countries"
cap label var COEUC_YES "Enterprise engaged in any type of innovation co-operation, within EU and the Candidate Countries"
cap label var COEUE_MISS "Missing information for any type of innovation co-operation, within EU and EFTA"
cap label var COEUE_NO "Enterprise not engaged in any type of innovation co-operation, within EU and EFTA"
cap label var COEUE_YES "Enterprise engaged in any type of innovation co-operation, within EU and EFTA"
cap label var COEUR_YES "Enterprises engaged in any type of innovation co-operation with a partner in EU countries, EFTA or EU candidates countries (except a national partner)"
cap label var COJAP "Partner in Japan"
cap label var COJP_MISS "Missing information for any type of innovation co-operation, with Japan"
cap label var COJP_NO "Enterprise not engaged in any type of innovation co-operation, with Japan"
cap label var COJP_YES "Enterprise engaged in any type of innovation co-operation, with Japan"
cap label var CONA "National partner"
cap label var CONAT_MISS "Missing information for any type of innovation co-operation, National"
cap label var CONAT_NO "Enterprise not engaged in any type of innovation co-operation, National"
cap label var CONAT_YES "Enterprises engaged in any type of innovation co-operation with a national partner"
cap label var CONATEUR_YES "Enterprises engaged in any type of innovation co-operation with a partner in EU countries, EFTA or EU candidates countries (incl. national partner)"
cap label var COOT_MISS "Missing information for any type of innovation co-operation, with other partner countries"
cap label var COOT_NO "Enterprise not engaged in any type of innovation co-operation, with other partner countries"
cap label var COOT_YES "Enterprises engaged in any type of innovation co-operation with a partner in all other countries except in EU countries, EFTA or EU candidates countries, United States, China or India"
cap label var COOTH "Partner in other countries"
cap label var COUS_MISS "Missing information for any type of innovation co-operation, with the US"
cap label var COUS_NO "Enterprise not engaged in any type of innovation co-operation, with the US"
cap label var COUS_YES "Enterprises engaged in any type of innovation co-operation with a partner in United States"
cap label var COUSA "Partner in the US"
cap label var COUSOT_YES "Enterprise engaged in any type of innovation co-operation, within United States and other countries"
cap label var ECAP "Increased capacity of production or service provision"
cap label var ECAP_HIGH "High, Increased production capacity"
cap label var ECAP_LOW "Low, Increased production capacity"
cap label var ECAP_MED "Medium, Increased production capacity"
cap label var ECAP_MISS "Missing information for given variable"
cap label var ECAP_NO "No, Increased production capacity"
cap label var ECOCO "Reduced CO2 'footprint' (total CO2 production) by your enterprise"
cap label var ECOEN "Reduced energy use per unit of output"
cap label var ECOENU "Enterprises that reduced energy use or CO2 'footprint' during the consumption or use of a good or service by the end user, by innovating"
cap label var ECOMAT "Enterprises that reduced material or water use per unit of output within the enterprises by innovating"
cap label var ECOPOL "Enterprises that reduced air, water, noise or soil pollution within the enterprises by innovating"
cap label var ECOPOS "Enterprises that reduced air, water, noise or soil pollution during the consumption or use of a good or service by the end user, by innovating"
cap label var ECOREA "Enterprises that facilitated recycling of product after use by the end user, by innovating"
cap label var ECOREC "Enterprises that recycled waste, water, or materials for own use or sale within the enterprises by innovating"
cap label var ECOSUB "Enterprises that replaced a share of materials with less polluting or hazardous substitutes within the enterprises by innovating"
cap label var EENV "Reduced environmental impacts or improved health and safety"
cap label var EENV_HIGH "High, Improved environmental impact or health and safety aspects"
cap label var EENV_LOW "Low, Improved environmental impact or health and safety aspects"
cap label var EENV_MED "Medium, Improved environmental impact or health and safety aspects"
cap label var EENV_MISS "Missing information for given variable"
cap label var EENV_NO "No, Improved environmental impact or health and safety aspects"
cap label var EFLEX "Improved flexibility of production or service provision"
cap label var EFLEX_HIGH "High, Improved production flexibility"
cap label var EFLEX_LOW "Low, Improved production flexibility"
cap label var EFLEX_MED "Medium, Improved production flexibility"
cap label var EFLEX_MISS "Missing information for given variable"
cap label var EFLEX_NO "No, Improved production flexibility"
cap label var EFORED_HIGH "Reduced time to respond to customer or supplier needs"
cap label var ELBR "Reduced labour costs per unit output"
cap label var ELBR_HIGH "High, Reduced labour costs per produced unit"
cap label var ELBR_LOW "Low, Reduced labour costs per produced unit"
cap label var ELBR_MED "Medium, Reduced labour costs per produced unit"
cap label var ELBR_MISS "Missing information for given variable"
cap label var ELBR_NO "No, Reduced labour costs per produced unit"
cap label var EMAR "Entered new markets or increased market share"
cap label var EMAR_HIGH "High Increased market or market share"
cap label var EMAR_LOW "Low Increased market or market share"
cap label var EMAR_MED "Medium Increased market or market share"
cap label var EMAR_MISS "Missing information for given variable"
cap label var EMAR_NO "No Increased market or market share"
cap label var EMAT "Reduced materials and energy per unit output"
cap label var EMAT_HIGH "High, Reduced materials and energy per produced unit"
cap label var EMAT_LOW "Low, Reduced materials and energy per produced unit"
cap label var EMAT_MED "Medium, Reduced materials and energy per produced unit"
cap label var EMAT_MISS "Missing information for given variable"
cap label var EMAT_NO "No, Reduced materials and energy per produced unit"
cap label var EMP "Number of Employees for 2000"
cap label var EMP02 "Total number of employees in 2002"
cap label var EMP04 "Total number of employees in 2004"
cap label var EMP06 "Total number of employees in 2006"
cap label var EMP08 "Total number of employees in 2008"
cap label var EMP10 "Total number of employees in 2010"
cap label var EMP12 "Total number of employees in 2012"
cap label var EMP98 "Number of Employees for 1998"
cap label var EMPHI "Number of Employees with higher education in 2000"
cap label var EMPUD0 "Enterprises with 0 % of employees with university education"
cap label var EMPUD1 "Enterprises with 1 % to 4 % of employees with university education"
cap label var EMPUD2 "Enterprises with 5 % to 9 % of employees with university education"
cap label var EMPUD3 "Enterprises with 10 % to 24 % of employees with university education"
cap label var EMPUD4 "Enterprises with 25 % to 49 % of employees with university education"
cap label var EMPUD5 "Enterprises with 50 % to 74 % of employees with university education"
cap label var EMPUD6 "Enterprises with more than 75 % of employees with university education"
cap label var ENAGR "Voluntary codes or agreements for environmental good practice within your sector"
cap label var ENDEM "Current or expected market demand from your customers for environmental innovations"
cap label var ENGRA "Availability of government grants, subsidies or other financial incentives for environmental innovation"
cap label var ENMRG_YES "Enterprises that have merged with/take over another enterprise"
cap label var ENNWEUR_YES "Enterprises that have established new subsidiaries in the national country and/or European country"
cap label var ENNWOTH_YES "Enterprises that have established new subsidiaries outside Europe"
cap label var ENOUT_YES "Enterprises that have sold/closed/outsourced tasks or functions"
cap label var ENREG "Existing environmental regulations or taxes on pollution"
cap label var ENREGF "Environmental regulations or taxes that you expected to be introduced in the future"
cap label var ENT_POP "Total survey population"
cap label var ENT_POPU "Number of enterprises in current strata (realised sample)"
cap label var ENT_POPU04 "Total number of enterprises in the population in 2004"
cap label var ENT_POPU06 "Total number of enterprises in the population in 2006"
cap label var ENT_POPU08 "Total number of enterprises in the population in 2008"
cap label var ENT_POPU10 "Total number of enterprises in the population in 2010"
cap label var ENT_POPU12 "Total number of enterprises in the population in 2012"
cap label var ENT_POPU2 "Number of enterprises in current strata (realised sample) not rounded"
cap label var ENT_SAMP "Realised sample"
cap label var ENVID1 "Implemented only before January 2006"
cap label var ENVID2 "Implemented or significantly improved only after January 2006"
cap label var ENVID3 "Implemented (both before January 2006 and after January 2006)"
cap label var EOQUA_HIGH "Improved quality of goods or services"
cap label var EORED_HIGH "Reduced costs per unit output"
cap label var EOSAT_HIGH "Improved employee satisfaction and/or reduced rates of employee turnover"
cap label var EQUA "Improved quality in goods or services"
cap label var EQUA_HIGH "High, improved quality in goods or services, in percent"
cap label var EQUA_LOW "Low, improved quality in goods or services, in percent"
cap label var EQUA_MED "Medium, improved quality in goods or services, in percent"
cap label var EQUA_MISS "Missing information for given variable"
cap label var EQUA_NO "No, improved quality in goods or services, in percent"
cap label var ERANGE "Increased range of goods and services"
cap label var ERANGE_HIGH "High increased range of goods or services"
cap label var ERANGE_LOW "Low increased range of goods or services"
cap label var ERANGE_MED "Medium increased range of goods or services"
cap label var ERANGE_MISS "Missing information for given variable"
cap label var ERANGE_NO "No increased range of goods or services"
cap label var EREG "Met regulation requirements"
cap label var ES_SDOS "Design of objects or services skills obtained from external sources-only"
cap label var ES_SENAP "Engineering / applied sciences skills obtained from external sources-only"
cap label var ES_SGALA "Graphic arts / layout / advertising skills obtained from external sources-only"
cap label var ES_SMED "Multimedia skills obtained from external sources-only"
cap label var ES_SMKR "Market research skills obtained from external sources-only"
cap label var ES_SMSDM "Mathematics / statistics / database management skills obtained from external sources-only"
cap label var ES_SSWD "Software development skills obtained from external sources-only"
cap label var ES_SWDS "Web design skills obtained from external sources-only"
cap label var EST_MISS "Missing information for given variable"
cap label var EST_NO "Number of enterprise that were not established between 1998-2000"
cap label var EST_YES "Number of enterprise that were established between 1998-2000"
cap label var ESTD_HIGH "High, Met regulations or standards"
cap label var ESTD_LOW "Low, Met regulations or standards"
cap label var ESTD_MED "Medium, Met regulations or standards"
cap label var ESTD_MISS "Missing information for given variable"
cap label var ESTD_NO "No, Met regulations or standards"
cap label var EX_HIGH1 "Innovating enterprises with high export intensity"
cap label var EX_HIGH2 "Enterprises with high export intensity"
cap label var EX_LOW1 "Innovating enterprises with low export intensity"
cap label var EX_LOW2 "Enterprises with low export intensity"
cap label var EX_MED1 "Innovating enterprises with medium export intensity"
cap label var EX_MED2 "Enterprises with medium export intensity"
cap label var EX_NULL1 "Innovating enterprises with no exports"
cap label var EX_NULL2 "Enterprises with no exports"
cap label var EXP "Total Export in 2000"
cap label var EXP98 "Total Export in 1998"
cap label var FAC1 "Excessive economic risk"
cap label var FAC2 "Too high innovation costs"
cap label var FAC3 "Lack of appropriate sources of finance"
cap label var FAC4 "Organisational rigidities"
cap label var FAC5 "Lack of qualified personnel"
cap label var FAC6 "Lack of information on technology"
cap label var FAC7 "Lack of information on markets"
cap label var FAC8 "Problems of regulations fulfilling"
cap label var FAC9 "Lack of customer responsiveness to new products"
cap label var FPUB_INNO "Product and/or process (PP) innovative enterprises that receive public funding as a % of PP innovative enterprises"
cap label var FUNEU "Enterprises that received funding from the European Union"
cap label var FUNEU_MISS "Missing information for given variable"
cap label var FUNEU_NO "No, Public funding from the EU"
cap label var FUNEU_YES "Yes, enterprise received public funding from the EU"
cap label var FUNGMT "Enterprises that received funding from central government (including central government agencies or ministries)"
cap label var FUNGMT_MISS "Missing information for given variable"
cap label var FUNGMT_NO "No, public funding from central government"
cap label var FUNGMT_YES "Yes, enterprise received public funding from central government"
cap label var FUNLOC "Enterprises that received funding from local or regional authorities"
cap label var FUNLOC_MISS "Missing information for given variable"
cap label var FUNLOC_NO "No, Public funding from local or regional authorities"
cap label var FUNLOC_YES "Yes, enterprise received funding from local or regional authorities"
cap label var FUNPUB "Enterprises that received any public funding"
cap label var FUNPUB_MISS "Missing information for given variable"
cap label var FUNPUB_NO "No, Public funding"
cap label var FUNPUB_YES "Yes, enterprise received public funding"
cap label var FUNRTD_MISS "Missing information for given variable"
cap label var FUNRTD_NO "No, funding from EU's 4th or 5th RTD"
cap label var FUNRTD_YES "Yes enterprise received funding from EU's 4th or 5th RTD"
cap label var FUNRTD56 "Enterprise that received funding from the 5th or 6th Framework Programme"
cap label var FUNRTD6 "Enterprise that received funding from the 6th Framework Programme"
cap label var FUNRTD6_7 "Enterprise that received funding from the 6th or 7th Framework Programme"
cap label var FUNRTD7 "Enterprises that received funding from the 7th Framework Programme"
cap label var FWTURN1 "Enterprises for which the percent of the total turnover in 2012 from world first product innovation is >0% and <1%"
cap label var FWTURN2 "Enterprises for which the percent of the total turnover in 2012 from world first product innovation is ?1% and <5%"
cap label var FWTURN3 "Enterprises for which the percent of the total turnover in 2012 from world first product innovation is ?5% and <10%"
cap label var FWTURN4 "Enterprises for which the percent of the total turnover in 2012 from world first product innovation is ?10% and <25%"
cap label var FWTURN5 "Enterprises for which the percent of the total turnover in 2012 from world first product innovation is ?25%"
cap label var FWTURN6 "Enterprises that don't know which percent of the total turnover in 2012 is from world first product innovation"
cap label var GMTSUP "Supported by government"
cap label var GOCOS_HIGH "Enterprises considering a decrease in costs highly important"
cap label var GOCOS_NR "Enterprises considering a decrease in costs not relevant"
cap label var GOMKT_HIGH "Enterprises considering an increase in market share highly important"
cap label var GOMKT_NR "Enterprises considering an increase in market share not relevant"
cap label var GOPRF_HIGH "Enterprises considering an increase in profit margins highly important"
cap label var GOPRF_NR "Enterprises considering an increase in profit margins not relevant"
cap label var GOTURN_HIGH "Enterprises considering an increase in turnover highly important"
cap label var GOTURN_NR "Enterprises considering an increase in turnover not relevant"
cap label var GP_MISS "Missing information for given variable"
cap label var GP_NO "Enterprise is not part of a group"
cap label var GP_YES "Enterprises that are part of an enterprise group"
cap label var H1 "Serious delays in innovation projects"
cap label var H2 "Abolishment of innovation projects"
cap label var H3 "Innovation project not even started"
cap label var HBEG_YES "Enterprise with innovation activity abandoned after it began"
cap label var HBUR_MISS "Missing information for given variable"
cap label var HBUR_NO "Enterprise with innovation activity not burdened/cumbered"
cap label var HBUR_YES "Enterprise with innovation activity burdened/cumbered"
cap label var HCON_YES "Enterprise with innovation activity abandoned at the concept stage"
cap label var HCOS_HIGH "No innovation activity due to factors impeding innovation, Hampering factor Innovation costs: High"
cap label var HCOS_LOW "No innovation activity due to factors impeding innovation, Hampering factor Innovation costs: Low"
cap label var HCOS_MED "No innovation activity due to factors impeding innovation, Hampering factor Innovation costs: Medium"
cap label var HCOS_MISS "Missing information for given variable"
cap label var HCOS_NO "No innovation activity not due to factors impeding innovation, Hampering factor Innovation costs"
cap label var HCUS_HIGH "No innovation activity due to factors impeding innovation, Hampering factor Customer responsiveness: High"
cap label var HCUS_LOW "No innovation activity due to factors impeding innovation, Hampering factor Customer responsiveness: Low"
cap label var HCUS_MED "No innovation activity due to factors impeding innovation, Hampering factor Customer responsiveness: Medium"
cap label var HCUS_MISS "Missing information for given variable"
cap label var HCUS_NO "No innovation activity not due to factors impeding innovation, Hampering factor Customer responsiveness"
cap label var HDLAY_MISS "Missing information for given variable"
cap label var HDLAY_NO "Enterprise with innovation activity not seriously delayed"
cap label var HDLAY_YES "Enterprise with innovation activity seriously delayed"
cap label var HECO_HIGH "No innovation activity due to factors impeding innovation, Hampering factor Economic risks: High"
cap label var HECO_LOW "No innovation activity due to factors impeding innovation, Hampering factor Economic risks: Low"
cap label var HECO_MED "No innovation activity due to factors impeding innovation, Hampering factor Economic risks: Medium"
cap label var HECO_MISS "Missing information for given variable"
cap label var HECO_NO "No innovation activity not due to factors impeding innovation, Hampering factor Economic risks"
cap label var HFCOS_HIGH "Enterprises for which the innovation costs too high is a highly important factor of hampering innovation activities"
cap label var HFDEM_HIGH "Enterprises for which uncertain demand for innovative goods or services is a highly important factor of hampering innovation activities"
cap label var HFDOM_HIGH "Enterprises for which markets dominated by established enterprises is a highly important factor of hampering innovation activities"
cap label var HFENT_HIGH "Enterprises for which the lack of internal finance was a highly important barrier to innovate"
cap label var HFENT_HIGH10 "Enterprises for which the lack of funds within the enterprise or group is a highly important factor of hampering innovation activities"
cap label var HFFUND_HIGH "Lack of funds within your enterprise or enterprise group, high important factor of hampering innovation activities"
cap label var HFIN_HIGH "No innovation activity due to factors impeding innovation, Hampering factor Sources of finance: High"
cap label var HFIN_LOW "No innovation activity due to factors impeding innovation, Hampering factor Sources of finance: Low"
cap label var HFIN_MED "No innovation activity due to factors impeding innovation, Hampering factor Sources of finance: Medium"
cap label var HFIN_MISS "Missing information for given variable"
cap label var HFIN_NO "No innovation activity not due to factors impeding innovation, Hampering factor Sources of finance"
cap label var HFINFO_HIGH "Enterprises for which the lack of information on markets is a highly important factor of hampering innovation activities"
cap label var HFIT_HIGH "Enterprises for which the lack of information on technology is a highly important factor of hampering innovation activities"
cap label var HFLEX_HIGH "No innovation activity due to factors impeding innovation, Hampering factor Regulations and standards: High"
cap label var HFLEX_LOW "No innovation activity due to factors impeding innovation, Hampering factor Regulations and standards: Low"
cap label var HFLEX_MED "No innovation activity due to factors impeding innovation, Hampering factor Regulations and standards: Medium"
cap label var HFLEX_MISS "Missing information for given variable"
cap label var HFLEX_NO "No innovation activity not due to factors impeding innovation, Hampering factor Regulations and standards"
cap label var HFOUT_HIGH "Innovation costs too high, high important factor of hampering innovation activities"
cap label var HFOUT_HIGH10 "Enterprises for which the lack of finance from sources outside the enterprise is a highly important factor of hampering innovation activities"
cap label var HFPAR_HIGH "Enterprises for which the difficulty in finding cooperation partners for innovation is a highly important factor of hampering innovation activities"
cap label var HFPER_HIGH "Enterprises for which the lack of qualified personnel is a highly important factor of hampering innovation activities"
cap label var HIMP_MISS "Missing information for given variable"
cap label var HIMP_NO "No innovation activity not due to market conditions"
cap label var HIMP_YES "No innovation activity due to market conditions"
cap label var HINF_HIGH "No innovation activity due to factors impeding innovation, Hampering factor Information on markets: High"
cap label var HINF_LOW "No innovation activity due to factors impeding innovation, Hampering factor Information on markets: Low"
cap label var HINF_MED "No innovation activity due to factors impeding innovation, Hampering factor Information on markets: Medium"
cap label var HINF_MISS "Missing information for given variable"
cap label var HINF_NO "No innovation activity not due to factors impeding innovation, Hampering factor Information on markets"
cap label var HMAR_MISS "Missing information for given variable"
cap label var HMAR_NO "No innovation activity needed not due to prior innovations"
cap label var HMAR_YES "No innovation activity needed due to prior innovations"
cap label var HOCC_YES "Enterprises head office the Candidate Countries"
cap label var HOEFTA_YES "Enterprises head office in EFTA"
cap label var HOEU_YES "Enterprises head office in the EU"
cap label var HOJP_YES "Enterprises head office in Japan"
cap label var HOOT_YES "Enterprises that are part of an enterprise group and have a foreign head office"
cap label var HORG_HIGH "No innovation activity due to factors impeding innovation, Hampering factor Organisational rigidities: High"
cap label var HORG_LOW "No innovation activity due to factors impeding innovation, Hampering factor Organisational rigidities: Low"
cap label var HORG_MED "No innovation activity due to factors impeding innovation, Hampering factor Organisational rigidities: Medium"
cap label var HORG_MISS "Missing information for given variable"
cap label var HORG_NO "No innovation activity not due to factors impeding innovation, Hampering factor Organisational rigidities"
cap label var HOUS_YES "Enterprises head office the USA"
cap label var HPER_HIGH "Enterprises for which the lack of skilled employees within the enterprise was a highly important barrier to innovate"
cap label var HPER_LOW "No innovation activity due to factors impeding innovation, Hampering factor Qualified personnel: Low"
cap label var HPER_MED "No innovation activity due to factors impeding innovation, Hampering factor Qualified personnel: Medium"
cap label var HPER_MISS "Missing information for given variable"
cap label var HPER_NO "No innovation activity not due to factors impeding innovation, Hampering factor Qualified personnel"
cap label var HPRIOR_MISS "Missing information for given variable"
cap label var HPRIOR_NO "No innovation activity not due to any reason"
cap label var HPRIOR_YES "No innovation activity: Summary"
cap label var HSTAR_MISS "Missing information for given variable"
cap label var HSTAR_NO "Enterprise with innovation activity not prevented to be started"
cap label var HSTAR_YES "Enterprise with innovation activity prevented to be started"
cap label var HTEC_HIGH "No innovation activity due to factors impeding innovation, Hampering factor Information on technology: High"
cap label var HTEC_LOW "No innovation activity due to factors impeding innovation, Hampering factor Information on technology: Low"
cap label var HTEC_MED "No innovation activity due to factors impeding innovation, Hampering factor Information on technology: Medium"
cap label var HTEC_MISS "Missing information for given variable"
cap label var HTEC_NO "No innovation activity not due to factors impeding innovation, Hampering factor Information on technology"
cap label var IES_SDOS "Design of objects or services skills employed in-house and obtained from external sources"
cap label var IES_SENAP "Engineering / applied sciences skills employed in-house and obtained from external sources"
cap label var IES_SGALA "Graphic arts / layout / advertising skills employed in-house and obtained from external sources"
cap label var IES_SMED "Multimedia skills employed in-house and obtained from external sources"
cap label var IES_SMKR "Market research skills employed in-house and obtained from external sources"
cap label var IES_SMSDM "Mathematics / statistics / database management skills employed in-house and obtained from external sources"
cap label var IES_SSWD "Software development skills employed in-house and obtained from external sources"
cap label var IES_SWDS "Web design skills employed in-house and obtained from external sources"
cap label var IH_SDOS "Design of objects or services skills employed in-house-only"
cap label var IH_SENAP "Engineering / applied sciences skills employed in-house-only"
cap label var IH_SGALA "Graphic arts / layout / advertising skills employed in-house-only"
cap label var IH_SMED "Multimedia skills employed in-house-only"
cap label var IH_SMKR "Market research skills employed in-house-only"
cap label var IH_SMSDM "Mathematics / statistics / database management skills employed in-house-only"
cap label var IH_SSWD "Software development skills employed in-house-only"
cap label var IH_SWDS "Web design skills employed in-house-only"
cap label var INAB_MISS "Missing information for given variable"
cap label var INAB_NO "Enterprise with no abandoned innovation activities"
cap label var INAB_YES "Enterprise with abandoned innovation activities"
cap label var INDEHIE "Employees with higher education per employee, 2000"
cap label var INDEP1 "Independent innovating enterprises"
cap label var INDEP2 "Independent enterprises"
cap label var INDEXE "Export per employee, 2000"
cap label var INDEXE98 "Export per employee, 1998"
cap label var INDEXP1 "Total innovation expenditure, per employee 2000"
cap label var INDEXP1_04 "Total innovation expenditure as a share of total turnover"
cap label var INDEXP10 "Expenditure in external knowledge, as a share of total turnover 2000"
cap label var INDEXP10_04 "Expenditure in acquisition of other external knowledge as a share of total turnover"
cap label var INDEXP11 "Expenditure in training, market introduction and other, per employee 2000"
cap label var INDEXP12 "Expenditure in training, market introduction and other, as a share of total turnover 2000"
cap label var INDEXP2 "Total innovation expenditure as a share of total turnover 2000"
cap label var INDEXP3 "Expenditure in intramural R&D, per employee 2000"
cap label var INDEXP4 "Expenditure in intramural R&D, as a share of total turnover 2000"
cap label var INDEXP4_04 "Intramural R&D expenditure as a share of total turnover"
cap label var INDEXP5 "Extramural innovation expenditure, per employee 2000"
cap label var INDEXP6 "Extramural innovation expenditure, as a share of total turnover 2000"
cap label var INDEXP6_04 "Extramural R&D expenditure as a share of total turnover"
cap label var INDEXP7 "Expenditure in acquisition of machinery, per employee 2000"
cap label var INDEXP8 "Expenditure in acquisition of machinery, as a share of total turnover 2000"
cap label var INDEXP8_04 "Expenditure in acquisition of machinery, equipment and software as a share of total turnover"
cap label var INDEXP9 "Expenditure in external knowledge, per employee 2000"
cap label var INDINE "Gross Investment in tangibles per employee, 2000"
cap label var INDINEHI "Gross Investment in tangibles per employee with higher education, 2000"
cap label var INDRDPE "Persons involved in intramural R&D, as a share of total number of employees"
cap label var INDRDPEHI "Persons involved in intramural R&D, as a share of total number of employees with higher education"
cap label var INDTE "Turnover per employee, 2000"
cap label var INDTE98 "Turnover per employee, 1998"
cap label var INDTEHI "Turnover per employee with higher education, 2000"
cap label var INHOUSE "Enterprises innovating inhouse by type of innovators"
cap label var INMAR_MISS "Missing information for given variable"
cap label var INMAR_NO "Enterprise did not introduced new or improved products on the market"
cap label var INMAR_YES "Enterprise introduced new or improved products on the market"
cap label var INN_ACT "Innovation active enterprises"
cap label var INNO_ENT "Innovating enterprises - total"
cap label var INNO_TOT "Product and/or process innovative enterprises, regardless of organisational or marketing innovation as a % of total number of enterprises"
cap label var INNOCOOP_INNO "Innovative enterprises with innovation co-operation as a percentage of all innovative enterprises"
cap label var INNOEXP_TURN "Innovation expenditure as a percentage of turnover for all enterprises"
cap label var INON_MISS "Missing information for given variable"
cap label var INON_NO "Enterprises have no, not yet completed ongoing innovation activities"
cap label var INON_YES "Enterprises have not yet completed or ongoing innovation activities"
cap label var INPCS_1 "New processes developed by other enterprises"
cap label var INPCS_2 "New processes developed in collaboration with other enterprises"
cap label var INPCS_3 "New processes developed on their own"
cap label var INPCS_MISS "Missing information for given variable"
cap label var INPCS_NO "Not a process Innovator, did not introduce onto the market a new or significantly improved process"
cap label var INPCS_YES "Process Innovator, introduced onto the market a new or significantly improved process"
cap label var INPCSW_ADP_RD "Enterprises that developed process innovation by adapting or modifying processs originally developed by other enterprises or institutions, R&D performers only"
cap label var INPCSW_COP "Process, developed in cooperation with other enterprises or institutions"
cap label var INPCSW_COP_NRD "Enterprises that developed process innovation in cooperation with other enterprises or institutions, non-R&D performers only"
cap label var INPCSW_COP_RD "Enterprises that developed process innovation in cooperation with other enterprises or institutions, R&D performers only"
cap label var INPCSW_ENT "Process, developed by enterprise or group"
cap label var INPCSW_ENT_NRD "Enterprises that developed process innovation by themselves, non-R&D performers only"
cap label var INPCSW_ENT_RD "Enterprises that developed process innovation by themselves, R&D performers only"
cap label var INPCSW_MISS "Missing information for given variable, who mainly developed these products"
cap label var INPCSW_OTH "Process, developed mainly by other enterprises or institutions"
cap label var INPCSW_OTH_NRD "Enterprises that introduced process innovation developed by other enterprises or institutions, non-R&D performers only"
cap label var INPCSW_OTH_RD "Enterprises that introduced process innovation developed by other enterprises or institutions, R&D performers only"
cap label var INPDFW_YES "Enterprises that introduced at least one "world first" product innovation"
cap label var INPDGD "Enterprises that developed goods innovation"
cap label var INPDPC_ADP_NRD "Enterprises that developed product and/or process innovation by adapting or modifying goods, services or process originally developed by other enterprises or institutions / non R&D performers"
cap label var INPDPC_ADP_RD "Enterprises that developed product and/or process innovation by adapting or modifying goods, services or process originally developed by other enterprises or institutions / R&D performers"
cap label var INPDPC_COP_NRD "Enterprises that developed product and/or process innovation together with other enterprises or institutions / non R&D performers"
cap label var INPDPC_COP_RD "Enterprises that developed product and/or process innovation together with other enterprises or institutions / R&D performers"
cap label var INPDPC_ENT_NRD "Enterprises that developed product and/or process innovation by itself / non R&D performers"
cap label var INPDPC_ENT_RD "Enterprises that developed product and/or process innovation by itself / R&D performers"
cap label var INPDPC_OTH_NRD "Enterprises that introduced product and/or process innovation developed by other enterprises or institutions / non R&D performers"
cap label var INPDPC_OTH_RD "Enterprises that introduced product and/or process innovation developed by other enterprises or institutions / R&D performers"
cap label var INPDSV "Enterprises that developed service innovation"
cap label var INPDT_1 "New products developed by other enterprises"
cap label var INPDT_2 "New products developed in collaboration with other enterprises"
cap label var INPDT_3 "New products developed on their own"
cap label var INPDT_MISS "Missing information for given variable"
cap label var INPDT_NO "Not product innovator, did not introduce new or significantly improved products onto the market"
cap label var INPDT_YES "Product innovator, introduced new or significantly improved products onto the market"
cap label var INPDTG1 "Enterprises that developed goods innovation by themselves"
cap label var INPDTG2 "Enterprises that developed goods innovation in cooperation with other enterprises or institutions"
cap label var INPDTG3 "Enterprises that developed goods innovation by adapting or modifying goods originally developed by other enterprises or institutions"
cap label var INPDTG4 "Enterprises that introduced goods innovation developed by other enterprises or institutions"
cap label var INPDTS1 "Enterprises that developed service innovation by themselves"
cap label var INPDTS2 "Enterprises that developed service innovation in cooperation with other enterprises or institutions"
cap label var INPDTS3 "Enterprises that developed service innovation by adapting or modifying services originally developed by other enterprises or institutions"
cap label var INPDTS4 "Enterprises that introduced service innovation developed by other enterprises or institutions"
cap label var INPDTW_ADP_NRD "Enterprises that developed product innovation by adapting or modifying products originally developed by other enterprises or institutions, non-R&D performers only"
cap label var INPDTW_ADP_RD "Enterprises that developed product innovation by adapting or modifying products originally developed by other enterprises or institutions, R&D performers only"
cap label var INPDTW_COP "Product, developed in cooperation with other enterprises or institutions"
cap label var INPDTW_COP_NRD "Enterprises that developed product innovation in cooperation with other enterprises or institutions, non-R&D performers only"
cap label var INPDTW_COP_RD "Enterprises that developed product innovation in cooperation with other enterprises or institutions, R&D performers only"
cap label var INPDTW_ENT "Product, developed by enterprise or group"
cap label var INPDTW_ENT_NRD "Enterprises that developed product innovation by themselves, non-R&D performers only"
cap label var INPDTW_ENT_RD "Enterprises that developed product innovation by themselves, R&D performers only"
cap label var INPDTW_MISS "Missing information for given variable, who mainly developed these products"
cap label var INPDTW_OTH "Product, developed mainly by other enterprises or institutions"
cap label var INPDTW_OTH_NRD "Enterprises that introduced product innovation developed by other enterprises or institutions, non-R&D performers only"
cap label var INPDTW_OTH_RD "Enterprises that introduced product innovation developed by other enterprises or institutions, R&D performers only"
cap label var INPSDV1 "Enterprises that developed process innovation by themselves"
cap label var INPSDV2 "Enterprises that developed process innovation in cooperation with other enterprises or institutions"
cap label var INPSDV3 "Enterprises that developed process innovation by adapting or modifying processs originally developed by other enterprises or institutions"
cap label var INPSDV4 "Enterprises that introduced process innovation developed by other enterprises or institutions"
cap label var INPSLG "Enterprises that developed process innovation by improving logistics, delivery or distribution methods"
cap label var INPSNM0 "Enterprises that have introduced process innovation not new to the market"
cap label var INPSNM1 "Enterprises that have introduced process innovation new to the market"
cap label var INPSNM2 "Enterprises that have introduced process innovation without knowing if it was new to the market"
cap label var INPSPD "Enterprises that developed process innovation by improving methods of manufacturing or producing"
cap label var INPSSU "Enterprises that developed process innovation by supporting activities for processes"
cap label var INSER_1 "New services developed by other enterprises"
cap label var INSER_2 "New services developed in collaboration with other enterprises"
cap label var INSER_3 "New services developed on their own"
cap label var INTURN "Turnover of new or significantly improved products, but not new to the market"
cap label var INTURN_MISS "Missing information for the given variable"
cap label var INUN "Enterprises with unsuccessful or not yet completed projects"
cap label var INVTA "Total Gross Investment in tangibles in 2000"
cap label var LARMAR_EU "Enterprises for which the largest market in terms of turnover is the other EU, EFTA and/or EU-candidate countries"
cap label var LARMAR_LREG "Enterprises for which the largest market in terms of turnover is the local or the regional market"
cap label var LARMAR_NAT "Enterprises for which the largest market in terms of turnover is the national market"
cap label var LARMAR_OTH "Enterprises for which the largest market in terms of turnover is all other countries than EU countries, EFTA or EU-candidate countries"
cap label var MAR_EU "Enterprises that sell goods and/or services in other EU, EFTA or EU-candidate countries"
cap label var MAR_LREG "Enterprises that sell goods and/or services in the local or the regional markets"
cap label var MAR_NAT "Enterprises that sell goods and/or services in the national market"
cap label var MAR_OTH "Enterprises that sell goods and/or services in any other country than EU countries, EFTA or EU-candidate countries"
cap label var MARTURN "Turnover of new or significantly improved products, and new to the market"
cap label var MARTURN_MISS "Missing information for the given variable"
cap label var MBRST "Brainstorming sessions, successful method stimulating creativity"
cap label var MFIN "Financial incentives for employees to develop new ideas, successful method stimulating creativity"
cap label var MJBRT "Job rotation of staff, successful method stimulating creativity"
cap label var MKTDGP "Enterprises that introduced significant changes to the aesthetic design or packaging"
cap label var MKTINNO_YES "Enterprises that introduced marketing innovation"
cap label var MKTPDL "Enterprises that introduced new methods for product placement"
cap label var MKTPDP "Enterprises that introduced new media or techniques for product promotion"
cap label var MKTPRI "Enterprises that introduced new methods of pricing goods or services"
cap label var MMDCF "Multidisciplinary or cross-functional work teams, successful method stimulating creativity"
cap label var MNFIN "Non-financial incentives for employees, successful method stimulating creativity"
cap label var MTREM "Training employees on how to develop new ideas or creativity, successful method stimulating creativity"
cap label var NEWFRM_TURN "Turnover from new or significantly improved products only new to the firm"
cap label var NEWFRM_YES "Enterprises that have introduced new or significantly improved products that were only new to the firm"
cap label var NEWMAR "Innovators with products also new to the market"
cap label var NEWMAR_TURN "Turnover from new or significantly improved products that were new to the market"
cap label var NEWMAR_YES "Enterprises that have introduced new or significantly improved products that were new to the market"
cap label var NODEM_YES "Enterprises for which no need to innovate due to no demand for innovations is a highly important factor of hampering innovation activities"
cap label var NOENVID "No procedures"
cap label var NON_INDEP1 "Non-independent innovating enterprises"
cap label var NON_INDEP2 "Non-independent enterprises"
cap label var OBSAMK_HIGH "Enterprises considering high costs of access to new markets highly important"
cap label var OBSAMK_NR "Enterprises considering high costs of access to new markets not relevant"
cap label var OBSCP_HIGH "Enterprises considering innovations introduced by competitors highly important"
cap label var OBSCP_NR "Enterprises considering innovations introduced by competitors not relevant"
cap label var OBSDMK_HIGH "Enterprises considering dominant market share held by competitors highly important"
cap label var OBSDMK_NR "Enterprises considering dominant market share held by competitors not relevant"
cap label var OBSFIN_HIGH "Enterprises considering a lack of adequate finance highly important"
cap label var OBSFIN_NR "Enterprises considering a lack of adequate finance not relevant"
cap label var OBSLDE_HIGH "Enterprises considering a lack of demand highly important"
cap label var OBSLDE_NR "Enterprises considering a lack of demand not relevant"
cap label var OBSPR_HIGH "Enterprises considering strong price competition highly important"
cap label var OBSPR_NR "Enterprises considering strong price competition not relevant"
cap label var OBSPRS_HIGH "Enterprises considering a lack of qualified personnel highly important"
cap label var OBSPRS_NR "Enterprises considering a lack of qualified personnel not relevant"
cap label var OBSQL_HIGH "Enterprises considering strong competition on product quality highly important"
cap label var OBSQL_NR "Enterprises considering strong competition on product quality not relevant"
cap label var OBSREG_HIGH "Enterprises considering high costs of meeting regulations highly important"
cap label var OBSREG_NR "Enterprises considering high costs of meeting regulations not relevant"
cap label var OCAP "Enterprises for which increasing capacity for producing goods or services is a highly important objective"
cap label var OENMK "Enter new markets"
cap label var OENV_IMP "Reduce environmental damage"
cap label var OENV_NO "Reduce environmental damage"
cap label var OEXT_IMP "Extend product or service range"
cap label var OEXT_NO "Extend product or service range"
cap label var OFLEX "Enterprises for which improving flexibility for producing goods or services is a highly important objective"
cap label var OHES "Improve health and safety"
cap label var OHESY "Enterprises for which improving health or safety of the employees is a highly important objective"
cap label var OIMKS "Increase market share"
cap label var OIMP_IMP "Improving product or service quality"
cap label var OIMP_NO "Improving product or service quality"
cap label var OLBR "Enterprises for which reducing labour costs per unit output is a highly important objective"
cap label var OLBR_IMP "Reduce labour cost"
cap label var OLBR_NO "Reduce labour cost"
cap label var OMAT_IMP "Reduce material consumption"
cap label var OMAT_NO "Reduce material consumption"
cap label var OMKTCG "Enterprises for which introducing products to new customer groups is a highly important objective"
cap label var OMKTGM "Enterprises for which introducing products to new geographic markets is a highly important objective"
cap label var OMKTS "Enterprises for which increasing or maintaining market share is a highly important objective"
cap label var ONMOMS "Enterprises for which entering new markets or increasing market share is a highly important objective"
cap label var ONRG_IMP "Reduce energy consumption"
cap label var ONRG_NO "Reduce energy consumption"
cap label var OOPN_IMP "Open up new markets or increase market share"
cap label var OOPN_NO "Open up new markets or increase market share"
cap label var OPDT_IMP "Improve production or internal business process flexibility"
cap label var OPDT_NO "Improve production or internal business process flexibility"
cap label var OQUA "Enterprises for which improving quality of goods or services is a highly important objective"
cap label var ORANGE "Enterprises for which increasing range of goods or services is a highly important objective"
cap label var OREI "Enterprises for which reducing environmental impacts is a highly important objective"
cap label var OREP_IMP "Replace products or services being phased out"
cap label var OREP_NO "Replace products or services being phased out"
cap label var OREPL "Enterprises for which replacing outdated products or processes is a highly important objective"
cap label var ORGBUP "Enterprises that introduced new business practices for organising procedures"
cap label var ORGEXR "Enterprises that introduced new methods of organising external relations"
cap label var ORGINNO_YES "Enterprises that introduced organisational innovation"
cap label var ORGMKT_YES "Enterprises that introduced organisational and/or marketing innovation"
cap label var ORGWKP "Enterprises that introduced new methods of organising work responsibilities and decision making"
cap label var ORME "Enterprises for which reducing material and energy costs per unit output is a highly important objective"
cap label var OROABL "Enterprises for which improving ability to develop new products or processes is a highly important objective"
cap label var OROCIN "Enterprises for which improving communication or information sharing is a highly important objective"
cap label var OROQUA "Enterprises for which improving quality of goods or services is a highly important objective"
cap label var ORORCO "Enterprises for which reducing costs per unit output is a highly important objective"
cap label var ORORED "Enterprises for which reducing time to respond to customer or supplier needs is a highly important objective"
cap label var OSTD_IMP "Fulfilling regulations and standards"
cap label var OSTD_NO "Fulfilling regulations and standards"
cap label var PAAP_MISS "Missing information for given variable"
cap label var PAAP_NO "Enterprise did not apply for at least a patent to protect inventions"
cap label var PAAP_YES "Enterprise applied for at least a patent to protect inventions"
cap label var PANDP_TOT "Product and process innovative enterprises only, as a % of total number of enterprises (regardless of organisational or marketing innovation )"
cap label var PAT "Having applied for a patent"
cap label var PAVAL_MISS "Missing information for given variable"
cap label var PAVAL_NO "No, number of valid patents at end of 2000"
cap label var PAVAL_YES "Number of valid patents at end of 2000"
cap label var PCSO_TOT "Process innovative enterprises only, as a % of total number of enterprises"
cap label var PDTO_TOT "Product innovative enterprises only, as a % of total number of enterprises (regardless of organisational or marketing innovation )"
cap label var PRIOR_YES "Enterprises for which no need to innovate due to prior innovations is a highly important factor of hampering innovation activities"
cap label var PROC_INN "Process innovators"
cap label var PROCP "Claimed copyright"
cap label var PROCP_MISS "Missing information for given variable"
cap label var PROCP_NO "No, protection through copyright"
cap label var PROCP_YES "Protection through copyright"
cap label var PROD_INN "Product innovators"
cap label var PRODES_MISS "Missing information for given variable"
cap label var PRODES_NO "No, protection through complexity of design"
cap label var PRODES_YES "Protection through complexity of design"
cap label var PRODSG "Enterprises that registered an industrial design right"
cap label var PROPAT "Enterprises that applied for a patent"
cap label var PROREG_MISS "Missing information for given variable"
cap label var PROREG_NO "No, protection through registration of design patters"
cap label var PROREG_YES "Protection through registration of design patters"
cap label var PROSEC_MISS "Missing information for given variable"
cap label var PROSEC_NO "No, protection through secrecy"
cap label var PROSEC_YES "Protection through secrecy"
cap label var PROTIM_MISS "Missing information for given variable"
cap label var PROTIM_NO "No, protection through lead-time advantage over competitors"
cap label var PROTIM_YES "Protection through lead-time advantage over competitors"
cap label var PROTM "Enterprises that registered a trademark"
cap label var PROTM_MISS "Missing information for given variable"
cap label var PROTM_NO "No, protection through trademarks"
cap label var PROTM_YES "Protection through trademarks"
cap label var PUB_GEN "Enterprises with procurement contract for domestic and/or foreign public sector"
cap label var PUBDINNR "Enterprises with procurement contract for domestic public sector that undertake innovation activities not required as part of the contract"
cap label var PUBDINRQ "Enterprises with procurement contract for domestic public sector that undertake innovation activities required as part of the contract"
cap label var PUBDNONIN "Enterprises with procurement contract for domestic public sector for which the enterprise didn't undertake any innovation activities"
cap label var PUBDOM "Enterprises with procurement contract for domestic public sector"
cap label var PUBFINNR "Enterprises with procurement contract for foreign public sector that undertake innovation activities not required as part of the contract"
cap label var PUBFINRQ "Enterprises with procurement contract for foreign public sector that undertake innovation activities required as part of the contract"
cap label var PUBFNONIN "Enterprises with procurement contract for foreign public sector for which the enterprise didn't undertake any innovation activities"
cap label var PUBFOR "Enterprises with procurement contract for foreign public sector"
cap label var PUBINNR "Enterprises with procurement contract for domestic and/or foreign public sector for which innovation was not required as part of the contract"
cap label var PUBINRQ "Enterprises with procurement contract for domestic and/or foreign public sector for which innovation was required as part of the contract"
cap label var PUBNONIN "Enterprises with procurement contract for domestic and/or foreign public sector without any innovation activity"
cap label var RD_HIGH "Innovating enterprises with high R&D intensity"
cap label var RD_LOW "Innovating enterprises with low R&D intensity"
cap label var RD_MED "Innovating enterprises with medium R&D intensity"
cap label var RD_NULL "Innovating enterprises with no R&D expenditures"
cap label var RDCON_1 "Engaged continuously in R&D"
cap label var RDCON_2 "Engaged occasionally in R&D"
cap label var RDCON_3 "Not engaged at all in R&D"
cap label var RDENG_CONT "Enterprises, engaged continuously in in-house R&D activities"
cap label var RDENG_MISS "Missing information for given variable"
cap label var RDENG_OCC "Enterprises, engaged occasionally in in-house R&D activities"
cap label var RDEX_INNO "Product and/or process (PP) innovative enterprises engaged in extra mural R&D activities as a % of PP innovative enterprises"
cap label var RDIN_INNO "Product and/or process (PP) innovative enterprises engaged in intra mural R&D activities as a % of PP innovative enterprises"
cap label var RDPER "Total number of persons involved in intramural R&D for 2000"
cap label var RDSG "Enterprises, engaged in design activities to improve or change the shape of the appearance of goods or services"
cap label var REXP04 "Total innovation expenditure"
cap label var REXP04_YES "Enterprises, engaged in innovation activities"
cap label var REXP06 "Total innovation expenditure"
cap label var REXP06_YES "Enterprises, engaged in innovation activities"
cap label var REXP08 "Total innovation expenditure"
cap label var REXP08_YES "Enterprises, engaged in innovation activities"
cap label var REXP10 "Total innovation expenditure (for in-house and external R&D, acquisition of machinery, equipment, software and external knowledge) in 2010"
cap label var REXP10_YES "Enterprises that have declared expenditures for in-house and external R&D, acquisition of machinery, equipment, software and external knowledge in 2010"
cap label var RID "Industrial design (manufacturing sector) or preparations to introduce new services or methods (service sector)"
cap label var RMAC "Machinery and equipment acquisition"
cap label var RMAC_MISS "Missing information for given variable"
cap label var RMAC_NO "Not engaged in acquisition of machinery"
cap label var RMAC_YES "Engaged in acquisition of machinery"
cap label var RMACES_YES "Enterprises, engaged in acquisition of machinery, equipment and software"
cap label var RMACES04 "Expenditure for acquisition of machinery, equipment and software in 2004"
cap label var RMACES06 "Expenditure for acquisition of machinery, equipment and software in 2006"
cap label var RMACES08 "Expenditure for acquisition of machinery, equipment and software in 2008"
cap label var RMACES10 "Expenditure for acquisition of machinery, equipment and software in 2010"
cap label var RMACES12 "Expenditures in acquisition of machinery, equipment and software in 2012"
cap label var RMACX "Total Expenditure in acquisition of machinery for 2000"
cap label var RMAR "Market introduction of innovation"
cap label var RMAR_MISS "Missing information for given variable"
cap label var RMAR_NO "Enterprises, not engaged in market introduction of innovation"
cap label var RMAR_YES "Enterprises, engaged in market introduction of innovations"
cap label var ROEK_MISS "Missing information for given variable"
cap label var ROEK_NO "Enterprises not engaged in other external knowledge"
cap label var ROEK_YES "Enterprises, engaged in aquisition of other external knowledge"
cap label var ROEK04 "Expenditure for acquisition of other external knowledge in 2004"
cap label var ROEK06 "Expenditure for acquisition of other external knowledge in 2006"
cap label var ROEK08 "Expenditure for acquisition of other external knowledge in 2008"
cap label var ROEK10 "Expenditure for acquisition of external knowledge in 2010"
cap label var ROEK12 "Expenditures in acquisition of external knowledge in 2012"
cap label var ROEKX "Total Expenditure in other external knowledge for 2000"
cap label var ROET "External technology acquisition"
cap label var ROTHE_YES "Enterprises, engaged in other innovation activities"
cap label var ROTHX "Total Expenditure in training, market introduction and other preparation for 2000"
cap label var ROTREX12 "Expenditures for the "other" innovation activities in 2012 (including design, training, marketing, and other relevant activities)"
cap label var ROTREX12_YES "Enterprises concerned by expenditures related to the "other" activities (including design, training, marketing, and other relevant activities)"
cap label var RPRE_MISS "Missing information for given variable"
cap label var RPRE_NO "Enterprises, not engaged in design, other preparation"
cap label var RPRE_YES "Enterprises, engaged in design, other preparation"
cap label var RRDEX "Extramural R&D"
cap label var RRDEX_MISS "Missing information for given variable"
cap label var RRDEX_NO "Not engaged in extramural R&D"
cap label var RRDEX_YES "Enterprises, engaged in external R&D activities"
cap label var RRDEX04 "Expenditure in extramural R&D in 2004"
cap label var RRDEX06 "Expenditure in extramural R&D in 2006"
cap label var RRDEX08 "Expenditure in extramural R&D in 2008"
cap label var RRDEX10 "Expenditure for purchase of external R&D in 2010"
cap label var RRDEX12 "Expenditures in external R&D in 2012"
cap label var RRDEXX "Total Expenditure in extramural R&D for 2000"
cap label var RRDIN "Intramural R&D"
cap label var RRDIN_MISS "Missing information for given variable"
cap label var RRDIN_NO "Enterprises, not engaged in intramural R&D"
cap label var RRDIN_YES "Enterprises, engaged in in-house R&D activities"
cap label var RRDIN04 "Expenditure in intramural R&D in 2004"
cap label var RRDIN06 "Expenditure in intramural R&D in 2006"
cap label var RRDIN08 "Expenditure in intramural R&D in 2008"
cap label var RRDIN10 "Expenditure for in-house R&D in 2010"
cap label var RRDIN12 "Expenditures in in-house R&D in 2012"
cap label var RRDINX "Total expenditure in intramural R&D for 2000"
cap label var RTOT "Total innovation expenditure for 2000"
cap label var RTR "Training directly linked to technological innovation"
cap label var RTR_MISS "Missing information for given variable"
cap label var RTR_NO "Enterprises not engaged in training"
cap label var RTR_YES "Enterprises, engaged in training for innovation activities"
cap label var SB311 "Enterprises innovating in-house of the total population"
cap label var SB341 "Turnover of new or significantly improved products, but not new to the market as a share of total turnover"
cap label var SB421 "Turnover of new or significantly improved products, and new to the market as a share of total turnover"
cap label var SCLI "Enterprises for which the clients or customers are a highly important source of information"
cap label var SCLI_HIGH "High use of Sources for innovation from Clients or customers"
cap label var SCLI_IMP "Clients"
cap label var SCLI_LOW "Low use of Sources for innovation from Clients or customers"
cap label var SCLI_MED "Medium use of Sources for innovation from Clients or customers"
cap label var SCLI_MISS "Missing information for given variable"
cap label var SCLI_NO "Sources for innovation from Clients or customers, not used"
cap label var SCLPR_HIGH "Enterprises considering information from clients or customers from the private sector highly important"
cap label var SCLPR_NU "Enterprises that don't use information from clients or customers from the private sector"
cap label var SCLPU_HIGH "Enterprises considering information from clients or customers from the public sector highly important"
cap label var SCLPU_NU "Enterprises that don't use information from clients or customers from the public sector"
cap label var SCOM "Enterprises for which the competitors or other enterprises of the same sector are a highly important source of information"
cap label var SCOM_HIGH "Enterprises considering information from competitors or other enterprises in your sector highly important"
cap label var SCOM_IMP "Competitors"
cap label var SCOM_LOW "Low use of sources for innovation from Competitors and other enterprises of same industry"
cap label var SCOM_MED "Medium use of sources for innovation from Competitors and other enterprises of same industry"
cap label var SCOM_MISS "Missing information for given variable"
cap label var SCOM_NO "Sources from Competitors for innovation and other enterprises of same industry, not used"
cap label var SCOM_NU "Enterprises that don't use information from competitors or other enterprises in your sector"
cap label var SCON "Enterprises for which the conferences, trade fairs, exhibitions are a highly important source of information"
cap label var SCON_HIGH "Enterprises considering information from conferences, trade fairs, exhibitions highly important"
cap label var SCON_IMP "Consultancy enterprises"
cap label var SCON_NO "Consultancy enterprises"
cap label var SCON_NU "Enterprises that don't use information from conferences, trade fairs, exhibitions"
cap label var SDOS "Design of objects or services , not used or not relevant skills"
cap label var SENAP "Engineering / applied sciences, not used or not relevant skills"
cap label var SENT_HIGH "High use of sources from within the enterprise"
cap label var SENT_IMP "Sources within the enterprise"
cap label var SENT_LOW "Low use of sources from within the enterprise"
cap label var SENT_MED "Medium use of sources from within the enterprise"
cap label var SENT_MISS "Missing information for given variable"
cap label var SENT_NO "Sources from within the enterprise, not used"
cap label var SENTG "Enterprises for which the enterprise or the enterprise group is a highly important source of information"
cap label var SENTG_HIGH "Enterprises considering information within the enterprise or enterprise group highly important"
cap label var SENTG_NU "Enterprises that don't use information within the enterprise or enterprise group"
cap label var SEXB_HIGH "High use of Sources for innovation from Fairs, exhibitions"
cap label var SEXB_IMP "Fairs and exhibitions"
cap label var SEXB_LOW "Low use of Sources for innovation from Fairs, exhibitions"
cap label var SEXB_MED "Medium use of Sources for innovation from Fairs, exhibitions"
cap label var SEXB_MISS "Missing information for given variable"
cap label var SEXB_NO "Sources for innovation from Fairs, exhibitions, not used"
cap label var SGALA "Graphic arts / layout / advertising, not used or not relevant skills"
cap label var SGMT "Enterprises for which the Government or public research institutes are a highly important source of information"
cap label var SGMT_HIGH "High use of Sources for innovation from Government or private non-profit research institutes"
cap label var SGMT_IMP "Government or private non-profit research institutes"
cap label var SGMT_LOW "Low use of Sources for innovation from Government or private non-profit research institutes"
cap label var SGMT_MED "Medium use of Sources for innovation from Government or private non-profit research institutes"
cap label var SGMT_MISS "Missing information for given variable"
cap label var SGMT_NO "Sources from Government for innovation or private non-profit research institutes, not used"
cap label var SGMTP_HIGH "Enterprises considering information from Government, public or private research institutes highly important"
cap label var SGMTP_NU "Enterprises that don't use information from Government, public or private research institutes"
cap label var SGRP_HIGH "High use of Sources for innovation from Other enterprises within the enterprise group"
cap label var SGRP_IMP "Other enterprises within the enterprise group"
cap label var SGRP_LOW "Low use of Sources for innovation from Other enterprises within the enterprise group"
cap label var SGRP_MED "Medium use of Sources for innovation from Other enterprises within the enterprise group"
cap label var SGRP_MISS "Missing information for given variable"
cap label var SGRP_NO "Sources for innovation from Other enterprises within the enterprise group, not used"
cap label var SIGMAR_INT "Number of enterprises where international market most significant market"
cap label var SIGMAR_LN "Number of enterprises where local/neighb. market most significant market"
cap label var SIGMAR_LOC "Number of enterprises where local market most significant market"
cap label var SIGMAR_MISS "Missing information for given variable"
cap label var SIGMAR_NAT "Number of enterprises where national market most significant market"
cap label var SINS "Enterprises for which the consultants, commercial labs or private R&D institutes are a highly important source of information"
cap label var SINSL_HIGH "Enterprises considering information from consultants or commercial labs highly important"
cap label var SINSL_NU "Enterprises that don't use information from consultants or commercial labs institutes"
cap label var SJOU "Enterprises for which scientific journals and trade/technical publications are a highly important source of information"
cap label var SJOU_HIGH "Enterprises considering information from scientific journals and trade/technical publications highly important"
cap label var SJOU_NU "Enterprises that don't use information from scientific journals and trade/technical publications"
cap label var SME_COOP "SMEs involved in innovation co-operation as a percentage of all SMEs"
cap label var SME_INNO "SMEs innovating in-house as a percentage of all SMEs"
cap label var SMED "Multimedia (combining audio, graphics, text, still pictures, animation, video etc), not used or not relevant skills"
cap label var SMKR "Market research, not used or not relevant skills"
cap label var SMSDM "Mathematics / statistics / database management, not used or not relevant skills"
cap label var SNET_IMP "Computer based information networks"
cap label var SNET_NO "Computer based information networks"
cap label var SPAT_IMP "Patent disclosures"
cap label var SPAT_NO "Patent disclosures"
cap label var SPRO_HIGH "High use of Sources for innovation from Professional conferences, meetings, journals"
cap label var SPRO_IMP "Professional conferences, meetings, journals"
cap label var SPRO_LOW "Low use of Sources for innovation from Professional conferences, meetings, journals"
cap label var SPRO_MED "Medium use of Sources for innovation from Professional conferences, meetings, journals"
cap label var SPRO_MISS "Missing information for given variable"
cap label var SPRO_NO "Sources for innovation from Professional conferences, meetings, journals, not used"
cap label var SPROF "Enterprises for which the professional and industry associations are a highly important source of information"
cap label var SPROF_HIGH "Enterprises considering information from professional and industry associations highly important"
cap label var SPROF_NU "Enterprises that don't use information from professional and industry associations"
cap label var SSUP "Enterprises for which the suppliers of equipment, materials, components or software are a highly important source of information"
cap label var SSUP_HIGH "Enterprises considering information from suppliers of equipment, materials, components or software highly important"
cap label var SSUP_IMP "Suppliers of equipment, material, components of software"
cap label var SSUP_LOW "Low use of Sources for innovation from Suppliers of equipment, materials, etc."
cap label var SSUP_MED "Medium use of Sources for innovation from Suppliers of equipment, materials, etc."
cap label var SSUP_MISS "Missing information for given variable"
cap label var SSUP_NO "Sources for innovation from Suppliers of equipment, materials, etc., not used"
cap label var SSUP_NU "Enterprises that don't use information from suppliers of equipment, materials, components or software"
cap label var SSWD "Software development, not used or not relevant skills"
cap label var STALL_HIGH "Enterprises that consider building alliances highly important"
cap label var STALL_NR "Enterprises that consider building alliances not relevant"
cap label var STEXCOS_HIGH "Enterprises that consider reducing costs of purchased materials,components or services highly important"
cap label var STEXCOS_NR "Enterprises that consider reducing costs of purchased materials, components or services not relevant"
cap label var STFLEX_HIGH "Enterprises that consider increasing flexibility / responsiveness highly important"
cap label var STFLEX_NR "Enterprises that consider increasing flexibility / responsiveness not relevant"
cap label var STIHCOS_HIGH "Enterprises that consider reducing in-house costs of operation highly important"
cap label var STIHCOS_NR "Enterprises that consider reducing in-house costs of operation not relevant"
cap label var STINNPD_HIGH "Enterprises that consider introducing new or significantly improved goods or services highly important"
cap label var STINNPD_NR "Enterprises that consider introducing new or significantly improved goods or services not relevant"
cap label var STMKEUR_HIGH "Enterprises that consider developing new markets within Europe highly important"
cap label var STMKEUR_NR "Enterprises that consider developing new markets within Europe not relevant"
cap label var STMKOTH_HIGH "Enterprises that consider developing new markets outside Europe highly important"
cap label var STMKOTH_NR "Enterprises that consider developing new markets outside Europe not relevant"
cap label var STMKT_HIGH "Enterprises that consider intensifying or improving the marketing of goods or services highly important"
cap label var STMKT_NR "Enterprises that consider intensifying or improving the marketing of goods or services not relevant"
cap label var SUNI "Enterprises for which the universities or other higher education institutes are a highly important source of information"
cap label var SUNI_HIGH "Enterprises considering information from universities or other higher education institutes highly important"
cap label var SUNI_IMP "Universities or other higher education institutes"
cap label var SUNI_LOW "Low use of Sources for innovation from Universities or other higher education institutes"
cap label var SUNI_MED "Medium use of Sources for innovation from Universities or other higher education institutes"
cap label var SUNI_MISS "Missing information for given variable"
cap label var SUNI_NO "Sources for innovation from Universities or other higher education institutes, not used"
cap label var SUNI_NU "Enterprises that don't use information from universities or other higher education institutes"
cap label var SWDS "Web design, not used or not relevant skills"
cap label var TURN "Total turnover in 2000"
cap label var TURN_ALL "Total turnover for all enterprises"
cap label var TURN02 "Total turnover in 2002"
cap label var TURN04 "Total turnover in 2004"
cap label var TURN06 "Total turnover in 2006"
cap label var TURN08 "Total turnover in 2008"
cap label var TURN10 "Total turnover in 2010"
cap label var TURN12 "Total turnover in 2012"
cap label var TURN98 "Total turnover in 1998"
cap label var TURNDEC_MISS "Missing information for given variable"
cap label var TURNDEC_NO "Number of enterprises where turnover did not decrease by 10%"
cap label var TURNDEC_YES "Number of enterprises where turnover decreased by 10%"
cap label var TURNENT_TURN "Turnover of new or significantly improved products which are new to the enterprise but not new to the market as a percentage of turnover for all enterprises"
cap label var TURNIMP "Improved products"
cap label var TURNINC_MISS "Missing information for given variable"
cap label var TURNINC_NO "Number of enterprises where turnover did not increase by 10%"
cap label var TURNINC_YES "Number of enterprises where turnover increased by 10%"
cap label var TURNMAR "Turnover of new products also new to the market"
cap label var TURNMKT_TURN "Turnover of new or significantly improved products which are new to the enterprise and also new to the market as a percentage of turnover for all enterprises"
cap label var TURNNEW "New products"
cap label var TURNPROD "Total turnover for product innovators"
cap label var TURNUNG "Unchanged products"
cap label var UNGETURN "Turnover from unchanged or marginally modified products (of product innovators)"
cap label var UNGTURN "Turnover of unchanged or marginally modified products, but not new to the market"
cap label var UNGTURN_MISS "Missing information for the given variable"
cap label var PROEUM "Enterprises that applied for a European utility model"
cap label var PROAMDT "Enterprises that applied for a patent, a European utility model or that registered an industrial design right or a trademark"
cap label var PROLEX "Enterprises that licensed out or sold a patent, industrial design right, copyright or trademark to another enterprise, university or research institute"
cap label var PROLIN "Enterprises that licensed in or bought a patent, industrial design right, copyright or trademark owned by another enterprise, university or research institute"
cap label var PROLINEX "Enterprises that licensed in/out or bought/sold a patent, industrial design right, copyright or trademark owned by another enterprise, university or research institute"
cap label var PROPATDSG "Enterprises that applied for a patent or an industrial design right"
cap label var PROPATTM "Enterprises that applied for a patent or registered a trademark"
cap label var ECOALL "Enterprises that introduced an innovation with environmental benefits (obtained within the enterprise or by the end user)"
cap label var ECOINENT "Enterprises that introduced an innovation with environmental benefits obtained within the enterprise"
cap label var ECOENO "Enterprises that reduced energy use or CO2 'footprint' within the enterprises by innovating"
cap label var ECOREP "Enterprises that replaced a share of fossil energy with renewable energy sources within the enterprises by innovating"
cap label var ECOUSER "Enterprises that introduced an innovation with environmental benefits obtained by the end user"
cap label var ECOEXT "Enterprises that extended product life through more durable products, by innovating"
cap label var ECOPRD "Enterprises with environmental benefits due to product innovation"
cap label var ECOPRC "Enterprises with environmental benefits due to process innovation"
cap label var ECORG "Enterprises with environmental benefits due to organisation innovation"
cap label var ECOMKT "Enterprises with environmental benefits due to marketing innovation"
cap label var ENEREG_HIGH "Enterprises for which existing environmental regulations were a highly important factor"
cap label var ENEREG_NR "Enterprises for which existing environmental regulations were not a relevant factor"
cap label var ENETX_HIGH "Enterprises for which existing environmental taxes, charges or fees were a highly important factor"
cap label var ENETX_NR "Enterprises for which existing environmental taxes, charges or fees were not a relevant factor"
cap label var ENREGF_HIGH "Enterprises for which environmental regulations or taxes expected in the future were a highly important factor"
cap label var ENREGF_NR "Enterprises for which environmental regulations or taxes expected in the future were not a relevant factor"
cap label var ENGRA_HIGH "Enterprises for which Government grants, subsidies or other financial incentives for environmental innovations were a highly important factor"
cap label var ENGRA_NR "Enterprises for which Government grants, subsidies or other financial incentives for environmental innovations were not a relevant factor"
cap label var ENDEM_HIGH "Enterprises for which current or expected market demand for environmental innovations was a highly important factor"
cap label var ENDEM_NR "Enterprises for which current or expected market demand for environmental innovations was not a relevant factor"
cap label var ENREP_HIGH "Enterprises for which improving the enterprise's reputation was a highly important factor"
cap label var ENREP_NR "Enterprises for which improving the enterprise's reputation was not a relevant factor"
cap label var ENAGR_HIGH "Enterprises for which voluntary actions or initiatives for environmental good practice within the sector were a highly important factor"
cap label var ENAGR_NR "Enterprises for which voluntary actions or initiatives for environmental good practice within the sector were not a relevant factor"
cap label var ENCOST_HIGH "Enterprises for which high cost of energy, water or materials was a highly important factor"
cap label var ENCOST_NR "Enterprises for which high cost of energy, water or materials was not a relevant factor"
cap label var ENREQU_HIGH "Enterprises for which the need to meet requirements for public procurement contracts was a highly important factor"
cap label var ENREQU_NR "Enterprises for which the need to meet requirements for public procurement contracts was not a relevant factor"
cap label var ENVID_YES "Enterprises that had procedures to identify and reduce the environmental impacts"
cap label var ENVID_NO "Enterprises that did not have procedures to identify and reduce the environmental impacts"
cap label var ENVBF "Enterprises that had procedures implemented before 2012 to identify and reduce the environmental impacts"
cap label var ENVBT "Enterprises that had procedures implemented between 2012 and 2014 to identify and reduce the environmental impacts"
cap label var TURN14 "Total turnover in 2014"
cap label var EMP14 "Total number of employees in 2014"
cap label var TURNOUT12 "Turnover from sales outside the home country in 2012"
cap label var TURNOUT14 "Turnover from sales outside the home country in 2014"
cap label var ENT_POPU14 "Total number of enterprises in the population in 2014"
cap label var C11_VAL "Enterprises for which cooperation with universities, other higher education institutions, Government, public or private research institutes is the most valuable method"
cap label var C11 "Enterprises co-operating with universities, other higher education institutions, Government, public or private research institutes"
cap label var HCOMPR "Enterprises with no compelling reason to innovate"
cap label var HBARIN "Enterprises that considered innovating, but too large barriers"
cap label var HLDEM_HIGH "Enterprises for which the low market demand was a highly important reason to not innovate"
cap label var HLDEM_NR "Enterprises for which the low market demand was not an important reason to not innovate"
cap label var HPRIOR_HIGH "Enterprises for which previous innovations were a highly important reason to not innovate"
cap label var HPRIOR_NR "Enterprises for which previous innovations were not an important reason to not innovate"
cap label var HCOMPL_HIGH "Enterprises for which the little market competition was a highly important reason to not innovate"
cap label var HCOMPL_NR "Enterprises for which the little market competition was not an important reason to not innovate"
cap label var HIDIN_HIGH "Enterprises for which the lack of good ideas was a highly important reason to not innovate"
cap label var HIDIN_NR "Enterprises for which the lack of good ideas was not an important reason to not innovate"
cap label var HFENT_NR "Enterprises for which the lack of internal finance was not an important barrier to innovate"
cap label var HCRE_HIGH "Enterprises for which the lack of credit or private equity was a highly important barrier to innovate"
cap label var HCRE_NR "Enterprises for which the lack of credit or private equity was not an important barrier to innovate"
cap label var HPER_NR "Enterprises for which the lack of skilled employees within the enterprise was not an important barrier to innovate"
cap label var HSUBS_HIGH "Enterprises for which the difficulties in obtaining government grants or subsidies were a highly important barrier to innovate"
cap label var HSUBS_NR "Enterprises for which the difficulties in obtaining government grants or subsidies were not an important barrier to innovate"
cap label var HPAR_HIGH "Enterprises for which the lack of collaboration partners was a highly important barrier to innovate"
cap label var HPAR_NR "Enterprises for which the lack of collaboration partners was not an important barrier to innovate"
cap label var HDEMI_HIGH "Enterprises for which the uncertain market demand was a highly important barrier to innovate"
cap label var HDEMI_NR "Enterprises for which the uncertain market demand was not an important barrier to innovate"
cap label var HCOMPH_HIGH "Enterprises for which too much market competition was a highly important barrier to innovate"
cap label var HCOMPH_NR "Enterprises for which too much market competition was not an important barrier to innovate"
cap label var RRDIN14 "Expenditures in in-house R&D in 2014"
cap label var RRDEX14 "Expenditures in external R&D in 2014"
cap label var RMACES14 "Expenditures in acquisition of machinery, equipment and software in 2014"
cap label var ROEK14 "Expenditures in acquisition of external knowledge in 2014"
cap label var ROTREX14 "Expenditures for the 'other' innovation activities in 2014 (including design, training, marketing, and other relevant activities)"
cap label var EXPTOT14 "Total innovation expenditures in 2014"
