cap label var ERN "Gross earnings"
cap label var E_F_M_PC "Gross earnings of women as a percentage of those of men"
cap label var OPAY "Overtime pay"
cap label var OP_E_PC "Overtime pay as a percentage of earnings"
cap label var MEAN_B_SALC_EUR "Mean annual bonuses per employee concerned in euro"
cap label var MEAN_B_SALC_PPS "Mean annual bonuses per employee concerned in PPS"
cap label var MEAN_H "Mean annual number of holidays"
cap label var SPAY "Shift pay"
cap label var SP_E_PC "Shift pay as a percentage of earnings"
cap label var BNS "Annual bonuses"
cap label var B_E_PC "Annual bonuses as a percentage of annual earnings"
cap label var HPAID "Hours paid"
cap label var OHP "Overtime hours paid"
cap label var OH_H_PC "Overtime hours as a percentage of hours"
cap label var MMW_MEAN_ME_PP "Monthly minimum wage as a proportion of the mean gross monthly earnings"
cap label var MMW_MED_ME_PP "Monthly minimum wage as a proportion of the median gross monthly earnings"
cap label var HOL "Annual holidays"
cap label var SAL "Employees"
cap label var LOC_UNIT "Local units"
cap label var MEAN_E_EUR "Mean earnings in euro"
cap label var MEAN_E_PPS "Mean earnings in PPS"
cap label var MED_E_EUR "Median earnings in euro"
cap label var MED_E_PPS "Median earnings in PPS"
cap label var D1_E_EUR "First decile earnings in euro"
cap label var D1_E_PPS "First decile earnings in PPS"
cap label var D9_E_EUR "Ninth decile earnings in euro"
cap label var D9_E_PPS "Ninth decile earnings in PPS"
cap label var MEAN_OP_SAL_EUR "Mean overtime pay per employee in euro"
cap label var MEAN_OP_SAL_PPS "Mean overtime pay per employee in PPS"
cap label var MEAN_OP_SALC_EUR "Mean overtime pay per employee concerned in euro"
cap label var MEAN_OP_SALC_PPS "Mean overtime pay per employee concerned in PPS"
cap label var MEAN_SP_SAL_EUR "Mean shift pay per employee in euro"
cap label var MEAN_SP_SAL_PPS "Mean shift pay per employee in PPS"
cap label var MEAN_SP_SALC_EUR "Mean shift pay per employee concerned in euro"
cap label var MEAN_SP_SALC_PPS "Mean shift pay per employee concerned in PPS"
cap label var MEAN_HP "Mean number of hours paid"
cap label var MEAN_OHP_SAL "Mean number of overtime hours paid per employee"
cap label var MEAN_OHP_SALC "Mean number of overtime hours paid per employee concerned"
cap label var MEAN_B_SAL_EUR "Mean annual bonuses per employee in euro"
cap label var MEAN_B_SAL_PPS "Mean annual bonuses per employee in PPS"
cap label var HE "Hourly earnings"
cap label var HE_FPCM "Hourly earnings of women as % of those of men"
cap label var HOVT "Hourly overtime pay"
cap label var HEAOVT "Hourly earnings plus overtime pay"
cap label var HEO_FPCM "Hourly earnings plus overtime pay of women as % of those of men"
cap label var HOVTPC "Hourly overtime pay as % of hourly earnings"
cap label var ME "Monthly earnings"
cap label var MOVT "Monthly overtime pay"
cap label var MS "Monthly shift pay"
cap label var MOVTPC "Monthly overtime pay as % of monthly earnings"
cap label var MSPC "Monthly shift pay as % of monthly earnings"
cap label var AE "Annual earnings"
cap label var AB "Annual bonuses"
cap label var ABPC "Annual bonuses as % of annual earnings"
cap label var MHP "Monthly hours paid"
cap label var MHPAOVT "Monthly overtime hours paid"
cap label var MHPOVTPC "Monthly overtime hours as % of monthly hours"
cap label var MW_MEAGE "Monthly minimum wage as a proportion of the mean value of average monthly earnings"
cap label var MW_MEDGE "Monthly minimum wage as a proportion of the median value of average monthly earnings"
cap label var AH "Annual holidays"
cap label var SAL_NR "Number of employees"
cap label var LOU_NR "Number of local units"
cap label var ERN_MN_EUR "Mean earnings in euro"
cap label var ERN_MN_PPS "Mean earnings in PPS"
cap label var ERN_MD_EUR "Median earnings in euro"
cap label var ERN_MD_PPS "Median earnings in PPS"
cap label var ERN_D1_EUR "First decile earnings in euro"
cap label var ERN_D1_PPS "First decile earnings in PPS"
cap label var ERN_D9_EUR "Ninth decile earnings in euro"
cap label var ERN_D9_PPS "Ninth decile earnings in PPS"
cap label var ERN_D10_EUR "Tenth decile earnings in euro"
cap label var ERN_D10_PPS "Tenth decile earnings in PPS"
cap label var LWE_PC "Proportion of low-wage earners based on hourly earnings"
cap label var OVS_MN_EUR "Mean monthly overtime pay per employee in euro"
cap label var OVS_MN_PPS "Mean monthly overtime pay per employee in PPS"
cap label var OVC_MN_EUR "Mean monthly overtime pay per employee concerned in euro"
cap label var OVC_MN_PPS "Mean monthly overtime pay per employee concerned in PPS"
cap label var SHS_MN_EUR "Mean monthly shift pay per employee in euro"
cap label var SHS_MN_PPS "Mean monthly shift pay per employee in PPS"
cap label var SHC_MN_EUR "Mean monthly shift pay per employee concerned in euro"
cap label var SHC_MN_PPS "Mean monthly shift pay per employee concerned in PPS"
cap label var HP_MN_HR "Mean monthly number of hours paid"
cap label var OVHPS_MN_HR "Mean monthly number of overtime hours paid per employee"
cap label var OVHPC_MN_HR "Mean monthly number of overtime hours paid per employee concerned"
cap label var BS_MN_EUR "Mean annual bonuses per employee in euro"
cap label var BS_MN_PPS "Mean annual bonuses per employee in PPS"
cap label var BC_MN_EUR "Mean annual bonuses per employee concerned in euro"
cap label var BC_MN_PPS "Mean annual bonuses per employee concerned in PPS"
cap label var HDAY_MN "Mean annual number of holidays"
