cap label var TOTAL "Total"
cap label var DG1 "Explosive substances and articles"
cap label var DG2 "Gases"
cap label var DG3 "Flammable liquids"
cap label var DG4 "Flammable solids; substances liable to spontaneous combustion; substances which, on contact with water, emit flammable gases"
cap label var DG41 "Flammable solids"
cap label var DG42 "Substances liable to spontaneous combustion"
cap label var DG43 "Substances, which on contact with water, emit flammable gases"
cap label var DG5 "Oxidising substances and organic peroxides"
cap label var DG51 "Oxidising substances"
cap label var DG52 "Organic peroxides"
cap label var DG6 "Toxic and infectious substances"
cap label var DG61 "Toxic substances"
cap label var DG62 "Infectious substances"
cap label var DG7 "Radioactive material"
cap label var DG8 "Corrosive substances"
cap label var DG9 "Miscellaneous dangerous substances and articles"
cap label var UNK "Unknown dangerous goods"
cap label var EXPLOSIF "1. Explosives"
cap label var GASES "2. Gases,compressed,liquified,dissolved und.pressure"
cap label var FLAM_LIQ "3. Flammable liquids"
cap label var FLAM_SOL "4.1. Flammable solids"
cap label var SUB_SP_COMB "4.2. Substances liable to spontaneous combustion"
cap label var SUB_FLAM_GAS "4.3. Substance emitting flammable gases (with water)"
cap label var OXID_SUB "5.1. Oxidising substances"
cap label var ORG_PEROX "5.2. Organic peroxides"
cap label var TOXIC_SUB "6.1. Toxic substances"
cap label var SUB_INFECT "6.2. Substances liable to cause infections"
cap label var RADIOACT "7. Radioactive material"
cap label var CORROS "8. Corrosives"
cap label var DANG_MISC "9. Miscellaneous dangerous substances"
cap label var DANG_GD_UNK "99. Unknown dangerous good"
cap label var TOT_DANG_GDS "10. Total all dangerous goods groups"
