cap label var TOTAL "Total"
cap label var DECR_CONS "Considerable decrease"
cap label var DECR_MOD "Moderate decrease"
cap label var SAME "No change"
cap label var INCR_MOD "Moderate increase"
cap label var INCR_CONS "Considerable increase"
cap label var UNK "Not relevant - unknown"
cap label var NEI "Negative impact"
cap label var NOI "No impact"
cap label var POI "Positive impact"
cap label var NAPPLUNK "Not applicable/Do not know"
cap label var SOI "Some impact"
cap label var SUI "Substantial impact"
cap label var NAPPL "Not applicable"
