cap label var TOTAL "Total"
cap label var IN "Within enterprise group"
cap label var IN_DOM "Within enterprise group domestically"
cap label var IN_INTL "Within enterprise group abroad"
cap label var IN_EXST "Existing foreign enterprise of same group"
cap label var IN_ACQ "New existing foreign enterprise of same group (by acquisition)"
cap label var IN_NEW "Newly created foreign enterprise of same group (green field operation)"
cap label var OUT "Outside enterprise group"
cap label var OUT_DOM "Outside enterprise group domestically"
cap label var OUT_INTL "Outside enterprise group abroad"
cap label var IN_OUT_INTL "Within and outside enterprise group abroad"
cap label var OTH "Other"
cap label var UNK "Unknown"
cap label var IN_EX "Existing foreign enterprise of same group"
cap label var IN_AQ "New existing foreign enterprise of same group (by acquisition)"
cap label var OTHER "Other foreign enterprises"
