cap label var TOTAL "Total"
cap label var ALL "All levels"
cap label var VH_H "Very high or high"
cap label var VHIGH_MOD "Very high or moderate"
cap label var VHIGH "Very high"
cap label var TYNG_SPK "Too young to speak"
cap label var MOT "Mother tongue"
cap label var PROF "Proficient"
cap label var STR "Strong"
cap label var GRT_MOD_SOME "Great, moderate or some"
cap label var GRT "Great"
cap label var HIGH "High"
cap label var HVY "Heavy"
cap label var VG_FG "Very good or fairly good"
cap label var VGOOD "Very good"
cap label var BROAD "Broad"
cap label var GOOD "Good"
cap label var VG_G "Very good or good"
cap label var FGOOD "Fairly good"
cap label var FAIR "Fair"
cap label var INT "Intermediate"
cap label var MED "Medium"
cap label var MOD_SEV "Moderate or severe"
cap label var MOD "Moderate"
cap label var LMOD "At least moderate"
cap label var MOD_HVY "Moderate or heavy"
cap label var SOME "Some"
cap label var BASIC "Basic"
cap label var LTD "Limited"
cap label var VMILD "Very mild"
cap label var MILD "Mild"
cap label var M_VM "Mild or very mild"
cap label var LGHT "Light"
cap label var NONE_LGHT "None or light"
cap label var NONE_MIN "None or minimum"
cap label var POOR "Poor"
cap label var L_VL "Low or very low"
cap label var LOW "Low"
cap label var NLOW "Not low"
cap label var BAD "Bad"
cap label var VLOW "Very low"
cap label var VB_FB "Very bad or fairly bad"
cap label var VBAD "Very bad"
cap label var FBAD "Fairly bad"
cap label var B_VB "Bad or very bad"
cap label var SEV_MOD_LOW "Severe, moderate or low"
cap label var SEV "Severe"
cap label var NSEV "Non severe"
cap label var MODS "Moderately severe"
cap label var MOD_MODS_SEV "Moderate, moderately severe or severe"
cap label var VSEV "Very severe"
cap label var S_VS "Severe or very severe"
cap label var SM_SEV "Some or severe"
cap label var MOD_S_VS "Moderate, severe or very severe"
cap label var FDIF_VDIF "Fairly difficult or very difficult"
cap label var VDIF "Very difficult"
cap label var DIF "Difficult"
cap label var FDIF "Fairly difficult"
cap label var FEASY_EASY_VEASY "Fairly easy, easy or very easy"
cap label var FEASY_VEASY "Fairly easy or very easy"
cap label var FEASY "Fairly easy"
cap label var EASY "Easy"
cap label var VEASY "Very easy"
cap label var LTL "A little"
cap label var LOT "A lot"
cap label var XTRM "Extreme"
cap label var NONE "None"
cap label var NAP "Not applicable"
cap label var NRP "No response"
cap label var NSP "Not specified"
cap label var UNK "Unknown"
