cap label var TOTAL "Total"
cap label var HOLDMAN "Holder is manager"
cap label var SPSMAN "Spouse of holder is manager"
cap label var FAMMAN "Manager not holder but member of holder 's family"
cap label var NONFAMMAN "Manager is not member of holder 's family"
cap label var LEGENT "Holding is legal entity"
cap label var GRPHLD "Group holding"
