cap label var TOTAL "Total"
cap label var COK "Coking plant"
cap label var PLP "Plant for load preparation"
cap label var IFA "Plant for iron-making and ferro-alloys (including blast furnaces)"
cap label var SMS "Steelworks melting shops"
cap label var SMSE "Electric Steelworks melting shops"
cap label var CCA "Continuous casting"
cap label var RMD "Rolling mill departments"
cap label var FPR "Flat products"
cap label var LPR "Long products"
cap label var CWS "Cold wide strip mills"
cap label var COA "Coating installations"
cap label var FRN "Blast furnaces and electric iron making furnaces"
cap label var EGS "Electricity generating stations"
cap label var ELC "Electricity"
cap label var CHP "Combined heat and power (CHP)"
cap label var CHPU "Combined heat and power units"
cap label var CHPU_HE "Combined heat and power units with high efficiency"
cap label var CHPU_LE "Combined heat and power units with low efficiency"
cap label var CHPU_NOP "Combined heat and power units not in operation"
cap label var CHPU_RENF "Combined heat and power units - renewable fuels"
cap label var CHPU_NRENF "Combined heat and power units - non-renewable fuels"
cap label var CHPU_GTHSOL "Combined heat and power units - geothermal or solar energy"
cap label var CHPU_CHM_OTH "Combined heat and power units - heat recovered from chemical processes and other processes"
cap label var HEAT "Heat"
cap label var HU_ONL_RENF "Heat only units - renewable fuels (including reduction heat)"
cap label var HU_ONL_NRENF "Heat only units - non-renewable fuels (including reduction heat)"
cap label var HU_ONL_ELC "Heat only units - electricity (electric boilers)"
cap label var HU_ONL_GTHSOL "Heat only units - geothermal energy, ambient heat or solar energy"
cap label var HU_ONL_CHM_OTH "Heat only units - heat recovered from chemical processes and other processes"
cap label var MLS "Melting shops"
cap label var ABSPU_CL_RENEI "Absorption units for cooling - renewable energy input"
cap label var ABSPU_CL_NRENEI "Absorption units for cooling - non-renewable energy input"
cap label var VPC_CHILU "Vapour compression chiller units (electric or gas chillers)"
cap label var FREE_CL "Free cooling (lakes, rivers, seasonal storage below surface, etc.)"
cap label var OTH "Other plant"
cap label var POL "Environmental protection (not specified by plant)"
