cap label var BP010 "Total"
cap label var BP020 "Trade in goods"
cap label var BP030 "Trade in services"
cap label var BP040 "Income"
cap label var BP050 "Current transfers"
cap label var BP060 "Capital account - Millions of euro - Monthly data"
cap label var BP070 "Current and capital account - Millions of euro - Monthly data"
cap label var BP080 "Total"
cap label var BP090 "Direct investment"
cap label var BP100 "Portfolio investment"
cap label var BP110 "Financial derivatives"
cap label var BP120 "Other investment"
cap label var BP130 "Reserves assets"
cap label var BP140 "Net errors and omissions"
cap label var BP200 "Total"
cap label var BP210 "Trade in goods"
cap label var BP220 "Trade in services"
cap label var BP230 "Income"
cap label var BP240 "Current transfers"
cap label var BP_CA "Current account"
cap label var BP_CKA "Current and capital account - Millions of euro - Monthly data"
cap label var BP_EO "Net errors and omissions"
cap label var BP_G "Goods"
cap label var BP_IN1 "Primary income"
cap label var BP_IN2 "Secondary income"
cap label var BP_S "Services"
cap label var BP_FA "Financial account"
cap label var BP_FA__D__F "Financial account; Direct Investment"
cap label var BP_FA__P__F "Financial account; Portfolio Investment"
cap label var BP_FA__F__F7 "Financial account; Financial derivatives and employee stock options"
cap label var BP_FA__O__F "Financial account; Other Investment"
cap label var BP_FA__R__F "Financial account; Reserve assets"
cap label var BP_100 "Trade in goods"
cap label var BP_200 "Trade in services"
cap label var BP_300 "Income"
cap label var BP_379 "Current transfers"
cap label var BP_993 "Current account"
cap label var BP_994 "Capital account"
cap label var BP_010 "Current and capital account"
cap label var BP_995 "Financial account"
cap label var BP_500 "Direct investment"
cap label var BP_600 "Portfolio investment"
cap label var BP_910 "Financial derivatives"
cap label var BP_700 "Other investment"
cap label var BP_802 "Reserves assets"
cap label var BP_998 "Net errors and omissions"
cap label var BS_IPT "Production development observed over the past 3 months"
cap label var BS_EEI_I "Employment expectations indicator over the next 3 months"
cap label var BS_IEME "Employment expectations over the next 3 months"
cap label var BS_IEME_BAL "Employment expectations over the next 3 months - industry"
cap label var BS_CEME_BAL "Employment expectations over the next 3 months - construction"
cap label var BS_REM_BAL "Employment expectations over the next 3 months - retail trade"
cap label var BS_SEEM_BAL "Employment expectations over the next 3 months - services"
cap label var BS_IOB "Assessment of order-book levels"
cap label var BS_IEOB "Assessment of export order-book levels"
cap label var BS_ISFP "Assessment of the current level of stocks of finished products"
cap label var BS_IPE "Production expectations over the next 3 months"
cap label var BS_ISPE "Selling price expectations over the next 3 months"
cap label var BS_ICI "Industrial confidence indicator"
cap label var BS_ICPC_BAL "Assessment of current production capacity"
cap label var BS_IPCO_BAL "Duration of production assured by current order-books, months"
cap label var BS_INO_BAL "New orders in recent months"
cap label var BS_IEE_BAL "Export expectations for the months ahead"
cap label var BS_ICU_PC "Current level of capacity utilization (%)"
cap label var BS_CP3M_DM_BAL "Competitive position over the past 3 months: on the domestic market"
cap label var BS_CP3M_FMIEU_BAL "Competitive position on foreign markets inside the EU over the past three months"
cap label var BS_CP3M_EXEU_BAL "Competitive position on foreign markets outside the EU over the past three months"
cap label var BS_FLP1_PC "Factors limiting the production - None"
cap label var BS_FLP2_PC "Factors limiting the production - Insufficient demand"
cap label var BS_FLP3_PC "Factors limiting the production - Labour"
cap label var BS_FLP4_PC "Factors limiting the production - Equipment"
cap label var BS_FLP5_PC "Factors limiting the production - Other"
cap label var BS_FLP6_PC "Factors limiting the production - Financial constraints"
cap label var BS_CTA_BAL "Building activity development over the past 3 months"
cap label var BS_COB_BAL "Evolution of the current overall order books"
cap label var BS_CPE_BAL "Price expectations over the next 3 months"
cap label var BS_CCI_BAL "Construction confidence indicator"
cap label var BS_FLBA1_PC "Factors limiting building activity - None"
cap label var BS_FLBA2_PC "Factors limiting building activity - Insufficient demand"
cap label var BS_FLBA3_PC "Factors limiting building activity - Weather conditions"
cap label var BS_FLBA4_PC "Factors limiting building activity - Shortage of labour"
cap label var BS_FLBA5_PC "Factors limiting building activity - Shortage of material and/or equipment"
cap label var BS_FLBA6_PC "Factors limiting building activity - Other"
cap label var BS_FLBA7_PC "Factors limiting building activity - Financial constraints"
cap label var BS_OTEB "Operating time ensured by current backlog, months"
cap label var BS_RPBS "Business activity (sales) development over the past 3 months"
cap label var BS_RAS "Volume of stocks currently hold"
cap label var BS_ROP "Expectations of the number of orders placed with suppliers over the next 3 months"
cap label var BS_REBS "Business activity expectations over the next 3 months"
cap label var BS_REM "Employment expectations over the next 3 months"
cap label var BS_RPE "Price expectations over the next 3 months"
cap label var BS_RCI "Retail confidence indicator"
cap label var BS_FS_LY "Financial situation over the last 12 months"
cap label var BS_FS_NY "Financial situation over the next 12 months"
cap label var BS_GES_LY "General economic situation over the last 12 months"
cap label var BS_GES_NY "General economic situation over the next 12 months"
cap label var BS_PT_LY "Price trends over the last 12 months"
cap label var BS_PT_NY "Price trends over the next 12 months"
cap label var BS_UE_NY "Unemployment expectations over the next 12 months"
cap label var BS_MP_PR "The current economic situation is adequate to make major  purchases"
cap label var BS_MP_NY "Major purchases over the next 12 months"
cap label var BS_SV_PR "The current economic situation is adequate for savings"
cap label var BS_SV_NY "Savings over the next 12 months"
cap label var BS_SFSH "Statement on financial situation of household"
cap label var BS_CSMCI "Consumer confidence indicator"
cap label var BS_IBC_NTY "Intention to buy a car within the next 12 months"
cap label var BS_PBH_NTY "Purchase or build a home within the next 12 months"
cap label var BS_HI_NY "Home improvements over the next 12 months"
cap label var BS_ESI_I "Economic sentiment indicator"
cap label var BS_ICI_BAL "Industrial confidence indicator"
cap label var BS_RCI_BAL "Retail confidence indicator"
cap label var BS_CSMCI_BAL "Consumer confidence indicator"
cap label var BS_SCI_BAL "Services confidence indicator"
cap label var BS_SABC "Business situation development over the past 3 months"
cap label var BS_SARM "Evolution of demand over the past 3 months"
cap label var BS_SAEM "Expectation of the demand over the next 3 months"
cap label var BS_SERM "Evolution of employment over the past 3 months"
cap label var BS_SEEM "Expectation of the employment over the next 3 months"
cap label var BS_SCI "Services confidence indicator"
cap label var BS_PE3M "Expectations of the prices over the next 3 months"
cap label var BS_BCI "Business climate indicator"
cap label var CP_HI00 "HICP - All items (HICP=Harmonized Index of Consumer Prices)"
cap label var CP_HI01 "HICP - Food and non alcoholic beverages"
cap label var CP_HI02 "HICP - Alcoholic beverages and tobacco"
cap label var CP_HI03 "HICP - Clothing and footwear"
cap label var CP_HI04 "HICP - Housing, water, electricity,gas and other fuels"
cap label var CP_HI05 "HICP - Furnishings, household equipment and maintenance"
cap label var CP_HI06 "HICP - Health"
cap label var CP_HI07 "HICP - Transport"
cap label var CP_HI08 "HICP - Communication"
cap label var CP_HI09 "HICP - Recreation and culture"
cap label var CP_HI10 "HICP - Education"
cap label var CP_HI11 "HICP - Hotels, cafes and restaurants"
cap label var CP_HI12 "HICP - Miscellaneous goods and services"
cap label var CP_HI00XEF "HICP - All items excluding energy, food, alcohol and tobacco"
cap label var CP_HI00XTB "HICP - All items excluding tobacco"
cap label var CP_HIE "HICP - Energy"
cap label var CP_HIF "HICP - Food"
cap label var CP_HIFU "HICP - Unprocessed food"
cap label var CP_HIG "HICP - Total goods"
cap label var CP_HIIG "HICP - Industrial goods"
cap label var CP_HIS "HICP - Total services"
cap label var CP_HIIGXE "HICP - Non-energy industrial goods"
cap label var CP_HI00XE "HICP - All items excluding energy"
cap label var CP_HI00XEFU "HICP - All items excluding energy and unprocessed food"
cap label var CP_HI00XES "HICP - All items excluding energy and seasonal food"
cap label var ET_T "Total"
cap label var ET_CAP "Capital goods"
cap label var ET_CONS "Consumer goods"
cap label var ET_CONXT "Consumer goods (excluding transport equipment)"
cap label var ET_INTER "Intermediate goods"
cap label var IS_PPI "Output prices of the domestic market index (Producer price index) (NSA)"
cap label var IS_IO "New orders received index"
cap label var IS_IP "Production index"
cap label var IS_IP_CA "Production index - Calendar adjusted data, not seasonally adjusted data (CA)"
cap label var IS_IP_SA "Production index - Seasonally and calendar adjusted data (SCA)"
cap label var IS_IP_SCA "Production index - Seasonally and working days adjusted data (SCA)"
cap label var IS_EPI "Number of persons employed index"
cap label var IS_HWI "Hours worked index"
cap label var IS_WSI "Gross wages and salaries index"
cap label var IS_IPI "Cost index (input price index) - New residential buildings"
cap label var IS_PEI "Building permits index - New residential buildings"
cap label var IS_IT "Turnover index - Calendar adjusted data, not seasonally adjusted data (CA)"
cap label var IS_ITT "Turnover index - total"
cap label var IS_ITD "Turnover index - domestic market"
cap label var IS_ITND "Turnover index - non-domestic market"
cap label var IS_DIT "Deflated turnover index"
cap label var IS_IMPR "Import price index (NSA)"
cap label var IS_IMPX "Import price index - non euro area (NSA)"
cap label var IS_IMPZ "Import price index - euro area (NSA)"
cap label var IS_PNG_TJ "Production of natural gas, TJ (GCV)"
cap label var IS_CNG_TJ "Total consumption of natural gas, TJ (GCV)"
cap label var IS_ING_TJ "Imports of natural gas, TJ (GCV)"
cap label var IS_PEL_GWH "Production of electricity - GWh"
cap label var IS_CEL_GWH "Consumption of electricity - GWh"
cap label var IS_IEL_GWH "Imports of electricity - GWh"
cap label var IS_ROMS_T "Refinery output of motor spirit - 1000t"
cap label var IS_IDMS_T "Inland deliveries of motor spirit - 1000t"
cap label var IS_ROGD_T "Refinery output of gas/diesel oil - 1000t"
cap label var IS_IDGD_T "Inland deliveries of gas/diesel oil - 1000t"
cap label var IS_IDC_T "Inland deliveries of brown coal - 1000t"
cap label var IS_ICO_T "Imports of crude oil - 1000t"
cap label var IS_IDMG_T "Inland deliveries of motor gasoline - 1000t"
cap label var IS_IDJF_T "Inland deliveries of kerosene-type jet fuel - 1000t"
cap label var LM_UN_T_TOT "Unemployment according to ILO definition - Total"
cap label var LM_UN_M_TOT "Unemployment according to ILO definition - Males"
cap label var LM_UN_F_TOT "Unemployment according to ILO definition - Females"
cap label var LM_UN_T_LE25 "Unemployment according to ILO definition - Under 25 years - Total"
cap label var LM_UN_M_LE25 "Unemployment according to ILO definition - Under 25 years - Males"
cap label var LM_UN_F_LE25 "Unemployment according to ILO definition - Under 25 years - Females"
cap label var LM_UN_T_GT25 "Unemployment according to ILO definition - Over 25 years - Total"
cap label var LM_UN_M_GT25 "Unemployment according to ILO definition - Over 25 years - Males"
cap label var LM_UN_F_GT25 "Unemployment according to ILO definition - Over 25 years - Females"
cap label var LM_LCI_TOT "Labour cost index - Total labour cost"
cap label var LM_LCI_SAL "Labour cost index - Wages and salaries"
cap label var LM_LCI_OTH "Labour cost index - Labour costs other than wages and salaries"
cap label var MF_DDI_RT "Day-to-day money market interest rates (average)"
cap label var MF_3MI_RT "3-month interest rates (average)"
cap label var MF_EY1YM_RT "Euro yields - 1 year (average)"
cap label var MF_EY5YM_RT "Euro yields - 5 years (average)"
cap label var MF_EY10YM_RT "Euro yields - 10 years (average)"
cap label var MF_LTGBY_RT "Long term government bond yields - Maastricht definition (average)"
cap label var MF_EXA_RT "Exchange rates against the ECU/euro (average)"
cap label var F4 "Loans"
cap label var NA_B1G_CP_MIO_EUR "Gross value added at current prices (mio euro)"
cap label var NA_B1G_CP "Gross value added at current prices"
cap label var NA_D1_CP_MIO_EUR "Compensation of employees at current prices (mio euro)"
cap label var NA_D11_CP_MIO_EUR "Gross wages and salaries at current prices (mio euro)"
cap label var NA_D11 "Gross wages and salaries"
cap label var NA_B2G_B3G_CP_MIO_EUR "Gross operating surplus and mixed income (mio euro)"
cap label var NA_EMP_1000 "Total employment (1000)"
cap label var NA_EMP "Total employment"
cap label var NA_SAL_1000 "Employees (1000)"
cap label var NA_SAL "Employees"
cap label var NA_SELF_1000 "Self-employed (1000)"
cap label var NA_SELF "Self-employed"
cap label var NA_B1GM_CP_MIO_EUR "Gross domestic product at market current prices (mio euro)"
cap label var NA_B1GM_KP_RT1 "Gross domestic product at constant prices (% change t/t-1)"
cap label var NA_B1GM_CLV_I2000 "Gross domestic product at constant prices (index 2000=100)"
cap label var NA_D21_M_D31 "Taxes less subsidies on production and imports"
cap label var NA_B2G_B3G "Gross operating surplus and gross mixed income"
cap label var NA_D1 "Compensation of employees"
cap label var NA_B5N "Net national income"
cap label var NA_B5G "Gross national income"
cap label var NA_B6N "Net disposable income"
cap label var NA_B6G "Gross disposable income"
cap label var NA_B8G "Gross saving"
cap label var NA_B8N "Net saving"
cap label var NA_B9 "Net lending (+) /net borrowing (-)"
cap label var NA_D1_D4PAY "Primary incomes, payable"
cap label var NA_D1_D4REC "Primary incomes, receivable"
cap label var NA_D1_D4 "Net primary income transfers"
cap label var NA_D5_TO_D7PAY "Current transfers, payable"
cap label var NA_D5_TO_D7REC "Current transfers, receivable"
cap label var NA_D5_TO_D7 "Net current transfers"
cap label var NA_D9 "Capital transfers, net"
cap label var NA_D9PAY "Capital transfers, payable"
cap label var NA_D9REC "Capital transfers, receivable"
cap label var NA_D8 "Adjustment for the change in net equity of households in pension funds reserves"
cap label var NA_K2 "Acquisitions less disposals of non-financial non-produced assets"
cap label var NA_K1 "Consumption of fixed capital"
cap label var NA_D2_M_D3 "Taxes on production and imports less subsidies"
cap label var NA_P119 "Financial intermediation services indirectly measured (FISIM)"
cap label var NA_B1G "Gross value added"
cap label var NA_B1G_CLV2000 "Gross value added in volumes"
cap label var NA_B1G_MIO_EUR_CLV2000 "Gross value added - chain-linked volumes, reference year 2000 (at 2000 exchange rates) (mio euro)"
cap label var NA_B1G_MIO_EUR_CLV2005 "Gross value added - chain-linked volumes, reference year 2005 (at 2005 exchange rates) (mio euro)"
cap label var NA_B1GM "Gross domestic product at market prices"
cap label var NA_P3 "Final consumption expenditure"
cap label var NA_P3_S13 "Final consumption expenditure: general government"
cap label var NA_P31_S14 "Final consumption expenditure: households"
cap label var NA_P31_S15 "Final consumption expenditure: NPISH"
cap label var NA_P31_S14_S15 "Final consumption expenditure: household and NPISH"
cap label var NA_P5 "Gross capital formation"
cap label var NA_P51 "Gross fixed capital formation - total"
cap label var NA_P51_AB "Gross fixed capital formation: products of agriculture"
cap label var NA_P51_MET "Gross fixed capital formation: metal products and machinery"
cap label var NA_P51_DM "Gross fixed capital formation: transport equipment"
cap label var NA_P51_FA "Gross fixed capital formation: construction work - housing"
cap label var NA_P51_FB "Gross fixed capital formation: construction work - other constructions"
cap label var NA_P51_OTH "Gross fixed capital formation: other products"
cap label var NA_P52 "Changes in inventories"
cap label var NA_P53 "Acquisition less disposals of valuables"
cap label var NA_P3_P5 "Domestic demand"
cap label var NA_P61 "Exports of goods"
cap label var NA_P62 "Exports of services"
cap label var NA_P6 "Exports of goods and services"
cap label var NA_P71 "Imports of goods"
cap label var NA_P72 "Imports of services"
cap label var NA_P7 "Imports of goods and services"
cap label var NA_B111 "External balance: goods"
cap label var NA_B112 "External balance: services"
cap label var NA_B11 "External balance: total"
cap label var NA_GDEF "General government deficit (-) / surplus (+)"
cap label var NA_GDEBT "General government gross debt"
cap label var NA_GEXP "General government expenditure"
cap label var NA_GREV "General government revenue"
cap label var NA_GFINV "General government fixed investment"
cap label var NA_GPBAL "General government primary balance"
cap label var GD "Government consolidated gross debt"
cap label var NA_IGL_EU27_2020 "Intergovernmental lending within EU27 (from 2020) in the context of the financial crisis"
cap label var NA_IGL_EU28 "Intergovernmental lending within EU28 (2013-2020) in the context of the financial crisis"
cap label var NA_IGL_EU27_2007 "Intergovernmental lending within EU27 (2007-2013) in the context of the financial crisis"
cap label var NA_IGL_EU25 "Intergovernmental lending within EU25 (2004-2006) in the context of the financial crisis"
cap label var NA_IGL_EA17 "Intergovernmental lending within EA17 (2011-2013) in the context of the financial crisis"
cap label var NA_IGL_EA16 "Intergovernmental lending within EA16 (2009-2010) in the context of the financial crisis"
cap label var INV_TOT "Total investment"
cap label var INV_BSN "Business investment"
cap label var INV_GOV "Government investment"
cap label var INV_HH "Households investment"
cap label var BS_FCI "Financial services confidence indicator"
cap label var BS_BSDP3 "Assessment of business situation over the past 3 months"
cap label var BS_DEVP3 "Evolution of demand over the past 3 months"
cap label var BS_DEXN3 "Evolution of demand expected over the next 3 months"
cap label var BS_EEVP3 "Evolution of employment over the past 3 months"
cap label var BS_EEXN3 "Evolution of employment expected over the next 3 months"
cap label var BS_OIDP3 "Operating income development over the last three months"
cap label var BS_OIEN3 "Operating income expectations over the next three months"
cap label var BS_OEDP3 "Operating expenses development over the last three months"
cap label var BS_OEEN3 "Operating expenses expectations over the next three months"
cap label var BS_PDP3 "Profitability development over the last three months"
cap label var BS_PEN3 "Profitability expectations over the next three months"
cap label var BS_CEDP3 "Capital expenditure development over the last 3 months"
cap label var BS_CEEN3 "Capital expenditure expectations over the next 3 months"
cap label var BS_CPDTP3 "Competitive position development over the past 3 months (total)"
cap label var BS_CPD1P3 "Competitive position development over the past 3 months (in your country)"
cap label var BS_CPD2P3 "Competitive position development over the past 3 months (within the euro area)"
cap label var BS_CPD3P3 "Competitive position development over the past 3 months (within the EU)"
cap label var BS_CPD4P3 "Competitive position development over the past 3 months (outside the EU)"
cap label var BS_CPETN3 "Competitive position expectations over the next 3 months (total)"
cap label var BS_CPE1N3 "Competitive position expectations over the next 3 months (in your country)"
cap label var BS_CPE2N3 "Competitive position expectations over the next 3 months (within the euro area)"
cap label var BS_CPE3N3 "Competitive position expectations over the next 3 months (within the EU)"
cap label var BS_CPE4N3 "Competitive position expectations over the next 3 months (outside the EU)"
cap label var TOTAL "Total"
cap label var NEW_DW "New dwellings"
cap label var EXST_DW "Existing dwellings"
cap label var JOBRATE "Job vacancy rate"
cap label var INTINVT "International investment position: Total"
cap label var DIRINVT "Direct investment: Total"
cap label var PORINVT "Portfolio investment: Total"
cap label var FINDERT "Financial derivatives: Total"
cap label var OTHINVT "Other investment: Total"
cap label var RESASSETST "Reserves assets: total"
cap label var GROSFORDEBT "Gross foreign debt"
cap label var NETFORDEBT "Net external debt"
cap label var NEEREA17 "Nominal Effective Exchange Rate - 17 trading partners (Euro Area)"
cap label var NEER27 "Nominal Effective Exchange Rate - 27 trading partners"
cap label var NEER37 "Nominal Effective Exchange Rate - 37 trading partners"
cap label var NEER42 "Nominal Effective Exchange Rate - 42 trading partners"
cap label var REEREA17CPI "Real Effective Exchange Rate (deflator: consumer price indices - 17 trading partners - Euro Area)"
cap label var REER27CPI "Real Effective Exchange Rate (deflator: consumer price indices - 27 trading partners)"
cap label var REER37CPI "Real Effective Exchange Rate (deflator: consumer price indices - 37 trading partners)"
cap label var REER42CPI "Real Effective Exchange Rate (deflator: consumer price indices - 42 trading partners)"
cap label var IND_H "Headline indicators"
cap label var IND_A "Auxiliary indicators"
cap label var IND_T "All indicators"
cap label var BS_FLB1_PC "Main factors limiting the business - none"
cap label var BS_FLB2_PC "Main factors limiting the business - insufficient demand"
cap label var BS_FLB3_PC "Main factors limiting the business - labour"
cap label var BS_FLB4_PC "Main factors limiting the business - equipment and/or space"
cap label var BS_FLB5_PC "Main factors limiting the business - financial constraints"
cap label var BS_FLB6_PC "Main factors limiting the business - others"
cap label var BS_QP_PC "Possibility to increase the volume of activity with present resources"
cap label var TOVT "Index of turnover - Total"
cap label var TOVV "Index of deflated turnover"
