cap label var VITOT "Area under all vine varieties"
cap label var WGV "Area under wine-grape vine varieties"
cap label var VQPRD "Area for the production of quality wines psr"
cap label var OTHWINE "Area for the production of other wines including potable spirits"
cap label var SPIRIT "Area for production of potable spirits"
cap label var TABLEG "Area under table-grape vines"
cap label var ROOTST "Planted root stock for grafting"
cap label var NURSE "Area under vines for propagation in nurseries"
cap label var PARVINES "Area under parent vines"
cap label var RAISINS "Area under dried grape vine varieties"
