cap label var NBS01 "Exploration and exploitation of the earth"
cap label var NBS0100 "General Research on the exploration and exploitation of the earth"
cap label var NBS0101 "Mineral, oil and natural gas prospecting"
cap label var NBS0102 "Exploration and exploitation of the sea-bed"
cap label var NBS0103 "Earths crust and mantle excluding sea-bed"
cap label var NBS0104 "Hydrology"
cap label var NBS0105 "Sea and oceans"
cap label var NBS0106 "Atmosphere"
cap label var NBS0109 "Other research on the exploration and exploitation of the earth"
cap label var NBS02 "Infrastructure and general planning of land-use"
cap label var NBS0200 "General research on the infrastucture and general planning of land use"
cap label var NBS0201 "General planning of land-use"
cap label var NBS0202 "Construction and planning of buildings"
cap label var NBS0203 "Civil engineering"
cap label var NBS0204 "Transport systems"
cap label var NBS0205 "Telecommunication systems"
cap label var NBS0206 "Water supply"
cap label var NBS0209 "Other research on the infrastructure and general planning of land-use"
cap label var NBS03 "Control and care of the environment"
cap label var NBS0300 "General research on the environment"
cap label var NBS0301 "Protection of atmosphere and climate"
cap label var NBS0302 "Protection of ambient air"
cap label var NBS0303 "Solid waste"
cap label var NBS0304 "Protection of ambient water (excluding groundwater)"
cap label var NBS0305 "Protection of soil and groundwater"
cap label var NBS0306 "Abatement of noise and vibration"
cap label var NBS0307 "Protection of species and habitats"
cap label var NBS0308 "Protection against natural hazards"
cap label var NBS0309 "Protection against radioactive radiation"
cap label var NBS0310 "Other research on the environment"
cap label var NBS04 "Protection and improvement of human health"
cap label var NBS0400 "General research on protection and improvement of human health"
cap label var NBS0401 "Medical research, hospital treatment, surgery"
cap label var NBS0402 "Preventive medicine"
cap label var NBS0403 "Biomedical engineering and medicines"
cap label var NBS0404 "Occupational medicine"
cap label var NBS0405 "Nutrition and food hygiene"
cap label var NBS0406 "Drug abuse and addiction"
cap label var NBS0407 "Social medicine"
cap label var NBS0408 "Hospital structures and organization of medical care"
cap label var NBS0409 "Other medical research"
cap label var NBS05 "Production, distribution and rational utilization of energy"
cap label var NBS0500 "General research on production, distribution, and rational utilization of energy"
cap label var NBS0501 "Fossil fuels and their derivatives"
cap label var NBS0502 "Nuclear fission"
cap label var NBS0503 "Radioactive waste management including decommissioning with regard to fuel/energy"
cap label var NBS0504 "Nuclear fusion"
cap label var NBS0505 "Renewable energy sources"
cap label var NBS05051 "Solar thermal and photovoltaic energy"
cap label var NBS05052 "Geothermal energy"
cap label var NBS05053 "Water, wind and wave energy"
cap label var NBS05054 "Research into biomass conversion (particularly into the areas of pyrolysis, gasification, extraction and enzyme processing); research on the processing of waste from industry, agriculture and the domestic sector with a view to energy"
cap label var NBS0506 "Rational utilization of energy"
cap label var NBS0509 "Other research on production, distribution and rational utilization of energy"
cap label var NBS06 "Agricultural production and technology"
cap label var NBS0600 "General research on agricultural production and technology"
cap label var NBS0601 "Animal Products"
cap label var NBS0602 "Fishing and fish-farming"
cap label var NBS0603 "Veterinary medicine"
cap label var NBS0604 "Crops"
cap label var NBS0605 "Forestry and timber production"
cap label var NBS0606 "Food technology"
cap label var NBS0609 "Other research on agricultural production and technology"
cap label var NBS07 "Industrial production, and technology"
cap label var NBS0700 "General research on industrial production and technology"
cap label var NBS0701 "Increasing economic efficiency and competitiveness"
cap label var NBS0702 "Manufacturing and processing techniques"
cap label var NBS0703 "Extractions and processing of non-energy mineral and derived products"
cap label var NBS0704 "Products of the chemical industry"
cap label var NBS07041 "Petrochemical and coal by-products"
cap label var NBS07042 "Pharmaceutical products"
cap label var NBS0705 "Manufacture of motor vehicles and other means of transport"
cap label var NBS07051 "Aerospace equipment manufacturing and repairing"
cap label var NBS07052 "Manufacture of motor vehicles and parts (including agricultural tractors)"
cap label var NBS07053 "Manufacture of all other transport equipment"
cap label var NBS0706 "Electronic and related industries"
cap label var NBS07061 "Manufacture of office machinery and data-processing equipment"
cap label var NBS07062 "Manufacture of radio, television and communications equipment and apparatus"
cap label var NBS07063 "Software development"
cap label var NBS0707 "Manufacture of electrical machinery and apparatus"
cap label var NBS0708 "Manufacture of non-electronic and non-electrical machinery"
cap label var NBS0709 "Manufacture of instruments"
cap label var NBS07091 "Manufacture of medical and surgical equipment and orthopaedic appliances"
cap label var NBS07092 "All other instrument manufacture"
cap label var NBS0710 "Manufacture of food products and beverages"
cap label var NBS0711 "Manufacture of textile, clothing and leather goods"
cap label var NBS0712 "Other manufacturing products"
cap label var NBS0713 "Recycling waste"
cap label var NBS08 "Social structures and relationships"
cap label var NBS0800 "Research of a general nature"
cap label var NBS0801 "Education, training, recurrent education and retraining"
cap label var NBS0802 "Cultural activities"
cap label var NBS0803 "Management of businesses and institutions"
cap label var NBS0804 "Improvement of working conditions"
cap label var NBS0805 "Social security system"
cap label var NBS0806 "Political structure of society"
cap label var NBS0807 "Social change, social processes and social conflicts"
cap label var NBS0809 "Other research with regard to society"
cap label var NBS09 "Exploration and exploitation of space"
cap label var NBS0900 "General research on exploration and exploitation of space"
cap label var NBS0901 "Scientific exploration of space"
cap label var NBS0902 "Applied research programmes"
cap label var NBS0903 "Launch systems"
cap label var NBS0904 "Space laboratories and space travel"
cap label var NBS0909 "Other research on the exploration and exploitation of space"
cap label var NBS10 "Research financed from general university funds (GUF)"
cap label var NBS1000 "Mathematics and computer sciences"
cap label var NBS1001 "Physical sciences"
cap label var NBS1002 "Chemical sciences"
cap label var NBS1003 "Biological sciences"
cap label var NBS1004 "Earth and related (environmental) sciences"
cap label var NBS1005 "Engineering sciences"
cap label var NBS1006 "Medical sciences"
cap label var NBS1007 "Agricultural sciences"
cap label var NBS1008 "Social sciences"
cap label var NBS1009 "Humanities"
cap label var NBS11 "Non-oriented research"
cap label var NBS1100 "Mathematics and computer sciences"
cap label var NBS1101 "Physical sciences"
cap label var NBS1102 "Chemical sciences"
cap label var NBS1103 "Biological sciences"
cap label var NBS1104 "Earth and related (environmental) sciences"
cap label var NBS1105 "Engineering sciences"
cap label var NBS1106 "Medical sciences"
cap label var NBS1107 "Agricultural sciences"
cap label var NBS1108 "Social sciences"
cap label var NBS1109 "Humanities"
cap label var NBS12 "Other civil research"
cap label var NBS13 "Defence"
cap label var NBS99_X_13 "Total civil research and development appropriations"
cap label var NBS99 "Total appropriations"
