cap label var FARM_NR "Farm - number"
cap label var UAA_HA "Utilised agricultural area - hectare"
cap label var FA_HA "Farm area - hectare"
cap label var FAXSAA_HA "Farm area excluding special agricultural production areas - hectare"
cap label var FARM_NR_LS "Farms with livestock - number"
cap label var FARM_LSU_LS "Farms with livestock - live stock unit"
cap label var SO_EUR "Standard output - euro"
cap label var LF_D_AWU "Labour force directly employed - annual working unit"
cap label var FARM_NR_PD_GT50 "Farms whose household consumes more than 50% of the final production - number"
cap label var HRI1 "Harmonised risk indicator 1"
cap label var HRI2 "Harmonised risk indicator 2"
