cap label var TOTAL "Total"
cap label var NEWS "Newspapers, magazines and journals"
cap label var ADVPT "Advertising material distributed by post"
cap label var RADIO "Radio"
cap label var TV "Television"
cap label var INET "Internet"
cap label var OUTRA "Outdoor and transport advertising (airplanes, buses, taxis, posters etc.)"
cap label var OTH "Other media"
