cap label var TOTAL "Total"
cap label var TOT_R "Total of rented accommodation"
cap label var R_HOT "Rented accommodation: hotels or similar establishments"
cap label var R_CAMP "Rented accommodation: campsites, caravan or trailer park"
cap label var R_APT "Rented accommodation: apartment, house, villa or room in a dwelling"
cap label var R_OTH "Rented accommodation: other"
cap label var TOT_NR "Total of non-rented accommodation"
cap label var NR_OWN "Non-rented accommodation: own holiday home"
cap label var NR_RF "Non-rented accommodation: accommodation provided without charge by relatives or friends"
cap label var NR_OTH "Non-rented accommodation: other"
cap label var SHR "Shared accomodation"
cap label var ENTI "Entire accommodation"
cap label var ESTBL "Establishments"
cap label var BEDRM "Bedrooms"
cap label var BEDPL "Bedplaces"
