cap label var TOTAL "Total"
cap label var HHW_10 "All adults working"
cap label var HHW_11 "All adults working full time"
cap label var HHW_12 "At least one adult working part time, all other adults (if any) working full time"
cap label var HHW_20 "At least one adult working and one adult not working"
cap label var HHW_30 "All adults not working (all households)"
cap label var HHW_31 "All adults not working (excluding households composed solely of students)"
cap label var HHW_32 "All adults not working (excluding households composed solely of students or solely inactive aged 65 and over)"
cap label var NRESP "No response"
cap label var UNK "Unknown"
