cap label var TOT_HC "Current health care expenditure (CHE)"
cap label var HC1_2 "Curative care and rehabilitative care"
cap label var HC1 "Curative care"
cap label var HC11_21 "Inpatient curative and rehabilitative care"
cap label var HC11 "Inpatient curative care"
cap label var HC12_22 "Day curative and rehabilitative care"
cap label var HC12 "Day curative care"
cap label var HC13_23 "Outpatient curative and rehabilitative care"
cap label var HC13 "Outpatient curative care"
cap label var HC131 "General outpatient curative care"
cap label var HC132 "Dental outpatient curative care"
cap label var HC133 "Specialised outpatient curative care"
cap label var HC139 "All other outpatient curative care n.e.c."
cap label var HC14_24 "Home-based curative and rehabilitative care"
cap label var HC14 "Home-based curative care"
cap label var HC2 "Rehabilitative care"
cap label var HC21 "Inpatient rehabilitative care"
cap label var HC22 "Day rehabilitative care"
cap label var HC23 "Outpatient rehabilitative care"
cap label var HC24 "Home-based rehabilitative care"
cap label var HC3 "Long-term care (health)"
cap label var HC31 "Inpatient long-term care (health)"
cap label var HC32 "Day long-term care (health)"
cap label var HC33 "Outpatient long-term care (health)"
cap label var HC34 "Home-based long-term care (health)"
cap label var HC4 "Ancillary services (non-specified by function)"
cap label var HC41 "Laboratory services"
cap label var HC42 "Imaging services"
cap label var HC43 "Patient transportation"
cap label var HC5 "Medical goods (non-specified by function)"
cap label var HC51 "Pharmaceuticals and other medical non-durable goods"
cap label var HC511 "Prescribed medicines"
cap label var HC512 "Over-the-counter medicines"
cap label var HC513 "Other medical non-durable goods"
cap label var HC52 "Therapeutic appliances and other medical durable goods"
cap label var HC6 "Preventive care"
cap label var HC61 "Information, education and counseling programmes"
cap label var HC62 "Immunisation programmes"
cap label var HC63 "Early disease detection programmes"
cap label var HC64 "Healthy condition monitoring programmes"
cap label var HC65 "Epidemiological surveillance and risk and disease control programmes"
cap label var HC66 "Preparing for disaster and emergency response programmes"
cap label var HC7 "Governance and health system and financing administration"
cap label var HC71 "Governance and health system administration"
cap label var HC72 "Administration of health financing"
cap label var HC9 "Other health care services not elsewhere classified (n.e.c.)"
cap label var HC_UNK "Other health care services unknown"
cap label var HCRI1 "Total pharmaceutical expenditure (TPE)"
cap label var HCRI2 "Traditional, complementary and alternative medicines (TCAM)"
cap label var HCR1 "Long-term care (social)"
cap label var HCR2 "Health promotion with multi-sectoral approach"
cap label var LTC "Long-term care (HC.3 and HCR.1)"
