cap label var HC1_9_R1 "Health care expenditure"
cap label var HC1_9 "Current health care expenditure (CHE)"
cap label var HC1 "Services of curative care"
cap label var HC11 "In-patient curative care"
cap label var HC12 "Day cases of curative care"
cap label var HC13 "Out-patient curative care"
cap label var HC14 "Services of curative home care"
cap label var HC2 "Services of rehabilitative care"
cap label var HC21 "In-patient rehabilitative care"
cap label var HC22 "Day cases of rehabilitative care"
cap label var HC23 "Out-patient rehabilitative care"
cap label var HC24 "Services of rehabilitative home care"
cap label var HC1_2 "Services of curative and rehabilitative care"
cap label var HC11_21 "Services of in-patient curative and rehabilitative care"
cap label var HC11_21_31 "In-patient care"
cap label var HC12_22 "Day cases of curative and rehabilitative care"
cap label var HC13_23 "Out-patient curative and rehabilitative care"
cap label var HC14_24 "Services of curative home and rehabilitative home care"
cap label var HC3 "Services of long-term nursing care"
cap label var HC31 "In-patient long-term nursing care"
cap label var HC32 "Day cases of long-term nursing care"
cap label var HC33 "Long-term nursing care: home care"
cap label var HC4 "Ancillary services to health care"
cap label var HC41 "Clinical laboratory"
cap label var HC42 "Diagnostic imaging"
cap label var HC43 "Patient transport and emergency rescue"
cap label var HC49 "All other miscellaneous ancillary services"
cap label var HC5 "Medical goods dispensed to out-patients"
cap label var HC51 "Pharmaceuticals and other medical non-durables"
cap label var HC52 "Therapeutic appliances and other medical durables"
cap label var HC6 "Prevention and public health services"
cap label var HC61 "Maternal and child health; family planning and counselling"
cap label var HC62 "School health services"
cap label var HC63 "Prevention of communicable diseases"
cap label var HC64 "Prevention of non-communicable diseases"
cap label var HC65 "Occupational health care"
cap label var HC69 "All other misc. public health services"
cap label var HC7 "Health administration and health insurance"
cap label var HC71 "General government administration of health"
cap label var HC72 "Health administration and health insurance: private"
cap label var HC9 "Not specified by kind"
cap label var HCR "Health-related functions"
cap label var HCR1 "Capital formation of health care provider institutions"
cap label var HCR2 "Education and training of health personnel"
cap label var HCR3 "Research and development in health"
cap label var HCR4 "Food, hygiene and drinking water control"
cap label var HCR5 "Environmental health"
cap label var HCR6 "Administration and provision of social services in kind to assist living with disease and impairment"
cap label var HCR61 "Social services of LTC (LTC other than HC.3)"
cap label var HCR7 "Administration and provision of health related cash-benefits"
cap label var HCR2_7 "Health care related goods and services"
cap label var LTC "Long term care (HC.3 and HC.R.6.1)"
cap label var TOT_PAT "Total patient"
cap label var IN "In-patient"
cap label var OUT "Out-patient"
cap label var DAY "Day patient"
