cap label var TOTAL "Total"
cap label var RES "Place of residence in the reporting country"
cap label var NRES "Place of residence outside the reporting country"
cap label var NRES_EU "Place of residence outside the reporting country but in another EU country"
cap label var NRES_EA "Place of residence outside the reporting country but in another Euro area country"
cap label var NRES_NEU "Place of residence outside the reporting country and in a non-EU country"
cap label var NRES_NEA "Place of residence outside the reporting country and in a non-Euro area country"
cap label var SAME "Place of residence unchanged"
cap label var CHG "Place of residence changed"
cap label var CHG_IN "Place of residence changed within the reporting country"
cap label var CHG_IN1 "Place of residence changed within the same NUTS1 area"
cap label var CHG_IN2 "Place of residence changed within the same NUTS2 area"
cap label var CHG_IN3 "Place of residence changed within the same NUTS3 area"
cap label var CHG_IN4 "Place of residence changed within the same NUTS4 area"
cap label var CHG_IN5 "Place of residence changed within the same NUTS5 area"
cap label var CHG_OUT3 "Place of residence changed outside the NUTS3 area"
cap label var CHG_OUT "Place of residence changed from outside the reporting country"
cap label var EUR "Europe"
cap label var BE "Belgium"
cap label var BG "Bulgaria"
cap label var CZ "Czechia"
cap label var DK "Denmark"
cap label var DE "Germany (including former GDR from 1991)"
cap label var DEW "Federal Republic of Germany (except former GDR)"
cap label var EE "Estonia"
cap label var IE "Ireland"
cap label var EL "Greece"
cap label var ES "Spain"
cap label var FR "France"
cap label var HR "Croatia"
cap label var IT "Italy"
cap label var CY "Cyprus"
cap label var LV "Latvia"
cap label var LT "Lithuania"
cap label var LU "Luxembourg"
cap label var HU "Hungary"
cap label var MT "Malta"
cap label var NL "Netherlands"
cap label var AT "Austria"
cap label var PL "Poland"
cap label var PT "Portugal"
cap label var RO "Romania"
cap label var SI "Slovenia"
cap label var SK "Slovakia"
cap label var FI "Finland"
cap label var SE "Sweden"
cap label var EU_FOR "EU-countries except reporting country"
cap label var EU_OTH "Resident in an EU country other than the country of birth / citizenship"
cap label var EFTA "European Free Trade Association"
cap label var IS "Iceland"
cap label var LI "Liechtenstein"
cap label var NO "Norway"
cap label var CH "Switzerland"
cap label var UK "United Kingdom"
cap label var MK "North Macedonia"
cap label var AL "Albania"
cap label var TR "Turkey"
cap label var AD "Andorra"
cap label var BY "Belarus"
cap label var BA "Bosnia and Herzegovina"
cap label var MD "Moldova"
cap label var RU "Russia"
cap label var SM "San Marino"
cap label var UA "Ukraine"
cap label var VA "Vatican City State"
cap label var CZ_SK "Former Czechoslovakia (before 1992) / Total components of former Czechoslovakia"
cap label var RS_ME "Former Serbia and Montenegro (before 2006) / Total components of the former Serbia and Montenegro"
cap label var EX_YU "Former Yugoslavia (before 1992) / Total components of the former republic of Yugoslavia"
cap label var EX_SU "Former Soviet Union (before 1991) / Total components of the former Soviet Union"
cap label var EX_SU_EUR "European Republics of the former Soviet Union"
cap label var EUR_C_E "Central and Eastern Europe"
cap label var AFR "Africa"
cap label var AO "Angola"
cap label var CM "Cameroon"
cap label var CF "Central African Republic"
cap label var TD "Chad"
cap label var CG "Congo"
cap label var CD "Democratic Republic of the Congo"
cap label var GQ "Equatorial Guinea"
cap label var GA "Gabon"
cap label var ST "São Tomé and Príncipe"
cap label var BI "Burundi"
cap label var KM "Comoros"
cap label var DJ "Djibouti"
cap label var ER "Eritrea"
cap label var ET "Ethiopia"
cap label var KE "Kenya"
cap label var MG "Madagascar"
cap label var MW "Malawi"
cap label var MU "Mauritius"
cap label var MZ "Mozambique"
cap label var RW "Rwanda"
cap label var SC "Seychelles"
cap label var SO "Somalia"
cap label var UG "Uganda"
cap label var TZ "Tanzania"
cap label var ZM "Zambia"
cap label var ZW "Zimbabwe"
cap label var AFR_N "Northern Africa"
cap label var DZ "Algeria"
cap label var EG "Egypt"
cap label var LY "Libya"
cap label var MA "Morocco"
cap label var SD "Sudan"
cap label var TN "Tunisia"
cap label var EH "Western Sahara"
cap label var BW "Botswana"
cap label var LS "Lesotho"
cap label var NA "Namibia"
cap label var ZA "South Africa"
cap label var SZ "Eswatini"
cap label var BJ "Benin"
cap label var BF "Burkina Faso"
cap label var CV "Cape Verde"
cap label var CI "Côte d'Ivoire"
cap label var GM "Gambia"
cap label var GH "Ghana"
cap label var GN "Guinea"
cap label var GW "Guinea-Bissau"
cap label var LR "Liberia"
cap label var ML "Mali"
cap label var MR "Mauritania"
cap label var NE "Niger"
cap label var NG "Nigeria"
cap label var SN "Senegal"
cap label var SL "Sierra Leone"
cap label var TG "Togo"
cap label var AFR_OTH "Other African countries (aggregate changing according to the context)"
cap label var AME "America"
cap label var AME_N "Northern America"
cap label var BM "Bermuda (UK)"
cap label var CA "Canada"
cap label var US "United States"
cap label var AG "Antigua and Barbuda"
cap label var BS "Bahamas"
cap label var BB "Barbados"
cap label var CU "Cuba"
cap label var DM "Dominica"
cap label var DO "Dominican Republic"
cap label var GD "Grenada"
cap label var HT "Haiti"
cap label var JM "Jamaica"
cap label var KN "Saint Kitts and Nevis"
cap label var LC "Saint Lucia"
cap label var VC "Saint Vincent and the Grenadines"
cap label var TT "Trinidad and Tobago"
cap label var BZ "Belize"
cap label var CR "Costa Rica"
cap label var SV "El Salvador"
cap label var GT "Guatemala"
cap label var HN "Honduras"
cap label var MX "Mexico"
cap label var NI "Nicaragua"
cap label var MC "Monaco"
cap label var PA "Panama"
cap label var AR "Argentina"
cap label var BO "Bolivia"
cap label var BR "Brazil"
cap label var CL "Chile"
cap label var CO "Colombia"
cap label var EC "Ecuador"
cap label var GY "Guyana"
cap label var PY "Paraguay"
cap label var PE "Peru"
cap label var SR "Suriname"
cap label var UY "Uruguay"
cap label var VE "Venezuela"
cap label var AME_OTH "Other American countries (aggregate changing according to the context)"
cap label var ASI "Asia"
cap label var KZ "Kazakhstan"
cap label var KG "Kyrgyzstan"
cap label var TJ "Tajikistan"
cap label var TM "Turkmenistan"
cap label var UZ "Uzbekistan"
cap label var CN "China (including Hong Kong)"
cap label var JP "Japan"
cap label var MN "Mongolia"
cap label var KP "North Korea"
cap label var KR "South Korea"
cap label var TW "Taiwan"
cap label var AF "Afghanistan"
cap label var BD "Bangladesh"
cap label var BT "Bhutan"
cap label var IN "India"
cap label var IR "Iran"
cap label var MV "Maldives"
cap label var NP "Nepal"
cap label var PK "Pakistan"
cap label var LK "Sri Lanka"
cap label var BN "Brunei Darussalam"
cap label var KH "Cambodia"
cap label var ID "Indonesia"
cap label var LA "Laos"
cap label var MY "Malaysia"
cap label var MM "Myanmar"
cap label var PH "Philippines"
cap label var SG "Singapore"
cap label var TH "Thailand"
cap label var TL "East Timor"
cap label var VN "Vietnam"
cap label var AM "Armenia"
cap label var AZ "Azerbaijan"
cap label var BH "Bahrain"
cap label var GE "Georgia"
cap label var IQ "Iraq"
cap label var IL "Israel"
cap label var JO "Jordan"
cap label var KW "Kuwait"
cap label var LB "Lebanon"
cap label var PS "Palestinian territory"
cap label var OM "Oman"
cap label var QA "Qatar"
cap label var SA "Saudi Arabia"
cap label var SY "Syria"
cap label var AE "United Arab Emirates"
cap label var YE "Yemen"
cap label var EX_YE "Former North Yemen (before 1990)"
cap label var EX_YD "Former South Yemen (before 1990)"
cap label var ASI_NME "Near and Middle East Asia (aggregate changing according to the context)"
cap label var EX_SU_ASI "Asian Republics of the former Soviet Union"
cap label var ASI_OTH "Other Asian countries (aggregate changing according to the context)"
cap label var OCE "Oceania"
cap label var AU "Australia"
cap label var NZ "New Zealand"
cap label var FJ "Fiji"
cap label var PG "Papua New Guinea"
cap label var SB "Solomon Islands"
cap label var VU "Vanuatu"
cap label var KI "Kiribati"
cap label var MH "Marshall Islands"
cap label var FM "Federated States of Micronesia"
cap label var NR "Nauru"
cap label var PW "Palau"
cap label var WS "Samoa"
cap label var TO "Tonga"
cap label var TV "Tuvalu"
cap label var OTH "Others"
cap label var NAP "Not applicable"
cap label var UNK "Unknown"
cap label var TOT_IN "All deaths reported in the country"
cap label var TOT_RESID "All deaths of residents in or outside their home country"
cap label var RESID_IN "Deaths of residents in their home country"
cap label var RESID_OUT "Deaths of residents outside their home country"
cap label var NRESID_IN "Deaths of non-residents in the reporting country"
