cap label var PEN "Pending"
cap label var REG "Registered"
cap label var REG_END "Registered at the end of the year"
cap label var REG_NEW "New registered during year"
cap label var REG_WDN "Registration withdrawn during year"
cap label var ERR "Absolute error"
cap label var INVPEN "Invalidity pending"
cap label var INVDEC "Declared invalid"
cap label var EXPLEG "Design legally expired"
cap label var EXPDAT "Design passed expiry date without renewal"
cap label var REGPUB "Registered and published"
cap label var REGWPUB "Registered and waiting for publication"
cap label var SURR "Surrendered"
cap label var EXAM "To be examined"
cap label var PUBDEF "Publication deferred"
cap label var PUBNDEF "Publication not deferred"
cap label var OPEN "Open application"
cap label var EXP "Expired"
cap label var CANCPEN "Cancellation pending"
cap label var CANC "Cancelled"
cap label var DEEMNF "Deemed not filed"
cap label var REF "Refused"
cap label var WDN "Withdrawn"
cap label var DEL "Deleted"
cap label var OPP "Opposed"
cap label var APPLBL "Appealable"
cap label var APP "Appealed"
