cap label var TOTAL "Total transported goods"
cap label var GT01 "Products of agriculture, hunting, and forestry; fish and other fishing products"
cap label var GT011 "Cereals"
cap label var GT012 "Potatoes"
cap label var GT013 "Sugar beet"
cap label var GT014 "Other fresh fruit and vegetables"
cap label var GT015 "Products of forestry and logging"
cap label var GT016 "Live plants and flowers"
cap label var GT017 "Other substances of vegetable origin"
cap label var GT018 "Live animals"
cap label var GT019 "Raw milk from bovine cattle, sheep and goats"
cap label var GT01A "Other raw materials of animal origin"
cap label var GT01B "Fish and other fishing products"
cap label var GT02 "Coal and lignite; crude petroleum and natural gas"
cap label var GT021 "Coal and lignite"
cap label var GT022 "Crude petroleum"
cap label var GT023 "Natural gas"
cap label var GT03 "Metal ores and other mining and quarrying products; peat; uranium and thorium"
cap label var GT031 "Iron ores"
cap label var GT032 "Non ferrous metal ores (except uranium and thorium ores)"
cap label var GT033 "Chemical and (natural) fertilizer minerals"
cap label var GT034 "Salt"
cap label var GT035 "Stone, sand, gravel, clay, peat and other mining and quarrying products n.e.c."
cap label var GT036 "Uranium and thorium ores"
cap label var GT04 "Food products, beverages and tobacco"
cap label var GT041 "Meat, raw hides and skins and meat products"
cap label var GT042 "Fish and fish products, processed and preserved"
cap label var GT043 "Fruit and vegetables, processed and preserved"
cap label var GT044 "Animal and vegetable oils and fats"
cap label var GT045 "Dairy products and ice cream"
cap label var GT046 "Grain mill products, starches, starch products and prepared animal feeds"
cap label var GT047 "Beverages"
cap label var GT048 "Other food products n.e.c. and tobacco products (except in parcel service or grouped)"
cap label var GT049 "Various food products and tobacco products in parcel service or grouped"
cap label var GT05 "Textiles and textile products; leather and leather products"
cap label var GT051 "Textiles"
cap label var GT052 "Wearing apparel and articles of fur"
cap label var GT053 "Leather and leather products"
cap label var GT06 "Wood and products of wood and cork (except furniture); articles of straw and plaiting materials; pulp, paper and paper products; printed matter and recorded media"
cap label var GT061 "Products of wood and cork (except furniture)"
cap label var GT062 "Pulp, paper and paper products"
cap label var GT063 "Printed matter and recorded media"
cap label var GT07 "Coke and refined petroleum products"
cap label var GT071 "Coke oven products; briquettes, ovoids and similar solid fuels"
cap label var GT072 "Liquid refined petroleum products"
cap label var GT073 "Gaseous, liquefied or compressed petroleum products"
cap label var GT074 "Solid or waxy refined petroleum products"
cap label var GT08 "Chemicals, chemical products, and man-made fibers; rubber and plastic products ; nuclear fuel"
cap label var GT081 "Basic mineral chemical products"
cap label var GT082 "Basic organic chemical products"
cap label var GT083 "Nitrogen compounds and fertilizers (except natural fertilizers)"
cap label var GT084 "Basic plastics and synthetic rubber in primary forms"
cap label var GT085 "Pharmaceuticals and parachemicals including pesticides and other agro-chemical products"
cap label var GT086 "Rubber or plastic products"
cap label var GT087 "Nuclear fuel"
cap label var GT09 "Other non metallic mineral products"
cap label var GT091 "Glass and glass products, ceramic and porcelain products"
cap label var GT092 "Cement, lime and plaster"
cap label var GT093 "Other construction materials, manufactures"
cap label var GT10 "Basic metals; fabricated metal products, except machinery and equipment"
cap label var GT101 "Basic iron and steel and ferro-alloys and products of the first processing of iron and steel (except tubes)"
cap label var GT102 "Non ferrous metals and products thereof"
cap label var GT103 "Tubes, pipes, hollow profiles and related fittings"
cap label var GT104 "Structural metal products"
cap label var GT105 "Boilers, hardware, weapons and other fabricated metal products"
cap label var GT11 "Machinery and equipment n.e.c.; office machinery and computers; electrical machinery and apparatus n.e.c.; radio, television and communication equipment and apparatus; medical, precision and optical instruments; watches and clocks"
cap label var GT111 "Agricultural and forestry machinery"
cap label var GT112 "Domestic appliances n.e.c. (white goods)"
cap label var GT113 "Office machinery and computers"
cap label var GT114 "Electric machinery and apparatus n.e.c."
cap label var GT115 "Electronic components and emission and transmission appliances"
cap label var GT116 "Television and radio receivers; sound or video recording or reproducing apparatus and associated goods (Brown goods)"
cap label var GT117 "Medical, precision and optical instruments, watches and clocks"
cap label var GT118 "Other machines, machine tools and parts"
cap label var GT12 "Transport equipment"
cap label var GT121 "Automobile industry products"
cap label var GT122 "Other transport equipment"
cap label var GT13 "Furniture; other manufactured goods n.e.c."
cap label var GT131 "Furniture"
cap label var GT132 "Other manufactured goods"
cap label var GT14 "Secondary raw materials; municipal wastes and other wastes"
cap label var GT141 "Household and municipal waste"
cap label var GT142 "Other waste and secondary raw materials"
cap label var GT15 "Mail, parcels"
cap label var GT151 "Mail"
cap label var GT152 "Parcels, small packages"
cap label var GT16 "Equipment and material utilized in the transport of goods"
cap label var GT161 "Containers and swap bodies in service, empty"
cap label var GT162 "Pallets and other packaging in service, empty"
cap label var GT17 "Goods moved in the course of household and office removals; baggage and articles accompanying travellers; motor vehicles being moved for repair; other non market goods n.e.c."
cap label var GT171 "Household removal"
cap label var GT172 "Baggage and articles accompanying travellers"
cap label var GT173 "Vehicles for repair"
cap label var GT174 "Plant equipment, scaffolding"
cap label var GT175 "Other non market goods n.e.c."
cap label var GT18 "Grouped goods: a mixture of types of goods which are transported together"
cap label var GT180 "Grouped goods"
cap label var GT19 "Unidentifiable goods: goods which for any reason cannot be identified and therefore cannot be assigned to groups 01-16."
cap label var GT191 "Unidentifiable goods in containers or swap bodies"
cap label var GT192 "Other unidentifiable goods"
cap label var GT20 "Other goods n.e.c."
cap label var GT200 "Other goods not elsewhere classified"
cap label var NAP "Not applicable"
cap label var UNK "Unknown"
