cap label var TOTAL "Total"
cap label var ANTQ "Antiques; postage or revenue stamps; collections and collector's pieces"
cap label var ART "Works of art (paintings, engravings, sculptures, designs, etc.)"
cap label var CRAFT "Craft (handmade fabrics and ornamental articles)"
cap label var JEWLR "Articles of jewellery (of precious and semi-precious metals and stones)"
cap label var BOOK "Books"
cap label var NWPR "Newspapers, journals and periodicals"
cap label var MAP "Maps and hydrographical or similar charts"
cap label var PLAN "Plans and drawings for architectural or other similar purposes"
cap label var PHOT "Photographic plates and film, exposed and developed"
cap label var RECMED_FILMVG_XVC "Music in manuscript, gramophone records, recorded magnetic tapes and optical media (CDs); audio-visual and interactive media (films, videos and video games excl. video game consoles)"
cap label var VG "Video games used with television receiver"
cap label var VC "Video game consoles (excl. operated by any means of payment)"
cap label var FILMVG "Audio-visual and interactive media (films, videos, video games and consoles)"
cap label var FILMVG_XVC "Audio-visual and interactive media (films, videos and video games excl. video game consoles)"
cap label var RECMED "Music in manuscript, gramophone records, recorded magnetic tapes and optical media (CDs)"
cap label var MUSI "Musical instruments; parts and accessories thereof"
