cap label var HP1_9 "All providers of health care"
cap label var HP1_3 "Hospitals and providers of ambulatory health care"
cap label var HP1 "Hospitals"
cap label var HP1_PUB "Publically owned hospital"
cap label var HP1_NPP "Not-for-profit privately owned hospital"
cap label var HP1_PP "For-profit privately owned hospital"
cap label var HP11 "General hospitals"
cap label var HP12 "Mental health and substance abuse hospitals"
cap label var HP13 "Speciality (other then mental health and substance abuse hospitals)"
cap label var HP2 "Nursing and residential care facilities"
cap label var HP21 "Nursing care facilities"
cap label var HP22 "Residential mental retardation, mental health and substance abuse facilities"
cap label var HP23 "Community care facilities for the elderly"
cap label var HP29 "All other residential care facilities"
cap label var HP3 "Providers of ambulatory health care"
cap label var HP31 "Offices of physicians"
cap label var HP32 "Offices of dentists"
cap label var HP33 "Offices of other health practitioners"
cap label var HP34 "Out-patient care centres"
cap label var HP35 "Medical and diagnostic laboratories"
cap label var HP36 "Providers of home health care services"
cap label var HP39 "Other providers of ambulatory health care"
cap label var HP4 "Retail sale and other providers of medical goods"
cap label var HP41 "Dispensing chemists"
cap label var HP42 "Retail sale and other suppliers of optical glasses and other vision products"
cap label var HP43 "Retail sale and other suppliers of hearing aids"
cap label var HP44_49 "Retail sale and other suppliers of medical appliances; All other miscellaneous sale and other suppliers of pharmaceuticals and medical goods"
cap label var HP5 "Provision and administration of public health programmes"
cap label var HP6 "General health administration and insurance"
cap label var HP61 "Government administration of health"
cap label var HP62 "Social security funds"
cap label var HP63_64 "Providers of private insurance"
cap label var HP63 "Other social insurance"
cap label var HP64 "Other (private) insurance"
cap label var HP69 "All other providers of health administration"
cap label var HP7 "Other industries (rest of the economy)"
cap label var HP71 "Establishments as providers of occupational health care services"
cap label var HP72 "Private households as providers of home care"
cap label var HP79 "All other industries as secondary producers of health care"
cap label var HP9 "Rest of the world"
cap label var HP0 "Not elsewhere classified"
