cap label var GEN "Generation of wastewater - all sources"
cap label var GEN_PS "Generation of wastewater - point sources - total"
cap label var GEN_AGR "Generation of wastewater - agriculture, forestry, fishing"
cap label var GEN_IND "Generation of wastewater - industry total"
cap label var GEN_IND_XURB "Generation of wastewater - industry except the part collected by urban wastewater collection systems"
cap label var GEN_MIN "Generation of wastewater - mining and quarrying"
cap label var GEN_MAN "Generation of wastewater - manufacturing industries"
cap label var GEN_FOOD "Generation of wastewater - foodprocessing industry"
cap label var GEN_MET "Generation of wastewater - basic metals"
cap label var GEN_TRA "Generation of wastewater - motor vehicles and transport equipment"
cap label var GEN_TEXT "Generation of wastewater - textiles"
cap label var GEN_PAP "Generation of wastewater - paper and paper products"
cap label var GEN_CHEM "Generation of wastewater - chemical products and refined petroleum"
cap label var GEN_ELC "Generation of wastewater - production and distribution of electricity (excluding cooling water)"
cap label var GEN_CON "Generation of wastewater - construction"
cap label var GEN_DOM "Generation of wastewater - domestic sources - total"
cap label var GEN_SER "Generation of wastewater - services"
cap label var GEN_HH "Generation of wastewater - private households"
cap label var GEN_NPS "Generation of wastewater - non-point sources"
cap label var GEN_URB "Urban wastewater - total generated"
cap label var TRT_IF "Urban and industrial wastewater treatment - total inflow"
cap label var TRT_URB_IF "Urban wastewater treatment in wastewater treatment plants - total inflow"
cap label var TRT_URB_GE2 "Urban wastewater treatment in wastewater treatment plants - at least secondary treatment"
cap label var TRT_IND_IF "Industrial wastewater treatment - total inflow"
cap label var TRT_IND_OTH_IF "Industrial wastewater treatment in other wastewater treatment plants - total inflow"
cap label var TRT_IND_GE2 "Industrial wastewater treatment - at least secondary treatment"
cap label var TRT_IND_OTH_GE2 "Industrial wastewater treatment in other wastewater treatment plants - at least secondary treatment"
cap label var DIS "Total discharges of wastewater treatment plants (urban and other)"
cap label var DIS_URB "Urban wastewater discharges - total"
cap label var DIS_URB_IW "Urban wastewater discharges to inland waters - total"
cap label var DIS_URB_AT "Urban wastewater discharged - after treatment"
cap label var DIS_URB_IW_AT "Urban wastewater discharges to inland waters - after treatment"
cap label var DIS_URB_AIT "Urban wastewater discharged - after independent treatment"
cap label var DIS_URB_IW_AIT "Urban wastewater discharges to inland waters - after independent treatment"
cap label var DIS_URB_NT "Urban wastewater discharged - without treatment"
cap label var DIS_URB_IW_NT "Urban wastewater discharges to inland waters - without treatment"
cap label var DIS_IND "Industrial wastewater discharges - total"
cap label var DIS_IND_IW "Industrial wastewater discharges to inland waters - total"
cap label var DIS_IND_AT "Industrial wastewater discharged - after treatment"
cap label var DIS_IND_IW_AT "Industrial wastewater discharges to inland waters - after treatment"
cap label var DIS_IND_NT "Industrial wastewater discharged - without treatment"
cap label var DIS_NT "Total wastewater discharged - without treatment"
cap label var DIS_IND_IW_NT "Industrial wastewater discharges to inland waters - without treatment"
cap label var DIS_AGR "Agricultural wastewater direct discharges (incl. forestry and fisheries)"
cap label var DIS_NPS "Direct discharges from non-point sources"
cap label var DIS_IW "Total discharges to inland waters - all sources"
cap label var DIS_SEA "Total discharges to marine waters - all sources"
