cap label var TOTAL "Total"
cap label var OGA_HLD "Holder having other gainful activities"
cap label var OGA_HLD_RH "Holder having other gainful activities (related to the agricultural holding)"
cap label var OGA_HLD_NRH "Holder having other gainful activities (not related to the agricultural holding)"
cap label var MOGA_HLD "Holder having other gainful activities as main activity"
cap label var MOGA_HLD_RH "Holder having other gainful activities (related to the agricultural holding) as main activity"
cap label var MOGA_HLD_NRH "Holder having other gainful activities (not related to the agricultural holding) as main activity"
cap label var MOGA_FAM "Family members having other gainful activities as main activity"
cap label var MOGA_FAM_RH "Family members having other gainful activities (related to the agricultural holding) as main activity"
cap label var MOGA_FAM_NRH "Family members having other gainful activities (not related to the agricultural holding) as main activity"
cap label var MOGA_NFAM_RH "Non-family labour force regularly working on the agricultural holding and having other gainful activities (related to the agricultural holding) as main activity"
cap label var SOGA_HLD "Holder having other gainful activities as secondary activity"
cap label var SOGA_HLD_RH "Holder having other gainful activities (related to the agricultural holding) as secondary activity"
cap label var SOGA_HLD_NRH "Holder having other gainful activities (not related to the agricultural holding) as secondary activity"
cap label var SOGA_FAM "Family members having other gainful activities as secondary activity"
cap label var SOGA_FAM_RH "Family members having other gainful activities (related to the agricultural holding) as secondary activity"
cap label var SOGA_FAM_NRH "Family members having other gainful activities (not related to the agricultural holding) as secondary activity"
cap label var SOGA_NFAM_RH "Non-family labour force regularly working on the agricultural holding and having other gainful activities (related to the agricultural holding) as secondary activity"
cap label var NOGA_HLD "Holder not having other gainful activities"
cap label var NOGA_HLD_RH "Holder not having other gainful activities (related to the agricultural holding)"
cap label var NOGA_HLD_NRH "Holder not having other gainful activities (not related to the agricultural holding)"
cap label var NOGA_FAM "Family members not having other gainful activities"
cap label var NOGA_FAM_RH "Family members not having other gainful activities (related to the agricultural holding)"
cap label var NOGA_FAM_NRH "Family members not having other gainful activities (not related to the agricultural holding)"
cap label var OGA_MT_HLD "Holder spending more time on other gainful activities than on his own holding"
cap label var OGA_MT_SPOU "Spouse spending more time on other gainful activities than on his own holding"
cap label var OGA_LT_HLD "Holder spending less time on other gainful activities than on his own holding"
cap label var OGA_LT_SPOU "Spouse spending less time on other gainful activities than on his own holding"
cap label var NOGA_SPOU "Spouse has no other gainful activity"
cap label var NSPOU "No spouse"
cap label var NMAN_NHLD "Sole-holder is not the manager"
cap label var LEG_GRP "Holding is a legal person or group holding"
