cap label var TOTAL "Total"
cap label var AIR "Air"
cap label var LAND "Land - total"
cap label var LAND_OTH "Other land"
cap label var RAIL_IWW_AVD "Railways, inland waterways - sum of available data"
cap label var RAIL "Railways"
cap label var ROAD "Roads"
cap label var PRV "Private cars, motorcycles, vans"
cap label var PUB "Public transport"
cap label var RDMV_PAS_X_BUS "Passenger road motor vehicles excluding buses and coaches"
cap label var PRDMV_PAS_X_BUS "Private passenger road motor vehicles excluding buses and coaches"
cap label var RRDMV_PAS_X_BUS "Rented passenger road motor vehicles excluding buses and coaches"
cap label var BUS "Buses, coaches"
cap label var BUS_REG "Buses, coaches - regular/scheduled"
cap label var BUS_OCC "Buses, coaches - occasional/non-scheduled"
cap label var CAR "Motor vehicles"
cap label var BIKE "Bicycles"
cap label var FOOT "On foot"
cap label var WW "Waterway"
cap label var SEA "Maritime"
cap label var IWW "Inland waterways"
cap label var OTH "Other"
