cap label var TOTAL "Total"
cap label var TO_FT "Transition to full-time work"
cap label var TO_PT "Transition to part-time work"
cap label var TO_EMP "Transition to employed person"
cap label var TO_NSAL "Transition to employed person except employee"
cap label var TO_UNE "Transition to unemployment"
cap label var TO_INAC "Transition to inactivity"
cap label var TO_PERM "Transition to employee with a permanent job"
cap label var TO_TEMP "Transition to employee with a temporary job"
cap label var TO_1UP "Transition to 1 income decile up"
cap label var TO_GT1UP "Transition to more than 1 income decile up"
cap label var TO_1DW "Transition to 1 income decile down"
cap label var TO_GT1DW "Transition to more than 1 income decile down"
cap label var TO_NONE "Transition to no income"
cap label var TO_GESEC "Transition to the same or higher employment security as previous year"
cap label var TO_LTSEC "Transition to less employment security than last year"
cap label var TO_GEQUA "Transition to the same or higher qualification level (employment status and pay) as previous year"
cap label var TO_LTQUA "Transition to lower qualification level (employment status and pay) than last year"
cap label var NO_CHG "No change"
