cap label var TOTAL "All enterprises (enterprise group + not enterprise group)"
cap label var EG "Enterprise group"
cap label var PEG "Part of an enterprise group"
cap label var HD_EG "Group head"
cap label var HD_EGG "Global group head"
cap label var HD_NAT "Head office of enterprise group in the country"
cap label var HD_FOR "Head office of enterprise group abroad"
cap label var ENT_EG_NAT "All enterprises of enterprise group in country"
cap label var HD_LCT "Location of Head office"
cap label var ENEWSUB_IEUR "Enterprises that have established new subsidiaries in the national country and/or European country"
cap label var ENEWSUBXEUR "Enterprises that have established new subsidiaries outside Europe"
cap label var MRG_ENT "Enterprises that have merged with/take over another enterprise"
cap label var SELL_CL_OUTSRC_TSK "Enterprises that have sold/closed/outsourced tasks or functions"
cap label var SUB "Subsidiary"
cap label var SUB_NAT "Subsidiary with global group head in own country"
cap label var SUB_EU27_2020 "Subsidiary with global group head in EU27 (from 2020)"
cap label var SUB_EU28 "Subsidiary with global group head in EU28 (2013-2020)"
cap label var SUB_EU27_2007 "Subsidiary with global group head in EU27 (2007-2013)"
cap label var SUB_XEU27_2020 "Subsidiary with global group head in extra-EU27 (from 2020)"
cap label var SUB_XEU28 "Subsidiary with global group head in extra-EU28 (2013-2020)"
cap label var SUB_XEU27_2007 "Subsidiary with global group head in extra-EU27 (2007-2013)"
cap label var NEG "Not enterprise group"
