cap label var TOTAL "Total"
cap label var VHIGH "Very high"
cap label var HIGH "High"
cap label var GOOD "Good"
cap label var FAIR "Fair"
cap label var MED "Medium"
cap label var LOW "Low"
cap label var VLOW "Very low"
cap label var NONE "None"
cap label var NAP "Not applicable"
cap label var NRP "No response"
