cap label var BB "Broadband"
cap label var BB_FX "Fixed broadband"
cap label var NGA "Next generation access"
cap label var FTTP "Fibre to the premises (FTTP)"
cap label var FTTP_DOCSIS3_0 "Fibre to the premises and data over cable service interface specification - version 3.0"
cap label var FTTP_DOCSIS3_1 "Fibre to the premises and data over cable service interface specification - version 3.1"
cap label var DOCSIS3_0 "Data over cable service interface specification - version 3.0 (DOCSIS 3.0)"
cap label var DOCSIS3_1 "Data over cable service interface specification - version 3.1 (DOCSIS 3.1)"
cap label var DSL "Digital subscriber line (DSL)"
cap label var VDSL "Very high-speed digital subscriber line (VDSL)"
cap label var VDSL2V "Very high-speed digital subscriber line 2 vectoring (VDSL2)"
cap label var FWA "Fixed wireless access"
cap label var LTE "Long-term evolution (LTE)"
cap label var LTE_AVG "Average long-term evolution (LTE)"
cap label var _5G "Fifth generation technology standard for broadband cellular networks (5G)"
cap label var SATL "Satellite"
cap label var CBL_MM "Cable modem"
cap label var WIMAX "Worldwide interoperability for microwave access (WiMAX)"
cap label var HSPA "High speed packet access (HSPA)"
cap label var VHCN_FX "Fixed very high capacity networks (VHCN)"
