cap label var CPA_TOTAL "Total"
cap label var CPA_A_B "Products of agriculture, forestry, fisheries and aquaculture"
cap label var CPA_A "Products of agriculture, hunting and forestry"
cap label var CPA_A01 "Products of agriculture, hunting and related services"
cap label var CPA_A02 "Products of forestry, logging and related services"
cap label var CPA_B "Fish and other fishing products; services incidental to fishing"
cap label var CPA_B05 "Fish and other fishing products; services incidental to fishing"
cap label var CPA_C "Products from mining and quarrying"
cap label var CPA_CA "Coal and lignite; peat; crude petroleum and natural gas; uranium and thorium"
cap label var CPA_CA10 "Coal and lignite; peat"
cap label var CPA_CA11 "Crude petroleum and natural gas; services incidental to oil and gas extraction excluding surveying"
cap label var CPA_CA12 "Uranium and thorium ores"
cap label var CPA_CB "Metal ores and other mining and quarrying products"
cap label var CPA_CB13 "Metal ores"
cap label var CPA_CB14 "Other mining and quarrying products"
cap label var CPA_D "Manufactured products"
cap label var CPA_DA "Food products, beverages and tobacco"
cap label var CPA_DA15 "Food products and beverages"
cap label var CPA_DA16 "Tobacco products"
cap label var CPA_DB "Textiles and textile products"
cap label var CPA_DB17 "Textiles"
cap label var CPA_DB18 "Wearing apparel; furs"
cap label var CPA_DC "Leather and leather products"
cap label var CPA_DC19 "Leather and leather products"
cap label var CPA_DC193 "Footwear"
cap label var CPA_DD "Wood and wood products"
cap label var CPA_DD20 "Wood and products of wood and cork (except furniture), articles of straw and plaiting materials"
cap label var CPA_DE "Pulp, paper and paper products; recorded media; printing services"
cap label var CPA_DE21 "Pulp, paper and paper products"
cap label var CPA_DE22 "Printed matter and recorded media"
cap label var CPA_DF "Coke, refined petroleum products and nuclear fuel"
cap label var CPA_DF23 "Coke, refined petroleum products and nuclear fuel"
cap label var CPA_DG "Chemicals, chemical products and man-made fibres"
cap label var CPA_DG24 "Chemicals, chemical products and man-made fibres"
cap label var CPA_DH "Rubber and plastic products"
cap label var CPA_DH25 "Rubber and plastic products"
cap label var CPA_DI "Other non metallic mineral products"
cap label var CPA_DI26 "Other non-metallic mineral products"
cap label var CPA_DI263 "Ceramic tiles and flags"
cap label var CPA_DJ "Basic metals and fabricated metal products"
cap label var CPA_DJ27 "Basic metals"
cap label var CPA_DJ28_DN36 "Metal products and machinery, transport equipment"
cap label var CPA_DJ28_DL_DN36 "Metal products and machinery"
cap label var CPA_DJ28 "Fabricated metal products, except machinery and equipment"
cap label var CPA_DK "Machinery and equipment n.e.c."
cap label var CPA_DK29 "Machinery and equipment n.e.c."
cap label var CPA_DL "Electrical and optical equipment"
cap label var CPA_DL30 "Office machinery and computers"
cap label var CPA_DL31 "Electrical machinery and apparatus n.e.c."
cap label var CPA_DL32 "Radio, television and communication equipment and apparatus"
cap label var CPA_DL33 "Medical, precision and optical instruments, watches and clocks"
cap label var CPA_DM "Transport equipment"
cap label var CPA_DM34 "Motor vehicles, trailers and semi-trailers"
cap label var CPA_DM35 "Other transport equipment"
cap label var CPA_DN "Other manufactured goods n.e.c."
cap label var CPA_DN36 "Furniture; other manufactured goods n.e.c."
cap label var CPA_DN37 "Recovered secondary raw materials"
cap label var CPA_E "Electrical energy, gas, steam and hot water"
cap label var CPA_E40 "Electrical energy, gas, steam and hot water"
cap label var CPA_E41 "Collected and purified water, distribution services of water"
cap label var CPA_F "Construction work"
cap label var CPA_F45 "Construction work"
cap label var CPA_FA "Construction work: housing"
cap label var CPA_FB "Construction work: other constructions"
cap label var CPA_G "Wholesale and retail trade services; repair services of motor vehicles, motorcycles and personal and household goods"
cap label var CPA_G50 "Trade, maintenance and repair services of motor vehicles and motorcycles; retail trade services of automotive fuel"
cap label var CPA_G503 "Trade services of motor vehicle parts and accessories"
cap label var CPA_G505 "Retail trade services of motor fuel"
cap label var CPA_G50101 "Wholesale trade services of motor vehicles- wholesale trade services of both new and second-hand vehicles"
cap label var CPA_G50102 "Retail trade services of motor vehicles"
cap label var CPA_G50103 "Sales on a fee or contract basis of motor vehicles"
cap label var CPA_G50201 "Maintenance and repair services of passenger motor cars"
cap label var CPA_G50202 "Maintenance and repair services of other motor vehicles"
cap label var CPA_G50203 "Other services related to motor vehicles"
cap label var CPA_G50301 "Wholesale trade services of parts and accessories of motor vehicles"
cap label var CPA_G50302 "Retail trade services of parts and accessories of motor vehicles"
cap label var CPA_G50303 "Sales on a fee or contract basis of parts and accessories of motor vehicles"
cap label var CPA_G50401 "Wholesale trade services of motorcycles and related parts and accessories"
cap label var CPA_G50402 "Retail trade services of motorcycles and related parts and accessories"
cap label var CPA_G50403 "Sales on a fee or contract basis of motorcycles and related parts and accessories"
cap label var CPA_G50404 "Maintenance and repair services of motorcycles"
cap label var CPA_G50501 "Retail trade services of motor fuel"
cap label var CPA_G51 "Wholesale trade and commission trade services, except of motor vehicles and motorcycles"
cap label var CPA_G511 "Sales on a fee or contract basis"
cap label var CPA_G5111 "Sales on a fee or contract basis of live animals, agricultural raw materials, textile raw materials and semi-finished goods"
cap label var CPA_G5112 "Sales on a fee or contract basis of fuels, ores, metals and industrial chemicals"
cap label var CPA_G5113 "Sales on a fee or contract basis of timber and building materials"
cap label var CPA_G5114 "Sales on a fee or contract basis of machinery, industrial equipment, ships and aircraft"
cap label var CPA_G5115 "Sales on a fee or contract basis of furniture, household goods, hardware and ironmongery"
cap label var CPA_G5116 "Sales on a fee or contract basis of textiles, clothing, footwear and leather goods"
cap label var CPA_G5117 "Sales on a fee or contract basis of food, beverages and tobacco"
cap label var CPA_G5118 "Sales on a fee or contract basis by agents specializing in particular products or ranges of products n.e.c."
cap label var CPA_G5119 "Sales on a fee or contract basis by agents specializing in a variety of goods"
cap label var CPA_G512 "Wholesale trade services of agricultural raw materials and live animals"
cap label var CPA_G5121 "Wholesale trade services of grain, seeds and animal feeds"
cap label var CPA_G5122 "Wholesale trade services of flowers and plants"
cap label var CPA_G5123 "Wholesale trade services of live animals"
cap label var CPA_G5124 "Wholesale trade services of hides, skins and leather"
cap label var CPA_G5125 "Wholesale trade services of unmanufactured tobacco"
cap label var CPA_G513 "Wholesale trade services of food, beverages and tobacco"
cap label var CPA_G5131 "Wholesale trade services of fruit and vegetables"
cap label var CPA_G5132 "Wholesale trade services of meat and meat products"
cap label var CPA_G5133 "Wholesale trade services of dairy products, eggs and edible oils and fats"
cap label var CPA_G5134 "Wholesale trade services of alcoholic and other beverages"
cap label var CPA_G5135 "Wholesale trade services of tobacco products"
cap label var CPA_G5136 "Wholesale trade services of sugar, chocolate and sugar confectionery"
cap label var CPA_G5137 "Wholesale trade services of coffee, tea, cocoa and spices"
cap label var CPA_G5138 "Wholesale trade services of other food including fish, crustaceans and molluscs"
cap label var CPA_G5139 "Wholesale trade services of food, beverages and tobacco, non-specialized"
cap label var CPA_G514 "Wholesale trade services of household goods"
cap label var CPA_G5141 "Wholesale trade services of textiles"
cap label var CPA_G5142 "Wholesale trade services of clothing and footwear"
cap label var CPA_G5143 "Wholesale trade services of electrical household appliances and radio and television goods"
cap label var CPA_G5144 "Wholesale trade services of china and glassware, wallpaper and cleaning materials"
cap label var CPA_G5145 "Wholesale trade services of perfume and cosmetics"
cap label var CPA_G5146 "Wholesale trade services of pharmaceutical goods"
cap label var CPA_G5147 "Wholesale trade services of other household goods"
cap label var CPA_G515 "Wholesale trade services of non-agricultural intermediate products and of waste and scrap"
cap label var CPA_G5151 "Wholesale trade services of solid, liquid and gaseous fuels and related products"
cap label var CPA_G5152 "Wholesale trade services of metal ores and metals"
cap label var CPA_G5153 "Wholesale trade services of wood, construction materials and sanitary equipment"
cap label var CPA_G5154 "Wholesale trade services of hardware, plumbing and heating equipment and supplies"
cap label var CPA_G5155 "Wholesale trade services of chemical products"
cap label var CPA_G5156 "Wholesale trade services of other intermediate products"
cap label var CPA_G5157 "Wholesale trade services of waste and scrap"
cap label var CPA_G518 "Wholesale trade services of machinery, equipment and supplies"
cap label var CPA_G5181 "Wholesale trade services of machine tools"
cap label var CPA_G5182 "Wholesale trade services of mining, construction and civil engineering machinery and equipment"
cap label var CPA_G5183 "Wholesale trade services of machinery for the textile industry and of sewing and knitting machines"
cap label var CPA_G5184 "Wholesale trade services of computers, computer peripheral equipment and software"
cap label var CPA_G5185 "Wholesale trade services of other office machinery and equipment"
cap label var CPA_G5186 "Wholesale trade services of other electronic parts and equipment"
cap label var CPA_G5187 "Wholesale trade services of other machinery and equipment for use in industry, trade and navigation"
cap label var CPA_G5188 "Wholesale trade services of agricultural machinery, accessories and implements, including tractors"
cap label var CPA_G519 "Other wholesale trade services"
cap label var CPA_G52 "Retail trade services, except of motor vehicles and motorcycles; repair services of personal and household goods"
cap label var CPA_G521 "Retail sale in non-specialized stores"
cap label var CPA_G52111 "Retail trade services in non-specialized stores with food, beverages or tobacco predominating"
cap label var CPA_G52121 "Other retail trade services in non-specialized stores"
cap label var CPA_G522 "Retail trade services"
cap label var CPA_G52211 "Retail trade services of fruit and vegetables"
cap label var CPA_G52221 "Retail trade services of meat (including poultry) and meat products"
cap label var CPA_G52231 "Retail trade services of fish, crustaceans and molluscs"
cap label var CPA_G52241 "Retail trade services of bread, cakes, flour confectionery and sugar confectionery"
cap label var CPA_G52251 "Retail trade services of alcoholic and other beverages"
cap label var CPA_G52261 "Retail trade services of tobacco products"
cap label var CPA_G52271 "Other retail trade services of food, in specialized stores"
cap label var CPA_G52311 "Retail trade services of pharmaceutical goods"
cap label var CPA_G52321 "Retail trade services of medical and orthopaedic goods"
cap label var CPA_G52331 "Retail trade services of cosmetic and toilet articles"
cap label var CPA_G52411 "Retail trade services of textiles and haberdashery"
cap label var CPA_G52421 "Retail trade services of clothing"
cap label var CPA_G52431 "Retail trade services of footwear and leather goods"
cap label var CPA_G52441 "Retail trade services of household furniture, lighting equipment and household articles n.e.c."
cap label var CPA_G52451 "Retail trade services of electrical household appliances"
cap label var CPA_G52452 "Retail trade services of radio and television equipment, musical instruments and records"
cap label var CPA_G52461 "Retail trade services of hardware, paints and glass"
cap label var CPA_G52471 "Retail trade services of books, newspapers and stationery"
cap label var CPA_G52481 "Specialized retail trade services of office furniture, office supplies and equipment, computers and optical and photographical equipment"
cap label var CPA_G52482 "Specialized retail trade services of watches, clocks and jewellery and of sports goods, games and toys"
cap label var CPA_G52483 "Specialized retail trade services of non-food products n.e.c."
cap label var CPA_G52501 "Retail trade services of second-hand goods in stores"
cap label var CPA_G52611 "Retail trade services via mail order houses"
cap label var CPA_G52621 "Retail trade services in stalls and markets"
cap label var CPA_G52631 "Other non-store retail trade services"
cap label var CPA_G52711 "Repair services of boots, shoes and other articles of leather"
cap label var CPA_G52721 "Repair services of electrical household goods"
cap label var CPA_G52731 "Repair services of watches, clocks and jewellery"
cap label var CPA_G52741 "Repair services of other personal and household goods"
cap label var CPA_H "Hotel and restaurant services"
cap label var CPA_H55 "Hotel and restaurant services"
cap label var CPA_I "Transport, storage and communication services"
cap label var CPA_I60 "Land transport and transport via pipeline services"
cap label var CPA_I61 "Water transport services"
cap label var CPA_I62 "Air transport services"
cap label var CPA_I63 "Supporting and auxiliary transport services; travel agency services"
cap label var CPA_I64 "Post and telecommunication services"
cap label var CPA_J "Financial intermediation services"
cap label var CPA_J65 "Financial intermediation services, except insurance and pension funding services"
cap label var CPA_J651 "Monetary intermediation services"
cap label var CPA_J6511 "Central banking services"
cap label var CPA_J6512 "Other monetary intermediation services"
cap label var CPA_J6512A "Deposit taking services"
cap label var CPA_J6512AA "Inter-industry deposit taking services"
cap label var CPA_J6512AB "Standardised deposit taking services"
cap label var CPA_J6512AC "Non-standardised deposit taking services"
cap label var CPA_J6512B "Credit granting services"
cap label var CPA_J6512BA "Inter-industry credit granting services"
cap label var CPA_J6512BB "Consumer credit granting services"
cap label var CPA_J6512BC "Mortgage credit granting services"
cap label var CPA_J6512BD "Commercial credit granting services"
cap label var CPA_J6512BE "Other credit granting services n.e.c"
cap label var CPA_J6512C "Other monetary intermediation services n.e.c."
cap label var CPA_J652 "Other financial intermediation services"
cap label var CPA_J6521 "Financial leasing services"
cap label var CPA_J6522 "Other credit granting services"
cap label var CPA_J6522A "Inter-industry credit granting services"
cap label var CPA_J6522B "Consumer credit granting services"
cap label var CPA_J6522C "Mortgage credit granting services"
cap label var CPA_J6522D "Commercial credit granting services"
cap label var CPA_J6522E "Other credit granting services n.e.c."
cap label var CPA_J6523 "Other financial intermediation services n.e.c., other than insurance and pension funding services"
cap label var CPA_J6523A "Investment banking services"
cap label var CPA_J6523B "Other financial intermediation services n.e.c"
cap label var CPA_J66 "Insurance and pension funding services, except compulsory social security services"
cap label var CPA_J660 "Insurance and pension funding services, except compulsory social security services"
cap label var CPA_J6601 "Life insurance services"
cap label var CPA_J66011 "Life insurance services"
cap label var CPA_J660111 "Life insurance services"
cap label var CPA_J660111A "Non linked life insurance services"
cap label var CPA_J660111AA "Insurance products accumulating capital, producing a capital sum"
cap label var CPA_J660111AB "Insurance products accumulating capital, producing an annuity"
cap label var CPA_J660111AC "Term insurance products, producing an annuity"
cap label var CPA_J660111AD "Term insurance products, producing a capital sum"
cap label var CPA_J660111B "Linked life insurance services"
cap label var CPA_J660111C "Tontine insurance services"
cap label var CPA_J660111D "Capital redemption insurance services"
cap label var CPA_J660111E "Other life insurance services"
cap label var CPA_J660112 "Reinsurance services related to life insurance services"
cap label var CPA_J6602 "Pension funding services"
cap label var CPA_J66021 "Pension funding services"
cap label var CPA_J660211 "Pension funding services"
cap label var CPA_J660212 "Reinsurance services related to pension funding"
cap label var CPA_J6603 "Non-life insurance services"
cap label var CPA_J66031 "Accident and health insurance services"
cap label var CPA_J660311 "Accident insurance services"
cap label var CPA_J660312 "Health insurance services"
cap label var CPA_J660313 "Permanent health insurance services"
cap label var CPA_J66032 "Motor vehicle insurance services"
cap label var CPA_J660321 "Motor vehicle insurance services, third party liability"
cap label var CPA_J660322 "Other motor vehicle insurance services"
cap label var CPA_J66033 "Transport and freight insurance services"
cap label var CPA_J660331 "Marine, aviation and transport insurance services"
cap label var CPA_J660332 "Freight insurance services"
cap label var CPA_J66034 "Fire and other damage to property insurance services"
cap label var CPA_J660340 "Fire and other damage to property insurance services"
cap label var CPA_J66035 "General liability insurance services"
cap label var CPA_J660350 "General liability insurance services"
cap label var CPA_J66036 "Credit and suretyship insurance services"
cap label var CPA_J660360 "Credit and suretyship insurance services"
cap label var CPA_J66037 "Assistance, legal expenses and financial loss insurance services"
cap label var CPA_J660371 "Assistance insurance services"
cap label var CPA_J660372 "Legal expenses insurance services"
cap label var CPA_J660373 "Miscellaneous financial loss insurance services"
cap label var CPA_J66038 "Other non life insurance services"
cap label var CPA_J660380 "Other non life insurance services"
cap label var CPA_J66039 "Reinsurance services related to non life insurance"
cap label var CPA_J660390 "Reinsurance services related to non life insurance"
cap label var CPA_J67 "Services auxiliary to financial intermediation"
cap label var CPA_J671 "Services auxiliary to financial intermediation, except to insurance and pension funding"
cap label var CPA_J6711 "Financial markets administration services"
cap label var CPA_J67111 "Financial markets administration services"
cap label var CPA_J671110 "Financial markets administration services"
cap label var CPA_J6712 "Security broking and fund management services"
cap label var CPA_J67121 "Security broking and fund management services"
cap label var CPA_J671210 "Security broking and fund management services"
cap label var CPA_J6712A "Security brokerage services"
cap label var CPA_J6712B "Fund management services"
cap label var CPA_J6713 "Other services auxiliary to financial intermediation n.e.c."
cap label var CPA_J67131 "Other services auxiliary to financial intermediation n.e.c."
cap label var CPA_J671310 "Other services auxiliary to financial intermediation n.e.c."
cap label var CPA_J672 "Services auxiliary to insurance and pension funding"
cap label var CPA_J6720 "Services auxiliary to insurance and pension funding"
cap label var CPA_J67201 "Services auxiliary to insurance and pension funding"
cap label var CPA_J672010 "Services auxiliary to insurance and pension funding"
cap label var CPA_J67202 "Insurance brokerage and agency services"
cap label var CPA_J672020 "Insurance brokerage and agency services"
cap label var CPA_J672A "Brokerage services"
cap label var CPA_J672B "Other services auxiliary to insurance and pension funding n.e.c."
cap label var CPA_K "Real estate, renting and business services"
cap label var CPA_K70 "Real estate services"
cap label var CPA_K71 "Renting services of machinery and equipment without operator and of personal and household goods"
cap label var CPA_K72 "Computer and related services"
cap label var CPA_K73 "Research and development services"
cap label var CPA_K74 "Other business services"
cap label var CPA_L "Public administration and defence services, compulsory social security services"
cap label var CPA_L75 "Public administration and defence services; compulsory social security services"
cap label var CPA_M "Education services"
cap label var CPA_M80 "Education services"
cap label var CPA_N "Health and social services"
cap label var CPA_N85 "Health and social work services"
cap label var CPA_O "Other community, social and personal services"
cap label var CPA_O90 "Sewage and refuse disposal services, sanitation and similar services"
cap label var CPA_O91 "Membership organisation services n.e.c."
cap label var CPA_O92 "Recreational, cultural and sporting services"
cap label var CPA_O93 "Other services"
cap label var CPA_P "Private households with employed persons"
cap label var CPA_P95 "Private households with employed persons"
cap label var CPA_Q "Services provided by extra-territorial organisations and bodies"
cap label var CPA_Q99 "Services provided by extra-territorial organisations and bodies"
cap label var CPA_OTH "Other products"
cap label var TOT_HH "All CPA products plus direct emissions by private households"
cap label var HH "Direct emissions by private households"
cap label var V12110 "Turnover or gross premiums written"
