cap label var TOTAL "Total"
cap label var PRES "Presence recorded"
cap label var HW_MNL_OSELF "Hours worked recorded manually by one-self"
cap label var HW_MNL_SVIS "Hours worked recorded manually by supervisor/colleague"
cap label var HW_ATM "Hours worked recorded automatically"
cap label var HW_OTH "Hours worked recorded with another method"
cap label var NONE "None"
cap label var NAP "Not applicable"
cap label var NRP "No response"
