cap label var TOTAL "Total"
cap label var AC0 "Personal care"
cap label var AC0A "Personal care except eating"
cap label var AC01 "Sleep"
cap label var AC02 "Eating"
cap label var AC03 "Other and/or unspecified personal care"
cap label var AC1_2_TR "Work and study"
cap label var AC1_TR "Employment, related activities and travel as part of/during main and second job"
cap label var AC1A "Main and second job and related travel"
cap label var AC1B "Activities related to employment and unspecified employment"
cap label var AC2 "Study"
cap label var AC21A "School and university except homework"
cap label var AC212 "Homework"
cap label var AC22 "Free time study"
cap label var AC3_X_38 "Household and family care, except childcare"
cap label var AC3 "Household and family care"
cap label var AC3_TR "Household and family care and related travel"
cap label var AC31A "Food management except dish washing"
cap label var AC313 "Dish washing"
cap label var AC321 "Cleaning dwelling"
cap label var AC32A "Household upkeep except cleaning dwelling"
cap label var AC331 "Laundry"
cap label var AC332 "Ironing"
cap label var AC33A "Handicraft and producing textiles and other care for textiles"
cap label var AC34A "Gardening; other pet care"
cap label var AC342 "Tending domestic animals"
cap label var AC343 "Caring for pets"
cap label var AC344 "Walking the dog"
cap label var AC35 "Construction and repairs"
cap label var AC36 "Shopping and services"
cap label var AC38 "Childcare, including teaching, reading and talking with child"
cap label var AC38A "Childcare, except teaching, reading and talking"
cap label var AC38B "Teaching, reading and talking with child"
cap label var AC37_39 "Household management and help family member"
cap label var AC4_8 "Leisure, social and associative life"
cap label var AC4_8A "Leisure, social and associative life except TV and video"
cap label var AC41 "Organisational work"
cap label var AC41A "Formal volontary activities"
cap label var AC42 "Informal help to other households"
cap label var AC42A "Informal volontary activities"
cap label var AC43 "Participatory activities"
cap label var AC43A "Active citizenship"
cap label var AC511 "Socialising with family"
cap label var AC51A "Visiting and feasts"
cap label var AC51B "Other social life"
cap label var AC52 "Entertainment and culture"
cap label var AC52A "Cultural activities (cinema, live performances or cultural sites)"
cap label var AC521 "Cinema"
cap label var AC522 "Theatre and concerts"
cap label var AC522A "Live performances (theatre, concerts, ballet)"
cap label var AC523H "Cultural sites (historical monuments, museums, art galleries or archaeological sites)"
cap label var AC525 "Sports events"
cap label var AC53 "Resting"
cap label var AC611 "Walking and hiking"
cap label var AC6A "Sports and outdoor activities except walking and hiking"
cap label var AC733 "Computer games"
cap label var AC7A "Computing"
cap label var AC7B "Hobbies and games except computing and computer games"
cap label var AC81 "Reading"
cap label var AC812 "Reading books"
cap label var AC811 "Reading, except books"
cap label var AC82 "TV and video"
cap label var AC83 "Radio and music"
cap label var AC4_8NSP "Unspecified leisure"
cap label var AC9A "Travel except travel related to jobs"
cap label var AC913 "Travel to/from work"
cap label var AC9B "Travel related to study"
cap label var AC936 "Travel related to shopping and services"
cap label var AC938 "Transporting a child"
cap label var AC9C "Travel related to other household purposes"
cap label var AC9D "Travel related to leisure, social and associative life"
cap label var AC90NSP "Unspecified travel"
cap label var AC99NSP "Unspecified time use"
cap label var AC9E "Travel to/from work/study"
cap label var NSP "Unspecified time use and travel"
cap label var AC_PNP_MAIN "Paid and unpaid productive main activities"
cap label var AC_NP_MAIN "Productive unpaid main activities"
cap label var AC_NP_SEC "Productive unpaid secondary activities"
