cap label var TOTAL "Total"
cap label var PAS "Passenger aircraft"
cap label var PAS_ST_LE50 "Passenger aircraft with 50 or less seats"
cap label var PAS_ST51_150 "Passenger aircraft with 51 to 150 seats"
cap label var PAS_ST151_250 "Passenger aircraft with 151 to 250 seats"
cap label var PAS_ST_GT250 "Passenger aircraft with more than 250 seats"
cap label var CARGO "Cargo aircraft"
cap label var CARGO_LBS_LT100000 "Cargo aircraft with a maximum take-off weight of less than 100 000 lbs"
cap label var CARGO_LBS_GT100000 "Cargo aircraft with a maximum take-off weight of over 100 000 lbs"
cap label var SPE_AMB_BSN "Special purpose, ambulance and business aircraft"
cap label var SPE_AMB "Special purpose and ambulance aircraft"
cap label var BSN_CRP_EXE "Business, corporate and executive aircraft"
cap label var COMBI "Combi aircraft"
cap label var QUICK "Quick change aircraft"
cap label var OTH "Other"
