cap label var TOTALNOREROUTE "Total receipts"
cap label var SOC_CONTRIBNOREROUTE "Social contribution"
cap label var SEMPLOYER "Employers' social contribution"
cap label var SEACTUAL "Actual employers' social contribution"
cap label var SEIMPUTED "Imputed employers' social contribution"
cap label var SPROT_PERS "Social contribution paid by the protected persons"
cap label var SPEMPLOY "Social contribution paid by the employees"
cap label var SPSELF "Social contribution paid by the self-employed"
cap label var SP_OTH "Social contribution paid by pensioners and other protected persons"
cap label var SREROUTED "Rerouted social contributionbetween schemes"
cap label var GG_CONTRIB "General government contributions"
cap label var GEARLYMARK "Earmarked taxes"
cap label var GGENREV "General revenue"
cap label var TRANSFER "Transfers from other schemes"
cap label var REC_OTH "Other receipts"
cap label var R_OTH_PROP "Property income"
cap label var R_OTH_OTH "Miscellaneous other receipts"
cap label var TOTAL "Total receipts including transactions between schemes"
cap label var SOC_CONTRIB "Social contribution including transactions between schemes"
