cap label var TOTAL "Total"
cap label var _0 "No active persons"
cap label var _1 "1 active person"
cap label var _2 "2 active persons"
cap label var _3 "3 active persons"
cap label var GE3 "3 active persons or more"
cap label var _4 "4 active persons"
cap label var _5 "5 active persons"
cap label var GT5 "More than 5 active persons"
cap label var UNK "Unknown"
