cap label var TOTAL "Total"
cap label var CF "Combustible fuels"
cap label var CF_R "Combustible fuels - renewable"
cap label var CF_NR "Combustible fuels - non-renewable"
cap label var CF_NR_OTH "Combustible fuels - non-renewable - other"
cap label var FF "Fossil fuels"
cap label var SFF_P1000 "Solid fossil fuels and peat"
cap label var SFF_P1000_S2000 "Solid fossil fuels, peat, peat products, oil shale and oil sands"
cap label var C0000 "Coal and manufactured gases"
cap label var C0000X0350_0370 "Solid fossil fuels"
cap label var C0100 "Hard coal"
cap label var C0110 "Anthracite"
cap label var C0120 "Bituminous coal"
cap label var C0121 "Coking coal"
cap label var C0129 "Other bituminous coal"
cap label var C0200 "Brown coal"
cap label var C0210 "Sub-bituminous coal"
cap label var C0220 "Lignite"
cap label var C0300 "Coal products"
cap label var C0310 "Coal coke"
cap label var C0311 "Coke oven coke"
cap label var C0312 "Gas coke"
cap label var C0313 "Coke breeze"
cap label var C0314 "Semi cokes"
cap label var C0320 "Patent fuel"
cap label var C0330 "Brown coal briquettes"
cap label var C0340 "Coal tar"
cap label var C0350_0370 "Manufactured gases"
cap label var C0350 "Coke oven gas"
cap label var C0360 "Gas works gas"
cap label var C0370 "Recovered gases"
cap label var C0371 "Blast furnace gas"
cap label var C0372 "Basic oxygen steel furnace gas"
cap label var C0379 "Other recovered gases"
cap label var C0390 "Other coal products"
cap label var P1000 "Peat and peat products"
cap label var P1100 "Peat"
cap label var P1110 "Sod peat"
cap label var P1120 "Milled peat"
cap label var P1200 "Peat products"
cap label var P1210 "Peat briquettes"
cap label var P1290 "Other peat products"
cap label var S2000 "Oil shale and oil sands"
cap label var SFF_OTH "Other solid fossil fuels"
cap label var G3000_C0350_370 "Gas"
cap label var G3000_C0360 "Natural gas and gas work gas"
cap label var G3000 "Natural gas"
cap label var G3100 "Compressed natural gas"
cap label var G3200 "Liquefied natural gas"
cap label var O4000 "Oil and petroleum products"
cap label var O4000XBIO "Oil and petroleum products (excluding biofuel portion)"
cap label var O4100_TOT_4200_4500 "Crude oil, NGL, refinery feedstocks, additives and oxygenates and other hydrocarbons"
cap label var O4100_TOT_4200_4500XBIO "Crude oil, NGL, refinery feedstocks, additives and oxygenates and other hydrocarbons (excluding biofuel portion)"
cap label var O4100_TOT "Crude oil"
cap label var O4100 "Conventional crude oil"
cap label var NO4100 "Unconventional crude oil"
cap label var O4200 "Natural gas liquids"
cap label var O4300 "Refinery feedstocks"
cap label var O4400X4410 "Additives and oxygenates (excluding biofuel portion)"
cap label var O4400 "Additives and oxygenates"
cap label var O4410 "Biofuels for blending"
cap label var O4500 "Other hydrocarbons"
cap label var O4110_4300_4500 "Other primary oil products"
cap label var O4200_4500 "Other primary oil"
cap label var O4600 "Oil products"
cap label var O4600XBIO "Oil products (excluding biofuel portion)"
cap label var O4610 "Refinery gas"
cap label var O4620 "Ethane"
cap label var O4630 "Liquefied petroleum gases"
cap label var O4640 "Naphtha"
cap label var O4650 "Gasolines"
cap label var O4651 "Aviation gasoline"
cap label var O4652 "Motor gasoline"
cap label var O4652XR5210B "Motor gasoline (excluding biofuel portion)"
cap label var O4653 "Gasoline-type jet fuel"
cap label var O4660 "Kerosenes"
cap label var O4661 "Kerosene-type jet fuel"
cap label var O4661XR5230B "Kerosene-type jet fuel (excluding biofuel portion)"
cap label var O4669 "Other kerosene"
cap label var O4670 "Gas oil and diesel oil and heavy gas oil"
cap label var O4671 "Gas oil and diesel oil"
cap label var O4671XR5220B "Gas oil and diesel oil (excluding biofuel portion)"
cap label var O46711 "Road diesel"
cap label var O46712 "Heating and other gasoil"
cap label var O4672 "Heavy gas oil"
cap label var O4680 "Fuel oil"
cap label var O4681 "Fuel oil (low sulphur <1%)"
cap label var O4682 "Fuel oil (high sulphur >=1%)"
cap label var O4690 "Other oil products"
cap label var O4690XO4694 "Other oil products (excluding petroleum coke portion)"
cap label var O4691 "White spirit and special boiling point industrial spirits"
cap label var O4692 "Lubricants"
cap label var O4693 "Paraffin waxes"
cap label var O4694 "Petroleum coke"
cap label var O4695 "Bitumen"
cap label var O4699 "Other oil products n.e.c."
cap label var ROIL "Refined oil products"
cap label var PP_OTH "Other petroleum products"
cap label var RA000 "Renewables and biofuels"
cap label var RA010 "Renewables and biofuels - statistical transfers, joint projects and joint support schemes - added amount"
cap label var RA020 "Renewables and biofuels - statistical transfers, joint projects and joint support schemes - deduced amount"
cap label var RA100 "Hydro"
cap label var RA110 "Pure hydro power"
cap label var RA110ROR "Run-of-river hydro power"
cap label var RA120 "Mixed hydro power"
cap label var RA120P "Mixed hydro power - pumping"
cap label var RA130 "Pumped hydro power"
cap label var RA200 "Geothermal"
cap label var RA300 "Wind"
cap label var RA310 "Wind on shore"
cap label var RA320 "Wind off shore"
cap label var RA400 "Solar"
cap label var RA410 "Solar thermal"
cap label var RA420 "Solar photovoltaic"
cap label var RA420KW_LT20 "Solar photovoltaic (< 20 kW)"
cap label var RA420KW20_1000 "Solar photovoltaic (20 kW - 1000 kW)"
cap label var RA420MW_GT1 "Solar photovoltaic (1+ MW)"
cap label var RA420OG "Solar photovoltaic (Off grid)"
cap label var RA500 "Tide, wave, ocean"
cap label var RA600 "Ambient heat (heat pumps)"
cap label var RA610 "Geothermal heat pumps"
cap label var RA620 "Aerothermal and hydrothermal heat pumps"
cap label var RA700 "Renewable cooling"
cap label var R5000 "Biofuels"
cap label var R5100 "Solid biofuels"
cap label var R5100F "Solid biofuels - co-firing"
cap label var R5101 "Primary biomass - from forest"
cap label var R5102 "Branches and tree tops"
cap label var R5103 "Stumps"
cap label var R5104 "Roundwood"
cap label var R5105 "Industrial roundwood"
cap label var R5106 "Fuelwood"
cap label var R5107 "Forest-based industry co-products"
cap label var R5108 "Bark"
cap label var R5109 "Chips, sawdust and other wood particles"
cap label var R5110_5150_W6000RI "Primary solid biofuels"
cap label var R5110_5150_W6000RIS "Sustainable primary solid biofuels"
cap label var R5110 "Fuelwood, wood residues and byproducts"
cap label var R5111 "Wood pellets"
cap label var R5112 "Post-consumer wood"
cap label var R5113 "Processed wood-based fuel, produced - from feedstocks"
cap label var R5119 "Other fuelwood, wood residues and byproducts"
cap label var R5120 "Bagasse"
cap label var R5130 "Animal waste"
cap label var R5140 "Black liquor"
cap label var R5150 "Other vegetal material and residues"
cap label var R5151 "Agricultural biomass"
cap label var R5152 "Energy crops for electricity or heat (including short rotation coppice)"
cap label var R5153 "Energy crops for electricity or heat - from food and feed feedstocks"
cap label var R5154 "Agricultural crop residues for electricity or heat"
cap label var W6000RI "Renewable fraction of industrial waste"
cap label var R5160 "Charcoal"
cap label var R5200 "Liquid biofuels"
cap label var R5210 "Biogasoline"
cap label var R5210P "Pure biogasoline"
cap label var R5210B "Blended biogasoline"
cap label var R5210E "Bioethanol"
cap label var R5220 "Biodiesels"
cap label var R5220P "Pure biodiesels"
cap label var R5220B "Blended biodiesels"
cap label var R5230 "Bio jet kerosene"
cap label var R5230P "Pure bio jet kerosene"
cap label var R5230B "Blended bio jet kerosene"
cap label var R5250S "Sustainable biofuels"
cap label var R5251S "Sustainable biofuels Annex IX"
cap label var R5252S "Sustainable biofuels Annex IX, Part A"
cap label var R5253S "Sustainable biofuels Annex IX, Part A (a) - from algae"
cap label var R5254S "Sustainable biofuels Annex IX, Part A (b) - from biomass in mixed municipal waste"
cap label var R5255S "Sustainable biofuels Annex IX, Part A (c) - from biowaste"
cap label var R5256S "Sustainable biofuels Annex IX, Part A (d) - from biomass in industrial waste"
cap label var R5257S "Sustainable biofuels Annex IX, Part A (e) - from straw"
cap label var R5258S "Sustainable biofuels Annex IX, Part A (f) - from animal manure and sewage sludge"
cap label var R5259S "Sustainable biofuels Annex IX, Part A (g) - from palm oil effluent and empty palm fruit bunches"
cap label var R5260S "Sustainable biofuels Annex IX, Part A (h) - from tall oil pitch"
cap label var R5261S "Sustainable biofuels Annex IX, Part A (i) - from crude glycerine"
cap label var R5262S "Sustainable biofuels Annex IX, Part A (j) - from bagasse"
cap label var R5263S "Sustainable biofuels Annex IX, Part A (k) - from grape marcs and wine lees"
cap label var R5264S "Sustainable biofuels Annex IX, Part A (l) - from nut shells"
cap label var R5265S "Sustainable biofuels Annex IX, Part A (m) - from husks"
cap label var R5266S "Sustainable biofuels Annex IX, Part A (n) - from cobs cleaned of kernels of corn"
cap label var R5267S "Sustainable biofuels Annex IX, Part A (o) - from biomass fraction of wastes and residues from forestry and forest-based industries"
cap label var R5268S "Sustainable biofuels Annex IX, Part A (p) - from other non-food cellulosic material - article 2 second paragraph point (s)"
cap label var R5269S "Sustainable biofuels Annex IX, Part A (q) - from other ligno-cellulosic material - article 2 second paragraph point (r) except saw logs and veneer logs"
cap label var R5270S "Sustainable biofuels Annex IX, Part A (r) - from renewable liquid and gaseous transport fuels of non-biological origin"
cap label var R5271S "Sustainable biofuels Annex IX, Part A (s) - from carbon capture and utilisation for transport purposes, if the energy source is renewable - article 2 second paragraph point (a)"
cap label var R5272S "Sustainable biofuels Annex IX, Part A (t) - from bacteria, if the energy source is renewable - article 2 second paragraph point (a)"
cap label var R5273S "Sustainable biofuels Annex IX, Part B"
cap label var R5274S "Sustainable biofuels Annex IX, Part B (a) - from used cooking oil"
cap label var R5275S "Sustainable biofuels Annex IX, Part B (b) - from animal fats classified as categories 1 and 2 (Regulation (EC) No 1069/2009)"
cap label var R5276S "Sustainable biofuels 3(4)d first paragraph - from cereal and other starch-rich crops, sugars and oil crops and from crops grown as main crops primarily for energy purposes on agricultural land"
cap label var R5277S "Sustainable biofuels 3(4)d third paragraph, subsection (i) and (ii)"
cap label var R5278S "Sustainable biofuels - other"
cap label var R5279S "Grandfathered biofuels"
cap label var R5280S "Sustainable biofuels from food and feed crops"
cap label var R5281S "Sustainable biofuels from food and feed crops - non-high indirect land use change-risk"
cap label var R5290 "Other liquid biofuels"
cap label var R5292 "Bioliquids"
cap label var R5292P "Pure bioliquids"
cap label var R5292B "Blended bioliquids (only bio-part)"
cap label var R5292S "Sustainable bioliquids"
cap label var R5292SP "Sustainable pure bioliquids"
cap label var R5292SB "Sustainable blended bioliquids (only bio-part)"
cap label var R5293S "Sustainable bioliquids from non-food sources"
cap label var R5293SP "Sustainable pure bioliquids from non-food sources"
cap label var R5293SB "Sustainable blended bioliquids (only bio-part) from non-food sources"
cap label var R5294S "Sustainable bioliquids from food and feed crops"
cap label var R5294SP "Sustainable pure bioliquids from food and feed crops"
cap label var R5294SB "Sustainable blended bioliquids (only bio-part) from food and feed crops"
cap label var R5295S "Sustainable bioliquids from food and feed crops - from non-high indirect land use change-risk"
cap label var R5295SP "Sustainable pure bioliquids from food and feed crops - from non-high indirect land use change-risk"
cap label var R5295SB "Sustainable blended bioliquids (only bio-part) from food and feed crops - from non-high indirect land use change-risk"
cap label var R5300 "Biogases"
cap label var R5300B "Blended biogases"
cap label var R5300S "Sustainable biogases"
cap label var R5300SB "Sustainable blended biogases"
cap label var R5301SB "Biogases in the grid allocated based on sustainability certificates"
cap label var R5310 "Biogases from anaerobic fermentation"
cap label var R5311 "Landfill gas"
cap label var R5312 "Sewage sludge gas"
cap label var R5319 "Other biogases from anaerobic fermentation"
cap label var R5320 "Biogases from thermal processes"
cap label var RA500_5160 "Other renewable energies"
cap label var W6000 "Waste"
cap label var W6100 "Industrial waste (non-renewable)"
cap label var W6100F "Industrial waste (non-renewable) - co-firing"
cap label var W6200 "Municipal waste"
cap label var W6200F "Municipal waste - co-firing"
cap label var W6205 "Organic waste biomass"
cap label var W6210 "Renewable municipal waste"
cap label var W6210F "Renewable municipal waste - co-firing"
cap label var W6220 "Non-renewable municipal waste"
cap label var W6220F "Non-renewable municipal waste - co-firing"
cap label var W6100_6220 "Non-renewable waste"
cap label var W6230 "Waste sludges"
cap label var N9000 "Nuclear fuels and other fuels n.e.c."
cap label var N900H "Nuclear heat"
cap label var N9100 "Uranium, plutonium and thorium"
cap label var N9110 "Uranium and thorium ores"
cap label var N9190 "Other uranium, plutonium and thorium"
cap label var N9200 "Other nuclear fuels"
cap label var E7000 "Electricity"
cap label var E7100 "Electricity - renewable"
cap label var E7200 "Electricity - non-renewable"
cap label var H8000 "Heat"
cap label var H8200 "Waste heat and cold"
cap label var X9900R "Other fuels n.e.c. - renewable"
cap label var X9900NR "Other fuels n.e.c. - non-renewable"
cap label var X9900H "Other fuels n.e.c. - heat from chemical sources"
cap label var X9900 "Other fuels n.e.c."
cap label var BIOE "Bioenergy"
cap label var FE "Fossil energy"
cap label var RHYD "Hydrogen of renewable origin"
cap label var RSYNF "Synthetic fuels of renewable origin"
cap label var RCF "Recycled carbon fuels"
