cap label var TOTAL "Total"
cap label var SSS "Short Sea Shipping"
cap label var DSS "Deep Sea Shipping"
cap label var EUR "Europe"
cap label var EU27_2020 "European Union - 27 countries (from 2020)"
cap label var EU28 "European Union - 28 countries (2013-2020)"
cap label var BE "Belgium"
cap label var BG "Bulgaria"
cap label var CZ "Czechia"
cap label var DK "Denmark"
cap label var DE "Germany"
cap label var DE_1 "Germany: North Sea"
cap label var DE_2 "Germany: Baltic Sea"
cap label var DE_3 "Germany: Rhine"
cap label var DE_9 "Germany: unspecified maritime coastal area"
cap label var EE "Estonia"
cap label var IE "Ireland"
cap label var EL "Greece"
cap label var ES "Spain"
cap label var ES_1 "Spain: North Atlantic"
cap label var ES_2 "Spain: Mediterranean and South Atlantic"
cap label var ES_3 "Spain: Ceuta"
cap label var ES_4 "Spain: Melilla"
cap label var ES_5 "Spain: Ceuta and Melilla"
cap label var ES_9 "Spain: unspecified maritime coastal area"
cap label var FR "France"
cap label var FR_1 "France: Atlantic / North Sea"
cap label var FR_2 "France: Mediterranean"
cap label var FR_3 "France: Guyane"
cap label var FR_4 "France: Guadeloupe and Martinique"
cap label var FR_5 "France: Réunion"
cap label var FR_6 "France: Mayotte"
cap label var FR_9 "France: unspecified maritime coastal area"
cap label var YT "Mayotte (FR - part of EU as of 01.01.2014)"
cap label var HR "Croatia"
cap label var IT "Italy"
cap label var CY "Cyprus"
cap label var LV "Latvia"
cap label var LT "Lithuania"
cap label var LU "Luxembourg"
cap label var HU "Hungary"
cap label var MT "Malta"
cap label var NL "Netherlands"
cap label var AT "Austria"
cap label var PL "Poland"
cap label var PT "Portugal"
cap label var RO "Romania"
cap label var SI "Slovenia"
cap label var SK "Slovakia"
cap label var FI "Finland"
cap label var SE "Sweden"
cap label var SE_1 "Sweden: Baltic Sea"
cap label var SE_2 "Sweden: North Sea"
cap label var SE_9 "Sweden: unspecified maritime coastal area"
cap label var IS "Iceland"
cap label var LI "Liechtenstein"
cap label var NO "Norway"
cap label var CH "Switzerland"
cap label var UK "United Kingdom"
cap label var UK_1 "United Kingdom: Great Britain and Northern Ireland"
cap label var UK_2 "United Kingdom: Isle of Man"
cap label var UK_3 "United Kingdom: Guernsey and Jersey (Channel Islands)"
cap label var UK_9 "United Kingdom: unspecified maritime coastal area"
cap label var ME "Montenegro"
cap label var MK "North Macedonia"
cap label var AL "Albania"
cap label var RS "Serbia"
cap label var TR "Turkey"
cap label var TR_1 "Turkey: Black Sea"
cap label var TR_2 "Turkey: Mediterranean"
cap label var TR_9 "Turkey: unspecified maritime coastal area"
cap label var BY "Belarus"
cap label var BA "Bosnia and Herzegovina"
cap label var FO "Faeroe Islands (DK)"
cap label var GI "Gibraltar (UK)"
cap label var XK "Kosovo (under United Nations Security Council Resolution 1244/99)"
cap label var MD "Moldova"
cap label var MC "Monaco"
cap label var RU "Russia"
cap label var RU_1 "Russia: Black Sea"
cap label var RU_2 "Russia: Baltic Sea (unspecified)"
cap label var RU_3 "Russia: Asia"
cap label var RU_4 "Russia: Barents and White Sea"
cap label var RU_5 "Russia: Baltic Sea (Gulf of Finland only)"
cap label var RU_6 "Russia: Baltic Sea (excluding Gulf of Finland)"
cap label var RU_7 "Russia: European inland waterways, including Caspian Sea"
cap label var RU_9 "Russia: unspecified maritime coastal area"
cap label var UA "Ukraine"
cap label var RS_ME "Former Serbia and Montenegro (before 2006) / Total components of the former Serbia and Montenegro"
cap label var EX_YU "Former Yugoslavia (before 1992) / Total components of the former republic of Yugoslavia"
cap label var EUR_NEU27_2020 "European non-EU27 countries (from 2020)"
cap label var EUR_NEU28 "European non-EU28 countries (2013-2020)"
cap label var AFR "Africa"
cap label var DZ "Algeria"
cap label var AO "Angola"
cap label var BJ "Benin"
cap label var CM "Cameroon"
cap label var CV "Cape Verde"
cap label var KM "Comoros"
cap label var CG "Congo"
cap label var CI "Côte d'Ivoire"
cap label var CD "Democratic Republic of the Congo"
cap label var DJ "Djibouti"
cap label var EG "Egypt"
cap label var GQ "Equatorial Guinea"
cap label var ER "Eritrea"
cap label var ET "Ethiopia"
cap label var GA "Gabon"
cap label var GM "Gambia, The"
cap label var GH "Ghana"
cap label var GN "Guinea"
cap label var GW "Guinea-Bissau"
cap label var KE "Kenya"
cap label var LR "Liberia"
cap label var LY "Libya"
cap label var MG "Madagascar"
cap label var ML "Mali"
cap label var MR "Mauritania"
cap label var MU "Mauritius"
cap label var MA "Morocco"
cap label var MA_1 "Morocco: Mediterranean"
cap label var MA_2 "Morocco: West Africa"
cap label var MA_9 "Morocco: unspecified maritime coastal area"
cap label var MZ "Mozambique"
cap label var NA "Namibia"
cap label var NE "Niger"
cap label var NG "Nigeria"
cap label var SH "Saint Helena, Ascension and Tristan da Cunha (UK)"
cap label var ST "São Tomé and Príncipe"
cap label var SN "Senegal"
cap label var SC "Seychelles"
cap label var SL "Sierra Leone"
cap label var SO "Somalia"
cap label var ZA "South Africa"
cap label var SD "Sudan"
cap label var TZ "Tanzania"
cap label var TG "Togo"
cap label var TN "Tunisia"
cap label var EH "Western Sahara"
cap label var AME "America"
cap label var AI "Anguilla (UK)"
cap label var AG "Antigua and Barbuda"
cap label var AR "Argentina"
cap label var AW "Aruba (NL)"
cap label var BS "Bahamas"
cap label var BB "Barbados"
cap label var BZ "Belize"
cap label var BM "Bermuda (UK)"
cap label var BQ "Bonaire, Saint Eustatius and Saba"
cap label var BR "Brazil"
cap label var VG "British Virgin Islands (UK)"
cap label var CA "Canada"
cap label var CA_1_2 "Canada: Atlantic, Great Lakes and Upper St Lawrence"
cap label var CA_1 "Canada: Atlantic"
cap label var CA_2 "Canada: Great Lakes, Upper St Lawrence"
cap label var CA_3 "Canada: West Coast"
cap label var CA_9 "Canada: unspecified maritime coastal area"
cap label var KY "Cayman Islands (UK)"
cap label var CL "Chile"
cap label var CO "Colombia"
cap label var CO_1 "Colombia: North Coast"
cap label var CO_2 "Colombia: West Coast"
cap label var CO_9 "Colombia: unspecified maritime coastal area"
cap label var CR "Costa Rica"
cap label var CU "Cuba"
cap label var CW "Curaçao"
cap label var DM "Dominica"
cap label var DO "Dominican Republic"
cap label var EC "Ecuador"
cap label var SV "El Salvador"
cap label var FK "Falkland Islands (UK)"
cap label var AN "Former Netherlands Antilles"
cap label var GL "Greenland (DK)"
cap label var GD "Grenada"
cap label var GT "Guatemala"
cap label var GY "Guyana"
cap label var HT "Haiti"
cap label var HN "Honduras"
cap label var JM "Jamaica"
cap label var MF "Saint Martin (FR)"
cap label var MX "Mexico"
cap label var MX_1 "Mexico: Atlantic"
cap label var MX_2 "Mexico: Pacific"
cap label var MX_9 "Mexico: unspecified maritime coastal area"
cap label var MS "Montserrat (UK)"
cap label var NI "Nicaragua"
cap label var PA "Panama"
cap label var PE "Peru"
cap label var KN "Saint Kitts and Nevis"
cap label var LC "Saint Lucia"
cap label var PM "Saint Pierre and Miquelon (FR)"
cap label var VC "Saint Vincent and the Grenadines"
cap label var BL "Saint-Barthélemy (FR)"
cap label var SX "Sint Maarten"
cap label var SR "Suriname"
cap label var TT "Trinidad and Tobago"
cap label var TC "Turks and Caicos Islands (UK)"
cap label var US "United States"
cap label var US_1_2_6 "United States: North and South Atlantic and Great Lakes"
cap label var US_1 "United States: North Atlantic"
cap label var US_2 "United States: South Atlantic"
cap label var US_3 "United States: Gulf"
cap label var US_4 "United States: South Pacific"
cap label var US_5 "United States: North Pacific"
cap label var US_6 "United States: Great Lakes"
cap label var US_7 "United States: Puerto Rico"
cap label var US_9 "United States: unspecified maritime coastal area"
cap label var UY "Uruguay"
cap label var VI "US Virgin Islands (US)"
cap label var VE "Venezuela"
cap label var ASI_OCE "Asia and Oceania"
cap label var ASI "Asia"
cap label var AZ "Azerbaijan"
cap label var BH "Bahrain"
cap label var BD "Bangladesh"
cap label var IO "British Indian Ocean Territory (UK)"
cap label var BN "Brunei Darussalam"
cap label var KH "Cambodia"
cap label var CN_X_HK "China (except Hong Kong)"
cap label var EG_1 "Egypt: Mediterranean"
cap label var EG_2 "Egypt: Red Sea"
cap label var EG_9 "Egypt: unspecified maritime coastal area"
cap label var GE "Georgia"
cap label var HK "Hong Kong"
cap label var IN "India"
cap label var ID "Indonesia"
cap label var IR "Iran"
cap label var IQ "Iraq"
cap label var IL "Israel"
cap label var IL_1 "Israel: Mediterranean"
cap label var IL_2 "Israel: Red Sea"
cap label var IL_9 "Israel: unspecified maritime coastal area"
cap label var JP "Japan"
cap label var JO "Jordan"
cap label var KZ "Kazakhstan"
cap label var KW "Kuwait"
cap label var LB "Lebanon"
cap label var MO "Macao"
cap label var MY "Malaysia"
cap label var MV "Maldives"
cap label var MM "Myanmar/Burma"
cap label var KP "North Korea"
cap label var OM "Oman"
cap label var PK "Pakistan"
cap label var PS "Palestine"
cap label var PH "Philippines"
cap label var QA "Qatar"
cap label var SA "Saudi Arabia"
cap label var SA_1 "Saudi Arabia: Red Sea"
cap label var SA_2 "Saudi Arabia: Gulf"
cap label var SA_9 "Saudi Arabia: unspecified maritime coastal area"
cap label var SG "Singapore"
cap label var KR "South Korea"
cap label var LK "Sri Lanka"
cap label var SY "Syria"
cap label var TW "Taiwan"
cap label var TH "Thailand"
cap label var TL "Timor-Leste"
cap label var TM "Turkmenistan"
cap label var AE "United Arab Emirates"
cap label var VN "Vietnam"
cap label var YE "Yemen"
cap label var OCE "Oceania"
cap label var US_ISL "American Oceania (US)"
cap label var AS "American Samoa (US)"
cap label var AU "Australia"
cap label var AU_ISL "Australian Oceania"
cap label var CX "Christmas Island (AU)"
cap label var CC "Cocos (Keeling) Islands (AU)"
cap label var CK "Cook Islands (NZ)"
cap label var FM "Federated States of Micronesia"
cap label var FJ "Fiji"
cap label var PF "French Polynesia (FR)"
cap label var GU "Guam (US)"
cap label var HM "Heard Island and McDonald Islands (AU)"
cap label var KI "Kiribati"
cap label var MH "Marshall Islands"
cap label var NR "Nauru"
cap label var NC "New Caledonia (FR)"
cap label var NZ "New Zealand"
cap label var NU "Niue (NZ)"
cap label var NF "Norfolk Island (AU)"
cap label var MP "Northern Mariana Islands (US)"
cap label var PW "Palau"
cap label var PG "Papua New Guinea"
cap label var PN "Pitcairn Islands (UK)"
cap label var WS "Samoa"
cap label var SB "Solomon Islands"
cap label var TK "Tokelau (NZ)"
cap label var TO "Tonga"
cap label var TV "Tuvalu"
cap label var UM "United States Minor Outlying Islands (US)"
cap label var VU "Vanuatu"
cap label var WF "Wallis and Futuna (FR)"
cap label var AQ "Antarctica"
cap label var BV "Bouvet Island (NO)"
cap label var GS "South Georgia and the South Sandwich Islands (UK)"
cap label var TF "French Southern Territories (FR)"
cap label var UNK_NSP "Total unspecified and unknown locations"
cap label var OFF_NSP "Offshore installations not elsewhere specified"
cap label var AGG_NSP "Aggregates extraction areas not elsewhere specified and other activities not elsewhere specified"
cap label var UNK "Unknown"
