cap label var _01000 "Cereals (including seeds)"
cap label var _01100 "Wheat and spelt"
cap label var _01110 "Soft wheat and spelt"
cap label var _01120 "Durum wheat"
cap label var _01200 "Rye and meslin"
cap label var _01300 "Barley"
cap label var _01400 "Oats and summer cereal mixtures"
cap label var _01500 "Grain maize"
cap label var _01600 "Rice"
cap label var _01900 "Other cereals"
cap label var _02000 "INDUSTRIAL CROPS"
cap label var _02100 "Oil seeds and oleaginous fruits (including seeds)"
cap label var _02110 "Rape and turnip rape seed"
cap label var _02120 "Sunflower"
cap label var _02130 "Soya"
cap label var _02190 "Other oleaginous products"
cap label var _02200 "Protein crops (including seeds)"
cap label var _02300 "Raw tobacco"
cap label var _02400 "Sugar beet"
cap label var _02900 "Other industrial crops"
cap label var _02910 "Fibre plants"
cap label var _02920 "Hops"
cap label var _02930 "Other industrial crops: others"
cap label var _03000 "FORAGE PLANTS"
cap label var _03100 "Fodder maize"
cap label var _03200 "Fodder root crops (including forage beet)"
cap label var _03900 "Other forage plants"
cap label var _04000 "VEGETABLES AND HORTICULTURAL PRODUCTS"
cap label var _04100 "Fresh vegetables"
cap label var _04110 "Cauliflower"
cap label var _04120 "Tomatoes"
cap label var _04190 "Other fresh vegetables"
cap label var _04200 "Plants and flowers"
cap label var _04210 "Nursery plants"
cap label var _04220 "Ornamental plants and flowers (including Christmas trees)"
cap label var _04230 "Plantations"
cap label var _05000 "POTATOES (including seeds)"
cap label var _06000 "FRUITS"
cap label var _06100 "Fresh fruit"
cap label var _06110 "Dessert apples"
cap label var _06120 "Dessert pears"
cap label var _06130 "Peaches"
cap label var _06190 "Other fresh fruit"
cap label var _06200 "Citrus fruits"
cap label var _06210 "Sweet oranges"
cap label var _06220 "Mandarins"
cap label var _06230 "Lemons"
cap label var _06290 "Other citrus fruits"
cap label var _06300 "Tropical fruit"
cap label var _06400 "Grapes"
cap label var _06410 "Dessert grapes"
cap label var _06490 "Other grapes"
cap label var _06500 "Olives"
cap label var _06510 "Table olives"
cap label var _06590 "Other olives"
cap label var _07000 "WINE"
cap label var _07100 "Table wine"
cap label var _07200 "Quality wine"
cap label var _08000 "OLIVE OIL"
cap label var _09000 "OTHER CROP PRODUCTS"
cap label var _09100 "Vegetable materials used primarily for plaiting"
cap label var _09200 "Seeds"
cap label var _09900 "Other crop products: others"
cap label var _10000 "CROP OUTPUT"
cap label var _11000 "ANIMALS"
cap label var _11100 "Cattle"
cap label var _11200 "Pigs"
cap label var _11300 "Equines"
cap label var _11400 "Sheep and goats"
cap label var _11500 "Poultry"
cap label var _11900 "Other animals"
cap label var _12000 "ANIMAL PRODUCTS"
cap label var _12100 "Milk"
cap label var _12200 "Eggs"
cap label var _12900 "Other animal products"
cap label var _12910 "Raw wool"
cap label var _12920 "Silkworm cocoons"
cap label var _12930 "Other animal products: others"
cap label var _13000 "ANIMAL OUTPUT"
cap label var _14000 "AGRICULTURAL GOODS OUTPUT"
cap label var _15000 "AGRICULTURAL SERVICES OUTPUT"
cap label var _15100 "AGRICULTURAL SERVICES"
cap label var _15200 "RENTING OF MILK QUOTA"
cap label var _16000 "AGRICULTURAL OUTPUT"
cap label var _17000 "SECONDARY ACTIVITIES (INSEPARABLE)"
cap label var _17100 "TRANSFORMATION OF AGRICULTURAL PRODUCTS"
cap label var _17110 "TRANSFORMATION OF AGRICULTURAL PRODUCTS - cereals"
cap label var _17120 "TRANSFORMATION OF AGRICULTURAL PRODUCTS - vegetables"
cap label var _17130 "TRANSFORMATION OF AGRICULTURAL PRODUCTS - fruits"
cap label var _17140 "TRANSFORMATION OF AGRICULTURAL PRODUCTS - wine"
cap label var _17150 "TRANSFORMATION OF AGRICULTURAL PRODUCTS - animals"
cap label var _17160 "TRANSFORMATION OF AGRICULTURAL PRODUCTS - animal products"
cap label var _17161 "TRANSFORMATION OF AGRICULTURAL PRODUCTS - animal products : milk"
cap label var _17162 "TRANSFORMATION OF AGRICULTURAL PRODUCTS - animal products : other animal products"
cap label var _17190 "TRANSFORMATION OF AGRICULTURAL PRODUCTS - other"
cap label var _17900 "OTHER NON-SEPARABLE SECONDARY ACTIVITIES (GOODS AND SERVICES)"
cap label var _18000 "OUTPUT OF THE AGRICULTURAL 'INDUSTRY'"
cap label var _19000 "TOTAL INTERMEDIATE CONSUMPTION"
cap label var _19010 "SEEDS AND PLANTING STOCK (INTERMEDIATE CONSUMPTION)"
cap label var _19011 "SEEDS AND PLANTING STOCK (INTERMEDIATE CONSUMPTION) supplied by other agricultural holdings"
cap label var _19012 "SEEDS AND PLANTING STOCK (INTERMEDIATE CONSUMPTION) purchased from outside the agricultural 'industry'"
cap label var _19020 "ENERGY; LUBRICANTS"
cap label var _19021 "ENERGY; LUBRICANTS - electricity"
cap label var _19022 "ENERGY; LUBRICANTS - gas"
cap label var _19023 "ENERGY; LUBRICANTS - other fuels and propellants"
cap label var _19029 "ENERGY; LUBRICANTS - energy; lubricants: other"
cap label var _19030 "FERTILISERS AND SOIL IMPROVERS"
cap label var _19031 "FERTILISERS AND SOIL IMPROVERS - Fertilisers supplied by other agricultural holdings"
cap label var _19032 "FERTILISERS AND SOIL IMPROVERS - Fertilisers purchased from outside the agricultural 'industry'"
cap label var _19040 "PLANT PROTECTION PRODUCTS, HERBICIDES, INSECTICIDES AND PESTICIDES"
cap label var _19050 "VETERINARY EXPENSES"
cap label var _19060 "FEEDINGSTUFFS (INTERMEDIATE CONSUMPTION)"
cap label var _19061 "FEEDINGSTUFFS (INTERMEDIATE CONSUMPTION) - feedingstuffs supplied by other agricultural holdings"
cap label var _19062 "FEEDINGSTUFFS (INTERMEDIATE CONSUMPTION) - feedingstuffs purchased from outside the agricultural 'industry'"
cap label var _19063 "FEEDINGSTUFFS (INTERMEDIATE CONSUMPTION) - feedingstuffs produced and consumed by the same holding"
cap label var _19070 "MAINTENANCE OF MATERIALS"
cap label var _19080 "MAINTENANCE OF BUILDINGS"
cap label var _19090 "AGRICULTURAL SERVICES (INTERMEDIATE CONSUMPTION)"
cap label var _19095 "FINANCIAL INTERMEDIATION SERVICES INDIRECTLY MEASURED (FISIM)"
cap label var _19900 "OTHER GOODS AND SERVICES"
cap label var _20000 "GROSS VALUE ADDED AT BASIC PRICES"
cap label var _21000 "FIXED CAPITAL CONSUMPTION"
cap label var _21100 "FIXED CAPITAL CONSUMPTION : EQUIPMENT"
cap label var _21200 "FIXED CAPITAL CONSUMPTION : BUILDINGS"
cap label var _21300 "PLANTATIONS"
cap label var _21900 "OTHERS"
cap label var _22000 "NET VALUE ADDED AT BASIC PRICES"
cap label var _23000 "COMPENSATION OF EMPLOYEES"
cap label var _24000 "OTHER TAXES ON PRODUCTION"
cap label var _25000 "OTHER SUBSIDIES ON PRODUCTION"
cap label var _26000 "FACTOR INCOME"
cap label var _27000 "OPERATING SURPLUS/MIXED INCOME"
cap label var _28000 "RENTS AND OTHER REAL ESTATE RENTAL CHARGES TO BE PAID"
cap label var _29000 "INTEREST PAID"
cap label var _30000 "INTEREST RECEIVED"
cap label var _31000 "ENTREPRENEURIAL INCOME"
cap label var _32000 "GFCF IN AGRICULTURAL PRODUCTS"
cap label var _32100 "GFCF IN PLANTATIONS"
cap label var _32200 "GFCF IN ANIMALS"
cap label var _33000 "GFCF IN NON-AGRICULTURAL PRODUCTS"
cap label var _33100 "GFCF IN MATERIALS"
cap label var _33110 "GFCF IN MACHINES AND OTHER EQUIPMENT"
cap label var _33120 "GFCF IN TRANSPORT EQUIPMENT"
cap label var _33200 "GFCF IN BUILDINGS"
cap label var _33210 "GFCF IN FARM BUILDINGS (NON-RESIDENTIAL)"
cap label var _33220 "GFCF IN OTHER WORKS EXCEPT LAND IMPROVEMENTS (OTHER BUILDINGS, STRUCTURES, ETC.)"
cap label var _33900 "OTHER GFCF"
cap label var _33910 "GFCF IN INTANGIBLE FIXED ASSETS (E.G. COMPUTER SOFTWARE)"
cap label var _33920 "ADDITION TO THE VALUE OF NON-FINANCIAL NON-PRODUCED ASSETS"
cap label var _33921 "GFCF IN MAJOR LAND IMPROVEMENTS"
cap label var _33922 "COSTS LINKED TO THE PURCHASE OF LAND AND PRODUCTION RIGHTS"
cap label var _34000 "GROSS FIXED CAPITAL FORMATION (EXCLUDING DEDUCTIBLE VAT)"
cap label var _35000 "NET FIXED CAPITAL FORMATION (EXCLUDING DEDUCTIBLE VAT)"
cap label var _36000 "CHANGES IN STOCKS"
cap label var _37000 "CAPITAL TRANSFERS"
cap label var _37100 "INVESTMENT GRANTS"
cap label var _37200 "OTHER CAPITAL TRANSFERS"
cap label var _73100 "BUCKWHEAT"
cap label var _73200 "TRITICALE"
cap label var _73300 "DRIED PULSES"
cap label var _73400 "DRIED PEAS"
cap label var _73500 "HARICOT BEANS"
cap label var _73600 "POTATOES FOR CONSUMPTION"
cap label var _73700 "INDUSTRIAL POTATOES"
cap label var _73800 "POTATOE SEEDS"
cap label var _73900 "FODDER POTATOES"
cap label var _74000 "POPPY"
cap label var _74100 "PAPRIKA"
cap label var _74200 "CABBAGES"
cap label var _74300 "ENDIVES"
cap label var _74400 "ARTICHOKES"
cap label var _74500 "FENNEL"
cap label var _74600 "SALAD"
cap label var _74700 "CONCUMBERS"
cap label var _74800 "COURGETTE"
cap label var _74900 "PEPPER"
cap label var _75000 "CAROT"
cap label var _75100 "ONIONS, SHALLOTS"
cap label var _75200 "FRESH PEAS"
cap label var _75300 "FRESH HARICOTS"
cap label var _75400 "MUSHROOMS"
cap label var _75500 "APRICOT"
cap label var _75600 "CHERRIES"
cap label var _75700 "WALNUTS"
cap label var _75800 "HAZELNUTS"
cap label var _75900 "STRAWBERRIES"
cap label var _76000 "CURRANTS"
cap label var _76100 "GOOSEBERRY"
cap label var _76200 "CLEMENTINES"
cap label var _76300 "BULBOUS OF FLOWERS"
cap label var _76400 "CATTLE (excluding calves)"
cap label var _76500 "CALVES"
cap label var _76600 "HEIFERS"
cap label var _76700 "COWS"
cap label var _76800 "BULLS"
cap label var _76900 "BEEF"
cap label var _77000 "SOWS"
cap label var _77100 "SLAUGHTERED PIGS"
cap label var _77200 "HENS"
cap label var _77300 "CHICKEN"
cap label var _77400 "CHICKS"
cap label var _77500 "CHICKS OF ONE DAY"
cap label var _77600 "DUCKS"
cap label var _77700 "GOOSE"
cap label var _77800 "TURKEYS"
cap label var _77900 "RABBITS"
cap label var _78000 "HONEY"
cap label var _40000 "Total labour force input"
cap label var _41000 "Non-salaried"
cap label var _42000 "Salaried"
cap label var IND_A_EURO "Indicator A: Index of the real income of factors in agriculture per annual work unit"
cap label var IND_B_EURO "Indicator B: Index of real net agricultural entrepreneurial income, per unpaid annual work unit"
cap label var IND_C_EURO "Indicator C: Net entrepreneurial income of agriculture"
cap label var IND_A "Indicator A: Index of the real income of factors in agricultural per annual work unit"
cap label var IND_B "Indicator B: Index of real net agricultural entrepreneurial income, per unpaid annual work unit"
cap label var IND_C "Indicator C: Net entrepreneurial income of agriculture"
