cap label var TOTAL "Total"
cap label var SRC "Sourcing"
cap label var SRC_IN "Sourcing within the enterprise group"
cap label var SRC_DOM "Domestic sourcing"
cap label var SRC_DOM_IN "Domestic sourcing within the enterprise group"
cap label var SRC_DOM_OUT "Domestic sourcing outside the enterprise group"
cap label var SRC_INTL "International sourcing"
cap label var SRC_INTL_BFR "International sourcing before the reference period"
cap label var SRC_INTL_REF "International sourcing in the reference period"
cap label var SRC_INTL_IN "International sourcing within the enterprise group"
cap label var SRC_INTL_IN_BFR "International sourcing within the enterprise group before the reference period"
cap label var SRC_INTL_OUT "International sourcing outside the enterprise group"
cap label var SRC_INTL_OUT_BFR "International sourcing outside the enterprise group before the reference period"
cap label var NSRC "No sourcing"
cap label var NSRC_BFR "No sourcing before the reference period"
cap label var NSRC_REF "No sourcing in the reference period"
cap label var SRC_INTL_NSRC "International sourcing and no sourcing"
cap label var SRC_INTL_NSRC_BFR "International sourcing and no sourcing before the reference period"
cap label var SRC_INTL_NSRC_REF "International sourcing and no sourcing in the reference period"
cap label var SO "Function is sourced"
cap label var SO_DO "Function is sourced Domestically"
cap label var SO_IN "Function is sourced Internationally"
cap label var NO "Function is not sourced"
cap label var UNK "Unknown"
