cap label var FOC_IEGDSERV "Focus on improving existing goods or services"
cap label var FOC_NEWGDSERV "Focus on introducing entirely new goods or services"
cap label var ITR_NEWIGDSERV "Introduce new or significantly improved goods or services"
cap label var FOC_NEWCUS "Focus on reaching out to new customer groups"
cap label var FOC_CUS_SLT "Focus on customer specific solution"
cap label var FOC_LOWPRC "Focus on low-price"
cap label var FOC_HQUAL "Focus on high quality"
cap label var FOC_BROAD_GDSERV "Focus on a broad range of goods and services"
cap label var FOC_KEY_GDSERV "Focus on key goods and services"
cap label var FOC_SAT_CUS "Focus on satisfying established customer groups"
cap label var FOC_STD_GDSERV "Focus on standardised goods or services"
cap label var B_ALIA "Build alliances"
cap label var RED_COST_MCS "Reduce costs of purchased materials, components or services"
cap label var INCR_FLEX_RESP "Increase flexibility/responsiveness"
cap label var RED_IH_COST "Reduce in-house costs of operation"
cap label var DEV_NEWMKT_IN_EU "Develop new markets within Europe"
cap label var DEV_NEWMKT_OUT_EU "Develop new markets outside Europe"
cap label var IMKTG_GDSERV "Intensify or improve the marketing of goods or services"
cap label var CH_MKTG "Undertake changing enterprise's marketing concepts/strategies"
cap label var CH_ESTH_APPEAR "Significant changes in aesthetic appearance"
cap label var IMPL_MGMT "Undertake implementation of advanced management techniques"
cap label var IMPL_CH_ORG "Undertake implementation of changed organisational structures"
cap label var IMPL_NEW_CRP "Undertake implementation of new corporate strategies"
cap label var PUR_MES_SAME "Purchase of machinery, equipment or software based on the same or improved technology"
cap label var PUR_MES_NEW "Purchase of machinery, equipment or software based on new technology"
