cap label var V11110 "Enterprises - number"
cap label var V11111 "Enterprises broken down by legal status - number"
cap label var V11112 "Enterprises broken down by size class of gross premiums written - number"
cap label var V11113 "Enterprises broken down by size class of gross technical provisions - number"
cap label var V11114_C "Enterprises broken down by residence of the parent enterprise - number"
cap label var V11115 "Enterprises broken down by country of residence of the parent enterprise - number"
cap label var V11116 "Enterprises broken down by size classes of the balance sheet total - number"
cap label var V11117 "Number of enterprises broken down by category of credit institutions - number"
cap label var V11150 "Enterprises with non-autonomous pension funds - number"
cap label var V11210 "Local units - number"
cap label var V11410 "Total number and location of branches in other countries - number"
cap label var V11411 "Branches broken down by location in non-EEA countries - number"
cap label var V11510 "Financial subsidiaries broken down by location in other countries - number"
cap label var V11610 "Pension schemes - number"
cap label var V11710 "Enterprises with members in other EEA countries - number"
cap label var V11910 "Population of active enterprises in t - number"
cap label var V11920 "Births of enterprises in t - number"
cap label var V11930 "Deaths of enterprises in t - number"
cap label var V11941 "Enterprises newly born in t-1 having survived to t - number"
cap label var V11942 "Enterprises newly born in t-2 having survived to t - number"
cap label var V11943 "Enterprises newly born in t-3 having survived to t - number"
cap label var V11944 "Enterprises newly born in t-4 having survived to t - number"
cap label var V11945 "Enterprises newly born in t-5 having survived to t - number"
cap label var V11950 "High growth enterprises measured in employment - number"
cap label var V11951 "High growth enterprises measured in turnover - number"
cap label var V11952 "Young high growth enterprises (gazelles) measured in employment - number"
cap label var V11953 "Young high growth enterprises (gazelles) measured in turnover - number"
cap label var V11955 "Medium growth enterprises measured in employment - number"
cap label var V11956 "Medium growth enterprises measured in turnover - number"
cap label var V11957 "Young medium-growth enterprises measured in employment - number"
cap label var V11958 "Young medium-growth enterprises measured in turnover - number"
cap label var V11960 "High growth enterprises measured in employment (growth by 10% or more) - number"
cap label var V12110 "Turnover or gross premiums written - million euro"
cap label var V12111 "Gross direct premiums written - million euro"
cap label var V12112 "Gross reinsurance premiums accepted, written premiums - million euro"
cap label var V12113 "Gross direct premiums written, individual premiums - million euro"
cap label var V12114 "Gross direct premiums written, premiums under group contracts - million euro"
cap label var V12115 "Gross direct premiums written, periodic premiums - million euro"
cap label var V12116 "Gross direct premiums written, single premiums - million euro"
cap label var V12117 "Gross direct premiums written, premiums from non-bonus contracts - million euro"
cap label var V12118 "Gross direct premiums written, premiums from bonus contracts - million euro"
cap label var V12119 "Gross direct premiums written, premiums from contracts where the investment risk is borne by policyholders - million euro"
cap label var V12120 "Production value - million euro"
cap label var V12130 "Gross margin on goods for resale - million euro"
cap label var V12140 "Value added at basic prices - million euro"
cap label var V12150 "Value added at factor cost - million euro"
cap label var V12151 "Value added at factor cost - percentage of gross domestic product (GDP)"
cap label var V12170 "Gross operating surplus - million euro"
cap label var V13110 "Total purchases of goods and services - million euro"
cap label var V13112 "Purchases of services - million euro"
cap label var V13120 "Purchases of goods and services purchased for resale in the same condition as received - million euro"
cap label var V13131 "Payments for agency workers - million euro"
cap label var V13210 "Change in stocks of goods and services - million euro"
cap label var V13211 "Change in stocks of goods and services purchased for resale in the same condition as received - million euro"
cap label var V13213 "Change in stocks of finished products and work in progress manufactured by the unit - million euro"
cap label var V13310 "Personnel costs - million euro"
cap label var V13320 "Wages and Salaries - million euro"
cap label var V13330 "Social security costs - million euro"
cap label var V13410 "Operating costs linked to buildings and equipment - million euro"
cap label var V13411 "Payments for long term rental and operational and financial leasing of goods - million euro"
cap label var V13420 "Cost of selling - million euro"
cap label var V13430 "Other operating costs - million euro"
cap label var V15110 "Gross investment in tangible goods - million euro"
cap label var V15111 "Gross investment in tangible goods - percentage of gross domestic product (GDP)"
cap label var V15120 "Gross investment in land - million euro"
cap label var V15130 "Gross investment in existing buildings and structures - million euro"
cap label var V15140 "Gross investment in construction and alteration of buildings - million euro"
cap label var V15150 "Gross investment in machinery and equipment - million euro"
cap label var V15210 "Sales of tangible investment goods - million euro"
cap label var V15250 "Net investment in tangible goods - million euro"
cap label var V15310 "Value of tangible goods acquired through financial leasing - million euro"
cap label var V15420 "Gross investment in concessions - million euro"
cap label var V15441 "Investment in purchased software - million euro"
cap label var V15442 "Investment in software purchased by the unit - million euro"
cap label var V15450 "Service related investment - million euro"
cap label var V15460 "Income from intellectual property rights - million euro"
cap label var V15470 "Purchase of advertising space or time for resale - million euro"
cap label var V16110 "Persons employed - number"
cap label var V16111 "Persons employed - percentage of total employment"
cap label var V16111_C "Persons employed broken down by category of credit institutions - number"
cap label var V16112 "Women employed - number"
cap label var V16113 "Persons employed on a fixed salary basis - number"
cap label var V16118 "Jobs created"
cap label var V16119 "Jobs lost - number"
cap label var V16120 "Unpaid persons employed - number"
cap label var V16130 "Employees - number"
cap label var V16131 "Part-time employees - number"
cap label var V16132 "Apprentices - number"
cap label var V16133 "Female employees - number"
cap label var V16135 "Homeworkers - number"
cap label var V16136 "Female employees - number"
cap label var V16140 "Employees in full time equivalent units - number"
cap label var V16150 "Hours worked by employees - number"
cap label var V16160 "Jobs - number"
cap label var V16910 "Persons employed in the population of active enterprises in t - number"
cap label var V16911 "Employees in the population of active enterprises in t - number"
cap label var V16920 "Persons employed in the population of births in t - number"
cap label var V16921 "Employees in the population of births in t - number"
cap label var V16930 "Persons employed in the population of deaths in t - number"
cap label var V16931 "Employees in the population of deaths in t - number"
cap label var V16941 "Persons employed in the population of enterprises newly born in t-1 having survived to t - number"
cap label var V16942 "Persons employed in the population of enterprises newly born in t-2 having survived to t - number"
cap label var V16943 "Persons employed in the population of enterprises newly born in t-3 having survived to t - number"
cap label var V16944 "Persons employed in the population of enterprises newly born in t-4 having survived to t - number"
cap label var V16945 "Persons employed in the population of enterprises newly born in t-5 having survived to t - number"
cap label var V16951 "Persons employed in the year of birth in the population of enterprises newly born in t-1 having survived to t - number"
cap label var V16952 "Persons employed in the year of birth in the population of enterprises newly born in t-2 having survived to t - number"
cap label var V16953 "Persons employed in the year of birth in the population of enterprises newly born in t-3 having survived to t - number"
cap label var V16954 "Persons employed in the year of birth in the population of enterprises newly born in t-4 having survived to t - number"
cap label var V16955 "Persons employed in the year of birth in the population of enterprises newly born in t-5 having survived to t - number"
cap label var V16961 "Employees in high growth enterprises measured in employment (growth by 10% or more) - number"
cap label var V17320 "Retail stores - number"
cap label var V17330 "Category of sales space for retail stores engaged in retail trade - number"
cap label var V17331 "Sales space - square meter"
cap label var V17340 "Fixed market stands and/ or stalls - number"
cap label var V18100 "Turnover from agriculture, forestry, fishing and industrial activities - million euro"
cap label var V18110 "Turnover from the principal activity at 3-digit level NACE Rev. 2 - million euro"
cap label var V18120 "Turnover from industrial activities - million euro"
cap label var V18121 "Turnover from industrial activities excluding construction - million euro"
cap label var V18122 "Turnover from construction - million euro"
cap label var V18130 "Turnover from trading activities of purchase and resale - million euro"
cap label var V18140 "Turnover from intermediary activities (agents) - million euro"
cap label var V18150 "Turnover from service activities - million euro"
cap label var V18160 "Turnover from trading activities of purchase and resale and intermediary activities (agents) - million euro"
cap label var V18210 "Breakdown of turnover by product (according to Section G of the CPA) - million euro"
cap label var V18310 "Turnover from building - million euro"
cap label var V18320 "Turnover from civil engineering - million euro"
cap label var V20110 "Purchases of energy products - million euro"
cap label var V20111 "Purchases of solid fuels - million euro"
cap label var V20112 "Purchases of petroleum products - million euro"
cap label var V20113 "Purchases of natural and derived gas - million euro"
cap label var V20114 "Purchases of renewable energy sources - million euro"
cap label var V20115 "Purchases of heat - million euro"
cap label var V20116 "Purchases of electricity - million euro"
cap label var V20210 "Purchases of hard coal - million euro"
cap label var V20220 "Purchases of coke - million euro"
cap label var V20230 "Purchases of patent fuels - million euro"
cap label var V20240 "Purchases of gasoil - million euro"
cap label var V20250 "Purchases of heavy fuel - million euro"
cap label var V20260 "Purchases of other petroleum products - million euro"
cap label var V20270 "Purchases of natural gas - million euro"
cap label var V20280 "Purchases of derived gas - million euro"
cap label var V20290 "Purchases of renewable energy sources - million euro"
cap label var V20300 "Purchases of heat - million euro"
cap label var V20310 "Purchases of electricity - million euro"
cap label var V21110 "Investment in equipment and plant for pollution control - million euro"
cap label var V21120 "Investment in equipment and plant linked to cleaner technology ('integrated technology') - million euro"
cap label var V21140 "Total current expenditure on environmental protection - million euro"
cap label var V22110 "Total intra-mural R & D expenditure - million euro"
cap label var V22120 "Total number of R & D personnel - number"
cap label var V23110 "Payments to sub-contractors - million euro"
cap label var V23120 "Income from sub-contracting - million euro"
cap label var V25111 "Share of turnover to resale traders: retail traders - percentage"
cap label var V25112 "Share of turnover to professional users (wholesalers - percentage"
cap label var V25113 "Share of turnover to final consumers (retail trade activity) - percentage"
cap label var V25211 "Share of purchases from wholesalers - percentage"
cap label var V25212 "Share of purchases from producers - percentage"
cap label var V32110 "Gross premiums earned - million euro"
cap label var V32112 "Gross change in the provision for unearned premiums - million euro"
cap label var V32114 "Gross premiums written broken down by legal status - million euro"
cap label var V32115 "Gross direct premiums written broken down according to the country of residence of the parent enterprise - million euro"
cap label var V32116 "Gross reinsurance premiums accepted, written premiums broken down according to the country of residence of the parent enterprise - million euro"
cap label var V32120 "Allocated investment return transferred from the non-technical account - million euro"
cap label var V32130 "Gross claims incurred - million euro"
cap label var V32131 "Gross claims payments - million euro"
cap label var V32132 "Gross claims payments in respect of claims incurred in the current accounting year - million euro"
cap label var V32134 "Gross change in the provision for outstanding claims - million euro"
cap label var V32140 "Gross operating expenses - million euro"
cap label var V32150 "Change in the equalisation provision - million euro"
cap label var V32160 "Other items in the technical account, gross amount - million euro"
cap label var V32161 "Other technical income, net amount - million euro"
cap label var V32162 "Net changes in other technical provisions, not shown under other headings - million euro"
cap label var V32163 "Bonuses and rebates, net amount - million euro"
cap label var V32164 "Other technical charges, net amount - million euro"
cap label var V32170 "Gross balance of the techncial account (sub-total I) - million euro"
cap label var V32180 "Reinsurance balance - million euro"
cap label var V32181 "Reinsurers share of gross premiums written - million euro"
cap label var V32182 "Reinsurers share of gross premiums written broken down according to the country of residence of the parent enterprise - million euro"
cap label var V32183 "Reinsurers share of gross change in the provision for unearned premiums - million euro"
cap label var V32185 "Reinsurers share of gross claims payments - million euro"
cap label var V32186 "Reinsurers share of gross change in the provision for outstanding claims - million euro"
cap label var V32187 "Reinsurance commissions and profit participations - million euro"
cap label var V32188 "Reinsurers share of the gross amount of other items in the technical account - million euro"
cap label var V32190 "Net balance of the technical account (sub-total II) - million euro"
cap label var V32220 "Investment income - million euro"
cap label var V32230 "Unrealised gains on investments - million euro"
cap label var V32250 "Gross change in life insurance provision - million euro"
cap label var V32270 "Investments charges - million euro"
cap label var V32280 "Unrealised losses on investments - million euro"
cap label var V32290 "Allocated investment return transferred to the non-technical account - million euro"
cap label var V32334 "Reinsurers share of gross change in life insurance provision - million euro"
cap label var V32420 "Investment income - million euro"
cap label var V32430 "Allocated investment return transferred from the life-assurance technical account - million euro"
cap label var V32440 "Investment charges - million euro"
cap label var V32450 "Allocated investment return transferred to the non-life insurance technical account - million euro"
cap label var V32460 "Other income - million euro"
cap label var V32470 "Other charges, including value adjustments - million euro"
cap label var V32480 "Profit or loss on ordinary activities - million euro"
cap label var V32490 "Extraordinary profit or loss - million euro"
cap label var V32500 "All taxes - million euro"
cap label var V32510 "Profit or loss for the financial year - million euro"
cap label var V32611 "Commissions for total insurance business - million euro"
cap label var V32612 "Commissions for direct insurance business - million euro"
cap label var V32614 "External expenses on goods and services - million euro"
cap label var V32615 "External and internal claims management expenses - million euro"
cap label var V32616 "Acquisition costs - million euro"
cap label var V32617 "Administrative expenses - million euro"
cap label var V32618 "Gross other technical charges - million euro"
cap label var V32619 "Investment management charges - million euro"
cap label var V32711 "Income from participating interests - million euro"
cap label var V32713 "Income from land and buildings - million euro"
cap label var V32714 "Income from other investments - million euro"
cap label var V32715 "Value re-adjustments on investments - million euro"
cap label var V32716 "Gains on the realization on investments - million euro"
cap label var V32721 "Investment management charges, including interest - million euro"
cap label var V32722 "Value adjustments on investments - million euro"
cap label var V32723 "Losses on the realization on investments - million euro"
cap label var V33111 "Gross premiums written in direct business by (sub) categories of the CPA (5-digit level and subcategories 66.03.21, 66.03.22) - million euro"
cap label var V33121 "Reinsurers share of gross direct premiums written by (sub) categories of the CPA (5 digit level and subcategories 66.03.21,66.03.22) - million euro"
cap label var V33131 "Gross claims incurred, direct business by (sub) categories of the CPA (5-digit level and subcategories 66.03.21, 66.03.22) - million euro"
cap label var V33141 "Gross operating expenses, direct business by (sub) categories of the CPA (5-digit level and subcategories 66.03.21, 66.03.22) - million euro"
cap label var V33151 "Reinsurance balance, direct business by (sub) categories of the CPA (5-digit level and subcategories 66.03.21, 66.03.22) - million euro"
cap label var V34110 "Geographical breakdown - in general - of gross direct premiums written - million euro"
cap label var V34120 "Geographical breakdown - in general - of gross reinsurance premiums accepted, premiums written - million euro"
cap label var V34130 "Geographical breakdown - in general - of reinsurers share of gross premiums written - million euro"
cap label var V34311 "Gross direct premiums written by CPA category (5-digit level) and by Member State, geographical breakdown of the business written under the right of establishment - million euro"
cap label var V34321 "Gross direct premiums written by CPA category (5-digit level) and by Member State, geographical breakdown of the business written under the right of freedom to provide services - million euro"
cap label var V36110 "Land and buildings - million euro"
cap label var V36111 "Land and buildings occupied by an insurance enterprise for its own activities - million euro"
cap label var V36112 "Land and buildings (current value) - million euro"
cap label var V36120 "Investments in affiliated enterprises and participating interests - million euro"
cap label var V36121 "Shares in affiliated enterprises and participating interests - million euro"
cap label var V36122 "Debt securities issued by, and loans to, affiliated enterprises and to enterprises with which an insurance enterprise is linked in virtue of a particiapting interest - million euro"
cap label var V36123 "Investments in affiliated enterprises and participating interest (current value) - million euro"
cap label var V36130 "Other financial investments - million euro"
cap label var V36131 "Shares and other variable-yield securities and units in unit trusts - million euro"
cap label var V36132 "Debt securities and other fixed-income securities - million euro"
cap label var V36133 "Participation in investments pools - million euro"
cap label var V36134 "Loans guaranted by mortgages - million euro"
cap label var V36135 "Other loans - million euro"
cap label var V36136 "Other (incl. deposits with credit institutions) - million euro"
cap label var V36138 "Other financial investments (current value) - million euro"
cap label var V36140 "Deposits with ceding enterprises - million euro"
cap label var V36200 "Investments for the benefit of life-assurance policyholders who bear the investment risk - million euro"
cap label var V36210 "Investments for the benefit of life-assurance policyholders who bear the investment risk - land and buildings - million euro"
cap label var V36220 "Investments for the benefit of life-assurance policyholders who bear the investment risk - other financial investments - million euro"
cap label var V36300 "Balance sheet total - million euro"
cap label var V37100 "Total capital and reserves - million euro"
cap label var V37101 "Total capital and reserves, broken down by legal status - million euro"
cap label var V37110 "Subscribed capital or equivalent funds - million euro"
cap label var V37120 "Share premium account, revaluation reserve, reserve - million euro"
cap label var V37200 "Subordinated liabilities - million euro"
cap label var V37300 "Total gross technical provisions - million euro"
cap label var V37301 "Total net technical provisions - million euro"
cap label var V37310 "Gross provision for unearned premiums - million euro"
cap label var V37320 "Gross life assurance provision - million euro"
cap label var V37330 "Gross provision for outstanding claims - million euro"
cap label var V37331 "Gross provision for outstanding claims, related to direct business - million euro"
cap label var V37332 "Gross provision for outstanding claims related to business accepted - million euro"
cap label var V37333 "Gross provision for outstanding claims, related to direct business, by product - million euro"
cap label var V37340 "Gross provision for bonuses and rebates - million euro"
cap label var V37350 "Equalization provision - million euro"
cap label var V37360 "Gross other technical provisions - million euro"
cap label var V37370 "Gross technical provisions for life-assurance policies where the investment risk is borne by the policyholders - million euro"
cap label var V37410 "Debenture loans - million euro"
cap label var V37420 "Amounts owed to credit institutions - million euro"
cap label var V39100 "Contracts outstanding at the end of the accounting year, relating to direct business for all individual life insurance contracts and for the following subcategories of the CPA: 66.01.1, 66.03.1, 66.03.4, 66.03.5 - number"
cap label var V39200 "Insured persons at the end of the accounting year, relating to direct business for all group life insurance contracts and for the following subcategory of the CPA: 66.03.1 - number"
cap label var V39300 "Insured vehicles at the end of the accounting year, relating to direct business, for the following subcategory of the CPA: 66.03.2 - number"
cap label var V39400 "Gross insured sum at the end of the accounting year, relating to direct business, for the following subcategories of the CPA: 66.01.1 and 66.01.4 - million euro"
cap label var V39500 "Claims incurred during the accounting year, relating to direct business, for the following subcategory of the CPA: 66.03.2 - number"
cap label var V42110 "Interest receivable and similar income - million euro"
cap label var V42111 "Interest receivable and similar income arising from fixed-income securities - million euro"
cap label var V42120 "Interest payable and similar charges - million euro"
cap label var V42121 "Interest payable and similar charges linked to debt securities in issue - million euro"
cap label var V42130 "Income from securities - million euro"
cap label var V42131 "Income from shares and other variable-yield securities - million euro"
cap label var V42140 "Commissions receivable - million euro"
cap label var V42150 "Commissions payable - million euro"
cap label var V42200 "Net profit or net loss on financial operations - million euro"
cap label var V42310 "Other operating income - million euro"
cap label var V42320 "General administrative expenses - million euro"
cap label var V42322 "Other administrative expenses - million euro"
cap label var V42330 "Other operating charges - million euro"
cap label var V42350 "Value adjustments and value readjustments in respect of loans and advances and provisions for contingent liabilities and for commitments - million euro"
cap label var V42360 "Other value adjustments and value readjustments - million euro"
cap label var V42400 "Profit or loss on ordinary activities - million euro"
cap label var V42500 "Extraordinary profit or loss - million euro"
cap label var V42510 "All taxes (tax on profit or loss on ordinary activities, tax on extraordinary profit or loss, other taxes) - million euro"
cap label var V42600 "Profit or loss for the financial year - million euro"
cap label var V43110 "Loans and advances to customers - million euro"
cap label var V43210 "Amounts owed to customers - million euro"
cap label var V43290 "Total of capital and reserves - million euro"
cap label var V43300 "Balance sheet total (CI) - million euro"
cap label var V43310 "Balance sheet total broken down according to the residence of the parent enterprise - million euro"
cap label var V43320 "Balance sheet total broken down by legal status - million euro"
cap label var V44110 "Interest receivable and similar income broken down by (sub)categories of the CPA - million euro"
cap label var V44120 "Interest payable and similar charges broken down by (sub)categories of the CPA - million euro"
cap label var V44130 "Commissions receivable broken down by (sub)categories of the CPA - million euro"
cap label var V44140 "Commissions payable broken down by (sub)categories of the CPA - million euro"
cap label var V45110 "Geographical breakdown of the total number of EEA branches - number"
cap label var V45210 "Geographical breakdown of interest receivable and similar income - million euro"
cap label var V45220 "Geographical breakdown of balance sheet total - million euro"
cap label var V45310 "Geographical breakdown of interest receivable and similar income via the freedom to provide services business in other EEA countries - million euro"
cap label var V45321 "Turnover per enterprise - thousand euro"
cap label var V45410 "Geographical breakdown of interest receivable and similar income via branch business (in non-EEA countries) - million euro"
cap label var V45420 "Geographical breakdown of interest receivable and similar income via freedom to provide services business (in non-EEA countries) - million euro"
cap label var V47110 "Accounts broken down by (sub)categories of the CPA - number"
cap label var V47120 "Loans and advances to customers broken down by (sub)categories of the CPA - number"
cap label var V47130 "Automatic teller machines (ATM) owned by credit institutions - number"
cap label var V48001 "Pension contributions receivable from members - million euro"
cap label var V48002 "Pension contributions receivable from employers - million euro"
cap label var V48003 "Incoming transfers - million euro"
cap label var V48004 "Other pension contributions - million euro"
cap label var V48005 "Pension contributions to defined benefits schemes - million euro"
cap label var V48006 "Pension contributions to defined contributions schemes - million euro"
cap label var V48007 "Pension contributions to hybrid schemes - million euro"
cap label var V48010 "Investment income (PF) - million euro"
cap label var V48011 "Capital gains and losses - million euro"
cap label var V48021 "Insurance claims receivable - million euro"
cap label var V48022 "Other income (PF) - million euro"
cap label var V48030 "Total expenditure on pensions - million euro"
cap label var V48031 "Regular pension payments - million euro"
cap label var V48032 "Pension payments of lump sums - million euro"
cap label var V48033 "Outgoing transfers - million euro"
cap label var V48040 "Net change in technical provisions (reserves) - million euro"
cap label var V48050 "Insurance premiums payable - million euro"
cap label var V48060 "Total operational expenses - million euro"
cap label var V48070 "All taxes - million euro"
cap label var V48080 "Turnover of non-autonomous pension funds - million euro"
cap label var V48100 "Total investments (PF) - million euro"
cap label var V48101 "Total investments invested in 'the sponsoring enterprise' - million euro"
cap label var V48102 "Total investments at market values - million euro"
cap label var V48104 "Total investments at market values - million euro"
cap label var V48110 "Land and buildings (PF) - million euro"
cap label var V48120 "Investments in affiliated enterprises and participating interests (PF) - million euro"
cap label var V48130 "Shares and other variable-yield securities - million euro"
cap label var V48131 "Shares traded on a regulated market - million euro"
cap label var V48132 "Shares quoted on a regulated market specialised in SMEs - million euro"
cap label var V48133 "Non publicly traded shares - million euro"
cap label var V48134 "Other variable yield securities - million euro"
cap label var V48140 "Units in undertaking for collective investment in transferable securities - million euro"
cap label var V48150 "Debt securities and other fixed-income securities - million euro"
cap label var V48151 "Debt securities and other fixed-income securities issued by public administrations - million euro"
cap label var V48152 "Other debt securities and other fixed income securities - million euro"
cap label var V48160 "Participation in investment pools (PF) - million euro"
cap label var V48170 "Loans guaranteed by mortgages and other loans not covered elsewhere - million euro"
cap label var V48180 "Other investments - million euro"
cap label var V48200 "Other assets - million euro"
cap label var V48300 "Capital and reserves - million euro"
cap label var V48400 "Net technical provisions (PF) - million euro"
cap label var V48500 "Other liabilities - million euro"
cap label var V48610 "Geographical breakdown of turnover - million euro"
cap label var V48620 "Shares and other variable-yield securities broken down by location - million euro"
cap label var V48630 "Total investments broken down by location - million euro"
cap label var V48700 "Members - number"
cap label var V48701 "Members of defined benefits schemes - number"
cap label var V48702 "Members of defined contributions schemes - number"
cap label var V48703 "Members of hybrid schemes - number"
cap label var V48704 "Active members - number"
cap label var V48705 "Deferred members - number"
cap label var V48706 "Retired persons - number"
cap label var V48707 "Female members - number"
cap label var V48710 "Members - number"
cap label var V85456 "Share of employees in the number of persons employed - percentage"
cap label var V85564 "Gross operating surplus per person employed - thousand euro"
cap label var V91100 "Turnover per person employed - thousand euro"
cap label var V91110 "Apparent labour productivity (Gross value added per person employed) - thousand euro"
cap label var V91111 "Enterprises - percentage"
cap label var V91120 "Wage adjusted labour productivity (Apparent labour productivity by average personnel costs) - percentage"
cap label var V91121 "Simple wage adjusted labour productivity (Gross value added by personnel costs) - percentage"
cap label var V91130 "Gross value added per employee - thousand euro"
cap label var V91140 "Gross value added per employee FTE - thousand euro"
cap label var V91150 "Gross value added per hour worked by employees"
cap label var V91170 "Share of personnel costs in production - percentage"
cap label var V91210 "Average personnel costs (personnel costs per employee) - thousand euro"
cap label var V91220 "Labour cost per employee FTE - thousand euro"
cap label var V91230 "Labour cost per hour worked by employees"
cap label var V91275 "Share of employees in persons employed - percentage"
cap label var V91290 "Growth rate of employment - percentage"
cap label var V91310 "Employer's social charges as a percentage of personnel costs - percentage"
cap label var V91616 "Jobs - percentage"
cap label var V92100 "Persons employed per enterprise - number"
cap label var V92102 "Value added at factor cost per enterprise - thousand euro"
cap label var V92110 "Gross operating surplus/turnover (gross operating rate) - percentage"
cap label var V92111 "Value added at factor cost in production value - percentage"
cap label var V92112 "Share of personnel costs in total purchases of goods and services - percentage"
cap label var V92113 "Share of gross operating surplus in value added - percentage"
cap label var V92300 "Growth rate of value added at factor cost at constant prices - percentage"
cap label var V92310 "Growth rate of production in constant prices - percentage"
cap label var V94110 "Share of principal activity in turnover (degree of specialisation) - percentage"
cap label var V94210 "Share of value added in manufacturing total - percentage"
cap label var V94220 "Share of value added in industry total - percentage"
cap label var V94240 "Share of production value in manufacturing total - percentage"
cap label var V94270 "Share of turnover in manufacturing total - percentage"
cap label var V94310 "Share of employment in manufacturing total - percentage"
cap label var V94320 "Share of employment in industry total - percentage"
cap label var V94410 "Ratio of stocks of finished products and work in progress to production value - percentage"
cap label var V94414 "Investment per person employed - thousands euro"
cap label var V94415 "Investment rate (investment/value added at factors cost) - percentage"
cap label var V95110 "Share of R&D expenditure in value added - percentage"
cap label var V95120 "Share of R&D employment in the number of persons employed - percentage"
cap label var V97010 "Net business population growth - percentage"
cap label var V97015 "Business churn: birth rate + death rate - percentage"
cap label var V97020 "Birth rate: number of enterprise births in the reference period (t) divided by the number of enterprises active in t - percentage"
cap label var V97021 "Proportion of enterprise births in the reference period (t) by size class - percentage"
cap label var V97022 "Density of birth rate: number of enterprise births in the reference period (t) divided by the population (in 10,000) in t - percentage"
cap label var V97023 "Density of birth rate (narrow version): number of enterprise births in the reference period (t) divided by the population aged 20-59 (in 10,000) in t - percentage"
cap label var V97030 "Death rate: number of enterprise deaths in the reference period (t) divided by the number of enterprises active in t - percentage"
cap label var V97031 "Proportion of enterprise deaths in the reference period (t) by size class - percentage"
cap label var V97041 "Survival rate 1: number of enterprises in the reference period (t) newly born in t-1 having survived to t divided by the number of enterprise births in t-1 - percentage"
cap label var V97042 "Survival rate 2: number of enterprises in the reference period (t) newly born in t-2 having survived to t divided by the number of enterprise births in t-2 - percentage"
cap label var V97043 "Survival rate 3: number of enterprises in the reference period (t) newly born in t-3 having survived to t divided by the number of enterprise births in t-3 - percentage"
cap label var V97044 "Survival rate 4: number of enterprises in the reference period (t) newly born in t-4 having survived to t divided by the number of enterprise births in t-4 - percentage"
cap label var V97045 "Survival rate 5: number of enterprises in the reference period (t) newly born in t-5 having survived to t divided by the number of enterprise births in t-5 - percentage"
cap label var V97051 "1 year old enterprises' share of the business population - percentage"
cap label var V97052 "2 year old enterprises' share of the business population - percentage"
cap label var V97053 "3 year old enterprises' share of the business population - percentage"
cap label var V97054 "4 year old enterprises' share of the business population - percentage"
cap label var V97055 "5 year old enterprises' share of the business population - percentage"
cap label var V97120 "Employment share of enterprise births: number of persons employed in the reference period (t) among enterprises newly born in t divided by the number of persons employed in t among the stock of enterprises active in t - percentage"
cap label var V97121 "Average size of newly born enterprises: number of persons employed in the reference period (t) among enterprises newly born in t divided by the number of enterprises newly born in t - number"
cap label var V97122 "New enterprise paid employment rate: number of employees in the reference period (t) among enterprises newly born in t divided by the number of persons employed in t among enterprises newly born in t - percentage"
cap label var V97130 "Employment share of enterprise deaths: number of persons employed in the reference period (t) among enterprise deaths divided by the number of persons employed in t among the stock of active enterprises in t - percentage"
cap label var V97131 "Average employment in enterprise deaths: number of persons employed in the reference period (t) among enterprise deaths  in t divided by the number of enterprise deaths in t - number"
cap label var V97141 "One-year old enterprises employment growth rate: number of persons employed in the reference period (t) among enterprises newly born in t-1 having survived to t divided by the number of persons employed in t-1 by the same enterprises, expressed as a percentage growth rate - percentage"
cap label var V97142 "Two-year old enterprises employment growth rate: number of persons employed in the reference period (t) among enterprises newly born in t-2 having survived to t divided by the number of persons employed in t-2 by the same enterprises, expressed as a percentage growth rate - percentage"
cap label var V97143 "Three-year old enterprises employment growth rate: number of persons employed in the reference period (t) among enterprises newly born in t-3 having survived to t divided by the number of persons employed in t-3 by the same enterprises, expressed as a percentage growth rate - percentage"
cap label var V97144 "Four-year old enterprises employment growth rate: number of persons employed in the reference period (t) among enterprises newly born in t-4 having survived to t divided by the number of persons employed in t-4 by the same enterprises, expressed as a percentage growth rate - percentage"
cap label var V97145 "Five-year old enterprises employment growth rate: number of persons employed in the reference period (t) among enterprises newly born in t-5 having survived to t divided by the number of persons employed in t-5 by the same enterprises, expressed as a percentage growth rate - percentage"
cap label var V97151 "Employment share of 1 year old enterprises: Number of persons employed in enterprises newly born in t-1 having survived to t, divided by the number of persons employed in the population of active enterprises in t"
cap label var V97152 "Employment share of 2 year old enterprises: Number of persons employed in enterprises newly born in t-2 having survived to t, divided by the number of persons employed in the population of active enterprises in t - percentage"
cap label var V97153 "Employment share of 3 year old enterprises: Number of persons employed in enterprises newly born in t-3 having survived to t, divided by the number of persons employed in the population of active enterprises in t - percentage"
cap label var V97154 "Employment share of 4 year old enterprises: Number of persons employed in enterprises newly born in t-4 having survived to t, divided by the number of persons employed in the population of active enterprises in t - percentage"
cap label var V97155 "Employment share of 5 year old enterprises: Number of persons employed in enterprises newly born in t-5 having survived to t, divided by the number of persons employed in the population of active enterprises in t - percentage"
cap label var V97161 "Average size of one-year old enterprises: number of persons employed in the reference period (t) among enterprises newly born in t-1 having survived to t divided by the number of enterprises in t newly born in t-1 having survived to t - number"
cap label var V97162 "Average size of two-year old enterprises: number of persons employed in the reference period (t) among enterprises newly born in t-2 having survived to t divided by the number of enterprises in t newly born in t-2 having survived to t - number"
cap label var V97163 "Average size of three-year old enterprises: number of persons employed in the reference period (t) among enterprises newly born in t-3 having survived to t divided by the number of enterprises in t newly born in t-3 having survived to t - number"
cap label var V97164 "Average size of four-year old enterprises: number of persons employed in the reference period (t) among enterprises newly born in t-4 having survived to t divided by the number of enterprises in t newly born in t-4 having survived to t - number"
cap label var V97165 "Average size of five-year old enterprises: number of persons employed in the reference period (t) among enterprises newly born in t-5 having survived to t divided by the number of enterprises in t newly born in t-5 having survived to t - number"
cap label var V97241 "Enterprises newly born in the year (n) having survived to n+1 - number"
cap label var V97242 "Enterprises newly born in the year (n) having survived to n+2 - number"
cap label var V97243 "Enterprises newly born in the year (n) having survived to n+3 - number"
cap label var V97244 "Enterprises newly born in the year (n) having survived to n+4 - number"
cap label var V97245 "Enterprises newly born in the year (n) having survived to n+5 - number"
cap label var V97251 "Cohort survival rate 1: newly born enterprises in the year (n) having survived to (n+1) divided by the number of enterprise births in (n) - number"
cap label var V97252 "Cohort survival rate 2: newly born enterprises in the year (n) having survived to (n+2) divided by the number of enterprise births in (n) - number"
cap label var V97253 "Cohort survival rate 3: newly born enterprises in the year (n) having survived to (n+3) divided by the number of enterprise births in (n) - number"
cap label var V97254 "Cohort survival rate 4: newly born enterprises in the year (n) having survived to (n+4) divided by the number of enterprise births in (n) - number"
cap label var V97255 "Cohort survival rate 5: newly born enterprises in the year (n) having survived to (n+5) divided by the number of enterprise births in (n) - number"
cap label var V97341 "Persons employed in the survival year among enterprises newly born in (n) having survived to n+1 - number"
cap label var V97342 "Persons employed in the survival year among enterprises newly born in (n) having survived to n+2 - number"
cap label var V97343 "Persons employed in the survival year among enterprises newly born in (n) having survived to n+3 - number"
cap label var V97344 "Persons employed in the survival year among enterprises newly born in (n) having survived to n+4 - number"
cap label var V97345 "Persons employed in the survival year among enterprises newly born in (n) having survived to n+5 - number"
cap label var V97351 "Persons employed in the year of birth in the population of enterprises newly born in (n) having survived to n+1 - number"
cap label var V97352 "Persons employed in the year of birth in the population of enterprises newly born in (n) having survived to n+2 - number"
cap label var V97353 "Persons employed in the year of birth in the population of enterprises newly born in (n) having survived to n+3 - number"
cap label var V97354 "Persons employed in the year of birth in the population of enterprises newly born in (n) having survived to n+4 - number"
cap label var V97355 "Persons employed in the year of birth in the population of enterprises newly born in (n) having survived to n+5 - number"
cap label var V97361 "One-year old enterprises employment growth rate: persons employed in the year (n+1) among enterprises newly born in (n) having survived to n+1 divided by the number of persons employed in (n) by the same enterprises - number"
cap label var V97362 "Two-year old enterprises employment growth rate: persons employed in the year (n+2) among enterprises newly born in (n) having survived to n+2 divided by the number of persons employed in (n) by the same enterprises - number"
cap label var V97363 "Three-year old enterprises employment growth rate: persons employed in the year (n+3) among enterprises newly born in (n) having survived to n+3 divided by the number of persons employed in (n) by the same enterprises - number"
cap label var V97364 "Four-year old enterprises employment growth rate: persons employed in the year (n+4) among enterprises newly born in (n) having survived to n+4 divided by the number of persons employed in (n) by the same enterprises - number"
cap label var V97365 "Five-year old enterprises employment growth rate: persons employed in the year (n+5) among enterprises newly born in (n) having survived to n+5 divided by the number of persons employed in (n) by the same enterprises - number"
cap label var V97450 "Share of high growth enterprises in the population of active enterprises, measured in employment - percentage"
cap label var V97451 "Share of high growth enterprises in the population of active enterprises, measured in turnover - percentage"
cap label var V97452 "Share of young high growth enterprises (gazelles) in the population of active enterprises, measured in employment - percentage"
cap label var V97453 "Share of young high growth enterprises (gazelles) in the population of active enterprises, measured in turnover - percentage"
cap label var V97455 "Share of medium growth enterprises in the population of active enterprises measured in employment - percentage"
cap label var V97456 "Share of medium growth enterprises in the population of active enterprises measured in turnover - percentage"
cap label var V97457 "Share of young medium growth enterprises in the population of active enterprises measured in employment - percentage"
cap label var V97458 "Share of young medium growth enterprises in the population of active enterprises measured in turnover - percentage"
cap label var V97460 "Share of high growth enterprises measured in employment: number of high growth enterprises divided by the number of active enterprises with at least 10 employees - percentage"
cap label var V97461 "Employment share of high growth enterprises measured in employment: number of employees among high growth divided by the number of employees among the stock of active enterprises with at least 10 employees - percentage"
cap label var V97462 "Average size of high growth enterprises measured in employment: number of employees in the reference period (t) among high growth enterprises measured in employment in t divided by the number of high growth enterprises measured in employment in t - number"
cap label var V99110 "Turnover at constant prices - million euro"
cap label var V99120 "Production value at constant prices - million euro"
cap label var V99150 "Value added at factor cost at constant prices - million euro"
