cap label var GSP_MIO_NAC "Gross social protection in millions of national currency"
cap label var NSP_MIO_NAC "Net social protection in millions of national currency"
cap label var GSP_MIO_EUR "Gross social protection in millions of Euros"
cap label var NSP_MIO_EUR "Net social protection in millions of Euros"
cap label var NSP_PC_GSP "Net social protection as a percentage of gross social protection"
cap label var GSP_PC_GDP "Gross social protection as a percentage of GDP"
cap label var NSP_PC_GDP "Net social protection as a percentage of GDP"
cap label var SPB_PC_TSC "Percentage of social protection benefits subject to taxation or social contributions"
cap label var SPB_PC_TAX "Percentage of social protection benefits subject to taxation"
cap label var SPB_PC_SC "Percentage of social protection benefits subject to social contributions"
cap label var SPC_PC_TSC "Percentage of social protection cash benefits subject to taxation or social contributions"
cap label var SPC_PC_TAX "Percentage of social protection cash benefits subject to taxation"
cap label var SPC_PC_SC "Percentage of social protection cash benefits subject to social contributions"
cap label var TSC_RT_LE "Effective combined taxation and social contribution rates on benefits subject to levies"
cap label var TSC_RT_SPB "Effective combined taxation and social contribution rates on all social protection benefits"
cap label var FBE_MIO_EUR "Residual fiscal benefits in millions of Euros"
