cap label var TOTAL "Total"
cap label var BRD_EXT "In the external border area"
cap label var BCP_SLA "At the border crossing point – at sea, land, air"
cap label var BCP_S "Between border crossing points - at sea"
cap label var BCP_L "Between border crossing points - at land"
cap label var INL "In the inland area"
