cap label var GHG "Greenhouse gases (CO2, N2O in CO2 equivalent, CH4 in CO2 equivalent, HFC in CO2 equivalent, PFC in CO2 equivalent, SF6 in CO2 equivalent, NF3 in CO2 equivalent)"
cap label var CO2_N2O_CH4_CO2E "Greenhouse gases (CO2, N2O in CO2 equivalent, CH4 in CO2 equivalent)"
cap label var CO2 "Carbon dioxide"
cap label var CH4 "Methane"
cap label var CH4_CO2E "Methane (CO2 equivalent)"
cap label var N2O "Nitrous oxide"
cap label var N2O_CO2E "Nitrous oxide (CO2 equivalent)"
cap label var HFC_PFC_NF3_SF6_CO2E "Fluorinated gases (HFC in CO2 equivalent, PFC in CO2 equivalent, NF3_SF6 in CO2 equivalent)"
cap label var HFC_CO2E "Hydrofluorocarbones (CO2 equivalent)"
cap label var PFC_CO2E "Perfluorocarbones (CO2 equivalent)"
cap label var HFC_PFC_NSP_CO2E "Hydrofluorocarbones and perfluorocarbones - not specified mix (CO2 equivalent)"
cap label var SF6_CO2E "Sulphur hexafluoride (CO2 equivalent)"
cap label var NF3_CO2E "Nitrogen trifluoride (CO2 equivalent)"
cap label var NF3_SF6 "Nitrogen trifluoride and sulphur hexafluoride"
cap label var NF3_SF6_CO2E "Nitrogen trifluoride and sulphur hexafluoride (CO2 equivalent)"
cap label var CO2_BIO "Carbon dioxide from biomass used as a fuel"
cap label var ACG "Acidifying gases (SOX in SO2 equivalent, NOX in SO2 equivalent, NH3 in SO2 equivalent)"
cap label var SOX_SO2E "Sulphur oxides (SO2 equivalent)"
cap label var NOX_NO2E "Nitrogen oxides (NO2 equivalent)"
cap label var NOX_SO2E "Nitrogen oxides (SO2 equivalent)"
cap label var NH3_SO2E "Ammonia (SO2 equivalent)"
cap label var O3PR "Ozone precursors (NMVOC, NOX in NMVOC equivalent, CO in NMVOC equivalent, CH4 in NMVOC equivalent)"
cap label var NOX_NMVOCE "Nitrogen oxides (NMVOC equivalent)"
cap label var CO "Carbon monoxide"
cap label var CO_NMVOCE "Carbon monoxide (NMVOC equivalent)"
cap label var CH4_NMVOCE "Methane (NMVOC equivalent)"
cap label var PM "Particulates"
cap label var O3 "Ozone"
cap label var PB "Lead (Pb)"
cap label var SO2 "Sulphur dioxide"
cap label var NOX "Nitrogen oxides"
cap label var NO2 "Nitrogen dioxide"
cap label var SOX "Sulphur oxides"
cap label var NH3 "Ammonia"
cap label var PM2_5 "Particulates < 2.5µm"
cap label var PM10 "Particulates < 10µm"
cap label var NMVOC "Non-methane volatile organic compounds"
cap label var AS "Arsenic (As)"
cap label var CD "Cadmium (Cd)"
cap label var HG "Mercury (Hg)"
cap label var CR "Chromium (Cr)"
cap label var CU "Copper (Cu)"
cap label var NI "Nickel (Ni)"
cap label var SE "Selenium (Se)"
cap label var ZN "Zinc (Zn)"
cap label var VOC "Volatile organic compounds"
cap label var HFC "Hydrofluorocarbons"
cap label var PFC "Perfluorocarbons"
cap label var SF6 "Sulphur hexafluoride"
