cap label var TOTAL "Total"
cap label var POS "Positive decision"
cap label var POS_RFG "Positive decision - refugee status"
cap label var POS_HUM "Positive decision - humanitarian status"
cap label var POS_SPROT "Positive decision - subsidiary protection status"
cap label var POS_TPROT "Positive decision - temporary protection status"
cap label var POS_PART "Partially positive decision"
cap label var POS_OTH "Positive decision - other"
cap label var NSTA "Non-status decision"
cap label var NEG "Negative decision"
cap label var PEN "Decision pending at the end of the period"
cap label var CHG "Decision to change"
cap label var RNEW "Decision to renew"
cap label var GRNT "Decision to grant"
cap label var GRNT_FRST "Decision to grant first permit"
cap label var WDN "Decision to withdraw"
cap label var NOTF_RECV "Notification received"
cap label var NOTF_OBJ "Notification objected"
cap label var TOTAL_POS "Total positive decisions"
cap label var GENCONV "Geneva Convention status"
cap label var HUMSTAT "Humanitarian status"
cap label var OTH_POS "Other positive decisions"
cap label var OTH_NONST "Other non-status decisions"
cap label var APP_PENDING "Applications pending at the end of the period"
cap label var GRANTED "Granted"
cap label var FIRST "First permit"
cap label var CHANGED "Changed"
cap label var RENEWED "Renewed"
cap label var WITHDRAWN "Withdrawn"
cap label var SUB_PROT "Subsidiary protection status"
cap label var TEMP_PROT "Temporary protection status"
cap label var REJECTED "Rejected"
cap label var ACC "Requests accepted"
cap label var PART "Requests partially accepted"
cap label var REF "Requests refused"
cap label var RECV "Notifications received"
cap label var OBJ "Notifications objected"
cap label var SOV "Sovereignty clause (Article 17.1)"
cap label var RESP_DEF "Responsibility by default"
cap label var RD_NCRI "Responsibility by default: No prior criteria applicable (Article 3.2 first par.)"
cap label var RD_NTRF "Responsibility by default: No transfer (Article 3.2 first and second par.)"
cap label var RD_NTL "Responsibility by default: Transfer not carried out within time limits (Article 29.2)"
cap label var UNK "Unknown"
