cap label var TOTAL "Total"
cap label var HEIGHT "Height"
cap label var WEIGHT "Weight"
cap label var N_EODS_OBL "Number of cases, non-fatal, EODS obligatory list"
cap label var I_EODS_OBL "Incidence rate, non-fatal, EODS obligatory list"
cap label var EM0611 "Index of the number of serious accidents at work per 100 thousand persons in employment (1998=100)"
cap label var EM0612 "Index of the number of serious accidents at work for women per 100 thousand females in employment (1998=100)"
cap label var EM0613 "Index of the number of serious accidents at work for men per 100 thousand males in employment (1998=100)"
cap label var EM062 "Index of the number of fatal accidents at work per 100 thousand persons in employment (1998=100)"
cap label var F_0_DFLE "Healthy life years in absolute value at birth - females"
cap label var F_0_DFLEPC "Healthy life years at birth in percentage of the total life expectancy - females"
cap label var F_0_LE "Life expectancy in absolute value at birth - females"
cap label var M_0_DFLE "Healthy life years in absolute value at birth - males"
cap label var M_0_DFLEPC "Healthy life years at birth in percentage of the total life expectancy - males"
cap label var M_0_LE "Life expectancy in absolute value at birth - males"
cap label var F_50_DFLE "Healthy life years in absolute value at 50 - females"
cap label var F_50_DFLEPC "Healthy life years at 50 in percentage of the total life expectancy - females"
cap label var F_50_LE "Life expectancy in absolute value at 50 - females"
cap label var M_50_DFLE "Healthy life years in absolute value at 50 - males"
cap label var M_50_DFLEPC "Healthy life years at 50 in percentage of the total life expectancy - males"
cap label var M_50_LE "Life expectancy in absolute value at 50 - males"
cap label var F_65_DFLE "Healthy life years in absolute value at 65 - females"
cap label var F_65_DFLEPC "Healthy life years at 65 in percentage of the total life expectancy - females"
cap label var F_65_LE "Life expectancy in absolute value at 65 - females"
cap label var M_65_DFLE "Healthy life years in absolute value at 65 - males"
cap label var M_65_DFLEPC "Healthy life years at 65 in percentage of the total life expectancy - males"
cap label var M_65_LE "Life expectancy in absolute value at 65 - males"
cap label var HE_BIRTH "Health expectancy in absolute values at birth"
cap label var HE_50 "Health expectancy in absolute values at 50"
cap label var HE_65 "Health expectancy in absolute values at 65"
cap label var HLY_0 "Healthy life years in absolute value at birth"
cap label var HLY_PC_0 "Healthy life years at birth in percentage of the total life expectancy"
cap label var LE_0 "Life expectancy in absolute value at birth"
cap label var HLY_50 "Healthy life years in absolute value at 50"
cap label var HLY_PC_50 "Healthy life years at 50 in percentage of the total life expectancy"
cap label var LE_50 "Life expectancy in absolute value at 50"
cap label var HLY_65 "Healthy life years in absolute value at 65"
cap label var HLY_PC_65 "Healthy life years at 65 in percentage of the total life expectancy"
cap label var LE_65 "Life expectancy in absolute value at 65"
cap label var DISCH "Discharges"
cap label var ALOS "In-patient average length of stay (in days)"
cap label var DAY_HOSP "Bed-days"
cap label var INPAT "in-patients (total number)"
cap label var ONE_DAY "Day cases (total number)"
cap label var AMEN "Amenable deaths"
cap label var YLL "Years of life lost"
cap label var PMD "Premature death"
