cap label var TOTAL "Total"
cap label var TYNG_SPK "Too young to speak"
cap label var MOT "Mother tongue"
cap label var PROF "Proficient"
cap label var GOOD "Good"
cap label var FAIR "Fair"
cap label var INT "Intermediate"
cap label var MOD "Moderate"
cap label var BASIC "Basic"
cap label var NONE_MIN "None or minimum"
cap label var NONE "None"
cap label var NAP "Not applicable"
cap label var NRP "No response"
