cap label var EE1000 "Environmental protection expenditure"
cap label var EE1100 "Total environmental investments"
cap label var EE1110 "Pollution treatment investments"
cap label var EE1120 "Pollution prevention investments"
cap label var EE1125 "Pollution prevention investments as % of total environmental protection investments"
cap label var EE1200 "Total environmental current expenditure"
cap label var EE1210 "Environmental in-house current expenditure"
cap label var EE1220 "Environmental fees and purchases"
cap label var EE1300 "Receipts from by-products of environmental services"
cap label var EE1400 "Environmental subsidies/transfers"
cap label var EE1500 "Revenues from sales of environmental services"
cap label var EE1610 "Environmental protection investments as % of gross fixed capital formation (GFCF)"
cap label var EE1620 "Current expenditure on environmental protection as % of output"
