cap label var TOTAL "Total"
cap label var TRN_GD "Goods trains"
cap label var TRN_PAS "Passenger trains"
cap label var TRN_OTH "Other trains"
cap label var STCL1 "Seats, first class"
cap label var STCL2 "Seats, second class"
cap label var STMIX "Mixed seats"
cap label var DIN "Dining cars"
cap label var COU "Couchette coaches, sleepling cars"
cap label var BRT "Berths in couchettes and sleeping cars"
