cap label var TOTAL "Total"
cap label var AP_PE "Apple and pear trees"
cap label var AP "Apple trees"
cap label var APD "Dessert apple trees"
cap label var APD_BKP "Boskoop group"
cap label var APD_BRB "Braeburn group"
cap label var APD_COO "Cox Orange group"
cap label var APD_CRP "Cripps Pink group"
cap label var APD_ELR "Elstar group"
cap label var APD_FUJ "Fuji group"
cap label var APD_GAL "Gala group"
cap label var APD_GOD "Golden Delicious group"
cap label var APD_GRS "Granny Smith group"
cap label var APD_IDR "Idared group"
cap label var APD_JON "Jonagold/Jonagored group"
cap label var APD_MOD "Morgenduft group"
cap label var APD_RED "Red Delicious group"
cap label var APD_RBC "Reinette group"
cap label var APD_SHP "Shampion group"
cap label var APD_LOB "Lobo group"
cap label var APD_PIN "Pinova group"
cap label var APD_OTH "Other dessert apples n.e.c."
cap label var API "Apple trees plantation for industrial processing"
cap label var PE "Pear trees"
cap label var PED "Dessert pear trees"
cap label var PED_CFR "Conference group"
cap label var PED_WIL "Williams group"
cap label var PED_ABT "Abate group"
cap label var PED_ROC "Rocha group"
cap label var PED_COE "Coscia-Ercolini group"
cap label var PED_GYT "Guyot group"
cap label var PED_BLQ "Blanquilla group"
cap label var PED_DCN "Decana group"
cap label var PED_KAS "Kaiser group"
cap label var PED_OTH "Other dessert pears n.e.c."
cap label var PEI "Pear trees for industrial processing"
cap label var PC_APC "Peach, nectarine and apricot trees"
cap label var PC "Peach and nectarine trees"
cap label var PCD "Dessert peach and nectarine trees"
cap label var PCD_PEA "Peaches for fresh consumption"
cap label var PCD_PEAY "Yellow flesh peaches"
cap label var PCD_PEAY_VE "Very early yellow flesh peaches"
cap label var PCD_PEAY_E "Early yellow flesh peaches"
cap label var PCD_PEAY_M "Medium-early yellow flesh peaches"
cap label var PCD_PEAY_L "Late yellow flesh peaches"
cap label var PCD_PEAW "White flesh peaches"
cap label var PCD_PEAW_VE "Very early white flesh peaches"
cap label var PCD_PEAW_E "Early white flesh peaches"
cap label var PCD_PEAW_M "Medium-early white flesh peaches"
cap label var PCD_PEAW_L "Late white flesh peaches"
cap label var PCD_PEAD "Doughnut peaches"
cap label var PCD_NEC "Nectarines for fresh consumption"
cap label var PCD_NECY "Yellow flesh nectarines"
cap label var PCD_NECY_VE "Very early yellow flesh nectarines"
cap label var PCD_NECY_E "Early yellow flesh nectarines"
cap label var PCD_NECY_M "Medium-early yellow flesh nectarines"
cap label var PCD_NECY_L "Late yellow flesh nectarines"
cap label var PCD_NECW "White flesh nectarines"
cap label var PCD_NECW_VE "Very early white flesh nectarines"
cap label var PCD_NECW_E "Early white flesh nectarines"
cap label var PCD_NECW_M "Medium-early white flesh nectarines"
cap label var PCD_NECW_L "Late white flesh nectarines"
cap label var PCI "Peach and nectarine trees for industrial processing (including group of Pavie)"
cap label var APC "Apricot trees"
cap label var APC_VE "Very early apricots (harvest until 31 May)"
cap label var APC_E "Early apricots (harvest between 1 and 30 June)"
cap label var APC_M "Medium-early apricots (harvest between 1 and 31 July)"
cap label var APC_L "Late apricots (harvest after 1 August)"
cap label var ORA_SCF_LEM "Orange, small citrus fruit and lemon trees"
cap label var ORA "Orange trees"
cap label var ORA_NVL "Navel oranges"
cap label var ORA_NVL_E "Early Navel oranges"
cap label var ORA_NVL_M "Medium-early Navel oranges"
cap label var ORA_NVL_L "Late Navel oranges"
cap label var ORA_BLC "Blancas oranges"
cap label var ORA_BLC_E "Early Blancas oranges"
cap label var ORA_BLC_L "Late Blancas oranges"
cap label var ORA_SGU "Sanguine oranges"
cap label var ORA_OTH "Other oranges n.e.c."
cap label var SCF "Small citrus fruit trees"
cap label var SCF_STM "Satsumas"
cap label var SCF_STM_VE "Extra-early satsumas"
cap label var SCF_STM_OTH "Other satsumas"
cap label var SCF_CLM "Clementines"
cap label var SCF_CLM_E "Early clementines"
cap label var SCF_CLM_M "Medium-early clementines"
cap label var SCF_CLM_L "Late clementines"
cap label var SCF_OTH "Other small citrus fruits including hybrids"
cap label var LEM "Lemon trees"
cap label var LEM_WI "Winter lemon varieties"
cap label var LEM_SU "Summer lemon varieties"
cap label var OLI "Olive trees"
cap label var OLIT "Table olives"
cap label var OLIO "Olives for oil"
cap label var ODP "Dual purpose olives"
cap label var GRV "Table grape vines"
cap label var GRV_W "White table grape vines"
cap label var GRV_WSDL "Seedless white table grape vines"
cap label var GRV_WNML "Normal white table grape vines"
cap label var GRV_R "Red table grape vines"
cap label var GRV_RSDL "Seedless red table grape vines"
cap label var GRV_RNML "Normal red table grape vines"
