cap label var TOTAL "Total"
cap label var FRW "Fresh surface and groundwater"
cap label var FSW "Fresh surface water"
cap label var FGW "Fresh groundwater"
cap label var NFW "Non fresh water"
cap label var DSW "Desalinated water"
cap label var RUW "Reused water"
cap label var NRGW "Non renewable groundwater"
cap label var IMP "Imports of water"
cap label var EXP "Exports of water"
cap label var WAU "Water available for use"
cap label var PRECIP "Precipitation"
cap label var RFW_RES "Renewable freshwater resources"
cap label var REW "Water returned without use"
cap label var WW "Wastewater"
cap label var RUWW_T "Reused treated wastewater"
cap label var RUWW_T_NT "Reused treated and untreated wastewater"
