cap label var YES "Yes"
cap label var NO "No"
cap label var NRP "No answer"
cap label var NAP "Not applicable"
cap label var UNK "Unknown"
cap label var OTH "Any other type of working schedule"
cap label var TOTAL "Total"
cap label var TCARE1 "Childcare services (including paid childminders), pre-school"
cap label var TCARE2 "Partner who is living in the household"
cap label var TCARE3 "Relatives/neighbours/friends (unpaid)"
cap label var TCARE4 "No childcare used"
cap label var TCRED9 "Not applicable (the respondent has no child up to 14 years old in the household or/and is not working)"
cap label var RCARE1 "The person regularly takes care of other children up to 14"
cap label var RCARE2 "The person regularly takes care of relatives/friends aged 15 or more in need of care"
cap label var RCARE3 "The person regularly takes care of other children up to 14 and of relatives/friends aged 15 or more in need of care"
cap label var CHORG2 "Wish to work or to work more (and reduce caring time)"
cap label var CHORG3 "Wish to work less to have more time for caring"
cap label var CHORG9 "Not applicable (the respondent cares of no child/relative/friend in need of care)"
cap label var NWCHI0 "No childcare services available"
cap label var NWCHI1 "Lack of childcare services during the day"
cap label var NWCHI2 "Lack of childcare services at special times"
cap label var NWCHI3 "Lack of childcare services during the day or at special times"
cap label var NWCHI4 "Childcare services are too expensive"
cap label var NWCHI5 "Available childcare services are not of sufficient quality"
cap label var NWCHI6 "Other reason not linked with the lack of suitable childcare services"
cap label var NWCHI7 "Other reason linked with the lack of suitable childcare services"
cap label var NWCHI9 "Not applicable (the respondent does not wish to work or work more and reduce the time for caring about children up to 14 and/or has no care responsibility)"
cap label var REDUC2 "The person took special arrangements because of lack of alternative childcare services during the day"
cap label var REDUC3 "The person took special arrangements because of lack of alternative childcare services at special times"
cap label var REDUC4 "The person took special arrangements because alternative childcare services too expensive"
cap label var REDUC5 "The person took special arrangements because alternative childcare services not of sufficient quality"
cap label var REDUC6 "The person took special arrangements, always because of other reasons"
cap label var NWCAR0 "No care services available"
cap label var NWCAR1 "Lack of care services during the day"
cap label var NWCAR2 "Lack of care services at special times"
cap label var NWCAR3 "Lack of care services during the day or at special times"
cap label var NWCAR4 "Care services are too expensive"
cap label var NWCAR5 "Available care services are not of sufficient quality"
cap label var NWCAR6 "Other reason not linked with the lack of suitable care services"
cap label var NWCAR7 "Other reason linked with the lack of suitable care services"
cap label var NWCAR9 "Not applicable (the respondent does not wish to work or work more and reduce the time for caring about relatives/friends in need of care)"
cap label var POSTO1 "Generally possible"
cap label var POSTO2 "Rarely possible"
cap label var POSTO3 "Not possible"
cap label var TMOFF2 "Yes, 'special leave' days remunerated"
cap label var TMOFF3 "Yes, 'special leave' days not at all remunerated"
cap label var TMOFF4 "Yes, other arrangements always used"
cap label var POSTIM9 "Not applicable (the respondent is not working)"
cap label var RDHR3 "No, but the person plans to do so within the next 5 years"
cap label var RDHR45 "No and the person has no plans or does not know for the next 5 years"
cap label var PAGS94 "Between 50 and 59 years old"
cap label var PAGS95 "Between 60 and 64 years old"
cap label var PAGS96 "At 65 years old or after or the person plans to work as long as possible"
cap label var PAGS97 "No exact planned age and the person does not know at all when he/she will stop working"
cap label var PAGS98 "The person has already stopped all work for pay or profit"
cap label var STAFT1 "Unemployed"
cap label var STAFT2 "In retirement or early retirement"
cap label var STAFT3 "Long term sick or disabled"
cap label var STAFT4 "Any other main reason for retirement or early retirement"
cap label var FXWRK1 "More flexible working time arrangements would contribute/have contributed to person staying longer at work"
cap label var FXWRK2 "More flexible working time arrangements would not contribute/have contributed to person staying longer at work"
cap label var OPSKL1 "More opportunities to update skills would contribute/have contributed to person staying longer at work"
cap label var OPSKL2 "More opportunities to update skills would not contribute/have contributed to person staying longer at work"
cap label var HLSAF1 "Better health and/or safety at work would contribute/have contributed to person staying longer at work"
cap label var HLSAF2 "Better health and/or safety at work would not contribute/have contributed to person staying longer at work"
cap label var OTBNF1 "A disability pension or a sick pension"
cap label var OTBNF2 "An early retirement scheme allowance"
cap label var OTBNF3 "Another individual benefit not elsewhere classified"
cap label var OTBNF4 "Combination of the three previous cases"
cap label var FINCT1 "To increase retirement pension entitlements"
cap label var FINCT2 "To provide sufficient household income"
cap label var FINCT3 "No financial incentive"
cap label var RRT158 "Job lost or job-related problems or other"
cap label var RRT27 "Reached retirement age or preference to stop working"
cap label var RRT346 "Health or care-related or financial reasons"
cap label var OWNMS0 "Person cannot determine how or when to do the work"
cap label var OWNMS1 "Person can determine how to do the work"
cap label var OWNMS2 "Person can determine when to do the work"
cap label var OWNMS3 "Person can determine when and how to do the work"
cap label var OWNMS8 "Person does not know"
cap label var SINCU0 "Works regularly for more than one client or customer"
cap label var SINCU1 "Works regularly for just one client or customer"
cap label var SHPAT1 "Continuous shift work, usually four-shift system"
cap label var SHPAT2 "Semi-continuous shift work, usually three-shift system"
cap label var SHPAT3 "Two-shift system: double day-shift"
cap label var SHPAT4 "Sometimes night, sometimes day-shift"
cap label var SHPAT5 "Fixed shift work"
cap label var SHPAT6 "Other type of shift work"
cap label var ANWKH0 "Person does not have an annualised hours contract"
cap label var ANWKH1 "Person has an annualised hours contract"
cap label var OCLWK0 "Person is not on an on-call job"
cap label var OCLWK1 "Person reports to work only when called"
cap label var WKPFT1 "Less hours per day"
cap label var WKPFT2 "Half a day less per week"
cap label var WKPFT3 "Less days per week"
cap label var WKPFT4 "Less hours per day and less days per week"
cap label var WKPFT5 "One week in two"
cap label var WKPFT6 "Any other working time pattern"
cap label var VARHR1 "Person has reduced her or his credit hours"
cap label var VARHR2 "Person has taken a few hours off (without the need to take holidays)"
cap label var VARHR3 "Person has taken half a day, one or more days off"
cap label var VARHR4 "Person has reduced her/his credit hours balance or has taken a few hours off and has also taken half a day, one or more days off (on different days of the week)"
cap label var VARHR5 "Person wanted to take credit hours but could not do so (and has not taken holidays)"
cap label var VARHR6 "Person wanted to take a few hours, half a day, one or more days off but could not do so"
cap label var VARHR7 "Other (hours actually worked is more than contractual, lay-off etc.)"
cap label var WKT1P0 "Shift work or on-call work is not convenient for personal life situation"
cap label var WKT1P1 "Shift work is convenient for personal life situation"
cap label var WKT1P2 "On-call work is convenient for personal life situation"
cap label var WKT2P1 "Work in the evening, at night or during weekend is convenient for personal life situation"
cap label var WKT2P3 "Work in the evening, at night or during weekend is not convenient for personal life situation"
cap label var VAWKH1 "Fixed start and end of a working day"
cap label var VAWKH2 "Staggered working hours, banded start and end"
cap label var VAWKH3 "Working time banking with possibility only to take hours off"
cap label var VAWKH4 "Working time banking with possibility to take full days off (besides taking hours off)"
cap label var VAWKH5 "Start and end of working day varying by individual agreement"
cap label var VAWKH6 "Determines own work schedule (no formal boundaries)"
cap label var VAWKH7 "Any other type of variable working hours"
cap label var DETMS0 "Subordinate relationship"
cap label var DETMS1 "Determines own work methods and schedule"
cap label var SINGF0 "Works regularly for more than one firm or customer"
cap label var SINGF1 "Works regularly for one firm or customer"
cap label var TERCT1 "Job or work ceases to exist when product or services are provided"
cap label var TERCT2 "Temporary job under contract for a fixed period"
cap label var TERCT3 "Job or work continues to exist after product or services are provided"
cap label var VAWKT1 "Fixed start and end of a working day or varying working time as decided by the employer"
cap label var VAWKT2 "Annualised hours contract"
cap label var VAWKT3 "Flexitime/working time banking"
cap label var VAWKT4 "Daily number of hours fixed, but some flexibility within the day"
cap label var VAWKT5 "Determines own work schedule (no formal boundaries)"
cap label var VAWKT6 "Other"
cap label var CMCRH0 "Cannot use credit hours to take full days or weeks off"
cap label var CMCRH1 "Can use credit hours to take full days or weeks off (besides to take hours off)"
cap label var CONTH0 "Other"
cap label var CONTH1 "A minimum number of hours is agreed by contract but the number of hours actually worked may exceed this minimum and they are not paid at overtime rate"
cap label var CONTH2 "Reports to work only when called"
cap label var RESHW1 "Shift work was the type of job person was looking for (personal initiative)"
cap label var RESHW2 "Shift work was not the type of job person was looking for but no similar job available without shift work (similar within this occupation or industry)"
cap label var REWAR1 "These working time arrangements were the type of job person was looking for (personal initiative)"
cap label var REWAR2 "These working time arrangements were not the type of job person was looking for but no similar job available with ordinary working time arrangements (similar within this occupation or industry)"
cap label var ANYPENS "Persons receiving any pension"
cap label var STATOAP "Persons receiving only statutory old-age pension"
cap label var ONLYOAP "Persons receiving only an old-age pension"
cap label var FINARR "Favourable financial arrangements to leave"
cap label var NOTJOB "Lost job and/or could not find a job"
cap label var MAXAGE "Had reached the maximum retirement age"
cap label var ELIGIB "Had reached eligibility for a pension"
cap label var OTHJRR "Other job-related reasons"
cap label var HEALTH "Own health or disability"
cap label var FAMCAR "Family or care-related reasons"
cap label var OTHREA "Other reasons"
cap label var PENENT "To establish or increase future retirement pension entitlements"
cap label var SUFINC "To provide sufficient personal/household income"
cap label var ENTINC "To establish/increase future retirement pension entitlements and to provide sufficient personal/household income"
cap label var NONFIN "Non-financial reasons, e.g. work satisfaction"
