cap label var TOTAL "Total - all products"
cap label var SITC0_4 "Primary goods"
cap label var SITC0_4A "Primary goods excluding SITC division 33"
cap label var SITC0_1 "Food, drinks and tobacco"
cap label var SITC0 "Food and live animals"
cap label var SITC1 "Beverages and tobacco"
cap label var SITC2_4 "Raw materials"
cap label var SITC2 "Crude materials, inedible, except fuels"
cap label var SITC3 "Mineral fuels, lubricants and related materials"
cap label var SITC33 "Petroleum, petroleum products and related materials"
cap label var SITC4 "Animal and vegetable oils, fats and waxes"
cap label var SITC5_8 "Manufactured goods"
cap label var SITC5 "Chemicals and related products, n.e.s."
cap label var SITC6_8 "Other manufactured goods"
cap label var SITC6 "Manufactured goods classified chiefly by material"
cap label var SITC7 "Machinery and transport equipment"
cap label var SITC8 "Miscellaneous manufactured articles"
cap label var SITC9 "Commodities and transactions not classified elsewhere in the SITC"
cap label var TOT_HT "Total high-tech products"
cap label var AER "Aerospace"
cap label var COM "Computers-office machines"
cap label var ELT "Electronics-telecommunications"
cap label var PHA "Pharmacy"
cap label var SCI "Scientific instruments"
cap label var ELM "Electrical machinery"
cap label var CHE "Chemistry"
cap label var NEM "Non-electrical machinery"
cap label var ARM "Armament"
