cap label var TOTAL "Total"
cap label var SRS "Serious accidents"
cap label var SRS_F "Serious accidents - women"
cap label var SRS_M "Serious accidents - men"
cap label var FATAL "Fatal accidents"
cap label var COLLIS "Collisions of trains, including collisions with obstacles within the clearance gauge"
cap label var COLLIS_X_LVLCROS "Collisions (excluding level-crossing accidents)"
cap label var DERAIL "Derailments of trains"
cap label var DGD "Accidents involving transport of dangerous goods"
cap label var NDGD "Accidents not involving transport of dangerous goods"
cap label var DGD_RL "Accidents in which dangerous goods are released"
cap label var DGD_NRL "Accidents in which dangerous goods are not released"
cap label var LVLCROS "Level crossing accidents"
cap label var RSTK_MOT "Accidents to persons caused by rolling stock in motion"
cap label var RD_TRF "Road traffic"
cap label var HOM_SCH "Accident at home / school / leisure"
cap label var HOM_LEIS "Home and leisure"
cap label var HOM "Home"
cap label var LEIS "Leisure"
cap label var RSTK_FIRE "Fires in rolling stock"
cap label var FAT_NT "Fatalities in injury accidents on national territory (all operators)"
cap label var ACC_NT "Injury accidents on national territory (all operators)"
cap label var FAT_NC "Fatalities in injury accidents where a national company was involved (worldwide)"
cap label var ACC_NC "Injury accidents where a national company was involved (worldwide)"
cap label var OTH "Others"
cap label var UNK "Unknown"
