cap label var TOTAL "All presentation forms"
cap label var FRE "Fresh"
cap label var FRE_WHL "Fresh, whole"
cap label var FRE_GUT "Fresh, gutted"
cap label var FRE_GUH "Fresh, gutted and headed"
cap label var FRE_TAL "Fresh, tails"
cap label var FRE_FIL "Fresh, filleted"
cap label var FRE_PEL "Fresh, peeled and cleaned"
cap label var FRE_ALI "Fresh, alive"
cap label var FRE_OTH "Fresh, other"
cap label var FRE_NSP "Fresh, not specified"
cap label var FRO "Frozen"
cap label var FRO_WHL "Frozen, whole"
cap label var FRO_GUT "Frozen, gutted"
cap label var FRO_GUH "Frozen, gutted and headed"
cap label var FRO_TAL "Frozen, tails"
cap label var FRO_FIL "Frozen, filleted"
cap label var FRO_NFL "Frozen, not filleted"
cap label var FRO_CLE "Frozen, clean"
cap label var FRO_NCL "Frozen, not clean"
cap label var FRO_OTH "Frozen, other"
cap label var FRO_NSP "Frozen, not specified"
cap label var SAL "Salted"
cap label var SAL_WHL "Salted, whole"
cap label var SAL_GUT "Salted, gutted"
cap label var SAL_GUH "Salted, gutted and headed"
cap label var SAL_FIL "Salted, filleted"
cap label var SAL_OTH "Salted, other"
cap label var SAL_NSP "Salted, not specified"
cap label var SMO "Smoked"
cap label var COK "Cooked"
cap label var COK_FRO "Cooked, frozen and packed"
cap label var DRI "Dried"
cap label var DRI_WHL "Dried, whole"
cap label var DRI_GUT "Dried, gutted"
cap label var DRI_GUH "Dried, gutted and headed"
cap label var DRI_FIL "Dried, filleted"
cap label var DRI_OTH "Dried, other"
cap label var DRI_NSP "Dried, not specified"
cap label var CLA "Claws"
cap label var ROE "Roes"
cap label var WHL "Whole"
cap label var UNK "Presentation unknown"
