cap label var TOTAL "Total"
cap label var PET "Petroleum products"
cap label var LPG "Liquefied petroleum gases (LPG)"
cap label var DIE "Diesel"
cap label var GAS "Natural Gas"
cap label var ELC "Electricity"
cap label var ALT "Alternative Energy"
cap label var PET_X_HYB "Petrol (excluding hybrids)  "
cap label var ELC_PET_HYB_PI "Hybrid electric-petrol and plug-in hybrid petrol-electric  "
cap label var ELC_PET_HYB "Hybrid electric-petrol"
cap label var ELC_PET_PI "Plug-in hybrid petrol-electric  "
cap label var DIE_X_HYB "Diesel (excluding hybrids)  "
cap label var ELC_DIE_HYB_PI "Hybrid electric-diesel and plug-in hybrid diesel-electric  "
cap label var ELC_DIE_HYB "Hybrid diesel-electric"
cap label var ELC_DIE_PI "Plug-in hybrid diesel-electric  "
cap label var HYD_FCELL "Hydrogen and fuel cells "
cap label var BIOETH "Bioethanol"
cap label var BIODIE "Biodiesel"
cap label var BIFUEL "Bi-fuel"
cap label var CNG "Compressed natural gas (CNG)  "
cap label var LNG "Liquefied natural gas (LNG)  "
cap label var OTH "Other"
