cap label var SOURINT "Internet"
cap label var SOURFAM "Member of the family, neighbour, work colleague"
cap label var SOUREMPL "Employer"
cap label var SOURGUID "Career guidance provider (including employment service office)"
cap label var SOURSCH "An education or training institution (school, college, centre, university)"
cap label var SOURTV "Mass media (TV, radio, newspaper, poster)"
cap label var SOURBOOK "Books"
cap label var SOUROTHER "Other"
cap label var NLK "Did not look for information on learning possibilities"
cap label var LK_FD "Looked for and found information on learning possibilities"
cap label var LK_NFD "Looked for but did not find any information on learning possibilities"
cap label var NRESP "No answer"
