cap label var SL "Slaughterings"
cap label var GP "Gross indigenous production"
cap label var IL "Total imports of live animals"
cap label var IN "Intra-EU imports of live animals"
cap label var EL "Total exports of live animals"
cap label var LE "Export to third countries: live animals"
cap label var LI "Import from third countries: live animals"
cap label var EN "Export intra-EU: live animals"
cap label var SLD "Slaughterings, other than in slaughterhouses"
