cap label var TOTAL "Total (all sectors including memo items and indirect CO2)"
cap label var TOTXMEMO "Total (excluding memo items)"
cap label var TOTXMEMONIA "Total (excluding memo items, including international aviation)"
cap label var TOTX4_MEMO "Total (excluding LULUCF and memo items)"
cap label var TOTX4_MEMONIA "Total (excluding LULUCF and memo items, including international aviation)"
cap label var TOTX4_MEMONIT "Total (excluding LULUCF and memo items, including international transport)"
cap label var TOTXMEMONIT "Total (excluding memo items, including international transport)"
cap label var CRF_MEMO "Memo items"
cap label var CRF1 "Energy"
cap label var CRF1A "Fuel combustion - sectoral approach"
cap label var CRF1A1 "Fuel combustion in energy industries"
cap label var CRF1A1A "Fuel combustion in public electricity and heat production"
cap label var CRF1A1B "Fuel combustion in petroleum refining"
cap label var CRF1A1C "Fuel combustion in manufacture of solid fuels and other energy industries"
cap label var CRF1A2 "Fuel combustion in manufacturing industries and construction"
cap label var CRF1A2A "Fuel combustion in manufacture of iron and steel"
cap label var CRF1A2B "Fuel combustion in manufacture of non-ferrous metals"
cap label var CRF1A2C "Fuel combustion in manufacture of chemicals"
cap label var CRF1A2D "Fuel combustion in manufacture of pulp, paper and printing"
cap label var CRF1A2E "Fuel combustion in manufacture of food, beverages and tobacco"
cap label var CRF1A2F "Fuel combustion in manufacture of non-metallic mineral products"
cap label var CRF1A2G "Fuel combustion in other manufacturing industries and construction"
cap label var CRF1A3 "Fuel combustion in transport"
cap label var CRF1A3A "Fuel combustion in domestic aviation"
cap label var CRF1A3B "Fuel combustion in road transport"
cap label var CRF1A3B1 "Fuel combustion in cars"
cap label var CRF1A3B2 "Fuel combustion in light duty trucks"
cap label var CRF1A3B3 "Fuel combustion in heavy duty trucks and buses"
cap label var CRF1A3B4 "Fuel combustion in motorcycles"
cap label var CRF1A3B5 "Fuel combustion in other road transportation"
cap label var CRF1A3C "Fuel combustion in railways"
cap label var CRF1A3D "Fuel combustion in domestic navigation"
cap label var CRF1A3E "Fuel combustion in other transport"
cap label var CRF1A4 "Other fuel combustion sectors"
cap label var CRF1A4A "Fuel combustion in commercial and institutional sector"
cap label var CRF1A4B "Fuel combustion by households"
cap label var CRF1A4C "Fuel combustion in agriculture, forestry and fishing"
cap label var CRF1A5 "Other fuel combustion sectors n.e.c."
cap label var CRF1A5A "Stationary fuel combustion sectors n.e.c."
cap label var CRF1A5B "Mobile fuel combustion sectors n.e.c."
cap label var CRF1B "Fuels - fugitive emissions"
cap label var CRF1B1 "Solid fuels - fugitive emissions"
cap label var CRF1B2 "Oil, natural gas and other energy production - fugitive emissions"
cap label var CRF1C "Transport and storage of CO2 (memo item)"
cap label var CRF1D1 "International bunkers (memo item)"
cap label var CRF1D1A "International aviation (memo item)"
cap label var CRF1D1B "International navigation (memo item)"
cap label var CRF1D2 "Multilateral operations (memo item)"
cap label var CRF1D3 "Biomass - CO2 emissions (memo item)"
cap label var CRF2 "Industrial processes and product use"
cap label var CRF2A "Mineral industry"
cap label var CRF2A1 "Cement production"
cap label var CRF2A2 "Lime production"
cap label var CRF2A3 "Glass production"
cap label var CRF2A4 "Other process uses of carbonates"
cap label var CRF2B "Chemical industry"
cap label var CRF2B1 "Ammonia production"
cap label var CRF2B2 "Nitric acid production"
cap label var CRF2B3 "Adipic acid production"
cap label var CRF2B4 "Caprolactam, glyoxal and glyoxylic acid production"
cap label var CRF2B5 "Carbide production"
cap label var CRF2B6 "Titanium dioxide production"
cap label var CRF2B7 "Soda ash production"
cap label var CRF2B8 "Petrochemical and carbon black production"
cap label var CRF2B9 "Fluorochemical production"
cap label var CRF2B10 "Other chemical industry"
cap label var CRF2C "Metal industry"
cap label var CRF2C1 "Iron and steel production"
cap label var CRF2C2 "Ferroalloys production"
cap label var CRF2C3 "Aluminium production"
cap label var CRF2C4 "Magnesium production"
cap label var CRF2C5 "Lead production"
cap label var CRF2C6 "Zinc production"
cap label var CRF2C7 "Other metal industry"
cap label var CRF2D "Non-energy products from fuels and solvent use"
cap label var CRF2D1 "Lubricant use"
cap label var CRF2D2 "Paraffin wax use"
cap label var CRF2D3 "Other non-energy product use"
cap label var CRF2E "Electronics industry"
cap label var CRF2E1 "Integrated circuit or semiconductor production"
cap label var CRF2E2 "TFT flat panel display production"
cap label var CRF2E3 "Photovoltaic"
cap label var CRF2E4 "Heat transfer fluid"
cap label var CRF2E5 "Other electronics industry"
cap label var CRF2F "Product uses as substitutes for ozone depleting substances"
cap label var CRF2F1 "Refrigeration and air conditioning"
cap label var CRF2F2 "Foam blowing agent use"
cap label var CRF2F3 "Fire protection"
cap label var CRF2F4 "Aerosol use"
cap label var CRF2F5 "Solvent use"
cap label var CRF2F6 "Other applications of substitutes for ozone depleting substances"
cap label var CRF2G "Other product manufacture and use"
cap label var CRF2H "Other industrial process and product use"
cap label var CRF3 "Agriculture"
cap label var CRF31 "Livestock"
cap label var CRF3A "Enteric fermentation"
cap label var CRF3A1 "Enteric fermentation of cattle"
cap label var CRF3A2 "Enteric fermentation of sheep"
cap label var CRF3A3 "Enteric fermentation of swine"
cap label var CRF3A4 "Enteric fermentation of other livestock"
cap label var CRF3B "Manure management"
cap label var CRF3B1 "Cattle manure management"
cap label var CRF3B2 "Sheep manure management"
cap label var CRF3B3 "Swine manure management"
cap label var CRF3B4 "Other livestock manure management"
cap label var CRF3B5 "Manure management - indirect N2O emissions"
cap label var CRF3C "Rice cultivation"
cap label var CRF3C1 "Irrigated rice cultivation"
cap label var CRF3C2 "Rainfed rice cultivation"
cap label var CRF3C3 "Deep water rice cultivation"
cap label var CRF3C4 "Other rice cultivation"
cap label var CRF3D "Managed agricultural soils"
cap label var CRF3D1 "Managed agricultural soils - direct N2O emissions"
cap label var CRF3D2 "Managed agricultural soils - indirect N2O emissions"
cap label var CRF3E "Prescribed burning of savannas"
cap label var CRF3F "Field burning of agricultural residues"
cap label var CRF3F1 "Field burning of cereals residues"
cap label var CRF3F2 "Field burning of pulses residues"
cap label var CRF3F3 "Field burning of tubers and roots residues"
cap label var CRF3F4 "Field burning of sugar cane residues"
cap label var CRF3F5 "Field burning of other agricultural residues"
cap label var CRF3G "Liming"
cap label var CRF3H "Urea application"
cap label var CRF3I "Other carbon-containing fertilizers"
cap label var CRF3J "Other agriculture"
cap label var CRF4 "Land use, land use change, and forestry (LULUCF)"
cap label var CRF4A "Forest land"
cap label var CRF4A0 "Drainage and rewetting and other management of organic and mineral soils related to forest land - emissions and removals"
cap label var CRF4A1 "Unconverted forest land"
cap label var CRF4A2 "Land converted to forest land"
cap label var CRF4B "Cropland"
cap label var CRF4B0 "Drainage and rewetting and other management of organic and mineral soils related to cropland - emissions and removals"
cap label var CRF4B1 "Unconverted cropland"
cap label var CRF4B2 "Land converted to cropland"
cap label var CRF4C "Grassland"
cap label var CRF4C0 "Drainage and rewetting and other management of organic and mineral soils related to grassland - emissions and removals"
cap label var CRF4C1 "Unconverted grassland"
cap label var CRF4C2 "Land converted to grassland"
cap label var CRF4D "Wetlands"
cap label var CRF4D0 "Drainage and rewetting and other management of organic and mineral soils related to wetlands - emissions and removals"
cap label var CRF4D1 "Unconverted wetlands"
cap label var CRF4D2 "Land converted to wetlands"
cap label var CRF4E "Settlements"
cap label var CRF4E0 "Biomass burning in settlements"
cap label var CRF4E1 "Unconverted settlements"
cap label var CRF4E2 "Land converted to settlements"
cap label var CRF4F "Other land"
cap label var CRF4F2 "Land converted to other land"
cap label var CRF4F3 "Nitrogen mineralization and immobilization in other land - direct N2O emissions"
cap label var CRF4F4 "Biomass burning on other land"
cap label var CRF4G "Harvested wood products"
cap label var CRF4H "Other land use, land use change, and forestry"
cap label var CRF4Z "Managed soils - indirect N2O emissions"
cap label var CRF5 "Waste management"
cap label var CRF5A "Solid waste disposal"
cap label var CRF5A1 "Managed waste disposal sites"
cap label var CRF5A2 "Unmanaged waste disposal sites"
cap label var CRF5A3 "Uncategorized waste disposal sites"
cap label var CRF5B "Biological treatment of solid waste"
cap label var CRF5B1 "Waste composting"
cap label var CRF5B2 "Anaerobic digestion at biogas facilities"
cap label var CRF5C "Incineration and open burning of waste"
cap label var CRF5C1 "Waste incineration"
cap label var CRF5C2 "Open burning of waste"
cap label var CRF5D "Wastewater treatment and discharge"
cap label var CRF5D1 "Domestic wastewater"
cap label var CRF5D2 "Industrial wastewater"
cap label var CRF5D3 "Other wastewater"
cap label var CRF5E "Other disposal"
cap label var CRF5F "Long-term storage of carbon (memo item)"
cap label var CRF5F1 "Long-term storage of carbon in waste disposal sites"
cap label var CRF5F2 "Annual change in total long-term carbon storage"
cap label var CRF5F3 "Annual change in total long-term carbon storage in harvested wood products HWP waste"
cap label var CRF6 "Other sectors"
cap label var CRF_INDCO2 "Indirect CO2"
