cap label var TOTAL "Total area"
cap label var LAND "Land area"
cap label var U100 "Primary sector"
cap label var U110 "Agriculture"
cap label var U111 "Agriculture (excluding fallow land and kitchen gardens)"
cap label var U112 "Fallow land"
cap label var U113 "Kitchen gardens"
cap label var U120 "Forestry"
cap label var U130 "Fishing and aquaculture"
cap label var HENVI "Land use with heavy environmental impact"
cap label var U140 "Mining and quarrying"
cap label var U150 "Other primary sector activities"
cap label var U200 "Secondary sector"
cap label var U210 "Energy production"
cap label var U220 "Industry and manufacturing"
cap label var U221 "Manufacturing of food products, beverages and tobacco products"
cap label var U222 "Manufacturing of textile products"
cap label var U223 "Coal, crude petroleum and metal processing"
cap label var U224 "Production of other non-metal mineral products"
cap label var U225 "Chemical and allied industries"
cap label var U226 "Manufacturing of machinery and equipment"
cap label var U227 "Manufacturing of wood based products and related activities"
cap label var U228 "Printing and reproduction"
cap label var U300 "Tertiary sector, transports, utilities and residential areas"
cap label var U310 "Transport, telecommunication, energy distribution, storage, protective works"
cap label var U311 "Railway transport"
cap label var U312 "Road transport"
cap label var U313 "Water transport"
cap label var U314 "Air transport"
cap label var U315 "Transport via pipelines"
cap label var U316 "Telecommunication"
cap label var U317 "Logistics and storage"
cap label var U318 "Protection infrastructure"
cap label var U319 "Electricity, gas and thermal power distribution"
cap label var U320 "Water and waste treatment"
cap label var U321 "Water supply and treatment"
cap label var U322 "Waste treatment"
cap label var U330 "Construction"
cap label var U340_370 "Services and residential area"
cap label var U340 "Commercial, financial, professional and information services"
cap label var U341 "Commerce"
cap label var U342 "Financial, professional and information services"
cap label var U350 "Community services"
cap label var U360 "Arts, entertainement and recreation"
cap label var U361 "Arts and entertainement"
cap label var U362 "Sports"
cap label var U370 "Residential area"
cap label var U400 "Unused and abandoned areas"
cap label var U410 "Abandoned areas"
cap label var U411 "Abandoned industrial area"
cap label var U412 "Abandoned commercial area"
cap label var U413 "Abandoned transport area"
cap label var U414 "Abandoned residential area"
cap label var U415 "Other abandoned areas"
cap label var U420 "Semi-natural and natural areas not in use"
cap label var L0000 "Area - Total"
cap label var L0008 "Land area - Total"
cap label var L0005 "Utilised agricultural area (UAA)"
cap label var L0001 "Arable land"
cap label var L1050 "Cereals for the production of grain (including seed but excluding rice)"
cap label var L1250 "Rice"
cap label var L1300 "Dried pulses and protein crops for the production of grain (including seed and mixtures of cereals and pulses)"
cap label var L1350 "Root crops"
cap label var L1360 "Potatoes (including early potatoes and seed potatoes)"
cap label var L1370 "Sugar beet (excluding seed)"
cap label var L1380 "Other root crops n.e.c."
cap label var L1400 "Industrial crops"
cap label var L2610 "Plants harvested green (grown on arable land)"
cap label var L1600 "Vegetables, melons and strawberries"
cap label var L3001 "Flowers and ornamental plants (excluding nurseries)"
cap label var L3310 "Seeds and seedlings"
cap label var L2690 "Other arable-land crops"
cap label var L2695 "Other field products n.e.s."
cap label var L2696 "Fallow land"
cap label var L0002 "Permanent grassland"
cap label var L0003 "Permanent crops"
cap label var L2002 "Total of fruit crops (including wine and olives)"
cap label var L0011 "Fruit and berry plantations"
cap label var L2300 "Citrus plantations"
cap label var L2450 "Olive plantations"
cap label var L2410 "Vineyards"
cap label var L2810 "Nurseries"
cap label var L2960 "Weaving plants"
cap label var L2980 "Other permanent crops n.e.c."
cap label var L0004 "Kitchen gardens"
cap label var L2990 "Other utilised agricultural area n.e.c."
cap label var L0900 "Crops under glass or high accessible cover"
cap label var L1112 "Vegetables, melons and strawberries under glass high accessible cover"
cap label var L1113 "Flowers and ornamental plants under glass high accessible cover"
cap label var L1114 "Permanent crops under glass or high accessible cover"
cap label var L0006 "Wooded area"
cap label var L0016 "Forest area"
cap label var L0007 "Other area"
cap label var L0009 "Inland waters"
cap label var LU "Total land use"
cap label var LUA "Agriculture"
cap label var LUB "Forestry"
cap label var LUC "Fishing and aquaculture"
cap label var LUD "Land use with heavy environmental impact"
cap label var LUE "Services and residential area"
cap label var LUF "Unused and abandoned areas"
cap label var LUG "Other primary sector activities"
cap label var LUA1 "Agriculture"
cap label var LUB1 "Forestry"
cap label var LUC1 "Fishing and aquaculture"
cap label var LUC2 "Hunting"
cap label var LUD1 "Mining and quarrying"
cap label var LUD2 "Energy production"
cap label var LUD3 "Industry and manufacturing"
cap label var LUD4 "Water and waste treatment"
cap label var LUD5 "Construction"
cap label var LUD6 "Transport, telecommunication, energy distribution, storage, protective works"
cap label var LUE1 "Commercial, financial, professional and information services"
cap label var LUE2 "Community services"
cap label var LUE3 "Arts, entertainement and recreation"
cap label var LUE4 "Residential area"
cap label var LUE5 "Nature reserves"
cap label var LUF1 "Unused and abandoned areas"
cap label var LUA11 "Agriculture (excluding fallow land and kitchen gardens)"
cap label var LUA12 "Fallow land"
cap label var LUA13 "Kitchen gardens"
cap label var LUB10 "Forestry"
cap label var LUC10 "Fishing and aquaculture"
cap label var LUC20 "Hunting"
cap label var LUD10 "Mining and quarrying"
cap label var LUD20 "Energy production"
cap label var LUD31 "Manufacturing of food products, beverages and tobacco products"
cap label var LUD32 "Manufacturing of textile products"
cap label var LUD33 "Coal, crude petroleum and metal processing"
cap label var LUD34 "Production of other non-metal mineral products"
cap label var LUD35 "Chemical and allied industries"
cap label var LUD36 "Manufacturing of machinery and equipment"
cap label var LUD37 "Manufacturing of wood based products and related activities"
cap label var LUD41 "Water supply and treatment"
cap label var LUD42 "Waste treatment"
cap label var LUD51 "Construction"
cap label var LUD61 "Railway transport"
cap label var LUD62 "Road transport"
cap label var LUD63 "Water transport"
cap label var LUD64 "Air transport"
cap label var LUD65 "Transport via pipelines"
cap label var LUD66 "Telecommunication"
cap label var LUD67 "Logistics and storage"
cap label var LUD68 "Protection infrastructure"
cap label var LUE10 "Commercial, financial, professional and information services"
cap label var LUE20 "Community services"
cap label var LUE31 "Arts and entertainement"
cap label var LUE32 "Sports"
cap label var LUE33 "Holiday camps"
cap label var LUE40 "Residential area"
cap label var LUF10 "Unused and abandoned areas"
cap label var LUF11 "Abandoned areas"
cap label var LUF12 "Semi-natural and natural areas not in use"
cap label var AGRIAREA "Utilized agricultural area"
cap label var ARABLAND "Arable land"
cap label var GRASLAND "Permanent grassland"
cap label var PERMCROP "Permanent crops"
