cap label var TOTCOST "Total costs"
cap label var DIR "Direct costs"
cap label var LCP "Labour costs of participants"
cap label var FEE "Fees and payments"
cap label var TRAVEL "Travel and subsistence payments"
cap label var INTEX "Labour costs of internal trainers, exclusively involved in training"
cap label var INTPART "Labour costs of internal trainers, partly involved in training"
cap label var PREM "Costs of training centre, rooms and teaching materials"
cap label var CONTR "CVT contributions"
cap label var RECEIPTS "CVT receipts"
