cap label var TOTAL "Total"
cap label var FRW "Freshwater"
cap label var SBW "Sea and brackish water (total)"
cap label var SEA "Seawater"
cap label var BRK "Brackish water"
cap label var CST_NR "Coastal water - number"
cap label var CST_EXC_NR "Coastal water excellent - number"
cap label var CST_EXC_PC "Coastal water excellent - %"
cap label var INL_NR "Inland water - number"
cap label var INL_EXC_NR "Inland water excellent - number"
cap label var INL_EXC_PC "Inland water excellent - %"
cap label var NSP "Not specified"
