cap label var TOTAL "Total"
cap label var KIL "Killed"
cap label var INJ "Injured"
cap label var INJ_SRL "Seriously injured"
cap label var KIL_MIO_HAB "Number of deaths per million inhabitants"
cap label var INJ_MIO_HAB "Number of persons injured per million inhabitants"
