cap label var TOTAL "Total"
cap label var SAL_SCTR "Employees and subcontractors"
cap label var SAL "Employees"
cap label var SAL_PERM "Employees with a permanent job"
cap label var SAL_TEMP "Employees with a temporary job"
cap label var SCTR "Subcontractors"
cap label var NONE "None"
cap label var NAP "Not applicable"
cap label var NRP "No response"
