cap label var TOTAL "All schemes"
cap label var PUBLIC "Public schemes"
cap label var PRIVATE "Private schemes"
cap label var COMPULSORY "Compulsory schemes"
cap label var N_CLAW "Non compulsory schemes available by law"
cap label var N_C_OTH "Other non compulsory schemes"
cap label var CONTRIBUTORY "Contributory schemes"
cap label var NON_CONTRIB "Non contributory schemes"
cap label var UNIVERSAL "Universal schemes"
cap label var GENERAL "General schemes"
cap label var SCIVCERV "Civil servants schemes"
cap label var SSELFEMP "Self-employed schemes"
cap label var SOTH_OCCUP "Other occupational schemes"
cap label var SOTHER "Other special schemes"
cap label var BASE "Basic schemes"
cap label var COMP "Supplementary schemes"
cap label var PUCENTGOV "Public central government schemes"
cap label var PULOCGOV "Public state and local government schemes"
cap label var PREMP "Private schemes for employees"
cap label var PRECONTR "Private schemes for employees contractual"
cap label var PREN_CONTR "Private schemes for employees non contractual"
cap label var PR_OTH "Other private schemes"
