cap label var TOTAL "Total"
cap label var STIM_INN "Stimulation of innovation"
cap label var NMAJPB "No major problems created"
cap label var UNC "Creation of uncertainty"
cap label var EXS_BUR "Generation of an excessive burden"
cap label var LCSI_EU "Lack of consistency across the EU"
cap label var INI "Initiation of one or more innovation activities"
cap label var NINI "No initiation of one or more innovation activities"
cap label var PCL "Preclusion of starting one or more activities"
cap label var NPCL "No preclusion of starting one or more activities"
cap label var STOP_ONGO "Stop of one or more ongoing innovation activities"
cap label var NSTOP_ONGO "No stop of one or more ongoing innovation activities"
cap label var D_END "Delay in the completion of one or more innovation activities"
cap label var ND_END "No delay in the completion of one or more innovation activities"
cap label var INCR_COST "Increase of the costs of one or more innovation activities"
cap label var NINCR_COST "No increase of the costs of one or more innovation activities"
cap label var SUCC "Success"
cap label var NSUCC "No success"
cap label var INI_FAC "Initiation or facilitation"
cap label var PHIC "Prevention, hampering or increase of the costs"
cap label var MOV_BK "Decision to move or plan to move business function back from abroad"
cap label var MOV_BK_TEMP "Temporary decision to move or plan to move business function back from abroad"
cap label var MOV_BK_PERM "Permanent decision to move or plan to move business function back from abroad"
cap label var ENGA_SRC_INTL "Decision to engage or plan to engage in international sourcing"
cap label var ENGA_SRC_INTL_TEMP "Temporary decision to engage or plan to engage in international sourcing"
cap label var ENGA_SRC_INTL_PERM "Permanent decision to engage or plan to engage in international sourcing"
cap label var DISR_SRC_INTL "Disruption of international sourcing plans"
cap label var DISR_SRC_INTL_TEMP "Temporary disruption of international sourcing plans"
cap label var DISR_SRC_INTL_PERM "Permanent disruption of international sourcing plans"
cap label var NIMPC "No impact"
cap label var CHG_INCR_INC "Any change to increase income"
cap label var CHG_JOB "Change of job or employer"
cap label var LS_WRKHR "Less working hours"
cap label var LS_DTSK "Less demanding tasks in job"
cap label var FAM_LEAV "Family leave"
cap label var WRKINTR "Work interruption"
cap label var NWRKINTR "No work interruption"
cap label var RED_WRKTIME "Reduction of working time"
cap label var NWRKINTR_NRED_WRKTIME "No work interruption or reduction of working time"
cap label var NVR_WRK_CHCARE "Never worked for childcare reasons"
cap label var NVR_WRK_OTH "Never worked for other reasons"
cap label var NVR_CH "Never had children"
cap label var NVR_CARE "Never had care responsibilities"
cap label var FQLF_REC "Formal qualification recognised"
cap label var FQLF_NREC "Formal qualification not recognised"
cap label var PROC_UW "Procedure under way or outcome pending"
cap label var OTH "Other"
cap label var NONE "No effects"
cap label var NAP_NAPLD "Not applicable - did not apply for recognition"
cap label var NAP "Not applicable"
cap label var NRP "No response"
