cap label var PROD "Volume index of production"
cap label var TOVT "Index of turnover - Total"
cap label var TOVD "Index of turnover - Domestic market"
cap label var TOVE "Index of turnover - Non domestic market"
cap label var TOVV "Index of deflated turnover"
cap label var TOVZ "non-domestic turnover - euro area market"
cap label var TOVX "non-domestic turnover - non euro area market"
cap label var EMPL "Employment (number of persons employed)"
cap label var HOWK "Volume of work done (hours worked)"
cap label var WAGE "Gross wages and salaries"
cap label var IMPR "Import price index"
cap label var IMPX "Import price index - non euro area"
cap label var IMPZ "Import price index - euro area"
cap label var CREG "Car registrations"
cap label var PRIN "Domestic output price index - in national currency"
cap label var PREN "Non-domestic output price index - in national currency"
cap label var PREZ "Non-domestic output price index - euro area"
cap label var PREX "Non-domestic output price index - non euro area"
cap label var PRON "Total output price index - in national currency"
cap label var PRBB "Service producer prices for businesses"
cap label var CSTI "Construction cost index - in national currency"
cap label var CSTL "Labour cost index in construction - in national currency"
cap label var CSTM "Input prices for materials - in national currency"
cap label var CSTO "Output price index in construction - in national currency"
cap label var PNUM "Building permits - number of dwellings"
cap label var PSQM "Building permits - m2 of useful floor area"
cap label var FIN_SIT "Financial situation of the business"
cap label var FIN_COS "Cost (interest and other) of obtaining finance"
cap label var FIN_DEB "Debt/turnover ratio of business"
cap label var FIN_OTH "Other terms or conditions of finance"
cap label var FIN_BUR "Burden or effort of obtaining finance"
cap label var FIN_WIL "Willingness of banks to provide finance"
cap label var OTH "Other reason(s)"
cap label var REG "Registrations"
cap label var BKRT "Bankruptcy declarations"
cap label var BPRM_DW "Building permits - number of dwellings"
cap label var BPRM_SQM "Building permits - m2 of useful floor area"
