cap label var TOTAL "Total"
cap label var CUR_OUT "Outside curriculum"
cap label var WBL "Work-based learning"
cap label var WBL_APP "Apprenticeship"
cap label var WBL_MTNS "Mandatory traineeship"
cap label var WBL_MTNG "Mandatory work-based training"
cap label var WBL_OTNS "Optional traineeship"
cap label var WE "Work experience (at least 1 month)"
cap label var PAID_NPAID "Paid and unpaid work experience"
cap label var PAID "Paid work experience"
cap label var NPAID "Unpaid work experience"
cap label var SHORT "Short work experience (1 to 6 months)"
cap label var LONG "Long work experience (7 months or over)"
cap label var NONE_LT1 "No work experience or less than 1 month"
cap label var NONE "No work experience"
cap label var OTH "Other"
cap label var NAP "Not applicable"
cap label var NRP "No response"
cap label var UNK "Unknown"
