cap label var TOTAL "Total"
cap label var HC "Health care"
cap label var HC_HOSP "Hospitalisation"
cap label var HC_AMB "Ambulatory care"
cap label var HC_MED "Medical care"
cap label var HC_DENT "Dental care"
cap label var HC_MENT "Mental health care"
cap label var HC_BLPR "Blood pressure measurement"
cap label var HC_BLCH "Blood cholesterol measurement"
cap label var HC_BLSU "Blood sugar measurement"
cap label var NHC "No health care"
cap label var MG_MEDS "Medicines"
cap label var MG_PMEDS "Prescribed medicines"
cap label var NRP "No response"
