cap label var TOTAL "Total"
cap label var DEV_0 "No information"
cap label var DEV_1 "Deviation due to electrical problems, explosion, fire"
cap label var DEV_2 "Deviation by overflow, overturn, leak, flow, vaporisation, emission"
cap label var DEV_3 "Breakage, bursting, splitting, slipping, fall, collapse of Material Agent"
cap label var DEV_4 "Loss of control (total or partial) of machine, means of transport or handling equipment, hand-held tool, object, animal"
cap label var DEV_5 "Slipping - Stumbling and falling - Fall of persons"
cap label var DEV_6 "Body movement without any physical stress (generally leading to an external injury)"
cap label var DEV_7 "Body movement under or with physical stress (generally leading to an internal injury)"
cap label var DEV_8 "Shock, fright, violence, aggression, threat, presence"
cap label var DEV_9 "Other Deviations not listed above in this classification."
