cap label var TOTAL "Total"
cap label var URB "Predominantly urban regions"
cap label var INT "Intermediate regions"
cap label var INT_CTC "Intermediate regions - close to city"
cap label var INT_RMT "Intermediate regions - remote"
cap label var RUR "Predominantly rural regions"
cap label var RUR_CTC "Predominantly rural regions - close to city"
cap label var RUR_RMT "Predominantly rural regions - remote"
cap label var DEG1 "Cities"
cap label var DEG2 "Towns and suburbs"
cap label var DEG3 "Rural areas"
cap label var CST_A "Coastal areas"
cap label var NCST_A "Non-coastal areas"
cap label var DEG1_CST_A "Cities in coastal areas"
cap label var DEG2_CST_A "Towns and suburbs in coastal areas"
cap label var DEG3_CST_A "Rural areas in coastal areas"
cap label var DEG1_NCST_A "Cities in non-coastal areas"
cap label var DEG2_NCST_A "Towns and suburbs in non-coastal areas"
cap label var DEG3_NCST_A "Rural areas in coastal non-coastal areas"
cap label var CST_R "Coastal regions"
cap label var NCST_R "Non-coastal regions"
cap label var MNT_R "Mountain regions"
cap label var NMNT_R "Non-mountain regions"
cap label var ISL_R "Island regions"
cap label var NISL_R "Non-island regions"
cap label var BRD_R "Border regions"
cap label var NBRD_R "Non-border regions"
cap label var LFA "Less favoured areas"
cap label var LFA_MNT "Less favoured areas - mountainous"
cap label var LFA_OTH "Less favoured areas - other"
cap label var NLFA "Not less favoured areas"
cap label var LSA "Low settled areas"
cap label var NRP "No response"
cap label var UNK "Unknown"
