cap label var TOTAL "Total"
cap label var ESEG0 "Persons in the labour force whose occupation or status in employment is not known"
cap label var ESEG01 "Employed persons whose occupation or status in employment is not known"
cap label var ESEG02 "Unemployed persons whose occupation or status in employment is not known or who never had a job"
cap label var ESEG1 "Managers"
cap label var ESEG10 "Managers - not specified"
cap label var ESEG11 "Higher managerial self-employed"
cap label var ESEG12 "Lower managerial self-employed"
cap label var ESEG13 "Higher managerial employees"
cap label var ESEG14 "Lower managerial employees"
cap label var ESEG2 "Professionals"
cap label var ESEG20 "Professionals - not specified"
cap label var ESEG21 "Science, engineering and information and communications technology professionals"
cap label var ESEG22 "Health professionals"
cap label var ESEG23 "Business and administration professionals"
cap label var ESEG24 "Legal, social and cultural professionals"
cap label var ESEG25 "Teaching professionals"
cap label var ESEG3 "Technicians and associate professional employees"
cap label var ESEG30 "Technicians and associate professional employees - not specified"
cap label var ESEG31 "Science and engineering associate professionals and information and communications technology technicians"
cap label var ESEG32 "Health associate professionals"
cap label var ESEG33 "Business and administration associate professionals"
cap label var ESEG34 "Legal, social and cultural associate professionals"
cap label var ESEG35 "Non-commissioned armed forces officers"
cap label var ESEG4 "Small entrepreneurs"
cap label var ESEG40 "Small entrepreneurs - not specified"
cap label var ESEG41 "Self-employed agricultural and related workers"
cap label var ESEG42 "Self-employed technicians, clerical support, services and sales workers"
cap label var ESEG43 "Self-employed drivers, craft, trades and elementary workers"
cap label var ESEG5 "Clerks and skilled service employees"
cap label var ESEG50 "Clerks and skilled service employees - not specified"
cap label var ESEG51 "General and numerical clerks and other clerical support employees"
cap label var ESEG52 "Customer services clerks"
cap label var ESEG53 "Personal care employees"
cap label var ESEG54 "Protective service employees and armed forces, other ranks"
cap label var ESEG6 "Skilled industrial employees"
cap label var ESEG60 "Skilled industrial employees - not specified"
cap label var ESEG61 "Building and related trade employees"
cap label var ESEG62 "Food processing, wood working, garment employees"
cap label var ESEG63 "Metal, machinery, handicraft, printing, electrical and electronic trade employees"
cap label var ESEG64 "Stationary plant and machinery operation and assembly employees"
cap label var ESEG65 "Employee drivers and mobile plant operators"
cap label var ESEG7 "Lower status employees"
cap label var ESEG70 "Lower status employees - not specified"
cap label var ESEG71 "Personal services and sales employees"
cap label var ESEG72 "Industrial labourers and food preparation assistants"
cap label var ESEG73 "Cleaners and helpers and services employees in elementary occupations"
cap label var ESEG74 "Agricultural employees"
cap label var ESEG8 "Retired persons"
cap label var ESEG80 "Retired persons - not specified"
cap label var ESEG81 "Retired managers"
cap label var ESEG82 "Retired professionals"
cap label var ESEG83 "Retired technicians and associated professionals employees"
cap label var ESEG84 "Retired small entrepreneurs"
cap label var ESEG85 "Retired clerks and skilled service employees"
cap label var ESEG86 "Retired skilled Industrial employees"
cap label var ESEG87 "Retired lower status employees"
cap label var ESEG9 "Other persons outside the Labour Force"
cap label var ESEG91 "Students"
cap label var ESEG92 "Permanently disabled persons not retired"
cap label var ESEG99 "Other persons outside the labour force not elsewhere classified"
cap label var NRP "No response"
