cap label var TOTAL "Total"
cap label var SUN "Surrounding nets"
cap label var SEI "Seines"
cap label var TRW "Trawls"
cap label var DRE "Dredges"
cap label var LIN "Lift nets"
cap label var GEN "Gill nets and entangling nets"
cap label var TRP "Traps"
cap label var FPO "Traps (pots)"
cap label var FIX "Traps (not specified)"
cap label var HOL "Hooks and lines"
cap label var HAR "Harpoons (grappling and wounding)"
cap label var FYK "Fyke nets"
cap label var FAG "Falling gear"
cap label var MSC "Miscellaneous gear"
cap label var MIS "Miscellaneous gear"
cap label var NONE "No gear"
cap label var UNK "Gear unknown"
