cap label var TOTAL "Total"
cap label var COL_ISM "Collective agreement between social partners on CVT or involvement of staff representatives/committees in the management of CVT (at enterprise level)"
cap label var COL "Collective agreement between social partners on CVT"
cap label var ISM "Involvement of staff representatives/committees in the management of CVT (at enterprise level)"
cap label var NONE "No CVT agreement in place"
cap label var NRP "No response"
