cap label var TOT_AR "Area under wine-grape vines - Total (ha)"
cap label var TOT_AR_INPRD "Area under wine-grape vines - In production (ha)"
cap label var TOT_AR_NOPRD "Area under wine-grape vines - Not yet in production (ha)"
cap label var QWA_AR "Area for quality wines - Total (ha)"
cap label var QWA_AR_INPRD "Area for quality wines - In production (ha)"
cap label var QWA_AR_NOPRD "Area for quality wines - Not yet in production (ha)"
cap label var QWA_CL1 "Area for quality wines - Yield < 30 hl/ha (ha)"
cap label var QWA_CL2 "Area for quality wines - Yield 30 - < 70 hl/ha (ha)"
cap label var QWA_CL3 "Area for quality wines - Yield 70 - < 110 hl/ha (ha)"
cap label var QWA_CL4 "Area for quality wines - Yield > 110 hl/ha (ha)"
cap label var QWA_CL1_POT "Area for quality wines - In production - Potential (or average) yield <30 hl/ha (ha)"
cap label var QWA_CL2_POT "Area for quality wines - In production - Potential (or average) yield 30-<70 hl/ha (ha)"
cap label var QWA_CL3_POT "Area for quality wines - In production - Potential (or average) yield 70-<110 hl/ha (ha)"
cap label var QWA_CL4_POT "Area for quality wines - In production - Potential (or average) yield >110 hl/ha (ha)"
cap label var QWA_CL1_EFF "Area for quality wines - In production - Actual (for the reference year) yield <30 hl/ha (ha)"
cap label var QWA_CL2_EFF "Area for quality wines - In production - Actual (for the reference year) yield 30-<70 hl/ha (ha)"
cap label var QWA_CL3_EFF "Area for quality wines - In production - Actual (for the reference year) yield 70 -<110 hl/ha (ha)"
cap label var QWA_CL4_EFF "Area for quality wines - In production - Actual (for the reference year) yield >110 hl/ha (ha)"
cap label var OWA_AR "Area for other wines - Total (ha)"
cap label var OWA_AR_INPRD "Area for other wines - In production (ha)"
cap label var OWA_AR_NOPRD "Area for other wines - Not yet in production (ha)"
cap label var OWA_CL1 "Area for other wines - Yield < 40 hl/ha (ha)"
cap label var OWA_CL2 "Area for other wines - Yield 40 - < 70 hl/ha (ha)"
cap label var OWA_CL3 "Area for other wines - Yield 70 - < 100 hl/ha (ha)"
cap label var OWA_CL4 "Area for other wines - Yield 100 - < 130 hl/ha (ha)"
cap label var OWA_CL5 "Area for other wines - Yield > 130 hl/ha (ha)"
cap label var OWA_CL1_POT "Area for other wines - In production - Potential (or average) yield <40 hl/ha (ha)"
cap label var OWA_CL2_POT "Area for other wines - In production - Potential (or average) yield 40-<70 hl/ha (ha)"
cap label var OWA_CL3_POT "Area for other wines - In production - Potential (or average) yield 70-<100 hl/ha (ha)"
cap label var OWA_CL4_POT "Area for other wines - In production - Potential (or average) yield 100-<130 hl/ha (ha)"
cap label var OWA_CL5_POT "Area for other wines - In production - Potential (or average) yield >130 hl/ha (ha)"
cap label var OWA_CL1_EFF "Area for other wines - In production - Actual (for the reference year) yield <40 hl/ha (ha)"
cap label var OWA_CL2_EFF "Area for other wines - In production - Actual (for the reference year) yield 40-<70 hl/ha (ha)"
cap label var OWA_CL3_EFF "Area for other wines - In production - Actual (for the reference year) yield 70-<100 hl/ha (ha)"
cap label var OWA_CL4_EFF "Area for other wines - In production - Actual (for the reference year) yield 100-<130 hl/ha (ha)"
cap label var OWA_CL5_EFF "Area for other wines - In production - Actual (for the reference year) yield >130 hl/ha (ha)"
cap label var TOT_PRD "Total production of grape must or wine (1 000 hl)"
cap label var QWP_PRD "Production of grape must or wine, quality wines (1 000 hl)"
cap label var QWP_CL1_POT "Production of grape must or wine, quality wines - Potential (or average) yield <30 hl/ha (1 000 hl)"
cap label var QWP_CL2_POT "Production of grape must or wine, quality wines - Potential (or average) yield 30-<70 hl/ha (1 000 hl)"
cap label var QWP_CL3_POT "Production of grape must or wine, quality wines - Potential (or average) yield 70-<110 hl/ha (1 000 hl)"
cap label var QWP_CL4_POT "Production of grape must or wine, quality wines - Potential (or average) yield >110 hl/ha (1 000 hl)"
cap label var QWP_CL1_EFF "Production of grape must or wine, quality wines - Actual (effective) yield <30 hl/ha (1 000 hl)"
cap label var QWP_CL2_EFF "Production of grape must or wine, quality wines - Actual (effective) yield 30-<70 hl/ha (1 000 hl)"
cap label var QWP_CL3_EFF "Production of grape must or wine, quality wines - Actual (effective) yield 70-<110 hl/ha (1 000 hl)"
cap label var QWP_CL4_EFF "Production of grape must or wine, quality wines - Actual (effective) yield >110 hl/ha (1 000 hl)"
cap label var QWP_ALCOOL "Natural alcoholic strength, quality wines (% vol.)"
cap label var OWP_PRD "Production of grape must or wine, other wines  (1 000 hl)"
cap label var OWP_CL1_POT "Production of grape must or wine, other wines - Potential (or average) yield <40 hl/ha (1 000 hl)"
cap label var OWP_CL2_POT "Production of grape must or wine, other wines - Potential (or average) yield 40-<70 hl/ha (1 000 hl)"
cap label var OWP_CL3_POT "Production of grape must or wine, other wines - Potential (or average) yield 70-<100 hl/ha (1 000 hl)"
cap label var OWP_CL4_POT "Production of grape must or wine, other wines - Potential (or average) yield 100-<130 hl/ha (1 000 hl)"
cap label var OWP_CL5_POT "Production of grape must or wine, other wines - Potential (or average) yield >130 hl/ha (1 000 hl)"
cap label var OWP_CL1_EFF "Production of grape must or wine, other wines - Actual (effective) yield <40 hl/ha (1 000 hl)"
cap label var OWP_CL2_EFF "Production of grape must or wine, other wines - Actual (effective) yield 40-<70 hl/ha (1 000 hl)"
cap label var OWP_CL3_EFF "Production of grape must or wine, other wines - Actual (effective) yield 70-<100 hl/ha (1 000 hl)"
cap label var OWP_CL4_EFF "Production of grape must or wine, other wines - Actual (effective) yield 100-<130 hl/ha (1 000 hl)"
cap label var OWP_CL5_EFF "Production of grape must or wine, other wines - Actual (effective) yield >130 hl/ha (1 000 hl)"
cap label var OWP_ALCOOL "Natural alcoholic strength, other wines (% vol.)"
