cap label var _0 "Agricultural products and live animals"
cap label var _1 "Foodstuffs and animal fodder"
cap label var _2 "Solid mineral fuels"
cap label var _3 "Petroleum products"
cap label var _4 "Ores and metal waste"
cap label var _5 "Metal products"
cap label var _6 "Crude and manufactured minerals, building material"
cap label var _7 "Fertilizers"
cap label var _8 "Chemicals"
cap label var _9 "Machinery, transport equipment, manufactured articles and miscellaneous articles"
cap label var _0_9 "Total from chapter 0 to 9"
cap label var _25 "Total from group 01 to 24"
cap label var _00 "Groups of goods"
cap label var _01 "Cereals"
cap label var _02 "Potatoes, other fresh or frozen fruits and vegetables"
cap label var _03 "Live animals, sugar beet"
cap label var _04 "Wood and cork"
cap label var _05 "Textiles, textile articles and man-made fibres, other raw animal and vegetable materials"
cap label var _06 "Foodstuff and animal fodder"
cap label var _07 "Oil seeds and oleaginous fruits and fats"
cap label var _08 "Solid minerals fuels"
cap label var _09 "Crude petroleum"
cap label var _10 "Petroleum products"
cap label var _11 "Iron ore, iron and steel waste and blast furnace dust"
cap label var _12 "Non-ferrous ores and waste"
cap label var _13 "Metal products"
cap label var _14 "Cement, lime, manufactured building materials"
cap label var _15 "Crude and manufactured minerals"
cap label var _16 "Natural and chemical fertilizers"
cap label var _17 "Coal chemicals, tar"
cap label var _18 "Chemicals other than coal chemicals and tar"
cap label var _19 "Paper pulp and waste paper"
cap label var _20 "Transport equipment, machinery, apparatus, engines, whether or not assembled, and parts thereof"
cap label var _21 "Manufactures of metal"
cap label var _22 "Glass, glassware, ceramic products"
cap label var _23 "Leather, textile, clothing, other manufactured articles"
cap label var _24 "Miscellaneous articles"
cap label var _99 "Not defined"
cap label var UNK "Unknown"
cap label var TOTAL "Total"
cap label var NSTR0 "Agricultural products and live animals"
cap label var NSTR0_GG1 "Cereals"
cap label var NSTR0_GG2 "Potatoes, other fresh or frozen fruits and vegetables"
cap label var NSTR0_GG3 "Live animals, sugar beet"
cap label var NSTR0_GG4 "Wood and cork"
cap label var NSTR0_GG5 "Textiles, textile articles and man-made fibres, other raw animal and vegetable materials"
cap label var NSTR1 "Foodstuff and animal fodder"
cap label var NSTR1_GG6 "Foodstuff and animal fodder"
cap label var NSTR1_GG7 "Oil seeds and oleaginous fruits and fats"
cap label var NSTR2 "Solid mineral fuels"
cap label var NSTR2_GG8 "Solid mineral fuels"
cap label var NSTR3 "Petroleum products"
cap label var NSTR3_GG9 "Crude petroleum"
cap label var NSTR3_GG10 "Petroleum products"
cap label var NSTR4 "Ores and metal waste"
cap label var NSTR4_GG11 "Iron ore, iron and steel waste and blast furnace dust"
cap label var NSTR4_GG12 "Non-ferrous ores and waste"
cap label var NSTR5 "Metal products"
cap label var NSTR5_GG13 "Metal products"
cap label var NSTR6 "Crude and manufactured minerals, building materials"
cap label var NSTR6_GG14 "Cement, lime, manufactured building materials"
cap label var NSTR6_GG15 "Crude and manufactured minerals"
cap label var NSTR7 "Fertilizers"
cap label var NSTR7_GG16 "Natural and chemical fertilizers"
cap label var NSTR8 "Chemicals"
cap label var NSTR8_GG17 "Coal chemicals, tar"
cap label var NSTR8_GG18 "Chemicals other than coal chemicals and tar"
cap label var NSTR8_GG19 "Paper pulp and waste paper"
cap label var NSTR9 "Machinery, transport equipment, manufactured articles and miscellaneous articles"
cap label var NSTR9_GG20 "Transport equipment, machinery, apparatus, engines, whether or not assembled, and parts thereof"
cap label var NSTR9_GG21 "Manufactures of metal"
cap label var NSTR9_GG22 "Glass, glassware, ceramic products"
cap label var NSTR9_GG23 "Leather, textile, clothing, other manufactured articles"
cap label var NSTR9_GG24 "Miscellaneous articles"
