cap label var GEN "Generalist medical practitioners"
cap label var GEN_PRAC "General practitioners"
cap label var GEN_OTH "Other generalist medical practitioners"
cap label var GEN_SPEC "Generalist and specialist medical practitioners"
cap label var GEN_SPEC_HOSP "Generalist and specialist medical practitioners in hospital"
cap label var SPEC "Specialist medical practitioners"
cap label var PAED "General paediatricians"
cap label var GYN "Gynaecologists and obstetricians"
cap label var PSY "Psychiatrists"
cap label var MED "Medical group of specialists"
cap label var MED_INT "Internal medicine"
cap label var MED_CAR "Cardiology"
cap label var MED_END "Endocrinology"
cap label var MED_GAS "Gastroenterology"
cap label var MED_RES "Respiratory medicine"
cap label var MED_ONC "Oncology"
cap label var MED_IMM "Immunology"
cap label var MED_NEU "Neurology"
cap label var MED_ORL "Otorhinolaryngology"
cap label var MED_RAD "Radiology"
cap label var MED_MIC "Microbiology-bacteriology"
cap label var MED_HAE "Haematology"
cap label var MED_DER "Dermatology"
cap label var MED_PAT "Pathology"
cap label var MED_OCC "Occupational medicine"
cap label var MED_DDS "Dentistry"
cap label var SURG "Surgical group of specialists"
cap label var SURG_GEN "General surgery"
cap label var SURG_NEU "Neurological surgery"
cap label var SURG_PLA "Plastic surgery"
cap label var SURG_OPH "Ophthalmology"
cap label var SURG_ORT "Orthopaedics"
cap label var SURG_THO "Thoracic surgery"
cap label var SURG_VAS "Vascular surgery"
cap label var SURG_ANE "Anaesthesiology and intensive care"
cap label var SURG_URO "Urology"
cap label var SURG_EME "Accident and emergency medicine"
cap label var OTH "Other specialists not elsewhere classified"
cap label var NSP "Medical doctors not further defined"
