cap label var TOTAL "Total"
cap label var M01_03 "From January to March"
cap label var M01_05 "From January to May"
cap label var M01 "January"
cap label var M02_09 "From February to September"
cap label var M02 "February"
cap label var M03_05 "From March to May"
cap label var M03 "March"
cap label var M04 "April"
cap label var M05_M06 "May-June"
cap label var M05 "May"
cap label var M_LT06 "31 May and before"
cap label var LT_MID06 "15 June and before"
cap label var M06 "June"
cap label var MID06_MID07 "From 16 June to 15 July"
cap label var M07 "July"
cap label var MID07_MID08 "From 16 July to 15 August"
cap label var M08 "August"
cap label var M_GE08 "1 August and after"
cap label var GE_MID08 "15 August and after"
cap label var M09_11 "From September to November"
cap label var M09_12 "From September to December"
cap label var M09 "September"
cap label var M10_12 "From October to December"
cap label var M10_01 "From October to January"
cap label var M10_04 "From October to April"
cap label var M10 "October"
cap label var M11_01 "From November to January"
cap label var M11 "November"
cap label var M12_03 "From December to March"
cap label var M12 "December"
cap label var PYM01 "January of previous calendar year"
cap label var PYM02 "February of previous calendar year"
cap label var PYM03 "March of previous calendar year"
cap label var PYM04 "April of previous calendar year"
cap label var PYM05 "May of previous calendar year"
cap label var PYM06 "June of previous calendar year"
cap label var PYM07 "July of previous calendar year"
cap label var PYM08 "August of previous calendar year"
cap label var PYM09 "September of previous calendar year"
cap label var PYM10 "October of previous calendar year"
cap label var PYM11 "November of previous calendar year"
cap label var PYM12 "December of previous calendar year"
cap label var UNK "Unknown"
