cap label var TOTAL "All sectors"
cap label var BES "Business enterprise sector"
cap label var GOV_PNP "Government sector or private non-profit sector"
cap label var GOV "Government sector"
cap label var HES "Higher education sector"
cap label var PNP "Private non-profit sector"
cap label var ABR "Abroad"
cap label var HOS "Hospitals"
cap label var INA "Individual applicant"
cap label var OTH "Other sectors"
cap label var UNK "Unknown"
