cap label var TOTAL "Total"
cap label var _0 "No actions"
cap label var _1 "1 action"
cap label var _2 "2 actions"
cap label var _3 "3 actions"
cap label var GT3 "More than 3 actions"
cap label var NRP "No response"
