cap label var CAP_HEAT "Installed thermal capacity"
cap label var CAP_HEAT_ABVTH "Installed thermal capacity above the minimum seasonal performance factor threshold"
cap label var ACT_FACT "Activity factor"
cap label var SPERF_FACT "Seasonal performance factor"
cap label var SPFPE_AVG "Average seasonal performance factor based on primary energy"
cap label var SPFPE_AVG_ABVTH "Average seasonal performance factor based on primary energy - systems above the threshold"
cap label var CLSUP_REN_SHR "Share of cooling supply - renewable"
cap label var CLDD_RED "Cooling degree days – Renewable Energy Directive"
cap label var CAP_CL_AVG_ABVTH "Average nominal cooling capacity - systems above the threshold"
cap label var CAP_CL_AVG_ABVTH_REN "Average nominal cooling capacity - systems above the threshold - renewable heat driven (absorption and adsorption)"
cap label var TIME_USE "Time usage"
cap label var CAP_NET_ELC "Net maximum electrical capacity"
cap label var SOL_COL_SURF "Solar collectors surface"
cap label var CAP_PRD "Production capacity"
cap label var CAP_GST "Gas storage capacity"
cap label var PO_GST "Gas storage - peak output"
cap label var PL "Peak load"
cap label var PCAP "Peak capacity"
cap label var LNGIT_RG "LNG import terminals - regasification capacity"
cap label var LNGIT_VP "LNG import terminals - vaporizers"
cap label var LNGIT_TRN "LNG import terminals - trains"
cap label var LNGIT_ST "LNG import terminals - storage capacity"
cap label var LNGIT_TNK "LNG import terminals - tanks"
cap label var LNGIT_PO "LNG import terminals - peak output"
cap label var LNGET_LIQ "LNG export terminals - liquefaction capacity"
cap label var LNGET_TRN "LNG export terminals - trains"
cap label var LNGET_ST "LNG export terminals - storage capacity"
cap label var LNGET_TNK "LNG export terminals - tanks"
cap label var LNGET_PO "LNG export terminals - peak output"
cap label var CAP_GNW "Gas network - maximum capacity"
cap label var CAP_GNW_R "Gas network - reverse flow maximum capacity"
cap label var RCAP_AD "Refinery capacity - atmospheric distillation"
cap label var RCAP_AD_NOP_NAR "Refinery capacity - atmospheric distillation - not in operation and not in active repair"
cap label var RCAP_VD "Refinery capacity - vacuum distillation"
cap label var RCAP_TC "Refinery capacity - thermal cracking"
cap label var RCAP_TC_VB "Refinery capacity - thermal cracking - visbreaking"
cap label var RCAP_TC_CO "Refinery capacity - thermal cracking - coking"
cap label var RCAP_CC "Refinery capacity - catalytic cracking"
cap label var RCAP_CC_FCC "Refinery capacity - catalytic cracking - fluid catalytic cracking"
cap label var RCAP_CC_HC "Refinery capacity - catalytic cracking - hydro-cracking"
cap label var RCAP_DS "Refinery capacity - desulphurisation"
cap label var RCAP_DS_NG_LD "Refinery capacity - desulphurisation - naphtha, gasoline and other light distillates"
cap label var RCAP_DS_MIDD "Refinery capacity - desulphurisation - middle distillates"
cap label var RCAP_DS_HD "Refinery capacity - desulphurisation - heavy distillates"
cap label var RCAP_RFOR "Refinery capacity - reforming"
cap label var RCAP_API "Refinery capacity - alkylation, polymerisation, isomeration"
cap label var RCAP_ETH "Refinery capacity - etherification"
cap label var RCAP_UPU_OTH "Refinery capacity - other upgrading units"
cap label var RCAP_H "Refinery capacity - hydrogen"
cap label var CAP_EN "Enrichment capacity (tSWU)"
cap label var PRDCAP_FF "Production capacity of fresh fuel elements (tHM)"
cap label var PRDCAP_MOXF "Production capacity of MOX fuel fabrication plants (tHM)"
cap label var PRD_FF "Production of fresh fuel elements (tHM)"
cap label var PRD_MOXF "Production of MOX fuel elements (tHM)"
cap label var PRD_NUCH "Production of nuclear heat (ktoe)"
cap label var BAA_IRRADF "Annual average burnup of definitively discharged irradiated fuel elements (GWd/tHM)"
cap label var PRD_UP "Production of uranium and plutonium in reprocessing plants (tHM)"
cap label var CAP_UP "Capacity (uranium and plutonium) of reprocessing plants (tHM)"
