cap label var TOTAL "Total"
cap label var PRECIP "Precipitation"
cap label var EVAP_TSP "Actual evapotranspiration"
cap label var INTFL "Internal Flow"
cap label var INFL_NBT "Actual external inflow from neighbouring territories"
cap label var OUTFL "Total actual outflow"
cap label var OUTFL_SEA "Total actual outflow into the sea"
cap label var OUTFL_NBT "Total actual outflow into neighbouring territories"
cap label var RFW_RES "Renewable freshwater resources"
cap label var AQUI "Recharge into the aquifer"
cap label var GWAA "Groundwater available for annual abstraction"
cap label var FW_95LTAA "Freshwater resources 95% of years, LTAA"
cap label var ABST "Total gross abstraction"
cap label var ABS_PWS "Water abstraction by public water supply"
cap label var ABS_AGR "Water abstraction by agriculture, forestry, fishing"
cap label var ABS_AGR_IR "Water abstraction by agriculture, forestry, fishing - irrigation"
cap label var ABS_AGR_AQ "Water abstraction by agriculture, forestry, fishing - aquaculture"
cap label var ABS_MIN "Water abstraction by mining and quarrying"
cap label var ABS_IND "Water abstraction by manufacturing industry"
cap label var ABS_IND_CL "Water abstraction by manufacturing industry - cooling"
cap label var ABS_ELC_CL "Water abstraction by electricity production - cooling"
cap label var ABS_CON "Water abstraction by construction"
cap label var ABS_SER "Water abstraction by services"
cap label var ABS_HH "Water abstraction by private households"
cap label var ABS_NET "Total net freshwater abstraction"
cap label var REW "Water returned without use"
cap label var IMP "Imports of water"
cap label var IMP_REG "Water transferred from other regions (imports)"
cap label var EXP "Exports of water"
cap label var EXP_REG "Water transferred to other regions (exports)"
cap label var LOSS "Losses during transport - total"
cap label var LOSS_EVAP "Evaporation losses"
cap label var LOSS_LEAK "Leakage losses"
cap label var LOSS_USE "Losses during use"
cap label var AVL_USE "Water available for use"
cap label var WAU "Water made available for use"
cap label var WAFU "Water available for final use within the territory"
cap label var GEN_HYDRO "Generation of hydroelectricity"
cap label var ABS_GEN_HYDRO "Water abstraction for hydroelectricity generation"
cap label var ART_RES "Artificial reservoirs"
cap label var ABS_ART_RES "Water abstraction from artificial reservoirs"
cap label var PWS "Public water supply"
cap label var SOWS "Self and other water supply"
cap label var PWS_SOWS "Public water supply and self and other supply"
cap label var CONS_USE "Consumptive water use"
cap label var CONSUM "Total water consumption"
cap label var POP_PWS "Population connected to public water supply (%)"
cap label var CWD "Total cooling water discharged"
cap label var CWD_IW "Cooling water discharged to inland waters"
cap label var CWD_SEA "Cooling water discharged to marine waters"
cap label var DIS "Total discharges of wastewater treatment plants (urban and other)"
cap label var DIS_IW "Total wastewater discharged to inland waters"
cap label var DIS_SEA "Total wastewater discharged to marine waters"
cap label var WEI "Water exploitation index"
