cap label var A0000 "Total of live animals"
cap label var A0010 "Livestock"
cap label var A0011 "Grazing livestock"
cap label var A0019 "Other livestock"
cap label var A0020 "Limited livestock (bovine, pigs, sheep and goats)"
cap label var A0030 "Other livestock (IFS2020)"
cap label var A1000 "Live horses, asses, mules and hinnies"
cap label var A1100 "Live horses"
cap label var A1100B "Horses for slaughter"
cap label var A1110 "Foals, less than 1 year old"
cap label var A1120 "Young horses, aged from 1 year to less than 3 years old"
cap label var A1130 "Horses, 3 years old or over"
cap label var A1200 "Live asses, mules and hinnies"
cap label var A1210 "Asses"
cap label var A1220 "Mules"
cap label var A1230 "Hinnies"
cap label var A2000 "Live bovine animals"
cap label var A2000B "Bovine animals for slaughter"
cap label var A2000D "Bovine animals for meat production"
cap label var A2000E "Bovine animals not for meat production"
cap label var A2000_ORG "Live bovine animals - organic"
cap label var A2010 "Bovine animals, less than 1 year old"
cap label var A2010B "Bovine animals, less than 1 year old, for slaughter"
cap label var A2010C "Bovine animals, less than 1 year old, not for slaughter"
cap label var A2020 "Bovine animals, 1 to less than 2 years old"
cap label var A2020B "Bovine animals, 1 year old, for slaughter"
cap label var A2020C "Bovine animals, 1 year old, not for slaughter"
cap label var A2030 "Bovine animals, 2 years old or over"
cap label var A2030B "Bovine animals, 2 years old or over, for slaughter"
cap label var A2030C "Bovine animals, 2 years old or over, not for slaughter"
cap label var A2100_2200 "Bovine animals, male and female (having not yet calved)"
cap label var A2100 "Male bovine animals"
cap label var A2110 "Male calves, less than 1 year old"
cap label var A2110C "Male calves, less than 1 year old, not for slaughter"
cap label var A2120 "Male bovine animals, 1 to less than 2 years old"
cap label var A2130 "Male bovine animals, 2 years old or over"
cap label var A2140 "Male bovine animals, 1 year old or over"
cap label var A2140A "Bullocks"
cap label var A2200_2300 "Female bovine animals"
cap label var A2230_2300 "Female bovine, 2 years old or over (including all cows)"
cap label var A2230_2330 "Female bovine animals, 2 years old or over"
cap label var A2200 "Female bovine animals (having not calved)"
cap label var A2210 "Female calves, less than 1 year old"
cap label var A2210C "Female calves, less than 1 year old, not for slaughter"
cap label var A2220 "Heifers, 1 to less than 2 years old"
cap label var A2220B "Heifers, 1 year old, for slaughter"
cap label var A2220C "Heifers, 1 year old, not for slaughter"
cap label var A2230 "Heifers, 2 years old or over"
cap label var A2230B "Heifers, 2 years old or over, for slaughter"
cap label var A2230C "Heifers, 2 years old or over, not for slaughter"
cap label var A2300 "Cows"
cap label var A2300F "Dairy cows"
cap label var A2300F_ORG "Dairy cows - organic"
cap label var A2300G "Non dairy cows"
cap label var A2300G_ORG "Non-dairy cows - organic"
cap label var A2300H "Suckler cows"
cap label var A2330 "Other cows, 2 years old and over"
cap label var A2400 "Buffaloes"
cap label var A2410 "Breeding female buffaloes"
cap label var A2410_ORG "Breeding female buffaloes - organic"
cap label var A2420 "Other buffaloes"
cap label var A2421 "Male buffaloes"
cap label var A2500 "Live cattle"
cap label var A2510 "Young cattle, less than 1 year old"
cap label var A2511 "Calves, less than 8 months old"
cap label var A2511AA "Calves, aged of few days"
cap label var A2511AB "Calves, aged of few weeks"
cap label var A2512 "Young cattle, aged from 8 months to less than 12 months old"
cap label var A2900 "Other bovine animals"
cap label var A3000 "Live swine"
cap label var A3000_ORG "Live swine - organic"
cap label var A3100 "Live swine, domestic species"
cap label var A3110 "Piglets, live weight of under 20 kg"
cap label var A3120_3133 "Breeding pigs"
cap label var A3120 "Breeding sows, live weight 50 kg or over"
cap label var A3120K "Covered sows"
cap label var A3120KA "Sows covered for the first time"
cap label var A3120L "Sows, not covered"
cap label var A3120LA "Gilts not yet covered"
cap label var A3130 "Other pigs"
cap label var A3131 "Pigs, from 20 kg to less than 50 kg"
cap label var A3132 "Fattening pigs, live weight 50 kg or over"
cap label var A3132X "Fattening pigs, from 50 kg to less than 80 kg"
cap label var A3132Y "Fattening pigs, from 80 kg to less than 110 kg"
cap label var A3132Z "Fattening pigs, live weight 110 kg or over"
cap label var A3133 "Breeding boars"
cap label var A3200 "Live swine, wild species"
cap label var A4000 "Live sheep and goats"
cap label var A4000_ORG "Live sheep and goats - organic"
cap label var A4100 "Live sheep"
cap label var A4100_ORG "Live sheep - organic"
cap label var A4110 "Ewes and ewe-lambs, breeding females"
cap label var A4110K "Ewes and ewe-lambs put to the ram"
cap label var A4110KC "Milk ewes and ewe-lambs put to the ram"
cap label var A4110KD "Non milk ewes and ewe-lambs put to the ram"
cap label var A4120 "Other sheep"
cap label var A4121 "Lambs"
cap label var A4121H "Suckling lambs"
cap label var A4121P "Fattening lambs"
cap label var A4200 "Live goats"
cap label var A4200_ORG "Live goats - organic"
cap label var A4201 "Goats, 12 months old or less"
cap label var A4210 "Goats, breeding females"
cap label var A4210K "Goats mated and having already kidded"
cap label var A4210KA "Goats mated for the first time"
cap label var A4210KB "Goats having already kidded"
cap label var A4210F "Dairy goats"
cap label var A4220 "Other goats"
cap label var A5000 "Live poultry"
cap label var A5000_ORG "Live poultry - organic"
cap label var A5010 "Breeding poultry"
cap label var A5000X5100 "Live poultry excluding chicken (species)"
cap label var A5000X5110O_5140 "Live poultry excluding laying hens and broilers"
cap label var A5100 "Chicken (species)"
cap label var A5110 "Hens"
cap label var A5110O "Laying hens"
cap label var A5110O_ORG "Laying hens - organic"
cap label var A5110OH "Laying hens (producing eggs for consumption)"
cap label var A5110ONH "Laying hens (not producing eggs for consumption)"
cap label var A5120 "Cocks"
cap label var A5130 "Chicks of chicken"
cap label var A5130O "Chicks of laying hen breeds (laying)"
cap label var A5130ON "Chicks of laying hen breeds (selection)"
cap label var A5130P "Chicks of meat broiler breeds (fattening)"
cap label var A5130PN "Chicks of meat broiler breeds (selection)"
cap label var A5130M "Chicks of mixed meat-laying breeds"
cap label var A5130OM "Chicks used for laying"
cap label var A5130PM "Chicks used for fattening"
cap label var A5130N "Chicks of chicken (selection)"
cap label var A5131 "Cockerels"
cap label var A5131P "Cockerels from sexing"
cap label var A5140 "Broilers"
cap label var A5140_ORG "Broilers - organic"
cap label var A5200 "Ducks, geese, turkeys, Guinea fowls"
cap label var A5210 "Ducks"
cap label var A5211P "Chicks of duck (fattening)"
cap label var A5220 "Geese"
cap label var A5221P "Chicks of goose (fattening)"
cap label var A5230 "Turkeys"
cap label var A5231P "Chicks of turkey (fattening)"
cap label var A5240 "Guinea fowls"
cap label var A5241P "Chicks of Guinea fowls (fattening)"
cap label var A5200_6521 "Other poultry including ostriches"
cap label var A5240_5300 "Guinea fowls and small poultry (including quails, pheasants and pigeons)"
cap label var A5300 "Small poultry"
cap label var A5310 "Quail"
cap label var A5320 "Pheasant"
cap label var A5330 "Pigeon"
cap label var A5410 "Ostrich"
cap label var A5900 "Other poultry"
cap label var A6000 "Other animals"
cap label var A6010 "Fur animals"
cap label var A6100 "Rodents"
cap label var A6110 "Rabbits"
cap label var A6111 "Rabbits, breeding females"
cap label var A6120 "Other rodents"
cap label var A6121 "Mice"
cap label var A6122 "Rats"
cap label var A6123 "Guinea pigs"
cap label var A6124 "Hamsters"
cap label var A6125 "Syrian (golden) hamsters"
cap label var A6126 "Chinese hamsters"
cap label var A6127 "Gerbils"
cap label var A6128 "Mongolian gerbils"
cap label var A6200 "Other big herbivores"
cap label var A6210 "Deer"
cap label var A6220 "Camels"
cap label var A6300 "Carnivores"
cap label var A6310 "Cats"
cap label var A6320 "Dogs"
cap label var A6330 "Ferrets"
cap label var A6340 "Foxes"
cap label var A6390 "Other carnivores"
cap label var A6400 "Primates"
cap label var A6410 "Prosimians"
cap label var A6420 "Marmosets and tamarins"
cap label var A6430 "Monkeys"
cap label var A6431 "Squirrel monkeys"
cap label var A6432 "Cynomolgus monkeys"
cap label var A6433 "Rhesus monkeys"
cap label var A6440 "Macaques and vervets"
cap label var A6450 "Baboons"
cap label var A6490 "Other species of primates"
cap label var A6500 "Birds"
cap label var A6510 "Birds, domestic species"
cap label var A6520 "Birds, wild species"
cap label var A6521 "Ostrich"
cap label var A6600 "Reptiles and amphibians"
cap label var A6610 "Reptiles"
cap label var A6620 "Amphibians"
cap label var A6629 "Other amphibians"
cap label var A6700 "Insects"
cap label var A6710 "Bees"
cap label var A6710R "Bees (hives)"
cap label var A6720 "Other insects (excl. bees)"
cap label var A6900 "Other live animals"
cap label var A6900A "Other animals excluding ostriches, rabbits, bees, insects and pet animals"
cap label var B0000 "Total of meat and edible meat offal"
cap label var B0010 "Meat of livestock"
cap label var B1000 "Bovine meat"
cap label var B1100 "Calve and young cattley"
cap label var B1110 "Calve"
cap label var B1120 "Young cattle"
cap label var B1200 "Adult cattle"
cap label var B1210_1220 "Bullock and bull"
cap label var B1210 "Bullock"
cap label var B1220 "Bull"
cap label var B1230 "Cow"
cap label var B1240 "Heifer"
cap label var B3000 "Meat of swine"
cap label var B3100 "Pigmeat"
cap label var B3100A "Swine (grade I)"
cap label var B3100B "Swine (grade II)"
cap label var B4000 "Meat of sheep and goats"
cap label var B4100 "Sheepmeat"
cap label var B4110 "Lamb"
cap label var B4120 "Mutton"
cap label var B4200 "Goat meat"
cap label var B5000 "Meat of horses, asses, mules or hinnies"
cap label var B6000 "Edible offal"
cap label var B7000 "Poultry meat"
cap label var B7100 "Chicken"
cap label var B7110 "Broiler"
cap label var B7120 "Boiling hen"
cap label var B7200 "Duck"
cap label var B7300 "Turkey"
cap label var B7400 "Goose, guinea fowl and other poultry"
cap label var B7410 "Goose"
cap label var B7420 "Guinea fowl"
cap label var B7490 "Other poultry"
cap label var B8000 "Meat of rabbits"
cap label var B9000 "Other meat"
cap label var D0000 "Milk, cheese and eggs"
cap label var D0100 "Milk products"
cap label var D0100AD "Farm milk products delivered to dairies"
cap label var D0110 "Fresh products"
cap label var D0120 "Manufactured products"
cap label var D0200 "Milk products, other than"
cap label var D0210D "Milk products, other than drinking milk, cream, butter and cheese, delivered to dairies"
cap label var D0220D "Milk products, other than milk and cream, delivered to dairies"
cap label var D0230D "Other milk products (than milk, cream, skimmed milk and buttermilk) delivered to dairies"
cap label var D1000 "Raw milk and cream"
cap label var D1100 "Milk or raw milk"
cap label var D1100A "Raw milk, total available on farms"
cap label var D1100DU "Raw milk, total available on dairies  (=total used)"
cap label var D1100D "Raw milk delivered to dairies"
cap label var D1100F "Raw milk for feed"
cap label var D1100DLA "Raw milk, differences and losses on farms"
cap label var D1100DLD "Raw milk, differences and losses in dairies"
cap label var D1100OUD "Raw milk, other uses by dairies"
cap label var D1110 "Raw cows' milk"
cap label var D1110D "Raw cows' milk delivered to dairies"
cap label var D1110A "Raw cows' milk from farm"
cap label var D1111A "Dairy raw cows' milk from farm"
cap label var D1112A "Non-dairy raw cows' milk from farm"
cap label var D1120 "Ewes' milk"
cap label var D1120D "Ewes' milk delivered to dairies"
cap label var D1120A "Ewes' milk from farm"
cap label var D1130 "Goats' milk"
cap label var D1130D "Goats' milk delivered to dairies"
cap label var D1130A "Goats' milk from farm"
cap label var D1140D "Buffalos' milk delivered to dairies"
cap label var D1140A "Buffalos' milk from farm"
cap label var D1190 "Raw milk from other species"
cap label var D1200A "Raw cream from farm"
cap label var D1200D "Raw cream delivered to dairies"
cap label var D1200DME "Raw cream delivered to dairies (in milk equivalent)"
cap label var D2000 "Milk and cream, not concentrated nor containing added sugar or other sweetening matter"
cap label var D2000X "Milk and cream in bulk - exports"
cap label var D2000Y "Milk and cream in bulk - exports intra-EU"
cap label var D2100 "Drinking milk"
cap label var D2110 "Raw drinking milk"
cap label var D2110V "Drinking milk - direct sales"
cap label var D2110H "Drinking milk - home consumption"
cap label var D2120 "Whole milk"
cap label var D2120I "Imports of whole milk (including raw milk)"
cap label var D2120J "Imports (intra-EU) of whole milk (including raw milk)"
cap label var D2121 "Whole milk pasteurised"
cap label var D2122 "Whole milk sterilised"
cap label var D2123 "Whole milk uperised"
cap label var D2130 "Partly skimmed milk"
cap label var D2131 "Partly skimmed milk pasteurised"
cap label var D2132 "Partly skimmed milk sterilised"
cap label var D2133 "Partly skimmed milk uperised"
cap label var D2140_4200A "Skimmed milk and buttermilk, total available on farms"
cap label var D2140_4200RD "Skimmed milk and buttermilk returned by dairies"
cap label var D2140_4200BC "Skimmed milk and buttermilk - balance of cream deliveries"
cap label var D2140_4200AB "Skimmed milk and buttermilk from butter and cream production"
cap label var D2140_4200D "Skimmed milk and buttermilk delivered to dairies"
cap label var D2140 "Skimmed milk"
cap label var D2140RA "Skimmed milk - returned to the farm"
cap label var D2140I "Imports of skimmed milk"
cap label var D2140J "Imports (intra-EU) of skimmed milk"
cap label var D2141 "Skimmed milk pasteurised"
cap label var D2142 "Skimmed milk sterilised"
cap label var D2143 "Skimmed milk uperised"
cap label var D2200_6110A "Cream and butter from farm"
cap label var D2200 "Cream"
cap label var D2200V "Cream for direct consumption"
cap label var D2201 "Cream of fat content by weight not exceeding 29 %"
cap label var D2202 "Cream of fat content by weight over 29 %"
cap label var D2200IME "Imports of cream (in milk equivalent)"
cap label var D2200JME "Imports (intra-EU) of cream (in milk equivalent)"
cap label var D3000 "Milk and cream, concentrated or containing added sugar or other sweetening matter"
cap label var D3100 "Powder products"
cap label var D3100_X_3113 "Milk and cream powders, excluding skimmed milk powders"
cap label var D3110 "Milk powder"
cap label var D3111 "Whole milk powder"
cap label var D3112 "Partly skimmed milk powder"
cap label var D3113 "Skimmed milk powder"
cap label var D3120 "Cream milk powder"
cap label var D3130 "Buttermilk powder"
cap label var D3190 "Other powder products"
cap label var D3200 "Concentrated milk"
cap label var D3210 "Concentrated milk not sweetened"
cap label var D3220 "Concentrated milk sweetened"
cap label var D4000 "Buttermilk, curdled milk and cream, yogurt, kephir and other fermented or acidified milk and cream"
cap label var D4100 "Acidified milk (yoghurts and other)"
cap label var D4110 "Acidified milk with additives"
cap label var D4120 "Acidified milk without additives"
cap label var D4200 "Buttermilk"
cap label var D5000 "Whey"
cap label var D5100 "Whey (liquid)"
cap label var D5200 "Whey (concentrated)"
cap label var D5300 "Whey (in powder or in block)"
cap label var D5400 "Lactose (milk sugar)"
cap label var D5500 "Lactalbumin"
cap label var D6000 "Butter, incl. dehydrated butter and ghee, and other fats and oils derived from milk; dairy spreads"
cap label var D6100 "Butter"
cap label var D6100A "Farm butter"
cap label var D6100AD "Farm butter delivered to dairies"
cap label var D6110 "Traditional butter"
cap label var D6120 "Recombined butter"
cap label var D6130 "Whey butter"
cap label var D6200 "Rendered butter and butteroil"
cap label var D6900 "Other yellow fat dairy products"
cap label var D6910 "Reduced-fat butter"
cap label var D6990 "Other yellow fat dairy products (without reduced-fat butter)"
cap label var D7000 "Cheese and curd"
cap label var D7100 "Cheese"
cap label var D7100A "Farm cheese"
cap label var D7100AD "Farm cheese delivered to dairies"
cap label var D7110 "All types of cheese"
cap label var D7111 "Soft cheese"
cap label var D7112 "Medium soft cheese"
cap label var D7113 "Medium hard cheese"
cap label var D7114 "Hard cheese"
cap label var D7115 "Extra hard cheese"
cap label var D7116 "Fresh cheese"
cap label var D7120 "Cheese from animals"
cap label var D7121 "Cheese from cows'milk (pure)"
cap label var D7122 "Cheese from ewes milk (pure)"
cap label var D7123 "Cheese from goats milk (pure)"
cap label var D7129 "Others (cheese from buffalos'milk (pure) or mixed cheese)"
cap label var D7200 "Processed cheese"
cap label var D8000 "Eggs"
cap label var D8000H "Eggs for consumption"
cap label var D8100 "Fertilised eggs from domestic bird species, for incubation"
cap label var D8110 "Hens' eggs"
cap label var D8120 "Ducks' eggs"
cap label var D8130 "Geeses' eggs"
cap label var D8140 "Turkeys' eggs"
cap label var D8150 "Guinea fowls' eggs"
cap label var D8190 "Eggs from other species"
cap label var D8200 "Eggs in shell from domestic birdspecies,not for incubation"
cap label var D8210 "Hens' eggs"
cap label var D8290 "Eggs from other species"
cap label var D8300 "Eggs not in shell"
cap label var D9000 "Other milk products"
cap label var D9000I "Imports of other products"
cap label var D9000J "Imports (intra-EU) of other products"
cap label var D9100 "Drinks with a milk base"
cap label var D9200 "Other fresh products  (milk-based desserts, ice cream)"
cap label var D9300 "Caseins and caseinates"
cap label var D9400 "Other manufactured milk products"
cap label var D9500 "Other organic dairy products"
cap label var D9900A "Other products collected from farm"
cap label var D9910 "Honey"
cap label var CRP "Crop products"
cap label var AA_WA_FA9 "Agricultural area, wooded area and other areas on the farms"
cap label var FA "Farm area"
cap label var FA_OTH "Other farmland"
cap label var FAXSAA "Farm area excluding special agricultural production areas"
cap label var AA "Agricultural area"
cap label var UAA "Utilised agricultural area"
cap label var UAA09S "Other utilised agricultural area n.e.c. - under glass or high accessible cover"
cap label var UAAIB "Irrigable utilised agricultural area"
cap label var UAAIT "Irrigated utilised agricultural area"
cap label var UAATIB "Irrigable utilised agricultural area - outdoor"
cap label var UAATIT "Irrigated utilised agricultural area - outdoor"
cap label var UAAT "Utilised agricultural area - outdoor"
cap label var UAAS "Utilised agricultural area - under glass or high accessible cover"
cap label var UAAXK0000 "Utilised agricultural area excluding kitchen gardens"
cap label var UAAXK0000_ORG "Fully converted and under conversion to organic farming utilised agricultural area (excluding kitchen gardens)"
cap label var UAAXK0000_ORGF "Fully converted to organic farming utilised agricultural area (excluding kitchen gardens)"
cap label var UAAXK0000_ORGU "Under conversion to organic farming utilised agricultural area (excluding kitchen gardens)"
cap label var UAATXK0000_ORG "Outdoor organic utilised agricultural area (excluding kitchen gardens)"
cap label var ARA_J0000 "Arable land and/or permanent grassland"
cap label var ARAT "Arable land - outdoor"
cap label var ARAT_ORG "Arable land - outdoor - organic"
cap label var ARAS "Arable land - under glass or high accessible cover"
cap label var ARA09S "Other arable land crops n.e.c. - under glass or high accessible cover"
cap label var ARA99T_ARA09S "Other arable land crops n.e.c. - outdoor and other arable land crops n.e.c. - under glass or high accessible cover"
cap label var ARA "Arable land"
cap label var ARAIB "Irrigable arable land"
cap label var ARAXIB "Non-irrigable arable land"
cap label var ARAXSC "Arable land excluding soil cover"
cap label var SC_WNTCR "Normal winter crop"
cap label var SC_COV_INTCR "Cover crop or intermediate crop"
cap label var SC_PLRES "Plant residues"
cap label var SC_BARE "Bare soil"
cap label var SC_MAPL "Multi-annual plants"
cap label var ARAXTIL "Arable land excluding tillage"
cap label var TIL_CV "Conventional tillage"
cap label var TIL_CSERV "Conservational tillage"
cap label var TIL_ZERO "Zero tillage"
cap label var FCONV_UCONV "Fully converted and under conversion to organic farming"
cap label var C0000 "Cereals for the production of grain (including seed)"
cap label var C0000T "Cereals for the production of grain (including seed) - outdoor"
cap label var C0000T_ORG "Cereals for the production of grain (including seed) - outdoor - organic"
cap label var C1000 "Cereals (excluding rice) for the production of grain (including seed)"
cap label var C1000X1100 "Cereals (excluding wheat)"
cap label var C1000X1500 "Cereals (excluding rice, grain maize and corn-cob-mix) for the production of grain (including seed)"
cap label var C1100 "Wheat and spelt"
cap label var C1110 "Common wheat and spelt"
cap label var C1110T "Common wheat and spelt - outdoor"
cap label var C1110T_ORG "Common wheat and spelt - outdoor - organic"
cap label var C1111 "Common winter wheat and spelt"
cap label var C1112 "Common spring wheat and spelt"
cap label var C1120 "Durum wheat"
cap label var C1120T "Durum wheat - outdoor"
cap label var C1120T_ORG "Durum wheat - outdoor - organic"
cap label var C1121 "Winter durum wheat"
cap label var C1122 "Spring durum wheat"
cap label var C1200 "Rye and winter cereal mixtures (maslin)"
cap label var C1200T "Rye and winter cereal mixtures (maslin) - outdoor"
cap label var C1210 "Rye"
cap label var C1211 "Winter rye"
cap label var C1212 "Spring rye"
cap label var C1220 "Winter cereal mixtures (maslin)"
cap label var C1300 "Barley"
cap label var C1300T "Barley - outdoor"
cap label var C1300F "Fodder barley"
cap label var C1310 "Winter barley"
cap label var C1320 "Spring barley"
cap label var C1320M "Malting barley"
cap label var C1400 "Oats and spring cereal mixtures (mixed grain other than maslin)"
cap label var C1400T "Oats and spring cereal mixtures (mixed grain other than maslin) - outdoor"
cap label var C1410 "Oats"
cap label var C1420 "Spring cereal mixtures (mixed grain other than maslin)"
cap label var C1500 "Grain maize and corn-cob-mix"
cap label var C1500T "Grain maize and corn-cob-mix - outdoor"
cap label var C1510 "Grain maize"
cap label var C1520 "Corn-cob-mix"
cap label var C1600_1700_1900 "Other cereals (including triticale and sorghum)"
cap label var C1600_1700_1900T "Other cereals (including triticale and sorghum) - outdoor"
cap label var C1600 "Triticale"
cap label var C1600T "Triticale - outdoor"
cap label var C1610 "Winter triticale"
cap label var C1700 "Sorghum"
cap label var C1700T "Sorghum - outdoor"
cap label var C1900 "Other cereals n.e.c. (buckwheat, millet, canary seed, etc.)"
cap label var C1900T "Other cereals n.e.c. (buckwheat, millet, canary seed, etc.) - outdoor"
cap label var C1910 "Buckwheat"
cap label var C2000 "Rice"
cap label var C2000T "Rice - outdoor"
cap label var C2000X2000B "Rice (excluding broken rice) (equivalent milled rice)"
cap label var C2100 "Rice Indica"
cap label var C2200 "Rice Japonica"
cap label var C2000B "Broken rice"
cap label var C2000Y "Paddy rice"
cap label var C2001Y "Paddy rice, long"
cap label var C2002Y "Paddy rice, round"
cap label var C2003Y "Paddy rice, medium"
cap label var C2000U "Husked rice"
cap label var C2001U "Husked rice, long"
cap label var C2002U "Husked rice, round"
cap label var C2003U "Husked rice, medium"
cap label var C2000L "Milled rice"
cap label var C2001L "Milled rice, long"
cap label var C2002L "Milled rice, round"
cap label var C2003L "Milled rice, medium"
cap label var P0000 "Dry pulses and protein crops for the production of grain (including seed and mixtures of cereals and pulses)"
cap label var P0000T "Dry pulses and protein crops for the production of grain (including seed and mixtures of cereals and pulses) - outdoor"
cap label var P0000T_ORG "Dry pulses and protein crops for the production of grain (including seed and mixtures of cereals and pulses) - outdoor - organic"
cap label var P1000 "Field peas, beans and sweet lupins"
cap label var P1000T "Field peas, beans and sweet lupins - outdoor"
cap label var P1100 "Field peas"
cap label var P1200 "Broad and field beans"
cap label var P1210 "Broad beans"
cap label var P1220 "Field beans"
cap label var P1300 "Sweet lupins"
cap label var P9000 "Other dry pulses and protein crops n.e.c."
cap label var P9000T "Other dry pulses and protein crops n.e.c. - outdoor"
cap label var P9100 "Lentils"
cap label var P9200 "Chick peas"
cap label var P9300 "Haricot beans"
cap label var R0000 "Root crops"
cap label var R0000T "Root crops - outdoor"
cap label var R0000T_ORG "Root crops - outdoor - organic"
cap label var R0000S "Root crops - under glass or high accessible cover"
cap label var R1000 "Potatoes (including seed potatoes)"
cap label var R1000T "Potatoes (including seed potatoes) - outdoor"
cap label var R1000T_ORG "Potatoes (including seed potatoes) - outdoor - organic"
cap label var R1000S "Potatoes (including seed potatoes) - under glass or high accessible cover"
cap label var R1100 "Potatoes for fresh consumption"
cap label var R1110 "Main harvest potatoes"
cap label var R1120 "Early potatoes"
cap label var R1900 "Other potatoes"
cap label var R1910 "Potatoes for processing"
cap label var R1911 "Starch potatoes"
cap label var R1919 "Other potatoes for processing n.e.c."
cap label var R1920 "Seed potatoes"
cap label var R1930 "Fodder potatoes"
cap label var R1990 "Other potatoes n.e.c."
cap label var R2000 "Sugar beet (excluding seed)"
cap label var R2000T "Sugar beet (excluding seed) - outdoor"
cap label var R2000T_ORG "Sugar beet (excluding seed) - outdoor - organic"
cap label var R2000SQ "Sugar beet: standard quality"
cap label var R9000 "Other root crops n.e.c."
cap label var R9000T "Other root crops n.e.c. - outdoor"
cap label var R9100 "Fodder root crops (including forage beet)"
cap label var I0000AM "Industrial crops (agri-monetary)"
cap label var I0000 "Industrial crops"
cap label var I0000T "Industrial crops - outdoor"
cap label var I0000T_ORG "Industrial crops - outdoor - organic"
cap label var I0000S "Industrial crops - under glass or high accessible cover"
cap label var I1000 "Oilseeds and oleaginous fruits"
cap label var I1100 "Oilseeds"
cap label var I1100XI1150T "Oilseeds (except cotton) - outdoor"
cap label var I1100XI1150T_ORG "Oilseeds except cotton - outdoor - organic"
cap label var I1110_1130 "Rape, turnip rape, sunflower seeds and soya"
cap label var I1110 "Rape and turnip rape seeds"
cap label var I1110T "Rape and turnip rape seeds - outdoor"
cap label var I1111 "Winter rape and turnip rape seeds"
cap label var I1112 "Spring rape and turnip rape seeds"
cap label var I1120 "Sunflower seed"
cap label var I1120T "Sunflower seed - outdoor"
cap label var I1130 "Soya"
cap label var I1130T "Soya - outdoor"
cap label var I1130T_ORG "Soya - outdoor - organic"
cap label var I1140_1190 "Other oilseed crops"
cap label var I1140 "Linseed (oilflax)"
cap label var I1140T "Linseed (oilflax) - outdoor"
cap label var I1150_2300 "Cotton seed and fibre"
cap label var I1150_2300T "Cotton seed and fibre - outdoor"
cap label var I1150 "Cotton seed"
cap label var I1190 "Other oilseed crops n.e.c."
cap label var I1190T "Other oilseeds and oleaginous fruits - outdoor"
cap label var I1900 "Other oilseeds and oleaginous fruits"
cap label var I1910 "Unshelled peanuts"
cap label var I1920AM "Poppy (seeds)"
cap label var I2000 "Fibre crops"
cap label var I2000T "Fibre crops - outdoor"
cap label var I2100_2200_2900 "Fibre flax, hemp and other fibre crops n.e.c."
cap label var I2100 "Fibre flax"
cap label var I2100T "Fibre flax - outdoor"
cap label var I2200 "Hemp"
cap label var I2200T "Hemp - outdoor"
cap label var I2300 "Cotton fibre"
cap label var I1190_2900 "Other oilseed and fibre crops"
cap label var I2900 "Other fibre crops n.e.c."
cap label var I2900T "Other fibre crops n.e.c. - outdoor"
cap label var I3000 "Tobacco"
cap label var I3000T "Tobacco - outdoor"
cap label var I3100 "Raw Tobacco"
cap label var I3100V1 "Raw tobacco - most important variety"
cap label var I3100V2 "Raw tobacco - 2nd most important variety"
cap label var I3110 "Raw tobacco - flue cured"
cap label var I3120 "Raw tobacco - light air cured"
cap label var I3130 "Raw tobacco - dark air cured"
cap label var I3140 "Raw tobacco - fire cured"
cap label var I3150 "Raw tobacco - sun cured"
cap label var I4000 "Hops"
cap label var I4000T "Hops - outdoor"
cap label var I4000V1 "Hops - most important variety"
cap label var I5000_9000 "Other industrial crops including aromatic, medicinal and culinary plants"
cap label var I5000 "Aromatic, medicinal and culinary plants"
cap label var I5000T "Aromatic, medicinal and culinary plants - outdoor"
cap label var I5000S "Aromatic, medicinal and culinary plants - under glass or high accessible cover"
cap label var I6000_9000 "Other industrial crops including energy crops n.e.c."
cap label var I6000_9000T "Energy crops n.e.c. and  other industrial crops n.e.c. - outdoor"
cap label var I6000 "Energy crops n.e.c."
cap label var I6000T "Energy crops n.e.c. - outdoor"
cap label var I9000 "Other industrial crops n.e.c."
cap label var I9000T "Other industrial crops n.e.c. - outdoor"
cap label var I9000AM "Other industrial crops (agri-monetary)"
cap label var I9900AM "Other industrial crops (agri-monetary) n.e.c."
cap label var G0000_J0000 "Graminaceous, leguminous and oleaginous plants harvested green (including grazings)"
cap label var G0000_J1000_2000 "Plants harvested green, permanent pastures, meadows and rough grazings"
cap label var G0000 "Plants harvested green from arable land"
cap label var G0000T "Plants harvested green from arable land - outdoor"
cap label var G0000T_ORG "Plants harvested green from arable land - outdoor - organic"
cap label var G0000X1000 "Plants harvested green from arable land excluding temporary grasses and grazings"
cap label var G0000X1000T "Plants harvested green from arable land excluding temporary grasses and grazings - outdoor"
cap label var G1000 "Temporary grasses and grazings"
cap label var G1000T "Temporary grasses and grazings - outdoor"
cap label var G1000T_ORG "Temporary grasses and grazings - outdoor - organic"
cap label var G1100 "Temporary grasses"
cap label var G1200 "Temporary grazings"
cap label var G2000 "Leguminous plants harvested green"
cap label var G2000T "Leguminous plants harvested green - outdoor"
cap label var G2000T_ORG "Leguminous plants harvested green - outdoor - organic"
cap label var G2100 "Lucerne"
cap label var G2900 "Other leguminous plants harvested green n.e.c."
cap label var G2910 "Clover and mixtures"
cap label var G3000 "Green maize"
cap label var G3000T "Green maize - outdoor"
cap label var G9000 "Other plants harvested green from arable land"
cap label var G9000T "Other plants harvested green from arable land - outdoor"
cap label var G9100 "Other cereals harvested green (excluding green maize)"
cap label var G9100T "Other cereals harvested green (excluding green maize) - outdoor"
cap label var G9900 "Other plants harvested green from arable land n.e.c."
cap label var G9900T "Other plants harvested green from arable land n.e.c. - outdoor"
cap label var G9100T_G9900T "Other cereals harvested green (excluding green maize) and other plants harvested green from arable land n.e.c. - outdoor"
cap label var VSK "Fresh vegetables (including melons) and strawberries (including kitchen gardens)"
cap label var V0000AM_PLF "Fresh vegetables (including melons) and horticultural products"
cap label var VSNPECRS "Vegetables, strawberries, permanent crops, flowers and ornamental plants under glass or high accessible cover"
cap label var V0000_S0000 "Fresh vegetables (including melons) and strawberries"
cap label var V0000_S0000T "Fresh vegetables (including melons) and strawberries - outdoor"
cap label var V0000_S0000T_ORG "Fresh vegetables (including melons) and strawberries - outdoor - organic"
cap label var V0000_S0000TO "Fresh vegetables (including melons) and strawberries grown in rotation with non-horticultural crops (open field)"
cap label var V0000_S0000TK "Fresh vegetables (including melons) and strawberries grown in rotation with horticultural crops (market gardening)"
cap label var V0000_S0000S "Fresh vegetables (including melons) and strawberries - under glass or high accessible cover"
cap label var V0000_S0000S_ORG "Fresh vegetables (including melons) and strawberries - under glass or high accessible cover - organic"
cap label var V0000X3500 "Fresh vegetables excluding melons"
cap label var V0000AM "Fresh vegetables including melons (agri-monetary)"
cap label var V0000 "Fresh vegetables (including melons)"
cap label var V1000 "Brassicas"
cap label var V1100 "Cauliflower and broccoli"
cap label var V1110 "Cauliflower"
cap label var V1110Q1 "Cauliflower - quality I"
cap label var V1120 "Broccoli"
cap label var V1200_1900 "Brussels sprouts and other brassicas n.e.c"
cap label var V1200 "Brussels sprouts"
cap label var V1200Q1 "Brussels sprouts - quality I"
cap label var V1300 "Cabbages"
cap label var V1310 "White cabbage"
cap label var V1310Q1 "White cabbage - quality I"
cap label var V1320 "Red cabbage"
cap label var V1320Q1 "Red cabbage - quality I"
cap label var V1330 "Savoy cabbage"
cap label var V1330Q1 "Savoy cabbage - quality I"
cap label var V1900 "Other brassicas n.e.c"
cap label var V1910 "Kohlrabi"
cap label var V1920 "Chinese cabbage"
cap label var V2000 "Leafy and stalked vegetables (excluding brassicas)"
cap label var V2100 "Leeks"
cap label var V2100T "Leeks - outdoor"
cap label var V2200 "Celery"
cap label var V2300 "Lettuces"
cap label var V2300T "Lettuces - outdoor"
cap label var V2300TQ1 "Lettuces - outdoor - quality I"
cap label var V2300S "Lettuces - under glass or high accessible cover"
cap label var V2300SQ1 "Lettuces - under glass or high accessible cover - quality I"
cap label var V2310 "Iceberg lettuce"
cap label var V2400 "Endives"
cap label var V2500 "Spinach"
cap label var V2600 "Asparagus"
cap label var V2600Q1 "Asparagus - quality I"
cap label var V2700 "Chicory"
cap label var V2710 "Chicory for fresh consumption"
cap label var V2720 "Chicory for processing"
cap label var V2800 "Artichokes"
cap label var V2900 "Other leafy or stalked vegetables n.e.c."
cap label var V3000 "Vegetables cultivated for fruit (including melons)"
cap label var V3100 "Tomatoes"
cap label var V3110 "Tomatoes for fresh consumption"
cap label var V3120 "Tomatoes for processing"
cap label var V3100T "Tomatoes - outdoor"
cap label var V3101TQ1 "Tomatoes - outdoor - round; quality I"
cap label var V3102TQ1 "Tomatoes - outdoor - long; quality I"
cap label var V3100S "Tomatoes - under glass or high accessible cover"
cap label var V3100SQ1 "Tomatoes - under glass or high accessible cover - quality I"
cap label var V3200 "Cucumbers"
cap label var V3200T "Cucumbers - outdoor"
cap label var V3200TQ1 "Cucumbers - outdoor - quality I"
cap label var V3200S "Cucumbers - under glass or high accessible cover"
cap label var V3200SQ1 "Cucumbers - under glass or high accessible cover - quality I"
cap label var V3300 "Gherkins"
cap label var V3300T "Gherkins - outdoor"
cap label var V3400 "Eggplants, courgettes (including marrows), gourds and pumpkins"
cap label var V3410 "Eggplants"
cap label var V3420 "Courgettes and marrows"
cap label var V3430 "Gourds and pumpkins"
cap label var V3500 "Melons"
cap label var V3510 "Muskmelons"
cap label var V3520 "Watermelons"
cap label var V3600 "Peppers (capsicum)"
cap label var V3600T "Peppers (capsicum) - outdoor"
cap label var V3600S "Peppers (capsicum) - under glass or high accessible cover"
cap label var V3610 "Red peppers (capsicum)"
cap label var V3900 "Other vegetables cultivated for fruit n.e.c."
cap label var V4000 "Root, tuber and bulb vegetables"
cap label var V4100 "Carrots"
cap label var V4100Q1 "Carrots  quality I"
cap label var V4200 "Onions and shallots"
cap label var V4210 "Onions"
cap label var V4220 "Shallots"
cap label var V4300 "Beetroot"
cap label var V4400 "Celeriac"
cap label var V4500 "Radishes"
cap label var V4600 "Garlic"
cap label var V4900 "Other root, tuber and bulb vegetables n.e.c."
cap label var V4910 "Turnips"
cap label var V4920 "Fennel"
cap label var V4930 "Salsifies and scorzonera"
cap label var V5000AM "Fresh pulses (agri-monetary)"
cap label var V5000 "Fresh pulses"
cap label var V5100 "Fresh peas"
cap label var V5100Q1 "Fresh peas - quality I"
cap label var V5200 "Fresh beans"
cap label var V5210 "French beans"
cap label var V5210Q1 "French beans - quality I"
cap label var V5220 "Runner beans"
cap label var V5900 "Other fresh pulses n.e.c."
cap label var V9000 "Other fresh vegetables n.e.c."
cap label var V9000AM "Other fresh vegetables (agri-monetary)"
cap label var V9900AM "Other fresh vegetables n.e.c. (agri-monetary)"
cap label var S0000 "Strawberries"
cap label var S0000T "Strawberries - outdoor"
cap label var S0000S "Strawberries - under glass or high accessible cover"
cap label var ARA9 "Other arable land crops"
cap label var ARA9T "Other arable land crops - outdoor"
cap label var ARA9S "Other arable land crops - under glass or high accessible cover"
cap label var PLF "Plants and flowers"
cap label var NUP "Nursery products and seedlings"
cap label var N0000_L0000 "Flowers, ornamental plants and nursery products"
cap label var N0000_X0000 "Flowers, ornamental plants and Christmas trees"
cap label var N0000 "Flowers and ornamental plants (excluding nurseries)"
cap label var N0000T "Flowers and ornamental plants (excluding nurseries) - outdoor"
cap label var N0000S "Flowers and ornamental plants (excluding nurseries) - under glass or high accessible cover"
cap label var N1001P "Azaleas - potted"
cap label var N1002P "Cyclamens - potted"
cap label var N1003P "Poinsettias - potted"
cap label var N1004P "Pelargonium - potted"
cap label var N1005P "Ficus - potted"
cap label var N1006P "Kalanchoe - potted"
cap label var N1007P "Saint Paulia - potted"
cap label var N1008P "Begonia - potted"
cap label var N1009 "Roses"
cap label var N1010 "Baccara roses"
cap label var N1011 "Carnations"
cap label var N1012 "Chrysanthemums"
cap label var N1012P "Chrysanthemums - potted"
cap label var N1013 "Gladioli"
cap label var N1014 "Tulips"
cap label var N1015 "Freesias"
cap label var N1016 "Lilium"
cap label var N1017 "Dianthus"
cap label var N1018 "Gerbera"
cap label var N1019 "Cymbidium"
cap label var PLT "Plantations"
cap label var E0000_ARA9 "Seeds, seedlings and other crops on arable land"
cap label var E0000 "Seeds and seedlings"
cap label var E0000T "Seeds and seedlings - outdoor"
cap label var E0000T_ORG "Seeds and seedlings - outdoor - organic"
cap label var E0000S "Seeds and seedlings - under glass or high accessible cover"
cap label var E1000 "Seeds"
cap label var E1000T "Seeds - outdoor"
cap label var E1000S "Seeds - under glass or high accessible cover"
cap label var E2000 "Seedlings"
cap label var E2000T "Seedlings - outdoor"
cap label var E2000S "Seedlings - under glass or high accessible cover"
cap label var E2100 "Flower bulbs"
cap label var ARA99 "Other arable land crops n.e.c."
cap label var ARA99T "Other arable land crops n.e.c. - outdoor"
cap label var Q0000 "Fallow land"
cap label var Q0000T "Fallow land - outdoor"
cap label var Q0000XS "Fallow land without subsidies"
cap label var Q0000ES "Fallow land not in use, eligible for subsidies"
cap label var FOP "Forage plants"
cap label var FOP9 "Other forage plants"
cap label var FOP91 "Hay"
cap label var FOP92 "Straw"
cap label var FOP93 "Silage"
cap label var FOP99 "Other forage plants n.e.c."
cap label var J0000 "Permanent grassland"
cap label var J0000T "Permanent grassland - outdoor"
cap label var J0000T_ORG "Permanent grassland - outdoor - organic"
cap label var J1000 "Permanent pastures and meadows"
cap label var J1000T "Permanent pastures and meadows - outdoor"
cap label var J1000T_ORG "Permanent pastures and meadows - outdoor - organic"
cap label var J1100 "Permanent pastures"
cap label var J1200 "Permanent meadows"
cap label var J2000 "Permanent rough grazings"
cap label var J2000T "Permanent rough grazings - outdoor"
cap label var J2000T_ORG "Permanent rough grazings  - outdoor - organic"
cap label var J3000 "Permanent agricultural grassland not in use"
cap label var J3000ES "Permanent agricultural grassland not in use, eligible for subsidies"
cap label var J3000TE "Permanent agricultural grassland not in use, eligible for subsidies - outdoor"
cap label var PECR_K0000 "Permanent crops including kitchen gardens"
cap label var PECR "Permanent crops"
cap label var PECRT "Permanent crops - outdoor"
cap label var PECRT_ORG "Permanent crops - outdoor - organic"
cap label var PECRS "Permanent crops under glass or high accessible cover"
cap label var H0000_K2000 "Permanent crops for human consumption including those from kitchen gardens"
cap label var H0000 "Permanent crops for human consumption"
cap label var H0000T "Permanent crops for human consumption - outdoor"
cap label var H0000S "Permanent crops for human consumption - under glass or high accessible cover"
cap label var FRUAM "Fruits, citrus fruits, berries (including strawberries), nuts, grapes, olives and dried fruits (agri-monetary)"
cap label var F0000AM "Fresh fruits (agri-monetary)"
cap label var F0000 "Fruits, berries and nuts (excluding citrus fruits, grapes and strawberries)"
cap label var F0000T "Fruits, berries and nuts (excluding citrus fruits, grapes and strawberries) - outdoor"
cap label var F0000T_ORG "Fruits, berries and nuts (excluding citrus fruits, grapes and strawberries) - outdoor - organic"
cap label var F0000X3000 "Fruits and nuts (excluding citrus fruits and grapes)"
cap label var F1000_3000 "Fruits and berries (excluding strawberries) from temperate climate zones"
cap label var F1000_2000 "Fruits from temperate, subtropical and tropical climate zones"
cap label var F1000_2000T "Fruits from temperate, subtropical and tropical climate zones - outdoor"
cap label var F1000 "Fruits from temperate climate zones"
cap label var F1000T "Fruits from temperate climate zones - outdoor"
cap label var F1100 "Pome fruits"
cap label var F1100T "Pome fruits - outdoor"
cap label var F1110_1120 "Apples and pears"
cap label var F1110 "Apples"
cap label var F1111 "Apples for fresh consumption"
cap label var F1111_01 "Boskoop group"
cap label var F1111_02 "Braeburn group"
cap label var F1111_03 "Cox's orange group"
cap label var F1111_031 "Cox's orange pippin apples"
cap label var F1111_04 "Cripps Pink group"
cap label var F1111_05 "Elstar apples group"
cap label var F1111_051 "Elstar apples"
cap label var F1111_06 "Fuji group"
cap label var F1111_07 "Gala group"
cap label var F1111_08 "Golden Delicious group"
cap label var F1111_081 "Golden Delicious apples"
cap label var F1111_09 "Granny Smith group"
cap label var F1111_10 "Idared group"
cap label var F1111_11 "Jonagold/Jonagored group"
cap label var F1111_111 "Jonagold apples"
cap label var F1111_112 "Jonathan apples"
cap label var F1111_12 "Lobo group"
cap label var F1111_13 "Morgenduft group"
cap label var F1111_14 "Pinova group"
cap label var F1111_15 "Red Delicious group"
cap label var F1111_16 "Reinette group"
cap label var F1111_17 "Shampion group"
cap label var F1111_90 "Other apples for fresh consumption"
cap label var F1111_901 "Egrement russet apples"
cap label var F1111_902 "Spartan apples"
cap label var F1111_909 "Other apples for fresh consumption n.e.c"
cap label var F1112 "Apples for processing"
cap label var F1112_01 "Cooking apples"
cap label var F1112_011 "Bramley's seedling cooking apples"
cap label var F1112_02 "Cider apples"
cap label var F1120 "Pears"
cap label var F1121 "Pears for fresh consumption"
cap label var F1121_01 "Abate group"
cap label var F1121_02 "Blanquilla group"
cap label var F1121_03 "Conference group"
cap label var F1121_04 "Coscia-Ercolini group"
cap label var F1121_05 "Decana group"
cap label var F1121_051 "Doyenne du comice pears"
cap label var F1121_06 "Guyot group"
cap label var F1121_07 "Kaiser group"
cap label var F1121_08 "Rocha group"
cap label var F1121_09 "Williams group"
cap label var F1121_091 "Williams pears"
cap label var F1121_90 "Other pears for fresh consumption n.e.c."
cap label var F1122 "Pears for processing"
cap label var F1190 "Other pome fruits n.e.c."
cap label var F1191 "Quinces"
cap label var F1200 "Stone fruits"
cap label var F1200T "Stone fruits - outdoor"
cap label var F1200S "Stone fruits - under glass or high accessible cover"
cap label var F1210_1230 "Peaches, nectarines and apricots"
cap label var F1210_1220 "Peaches and nectarines"
cap label var F1211_1221 "Peaches and nectarines for fresh consumption"
cap label var F1212_1222 "Peaches and nectarines for processing"
cap label var F1210 "Peaches"
cap label var F1211 "Peaches for fresh consumption"
cap label var F1211_01 "Yellow flesh peaches"
cap label var F1211_01VE "Very early yellow flesh peaches"
cap label var F1211_01ER "Early yellow flesh peaches"
cap label var F1211_01ME "Medium-early yellow flesh peaches"
cap label var F1211_01LA "Late yellow flesh peaches"
cap label var F1211_02 "White flesh peaches"
cap label var F1211_02VE "Very early white flesh peaches"
cap label var F1211_02ER "Early white flesh peaches"
cap label var F1211_02ME "Medium-early white flesh peaches"
cap label var F1211_02LA "Late white flesh peaches"
cap label var F1211_03 "Doughnut peaches"
cap label var F1212 "Peaches for processing"
cap label var F1220 "Nectarines"
cap label var F1221 "Nectarines for fresh consumption"
cap label var F1221_01 "Yellow flesh nectarines"
cap label var F1221_01VE "Very early yellow flesh nectarines"
cap label var F1221_01ER "Early yellow flesh nectarines"
cap label var F1221_01ME "Medium-early yellow flesh nectarines"
cap label var F1221_01LA "Late yellow flesh nectarines"
cap label var F1221_02 "White flesh nectarines"
cap label var F1221_02VE "Very early white flesh nectarines"
cap label var F1221_02ER "Early white flesh nectarines"
cap label var F1221_02ME "Medium-early white flesh nectarines"
cap label var F1221_02LA "Late white flesh nectarines"
cap label var F1222 "Nectarines for processing"
cap label var F1230 "Apricots"
cap label var F1230VE "Very early apricots"
cap label var F1230ER "Early apricots"
cap label var F1230ME "Medium-early apricots"
cap label var F1230LA "Late apricots"
cap label var F1240 "Cherries"
cap label var F1241 "Sour cherries"
cap label var F1242 "Sweet cherries"
cap label var F1250 "Plums"
cap label var F1251 "Quetsches"
cap label var F1252 "Greengages"
cap label var F1253 "Mirabelles"
cap label var F1259 "Plums for drying and other plums"
cap label var F1290 "Other stone fruits n.e.c"
cap label var F2000 "Fruits from subtropical and tropical climate zones"
cap label var F2000T "Fruits from subtropical and tropical climate zones - outdoor"
cap label var F2000S "Fruits from subtropical and tropical climate zones - under glass or high accessible cover"
cap label var F2100 "Figs"
cap label var F2200 "Kiwis"
cap label var F2300 "Avocados"
cap label var F2400 "Bananas"
cap label var F2900 "Other fruits from subtropical and tropical climate zones n.e.c."
cap label var F2910 "Dates"
cap label var F3000 "Berries (excluding strawberries)"
cap label var F3000T "Berries (excluding strawberries) - outdoor"
cap label var F3000S "Berries (excluding strawberries) - under glass or high accessible cover"
cap label var F3100 "Currants"
cap label var F3100T "Currants - outdoor"
cap label var F3100S "Currants - under glass or high accessible cover"
cap label var F3110 "Blackcurrants"
cap label var F3110T "Blackcurrants - outdoor"
cap label var F3110S "Blackcurrants - under glass or high accessible cover"
cap label var F3120 "Redcurrants"
cap label var F3120T "Redcurrants - outdoor"
cap label var F3120S "Redcurrants - under glass or high accessible cover"
cap label var F3200 "Raspberries"
cap label var F3200T "Raspberries - outdoor"
cap label var F3200S "Raspberries - under glass or high accessible cover"
cap label var F3300 "Blueberries"
cap label var F3300T "Blueberries - outdoor"
cap label var F3300S "Blueberries - under glass or high accessible cover"
cap label var F3900 "Other berries n.e.c."
cap label var F3900T "Other berries n.e.c. - outdoor"
cap label var F3900S "Other berries n.e.c. - under glass or high accessible cover"
cap label var F3910 "Gooseberries"
cap label var F4000_5000AM "Nuts and dried fruit"
cap label var F4000 "Nuts"
cap label var F4000T "Nuts - outdoor"
cap label var F4100 "Walnuts"
cap label var F4200 "Hazelnuts"
cap label var F4300 "Almonds"
cap label var F4400 "Chestnuts"
cap label var F4900 "Other nuts n.e.c."
cap label var F4910 "Pistachios"
cap label var F5000AM_9000AM "Other fresh and dried fruits (agri-monetary)"
cap label var F5000AM "Dried fruits (agri-monetary)"
cap label var F5100AM "Dried figs (agri-monetary)"
cap label var F5900AM "Other dried fruits n.e.c. (agri-monetary)"
cap label var F9000AM "Other fresh fruits, nuts and dried fruits (agri-monetary)"
cap label var F9900AM "Other fresh fruit n.e.c. (agri-monetary)"
cap label var T0000 "Citrus fruits"
cap label var T0000T "Citrus fruits - outdoor"
cap label var T0000T_ORG "Citrus fruits - outdoor - organic"
cap label var T1000_2000_3100 "Oranges, small citrus fruits and yellow lemons"
cap label var T1000 "Oranges"
cap label var T1100 "Navel oranges"
cap label var T1100ER "Early Navel oranges"
cap label var T1100ME "Medium-early Navel oranges"
cap label var T1100LA "Late Navel oranges"
cap label var T1110 "Washington Navel oranges"
cap label var T1200 "White oranges (blancas)"
cap label var T1200ER "Early white oranges (blancas )"
cap label var T1200LA "Late white oranges (blancas)"
cap label var T1210 "Valencia oranges"
cap label var T1300 "Blood oranges (sanguines)"
cap label var T1310 "Moro oranges"
cap label var T1320 "Sanguinello oranges"
cap label var T1330 "Tarocco oranges"
cap label var T1900 "Others oranges n.e.c"
cap label var T2000 "Small citrus fruits"
cap label var T2100 "Satsumas"
cap label var T2100VE "Very early satsumas"
cap label var T2190 "Other satsumas"
cap label var T2200 "Clementines"
cap label var T2200ER "Early clementines"
cap label var T2200ME "Medium-early clementines"
cap label var T2200LA "Late clementines"
cap label var T2900 "Other small citrus fruits (including hybrids) n.e.c."
cap label var T2910 "Mandarins"
cap label var T2920 "Tangerines"
cap label var T3000 "Lemons and acid limes"
cap label var T3000AM "Lemons (agri-monetary)"
cap label var T3100 "Yellow lemons"
cap label var T3110 "Winter lemon varieties"
cap label var T3110_01 "Invernali lemons"
cap label var T3110_02 "Mesero lemons"
cap label var T3120 "Summer lemon varieties"
cap label var T3120_01 "Verdelli lemons"
cap label var T3120_02 "Verna lemons"
cap label var T3200 "Acid limes"
cap label var T4000 "Pomelos and grapefruit"
cap label var T9000 "Other citrus fruits n.e.c."
cap label var T9000AM "Other citrus fruits n.e.c. (agri-monetary)"
cap label var W0000 "Grapes, must and wines"
cap label var W1000 "Grapes"
cap label var W1000T "Grapes - outdoor"
cap label var W1000S "Grapes - under glass or high accessible cover"
cap label var W1100 "Grapes for wines"
cap label var W1100T "Grapes for wines - outodoor"
cap label var W1100T_ORG "Grapes for wine - outdoor - organic"
cap label var W1110_1120 "Grapes for wines with geographical indication (PDO/PGI)"
cap label var W1110_1120T "Grapes for wines with geographical indication (PDO/PGI) - outdoor"
cap label var W1110 "Grapes for wines with protected designation of origin (PDO)"
cap label var W1110T "Grapes for wines with protected designation of origin (PDO) - outodoor"
cap label var W1120 "Grapes for wines with protected geographical indication (PGI)"
cap label var W1120T "Grapes for wines with protected geographical indication (PGI) - outdoor"
cap label var W1190 "Grapes for other wines n.e.c. (without PDO/PGI)"
cap label var W1190T "Grapes for other wines n.e.c. (without PDO/PGI) - outdoor"
cap label var WDP "Dual purpose grapes"
cap label var W1200 "Grapes for table use"
cap label var W1200T "Grapes for table use - outdoor"
cap label var W1210 "White grapes for table use"
cap label var W1211 "Seedless white grapes for table use"
cap label var W1212 "Normal white grapes for table use"
cap label var W1220 "Red grapes for table use"
cap label var W1221 "Seedless red grapes for table use"
cap label var W1222 "Normal red grapes for table use"
cap label var W1300 "Grapes for raisins"
cap label var W1300T "Grapes for raisins - outdoor"
cap label var W1310 "Black Corinth grapes (currants)"
cap label var W1320 "Sultana grapes"
cap label var W1900 "Grapes for other purposes n.e.c."
cap label var W1900AM "Other fresh grapes (agri-monetary)"
cap label var W2000 "Must"
cap label var W2100 "Vinified must"
cap label var W2200 "Non-vinified must"
cap label var W2210 "Concentrated must"
cap label var W2220 "Grape juice"
cap label var W3000 "Wines"
cap label var W3000R "Wines - red and rosé"
cap label var W3000W "Wines - white"
cap label var W3100 "Wines with geographical indication (PDO/PGI)"
cap label var W3100R "Wines with PDO/PGI - red and rosé"
cap label var W3100W "Wines with PDO/PGI - white"
cap label var W3110 "Wines with protected designation of origin (PDO)"
cap label var W3110R "Wines with PDO - red and rosé"
cap label var W3110W "Wines with PDO - white"
cap label var W3120 "Wines with protected geographical indication (PGI)"
cap label var W3120R "Wines with PGI - red and rosé"
cap label var W3120W "Wines with PGI - white"
cap label var W3200 "Wines without geographical indication (PDO/PGI), including varietal wines"
cap label var W3200R "Wines without PDO/PGI, including varietal wines - red and rosé"
cap label var W3200W "Wines without PDO/PGI, including varietal wines - white"
cap label var W3120_3210_3221 "Table wines"
cap label var W3120_3210_3221R "Table wines - red and rosé"
cap label var W3120_3210_3221W "Table wines - white"
cap label var W3210_3221 "Tables wines without geographical indication (PDO/PGI)"
cap label var W3210_3221R "Table wines without PDO/PGI - red and rosé"
cap label var W3210_3221W "Table wines without PDO/PGI - white"
cap label var W3210 "Varietal wines"
cap label var W3210R "Varietal wines - red and rosé"
cap label var W3210W "Varietal wines - white"
cap label var W3220 "Other wines"
cap label var W3220R "Other wines - red and rosé"
cap label var W3220W "Other wines - white"
cap label var W3221 "Other wines for direct human consumption without geographical indication (PDO/PGI) and without mention of variety"
cap label var W3221R "Other wines for direct human consumption without PDO/PGI and without mention of variety - red and rosé"
cap label var W3221W "Other wines for direct human consumption without PDO/PGI and without mention of variety - white"
cap label var W3222 "Other wines for processing n.e.c."
cap label var W3222R "Other wines for processing n.e.c. - red and rosé"
cap label var W3222W "Other wines for processing n.e.c. - white"
cap label var O0000 "Olives and olive oil"
cap label var O1000 "Olives"
cap label var O1000T "Olives - outdoor"
cap label var O1000T_ORG "Olives - outdoor - organic"
cap label var O1100 "Olives for table use"
cap label var O1100T "Olives for table use - outdoor"
cap label var O1900 "Other olives"
cap label var O1910 "Olives for oil"
cap label var O1910T "Olives for oil - outdoor"
cap label var O1990 "Other olives n.e.c."
cap label var ODP "Dual purpose olives"
cap label var O2000 "Olive oil"
cap label var O2100 "Extra virgin olive oil"
cap label var O2200 "Virgin olive oil"
cap label var O2210 "Virgin olive oil - superfine"
cap label var O2220 "Virgin olive oil - fine"
cap label var O2230 "Ordinary virgin olive oil - semi-fine/corrente"
cap label var O2300 "Refined (common) olive oil"
cap label var O2400 "Lampante virgin olive oil"
cap label var H9000 "Other permanent crops for human consumption n.e.c."
cap label var H9100 "Carobs"
cap label var L0000 "Nurseries"
cap label var L0000T "Nurseries - outdoor"
cap label var L0000S "Nurseries - under glass or high accessible cover"
cap label var PECR9_H9000 "Other permanent crops including other permanent crops for human consumption"
cap label var PECR9_H9000T "Other permanent crops including other permanent crops for human consumption - outdoor"
cap label var PECR9_H9000S "Other permanent crops including other permanent crops for human consumption - under glass or high accessible cover"
cap label var PECR9 "Other permanent crops"
cap label var PECR9T "Other permanent crops - outdoor"
cap label var PECR9S "Other permanent crops - under glass or high accessible cover"
cap label var X0000 "Christmas trees"
cap label var X0000T "Christmas trees - outdoor"
cap label var Z0000 "Plaiting, weaving and other permanent crops n.e.c."
cap label var Z1000 "Vegetative materials used primarily for plaiting"
cap label var K0000 "Kitchen gardens"
cap label var K0000T "Kitchen gardens - outdoor"
cap label var K0000T_UAA09S "Kitchen gardens outdoor and other utilised agricultural area n.e.c. under glass or high accessible cover"
cap label var K1000 "Vegetables from kitchen gardens"
cap label var K2000 "Fruits from kitchen gardens"
cap label var SAA "Special agricultural production areas"
cap label var U0000 "Mushrooms"
cap label var U1000 "Cultivated mushrooms"
cap label var U1100 "Champignons"
cap label var U1900 "Other cultivated mushrooms n.e.c."
cap label var U2000 "Wild mushrooms"
cap label var SAA9 "Other special agricultural production areas"
cap label var NUAA "Unutilised agricultural area"
cap label var WA "Wooded areas"
cap label var SRCAA "Short rotation coppice areas"
cap label var FA9 "Other areas on the farms"
cap label var CRP9 "Other crop products"
cap label var CRP9ORG "Other organic crop products"
cap label var CRP99 "Other crop products n.e.c."
cap label var NONE "None"
