cap label var TOTAL "Total"
cap label var COL "Collective pay agreement"
cap label var NAT "National level or interconfederal agreement"
cap label var IND "Industry agreement"
cap label var INDREG "Agreement for individual industries in individual regions"
cap label var ENT "Enterprise or single-employer agreement"
cap label var UNIT "Agreement applying only to the employees in one local unit"
cap label var OTH "Any other type of agreement"
cap label var NONE "No collective pay agreement exists"
cap label var UNK "Unknown"
