cap label var WA_1 "Total gross abstraction"
cap label var WA_1_1 "Abstraction by public water supply"
cap label var WA_1_2 "Abstraction by agriculture, forestry, fishing (total)"
cap label var WA_1_2_1 "Abstraction by agriculture, for irrigation purposes"
cap label var WA_1_3 "Abstraction by mining and quarrying"
cap label var WA_1_4 "Abstraction by manufacturing industry (total)"
cap label var WA_1_4_1 "Abstraction by manufacturing industry, for foodprocessing industry"
cap label var WA_1_4_2 "Abstraction by manufacturing industry, for cooling purposes"
cap label var WA_1_5 "Abstraction by production of electricity, for cooling purposes"
cap label var WA_1_6 "Abstraction by services"
cap label var WA_1_7 "Construction and other industrial activities"
cap label var WA_1_8 "Abstraction by households"
cap label var WA_1_8_1 "Abstraction by households of which: Returned water"
cap label var WA_1_9 "Returned water (before use or without use) - (only available for total surface and groundwater)"
cap label var WA_1_10 "Net abstraction - (only available for total surface and groundwater)"
cap label var WA_1_11 "Abstraction by any other economic activity (e.g. construction)"
cap label var WA_2 "Water abstraction for purposes of hydroelectricity generation"
cap label var WEI "Water exploitation index"
cap label var W18_1 "Population connected to public water supply (% of national population) - (only available for public water supply)"
cap label var W18_2 "Total supply"
cap label var W18_2_1 "Supply to agriculture, forestry, fishing (total)"
cap label var W18_2_1_1 "Supply to agriculture, for irrigation purposes"
cap label var W18_2_2 "Supply to mining and quarrying"
cap label var W18_2_3 "Supply to manufacturing industries (Total)"
cap label var W18_2_3_1 "Supply to food processing industry"
cap label var W18_2_3_2 "Supply to basic metals industry"
cap label var W18_2_3_3 "Supply to motor vehicles and transport equipment industry"
cap label var W18_2_3_4 "Supply to the textiles industry"
cap label var W18_2_3_5 "Supply to paper and paper products industry"
cap label var W18_2_3_6 "Supply to chemicals, refined petroleum industry"
cap label var W18_2_3_7 "Supply to other manufacturing industry"
cap label var W18_2_3_8 "Supply to manufacturing industries, for cooling purposes"
cap label var W18_2_4 "Supply to the production and distribution of electricity (Total)"
cap label var W18_2_4_1 "Supply to the production and distribution of electricity, for cooling purposes"
cap label var W18_2_5 "Supply to all industrial activities"
cap label var W18_2_6 "Supply to construction"
cap label var W18_2_7 "Supply to the domestic sector (Total)"
cap label var W18_2_7_1 "Supply to the domestic sector, services"
cap label var W18_2_7_2 "Supply to the domestic sector, households"
cap label var WW2_1 "Primary treatment"
cap label var WW2_2 "Secondary treatment"
cap label var WW2_3 "Tertiary treatment"
cap label var WW2_3_1 "Tertiary treatment with nitrogen removal"
cap label var WW2_3_2 "Tertiary treatment with phosporus removal"
cap label var WW2_4 "Total treatment"
cap label var WW2_4_1 "Total treatment with at least secondary treatment - (available only for independent treatment)"
cap label var WW2_4_2 "Total of which with dephosphatation facilities (old version)"
cap label var SL_1 "Total sludge production"
cap label var SL_2 "Total sludge disposal"
cap label var SL_2_1 "Agricultural use"
cap label var SL_2_2 "Compost and other applications"
cap label var SL_2_3 "Landfill"
cap label var SL_2_4 "Dumping at sea"
cap label var SL_2_5 "Incineration"
cap label var SL_2_6 "Others"
cap label var SL_3 "Agricultural use"
cap label var SL_4 "Compost and other applications"
cap label var SL_4_1 "Agricultural use (in volume: 1 000 m3)"
cap label var SL_4_2 "Compost and other applications (in volume: 1 000 m3)"
cap label var SL_4_3 "Landfill (in volume: 1 000 m3)"
cap label var SL_4_4 "Dumping at sea (in volume: 1 000 m3)"
cap label var SL_4_5 "Incineration (in volume: 1 000 m3)"
cap label var SL_4_6 "Others (in volume: 1 000 m3)"
cap label var SL_5 "Landfill"
cap label var SL_6 "Dumping at sea"
cap label var SL_6_1 "Agricultural use (in dry solids: kg/capita)"
cap label var SL_6_2 "Compost and other applications (in dry solids: kg/capita)"
cap label var SL_6_3 "Landfill (in dry solids: kg/capita)"
cap label var SL_6_4 "Dumping at sea (in dry solids: kg/capita)"
cap label var SL_6_5 "Incineration (in dry solids: kg/capita)"
cap label var SL_6_6 "Others (in dry solids: kg/capita)"
cap label var SL_7 "Incineration"
cap label var SL_8 "Others"
cap label var SL_8_1 "Agricultural use (in volume: m3/capita)"
cap label var SL_8_2 "Compost and other applications (in volume: m3/capita)"
cap label var SL_8_3 "Landfill (in volume: m3/capita)"
cap label var SL_8_4 "Dumping at sea (in volume: m3/capita)"
cap label var SL_8_5 "Incineration (in volume: m3/capita)"
cap label var SL_8_6 "Others (in volume: m3/capita)"
cap label var WA_3 "Abstraction from artificial reservoirs"
cap label var WA_4 "Illegal abstractions, total (estimates)"
cap label var WA_4_1 "Illegal abstractions (estimates) : surface water"
cap label var WA_4_2 "Illegal abstractions (estimates) : groundwater"
cap label var W18_2_8 "Supply to other economic activities"
cap label var WA_1_12 "Self abstraction for own use"
cap label var WW2_5 "Secondary and Tertiary Treatment"
cap label var WW2_6 "Idenpendent Treatment"
