cap label var TOTAL "Total enterprises"
cap label var INNO "Innovative enterprises (including enterprises with abandoned/suspended or on-going innovation activities)"
cap label var INNO_PP "Product and/or process innovative enterprises only (including enterprises with abandoned/suspended or on-going innovation activities)"
cap label var INNO_NPP "Organisation and/or marketing innovative enterprises only"
cap label var INNO_PPANPP "Product and/or process AND organisation and/or marketing innovative enterprises only (including enterprises with abandoned/suspended or on-going innovation activities)"
cap label var INNOACT "Product and/or process innovative enterprises, regardless of organisational or marketing innovation (including enterprises with abandoned/suspended or on-going innovation activities)"
cap label var PAOP "Novel innovators, product and/or process"
cap label var INPDTONLY "Product innovative enterprises only"
cap label var INPCSONLY "Process innovative enterprises only"
cap label var PANDP "Product and process innovative enterprises only"
cap label var INONONAB "Enterprises with abandoned/suspended and on-going innovation activities only"
cap label var NON_INNO "Non-innovative enterprises"
cap label var INABA "Enterprises with abandoned/suspended innovation activities only"
cap label var INONG "Enterprises with on-going innovation activities only"
cap label var INABA_ONG "Enterprises with abandoned/suspended and on-going innovation activities only"
cap label var INPDT "Product innovative enterprises (regardless of any other type of innovation)"
cap label var INPCS "Process innovative enterprises (regardless of any other type of innovation)"
cap label var INMKT "Marketing innovative enterprises (regardless of any other type of innovation)"
cap label var INNORGMK "Organisation and/or marketing innovative enterprises, regardless of product or process innovation"
cap label var INORG "Organisation innovative enterprises (regardless of any other type of innovation)"
cap label var MKT_ONLY "Marketing innovative enterprises only"
cap label var OANDM "Organisation and marketing innovative enterprises only"
cap label var ORG_ONLY "Organisation innovative enterprises only"
cap label var PROD_PCS "Product and/or process innovative enterprises excluding enterprises with only ongoing and/or abandoned activities"
cap label var INNOS "Entreprises that have introduced an innovation (all types)"
