cap label var TOTAL "Total"
cap label var PUBOFFICE "Contact public employment office"
cap label var PRIVOFFICE "Contact private employment office"
cap label var PERSEMPR "Person contacted employer directly"
cap label var EMPRPERS "Employer contacted person directly"
cap label var REFRAC "Relatives, friends or acquaintances"
cap label var EDUC "Education or training institution"
cap label var APPLYEMP "Apply to employers directly"
cap label var ASKFRIENDS "Ask friends, relatives, trade unions"
cap label var PUBANSWADV "Publish or answer advertisements"
cap label var STUDYADV "Study advertisements"
cap label var TESTSINTER "Took test, interview, examination"
cap label var LOOKLAND "Look for land, premises, equipment"
cap label var LOOKLICENC "Look for permits, licenses, financial resources"
cap label var OTHER "Other method"
cap label var NAP "Not applicable"
cap label var NRP "No response"
cap label var NRESP "No answer"
