cap label var TOTAL "Total"
cap label var MV_WALK_CYCL_GET "Walking or cycling to get to and from place"
cap label var MV_WALK_GET "Walking to get to and from place"
cap label var MV_CYCL_GET "Cycling to get to and from place"
cap label var MV_AERO_MSC "Aerobic and muscle-strengthening"
cap label var MV_AERO "Aerobic"
cap label var MV_AERO_SPRT "Aerobic sports"
cap label var MV_MSC "Muscle-strengthening"
cap label var MV_SITT "Sitting"
cap label var MV_STD "Standing"
cap label var MV_MOD_EFF "Moderate physical effort"
cap label var MV_HVY_EFF "Heavy physical effort"
cap label var PHA_0 "No information"
cap label var PHA_1 "Operating machine"
cap label var PHA_2 "Working with hand-held tools"
cap label var PHA_3 "Driving/being on board a means of transport or handling equipment"
cap label var PHA_4 "Handling of objects"
cap label var PHA_5 "Carrying by hand"
cap label var PHA_6 "Movement"
cap label var PHA_7 "Presence"
cap label var PHA_9 "Other Specific Physical Activities not listed in this classification"
cap label var NRP "No response"
