cap label var TOTAL "Total"
cap label var KITC "Separate kitchen in the housing unit"
cap label var WTR "Piped water in the housing unit"
cap label var NWTR "No piped water in the housing unit"
cap label var WTR_UNK "Piped water - unknown"
cap label var TOIL "Flush toilet in the housing unit"
cap label var NTOIL "No flush toilet in the housing unit"
cap label var TOIL_UNK "Flush toilet - unknown"
cap label var BATH "Fixed bath or shower in the housing unit"
cap label var NBATH "No fixed bath or shower in the housing unit"
cap label var BATH_UNK "Bath, shower in building - unknown"
cap label var HEAT "Central heating"
cap label var NHEAT "No central heating"
cap label var HEAT_UNK "Central heating - unknown"
cap label var UNK "Unknown"
cap label var OTH "Other"
