cap label var TOTAL "Total"
cap label var NINFO "No information"
cap label var WPR1 "Production, manufacturing, processing, storing"
cap label var WPR2 "Excavation, construction, repair, demolition"
cap label var WPR3 "Agriculture, forestry, horticulture, fish farming, work with live animals"
cap label var WPR4 "Service provided to enterprise and/or to the general public; intellectual activity"
cap label var WPR5 "Other work processes related to: production, manufacturing, processing, storing (WPR1); excavation, construction, repair, demolition (WPR2); agriculture, forestry, horticulture, fish farming, work with live animals (WPR3); service provided to enterprise and/or to the general public, intellectual activity (WPR4)"
cap label var WPR6 "Movement, sport, artistic activity"
cap label var OTH "Other"
