cap label var TOTAL "Total"
cap label var PACK "Package travel"
cap label var NPACK "Non-package travel"
cap label var TRA_TO_TA "Booking of the main means of transport via tour operator or travel agency"
cap label var ACC_TO_TA "Booking of the main means of accommodation via tour operator or travel agency"
cap label var TRA_WEB "Internet booking of the main means of transport"
cap label var ACC_WEB "Internet booking of the main means of accommodation"
cap label var TO_TA "Tour operator or travel agency"
cap label var TO_TA_OCP "Tour operator or travel agency, of which online collaborative platform"
cap label var DIRECT "Direct booking with the service provider"
cap label var NBOOK "No booking needed"
