cap label var TOTAL "Total"
cap label var DIR "Direct costs"
cap label var LCP "Labour costs of participants"
cap label var NET "Net contributions to training funds"
cap label var FUL_RED "Full or reduced price"
cap label var FUL "Full price"
cap label var RED "Reduced price"
cap label var FREE "Cost free"
cap label var NONE_NUSE "No costs as not used"
