cap label var TOTALNOREROUTE "Total expenditure"
cap label var SPBENEFNOREROUTE "Social protection benefits"
cap label var SNONTARGETNOREROUTE "Non means-tested benefits"
cap label var STARGETNOREROUTE "Means-tested benefits"
cap label var ADMIN "Administration costs"
cap label var OTHER "Other expenditure"
cap label var SICK "Sickness/Health care"
cap label var DISA "Disability"
cap label var OLD "Old age"
cap label var SURVIV "Survivors"
cap label var FAM "Family/Children"
cap label var UNEMPLOY "Unemployment"
cap label var HOUSE "Housing"
cap label var EXCLU "Social exclusion n.e.c."
cap label var SICKDISA "Sickness / healthcare and disability"
cap label var OLDSURVIV "Old age and survivors"
cap label var HOUSEEXCLU "Housing and Social exclusion n.e.c."
