cap label var DO__D__F "Direct investment abroad (DIA)"
cap label var DO__D__F5A "DIA Equity other than reinvested earnings"
cap label var DO__D1D2__F5A "DIA Equity other than reinvested earnings (excluding equity between fellow enterprises)"
cap label var DO__U1__F5A "DIA Equity other than reinvested earnings between fellow enterprises (UCP is resident in the reporting country)"
cap label var DO__D__F5B "DIA Reinvestment of earnings"
cap label var DO__D__F5 "DIA Equity"
cap label var DO__D1D2__F5 "DIA Equity (excluding equity between fellow enterprises)"
cap label var DO__U1__F5 "DIA Equity between fellow enterprises (UCP is resident in the reporting country)"
cap label var DO__D__FL "DIA Debt instruments"
cap label var DO__D1D2__FL "DIA Debt instruments (excluding debt between fellow enterprises)"
cap label var DO__U1__FL "DIA Debt instruments between fellows (UCP is resident in the reporting country)"
cap label var DI__D__F "Direct investment in the reporting economy (DIRE)"
cap label var DI__D__F5A "DIRE Equity other than reinvested earnings"
cap label var DI__D1D2__F5A "DIRE Equity other than reinvested earnings (excluding equity between fellow enterprises)"
cap label var DI__U2__F5A "DIRE Equity other than reinvested earnings between fellow enterprises (UCP is not resident in the reporting country)"
cap label var DI__U21__F5A "Of which: UCP is resident in other euro area country"
cap label var DI__U22__F5A "UCP is resident in the EU but outside euro area"
cap label var DI__U23__F5A "UCP is resident outside the EU"
cap label var DI__D__F5B "DIRE Reinvestment of earnings"
cap label var DI__D__F5 "DIRE Equity"
cap label var DI__D1D2__F5 "DIRE Equity (excluding equity between fellow enterprises)"
cap label var DI__U2__F5 "DIRE Equity between fellow enterprises (UCP is not resident in the reporting country)"
cap label var DI__U21__F5 "Of which: UCP is resident in other euro area country"
cap label var DI__U22__F5 "UCP is resident in the EU but outside euro area"
cap label var DI__U23__F5 "UCP is resident outside the EU"
cap label var DI__D__FL "DIRE Debt instruments"
cap label var DI__D1D2__FL "DIRE Debt instruments (excluding debt between fellow enterprises)"
cap label var DI__U2__FL "DIRE Debt instruments between fellows (UCP is not resident in the reporting country)"
cap label var DI__U21__FL "Of which: UCP is resident in other euro area country"
cap label var DI__U22__FL "UCP is resident in the EU but outside euro area"
cap label var DI__U23__FL "UCP is resident outside the EU"
cap label var DO__D4P__D__F "Direct investment abroad"
cap label var DO__D42S__D__F5 "Direct investment abroad; Dividends"
cap label var DO__D42S__D1D2__F5 "Direct investment abroad; Dividends (excluding dividends between fellow enterprises)"
cap label var DO__D42S__U1__F5 "Direct investment abroad; Dividends between fellow enterprises (UCP is resident in the reporting country)"
cap label var DO__D43S__D__F5 "Direct investment abroad; Reinvested earnings"
cap label var DO__D4Q__D__FL "Direct investment abroad; Income on debt"
cap label var DO__D4Q__D1D2__FL "Direct investment abroad; Income on debt (excluding income on debt between fellow enterprises)"
cap label var DO__D4Q__U1__FL "Direct investment abroad; Income on debt between fellows (UCP is resident in the reporting country)"
cap label var DI__D4P__D__F "Direct investment in the reporting economy"
cap label var DI__D42S__D__F5 "Direct investment in the reporting economy; Dividends"
cap label var DI__D42S__D1D2__F5 "Direct investment in the reporting economy; Dividends (excluding dividends between fellow enterprises)"
cap label var DI__D42S__U2__F5 "Direct investment in the reporting economy; Dividends between fellow enterprises (UCP is not resident in the reporting country)"
cap label var DI__D42S__U21__F5 "Of which: UCP is resident in other euro area country"
cap label var DI__D42S__U22__F5 "UCP is resident in the EU but outside euro area"
cap label var DI__D42S__U23__F5 "UCP is resident outside the EU"
cap label var DI__D43S__D__F5 "Direct investment in the reporting economy; Reinvested earnings"
cap label var DI__D4Q__D__FL "Direct investment in the reporting economy; Income on debt"
cap label var DI__D4Q__D1D2__FL "Direct investment in the reporting economy; Income on debt (excluding income on debt between fellow enterprises)"
cap label var DI__D4Q__U2__FL "Direct investment in the reporting economy; Income on debt between fellows (UCP is not resident in the reporting country)"
cap label var DI__D4Q__U21__FL "Direct investment in the reporting economy; Income on debt between fellows (UCP is not resident in the reporting country); UCP is resident in other euro area country"
cap label var DI__D4Q__U22__FL "Direct investment in the reporting economy; Income on debt between fellows (UCP is not resident in the reporting country); UCP is resident in the EU but outside euro area"
cap label var DI__D4Q__U23__FL "Direct investment in the reporting economy; Income on debt between fellows (UCP is not resident in the reporting country); UCP is resident outside the EU"
cap label var NAP "Not applicable"
