cap label var VIM_TOT "Total main grape varieties"
cap label var VIRM_TOT "Total main red grape varieties (R)"
cap label var VIR001 "Agiorgitiko (R)"
cap label var VIR002 "Aglianico (R)"
cap label var VIR003 "Aglianico del Vulture (R)"
cap label var VIR004 "Alfrocheiro (R)"
cap label var VIR004A "Tinta Bastardinha (R)"
cap label var VIR005 "Alicante Henri Bouschet (R)"
cap label var VIR005A "Alicante Bouschet (R)"
cap label var VIR005B "Garnacha tintorera (R)"
cap label var VIR006 "Alphonse Lavallee (R)"
cap label var VIR006A "Alphon Lavallee (R)"
cap label var VIR007 "Ancellotta (R)"
cap label var VIR008 "Aramon noir (R)"
cap label var VIR008A "Aramon (R)"
cap label var VIR009 "Avarengo (R)"
cap label var VIR010 "Babeasca neagra (R)"
cap label var VIR011 "Baga (R)"
cap label var VIR012 "Barbera nera (R)"
cap label var VIR013 "Trousseau noir (R)"
cap label var VIR013A "Bastardo (R)"
cap label var VIR013B "Graciosa (R)"
cap label var VIR014 "Blauburger (R)"
cap label var VIR015 "Blaufrankisch (R)"
cap label var VIR015A "Burgund mare (R)"
cap label var VIR015B "Frankovka (R)"
cap label var VIR015C "Frankovka modra (R)"
cap label var VIR015D "Kekfrankos (R)"
cap label var VIR015E "Limberger, blauer (R)"
cap label var VIR015F "Modra frankinja (R)"
cap label var VIR016 "Bobal (R)"
cap label var VIR017 "Bombino nero (R)"
cap label var VIR017A "Bombino rosso (R)"
cap label var VIR018 "Bonarda piemontese (R)"
cap label var VIR018A "Bonarda (R)"
cap label var VIR019 "Brachetto (R)"
cap label var VIR020 "Cabernet franc (R)"
cap label var VIR021 "Cabernet Sauvignon (R)"
cap label var VIR022 "Borracal (R)"
cap label var VIR022A "Caino tinto (R)"
cap label var VIR023 "Calabrese (R)"
cap label var VIR024 "Caladoc (R)"
cap label var VIR025 "Canaiolo nero (R)"
cap label var VIR026 "Carignan noir (R)"
cap label var VIR026A "Carignan (R)"
cap label var VIR026B "Carignano (R)"
cap label var VIR027 "Carmenere (R)"
cap label var VIR028 "Castelao (R)"
cap label var VIR028A "Joao-de-Santarem (R)"
cap label var VIR028B "Periquita (R)"
cap label var VIR029 "Ciliegiolo (R)"
cap label var VIR030 "Cinsaut (R)"
cap label var VIR031 "Corvina (R)"
cap label var VIR031A "Cruina (R)"
cap label var VIR032 "Corvinone (R)"
cap label var VIR033 "Cot (R)"
cap label var VIR034 "Croatina (R)"
cap label var VIR035 "Dolcetto (R)"
cap label var VIR036 "Dornfelder (R)"
cap label var VIR037 "Duras (R)"
cap label var VIR038 "Fer (R)"
cap label var VIR039 "Feteasca neagra (R)"
cap label var VIR040 "Forcallat tinta (R)"
cap label var VIR041 "Frappato di vittoria (R)"
cap label var VIR041A "Frappato (R)"
cap label var VIR042 "Freisa (R)"
cap label var VIR043 "Gaglioppo (R)"
cap label var VIR044 "Gamay noir (R)"
cap label var VIR044A "Gamay (R)"
cap label var VIR045 "Garnacha peluda (R)"
cap label var VIR046 "Garnacha tinta (R)"
cap label var VIR046A "Cannonau (R)"
cap label var VIR046B "Garnacha (R)"
cap label var VIR046C "Grenache (R)"
cap label var VIR046D "Tocai rosso (R)"
cap label var VIR047 "Graciano (R)"
cap label var VIR048 "Gran negro (R)"
cap label var VIR049 "Grand noir (R)"
cap label var VIR050 "Greco nero (R)"
cap label var VIR051 "Grignolino (R)"
cap label var VIR052 "Grolleau noir (R)"
cap label var VIR052A "Grolleau (R)"
cap label var VIR053 "Mouraton (R)"
cap label var VIR053A "Juan Garcia (R)"
cap label var VIR054 "Jurancon noir (R)"
cap label var VIR055 "Kadarka kek (R)"
cap label var VIR055A "Gamza (R)"
cap label var VIR055B "Kadarka (R)"
cap label var VIR056 "Kotsifali (R)"
cap label var VIR057 "Lagrein (R)"
cap label var VIR058 "Lambrusco a foglia frastagliata (R)"
cap label var VIR059 "Lambrusco di Sorbara (R)"
cap label var VIR060 "Lambrusco Grasparossa (R)"
cap label var VIR061 "Lambrusco Maestri (R)"
cap label var VIR062 "Lambrusco Marani (R)"
cap label var VIR063 "Lambrusco Salamino (R)"
cap label var VIR064 "Liatiko (R)"
cap label var VIR065 "Listan prieto (R)"
cap label var VIR065A "Listan negro (R)"
cap label var VIR066 "Magliocco canino (R)"
cap label var VIR067 "Malvasia nera (R)"
cap label var VIR068 "Malvasia nera di Brindisi (R)"
cap label var VIR069 "Malvasia Preta (R)"
cap label var VIR070 "Mandilaria (R)"
cap label var VIR071 "Marselan (R)"
cap label var VIR072 "Marufo (R)"
cap label var VIR072A "Mourisco Roxo (R)"
cap label var VIR073 "Marzemino (R)"
cap label var VIR074 "Mavro (R)"
cap label var VIR075 "Mavroudi (R)"
cap label var VIR076 "Mavrud (R)"
cap label var VIR077 "Mazuela (R)"
cap label var VIR078 "Mencia (R)"
cap label var VIR078A "Jaen (R)"
cap label var VIR079 "Merlot noir (R)"
cap label var VIR079A "Merlot (R)"
cap label var VIR080 "Pinot Meunier (R)"
cap label var VIR080A "Meunier (R)"
cap label var VIR080B "Mullerrebe (R)"
cap label var VIR080C "Schwarzriesling (R)"
cap label var VIR081 "Miguel del arco (R)"
cap label var VIR082 "Molinara (R)"
cap label var VIR083 "Mollar cano (R)"
cap label var VIR083A "Mollar (R)"
cap label var VIR083B "Negramoll (R)"
cap label var VIR084 "Monastrell (R)"
cap label var VIR084A "Mourvedre (R)"
cap label var VIR085 "Monica nera (R)"
cap label var VIR085A "Monica (R)"
cap label var VIR086 "Montepulciano (R)"
cap label var VIR087 "Moravia agria (R)"
cap label var VIR088 "Moravia dulce (R)"
cap label var VIR089 "Moreto (R)"
cap label var VIR090 "Moristel (R)"
cap label var VIR091 "Mourisco (R)"
cap label var VIR092 "Moschato mavro (R)"
cap label var VIR093 "Muscat Hamburg (R)"
cap label var VIR093A "Muscat Hambourg (R)"
cap label var VIR094 "Nebbiolo (R)"
cap label var VIR095 "Negrette (R)"
cap label var VIR096 "Negro amaro (R)"
cap label var VIR097 "Nerello Cappuccio (R)"
cap label var VIR098 "Nerello Mascalese (R)"
cap label var VIR099 "Pamid (R)"
cap label var VIR100 "Verdot petit (R)"
cap label var VIR101 "Piedirosso (R)"
cap label var VIR102 "Pinot noir (R)"
cap label var VIR102A "Blauburgunder (R)"
cap label var VIR102B "Blauer Burgunder (R)"
cap label var VIR102C "Blauer Spatburgunder (R)"
cap label var VIR102D "Pinot (R)"
cap label var VIR102E "Rulandske modre (R)"
cap label var VIR103 "Plantet (R)"
cap label var VIR104 "Plavac mali (R)"
cap label var VIR104A "Plavac mali crni (R)"
cap label var VIR105 "Plavina crna (R)"
cap label var VIR106 "Portugieser Blau (R)"
cap label var VIR106A "Kekoporto (R)"
cap label var VIR106B "Modry Portugal (R)"
cap label var VIR106C "Oporto (R)"
cap label var VIR106D "Portoghese (R)"
cap label var VIR106E "Portugieser, Blauer (R)"
cap label var VIR107 "Prieto picudo tinto (R)"
cap label var VIR107A "Prieto picudo (R)"
cap label var VIR108 "Primitivo (R)"
cap label var VIR109 "Raboso Piave (R)"
cap label var VIR110 "Refosco dal peduncolo rosso (R)"
cap label var VIR111 "Refosco (R)"
cap label var VIR111A "Refosk (R)"
cap label var VIR112 "Regent (R)"
cap label var VIR113 "Rojal tinta (R)"
cap label var VIR113A "Rojal (R)"
cap label var VIR114 "Romeiko (R)"
cap label var VIR115 "Rondinella (R)"
cap label var VIR116 "Rosioara (R)"
cap label var VIR117 "Royal (R)"
cap label var VIR118 "Rufete (R)"
cap label var VIR118A "Tinta Pinheira (R)"
cap label var VIR119 "Sagrantino (R)"
cap label var VIR120 "Saint Laurent (R)"
cap label var VIR120A "Svatovavrinecke (R)"
cap label var VIR121 "Sangiovese (R)"
cap label var VIR121A "Nielluccio (R)"
cap label var VIR122 "Santareno (R)"
cap label var VIR123 "Schiava lombarda (R)"
cap label var VIR123A "Schiava (R)"
cap label var VIR124 "Schiava gentile (R)"
cap label var VIR125 "Schiava grossa (R)"
cap label var VIR125A "Trollinger, blauer (R)"
cap label var VIR126 "Sciaccarello (R)"
cap label var VIR127 "Siroka melniska (R)"
cap label var VIR127A "Shiroka melnishka loza (R)"
cap label var VIR128 "Souson (R)"
cap label var VIR129 "Storgoziya (R)"
cap label var VIR129A "Storgozia (R)"
cap label var VIR130 "Syrah (R)"
cap label var VIR130A "Shiraz (R)"
cap label var VIR131 "Sirah (R)"
cap label var VIR132 "Tannat (R)"
cap label var VIR133 "Tempranillo tinto (R)"
cap label var VIR133A "Aragonez (R)"
cap label var VIR133B "Tinta Roriz (R)"
cap label var VIR133C "Tinto de toro (R)"
cap label var VIR134 "Teroldego (R)"
cap label var VIR135 "Tinta (R)"
cap label var VIR136 "Tinta Barroca (R)"
cap label var VIR137 "Tinta Carvalha (R)"
cap label var VIR138 "Tinta Negra (R)"
cap label var VIR139 "Tinto de la pampana blanca (R)"
cap label var VIR140 "Tinto velasco (R)"
cap label var VIR141 "Touriga Franca (R)"
cap label var VIR142 "Touriga nacional (R)"
cap label var VIR143 "Trepat (R)"
cap label var VIR144 "Trincadeira (R)"
cap label var VIR144A "Tinta Amarela (R)"
cap label var VIR144B "Trincadeira Preta (R)"
cap label var VIR145 "Uva di Troia (R)"
cap label var VIR146 "Uva Longanesi (R)"
cap label var VIR147 "Villard noir (R)"
cap label var VIR148 "Vinhao (R)"
cap label var VIR148A "Sousao (R)"
cap label var VIR149 "Vranac (R)"
cap label var VIR150 "Xynomavro (R)"
cap label var VIR150A "Xinomavro (R)"
cap label var VIR151 "Kavcina crna (R)"
cap label var VIR151A "Zametovka (R)"
cap label var VIR152 "Zweigeltrebe Blau (R)"
cap label var VIR152A "Rotburger (R)"
cap label var VIR152B "Zweigelt (R)"
cap label var VIR152C "Zweigelt, Blauer (R)"
cap label var VIR152D "Zweigeltrebe (R)"
cap label var VIR153 "Colorino (R)"
cap label var VIR154 "Fokiano (R)"
cap label var VIR155 "Mavrodaphni (R)"
cap label var VIRM_OTH "Other main red grape varieties (R)"
cap label var VIRMM_TOT "Other main red mixed grape varieties (R)"
cap label var VIWM_TOT "Total main white grape varieties (W)"
cap label var VIW001 "Airen (W)"
cap label var VIW002 "Alarije (W)"
cap label var VIW003 "Albana (W)"
cap label var VIW004 "Albillo mayor (W)"
cap label var VIW005 "Albillo real (W)"
cap label var VIW006 "Alicante branco (W)"
cap label var VIW007 "Aligote (W)"
cap label var VIW008 "Alvarinho (W)"
cap label var VIW008A "Albarino (W)"
cap label var VIW009 "Ansonica (W)"
cap label var VIW010 "Antao vaz (W)"
cap label var VIW011 "Arinto (W)"
cap label var VIW011A "Pederna (W)"
cap label var VIW012 "Arneis (W)"
cap label var VIW013 "Assyrtiko (W)"
cap label var VIW013A "Asirtiko (W)"
cap label var VIW014 "Athiri aspro (W)"
cap label var VIW014A "Athiri (W)"
cap label var VIW015 "Auxerrois (W)"
cap label var VIW016 "Avesso (W)"
cap label var VIW017 "Azal branco (W)"
cap label var VIW017A "Azal (W)"
cap label var VIW018 "Bacchus weiss (W)"
cap label var VIW018A "Bacchus (W)"
cap label var VIW019 "Baco blanc (W)"
cap label var VIW020 "Beba (W)"
cap label var VIW021 "Bellone (W)"
cap label var VIW022 "Bianca (W)"
cap label var VIW023 "Biancame (W)"
cap label var VIW024 "Bical (W)"
cap label var VIW024A "Borrado das Moscas (W)"
cap label var VIW025 "Bombino bianco"
cap label var VIW026 "Borba"
cap label var VIW027 "Bourboulenc"
cap label var VIW028 "Calagrano"
cap label var VIW029 "Carignan blanc (W)"
cap label var VIW029A "Carinena blanco (W)"
cap label var VIW030 "Catarratto bianco comune (W)"
cap label var VIW030A "Catarratto commune (W)"
cap label var VIW031 "Catarratto bianco lucido (W)"
cap label var VIW031A "Cataratto lucido (W)"
cap label var VIW032 "Cayetana blanca (W)"
cap label var VIW032A "Blanca cayetana (W)"
cap label var VIW033 "Chardonnay blanc (W)"
cap label var VIW033A "Chardonnay (W)"
cap label var VIW033B "Feinburgunder (W)"
cap label var VIW033C "Morillon (W)"
cap label var VIW033D "Sardone (W)"
cap label var VIW034 "Chasan (W)"
cap label var VIW035 "Chasselas blanc (W)"
cap label var VIW035A "Chasselas (W)"
cap label var VIW035B "Gutedel, Weisser (W)"
cap label var VIW036 "Chenin blanc (W)"
cap label var VIW036A "Chenin (W)"
cap label var VIW037 "Clairette blanche (W)"
cap label var VIW037A "Clairette (W)"
cap label var VIW038 "Cococciola (W)"
cap label var VIW039 "Coda di volpe bianca (W)"
cap label var VIW040 "Codega do Larinho (W)"
cap label var VIW041 "Colombard (W)"
cap label var VIW042 "Cortese (W)"
cap label var VIW043 "Cramposie selectionata (W)"
cap label var VIW044 "Cserszegi fuszeres (W)"
cap label var VIW045 "Diagalves (W)"
cap label var VIW046 "Dimyat (W)"
cap label var VIW047 "Elbling Weiss (W)"
cap label var VIW047A "Elbling, Weisser (W)"
cap label var VIW048 "Ezerfurtu (W)"
cap label var VIW049 "Ezerjo (W)"
cap label var VIW050 "Falanghina flegrea (W)"
cap label var VIW050A "Falanghina (W)"
cap label var VIW051 "Fernao Pires (W)"
cap label var VIW051A "Maria Gomes (W)"
cap label var VIW052 "Feteasca alba (W)"
cap label var VIW052A "Dievcie hrozno (W)"
cap label var VIW052B "Leanyka (W)"
cap label var VIW053 "Feteasca regala (W)"
cap label var VIW053A "Kiralyleanyka (W)"
cap label var VIW054 "Fiano (W)"
cap label var VIW055 "Folle blanche (W)"
cap label var VIW056 "Francuse (W)"
cap label var VIW056A "Francusa (W)"
cap label var VIW057 "Friulano (W)"
cap label var VIW057A "Tocai friulano (W)"
cap label var VIW058 "Furmint (W)"
cap label var VIW058A "Sipon (W)"
cap label var VIW059 "Galbena de Odobesti (W)"
cap label var VIW060 "Garganega (W)"
cap label var VIW061 "Garnacha blanca (W)"
cap label var VIW061A "Grenache blanc (W)"
cap label var VIW062 "Glera lunga (W)"
cap label var VIW062A "Prosecco lungo (W)"
cap label var VIW063 "Gouveio (W)"
cap label var VIW063A "Godello (W)"
cap label var VIW064 "Gouveio Real (W)"
cap label var VIW065 "Grasa de Cotnari (W)"
cap label var VIW066 "Grecanico dorato (W)"
cap label var VIW067 "Grechetto bianco (W)"
cap label var VIW067A "Grechetto (W)"
cap label var VIW068 "Greco bianco (W)"
cap label var VIW069 "Grillo (W)"
cap label var VIW070 "Harslevelu (W)"
cap label var VIW071 "Huxelrebe (W)"
cap label var VIW072 "Iordan (W)"
cap label var VIW072A "Iordana (W)"
cap label var VIW073 "Irsai Oliver (W)"
cap label var VIW074 "Izsaki sarfeher"
cap label var VIW074A "Arany sarfeher"
cap label var VIW075 "Jacquere (W)"
cap label var VIW076 "Kerner (W)"
cap label var VIW077 "Koevidinka (W)"
cap label var VIW077A "Kovidinka (W)"
cap label var VIW078 "Kunleany (W)"
cap label var VIW079 "Lakhegyi mezes (W)"
cap label var VIW080 "Len de l'El (W)"
cap label var VIW081 "Loureiro blanco (W)"
cap label var VIW081A "Loureiro (W)"
cap label var VIW082 "Malvasia (W)"
cap label var VIW083 "Malvasia bianca (W)"
cap label var VIW084 "Malvasia bianca di Candia (W)"
cap label var VIW085 "Malvasia bianca lunga (W)"
cap label var VIW086 "Malvasia Branca (W)"
cap label var VIW087 "Malvasia del Lazio (W)"
cap label var VIW088 "Malvasia di Candia aromatica (W)"
cap label var VIW089 "Malvasia Fina (W)"
cap label var VIW089A "Boal (W)"
cap label var VIW090 "Malvasia Istriana (W)"
cap label var VIW090A "Malvazija (W)"
cap label var VIW090B "Malvazija Istarska (W)"
cap label var VIW091 "Manseng gros blanc (W)"
cap label var VIW091A "Gros Manseng blanc (W)"
cap label var VIW092 "Manseng petit blanc (W)"
cap label var VIW092A "Petit Manseng (W)"
cap label var VIW093 "Mantuo (W)"
cap label var VIW093A "Chelva (W)"
cap label var VIW093B "Mantua (W)"
cap label var VIW093C "Montua (W)"
cap label var VIW094 "Marsanne (W)"
cap label var VIW095 "Mauzac blanc (W)"
cap label var VIW095A "Mauzac (W)"
cap label var VIW096 "Melon (W)"
cap label var VIW097 "Merseguera (W)"
cap label var VIW097A "Messeguera (W)"
cap label var VIW098 "Misket cherven (W)"
cap label var VIW099 "Monemvassia (W)"
cap label var VIW100 "Moscato giallo (W)"
cap label var VIW101 "Muller Thurgau Weiss (W)"
cap label var VIW101A "Muller - Thurgau (W)"
cap label var VIW101B "Riesling x Sylvaner (W)"
cap label var VIW101C "Rivaner (W)"
cap label var VIW101D "Rizlingszilvani (W)"
cap label var VIW102 "Muscadelle (W)"
cap label var VIW103 "Muscat a petits grains blancs (W)"
cap label var VIW103A "Moscatel de grano menudo (W)"
cap label var VIW103B "Moscatel Galego Branco (W)"
cap label var VIW103C "Moscato (W)"
cap label var VIW103D "Moschato aspro (W)"
cap label var VIW103E "Muscat a petits grains (W)"
cap label var VIW103F "Muskateller (W)"
cap label var VIW103G "Sarga muskotaly (W)"
cap label var VIW103H "Tamaioasa romaneasca (W)"
cap label var VIW104 "Muscat of Alexandria (W)"
cap label var VIW104A "Moscatel de Alejandria (W)"
cap label var VIW104B "Moscatel de Malaga (W)"
cap label var VIW104C "Moscatel graudo (W)"
cap label var VIW104D "Moscatel-de-Setubal (W)"
cap label var VIW104E "Muscat Alexandrie (W)"
cap label var VIW104F "Zibibbo (W)"
cap label var VIW105 "Muscat Ottonel (W)"
cap label var VIW105A "Otthonel muskotaly (W)"
cap label var VIW106 "Mustoasa de Maderat (W)"
cap label var VIW107 "Neuburger (W)"
cap label var VIW108 "Nuragus (W)"
cap label var VIW109 "Ondarrabi Zuri (W)"
cap label var VIW110 "Ortega (W)"
cap label var VIW111 "Ortrugo (W)"
cap label var VIW112 "Palomino fino (W)"
cap label var VIW112A "Listan blanca (W)"
cap label var VIW112B "Malvasia rei (W)"
cap label var VIW113 "Palomino superior (W)"
cap label var VIW114 "Pardillo (W)"
cap label var VIW114A "Marisancho (W)"
cap label var VIW114B "Verdoncho (W)"
cap label var VIW115 "Pardina (W)"
cap label var VIW116 "Parellada (W)"
cap label var VIW117 "Passerina (W)"
cap label var VIW118 "Pecorino (W)"
cap label var VIW119 "Pedro Ximenes (W)"
cap label var VIW119A "Pedro Ximenez (W)"
cap label var VIW120 "Perruno (W)"
cap label var VIW121 "Pignoletto (W)"
cap label var VIW122 "Pinot blanc (W)"
cap label var VIW122A "Beli pinot (W)"
cap label var VIW122B "Burgunder, Weisser (W)"
cap label var VIW122C "Klevner (W)"
cap label var VIW122D "Pinot (W)"
cap label var VIW122E "Rulandske biele (W)"
cap label var VIW122F "Rulandske bile (W)"
cap label var VIW122G "Weissburgunder (W)"
cap label var VIW123 "Piquepoul blanc (W)"
cap label var VIW124 "Planta nova (W)"
cap label var VIW125 "Rabigato (W)"
cap label var VIW126 "Rabo de Ovelha (W)"
cap label var VIW127 "Ribolla gialla (W)"
cap label var VIW127A "Rebula (W)"
cap label var VIW128 "Riesling Weiss (W)"
cap label var VIW128A "Rajnai rizling (W)"
cap label var VIW128B "Rajnski rizling (W)"
cap label var VIW128C "Renski rizling (W)"
cap label var VIW128D "Rheinriesling (W)"
cap label var VIW128E "Riesling (W)"
cap label var VIW128F "Riesling, Weisser (W)"
cap label var VIW128G "Risling rynsky (W)"
cap label var VIW128H "Ryzlink rynsky (W)"
cap label var VIW129 "Rkatsiteli (W)"
cap label var VIW130 "Robola (W)"
cap label var VIW130A "Rompola (W)"
cap label var VIW131 "Roussanne (W)"
cap label var VIW132 "Sarba (W)"
cap label var VIW133 "Sauvignon blanc (W)"
cap label var VIW133A "Muskat-Sylvaner (W)"
cap label var VIW133B "Sauvignon (W)"
cap label var VIW134 "Savagnin blanc (W)"
cap label var VIW135 "Savvatiano (W)"
cap label var VIW136 "Scheurebe (W)"
cap label var VIW137 "Seara Nova (W)"
cap label var VIW138 "Semillon (W)"
cap label var VIW139 "Silvaner grun (W)"
cap label var VIW139A "Silvaner, Gruner (W)"
cap label var VIW139B "Sylvaner (W)"
cap label var VIW140 "Siria (W)"
cap label var VIW140A "Codega (W)"
cap label var VIW140B "Dona Blanca (W)"
cap label var VIW140C "Roupeiro (W)"
cap label var VIW141 "Sultanina (W)"
cap label var VIW141A "Soultanina (W)"
cap label var VIW142 "Terret blanc (W)"
cap label var VIW143 "Torrontes (W)"
cap label var VIW144 "Tortosina (W)"
cap label var VIW145 "Trajadura (W)"
cap label var VIW145A "Treixadura (W)"
cap label var VIW146 "Trebbiano abruzzese (W)"
cap label var VIW147 "Trebbiano giallo (W)"
cap label var VIW148 "Trebbiano romagnolo (W)"
cap label var VIW149 "Trebbiano toscano (W)"
cap label var VIW149A "Ugni blanc (W)"
cap label var VIW150 "Veltliner Fruhrot (W)"
cap label var VIW150A "Fruhroter Veltliner (W)"
cap label var VIW150B "Malvasier (W)"
cap label var VIW151 "Veltliner Grun (W)"
cap label var VIW151A "Veltliner (W)"
cap label var VIW151B "Veltliner, Gruner"
cap label var VIW151C "Veltlinske zelene (W)"
cap label var VIW151D "Weissgipfler (W)"
cap label var VIW151E "Zold veltelini (W)"
cap label var VIW152 "Verdeca (W)"
cap label var VIW153 "Verdejo blanco (W)"
cap label var VIW154 "Verdicchio bianco (W)"
cap label var VIW154A "Trebbiano di soave (W)"
cap label var VIW155 "Verduzzo friulano (W)"
cap label var VIW156 "Verduzzo trevigiano (W)"
cap label var VIW157 "Vermentino (W)"
cap label var VIW158 "Vernaccia di San Gimignano (W)"
cap label var VIW159 "Vilana (W)"
cap label var VIW160 "Viognier (W)"
cap label var VIW160A "Viogner (W)"
cap label var VIW161 "Viosinho (W)"
cap label var VIW162 "Vital (W)"
cap label var VIW163 "Viura (W)"
cap label var VIW163A "Macabeo (W)"
cap label var VIW163B "Macabeu (W)"
cap label var VIW164 "Welschriesling (W)"
cap label var VIW164A "Grasevina (W)"
cap label var VIW164B "Laski rizling (W)"
cap label var VIW164C "Olasz rizling (W)"
cap label var VIW164D "Riesling italico (W)"
cap label var VIW164E "Risling vlassky (W)"
cap label var VIW164F "Rizling vlassky (W)"
cap label var VIW164G "Ryzlink vlassky (W)"
cap label var VIW165 "Xarello (W)"
cap label var VIW165A "Xarello blanco (W)"
cap label var VIW166 "Xynisteri (W)"
cap label var VIW166A "Xinisteri (W)"
cap label var VIW167 "Zala gyoengye (W)"
cap label var VIW167A "Zalagyongye (W)"
cap label var VIW168 "Zalema (W)"
cap label var VIW169 "Zenit (W)"
cap label var VIW170 "Aletta (W)"
cap label var VIW171 "Asproudes (W)"
cap label var VIW172 "Glera (W)"
cap label var VIW173 "Malagousia (W)"
cap label var VIW174 "Manzoni bianco (W)"
cap label var VIW175 "Razaki (W)"
cap label var VIW176 "Skiadopoulo (W)"
cap label var VIW177 "Tempranillo blanco (W)"
cap label var VIW178 "Pálava (W)"
cap label var VIWM_OTH "Other main white grape varieties(W)"
cap label var VIWMM_OTH "Other main white mixed grape varieties (W)"
cap label var VIOM_TOT "Total main other different colour grape varieties (O)"
cap label var VIO001 "Babeasca gris (O)"
cap label var VIO002 "Garnacha roja (O)"
cap label var VIO002A "Grenache gris (O)"
cap label var VIO002B "Grenas rose (O)"
cap label var VIO003 "Gewurztraminer (O)"
cap label var VIO003A "Tramin cerveny (O)"
cap label var VIO003B "Traminer aromatico (O)"
cap label var VIO003C "Traminer roz (O)"
cap label var VIO003D "Tramini (O)"
cap label var VIO004 "Moschofilero (O)"
cap label var VIO005 "Muscat a petits grains rouges (O)"
cap label var VIO005A "Busuioaca de Bohotin (O)"
cap label var VIO006 "Pinot gris (O)"
cap label var VIO006A "Burgunder, Grauer (O)"
cap label var VIO006B "Pinot grigio (O)"
cap label var VIO006C "Rulander (O)"
cap label var VIO006D "Rulandske sede (O)"
cap label var VIO006E "Sivi pinot (O)"
cap label var VIO006F "Szurkebarat (O)"
cap label var VIO007 "Roditis (O)"
cap label var VIO008 "Sauvignon gris (O)"
cap label var VIO009 "Fileri (O)"
cap label var VIO010 "Generosa (O)"
cap label var VIO011 "Grolleau gris (O)"
cap label var VIOM_OTH "Other main different colour grape varieties (O)"
cap label var VIOMM_OTH "Other mixed main grape varieties of other colours (O)"
cap label var VIUNKM_TOT "Total main grape varieties without specified colour"
