cap label var TOTAL "Total"
cap label var SGL "Single inventors/applicants"
cap label var NAT "Co-patenting involving inventors/applicants from the reporting country"
cap label var NAT_EU "Co-patenting involving inventors/applicants from the reporting country and one or more EU Member States"
cap label var NAT_EU_NEU "Co-patenting involving inventors/applicants from the reporting country, one or more EU Member States and one or more non-EU countries"
cap label var NAT_NEU "Co-patenting involving inventors/applicants from the reporting country and one or more non-EU countries"
cap label var EUI_NEUA "Share of co-patenting involving EU inventors and non-EU applicants in the total of EU's domestic inventions"
cap label var NEUI_EUA "Share of co-patenting involving non-EU inventors and EU applicants in the total of EU's domestic applications"
cap label var EU_NEU "Co-patenting between EU Member States and non-EU countries"
cap label var EU_EU "Co-patenting between EU Member States"
cap label var EUA_NEUA "Share of co-patenting involving EU and non-EU applicants in the total of all international patents"
cap label var EUI_NEUI "Share of co-patenting involving EU and non-EU inventors in the total of all international patents"
