cap label var TOTAL "Total"
cap label var BP1 "Head, not further specified     "
cap label var BP11 "Head (caput), brain and cranial nerves and vessels"
cap label var BP12 "Facial area"
cap label var BP13 "Eye(s)"
cap label var BP14 "Ear(s)"
cap label var BP15 "Teeth"
cap label var BP18 "Head, multiple sites affected"
cap label var BP19 "Head, other parts not mentioned above"
cap label var BP2 "Neck, inclusive spine and vertebra in the neck       "
cap label var BP21 "Neck, inclusive spine and vertebra in the neck"
cap label var BP29 "Neck, other parts not mentioned above"
cap label var BP3 "Back, including spine and vertebra in the back       "
cap label var BP31 "Back, including spine and vertebra in the back"
cap label var BP39 "Back, other parts not mentioned above"
cap label var BP4 "Torso and organs, not further specified"
cap label var BP41 "Rib cage, ribs including joints and shoulder blades"
cap label var BP42 "Chest area including organs"
cap label var BP43 "Pelvic and abdominal area including organs"
cap label var BP48 "Torso, multiple sites affected"
cap label var BP49 "Torso, other parts not mentioned above"
cap label var BP5 "Upper extremities, not further specified"
cap label var BP51 "Shoulder and shoulder joints"
cap label var BP52 "Arm, including elbow"
cap label var BP53 "Hand"
cap label var BP54 "Finger(s)"
cap label var BP55 "Wrist"
cap label var BP58 "Upper extremities, multiple sites affected"
cap label var BP59 "Upper extremities, other parts not mentioned above"
cap label var BP6 "Lower extremities, not further specified"
cap label var BP61 "Hip and hip joint"
cap label var BP62 "Leg, including knee"
cap label var BP63 "Ankle"
cap label var BP64 "Foot"
cap label var BP65 "Toe(s)"
cap label var BP68 "Lower extremities, multiple sites affected"
cap label var BP69 "Lower extremities, other parts not mentioned above"
cap label var BP7 "Whole body and multiple sites, not further specified "
cap label var BP71 "Whole body (systemic effects)"
cap label var BP78 "Multiple sites of the body affected"
cap label var OTH "Other parts of body injured, not mentioned above"
cap label var UNK "Part of body injured not specified"
