cap label var _1001 "Population: total"
cap label var _1002 "Population: male"
cap label var _1003 "Population: female"
cap label var _1011 "Population: people aged under 15 as a share of the total population (%)"
cap label var _1012 "Population: people aged between 15 and 64  as a share of the total population (%)"
cap label var _1013 "Population: people aged 65 or over as a share of the total population (%)"
cap label var _1014 "Population: people aged between 20 and 64 as a share of the total population (%)"
cap label var _1015 "Population: people aged between 20 and 64 (Thousand)"
cap label var _1021 "Crude birth rate (per 1000)"
cap label var _1022 "Crude death rate (per 1000)"
cap label var _1023 "Natural growth rate (per 1000)"
cap label var _1024 "Crude rate of net migration (per 1000)"
cap label var _1025 "Number of immigrants (Thousand)"
cap label var _1026 "Number of emigrants (Thousand)"
cap label var _1031 "Fertility rate"
cap label var _1041 "Life expectancy at birth: male (Years)"
cap label var _1042 "Life expectancy at birth: female (Years)"
cap label var _1043 "Life expectancy at less then 1 year: male (Years)"
cap label var _1044 "Life expectancy at less then 1 year: female (Years)"
cap label var _1051 "Infant mortality rate: number of deaths of children under one year of age relative to 1000 live births"
cap label var _1071 "Age dependency ratio, 1st variant (Population aged 0-14 and 65 and more to pop. aged 15-64)"
cap label var _1072 "Young-age dependency ratio 1st variant (population aged 0-14 to population 15-64 years)"
cap label var _1073 "Old dependency ratio 1st variant (population 65 and over to population 15 to 64 years)"
cap label var _1101 "Early school-leavers - total (%)"
cap label var _1102 "Early school-leavers - male (%)"
cap label var _1103 "Early school-leavers - female (%)"
cap label var _1111 "Proportion of the population aged 20-24 having completed at least upper secondary education (%)"
cap label var _1112 "Proportion of the population aged 20-24 having completed at least upper secondary education: male (%)"
cap label var _1113 "Proportion of the population aged 20-24 having completed at least upper secondary education: female (%)"
cap label var _1114 "Number of students/pupils in pre-primary education (ISCED level 0)"
cap label var _1115 "Number of students/pupils in primary education/first stage of basic education (ISCED level 1)"
cap label var _1116 "Number of students/pupils in lower secondary education/Second stage of basic education (ISCED level 2)"
cap label var _1117 "Number of students/pupils in (upper) secondary education (ISCED level 3)"
cap label var _1118 "Number of students/pupils in post-secondary non-tertiary education (ISCED level 4)"
cap label var _1119 "Number of students/pupils in first stage of tertiary education (not leading directly to an advanced research qualification) (ISCED level 5)"
cap label var _1120 "Number of students/pupils in second stage of tertiary education (leading to an advanced research qualification) (ISCED level 6)"
cap label var _1131 "Life-long learning: share of persons aged 25-64 having participated in education and training (at any time during a four week period prior to being surveyed) (%)"
cap label var _1141 "Tertiary graduates in science and technology per 1 000 of population aged 20-29 years - male"
cap label var _1142 "Tertiary graduates in science and technology per 1 000 of population aged 20-29 years - female"
cap label var _1151 "Spending on human resources (public expenditure on education) as a share of GDP (%)"
cap label var _1152 "Public expenditure on education as a percentage of total public expenditure (%)"
cap label var _1161 "Educational attainment: percentage of 30-34 years old having completed tertiary or equivalent education"
cap label var _1201 "Total household expenditure (National currency, million)"
cap label var _1202 "Food and non-alcoholic beverages: share of household expenditure (COICOP 01) (%)"
cap label var _1203 "Alcoholic beverages, tobacco: share of household expenditure (COICOP 02) (%)"
cap label var _1204 "Clothing and footwear: share of household expenditure (COICOP 03) (%)"
cap label var _1205 "Housing,  water, electricity, gas and other fuels: share of household expenditure (COICOP 04) (%)"
cap label var _1206 "Furnishings, household equipment and routine maintenance of the house: share of household expenditure (COICOP 05) (%)"
cap label var _1207 "Health: share of household expenditure (COICOP 06) (%)"
cap label var _1208 "Transport: share of household expenditure (COICOP 07) (%)"
cap label var _1209 "Communication: share of household expenditure (COICOP 08) (%)"
cap label var _1210 "Recreation and culture: share of household expenditure (COICOP 09) (%)"
cap label var _1211 "Education: share of household expenditure (COICOP 10) (%)"
cap label var _1212 "Restaurants and hotels: share of household expenditure (COICOP 11) (%)"
cap label var _1213 "Personal care: share of household expenditure (COICOP 12.1) (%)"
cap label var _1221 "Inequality of income distribution (income quintile share ratio)"
cap label var _1222 "Children aged 0-17 living in jobless households (%)"
cap label var _1223 "People aged 18-59 living in jobless households (%)"
cap label var _1231 "Average nominal monthly wages and salaries (National currency)"
cap label var _1232 "Index of real wages and salaries (2000=100)"
cap label var _1241 "Gender pay gap in unadjusted form (%)"
cap label var _1242 "Tax rate on low wage earners: Tax wedge on labour cost (%)"
cap label var _1243 "Tax rate on low wage earners: Unemployment trap (%)"
cap label var _1244 "Tax rate on low wage earners: Low wage trap - single person without children (%)"
cap label var _1245 "Tax rate on low wage earners: Low wage trap - one earner couple with two children (%)"
cap label var _1251 "Poverty level threshold (income per month) (National currency)"
cap label var _1252 "At-risk-of-poverty rate before social transfers: total (%)"
cap label var _1253 "At-risk-of-poverty rate before social transfers: males (%)"
cap label var _1254 "At-risk-of-poverty rate before social transfers: females (%)"
cap label var _1255 "At-persistent-risk-of-poverty rate: total (%)"
cap label var _1256 "At-persistent-risk-of-poverty rate: males (%)"
cap label var _1257 "At-persistent-risk-of-poverty rate: females (%)"
cap label var _1261 "Health expenditure, as a share of GDP (%)"
cap label var _1262 "Social protection expenditure excluding administrative costs (including health expenditure), as a share of GDP (%)"
cap label var _1301 "Economic activity rate (15 - 64) (%)"
cap label var _1302 "Economic activity rate (15 - 64) - males (%)"
cap label var _1303 "Economic activity rate (15 - 64) - females (%)"
cap label var _1304 "Employment rate (15 to 64 years), total (%)"
cap label var _1305 "Employment rate (15 to 64 years), males (%)"
cap label var _1306 "Employment rate (15 to 64 years), females (%)"
cap label var _1307 "Total employment rate of older workers (%)"
cap label var _1308 "Employment rate of older workers: males (%)"
cap label var _1309 "Employment rate of older workers: females (%)"
cap label var _1311 "Total unemployment rate (%)"
cap label var _1312 "Unemployment rate - males (%)"
cap label var _1313 "Unemployment rate - females (%)"
cap label var _1314 "Unemployment rate: less than 25 years (%)"
cap label var _1315 "Unemployment rate: less than 25 years - male (%)"
cap label var _1316 "Unemployment rate: less than 25 years - female (%)"
cap label var _1317 "Unemployment rate: 25 years and over (%)"
cap label var _1318 "Total long-term unemployment rate (%)"
cap label var _1319 "Long-term unemployment rate: males (%)"
cap label var _1320 "Long-term unemployment rate: females (%)"
cap label var _1321 "Employment rate (20 to 64 years), males (%)"
cap label var _1322 "Employment rate (20 to 64 years), females (%)"
cap label var _1323 "Economic activity rate (20 to 64 years), total (%)"
cap label var _1324 "Employment rate (20 to 64 years), total (%)"
cap label var _1325 "Economic activity rate (20 to 64 years), males (%)"
cap label var _1326 "Economic activity rate (20 to 64 years), females (%)"
cap label var _1327 "Employment (20 to 64 years)"
cap label var _1331 "Total employment: number of persons in employment (Thousand)"
cap label var _1332 "Total employment: agriculture, forestry and fishing (NACE Rev. 2 Section A) (Thousand)"
cap label var _1333 "Total employment: industry (NACE Rev. 2 Sections B to E) (Thousand)"
cap label var _1334 "Total employment: construction (NACE Rev. 2 Sections F) (Thousand)"
cap label var _1335 "Total employment: services (NACE Rev. 2 Sections G to T) (Thousand)"
cap label var _1340 "Total self-employment (15-64) and family workers (15-64): number of persons who are self-employed including self employed with employees (employers) and self-employed without employees (Thousand)"
cap label var _1341 "Total employees (15-64): number of persons who are employees (Thousand)"
cap label var _1342 "Population: people aged between 15 and 64 (in private households)"
cap label var _1343 "Population: people aged between 20 and 64 (in private households)"
cap label var _1362 "Total employment: agriculture, forestry and fishing (NACE Rev. 1.1 Sections A and B) (Thousand)"
cap label var _1363 "Total employment: industry (NACE Rev. 1.1 Sections C to E) (Thousand)"
cap label var _1364 "Total employment: construction (NACE Rev. 1.1 Sections F) (Thousand)"
cap label var _1365 "Total employment: services (NACE Rev. 1.1 Sections G to P) (Thousand)"
cap label var _1401 "Gross domestic product (current prices) (National currency, million)"
cap label var _1402 "Gross domestic product (current prices) (EUR million)"
cap label var _1403 "Real GDP growth rate (%)"
cap label var _1404 "Gross domestic product (constant prices) (National currency, million)"
cap label var _1405 "Gross domestic product per capita (current prices) (EUR)"
cap label var _1406 "Gross domestic product per capita (National currency)"
cap label var _1407 "Gross domestic product (constant prices) per capita (National currency)"
cap label var _1411 "Final consumption expenditure, as a share of GDP (%)"
cap label var _1412 "Final consumption  expenditure (constant prices) (National currency, million)"
cap label var _1413 "Final consumption expenditure: household and NPISH, as a share of GDP (%)"
cap label var _1414 "Final consumption expenditure: General government, as a share of GDP (%)"
cap label var _1415 "Gross capital formation, as a share of GDP (%)"
cap label var _1416 "Gross fixed capital formation, as a share of GDP (%)"
cap label var _1417 "Stock variation, as a share of GDP (%)"
cap label var _1418 "Imports of goods and services, relative to GDP (%)"
cap label var _1419 "Exports of goods and services, relative to GDP (%)"
cap label var _1420 "Average of exports and imports, relative to GDP (%)"
cap label var _1431 "GDP per capita at current prices (PPS)"
cap label var _1433 "GDP per capita in PPS (%, EU27_2007=100)"
cap label var _1441 "Agriculture (NACE Rev. 2 Section A): share of total gross value added (%)"
cap label var _1442 "Industry (excluding construction) (NACE Rev. 2 Sections B to E): share of total gross value added (%)"
cap label var _1443 "Construction (NACE Rev. 2 Section F): share of total gross value added (%)"
cap label var _1444 "Services (NACE Rev. 2 Sections G to T): share of total gross value added (%)"
cap label var _1445 "Distributive trades, hotels and restaurants, transport, information and communications (NACE Rev. 2 Sections G to J): share of total gross value added (%)"
cap label var _1446 "Financial intermediation, real estate, renting and business activities (NACE Rev. 2 Sections K to N): share of total gross value added (%)"
cap label var _1447 "Other services (NACE Rev. 2 Sections O to T): share of total gross value added (%)"
cap label var _1451 "Employment growth (%)"
cap label var _1452 "Labour productivity growth: growth in GDP (constant prices) per person employed, relative to the previous year (%)"
cap label var _1453 "Unit labour cost growth (%)"
cap label var _1461 "Agriculture, forestry and fishing (NACE Rev. 1.1 Sections A and B): share of total gross value added (%)"
cap label var _1462 "Industry (excluding construction) (NACE Rev. 1.1 Sections C to E): share of total gross value added (%)"
cap label var _1463 "Construction (NACE Rev. 1.1 Section F): share of total gross value added (%)"
cap label var _1464 "Services (NACE Rev. 1.1 Sections G to P): share of total gross value added (%)"
cap label var _1465 "Distributive trades, hotels and restaurants, transport and communication (NACE Rev. 1.1 Sections G to I): share of total gross value added (%)"
cap label var _1466 "Financial intermediation, real estate, renting and business activities (NACE Rev. 1.1 Sections J and K): share of total gross value added (%)"
cap label var _1468 "Other services (NACE Rev. 1.1 Sections L to P): share of total gross value added (%)"
cap label var _1501 "General government net borrowing (-)/net lending (+), relative to GDP (%)"
cap label var _1502 "General government net borrowing (-)/net lending (+) (EUR million)"
cap label var _1503 "General government consolidated gross debt, relative to GDP (%)"
cap label var _1504 "General government consolidated gross debt (EUR million)"
cap label var _1505 "Gross foreign debt of the whole economy/Public external debt, relative to GDP (%)"
cap label var _1506 "Gross foreign debt of the whole economy/Public external debt (EUR million)"
cap label var _1507 "Gross foreign debt of the whole economy, relative to total exports (%)"
cap label var _1511 "Balance of payments: current account (EUR million)"
cap label var _1512 "Balance of payments: capital account (EUR million)"
cap label var _1513 "Balance of payments: financial account (EUR million)"
cap label var _1514 "Balance of payments: net errors and omissions (EUR million)"
cap label var _1515 "Balance of payments: trade balance (EUR million)"
cap label var _1516 "Balance of payments: exports of goods (EUR million)"
cap label var _1517 "Balance of payments: imports of goods (EUR million)"
cap label var _1518 "Balance of payments: net services (EUR million)"
cap label var _1519 "Balance of payments: services credit (EUR million)"
cap label var _1520 "Balance of payments: services debit (EUR million)"
cap label var _1521 "Balance of payments: net income (EUR million)"
cap label var _1522 "Balance of payments: net current transfers (EUR million)"
cap label var _1523 "Balance of payments: net current transfers - of which government transfers (EUR million)"
cap label var _1524 "Balance of payments: direct investment (EUR million)"
cap label var _1525 "Balance of payments: portfolio investment (EUR million)"
cap label var _1526 "Balance of payments: other investment (EUR million)"
cap label var _1527 "Balance of payments: financial derivatives (EUR million)"
cap label var _1528 "Balance of payments: reserves assets (EUR million)"
cap label var _1531 "Abroad, total direct investment (EUR million)"
cap label var _1532 "In the reporting economy, total direct investment (EUR million)"
cap label var _1533 "Average of FDI inflows and outflows, relative to GDP (%)"
cap label var _1534 "Total net foreign direct investment with the EU27 Member States (2007-2013) (EUR million)"
cap label var _1535 "Foreign direct investment of the reporting economy in the EU countries (EUR million)"
cap label var _1536 "Foreign direct investment of the EU countries in the reporting economy (EUR million)"
cap label var _1541 "Money supply: M1 (EUR million)"
cap label var _1542 "Money supply: M2 (EUR million)"
cap label var _1543 "Money supply: M3 (EUR million)"
cap label var _1551 "Total credit by monetary financial institutions (MFIs) to total residents (consolidated) (EUR million)"
cap label var _1561 "Day-to-day rates, per annum (%)"
cap label var _1562 "Lending interest rate (one year), per annum (%)"
cap label var _1563 "Deposit interest rate (one year), per annum (%)"
cap label var _1564 "Central bank interest rates, per annum (%)"
cap label var _1565 "Long-term interest rates (government bond yields), per annum (%)"
cap label var _1571 "Foreign official reserves: total reserves including gold (EUR million)"
cap label var _1572 "Foreign official reserves: total reserves excluding gold (EUR million)"
cap label var _1581 "EUR exchange rates: average - 1 euro = ... national currency"
cap label var _1582 "EUR exchange rates: end of period - 1 euro = ... national currency"
cap label var _1583 "Effective exchange rate index (2005=100)"
cap label var _1591 "Inflation rate (%)"
cap label var _1592 "Annual average inflation rate (HICP), (total, % change on previous year)"
cap label var _1601 "Total area of the country (km²)"
cap label var _1602 "Utilised agricultural area (Thousand hectare)"
cap label var _1603 "Arable land (Thousand hectare)"
cap label var _1604 "Permanent grassland (Thousand hectare)"
cap label var _1605 "Land under permanent crops (Thousand hectare)"
cap label var _1606 "Wooded area (Thousand hectare)"
cap label var _1607 "Area of other land (Thousand hectare)"
cap label var _1611 "Agricultural production volume indices of goods and services (at producer prices) (previous year=100)"
cap label var _1621 "Livestock (December): cattle (Thousand heads)"
cap label var _1622 "Livestock (December): dairy cows (Thousand heads)"
cap label var _1623 "Livestock (December): pigs (Thousand heads)"
cap label var _1624 "Livestock (December): sheep and goats (Thousand heads)"
cap label var _1631 "Slaughterings - total production (Thousand tonnes)"
cap label var _1632 "Slaughterings - pigs (Thousand tonnes)"
cap label var _1633 "Slaughterings - cattle (Bovines) (Thousand tonnes)"
cap label var _1634 "Slaughterings - poultry (Thousand tonnes)"
cap label var _1635 "Slaughterings - sheep and goats (Thousand tonnes)"
cap label var _1641 "Production and utilisation of milk on the farm (products obtained; total whole milk) (Thousand tonnes)"
cap label var _1651 "Crop production (harvested production): cereals (including rice) (Thousand tonnes)"
cap label var _1652 "Crop production (harvested production): sugar beet (Thousand tonnes)"
cap label var _1653 "Crop production (harvested production): oilseeds (Thousand tonnes)"
cap label var _1654 "Crop production (harvested production): potatoes (Thousand tonnes)"
cap label var _1656 "Crop production (harvested production): fruit (Thousand tonnes)"
cap label var _1657 "Crop production (harvested production): vegetables (Thousand tonnes)"
cap label var _1661 "Total annual fish catch (Thousand tonnes)"
cap label var _1671 "Forestry: industrial round wood removals (under bark) (Thousand m³)"
cap label var _1681 "Total Fishery Production (Catch + Aquaculture)  (Tonnes)"
cap label var _1682 "Catches (total fishery products) - Total all fishing areas (Tonnes)"
cap label var _1701 "All energy products: primary production (Thousand TOE)"
cap label var _1702 "Crude oil: primary production (Thousand TOE)"
cap label var _1703 "Hard coal and lignite: primary production (Thousand TOE)"
cap label var _1704 "Natural gas: primary production (Thousand TOE)"
cap label var _1705 "All energy products: net imports (Thousand TOE)"
cap label var _1706 "All energy products: gross inland energy consumption (Thousand TOE)"
cap label var _1711 "Final energy consumption: industry as a share of total (%)"
cap label var _1712 "Final energy consumption: transport as a share of total (%)"
cap label var _1713 "Final energy consumption: households and services as a share of total (%)"
cap label var _1714 "Final energy consumption: households as a share of total (%)"
cap label var _1721 "Energy intensity of the economy (kg of oil equivalent per EUR 1000 GDP)"
cap label var _1731 "Electricity generation (Thousand GWh)"
cap label var _1741 "Share of electricity from renewables in gross electricity consumption (%)"
cap label var _1751 "Electricity prices - industrial users (EUR/kWh)"
cap label var _1752 "Electricity prices - households (EUR/kWh)"
cap label var _1753 "Gas prices - industrial users (EUR/Gigajoule)"
cap label var _1754 "Gas prices - households (EUR/Gigajoule)"
cap label var _1801 "Business demography: Birth rate of enterprises (%)"
cap label var _1802 "Business demography: Survival rate of enterprises (%)"
cap label var _1803 "Business demography: Death rate of enterprises (%)"
cap label var _1811 "Industrial production index (2005=100)"
cap label var _1812 "Industrial producer price index (2005=100)"
cap label var _1813 "Volume index of construction output (2005=100)"
cap label var _1814 "Construction cost index (2005=100)"
cap label var _1815 "Retail trade volume of sales index (NACE Division 47) (2005=100)"
cap label var _1816 "Retail trade turnover index (NACE Division 52) (2005=100)"
cap label var _1817 "Motor trade turnover index (NACE Division 50) (2005=100)"
cap label var _1818 "Wholesale trade turnover index (NACE Division 51) (2005=100)"
cap label var _1819 "Hotels and restaurants turnover index (NACE Division 55) (2005=100)"
cap label var _1820 "Transport and communications turnover index (NACE Divisions 60 to 64) (2005=100)"
cap label var _1821 "Communications turnover index (NACE Division 64) (2005=100)"
cap label var _1822 "Computer services turnover index (NACE Division 72) (2005=100)"
cap label var _1823 "Business services turnover index (NACE Division 74) (2005=100)"
cap label var _1831 "Number of bed places in hotels and similar establishments (Thousand)"
cap label var _1832 "Arrivals of non-residents staying in hotels and similar establishments (Thousand)"
cap label var _1833 "Number of tourists: all holidays and business -outbound (1 plus nights) (Thousand)"
cap label var _1850 "Industrial production index (NACE Rev. 2) (2010 = 100)"
cap label var _1865 "Industrial production index (NACE Rev. 2) (2015 = 100)"
cap label var _1851 "Industrial producer price index (NACE Rev. 2) (2010 = 100)"
cap label var _1869 "Industrial producer price index (NACE Rev. 2) (2015 = 100)"
cap label var _1852 "Volume index of construction output (NACE Rev. 2) (2010 = 100)"
cap label var _1874 "Volume index of construction output (NACE Rev. 2) (2015 = 100)"
cap label var _1853 "Construction cost index (NACE Rev. 2) (2010 = 100)"
cap label var _1875 "Construction cost index (NACE Rev. 2) (2015 = 100)"
cap label var _1854 "Retail trade volume of sales index (NACE Rev. 2 Division 47) (2010 = 100)"
cap label var _1840 "Retail trade volume of sales index (NACE Rev. 2 Division 47) (2015 = 100)"
cap label var _1855 "Retail trade turnover index (NACE Rev. 2 Division 47) (2010 = 100)"
cap label var _1843 "Retail trade turnover index (NACE Rev. 2 Division 47) (2015 = 100)"
cap label var _1856 "Motor trade turnover index (NACE Rev. 2 Division 45) (2010 = 100)"
cap label var _1841 "Motor trade turnover index (NACE Rev. 2 Division 45) (2015 = 100)"
cap label var _1857 "Wholesale trade turnover index (NACE Rev. 2 Division 46) (2010 = 100)"
cap label var _1842 "Wholesale trade turnover index (NACE Rev. 2 Division 46) (2015 = 100)"
cap label var _1858 "Accommodation and food services turnover index (NACE Rev. 2 Section I) (2010 = 100)"
cap label var _1845 "Accommodation and food services turnover index (NACE Rev. 2 Section I) (2015 = 100)"
cap label var _1859 "Transport and storage turnover index (NACE Rev. 2 Section H) (2010 = 100)"
cap label var _1844 "Transport and storage turnover index (NACE Rev. 2 Section H) (2015 = 100)"
cap label var _1860 "Information and communication turnover index (NACE Rev. 2 Section J) (2010 = 100)"
cap label var _1846 "Information and communication turnover index (NACE Rev. 2 Section J) (2015 = 100)"
cap label var _1863 "Professional, scientific and technical activities turnover index (NACE Rev. 2 Section M excluding Group 70.1 and Division 75) (2010 = 100)"
cap label var _1847 "Professional, scientific and technical activities turnover index (NACE Rev. 2 Section M excluding Group 70.1 and Division 75) (2015 = 100)"
cap label var _1864 "Administrative and support service activities turnover index (NACE Rev. 2 Section N excluding Division 77 and Groups 81.1 and 81.3) (2010 = 100)"
cap label var _1848 "Administrative and support service activities turnover index (NACE Rev. 2 Section N excluding Division 77 and Groups 81.1 and 81.3) (2015 = 100)"
cap label var _1871 "Industrial production index, mining and quarrying (NACE Rev. 2 Section B) (2010 = 100)"
cap label var _1866 "Industrial production index, mining and quarrying (NACE Rev. 2 Section B) (2015 = 100)"
cap label var _1872 "Industrial production index, manufacturing (NACE Rev. 2 Section C) (2010 = 100)"
cap label var _1867 "Industrial production index, manufacturing (NACE Rev. 2 Section C) (2015 = 100)"
cap label var _1873 "Industrial production index, electricity, gas, steam and air conditioning supply (NACE Rev. 2 Section D) (2010 = 100)"
cap label var _1868 "Industrial production index, electricity, gas, steam and air conditioning supply (NACE Rev. 2 Section D) (2015 = 100)"
cap label var _1880 "Industrial production index (NACE Rev. 1.1) (2010 = 100)"
cap label var _1881 "Industrial producer price index (NACE Rev. 1.1) (2010 = 100)"
cap label var _1882 "Volume index of construction output (NACE Rev. 1.1) (2010 = 100)"
cap label var _1883 "Construction cost index (NACE Rev. 1.1) (2010 = 100)"
cap label var _1884 "Retail trade volume of sales index (NACE Rev. 1.1 Division 52) (2010 = 100)"
cap label var _1885 "Retail trade turnover index (NACE Rev. 1.1 Division 52) (2010 = 100)"
cap label var _1886 "Motor trade turnover index (NACE Rev. 1.1 Division 50) (2010 = 100)"
cap label var _1887 "Wholesale trade turnover index (NACE Rev. 1.1 Division 51) (2010 = 100)"
cap label var _1888 "Hotels and restaurants turnover index (NACE Rev. 1.1 Division 55) (2010 = 100)"
cap label var _1891 "Industrial production index, mining and quarrying (NACE Rev. 1.1 Section C) (2010 = 100)"
cap label var _1892 "Industrial production index, manufacturing (NACE Rev. 1.1 Section D) (2010 = 100),"
cap label var _1893 "Industrial production index, electricity and gas supply (NACE Rev. 1.1 Groups 40.1 and 40.2) (2010 = 100)"
cap label var _1901 "Length of motorways (km)"
cap label var _1902 "Length of other roads (km)"
cap label var _1903 "Railway transport: length of lines (km)"
cap label var _1904 "Number of passenger cars (Thousand)"
cap label var _1911 "Total inland freight transport Tonne-km/GDP (constant prices) (2000=100)"
cap label var _1912 "Railway transport: goods transported (Million tonne-km)"
cap label var _1913 "Freight transport: road (Million tonne-km)"
cap label var _1914 "Freight transport: inland waterway (Million tonne-km)"
cap label var _1915 "Freight transport: sea - total inward and outward (Million tonnes)"
cap label var _1917 "Freight transport: pipeline (Million tonne-km)"
cap label var _1918 "Road share of inland freight transport (%)"
cap label var _1921 "Total inland passenger transport, passenger-km/GDP (constant prices) (2000=100)"
cap label var _1922 "Car share of inland passenger transport (%)"
cap label var _1924 "Railway transport: total passenger transport (Passenger-km)"
cap label var _1925 "Road transport: total passenger transport  (Passenger-km)"
cap label var _2001 "Main telephone lines (Thousand)"
cap label var _2002 "Number of mobile phone subscriptions (Thousand)"
cap label var _2011 "Percentage of households who have Internet access at home. All forms of Internet use are included. The population considered is aged 16 to 74. (%)"
cap label var _2012 "E-government usage by individuals by gender - all Individuals. Percentage of individuals aged 16 to 74 using the Internet for interaction with public authorities: total (at the last three months) (%)"
cap label var _2013 "E-government usage by individuals by gender - all Individuals. Percentage of individuals aged 16 to 74 using the Internet for interaction with public authorities: male (at the last three months) (%)"
cap label var _2014 "E-government usage by individuals by gender - all Individuals. Percentage of individuals aged 16 to 74 using the Internet for interaction with public authorities: female (at the last three months) (%)"
cap label var _2015 "Proportion of individuals aged 16 to 74 who access the Internet, on average, at least once a week  (nut not every day)  (%)"
cap label var _2016 "Percentage of enterprises having access to the Internet (%)"
cap label var _2017 "E-government usage by enterprises - Percentage of enterprises which use the Internet for interaction with public authorities. All without financial sector (10 person employed or more) (%)"
cap label var _2018 "E-Commerce - Percentage of enterprises' total turnover from E-commerce (%)"
cap label var _2021 "Proportion of individuals aged 16 to 74 who access the Internet, on average, at least once a week  (including every day)  (%)"
cap label var _2022 "Proportion of individuals aged 16 to 74 who access the Internet, on average, at least once a month   (%)"
cap label var _2023 "Proportion of individuals aged 16 to 74 who access the Internet, on average, less than once a month   (%)"
cap label var _2101 "Value of imports (EUR million)"
cap label var _2102 "Value of exports (EUR million)"
cap label var _2103 "Trade balance (EUR million)"
cap label var _2110 "Value of imports: SITC 0 (EUR million)"
cap label var _2111 "Value of imports: SITC 1 (EUR million)"
cap label var _2112 "Value of imports: SITC 2 (EUR million)"
cap label var _2113 "Value of imports: SITC 3 (EUR million)"
cap label var _2114 "Value of imports: SITC 4 (EUR million)"
cap label var _2115 "Value of imports: SITC 5 (EUR million)"
cap label var _2116 "Value of imports: SITC 6 (EUR million)"
cap label var _2117 "Value of imports: SITC 7 (EUR million)"
cap label var _2118 "Value of imports: SITC 8 (EUR million)"
cap label var _2119 "Value of imports: SITC 9 (EUR million)"
cap label var _2120 "Value of exports: SITC 0 (EUR million)"
cap label var _2121 "Value of exports: SITC 1 (EUR million)"
cap label var _2122 "Value of exports: SITC 2 (EUR million)"
cap label var _2123 "Value of exports: SITC 3 (EUR million)"
cap label var _2124 "Value of exports: SITC 4 (EUR million)"
cap label var _2125 "Value of exports: SITC 5 (EUR million)"
cap label var _2126 "Value of exports: SITC 6 (EUR million)"
cap label var _2127 "Value of exports: SITC 7 (EUR million)"
cap label var _2128 "Value of exports: SITC 8 (EUR million)"
cap label var _2129 "Value of exports: SITC 9 (EUR million)"
cap label var _2140 "Share of imports from EU28 countries (2013-2020) (%)"
cap label var _2141 "Share of imports from EU27 countries (2007-2013) (%)"
cap label var _2142 "Share of imports from largest partner (%)"
cap label var _2143 "Share of imports from second largest partner (%)"
cap label var _2144 "Share of imports from third largest partner (%)"
cap label var _2145 "Share of imports from fourth largest partner (%)"
cap label var _2146 "Share of imports from fifth largest partner (%)"
cap label var _2147 "Share of imports from sixth largest partner (%)"
cap label var _2148 "Share of imports from seventh largest partner (%)"
cap label var _2149 "Share of imports from eighth largest partner (%)"
cap label var _2150 "Share of imports from ninth largest partner (%)"
cap label var _2151 "Share of imports from tenth largest partner (%)"
cap label var _2160 "Share of exports to EU28 countries (2013-2020) (%)"
cap label var _2161 "Share of exports to EU27 countries (2007-2013) (%)"
cap label var _2162 "Share of exports to largest partner (%)"
cap label var _2163 "Share of exports to second largest partner (%)"
cap label var _2164 "Share of exports to third largest partner (%)"
cap label var _2165 "Share of exports to fourth largest partner (%)"
cap label var _2166 "Share of exports to fifth largest partner (%)"
cap label var _2167 "Share of exports to sixth largest partner (%)"
cap label var _2168 "Share of exports to seventh largest partner (%)"
cap label var _2169 "Share of exports to eighth largest partner (%)"
cap label var _2170 "Share of exports to ninth largest partner (%)"
cap label var _2171 "Share of exports to tenth largest partner (%)"
cap label var _2180 "Value of trade balance with EU28 countries (2013-2020) (EUR million)"
cap label var _2181 "Value of trade balance with EU27 countries (2007-2013) (EUR million)"
cap label var _2182 "Value of trade balance with New Independent States (EUR million)"
cap label var _2183 "Value of trade balance with the United States of America (EUR million)"
cap label var _2184 "Value of trade balance with China (EUR million)"
cap label var _2185 "Value of trade balance with Japan (EUR million)"
cap label var _2191 "Terms of trade"
cap label var _2201 "Gross domestic expenditure on research & development, relative to GDP (%)"
cap label var _2202 "Gross domestic expenditure on research & development (EUR million)"
cap label var _2203 "Gross domestic expenditure on R&D (GERD) by source of funds - industry (%)"
cap label var _2204 "Gross domestic expenditure on R&D (GERD) by source of funds - government (%)"
cap label var _2205 "Gross domestic expenditure on R&D (GERD) by source of funds - abroad (%)"
cap label var _2221 "Research & development personnel, full time equivalent units (FTE)"
cap label var _2301 "Total greenhouse gas emissions (CO2 equivalent (1990=100))"
cap label var _2311 "Municipal waste collected (kg/person/year)"
cap label var _2312 "Municipal waste land filled (kg/person/year)"
cap label var _2313 "Municipal waste incinerated (kg)"
cap label var _2401 "Consumer price index of basic non-food products, (2005=100)"
cap label var _2402 "Consumer price index of basic food products, (2005=100)"
cap label var _2403 "Consumer price index of goods, (2005=100)"
cap label var _2404 "Consumer price index of services, (2005=100)"
cap label var _2405 "CPI item weights: Food (%)"
cap label var _2406 "CPI item weights: non-food products (%)"
cap label var _2407 "CPI item weights: goods (%)"
cap label var _2408 "CPI item weights: services (%)"
cap label var _2409 "Consumer price index: Total  (2005=100)"
cap label var _2500 "Value of imports from EU28 countries (2013-2020) (EUR million)"
cap label var _2501 "Value of imports from EU27 countries (2007-2013) (EUR million)"
cap label var _2502 "Value of imports from New Independent States (EUR million)"
cap label var _2503 "Value of imports from the United States of America (EUR million)"
cap label var _2504 "Value of imports from China (EUR million)"
cap label var _2505 "Value of imports from Japan (EUR million)"
cap label var _2510 "Value of exports to EU28 countries (2013-2020) (EUR million)"
cap label var _2511 "Value of exports to EU27 countries (2007-2013) (EUR million)"
cap label var _2512 "Value of exports to New Independent States (EUR million)"
cap label var _2513 "Value of exports to the United States of America (EUR million)"
cap label var _2514 "Value of exports to China (EUR million)"
cap label var _2515 "Value of exports to Japan (EUR million)"
