cap label var TOTAL "Total"
cap label var CH_RELIC "For own or partner's children and incapacitated relatives"
cap label var CH_IN_RELIC "For own or partner's children in the household and incapacitated relatives"
cap label var CH_OUT_RELIC "For own or partner's children outside the household and incapacitated relatives"
cap label var CH_INOUT_RELIC "For own or partner's children in- and outside the household and incapacitated relatives"
cap label var CH "For own or partner's children"
cap label var CH_IN "For own or partner's children in household"
cap label var CH_OUT "For own or partner's children outside the household"
cap label var CH_INOUT "For own or partner's children in- and outside the household"
cap label var RELIC "For incapacitated relatives"
cap label var NONE "No care responsibility"
cap label var NAP "Not applicable"
cap label var NRP "No response"
