cap label var TOTAL "Total waste"
cap label var PRIM "Primary waste (TOTAL minus SEC)"
cap label var SEC "Secondary waste (W033+W103+W128_13)"
cap label var W01_05 "Chemical and medical wastes (subtotal)"
cap label var W011 "Spent solvents"
cap label var W012 "Acid, alkaline or saline wastes"
cap label var W013 "Used oils"
cap label var W014 "Spent chemical catalysts"
cap label var W02A "Chemical wastes"
cap label var W032 "Industrial effluent sludges"
cap label var W033 "Sludges and liquid wastes from waste treatment"
cap label var W05 "Health care and biological wastes"
cap label var W06_07A "Recyclable wastes (subtotal, W06+W07 except W077)"
cap label var W061 "Metal wastes, ferrous"
cap label var W062 "Metal wastes, non-ferrous"
cap label var W063_122_MUN "Metal wastes - municipal"
cap label var W063_122_MUN_INC "Metal wastes - metals separated after incineration of municipal waste"
cap label var W063 "Metal wastes, mixed ferrous and non-ferrous"
cap label var W071 "Glass wastes"
cap label var W071_MUN "Glass wastes - municipal"
cap label var W072 "Paper and cardboard wastes"
cap label var W072_MUN "Paper and cardboard wastes - municipal"
cap label var W073 "Rubber wastes"
cap label var W074 "Plastic wastes"
cap label var W074_MUN "Plastic wastes - municipal"
cap label var W075 "Wood wastes"
cap label var W075_MUN "Wood wastes - municipal"
cap label var W076 "Textile wastes"
cap label var W076_MUN "Textile wastes - municipal"
cap label var W077_08 "Equipment (subtotal, W077+W08A+W081+W0841)"
cap label var W077 "Waste containing PCB"
cap label var W08A "Discarded equipment (except discarded vehicles and batteries and accumulators waste) (W08 except W081, W0841)"
cap label var W081 "Discarded vehicles"
cap label var W082_84_MUN "Electrical and electronic equipment  - municipal"
cap label var W0841 "Batteries and accumulators wastes"
cap label var W0841_MUN "Batteries and accumulators wastes - municipal"
cap label var W09 "Animal and vegetal wastes (subtotal, W091+W092+W093)"
cap label var W091_092_MUN "Bio-waste - municipal"
cap label var W091_092_MUN_S "Bio-waste separated and recycled at source - municipal"
cap label var W091_092_101_FD "Food waste - bio, household and similar waste"
cap label var W091 "Animal and mixed food waste"
cap label var W092 "Vegetal wastes"
cap label var W093 "Animal faeces, urine and manure"
cap label var W10 "Mixed ordinary wastes (subtotal, W101+W102+W103)"
cap label var W101 "Household and similar wastes"
cap label var W1011_MUN "Bulky waste"
cap label var W1011_1021_MUN "Mixed wastes - municipal"
cap label var W102 "Mixed and undifferentiated materials"
cap label var W103 "Sorting residues"
cap label var W11 "Common sludges"
cap label var W12_13 "Mineral and solidified wastes (subtotal)"
cap label var W121 "Mineral waste from construction and demolition"
cap label var W12B "Other mineral wastes (W122+W123+W125)"
cap label var W124 "Combustion wastes"
cap label var W126 "Soils"
cap label var W127 "Dredging spoils"
cap label var W128_13 "Mineral wastes from waste treatment and stabilised wastes"
cap label var W06 "Metallic wastes (W061+W062+W063)"
cap label var W091_092 "Animal and mixed food waste; vegetal wastes (W091+W092)"
cap label var W11_127 "Common sludges and dredging spoils (W11+W127, valid up to 2008)"
cap label var W12_X_127NH "Mineral waste (except non-hazardous dredging spoils, valid up to 2008)"
cap label var W12A "Mineral wastes (except combustion wastes, contaminated soils and polluted dredging spoils) (W121+122+W123+W125+W126, valid up to 2008)"
cap label var W126_127 "Soils and dredging spoils (W126+W127, valid up to 2008)"
cap label var W13 "Solidified, stabilised or vitrified wastes (valid up to 2008)"
cap label var RCV_OTH "Other recovered wastes (valid up to 2008)"
cap label var DSP_OTH "Other disposed wastes (valid up to 2008)"
cap label var INC_OTH "Other incinerated wastes (valid up to 2008)"
cap label var TOT_X_MIN "Waste excluding major mineral wastes"
cap label var W1501 "Packaging"
cap label var W150101 "Paper and cardboard packaging"
cap label var W150102 "Plastic packaging"
cap label var W150102CB_LT50 "Lightweight plastic carrier bags having a wall thickness of less than 50 micron"
cap label var W150102CB_LT15 "Lightweight plastic carrier bags having a wall thickness of less than 15 micron"
cap label var W150102CB_15_49 "Lightweight plastic carrier bags having a wall thickness from 15 to 49 micron"
cap label var W150102CB_GE50 "Plastic carrier bags having a wall thickness of 50 microns or over"
cap label var W150103 "Wooden packaging"
cap label var W150104 "Metallic packaging"
cap label var W15010401 "Aluminium packaging"
cap label var W15010401_IBA "Aluminium from incineration bottom ash (IBA)"
cap label var W15010402 "Steel packaging"
cap label var W15010402_IBA "Ferrous metal from incineration bottom ash (IBA)"
cap label var W150107 "Glass packaging"
cap label var W150199 "Other packaging"
cap label var ELV "Waste arising only from end-of-life vehicles of type passenger cars (M1), light commercial vehicles (N1) and three wheeled moped vehicles (ELV directive)"
cap label var DMDP "Waste from dismantling and de-pollution of end-of-life-vehicles (LIQ+W1601A+W1601B+W1601C+LoW:160103+160107+160119+160120+1606+1608)"
cap label var LIQ "Liquids (excluding fuel) (LoW: 1301 until 1305+1308+1406+160113 until 160115+160121+160122+160199)"
cap label var W160103 "End-of-life vehicles: tyres"
cap label var W160107 "End-of-life vehicles: oil filters"
cap label var W1601A "End-of-life vehicles: other materials arising from depollution (excluding fuel) (LoW: 160108 until 160111+160121)"
cap label var W1601B "End-of-life vehicles: metal components (LoW: 160117+160118)"
cap label var W160119 "End-of-life vehicles: large plastic parts"
cap label var W160120 "End-of-life vehicles: glass"
cap label var W1601C "End-of-life vehicles: other materials arising from dismantling (LoW: 160112+160122+160199)"
cap label var W1606 "Batteries and accumulators"
cap label var W160601 "Lead batteries"
cap label var W160601PB "Lead content of batteries"
cap label var W160602 "Ni-Cd batteries"
cap label var W160602CD "Cadmium content of batteries"
cap label var W1606B "Portable batteries and accumulators"
cap label var W160605 "Other batteries and accumulators"
cap label var W1608 "Catalysts"
cap label var W1910 "Waste arising from shredding of end-of-life vehicles (W191001+W191002+W1910A+W1910B)"
cap label var W191001 "Ferrous scrap (steel) from shredding"
cap label var W191002 "Non-ferrous materials (aluminium, copper, zinc, lead, etc.) from shredding"
cap label var W1910A "Shredder Light Fraction (SLF) (LoW: 191003+191004)"
cap label var W1910B "Other materials arising from shredding (LoW: 191005+191006)"
cap label var EXP "End-of-life vehicles exported"
cap label var PLAST "Plastics"
cap label var PAPER "Paper and cardboard"
cap label var MT_FER "Iron and steel"
cap label var MT_PRE "Precious metals"
cap label var CAN "Copper, aluminium and nickel"
cap label var EE10 "Waste arising only from separate collection of EEE (10 categories methodology defined in WEEE directive)"
cap label var EE_LHA "Large household appliances"
cap label var EE_SHA "Small household appliances"
cap label var EE_ITT "IT and telecommunications equipment"
cap label var EE_CPV "Consumer equipment and photovoltaic panels"
cap label var EE_CPV_CON "Consumer equipment"
cap label var EE_CPV_PVP "Photovoltaic panels"
cap label var EE_LIT "Lighting equipment"
cap label var EE_LIT_GDL "Gas discharge lamps"
cap label var EE_EET "Electrical and electronic tools"
cap label var EE_TLS "Toys, leisure and sports equipment"
cap label var EE_MED "Medical devices"
cap label var EE_MON "Monitoring and control instruments"
cap label var EE_ATD "Automatic dispensers"
cap label var EE6 "Waste arising only from separate collection of EEE (6 categories methodology defined in WEEE directive)"
cap label var EE_TEE "Temperature exchange equipment"
cap label var EE_SME "Screens, monitors, and equipment containing screens having a surface greater than 100 cm2"
cap label var EE_LMP "Lamps"
cap label var EE_LE "Large equipment (any external dimension more than 50 cm)"
cap label var EE_LEXPVP "Large equipment excluding photovoltaic panels"
cap label var EE_LE_PVP "Photovoltaic panels"
cap label var EE_SE "Small equipment (no external dimension more than 50 cm)"
cap label var EE_SITTE "Small IT and telecommunications equipment (no external dimension more than 50 cm)"
cap label var HAZ "Hazardous waste"
cap label var MUN "Municipal waste"
cap label var MUN_OTH "Other municipal waste"
cap label var ORG "Organic material"
cap label var ORG_OTH "Other in-organic material"
