cap label var TOTAL "Total"
cap label var GD_SERV_PCS "Goods, services or processes"
cap label var PRD "Product innovation"
cap label var PRD_GD "Goods"
cap label var PRD_SERV "Services"
cap label var BPCS "Business process innovation"
cap label var PCS_GD_SERV "New or improved methods for producing goods or providing services"
cap label var PCS "Process innovation"
cap label var PCS_ACT "Supporting activities for processes"
cap label var PCS_LOG "New or improved logistics, delivery or distribution methods"
cap label var LOG "Innovations in logistics"
cap label var LOG_OTH "Other innovations in logistics"
cap label var RDESG_SHPM "Redesign of shipment (packaging, weight and density)"
cap label var OPROC_EXTREL "New business practices for organising procedures or external relations"
cap label var OPROC "New business practices for organising procedures"
cap label var OEXTREL "New methods of organising external relations"
cap label var OWR_DEC_HRM "New methods of organising work responsibility, decision making or human resource management"
cap label var OWR_DEC "New methods of organising work responsibilities and decision making"
cap label var COMM "New or improved methods for information processing or communication"
cap label var ACCT "New methods for accounting or other administrative operations"
cap label var SLS_SERV "New marketing methods for promotion, packaging, pricing, product placement or after sales services"
cap label var DESG_PK "Significant changes to the aesthetic design or packaging"
cap label var PROMO "New media or techniques for product promotion"
cap label var PLACMT "New methods for product placement"
cap label var PRC_GD_SERV "New methods of pricing goods or services"
cap label var IMS "Inventory management systems"
cap label var DSCM "Digital supply chain management"
cap label var EPROC "E-procurement"
cap label var UNAIDF_WSUPCH "Unique and automatic identification of products within the whole supply chain"
cap label var LOG_RVS "Reverse logistics"
cap label var NEWDLV_MDL "New delivery models, including the use of alternatively fueled vehicles or multi-modal logistics"
cap label var INN_WRL_GE1 "At least one 'world first' product innovation"
cap label var INN_NWRL "No 'world first' product innovation"
cap label var INN_WRL_UNK "Unknown 'world first' product innovation"
cap label var PRD_NEW "New or significantly improved products"
cap label var PRD_NEW_ENT "New or significantly improved products that were new to the firm"
cap label var PRD_NEW_ENT_ONL "New or significantly improved products that were new to the firm only"
cap label var PRD_NEW_MKT "New or significantly improved products that were new to the market"
cap label var SAME "Unchanged or marginally modified products (of product innovators)"
