cap label var TOTAL "Total"
cap label var PAS_FR "Passengers and freight"
cap label var PAS "Passengers embarked and disembarked"
cap label var PAS_EMB "Passengers embarked"
cap label var PAS_DEMB "Passengers disembarked"
cap label var PAS_BRD "Passengers on board"
cap label var PAS_BRD_ARR "Passengers on board (arrivals)"
cap label var PAS_BRD_DEP "Passengers on board (departures)"
cap label var PAS_CRD "Passengers carried"
cap label var PAS_CRD_ARR "Passengers carried (arrival)"
cap label var PAS_CRD_DEP "Passengers carried (departures)"
cap label var PAS_TRS "Direct transit passengers"
cap label var PAS_TRF "Transfer passengers"
cap label var PAS_ONL "Passengers only"
cap label var ST_PAS "Passengers seats available"
cap label var ST_PAS_ARR "Passengers seats available (arrivals)"
cap label var ST_PAS_DEP "Passengers seats available (departures)"
cap label var FR "Freight"
cap label var FR_LD_NLD "Freight loaded and unloaded"
cap label var FR_LD "Freight loaded"
cap label var FR_NLD "Freight unloaded"
cap label var FR_ONL "Freight only"
cap label var FRM_BRD "Freight and mail on board"
cap label var FRM_BRD_ARR "Freight and mail on board (arrivals)"
cap label var FRM_BRD_DEP "Freight and mail on board (departures)"
cap label var FRM_LD_NLD "Freight and mail loaded and unloaded"
cap label var FRM_LD "Freight and mail loaded"
cap label var FRM_NLD "Freight and mail unloaded"
cap label var FRM_TRS "Freight and mail in transit"
cap label var CAF "Commercial air flights (passengers, freight and mail)"
cap label var CAF_PAS "Commercial passenger air flights"
cap label var CAF_PAS_ARR "Commercial passenger air flights (arrivals)"
cap label var CAF_PAS_DEP "Commercial passenger air flights (departures)"
cap label var CAF_FRM "Freight and mail commercial air flights"
cap label var CAF_FRM_ARR "Freight and mail commercial air flights (arrivals)"
cap label var CAF_FRM_DEP "Freight and mail commercial air flights (departures)"
cap label var ACM "Aircraft movements (passenger, freight and mail, commercial and non-commercial general aviation operations)"
cap label var CACM "Commercial aircraft movements (passenger, freight and mail, commercial general aviation operations)"
