cap label var TOTAL "Total"
cap label var _0 "No persons"
cap label var _1 "1 person"
cap label var _2 "2 persons"
cap label var _3 "3 persons"
cap label var _3_5 "From 3 to 5 persons"
cap label var _4 "4 persons"
cap label var GE4 "4 persons or more"
cap label var _5 "5 persons"
cap label var _6 "6 persons"
cap label var _6_10 "From 6 to 10 persons"
cap label var GE6 "6 persons or more"
cap label var _7 "7 persons"
cap label var GE7 "7 persons or more"
cap label var _8 "8 persons"
cap label var _9 "9 persons"
cap label var _10 "10 persons"
cap label var GE11 "11 persons or more"
cap label var UNK "Unknown"
