cap label var C0 "Coefficient 0"
cap label var C1 "Coefficient 1"
cap label var C2 "Coefficient 2"
cap label var C3 "Coefficient 3"
cap label var C4 "Coefficient 4"
cap label var C5 "Coefficient 5"
