cap label var TOTAL "Total"
cap label var A1 "Single person"
cap label var A1_LT30 "One adult younger than 30 years"
cap label var A1_30_64 "One adult aged between 30 and 64 years"
cap label var A1_LT64 "One adult younger than 64 years"
cap label var A1_LT65 "One adult younger than 65 years"
cap label var A1_GE65 "One adult 65 years or over"
cap label var A1_DCH "Single person with dependent children"
cap label var A1F "Single female"
cap label var A1M "Single male"
cap label var A2 "Two adults"
cap label var A2_2LT65 "Two adults younger than 65 years"
cap label var A2_GE1_GE65 "Two adults, at least one aged 65 years or over"
cap label var A2_DCH "Two adults with dependent children"
cap label var A2_1DCH "Two adults with one dependent child"
cap label var A2_2DCH "Two adults with two dependent children"
cap label var A2_2CH_LT14 "Two adults with two children younger than 14 years"
cap label var A2_GE3DCH "Two adults with three or more dependent children"
cap label var A_GE2_NDCH "Two or more adults without dependent children"
cap label var A_GE2_DCH "Two or more adults with dependent children"
cap label var A_GE3 "Three or more adults"
cap label var A_GE3_DCH "Three or more adults with dependent children"
cap label var CPL_NCH_NOTH "Couple without children without other persons"
cap label var CPL_OTH "Couple living with other persons"
cap label var CH_MCPL "Child living with both married parents"
cap label var CH_CCPL "Child living with both parents cohabiting"
cap label var CH_A0 "Child not living with parents"
cap label var CH_A1 "Child living with a single parent"
cap label var OTH "Other"
cap label var OTH_NCH "Other, no children"
cap label var OTH_CH "Other with children"
cap label var ALL_NDCH "All types without dependent children"
cap label var ALL_DCH "All types with dependent children"
cap label var HH_NDCH "Households without dependent children"
cap label var HH_DCH "Households with dependent children"
cap label var HH_O1 "Households in Objective 1 regions / "Convergence" regions"
cap label var OTHER "Other households"
cap label var HH_NO1 "Households in not Objective 1 regions / "Regional Competitiveness and Employment" Region"
cap label var HH_DEG1 "Households located in cities"
cap label var HH_DEG2 "Households located in towns and suburbs"
cap label var HH_DEG3 "Households located in rural areas"
cap label var HHI_Q1 "Number of households with income in first quartile"
cap label var HHI_Q2 "Number of households with income in second quartile"
cap label var HHI_Q3 "Number of households with income in third quartile"
cap label var HHI_Q4 "Number of households with income in fourth quartile"
cap label var UNK "Unknown"
