cap label var TOTALNOREROUTE "Total receipts"
cap label var CORPORATION "Corporations (non-financial and financial)"
cap label var GG_CENT "General government central"
cap label var GG_LOC "General government state and local"
cap label var GG_SS "General government social security funds"
cap label var GG_TOT "Total general government"
cap label var HOUSENOREROUTE "Households"
cap label var NONPROF "Non-profit institutions serving households"
cap label var RESTNOREROUTE "Rest of the world"
cap label var TOTAL "Total receipts including transactions between schemes"
cap label var HOUSE "Households including transactions between schemes"
cap label var REST "Rest of the world including transactions between schemes"
