cap label var TOTAL "All ISCED 2011 levels"
cap label var ED0_8 "Early childhood to tertiary education"
cap label var ED0_4 "Less than primary, primary, secondary and post-secondary non-tertiary education (levels 0-4)"
cap label var ED0_2 "Less than primary, primary and lower secondary education (levels 0-2)"
cap label var ED0 "Early childhood education"
cap label var ED01 "Early childhood educational development"
cap label var ED02_8 "Pre-primary to tertiary education"
cap label var ED02 "Pre-primary education"
cap label var ED1_4 "Primary, lower secondary, upper secondary and post-secondary non-tertiary education (levels 1-4)"
cap label var ED1_3 "Primary and secondary education (levels 1-3)"
cap label var ED1_2 "Primary and lower secondary education (levels 1 and 2)"
cap label var ED1 "Primary education"
cap label var ED2_4 "Lower secondary, upper secondary and post-secondary non-tertiary education (levels 2-4)"
cap label var ED2_3 "Secondary education (levels 2 and 3)"
cap label var ED2 "Lower secondary education"
cap label var ED24 "Lower secondary education - general"
cap label var ED25_35_45 "Lower secondary, upper secondary and post-secondary non-tertiary education - vocational (levels 25, 35 and 45)"
cap label var ED25 "Lower secondary education - vocational"
cap label var ED3_8 "Upper secondary, post-secondary non-tertiary and tertiary education (levels 3-8)"
cap label var ED3_4 "Upper secondary and post-secondary non-tertiary education (levels 3 and 4)"
cap label var ED3_4GEN "Upper secondary and post-secondary non-tertiary education (levels 3 and 4) - general"
cap label var ED3_4VOC "Upper secondary and post-secondary non-tertiary education (levels 3 and 4) - vocational"
cap label var ED3_4UNK "Upper secondary and post-secondary non-tertiary education (levels 3 and 4) - orientation unknown"
cap label var ED3 "Upper secondary education"
cap label var ED3SW "Upper secondary education - school and work-based vocational programmes"
cap label var ED34_44 "Upper secondary and post-secondary non-tertiary education - general (levels 34 and 44)"
cap label var ED34 "Upper secondary education - general"
cap label var ED341 "Upper secondary education - general, insufficient for level completion or partial level completion, without direct access to tertiary education"
cap label var ED342_352 "Upper secondary education - all programmes, sufficient for partial level completion, without direct access to tertiary education (levels 342 and 352)"
cap label var ED342 "Upper secondary education - general, sufficient for partial level completion, without direct access to tertiary education"
cap label var ED343_353 "Upper secondary education - all programmes, sufficient for level completion, without direct access to tertiary education (levels 343 and 353)"
cap label var ED343 "Upper secondary education - general, sufficient for level completion, without direct access to tertiary education"
cap label var ED344_354 "Upper secondary education - all programmes, sufficient for level completion, with direct access to tertiary education (levels 344 and 354)"
cap label var ED344 "Upper secondary education - general, sufficient for level completion, with direct access to tertiary education"
cap label var ED35_45 "Upper secondary and post-secondary non-tertiary education - vocational (levels 35 and 45)"
cap label var ED35 "Upper secondary education - vocational"
cap label var ED351 "Upper secondary education - vocational, insufficient for level completion or partial level completion, without direct access to tertiary education"
cap label var ED352 "Upper secondary education - vocational, sufficient for partial level completion, without direct access to tertiary education"
cap label var ED353 "Upper secondary education - vocational, sufficient for level completion, without direct access to tertiary education"
cap label var ED354 "Upper secondary education - vocational, sufficient for level completion, with direct access to tertiary education"
cap label var ED4 "Post-secondary non-tertiary education"
cap label var ED4SW "Post-secondary non-tertiary education - school and work-based vocational programmes"
cap label var ED44 "Post-secondary non-tertiary education - general"
cap label var ED441 "Post-secondary non-tertiary education - general, insufficient for level completion, without direct access to tertiary education"
cap label var ED443_453 "Post-secondary non-tertiary education - all programmes, sufficient for level completion, without direct access to tertiary education (levels 443 and 453)"
cap label var ED443 "Post-secondary non-tertiary education - general, sufficient for level completion, without direct access to tertiary education"
cap label var ED444_454 "Post-secondary non-tertiary education - all programmes, sufficient for level completion, with direct access to tertiary education (levels 444 and 454)"
cap label var ED444 "Post-secondary non-tertiary education - general, sufficient for level completion, with direct access to tertiary education"
cap label var ED45 "Post-secondary non-tertiary education - vocational"
cap label var ED451 "Post-secondary non-tertiary education - vocational, insufficient for level completion, without direct access to tertiary education"
cap label var ED453 "Post-secondary non-tertiary education - vocational, sufficient for level completion, without direct access to tertiary education"
cap label var ED454 "Post-secondary non-tertiary education - vocational, sufficient for level completion, with direct access to tertiary education"
cap label var ED5_8 "Tertiary education (levels 5-8)"
cap label var ED5_7 "Tertiary education excluding doctoral or equivalent level (levels 5-7)"
cap label var ED5_6 "Short-cycle tertiary education and Bachelor's or equivalent level (levels 5 and 6)"
cap label var ED5 "Short-cycle tertiary education"
cap label var ED5SW "Short-cycle tertiary education - school and work-based vocational programmes"
cap label var ED54 "Short-cycle tertiary education - general/academic"
cap label var ED541 "Short-cycle tertiary education - general/academic, insufficient for level completion"
cap label var ED544 "Short-cycle tertiary education - general/academic, sufficient for level completion"
cap label var ED55 "Short-cycle tertiary education - vocational/professional"
cap label var ED551 "Short-cycle tertiary education - vocational/professional, insufficient for level completion"
cap label var ED554 "Short-cycle tertiary education - vocational/professional, sufficient for level completion"
cap label var ED6_8 "Tertiary education excluding short-cycle tertiary education (levels 6-8)"
cap label var ED6 "Bachelor's or equivalent level"
cap label var ED64 "Bachelor's or equivalent level - academic"
cap label var ED641_651_661 "Bachelors's or equivalent level - all programmes, insufficient for level completion (levels 641, 651 and 661)"
cap label var ED641 "Bachelor's or equivalent level - academic, insufficient for level completion"
cap label var ED645_655_665 "Bachelors's or equivalent level - all programmes, first degree (3-4 years) (levels 645, 655 and 665)"
cap label var ED645 "Bachelor's or equivalent level - academic, first degree (3-4 years)"
cap label var ED646_656_666 "Bachelors's or equivalent level - all programmes, long first degree (more than 4 years) (levels 646, 656 and 666)"
cap label var ED646 "Bachelor's or equivalent level - academic, long first degree (more than 4 years)"
cap label var ED647_657_667 "Bachelors's or equivalent level - all programmes, second or further degree (following a Bachelor's or equivalent programme) (levels 647, 657 and 667)"
cap label var ED647 "Bachelor's or equivalent level - academic, second or further degree (following a Bachelor's or equivalent programme)"
cap label var ED65 "Bachelor's or equivalent level - professional"
cap label var ED651 "Bachelor's or equivalent level - professional, insufficient for level completion"
cap label var ED655 "Bachelor's or equivalent level - professional, first degree (3-4 years)"
cap label var ED656 "Bachelor's or equivalent level - professional, long first degree (more than 4 years)"
cap label var ED657 "Bachelor's or equivalent level - professional, second or further degree (following a Bachelor's or equivalent programme)"
cap label var ED66 "Bachelor's or equivalent level - orientation unspecified"
cap label var ED661 "Bachelor's or equivalent level - orientation unspecified, insufficient for level completion"
cap label var ED665 "Bachelor's or equivalent level - orientation unspecified, first degree (3-4 years)"
cap label var ED666 "Bachelor's or equivalent level - orientation unspecified, long first degree (more than 4 years)"
cap label var ED667 "Bachelor's or equivalent level - orientation unspecified, second or further degree (following a Bachelor's or equivalent programme)"
cap label var ED7_8 "Master's and Doctoral or equivalent level (levels 7 and 8)"
cap label var ED7 "Master's or equivalent level"
cap label var ED74 "Master's or equivalent level - academic"
cap label var ED741_751_761 "Master's or equivalent level - all programmes, insufficient for level completion (levels 741, 751 and 761)"
cap label var ED741 "Master's or equivalent level - academic, insufficient for level completion"
cap label var ED746_756_766 "Master's or equivalent level - all programmes, long first degree (at least 5 years) (levels 746, 756 and 766)"
cap label var ED746 "Master's or equivalent level - academic, long first degree (at least 5 years)"
cap label var ED747_757_767 "Master's or equivalent level - all programmes, second or further degree (following a Bachelor's or equivalent programme) (levels 747, 757 and 767)"
cap label var ED747 "Master's or equivalent level - academic, second or further degree (following a Bachelor's or equivalent programme)"
cap label var ED748_758_768 "Master's or equivalent level - all programmes, second or further degree (following a Master's or equivalent programme) (levels 748, 758 and 768)"
cap label var ED748 "Master's or equivalent level - academic, second or further degree (following a Master's or equivalent programme)"
cap label var ED75 "Master's or equivalent level - professional"
cap label var ED751 "Master's or equivalent level - professional, insufficient for level completion"
cap label var ED756 "Master's or equivalent level - professional, long first degree (at least 5 years)"
cap label var ED757 "Master's or equivalent level - professional, second or further degree (following a Bachelor's or equivalent programme)"
cap label var ED758 "Master's or equivalent level - professional, second or further degree (following a Master's or equivalent programme)"
cap label var ED76 "Master's or equivalent level - orientation unspecified"
cap label var ED761 "Master's or equivalent level - orientation unspecified, insufficient for level completion"
cap label var ED766 "Master's or equivalent level - orientation unspecified, long first degree (at least 5 years)"
cap label var ED767 "Master's or equivalent level - orientation unspecified, second or further degree (following a Bachelor's or equivalent programme)"
cap label var ED768 "Master's or equivalent level - orientation unspecified, second or further degree (following a Master's or equivalent programme)"
cap label var ED8 "Doctoral or equivalent level"
cap label var ED9 "Not elsewhere classified"
cap label var NAP "Not applicable"
cap label var NRP "No response"
cap label var UNK "Unknown"
