cap label var TOTAL "Total"
cap label var CA "Current account"
cap label var CKA "Current plus capital account (balance = Net lending (+) / net borrowing (-))"
cap label var GS "Goods and services"
cap label var GSIN1 "Goods, services and primary income"
cap label var G "Goods"
cap label var G1 "General merchandise on a balance of payments basis"
cap label var G1Z "General merchandise on a balance of payments basis, re-exports"
cap label var G2 "Net exports of goods under merchanting"
cap label var G21 "Goods acquired under merchanting"
cap label var G22 "Goods sold under merchanting"
cap label var G3 "Nonmonetary gold"
cap label var G4EU "Branding - quasi-transit trade adjustment"
cap label var S "Services"
cap label var SA "Services: Manufacturing services on physical inputs owned by others"
cap label var SAY "Services: Goods for processing in reporting economy ? Goods returned , Goods received"
cap label var SAZ "Services: Goods for processing abroad - Goods sent , Goods returned"
cap label var SB "Services: Maintenance and repair services n.i.e."
cap label var SBG "Services: Maintenance and repair services n.i.e. (of which goods)"
cap label var SC "Services: Transport"
cap label var SC1 "Services: Sea transport"
cap label var SC11 "Services: Sea transport; Passenger"
cap label var SC11Z "Services: Sea transport; Passenger; Of which: Payable by border, seasonal, and other short-term workers"
cap label var SC12 "Services: Sea transport; Freight"
cap label var SC13 "Services: Sea transport; Other than passenger and freight"
cap label var SC2 "Services: Air transport"
cap label var SC21 "Services: Air transport; Passenger"
cap label var SC21Z "Services: Air transport; Passenger; Of which: Payable by border, seasonal, and other short-term workers"
cap label var SC22 "Services: Air transport; Freight"
cap label var SC23 "Services: Air transport; Other than passenger and freight"
cap label var SC3 "Services: Other modes of transport"
cap label var SC31 "Services: Other modes of transport; Passenger"
cap label var SC31Z "Services: Other modes of transport; Passenger; Of which: Payable by border, seasonal, and other short-term workers"
cap label var SC32 "Services: Other modes of transport; Freight"
cap label var SC33 "Services: Other modes of transport; Other than passenger and freight"
cap label var SC3A "Services: Space transport"
cap label var SC3B "Services: Rail transport"
cap label var SC3B1 "Services: Rail transport; Passenger"
cap label var SC3B2 "Services: Rail transport; Freight"
cap label var SC3B3 "Services: Rail transport; Other than passenger and freight"
cap label var SC3C "Services: Road transport"
cap label var SC3C1 "Services: Road transport; Passenger"
cap label var SC3C2 "Services: Road transport; Freight"
cap label var SC3C3 "Services: Road transport; Other than passenger and freigh"
cap label var SC3D "Services: Inland waterway transport"
cap label var SC3D1 "Services: Inland waterway transport; Passenger"
cap label var SC3D2 "Services: Inland waterway transport; Freight"
cap label var SC3D3 "Services: Inland waterway transport; Other than passenger and freight"
cap label var SC3E "Services: Pipeline transport"
cap label var SC3F "Services: Electricity transmission"
cap label var SC3G "Services: Other supporting and auxiliary transport services"
cap label var SC4 "Services: Postal and courier services"
cap label var SC41X "Services: Postal services"
cap label var SC42X "Services: Courier services"
cap label var SCA "Services: All modes of transport; Passenger"
cap label var SCAZ "Services: All modes of transport; Passenger; Of which: payable by border, seasonal, and other short-term workers"
cap label var SCB "Services: All modes of transport; Freight"
cap label var SCC "Services: All modes of transport; Other than passenger and freight"
cap label var SCC1 "Services: All modes of transport; Other than passenger and freight; Other than Postal and courier services"
cap label var SD "Services: Travel"
cap label var SD1 "Services: Travel; Goods (Travel)"
cap label var SD2 "Services: Travel; Local transport services"
cap label var SD3 "Services: Travel; Accommodation services"
cap label var SD4 "Services: Travel; Food-serving services"
cap label var SD5 "Services: Travel; Other services than goods (Travel), local transport services, accommodation services, and food-serving services"
cap label var SD5Y "Services: Travel; Other services than goods (Travel), local transport services, accommodation services, and food-serving services; Of which: Education services"
cap label var SD5Z "Services: Travel; Other services than goods (Travel), local transport services, accommodation services, and food-serving services; Of which: Health services"
cap label var SDA "Services: Travel; Business"
cap label var SDA1 "Services: Travel; Business; Acquisition of goods and services by border, seasonal, and other short-term workers"
cap label var SDA2 "Services: Travel; Business; Other than acquisition of goods and services by border, seasonal, and other short-term workers"
cap label var SDB "Services: Travel; Personal"
cap label var SDB1 "Services: Travel; Personal; Health-related"
cap label var SDB2 "Services: Travel; Personal; Education-related"
cap label var SDB3 "Services: Travel; Personal; Other than heath-related and education-related"
cap label var SDG "Services: Travel (of which goods)"
cap label var SDZ "Services: Tourism-related services in travel and passenger transport"
cap label var SE "Services: Construction"
cap label var SE1 "Services: Construction abroad"
cap label var SE2 "Services: Construction in the reporting economy"
cap label var SEG "Services: Construction (of which goods)"
cap label var SF "Services: Insurance and pension services"
cap label var SF1 "Services: Direct insurance"
cap label var SF11 "Services: Life insurance"
cap label var SF11Y "Services: Gross life insurance premiums receivable (credits) and payable (debits)"
cap label var SF11Z "Services: Gross life insurance claims receivable (credits) and payable (debits)"
cap label var SF12 "Services: Freight insurance"
cap label var SF12Y "Services: Gross freight insurance premiums receivable (credits) and payable (debits)"
cap label var SF12Z "Services: Gross freight insurance claims receivable (credits) and payable (debits)"
cap label var SF13 "Services: Direct insurance other than life and freight insurance"
cap label var SF13Y "Services: Gross direct insurance (other than life and freight insurance), premiums receivable (credits) and payable (debits)"
cap label var SF13Z "Services: Gross direct insurance (other than life and freight insurance), claims receivable (credits) and payable (debits)"
cap label var SF2 "Services: Reinsurance"
cap label var SF3 "Services: Auxiliary insurance services"
cap label var SF4 "Services: Pension and standardized guarantee services"
cap label var SF41 "Services: Pension services"
cap label var SF42 "Services: Standardized guarantee services"
cap label var SG "Services: Financial services"
cap label var SG1 "Services: Financial services explicitly charged and other financial services"
cap label var SG2 "Services: Financial intermediation services indirectly measured (FISIM)"
cap label var SH "Services: Charges for the use of intellectual property n.i.e."
cap label var SH1 "Services: Franchises and trademarks licensing fees"
cap label var SH2 "Services: Licences for the use of outcomes of research and development"
cap label var SH3 "Services: Licences to reproduce and/or distribute computer software"
cap label var SH4 "Services: Licences to reproduce and/or distribute audio-visual and related products"
cap label var SH41 "Services: Licences to reproduce and/or distribute audio-visual products"
cap label var SH42 "Services: Licences to reproduce and/or distribute other than audio-visual products"
cap label var SI "Services: Telecommunications, computer, and information services"
cap label var SI1 "Services: Telecommunications services"
cap label var SI2 "Services: Computer services"
cap label var SI21 "Services: Computer software"
cap label var SI21Z "Services: Computer software; Of which: Software originals"
cap label var SI22 "Services: Computer services other than computer software"
cap label var SI3 "Services: Information services"
cap label var SI31 "Services: News agency services"
cap label var SI32 "Services: Information services other than news agency services"
cap label var SJ "Services: Other business services"
cap label var SJ1 "Services: Research and development services"
cap label var SJ11 "Services: Work undertaken on a systematic basis to increase the stock of knowledge"
cap label var SJ111 "Services: Provision of customized and non-customized research and development services"
cap label var SJ112 "Services: Sale of proprietary rights arising from research and development"
cap label var SJ1121 "Services: Patents"
cap label var SJ1122 "Services: Copyrights arising from research and development"
cap label var SJ1123 "Services: Industrial processes and designs"
cap label var SJ1124 "Services: Sales of proprietary rights arising from research and development other than patents, copyrights arising from research and development and industrial processes and designs"
cap label var SJ12 "Services: Research and development services other than work undertaken on a systematic basis to increase the stock of knowledge"
cap label var SJ2 "Services: Professional and management consulting services"
cap label var SJ21 "Services: Legal, accounting, management consulting, and public relations services"
cap label var SJ211 "Services: Legal services"
cap label var SJ212 "Services: Accounting, auditing, bookkeeping, and tax consulting services"
cap label var SJ213 "Services: Business and management consulting and public relations services"
cap label var SJ22 "Services: Advertising, market research, and public opinion polling services"
cap label var SJ22Z "Services: Advertising, market research, and public opinion polling services; Of which: Convention, trade-fair and exhibition organization services"
cap label var SJ3 "Services: Technical, trade-related, and other business services"
cap label var SJ31 "Services: Architectural, engineering, scientific, and other technical services"
cap label var SJ311 "Services: Architectural services"
cap label var SJ312 "Services: Engineering services"
cap label var SJ313 "Services: Scientific and other technical services"
cap label var SJ32 "Services: Waste treatment and de-pollution, agricultural and mining services"
cap label var SJ321 "Services: Waste treatment and de-pollution"
cap label var SJ322 "Services: Services incidental to agriculture, forestry and fishing"
cap label var SJ323 "Services: Services incidental to mining, and oil and gas extraction"
cap label var SJ32X "Memo grouping: Services, Services incidental to agriculture and mining"
cap label var SJ33 "Services: Operating leasing services"
cap label var SJ34T "Services: Total trade related transactions"
cap label var SJ34 "Services: Trade-related services"
cap label var SJ34D "Services: Distribution services"
cap label var SJ35 "Services: Other business services n.i.e."
cap label var SJ35Z "Services: Other business services n.i.e.; Of which: Employment services, i.e., search, placement and supply services of personnel"
cap label var SK "Services: Personal, cultural, and recreational services"
cap label var SK1 "Services: Audiovisual and related services"
cap label var SK11 "Services: Audio-visual services"
cap label var SK11Z "Services: Audio-visual services; Of which: Audio-visual originals"
cap label var SK12 "Services: Artistic related services"
cap label var SK2 "Services: Personal, cultural, and recreational services other than audiovisual and related services"
cap label var SK21 "Services: Personal, cultural, and recreational services other than audiovisual and related services; Health services"
cap label var SK22 "Services: Personal, cultural, and recreational services other than audiovisual and related services; Education services"
cap label var SK23 "Services: Personal, cultural, and recreational services other than audiovisual and related services; Heritage and recreational services"
cap label var SK24 "Services: Personal, cultural, and recreational services other than audiovisual and related services; Personal services other than health, education and heritage and recreational services"
cap label var SL "Services: Government goods and services n.i.e."
cap label var SL1 "Services: Embassies and consulates"
cap label var SL2 "Services: Military units and agencies"
cap label var SL3 "Services: Government goods and services n.i.e. other than embassies and consulates and military units and agencies"
cap label var SL31X "Memo item: Services, Government services: reimbursement of MSs' cost of collecting own resources"
cap label var SL32X "Memo item: Services, Government services: building rentals"
cap label var SL33X "Memo item: Services, Government services: other government services n.i.e."
cap label var SLG "Services: Government goods and services n.i.e. (of which goods)"
cap label var SOX "Services: Commercial services"
cap label var SN "Services: Services not allocated"
cap label var S1 "Services: EBOPS 2010 complementary groupings: Audio-visual transactions"
cap label var S1Z "Services: EBOPS 2010 complementary groupings: Audio-visual transactions; Licences to use audio-visual products"
cap label var S2 "Services: EBOPS 2010 complementary groupings: Cultural transactions"
cap label var S3 "Services: EBOPS 2010 complementary groupings: Computer software transactions"
cap label var S3Z "Services: EBOPS 2010 complementary groupings: Computer software transactions; Licences to use computer software products"
cap label var S4 "Services: EBOPS 2010 complementary groupings: Call-centre services"
cap label var S6 "Services: EBOPS 2010 complementary groupings: Total trade-related transactions"
cap label var S7 "Services: EBOPS 2010 complementary groupings: Environmental transactions"
cap label var S8 "Services: EBOPS 2010 complementary groupings: Total health services"
cap label var S9 "Services: EBOPS 2010 complementary groupings: Total education services"
cap label var S_X_CG "Services excluding Transport and Financial services"
cap label var OTH_S "Other services"
cap label var IN "Primary and secondary income"
cap label var IN1 "Primary income"
cap label var D1 "Primary income: Compensation of employees"
cap label var D11 "Primary income: Wages and salaries excluding employers' social contributions"
cap label var D12 "Primary income: Employers' social contributions"
cap label var D4 "Property income"
cap label var D4P__F "Primary income: Investment income"
cap label var D4P__D__F "Primary income: Investment income; Direct investment"
cap label var D42S "Primary income: Dividends, withdrawals from income of quasi corporations and income distributed to investment fund shareholders (excluding RIE)"
cap label var D4S__D__F5 "Primary income: Direct Investment income attributable to equity and investment fund shareholders"
cap label var D42S__D__F5 "Primary income: Direct Investment, equity, dividends, withdrawals from income of quasi corporations and income distributed to investment fund shareholders (excluding RIE)"
cap label var D42S__D1__F5 "Primary income: Direct investment, Equity, Direct investor in direct investment enterprises, dividends, withdrawals from income of quasi corporations and income distributed to investment fund shareholders (excluding RIE)"
cap label var D42S__D2__F5 "Primary income: Direct Investment, Equity, Direct investment enterprises in direct Investor (Reverse Investment), dividends, withdrawals from income of quasi corporations and income distributed to investment fund shareholders"
cap label var D42S__D3__F5 "Primary income: Direct investment, equity, between fellow enterprises, dividends, withdrawals from income of quasi corporations and income distributed to investment fund shareholders"
cap label var D43 "Primary income: Reinvested earnings on foreign direct investment (excluding investment funds)"
cap label var D43S__D__F5 "Primary income: Reinvested earnings on foreign direct investment (including investment funds)"
cap label var D4Q__D__FL "Primary income: Direct Investment, debt instruments"
cap label var D4Q__D1__FL "Primary income: Direct Investment, debt instruments, Direct investor in direct Investment enterprises"
cap label var D4Q__D2__FL "Primary income: Direct Investment, debt instruments, Direct investment enterprises in direct investor (Reverse Investment)"
cap label var D4Q__D3__FL "Primary income: Direct Investment, debt instruments, Direct investment between fellow enterprises"
cap label var D41 "Primary income: interest"
cap label var D41__D__FLA "Primary income: Direct Investment, debt instruments, interest"
cap label var D41G "Primary income: Interest before FISIM"
cap label var D41G__D__FLA "Primary income: Direct Investment, debt instruments, interest before FISIM"
cap label var D4P__P__F "Primary income: Investment income; Portfolio investment"
cap label var D4S__P__F5 "Primary income: Portfolio Investment income on equity and investment fund shares"
cap label var D42 "Primary income: Dividends and withdrawals from income of quasi corporations"
cap label var D42__P__F51 "Primary income: Portfolio investment, equity securities; Dividends and withdrawals from income of quasi corporations"
cap label var D443__P__F52 "Primary income: Portfolio investment, investment fund shares; investment income attributable to collective investment fund shareholders"
cap label var D4431__P__F52 "Primary income: Portfolio investment, investment fund shares; dividends attributable to collective investment fund shareholders"
cap label var D4432__P__F52 "Primary income: Portfolio investment, investment fund shares; Reinvested earnings attributable to collective investment fund shareholders"
cap label var D41__P__F3 "Primary income: Portfolio Investment, debt securities, interest"
cap label var D41__P__F3__S "Primary income: Portfolio Investment, debt securities, interest, short term"
cap label var D41__P__F3__L "Primary income: Portfolio Investment, debt securities, interest, long term"
cap label var D4P__O__F "Primary income: Investment income; Other investment"
cap label var D41__O__F12 "Primary income: Other Investment, interest on SDR"
cap label var D422__O__F5 "Primary income: Other investment, Withdrawals from income of quasi corporations"
cap label var D41__O__FLA "Primary income: Other Investment, interest"
cap label var D41G__O__FLA "Primary income: Other investment, interest before FISIM"
cap label var D44P__O__F6 "Primary income: Other Investment income attributable to policy holders (insurance, pension and standardized guarantee schemes)"
cap label var D4P__R__F "Primary income: Investment income; Reserve assets"
cap label var D41__R__FLA "Primary income: Reserve assets, interest"
cap label var D41G__R__FLA "Primary income: Reserve assets, interest before FISIM"
cap label var D4O "Primary income: Other primary income"
cap label var D2 "Primary income: Taxes on production and imports"
cap label var D21 "Primary income: Taxes on products"
cap label var D2121EU1 "Primary income: Taxes and duties on imports, Customs duties, Traditional Own Resources"
cap label var D2122EU2 "Primary income: Taxes and duties on imports, Agricultural levies, Trade with non member countries under the CAP, Traditional Own Resources"
cap label var D214AEU3 "Primary income: Taxes on products, Sugar/isoglucose production levies, Traditional Own Resources"
cap label var D21EU "Primary income: Taxes on products involving EU Institutions, Traditional Own Resources"
cap label var D29 "Primary income: Other taxes on production"
cap label var D29EU "Primary income: Other taxes on production - ECSC levy"
cap label var D3 "Primary income: Subsidies"
cap label var D31 "Primary income: Subsidies on products"
cap label var D31EU "Primary income: Subsidies on products, EU Institutions"
cap label var D31EU1 "Primary income: Subsidies on products - Agriculture and fishery"
cap label var D39 "Primary income: Other subsidies on production excluding subsidies on products"
cap label var D39EU "Primary income: Other subsidies on production excluding subsidies on products, EU Institutions"
cap label var D39EU1 "Primary income: Subsidies on production - Agriculture and fishery"
cap label var D39EU2 "Primary income: Subsidies on production - Grants for interest relief"
cap label var D39EU3 "Primary income: Subsidies on production - Other excluding agriculture, fishery and grants for interest of relief"
cap label var D45 "Primary income: Rent"
cap label var IN2 "Secondary income"
cap label var IN21 "Secondary income, current transfers"
cap label var IN22 "Secondary income: Other current transfers excluding personal transfers"
cap label var D5 "Secondary income: Current taxes on income, wealth, etc."
cap label var D51 "Secondary income: Taxes on income"
cap label var D59 "Secondary income: Other current taxes"
cap label var D5Z "Secondary income: Current taxes on income, wealth, etc. payable by border, seasonal, and other short-term workers"
cap label var D6 "Secondary income: Social contributions and benefits"
cap label var D61 "Secondary income: Social contributions"
cap label var D61Z "Secondary income: Social contributions payable by border, seasonal, and other short-term workers"
cap label var D62 "Secondary income: Social benefits other than social transfers in kind"
cap label var D63 "Secondary income: Social transfers in kind"
cap label var D7 "Secondary income: Other current transfers"
cap label var D71 "Secondary income: Net non-life insurance premiums"
cap label var D72 "Secondary income: Non-life insurance claims"
cap label var D73 "Secondary income: Current transfers within general government"
cap label var D74 "Secondary income: Current international cooperation"
cap label var D74EU "Secondary income: Current international cooperation involving the EU institutions"
cap label var D74EU1 "Secondary income: Current international cooperation -European Development Fund"
cap label var D74EU2 "Secondary income: Current international cooperation -European Social Fund"
cap label var D74EU3 "Secondary income: Current international cooperation -Agriculture and Fishery"
cap label var D74EU4 "Secondary income: Current international cooperation -European Regional Development Fund"
cap label var D74EU5 "Secondary income: Current international cooperation - European Coal and Steel Community"
cap label var D74EU6 "Secondary income: Current international cooperation - Other"
cap label var D75 "Secondary income: Miscellaneous current transfers"
cap label var D751 "Secondary income: Current transfers to NPISH (Non-Profit Institutions serving Households)"
cap label var D752 "Secondary income: Personal transfers (Current transfers between resident and non resident households)"
cap label var D752O "Secondary income: Personal transfers other than Workers' remittances"
cap label var D752W "Secondary income: Workers' remittances"
cap label var R1 "Supplementary item: Personal Remittances"
cap label var R1WR "Supplementary item: Workers remittances and compensation of employees"
cap label var R2 "Supplementary item: Total Remittances"
cap label var R3 "Supplementary item: Remittances and transfers"
cap label var D759 "Secondary income: Other miscellaneous current transfers"
cap label var D76 "Secondary income: VAT-and GNI-based EU own resources"
cap label var D761 "Secondary income: VAT-based third EU own resource"
cap label var D762 "Secondary income: GNI-based fourth EU own resource"
cap label var D762K "Secondary income: Current transfers - UK rebate"
cap label var D763 "Secondary income: Miscellaneous non-tax contributions of the governments to the institutions of the EU"
cap label var D7N "Secondary income: Current international cooperation and miscellaneous current transfers"
cap label var D7O "Secondary income: All miscellaneous current transfers"
cap label var D8 "Secondary income : Adjustment for change in pension entitlements"
cap label var KA "Capital account"
cap label var KAFA "Capital and financial account"
cap label var NP "Gross acquisitions / disposals of nonproduced nonfinancial assets"
cap label var D9 "Capital transfers"
cap label var D91 "Capital taxes"
cap label var D92 "Investment grants"
cap label var D92EU "Investment grants involving EU Institutions"
cap label var D92EU1 "Agriculture and Fishery grants"
cap label var D92EU2 "European Regional Development Fund - grants"
cap label var D92EU3 "European Development Fund: EU Commission capital transfers to third countries"
cap label var D92EU4 "Cohesion funds"
cap label var D92EU5 "Investment grants - Other"
cap label var D99 "Other capital transfers"
cap label var D99A "Other capital transfers: Debt forgiveness"
cap label var D99B "Other capital transfers excluding debt forgiveness"
cap label var D99EU "Other capital transfers involving EU Institutions"
cap label var D99EU1 "Other capital transfers - Agriculture and Fishery"
cap label var D99EU2 "Other capital transfers - Other"
cap label var FA "Financial account"
cap label var FA__D__F "Financial account; Direct Investment"
cap label var FA__D__F5 "Financial account; Direct Investment, Equity and investment fund shares/units"
cap label var FA__D__F51 "Financial account; Direct Investment; Equity"
cap label var FA__D__F511 "Financial account; Direct Investment; Equity; Listed shares"
cap label var FA__D__F512 "Financial account; Direct Investment; Equity; Unlisted shares"
cap label var FA__D__F519 "Financial account; Direct Investment; Equity; Other equity (e.g. real estate)"
cap label var FA__D__F52 "Financial account; Direct Investment; Investment fund shares/units"
cap label var FA__D__F5A "Financial account; Direct Investment; Equity other than reinvestment of earnings"
cap label var FA__D1__F5A "Financial account; Direct Investment; Equity other than reinvestment of earnings; in Direct investment enterprise"
cap label var FA__D2__F5A "Financial account; Direct Investment; Equity other than reinvestment of earnings; in Direct investor (reverse investment)"
cap label var FA__D3__F5A "Financial account; Direct Investment; Equity other than reinvestment of earnings; between fellow enterprises"
cap label var FA__D1__F5 "Financial account; Direct Investment; Equity and investment fund shares; in Direct investment enterprise"
cap label var FA__D2__F5 "Financial account; Direct Investment; Equity and investment fund shares; in Direct investor (reverse investment)"
cap label var FA__D3__F5 "Financial account; Direct Investment; Equity and investment fund shares; between fellow enterprises"
cap label var FA__D__F5B "Financial account; Direct Investment; Reinvestment of earnings"
cap label var FA__D__FL "Financial account; Direct Investment; Debt instruments"
cap label var FA__D1__FL "Financial account; Direct Investment; Debt instruments; in Direct investment enterprise"
cap label var FA__D2__FL "Financial account; Direct Investment; Debt instruments; in Direct investor (reverse investment)"
cap label var FA__D3__FL "Financial account; Direct Investment; Debt instruments; between Fellow enterprises"
cap label var FA__P__F "Financial account; Portfolio Investment"
cap label var FA__P__F5 "Financial account; Portfolio Investment; Equity and investment fund shares/units"
cap label var FA__P__F51 "Financial account; Portfolio Investment; Equity"
cap label var FA__P__F511 "Financial account; Portfolio Investment; Equity; Listed shares"
cap label var FA__P__F512 "Financial account; Portfolio Investment; Equity; Unlisted shares"
cap label var FA__P__F519 "Financial account; Portfolio Investment; Equity; Other equity"
cap label var FA__P__F52 "Financial account; Portfolio Investment; Investment fund shares/units"
cap label var FA__P__F52B "Financial account; Portfolio Investment; Reinvestment of earnings"
cap label var FA__P__F3 "Financial account; Portfolio Investment; Debt securities"
cap label var FA__P__F3__S "Financial account; Portfolio Investment; Debt securities; Short term"
cap label var FA__P__F3__EUR "Financial account; Portfolio Investment; Debt securities; currency of denomination Euro"
cap label var FA__P__F3__T__EUR "Financial account; Portfolio Investment; Debt securities; currency of denomination Euro"
cap label var FA__P__F3__USD "Financial account; Portfolio Investment; Debt securities; currency of denomination US Dollar"
cap label var FA__P__F3__T__USD "Financial account; Portfolio Investment; Debt securities; currency of denomination US Dollar"
cap label var FA__P__F3__X4 "Financial account; Portfolio Investment; Debt securities; all currencies of denomination except EUR and USD"
cap label var FA__P__F3__T__X4 "Financial account; Portfolio Investment; Debt securities; all currencies of denomination except EUR and USD"
cap label var FA__P__F3__S__EUR "Financial account; Portfolio Investment; Debt securities; Short term; currency of denomination Euro"
cap label var FA__P__F3__S__USD "Financial account; Portfolio Investment; Debt securities; Short term; currency of denomination US Dollar"
cap label var FA__P__F3__S__X4 "Financial account; Portfolio Investment; Debt securities; Short term; all currencies of denomination except EUR and USD"
cap label var FA__P__F3__L "Financial account; Portfolio Investment; Debt securities; Long term"
cap label var FA__P__F3__LS "Financial account; Portfolio Investment; Debt securities; Long-term original maturity (over 1 year) with short-term residual maturity (up to 1 year)"
cap label var FA__P__F3__LL "Financial account; Portfolio Investment; Debt securities; Long-term original maturity (over 1 year) with long-term residual maturity (over 1 year)"
cap label var FA__P__F3__L__EUR "Financial account; Portfolio Investment; Debt securities; Long term; currency of denomination Euro"
cap label var FA__P__F3__L__USD "Financial account; Portfolio Investment; Debt securities; Long term; currency of denomination US Dollar"
cap label var FA__P__F3__L__X4 "Financial account; Portfolio Investment; Debt securities; Long term; all currencies of denomination except EUR and USD"
cap label var FA__F__F7 "Financial account; Financial derivatives and employee stock options"
cap label var FA__O__F "Financial account; Other Investment"
cap label var FA__O__F12 "Financial account; Other Investment; SDRs"
cap label var FA__O__F2 "Financial account; Other Investment; Currency and deposits"
cap label var FA__O__F2__EUR "Financial account; Other Investment; Currency and deposits in Euro currency"
cap label var FA__O__F2__T__EUR "Financial account; Other Investment; Currency and deposits in Euro currency"
cap label var FA__O__F2__S "Financial account; Other Investment; Currency and deposits; Short term"
cap label var FA__O__F2__L "Financial account; Other Investment; Currency and deposits; Long term"
cap label var FA__O__F21__EUR "Financial account; Other Investment; Currency; Intra-Eurosystem technical claims and liabilities"
cap label var FA__O__F21__S__EUR "Financial account; Other Investment; Currency; Intra-Eurosystem technical claims and liabilities; short term"
cap label var FA__O__F221C__S__EUR "Financial account; Other Investment; Currency and deposits, central bank; Intra-Eurosystem technical claims and liabilities"
cap label var FA__O__F4 "Financial account; Other Investment; Loans"
cap label var FA__O__F4__S "Financial account; Other Investment; Loans; Short term"
cap label var FA__O__F4__L "Financial account; Other Investment; Loans; Long term"
cap label var FA__O__F519 "Financial account; Other Investment; Other equity"
cap label var FA__O__F6 "Financial account; Other Investment; Insurance, pension and standardized guarantee schemes"
cap label var FA__O__F81 "Financial account; Other Investment; Trade credits and advances"
cap label var FA__O__F81__S "Financial account; Other Investment; Trade credits and advances; Short term"
cap label var FA__O__F81__L "Financial account; Other Investment; Trade credits and advances; Long term"
cap label var FA__O__F89 "Financial account; Other Investment; Other accounts receivable/payable"
cap label var FA__O__F89__S "Financial account; Other Investment; Other accounts receivable/payable; Short term"
cap label var FA__O__F89__L "Financial account; Other Investment; Other accounts receivable/payable; Long term"
cap label var FA__R__F "Financial account; Reserve assets"
cap label var FA__R__F1 "Financial account; Reserve assets; Monetary gold and SDRs"
cap label var FA__R__F11 "Financial account; Reserve assets; Monetary gold"
cap label var FA__R__F11A "Financial account; Reserve assets; Gold bullion"
cap label var FA__R__F11B "Financial account; Reserve assets; Unallocated gold accounts"
cap label var FA__R__F12 "Financial account; Reserve assets; SDRs"
cap label var FA__R__F2 "Financial account; Reserve assets; Currency and deposits"
cap label var FA__R__FK "Financial account; Reserve assets; Reserve Position in the IMF"
cap label var FA__R__FR1 "Financial account; Reserve assets; Securities (Equity, investment fund shares/units and debt securities)"
cap label var FA__R__FR2 "Financial account; Reserve assets; Other reserve assets (currency, deposits, securities, financial derivatives and other claims)"
cap label var FA__R__FR41 "Financial account; Reserve assets; Other claims"
cap label var FA__R__F3 "Financial account; Reserve assets; Debt securities"
cap label var FA__R__F3__S "Financial account; Reserve assets; Debt securities; Short term"
cap label var FA__R__F3__L "Financial account; Reserve assets; Debt securities; Long term"
cap label var FA__R__F5 "Financial account; Reserve assets; Equity and investment fund shares/units"
cap label var FA__R__F71 "Financial account; Reserve assets; Financial derivatives"
cap label var EO "Net errors and omissions"
cap label var FA__T__F1 "Financial account; All functional categories; Monetary gold and SDRs"
cap label var FA__T__F2 "Financial account; All functional categories; Currency and deposits"
cap label var FA__T__F3 "Financial account; All functional categories; Debt securities"
cap label var FA__T__F4 "Financial account; All functional categories; Loans"
cap label var FA__T__F5 "Financial account; All functional categories; Equity and investment fund shares/units"
cap label var FA__T__F6 "Financial account; All functional categories; Insurance, pension and standardized guarantee schemes"
cap label var FA__T__F7 "Financial account; All functional categories; Financial derivatives and employee stock options"
cap label var FA__T__F8 "Financial account; All functional categories; Other accounts receivable/payable"
cap label var FA__TXR__F "Financial account excluding reserve assets"
cap label var FA__FNED "Net external debt"
cap label var FA__FGED "Gross external debt"
cap label var FA__NENDI "Net international investment position excluding non-defaultable instruments"
cap label var D4S__D1__F5 "Primary income: Direct Investment income attributable to equity and investment fund shareholders, Direct investor in direct investment enterprises"
cap label var D4S__D2__F5 "Primary income: Direct Investment income attributable to equity and investment fund shareholders, Direct investment enterprises in direct Investor (Reverse Investment)"
cap label var D4S__D3__F5 "Primary income: Direct Investment income attributable to equity and investment fund shareholders, between fellow enterprises"
cap label var FA__D__F51M "Financial account; Direct Investment; Equity; Unlisted shares and other equity"
cap label var FA__D__F3 "Financial account; Direct Investment; Debt securities"
cap label var FA__D__F4 "Financial account; Direct Investment; Loans"
cap label var FA__D__F81 "Financial account; Direct Investment; Trade credits and advances"
cap label var FA__D__FLF "Financial account; Direct Investment; Other debt instruments"
cap label var FA__P__F3__S__JPY "Financial account; Portfolio Investment; Debt securities; Short term; currency of denomination Japanese yen"
cap label var FA__P__F3__S__X5 "Financial account; Portfolio Investment; Debt securities; Short term; all currencies of denomination except EUR, USD and JPY"
cap label var FA__P__F3__L__JPY "Financial account; Portfolio Investment; Debt securities; Long term; currency of denomination Japanese yen"
cap label var FA__P__F3__L__X5 "Financial account; Portfolio Investment; Debt securities; Long term; all currencies of denomination except EUR, USD and JPY"
cap label var FA__TXF_R__F "Financial account excluding reserve assets and financial derivatives and employee stock options"
cap label var FA__TXF_R__F__EUR "Financial account excluding reserve assets and financial derivatives and employee stock options; currency of denomination Euro"
cap label var FA__TXF_R__F__USD "Financial account excluding reserve assets and financial derivatives and employee stock options; currency of denomination US dollar"
cap label var FA__TXF_R__F__JPY "Financial account excluding reserve assets and financial derivatives and employee stock options; currency of denomination Japanese yen"
cap label var FA__TXF_R__F__X5 "Financial account excluding reserve assets and financial derivatives and employee stock options; all currencies of denomination except Euro, US dollar and Japanese yen"
cap label var FA__O__F__EUR "Financial account; Other Investment; currency of denomination Euro"
cap label var FA__O__F__USD "Financial account; Other Investment; currency of denomination US dollar"
cap label var FA__O__F__JPY "Financial account; Other Investment; currency of denomination Japanese yen"
cap label var FA__O__F__X5 "Financial account; Other Investment; all currencies of denomination except Euro, US dollar and Japanese yen"
cap label var FA__O__F2__USD "Financial account; Other Investment; Currency and deposits; currency of denomination US dollar"
cap label var FA__O__F2__JPY "Financial account; Other Investment; Currency and deposits; currency of denomination Japanese yen"
cap label var FA__O__F2__X5 "Financial account; Other Investment; Currency and deposits; all currencies of denomination except Euro, US dollar and Japanese yen"
cap label var FA__O__F4__EUR "Financial account; Other Investment; Loans; currency of denomination Euro"
cap label var FA__O__F4__USD "Financial account; Other Investment; Loans; currency of denomination US dollar"
cap label var FA__O__F4__JPY "Financial account; Other Investment; Loans; currency of denomination Japanese yen"
cap label var FA__O__F4__X5 "Financial account; Other Investment; Loans; all currencies of denomination except Euro, US dollar and Japanese yen"
cap label var FA__O__F81__EUR "Financial account; Other Investment; Trade credits and advances; currency of denomination Euro"
cap label var FA__O__F81__USD "Financial account; Other Investment; Trade credits and advances; currency of denomination US dollar"
cap label var FA__O__F81__JPY "Financial account; Other Investment; Trade credits and advances; currency of denomination Japanese yen"
cap label var FA__O__F81__X5 "Financial account; Other Investment; Trade credits and advances; all currencies of denomination except Euro, US dollar and Japanese yen"
cap label var FA__F__F71 "Financial account; Financial derivatives"
cap label var FA__P__F5__EUR "Financial account; Portfolio Investment; Equity and investment fund shares/units; currency of denomination Euro"
cap label var FA__P__F5__USD "Financial account; Portfolio Investment; Equity and investment fund shares/units; currency of denomination US dollar"
