cap label var TOTAL "Total"
cap label var LT18P5 "Underweight"
cap label var _18P5_25 "Normal"
cap label var _25_30 "Overweight"
cap label var GE30 "Obese"
cap label var BMI_LT18P5 "Underweight"
cap label var BMI18P5_24 "Normal"
cap label var BMI_GE25 "Overweight"
cap label var BMI25_29 "Pre-obese"
cap label var BMI_GE30 "Obese"
cap label var BMI30_34 "Obese class I"
cap label var BMI35_39 "Obese class II"
cap label var BMI_GE40 "Obese class III"
