cap label var TOTAL "Total"
cap label var _0 "No children"
cap label var _1 "1 child"
cap label var GE1 "1 child or more"
cap label var _2 "2 children"
cap label var _3 "3 children"
cap label var GE3 "3 children or more"
cap label var _4 "4 children"
cap label var GE4 "4 children or more"
cap label var _5 "5 children"
cap label var GE5 "5 children or more"
cap label var _6 "6 children"
cap label var GE6 "6 children or more"
cap label var _7 "7 children"
cap label var GE7 "7 children or more"
cap label var _8 "8 children"
cap label var _9 "9 children"
cap label var _10 "10 children"
cap label var UNK "Unknown"
cap label var NRP "No response"
