cap label var TOTAL "Total"
cap label var D0_3 "From 0 to 3 days"
cap label var D_LT1 "Less than 1 day"
cap label var D1_3 "From 1 to 3 days"
cap label var D4_6 "From 4 to 6 days"
cap label var D_GE4 "4 days or over"
cap label var D7_13 "From 7 to 13 days"
cap label var D14_20 "From 14 to 20 days"
cap label var D14_29 "From 14 to 29 days"
cap label var D_GE14 "14 days or over"
cap label var D21_M1 "From 21 days to 1 month"
cap label var D_GE183_PI "Permanent incapacity or 183 days or over"
cap label var M1_3 "From 1 to 3 months"
cap label var M_GE1 "1 month or over"
cap label var M3_6 "From 3 to 6 months"
cap label var M_GE3 "3 months or over"
cap label var M_GE6 "6 months or over"
cap label var FAT "Fatal"
cap label var NSP "Not specified"
cap label var OTH "Other"
cap label var UNK "Unknown"
