cap label var TOTAL "Total"
cap label var VHIGH_MOD "Very high or moderate"
cap label var VHIGH "Very high"
cap label var HIGH "High"
cap label var FAIR "Fair"
cap label var MED "Medium"
cap label var MOD "Moderate"
cap label var SOME "Some"
cap label var LOW "Low"
cap label var NONE "None"
cap label var NAP "Not applicable"
cap label var UNK "Unknown"
