cap label var TOTAL "Total"
cap label var EM_GSD "Households making ends meet with great difficulty, with difficulty or with some difficulty"
cap label var EM_FVE "Households making ends meet fairly easily, easily or very easily"
cap label var EM_GD "Households making ends meet with great difficulty"
cap label var EM_D "Households making ends meet with difficulty"
cap label var EM_SD "Households making ends meet with some difficulty"
cap label var EM_FE "Households making ends meet fairly easily"
cap label var EM_E "Households making ends meet easily"
cap label var EM_VE "Households making ends meet very easily"
cap label var N_SAVE "Households that are unable to save regularly (i.e. normally no money left to save)"
cap label var SAVE "Households able to save regularly (i.e. normally some money left to save)"
cap label var N_WARM "Households that cannot afford keeping home adequately warm"
cap label var N_HOLI "Households that cannot afford paying for a week annual holiday away from home"
cap label var N_FURN "Households that cannot afford replacing any worn-out furniture"
cap label var N_CLOT "Households that cannot afford buying new rather than second hand clothes"
cap label var N_MEAT "Households that cannot afford eating meat or chicken or fish every second day"
cap label var N_FRIE "Households that cannot afford having friends for a drink or meal once a week"
cap label var MBN_GE1 "Households that cannot afford at least one out of the six basic necessities (see list)"
cap label var MBN_GE2 "Households that cannot afford at least two out of the six basic necessities (see list)"
