cap label var TOTAL "Total"
cap label var AC_A32 "Aerospatiale AS332"
cap label var AC_AT4 "Aerospatiale ATR 42 - all models"
cap label var AC_AT7 "Aerospatiale ATR 72 - all models"
cap label var AC_OAS "Other Aerospatiale models"
cap label var AC_300 "Airbus A300 - all models"
cap label var AC_310 "Airbus A310 - all models"
cap label var AC_318 "Airbus A318 - all models"
cap label var AC_319 "Airbus A319 - all models"
cap label var AC_320 "Airbus A320 - all models"
cap label var AC_321 "Airbus A321 - all models"
cap label var AC_330 "Airbus A330 - all models"
cap label var AC_340 "Airbus A340 - all models"
cap label var AC_380 "Airbus A380 - all models"
cap label var AC_OAB "Other Airbus models"
cap label var AC_AN3 "Antonov An-32"
cap label var AC_OAN "Other Antonov models"
cap label var AC_RJ1 "BAe-Avroliner RJ 100"
cap label var AC_RJ8 "BAe-Avroliner RJ 85"
cap label var AC_OAL "Other Avroliner models"
cap label var AC_B46 "BAe 146 - all models"
cap label var AC_OBA "Other BAe models"
cap label var AC_717 "Boeing 717 - all models"
cap label var AC_727 "Boeing 727 - all models"
cap label var AC_737 "Boeing 737 - all models"
cap label var AC_747 "Boeing 747 - all models"
cap label var AC_757 "Boeing 757 - all models"
cap label var AC_767 "Boeing 767 - all models"
cap label var AC_777 "Boeing 777 - all models"
cap label var AC_M11 "Boeing MD-11"
cap label var AC_M80 "Boeing MD-80"
cap label var AC_M81 "Boeing MD-81"
cap label var AC_M82 "Boeing MD-82"
cap label var AC_M83 "Boeing MD-83"
cap label var AC_M87 "Boeing MD-87"
cap label var AC_M88 "Boeing MD-88"
cap label var AC_M90 "Boeing MD-90"
cap label var AC_OBO "Other Boeing models"
cap label var AC_BN2 "Britten-Norman BN-2"
cap label var AC_OBN "Other Britten-Norman models"
cap label var AC_C60 "Canadair CL-600 regional jet - all models"
cap label var AC_OCA "Other Canadair models"
cap label var AC_DH8 "De Havilland Canada Dash 8 - all models"
cap label var AC_ODH "Other de Havilland models"
cap label var AC_DO3 "Dornier 328"
cap label var AC_ODO "Other Dornier models"
cap label var AC_DC1 "Douglas DC-10 - all models"
cap label var AC_DC8 "Douglas DC-8 - all models"
cap label var AC_DC9 "Douglas DC-9 - all models"
cap label var AC_ODG "Other Douglas models"
cap label var AC_E12 "Embraer 120"
cap label var AC_E13 "Embraer 135"
cap label var AC_E14 "Embraer 145"
cap label var AC_E17 "Embraer 170"
cap label var AC_OEM "Other Embraer models"
cap label var AC_F50 "Fokker 50"
cap label var AC_F70 "Fokker 70"
cap label var AC_F10 "Fokker 100"
cap label var AC_OFK "Other Fokker models"
cap label var AC_JJ "Jumbo jet"
cap label var AC_L10 "Lockheed L-1011 TriStar"
cap label var AC_OLO "Other Lockheed models"
cap label var AC_NJ "Narrow-body jet"
cap label var AC_RJ "Regional jet"
cap label var AC_RT "Regional turboprop"
cap label var AC_S20 "Saab 2000"
cap label var AC_S34 "Saab 340"
cap label var AC_OSA "Other Saab models"
cap label var AC_T13 "Tupolev Tu-134"
cap label var AC_T15 "Tupolev Tu-154"
cap label var AC_OUT "Other Tupolev models"
cap label var AC_WJ "Wide-body jet"
cap label var OTH "Other"
cap label var UNK "Unknown"
