cap label var TOTAL "Total"
cap label var WST_0 "Not specified"
cap label var WST_1 "Usual workstation or within the usual local unit of work"
cap label var WST_2 "Occasional or mobile workstation or in a journey on behalf of the employer"
cap label var WST_9 "Other workstation"
