cap label var ABORTRT "Abortion rate"
cap label var ABRATIO "Abortion ratio"
cap label var AGEMAR1 "Mean age at first marriage"
cap label var AGEMOTH "Mean age of women at childbirth"
cap label var AGEMOTH1 "Mean age of women at birth of first child"
cap label var AGEMOTH2 "Mean age of women at birth of second child"
cap label var AGEMOTH3 "Mean age of women at birth of third child"
cap label var AGEMOTH4_MAX "Mean age of women at birth of fourth and higher order child"
cap label var AVG "Average population - total"
cap label var BIRTH "Births"
cap label var CNMIGRAT "Net migration plus statistical adjustment"
cap label var CNMIGRATRT "Crude rate of net migration plus statistical adjustment"
cap label var DEATH "Deaths - total"
cap label var DEATHRATE "Age specific death rate (Mx)"
cap label var DEATHUN5 "Under 5 mortality rate (per 1000 live birth)"
cap label var DEATH_NR "Deaths - number"
cap label var DEPRATIO1 "Age dependency ratio, 1st variant (population 0 to 14 years and 65 years or over to population 15 to 64 years)"
cap label var DEPRATIO2 "Age dependency ratio, 2nd variant (population 0 to 19 years and 60 years or over to population 20 to 59 years)"
cap label var DEPRATIO3 "Age dependency ratio, 3rd variant (population 0 to 19 years and 65 years or over to population 20 to 64 years)"
cap label var DEPRATIO4 "Age dependency ratio, 4th variant (population 0 to 24 years and 65 years or over to population 25 to 64 years)"
cap label var DIV "Divorces"
cap label var DIVMARPCT "Divorces per 100 marriages"
cap label var DURMAR "Mean duration of marriage at divorce"
cap label var EMIGR "Emigration - total"
cap label var ENEOMORRT "Early neonatal mortality rate"
cap label var FAGEMAR1 "Mean age at first marriage - females"
cap label var FAVG "Average population - females"
cap label var FDEATH "Deaths - females"
cap label var FJAN "Population on 1 January - females"
cap label var FLBIRTH "Live births - females"
cap label var FLEXPEC "Life expectancy at birth - females"
cap label var FMAR1CUM "Total first marriage rate - females"
cap label var FMAR1PC "Proportion of first marriages - females"
cap label var FMEDAGEPOP "Median age of population - females"
cap label var GBIRTHRT "Crude birth rate"
cap label var GBIRTHRT_THSP "Crude birth rate - per thousand persons"
cap label var GDEATHRT "Crude death rate"
cap label var GDEATHRT_THSP "Crude death rate - per thousand persons"
cap label var GDIVRT "Crude divorce rate"
cap label var GNUPRT "Crude marriage rate"
cap label var GREPRT "Gross reproduction rate"
cap label var GROW "Total population change"
cap label var GROWRT "Crude rate of total population change"
cap label var IMMIGR "Immigration - total"
cap label var INFMOR "Infant mortality"
cap label var INFMORRT "Infant mortality rate"
cap label var INTL_MIG "International migration"
cap label var INTRG_MIG "Interregional migration"
cap label var JAN "Population on 1 January - total"
cap label var LBIRTH "Live births - total"
cap label var LBIRTHOUT "Births outside marriage"
cap label var LBIRTHR1PC "Percentage first order live births"
cap label var LBIRTHR2PC "Percentage second order live births"
cap label var LBIRTHR3PC "Percentage third order live births"
cap label var LBIRTHR4_MAXPC "Percentage fourth and higher order live births"
cap label var LBIRTH_NR "Live births - number"
cap label var LEXPEC "Life expectancy at birth"
cap label var LFOEMORRT "Late foetal mortality rate"
cap label var LIFEXP "Life expectancy at given exact age (ex)"
cap label var LIFEXP_R "Life expectancy at age x (ex)"
cap label var MAGEMAR1 "Mean age at first marriage - males"
cap label var MAR "In marriage"
cap label var MARRIAGE "Marriages"
cap label var MAVG "Average population - males"
cap label var MDEATH "Deaths - males"
cap label var MEDAGEMOTH "Median age of women at childbirth"
cap label var MEDAGEPOP "Median age of population"
cap label var MEDDURMAR "Median durantion of marriage at divorce"
cap label var MIGT "Sum of immigration and emigration plus statistical adjustment (migration turnover plus statistical adjustment)"
cap label var MIGTRT "Crude rate of the sum of immigration and emigration plus statistical adjustment (Crude Rate of migration turnover plus statistical adjustment)"
cap label var MJAN "Population on 1 January - males"
cap label var MLBIRTH "Live births - males"
cap label var MLEXPEC "Life expectancy at birth - males"
cap label var MMAR1CUM "Total first marriage rate - males"
cap label var MMAR1PC "Proportion of first marriages - males"
cap label var MMEDAGEPOP "Median age of population - males"
cap label var NATGROW "Natural change of population"
cap label var NATGROWRT "Crude rate of natural change of population"
cap label var NATT "Sum of births and deaths (natural turnover)"
cap label var NATTRT "Crude rate of sum of births and deaths (crude rate of natural turnover); "
cap label var NEOMORRT "Neonatal mortality rate"
cap label var NMAR "Outside marriage"
cap label var NMARPCT "Proportion of live births outside marriage"
cap label var NMIGRAT "Net migration - total"
cap label var NREPRT "Net reproduction rate"
cap label var NUMBERDYING "Number dying between exact ages (dx)"
cap label var NUMBERDYING_R "Number dying aged x (dx)"
cap label var OLDDEP1 "Old-age dependency ratio 1st variant (population 65 years or over to population 15 to 64 years)"
cap label var OLDDEP2 "Old-age dependency ratio 2nd variant (population 60 years or over to population 20 to 59 years)"
cap label var OLDDEP3 "Old-age dependency ratio 3rd variant (population 65 years or over to population 20 to 64 years)"
cap label var OLDDEP4 "Old-age dependency ratio 4th variant (population 65 years or over to population 25 to 64 years)"
cap label var PC_FM "Women per 100 men"
cap label var PC_Y0_14 "Proportion of population aged 0-14 years"
cap label var PC_Y0_17 "Proportion of population aged 0-17 years"
cap label var PC_Y0_19 "Proportion of population aged 0-19 years"
cap label var PC_Y0_24 "Proportion of population aged 0-24 years"
cap label var PC_Y0_4 "Proportion of population aged 0-4 years"
cap label var PC_Y10_14 "Proportion of population aged 10-14 years"
cap label var PC_Y15_19 "Proportion of population aged 15-19 years"
cap label var PC_Y15_24 "Proportion of population aged 15-24 years"
cap label var PC_Y15_64 "Proportion of population aged 15-64 years"
cap label var PC_Y15_74 "Proportion of population aged 15-74 years"
cap label var PC_Y20_24 "Proportion of population aged 20-24 years"
cap label var PC_Y20_39 "Proportion of population aged 20-39 years"
cap label var PC_Y20_64 "Proportion of population aged 20-64 years"
cap label var PC_Y24_64 "Proportion of population aged 24-64 years"
cap label var PC_Y25_29 "Proportion of population aged 25-29 years"
cap label var PC_Y25_44 "Proportion of population aged 25-44 years"
cap label var PC_Y25_49 "Proportion of population aged 25-49 years"
cap label var PC_Y30_34 "Proportion of population aged 30-34 years"
cap label var PC_Y35_39 "Proportion of population aged 35-39 years"
cap label var PC_Y40_44 "Proportion of population aged 40-44 years"
cap label var PC_Y40_59 "Proportion of population aged 40-59 years"
cap label var PC_Y45_49 "Proportion of population aged 45-49 years"
cap label var PC_Y45_64 "Proportion of population aged 45-64 years"
cap label var PC_Y50_54 "Proportion of population aged 50-54 years"
cap label var PC_Y50_64 "Proportion of population aged 50-64 years"
cap label var PC_Y55_59 "Proportion of population aged 55-59 years"
cap label var PC_Y5_9 "Proportion of population aged 5-9 years"
cap label var PC_Y60_64 "Proportion of population aged 60-64 years"
cap label var PC_Y60_79 "Proportion of population aged 60-79 years"
cap label var PC_Y60_MAX "Proportion of population aged 60 years and more"
cap label var PC_Y65_69 "Proportion of population aged 65-69 years"
cap label var PC_Y65_79 "Proportion of population aged 65-79 years"
cap label var PC_Y65_MAX "Proportion of population aged 65 years and more"
cap label var PC_Y70_74 "Proportion of population aged 70-74 years"
cap label var PC_Y75_79 "Proportion of population aged 75-79 years"
cap label var PC_Y80_84 "Proportion of population aged 80-84 years"
cap label var PC_Y80_MAX "Proportion of population aged 80 years and more"
cap label var PC_Y85_MAX "Proportion of population aged 85 years and more"
cap label var PERIMORRT "Perinatal mortality rate"
cap label var POP_Y15_74 "Population aged 15-74 years"
cap label var POPSHARE "Population as a percentage of EU28 (2013-2020) population"
cap label var POPSHARE_EU27_2020 "Population as a percentage of EU27 (from 2020) population"
cap label var POPT "Sum of population changes (population turnover)"
cap label var POPTRT "Crude rate of sum of population changes(crude rate of population turnover)"
cap label var PROBDEATH "Probability of dying between exact ages (qx)"
cap label var PROBDEATH_R "Probability of dying at age x (qx)"
cap label var PROBSURV "Probability of surviving between exact ages (px)"
cap label var PROBSURV_R "Probability of surviving at age x (px)"
cap label var PYLIVED "Person-years lived between exact age (Lx)"
cap label var PYLIVED_R "Person-years lived above age x (Lx)"
cap label var SURVIVORS "Number left alive at given exact age (lx)"
cap label var SURVIVORS_R "Number of survivors aged x (lx)"
cap label var TOTDIVRT "Total divorce rate"
cap label var TOTFERRT "Total fertility rate"
cap label var TOTPYLIVED "Total person-years lived above given exact age (Tx)"
cap label var TOTPYLIVED_R "Total person-years lived above age x (Tx)"
cap label var UNK "Unknown"
cap label var YOUNGDEP1 "Young-age dependency ratio 1st variant (population 0 to 14 years to population 15 to 64 years)"
cap label var YOUNGDEP2 "Young-age dependency ratio 2nd variant (population 0 to 19 years to population 20 to 59 years)"
cap label var YOUNGDEP3 "Young-age dependency ratio 3rd variant (population 0 to 19 years to population 20 to 64 years)"
cap label var YOUNGDEP4 "Young-age dependency ratio 4th variant (population 0 to 24 years to population 25 to 64 years)"
