cap label var TOTAL "Total environmental protection and resource management activities"
cap label var TOT_CEPA "Total environmental protection activities"
cap label var CEPA1_3 "Protection of ambient air and climate; wastewater management; waste management"
cap label var CEPA1_4_5_7 "Protection of ambient air and climate; protection and remediation of soil, groundwater and surface water; noise and vibration abatement; protection against radiation"
cap label var CEPA1_4_9 "Protection of ambient air and climate; protection and remediation of soil, groundwater and surface water; noise and vibration abatement; protection of biodiversity and landscapes; protection against radiation; environmental research and development; other environmental protection activities"
cap label var CEPA1 "Protection of ambient air and climate"
cap label var CEPA112_122 "Protection of climate and ozone layer"
cap label var CEPA2 "Wastewater management"
cap label var CEPA3 "Waste management"
cap label var CEPA4_9 "Protection and remediation of soil, groundwater and surface water; noise and vibration abatement; protection of biodiversity and landscapes; protection against radiation; environmental research and development; other environmental protection activities"
cap label var CEPA4 "Protection and remediation of soil, groundwater and surface water"
cap label var CEPA5 "Noise and vibration abatement (excluding workplace protection)"
cap label var CEPA6 "Protection of biodiversity and landscapes"
cap label var CEPA7_9 "Protection against radiation; environmental research and development; other environmental protection activities"
cap label var CEPA7 "Protection against radiation (excluding external safety)"
cap label var CEPA8_9 "Environmental research and development; other environmental protection activities"
cap label var CEPA8 "Environmental research and development"
cap label var CEPA812 "Environmental research and development for the protection of atmosphere and climate"
cap label var CEPA9 "Other environmental protection activities"
cap label var TOT_CREMA "Total resource management activities"
cap label var CREMA10 "Management of waters"
cap label var CREMA11_12 "Management of forest resources; management of wild flora and fauna"
cap label var CREMA11 "Management of forest resources"
cap label var CREMA11A "Management of forest areas"
cap label var CREMA11B_13C_14 "Minimisation of the intake of forest resources; minimisation of the use of fossil energy as raw materials; management of minerals"
cap label var CREMA11B "Minimisation of the intake of forest resources"
cap label var CREMA12 "Management of wild flora and fauna"
cap label var CREMA13 "Management of energy resources"
cap label var CREMA13A "Production of energy from renewable sources"
cap label var CREMA13B "Heat/energy saving and management"
cap label var CREMA13C "Minimisation of the use of fossil energy as raw materials"
cap label var CREMA14 "Management of minerals"
cap label var CREMA15_16 "Research and development activities for resource management; other resource management activities"
cap label var CREMA15 "Research and development activities for resource management"
cap label var CREMA15A "Research and development activities for the production of energy from renewable sources"
cap label var CREMA16 "Other resource management activities"
cap label var CREMA12_15_16 "Management of wild flora and fauna; research and development activities for resource management; other resource management activities"
