cap label var TOTAL "Total"
cap label var _0 "No items"
cap label var _1 "1 item"
cap label var LT2 "Fewer than 2 items"
cap label var _2 "2 items"
cap label var LT3 "Fewer than 3 items"
cap label var _3 "3 items"
cap label var GE3 "3 items or more"
cap label var LT4 "Fewer than 4 items"
cap label var _4 "4 items"
cap label var GE4 "4 items or more"
cap label var LT5 "Fewer than 5 items"
cap label var _5 "5 items"
cap label var GE5 "5 items or more"
cap label var _6 "6 items"
cap label var _7 "7 items"
cap label var _8 "8 items"
cap label var _9 "9 items"
cap label var _10 "10 items"
cap label var _11 "11 items"
cap label var _12 "12 items"
cap label var _13 "13 items"
cap label var LT13 "Fewer than 13 items"
