cap label var TOTAL "Total"
cap label var MER "Merchant ship"
cap label var MER_NF "Merchant ship under national flag"
cap label var MER_FF "Merchant ship under foreign flag belonging to a resident company"
cap label var LBK "Liquid bulk tanker"
cap label var LBK_OIL "Oil tanker"
cap label var LBK_CHM "Chemical tanker"
cap label var LBK_LGAS "Liquefied gas tanker"
cap label var LBK_TB "Tanker barge"
cap label var LBK_OTH "Other tanker"
cap label var DBK "Dry bulk carrier"
cap label var DBK_OIL "Bulk/oil carrier"
cap label var DBK_BC "Bulk carrier"
cap label var ODC "Other dry cargo"
cap label var ODC_CNT "Container ship"
cap label var ODC_SPE "Specialised carrier"
cap label var ODC_GEN "General cargo, non-specialised"
cap label var ODC_PRO "Passenger and Ro-ro passenger ship"
cap label var ODC_RO "Ro-ro cargo"
cap label var ODC_DCB "Dry cargo barge"
cap label var ODC_PAS "Passenger ship"
cap label var ODC_PCRU "Cruise ship"
cap label var ODC_PAS_XCR "Passenger ship (excluding cruise ship)"
cap label var MSC "Miscellaneous type of vessel"
cap label var MSC_FISH "Fishing vessel"
cap label var MSC_OFF "Offshore activities vessel"
cap label var MSC_TOW "Tug and pusher craft"
cap label var MSC_OTH "Other type of vessel (dredger, research vessel, other)"
cap label var BAR_SP "Self-propelled barge"
cap label var BAR_NSP "Not self-propelled barge"
cap label var BAR_SPT "Self-propelled tanker barge"
cap label var BAR_NSPT "Not self-propelled tanker barge"
cap label var SEA "Seagoing vessel"
cap label var TUG_PUSH "Tug and pusher"
cap label var DUM_PUSV "Dumb and pushed vessel"
cap label var OTH_GD "Other goods carrying vessel"
cap label var CARGO "Cargo ship"
cap label var IWW "Inland waterway vessel"
cap label var NAVY "Navy ship"
cap label var REC "Recreational craft"
cap label var SERV "Service ship"
cap label var OTH "Other vessel"
cap label var UNK "Unknown"
