cap label var TOTAL "Total"
cap label var ISCO1_5 "Non manual workers"
cap label var ISCO1_3 "Managers, professionals, technicians and associate professionals"
cap label var ISCO1_2 "Managers and professionals"
cap label var ISCO1 "Legislators, senior officials and managers"
cap label var ISCO11 "Legislators and senior officials"
cap label var ISCO111 "Legislators"
cap label var ISCO112 "Senior government officials"
cap label var ISCO113 "Traditional chiefs and heads of villages"
cap label var ISCO114 "Senior officials of special-interest organisations"
cap label var ISCO12 "Corporate managers"
cap label var ISCO121 "Directors and chief executives"
cap label var ISCO122 "Production and operations department managers"
cap label var ISCO123 "Other specialist managers"
cap label var ISCO13 "General managers"
cap label var ISCO131 "General managers"
cap label var ISCO2 "Professionals"
cap label var ISCO21 "Physical, mathematical and engineering science professionals"
cap label var ISCO211 "Physicists, chemists and related professionals"
cap label var ISCO212 "Mathematicians, statisticians and related professionals"
cap label var ISCO213 "Computing professionals"
cap label var ISCO214 "Architects, engineers and related professionals"
cap label var ISCO22 "Life science and health professionals"
cap label var ISCO221 "Life science professionals"
cap label var ISCO222 "Health professionals (except nursing)"
cap label var ISCO223 "Nursing and midwifery professionals"
cap label var ISCO23 "Teaching professionals"
cap label var ISCO231 "College, university and higher education teaching professionals"
cap label var ISCO232 "Secondary education teaching professionals"
cap label var ISCO233 "Primary and pre-primary education teaching professionals"
cap label var ISCO234 "Special education teaching professionals"
cap label var ISCO235 "Other teaching professionals"
cap label var ISCO24 "Other professionals"
cap label var ISCO241 "Business professionals"
cap label var ISCO242 "Legal professionals"
cap label var ISCO243 "Archivists, librarians and related information professionals"
cap label var ISCO244 "Social science and related professionals"
cap label var ISCO245 "Writers and creative or performing artists"
cap label var ISCO246 "Religious professionals"
cap label var ISCO247 "Scientific administration employees"
cap label var ISCO3 "Technicians and associate professionals"
cap label var ISCO31 "Physical and engineering science associate professionals"
cap label var ISCO311 "Physical and engineering science technicians"
cap label var ISCO312 "Computer associate professionals"
cap label var ISCO313 "Optical and electronic equipment operators"
cap label var ISCO314 "Ship and aircraft controllers and technicians"
cap label var ISCO315 "Safety and quality inspectors"
cap label var ISCO32 "Life science and health associate professionals"
cap label var ISCO321 "Life science technicians and related associate professionals"
cap label var ISCO322 "Health associate professionals (except nursing)"
cap label var ISCO323 "Nursing and midwifery associate professionals"
cap label var ISCO324 "Traditional medicine practitioners and faith healers"
cap label var ISCO33 "Teaching associate professionals"
cap label var ISCO331 "Primary education teaching associate professionals"
cap label var ISCO332 "Pre-primary education teaching associate professionals"
cap label var ISCO333 "Special education teaching associate professionals"
cap label var ISCO334 "Other teaching associate professionals"
cap label var ISCO34 "Other associate professionals"
cap label var ISCO341 "Finance and sales associate professionals"
cap label var ISCO342 "Business services agents and trade brokers"
cap label var ISCO343 "Administrative associate professionals"
cap label var ISCO344 "Customs, tax and related government associate professionals"
cap label var ISCO345 "Police inspectors and detectives"
cap label var ISCO346 "Social work associate professionals"
cap label var ISCO347 "Artistic, entertainment and sports associate professionals"
cap label var ISCO348 "Religious associate professionals"
cap label var ISCO4_5 "Clerks and sales"
cap label var ISCO4 "Clerks"
cap label var ISCO41 "Office clerks"
cap label var ISCO411 "Secretaries and keyboard-operating clerks"
cap label var ISCO412 "Numerical clerks"
cap label var ISCO413 "Material-recording and transport clerks"
cap label var ISCO414 "Library, mail and related clerks"
cap label var ISCO419 "Other office clerks"
cap label var ISCO42 "Customer services clerks"
cap label var ISCO421 "Cashiers, tellers and related clerks"
cap label var ISCO422 "Client information clerks"
cap label var ISCO5 "Service workers and shop and market sales workers"
cap label var ISCO51 "Personal and protective services workers"
cap label var ISCO511 "Travel attendants and related workers"
cap label var ISCO512 "Housekeeping and restaurant services workers"
cap label var ISCO513 "Personal care and related workers"
cap label var ISCO514 "Other personal services workers"
cap label var ISCO515 "Astrologers, fortune-tellers and related workers"
cap label var ISCO516 "Protective services workers"
cap label var ISCO52 "Models, salespersons and demonstrators"
cap label var ISCO521 "Fashion and other models"
cap label var ISCO522 "Shop, stall and market salespersons and demonstrators"
cap label var ISCO523 "Stall and market salespersons"
cap label var ISCO6_8 "Skilled manual workers"
cap label var ISCO6_7 "Skilled agricultural and fishery workers, craft and related trades workers"
cap label var ISCO6 "Skilled agricultural and fishery workers"
cap label var ISCO61 "Market-oriented skilled agricultural and fishery workers"
cap label var ISCO611 "Market gardeners and crop growers"
cap label var ISCO612 "Market-oriented animal producers and related workers"
cap label var ISCO613 "Market-oriented crop and animal producers"
cap label var ISCO614 "Forestry and related workers"
cap label var ISCO615 "Fishery workers, hunters and trappers"
cap label var ISCO62 "Subsistence agricultural and fishery workers"
cap label var ISCO621 "Subsistence agricultural and fishery workers"
cap label var ISCO7_9 "Manual workers"
cap label var ISCO7 "Craft and related trades workers"
cap label var ISCO71 "Extraction and building trades workers"
cap label var ISCO711 "Miners, shotfirers, stone cutters and carvers"
cap label var ISCO712 "Building frame and related trades workers"
cap label var ISCO713 "Building finishers and related trades workers"
cap label var ISCO714 "Painters, building structure cleaners and related trades workers"
cap label var ISCO72 "Metal, machinery and related trades workers"
cap label var ISCO721 "Metal moulders, welders, sheet-metal workers, structural-metal preparers, and related trades workers"
cap label var ISCO722 "Blacksmiths, tool-makers and related trades workers"
cap label var ISCO723 "Machinery mechanics and fitters"
cap label var ISCO724 "Electrical and electronic equipment mechanics and fitters"
cap label var ISCO73 "Precision, handicraft, craft printing and related trades workers"
cap label var ISCO731 "Precision workers in metal and related materials"
cap label var ISCO732 "Potters, glass-makers and related trades workers"
cap label var ISCO733 "Handicraft workers in wood, textile, leather and related materials"
cap label var ISCO734 "Printing and related trades workers"
cap label var ISCO74 "Other craft and related trades workers"
cap label var ISCO741 "Food processing and related trades workers"
cap label var ISCO742 "Wood treaters, cabinet-makers and related trades workers"
cap label var ISCO743 "Textile, garment and related trades workers"
cap label var ISCO744 "Pelt, leather and shoemaking trades workers"
cap label var ISCO8_9 "Plant and machine operators and assemblers and elementary occupations"
cap label var ISCO8 "Plant and machine operators and assemblers"
cap label var ISCO81 "Stationary plant and related operators"
cap label var ISCO811 "Mining and mineral-processing-plant operators"
cap label var ISCO812 "Metal-processing plant operators"
cap label var ISCO813 "Glass, ceramics and related plant operators"
cap label var ISCO814 "Wood-processing- and papermaking-plant operators"
cap label var ISCO815 "Chemical-processing-plant operators"
cap label var ISCO816 "Power-production and related plant operators"
cap label var ISCO817 "Automated-assembly-line and industrial-robot operators"
cap label var ISCO82 "Machine operators and assemblers"
cap label var ISCO821 "Metal- and mineral-products machine operators"
cap label var ISCO822 "Chemical-products machine operators"
cap label var ISCO823 "Rubber- and plastic-products machine operators"
cap label var ISCO824 "Wood-products machine operators"
cap label var ISCO825 "Printing-, binding- and paper-products machine operators"
cap label var ISCO826 "Textile-, fur- and leather-products machine operators"
cap label var ISCO827 "Food and related products machine operators"
cap label var ISCO828 "Assemblers"
cap label var ISCO829 "Other machine operators and assemblers"
cap label var ISCO83 "Drivers and mobile plant operators"
cap label var ISCO831 "Locomotive engine drivers and related workers"
cap label var ISCO832 "Motor-vehicle drivers"
cap label var ISCO833 "Agricultural and other mobile-plant operators"
cap label var ISCO834 "Ships' deck crews and related workers"
cap label var ISCO9 "Elementary occupations"
cap label var ISCO91 "Sales and services elementary occupations"
cap label var ISCO911 "Street vendors and related workers"
cap label var ISCO912 "Shoe cleaning and other street services elementary occupations"
cap label var ISCO913 "Domestic and related helpers, cleaners and launderers"
cap label var ISCO914 "Building caretakers, window and related cleaners"
cap label var ISCO915 "Messengers, porters, doorkeepers and related workers"
cap label var ISCO916 "Garbage collectors and related labourers"
cap label var ISCO92 "Agricultural, fishery and related labourers"
cap label var ISCO921 "Agricultural, fishery and related labourers"
cap label var ISCO93 "Labourers in mining, construction, manufacturing and transport"
cap label var ISCO931 "Mining and construction labourers"
cap label var ISCO932 "Manufacturing labourers"
cap label var ISCO933 "Transport labourers and freight handlers"
cap label var ISCO0 "Armed forces"
cap label var ISCO0_4_9 "Not managers, professionals, technicians and associate professionals (ISCO1-3)"
cap label var OTH "Other occupations"
cap label var NRP "No response"
cap label var UNK "Unknown"
