cap label var TOTAL "All providers of health care"
cap label var HP1 "Hospitals"
cap label var HP11 "General hospitals"
cap label var HP12 "Mental health hospitals"
cap label var HP13 "Specialised hospitals (other than mental health hospitals)"
cap label var HP2 "Residential long-term care facilities"
cap label var HP21 "Long-term nursing care facilities"
cap label var HP22 "Mental health and substance abuse facilities"
cap label var HP29 "Other residential long-term care facilities"
cap label var HP3 "Providers of ambulatory health care"
cap label var HP31 "Medical practices"
cap label var HP32 "Dental practice"
cap label var HP33 "Other health care practitioners"
cap label var HP34 "Ambulatory health care centres"
cap label var HP35 "Providers of home health care services"
cap label var HP4 "Providers of ancillary services"
cap label var HP41 "Providers of patient transportation and emergency rescue"
cap label var HP42 "Medical and diagnostic laboratories"
cap label var HP49 "Other providers of ancillary services"
cap label var HP5 "Retailers and other providers of medical goods"
cap label var HP51 "Pharmacies"
cap label var HP52 "Retail sellers and other suppliers of durable medical goods and medical appliances"
cap label var HP59 "All other miscellaneous sellers and other suppliers of pharmaceuticals and medical goods"
cap label var HP6 "Providers of preventive care"
cap label var HP7 "Providers of health care system administration and financing"
cap label var HP71 "Government health administration agencies"
cap label var HP72 "Social health insurance agencies"
cap label var HP73 "Private health insurance administration agencies"
cap label var HP79 "Other administration agencies"
cap label var HP8 "Rest of economy"
cap label var HP81 "Households as providers of home health care"
cap label var HP82 "All other industries as secondary providers of health care"
cap label var HP89 "Other industries n.e.c."
cap label var HP9 "Rest of the world"
cap label var HP_UNK "Providers unknown"
