cap label var HOLD "Vineyard holdings"
cap label var AAU "Agricultural area in use of vineyard holdings (ha)"
cap label var VITAR "Area under vines (ha)"
cap label var WGVHOLD "Holdings with wine-grape vine varieties"
cap label var WGVAREA "Cultivated area under wine-grape vine varieties (ha)"
cap label var QWAREA "Cultivated area under wine-grape vine varieties for the production of quality wines psr (ha)"
cap label var GRUB "Grubbed"
cap label var PLTED "Planted (new plantings)"
cap label var REPLTED "Replanted"
