cap label var IPC "International patent classification (IPC) - total"
cap label var A "Section A - Human necessities"
cap label var A01 "Agriculture; forestry; animal husbandry; hunting; trapping; fishing"
cap label var A21 "Baking; equipment for making or processing doughs; doughs for baking"
cap label var A22 "Butchering; meat treatment; processing poultry or fish"
cap label var A23 "Foods or foodstuffs; their treatment, not covered by other classes"
cap label var A24 "Tobacco; cigars; cigarettes; smokers' requisites"
cap label var A41 "Wearing apparel"
cap label var A42 "Headwear"
cap label var A43 "Footwear"
cap label var A44 "Haberdashery; jewellery"
cap label var A45 "Hand or travelling articles"
cap label var A46 "Brushware"
cap label var A47 "Furniture; domestic articles or appliances; coffee mills; spice mills; suction cleaners in general"
cap label var A61 "Medical or veterinary science; hygiene"
cap label var A62 "Life-saving; fire-fighting"
cap label var A63 "Sports; games; amusements"
cap label var B "Section B - Performing operations; transporting"
cap label var B01 "Physical or chemical processes or apparatus in general"
cap label var B02 "Crushing, pulverising, or disintegrating; preparatory treatment of grain for milling"
cap label var B03 "Separation of solid materials using liquids or using pneumatic tables or jigs; magnetic or electrostatic separation of solid materials from solid materials or fluids; separation by high-voltage electric fields"
cap label var B04 "Centrifugal apparatus or machines for carrying-out physical or chemical processes"
cap label var B05 "Spraying or atomising in general; applying liquids or other fluent materials to surfaces, in general"
cap label var B06 "Generating or transmitting mechanical vibrations in general"
cap label var B07 "Separating solids from solids; sorting"
cap label var B08 "Cleaning"
cap label var B09 "Disposal of solid waste; reclamation of contaminated soil"
cap label var B21 "Mechanical metal-working without essentially removing material; punching metal"
cap label var B22 "Casting; powder metallurgy"
cap label var B23 "Machine tools; metal-working not otherwise provided for"
cap label var B24 "Grinding; polishing"
cap label var B25 "Hand tools; portable power-driven tools; handles for hand implements; workshop equipment; manipulators"
cap label var B26 "Hand cutting tools; cutting; severing"
cap label var B27 "Working or preserving wood or similar material; nailing or stapling machines in general"
cap label var B28 "Working cement, clay, or stone"
cap label var B29 "Working of plastics; working of substances in a plastic state in general"
cap label var B30 "Presses"
cap label var B31 "Making paper articles; working paper"
cap label var B32 "Layered products"
cap label var B41 "Printing; lining machines; typewriters; stamps"
cap label var B42 "Bookbinding; albums; files; special printed matter"
cap label var B43 "Writing or drawing implements; bureau accessories"
cap label var B44 "Decorative arts"
cap label var B60 "Vehicles in general"
cap label var B61 "Railways"
cap label var B62 "Land vehicles for travelling otherwise than on rails"
cap label var B63 "Ships or other waterborne vessels; related equipment"
cap label var B64 "Aircraft; aviation; cosmonautics"
cap label var B65 "Conveying; packing; storing; handling thin or filamentary material"
cap label var B66 "Hoisting; lifting; hauling"
cap label var B67 "Opening or closing bottles, jars or similar containers; liquid handling"
cap label var B68 "Saddlery; upholstery"
cap label var B81 "Micro-structural technology"
cap label var B82 "Nanotechnology"
cap label var B82Y "Nanotechnology - Specific uses or applications of nano-structures"
cap label var B82Y5 "Nanobiotechnology or nano-medicine"
cap label var B82Y10 "Nanotechnology for information processing, storage and transmission"
cap label var B82Y15 "Nanotechnology for interacting, sensing or actuating"
cap label var B82Y20 "Nanotechnology for optics"
cap label var B82Y25 "Nanomagnetism"
cap label var B82Y30 "Nanotechnology for materials and surface science"
cap label var B82Y35 "Methods or apparatus for measurement or analysis of nanostructures"
cap label var B82Y40 "Manufacture or treatment of nanostructures"
cap label var B82Y99 "Subject matter not provided for in other groups of this subclass"
cap label var C "Section C - Chemistry; metallurgy"
cap label var C01 "Inorganic chemistry"
cap label var C02 "Treatment of water, waste water, sewage, or sludge"
cap label var C03 "Glass; mineral or slag wool"
cap label var C04 "Cements; concrete; artificial stone; ceramics; refractories"
cap label var C05 "Fertilisers; manufacture thereof"
cap label var C06 "Explosives; matches"
cap label var C07 "Organic chemistry"
cap label var C08 "Organic macromolecular compounds; their preparation or chemical working-up; compositions based thereon"
cap label var C09 "Dyes; paints; polishes; natural resins; adhesives; compositions not otherwise provided for; applications of materials not otherwise provided for"
cap label var C10 "Petroleum, gas or coke industries; technical gases containing carbon monoxide; fuels; lubricants; peat"
cap label var C11 "Animal or vegetable oils, fats, fatty substances or waxes; fatty acids therefrom; detergents; candles"
cap label var C12 "Biochemistry; beer; spirits; wine; vinegar; microbiology; enzymology; mutation or genetic engineering"
cap label var C13 "Sugar industry"
cap label var C14 "Skins; hides; pelts; leather"
cap label var C21 "Metallurgy of iron"
cap label var C22 "Metallurgy; ferrous or non-ferrous alloys; treatment of alloys or non-ferrous metals"
cap label var C23 "Coating metallic material; coating material with metallic material; chemical surface treatment; diffusion treatment of metallic material; coating by vacuum evaporation, by sputtering, by ion implantation or by chemical vapour deposition, in general; inhibiting corrosion of metallic material or incrustation in general"
cap label var C25 "Electrolytic or electrophoretic processes; apparatus therefor"
cap label var C30 "Crystal growth"
cap label var C40 "Combinatorial technology"
cap label var C99 "Section C Other - Chemistry; metallurgy"
cap label var D "Section D - Textiles; paper"
cap label var D01 "Natural or artificial threads or fibres; spinning"
cap label var D02 "Yarns; mechanical finishing of yarns or ropes; warping or beaming"
cap label var D03 "Weaving"
cap label var D04 "Braiding; lace-making; knitting; trimmings; non-woven fabrics"
cap label var D05 "Sewing; embroidering; tufting"
cap label var D06 "Treatment of textiles or the like; laundering; flexible materials not otherwise provided for"
cap label var D07 "Ropes; cables other than electric"
cap label var D21 "Paper-making; production of cellulose"
cap label var E "Section E - Fixed constructions"
cap label var E01 "Construction of roads, railways, or bridges"
cap label var E02 "Hydraulic engineering; foundations; soil-shifting"
cap label var E03 "Water supply; sewerage"
cap label var E04 "Building"
cap label var E05 "Locks; keys; window or door fittings; safes"
cap label var E06 "Doors, windows, shutters, or roller blinds, in general; ladders"
cap label var E21 "Earth or rock drilling; mining"
cap label var F "Section F - Mechanical engineering; lighting; heating; weapons; blasting"
cap label var F01 "Machines or engines in general; engine plants in general; steam engines"
cap label var F02 "Combustion engines; hot-gas or combustion-product engine plants"
cap label var F03 "Machines or engines for liquids; wind, spring, or weight motors; producing mechanical power or a reactive propulsive thrust, not otherwise provided for"
cap label var F04 "Positive-displacement machines for liquids; pumps for liquids or elastic fluids"
cap label var F15 "Fluid-pressure actuators; hydraulics or pneumatics in general"
cap label var F16 "Engineering elements or units; general measures for producing and maintaining effective functioning of machines or installations; thermal insulation in general"
cap label var F17 "Storing or distributing gases or liquids"
cap label var F21 "Lighting"
cap label var F22 "Steam generation"
cap label var F23 "Combustion apparatus; combustion processes"
cap label var F24 "Heating; ranges; ventilating"
cap label var F25 "Refrigeration or cooling; combined heating and refrigeration systems; heat pump systems; manufacture or storage of ice; liquefaction or solidification of gases"
cap label var F26 "Drying"
cap label var F27 "Furnaces; kilns; ovens; retorts"
cap label var F28 "Heat exchange in general"
cap label var F41 "Weapons"
cap label var F42 "Ammunition; blasting"
cap label var G "Section G - Physics"
cap label var G01 "Measuring; testing"
cap label var G02 "Optics"
cap label var G03 "Photography; cinematography; analogous techniques using waves other than optical waves; electrography; holography"
cap label var G04 "Horology"
cap label var G05 "Controlling; regulating"
cap label var G06 "Computing; calculating; counting"
cap label var G07 "Checking-devices"
cap label var G08 "Signalling"
cap label var G09 "Educating; cryptography; display; advertising; seals"
cap label var G10 "Musical instruments; acoustics"
cap label var G11 "Information storage"
cap label var G12 "Instrument details"
cap label var G21 "Nuclear physics; nuclear engineering"
cap label var G99 "Section G Other - Physics"
cap label var H "Section H - Electricity"
cap label var H01 "Basic electric elements"
cap label var H02 "Generation, conversion, or distribution of electric power"
cap label var H03 "Basic electronic circuitry"
cap label var H04 "Electric communication technique"
cap label var H05 "Electric techniques not otherwise provided for"
cap label var HT "High tech - total"
cap label var AVI "Aviation"
cap label var CAB "Computer and automated business equipment"
cap label var CTE "Communication technology"
cap label var LSR "Laser"
cap label var MGE "Micro-organism and genetic engineering"
cap label var SMC "Semiconductors"
cap label var ICT "Information and communication technology (ICT) - total"
cap label var COE "Consumer electronics"
cap label var COM "Computers, office machinery"
cap label var TEL "Telecommunications"
cap label var ICT_OTH "Other ICT"
cap label var BIO "Biotechnology sector - total"
cap label var NRG "Energy technologies - total"
cap label var BFS "Biofuels"
cap label var BMA "Biomass"
cap label var CCS "Carbon Capture and Storage"
cap label var EBU "Efficient Buildings"
cap label var FCE "Fuel cells"
cap label var GTH "Geothermal"
cap label var HEP "Heat pump"
cap label var HEX "Heat exchange"
cap label var HYD "Hydrogen"
cap label var LGT "Lighting"
cap label var SEN "Stirling engines"
cap label var SMG "Smart grids"
cap label var SOL "Solar"
cap label var STR "Storage and transport"
cap label var TEN "Traditional engines"
cap label var TWA "Tide and wave"
cap label var WHR "Waste heat recovery"
cap label var WND "Wind"
cap label var Y02 "Technologies or applications for mitigation or adaptation against climate change"
cap label var Y02C "Capture, storage, sequestration or disposal of greenhouse gases"
cap label var Y02C10 "CO2 capture or storage"
cap label var Y02C1002 "CO2 capture by biological separation"
cap label var Y02C1004 "CO2 capture by chemical separation"
cap label var Y02C1006 "CO2 capture by absorption"
cap label var Y02C1008 "CO2 capture by adsorption"
cap label var Y02C1010 "CO2 capture by membranes or diffusion"
cap label var Y02C1012 "CO2 capture by rectification and condensation"
cap label var Y02C1014 "Subterranean or submarine CO2 storage"
cap label var Y02C20 "Capture or disposal of greenhouse gases other than CO2"
cap label var Y02C2010 "Capture or disposal of nitrous oxide"
cap label var Y02C2020 "Capture or disposal of methane"
cap label var Y02C2030 "Capture or disposal of perfluorocarbons, hydrofluorocarbons or sulfur hexafluoride"
cap label var Y02E "Reduction of greenhouse gases emission, related to energy generation, transmission or distribution"
cap label var Y02E10 "Energy generation through renewable energy sources"
cap label var Y02E1010 "Renewable energy sources: Geothermal energy"
cap label var Y02E1020 "Renewable energy sources: Hydro energy"
cap label var Y02E1030 "Renewable energy sources: Energy from sea"
cap label var Y02E1040 "Renewable energy sources: Solar thermal energy"
cap label var Y02E1050 "Renewable energy sources: Photovoltaic energy"
cap label var Y02E1060 "Renewable energy sources: Thermal-Photovoltaic hybrids"
cap label var Y02E1070 "Renewable energy sources: Wind energy"
cap label var Y02E20 "Combustion technologies with mitigation potential"
cap label var Y02E2010 "Combined combustion"
cap label var Y02E2030 "Technologies for a more efficient combustion or heat usage"
cap label var Y02E30 "Energy generation of nuclear origin"
cap label var Y02E3010 "Fusion reactors"
cap label var Y02E3030 "Nuclear fission reactors"
cap label var Y02E40 "Technologies for an efficient electrical power generation, transmission or distribution"
cap label var Y02E4010 "Flexible AC transmission systems"
cap label var Y02E4020 "Active power filtering"
cap label var Y02E4030 "Reactive power compensation"
cap label var Y02E4040 "Arrangements for reducing harmonics"
cap label var Y02E4050 "Arrangements for eliminating or reducing asymmetry in polyphase networks"
cap label var Y02E4060 "Superconducting electric elements and equipment"
cap label var Y02E4070 "Methods and systems for the efficient management or operation of electric power systems"
cap label var Y02E50 "Technologies for the production of fuel of non-fossil origin"
cap label var Y02E5010 "Biofuels"
cap label var Y02E5030 "Fuel from waste"
cap label var Y02E60 "Technologies with potential or indirect contribution to GHG emissions mitigation"
cap label var Y02E6010 "Energy storage"
cap label var Y02E6030 "Hydrogen technology"
cap label var Y02E6050 "Fuel cells"
cap label var Y02E70 "Other energy conversion or management systems reducing GHG emissions"
cap label var Y02E7010 "Hydrogen from electrolysis with energy of non-fossil origin"
cap label var Y02E7020 "Systems combining fuel cells with production of fuel of non-fossil origin"
cap label var Y02E7030 "Systems combining energy storage with energy generation of non-fossil origin"
cap label var Y02E7040 "Batteries, ultracapacitors, supercapacitors or double-layer capacitors, charging or discharging systems or methods for reducing GHG emissions"
cap label var Y02W "Climate change mitigation technologies related to wastewater treatment or waste management"
cap label var Y02W_X_1030_3030_9010 "Climate change mitigation technologies related to wastewater treatment or waste management except Y02W1030, Y02W3030 and Y02W9010"
cap label var Y02W10 "Technologies for wastewater treatment"
cap label var Y02W1010 "Biological treatment of water, waste water, or sewage"
cap label var Y02W1012 "Anaerobic processes with biogas recycling, capture or flaring"
cap label var Y02W1015 "Aerobic processes"
cap label var Y02W1018 "Constructed wetlands"
cap label var Y02W1020 "Sludge processing"
cap label var Y02W1023 "Anaerobic processes with biogas recycling, capture or flaring"
cap label var Y02W1027 "Aerobic processes"
cap label var Y02W1030 "Wastewater or sewage treatment systems with climate change mitigation effect characterised by the origin of the energy"
cap label var Y02W1033 "Wastewater or sewage treatment systems with climate change mitigation effect characterised by the origin of the energy - using wind energy"
cap label var Y02W1037 "Wastewater or sewage treatment systems with climate change mitigation effect characterised by the origin of the energy - using solar energy"
cap label var Y02W1040 "Valorisation of by-products of wastewater, sewage or sludge processing"
cap label var Y02W1045 "Obtention of bio-polymers"
cap label var Y02W30 "Technologies for solid waste management"
cap label var Y02W3010 "Related to waste collection, transportation, transfer or storage, e.g. segregated refuse collecting, electric or hybrid propulsion"
cap label var Y02W3020 "Related to waste processing or separation"
cap label var Y02W3030 "Landfill technologies aiming to mitigate methane emissions"
cap label var Y02W3032 "Sealing or covering"
cap label var Y02W3035 "Landfill gas capture"
cap label var Y02W3038 "Landfill gas flaring"
cap label var Y02W3040 "Bio-organic fraction processing; Production of fertilisers from the organic fraction of waste or refuse"
cap label var Y02W3043 "Aerobic fermentation, e.g. composting"
cap label var Y02W3047 "Anaerobic fermentation, e.g. methanation combined with capture, recycling or flaring"
cap label var Y02W3050 "Reuse, recycling or recovery technologies"
cap label var Y02W3052 "Dismantling or mechanical processing of waste for the recovery of materials during separation, disassembly, pre-processing or upgrading"
cap label var Y02W3054 "Metal recycling"
cap label var Y02W3056 "Disassembly of vehicles for recovery of salvageable parts"
cap label var Y02W3058 "Construction or demolition [C&D] waste"
cap label var Y02W3060 "Glass recycling"
cap label var Y02W3062 "Plastics recycling"
cap label var Y02W3064 "Paper recycling"
cap label var Y02W3066 "Disintegrating fibre-containing textile articles to obtain fibres for re-use"
cap label var Y02W3068 "Rubber waste recycling"
cap label var Y02W3070 "Recovery of polymers other than plastics or rubbers"
cap label var Y02W3072 "Recovery of luminescent materials"
cap label var Y02W3074 "Recovery of fats, fatty oils, fatty acids or other fatty substances, e.g. lanolin or waxes"
cap label var Y02W3076 "Recovery of tanning agents from leather"
cap label var Y02W3078 "Recycling of wood or furniture waste"
cap label var Y02W3080 "Packaging reuse or recycling"
cap label var Y02W3082 "Recycling of waste of electrical or electronic equipment [WEEE]"
cap label var Y02W3084 "Recycling of batteries"
cap label var Y02W3086 "Recycling of fuel cells"
cap label var Y02W3088 "Nuclear fuel reprocessing"
cap label var Y02W3090 "Reuse, recycling or recovery technologies cross-cutting to different types of waste"
cap label var Y02W90 "Enabling technologies or technologies with a potential or indirect contribution to greenhouse gas [GHG] emissions mitigation"
cap label var Y02W9010 "Bio-packaging"
cap label var Y02W9011 "Packing containers made from renewable resources"
cap label var Y02W9020 "Computer systems or methods specially adapted for waste reduction or recycling of materials or goods"
cap label var Y01N "Nanotechnology - total"
cap label var Y01N2 "Nanobiotechnology"
cap label var Y01N4 "Nanotechnology for information processing, storage and transmission"
cap label var Y01N6 "Nanotechnology for materials and surface science"
cap label var Y01N8 "Nanotechnology for interacting, sensing or actuating"
cap label var Y01N10 "Nano optics"
cap label var Y01N12 "Nanomagnetics"
cap label var UNK "Unknown"
