cap label var _12_1176011 "Electrical capacity, main activity producers - Combustible Fuels"
cap label var _12_1176012 "Electrical capacity, autoproducers -Combustible Fuels"
cap label var _12_1176031 "Electrical capacity, main activity producers - Nuclear"
cap label var _12_1176032 "Electrical capacity, autoproducers -Nuclear"
cap label var _12_1176051 "Electrical capacity, main activity producers - Hydro"
cap label var _12_1176052 "Electrical capacity, autoproducers -Hydro"
cap label var _12_1176061 "Electrical capacity, main activity producers - Mixed plants"
cap label var _12_1176062 "Electrical capacity, autoproducers - Mixed plants"
cap label var _12_1176070 "Electrical capacity, autoproducers - Mixed plants"
cap label var _12_1176071 "Electrical capacity, main activity producers - Pure Pumped Hydro"
cap label var _12_1176072 "Electrical capacity, autoproducers - Pure Pumped Hydro"
cap label var _12_1176081 "Electrical capacity, main activity producers - Geothermal"
cap label var _12_1176082 "Electrical capacity, autoproducers -Geothermal"
cap label var _12_1176083 "Electrical capacity - Geothermal"
cap label var _12_1176091 "Electrical capacity, main activity producers - Wind"
cap label var _12_1176092 "Electrical capacity, autoproducers -Wind"
cap label var _12_1176101 "Electrical capacity, main activity producers - Other Sources"
cap label var _12_1176102 "Electrical capacity, autoproducers -Other Sources"
cap label var _12_1176111 "Electrical capacity, main activity producers - Steam"
cap label var _12_1176112 "Electrical capacity, autoproducers -Steam"
cap label var _12_1176121 "Electrical capacity, main activity producers - Gas Turbine"
cap label var _12_1176122 "Electrical capacity, autoproducers -Gas Turbine"
cap label var _12_1176131 "Electrical capacity, main activity producers - Combined Cycle"
cap label var _12_1176132 "Electrical capacity, autoproducers -Combined Cycle"
cap label var _12_1176141 "Electrical capacity, main activity producers - Internal Combustion"
cap label var _12_1176142 "Electrical capacity, autoproducers -Internal Combustion"
cap label var _12_117615 "Electrical capacity - Hydro <1 MW"
cap label var _12_117616 "Electrical capacity - Hydro >= 1 MW and <= 10 MW"
cap label var _12_117617 "Electrical capacity - Hydro 10 MW and over"
cap label var _12_1176231 "Electrical capacity, main activity producers - Solar"
cap label var _12_1176232 "Electrical capacity, autoproducers -  Solar"
cap label var _12_1176233 "Electrical capacity - Solar Photovoltaic"
cap label var _12_1176243 "Electrical capacity - Solar Thermal Electric"
cap label var _12_1176253 "Electrical capacity - Municipal Wastes"
cap label var _12_1176263 "Elelectrical capacity - solid biofuels (Wood/Wood Wastes/Other Solid Wastes)"
cap label var _12_1176273 "Electrical capacity - Biogases"
cap label var _12_1176283 "Electrical capacity - Industrial Wastes (non-renewable)"
cap label var _12_1176301 "Electrical capacity, main activity producers - Tide, wave and ocean"
cap label var _12_1176302 "Electrical capacity, autoproducers -Tide, wave and ocean"
cap label var _12_1176303 "Electrical capacity - Tide, Wave, Ocean"
cap label var _12_1176313 "Net maximum capacity - Landfill Gas"
cap label var _12_1176323 "Net maximum capacity - Sewage Sludge Gas"
cap label var _12_1176333 "Net maximum capacity - Other Biogas"
cap label var _12_1176343 "Electrical capacity - Liquid Biofuels"
cap label var _12_1176401 "Electrical capacity, main activity producers - Other Type of Generation"
cap label var _12_1176402 "Electrical capacity, autoproducers -Other Type of Generation"
cap label var _12_119300 "Solar collectors' surface"
cap label var _12_119400 "Biofuel production capacities"
cap label var _14_1070341 "Gross electricity generation Main activity electricity only - Hydro -1 MW"
cap label var _14_1070342 "Gross electricity generation Main activity electricity only - Hydro 1-10 MW"
cap label var _14_1070343 "Gross electricity generation Main activity electricity only - Hydro 10+ MW"
cap label var _14_1070351 "Gross electricity generation Autoproducer electricity only - Hydro -1 MW"
cap label var _14_1070352 "Gross electricity generation Autoproducer electricity only - Hydro 1-10 MW"
cap label var _14_1070353 "Gross electricity generation Autoproducer electricity only - Hydro 10+ MW"
cap label var _14_1070421 "Gross electricity generation Main activity electricity only - Solar Photovoltaic"
cap label var _14_1070422 "Gross electricity generation Main activity electricity only - Solar Thermal"
cap label var _14_1070423 "Gross electricity generation Main activity CHP plants - Solar Thermal"
cap label var _14_1070431 "Gross electricity generation Autoproducer electricity only - Solar Photovoltaic"
cap label var _14_1070432 "Gross electricity generation Autoproducer electricity only - Solar Thermal"
cap label var _14_1070433 "Gross electricity generation Autoproducer CHP plants - Solar Thermal"
cap label var _14_1070681 "Gross heat production Main activity CHP plants - Solar Thermal"
cap label var _14_1070691 "Gross heat production Main activity heat only plants - Solar Thermal"
cap label var _14_1070701 "Gross heat production Autoproducer CHP plants - Solar Thermal"
cap label var _14_1070711 "Gross heat production Autoproducer heat only plants - Solar Thermal"
cap label var _15_107030 "Gross electricity generation Main activity electricity only - Nuclear"
cap label var _15_107031 "Gross electricity generation Main activity CHP plants - Nuclear"
cap label var _15_107032 "Gross electricity generation Autoproducer electricity only - Nuclear"
cap label var _15_107033 "Gross electricity generation Autoproducer CHP plants - Nuclear"
cap label var _15_107034 "Gross electricity generation Main activity electricity only - Hydro"
cap label var _15_107035 "Gross electricity generation Autoproducer electricity only - Hydro"
cap label var _15_107036 "Gross electricity generation Main activity electricity only - Pumped Hydro"
cap label var _15_107037 "Gross electricity generation Autoproducer electricity only - Pumped Hydro"
cap label var _15_107038 "Gross electricity generation Main activity electricity only - Geothermal"
cap label var _15_107039 "Gross electricity generation Main activity CHP plants - Geothermal"
cap label var _15_107040 "Gross electricity generation Autoproducer electricity only - Geothermal"
cap label var _15_107041 "Gross electricity generation Autoproducer CHP plants - Geothermal"
cap label var _15_107043 "Gross electricity generation Autoproducer electricity only - Solar"
cap label var _15_107044 "Gross electricity generation Main activity electricity only - Tide, Wave and Ocean"
cap label var _15_107045 "Gross electricity generation Autoproducer electricity only - Tide, Wave and Ocean"
cap label var _15_107046 "Gross electricity generation Main activity electricity only - Wind"
cap label var _15_107047 "Gross electricity generation Autoproducer electricity only - Wind"
cap label var _15_107048 "Gross electricity generation Main activity electricity only - Combustible Fuels"
cap label var _15_107049 "Gross electricity generation Main activity CHP plants - Combustible Fuels"
cap label var _15_107050 "Gross electricity generation Autoproducer electricity only - Combustible Fuels"
cap label var _15_107051 "Gross electricity generation Autoproducer CHP plants - Combustible Fuels"
cap label var _15_107052 "Gross electricity generation Autoproducer electricity only - Heat from Chemical Sources"
cap label var _15_107053 "Gross electricity generation Autoproducer CHP plants - Heat from Chemical Sources"
cap label var _15_107054 "Gross electricity generation Main activity electricity only - Other Sources"
cap label var _15_107055 "Gross electricity generation Main activity CHP plants - Other Sources"
cap label var _15_107056 "Gross electricity generation Autoproducer electricity only - Other Sources"
cap label var _15_107057 "Gross electricity generation Autoproducer CHP plants - Other Sources"
cap label var _15_107060 "Gross heat production Main activity CHP plants - Nuclear"
cap label var _15_107061 "Gross heat production Main activity heat only plants - Nuclear"
cap label var _15_107062 "Gross heat production Autoproducer CHP plants - Nuclear"
cap label var _15_107063 "Gross heat production Autoproducer heat only plants - Nuclear"
cap label var _15_107064 "Gross heat production Main activity CHP plants - Geothermal"
cap label var _15_107065 "Gross heat production Main activity heat only plants - Geothermal"
cap label var _15_107066 "Gross heat production Autoproducer CHP plants - Geothermal"
cap label var _15_107067 "Gross heat production Autoproducer heat only plants - Geothermal"
cap label var _15_107068 "Gross heat production Main activity CHP plants - Solar"
cap label var _15_107069 "Gross heat production Main activity heat only plants - Solar"
cap label var _15_107070 "Gross heat production Autoproducer CHP plants - Solar"
cap label var _15_107071 "Gross heat production Autoproducer heat only plants - Solar"
cap label var _15_107072 "Gross heat production Main activity CHP plants - Combustible Fuels"
cap label var _15_107073 "Gross heat production Main activity heat only plants - Combustible Fuels"
cap label var _15_107074 "Gross heat production Autoproducer CHP plants - Combustible Fuels"
cap label var _15_107075 "Gross heat production Autoproducer heat only plants - Combustible Fuels"
cap label var _15_107076 "Gross heat production Main activity CHP plants - Heat Pumps"
cap label var _15_107077 "Gross heat production Main activity heat only plants - Heat Pumps"
cap label var _15_107078 "Gross heat production Autoproducer CHP plants - Heat Pumps"
cap label var _15_107079 "Gross heat production Autoproducer heat only plants - Heat Pumps"
cap label var _15_107080 "Gross heat production Main activity CHP plants - Electric Boilers"
cap label var _15_107081 "Gross heat production Main activity heat only plants - Electric Boilers"
cap label var _15_107082 "Gross heat production Autoproducer CHP plants - Electric Boilers"
cap label var _15_107083 "Gross heat production Autoproducer heat only plants - Electric Boilers"
cap label var _15_107084 "Gross heat production Autoproducer CHP plants - Heat from Chemical Sources"
cap label var _15_107085 "Gross heat production Autoproducer heat only plants - Heat from Chemical Sources"
cap label var _15_107086 "Gross heat production Main activity CHP plants - Other Sources"
cap label var _15_107087 "Gross heat production Main activity heat only plants - Other Sources"
cap label var _15_107088 "Gross heat production Autoproducer CHP plants - Other Sources"
cap label var _15_107089 "Gross heat production Autoproducer heat only plants - Other Sources"
cap label var _16_107130 "Net electricity generation Main activity electricity only - Nuclear"
cap label var _16_107131 "Net electricity generation Main activity CHP plants - Nuclear"
cap label var _16_107132 "Net electricity generation Autoproducer electricity only - Nuclear"
cap label var _16_107133 "Net electricity generation Autoproducer CHP plants - Nuclear"
cap label var _16_107134 "Net electricity generation Main activity electricity only - Hydro"
cap label var _16_107135 "Net electricity generation Autoproducer electricity only - Hydro"
cap label var _16_107136 "Net electricity generation Main activity electricity only - Pumped Hydro"
cap label var _16_107137 "Net electricity generation Autoproducer electricity only - Pumped Hydro"
cap label var _16_107138 "Net electricity generation Main activity electricity only - Geothermal"
cap label var _16_107139 "Net electricity generation Main activity CHP plants - Geothermal"
cap label var _16_107140 "Net electricity generation Autoproducer electricity only - Geothermal"
cap label var _16_107141 "Net electricity generation Autoproducer CHP plants - Geothermal"
cap label var _16_107142 "Net electricity generation Main activity electricity only - Solar"
cap label var _16_107143 "Net electricity generation Autoproducer electricity only - Solar"
cap label var _16_107144 "Net electricity generation Main activity electricity only - Tide, Wave and Ocean"
cap label var _16_107145 "Net electricity generation Autoproducer electricity only - Tide, Wave and Ocean"
cap label var _16_107146 "Net electricity generation Main activity electricity only - Wind"
cap label var _16_107147 "Net electricity generation Autoproducer electricity only - Wind"
cap label var _16_107148 "Net electricity generation Main activity electricity only - Combustible Fuels"
cap label var _16_107149 "Net electricity generation Main activity CHP plants - Combustible Fuels"
cap label var _16_107150 "Net electricity generation Autoproducer electricity only - Combustible Fuels"
cap label var _16_107151 "Net electricity generation Autoproducer CHP plants - Combustible Fuels"
cap label var _16_107152 "Net electricity generation Autoproducer electricity only - Heat from Chemical Sources"
cap label var _16_107153 "Net electricity generation Autoproducer CHP plants - Heat from Chemical Sources"
cap label var _16_107154 "Net electricity generation Main activity electricity only - Other Sources"
cap label var _16_107155 "Net electricity generation Main activity CHP plants - Other Sources"
cap label var _16_107156 "Net electricity generation Autoproducer electricity only - Other Sources"
cap label var _16_107157 "Net electricity generation Autoproducer CHP plants - Other Sources"
cap label var _16_107160 "Net heat production Main activity CHP plants - Nuclear"
cap label var _16_107161 "Net heat production Main activity heat only plants - Nuclear"
cap label var _16_107162 "Net heat production Autoproducer CHP plants - Nuclear"
cap label var _16_107163 "Net heat production Autoproducer heat only plants - Nuclear"
cap label var _16_107164 "Net heat production Main activity CHP plants - Geothermal"
cap label var _16_107165 "Net heat production Main activity heat only plants - Geothermal"
cap label var _16_107166 "Net heat production Autoproducer CHP plants - Geothermal"
cap label var _16_107167 "Net heat production Autoproducer heat only plants - Geothermal"
cap label var _16_107168 "Net heat production Main activity CHP plants - Solar"
cap label var _16_107169 "Net heat production Main activity heat only plants - Solar"
cap label var _16_107170 "Net heat production Autoproducer CHP plants - Solar"
cap label var _16_107171 "Net heat production Autoproducer heat only plants - Solar"
cap label var _16_107172 "Net heat production Main activity CHP plants - Combustible Fuels"
cap label var _16_107173 "Net heat production Main activity heat only plants - Combustible Fuels"
cap label var _16_107174 "Net heat production Autoproducer CHP plants - Combustible Fuels"
cap label var _16_107175 "Net heat production Autoproducer heat only plants - Combustible Fuels"
cap label var _16_107176 "Net heat production Main activity CHP plants - Heat Pumps"
cap label var _16_107177 "Net heat production Main activity heat only plants - Heat Pumps"
cap label var _16_107178 "Net heat production Autoproducer CHP plants - Heat Pumps"
cap label var _16_107179 "Net heat production Autoproducer heat only plants - Heat Pumps"
cap label var _16_107180 "Net heat production Main activity CHP plants - Electric Boilers"
cap label var _16_107181 "Net heat production Main activity heat only plants - Electric Boilers"
cap label var _16_107182 "Net heat production Autoproducer CHP plants - Electric Boilers"
cap label var _16_107183 "Net heat production Autoproducer heat only plants - Electric Boilers"
cap label var _16_107184 "Net heat production Autoproducer CHP plants - Heat from Chemical Sources"
cap label var _16_107185 "Net heat production Autoproducer heat only plants - Heat from Chemical Sources"
cap label var _16_107186 "Net heat production Main activity CHP plants - Other Sources"
cap label var _16_107187 "Net heat production Main activity heat only plants - Other Sources"
cap label var _16_107188 "Net heat production Autoproducer CHP plants - Other Sources"
cap label var _16_107189 "Net heat production Autoproducer heat only plants - Other Sources"
cap label var _17_107000 "Total gross production"
cap label var _17_107100 "Total net production"
cap label var _22_108501 "Gross electricity generation Main activity electricity only - Anthracite"
cap label var _22_108502 "Gross electricity generation Main activity CHP plants - Anthracite"
cap label var _22_108503 "Gross electricity generation Autoproducer electricity only - Anthracite"
cap label var _22_108504 "Gross electricity generation Autoproducer CHP plants - Anthracite"
cap label var _22_108506 "Gross heat production Main activity CHP plants - Anthracite"
cap label var _22_108507 "Gross heat production Main activity heat only plants - Anthracite"
cap label var _22_108508 "Gross heat production Autoproducer CHP plants - Anthracite"
cap label var _22_108509 "Gross heat production Autoproducer heat only plants - Anthracite"
cap label var _22_108511 "Gross electricity generation Main activity electricity only - Coking Coal"
cap label var _22_108512 "Gross electricity generation Main activity CHP plants - Coking Coal"
cap label var _22_108513 "Gross electricity generation Autoproducer electricity only - Coking Coal"
cap label var _22_108514 "Gross electricity generation Autoproducer CHP plants - Coking Coal"
cap label var _22_108516 "Gross heat production Main activity CHP plants - Coking Coal"
cap label var _22_108517 "Gross heat production Main activity heat only plants - Coking Coal"
cap label var _22_108518 "Gross heat production Autoproducer CHP plants - Coking Coal"
cap label var _22_108519 "Gross heat production Autoproducer heat only plants - Coking Coal"
cap label var _22_108521 "Gross electricity generation Main activity electricity only - Other Bituminous Coal"
cap label var _22_108522 "Gross electricity generation Main activity CHP plants - Other Bituminous Coal"
cap label var _22_108523 "Gross electricity generation Autoproducer electricity only - Other Bituminous Coal"
cap label var _22_108524 "Gross electricity generation Autoproducer CHP plants - Other Bituminous Coal"
cap label var _22_108526 "Gross heat production Main activity CHP plants - Other Bituminous Coal"
cap label var _22_108527 "Gross heat production Main activity heat only plants - Other Bituminous Coal"
cap label var _22_108528 "Gross heat production Autoproducer CHP plants - Other Bituminous Coal"
cap label var _22_108529 "Gross heat production Autoproducer heat only plants - Other Bituminous Coal"
cap label var _22_108531 "Gross electricity generation Main activity electricity only - Sub-Bituminous Coal"
cap label var _22_108532 "Gross electricity generation Main activity CHP plants - Sub-Bituminous Coal"
cap label var _22_108533 "Gross electricity generation Autoproducer electricity only - Sub-Bituminous Coal"
cap label var _22_108534 "Gross electricity generation Autoproducer CHP plants - Sub-Bituminous Coal"
cap label var _22_108536 "Gross heat production Main activity CHP plants - Sub-Bituminous Coal"
cap label var _22_108537 "Gross heat production Main activity heat only plants - Sub-Bituminous Coal"
cap label var _22_108538 "Gross heat production Autoproducer CHP plants - Sub-Bituminous Coal"
cap label var _22_108539 "Gross heat production Autoproducer heat only plants - Sub-Bituminous Coal"
cap label var _22_108541 "Gross electricity generation Main activity electricity only - Lignite/Brown Coal"
cap label var _22_108542 "Gross electricity generation Main activity CHP plants - Lignite/Brown Coal"
cap label var _22_108543 "Gross electricity generation Autoproducer electricity only - Lignite/Brown Coal"
cap label var _22_108544 "Gross electricity generation Autoproducer CHP plants - Lignite/Brown Coal"
cap label var _22_108546 "Gross heat production Main activity CHP plants - Lignite/Brown Coal"
cap label var _22_108547 "Gross heat production Main activity heat only plants - Lignite/Brown Coal"
cap label var _22_108548 "Gross heat production Autoproducer CHP plants - Lignite/Brown Coal"
cap label var _22_108549 "Gross heat production Autoproducer heat only plants - Lignite/Brown Coal"
cap label var _22_108551 "Gross electricity generation Main activity electricity only - Peat"
cap label var _22_108552 "Gross electricity generation Main activity CHP plants - Peat"
cap label var _22_108553 "Gross electricity generation Autoproducer electricity only - Peat"
cap label var _22_108554 "Gross electricity generation Autoproducer CHP plants - Peat"
cap label var _22_108556 "Gross heat production Main activity CHP plants - Peat"
cap label var _22_108557 "Gross heat production Main activity heat only plants - Peat"
cap label var _22_108558 "Gross heat production Autoproducer CHP plants - Peat"
cap label var _22_108559 "Gross heat production Autoproducer heat only plants - Peat"
cap label var _22_108561 "Gross electricity generation Main activity electricity only - Patent Fuel"
cap label var _22_108562 "Gross electricity generation Main activity CHP plants - Patent Fuel"
cap label var _22_108563 "Gross electricity generation Autoproducer electricity only - Patent Fuel"
cap label var _22_108564 "Gross electricity generation Autoproducer CHP plants - Patent Fuel"
cap label var _22_108566 "Gross heat production Main activity CHP plants - Patent Fuel"
cap label var _22_108567 "Gross heat production Main activity heat only plants - Patent Fuel"
cap label var _22_108568 "Gross heat production Autoproducer CHP plants - Patent Fuel"
cap label var _22_108569 "Gross heat production Autoproducer heat only plants - Patent Fuel"
cap label var _22_108571 "Gross electricity generation Main activity electricity only - Coke Oven Coke"
cap label var _22_108572 "Gross electricity generation Main activity CHP plants - Coke Oven Coke"
cap label var _22_108573 "Gross electricity generation Autoproducer electricity only - Coke Oven Coke"
cap label var _22_108574 "Gross electricity generation Autoproducer CHP plants - Coke Oven Coke"
cap label var _22_108576 "Gross heat production Main activity CHP plants - Coke Oven Coke"
cap label var _22_108577 "Gross heat production Main activity heat only plants - Coke Oven Coke"
cap label var _22_108578 "Gross heat production Autoproducer CHP plants - Coke Oven Coke"
cap label var _22_108579 "Gross heat production Autoproducer heat only plants - Coke Oven Coke"
cap label var _22_108581 "Gross electricity generation Main activity electricity only - Gas Coke"
cap label var _22_108582 "Gross electricity generation Main activity CHP plants - Gas Coke"
cap label var _22_108583 "Gross electricity generation Autoproducer electricity only - Gas Coke"
cap label var _22_108584 "Gross electricity generation Autoproducer CHP plants - Gas Coke"
cap label var _22_108586 "Gross heat production Main activity CHP plants - Gas Coke"
cap label var _22_108587 "Gross heat production Main activity heat only plants - Gas Coke"
cap label var _22_108588 "Gross heat production Autoproducer CHP plants - Gas Coke"
cap label var _22_108589 "Gross heat production Autoproducer heat only plants - Gas Coke"
cap label var _22_108591 "Gross electricity generation Main activity electricity only - Coal Tar"
cap label var _22_108592 "Gross electricity generation Main activity CHP plants - Coal Tar"
cap label var _22_108593 "Gross electricity generation Autoproducer electricity only - Coal Tar"
cap label var _22_108594 "Gross electricity generation Autoproducer CHP plants - Coal Tar"
cap label var _22_108596 "Gross heat production Main activity CHP plants - Coal Tar"
cap label var _22_108597 "Gross heat production Main activity heat only plants - Coal Tar"
cap label var _22_108598 "Gross heat production Autoproducer CHP plants - Coal Tar"
cap label var _22_108599 "Gross heat production Autoproducer heat only plants - Coal Tar"
cap label var _22_108601 "Gross electricity generation Main activity electricity only - BKB"
cap label var _22_108602 "Gross electricity generation Main activity CHP plants - BKB"
cap label var _22_108603 "Gross electricity generation Autoproducer electricity only - BKB"
cap label var _22_108604 "Gross electricity generation Autoproducer CHP plants - BKB"
cap label var _22_108606 "Gross heat production Main activity CHP plants - BKB"
cap label var _22_108607 "Gross heat production Main activity heat only plants - BKB"
cap label var _22_108608 "Gross heat production Autoproducer CHP plants - BKB"
cap label var _22_108609 "Gross heat production Autoproducer heat only plants - BKB"
cap label var _22_108611 "Gross electricity generation Main activity electricity only - Gas Works Gas"
cap label var _22_108612 "Gross electricity generation Main activity CHP plants - Gas Works Gas"
cap label var _22_108613 "Gross electricity generation Autoproducer electricity only - Gas Works Gas"
cap label var _22_108614 "Gross electricity generation Autoproducer CHP plants - Gas Works Gas"
cap label var _22_108616 "Gross heat production Main activity CHP plants - Gas Works Gas"
cap label var _22_108617 "Gross heat production Main activity heat only plants - Gas Works Gas"
cap label var _22_108618 "Gross heat production Autoproducer CHP plants - Gas Works Gas"
cap label var _22_108619 "Gross heat production Autoproducer heat only plants - Gas Works Gas"
cap label var _22_108621 "Gross electricity generation Main activity electricity only - Coke Oven Gas"
cap label var _22_108622 "Gross electricity generation Main activity CHP plants - Coke Oven Gas"
cap label var _22_108623 "Gross electricity generation Autoproducer electricity only - Coke Oven Gas"
cap label var _22_108624 "Gross electricity generation Autoproducer CHP plants - Coke Oven Gas"
cap label var _22_108626 "Gross heat production Main activity CHP plants - Coke Oven Gas"
cap label var _22_108627 "Gross heat production Main activity heat only plants - Coke Oven Gas"
cap label var _22_108628 "Gross heat production Autoproducer CHP plants - Coke Oven Gas"
cap label var _22_108629 "Gross heat production Autoproducer heat only plants - Coke Oven Gas"
cap label var _22_108631 "Gross electricity generation Main activity electricity only - Blast Furnace Gas"
cap label var _22_108632 "Gross electricity generation Main activity CHP plants - Blast Furnace Gas"
cap label var _22_108633 "Gross electricity generation Autoproducer electricity only - Blast Furnace Gas"
cap label var _22_108634 "Gross electricity generation Autoproducer CHP plants - Blast Furnace Gas"
cap label var _22_108636 "Gross heat production Main activity CHP plants - Blast Furnace Gas"
cap label var _22_108637 "Gross heat production Main activity heat only plants - Blast Furnace Gas"
cap label var _22_108638 "Gross heat production Autoproducer CHP plants - Blast Furnace Gas"
cap label var _22_108639 "Gross heat production Autoproducer heat only plants - Blast Furnace Gas"
cap label var _22_108641 "Gross electricity generation Main activity electricity only - Other Recovered Gases"
cap label var _22_108642 "Gross electricity generation Main activity CHP plants - Other Recovered Gases"
cap label var _22_108643 "Gross electricity generation Autoproducer electricity only - Other Recovered Gases"
cap label var _22_108644 "Gross electricity generation Autoproducer CHP plants - Other Recovered Gases"
cap label var _22_108646 "Gross heat production Main activity CHP plants - Other Recovered Gases"
cap label var _22_108647 "Gross heat production Main activity heat only plants - Other Recovered Gases"
cap label var _22_108648 "Gross heat production Autoproducer CHP plants - Other Recovered Gases"
cap label var _22_108649 "Gross heat production Autoproducer heat only plants - Other Recovered Gases"
cap label var _22_108651 "Gross electricity generation Main activity electricity only - Oil shale and oil sands"
cap label var _22_108652 "Gross electricity generation Main activity CHP plants - Oil shale and oil sands"
cap label var _22_108653 "Gross electricity generation Autoproducer electricity only - Oil shale and oil sands"
cap label var _22_108654 "Gross electricity generation Autoproducer CHP plants - Oil shale and oil sands"
cap label var _22_108656 "Gross heat production Main activity CHP plants - Oil shale and oil sands"
cap label var _22_108657 "Gross heat production Main activity heat only plants - Oil shale and oil sands"
cap label var _22_108658 "Gross heat production Autoproducer CHP plants - Oil shale and oil sands"
cap label var _22_108659 "Gross heat production Autoproducer heat only plants - Oil shale and oil sands"
cap label var _22_108661 "Gross electricity generation Main activity electricity only - Peat products"
cap label var _22_108662 "Gross electricity generation Main activity CHP plants - Peat products"
cap label var _22_108663 "Gross electricity generation Autoproducer electricity only - Peat products"
cap label var _22_108664 "Gross electricity generation Autoproducer CHP plants - Peat products"
cap label var _22_108666 "Gross heat production Main activity CHP plants - Peat products"
cap label var _22_108667 "Gross heat production Main activity heat only plants - Peat products"
cap label var _22_108668 "Gross heat production Autoproducer CHP plants - Peat products"
cap label var _22_108669 "Gross heat production Autoproducer heat only plants - Peat products"
cap label var _22_108701 "Gross electricity generation Main activity electricity only - Crude Oil"
cap label var _22_108702 "Gross electricity generation Main activity CHP plants - Crude Oil"
cap label var _22_108703 "Gross electricity generation Autoproducer electricity only - Crude Oil"
cap label var _22_108704 "Gross electricity generation Autoproducer CHP plants - Crude Oil"
cap label var _22_108706 "Gross heat production Main activity CHP plants - Crude Oil"
cap label var _22_108707 "Gross heat production Main activity heat only plants - Crude Oil"
cap label var _22_108708 "Gross heat production Autoproducer CHP plants - Crude Oil"
cap label var _22_108709 "Gross heat production Autoproducer heat only plants - Crude Oil"
cap label var _22_108711 "Gross electricity generation Main activity electricity only - NGL (Natural Gas Liquids)"
cap label var _22_108712 "Gross electricity generation Main activity CHP plants - NGL (Natural Gas Liquids)"
cap label var _22_108713 "Gross electricity generation Autoproducer electricity only - NGL (Natural Gas Liquids)"
cap label var _22_108714 "Gross electricity generation Autoproducer CHP plants - NGL (Natural Gas Liquids)"
cap label var _22_108716 "Gross heat production Main activity CHP plants - NGL (Natural Gas Liquids)"
cap label var _22_108717 "Gross heat production Main activity heat only plants - NGL (Natural Gas Liquids)"
cap label var _22_108718 "Gross heat production Autoproducer CHP plants - NGL (Natural Gas Liquids)"
cap label var _22_108719 "Gross heat production Autoproducer heat only plants - NGL (Natural Gas Liquids)"
cap label var _22_108721 "Gross electricity generation Main activity electricity only - Refinery Gas"
cap label var _22_108722 "Gross electricity generation Main activity CHP plants - Refinery Gas"
cap label var _22_108723 "Gross electricity generation Autoproducer electricity only - Refinery Gas"
cap label var _22_108724 "Gross electricity generation Autoproducer CHP plants - Refinery Gas"
cap label var _22_108726 "Gross heat production Main activity CHP plants - Refinery Gas"
cap label var _22_108727 "Gross heat production Main activity heat only plants - Refinery Gas"
cap label var _22_108728 "Gross heat production Autoproducer CHP plants - Refinery Gas"
cap label var _22_108729 "Gross heat production Autoproducer heat only plants - Refinery Gas"
cap label var _22_108731 "Gross electricity generation Main activity electricity only - LPG (Liquefied Petroleum Gases)"
cap label var _22_108732 "Gross electricity generation Main activity CHP plants - LPG (Liquefied Petroleum Gases)"
cap label var _22_108733 "Gross electricity generation Autoproducer electricity only - LPG (Liquefied Petroleum Gases)"
cap label var _22_108734 "Gross electricity generation Autoproducer CHP plants - LPG (Liquefied Petroleum Gases)"
cap label var _22_108736 "Gross heat production Main activity CHP plants - LPG (Liquefied Petroleum Gases)"
cap label var _22_108737 "Gross heat production Main activity heat only plants - LPG (Liquefied Petroleum Gases)"
cap label var _22_108738 "Gross heat production Autoproducer CHP plants - LPG (Liquefied Petroleum Gases)"
cap label var _22_108739 "Gross heat production Autoproducer heat only plants - LPG (Liquefied Petroleum Gases)"
cap label var _22_108741 "Gross electricity generation Main activity electricity only - Naphtha"
cap label var _22_108742 "Gross electricity generation Main activity CHP plants - Naphtha"
cap label var _22_108743 "Gross electricity generation Autoproducer electricity only - Naphtha"
cap label var _22_108744 "Gross electricity generation Autoproducer CHP plants - Naphtha"
cap label var _22_108746 "Gross heat production Main activity CHP plants - Naphtha"
cap label var _22_108747 "Gross heat production Main activity heat only plants - Naphtha"
cap label var _22_108748 "Gross heat production Autoproducer CHP plants - Naphtha"
cap label var _22_108749 "Gross heat production Autoproducer heat only plants - Naphtha"
cap label var _22_108751 "Gross electricity generation Main activity electricity only - Kerosene Type Jet Fuel"
cap label var _22_108752 "Gross electricity generation Main activity CHP plants - Kerosene Type Jet Fuel"
cap label var _22_108753 "Gross electricity generation Autoproducer electricity only - Kerosene Type Jet Fuel"
cap label var _22_108754 "Gross electricity generation Autoproducer CHP plants - Kerosene Type Jet Fuel"
cap label var _22_108756 "Gross heat production Main activity CHP plants - Kerosene Type Jet Fuel"
cap label var _22_108757 "Gross heat production Main activity heat only plants - Kerosene Type Jet Fuel"
cap label var _22_108758 "Gross heat production Autoproducer CHP plants - Kerosene Type Jet Fuel"
cap label var _22_108759 "Gross heat production Autoproducer heat only plants - Kerosene Type Jet Fuel"
cap label var _22_108761 "Gross electricity generation Main activity electricity only - Other Kerosene"
cap label var _22_108762 "Gross electricity generation Main activity CHP plants - Other Kerosene"
cap label var _22_108763 "Gross electricity generation Autoproducer electricity only - Other Kerosene"
cap label var _22_108764 "Gross electricity generation Autoproducer CHP plants - Other Kerosene"
cap label var _22_108766 "Gross heat production Main activity CHP plants - Other Kerosene"
cap label var _22_108767 "Gross heat production Main activity heat only plants - Other Kerosene"
cap label var _22_108768 "Gross heat production Autoproducer CHP plants - Other Kerosene"
cap label var _22_108769 "Gross heat production Autoproducer heat only plants - Other Kerosene"
cap label var _22_108771 "Gross electricity generation Main activity electricity only - Gas / Diesel Oil"
cap label var _22_108772 "Gross electricity generation Main activity CHP plants - Gas / Diesel Oil"
cap label var _22_108773 "Gross electricity generation Autoproducer electricity only - Gas / Diesel Oil"
cap label var _22_108774 "Gross electricity generation Autoproducer CHP plants - Gas / Diesel Oil"
cap label var _22_108776 "Gross heat production Main activity CHP plants - Gas / Diesel Oil"
cap label var _22_108777 "Gross heat production Main activity heat only plants - Gas / Diesel Oil"
cap label var _22_108778 "Gross heat production Autoproducer CHP plants - Gas / Diesel Oil"
cap label var _22_108779 "Gross heat production Autoproducer heat only plants - Gas / Diesel Oil"
cap label var _22_108781 "Gross electricity generation Main activity electricity only - Residual Fuel Oil"
cap label var _22_108782 "Gross electricity generation Main activity CHP plants - Residual Fuel Oil"
cap label var _22_108783 "Gross electricity generation Autoproducer electricity only - Residual Fuel Oil"
cap label var _22_108784 "Gross electricity generation Autoproducer CHP plants - Residual Fuel Oil"
cap label var _22_108786 "Gross heat production Main activity CHP plants - Residual Fuel Oil"
cap label var _22_108787 "Gross heat production Main activity heat only plants - Residual Fuel Oil"
cap label var _22_108788 "Gross heat production Autoproducer CHP plants - Residual Fuel Oil"
cap label var _22_108789 "Gross heat production Autoproducer heat only plants - Residual Fuel Oil"
cap label var _22_108791 "Gross electricity generation Main activity electricity only - Bitumen"
cap label var _22_108792 "Gross electricity generation Main activity CHP plants - Bitumen"
cap label var _22_108793 "Gross electricity generation Autoproducer electricity only - Bitumen"
cap label var _22_108794 "Gross electricity generation Autoproducer CHP plants - Bitumen"
cap label var _22_108796 "Gross heat production Main activity CHP plants - Bitumen"
cap label var _22_108797 "Gross heat production Main activity heat only plants - Bitumen"
cap label var _22_108798 "Gross heat production Autoproducer CHP plants - Bitumen"
cap label var _22_108799 "Gross heat production Autoproducer heat only plants - Bitumen"
cap label var _22_108801 "Gross electricity generation Main activity electricity only - Petroleum Coke"
cap label var _22_108802 "Gross electricity generation Main activity CHP plants - Petroleum Coke"
cap label var _22_108803 "Gross electricity generation Autoproducer electricity only - Petroleum Coke"
cap label var _22_108804 "Gross electricity generation Autoproducer CHP plants - Petroleum Coke"
cap label var _22_108806 "Gross heat production Main activity CHP plants - Petroleum Coke"
cap label var _22_108807 "Gross heat production Main activity heat only plants - Petroleum Coke"
cap label var _22_108808 "Gross heat production Autoproducer CHP plants - Petroleum Coke"
cap label var _22_108809 "Gross heat production Autoproducer heat only plants - Petroleum Coke"
cap label var _22_108811 "Gross electricity generation Main activity electricity only - Other Oil Products"
cap label var _22_108812 "Gross electricity generation Main activity CHP plants - Other Oil Products"
cap label var _22_108813 "Gross electricity generation Autoproducer electricity only - Other Oil Products"
cap label var _22_108814 "Gross electricity generation Autoproducer CHP plants - Other Oil Products"
cap label var _22_108816 "Gross heat production Main activity CHP plants - Other Oil Products"
cap label var _22_108817 "Gross heat production Main activity heat only plants - Other Oil Products"
cap label var _22_108818 "Gross heat production Autoproducer CHP plants - Other Oil Products"
cap label var _22_108819 "Gross heat production Autoproducer heat only plants - Other Oil Products"
cap label var _22_108891 "Gross electricity generation Main activity electricity only - Natural Gas"
cap label var _22_108892 "Gross electricity generation Main activity CHP plants - Natural Gas"
cap label var _22_108893 "Gross electricity generation Autoproducer electricity only - Natural Gas"
cap label var _22_108894 "Gross electricity generation Autoproducer CHP plants - Natural Gas"
cap label var _22_108896 "Gross heat production Main activity CHP plants - Natural Gas"
cap label var _22_108897 "Gross heat production Main activity heat only plants - Natural Gas"
cap label var _22_108898 "Gross heat production Autoproducer CHP plants - Natural Gas"
cap label var _22_108899 "Gross heat production Autoproducer heat only plants - Natural Gas"
cap label var _22_108901 "Gross electricity generation Main activity electricity only - Industrial Waste"
cap label var _22_108902 "Gross electricity generation Main activity CHP plants - Industrial Waste"
cap label var _22_108903 "Gross electricity generation Autoproducer electricity only - Industrial Waste"
cap label var _22_108904 "Gross electricity generation Autoproducer CHP plants - Industrial Waste"
cap label var _22_108906 "Gross heat production Main activity CHP plants - Industrial Waste"
cap label var _22_108907 "Gross heat production Main activity heat only plants - Industrial Waste"
cap label var _22_108908 "Gross heat production Autoproducer CHP plants - Industrial Waste"
cap label var _22_108909 "Gross heat production Autoproducer heat only plants - Industrial Waste"
cap label var _22_108911 "Gross electricity generation Main activity electricity only - Municipal Waste (Renewable)"
cap label var _22_108912 "Gross electricity generation Main activity CHP plants - Municipal Waste (Renewable)"
cap label var _22_108913 "Gross electricity generation Autoproducer electricity only - Municipal Waste (Renewable)"
cap label var _22_108914 "Gross electricity generation Autoproducer CHP plants - Municipal Waste (Renewable)"
cap label var _22_108916 "Gross heat production Main activity CHP plants - Municipal Waste (Renewable)"
cap label var _22_108917 "Gross heat production Main activity heat only plants - Municipal Waste (Renewable)"
cap label var _22_108918 "Gross heat production Autoproducer CHP plants - Municipal Waste (Renewable)"
cap label var _22_108919 "Gross heat production Autoproducer heat only plants - Municipal Waste (Renewable)"
cap label var _22_108921 "Gross electricity generation Main activity electricity only - Municipal Waste (Non-Renewable)"
cap label var _22_108922 "Gross electricity generation Main activity CHP plants - Municipal Waste (Non-Renewable)"
cap label var _22_108923 "Gross electricity generation Autoproducer electricity only - Municipal Waste (Non-Renewable)"
cap label var _22_108924 "Gross electricity generation Autoproducer CHP plants - Municipal Waste (Non-Renewable)"
cap label var _22_108926 "Gross heat production Main activity CHP plants - Municipal Waste (Non-Renewable)"
cap label var _22_108927 "Gross heat production Main activity heat only plants - Municipal Waste (Non-Renewable)"
cap label var _22_108928 "Gross heat production Autoproducer CHP plants - Municipal Waste (Non-Renewable)"
cap label var _22_108929 "Gross heat production Autoproducer heat only plants - Municipal Waste (Non-Renewable)"
cap label var _22_108931 "Gross electricity generation Main activity electricity only - Solid biofuels excluding charcoal"
cap label var _22_108932 "Gross electricity generation Main activity CHP plants - Solid biofuels excluding charcoal"
cap label var _22_108933 "Gross electricity generation Autoproducer electricity only - Solid biofuels excluding charcoal"
cap label var _22_108934 "Gross electricity generation Autoproducer CHP plants - Solid biofuels excluding charcoal"
cap label var _22_108936 "Gross heat production Main activity CHP plants - Solid biofuels excluding charcoal"
cap label var _22_108937 "Gross heat production Main activity heat only plants - Solid biofuels excluding charcoal"
cap label var _22_108938 "Gross heat production Autoproducer CHP plants - Solid biofuels excluding charcoal"
cap label var _22_108939 "Gross heat production Autoproducer heat only plants - Solid biofuels excluding charcoal"
cap label var _22_108941 "Gross electricity generation Main activity electricity only - Biogases"
cap label var _22_108942 "Gross electricity generation Main activity CHP plants - Biogases"
cap label var _22_108943 "Gross electricity generation Autoproducer electricity only - Biogases"
cap label var _22_108944 "Gross electricity generation Autoproducer CHP plants - Biogases"
cap label var _22_108946 "Gross heat production Main activity CHP plants - Biogases"
cap label var _22_108947 "Gross heat production Main activity heat only plants - Biogases"
cap label var _22_108948 "Gross heat production Autoproducer CHP plants - Biogases"
cap label var _22_108949 "Gross heat production Autoproducer heat only plants - Biogases"
cap label var _22_108951 "Gross electricity generation Main activity electricity only - Biodiesels"
cap label var _22_108952 "Gross electricity generation Main activity CHP plants - Biodiesels"
cap label var _22_108953 "Gross electricity generation Autoproducer electricity only - Biodiesels"
cap label var _22_108954 "Gross electricity generation Autoproducer CHP plants - Biodiesels"
cap label var _22_108956 "Gross heat production Main activity CHP plants - Biodiesels"
cap label var _22_108957 "Gross heat production Main activity heat only plants - Biodiesels"
cap label var _22_108958 "Gross heat production Autoproducer CHP plants - Biodiesels"
cap label var _22_108959 "Gross heat production Autoproducer heat only plants - Biodiesels"
cap label var _22_108961 "Gross electricity generation Main activity electricity only - Other Biogas"
cap label var _22_108962 "Gross electricity generation Main activity CHP plants - Other Biogas"
cap label var _22_108963 "Gross electricity generation Autoproducer electricity only - Other Biogas"
cap label var _22_108964 "Gross electricity generation Autoproducer CHP plants - Other Biogas"
cap label var _22_108966 "Gross heat production Main activity CHP plants - Other Biogas"
cap label var _22_108967 "Gross heat production Main activity heat only plants - Other Biogas"
cap label var _22_108968 "Gross heat production Autoproducer CHP plants - Other Biogas"
cap label var _22_108969 "Gross heat production Autoproducer heat only plants - Other Biogas"
cap label var _22_108971 "Gross electricity generation Main activity electricity only - Other Liquid Biofuels"
cap label var _22_108972 "Gross electricity generation Main activity CHP plants - Other Liquid Biofuels"
cap label var _22_108973 "Gross electricity generation Autoproducer electricity only - Other Liquid Biofuels"
cap label var _22_108974 "Gross electricity generation Autoproducer CHP plants - Other Liquid Biofuels"
cap label var _22_108976 "Gross heat production Main activity CHP plants - Other Liquid Biofuels"
cap label var _22_108977 "Gross heat production Main activity heat only plants - Other Liquid Biofuels"
cap label var _22_108978 "Gross heat production Autoproducer CHP plants - Other Liquid Biofuels"
cap label var _22_108979 "Gross heat production Autoproducer heat only plants - Other Liquid Biofuels"
cap label var B_100100 "Primary production"
cap label var B_100101 "Indigenous production"
cap label var B_100110 "Primary product receipts"
cap label var B_100111 "Direct use (Crude Oil & NGL)"
cap label var B_100112 "Direct use"
cap label var B_100113 "Primary product receipts (Crude oil & NGL)"
cap label var B_100115_S "Other production"
cap label var B_100200 "From Other Sources"
cap label var B_100210 "Recycled products"
cap label var B_100300 "Imports"
cap label var B_100310 "Imports from outside EU"
cap label var B_100320 "Imports from EU"
cap label var B_100500 "Exports"
cap label var B_100510 "Exports to EU"
cap label var B_100400 "Stock Changes"
cap label var B_100401_S "Stock draw"
cap label var B_100402_S "Stock build"
cap label var B_100420_S "Available from all sources"
cap label var B_100450_S "Into direct carry-over"
cap label var B_100460_S "From direct carry-over"
cap label var B_100800 "International Marine Bunkers"
cap label var B_100900 "Gross inland consumption"
cap label var B_100910 "Primary energy consumption"
cap label var B_100120_S "Production"
cap label var B_102201_S "Statistical difference - inflow"
cap label var B_102202_S "Statistical difference - outflow"
cap label var B_101550_S "Final consumption"
cap label var B_101251_S "Transformation losses"
cap label var B_101280_S "Exchanges, Transfers, Returns - losses"
cap label var B_101201_S "Transformation losses from Conventional Thermal Power Stations"
cap label var B_101202_S "Transformation losses from Nuclear Power Stations"
cap label var B_101204_S "Transformation losses from Coke Ovens"
cap label var B_101206_S "Transformation losses from Blast-furnaces"
cap label var B_101207_S "Transformation losses from Gas works"
cap label var B_101208_S "Transformation losses from Refineries"
cap label var B_101209_S "Transformation losses from District Heating Plants"
cap label var B_101211_S "Transformation losses from BKB / PB Plants"
cap label var B_101260_S "Other transformation losses"
cap label var B_101000 "Transformation input"
cap label var B_101002 "Transformation input - Nuclear Power Stations"
cap label var B_101004 "Transformation input in Coke Ovens"
cap label var B_101006 "Transformation input in Blast Furnaces"
cap label var B_101007 "Transformation input in Gas Works"
cap label var B_101008 "Transformation input in Refineries"
cap label var B_101010 "Transformation input in Patent Fuel Plants"
cap label var B_101011 "Transformation input in BKB / PB Plants"
cap label var B_101012 "Transformation input in Coal Liquefaction Plants"
cap label var B_101013 "Transformation input in For Blended Natural Gas"
cap label var B_101015 "Transformation input in Charcoal production plants (transformation)"
cap label var B_101016 "Transformation input in Gas-to-Liquids (GTL) Plants (Transformation)"
cap label var B_101017 "Transformation input - Used for electricity generation"
cap label var B_101020 "Non-specified Transformation input"
cap label var B_101001 "Transformation input - Conventional Thermal Power Stations"
cap label var B_101021 "Transformation input in Main Activity Producer Conventional Power Stations"
cap label var B_101031 "Transformation input in Main Activity Producer Electricity Plants"
cap label var B_101032 "Transformation input in Main Activity Producer CHP Plants"
cap label var B_101022 "Transformation input in Autoproducer Conventional Power Stations"
cap label var B_101034 "Transformation input in Autoproducer Electricity Plants"
cap label var B_101035 "Transformation input in Autoproducer CHP Plants"
cap label var B_101009 "Transformation input - District heating plants"
cap label var B_101038 "Transformation input in Main Activity Producer Heat Plants"
cap label var B_101039 "Transformation input in Autoproducer Heat Plants"
cap label var B_101050_S "Gross transformation input"
cap label var B_101051_S "Net transformation input"
cap label var B_101060_S "Other transformation input"
cap label var B_101080_S "Exchanges, Transfers, Returns - input"
cap label var B_101085_S "Transformation backflow"
cap label var B_101100 "Transformation output"
cap label var B_101101 "Transformation output - Conventional Thermal Power Stations"
cap label var B_101109 "Transformation output - District Heating Plants"
cap label var B_101121 "Transformation output - Main Activity Conventional Thermal Power Stations"
cap label var B_101122 "Transformation output - Autoproducer Conventional Thermal Power Stations"
cap label var B_101102 "Transformation output - Nuclear Power Stations"
cap label var B_101104 "Transformation output from Coke Ovens"
cap label var B_101106 "Transformation output from Blast Furnaces"
cap label var B_101107 "Transformation output from Gas Works"
cap label var B_101108 "Transformation output from Refineries"
cap label var B_101110 "Transformation output from Patent Fuel Plants"
cap label var B_101111 "Transformation output from BKB / PB Plants"
cap label var B_101115 "Transformation output from Charcoal production plants"
cap label var B_101150_S "Gross transformation output"
cap label var B_101151_S "Net transformation output"
cap label var B_101160_S "Other transformation output"
cap label var B_101180_S "Exchanges, Transfers, Returns - output"
cap label var B_101195_S "Available after transformation"
cap label var B_101200 "Exchanges, Transfers, Returns"
cap label var B_101210 "Interproduct transfers"
cap label var B_101220 "Products transferred"
cap label var B_101230 "Returns from petrochemical industry"
cap label var _17_107301 "Production in Pumped storage power stations"
cap label var _17_107302 "Used for pumped storage"
cap label var B_101300 "Consumption in Energy Sector"
cap label var B_101301 "Own Use in Electricity, CHP and Heat Plants"
cap label var B_101302 "Pumped storage power stations balance"
cap label var B_101305 "Consumption in Oil and gas extraction"
cap label var B_101307 "Consumption in Petroleum Refineries"
cap label var B_101308 "Consumption in Nuclear industry"
cap label var B_101310 "Consumption in Coal Mines"
cap label var B_101311 "Consumption in Patent Fuel Plants"
cap label var B_101312 "Consumption in Coke Ovens"
cap label var B_101313 "Consumption in BKB / PB Plants"
cap label var B_101314 "Consumption in Gas Works"
cap label var B_101315 "Consumption in Blast Furnaces"
cap label var B_101316 "Consumption in Coal Liquefaction Plants"
cap label var B_101317 "Consumption in Liquefaction (LNG) / regasification plants"
cap label var B_101318 "Consumption in Gasification plants for biogas"
cap label var B_101319 "Consumption in Gas-to-liquids (GTL) plants (energy)"
cap label var B_101320 "Consumption in Non-specified (Energy)"
cap label var B_101321 "Consumption in Charcoal production plants (Energy)"
cap label var B_101322 "Used for heat pumps"
cap label var B_101323 "Used for electric boilers"
cap label var B_101400 "Distribution Losses"
cap label var B_101500 "Energy Available for Final Consumption"
cap label var B_101550 "Energy dependence"
cap label var B_101600 "Final Non-energy Consumption"
cap label var B_101601 "Final Non-energy Consumption - of which Non-Energy Use In The Petrochemical Sector"
cap label var B_101603 "Non-energy use in Transformation sector"
cap label var B_101604 "Non-energy use in Energy sector"
cap label var B_101605 "Non-energy use in Industry sector"
cap label var B_101606 "Non-energy use in Transport Sector"
cap label var B_101607 "Non-energy use in Other Sectors"
cap label var B_101608 "Non-energy use in Industry, Transformation & Energy Sectors"
cap label var B_101610_S "Non-energy use - miscellaneous"
cap label var B_101700 "Final Energy Consumption"
cap label var B_101800 "Final Energy Consumption - Industry"
cap label var B_101805 "Iron and Steel"
cap label var B_101810 "Non-Ferrous Metals"
cap label var B_101815 "Chemical and Petrochemical"
cap label var B_101820 "Non-Metallic Minerals"
cap label var B_101825 "Mining and Quarrying"
cap label var B_101830 "Food and Tobacco"
cap label var B_101835 "Textile and Leather"
cap label var B_101840 "Paper, Pulp and Print"
cap label var B_101846 "Transport Equipment"
cap label var B_101847 "Machinery"
cap label var B_101851 "Wood and Wood Products"
cap label var B_101852 "Construction"
cap label var B_101853 "Non-specified (Industry)"
cap label var B_101900 "Final Energy Consumption - Transport"
cap label var B_101910 "Rail"
cap label var B_101920 "Road"
cap label var B_101931 "International aviation"
cap label var B_101932 "Domestic aviation"
cap label var B_101940 "Domestic Navigation"
cap label var B_101945 "Consumption in Pipeline transport"
cap label var B_101950 "Non-specified (Transport)"
cap label var B_102000 "Final Energy Consumption - Other Sectors"
cap label var B_102010 "Residential"
cap label var B_102020 "Fishing"
cap label var B_102030 "Agriculture/Forestry"
cap label var B_102035 "Services"
cap label var B_102040 "Non-specified (Other)"
cap label var B_102200 "Statistical Difference"
cap label var _10_105003 "Fuel stocks in Public Thermal Power Stations at the end of the period"
cap label var _10_106101 "Total opening stocks on national territory"
cap label var _10_128101 "Stock levels / Opening / All stocks on national territory"
cap label var _10_106102 "Total closing stocks on national territory"
cap label var _10_128201 "Stock levels / Closing / All stocks on national territory"
cap label var B_107200 "Available for the internal market"
cap label var B_109013 "Backflows from Petrochemical Sector to Refineries"
cap label var _10_196102 "Closing Stocks"
cap label var B_105122 "Deliveries of Automotive LPG"
cap label var B_105105 "Deliveries to Coking Plants"
cap label var B_105106 "Deliveries to Iron & Steel industry"
cap label var B_105102 "Deliveries to Main Activity Producer Power Plants"
cap label var B_105110 "Deliveries to Others (services, households, etc.)"
cap label var B_105112 "Deliveries to Patent Fuel Plants"
cap label var B_105120 "Deliveries to Total Industry"
cap label var B_105123 "Deliveries to power generation"
cap label var B_195500 "Demand"
cap label var B_109010 "Gross Deliveries to Petrochemical Sector"
cap label var _15_107000 "Gross electricity generation - Total"
cap label var _15_107001 "Gross electricity generation - Hydro"
cap label var _15_107002 "Gross electricity generation - Geothermal"
cap label var _15_107003 "Gross electricity generation - Nuclear"
cap label var _15_107004 "Gross electricity generation - Conventional Thermal"
cap label var _15_107005 "Gross electricity generation - Wind"
cap label var _15_107301 "Gross electricity generation - Hydro (of which from pumped storage)"
cap label var _16_107100B "Net electricity generation - Total"
cap label var _16_107101 "Net electricity generation - Hydro"
cap label var _16_107101A "Net electricity generation of pure hydro plants"
cap label var _16_107101B "Net electricity generation of mixed hydro plants"
cap label var _16_107101C "Net electricity generation of pure pumped storage hydro plants"
cap label var _16_107102 "Net electricity generation - Geothermal"
cap label var _16_107103 "Net electricity generation - Nuclear"
cap label var _16_107104 "Net electricity generation - Conventional Thermal"
cap label var _16_107104A "Net electricity generation from combustion of coal"
cap label var _16_107104B "Net electricity generation from combustion of oil"
cap label var _16_107104C "Net electricity generation from combustion of natural gas"
cap label var _16_107104D "Net electricity generation from combustion of renewables"
cap label var _16_107104E "Net electricity generation from combustion of other non-renewable fuels"
cap label var _16_107105 "Net electricity generation - Wind"
cap label var _16_107105A "Net electricity generation from wind onshore"
cap label var _16_107105B "Net electricity generation from wind offshore"
cap label var _16_107105C "Net electricity generation from solar radiation"
cap label var _16_107105C1 "Net electricity generation from solar photovoltaic installations"
cap label var _16_107105C2 "Net electricity generation from solar thermal plants"
cap label var _16_107105D "Net electricity generation from tide, wave, ocean and other non-combustible sources"
cap label var _16_107105E "Net electricity generation not elsewhere specified"
cap label var B_150201 "From Other Sources - of which From Oil Products"
cap label var B_150202 "From Other Sources - of which From Natural Gas"
cap label var B_150203 "From Other Sources - of which From Renewables"
cap label var B_150204 "Other Sources - of which From Coal"
cap label var B_190100 "Primary Production"
cap label var B_190300 "Imports"
cap label var B_190400 "Stock Changes"
cap label var B_190500 "Exports"
cap label var B_190600 "Net Imports"
cap label var B_190900 "Supply"
cap label var B_191008 "Refinery Intake"
cap label var B_191108 "Refinery Output"
cap label var B_197000 "Total gross production"
cap label var B_105200 "Gross Inland Deliveries Observed"
cap label var B_101401 "Memo Item:       Refinery Losses"
cap label var B_105121 "Memo Items:7                    Deliveries to International Aviation"
cap label var B_101103 "Transformation output - Patent Fuel / BKB plants"
cap label var B_105000 "Gross inland deliveries (calculated)"
cap label var D_100910 "Distance to target - Primary energy consumption"
cap label var D_101700 "Distance to target - Final energy consumption"
cap label var HDD "Heating degree days"
cap label var CDD "Cooling degree days"
cap label var COMP_NR "Number of reporting companies"
cap label var API_DEG "API Gravity - degree"
cap label var SULPH_PC "Sulphur content - %"
cap label var VOL_THS_BBL "Volume - thousand barrels"
cap label var VAL_THS_USD "Value - thousand USD"
cap label var AVGPRC_USD_BBL "Average price - USD per barrel"
cap label var AVGPRC_USD_T "Average price - USD per tonne"
cap label var WT_THS_T "Weight - thousand tonnes"
