cap label var TOTAL "Total"
cap label var EF0 "General Programmes"
cap label var EF01 "Basic/broad, general programmes"
cap label var EF010 "Basic/broad, general programmes"
cap label var EF08 "Literacy and numeracy"
cap label var EF080 "Literacy and numeracy"
cap label var EF09 "Personal skills/development"
cap label var EF090_347 "Personal development, Working life"
cap label var EF090 "Personal skills/development"
cap label var EF1 "Education"
cap label var EF14 "Teacher training and education science"
cap label var EF140 "Teacher training and education science (broad programmes)"
cap label var EF141 "Teaching and training"
cap label var EF142 "Education Science"
cap label var EF143 "Training for pre-school teachers"
cap label var EF144 "Training for teachers at basic levels"
cap label var EF145 "Training for teachers with subject specialisation"
cap label var EF146 "Training for teachers of vocational subjects"
cap label var EF2 "Humanities and arts"
cap label var EF21 "Arts"
cap label var EF210 "Arts (broad programmes)"
cap label var EF211 "Fine arts"
cap label var EF212 "Music and performing arts"
cap label var EF213 "Audio-visual techniques and media production"
cap label var EF214 "Design"
cap label var EF215 "Craft skills"
cap label var EF22 "Humanities"
cap label var EF220 "Humanities (broad programmes)"
cap label var EF221 "Religion"
cap label var EF222_223 "Languages (foreign + mother tongue)"
cap label var EF222 "Foreign languages"
cap label var EF223 "Mother tongue"
cap label var EF224 "History, philosophy and related subjects"
cap label var EF225 "History and archaeology"
cap label var EF226 "Philosophy and ethics"
cap label var EF3 "Social sciences, business and law"
cap label var EF31 "Social and behavioural science"
cap label var EF310 "Social and behavioural sciences (broad programmes)"
cap label var EF311 "Psychology"
cap label var EF312 "Sociology and cultural studies"
cap label var EF313 "Political science and civics"
cap label var EF314 "Economics"
cap label var EF32 "Journalism and information"
cap label var EF321 "Journalism and reporting"
cap label var EF322 "Library, information, archive"
cap label var EF34 "Business and administration"
cap label var EF340 "Business and administration (broad programmes)"
cap label var EF341_342 "Sales and marketing"
cap label var EF341 "Wholesale and retail sales"
cap label var EF342 "Marketing and advertising"
cap label var EF343_346 "Accounting and finance, management and administration, secretarial and office work computing"
cap label var EF343_344 "Accounting and finance"
cap label var EF343 "Finance, banking, insurance"
cap label var EF344 "Accounting and taxation"
cap label var EF345 "Management and administration"
cap label var EF346 "Secretarial and office work"
cap label var EF347 "Working life"
cap label var EF38 "Law"
cap label var EF380 "Law"
cap label var EF4_5 "Science, mathematics and computing, engineering, manufacturing and construction"
cap label var EF4 "Science, mathematics and computing"
cap label var EF42 "Life science"
cap label var EF421 "Biology and biochemistry"
cap label var EF422 "Environmental science"
cap label var EF44 "Physical science"
cap label var EF440 "Physical sciences (broad programmes)"
cap label var EF441 "Physics"
cap label var EF442 "Chemistry"
cap label var EF443 "Earth science"
cap label var EF46 "Mathematics and statistics"
cap label var EF461 "Mathematics"
cap label var EF462 "Statistics"
cap label var EF48 "Computing"
cap label var EF481 "Computer science"
cap label var EF482 "Computer use"
cap label var EF5 "Engineering, manufacturing and construction"
cap label var EF52_54 "Engineering and manufacturing"
cap label var EF52 "Engineering and engineering trades"
cap label var EF520 "Engineering and engineering trades (broad programmes)"
cap label var EF521 "Mechanics and metal work"
cap label var EF522 "Electricity and energy"
cap label var EF523 "Electronics and automation"
cap label var EF524 "Chemical and process"
cap label var EF525 "Motor vehicles, ships and aircraft"
cap label var EF54 "Manufacturing and processing"
cap label var EF540 "Manufacturing and processing (broad programmes)"
cap label var EF541 "Food processing"
cap label var EF542 "Textiles, clothes, footwear, leather"
cap label var EF543 "Materials (wood, paper, plastic, glass)"
cap label var EF544 "Mining and extraction"
cap label var EF58 "Architecture and building"
cap label var EF581 "Architecture and town planning"
cap label var EF582 "Building and civil engineering"
cap label var EF6 "Agriculture and veterinary"
cap label var EF62 "Agriculture, forestry and fishery"
cap label var EF620 "Agriculture, forestry and fishery (broad programmes)"
cap label var EF621 "Crop and livestock production"
cap label var EF622 "Horticulture"
cap label var EF623 "Forestry"
cap label var EF624 "Fisheries"
cap label var EF64 "Veterinary"
cap label var EF641 "Veterinary"
cap label var EF7 "Health and Welfare"
cap label var EF72 "Health"
cap label var EF720 "Health (broad programmes)"
cap label var EF721 "Medicine"
cap label var EF722 "Medical services"
cap label var EF723 "Nursing and caring"
cap label var EF724 "Dental studies"
cap label var EF725 "Medical diagnostic and treatment technology"
cap label var EF726 "Therapy and rehabilitation"
cap label var EF727 "Pharmacy"
cap label var EF76 "Social services"
cap label var EF761 "Child care and youth services"
cap label var EF762 "Social work and counselling"
cap label var EF8 "Services"
cap label var EF81_84_86 "Personnal services, transport services, security services"
cap label var EF81 "Personal services"
cap label var EF810 "Personal services (broad programmes)"
cap label var EF811 "Hotel, restaurant and catering"
cap label var EF812 "Travel, tourism and leisure"
cap label var EF813 "Sports"
cap label var EF814 "Domestic services"
cap label var EF815 "Hair and beauty services"
cap label var EF84 "Transport services"
cap label var EF840 "Transport services"
cap label var EF85_862 "Environment protection, occupational health and safety"
cap label var EF85 "Environmental protection"
cap label var EF850 "Environmental protection (broad programmes)"
cap label var EF851 "Environmental protection technology"
cap label var EF852 "Natural environments and wildlife"
cap label var EF853 "Community sanitation services"
cap label var EF86 "Security services"
cap label var EF860 "Security services (broad programmes)"
cap label var EF861 "Protection of persons and property"
cap label var EF862 "Occupational health and safety"
cap label var EF863 "Military and defence"
cap label var OTH "Others"
cap label var NRP "No response"
cap label var UNK "Unknown"
cap label var READ "Reading"
cap label var SCI "Science"
