cap label var TOTAL "Total"
cap label var BASIC "Basic training"
cap label var PRACT "Practical experience only"
cap label var FULL "Full agricultural training"
cap label var CO_OF "CVT courses and/or other forms of CVT"
cap label var CO "CVT courses"
cap label var CO_INT "CVT courses - internal"
cap label var CO_EXT "CVT courses - external"
cap label var CO_HSW "Obligatory courses on health and safety at work"
cap label var OF "Other forms of CVT"
cap label var OF_GUID "Other forms of CVT - guided-on-the-job training"
cap label var OF_JROT "Other forms of CVT - job rotation, exchanges or secondments"
cap label var OF_CONF "Other forms of CVT - training at conferences, workshops, trade fairs and lectures"
cap label var OF_LQC "Other forms of CVT - learning/quality circles"
cap label var OF_SDL "Other forms of CVT - self-directed learning"
cap label var NO_CVT "No CVT"
cap label var CO_LANG "Language course"
cap label var CO_LANG_G "General language course"
cap label var CO_LANG_WS "Work-specific language course"
cap label var NO_CO_LANG "No language course"
cap label var FE_NFE "Formal and non-formal education and training"
cap label var FE "Formal education and training"
cap label var NFE "Non-formal education and training"
cap label var NFE_JB "Non-formal education and training - job-related"
cap label var NFE_JB_ES "Non-formal education and training - job-related and sponsored by the employer"
cap label var NFE_JB_ES_SAL "Non-formal education and training - job-related and sponsored by the employer (employees only)"
cap label var NFE_JB_NES "Non-formal education and training - job-related and not sponsored by the employer"
cap label var NFE_NJB "Non-formal education and training - not job-related"
cap label var NFE_NJB_ONL "Non-formal education and training - not job-related only"
cap label var NO_FE_NO_NFE "Neither formal nor non-formal education or training"
cap label var NO_FE "No formal education or training"
cap label var NO_NFE "No non-formal education or training"
cap label var INF "Informal learning"
cap label var INF_ONL "Informal learning only"
cap label var NO_LEARN "No learning activity"
cap label var NAP "Not applicable"
cap label var NRP "No response"
