cap label var LOAN "Loan finance"
cap label var EQUIT "Equity finance"
cap label var EQUIT_RNDINN "Equity finance for R&D or other innovation activities"
cap label var DEBT "Debt finance"
cap label var DEBT_RNDINN "Debt finance for R&D or other innovation activities"
cap label var OTH "Other"
