cap label var D0000 "Milk, cheese and eggs"
cap label var D0100 "Milk products"
cap label var D0100AD "Farm milk products delivered to dairies"
cap label var D0110 "Fresh products"
cap label var D0120 "Manufactured products"
cap label var D0200 "Milk products, other than"
cap label var D0210D "Milk products, other than drinking milk, cream, butter and cheese, delivered to dairies"
cap label var D0220D "Milk products, other than milk and cream, delivered to dairies"
cap label var D0230D "Other milk products (than milk, cream, skimmed milk and buttermilk) delivered to dairies"
cap label var D1000 "Raw milk and cream"
cap label var D1100 "Milk or raw milk"
cap label var D1100A "Raw milk, total available on farms"
cap label var D1100DU "Raw milk, total available on dairies  (=total used)"
cap label var D1100D "Raw milk delivered to dairies"
cap label var D1100F "Raw milk for feed"
cap label var D1100DLA "Raw milk, differences and losses on farms"
cap label var D1100DLD "Raw milk, differences and losses in dairies"
cap label var D1100OUD "Raw milk, other uses by dairies"
cap label var D1110 "Raw cows' milk"
cap label var D1110D "Raw cows' milk delivered to dairies"
cap label var D1110A "Raw cows' milk from farm"
cap label var D1111A "Dairy raw cows' milk from farm"
cap label var D1112A "Non-dairy raw cows' milk from farm"
cap label var D1120 "Ewes' milk"
cap label var D1120D "Ewes' milk delivered to dairies"
cap label var D1120A "Ewes' milk from farm"
cap label var D1130 "Goats' milk"
cap label var D1130D "Goats' milk delivered to dairies"
cap label var D1130A "Goats' milk from farm"
cap label var D1140D "Buffalos' milk delivered to dairies"
cap label var D1140A "Buffalos' milk from farm"
cap label var D1190 "Raw milk from other species"
cap label var D1200A "Raw cream from farm"
cap label var D1200D "Raw cream delivered to dairies"
cap label var D1200DME "Raw cream delivered to dairies (in milk equivalent)"
cap label var D2000 "Milk and cream, not concentrated nor containing added sugar or other sweetening matter"
cap label var D2000X "Milk and cream in bulk - exports"
cap label var D2000Y "Milk and cream in bulk - exports intra-EU"
cap label var D2100 "Drinking milk"
cap label var D2110 "Raw drinking milk"
cap label var D2110V "Drinking milk - direct sales"
cap label var D2110H "Drinking milk - home consumption"
cap label var D2120 "Whole milk"
cap label var D2120I "Imports of whole milk (including raw milk)"
cap label var D2120J "Imports (intra-EU) of whole milk (including raw milk)"
cap label var D2121 "Whole milk pasteurised"
cap label var D2122 "Whole milk sterilised"
cap label var D2123 "Whole milk uperised"
cap label var D2130 "Partly skimmed milk"
cap label var D2131 "Partly skimmed milk pasteurised"
cap label var D2132 "Partly skimmed milk sterilised"
cap label var D2133 "Partly skimmed milk uperised"
cap label var D2140_4200A "Skimmed milk and buttermilk, total available on farms"
cap label var D2140_4200RD "Skimmed milk and buttermilk returned by dairies"
cap label var D2140_4200BC "Skimmed milk and buttermilk - balance of cream deliveries"
cap label var D2140_4200AB "Skimmed milk and buttermilk from butter and cream production"
cap label var D2140_4200D "Skimmed milk and buttermilk delivered to dairies"
cap label var D2140 "Skimmed milk"
cap label var D2140RA "Skimmed milk - returned to the farm"
cap label var D2140I "Imports of skimmed milk"
cap label var D2140J "Imports (intra-EU) of skimmed milk"
cap label var D2141 "Skimmed milk pasteurised"
cap label var D2142 "Skimmed milk sterilised"
cap label var D2143 "Skimmed milk uperised"
cap label var D2200_6110A "Cream and butter from farm"
cap label var D2200 "Cream"
cap label var D2200V "Cream for direct consumption"
cap label var D2201 "Cream of fat content by weight not exceeding 29 %"
cap label var D2202 "Cream of fat content by weight over 29 %"
cap label var D2200IME "Imports of cream (in milk equivalent)"
cap label var D2200JME "Imports (intra-EU) of cream (in milk equivalent)"
cap label var D3000 "Milk and cream, concentrated or containing added sugar or other sweetening matter"
cap label var D3100 "Powder products"
cap label var D3100_X_3113 "Milk and cream powders, excluding skimmed milk powders"
cap label var D3110 "Milk powder"
cap label var D3111 "Whole milk powder"
cap label var D3112 "Partly skimmed milk powder"
cap label var D3113 "Skimmed milk powder"
cap label var D3120 "Cream milk powder"
cap label var D3130 "Buttermilk powder"
cap label var D3190 "Other powder products"
cap label var D3200 "Concentrated milk"
cap label var D3210 "Concentrated milk not sweetened"
cap label var D3220 "Concentrated milk sweetened"
cap label var D4000 "Buttermilk, curdled milk and cream, yogurt, kephir and other fermented or acidified milk and cream"
cap label var D4100 "Acidified milk (yoghurts and other)"
cap label var D4110 "Acidified milk with additives"
cap label var D4120 "Acidified milk without additives"
cap label var D4200 "Buttermilk"
cap label var D5000 "Whey"
cap label var D5100 "Whey (liquid)"
cap label var D5200 "Whey (concentrated)"
cap label var D5300 "Whey (in powder or in block)"
cap label var D5400 "Lactose (milk sugar)"
cap label var D5500 "Lactalbumin"
cap label var D6000 "Butter, incl. dehydrated butter and ghee, and other fats and oils derived from milk; dairy spreads"
cap label var D6100 "Butter"
cap label var D6100A "Farm butter"
cap label var D6100AD "Farm butter delivered to dairies"
cap label var D6110 "Traditional butter"
cap label var D6120 "Recombined butter"
cap label var D6130 "Whey butter"
cap label var D6200 "Rendered butter and butteroil"
cap label var D6900 "Other yellow fat dairy products"
cap label var D6910 "Reduced-fat butter"
cap label var D6990 "Other yellow fat dairy products (without reduced-fat butter)"
cap label var D7000 "Cheese and curd"
cap label var D7100 "Cheese"
cap label var D7100A "Farm cheese"
cap label var D7100AD "Farm cheese delivered to dairies"
cap label var D7110 "All types of cheese"
cap label var D7111 "Soft cheese"
cap label var D7112 "Medium soft cheese"
cap label var D7113 "Medium hard cheese"
cap label var D7114 "Hard cheese"
cap label var D7115 "Extra hard cheese"
cap label var D7116 "Fresh cheese"
cap label var D7120 "Cheese from animals"
cap label var D7121 "Cheese from cows'milk (pure)"
cap label var D7122 "Cheese from ewes milk (pure)"
cap label var D7123 "Cheese from goats milk (pure)"
cap label var D7129 "Others (cheese from buffalos'milk (pure) or mixed cheese)"
cap label var D7200 "Processed cheese"
cap label var D8000 "Eggs"
cap label var D8000H "Eggs for consumption"
cap label var D8100 "Fertilised eggs from domestic bird species, for incubation"
cap label var D8110 "Hens' eggs"
cap label var D8120 "Ducks' eggs"
cap label var D8130 "Geeses' eggs"
cap label var D8140 "Turkeys' eggs"
cap label var D8150 "Guinea fowls' eggs"
cap label var D8190 "Eggs from other species"
cap label var D8200 "Eggs in shell from domestic birdspecies,not for incubation"
cap label var D8210 "Hens' eggs"
cap label var D8290 "Eggs from other species"
cap label var D8300 "Eggs not in shell"
cap label var D9000 "Other milk products"
cap label var D9000I "Imports of other products"
cap label var D9000J "Imports (intra-EU) of other products"
cap label var D9100 "Drinks with a milk base"
cap label var D9200 "Other fresh products  (milk-based desserts, ice cream)"
cap label var D9300 "Caseins and caseinates"
cap label var D9400 "Other manufactured milk products"
cap label var D9500 "Other organic dairy products"
cap label var D9900A "Other products collected from farm"
cap label var D9910 "Honey"
