cap label var N1N "Produced non-financial assets (net)"
cap label var N1ON "Fixed assets and inventories (net)"
cap label var N11N "Total fixed assets (net)"
cap label var N11KN "Total Construction (net)"
cap label var N111N "Dwellings (net)"
cap label var N112N "Other buildings and structures (net)"
cap label var N1121N "Buildings other than dwellings (net)"
cap label var N1122N "Other structures (net)"
cap label var N11MN "Machinery and equipment and weapons systems (net)"
cap label var N1131N "Transport equipment (net)"
cap label var N1132N "ICT equipment (net)"
cap label var N11321N "Computer hardware (net)"
cap label var N11322N "Telecommunications equipment (net)"
cap label var N11ON "Other machinery and equipment and weapons systems (net)"
cap label var N115N "Cultivated biological resources (net)"
cap label var N117N "Intellectual property products (net)"
cap label var N1171N "Research and development (net)"
cap label var N1172N "Mineral exploration and evaluation (net)"
cap label var N1173N "Computer software and databases (net)"
cap label var N1174N "Entertainment, literary or artistic originals (net)"
cap label var N1179N "Other intellectual property products (net)"
cap label var N12N "Inventories  (net)"
cap label var N13N "Valuables (net)"
cap label var N1MN "Inventories and acquisitions less disposals of valuables (net)"
cap label var N2N "Non-produced non-financial assets (net)"
cap label var N21N "Natural resources (net)"
cap label var N211N "Land (net)"
cap label var N212N "Mineral and energy reserves (net)"
cap label var N21ON "Non-cultivated biological resources and water resources (net)"
cap label var N215N "Other natural resources (net)"
cap label var N22N "Contracts, leases and licences (net)"
cap label var N23N "Purchases less sales of goodwill and marketing assets (net)"
cap label var N1G "Produced non-financial assets (gross)"
cap label var N1OG "Fixed assets and inventories (gross)"
cap label var N11G "Total fixed assets (gross)"
cap label var N11KG "Total Construction (gross)"
cap label var N111G "Dwellings (gross)"
cap label var N112G "Other buildings and structures (gross)"
cap label var N1121G "Buildings other than dwellings (gross)"
cap label var N1122G "Other structures (gross)"
cap label var N11MG "Machinery and equipment and weapons systems (gross)"
cap label var N1131G "Transport equipment (gross)"
cap label var N1132G "ICT equipment (gross)"
cap label var N11321G "Computer hardware (gross)"
cap label var N11322G "Telecommunications equipment (gross)"
cap label var N11OG "Other machinery and equipment and weapons systems (gross)"
cap label var N115G "Cultivated biological resources (gross)"
cap label var N117G "Intellectual property products (gross)"
cap label var N1171G "Research and development (gross)"
cap label var N1172G "Mineral exploration and evaluation (gross)"
cap label var N1173G "Computer software and databases (gross)"
cap label var N1174G "Entertainment, literary or artistic originals (gross)"
cap label var N1179G "Other intellectual property products (gross)"
cap label var N12G "Inventories  (gross)"
cap label var N13G "Valuables (gross)"
cap label var N1MG "Inventories and acquisitions less disposals of valuables (gross)"
cap label var N2G "Non-produced non-financial assets (gross)"
cap label var N21G "Natural resources (gross)"
cap label var N211G "Land (gross)"
cap label var N212G "Mineral and energy reserves (gross)"
cap label var N21OG "Non-cultivated biological resources and water resources (gross)"
cap label var N215G "Other natural resources (gross)"
cap label var N22G "Contracts, leases and licences (gross)"
cap label var N23G "Purchases less sales of goodwill and marketing assets (gross)"
