cap label var TOTAL "Total (all currencies)"
cap label var EUR "Euro"
cap label var MIO_EUR "Million euro"
cap label var BGN "Bulgarian lev"
cap label var CZK "Czech koruna"
cap label var DKK "Danish krone"
cap label var HRK "Croatian kuna"
cap label var HUF "Hungarian forint"
cap label var PLN "Polish zloty"
cap label var RON "Romanian leu"
cap label var SEK "Swedish krona"
cap label var EU_OTH "National currency of EU Member States not belonging to the euro area"
cap label var ATS "Austrian schilling"
cap label var BEF "Belgian franc"
cap label var CYP "Cyprus pound"
cap label var DEM "German mark"
cap label var EEK "Estonian Kroon"
cap label var ESP "Spanish peseta"
cap label var FIM "Finnish markka"
cap label var FRF "French franc"
cap label var GRD "Greek drachma"
cap label var IEP "Irish pound"
cap label var ITL "Italian lira"
cap label var LTL "Lithuanian litas"
cap label var LUF "Luxembourg franc"
cap label var LVL "Latvian lats"
cap label var MTL "Maltese lira"
cap label var NLG "Dutch guilder"
cap label var PTE "Portuguese escudo"
cap label var SIT "Slovenian tolar"
cap label var SKK "Slovak koruna"
cap label var CHF "Swiss franc"
cap label var ISK "Icelandic króna"
cap label var NOK "Norwegian krone"
cap label var GBP "Pound sterling"
cap label var ALL "Albanian lek"
cap label var MKD "North Macedonian denar"
cap label var RSD "Serbian dinar"
cap label var TRY "Turkish lira"
cap label var AED "UAE dirham"
cap label var AFN "Afghan afghani"
cap label var AMD "Armenian dram"
cap label var ANG "Netherlands Antillean guilder"
cap label var AOA "Angolan kwanza"
cap label var ARS "Argentine peso"
cap label var AUD "Australian dollar"
cap label var AWG "Aruban guilder"
cap label var AZN "Azerbaijan manat"
cap label var BAM "Bosnia and Herzegovina convertible mark"
cap label var BBD "Barbados dollar"
cap label var BDT "Bangladeshi taka"
cap label var BHD "Bahraini dinar"
cap label var BIF "Burundi franc"
cap label var BMD "Bermuda dollar"
cap label var BND "Brunei dollar"
cap label var BOB "Bolivian boliviano"
cap label var BRL "Brazilian real"
cap label var BSD "Bahamian dollar"
cap label var BTN "Bhutan ngultrum"
cap label var BWP "Botswana pula"
cap label var BYN "Belarusian rouble"
cap label var BZD "Belize dollar"
cap label var CAD "Canadian dollar"
cap label var CDF "Congolese franc"
cap label var CLP "Chilean peso"
cap label var CNY "Chinese renminbi-yuan"
cap label var COP "Colombian peso"
cap label var CRC "Costa Rican colón"
cap label var CUC "Cuban convertible peso"
cap label var CUP "Cuban peso"
cap label var CVE "Cabo Verde escudo"
cap label var DJF "Djibouti franc"
cap label var DOP "Dominican peso"
cap label var DZD "Algerian dinar"
cap label var EGP "Egyptian pound"
cap label var ERN "Eritrean nakfa"
cap label var ETB "Ethiopian birr"
cap label var FJD "Fiji dollar"
cap label var FKP "Falkland Islands pound"
cap label var GEL "Georgian lari"
cap label var GHS "Ghana cedi"
cap label var GIP "Gibraltar pound"
cap label var GMD "Gambian dalasi"
cap label var GNF "Guinean franc"
cap label var GTQ "Guatemalan quetzal"
cap label var GYD "Guyana dollar"
cap label var HKD "Hong Kong dollar"
cap label var HNL "Honduran lempira"
cap label var HTG "Haitian gourde"
cap label var IDR "Indonesian rupiah"
cap label var ILS "Israeli shekel"
cap label var INR "Indian rupee"
cap label var IQD "Iraqi dinar"
cap label var IRR "Iranian rial"
cap label var JMD "Jamaica dollar"
cap label var JOD "Jordanian dinar"
cap label var JPY "Japanese yen"
cap label var KES "Kenyan shilling"
cap label var KGS "Kyrgyzstanian som"
cap label var KHR "Cambodian riel"
cap label var KMF "Comorian franc"
cap label var KPW "North Korean won"
cap label var KRW "South Korean won"
cap label var KWD "Kuwaiti dinar"
cap label var KYD "Cayman Islands dollar"
cap label var KZT "Kazakhstan tenge"
cap label var LAK "Lao kip"
cap label var LBP "Lebanese pound"
cap label var LKR "Sri Lankan rupee"
cap label var LRD "Liberian dollar"
cap label var LSL "Lesotho loti"
cap label var LYD "Libyan dinar"
cap label var MAD "Moroccan dirham"
cap label var MDL "Moldovan leu"
cap label var MGA "Malagasy ariary"
cap label var MMK "Myanmar kyat"
cap label var MNT "Mongolian tugrik"
cap label var MOP "Macau pataca"
cap label var MRU "Mauritanian ouguiya"
cap label var MUR "Mauritian rupee"
cap label var MVR "Maldive rufiyaa"
cap label var MWK "Malawian kwacha"
cap label var MXN "Mexican peso"
cap label var MYR "Malaysian ringgit"
cap label var MZN "Mozambique metical"
cap label var NAD "Namibian dollar"
cap label var NGN "Nigerian naira"
cap label var NIO "Nicaraguan córdoba oro"
cap label var NPR "Nepalese rupee"
cap label var NZD "New Zealand dollar"
cap label var OMR "Omani rial"
cap label var PAB "Panamanian balboa"
cap label var PEN "Peruvian sol"
cap label var PGK "Papua New Guinea kina"
cap label var PHP "Philippine peso"
cap label var PKR "Pakistani rupee"
cap label var PYG "Paraguay guaraní"
cap label var QAR "Qatari riyal"
cap label var RUB "Russian rouble"
cap label var RWF "Rwandese franc"
cap label var SAR "Saudi riyal"
cap label var SBD "Solomon Islands dollar"
cap label var SCR "Seychelles rupee"
cap label var SDG "Sudanese pound"
cap label var SGD "Singapore dollar"
cap label var SHP "Saint Helena pound"
cap label var SLL "Sierra Leonean leone"
cap label var SOS "Somali shilling"
cap label var SRD "Surinamese dollar"
cap label var SSP "South Sudanese pound"
cap label var STN "Sao Tomé and Principe dobra"
cap label var SVC "Salvadorian colón"
cap label var SYP "Syrian pound"
cap label var SZL "Swaziland lilangeni (Eswatini)"
cap label var THB "Thai baht"
cap label var TJS "Tajikistani somoni"
cap label var TMT "Turkmen manat"
cap label var TND "Tunisian dinar"
cap label var TOP "Tonga pa'anga"
cap label var TTD "Trinidad and Tobago dollar"
cap label var TWD "New Taiwan dollar"
cap label var TZS "Tanzanian shilling"
cap label var UAH "Ukraine hryvnia"
cap label var UGX "Uganda shilling"
cap label var USD "US dollar"
cap label var UYU "Uruguayan peso"
cap label var UZS "Uzbekistan sum"
cap label var VES "Venezuelan Bolívar soberano"
cap label var VND "Vietnamese dong"
cap label var VUV "Vanuatu vatu"
cap label var WST "Samoan tala"
cap label var XAF "CFA franc (BEAC)"
cap label var XCD "East Caribbean dollar"
cap label var XOF "CFA franc (BCEAO)"
cap label var XPF "CFP franc (French Polynesia, New Caledonia, Wallis and Futuna)"
cap label var YER "Yemeni rial"
cap label var ZAR "South African rand"
cap label var ZMW "Zambian kwacha"
cap label var ZWL "Zimbabwe dollar"
cap label var XDR "Special Drawing Right (SDR)"
cap label var PPS "Purchasing Power Standard"
cap label var MIO_PPS "Million Purchasing Power Standards"
cap label var PC "Percentage"
cap label var NAC "National currency"
cap label var MIO_NAC "Million units of national currency"
cap label var NAT "National currency (former currencies of the euro area countries)"
cap label var FOR "Foreign currency"
cap label var OTH "Other currencies"
cap label var NAP "Not applicable"
cap label var UNK "Unknown"
