cap label var _010 "Current + capital account"
cap label var _011 "Current and capital transfers"
cap label var _993 "Current account"
cap label var _100 "Current account, Goods"
cap label var _110 "Current account, Goods, General merchandise"
cap label var _150 "Current account, Goods, Goods for processing"
cap label var _151 "Current account, Goods, Goods for processing, Abroad"
cap label var _152 "Current account, Goods, Goods for processing, In the compiling economy"
cap label var _160 "Current account, Goods, Repairs on goods"
cap label var _170 "Current account, Goods, Goods procured  in ports by carriers"
cap label var _180 "Current account, Goods, Non monetary gold"
cap label var _181 "Current account, Goods, Non monetary gold, Gold held as a store of value"
cap label var _182 "Current account, Goods, Non monetary gold, Other non monetary gold"
cap label var _200 "Current account, Services"
cap label var _201 "Current account, Services, Branding, Quasi-transit adjustment"
cap label var _205 "Current account, Services, Transportation"
cap label var _206 "Current account, Services, Transportation, Sea transport"
cap label var _207 "Current account, Services, Transportation, Sea transport, Passenger transport on sea"
cap label var _208 "Current account, Services, Transportation, Sea transport, Freight transport on sea"
cap label var _209 "Current account, Services, Transportation, Sea transport, Supporting, auxiliary and other sea transport services"
cap label var _210 "Current account, Services, Transportation, Air transport"
cap label var _211 "Current account, Services, Transportation, Air transport, Passenger transport by air"
cap label var _212 "Current account, Services, Transportation, Air transport, Freight transport by air"
cap label var _213 "Current account, Services, Transportation, Air transport, Supporting, auxiliary and other air transport services"
cap label var _214 "Current account, Services, Transportation, Other transport (other than sea and air)"
cap label var _215 "Current account, Services, Transportation, Other transport (other than sea and air), Passenger on other transport"
cap label var _216 "Current account, Services, Transportation, Other transport (other than sea and air), Freight on other transport"
cap label var _217 "Current account, Services, Transportation, Other transport (other than sea and air), Other of other transport"
cap label var _218 "Current account, Services, Transportation, Other transport (other than sea and air) - extended classification, Space transport"
cap label var _219 "Current account, Services, Transportation, Other transport (other than sea and air) - extended classification, Rail transport"
cap label var _220 "Current account, Services, Transportation, Other transport (other than sea and air) - extended classification, Rail transport, Passenger on rail"
cap label var _221 "Current account, Services, Transportation, Other transport (other than sea and air) - extended classification, Rail transport, Freight on rail"
cap label var _222 "Current account, Services, Transportation, Other transport (other than sea and air) - extended classification, Rail transport, Supporting, auxiliary and other rail transport services"
cap label var _223 "Current account, Services, Transportation, Other transport (other than sea and air) - extended classification, Road transport"
cap label var _224 "Current account, Services, Transportation, Other transport (other than sea and air) - extended classification, Road transport, Passenger on road"
cap label var _225 "Current account, Services, Transportation, Other transport (other than sea and air) - extended classification, Road transport, Freight on road"
cap label var _226 "Current account, Services, Transportation, Other transport (other than sea and air) - extended classification, Road transport, Supporting, auxiliary and other road transport services"
cap label var _227 "Current account, Services, Transportation, Other transport (other than sea and air) - extended classification, Inland waterway transport"
cap label var _228 "Current account, Services, Transportation, Other transport (other than sea and air) - extended classification, Inland waterway transport, Passenger on inland waterway"
cap label var _229 "Current account, Services, Transportation, Other transport (other than sea and air) - extended classification, Inland waterway transport, Freight on inland waterway"
cap label var _230 "Current account, Services, Transportation, Other transport (other than sea and air) - extended classification, Inland waterway transport, Supporting, auxiliary and other inland waterway transport services"
cap label var _231 "Current account, Services, Transportation, Other transport (other than sea and air) - extended classification, Pipeline transport"
cap label var _232 "Current account, Services, Transportation, Other transport (other than sea and air) - extended classification, Other supporting and auxiliary transport services"
cap label var _236 "Current account, Services, Travel"
cap label var _237 "Current account, Services, Travel, Business travel"
cap label var _238 "Current account, Services, Travel, Business travel, Expenditure by seasonal and border workers"
cap label var _239 "Current account, Services, Travel, Business travel, Other business travel"
cap label var _240 "Current account, Services, Travel, Personal travel"
cap label var _241 "Current account, Services, Travel, Personal travel, Health-related expenditure"
cap label var _242 "Current account, Services, Travel, Personal travel, Education related expenditure"
cap label var _243 "Current account, Services, Travel, Personal travel, Other personal travel"
cap label var _981 "Current account, Services, Other services"
cap label var _245 "Current account, Services, Other services, Communications services"
cap label var _246 "Current account, Services, Other services, Communications services, Postal and courier services"
cap label var _958 "Current account, Services, Communications services, Postal and courier services, Postal services"
cap label var _959 "Current account, Services, Communications services, Postal and courier services, Courier services"
cap label var _247 "Current account, Services, Other services, Communications services, Telecommunication services"
cap label var _249 "Current account, Services, Other services, Construction services"
cap label var _250 "Current account, Services, Other services, Construction services, Construction abroad"
cap label var _251 "Current account, Services, Other services, Construction services, Construction in the compiling economy"
cap label var _253 "Current account, Services, Other services, Insurance services"
cap label var _254 "Current account, Services, Other services, Insurance services, Life insurance and pension funding"
cap label var _255 "Current account, Services, Other services, Insurance services, Freight insurance"
cap label var _256 "Current account, Services, Other services, Insurance services, Other direct insurance"
cap label var _257 "Current account, Services, Other services, Insurance services, Reinsurance"
cap label var _258 "Current account, Services, Other services, Insurance services, Auxiliary services"
cap label var _260 "Current account, Services, Other services, Financial services"
cap label var _262 "Current account, Services, Other services, Computer and information services"
cap label var _263 "Current account, Services, Other services, Computer and information services, Computer services"
cap label var _264 "Current account, Services, Other services, Computer and information services, Information services"
cap label var _889 "Current account, Services, Other services, Computer and information services, Information services, News agency services"
cap label var _890 "Current account, Services, Other services, Computer and information services, Information services, Other information provision services"
cap label var _266 "Current account, Services, Other services, Royalties and license fees"
cap label var _891 "Current account, Services, Other services, Royalties and license fees, Franchises and similar rights"
cap label var _892 "Current account, Services, Other services, Royalties and license fees, Other royalties and license fees"
cap label var _268 "Current account, Services, Other services, Other business services"
cap label var _269 "Current account, Services, Other services, Other business services, Merchanting and other trade-related services"
cap label var _270 "Current account, Services, Other services, Other business services, Merchanting and other trade-related services, Merchanting"
cap label var _271 "Current account, Services, Other services, Other business services, Merchanting and other trade-related services, Other trade-related services"
cap label var _272 "Current account, Services, Other services, Other business services, Operational leasing services"
cap label var _273 "Current account, Services, Other services, Other business services, Miscellaneous business, professional and technical services"
cap label var _274 "Current account, Services, Other services, Other business services, Miscellaneous business, professional and technical services, Legal, accounting, management and public relations services"
cap label var _275 "Current account, Services, Other services, Other business services, Miscellaneous business, professional and technical services, Legal, accounting, management and public relations services, Legal services"
cap label var _276 "Current account, Services, Other services, Other business services, Miscellaneous business, professional and technical services, Legal, accounting, management and public relations services, Accounting, auditing, book-keeping and tax consulting services"
cap label var _277 "Current account, Services, Other services, Other business services, Miscellaneous business, professional and technical services, Legal, accounting, management and public relations services, Business and management consultancy, public relations services"
cap label var _278 "Current account, Services, Other services, Other business services, Miscellaneous business, professional and technical services, Advertising, market research and public opinion polling"
cap label var _279 "Current account, Services, Other services, Other business services, Miscellaneous business, professional and technical services, Research and development services"
cap label var _280 "Current account, Services, Other services, Other business services, Miscellaneous business, professional and technical services, Architectural, engineering and other technical consultancy"
cap label var _281 "Current account, Services, Other services, Other business services, Miscellaneous business, professional and technical services, Agricultural, mining , and on-site processing"
cap label var _282 "Current account, Services, Other services, Other business services, Miscellaneous business, professional and technical services, Agricultural, mining , and on-site processing, Waste treatment and depolution"
cap label var _283 "Current account, Services, Other services, Other business services, Miscellaneous business, professional and technical services, Agricultural, mining , and on-site processing, Other agricultural, mining and on-site processing"
cap label var _284 "Current account, Services, Other services, Other business services, Miscellaneous business, professional and technical services, Other miscellaneous business, professional and technical services"
cap label var _285 "Current account, Services, Other services, Other business services, Miscellaneous business, professional and technical services, Services between affiliated enterprises, n.i.e."
cap label var _287 "Current account, Services, Other services, Personal, cultural and recreational services"
cap label var _288 "Current account, Services, Other services, Personal, cultural and recreational services, Audio-visual and related services"
cap label var _289 "Current account, Services, Other services, Personal, cultural and recreational services, Other personal, cultural and recreational services"
cap label var _895 "Current account, Services, Other services, Personal, cultural and recreational services, Other personal, cultural and recreational services, Education services"
cap label var _896 "Current account, Services, Personal, cultural and recreational services, Other personal, cultural and recreational services, Health services"
cap label var _897 "Current account, Services, Other services, Personal, cultural and recreational services, Other personal, cultural and recreational services, Other"
cap label var _291 "Current account, Services, Other services, Government services, n.i.e."
cap label var _29110 "Current account, Services, Other services, Government services: Reimbursement of MS for cost of collecting own resources"
cap label var _29120 "Current account, Services, Other services, Government services: Building acquisition, construction and rent"
cap label var _29130 "Current account, Services, Other services, Government services: Other government services"
cap label var _292 "Current account, Services, Other services, Government services, n.i.e., Embassies and consulates"
cap label var _293 "Current account, Services, Other services, Government services, n.i.e., Military units and agencies"
cap label var _294 "Current account, Services, Other services, Government services, n.i.e., Other government services"
cap label var _298 "Current account, services, commercial services"
cap label var _982 "Current account, Services, Services not allocated"
cap label var _950 "Current account, Services, Memorandum items, Freight transportation on merchandise, valued on a transaction basis"
cap label var _951 "Current account, Services, Memorandum items, Freight transportation on merchandise, valued on a transaction basis, Sea Freight"
cap label var _952 "Current account, Services, Memorandum items, Freight transportation on merchandise, valued on a transaction basis, Air Freight"
cap label var _858 "Current account, Services, Memorandum items, Freight transportation on merchandise, valued on a transaction basis, Other freight"
cap label var _862 "Current account, Services, Memorandum items, Freight transportation on merchandise, valued on a transaction basis, Space freight"
cap label var _863 "Current account, Services, Memorandum items, Freight transportation on merchandise, valued on a transaction basis, Rail freight"
cap label var _953 "Current account, Services, Memorandum items, Freight transportation on merchandise, valued on a transaction basis, Road freight"
cap label var _865 "Current account, Services, Memorandum items, Freight transportation on merchandise, valued on a transaction basis, Inland waterway freight"
cap label var _868 "Current account, Services, Memorandum items, Freight transportation on merchandise, valued on a transaction basis, Pipeline freight"
cap label var _955 "Current account, Services, Memorandum items, Travel"
cap label var _956 "Current account, Services, Memorandum items, Travel, Expenditure on goods"
cap label var _957 "Current account, Services, Memorandum items, Travel, Expenditure on accommodation and food and beverage"
cap label var _871 "Current account, Services, Memorandum items, Travel, All other travel expenditure"
cap label var _960 "Current account, Services, Memorandum items, Gross insurance premiums"
cap label var _972 "Current account, Services, Memorandum items, Gross insurance premiums, Gross premiums - Life insurance"
cap label var _974 "Current account, Services, Memorandum items, Gross insurance premiums, Gross premiums - Freight insurance"
cap label var _976 "Current account, Services, Memorandum items, Gross insurance premiums, Gross premiums - Other direct insurance"
cap label var _961 "Current account, Services, Memorandum items, Gross insurance claims"
cap label var _973 "Current account, Services, Memorandum items, Gross insurance claims, Gross claims - Life insurance"
cap label var _975 "Current account, Services, Memorandum items, Gross insurance claims, Gross claims - Freight insurance"
cap label var _977 "Current account, Services, Memorandum items, Gross insurance claims, Gross claims - Other direct insurance"
cap label var _887 "Current account, Services, Memorandum items, Financial intermediation services indirectly measured (FISIM)"
cap label var _888 "Current account, Services, Memorandum items, Financial services including FISIM"
cap label var _962 "Current account, Services, Memorandum items, Merchanting gross flows"
cap label var _894 "Current account, Services, Memorandum items, Audiovisual transactions"
cap label var _300 "Current account, Income"
cap label var _310 "Current account, Income, Compensation of employees (including border, seasonal, and other workers)"
cap label var _31010 "Current account, Income, Compensation of employees, Gross wages and salaries"
cap label var _31020 "Current account, Income, Compensation of employees, Employers' Social contribution"
cap label var _320 "Current account, Income, Investment income"
cap label var _320INT "Current account, Income, Investment income, Memorandum items, Interest BPM5 (not adjusted for FISIM)"
cap label var _320D41 "Current account, Income, Investment income, Memorandum items, Interest SNA93  (adjusted for FISIM)"
cap label var _320FIS "Current account, Income, Investment income, Memorandum items, Value of  FISIM"
cap label var _320D4N "Current account, Income, Investment income, Memorandum items, Other than interest"
cap label var _330 "Current account, Income, Investment income, Direct investment"
cap label var _331 "Current account, Income, Investment income, Direct investment, Income on equity"
cap label var _332 "Current account, Income, Investment income, Direct investment, Income on equity, Dividends and distributed branch profits"
cap label var _333 "Current account, Income, Investment income, Direct investment, Income on equity, Reinvested earnings and undistributed branch profits"
cap label var _334 "Current account, Income, Investment income, Direct investment, Income on debt (interest)"
cap label var _339 "Current account, Income, Investment income, Portfolio investment"
cap label var _340 "Current account, Income, Investment income, Portfolio investment, Income on equity (dividends)"
cap label var _341 "Current account, Income, Investment income, Portfolio investment, Income on equity (dividends), Monetary authorities"
cap label var _349 "Current account, Income, Investment income, Portfolio investment, Income on debt (interest)"
cap label var _370 "Current account, Income, Investment income, Other investment"
cap label var _370INT "Current account, Income, Investment income, Other investment, Memorandum items, Interest BPM5 (not adjusted for FISIM)"
cap label var _370D44 "Current account, Income, Investment income, Other investment, Memorandum items, Income attributed to insurance policy holders"
cap label var _370D4N "Current account, Income, Investement income, Other investment, Memorandum items, Other"
cap label var _37010 "Current account, Income, Investement income, Other investment, Memorandum items, Other, EIB reinvested earnings"
cap label var _379 "Current account, Current transfers"
cap label var _380 "Current account, Current transfers, General government"
cap label var _380D2 "Current account, Current transfers, General government, Taxes on production and imports"
cap label var _380D21 "Current account, Current transfers, General government, Taxes on products"
cap label var _380D212X21 "Current account, Current transfers, General government, Taxes on products, Taxes and duties on imports, Customs duties, Traditional Own Resources"
cap label var _380D212X22 "Current account, Current transfers, General government, Taxes on products, Taxes and duties on imports, Agricultural levies, Traditional Own Resources"
cap label var _380D211X24 "Current account, Current transfers, General government, Taxes on products, Own resources from Value Added Taxes, VAT contribution"
cap label var _380D214X23 "Current account, Current transfers, General government, Taxes on products, Sugar and isoglucose production levies, Traditional Own Resources"
cap label var _380D29 "Current account, Current transfers, General government, Other taxes on production"
cap label var _380D29X25 "Current account, Current transfers, General government, Other taxes on production, ECSC levy"
cap label var _380D3 "Current account, Current transfers, General government, Subsidies"
cap label var _380D31 "Current account, Current transfers, General government, Subsidies on products"
cap label var _380D319X31 "Current account, Current transfers, General government, Subsidies on products, Agriculture and fishery"
cap label var _380D39 "Current account, Current transfers, General government, Other subsidies on production"
cap label var _380D39X31 "Current account, Current transfers, General government, Other subsidies on production, Agriculture and fishery"
cap label var _380D39X32 "Current account, Current transfers, General government, Other subsidies on production, Grants for interest relief"
cap label var _380D39X33 "Current account, Current transfers, General government, Other subsidies on production, Other"
cap label var _380D5 "Current account, Current transfers, General government, Taxes on income, wealth, etc"
cap label var _380D50 "Current account, Current transfers, General government, Taxes on income, wealth, etc"
cap label var _380D51 "Current account, Current transfers, General government, Taxes on income, wealth, etc, Taxes on income"
cap label var _380D6 "Current account, Current transfers, General government, Social Contributions and benefits"
cap label var _380D61 "Current account, Current transfers, General government, Social contributions"
cap label var _380D61121 "Compulsory employees' actual social contributions"
cap label var _380D612 "Employers' imputed social contributions"
cap label var _380D62 "Current account, Current transfers, General government, Social benefits other than social transfers in kind"
cap label var _380D63 "General government current transfers, social transfers in kind"
cap label var _380D7 "Current account, Current transfers, General government, Other current transfers"
cap label var _380D74 "Current account, Current transfers, General government, Other current transfers, Current international cooperation"
cap label var _380D74X66 "Current account, Current transfers, General government, Other current transfers, Current international cooperation, Contributions of Member States to the European Development Fund"
cap label var _380D74X68 "Current account, Current transfers, General government, Other current transfers, Current international cooperation, European Social Fund and others"
cap label var _380D74X70 "Current account, Current transfers, General government, Other current transfers, Current international cooperation, Agriculture and fishery (Guidance and other)"
cap label var _380D74X74 "Current account, Current transfers, General government, Other current transfers, Current international cooperation, European Regional Development Fund and others"
cap label var _380D74X88 "Current account, Current transfers, General government, Other current transfers, Current international cooperation, European Development Fund"
cap label var _380D74X90 "Current account, Current transfers, General government, Other current transfers, Current international cooperation, European Comunity Steel and Coal transfers"
cap label var _380D74X94 "Current account, Current transfers, General government, Other current transfers, Current international cooperation, Other"
cap label var _380D75 "Current account, Current transfers, General government, Other current transfers, Miscellaneous current transfer"
cap label var _380D7N "Current account, Current transfers, General government, Other current transfers, Other of general government n.i.e."
cap label var _380D75X64 "Current account, Current transfers, General government, Other current transfers, Miscellaneous, GNI related contributions, Own resources based on Gross National Income"
cap label var _380D75X92 "Current account, Current transfers, General government, Other current transfers, Miscellaneous, Financial compensation to MS, Correction of budgetary imbalances granted to the UK"
cap label var _380D75X94 "Current account, Current transfers, General government, Other current transfers, Miscellaneous, Miscellaneous revenue/Fines and penalities"
cap label var _380D75X96 "Current account, Current transfers, General government, Other current transfers, Miscellaneous, Transfers to private non profit institutions"
cap label var _390 "Current account, Current transfers, Other sectors"
cap label var _391 "Current account, Current transfers, Other sectors, Worker's remittances"
cap label var _392 "Current account, Current transfers, Other sectors, Other private transfers"
cap label var _392D21 "Current account, Current transfers, Other sectors, Other private transfers, Taxes on products"
cap label var _392D29 "Current account, Current transfers, Other sectors, Other private transfers, Other taxes on production"
cap label var _392D31 "Current account, Current transfers, Other sectors, Other private transfers, Subsidies on products"
cap label var _392D39 "Current account, Current transfers, Other sectors, Other private transfers, Other subsidies on production"
cap label var _392D50 "Current account, Current transfers, Other sectors, Other private transfers, Taxes on income, wealth, etc"
cap label var _392D61 "Current account, Current transfers, Other sectors, Other private transfers, Social contributions"
cap label var _392D62 "Current account, Current transfers, Other sectors, Other private transfers, Social benefits other than social transfers in kind"
cap label var _392D71 "Current account, Current transfers, Other sectors, Other private transfers, Net non-life insurance premiums"
cap label var _392D72 "Current account, Current transfers, Other sectors, Other private transfers, Non life insurance claims"
cap label var _392D7N "Current account, Current transfers, Other sectors, Other private transfers, Other current transfers of other sectors n.i.e."
cap label var _392D80 "Current account, Current transfers, Other sectors, Other private transfers, Adjustment for the change in net equity of households in pension fund reserves"
cap label var _994 "Capital account"
cap label var _400 "Capital account, Capital transfers"
cap label var _400D91 "Capital account, Capital transfers, Capital taxes"
cap label var _400D9N "Capital account, Capital transfers, Investment grants and other capital transfers"
cap label var _401 "Capital account, Capital transfers, General government"
cap label var _401D92 "Capital account, Capital transfers, General government, Investment grants"
cap label var _401D92X11 "Capital account, Capital transfers, General government, Investment grants, Agriculture and Fishery (EAGGF guidance and others)"
cap label var _401D92X12 "Capital account, Capital transfers, General government, Investment grants, European Regional Development Fund and others"
cap label var _401D92X13 "Capital account, Capital transfers, General government, Investment grants, European Development Fund"
cap label var _401D92X14 "Capital account, Capital transfers, General government, Investment grants, Cohesion funds and others"
cap label var _401D92X15 "Capital account, Capital transfers, General government, Investment grants, Investment grants - Other"
cap label var _401D99 "Capital account, Capital transfers, General Government, Other"
cap label var _401D99X11 "Capital account, Capital transfers, General Government, Other, Agriculture and Fishery  (EAGGF guidance and others)"
cap label var _401D99X15 "Capital account, Capital transfers, General Government, Other, Other"
cap label var _401D99X20 "Capital account, Capital transfers, General Government, Other, Debt forgiveness"
cap label var _480 "Capital account, Acquisition disposal of non-produced non-financial assets"
cap label var _995 "Financial account"
cap label var _500 "Financial account, Direct investment"
cap label var _505 "Financial account, Direct investment, Abroad"
cap label var _506 "Financial account, Direct investment, Abroad, Equity capital and reinvested earnings"
cap label var _510 "Financial account, Direct investment, Abroad, Equity capital"
cap label var _525 "Financial account, Direct investment, Abroad, Reinvested earnings"
cap label var _530 "Financial account, Direct investment, Abroad, Other capital"
cap label var _541 "Financial account, Direct investment, Abroad, Equity capital & Other capital"
cap label var _555 "Financial account, Direct investment, In the reporting economy"
cap label var _556 "Financial account, Direct investment, In the reporting economy, Equity capital and Reinvested earnings"
cap label var _560 "Financial account, Direct investment, In the reporting economy, Equity capital"
cap label var _575 "Financial account, Direct investment, In the reporting economy, Reinvested earnings"
cap label var _580 "Financial account, Direct investment, In the reporting economy, Other capital"
cap label var _591 "Financial account, Direct investment, In the reporting economy, Equity capital & Other capital"
cap label var _600 "Financial account, Portfolio investment"
cap label var _602 "Financial account, Portfolio investment, Assets"
cap label var _610 "Financial account, Portfolio investment, Assets, Equities securities"
cap label var _614 "Financial account, Portfolio investment, Assets, Equities securities, Other sectors"
cap label var _619 "Financial account, Portfolio investment, Assets, Debt securities"
cap label var _620 "Financial account, Portfolio investment, Assets, Debt securities, Bonds and notes"
cap label var _624 "Financial account, Portfolio investment, Assets, Debt securities, Bonds and notes, Other sectors"
cap label var _630 "Financial account, Portfolio investment, Assets, Debt securities, Money market instruments"
cap label var _634 "Financial account, Portfolio investment, Assets, Debt securities, Money market instruments, Other sectors"
cap label var _652 "Financial account, Portfolio investment, Liabilities"
cap label var _660 "Financial account, Portfolio investment, Liabilities, Equities securities"
cap label var _669 "Financial account, Portfolio investment, Liabilities, Debt securities"
cap label var _670 "Financial account, Portfolio investment, Liabilities, Debt securities, Bonds and notes"
cap label var _672 "Financial account, Portfolio investment, Liabilities, Debt securities, Bonds and notes, General government"
cap label var _674 "Financial account, Portfolio investment, Liabilities, Debt securities, Bonds and notes, Other sectors"
cap label var _680 "Financial account, Portfolio investment, Liabilities, Debt securities, Money market instruments"
cap label var _684 "Financial account, Portfolio investment, Liabilities, Debt securities, Money market instruments, Other sectors"
cap label var _910 "Financial account, Financial derivatives, Balance"
cap label var _914 "Financial account, Financial derivatives, Balance, Other sectors"
cap label var _904 "Financial account, Financial derivatives, Assets, Other sectors"
cap label var _909 "Financial account, Financial derivatives, Liabilities, Other sectors"
cap label var _700 "Financial account, Other investment"
cap label var _703 "Financial account, Other investment, Assets"
cap label var _704 "Financial account, Other investment, Assets, General government"
cap label var _713 "Financial account, Other investment, Assets, Loans/currency & deposits, General government"
cap label var _714 "Financial account, Other investment, Assets, Loans"
cap label var _719 "Financial account, Other investment, Assets, Loans, General government"
cap label var _725 "Financial account, Other investment, Assets, Loans, Other sectors"
cap label var _728 "Financial account, Other investment, Assets, Other sectors"
cap label var _729 "Financial account, Other investment, Assets, Loans/currency & deposits, Other sectors"
cap label var _730 "Financial account, Other investment, Assets, Currency and deposits"
cap label var _732 "Financial account, Other investment, Assets, Currency and deposits, General government"
cap label var _734 "Financial account, Other investment, Assets, Currency and deposits, Other sectors"
cap label var _736 "Financial account, Other investment, Assets, Other assets"
cap label var _740 "Financial account, Other investment, Assets, Other assets, General government"
cap label var _741 "Financial account, Other investment, Assets, Other assets, General government, Long-term"
cap label var _742 "Financial account, Other investment, Assets, Other assets, General government, Short-term"
cap label var _746 "Financial account, Other investment, Assets, Other assets, Other sectors"
cap label var _753 "Financial account, Other investment, Liabilities"
cap label var _754 "Financial account, Other investment, Liabilities, General government"
cap label var _759 "Financial account, Other investment, Liabilities, Trade credits, General government, Short-term"
cap label var _764 "Financial account, Other investment, Liabilities, Loans"
cap label var _769 "Financial account, Other investment, Liabilities, General government, Loans"
cap label var _775 "Financial account, Other investment, Liabilities, Other sectors, Loans"
cap label var _779 "Financial account, Other investment, Liabilities, Other sectors"
cap label var _780 "Financial account, Other investment, Liabilities, Currency and deposits"
cap label var _786 "Financial account, Other investment, Liabilities, Other liabilities"
cap label var _790 "Financial account, Other investment, Liabilities, Other liabilities, General government"
cap label var _791 "Financial account, Other investment, Liabilities, Other liabilities, General government, Long-term"
cap label var _792 "Financial account, Other investment, Liabilities, Other liabilities, General government, Short-term"
cap label var _796 "Financial account, Other investment, Liabilities, Other liabilities, Other sectors"
cap label var _802 "Financial account, Official reserve assets"
cap label var _980 "Net external debt"
cap label var _983 "Commercial services (services excluding Government services, n.i.e.)"
cap label var _988 "Financial account, International investment position, Assets"
cap label var _989 "Financial account, International investment position, Liabilities"
cap label var _998 "Net errors and omissions"
cap label var _991 "Current account, Goods and services"
cap label var _992 "Current account, Goods, services and income"
cap label var _996 "Capital and financial account"
cap label var EMP "Number of persons employed"
cap label var ENT "Number of enterprises"
cap label var EXP "Exports of goods and services"
cap label var EXPEU "Exports of goods and services to the EU"
cap label var EXPG "Exports of goods"
cap label var EXPGEU "Exports of goods to the EU"
cap label var EXPGRW "Exports of goods to the rest of world"
cap label var EXPI "Intra-group export of goods and services"
cap label var EXPICC "Intra-group exports of goods and services to the controlling unit in the compiling country"
cap label var EXPINC "Intra-group exports of goods and services excluding controlling unit"
cap label var EXPRW "Exports of goods and services to the rest of world"
cap label var EXPS "Exports of services"
cap label var EXPSEU "Exports of services to the EU"
cap label var EXPSRW "Exports of services to the rest of world"
cap label var GIT "Gross investment in tangible goods"
cap label var IMP "Import of goods and services"
cap label var IMPEU "Import of goods and services from the EU"
cap label var IMPG "Import of goods"
cap label var IMPGEU "Import of goods from the EU"
cap label var IMPGRW "Import of goods from the rest of world"
cap label var IMPI "Intra-group import of goods and services"
cap label var IMPICC "Intra-group import of goods and services from the controlling unit in the compiling country"
cap label var IMPINC "Intra-group import of goods and services excluding controlling unit"
cap label var IMPRW "Import of goods and services from the rest of world"
cap label var IMPS "Import of services"
cap label var IMPSEU "Import of services from the EU"
cap label var IMPSRW "Import of services from the rest of world"
cap label var PEC "Personnel costs"
cap label var RDE "Total intra-mural R&D expenditure"
cap label var RDP "Total number of R&D personnel"
cap label var TUR "Turnover"
cap label var VAC "Value added at factor cost"
cap label var _518 "Financial account, Direct investment, Abroad, Equity capital, MFIs (excluding central bank)"
cap label var _519 "Financial account, Direct investment, Abroad, Equity capital, Other sectors"
cap label var _528 "Financial account, Direct investment, Abroad, Reinvested earnings, MFIs (excluding central bank)"
cap label var _529 "Financial account, Direct investment, Abroad, Reinvested earnings, Other sectors"
cap label var _538 "Financial account, Direct investment, Abroad, Other capital, MFIs (excluding central bank)"
cap label var _539 "Financial account, Direct investment, Abroad, Other capital, Other sectors"
cap label var _568 "Financial account, Direct investment, In the reporting economy, Equity capital, MFIs (excluding central bank)"
cap label var _569 "Financial account, Direct investment, In the reporting economy, Equity capital, Other sectors"
cap label var _578 "Financial account, Direct investment, In the reporting economy, Reinvested earnings, MFIs (excluding central bank)"
cap label var _579 "Financial account, Direct investment, In the reporting economy, Reinvested earnings, Other sectors"
cap label var _588 "Financial account, Direct investment, In the reporting economy, Other capital, MFIs (excluding central bank)"
cap label var _589 "Financial account, Direct investment, In the reporting economy, Other capital, Other sectors"
cap label var _611 "Financial account, Portfolio investment, Assets, Equity securities, Monetary authorities"
cap label var _612 "Financial account, Portfolio investment, Assets, Equity securities, General government"
cap label var _613 "Financial account, Portfolio investment, Assets, Equity securities, MFIs"
cap label var _621 "Financial account, Portfolio investment, Assets, Debt securities, Bonds and notes, Monetary authorities"
cap label var _622 "Financial account, Portfolio investment, Assets, Debt securities, Bonds and notes, General government"
cap label var _623 "Financial account, Portfolio investment, Assets, Debt securities, Bonds and notes, MFIs"
cap label var _631 "Financial account, Portfolio investment, Assets, Debt securities, Money market instruments, Monetary authorities"
cap label var _632 "Financial account, Portfolio investment, Assets, Debt securities, Money market instruments, General government"
cap label var _633 "Financial account, Portfolio investment, Assets, Debt securities, Money market instruments, MFIs"
cap label var _663 "Financial account, Portfolio investment, Liabilities, Equity securities, MFIs"
cap label var _664 "Financial account, Portfolio investment, Liabilities, Equity securities, Other sectors"
cap label var _671 "Financial account, Portfolio investment, Liabilities, Debt securities, Bonds and notes, Monetary authorities"
cap label var _673 "Financial account, Portfolio investment, Liabilities, Debt securities, Bonds and notes, MFIs"
cap label var _681 "Financial account, Portfolio investment, Liabilities, Debt securities, Money market instruments, Monetary authorities"
cap label var _682 "Financial account, Portfolio investment, Liabilities, Debt securities, Money market instruments, General government"
cap label var _683 "Financial account, Portfolio investment, Liabilities, Debt securities, Money market instruments, MFIs"
cap label var _701 "Financial account, Other investment, Assets, Monetary authorities"
cap label var _702 "Financial account, Other investment, Assets, Monetary authorities, Loans/currency and deposits"
cap label var _705 "Financial account, Other investment, Assets, MFIs"
cap label var _707 "Financial account, Other investment, Assets, Trade credits, general government"
cap label var _710 "Financial account, Other investment, Assets, Trade credits, Other sectors"
cap label var _716 "Financial account, Other investment, Assets, MFIs, Loans/currency and deposits"
cap label var _737 "Financial account, Other investment, Assets, Other assets, Monetary authorities"
cap label var _743 "Financial account, Other investments, Assets, Other assets, MFIs"
cap label var _751 "Financial account, Other investment, Liabilities, Monetary authorities"
cap label var _752 "Financial account, Other investment, Liabilities, Monetary authorities, Loans/currency and deposits"
cap label var _755 "Financial account, Other investment, Liabilities, MFIs"
cap label var _757 "Financial account, Other investment, Liabilities, Trade credits, General government"
cap label var _760 "Financial account, Other investment, Liabilities, Trade credits, Other sectors"
cap label var _778 "Financial account, Other investment, Liabilities, MFIs, Loans/currency and deposits"
cap label var _787 "Financial account, Other investment, Liabilities, Other liabilities, Monetary authorities"
cap label var _793 "Financial account, Other investment, Liabilities, Other liabilities, MFIs"
cap label var _911 "Financial account, Financial derivatives, Balance, Monetary authorities"
cap label var _912 "Financial account, Financial derivatives, Balance, General government"
cap label var _913 "Financial account, Financial derivatives, Balance, MFIs"
cap label var _968 "Workers' remittances and  compensation of employees"
