cap label var TOTAL "Total"
cap label var GRS "Gross earning"
cap label var TAX "Taxes"
cap label var SOC "Social Security"
cap label var FAM "Family allowances"
cap label var NET "Net earning"
