cap label var SAL "Employees"
cap label var HW_SAL_Y "Hours actually worked by the employees per year"
cap label var HP_SAL_Y "Hours paid for employees per year"
cap label var APP "Apprentices"
cap label var HW_APP_Y "Hours actually worked by the apprentices per year"
cap label var HW_SAL_AVG "Average annual hours actually worked per employee"
cap label var HP_SAL_AVG "Average annual hours paid per employee"
cap label var HW_APP_AVG "Average annual hours actually worked per apprentice"
cap label var HP_APP_AVG "Average annual hours paid per apprentice"
cap label var LC_NAC "Labour cost - national currency"
cap label var LC_EUR "Labour cost - euro"
cap label var LC_M "Labour cost per month"
cap label var LC_H "Labour cost per hour"
cap label var HW "Hours worked"
cap label var HP_HW_RAT "Ratio between hours paid and actually worked"
cap label var HP_NHW "Hours paid but not actually worked"
