cap label var BSL "Baseline projections"
cap label var LFRT "Sensitivity test: lower fertility"
cap label var LMRT "Sensitivity test: lower mortality"
cap label var HMIGR "Sensitivity test: higher migration"
cap label var LMIGR "Sensitivity test: lower migration"
cap label var NMIGR "Sensitivity test: no migration"
cap label var NIRMIGR "Sensitivity test: no inter-regional migration"
cap label var HRFG "Sensitivity test: high number of refugees"
cap label var VHRFG "Sensitivity test: very high number of refugees"
