cap label var TOTAL "Total"
cap label var PC_LT10 "Less than 10 percent of all persons employed"
cap label var PC10_49 "From 10 percent to 49 percent of all persons employed"
cap label var PC_GE50 "50 percent or more of all persons employed"
cap label var PT_W "Persons who participated but wanted to participate more"
cap label var PT_NW "Persons who participated and did not want to participate more"
cap label var NPT_W "Persons who did not participate but wanted to participate"
cap label var NPT_NW "Persons who did not participate and did not want to participate"
cap label var NRP "No response"
cap label var _0 "Percentage of enterprises in which persons employed did not participate in CVT courses"
cap label var _1_10 "Percentage of enterprises in which 1-10% of the persons employed actually participated in CVT courses"
cap label var _11_20 "Percentage of enterprises in which 11-20% of the persons employed actually participated in CVT courses"
cap label var _21_40 "Percentage of enterprises in which 21-40% of the persons employed actually participated in CVT courses"
cap label var GT_40 "Percentage of enterprises in which more than 40% of the persons employed actually participated in CVT courses"
