cap label var TOTAL "Total"
cap label var ARCT "Arctic Ocean"
cap label var BALT "Baltic Sea"
cap label var NORTH "North Sea"
cap label var CHAN_ENG "English Channel"
cap label var ATL "Atlantic Ocean"
cap label var ATL_NE "North East Atlantic Ocean"
cap label var BLACK "Black Sea"
cap label var MED "Mediterranean Sea"
cap label var OUTER "Outermost regions"
cap label var OTH "Other sea basins"
cap label var UNK "Unknown"
