cap label var TOTAL "Total"
cap label var NLTD "Unlimited duration"
cap label var NLTD_FT "Unlimited duration and full-time"
cap label var NLTD_PT "Unlimited duration and part-time"
cap label var LTD "Limited duration"
cap label var LTD_FT "Limited duration and full-time"
cap label var LTD_PT "Limited duration and part-time"
cap label var LTD_X_APP_TRN "Limited duration except apprentice and trainee"
cap label var TNG_PROB "Training or probationary period"
cap label var EMP_SELF_FAM "Employers, self-employed and family workers"
cap label var APP_TRN "Apprentice or trainee"
cap label var FT "Full-time"
cap label var PT "Part-time"
cap label var OTH "Other"
cap label var NAP "Not applicable"
cap label var NRP "No response"
cap label var UNK "Unknown"
