cap label var DE "Domestic extraction"
cap label var IMP "Imports"
cap label var IMP_EU "Imports from EU countries"
cap label var IMP_XEU "Imports extra-EU"
cap label var IMP_RME "Imports in raw material equivalents"
cap label var IMP_RCV_R "Imports of waste for recovery - recycling"
cap label var IMP_X_RCV_R "Imports excluding imports of waste for recovery - recycling"
cap label var EXP "Exports"
cap label var EXP_EU "Exports to EU countries"
cap label var EXP_XEU "Exports extra-EU"
cap label var EXP_RME "Exports in raw material equivalents"
cap label var EXP_RCV_R "Exports of waste for recovery - recycling"
cap label var EXP_X_RCV_R "Exports excluding exports of waste for recovery - recycling"
cap label var INV "Investment"
cap label var PRV_INV "Private investments"
cap label var EMP "Persons employed"
cap label var GVA "Gross value added"
cap label var OUT "Output"
cap label var DMC "Domestic material consumption"
cap label var DMI_RCV_R_B "Processed material - direct material inputs and recovery - recycling and backfilling"
cap label var DMI "Direct material inputs"
cap label var DPO "Domestic processed output"
cap label var NAS "Net additions to stock"
cap label var PTB "Physical trade balance"
cap label var BI "Balancing items (input - output)"
cap label var PH_GLB "Global pH value"
cap label var TD_GLB "Global temperature deviation"
cap label var TD_GLB_A "Annual global temperature deviation"
cap label var TD_GLB_DEC "Decadal global temperature deviation"
cap label var TD_EUR "European temperature deviation"
cap label var TD_EUR_A "Annual European temperature deviation"
cap label var TD_EUR_DEC "Decadal European temperature deviation"
cap label var RMC "Raw material consumption"
cap label var RMC_P3 "Raw material consumption as result of final consumption expenditure"
cap label var RMC_P3_S13 "Raw material consumption as result of final consumption expenditure of general government"
cap label var RMC_P3_S14 "Raw material consumption as result of final consumption expenditure of households"
cap label var RMC_P3_S15 "Raw material consumption as result of final consumption expenditure of non-profit institutions serving households"
cap label var RMC_P5 "Raw material consumption as result of gross capital formation"
cap label var RMC_P51G "Raw material consumption as result of gross fixed capital formation"
cap label var RMC_P52_53 "Raw material consumption as result of changes in inventories and acquisitions less disposals of valuables"
cap label var RMI "Raw material input"
cap label var MAT_ACCUM "Material accumulation"
cap label var CAP "Capacity - tonnes per year"
cap label var CAP_RST "Rest capacity - cubic metres"
cap label var FAC "Facilities - number"
cap label var FAC_CL "Closed facilities - number"
cap label var PRD "Production of chemicals"
cap label var EXR "Extraction"
cap label var PCS "Processing"
cap label var CONS "Consumption of chemicals"
cap label var EMIS "Emissions"
cap label var EMIS_X_WST_INC "Emissions excluding emissions from incineration of waste"
cap label var EMIS_AIR_NBI "Emissions to air - net of balancing items"
cap label var EMIS_WTR "Emissions to water"
cap label var GHG_I90 "Greenhouse gas emissions (in CO2 equivalent), base year 1990"
cap label var GHG_I_KBY "Greenhouse gas emissions without international aviation (in CO2 equivalent), Kyoto base year"
cap label var GHG_T_HAB "Greenhouse gas emissions - tonnes per capita"
cap label var AEMIS_RES "Air emissions by resident units (production activities and households)"
cap label var AEMIS_RES_ABR "Air emissions by resident units released from use of fuel purchased abroad - total"
cap label var AEMIS_RES_ABR_FWTR "Air emissions by resident units released from use of fuel purchased abroad  - fishing vessels"
cap label var AEMIS_RES_ABR_LTR "Air emissions by resident units released from use of fuel purchased abroad  - land transport"
cap label var AEMIS_RES_ABR_WTR "Air emissions by resident units released from use of fuel purchased abroad  - water transport"
cap label var AEMIS_RES_ABR_ATR "Air emissions by resident units released from use of fuel purchased abroad  - air transport"
cap label var AEMIS_TER_NRES "Air emissions by non-resident units released from use of fuel purchased on the territory (only if included in national totals according to international conventions) - total"
cap label var AEMIS_TER_NRES_LTR "Air emissions by non-resident units released from use of fuel purchased on the territory (only if included in national totals according to international conventions) - land transport"
cap label var AEMIS_TER_NRES_WTR "Air emissions by non-resident units released from use of fuel purchased on the territory (only if included in national totals according to international conventions) - water transport"
cap label var AEMIS_TER_NRES_ATR "Air emissions by non-resident units released from use of fuel purchased on the territory (only if included in national totals according to international conventions) - air transport"
cap label var ADJ_SD "Other adjustments and statistical differences"
cap label var AEMIS_TER "Air emissions as reported to international conventions (UNFCCC and CLRTAP inventories, territory principle)"
cap label var AEMIS_TER_LULUCF "Air emissions as reported to international convention including LULUCF (UNFCCC, territory principle)"
cap label var LULUCF "Land use, land use change, and forestry (LULUCF)"
cap label var FORL "Forest land"
cap label var CRL_GRL "Cropland and grassland"
cap label var LULUCF_OTH "Other land use, land use change, and forestry (LULUCF)"
cap label var ORG_EMAS "EMAS registered organisations"
cap label var SITE_EMAS "EMAS registered sites"
cap label var FSTK_ASS_NR "Assessed fish stocks - number"
cap label var FSTK_OVF_NR "Overfished fish stocks - number"
cap label var FSTK_OVF_PC "Overfished fish stocks - %"
cap label var FSTK_BMA_I03 "Fish stock biomass - index 2003 = 100"
cap label var FSTK_MBMED "Fish stocks - model based median value"
cap label var FSTK_AMV_ASS "Arithmetic mean value of all assessments"
cap label var PER_NGUA_PC "Persons in urban areas without green urban areas in their neighbourhood - %"
cap label var MGCI "Mountain green cover index"
cap label var CO2_UVA_KG_EUR "CO2 emissions per unit of value added - kilograms per euro"
cap label var MA_ETR "Marine area affected by eutrophication"
cap label var WEI "Water exploitation index"
cap label var WSL "Water stress level"
cap label var TPW "Throughput waste"
cap label var DFLOW "Dissipative flows"
cap label var DEM_DCR "Demolition and discard"
cap label var MAT_USE "Material use"
cap label var NRS "Net reductions in stock"
