cap label var NEER_EA18 "Nominal effective exchange rate - 18 trading partners (euro area 2014)"
cap label var NEER_EA19 "Nominal effective exchange rate - 19 trading partners (euro area from 2015)"
cap label var NEER_EU27_2020 "Nominal effective exchange rate - 27 trading partners (European Union from 2020)"
cap label var NEER_EU28 "Nominal effective exchange rate - 28 trading partners (European Union 2013-2020)"
cap label var NEER_IC37 "Nominal effective exchange rate - 37 trading partners (industrial countries)"
cap label var NEER_IC42 "Nominal effective exchange rate - 42 trading partners (industrial countries)"
cap label var REER_EA18_CPI "Real effective exchange rate (deflator: consumer price index - 18 trading partners - euro area 2014)"
cap label var REER_EA18_ULCT "Real effective exchange rate (deflator: unit labour costs in the total economy - 18 trading partners - euro area 2014)"
cap label var REER_EA19_CPI "Real effective exchange rate (deflator: consumer price index - 19 trading partners - euro area from 2015)"
cap label var REER_EA19_ULCT "Real effective exchange rate (deflator: unit labour costs in the total economy - 19 trading partners - euro area from 2015)"
cap label var REER_EU27_2020_CPI "Real effective exchange rate (deflator: consumer price index - 27 trading partners - European Union from 2020)"
cap label var REER_EU28_CPI "Real effective exchange rate (deflator: consumer price index - 28 trading partners - European Union 2013-2020)"
cap label var REER_EU27_2020_ULCT "Real effective exchange rate (deflator: unit labour costs in the total economy - 27 trading partners - European Union from 2020)"
cap label var REER_EU28_ULCT "Real effective exchange rate (deflator: unit labour costs in the total economy - 28 trading partners - European Union 2013-2020)"
cap label var REER_IC37_CPI "Real effective exchange rate (deflator: consumer price index - 37 trading partners - industrial countries)"
cap label var REER_IC37_ULCT "Real effective exchange rate (deflator: unit labour costs in the total economy - 37 trading partners - industrial countries)"
cap label var REER_IC42_CPI "Real effective exchange rate (deflator: consumer price index - 42 trading partners - industrial countries )"
