cap label var TOT_NACE_HH "All NACE branches plus households"
cap label var DEU_RES "Domestic energy use - residence principle"
cap label var TOT_NRA "Production and consumption activities abroad by residents"
cap label var NRA_FISH "Fishing vessels operated abroad by residents"
cap label var NRA_LAND "Land transport operated abroad by residents"
cap label var NRA_WATER "Water transport operated abroad by residents"
cap label var NRA_AIR "Air transport operated abroad by residents"
cap label var TOT_NRES "Production and consumption activities on the territory by non-residents"
cap label var NRES_LAND "Land transport operated on the territory by non-residents"
cap label var NRES_WATER "Water transport operated on the territory by non-residents"
cap label var NRES_AIR "Air transport operated on the territory by non-residents"
cap label var ADJ_OTH "Adjustments and statistical discrepancy"
cap label var GIEC_TER "Gross inland energy consumption - territory principle"
cap label var TOT_CONV "Total emissions as reported to international conventions (UNFCCC and CLRTAP)"
cap label var DE "Domestic Extraction"
cap label var IMP "Total Imports"
cap label var IMP_XEU "Extra EU Imports"
cap label var IMP_RME "Total Imports in Raw Material Equivalents"
cap label var EXP "Total Exports"
cap label var EXP_XEU "Extra EU Exports"
cap label var EXP_RME "Total Exports in Raw Material Equivalents"
cap label var DMC "Domestic Material Consumption"
cap label var DMI "Direct Material Inputs"
cap label var RMC "Raw Material Consumption"
cap label var RMI "Raw Material Input"
cap label var CAP "Capacity (tonnes per year)"
cap label var CAP_RST "Rest capacity (cubic metres)"
cap label var FAC "Number of facilities"
cap label var FAC_CL "Closed facilities"
cap label var GHG_I90 "Greenhouse gas emissions (in CO2 equivalent) indexed to 1990"
cap label var GHG_I_KBY "Greenhouse gas emissions without international aviation (in CO2 equivalent) indexed to Kyoto base year"
cap label var PRD "Production of chemicals"
cap label var CONS "Consumption of chemicals"
cap label var ADJ_DSP_DNRGXINRG "Adjustments and statistical discrepancy amongst which energy flows included in domestic energy use by resident units while excluded in gross inland energy consumption"
