cap label var TOTAL "Total"
cap label var HHC_10 "Children (living with other adults)"
cap label var HHC_20 "Single adult - total"
cap label var HHC_21 "Single adult with children"
cap label var HHC_22 "Single adult without children"
cap label var HHC_30 "Couple - total"
cap label var HHC_31 "Couple with children"
cap label var HHC_32 "Couple without children"
cap label var HIC_30 "Adult living in a couple - total"
cap label var HIC_31 "Adult living in a couple with children"
cap label var HIC_32 "Adult living in a couple without children"
cap label var HHC_40 "Other type of household - total"
cap label var HHC_41 "Other type of household with children"
cap label var HHC_42 "Other type of household without children"
cap label var HIC_40 "Adult living in another type of household - total"
cap label var HIC_41 "Adult living in another type of household with children"
cap label var HIC_42 "Adult living in another type of household without children"
cap label var HHC_50 "Total of adults"
cap label var HHC_51 "Adult (total) with children"
cap label var HHC_52 "Adult (total) without children"
cap label var HWC_50 "Total (all households)"
cap label var HWC_51 "Households with dependent children - total"
cap label var HWC_52 "Households without dependent children - total"
cap label var FAM "Household composed of family nucleus"
cap label var FAM1 "Household composed of one-family nucleus"
cap label var CPL_YCH "Household composed of couple with at least one resident child under 25 years"
cap label var CPL_NYCH "Household composed of couple without resident children under 25 years"
cap label var MAR "Household composed of married couple"
cap label var MAR_NCH "Household composed of married couple without resident children"
cap label var MARO_NCH "Household composed of opposite-sex married couple without resident children"
cap label var MARS_NCH "Household composed of same-sex married couple without resident children"
cap label var MAR_YCH "Household composed of married couple with at least one resident child under 25 years"
cap label var MARO_YCH "Household composed of opposite-sex married couple with at least one resident child under 25 years"
cap label var MARS_YCH "Household composed of same-sex married couple with at least one resident child under 25 years"
cap label var MAR_OCH "Household composed of married couple with youngest resident child 25 years or older"
cap label var MARO_OCH "Household composed of opposite-sex married couple with youngest resident child 25 years or older"
cap label var MARS_OCH "Household composed of same-sex married couple with youngest resident child 25 years or older"
cap label var REP "Household composed of couple in registered partnership"
cap label var REP_NCH "Household composed of couple in registered partnership without resident children"
cap label var REPO_NCH "Household composed of opposite-sex couple in registered partnership without resident children"
cap label var REPS_NCH "Household composed of same-sex couple in registered partnership without resident children"
cap label var REP_YCH "Household composed of couple in registered partnership with at least one resident child under 25 years"
cap label var REPO_YCH "Household composed of opposite-sex couple in registered partnership with at least one resident child under 25 years"
cap label var REPS_YCH "Household composed of same-sex couple in registered partnership with at least one resident child under 25 years"
cap label var REP_OCH "Household composed of couple in registered partnership with youngest resident child 25 years or older"
cap label var REPO_OCH "Household composed of opposite-sex couple in registered partnership with youngest resident child 25 years or older"
cap label var REPS_OCH "Household composed of same-sex couple in registered partnership with youngest resident child 25 years or older"
cap label var CSU "Household composed of couple in consensual union"
cap label var CSU_NCH "Household composed of couple in consensual union without resident children"
cap label var CSUO_NCH "Household composed of opposite-sex couple in consensual union without resident children"
cap label var CSUS_NCH "Household composed of same-sex couple in consensual union without resident children"
cap label var CSU_YCH "Household composed of couple in consensual union with at least one resident child under 25 years"
cap label var CSUO_YCH "Household composed of opposite-sex couple in consensual union with at least one resident child under 25 years"
cap label var CSUS_YCH "Household composed of same-sex couple in consensual union with at least one resident child under 25 years"
cap label var CSU_OCH "Household composed of couple in consensual union with youngest resident child 25 years or older"
cap label var CSUO_OCH "Household composed of opposite-sex couple in consensual union with youngest resident child 25 years or older"
cap label var CSUS_OCH "Household composed of same-sex couple in consensual union with youngest resident child 25 years or older"
cap label var PAR_YCH_P "Household composed of at least one parent with at least one resident child under 25 years and other person"
cap label var PAR1_YCH "Household composed of lone parent with at least one resident child under 25 years"
cap label var M1 "Household composed of one single male"
cap label var M1_CH "Household composed of lone father living with at least one child"
cap label var M1_YCH "Household composed of lone father with at least one resident child under 25 years"
cap label var M1_OCH "Household composed of lone father with at least one resident child 25 years or older"
cap label var F1 "Household composed of one single female"
cap label var F1_CH "Household composed of lone mother living with at least one child"
cap label var F1_YCH "Household composed of lone mother with at least one resident child under 25 years"
cap label var F1_OCH "Household composed of lone mother with at least one resident child 25 years or older"
cap label var P1_CH "Household composed of lone mother or father living with at least one child"
cap label var FAM_GE2 "Household composed of two-or-more-family nucleus"
cap label var NFAM "Household composed of non-family nucleus"
cap label var P1 "One-person household"
cap label var A1 "Household composed of one adult"
cap label var A1_DCH "Household composed of one adult with dependent children"
cap label var A2 "Household composed of two adults"
cap label var A2_DCH "Household composed of two adults with dependent children"
cap label var A2_DCH1 "Household composed of two adults with one dependent child"
cap label var A2_DCH2 "Household composed of two adults with two dependent children"
cap label var A2_DCH_GE3 "Household composed of two adults with three or more dependent children"
cap label var A_GE2_DCH "Household composed of two or more adults with dependent children"
cap label var A_GE2_NDCH "Household composed of two or more adults without dependent children"
cap label var A_GE3 "Household composed of three or more adults"
cap label var A_GE3_DCH "Household composed of three or more adults with dependent children"
cap label var MULTI "Multiperson household other than family nucleus"
cap label var DCH "Households with dependent children"
cap label var NDCH "Households without dependent children"
cap label var A1_LT65 "Household composed of one adult younger than 65 years"
cap label var A1_GE65 "Household composed of one adult 65 years or over"
cap label var A2_2LT65 "Household composed of two adults younger than 65 years"
cap label var A2_GE1_GE65 "Household composed of two adults, at least one aged 65 years or over"
cap label var OTH "Other"
cap label var NRP "No response"
cap label var UNK "Unknown"
