cap label var TOTAL "Total"
cap label var TOT_X_RSE "Total excluding researchers"
cap label var BRD "Board members"
cap label var EXEC "Executives"
cap label var RSE "Researchers"
cap label var TEC "Technicians and equivalent staff"
cap label var MAN "Managers"
cap label var SPEC "Specialists"
cap label var TRN "Trainee employees"
cap label var OTH "Others"
