cap label var TOTAL "Total"
cap label var NR "Number"
cap label var NR_HAB "Number per inhabitant"
cap label var THS "Thousand"
cap label var MIO "Million"
cap label var BN "Billion"
cap label var CT "Euro cent"
cap label var EUR "Euro"
cap label var THS_EUR "Thousand euro"
cap label var MIO_EUR "Million euro"
cap label var BN_EUR "Billion euro"
cap label var MEUR_KP11 "Million euro (at constant 2011 prices)"
cap label var MEUR_KP10 "Million euro (at constant 2010 prices)"
cap label var MEUR_KP05 "Million euro (at constant 2005 prices)"
cap label var MEUR_KP00 "Million euro (at constant 2000 prices)"
cap label var MEUR_KP_PRE "Million euro (at prices of the previous year)"
cap label var MEUR_CLV10 "Million euro, chain-linked volumes, reference year 2010 (at 2010 exchange rates)"
cap label var MEUR_NSA "Million euro (NSA)"
cap label var MIO_EUR_NSA "Million euro (NSA)"
cap label var MIO_EUR_SCA "Million euro (SCA)"
cap label var MIO_EUR_SA "Trade value - million of euro - seasonally and working day adjusted"
cap label var MIO__EUR__NSA "Trade value - million of euro - not seasonally adjusted"
cap label var EUR_M3_CLV10 "Euro per cubic metre (Euro: chain-linked volumes, reference year 2010, at 2010 exchange rates)"
cap label var EUR_BGDP "Euro per billion GDP"
cap label var EUR_KG "Euro per kilogram"
cap label var EUR_KGOE "Euro per kilogram of oil equivalent (KGOE)"
cap label var EUR_KG_CLV15 "Euro per kilogram, chain linked volumes (2015)"
cap label var EUR_KG_CLV10 "Euro per kilogram, chain linked volumes (2010)"
cap label var EUR_T "Euro per tonne"
cap label var EUR_TOE "Euro per tonne of oil equivalent (TOE)"
cap label var EUR_HA "Euro per hectare"
cap label var EUR_HM2 "Euro per hundred square metres"
cap label var EUR_HD "Euro per head (animal)"
cap label var EUR_HHD "Euro per hundred heads (animals)"
cap label var EUR_HIVE "Euro per beehive"
cap label var EUR_HAB "Euro per inhabitant"
cap label var EUR_HAB_EU "Euro per inhabitant in percentage of the EU average"
cap label var EUR_HAB_EU27_2020 "Euro per inhabitant in percentage of the EU27 (from 2020) average"
cap label var EUR_HAB_KP10 "Euro per inhabitant (at constant 2010 prices)"
cap label var EUR_AE "Euro per adult equivalent"
cap label var EUR_HH "Euro per household"
cap label var MEUR_HAB "Million euro per inhabitant"
cap label var ECU "European currency unit (Ecu)"
cap label var NAC "National currency"
cap label var THS_NAC "Thousand units of national currency"
cap label var MIO_NAC "Million units of national currency"
cap label var BN_NAC "Billion units of national currency"
cap label var MNAC_KP10 "Million units of national currency at constant 2010 prices"
cap label var MNAC_KP05 "Million units of national currency at constant 2005 prices"
cap label var NAC_T "National currency per tonne"
cap label var NAC_HA "National currency per hectare"
cap label var NAC_HAB "National currency per inhabitant"
cap label var NAC_AE "National currency per adult equivalent"
cap label var NAC_HH "National currency per household"
cap label var NAT "National currency (former currencies of the euro area countries)"
cap label var MIO_NAT "Million units of national currency (former currencies of the euro area countries)"
cap label var PPS "Purchasing power standard (PPS)"
cap label var PPS_EU27_2020 "Purchasing power standard (PPS, EU27 from 2020)"
cap label var MIO_PPS "Million purchasing power standards (PPS)"
cap label var MIO_PPS_EU27_2020 "Million purchasing power standards (PPS, EU27 from 2020)"
cap label var MIO_PPS_KP05 "Million purchasing power standards (PPS) at 2005 prices"
cap label var MIO_PPS_KP00 "Million purchasing power standards (PPS) at 2000 prices"
cap label var PPS_BGDP "Purchasing power standard (PPS) per billion GDP"
cap label var PPS_KG "Purchasing power standard (PPS) per kilogram"
cap label var PPS_KGOE "Purchasing power standard (PPS) per kilogram of oil equivalent"
cap label var MPPS_KM2 "Million purchasing power standards (PPS) per square kilometre"
cap label var PPS_M3 "Purchasing power standard (PPS) per cubic metre"
cap label var PPS_HAB "Purchasing power standard (PPS) per inhabitant"
cap label var PPS_EU27_2020_HAB "Purchasing power standard (PPS, EU27 from 2020), per inhabitant"
cap label var PPS_HAB_KP05 "Purchasing power standard (PPS) per inhabitant at constant 2005 prices"
cap label var PPS_HAB_KP00 "Purchasing power standard (PPS) per inhabitant at constant 2000 prices"
cap label var PPS_HAB_EU "Purchasing power standard (PPS) per inhabitant in percentage of the EU average"
cap label var PPS_HAB_EU27_2020 "Purchasing power standard (PPS, EU27 from 2020), per inhabitant in percentage of the EU27 (from 2020) average"
cap label var PPS_HAB_EU28 "Purchasing power standard (PPS) per inhabitant in percentage of the EU28 (2013-2020) average"
cap label var PPS_AE "Purchasing power standard (PPS) per adult equivalent"
cap label var PPS_HH "Purchasing power standard (PPS) per household"
cap label var PPCS_HAB "Purchasing power standard based on final consumption per inhabitant"
cap label var PPCS_HAB_EU "Purchasing power consumption standards per inhabitant in percentage of the EU average"
cap label var GDP_HAB "GDP per capita"
cap label var GDP_BEUR "Nominal GDP in billion euro"
cap label var OZ "Ounce"
cap label var MCG_M3 "Micrograms per cubic metre"
cap label var MG_L "Milligrams per litre"
cap label var G "Gram"
cap label var G_HAB "Grams per capita"
cap label var G_EUR_CP "Grams per euro, current prices"
cap label var G_EUR_CLV10 "Grams per euro, chain linked volumes (2010)"
cap label var G_PKM "Grams per passenger-kilometre"
cap label var G_TKM "Grams per tonne-kilometre"
cap label var KG "Kilogram"
cap label var KG_HAB "Kilograms per capita"
cap label var KG_EUR_CP "Kilograms per euro, current prices"
cap label var KG_EUR_CLV10 "Kilograms per euro, chain linked volumes (2010)"
cap label var KG_TEUR_CLV10 "Kilograms per thousand euro, chain linked volumes (2010)"
cap label var KG_HA "Kilograms per hectare"
cap label var KGOE "Kilogram of oil equivalent (KGOE)"
cap label var KGOE_HAB "Kilograms of oil equivalent (KGOE) per capita"
cap label var KGOE_TEUR "Kilograms of oil equivalent (KGOE) per thousand euro"
cap label var KGOE_TEUR_PPS "Kilograms of oil equivalent (KGOE) per thousand euro in purchasing power standards (PPS)"
cap label var T "Tonne"
cap label var THS_T "Thousand tonnes"
cap label var MIO_T "Million tonnes"
cap label var TCO2E "Tonnes of CO2 equivalent"
cap label var MTCO2E "Million tonnes of CO2 equivalent"
cap label var TCO2E_HAB "Tonnes of CO2 equivalent per capita"
cap label var TOE "Tonnes of oil equivalent (TOE)"
cap label var KTOE "Thousand tonnes of oil equivalent"
cap label var MTOE "Million tonnes of oil equivalent"
cap label var TOE_HAB "Tonnes of oil equivalent (TOE) per capita"
cap label var TOE_MEUR "Tonnes of oil equivalent (TOE) per million euro"
cap label var TSWU "Tonnes of separative work units"
cap label var THM "Tonnes of heavy metal"
cap label var TPW "Tonnes product weight"
cap label var TLW "Tonnes live weight"
cap label var T_HA "Tonnes per hectare"
cap label var T_HAB "Tonnes per capita"
cap label var T_KM2 "Tonnes per square kilometre"
cap label var TD "Tonnes per day"
cap label var THS_TD "Thousand tonnes per day"
cap label var THS_TY "Thousand tonnes per year"
cap label var O2_TD "Tonnes of O2 per day"
cap label var GT "Gross tonnage (GT)"
cap label var THS_GT "Gross tonnage (GT) in thousand"
cap label var M "Metre"
cap label var M_KM2 "Metres per square kilometre"
cap label var KM "Kilometre"
cap label var MIO_GTKM "Million gross tonne-kilometres"
cap label var TKM "Tonne-kilometre (TKM)"
cap label var THS_TKM "Thousand tonne-kilometre (TKM)"
cap label var MIO_TKM "Million tonne-kilometre (TKM)"
cap label var THS_TRKM "Thousand train-kilometres"
cap label var MIO_PKM "Millions of passenger-kilometres"
cap label var VKM "Vehicle-kilometre (VKM)"
cap label var THS_VKM "Thousand vehicle-kilometres (VKM)"
cap label var MIO_VKM "Million vehicle-kilometres (VKM)"
cap label var THS_VESKM "Thousand vessel-kilometres"
cap label var KM_THAB "Kilometres per thousand inhabitants"
cap label var KM_TKM2 "Kilometres per thousand square kilometres"
cap label var M2 "Square metre"
cap label var THS_M2 "Thousand square metres"
cap label var MIO_M2 "Million square metres"
cap label var M2_HAB "Square metres per capita"
cap label var HA "Hectare"
cap label var THS_HA "Thousand hectares"
cap label var KM2 "Square kilometre"
cap label var KM2_HAB "Square kilometres per capita"
cap label var M3 "Cubic metre"
cap label var THS_M3 "Thousand cubic metres"
cap label var MIO_M3 "Million cubic metres"
cap label var MIO_M3D "Million cubic metres per day"
cap label var M3_HAB "Cubic metres per inhabitant"
cap label var L "Litre"
cap label var THS_L "Thousand litres"
cap label var HL "Hectolitre"
cap label var THS_HL "Thousand hectolitres"
cap label var MN "Minute"
cap label var THS_MN "Thousand minutes"
cap label var HR "Hour"
cap label var THS_HR "Thousand hours"
cap label var MIO_HR "Million hours"
cap label var HW "Hours worked"
cap label var THS_HW "Thousand hours worked"
cap label var HR_SAL "Hours per employee"
cap label var DAY "Day"
cap label var MTH "Month"
cap label var YR "Year"
cap label var TIME_SP "Time spent (hh:mm)"
cap label var PTP_TIME "Participation time (hh:mm)"
cap label var KW "Kilowatt"
cap label var THS_KW "Thousand kilowatts"
cap label var MW "Megawatt"
cap label var GW "Gigawatt"
cap label var KWH "Kilowatt-hour"
cap label var MWH "Megawatt-hour"
cap label var GWH "Gigawatt-hour"
cap label var GWD_THM "Gigawatt-days per tonne of heavy metal"
cap label var KCAL "Kilocalorie"
cap label var KJ "Kilojoule"
cap label var KJ_M3 "Kilojoule per cubic metre"
cap label var KJ_M3_GCV "Kilojoule per cubic metre (gross calorific value - GCV)"
cap label var KJ_M3_NCV "Kilojoule per cubic metre (net calorific value - NCV)"
cap label var MJ "Megajoule"
cap label var MJ_HAB "Megajoule per capita"
cap label var MJ_T_GCV "Megajoule per tonne (gross calorific value - GCV)"
cap label var MJ_T_NCV "Megajoule per tonne (net calorific value - NCV)"
cap label var GJ "Gigajoule"
cap label var GJ_GCV "Gigajoule (gross calorific value - GCV)"
cap label var GJ_HAB "Gigajoule per capita"
cap label var TJ "Terajoule"
cap label var TJ_GCV "Terajoule (gross calorific value - GCV)"
cap label var TJ_NCV "Terajoule (net calorific value - NCV)"
cap label var TJ_HAB "Terajoule per capita"
cap label var TJ_TM3_NCV "Terajoule per thousand cubic metres (net calorific value - NCV)"
cap label var DEGC "Degree Celsius"
cap label var PH "pH value"
cap label var INX "Index"
cap label var INX_Q "Quarterly index"
cap label var INX_A_AVG "Annual average index"
cap label var I2015 "Index, 2015=100"
cap label var I2010 "Index, 2010=100"
cap label var I21 "Index, 2021=100"
cap label var I16 "Index, 2016=100"
cap label var I15 "Index, 2015=100"
cap label var I13 "Index, 2013=100"
cap label var I12 "Index, 2012=100"
cap label var I10 "Index, 2010=100"
cap label var I09 "Index, 2009=100"
cap label var I08 "Index, 2008=100"
cap label var I06 "Index, 2006=100"
cap label var I05 "Index, 2005=100"
cap label var I03 "Index, 2003=100"
cap label var I01 "Index, 2001=100"
cap label var I00 "Index, 2000=100"
cap label var I99 "Index, 1999=100"
cap label var I98 "Index, 1998=100"
cap label var I96 "Index, 1996=100"
cap label var I95 "Index, 1995=100"
cap label var I91 "Index, 1991=100"
cap label var I90 "Index, 1990=100"
cap label var I10_Q "Quarterly index, 2010=100"
cap label var I15_Q "Quarterly index, 2015=100"
cap label var I10_A_AVG "Annual average index, 2010=100"
cap label var I15_A_AVG "Annual average index, 2015=100"
cap label var I_EU "Index, EU=100"
cap label var I_LY "Index, latest year = 100"
cap label var I_N_1 "Index, n-1 = 100"
cap label var I_1Y "Index, t-1 = 100"
cap label var I15_17_AVG "Index, 2015-2017 average =100"
cap label var I11_13_AVG "Index, 2011-2013 average =100"
cap label var I15_NAC_CP "Index, 2015=100, national currency, current prices"
cap label var I15_PER "Index, 2015=100 (based on persons)"
cap label var I10_PER "Index, 2010=100 (based on persons)"
cap label var I15_HW "Index, 2015=100 (based on hours worked)"
cap label var I10_HW "Index, 2010=100 (based on hours worked)"
cap label var I15_JOB "Index, 2015=100 (based on jobs)"
cap label var I10_JOB "Index, 2010=100 (based on jobs)"
cap label var SEI "Shannon evenness index"
cap label var SDI "Shannon diversity index"
cap label var I_ESD "Index, EU effort sharing decision base year=100"
cap label var I_MED "Income index (compared to national median)"
cap label var I_MEAN "Income index (compared to national mean)"
cap label var HICP2015 "Harmonized consumer price index, 2015=100"
cap label var I2015_SCA "Index, 2015=100 (SCA)"
cap label var I15_NSA "Index, 2015=100 (NSA)"
cap label var I2015_NSA "Index, 2015=100 (NSA)"
cap label var I2010_NSA "Index, 2010=100 (NSA)"
cap label var KP_I15 "Constant prices, index 2015=100"
cap label var KP_I10 "Constant prices, index 2010=100"
cap label var CLV_I15 "Chain linked volumes, index 2015=100"
cap label var CLV_I10 "Chain linked volumes, index 2010=100"
cap label var CLV_I05 "Chain linked volumes, index 2005=100"
cap label var IVU_NSA "Unit value index (2015=100) - not seasonally adjusted"
cap label var IVOL_SA "Volume index (2015=100) - seasonally and working day adjusted"
cap label var IVOL_NSA "Volume index (2015=100) - not seasonally adjusted"
cap label var AVG "Average"
cap label var AVG_A "Annual average"
cap label var AVG_3Y "Three-year average"
cap label var THS_CD08 "Cumulative difference from 2008, in thousands"
cap label var MV12R "Moving 12-months average rate of change"
cap label var SUM_4Q "Sum of the last 4 quarters"
cap label var RK "Rank"
cap label var RTG "Rating (0-10)"
cap label var REL1 "Relative value, relating to all enterprises"
cap label var REL2 "Relative value, relating to innovating enterprises"
cap label var REL3 "Relative value, relating to product innovators"
cap label var REL4 "Relative value, relating to process innovators"
cap label var REL5 "Relative value, relating to service innovators"
cap label var REL6 "Relative value, relating to total innovation expenditure"
cap label var REL7 "Relative value, relating to innovating enterprises with innovation cooperation"
cap label var REL8 "Relative value, relating to innovating enterprises with seriously delayed projects"
cap label var REL9 "Relative value, relating to innovating enterprises with abolished projects"
cap label var REL10 "Relative value, relating to innovating enterprises with not even started projects"
cap label var REL11 "Relative value, relating to enterprises in the corresponding level of export intensity"
cap label var REL12 "Relative value, relating to enterprises in the corresponding type of firm"
cap label var CVA "Coefficient of variation for absolute value"
cap label var CV1 "Coefficient of variation for relative value, relating to all enterprises"
cap label var CV2 "Coefficient of variation for relative value, relating to innovating enterprises"
cap label var CV3 "Coefficient of variation for relative value, relating to product innovators"
cap label var CV4 "Coefficient of variation for relative value, relating to process innovators"
cap label var CV5 "Coefficient of variation for relative value, relating to service innovators"
cap label var CV6 "Coefficient of variation for relative value, relating to total innovation expenditure"
cap label var CV7 "Coefficient of variation for relative value, relating to enterprises with innovation cooperation"
cap label var CV8 "Coefficient of variation for relative value, relating to innovating enterprises with seriously delayed projects"
cap label var CV9 "Coefficient of variation for relative value, relating to innovating enterprises with abolished projects"
cap label var CV10 "Coefficient of variation for relative value, relating to innovating enterprises with not even started projects"
cap label var CV11 "Coefficient of variation for relative value, relating to enterprises in the corresponding level of export intensity"
cap label var CV12 "Coefficient of variation for relative value, relating to enterprises in the corresponding type of firm"
cap label var SGM_ESU "Standard gross margin (SGM) in economic size unit (ESU)"
cap label var TEU "Twenty-foot equivalent unit (TEU)"
cap label var THS_TEU "Thousand twenty-foot equivalent unit (TEU)"
cap label var THS_TEUKM "Thousand TEU-kilometres"
cap label var CFU "Colony-forming unit (CFU)"
cap label var AWU "Annual working unit (AWU)"
cap label var THS_AWU "Thousand annual working units (AWU)"
cap label var LSU "Livestock unit (LSU)"
cap label var FTE "Full-time equivalent (FTE)"
cap label var THS_FTE "Thousand full-time equivalents (FTE)"
cap label var FTE_HTHAB "Full time equivalent per hundred thousand inhabitants"
cap label var PER "Person"
cap label var PERS "Persons"
cap label var THS_PER "Thousand persons"
cap label var MIO_PER "Million persons"
cap label var PER_KM2 "Persons per square kilometre"
cap label var HAB "Inhabitant/person/capita"
cap label var HAB_P "Inhabitants per ..."
cap label var HAB_KM2 "Inhabitants per square kilometre"
cap label var HAB_HC "Inhabitants per ... (head count)"
cap label var HAB_FTE "Inhabitants per ... (full time equivalent)"
cap label var MIO_EMP "Millions of persons employed"
cap label var MIO_SAL "Millions of employees"
cap label var P_BERD "Per billion euro of business enterprise expenditure on R&D (BERD)"
cap label var P_GERD "Per billion euro of gross domestic expenditure on R&D (GERD)"
cap label var PB "Planetary Boundary"
cap label var P_HAB "Per inhabitant"
cap label var P_HHAB "Per hundred inhabitants"
cap label var P_THAB "Per thousand inhabitants"
cap label var P_HTHAB "Per hundred thousand inhabitants"
cap label var P_MHAB "Per million inhabitants"
cap label var P_MACT "Per million of population in the labour force"
cap label var P_SAL_Y "Per employee in full-time equivalents, per year"
cap label var P_SAL_M "Per employee in full-time equivalents, per month"
cap label var P_SAL_H "Per employee in full-time equivalents, per hour"
cap label var P_HH "Per household"
cap label var P_KM2 "Per square kilometre"
cap label var PAS "Passenger"
cap label var THS_PAS "Thousand passengers"
cap label var THS_PASF "Thousand passengers (excluding cruise passengers)"
cap label var THS_PASC "Thousand cruise passengers starting and ending a cruise"
cap label var THS_PASE "Thousand cruise passengers on excursion"
cap label var HD "Head (animal)"
cap label var HD_AVG "Average of heads"
cap label var THS_HD "Thousand heads (animals)"
cap label var HC "Head count"
cap label var HC_HTHAB "Head count per hundred thousand inhabitants"
cap label var HLD "Holding"
cap label var MACH "Machine"
cap label var PCE "Piece"
cap label var PLC "Place"
cap label var HIVE "Beehives"
cap label var BAL "Balance"
cap label var MOVE "Movement"
cap label var FLIGHT "Flight"
cap label var THS_JOB "Thousand jobs"
cap label var THS_JRNY "Thousand journeys"
cap label var THS_BTO "Thousand basic transport operations"
cap label var SEAT "Seats and berths"
cap label var THS_SEAT "Thousand seats"
cap label var VES_MOV "Vessel movements"
cap label var NR_ENT "Number of enterprises"
cap label var TVAL_SA "Trade value in million euro (SA)"
cap label var TVAL_MEUR "Trade value in million euro"
cap label var CAP_1000T_Y "Annual capacity/inputs in 1000T"
cap label var RAT "Ratio"
cap label var RT "Rate"
cap label var RT_R4Q "Rolling 4-quarter growth rate"
cap label var RT_INC "Incidence rate"
cap label var RT_SINC "Standardised incidence rate"
cap label var RT_UNE "Unemployment rate"
cap label var RT_PRE "Growth rate on previous period (t/t-1)"
cap label var RT_PRE_EUR "Growth rate on previous period (t/t-1) for values in euro"
cap label var RT_PRE_NAC "Growth rate on previous period (t/t-1) for values in national currency"
cap label var RT_PRE_GT "Growth rate on previous period (t/t-1) for gross tonnage of vessels"
cap label var RT_PRE_NR "Growth rate on previous period (t/t-1) for number of vessels"
cap label var RT1 "Growth rate on previous period (t/t-1)"
cap label var PTP_RT "Participation rate (%)"
cap label var RT12 "Growth rate (t/t-12)"
cap label var RT1_ABS_SA "Trade value - growth rate (m/m-1) - seasonally and working day adjusted"
cap label var RT12_ABS_NSA "Trade value - growth rate (m/m-12) - not seasonally adjusted"
cap label var RT1_IVU_NSA "Unit value index (2015=100) - growth rate (m/m-1) - not seasonally adjusted"
cap label var RT12_IVU_NSA "Unit value index (2015=100) - growth rate (m/m-12) - not seasonally adjusted"
cap label var RT1_IVOL_SA "Volume index (2015=100) - growth rate (m/m-1) - seasonally and working day adjusted"
cap label var RT12_IVOL_NSA "Volume index (2015=100) - growth rate (m/m-12) - not seasonally adjusted"
cap label var RT1_SCA "Percentage change (t/t-1) - seasonally and calendar adjusted data"
cap label var RT4_NSA "Percentage change (t/t-4) - not seasonally adjusted data"
cap label var RT12_NSA "Percentage change (t/t-12) - not seasonally adjusted data"
cap label var RT12_CA "Percentage change (t/t-12) - calendar adjusted data, not seasonally adjusted data"
cap label var RT4 "Growth rate on the same quarter in previous year"
cap label var RT_M_DIF "Monthly rate differences between HICP and HICP at constant taxes"
cap label var RCH_M "Monthly rate of change"
cap label var RCH_Q "Quarterly rate of change"
cap label var RCH_A "Annual rate of change"
cap label var RCH_A_AVG "Annual average rate of change"
cap label var RCH_MV12MAVR "Moving 12 months average rate of change"
cap label var PC_PNT "Percentage point"
cap label var PC "Percentage"
cap label var PM "Per mille"
cap label var PC_S "Standardised percentage"
cap label var PC_Y "Percentage in the year"
cap label var PC_OECD "Percentage of OECD total"
cap label var PC_AREA "Percentage of area"
cap label var PC_UAA "Percentage of total utilised agricultural area"
cap label var PC_LSU "Percentage of total livestock units"
cap label var PC_POP "Percentage of total population"
cap label var PC_WMN "Percentage of women"
cap label var PC_STU "Percentage of total tertiary students"
cap label var PC_FSTU "Percentage of total foreign tertiary students"
cap label var PC_Y20_29 "Percentage of total population aged 20-29"
cap label var PC_Y25_29 "Percentage of total population aged 25-29"
cap label var PC_Y_LT60 "Percentage of total population aged less than 60"
cap label var PC_Y_LT65 "Percentage of total population aged less than 65"
cap label var PC_UP95 "Percentage of total population - upper boundary of the 95% confidence interval"
cap label var PC_LW95 "Percentage of total population - lower boundary of the 95% confidence interval"
cap label var PC_RIMG "Percentage of total recent immigrants"
cap label var PC_EMP "Percentage of total employment"
cap label var PC_UNE "Percentage of unemployment"
cap label var PC_ACT "Percentage of population in the labour force"
cap label var PC_ACT_HC "Percentage of population in the labour force - numerator in head count (HC)"
cap label var PC_ACT_FTE "Percentage of population in the labour force - numerator in full-time equivalent (FTE)"
cap label var PC_INAC "Percentage of population outside the labour force"
cap label var PC_INAC_WWRK "Percentage of population outside the labour force and wanting to work"
cap label var PC_SAL "Percentage of employees"
cap label var PC_SAL_TEMP "Percentage of employees with a temporary job"
cap label var PC_EMP_HC "Percentage of total employment - numerator in head count (HC)"
cap label var PC_EMP_FTE "Percentage of total employment - numerator in full-time equivalent (FTE)"
cap label var PC_ELF "Percentage of extended labour force"
cap label var PC_TSCO "Percentage of total revenues from taxes and social contributions (including imputed social contributions)"
cap label var PC_TSCO_X_ISCO "Percentage of total revenues from taxes and social contributions (excluding imputed social contributions)"
cap label var PC_GDP "Percentage of gross domestic product (GDP)"
cap label var PC_GVA "Percentage of gross value added (GVA)"
cap label var PC_GNI "Percentage of gross national income (GNI)"
cap label var PC_DI "Percentage of disposable income"
cap label var PC_GEXP "Percentage of government expenditure"
cap label var PC_BEN "Percentage of total benefits"
cap label var PC_EXP "Percentage of total expenditure"
cap label var PC_PEXP "Percentage of total public expenditure"
cap label var PC_REC "Percentage of total receipts"
cap label var PC_CHE "Percentual share of total current health expenditure (CHE)"
cap label var PC_WRL "Percentage of world total"
cap label var PC_TAX "Percentage of total taxation"
cap label var PC_HH "Percentage of households"
cap label var PC_IND "Percentage of individuals"
cap label var PC_HC "Percentage based on head count (HC)"
cap label var PC_FTE "Percentage based on full-time equivalents (FTE)"
cap label var PC_GBA "Percentage of total GBAORD"
cap label var PC_DT "Distance to target in percentage"
cap label var PC_FAT "Fat content (% of product weight)"
cap label var PC_PRO "Protein content (% of product weight)"
cap label var PC_TOT "Percentage of total"
cap label var PC_TOT_PER "Percentage of total (based on persons)"
cap label var PC_TOT_HW "Percentage of total (based on hours worked)"
cap label var PC_TOT_HAB "Percentage of total (based on inhabitants)"
cap label var PC_TOT_FTE "Percentage of total (based on full-time equivalents)"
cap label var PC_TOT_JOB "Percentage of total (based on jobs)"
cap label var PC_EU27_2020 "Percentage of EU27 (from 2020) total"
cap label var PC_EU28 "Percentage of EU28 (2013-2020) total"
cap label var PC_EU27_2007 "Percentage of EU27 (2007-2013) total"
cap label var PC_EU25 "Percentage of EU25 (2004-2006) total"
cap label var PC_EU27_2020_EUR_HAB "Percentage of EU27 (from 2020) total (based on euro per inhabitant)"
cap label var PC_EU28_EUR_HAB "Percentage of EU28 (2013-2020) total (based on euro per inhabitant)"
cap label var PC_EU27_2007_EUR_HAB "Percentage of EU27 (2007-2013) total (based on euro per inhabitant)"
cap label var PC_EU27_2020_PPS_HAB "Percentage of EU27 (from 2020) total (based on purchasing power standards per inhabitant)"
cap label var PC_EU28_PPS_HAB "Percentage of EU28 (2013-2020) total (based on purchasing power standards per inhabitant)"
cap label var PC_EU27_2007_PPS_HAB "Percentage of EU27 (2007-2013) total (based on purchasing power standards per inhabitant)"
cap label var PC_EU27_2020_PPS_EMP "Percentage of EU27 (from 2020) total (based on purchasing power standards per employed person)"
cap label var PC_EU28_PPS_EMP "Percentage of EU28 (2013-2020) total (based on purchasing power standards per employed person)"
cap label var PC_EU27_2007_PPS_EMP "Percentage of EU27 (2007-2013) total (based on purchasing power standards per employed person)"
cap label var PC_EU15_PPS_EMP "Percentage of EU15 (1995-2004) total (based on purchasing power standards per employed person)"
cap label var PC_EU27_2020_MEUR "Percentage of EU27 (from 2020) total (based on million euro)"
cap label var PC_EU28_MEUR "Percentage of EU28 (2013-2020) total (based on million euro)"
cap label var PC_EU27_2007_MEUR "Percentage of EU27 (2007-2013) total (based on million euro)"
cap label var PC_EU27_2020_MPPS "Percentage of EU27 (from 2020) total (based on million purchasing power standards)"
cap label var PC_EU28_MPPS "Percentage of EU28 (2013-2020) total (based on million purchasing power standards)"
cap label var PC_EU27_2007_MPPS "Percentage of EU27 (2007-2013) total (based on million purchasing power standards)"
cap label var PC_EU27_2020_MEUR_CP "Percentage of EU27 (from 2020) total (based on million euro), current prices"
cap label var PC_EU28_MEUR_CP "Percentage of EU28 (2013-2020) total (based on million euro), current prices"
cap label var PC_EU27_2020_MPPS_CP "Percentage of EU27 (from 2020) total (based on million purchasing power standards), current prices"
cap label var PC_EU28_MPPS_CP "Percentage of EU28 (2013-2020) total (based on million purchasing power standards), current prices"
cap label var PC_EU27_2020_HAB_MEUR_CP "Percentage of EU27 (from 2020) total per capita (based on million euro, EU27 from 2020), current prices"
cap label var PC_EU28_HAB_MEUR_CP "Percentage of EU28 (2013-2020) total per capita (based on million euro), current prices"
cap label var PC_EU27_2020_HAB_MPPS_CP "Percentage of EU27 (from 2020) total per capita (based on million purchasing power standards, EU27 from 2020), current prices"
cap label var PC_EU28_HAB_MPPS_CP "Percentage of EU28 (2013-2020) total per capita (based on million purchasing power standards), current prices"
cap label var PC_EA_MEUR "Percentage of euro area total (based on million euro)"
cap label var PC_EA18_MEUR "Percentage of EA18 (2014) total (based on million euro)"
cap label var PC_EA17_MEUR "Percentage of EA17 (2011-2013) total (based on million euro)"
cap label var PC_EA16_MEUR "Percentage of EA16 (2009-2010) total (based on million euro)"
cap label var PC_EA12_MEUR "Percentage of EA12 (2001-2006) total (based on million euro)"
cap label var PC_EA18_MPPS "Percentage of EA18 (2014) total (based on million purchasing power standards)"
cap label var PC_EA17_MPPS "Percentage of EA17 (2011-2013) total (based on million purchasing power standards)"
cap label var PC_EA16_MPPS "Percentage of EA16 (2009-2010) total (based on million purchasing power standards)"
cap label var PC_GDP_3Y "Percentage of GDP - three-year average"
cap label var PC_GDP_NSA "Percentage of gross domestic product (GDP), (NSA)"
cap label var PC_GDP_SCA "Percentage of gross domestic product (GDP), (SCA)"
cap label var PC_ENT "Percentage of enterprises"
cap label var PC_ENT_CC "Percentage of enterprises buying CC services"
cap label var PC_ENT_CCX "Percentage of enterprises not buying CC services"
cap label var PC_ENT_BDA "Percentage of enterprises analysing big data internally or externally"
cap label var PC_ENT_BDAAM "Percentage of enterprises analysing big data internally using any method"
cap label var PC_ENT_BD "Percentage of enterprises analysing big data"
cap label var PC_ENT_IOT1 "Percentage of enterprises using Internet of Things (as of 2021)"
cap label var PC_ENT_IOT "Percentage of enterprises using Internet of Things"
cap label var PC_ENT_RFID1 "Percentage of enterprises using RFID (as of 2014)"
cap label var PC_ENT_RFID "Percentage of the enterprises using RFID"
cap label var PC_ENT_ADS "Percentage of enterprises using internet ads"
cap label var PC_ENT_SM "Percentage of enterprises using social media"
cap label var PC_ENT_WEB "Percentage of the enterprises having a website"
cap label var PC_ENT_FIXBB "Percentage of enterprises using a fixed broadband connection"
cap label var PC_ENT_ITSPRCR2 "Percentage of enterprises which recruited / tried to recruit personnel for jobs requiring ICT specialist skills (reduced comparability with 2007)"
cap label var PC_ENT_SECPOL1 "Percentage of enterprises with an ICT security policy (as of 2015)"
cap label var PC_ENT_SECPOL2 "Percentage of enterprises with  document(s) on measures, practices or procedures on ICT security (as of 2019)"
cap label var PC_ENT_SECPOL "Percentage of enterprises with an ICT security policy"
cap label var PC_ENT_PMD1 "Percentage of enterprises providing to persons employed portable devices that allow a mobile connection to the internet (as of 2016)"
cap label var PC_ENT_PMD "Percentage of enterprises providing to persons employed portable devices that allow a mobile connection to the internet"
cap label var PC_ENT_AWSELL "Percentage of enterprises with web sales"
cap label var PC_ENT_AWSELLX "Percentage of enterprises without web sales"
cap label var PC_ENT_AWSEU "Percentage of enterprises with web sales to other EU countries"
cap label var PC_ENT_AWS_CMP "Percentage of enterprises with web sales via e-commerce marketplaces"
cap label var PC_ENT_AEBUY "Percentage of enterprises sending e-commerce orders over the last calendar year"
cap label var PC_ENT_AESELL "Percentage of enterprises receiving e-commerce orders over the last calendar year"
cap label var PC_TURN "Percentage of turnover"
cap label var PC_ETURN "Percentage of turnover from e-commerce"
cap label var PC_AWSVAL "Percentage of web sales"
cap label var PC_SAL_AESELL "Percentage of the employees working in enterprises which received orders via computer networks"
cap label var PC_EMP_PMD1 "Percentage of persons employed working in enterprises which provide mobile devices (as of 2016)"
cap label var PC_EMP_PMD "Percentage of persons employed working in enterprises which provide mobile devices"
cap label var PC_ENT_CUSE "Percentage of the enterprises which use a computer"
cap label var PC_ENT_IUSE "Percentage of enterprises where persons employed have access to the internet"
cap label var PC_ENT_IACC "Percentage of the enterprises with internet access"
cap label var PC_ENT_ECOM "Percentage of enterprises which sent/received orders via any computer networks"
cap label var PC_EMP_CUSE "Percentage of persons employed using a computer"
cap label var PC_EMP_CUSE2 "Percentage of persons employed working in enterprises which use computers"
cap label var PC_EMP_IACC "Percentage of persons employed working in an enterprise with internet access"
cap label var PC_EMP_IUSE "Percentage of persons employed using a computer with access to the www"
cap label var PC_EMP_AESELL "Percentage of persons employed working in enterprises which received orders via computer networks"
cap label var PC_ENT_AI_EC "Percentage of the enterprises which ever considered to use any of the AI technologies"
cap label var PC_ENT_AI_TANY "Percentage of the enterprises using at least one AI technologies"
cap label var PC_ENT_AI_TX "Percentage of the enterprises using no AI technologies"
cap label var PC_ENT_CVD_IEM "Percentage of the enterprises which increased the percentage of persons employed having remote access to their e-mail system"
cap label var PC_ENT_CVD_IRA "Percentage of the enterprises which increased the percentage of persons employed having remote access their ICT systems other than e-mail"
cap label var PC_ENT_CVD_IRM "Percentage of the enterprises which increased the number of their remote meetings"
cap label var PC_ENT_INV3SBG "Percentage of enterprises sending invoices B2BG"
cap label var PC_ENT_ISELL "Percentage of the enterprises which sold over the internet over the last calendar year"
cap label var PC_ENT_IBUY "Percentage of enterprises which purchased over the internet over the last calendar year"
cap label var PC_ENT_PURCH "Percentage of total purchases"
cap label var PC_ENT_OBUY "Percentage of enterprises which purchased over networks other than the internet over the last calendar year"
cap label var PC_ENT_OSELL "Percentage of enterprises which sold over networks other than the internet over the last calendar year"
cap label var PC_ENT_ITSPRCR "Percentage of enterprises which recruited or tried to recruit personnel for jobs requiring ICT specialist skills"
cap label var PC_ENT_ITSPVAC2 "Percentage of enterprises with hard-to-fill vacancies for jobs requiring ICT specialist skills (as of 2020)"
cap label var PC_ENT_ITSPVAC "Percentage of enterprises which had hard-to-fill vacancies for jobs requiring ICT specialist skills"
cap label var PC_ENT_ITUSRCR "Percentage of enterprises which recruited or tried to recruit personnel for jobs requiring skills in the use of ICT"
cap label var PC_ENT_ADE "Percentage of enterprises using ADE"
cap label var PC_ENT_SISC "Percentage of enterprises sharing information electronically on the supply chain management"
cap label var PC_ENT_P3D "Percentage of enterprises with 3D printing"
cap label var PC_ENT_RBTS "Percentage of enterprises using service robots"
cap label var PC_HH_IACC "Percentage of households with internet access at home"
cap label var PC_IND_C3 "Percentage of individuals who used a computer within the last 3 months"
cap label var PC_IND_CEVR "Percentage of individuals who used a computer, ever"
cap label var PC_IND_ILT12 "Percentage of individuals who used internet within the last year"
cap label var PC_IGRTX "Percentage of individuals who have used internet but not for sending filled forms to public authorities"
cap label var PC_IGRTX_NAPX "Percentage of individuals who have used internet but not for sending filled forms to public authorities although they had to"
cap label var PC_IND_IU3 "Percentage of individuals who used internet in the last 3 months"
cap label var PC_IND_CTMT3YX "Percentage of individuals who have taken a computer course more than 3 years ago or never"
cap label var PC_IND_CIANY "Percentage of individuals who have done at least one of the listed computer or internet activities"
cap label var PC_IND_BLT12 "Percentage of individuals who ordered goods or services, over the internet, for private use, in the last year"
cap label var PC_IND_BMT12X "Percentage of individuals who ordered goods or services, over the internet, for private use, more than a year ago or who never did"
cap label var PC_IND_CC_AW "Percentage of individuals who used internet, were aware of cloud services but did not use them"
cap label var PC_IND_CC_CCS "Percentage of individuals who used internet and cloud services for file saving or sharing"
cap label var PC_IND_CC_CCSX "Percentage of individuals who used internet but not cloud services"
cap label var PC_IND_BUY3 "Percentage of individuals who purchased online in the last 3 months"
cap label var PC_IND_BFFOR "Percentage of individuals who purchased online from sellers from other countries (EU or non-EU)"
cap label var PC_IND_BHHS "Percentage of individuals who purchased online household services"
cap label var PC_IND_BPG_ANY "Percentage of individuals who purchased online physical goods"
cap label var PC_IND_BRA "Percentage of individuals who rented accommodation online from an enterprise or a private person"
cap label var PC_IND_BTPS "Percentage of individuals who purchased online transport service from a transport enterprise or a private person"
cap label var PC_IND_IOT_BDKX "Percentage of individuals who have not used any internet-connected device or systems although they knew about them"
cap label var PC_IND_IOT_DX "Percentage of individuals who have not used any internet-connected devices or systems"
cap label var PC_VAL_ISELL "Percentage of internet sales"
cap label var PC_HH_IACCX "Percentage of households without internet access at home"
cap label var PC_HH_BROADX "Percentage of households without broadband access"
cap label var PC_IND_IUEVR "Percentage of individuals who used internet, ever"
cap label var PC_IND_SCSOFT "Percentage of individuals who used security software or tool"
cap label var PC_IND_SCUAVX "Percentage of individuals who don't update their security products"
cap label var PC_IND_SECOITPP "Percentage of individuals who have experienced online identity theft, phishing or pharming"
cap label var PC_IND_MDW "Percentage of individuals who, at work, use any type of computers, portable devices or computerised equipment or machinery"
cap label var PC_IND_IUMC "Percentage of individuals who have used a portable computer to access internet"
cap label var PC_IND_IUMD "Percentage of individuals who used a handheld device or portable computer to access internet"
cap label var PC_IND_IUMDX "Percentage of individuals who didn't use a handheld device or portable computer to access internet"
cap label var PC_IND_IUHD "Percentage of individuals who used a handheld device to access internet"
cap label var PC_IND_IUGOV12 "Percentage of e-government users"
cap label var PC_IND_IUG_TV "Percentage of individuals who used the internet on a smart TV (directly connected to the internet)"
cap label var PC_IND_IUP2P_WRK "Percentage of individuals who have obtained paid work by using an intermediary website or apps"
cap label var PC_IND_MPP1 "Percentage of individuals who use a smartphone for private purposes (3 months)"
cap label var PC_IND_MPP "Percentage of individuals who use a smartphone for private purposes"
cap label var PC_IND_ILT12_SSF "Percentage of employees and self-employed who used internet within the last year"
cap label var PC_IND_WH "Percentage of individuals working from home"
cap label var PC_IND_WM "Percentage of individuals working at an external site or on the move"
cap label var PC_IND_BGT3_IU3 "Percentage of individuals who used internet and did not purchase online in the last 3 months"
cap label var PC_IND_TIC "Percentage of individuals who checked the truthfulness of the information or content found on the internet news sites or social media"
cap label var PC_IND_TICX "Percentage of individuals who did not check the truthfulness of the information or content found on the internet news sites or social media"
cap label var PC_IND_UDI "Percentage of individuals who saw untrue or doubtful information or content on the internet news sites or social media"
cap label var PC_EMP_PREEMP_M12 "Percentage of persons employed and previously employed within 12 months"
cap label var PC_EMP_PREEMP "Percentage of persons employed and previously employed"
cap label var PC_PER_HPB "Percentage of persons reporting a health problem"
cap label var PC_PER_ACC "Percentage of persons reporting an accident"
cap label var PPCH_3Y "Percentage point change (t-(t-3))"
cap label var PPCH_PRE "Percentage point change on previous period, contribution to GDP growth"
cap label var PPCH_SM "Percentage point change compared to same period in previous year, contribution to GDP growth"
cap label var PCH_RV "Percentage change, real values"
cap label var PCH_LV_M_16_19 "Percentage change of the current month compared to the lowest value for the corresponding month in the period 2016-2019"
cap label var PCH_PRE "Percentage change on previous period"
cap label var PCH_SM "Percentage change compared to same period in previous year"
cap label var PCH_SM_EUR "Percentage change compared to same period in previous year, euro"
cap label var PCH_PRE_PER "Percentage change on previous period (based on persons)"
cap label var PCH_PRE_HW "Percentage change on previous period (based on hours worked)"
cap label var PCH_SM_PER "Percentage change compared to same period in previous year (based on persons)"
cap label var PCH_SM_HW "Percentage change compared to same period in previous year (based on hours worked)"
cap label var PCH_SM_JOB "Percentage change compared to same period in previous year (based on jobs)"
cap label var PCH_SM_FTE "Percentage change compared to same period in previous year (based on full-time equivalents)"
cap label var PCH_SM_2Y "Percentage change compared to same period two years ago"
cap label var PCH_SM_19 "Percentage change compared to same month in 2019"
cap label var PCH_PRE_NAC_CP "Percentage change on previous period, national currency, current prices"
cap label var PCH_PRE_CPI05_EUR "Price index - percentage change on previous period, based on 2005=100 and the euro"
cap label var PCH_PRE_CPI00_EUR "Price index - percentage change on previous period, based on 2000=100 and the euro"
cap label var PCH_PRE_CPI05_NAC "Price index - percentage change on previous period, based on 2005=100 and national currency"
cap label var PCH_PRE_CPI00_NAC "Price index - percentage change on previous period, based on 2000=100 and national currency"
cap label var PCH_5Y_CPI15_NAC "Price index - percentage change (t/t-5), based on 2015=100 and national currency"
cap label var PCH_5Y_CPI10_NAC "Price index - percentage change (t/t-5), based on 2010=100 and national currency"
cap label var PCH_5Y_CPI05_NAC "Price index - percentage change (t/t-5), based on 2005=100 and national currency"
cap label var PCH_PRE_EUR "Percentage change on previous period, euro"
cap label var PCH_PRE_HAB "Percentage change on previous period (based on inhabitants)"
cap label var PCH_PRE_FTE "Percentage change on previous period (based on full-time equivalents)"
cap label var PCH_PRE_JOB "Percentage change on previous period (based on jobs)"
cap label var PCH_PRE_PERS_SCA "Percentage change on previous period (based on persons, SCA)"
cap label var PCH_SAME_PERS_NSA "Percentage change compared to same period in previous year (based on persons, NSA)"
cap label var PCH_SM_PER_NSA "Percentage change compared to same period in previous year (based on persons, NSA)"
cap label var PCH_SM_PER_SCA "Percentage change compared to same period in previous year (based on persons, SCA)"
cap label var PCH_M1 "Percentage change m/m-1"
cap label var PCH_M1_NSA "Percentage change m/m-1 (NSA)"
cap label var PCH_M1_SA "Percentage change m/m-1 (SA)"
cap label var PCH_M1_SCA "Percentage change m/m-1 (SCA)"
cap label var PCH_Q1_NSA "Percentage change q/q-1 (NSA)"
cap label var PCH_Q1_SCA "Percentage change q/q-1 (SCA)"
cap label var PCH_Q4_NSA "Percentage change q/q-4 (NSA)"
cap label var PCH_Q4_SCA "Percentage change q/q-4 (SCA)"
cap label var PCH_Q4_CA "Percentage change q/q-4 (CA)"
cap label var PCH_M12 "Percentage change m/m-12"
cap label var PCH_M12_NSA "Percentage change m/m-12 (NSA)"
cap label var PCH_M12_CA "Percentage change m/m-12 (CA)"
cap label var PCH_MV12 "Percentage change - 12-months average"
cap label var PCH_M24 "Percentage change m/m-24"
cap label var PCH_1Y "Percentage change (t/t-1)"
cap label var PCH_3Y "Percentage change (t/t-3)"
cap label var PCH_5Y "Percentage change (t/t-5)"
cap label var PCH_10Y "Percentage change (t/t-10)"
cap label var PCH_WRL_1Y "Percentage of world total - 1-year change"
cap label var PCH_WRL_5Y "Percentage of world total - 5-year change"
cap label var PCH_OECD_5Y "Percentage of OECD total - 5-year change"
cap label var CP_MEUR "Current prices, million euro"
cap label var CP_MNAC "Current prices, million units of national currency"
cap label var CP_MPPS "Current prices, million purchasing power standards"
cap label var CP_MPPS_EU27_2020 "Current prices, million purchasing power standards (PPS, EU27 from 2020)"
cap label var CP_MUSD "Current prices, million US dollars"
cap label var CP_EUR_HAB "Current prices, euro per capita"
cap label var CP_NAC_HAB "Current prices, units of national currency per capita"
cap label var CP_PPS_HAB "Current prices, purchasing power standard per capita"
cap label var CP_PPS_EU27_2020_HAB "Current prices, purchasing power standard (PPS, EU27 from 2020) per capita"
cap label var CLV15_MEUR "Chain linked volumes (2015), million euro"
cap label var CLV10_MEUR "Chain linked volumes (2010), million euro"
cap label var CLV05_MEUR "Chain linked volumes (2005), million euro"
cap label var CLV15_MNAC "Chain linked volumes (2015), million units of national currency"
cap label var CLV10_MNAC "Chain linked volumes (2010), million units of national currency"
cap label var CLV05_MNAC "Chain linked volumes (2005), million units of national currency"
cap label var CLV_I15_HAB "Chain linked volumes, Index 2015=100, per capita"
cap label var CLV_I10_HAB "Chain linked volumes, Index 2010=100, per capita"
cap label var CLV15_EUR_HAB "Chain linked volumes (2015), euro per capita"
cap label var CLV10_EUR_HAB "Chain linked volumes (2010), euro per capita"
cap label var CLV10_EUR_AWU "Chain linked volumes (2010), euro per annual work unit (AWU)"
cap label var CLV_PY_MEUR "Chain linked volumes, previous year, million euro"
cap label var CLV_PY_MNAC "Chain linked volumes, previous year, million units of national currency"
cap label var CLV_PCH_PRE "Chain linked volumes, percentage change on previous period"
cap label var CLV_PCH_SM "Chain linked volumes, percentage change compared to same period in previous year"
cap label var CLV_PCH_ANN "Chain linked volumes, annualized percentage change on previous period"
cap label var CLV_PCH_PRE_HAB "Chain linked volumes, percentage change on previous period, per capita"
cap label var CLV_PCH_SM_HAB "Chain linked volumes, percentage change compared to same period in previous year, per capita"
cap label var PYP_MEUR "Previous year prices, million euro"
cap label var PYP_MNAC "Previous year prices, million units of national currency"
cap label var PYP_MUSD "Previous year prices, million US dollars"
cap label var KP_PCH_PRE "Constant prices, percentage change on previous period"
cap label var KP_PCH_SM "Constant prices, percentage change compared to same period in previous year"
cap label var CON_PPCH_PRE "Contribution to GDP growth, percentage point change on previous period"
cap label var CON_PPCH_SM "Contribution to GDP growth, percentage point change compared to same period in previous year"
cap label var PD15_EUR "Price index (implicit deflator), 2015=100, euro"
cap label var PD10_EUR "Price index (implicit deflator), 2010=100, euro"
cap label var PD05_EUR "Price index (implicit deflator), 2005=100, euro"
cap label var PD15_NAC "Price index (implicit deflator), 2015=100, national currency"
cap label var PD10_NAC "Price index (implicit deflator), 2010=100, national currency"
cap label var PD05_NAC "Price index (implicit deflator), 2005=100, national currency"
cap label var PD_PCH_PRE_EUR "Price index (implicit deflator), percentage change on previous period, euro"
cap label var PD_PCH_PRE_NAC "Price index (implicit deflator), percentage change on previous period, national currency"
cap label var PD_PCH_SM_EUR "Price index (implicit deflator), percentage change compared to same period in previous year, euro"
cap label var PD_PCH_SM_NAC "Price index (implicit deflator), percentage change compared to same period in previous year, national currency"
cap label var CRC_MEUR "Current replacement costs, million euro"
cap label var CRC_MNAC "Current replacement costs, million units of national currency"
cap label var PYR_MEUR "Previous year replacement costs, million euro"
cap label var PYR_MNAC "Previous year replacement costs, million units of national currency"
