cap label var FEI "Formal education and training institutions"
cap label var NFEI "Non-formal education and training institutions"
cap label var PUB_TNG "Public training institutions (financed or guided by the government)"
cap label var PRV_TNG "Private training companies"
cap label var PRV_NTNG "Private companies where the main activity is not training (e.g. equipment suppliers, parent/associate companies)"
cap label var COM_NTNG "Commercial institutions where education and training is not the main activity (e.g. equipment suppliers)"
cap label var NCOM_NTNG "Non-commercial institutions where education and training is not the main activity (e.g. libraries, museums, ministries)"
cap label var EMPL "Employer"
cap label var EO_CHC "Employers' organisations, chambers of commerce"
cap label var TRD_UN "Trade unions"
cap label var NPA "Non-profit associations (e.g. cultural society, political party)"
cap label var IND "Individuals (e.g. students giving private lessons)"
cap label var OTH "Other training providers"
cap label var NRP "No response"
