cap label var TOTAL "Total"
cap label var CRE_DEB_AVG "Average of credits and debits"
cap label var CRE_DEB_SUM "Sum of credits and debits"
cap label var CRE "Credit"
cap label var DEB "Debit"
cap label var LOAN "Loan"
cap label var DPT "Deposit"
cap label var NET "Net"
cap label var PRD "Production"
cap label var PRD_U "Usable production"
cap label var RESASS_MAU "Reserve assets including monetary gold"
cap label var ASS "Assets"
cap label var AD "Gross sales of assets"
cap label var AI "Gross acquisition of assets"
cap label var LIAB "Liabilities"
cap label var LD "Gross decrease in liabilities"
cap label var LI "Gross incurrence of liabilities"
cap label var IMP "Imports"
cap label var IMP_IEU27_2020 "Imports intra-EU27 (from 2020)"
cap label var IMP_IEU28 "Imports intra-EU28 (2013-2020)"
cap label var IMP_XEU "Imports from non-EU countries"
cap label var IMP_XEU27_2020 "Imports extra-EU27 (from 2020)"
cap label var IMP_XEU28 "Imports extra-EU28 (2013-2020)"
cap label var EXP "Exports"
cap label var EXP_IEU27_2020 "Exports intra-EU27 (from 2020)"
cap label var EXP_IEU28 "Exports intra-EU28 (2013-2020)"
cap label var EXP_XEU "Exports to non-EU countries"
cap label var EXP_XEU27_2020 "Exports extra-EU27 (from 2020)"
cap label var EXP_XEU28 "Exports extra-EU28 (2013-2020)"
cap label var BAL "Balance"
cap label var BAL_RT "Balance for values / Ratio for indices"
cap label var BAL_TRD "Trade balance"
cap label var DOM "Domestic"
cap label var DOM_HCN "Domestic - human consumption"
cap label var DOM_IND "Domestic - industrial use"
cap label var DOM_IND_BIO "Domestic - industrial bioethanol or biofuel use"
cap label var DOM_ANF "Domestic - animal feed"
cap label var DOM_CRU "Domestic - crushing"
cap label var DOM_SEED "Domestic - seeds"
cap label var DOM_LOSS "Domestic - losses"
cap label var ADJ "Other adjustments"
cap label var TRN "Transactions"
cap label var M1 "Currency in circulation and overnight deposits"
cap label var M2 "Currency in circulation and overnight deposits (M1) plus deposits with an agreed maturity up to 2 years and deposits redeemable at a period of notice up to 3 months"
cap label var M3 "Currency in circulation and overnight deposits (M1) plus deposits with an agreed maturity up to 2 years and deposits redeemable at a period of notice up to 3 months (M2) plus repurchase agreements and money market fund (MMF) shares/units and debt securities up to 2 years"
cap label var STK "Stock"
cap label var STK_OP "Opening stock"
cap label var STK_CL "Closing stock"
cap label var STKCL_CG "Closing stock - cushion gas"
cap label var STKOP_EUE "Opening stock - EU emergency"
cap label var STKCL_EUE "Closing stock - EU emergency"
cap label var STKOP_NAT "Opening stock - national territory"
cap label var STKCL_NAT "Closing stock - national territory"
cap label var STKOP_JAN_NAT "Opening stock - January - national territory"
cap label var STKCL_DEC_NAT "Closing stock - December - national territory"
cap label var STKOP_EUE_NAT "Opening stock - EU emergency - national territory"
cap label var STKCL_EUE_NAT "Closing stock - EU emergency - national territory"
cap label var STKOP_C_OTH_OA "Opening stock - held for other countries under official agreement"
cap label var STKCL_C_OTH_OA "Closing stock - held for other countries under official agreement"
cap label var STKOP_EUE_EU_OTH_OA "Opening stock - EU emergency - held for other EU Member States under official agreement"
cap label var STKCL_EUE_EU_OTH_OA "Closing stock - EU emergency - held for other EU Member States under official agreement"
cap label var STKCL_C_OTH_OA_TKT "Closing stock - held for other countries under official agreement - of which as tickets"
cap label var STKOP_KFD "Opening stock - with known foreign destination"
cap label var STKCL_KFD "Closing stock - with known foreign destination"
cap label var STKOP_EUE_KFDEU "Opening stock - EU emergency - with known foreign EU destination"
cap label var STKCL_EUE_KFDEU "Closing stock - EU emergency - with known foreign EU destination"
cap label var STKOP_BAXC_OTH_OA_KFD "Opening stock - held in bonded areas excluding stocks held for other countries under official agreement and stocks with known foreign destination"
cap label var STKCL_BAXC_OTH_OA_KFD "Closing stock - held in bonded areas excluding stocks held for other countries under official agreement and stocks with known foreign destination"
cap label var STKOP_MCL "Opening stock - held by major consumers, obligated by law"
cap label var STKCL_MCL "Closing stock - held by major consumers, obligated by law"
cap label var STKOP_OV "Opening stock - held on board incoming ocean vessels in port or at mooring"
cap label var STKCL_OV "Closing stock - held on board incoming ocean vessels in port or at mooring"
cap label var STKOP_NAT_GOV "Opening stock - held by government on national territory"
cap label var STKCL_NAT_GOV "Closing stock - held by government on national territory"
cap label var STKOP_EUE_NAT_GOV "Opening stock - EU emergency - held by government on national territory"
cap label var STKCL_EUE_NAT_GOV "Closing stock - EU emergency - held by government on national territory"
cap label var STKOP_NAT_SHO "Opening stock - held by stock holding organisation on national territory"
cap label var STKCL_NAT_SHO "Closing stock - held by stock holding organisation on national territory"
cap label var STKOP_EUE_NAT_CSE "Opening stock - EU emergency - held by the Central Stockholding Entity (CSE) on national territory"
cap label var STKCL_EUE_NAT_CSE "Closing stock - EU emergency - held by the Central Stockholding Entity (CSE) on national territory"
cap label var STKOP_NAT_OTH "Opening stock - other held on national territory"
cap label var STKCL_NAT_OTH "Closing stock - other held on national territory"
cap label var STKOP_EUE_NAT_EO "Opening stock - EU emergency - held by Economic Operators on national territory"
cap label var STKCL_EUE_NAT_EO "Closing stock - EU emergency - held by Economic Operators on national territory"
cap label var STKOP_EUE_NAT_CEO_DIR "Opening stock - EU emergency - commercial stocks held by Economic Operators on national territory under Directive 2009/119/EC"
cap label var STKCL_EUE_NAT_CEO_DIR "Closing stock - EU emergency - commercial stocks held by Economic Operators on national territory under Directive 2009/119/EC"
cap label var STKOP_ABR "Opening stock - held abroad"
cap label var STKCL_ABR "Closing stock - held abroad"
cap label var STKCL_ABR_GOV_CSE "Closing stock - held abroad - of which pursuant to government - CSE delegation"
cap label var STKOP_ABR_OA "Opening stock - held abroad under official agreement"
cap label var STKCL_ABR_OA "Closing stock - held abroad under official agreement"
cap label var STKCL_ABR_OA_TKT "Closing stock - held abroad under official agreement - of which as tickets"
cap label var STKOP_EUE_ABR_EU_OTH_OA "Opening stock - EU emergency - held abroad in other EU Member States under official agreement"
cap label var STKCL_EUE_ABR_EU_OTH_OA "Closing stock - EU emergency - held abroad in other EU Member States under official agreement"
cap label var STKOP_ABR_OA_GOV "Opening stock - government stocks held abroad under official agreement"
cap label var STKCL_ABR_OA_GOV "Closing stock - government stocks held abroad under official agreement"
cap label var STKOP_ABR_OA_SHO "Opening stock - holding organisation's stocks held abroad under official agreement"
cap label var STKCL_ABR_OA_SHO "Closing stock - holding organisation's stocks held abroad under official agreement"
cap label var STKOP_ABR_OA_OTH "Opening stock - other held abroad under official agreement"
cap label var STKCL_ABR_OA_OTH "Closing stock - other held abroad under official agreement"
cap label var STKOP_ABR_IMP "Opening stock - held abroad - designated definitely for import into your country"
cap label var STKCL_ABR_IMP "Closing stock - held abroad - designated definitely for import into your country"
cap label var STKOP_EUE_EU_OTH_IMP "Opening stock - EU emergency - held abroad in EU, designated definitely for import into your country"
cap label var STKCL_EUE_EU_OTH_IMP "Closing stock levels - EU emergency - held abroad in EU, designated definitely for import into your country"
cap label var STKOP_BA "Opening stock - other in bonded areas"
cap label var STKCL_BA "Closing stock - other in bonded areas"
cap label var STKOP_PF "Opening stock - pipeline fill"
cap label var STKCL_PF "Closing stock - pipeline fill"
cap label var STK_EUE_MTH "Method for Emergency Stocks held by the MS"
cap label var STK_EUE_DIR "Emergency Stocks held by the MS in accordance with the EU Directive (in Days Equivalent)"
cap label var STK_EUE_DNY_MTH "Method of deduction for naphtha yield - EU emergency"
cap label var STK_EUE_MIN_MTH "Method of calculation of the minimum stock level - EU emergency"
cap label var IMP_DNC "Daily net imports for compliance"
cap label var IC_DC "Daily inland consumption for compliance"
cap label var NETIMP_ICC_CAL "Daily net imports or inland consumption for compliance - calculated"
cap label var OBL_MTH_CAL "Method for calculation of obligation - calculated"
cap label var STK_MIN_CAL "Minimum stocklevel for compliance - calculated"
cap label var MRGO "Refinery gross output (sum of monthly figures)"
cap label var MRF "Refinery fuel (sum of monthly figures)"
cap label var MIMP "Imports (sum of monthly figures)"
cap label var MEXP "Exports (sum of monthly figures)"
cap label var MRI_CAL "Refinery intake - calculated (sum of monthly figures)"
cap label var MINTMARB "International marine bunkers (sum of monthly figures)"
cap label var MGID_OBS "Gross inland deliveries - observed (sum of monthly figures)"
cap label var MBKFLOW "Backflows to refineries (sum of monthly figures)"
cap label var STK_BMY "Stock at the beginning of the marketing year"
cap label var STK_EMY "Stock at the end of the marketing year"
cap label var STK_CHG "Change in stock"
cap label var STK_GRS "Gross stock"
cap label var STK_NET "Net stock"
cap label var FLOW_GRS "Gross flow"
cap label var FLOW_NET "Net flow"
cap label var EXPN "Expenditure"
cap label var INC "Income"
cap label var SAV "Savings"
cap label var WLTH_NET "Net wealth"
cap label var INCR "Increase"
cap label var DECR "Decrease"
cap label var NAI "Net annual increment"
cap label var RMOV "Removals"
cap label var LOSS "Losses"
cap label var LOSS_MEUR "Losses - million euro"
cap label var LOSS_MET "Losses by meteorological events"
cap label var LOSS_MET_MEUR "Losses by meteorological events - million euro"
cap label var LOSS_HYD "Losses by hydrological events"
cap label var LOSS_HYD_MEUR "Losses by hydrological events - million euro"
cap label var LOSS_CLIM "Losses by climatological events"
cap label var LOSS_CLIM_MEUR "Losses by climatological events - million euro"
cap label var LOSS_AVG30Y_MEUR "Average losses over 30 years - million euro"
cap label var LOSS_AVG30Y_EUR_HAB "Average losses over 30 years - euro per capita"
cap label var ENT "Entrants"
cap label var EXIT "Exits"
cap label var IN "Inwards"
cap label var OUT "Outwards"
cap label var PAID "Paid"
cap label var RECV "Received"
cap label var SUP "Supply"
cap label var USE "Use"
cap label var USE_TRS "Transformation use"
cap label var USE_END "End use"
cap label var ER_USE "Emission-relevant use"
cap label var BL "Backward linkages"
cap label var FL "Forward linkages"
cap label var REVAL "Revaluation"
cap label var RCLAS "Statistical re-classification"
cap label var II "Net income on inward FDI"
cap label var IO "Net income on outward FDI"
cap label var NI "Net FDI inward"
cap label var NI_LE "Net FDI inward - positions at the end of period"
cap label var NO "Net FDI outward"
cap label var NO_LE "Net FDI outward - positions at the end of period"
cap label var K3_K6 "Other flows: catastrophic losses, uncompensated seizures, other changes in volume n.e.c. and changes in classification"
cap label var KA "Other changes in volume"
cap label var K7 "Nominal holding gains and losses"
cap label var A_LE "Assets - positions at the end of period"
cap label var A_K7A "Assets - revaluations due to exchange rate changes"
cap label var A_K7B "Assets - revaluations due to other price changes"
cap label var A_KA "Assets - other changes in the volume of Assets/Liabilities"
cap label var L_LE "Liabilities - positions at the end of period"
cap label var L_K7A "Liabilities - revaluations due to exchange rate changes"
cap label var L_K7B "Liabilities - revaluations due to other price changes"
cap label var L_KA "Liabilities - other changes in the volume of Assets/Liabilities"
cap label var N_LE "Net positions at the end of period"
cap label var N_K7A "Net revaluations due to exchange rate changes"
cap label var N_K7B "Net revaluations due to other price changes"
cap label var N_KA "Net other changes in the volume of Assets/Liabilities"
cap label var NE_LE "Net liabilities (liabilities minus assets)"
cap label var HUMD_PC "Humidity (%)"
cap label var NSP "Not specified"
cap label var UNK "Unknown"
