cap label var INP "Input total"
cap label var INP_S1 "Intermediate consumption"
cap label var SED "Seeds and planting stock"
cap label var SED_IN "Seeds and planting stock supplied by other agricultural holdings"
cap label var SED_OUT "Seeds and planting stock purchased from outside the agricultural 'industry'"
cap label var ARP "Animals for rearing and production"
cap label var NRG_LUB_X_E_F "Energy products and lubricants, excluding electricity, fuels and propellants"
cap label var NRG_LUB "Energy products and lubricants"
cap label var NRG "Energy products"
cap label var NRG_E "Electricity"
cap label var NRG_G "Gas"
cap label var NRG_F "Fuels and propellants"
cap label var NRG_FH "Fuels for heating"
cap label var NRG_FH_G "Heating gas oil"
cap label var NRG_R "Residual fuel oil"
cap label var NRG_FM "Motor fuels"
cap label var NRG_FM_S "Motor spirit"
cap label var NRG_FM_D "Diesel oil"
cap label var LUB "Lubricants"
cap label var NRG_LUB_OTH "Other energy products and lubricants"
cap label var FER "Fertilisers and soil improvers"
cap label var FER_IN "Fertilisers supplied by other agricultural holdings"
cap label var FER_OUT "Fertilisers purchased from outside the agricultural 'industry'"
cap label var FER_S "Straight fertilisers"
cap label var FER_S_N "Nitrogenous fertilisers"
cap label var FER_S_N_SA "Sulphate of ammonia"
cap label var FER_S_N_AN1 "Ammonium nitrate (20.5% N)"
cap label var FER_S_N_AN2 "Ammonium nitrate (21% N)"
cap label var FER_S_N_AN3S "Ammonium nitrate (26% N) (in sacks)"
cap label var FER_S_N_AN3B "Ammonium nitrate (26% N) (in bulk)"
cap label var FER_S_N_AN4 "Ammonium nitrate (33% N)"
cap label var FER_S_N_AN4S "Ammonium nitrate (33% N) (in sacks)"
cap label var FER_S_N_AN4B "Ammonium nitrate (33% N) (in bulk)"
cap label var FER_S_N_AA "Anhydrous ammonia (82% N)"
cap label var FER_S_N_NH "Urea"
cap label var FER_S_N_UAN "Urea - ammonium nitrate solution (UAN)"
cap label var FER_S_N_OTH "Other nitrogenous fertilisers"
cap label var FER_S_P "Phosphatic fertilisers"
cap label var FER_S_P_PR "Phosphate rock"
cap label var FER_S_P_AP "Ammonium phosphate"
cap label var FER_S_P_SP "Superphosphate (18% P2O5)"
cap label var FER_S_P_TSP "Triple superphosphate (46% P2O5)"
cap label var FER_S_K "Potassic fertilisers"
cap label var FER_S_K_MOP "Muriate of potash"
cap label var FER_S_K_SOP "Sulphate of potash"
cap label var FER_C "Compound fertilisers"
cap label var FER_C_NP "NP fertilisers"
cap label var FER_C_NP1 "NP fertilisers 1 - 1 - 0"
cap label var FER_C_NP2 "Diammonium phosphate (DAP)"
cap label var FER_C_NP3 "Monoammonium phosphate (MAP)"
cap label var FER_C_NP_OTH "Other NP fertilisers"
cap label var FER_C_PK "PK fertilisers"
cap label var FER_C_PK1 "PK fertilisers 0 - 1 - 1"
cap label var FER_C_PK2 "PK fertilisers 0 - 20 - 20"
cap label var FER_C_PK3 "Potassium nitrate"
cap label var FER_C_PK4 "PK fertilisers 0 - 20 - 25"
cap label var FER_C_NPK "NPK fertilisers"
cap label var FER_C_NPK1 "NPK fertilisers 1 - 0.5 - 0.5"
cap label var FER_C_NPK2 "NPK fertilisers 20 - 10 - 10"
cap label var FER_C_NPK3S "NPK fertilisers 1 - 1 - 1 (in sacks)"
cap label var FER_C_NPK4S "NPK fertilisers 17 - 17 - 17 (in sacks)"
cap label var FER_C_NPK3B "NPK fertilisers 1 - 1 - 1 (in bulk)"
cap label var FER_C_NPK4B "NPK fertilisers 17 - 17 - 17 (in bulk)"
cap label var FER_C_NPK5C "NPK complex fertilisers 15 - 15 - 15"
cap label var FER_C_NPK5M "NPK blended fertilisers 15 - 15 - 15"
cap label var FER_C_NPK6 "NPK fertilisers 26 - 2 - 3"
cap label var FER_C_NPK7 "NPK fertilisers 20 - 4 - 8"
cap label var FER_C_NPK8 "NPK fertilisers 18 - 5 - 10"
cap label var FER_C_NPK9 "NPK fertilisers 23 - 5 - 10"
cap label var FER_C_NPK10 "NPK fertilisers 18 - 3 - 12"
cap label var FER_C_NPK11 "NPK fertilisers 12 - 6 - 17"
cap label var FER_C_NPK12 "NPK fertilisers 14 - 9 - 10"
cap label var FER_C_NPK13 "NPK fertilisers 1 - 1 - 2"
cap label var FER_C_NPK14 "NPK fertilisers 9 - 9 - 18"
cap label var FER_C_NPK15 "NPK fertilisers 1 - 2 - 2"
cap label var FER_C_NPK16 "NPK fertilisers 10 - 20 - 20"
cap label var FER_OTH "Other fertilisers and soil improvers"
cap label var PES "Plant protection products"
cap label var PES_F "Fungicides and bactericides"
cap label var F01 "Inorganic fungicides"
cap label var F01_01 "Copper compounds"
cap label var F01_02 "Inorganic sulfur"
cap label var F01_99 "Other inorganic fungicides"
cap label var F02 "Fungicides based on carbamates and dithiocarbamates"
cap label var F02_01 "Carbanilate fungicides"
cap label var F02_02 "Carbamate fungicides"
cap label var F02_03 "Dithiocarbamate fungicides"
cap label var F02_99 "Other fungicides based on carbamates and dithiocarbamates"
cap label var F03 "Fungicides based on benzimidazoles"
cap label var F03_01 "Benzimidazole fungicides"
cap label var F03_99 "Other fungicides based on benzimidazoles"
cap label var F04 "Fungicides based on imidazoles and triazoles"
cap label var F04_01 "Conazole fungicides"
cap label var F04_02 "Imidazole fungicides"
cap label var F04_99 "Other fungicides based on imidazoles and triazoles"
cap label var F05 "Fungicides based on morpholines"
cap label var F05_01 "Morpholine fungicides"
cap label var F05_99 "Other fungicides based on morpholines"
cap label var F06 "Biological fungicides"
cap label var F06_01 "Biological fungicides"
cap label var F06_99 "Other biological fungicides"
cap label var F99 "Other fungicides"
cap label var F99_01 "Aliphatic nitrogen fungicides"
cap label var F99_02 "Amide fungicides"
cap label var F99_03 "Anilide fungicides"
cap label var F99_05 "Aromatic fungicides"
cap label var F99_06 "Dicarboximide fungicides"
cap label var F99_07 "Dinitroaniline fungicides"
cap label var F99_08 "Dinitrophenol fungicides"
cap label var F99_09 "Organophosphorus fungicides"
cap label var F99_10 "Oxazole fungicides"
cap label var F99_11 "Phenylpyrrole fungicides"
cap label var F99_12 "Phthalimide fungicides"
cap label var F99_13 "Pyrimidine fungicides"
cap label var F99_14 "Quinoline fungicides"
cap label var F99_15 "Quinone fungicides"
cap label var F99_16 "Strobilurine fungicides"
cap label var F99_17 "Urea fungicides"
cap label var F99_99 "Unclassified fungicides"
cap label var PES_I "Insecticides and acaricides"
cap label var I01 "Insecticides based on pyrethroids"
cap label var I01_01 "Pyrethroid insecticides"
cap label var I01_99 "Other insecticides based on pyrethroids"
cap label var I02 "Insecticides based on chlorinated hydrocarbons"
cap label var I02_99 "Other insecticides based on chlorinated hydrocarbons"
cap label var I03 "Insecticides based on carbamates and oxime-carbamate"
cap label var I03_01 "Oxime-carbamate insecticides"
cap label var I03_02 "Carbamate insecticides"
cap label var I03_99 "Other insecticides based on carbamates and oxime-carbamate"
cap label var I04 "Insecticides based on organophosphates"
cap label var I04_01 "Organophosphorus insecticides"
cap label var I04_99 "Other insecticides based on organophosphates"
cap label var I05 "Biological and botanical product-based insecticides"
cap label var I05_01 "Biological insecticides"
cap label var I05_99 "Other biological and botanical product based insecticides"
cap label var I99 "Other insecticides"
cap label var I99_01 "Insecticides produced by fermentation"
cap label var I99_03 "Benzoylurea insecticides"
cap label var I99_04 "Carbazate insecticides"
cap label var I99_05 "Diazylhydrazine insecticides"
cap label var I99_06 "Insect growth regulators"
cap label var I99_07 "Insect pheromones"
cap label var I99_08 "Nitroguanidine insecticides"
cap label var I99_09 "Organotin insecticides"
cap label var I99_10 "Oxadiazine insecticides"
cap label var I99_11 "Phenyl-ether insecticides"
cap label var I99_12 "Pyrazole (phenyl-) insecticides"
cap label var I99_13 "Pyridine insecticides"
cap label var I99_14 "Pyridylmethylamine insecticides"
cap label var I99_15 "Sulfite ester insecticides"
cap label var I99_16 "Tetrazine insecticides"
cap label var I99_17 "Tetronic acid insecticides"
cap label var I99_99 "Unclassified insecticides-acaricides"
cap label var PES_H "Herbicides, haulm destructors and moss killers"
cap label var H01 "Herbicides based on phenoxy-phytohormones"
cap label var H01_01 "Phenoxy herbicides"
cap label var H01_99 "Other herbicides based on phenoxy-phytohormones"
cap label var H02 "Herbicides based on triazines and triazinones"
cap label var H02_02 "Triazine herbicides"
cap label var H02_03 "Triazinone herbicides"
cap label var H02_99 "Other herbicides based on triazines and triazinones"
cap label var H03 "Herbicides based on amides and anilides"
cap label var H03_01 "Amide herbicides"
cap label var H03_02 "Anilide herbicides"
cap label var H03_03 "Chloroacetanilide herbicides"
cap label var H03_99 "Other herbicides based on amides and anilides"
cap label var H04 "Herbicides based on carbamates and bis-carbamates"
cap label var H04_01 "Bis-carbamate herbicides"
cap label var H04_02 "Carbamate herbicides"
cap label var H04_99 "Other herbicides based on carbamates and bis-carbamates"
cap label var H05 "Herbicides based on dinitroaniline derivatives"
cap label var H05_01 "Dinitroaniline herbicides"
cap label var H05_99 "Other herbicides based on dinitroaniline derivatives"
cap label var H06 "Herbicides based on derivatives of urea, of uracil or of sulfonylurea"
cap label var H06_01 "Sulfonylurea herbicides"
cap label var H06_02 "Uracil herbicides"
cap label var H06_03 "Urea herbicides"
cap label var H06_99 "Other herbicides based on derivatives of urea, of uracil or of sulfonylurea"
cap label var H99 "Other herbicides"
cap label var H99_01 "Aryloxyphenoxy- propionic herbicides"
cap label var H99_02 "Benzofurane herbicides"
cap label var H99_03 "Benzoic-acid herbicides"
cap label var H99_04 "Bipyridylium herbicides"
cap label var H99_05 "Cyclohexanedione herbicides"
cap label var H99_06 "Diazine herbicides"
cap label var H99_07 "Dicarboximide herbicides"
cap label var H99_08 "Diphenyl ether herbicides"
cap label var H99_09 "Imidazolinone herbicides"
cap label var H99_10 "Inorganic herbicides"
cap label var H99_11 "Isoxazole herbicides"
cap label var H99_13 "Nitrile herbicides"
cap label var H99_14 "Organophosphorus herbicides"
cap label var H99_15 "Phenylpyrazole herbicides"
cap label var H99_16 "Pyridazinone herbicides"
cap label var H99_17 "Pyridinecarboxamide herbicides"
cap label var H99_18 "Pyridinecarboxylic-acid herbicides"
cap label var H99_19 "Pyridyloxyacetic-acid herbicides"
cap label var H99_20 "Quinoline herbicides"
cap label var H99_21 "Thiadiazine herbicides"
cap label var H99_22 "Thiocarbamate herbicides"
cap label var H99_23 "Triazole herbicides"
cap label var H99_24 "Triazolinone herbicides"
cap label var H99_25 "Triazolone herbicides"
cap label var H99_26 "Triketone herbicides"
cap label var H99_99 "Unclassified herbicides"
cap label var PES_M "Molluscicides"
cap label var M01 "Molluscicides"
cap label var M01_01 "Molluscicides"
cap label var PES_PGR "Plant growth regulators"
cap label var PGR01 "Physiological plant growth regulators"
cap label var PGR01_01 "Physiological plant growth regulators"
cap label var PGR01_99 "Other physiological plant growth regulators"
cap label var PGR02 "Anti-sprouting products"
cap label var PGR02_02 "Antisprouting products"
cap label var PGR02_99 "Other antisprouting products"
cap label var PGR03 "Other plant growth regulators"
cap label var PGR03_99 "Other plant growth regulators"
cap label var PES_ZR "Other plant protection products"
cap label var ZR01 "Mineral oils"
cap label var ZR02 "Vegetal oils"
cap label var ZR02_01 "Vegetal oils"
cap label var ZR03 "Soil sterilants (incl. nematicides)"
cap label var ZR03_01 "Methyl bromide"
cap label var ZR03_99 "Other soil sterilants"
cap label var ZR04 "Rodenticides"
cap label var ZR04_01 "Rodenticides"
cap label var ZR99 "All other plant protection products"
cap label var ZR99_01 "Disinfectants"
cap label var ZR99_99 "Other plant protection products"
cap label var FDS "Animal feedingstuffs"
cap label var FDS_IN "Feedingstuffs supplied by other agricultural holdings"
cap label var FDS_OUT "Feedingstuffs purchased from outside the agricultural 'industry'"
cap label var FDS_OWN "Feedingstuffs produced and consumed by the same holding"
cap label var FDS_S "Straight feedingstuffs"
cap label var FDS_S_CM "Feedingstuffs: cereals and milling by-products"
cap label var FDS_S_CM_FW "Feedingstuffs: fodder wheat"
cap label var FDS_S_CM_BAR "Feedingstuffs: barley"
cap label var FDS_S_CM_OAT "Feedingstuffs: oats"
cap label var FDS_S_CM_MAI "Feedingstuffs: maize"
cap label var FDS_S_CM_WB "Feedingstuffs: wheat bran"
cap label var FDS_S_CM_GB "Feedingstuffs: ground barley"
cap label var FDS_S_CM_GM "Feedingstuffs: ground maize"
cap label var FDS_S_OC "Feedingstuffs: oil-cakes"
cap label var FDS_S_OC_L "Feedingstuffs: linseed cake (expeller)"
cap label var FDS_S_OC_TSM "Feedingstuffs: toasted extracted soyabean meal"
cap label var FDS_S_ANI "Feedingstuffs of animal origin"
cap label var FDS_S_ANI_A "Feedingstuffs: Animal meal"
cap label var FDS_S_ANI_F "Feedingstuffs: Fish meal"
cap label var FDS_S_OTH "Other straight feedingstuffs"
cap label var FDS_S_OTH_FDB "Feedingstuffs: field beans"
cap label var FDS_S_OTH_FDP "Feedingstuffs: field peas"
cap label var FDS_S_OTH_FOP "Feedingstuffs: fodder peas"
cap label var FDS_S_OTH_DSB "Feedingstuffs: dried sugar beet pulp"
cap label var FDS_S_OTH_MH "Feedingstuffs: meadow hay"
cap label var FDS_S_OTH_DL "Feedingstuffs: dried lucerne"
cap label var FDS_S_OTH_CS "Feedingstuffs: cereal straw"
cap label var FDS_C "Compound feedingstuffs"
cap label var FDS_C_CAL "Compound feedingstuffs for calves"
cap label var FDS_C_CAL_1 "Complementary feed for rearing calves"
cap label var FDS_C_CAL_2MS "Milk replacer for fattening calves (in sacks)"
cap label var FDS_C_CAL_2MB "Milk replacer for fattening calves (in bulk)"
cap label var FDS_C_CATXCAL "Compound feedingstuffs for cattle (excluding calves)"
cap label var FDS_C_CAT_1 "Complementary feed for dairy cattle (grass-fed)"
cap label var FDS_C_CAT_2S "Complementary feed for dairy cattle (stall-fed) (in sacks)"
cap label var FDS_C_CAT_2B "Complementary feed for dairy cattle (stall-fed) (in bulk)"
cap label var FDS_C_CAT_P2S "Protein-rich complementary feed for dairy cattle (stall-fed) (in sacks)"
cap label var FDS_C_CAT_P2B "Protein-rich complementary feed for dairy cattle (stall-fed) (in bulk)"
cap label var FDS_C_CAT_3S "Complementary feed for cattle fattening (in sacks)"
cap label var FDS_C_CAT_3B "Complementary feed for cattle fattening (in bulk)"
cap label var FDS_C_CAT_P3S "Protein-rich complementary feed for cattle fattening (in sacks)"
cap label var FDS_C_CAT_P3B "Protein-rich complementary feed for cattle fattening (in bulk)"
cap label var FDS_C_PIG "Compound feedingstuffs for pigs"
cap label var FDS_C_PIG_1S "Complete feed for rearing pigs (in sacks)"
cap label var FDS_C_PIG_1B "Complete feed for rearing pigs (in bulk)"
cap label var FDS_C_PIG_2S "Complete feed for sows (in sacks)"
cap label var FDS_C_PIG_2B "Complete feed for sows (in bulk)"
cap label var FDS_C_PIG_3S "Complete feed for fattening pigs (in sacks)"
cap label var FDS_C_PIG_3B "Complete feed for fattening pigs (in bulk)"
cap label var FDS_C_PLT "Compound feedingstuffs for poultry"
cap label var FDS_C_PLT_1S "Baby chick feed (in sacks)"
cap label var FDS_C_PLT_1B "Baby chick feed (in bulk)"
cap label var FDS_C_PLT_2S "Complete feed for rearing pullet (in sacks)"
cap label var FDS_C_PLT_2B "Complete feed for rearing pullet (in bulk)"
cap label var FDS_C_PLT_3S "Complete feed for battery laying hens (in sacks)"
cap label var FDS_C_PLT_3B "Complete feed for battery laying hens (in bulk)"
cap label var FDS_C_PLT_4S "Complete feed for broiler production (in sacks)"
cap label var FDS_C_PLT_4B "Complete feed for broiler production (in bulk)"
cap label var FDS_C_OTH "Other compound feedingstuffs"
cap label var MTL "Material and small tools"
cap label var MNT "Maintenance and repair of plants"
cap label var MNT_BLD "Maintenance of buildings"
cap label var VET "Veterinary services"
cap label var AGR "Agricultural services"
cap label var AGR_FISIM "Financial intermediation services indirectly measured (FISIM)"
cap label var GEN "General expenses"
cap label var INP_S1_OTH "Other intermediate consumption"
cap label var INP_S2 "Investment goods and services"
cap label var MAC "Machinery and other equipment"
cap label var MAC_2WHL "Rotovator and other 2 wheels equipment"
cap label var MAC_CLT "Machinery and plant for cultivation"
cap label var MAC_HVT "Machinery and plant for harvesting"
cap label var MAC_INS "Farm machinery and installations"
cap label var MAC_INS_CRP "Machinery and installations for crop production"
cap label var MAC_INS_ANI "Machinery and installations for animal production"
cap label var MAC_INS_OTH "Other farm machinery and installations"
cap label var MAC_TSP "Transport equiment"
cap label var MAC_TSP_TRT "Tractors"
cap label var MAC_TSP_OTH "Other vehicles"
cap label var BLD "Buildings and structures"
cap label var BLD_FRM "Farm buildings"
cap label var BLD_IMP "Engineering and soil improvement operations"
cap label var BLD_OTH "Other buildings and structures"
cap label var INP_S2_OTH "Other investment goods and services"
cap label var INP_OTH "Other investment"
