cap label var AREA_KM2 "Country area (km2)"
cap label var PRO "Protected area"
cap label var PRO_BIO "Protected area - biodiversity"
cap label var PRO_LSC "Protected area - landscape features"
cap label var PRO_NAT00 "Protected area - Natura 2000"
cap label var TPA "Terrestrial protected area"
cap label var TPA_KM2 "Terrestrial protected area (km2)"
cap label var TPA_PC "Terrestrial protected area (%)"
cap label var TPA_SI "Terrestrial protected area (sufficiency index)"
cap label var MA_KM2 "Marine area (km2)"
cap label var MPA "Marine protected area"
cap label var MPA_KM2 "Marine protected area (km2)"
cap label var MPA_PC "Marine protected area (%)"
cap label var MPA_SI "Marine protected area (sufficiency index)"
cap label var PRT "Area with a protective function"
cap label var PRT_ECO "Area protecting soil, water and other ecosystems"
cap label var PRT_INFR "Area protecting infrastructure"
