cap label var TOTAL "Total"
cap label var ICCS01 "Acts leading to death or intending to cause death"
cap label var ICCS0101_0102 "Intentional homicide and attempted intentional homicide"
cap label var ICCS0101 "Intentional homicide"
cap label var ICCS0102 "Attempted intentional homicide"
cap label var ICCS02_04 "Acts causing harm or intending to cause harm to the person, injurious acts of a sexual nature and acts against property involving violence or threat against a person"
cap label var ICCS02 "Acts causing harm or intending to cause harm to the person"
cap label var ICCS0201 "Assaults and threats"
cap label var ICCS02011 "Assault"
cap label var ICCS020111 "Serious assault"
cap label var ICCS0202 "Acts against liberty"
cap label var ICCS02022 "Deprivation of liberty"
cap label var ICCS020221 "Kidnapping"
cap label var ICCS0204 "Trafficking in persons"
cap label var ICCS02041 "Trafficking in persons for sexual exploitation"
cap label var ICCS02042 "Trafficking in persons for forced labour or services"
cap label var ICCS02043_02044 "Trafficking in persons for organ removal and other purposes"
cap label var ICCS03 "Injurious acts of a sexual nature"
cap label var ICCS0301 "Sexual violence"
cap label var ICCS03011 "Rape"
cap label var ICCS03012 "Sexual assault"
cap label var ICCS03019 "Other acts of sexual violence"
cap label var ICCS0302 "Sexual exploitation"
cap label var ICCS03022 "Sexual exploitation of children"
cap label var ICCS04 "Acts against property involving violence or threat against a person"
cap label var ICCS0401 "Robbery"
cap label var ICCS05 "Acts against property only"
cap label var ICCS0501 "Burglary"
cap label var ICCS05012 "Burglary of private residential premises"
cap label var ICCS0502 "Theft"
cap label var ICCS05021 "Theft of a motorized vehicle or parts thereof"
cap label var ICCS050211 "Theft of a motorized land vehicle"
cap label var ICCS06 "Acts involving controlled drugs or other psychoactive substances"
cap label var ICCS0601 "Unlawful acts involving controlled drugs or precursors"
cap label var ICCS07 "Acts involving fraud, deception or corruption"
cap label var ICCS08 "Acts against public order, authority and provisions of the State"
cap label var ICCS09 "Acts against public safety and state security"
cap label var ICCS10 "Acts against the natural environment"
cap label var ICCS11 "Other criminal acts not elsewhere classified"
