cap label var LA_1 "Total agricultural land"
cap label var LA_1_1 "Arable land"
cap label var LA_1_2 "Land under permanent crops"
cap label var LA_1_3 "Land under permanent meadows and pasture"
cap label var LA_1_4 "Other agricultural land"
cap label var LA_1_5 "Agricultural irrigated land"
cap label var LA_2 "Total land under forest and other wooded land"
cap label var LA_2_1 "Predominantly coniferous"
cap label var LA_2_2 "Predominantly broadleaved"
cap label var LA_2_3 "Predominantly other"
cap label var LA_2_4 "Mixed forest"
cap label var LA_2_5 "Other wooded land"
cap label var LA_3 "Built-up and related land"
cap label var LA_3_1 "Residential land"
cap label var LA_3_2 "Industrial land"
cap label var LA_3_3 "Land used for quarries, pits, mines, etc."
cap label var LA_3_4 "Commercial land"
cap label var LA_3_5 "Land used for public services, excluding transport, communication and technical infrastructure"
cap label var LA_3_6 "Land of mixed use"
cap label var LA_3_7 "Land used for transport and communication"
cap label var LA_3_8 "Land used for technical infrastucture"
cap label var LA_3_9 "Recreational and other open land"
cap label var LA_4 "Wet open lands"
cap label var LA_4_1 "Mires"
cap label var LA_4_2 "Wet tundra"
cap label var LA_4_3 "Other wet open lands"
cap label var LA_5 "Total dry open lands"
cap label var LA_5_1 "Dry open land with special vegetation cover"
cap label var LA_5_1_1 "Heathland"
cap label var LA_5_1_2 "Dry tundra"
cap label var LA_5_1_3 "Mountainous grassland"
cap label var LA_5_1_4 "Other dry open land with special vegetation cover"
cap label var LA_5_2 "Dry open land without, or with insignificant vegetation cover"
cap label var LA_5_2_1 "Bare rocks, glaciers and perpetual snow"
cap label var LA_5_2_2 "Sand beaches, dunes and other sandy lands"
cap label var LA_5_2_3 "Other dry open land without, or with insignificant vegetation cover"
cap label var LA_6 "Waters"
cap label var LA_6_1 "Inland waters"
cap label var LA_6_2 "Tidal waters"
cap label var LA_7 "Land area"
cap label var LA_8 "Total area"
cap label var LA_9 "Total gains"
cap label var LA_9_1 "Area affected by erosion"
cap label var LA_9_2 "Area affected by desertification"
