cap label var TOTAL "Total"
cap label var IND_TOTAL "All Individuals"
cap label var Y0_15 "Individuals, 15 years old or less"
cap label var Y15_29 "Individuals, 15 to 29 years old"
cap label var Y16_19 "Individuals, 16 to 19 years old"
cap label var Y16_24 "Individuals, 16 to 24 years old"
cap label var Y16_29 "Individuals, 16 to 29 years old"
cap label var Y20_24 "Individuals, 20 to 24 years old"
cap label var Y25_29 "Individuals, 25 to 29 years old"
cap label var Y25_34 "Individuals, 25 to 34 years old"
cap label var Y25_54 "Individuals, 25 to 54 years old"
cap label var Y25_64 "Individuals, 25 to 64 years old"
cap label var Y35_44 "Individuals, 35 to 44 years old"
cap label var Y45_54 "Individuals, 45 to 54 years old"
cap label var Y55_64 "Individuals, 55 to 64 years old"
cap label var Y55_74 "Individuals, 55 to 74 years old"
cap label var Y65_74 "Individuals, 65 to 74 years old"
cap label var Y75_MAX "Individuals, 75 years old or more"
cap label var Y16_24LO "Individuals aged 16-24 with low education"
cap label var Y16_24ME "Individuals aged 16-24 with medium formal education"
cap label var Y16_24HI "Individuals aged 16-24 with high formal education"
cap label var Y25_54LO "Individuals aged 25 to 54 with low formal education"
cap label var Y25_54ME "Individuals aged 25 to 54 with medium formal education"
cap label var Y25_54HI "Individuals aged 25 to 54 with high formal education"
cap label var Y25_64LO "Individuals aged 25 to 64 with low formal education"
cap label var Y25_64ME "Individuals aged 25 to 64 with medium formal education"
cap label var Y25_64HI "Individuals aged 25 to 64 with high formal education"
cap label var Y55_74LO "Individuals aged 55 to 74 with low formal education"
cap label var Y55_74ME "Individuals aged 55 to 74 with medium formal education"
cap label var Y55_74HI "Individuals aged 55 to 74 with high formal education"
cap label var Y25_64_SALSELFFAM "Individuals aged 25 to 64 who are employees, self-employed or family workers"
cap label var Y25_64_UNE "Individuals aged 25 to 64 who are unemployed"
cap label var Y25_64_EMPL_UNE "Individuals aged 25 to 64 who are in the labour force (employed and unemployed)"
cap label var Y25_64_RETIROTH "Individuals aged 25 to 64 who are retired or not in the labour force (excluding students)"
cap label var M_Y16_19 "Males, 16 to 19 years old"
cap label var F_Y16_19 "Females, 16 to 19 years old"
cap label var M_Y16_24 "Males, 16 to 24 years old"
cap label var F_Y16_24 "Females, 16 to 24 years old"
cap label var M_Y16_29 "Males, 16 to 29 years old"
cap label var F_Y16_29 "Females, 16 to 29 years old"
cap label var M_Y16_74 "Males, 16 to 74 years old"
cap label var F_Y16_74 "Females, 16 to 74 years old"
cap label var M_Y20_24 "Males, 20 to 24 years old"
cap label var F_Y20_24 "Females, 20 to 24 years old"
cap label var M_Y25_29 "Males, 25 to 29 years old"
cap label var F_Y25_29 "Females, 25 to 29 years old"
cap label var M_Y25_34 "Males, 25 to 34 years old"
cap label var F_Y25_34 "Females, 25 to 34 years old"
cap label var M_Y25_54 "Males 25 to 54 years old"
cap label var F_Y25_54 "Females 25 to 54 years old"
cap label var M_Y25_64 "Males, 25 to 64 years old"
cap label var F_Y25_64 "Females, 25 to 64 years old"
cap label var M_Y35_44 "Males, 35 to 44 years old"
cap label var F_Y35_44 "Females, 35 to 44 years old"
cap label var M_Y45_54 "Males, 45 to 54 years old"
cap label var F_Y45_54 "Females, 45 to 54 years old"
cap label var M_Y55_64 "Males, 55 to 64 years old"
cap label var F_Y55_64 "Females, 55 to 64 years old"
cap label var M_Y55_74 "Males 55 to 74 years old"
cap label var F_Y55_74 "Females 55 to 74 years old"
cap label var M_Y65_74 "Males, 65 to 74 years old"
cap label var F_Y65_74 "Females, 65 to 74 years old"
cap label var M_I0_2 "Males with low formal education"
cap label var F_I0_2 "Females with low formal education"
cap label var M_I3_4 "Males with medium formal education"
cap label var F_I3_4 "Females with medium formal education"
cap label var M_I5_8 "Males with high formal education"
cap label var F_I5_8 "Females with high formal education"
cap label var I0_2 "Individuals with no or low formal education"
cap label var I3_4 "Individuals with medium formal education"
cap label var I5_8 "Individuals with high formal education"
cap label var CB_EU_FOR "Individuals who are born in another EU Member State"
cap label var CB_EXT_EU "Individuals who are born in non-EU country"
cap label var CB_FOR "Individuals who are foreign-born"
cap label var CB_NAT "Individuals who are native-born"
cap label var CC_EU_FOR "Nationals of another EU-Member State"
cap label var CC_EXT_EU "Nationals of non-EU country"
cap label var CC_FOR "Non-nationals"
cap label var CC_NAT "Nationals"
cap label var EMPL_UNE "Individuals in the labour force (employed and unemployed)"
cap label var FAM "Family and relatives"
cap label var FAM_HLD_BLUE "Family member of EU Blue Cards holder"
cap label var PRT_INT "Intimate partner"
cap label var FRD "Friends"
cap label var HHI_Q1 "Individual living in a household with income in first quartile"
cap label var HHI_Q2 "Individual living in a household with income in second quartile"
cap label var HHI_Q3 "Individual living in a household with income in third quartile"
cap label var HHI_Q4 "Individual living in a household with income in fourth quartile"
cap label var IND_DEG1 "Individuals living in cities"
cap label var IND_DEG2 "Individuals living in towns and suburbs"
cap label var IND_DEG3 "Individuals living in rural areas"
cap label var IND_DEV_L "Individuals living in less developed regions"
cap label var IND_DEV_M "Individuals living in more developed regions"
cap label var IND_DEV_T "Individuals living in transition regions"
cap label var IND_O1 "Individuals living in Objective 1 regions / 'Convergence' regions"
cap label var IND_NO1 "Individuals living in Not Objective 1 regions / 'Regional Competitiveness and Employment' Region"
cap label var IND_BROAD "Individuals living in a household with broadband access"
cap label var IND_BROADX "Individuals living in a household with Internet access but with no broadband access"
cap label var ISCO_ICT "ICT professionals"
cap label var ISCO_ICTX "Non ICT professionals"
cap label var ISCO0_5 "Non-manual including the armed forces"
cap label var ISCO6_9 "Manual"
cap label var IREG "Individuals regularly using the Internet (at least once per week)"
cap label var IREGX "Individuals not regularly using the Internet (less than once per week)"
cap label var OTHER "Other Inactive"
cap label var RETIR "Retired Individuals"
cap label var RETIR_OTHER "Individuals who are retired or not in the labour force (excluding students)"
cap label var RF_LE1 "Individuals with no risk factor or one risk factor"
cap label var RF_GE1 "Individuals with at least one of the 3 following characteristics: 55 to 74 years old; low education; unemployed or inactive or retired"
cap label var RF_GE2 "Individuals with at least two of the 3 following characteristics: 55 to 74 years old; low education; unemployed or inactive or retired"
cap label var SAL "Employees"
cap label var SAL_SELF_FAM "Employees, self-employed, family workers"
cap label var SAL_PERM "Employees with a permanent job"
cap label var SELF "Self-employed persons"
cap label var SELF_FAM "Self-employed, family workers"
cap label var EMP_FT "Employed persons working full-time"
cap label var EMP_JOB1 "Employed persons with one job only"
cap label var STUD "Students"
cap label var UNE "Unemployed"
cap label var IND_DISABL "Individuals who are unable to work due to long-standing health problems"
cap label var HLD_BLUE "EU Blue Cards holder"
cap label var HLDR "EU Blue Cards holder"
cap label var IND_DCH "Individuals living in a household with children"
cap label var IND_NO_DCH "Individuals living in a household without children"
cap label var MD "Mobile internet users"
cap label var MDX "Non-users of mobile internet"
cap label var Y16_29LO "Individuals aged 16-29 with low formal education"
cap label var Y16_29ME "Individuals aged 16-29 with medium formal education"
cap label var Y16_29HI "Individuals aged 16-29 with high formal education"
cap label var ARP "Individuals at risk of poverty"
cap label var NARP "Individuals not at risk of poverty"
cap label var IND_HH_NHH "Individuals living and not living in the household"
cap label var IND_HH "Individuals living in the household"
cap label var IND_NHH "Individuals not living in the household"
cap label var NONE "No individuals"
cap label var EMP_WKT_FT "Employees working full time"
cap label var EMP_WKT_PT "Employees working part time"
cap label var EMP_CON_PRM "Working with a permanent job or under contract of unlimited duration"
cap label var EMP_CON_TMP "Working with a temporary job or under contract of limited duration"
cap label var EMP_SECT_AFF "Working in agriculture, forestry or fishing"
cap label var EMP_SECT_MQM "Working in mining or quarrying, manufacturing or other industry"
cap label var EMP_SECT_CON "Working in construction"
cap label var EMP_SECT_TTAFS "Working in wholesale or retail trade, transport, accommodation or food service activities"
cap label var EMP_SECT_IC "Working in information or communication"
cap label var EMP_SECT_FIN "Working in financial or insurance activities"
cap label var EMP_SECT_RE "Working in real estate activities"
cap label var EMP_SECT_BS "Working in business services"
cap label var EMP_SECT_ADM "Working in public administration, defence, education, human health or social work activities"
cap label var EMP_SECT_OTH "Working in other service activities"
cap label var HI_Q5_1 "Individual living in a household with income in first quintile"
cap label var HI_Q5_2 "Individual living in a household with income in second quintile"
cap label var HI_Q5_3 "Individual living in a household with income in third quintile"
cap label var HI_Q5_4 "Individual living in a household with income in fourth quintile"
cap label var HI_Q5_5 "Individual living in a household with income in fifth quintile"
