cap label var NRG_SUP "Energy and supply"
cap label var NETC "Network costs"
cap label var NETC_TRANS "Network transmission costs"
cap label var NETC_DIST "Network distribution costs"
cap label var TAX_FEE_LEV_CHRG "Taxes, fees, levies and charges"
cap label var TAX_LEV "Taxes and levies"
cap label var TAX_LEV_X_VAT "Taxes and levies excluding VAT"
cap label var VAT "Value added tax (VAT)"
cap label var TAX_RNW "Renewable taxes"
cap label var TAX_CAP "Capacity taxes"
cap label var TAX_ENV "Environmental taxes"
cap label var TAX_NUC "Nuclear taxes"
cap label var I_TAX_LEV "All taxes and levies included"
cap label var X_TAX_LEV "Excluding taxes and levies"
cap label var X_VAT_TAX_LEV "Excluding VAT and other recoverable taxes and levies"
cap label var TAX_FEE_LEV_CHRG_ALLOW "Taxes, fees, levies and charges allowance"
cap label var TAX_RNW_ALLOW "Renewable taxes allowance"
cap label var TAX_CAP_ALLOW "Capacity taxes allowances"
cap label var TAX_ENV_ALLOW "Environmental taxes allowance"
cap label var TAX_NUC_ALLOW "Nuclear taxes allowance"
cap label var ALLOW_OTH "Other allowance"
cap label var OTH "Other"
