cap label var TOTAL "Total"
cap label var CHRG "Take charge request"
cap label var CHRG_FAM "Take charge request - family criteria (articles 8, 9, 10, 11)"
cap label var CHRG_FAM_8 "Take charge request - minors with a family member legally present (article 8)"
cap label var CHRG_FAM_9 "Take charge request - family members who are beneficiaries of international protection (article 9)"
cap label var CHRG_FAM_10 "Take charge request - family members who are applicants for international protection (article 10)"
cap label var CHRG_FAM_11 "Take charge request - family procedure (article 11)"
cap label var CHRG_DOC "Taking charge request - documentation and legal entry criteria (articles 12.1, 12.2, 12.3, 12.4, 14)"
cap label var CHRG_DOC_121 "Take charge request - valid residence document (article 12.1)"
cap label var CHRG_DOC_122 "Take charge request - valid visa (article 12.2)"
cap label var CHRG_DOC_123 "Take charge request - more than one valid residence document (article 12.3)"
cap label var CHRG_DOC_124 "Take charge request - residence document expired (article 12.4)"
cap label var CHRG_DOC_14 "Take charge request - visa waived entry (article 14)"
cap label var CHRG_131 "Take charge request - irregular entry (article 13.1)"
cap label var CHRG_132 "Take charge request - irregular stay (article 13.2)"
cap label var CHRG_15 "Take charge request - application in an international transit area of an airport (article 15)"
cap label var CHRG_16 "Take charge request- dependent persons (article 16)"
cap label var CHRG_172 "Take charge request - humanitarian criteria (article 17.2)"
cap label var CHRG_UNK "Take charge request - criteria unknown"
cap label var BACK "Take back request"
cap label var BACK_181B "Take back request – application under examination when new application lodged or present without a residence document in another Member State (article 18.1.b)"
cap label var BACK_181C "Take back request - withdrawal of application under examination and new application lodged or present without residence document in another Member State (article 18.1.c)"
cap label var BACK_181D "Take back request - rejection in another Member State and new application lodged or present without residence document (article 18.1.d)"
cap label var BACK_205 "Take back request - present without residence document or lodged new application in another Member State after withdrawing the first application made in a different Member State during the 'Dublin' procedure (article 20.5)"
cap label var BACK_UNK "Take back request - criteria unknown"
cap label var EDAC_CHRG "Take charge request - EURODAC (European Asylum Dactyloscopy Database)"
cap label var EDAC_BACK "Take back request - EURODAC (European Asylum Dactyloscopy Database)"
cap label var INFO "Request for information"
cap label var INFO_345 "Request for information - general criteria (article 34.5)"
cap label var INFO_65_86 "Request for information - family of unaccompanied minors (articles 6.5 and 8.6)"
cap label var INFO_164 "Request for information - family of dependent persons (article 16.4)"
cap label var RP_INFO "Response to request for information"
cap label var RP_INFO_345 "Response to request for information - general criteria (article 34.5)"
cap label var RP_INFO_65_86 "Response to request for information - family of unaccompanied minors (articles 6.5 and 8.6)"
cap label var RP_INFO_164 "Response to request for information - family of dependent persons (article 16.4)"
cap label var SOV_171 "Application of the sovereignty clause (article 17.1)"
cap label var RESPD "Member State to become responsible by default"
cap label var RESPD_32B_C "Member State to become responsible by default - transfer impossible due to flaws in reception conditions (article 3.2 second and third par.)"
cap label var RESPD_32A "Member State to become responsible by default - existing criteria not applicable (article 3.2 first par.)"
cap label var RESPD_292 "Member State to become responsible by default - transfer not carried out within time limits (article 29.2)"
cap label var UNK "Unknown"
cap label var CHARGE "Take charge request"
cap label var CHF "Take charge request - family criteria (articles 8, 9, 10, 11)"
cap label var CHF_8 "Take charge request - minors with a family member legally present (article 8)"
cap label var CHF_9 "Take charge request - family members who are beneficiaries of international protection (article 9)"
cap label var CHF_10 "Take charge request - family members who are applicants for international protection (article 10)"
cap label var CHF_11 "Take charge request - family procedure (article 11)"
cap label var CHD "Taking charge request - documentation and legal entry criteria (articles 12.1, 12.2, 12.3, 12.4, 14)"
cap label var CHD_121 "Take charge request - valid residence document (article 12.1)"
cap label var CHD_122 "Take charge request - valid visa (article 12.2)"
cap label var CHD_123 "Take charge request - more than one valid residence document (article 12.3)"
cap label var CHD_124 "Take charge request - residence document expired (article 12.4)"
cap label var CHD_14 "Take charge request - visa waived entry (article 14)"
cap label var CH_15 "Take charge request - application in an international transit area of an airport (article 15)"
cap label var CH_131 "Take charge request - irregular entry (article 13.1)"
cap label var CH_132 "Take charge request - irregular stay (article 13.2)"
cap label var CH_16 "Take charge request- dependent persons (article 16)"
cap label var CH_172 "Take charge request - humanitarian criteria (article 17.2)"
cap label var CH_UNK "Take charge request - criteria unknown"
cap label var BK_205 "Take back request - present without residence document or lodged new application in another Member State after withdrawing the first application made in a different Member State during the 'Dublin' procedure (article 20.5)"
cap label var BK_181B "Take back request - application under examination when new application lodged or present without a residence document in another Member State (article 18.1.b)"
cap label var BK_181C "Take back request - withdrawal of application under examination and new application lodged or present without residence document in another Member State (article 18.1.c)"
cap label var BK_181D "Take back request - rejection in another Member State and new application lodged or present without residence document (article 18.1.d)"
cap label var BK_UNK "Take back request - criteria unknown"
cap label var EDAC "Requests based on EURODAC (European Dactyloscopy)"
cap label var EDAC_CH "Take charge request - EURODAC (European Asylum Dactyloscopy Database)"
cap label var EDAC_BK "Take back request - EURODAC (European Asylum Dactyloscopy Database)"
cap label var INFO_GEN "Request for information - general criteria (article 34.5)"
cap label var INFO_UAM "Request for information - family of unaccompanied minors (articles 6.5 and 8.6)"
cap label var INFO_DEP "Request for information - family of dependent persons (article 16.4)"
cap label var RESP "Response to request for information"
cap label var RESP_GEN "Response to request for information - general criteria (article 34.5)"
cap label var RESP_UAM "Response to request for information - family of unaccompanied minors (articles 6.5 and 8.6)"
cap label var RESP_DEP "Response to request for information - family of dependent persons (article 16.4)"
