cap label var CP "Current price"
cap label var NP "Nominal price"
cap label var RP "Real price"
cap label var NV "Nominal value"
cap label var RV "Real value"
cap label var NI "Nominal index"
cap label var RI "Real index"
cap label var VOL "Volume"
cap label var CLV00 "Chain-linked volumes, reference year 2000 (at 2000 exchange rates)"
cap label var CLV05 "Chain-linked volumes, reference year 2005 (at 2005 exchange rates)"
cap label var VW "Value weight"
cap label var NAP "Not applicable"
