cap label var RCMPY_NEG95 "Companies representing at least 95% of the net electricity generation"
cap label var PCMPY_NEG5 "Companies producing at least 5% of the net electricity generation"
cap label var LCMPY_EG "Largest company - electricity generation"
cap label var CMPY_EG5 "Companies with at least 5% of the electricity generation"
cap label var LCMPY_IECAP "Largest company - installed electricity capacity"
cap label var CMPY_ECAP5 "Companies with at least 5% of the electricity capacity"
cap label var ECAP_CN "New electricity capacity connected"
cap label var ECAP_DC "Electricity capacity decommissioned"
cap label var ECAP_VAR "Electricity capacity variation"
cap label var ERTL "Electricity retailers"
cap label var ERTL_SELL_EC5 "Electricity retailers selling at least 5% of total electricity consumed"
cap label var ERTL_LG "Largest electricity retailer"
cap label var ERTL_EC5 "Electricity retailers with at least 5% of total electricity consumed"
cap label var CMPY_NG "Companies bringing natural gas"
cap label var CMPY_NG5 "Companies bringing at least 5% of the natural gas"
cap label var CMPY_LNG "Company bringing the largest amount of the natural gas"
cap label var GRTL "Gas retailers"
cap label var GRTL_SELL_NG5 "Gas retailers selling at least 5% of total natural gas consumed"
cap label var GRTL_LG "Largest gas retailer"
cap label var GRTL_NG5 "Gas retailers with at least 5% of total natural gas consumed"
