cap label var TY0001 "Current expenditure plus capital expenditure"
cap label var TY0002 "Investments"
cap label var TY0003 "End-of-pipe"
cap label var TY0004 "Integrated technologies"
cap label var TY0005 "Current expenditure"
cap label var TY0006 "Internal current expenditure"
cap label var TY0007 "Wages"
cap label var TY0008 "Other"
cap label var TY0009 "External current expenditure"
cap label var TY0010 "Fees and other payments to public bodies"
cap label var TY0011 "Payments to private enterprises"
cap label var TY0012 "Operational benefits from environmental protection activities"
cap label var TY0013 "Sales of related goods and services"
cap label var TY0014 "Saving/Costs offsets"
cap label var TY0015 "Labour inputs - number of persons"
cap label var TY0016 "Capital expenditure"
cap label var TOT_EGSS "Total environmental goods and services sector"
cap label var ANC "Ancillary activities"
cap label var MKT "Market activities"
cap label var ES_CS "Market activities: environmental specific and connected services"
cap label var GDC "Market activities: connected goods"
cap label var GDA "Market activities: adapted goods"
cap label var TCE "Market activities: end-of-pipe technologies"
cap label var TCI "Market activities: integrated technologies"
cap label var C_REP "Market activities: cleaner and resource efficient products"
cap label var NMKT "Non-market activities"
cap label var OWN_USE "Own final use activities"
