cap label var TOTAL "Total"
cap label var CORE "Core (production of goods and services for the market)"
cap label var SUPP "Support function"
cap label var PRD "Production of goods and materials"
cap label var DIST_LOG "Distribution and logistics"
cap label var MKTG_SLS "Marketing, sales, and after sales services"
cap label var ICT "Information and communication technology services"
cap label var ADM_MGMT "Administrative and management"
cap label var EGNG_TEC "Engineering and related technical services"
cap label var RND "Research and development"
cap label var RND_EGNG_TEC "Research, development, engineering and related technical services"
cap label var CORE_SUPP "Core and/or support function"
cap label var OTH "Other"
cap label var CORE_F "Core function (Production of goods and services for the market)"
cap label var SUP_F "Support function"
cap label var DIST_F "Distribution and logistics"
cap label var MK_F "Marketing, sales and after sales services"
cap label var ICT_F "ICT services"
cap label var ADM_F "Administrative and management"
cap label var ENG_F "Engineering and related technical services"
cap label var RD_F "Research and development"
cap label var RD_ENG_F "Research, development, engineering and related technical services"
cap label var OTHER "Other functions"
cap label var CO_SUP_F "Core and/or support function"
