cap label var VOL "Volume"
cap label var VOL_WW "Volume of wastewater"
cap label var BOD "Biochemical oxygen demand (BOD)"
cap label var COD "Chemical oxygen demand (COD)"
cap label var SS "Suspended solids"
cap label var N_T "Nitrogen (N-tot)"
cap label var P_T "Phosphor (P-tot)"
cap label var PE "Population equivalent (p.e.)"
cap label var CD "Cadmium (Cd)"
cap label var CR "Chromium (Cr)"
cap label var CU "Copper (Cu)"
cap label var NI "Nickel (Ni)"
cap label var PB "Lead (Pb)"
cap label var ZN "Zinc (Zn)"
cap label var AS "Arsenic (As)"
cap label var NO3_GW "Nitrate in groundwater"
cap label var PO4_RIV "Phosphate in rivers"
