cap label var TOTAL "Corresponding (total) number of students enrolled"
cap label var _0 "No languages"
cap label var _1 "1 language"
cap label var GE1 "1 language or more"
cap label var _2 "2 languages"
cap label var GE2 "2 languages or more"
cap label var _3 "3 languages"
cap label var GE3 "3 languages or more"
cap label var GE4 "4 languages or more"
