cap label var TOTAL "Total"
cap label var PC0 "Zero percent of a full-time"
cap label var PC1_24 "From 1 to 24 percent of a full-time"
cap label var PC25_49 "From 25 to 49 percent of a full-time"
cap label var PC50_74 "From 50 to 74 percent of a full-time"
cap label var PC75_99 "From 75 to 99 percent of a full-time"
cap label var PC100 "100 percent of a full-time"
cap label var H0 "Zero hours"
cap label var H1_9 "From 1 to 9 hours"
cap label var H1_19 "From 1 to 19 hours"
cap label var H10_19 "From 10 to 19 hours"
cap label var H20_29 "From 20 to 29 hours"
cap label var H20_31 "From 20 to 31 hours"
cap label var H30_39 "From 30 to 39 hours"
cap label var H_GE32 "32 hours or over"
cap label var H40_49 "From 40 to 49 hours"
cap label var H_GE50 "50 hours or over"
cap label var PT "Part-time"
cap label var FT "Full-time"
cap label var TEMP "Temporary contracts"
cap label var TOT_FTE "Total in full-time equivalents"
cap label var AVG_FTE "Yearly average in full-time equivalents"
cap label var PT_FTE "Part-time in full-time equivalents"
cap label var NORM "Normal working time"
cap label var ATYP "Atypical working time"
cap label var INCR "Increase working hours"
cap label var DECR "Decrease working hours"
cap label var NCHG "No changes to working hours"
cap label var NAP "Not applicable"
cap label var NRP "No response"
cap label var UNK "Unknown"
