cap label var RW "Roundwood (wood in the rough)"
cap label var RW_C "Industrial roundwood, fuel wood - coniferous"
cap label var RW_NC "Industrial roundwood, fuel wood - non-coniferous"
cap label var RW_FW "Fuelwood (including wood for charcoal)"
cap label var RW_FW_C "Fuel wood - coniferous"
cap label var RW_FW_NC "Fuel wood - non-coniferous"
cap label var RW_IN "Industrial roundwood"
cap label var RW_IN_C "Industrial roundwood - coniferous"
cap label var RW_IN_NC "Industrial roundwood - non-coniferous"
cap label var RW_IN_TNC "Industrial roundwood - tropical, non-coniferous"
cap label var RW_IN_LG "Sawlogs and veneer logs"
cap label var RW_IN_LG_C "Sawlogs and veneer logs - coniferous"
cap label var RW_IN_LG_NC "Sawlogs and veneer logs - non-coniferous"
cap label var RW_IN_PW_O "Pulpwood, round and split and other industrial roundwood"
cap label var RW_IN_PW "Pulpwood, round and split"
cap label var RW_IN_PW_C "Pulpwood, round and split - coniferous"
cap label var RW_IN_PW_NC "Pulpwood, round and split - non-coniferous"
cap label var RW_IN_O "Other industrial roundwood"
cap label var RW_IN_O_C "Other industrial roundwood - coniferous"
cap label var RW_IN_O_NC "Other industrial roundwood - non-coniferous"
cap label var CHA "Wood charcoal"
cap label var CHP_RES "Wood chips, particles and residues"
cap label var CHP "Wood chips and particles"
cap label var RES "Wood residues (including wood for agglomerates)"
cap label var RCW "Recovered wood"
cap label var PEL_AGG "Wood pellets and other agglomerates"
cap label var PEL "Wood pellets"
cap label var AGG "Other agglomerates"
cap label var SN "Sawnwood (including sleepers)"
cap label var SN_C "Sawnwood (including sleepers) - coniferous"
cap label var SN_NC "Sawnwood (including sleepers) - non-coniferous"
cap label var SN_TNC "Sawnwood (including sleepers) - tropical, non-coniferous"
cap label var PN "Wood-based panels"
cap label var PN_VN "Veneer sheets"
cap label var PN_VN_C "Veneer sheets - coniferous"
cap label var PN_VN_NC "Veneer sheets - non-coniferous"
cap label var PN_VN_TNC "Veneer sheets - tropical, non-coniferous"
cap label var PN_PY "Plywood"
cap label var PN_PY_C "Plywood - coniferous"
cap label var PN_PY_NC "Plywood - non-coniferous"
cap label var PN_PY_TNC "Plywood - tropical, non-coniferous"
cap label var PN_PB "Particle board, oriented strandboard (OSB) and similar board"
cap label var PN_PB_OSB "Oriented strandboard (OSB)"
cap label var PN_FB "Fibreboard"
cap label var PN_FB_HB "Hardboard"
cap label var PN_FB_MDF "Medium/high density fibreboard (MDF/HDF)"
cap label var PN_FB_O "Other fibreboard"
cap label var GLT "Glue-laminated timber"
cap label var CLT "Cross-laminated timber"
cap label var PL "Wood pulp"
cap label var PL_MC_SCH "Mechanical and semi-chemical wood pulp"
cap label var PL_MC_SCH_NW "Mechanical, semi-chemical wood pulp and pulp from fibres other than wood"
cap label var PL_MC "Mechanical wood pulp"
cap label var PL_SCH "Semi-chemical wood pulp"
cap label var PL_CH_DS "Chemical and dissolving grades wood pulp"
cap label var PL_CH "Chemical wood pulp"
cap label var PL_CH_SA "Sulphate wood pulp"
cap label var PL_CH_SANB "Sulphate unbleached wood pulp"
cap label var PL_CH_SAB "Sulphate bleached wood pulp"
cap label var PL_CH_SI "Sulphite wood pulp"
cap label var PL_CH_SINB "Sulphite unbleached wood pulp"
cap label var PL_CH_SIB "Sulphite bleached wood pulp"
cap label var PL_DS "Dissolving grades wood pulp"
cap label var PLO "Other pulp"
cap label var PLO_NW "Pulp from fibres other than wood"
cap label var PLO_RC "Recovered fibre pulp"
cap label var RCP "Recovered paper"
cap label var PP "Paper and paperboard"
cap label var PP_GR "Graphic papers"
cap label var PP_GR_NP "Newsprint"
cap label var PP_GR_CO_NCO "Graphic papers, printing and writing"
cap label var PP_GR_MC "Uncoated mechanical papers"
cap label var PP_GR_NW "Uncoated woodfree papers"
cap label var PP_GR_CO "Coated papers"
cap label var PP_HS "Household and sanitary papers"
cap label var PP_PK "Packaging materials"
cap label var PP_PK_CS "Case materials"
cap label var PP_PK_CB "Cartonboard"
cap label var PP_PK_WR "Wrapping papers"
cap label var PP_PK_O "Other papers mainly for packaging"
cap label var PP_O "Other paper and paperboard n.e.s."
cap label var SW "Secondary wood products"
cap label var SW_SN "Further processed sawnwood"
cap label var SW_SN_C "Further processed sawnwood - coniferous"
cap label var SW_SN_NC "Further processed sawnwood - non-coniferous"
cap label var SW_SN_TNC "Further processed sawnwood - tropical, non-coniferous"
cap label var SW_WR "Wooden wrapping and packaging material"
cap label var SW_DM "Wood products for domestic/decorative use"
cap label var SW_O "Other manufactured wood products"
cap label var SW_JN "Builder's joinery and carpentry of wood"
cap label var SW_FU "Wooden furniture"
cap label var SW_BL "Prefabricated buildings"
cap label var SW_BL_W "Prefabricated buildings of wood"
cap label var SP "Secondary paper products"
cap label var SP_CM "Composite paper and paperboard"
cap label var SP_SCO "Special coated paper and pulp products"
cap label var SP_CC "Carbon paper and copying paper, ready for use"
cap label var SP_HS "Household and sanitary paper, ready for use"
cap label var SP_PK "Packaging cartons, boxes, etc."
cap label var SP_O "Other articles of paper and paperboard, ready for use"
cap label var SP_O_PR "Printing and writing paper, ready for use"
cap label var SP_O_AR "Articles moulded or pressed from pulp"
cap label var SP_O_FL "Filter paper and paperboard, ready for use"
cap label var SP_PR "Printed paper"
cap label var NAP "Not applicable"
