cap label var TOTAL "All sectors"
cap label var BES "Business enterprise sector"
cap label var REG "Regional/sector funds"
cap label var NAT "National funds"
cap label var SPE "Specific national measure"
cap label var EUS "EU sources"
cap label var GOV "Government sector"
cap label var GOV_REB "Government rebates on expenditure"
cap label var GOV_GUF "Government - general university funds"
cap label var GOV_DIR "Government - direct government"
cap label var HES "Higher education sector"
cap label var PNP "Private non-profit sector"
cap label var HES_AND_PNP "Higher education and private-non-profit sector"
cap label var TAX "Tax concessions on expenditure"
cap label var EXT "External financial assistance from non-government sources"
cap label var PAYTR "Royalty payments from external bodies/persons for the use of training resources"
cap label var PAYC "Payments from external bodies/persons for the use of training resources"
cap label var ROW "Rest of the world"
cap label var ROW_BES "Rest of the world - business enterprise sector"
cap label var ROW_BES_IN "Rest of the world - business enterprises within the enterprise group"
cap label var ROW_BES_OTH "Rest of the world - other business enterprise companies"
cap label var ROW_EC "Rest of the world - European Commission"
cap label var ROW_IORG "Rest of the world - international organisations"
cap label var ROW_OTH "Rest of the world - other"
cap label var ABR "Abroad"
cap label var ABR_PRIVATE "Abroad - Private sector"
cap label var ABR_BES "Abroad - Business enterprise sector"
cap label var ABR_PNP "Abroad - Private non-profit sector"
cap label var ABR_PUBLIC "Abroad - Public sector"
cap label var ABR_GOV "Abroad - Government sector"
cap label var ABR_HES "Abroad - Higher education sector"
cap label var ABR_EC "Abroad - European Commission"
cap label var ABR_INT "Abroad - International Organisations"
cap label var ABR_OTHER "Abroad - other"
cap label var ABR_BES_GROUP "Abroad - enterprises within the same group"
cap label var ABR_BES_OTH "Abroad - other business enterprise companies"
