cap label var D "Total labour costs (total)"
cap label var D01 "Total labour costs (excluding apprentices)"
cap label var D02 "Total labour costs for apprentices"
cap label var D1_D4_MD5 "Labour cost for LCI (compensation of employees plus taxes minus subsidies)"
cap label var D1_D4_MD5_XB "Labour cost for LCI excluding bonuses"
cap label var D1 "Compensation of employees (total)"
cap label var D11 "Wages and salaries (total)"
cap label var D111 "Wages and salaries (excluding apprentices)"
cap label var D1111 "Direct remuneration, bonuses and allowances"
cap label var D11111 "Direct remuneration, bonuses and allowances paid in each pay period"
cap label var D11112 "Direct remuneration, bonuses and allowances not paid in each pay period"
cap label var D1111A "Direct remuneration (LCS 2000)"
cap label var D1111B "Bonuses (LCS 2000)"
cap label var D111121 "Bonuses paid at fixed period"
cap label var D1112 "Payments to employees savings schemes"
cap label var D1113 "Payments for days not worked"
cap label var D1114 "Wages and salaries in kind"
cap label var D11141 "Company products"
cap label var D11142 "Staff housing"
cap label var D11143 "Company cars"
cap label var D11144 "Stock options and share purchase schemes"
cap label var D11144A "Other remuneration in kind (LCS 2000)"
cap label var D11145 "Other"
cap label var D112 "Wages and salaries of apprentices"
cap label var D12 "Employers' social contributions (total)"
cap label var D121 "Employers' actual social contributions"
cap label var D1211 "Statutory social security contributions"
cap label var D1212 "Collectively agreed, contractual and voluntary social security contributions"
cap label var D122 "Employers' imputed social contributions"
cap label var D1221 "Guaranteed remuneration in the event of sickness"
cap label var D1222 "Employers' imputed social contributions for pensions and health"
cap label var D1222A "Guaranteed remuneration in event of short-time working (LCS 2000)"
cap label var D1222_00 "Guaranteed remuneration in event of short-time working"
cap label var D1223 "Payments to employees leaving the enterprise"
cap label var D1224 "Other employers' imputed social benefits"
cap label var D1224A "Employers' imputed social benefits (LCS 2000)"
cap label var D1224_00 "Employers' imputed social benefits"
cap label var D123 "Employers' social contributions for apprentices"
cap label var D2_D4_MD5 "Labour costs other than compensation of employees"
cap label var D12__D4_MD5 "Employers' social contributions and other labour costs paid by employer"
cap label var D12_D4_MD5 "Labour costs other than wages and salaries"
cap label var D2 "Vocational training costs"
cap label var D3 "Other expenditure"
cap label var D4 "Taxes"
cap label var D5 "Subsidies"
cap label var NREM "Net remuneration in nominal terms / real terms"
cap label var GREM "Gross remuneration in nominal terms / real terms"
cap label var TWAGSAL "Total wages and salaries"
cap label var DIREB "Direct remuneration and bonuses"
cap label var SS "Social security paid by employer"
cap label var OTHLC "Other labour costs"
cap label var SS_OTHLC "Social security and other labour costs paid by employer"
cap label var D2_D4_MD5_RAT "Share of non-wage costs (%)"
