cap label var TOTAL "Total"
cap label var SAL "Employees"
cap label var SELF "Self-employed persons"
cap label var NCHG "No change"
cap label var NAP "Not applicable"
cap label var NRP "No response"
