cap label var TOTAL "Total"
cap label var MOD "Moderate"
cap label var SOME "Some"
cap label var LTD "Limited"
cap label var SEV "Severe"
cap label var SM_SEV "Some or severe"
cap label var NONE "None"
