cap label var TOTAL "Total"
cap label var INJ010 "Wounds and superficial injuries"
cap label var INJ011 "Superficial injuries"
cap label var INJ012 "Open wounds"
cap label var INJ019 "Other types of wounds and superficial injuries"
cap label var CONT_BRU "Contusions, bruisings"
cap label var CUT_LACE "Cuts, lacerations, severed nerves or tendons"
cap label var INJ020 "Bone fractures"
cap label var INJ021 "Closed fractures"
cap label var INJ022 "Open fractures"
cap label var INJ029 "Other types of bone fractures"
cap label var INJ030 "Dislocations, sprains and strains"
cap label var INJ031 "Dislocations and subluxations"
cap label var INJ032 "Sprains and strains"
cap label var INJ039 "Other types of dislocations, sprains and strains"
cap label var INJ040 "Traumatic amputations (Loss of body parts)"
cap label var INJ050 "Concussions and internal injuries"
cap label var INJ051 "Concussions"
cap label var INJ052 "Internal injuries"
cap label var INJ059 "Other types of concussions and internal injuries"
cap label var INJ060 "Burns, scalds and frostbites"
cap label var INJ061 "Burns and scalds (thermal)"
cap label var INJ062 "Chemical burns (corrosions)"
cap label var INJ063 "Frostbites"
cap label var INJ069 "Other types of burns, scalds and frostbites"
cap label var INJ070 "Poisonings and infections"
cap label var INJ071 "Acute poisonings"
cap label var INJ072 "Acute infections"
cap label var POIS_ASP "Poisonings, gassings and asphyxiations"
cap label var INJ079 "Other types of poisonings and infections"
cap label var INJ080 "Drownings and asphyxiations"
cap label var INJ081 "Asphyxiations"
cap label var INJ082 "Drownings and non-fatal submersions"
cap label var INJ089 "Other types of drownings and asphyxiations"
cap label var INJ090 "Effects of sound, vibration and pressure"
cap label var INJ091 "Acute hearing losses"
cap label var INJ092 "Effects of pressure (barotrauma)"
cap label var INJ099 "Other effects of sound, vibration and pressure"
cap label var INJ100 "Effects of temperature extremes, light and radiation"
cap label var INJ101 "Heats and sunstrokes"
cap label var INJ102 "Effects of radiation (non-thermal)"
cap label var INJ103 "Effects of reduced temperature"
cap label var INJ109 "Other effects of temperature extremes, light and radiation"
cap label var INJ110 "Shocks"
cap label var INJ111 "Shocks after aggression and threats"
cap label var INJ112 "Traumatic shocks"
cap label var INJ119 "Other types of shocks"
cap label var INJ120 "Multiple injuries"
cap label var OTH "Other not elsewhere mentioned"
cap label var UNK "Unspecified"
