cap label var NEI_EXT "Extraction of natural energy inputs"
cap label var EPRD_DOM "Domestic production of energy products"
cap label var EPRD_ICNS "Intermediate consumption of energy products"
cap label var EPRD_HHCNS "Household consumption of energy products"
cap label var WST_USE "Use of waste for energetic purposes"
cap label var WST_USE_EP "Use of waste for energy purposes"
cap label var NETDOM_EUSE "Net domestic energy use"
cap label var NETDOM_EUSE_EP "Net domestic energy use for energy purposes"
cap label var NETDOM_EUSE_NEP "Net domestic energy use for non-energy purposes"
cap label var NRG_INP_OUT "Energy input and output"
cap label var ER_EUSE "Emission-relevant use of energy"
cap label var EUSE_RES "Energy use by resident units"
cap label var EUSE_RES_ABR "Energy use by resident units, fuel purchased abroad - total"
cap label var EUSE_RES_ABR_FWTR "Energy use by resident units, fuel purchased abroad - fishing vessels"
cap label var EUSE_RES_ABR_LTR "Energy use by resident units, fuel purchased abroad - land transport"
cap label var EUSE_RES_ABR_WTR "Energy use by resident units, fuel purchased abroad - water transport"
cap label var EUSE_RES_ABR_ATR "Energy use by resident units, fuel purchased abroad - air transport"
cap label var EUSE_TER_NRES "Energy use by non-resident units (only if included in gross inland energy consumption), fuel purchased on the territory - total"
cap label var EUSE_TER_NRES_LTR "Energy use by non-resident units (only if included in gross inland energy consumption), fuel purchased on the territory - land transport"
cap label var EUSE_TER_NRES_WTR "Energy use by non-resident units (only if included in gross inland energy consumption), fuel purchased on the territory - water transport"
cap label var EUSE_TER_NRES_ATR "Energy use by non-resident units (only if included in gross inland energy consumption), fuel purchased on the territory - air transport"
cap label var ADJ_SD "Other adjustments and statistical differences"
cap label var ADJ_SD_DUXGIC "Other adjustments and statistical differences - energy flows included in energy use by resident units (net domestic energy use) while excluded in gross inland energy consumption"
cap label var EUSE_TER "Gross inland energy consumption (territory principle)"
cap label var DEI "Direct energy input"
cap label var DEO "Direct energy output"
cap label var NAS_CAL "Net additions to stock (calculated)"
cap label var NAS_REP "Net additions to stock (reported)"
cap label var DEC "Domestic energy consumption"
cap label var EPRD_ERES_IMP "Imports of energy products and energy residuals (waste for energetic use)"
cap label var EPRD_IMP "Imports of energy products"
cap label var ERES_IMP "Imports of energy residuals (waste for energetic use)"
cap label var DPO "Domestic processed output"
cap label var EPRD_ERES_EXP "Exports of energy products and residuals"
cap label var EPRD_ERES_NETCHG "Net changes (use minus supply) of energy products and residuals in inventories and produced assets"
cap label var ERES_SUP "Supply of energy residuals from stock"
cap label var EPRD_ERES_AS "Additions (use) of energy products and residuals to stocks"
cap label var EPRD_ERES_DSP "Statistical discrepancy between supply and use of energy products and residuals"
