cap label var EU27_2020 "European Union - 27 countries (from 2020)"
cap label var EU28 "European Union - 28 countries (2013-2020)"
cap label var EU27_2007 "European Union - 27 countries (2007-2013)"
cap label var EU25 "European Union - 25 countries (2004-2006)"
cap label var EU15 "European Union - 15 countries (1995-2004)"
cap label var BE "Belgium"
cap label var BG "Bulgaria"
cap label var DK "Denmark"
cap label var DE "Germany"
cap label var EE "Estonia"
cap label var IE "Ireland"
cap label var EL "Greece"
cap label var ES "Spain"
cap label var FR "France"
cap label var HR "Croatia"
cap label var IT "Italy"
cap label var CY "Cyprus"
cap label var LV "Latvia"
cap label var LT "Lithuania"
cap label var MT "Malta"
cap label var NL "Netherlands"
cap label var PL "Poland"
cap label var PT "Portugal"
cap label var RO "Romania"
cap label var SI "Slovenia"
cap label var FI "Finland"
cap label var SE "Sweden"
cap label var EEA30_2020 "European Economic Area (EU27 from 2020 and IS, LI, NO)"
cap label var EEA31 "European Economic Area (EU28 plus IS, LI, NO)"
cap label var IS "Iceland"
cap label var NO "Norway"
cap label var UK "United Kingdom"
cap label var ME "Montenegro"
cap label var TR "Turkey"
cap label var DE_1 "Germany: North Sea"
cap label var DE_2 "Germany: Baltic Sea"
cap label var DE_3 "Germany: Inland"
cap label var DE_9 "Germany: unspecified maritime coastal area"
cap label var ES_1 "Spain: North Atlantic"
cap label var ES_2 "Spain: Mediterranean and South Atlantic"
cap label var ES_3 "Spain: Ceuta"
cap label var ES_4 "Spain: Melilla"
cap label var ES_9 "Spain: unspecified maritime coastal area"
cap label var FR_1 "France: Atlantic / North Sea"
cap label var FR_2 "France: Mediterranean"
cap label var FR_3 "France: Guyane"
cap label var FR_4 "France: Guadeloupe and Martinique"
cap label var FR_5 "France: Réunion"
cap label var FR_9 "France: unspecified maritime coastal area"
cap label var SE_1 "Sweden: Baltic Sea"
cap label var SE_2 "Sweden: North Sea"
cap label var SE_9 "Sweden: unspecified maritime coastal area"
cap label var UK_1 "United Kingdom: Great Britain and Northern Ireland"
cap label var UK_2 "United Kingdom: Isle of Man"
cap label var UK_3 "United Kingdom: Guernsey and Jersey (Channel Islands)"
cap label var UK_9 "United Kingdom: unspecified maritime coastal area"
cap label var TR_1 "Turkey: Black Sea"
cap label var TR_2 "Turkey: Mediterranean"
cap label var TR_9 "Turkey: unspecified maritime coastal area"
cap label var BE_0BEANR "Antwerpen"
cap label var BE_0BEBRU "Bruxelles (Brussel)"
cap label var BE_0BEGNE "Gent (Ghent)"
cap label var BE_0BELGG "Liège"
cap label var BE_0BENIE "Nieuwpoort"
cap label var BE_0BEOST "Oostende (Ostend)"
cap label var BE_0BEZEE "Zeebrugge"
cap label var BE_0BE001 "Zeekanaal Brussel-Schelde - ports"
cap label var BE_0BE002 "Belgium - other inland ports (other than Zeekanaal Brussel-Schelde ports)"
cap label var BE_0BE003 "Antwerp-Bruges"
cap label var BE_0BE888 "Belgium - other ports"
cap label var BG_0BGBOJ "Burgas"
cap label var BG_0BGVAR "Varna"
cap label var BG_0BG888 "Bulgaria - other ports"
cap label var DK_0DKAAB "Aabenraa"
cap label var DK_0DKAAL "Aalborg"
cap label var DK_0DKROR "Aalborg Portland (Cementfabrikken Rordal)"
cap label var DK_0DKARK "Ærøskøbing"
cap label var DK_0DKAGO "Agersø"
cap label var DK_0DKAGH "Agger Havn"
cap label var DK_0DKASH "Aggersund Havn"
cap label var DK_0DKANH "Anholt"
cap label var DK_0DKAAR "Århus"
cap label var DK_0DKARO "Årø"
cap label var DK_0DKARD "Årøsund"
cap label var DK_0DKASK "Askø"
cap label var DK_0DKAIT "Asnæs Inter Terminal"
cap label var DK_0DKASV "Asnæsværkets Havn"
cap label var DK_0DKASN "Assens"
cap label var DK_0DKAUB "Augustenborg"
cap label var DK_0DKAVE "Avedøreværkets Havn"
cap label var DK_0DKAVK "Avernakø/Lyø"
cap label var DK_0DKBAG "Bagenkop"
cap label var DK_0DKBGO "Bågø"
cap label var DK_0DKBLB "Ballebro"
cap label var DK_0DKBDX "Bandholm (Maribo)"
cap label var DK_0DKBAR "Barso"
cap label var DK_0DKBSL "Barso Landing"
cap label var DK_0DKBOG "Bogø"
cap label var DK_0DKBOS "Bøjden"
cap label var DK_0DKBRH "Branden Havn"
cap label var DK_0DKDAN "Cementfabrikken Danias Havn"
cap label var DK_0DKKON "Cementfabrikken Kongsdal Havn"
cap label var DK_0DKCSO "Christiansø Havn"
cap label var DK_0DKDAS "Dansk Salts Havn"
cap label var DK_0DKDRA "Dragør"
cap label var DK_0DKEBT "Ebeltoft"
cap label var DK_0DKEGN "Egense"
cap label var DK_0DKEDL "Endelave"
cap label var DK_0DKEIT "Ensted Inter Terminal"
cap label var DK_0DKENS "Enstedværkets Havn"
cap label var DK_0DKEBJ "Esbjerg"
cap label var DK_0DKFAA "Fåborg Havn"
cap label var DK_0DKFAK "Fakse Ladeplads Havn"
cap label var DK_0DKFGS "Feggesund"
cap label var DK_0DKFEJ "Fejø"
cap label var DK_0DKFMO "Femø"
cap label var DK_0DKFRC "Fredericia (Og Shell-Havnen)"
cap label var DK_0DKFDH "Frederikshavn"
cap label var DK_0DKFDS "Frederikssund Havn"
cap label var DK_0DKSVV "Frederiskværk Havn (Frederiksværk Stålvalseværk)"
cap label var DK_0DKFUH "Fur"
cap label var DK_0DKFYH "Fynshav"
cap label var DK_0DKGED "Gedser"
cap label var DK_0DKGTS "Glatved Strand"
cap label var DK_0DKGRA "Gråsten"
cap label var DK_0DKGRE "Grenå"
cap label var DK_0DKGDM "Gudhjem"
cap label var DK_0DKGFH "Gulfhavnen"
cap label var DK_0DKHAD "Haderslev"
cap label var DK_0DKHSU "Hadsund"
cap label var DK_0DKHAS "Hals"
cap label var DK_0DKHAN "Hanstholm"
cap label var DK_0DKHDH "Hardeshøj"
cap label var DK_0DKHSL "Hasle"
cap label var DK_0DKHNB "Havneby"
cap label var DK_0DKHVN "Havnsø"
cap label var DK_0DKHLS "Helsingør (Elsinore)"
cap label var DK_0DKHIR "Hirtshals"
cap label var DK_0DKHBO "Hobro"
cap label var DK_0DKHBK "Holbæk"
cap label var DK_0DKHOR "Horsens"
cap label var DK_0DKHOH "Hou Havn"
cap label var DK_0DKHUN "Hundested"
cap label var DK_0DKHVA "Hvalpsund"
cap label var DK_0DKHVS "Hvide Sande"
cap label var DK_0DKJUE "Juelsminde Havn"
cap label var DK_0DKKAL "Kalundborg"
cap label var DK_0DKKTP "Kastrup"
cap label var DK_0DKKTD "Kerteminde"
cap label var DK_0DKKLP "Kleppen"
cap label var DK_0DKCPH "Københavns Havn"
cap label var DK_0DKKOG "Køge"
cap label var DK_0DKKOK "Kolby Kås Havn"
cap label var DK_0DKKOL "Kolding"
cap label var DK_0DKKRR "Korsør"
cap label var DK_0DKKRA "Kragenæs"
cap label var DK_0DKKBY "Kyndbyværkets Havn"
cap label var DK_0DKLVG "Lemvig"
cap label var DK_0DKLGR "Løgstør"
cap label var DK_0DKLOH "Lohals"
cap label var DK_0DKLYO "Lyngs Odde Havn"
cap label var DK_0DKMRB "Marbæk Havn"
cap label var DK_0DKMRS "Marstal"
cap label var DK_0DKUNX "Masnedø Godningshavn (Uno-X Havn)"
cap label var DK_0DKMAS "Masnedøværkets Havn"
cap label var DK_0DKMNS "Masnedsund"
cap label var DK_0DKMID "Middelfart"
cap label var DK_0DKMOM "Mommark"
cap label var DK_0DKNUD "Næssund"
cap label var DK_0DKNVD "Næstved"
cap label var DK_0DKNAK "Nakskov"
cap label var DK_0DKNEX "Neksø"
cap label var DK_0DKNDB "Nordby Havn, Fanø"
cap label var DK_0DKVSV "Nordjyllandsværkets Havn"
cap label var DK_0DKNRS "Nørresundby"
cap label var DK_0DKNBG "Nyborg"
cap label var DK_0DKNYF "Nykøbing Falster"
cap label var DK_0DKNYM "Nykøbing Mors"
cap label var DK_0DKODE "Odense"
cap label var DK_0DKOMO "Omø"
cap label var DK_0DKORE "Orehoved, Falster"
cap label var DK_0DKORO "Orø"
cap label var DK_0DKRAN "Randers"
cap label var DK_0DKROD "Rødby"
cap label var DK_0DKROF "Rødby (Færgehavn)"
cap label var DK_0DKRNN "Rønne"
cap label var DK_0DKRRV "Rørvig"
cap label var DK_0DKRKB "Rudkøbing"
cap label var DK_0DKSLV "Sælvig Havn"
cap label var DK_0DKSAX "Sakskøbing"
cap label var DK_0DKSEO "Sejerø"
cap label var DK_0DKSJO "Sjællands Odde"
cap label var DK_0DKSSK "Skælskør"
cap label var DK_0DKSKB "Skærbækværkets Havn"
cap label var DK_0DKSKA "Skagen"
cap label var DK_0DKSDO "Skarø/Drejø"
cap label var DK_0DKSKV "Skive"
cap label var DK_0DKSOB "Søby Havn"
cap label var DK_0DKSGD "Sønderborg"
cap label var DK_0DKSPB "Spodsbjerg Havn"
cap label var DK_0DKSTT "Statoil-Havnen"
cap label var DK_0DKSTP "Stevns Pier"
cap label var DK_0DKSTN "Stigsnæs"
cap label var DK_0DKSIT "Stigsnaes Inter Terminal"
cap label var DK_0DKSTG "Stigsnæsværkets Havn"
cap label var DK_0DKSTR "Struer Havn"
cap label var DK_0DKSNO "Strynø"
cap label var DK_0DKSBK "Stubbekøbing Havn"
cap label var DK_0DKSSV "Studstrupværkets Havn"
cap label var DK_0DKSUE "Sundsøre"
cap label var DK_0DKSVE "Svendborg"
cap label var DK_0DKTRS "Tårs"
cap label var DK_0DKTED "Thisted"
cap label var DK_0DKTYB "Thyborøn"
cap label var DK_0DKTNO "Tunø"
cap label var DK_0DKUDN "Udbyhoj Nord"
cap label var DK_0DKUDS "Udbyhoj Syd"
cap label var DK_0DKVNG "Vang Havn"
cap label var DK_0DKVEJ "Vejle"
cap label var DK_0DKVEN "Venø Havn"
cap label var DK_0DKVES "Vesterø Havn, Læsø"
cap label var DK_0DKVOR "Vordingborg Havn"
cap label var DK_0DK888 "Denmark - other ports"
cap label var DE_1DEIAM "Amrum"
cap label var DE_3DEAND "Andernach"
cap label var DE_2DEANK "Anklam"
cap label var DE_1DEBMR "Baltrum"
cap label var DE_1DEBEI "Beidenfleth"
cap label var DE_3DEBDF "Bendorf/Rhein"
cap label var DE_1DEBEN "Bensersiel"
cap label var DE_3DEBER "Berlin"
cap label var DE_2DEBOF "Berndshof"
cap label var DE_3DEIEN "Biene"
cap label var DE_1DEBMK "Borkum"
cap label var DE_3DEBOT "Bottrop"
cap label var DE_1DEBKE "Brake"
cap label var DE_3DEBWE "Braunschweig"
cap label var DE_1DEBRE "Bremen"
cap label var DE_1DEBRV "Bremerhaven"
cap label var DE_1DEBRB "Brunsbüttel"
cap label var DE_3DEBYN "Bülstringen"
cap label var DE_2DEBSK "Burgstaaken/Fehmarn"
cap label var DE_1DEBUM "Büsum"
cap label var DE_1DEBUZ "Bützfleth"
cap label var DE_1DECAR "Carolinensiel"
cap label var DE_3DECRL "Castrop-Rauxel"
cap label var DE_1DECUX "Cuxhaven"
cap label var DE_1DEDAG "Dagebüll"
cap label var DE_2DEDMN "Demmin"
cap label var DE_3DEDON "Dorsten"
cap label var DE_3DEDTM "Dortmund"
cap label var DE_3DEDUI "Duisburg"
cap label var DE_3DEDUS "Düsseldorf"
cap label var DE_2DEECK "Eckernförde"
cap label var DE_1DEEME "Emden"
cap label var DE_3DEESU "Emmelsum"
cap label var DE_3DEEMM "Emmerich"
cap label var DE_1DE76Y "Esens"
cap label var DE_2DEFLF "Flensburg"
cap label var DE_2DE117 "Flensburger Förde - other ports"
cap label var DE_1DE017 "Föhr"
cap label var DE_3DEFRA "Frankfurt am Main"
cap label var DE_1DEFRI "Friedrichstadt"
cap label var DE_3DEGEK "Gelsenkirchen"
cap label var DE_1DE118 "Gieselaukanal and Eider - other ports"
cap label var DE_1DEGLU "Glückstadt"
cap label var DE_3DEGDO "Godorf"
cap label var DE_2DEGRD "Greifswald"
cap label var DE_1DEGXR "Gröde"
cap label var DE_1DEHAM "Hamburg"
cap label var DE_3DEHAU "Hanau"
cap label var DE_1DEHRN "Haren/Ems"
cap label var DE_2DEHHF "Heiligenhafen"
cap label var DE_1DEHGL "Helgoland"
cap label var DE_3DEHNF "Hennigsdorf"
cap label var DE_3DEHIL "Hildesheim"
cap label var DE_1DEHOD "Hochdonn"
cap label var DE_1DEHHS "Hohenhörn"
cap label var DE_1DEHOO "Hooksiel"
cap label var DE_1DEHRM "Hörnum/Sylt"
cap label var DE_1DEHUS "Husum"
cap label var DE_3DEIBB "Ibbenbüren"
cap label var DE_1DEITZ "Itzehoe"
cap label var DE_1DEJUI "Juist"
cap label var DE_2DEKAP "Kappeln"
cap label var DE_3DEKEH "Kehl"
cap label var DE_1DEKEI "Keitum"
cap label var DE_2DEKEL "Kiel"
cap label var DE_3DECGN "Köln"
cap label var DE_3DEKRE "Krefeld"
cap label var DE_2DELAB "Laboe"
cap label var DE_1DELGO "Langeoog"
cap label var DE_2DELAU "Lauterbach"
cap label var DE_1DELEE "Leer"
cap label var DE_3DELEV "Leverkusen"
cap label var DE_3DELIG "Lingen"
cap label var DE_1DELIS "List/Sylt"
cap label var DE_1DELOH "Lohesch"
cap label var DE_3DELBM "Lubmin"
cap label var DE_3DELUH "Ludwigshafen"
cap label var DE_3DELBE "Lübbecke"
cap label var DE_2DELBC "Lübeck"
cap label var DE_3DELLS "Lülsdorf"
cap label var DE_3DELUE "Lünen"
cap label var DE_3DEMAG "Magdeburg"
cap label var DE_3DEMEP "Meppen"
cap label var DE_3DEMID "Minden"
cap label var DE_3DEMUH "Mülheim an der Ruhr"
cap label var DE_1DENES "Nessmersiel"
cap label var DE_1DENHS "Neuharlingersiel"
cap label var DE_3DENSS "Neuss"
cap label var DE_2DENHO "Neustadt/Holstein"
cap label var DE_1DENOE "Norddeich"
cap label var DE_1DENHA "Nordenham"
cap label var DE_1DENRD "Norderney"
cap label var DE_1DENOR "Nordstrand"
cap label var DE_1DEOLO "Oldenburg"
cap label var DE_3DEORS "Orsoy"
cap label var DE_2DEORT "Orth/Fehmarn"
cap label var DE_1DEPAP "Papenburg"
cap label var DE_3DEPEI "Peine"
cap label var DE_1DEPEL "Pellworm"
cap label var DE_2DEPUB "Putbus"
cap label var DE_2DEPUT "Puttgarden"
cap label var DE_3DEREC "Recklinghausen"
cap label var DE_3DERHO "Reisholz"
cap label var DE_2DEREN "Rendsburg"
cap label var DE_3DERHB "Rheinberg-Ossenberg"
cap label var DE_3DERSA "Riesa"
cap label var DE_2DERSK "Rostock"
cap label var DE_2DE055 "Rügen (Östlich Stralsunder Fahrwasser)"
cap label var DE_3DE75F "Sachsenhagen"
cap label var DE_3DESAR "Salzgitter"
cap label var DE_2DESAS "Sassnitz"
cap label var DE_1DEHMO "Schwarzenhütten, Hemmoor"
cap label var DE_3DESDT "Schwedt"
cap label var DE_3DESNE "Sehnde"
cap label var DE_1DESPI "Spieckeroog"
cap label var DE_3DE061 "Spyck"
cap label var DE_3DEPYK "Spyck"
cap label var DE_1DESTA "Stade"
cap label var DE_1DESTS "Stadersand"
cap label var DE_1DESDD "Steenodde"
cap label var DE_2DESTL "Stralsund"
cap label var DE_3DESTR "Stuttgart"
cap label var DE_2DEUCK "Ueckermünde"
cap label var DE_3DEUEL "Uelzen"
cap label var DE_3DEVNA "Venhaus"
cap label var DE_3DEVIW "Vierow"
cap label var DE_3DEWLM "Walsum"
cap label var DE_1DEAGE "Wangerooge"
cap label var DE_1DEWED "Wedel-Schulau"
cap label var DE_3DEWNU "Weissenthurm"
cap label var DE_3DEWTM "Wertheim"
cap label var DE_3DEWES "Wesel"
cap label var DE_1DEWVN "Wilhelmshaven"
cap label var DE_1DEWIF "Wischhafen"
cap label var DE_2DEWIS "Wismar"
cap label var DE_1DEWMD "Wittmund"
cap label var DE_2DEWOL "Wolgast"
cap label var DE_3DEWOR "Worms"
cap label var DE_1DEWYK "Wyk/Föhr"
cap label var DE_2DE88O "Germany (Baltic Sea) - other ports"
cap label var DE_1DE116 "Germany (Elbe) - other ports"
cap label var DE_1DE88N "Germany (North Sea) - other ports"
cap label var DE_3DE888 "Germany - other inland ports"
cap label var DE_9DE888 "Germany (unknown maritime coastal area) - other ports"
cap label var EE_0EEBEK "Bekkeri"
cap label var EE_0EEHLT "Heltermaa"
cap label var EE_0EEKUI "Kuivastu"
cap label var EE_0EEKND "Kunda"
cap label var EE_0EEMDR "Miiduranna"
cap label var EE_0EEPLN "Paldiski Põhjasadam"
cap label var EE_0EEPRN "Pärnu"
cap label var EE_0EEPAR "Patareisadam"
cap label var EE_0EERHK "Rohuküla"
cap label var EE_0EESLM "Sillamäe"
cap label var EE_0EETLL "Tallinn"
cap label var EE_0EEVEB "Vene-Balti"
cap label var EE_0EEVIR "Virtsu"
cap label var EE_0EE888 "Estonia - other ports"
cap label var IE_0IEARK "Arklow"
cap label var IE_0IEBYT "Bantry Bay"
cap label var IE_0IECTB "Castletownbere (Castletown Bearhaven)"
cap label var IE_0IEORK "Cork"
cap label var IE_0IEDRO "Drogheda"
cap label var IE_0IEDUB "Dublin"
cap label var IE_0IEDLG "Dun Laoghaire"
cap label var IE_0IEDDK "Dundalk"
cap label var IE_0IEFOV "Foynes"
cap label var IE_0IEGWY "Galway"
cap label var IE_0IEGRN "Greenore"
cap label var IE_0IEKBS "Killybegs"
cap label var IE_0IEKLR "Kilrush"
cap label var IE_0IEKLN "Kinsale"
cap label var IE_0IELMK "Limerick"
cap label var IE_0IENRS "New Ross"
cap label var IE_0IEROS "Rosslare Harbour"
cap label var IE_0IESLI "Sligo"
cap label var IE_0IETRA "Tralee"
cap label var IE_0IEWAT "Waterford"
cap label var IE_0IEWIC "Wicklow"
cap label var IE_0IEYOU "Youghal"
cap label var EL_0GRACL "Achladi"
cap label var EL_0GRMLO "Adamas Milou"
cap label var EL_0GRAGN "Agathonisi Dodekanisou"
cap label var EL_0GR702 "Agathonisi Dodekanisou"
cap label var EL_0GRAEF "Agia Efimia"
cap label var EL_0GR701 "Agia Galini Rethimnou"
cap label var EL_0GRAKM "Agia Kyriaki (Trikeri) Magnisias"
cap label var EL_0GRAMR "Agia Marina Aiginas"
cap label var EL_0GR868 "Agia Marina Aiginas"
cap label var EL_0GRGMA "Agia Marina Attikis"
cap label var EL_0GR883 "Agia Marina Attikis"
cap label var EL_0GRAGM "Agia Marina Fthiotidas"
cap label var EL_0GRAPE "Agia Pelagia"
cap label var EL_0GRROU "Agia Roumeli Chanion"
cap label var EL_0GRAGT "Agioi Theodoroi"
cap label var EL_0GRAGK "Agiokampos Larisas"
cap label var EL_0GRAGO "Agios Efstratios Lesvou"
cap label var EL_0GR912 "Agios Georgios Saronikou"
cap label var EL_0GRAKI "Agios Kirykos"
cap label var EL_0GRAKO "Agios Konstantinos"
cap label var EL_0GRAGF "Agios Nikolaos Fokidas"
cap label var EL_0GRANI "Agios Nikolaos Kritis"
cap label var EL_0GRAGG "Agkistri Aiginas"
cap label var EL_0GRAGA "Agria Volou"
cap label var EL_0GREDI "Aidipsos"
cap label var EL_0GRAIG "Aigiali Amorgou"
cap label var EL_0GRAEG "Aigina"
cap label var EL_0GRAEN "Aigio"
cap label var EL_0GRAKT "Aktio Vonitsas"
cap label var EL_0GRAXD "Alexandroupolis"
cap label var EL_0GRLVR "Aliverio"
cap label var EL_0GR886 "Almyropotamos Evvoias"
cap label var EL_0GRALM "Almyros Volou"
cap label var EL_0GRALO "Alonnisos"
cap label var EL_0GRATS "Altsi"
cap label var EL_0GRAPL "Amaliapolis Magnisias"
cap label var EL_0GRAMF "Amfilochia"
cap label var EL_0GRAMI "Ammouliani"
cap label var EL_0GRAMO "Amorgos (Katapola)"
cap label var EL_0GRANA "Anafi, Kyklades"
cap label var EL_0GRAND "Andros"
cap label var EL_0GRATK "Antikyra"
cap label var EL_0GRANP "Antiparos"
cap label var EL_0GRANT "Antirrio"
cap label var EL_0GRARX "Araxos"
cap label var EL_0GR870 "Araxos"
cap label var EL_0GRARM "Argostoli"
cap label var EL_0GREFL "Argostoli"
cap label var EL_0GRARD "Arkioi Dodekanisou"
cap label var EL_0GR717 "Arkioi Dodekanisou"
cap label var EL_0GRARK "Arkitsa Fthiotidas"
cap label var EL_0GRASS "Aspropyrgos"
cap label var EL_0GRAPY "Aspropyrgos"
cap label var EL_0GRAST "Astakos"
cap label var EL_0GRARS "Astros Arkadias"
cap label var EL_0GR719 "Astros Arkadias"
cap label var EL_0GRJTY "Astypalaia"
cap label var EL_0GR720 "Atalanti Fthiotidas"
cap label var EL_0GRHAL "Chalki Dodekanisou"
cap label var EL_0GRCLK "Chalkida"
cap label var EL_0GRCHQ "Chania"
cap label var EL_0GRJKH "Chios"
cap label var EL_0GRCSF "Chora Sfakion"
cap label var EL_0GRDAF "Dafni Agiou Orous"
cap label var EL_0GR730 "Derveni Korinthias"
cap label var EL_0GRDIA "Diafani Karpathou"
cap label var EL_0GRDIK "Diakofti Kythiron"
cap label var EL_0GRDMB "Domvraina Voiotias"
cap label var EL_0GR900 "Domvraina Voiotias"
cap label var EL_0GRDON "Donousa, Kyklades"
cap label var EL_0GRDPA "Drapetsona"
cap label var EL_0GRDRE "Drepano Riou"
cap label var EL_0GRELN "Elafonisos Lakonias"
cap label var EL_0GREEU "Elefsina"
cap label var EL_0GRELT "Eleftheres"
cap label var EL_0GRERK "Ereikousa, Diapontia nisia"
cap label var EL_0GRERE "Eretria Evvoias"
cap label var EL_0GRERM "Ermioni"
cap label var EL_0GREYD "Evdilos"
cap label var EL_0GRFNR "Faneromeni Salaminas"
cap label var EL_0GRFIS "Fiskardo Kefallinias"
cap label var EL_0GRFOL "Folegandros Kyklades"
cap label var EL_0GRFOU "Fournoi Samou"
cap label var EL_0GRSAT "Frikes Ithakis"
cap label var EL_0GRGAL "Galatas Troizinias"
cap label var EL_0GRGAD "Gavdos Chanion"
cap label var EL_0GRGAV "Gavrio"
cap label var EL_0GR857 "Gerakas Lakonias"
cap label var EL_0GRYER "Gerakini"
cap label var EL_0GRGLO "Glossa Skopelou"
cap label var EL_0GRGLY "Glyfa Fthiotidas"
cap label var EL_0GRGYT "Gytheio"
cap label var EL_0GRIER "Ierapetra Lasithiou"
cap label var EL_0GRIES "Ierissos Chalkidikis"
cap label var EL_0GRIGO "Igoumenitsa"
cap label var EL_0GRIOS "Ios"
cap label var EL_0GRHRK "Irakleia, Kyklades"
cap label var EL_0GRHER "Irakleio"
cap label var EL_0GRITM "Isthmia"
cap label var EL_0GRITA "Itea"
cap label var EL_0GRITH "Ithaki"
cap label var EL_0GRKLX "Kalamata"
cap label var EL_0GRKLD "Kalathos Rodou"
cap label var EL_0GR743 "Kalloni Lesvou"
cap label var EL_0GRKLS "Kaloi Limenes Rethymnou"
cap label var EL_0GRKLI "Kaloi Limenes Rethymnou"
cap label var EL_0GRKMI "Kalymnos"
cap label var EL_0GR745 "Kameiros Rodou"
cap label var EL_0GRKAP "Kapsali"
cap label var EL_0GRKAR "Karlovasi"
cap label var EL_0GRAOK "Karpathos"
cap label var EL_0GR854 "Karra Chalkidikis"
cap label var EL_0GRKST "Karystos"
cap label var EL_0GRKSJ "Kasos"
cap label var EL_0GRKIS "Kasteli Kissamou"
cap label var EL_0GRKAK "Katakolo"
cap label var EL_0GRKVA "Kavala"
cap label var EL_0GRKEA "Kea"
cap label var EL_0GRKEF "Kefalos Kos"
cap label var EL_0GRKER "Keramoti"
cap label var EL_0GRKTS "Keratsini"
cap label var EL_0GRCFU "Kerkyra"
cap label var EL_0GRKIO "Kiato"
cap label var EL_0GRKMS "Kimolos"
cap label var EL_0GR754 "Koilas Ermionidas, Argolida"
cap label var EL_0GRKIN "Koilas Ermionidas, Argolida"
cap label var EL_0GRKRT "Korinthos"
cap label var EL_0GR755 "Korthio Androu"
cap label var EL_0GRKGS "Kos"
cap label var EL_0GRKEM "Kosta Ermionidas"
cap label var EL_0GR881 "Kosta Ermionidas"
cap label var EL_0GRKOF "Koufonisi, Kyklades"
cap label var EL_0GRKYL "Kylini"
cap label var EL_0GRKYM "Kymasi"
cap label var EL_0GRKIM "Kymi"
cap label var EL_0GRKYT "Kythnos"
cap label var EL_0GR862 "Lagos"
cap label var EL_0GRLRS "Lakki Lerou"
cap label var EL_0GRLRY "Larymna"
cap label var EL_0GRLAV "Lavrio"
cap label var EL_0GRLEV "Lefkada"
cap label var EL_0GRLEF "Lefkadi"
cap label var EL_0GRLFK "Lefkimmi"
cap label var EL_0GRLIP "Leipsoi Dodekanisou"
cap label var EL_0GRLND "Leonidio"
cap label var EL_0GRSKU "Linaria Skyrou"
cap label var EL_0GRLIN "Linoperamata Irakleiou"
cap label var EL_0GRLIX "Lixouri"
cap label var EL_0GRLTR "Loutro Chanion"
cap label var EL_0GRZEA "Marina Zeas"
cap label var EL_0GRMRM "Marmari"
cap label var EL_0GRMTR "Mathraki, Diapontia nisia"
cap label var EL_0GRMGN "Meganisi"
cap label var EL_0GRMGR "Megara"
cap label var EL_0GRKAS "Megisti Kastelorizou"
cap label var EL_0GRMEN "Menidi Aitoloakarnanias"
cap label var EL_0GRMES "Messogaia"
cap label var EL_0GRMEL "Messolongi"
cap label var EL_0GRMHI "Mesta Chiou"
cap label var EL_0GRMET "Methana"
cap label var EL_0GRMOL "Molyvos Lesvou"
cap label var EL_0GRMON "Monemvasia"
cap label var EL_0GRMDR "Moudros Limnou"
cap label var EL_0GRJMK "Mykonos"
cap label var EL_0GRMYR "Myrina"
cap label var EL_0GRMJT "Mytilini"
cap label var EL_0GRNAF "Nafplio"
cap label var EL_0GRJNX "Naxos"
cap label var EL_0GRNKV "Nea Karvali Kavalas"
cap label var EL_0GRNMA "Nea Moudania Chalkidikis"
cap label var EL_0GR795 "Nea Psara Chiou"
cap label var EL_0GRNST "Nea Styra"
cap label var EL_0GRNEA "Neapoli Lakonias"
cap label var EL_0GRNIS "Nissyros"
cap label var EL_0GRNID "Nydri"
cap label var EL_0GRINO "Oinousses"
cap label var EL_0GRORE "Oreoi"
cap label var EL_0GRORO "Oropos"
cap label var EL_0GROTH "Othonoi"
cap label var EL_0GROUR "Ouranoupoli Chalkidikis"
cap label var EL_0GRPEP "Palaia Epidavros"
cap label var EL_0GRPAA "Palaia Psara Chiou"
cap label var EL_0GRPSF "Palaiochora Sfakion"
cap label var EL_0GRPAO "Paloukia Salaminas"
cap label var EL_0GR913 "Panormitis"
cap label var EL_0GRPAR "Parga"
cap label var EL_0GRPAS "Paros"
cap label var EL_0GRPMS "Patmos"
cap label var EL_0GRGPA "Patra"
cap label var EL_0GRPAX "Paxoi"
cap label var EL_0GRPIR "Peiraias"
cap label var EL_0GRPER "Perama"
cap label var EL_0GRPGM "Perama Geras Mytilinis"
cap label var EL_0GRPSK "Pessada Kefallinias"
cap label var EL_0GR887 "Pessada Kefallinias"
cap label var EL_0GRPET "Petra Lesvou"
cap label var EL_0GR813 "Petritis Kerkyras"
cap label var EL_0GRPYV "Pevki Evvoias"
cap label var EL_0GRPIS "Pisaetos Ithakis"
cap label var EL_0GRPTI "Plataria Thesprotias"
cap label var EL_0GRPLG "Platygiali Aitoloakarnanias"
cap label var EL_0GRPLM "Plomari Lesvou"
cap label var EL_0GRPLC "Polichnitos Lesvou"
cap label var EL_0GRPTK "Politika"
cap label var EL_0GRPKE "Poros Kefallinias"
cap label var EL_0GRPTR "Poros Troizinias"
cap label var EL_0GRPHE "Porto Cheli"
cap label var EL_0GRPTL "Porto Lagos"
cap label var EL_0GRPOA "Potamos Antikythiron"
cap label var EL_0GRPVK "Preveza"
cap label var EL_0GR822 "Prinos Kavalas"
cap label var EL_0GRPPI "Prinos Thasou"
cap label var EL_0GRPSA "Psachna"
cap label var EL_0GRPYL "Pylos"
cap label var EL_0GRPYT "Pythagorio"
cap label var EL_0GRRAF "Rafina"
cap label var EL_0GRRET "Rethymno"
cap label var EL_0GRRIO "Rio"
cap label var EL_0GRRHO "Rodos"
cap label var EL_0GRSMI "Sami"
cap label var EL_0GRSAM "Samothraki"
cap label var EL_0GRSHI "Schoinari Zakynthou"
cap label var EL_0GR892 "Schoinari Zakynthou"
cap label var EL_0GRSHC "Schoinousa, Kyklades"
cap label var EL_0GRSER "Serifos"
cap label var EL_0GRKRE "Sifnos"
cap label var EL_0GRSGR "Sigri Lesvou"
cap label var EL_0GR835 "Sikia Porto Rafti"
cap label var EL_0GRSII "Sikinos, Kyklades"
cap label var EL_0GRJSH "Siteia"
cap label var EL_0GRSKA "Skaramagkas"
cap label var EL_0GRJSI "Skiathos"
cap label var EL_0GRSKO "Skopelos"
cap label var EL_0GRSUD "Souda Bay"
cap label var EL_0GRSOG "Sougia"
cap label var EL_0GRSLA "Souvala Aiginas"
cap label var EL_0GR832 "Souvala Aiginas"
cap label var EL_0GRSPE "Spetses"
cap label var EL_0GRSHA "Stavros Chalkidikis"
cap label var EL_0GRSTI "Stratonio"
cap label var EL_0GRSYS "Stylida"
cap label var EL_0GRSYM "Symi"
cap label var EL_0GRJSY "Syros"
cap label var EL_0GRTSO "Thasos"
cap label var EL_0GRSKG "Thessaloniki"
cap label var EL_0GRJTR "Thira"
cap label var EL_0GRTRS "Thirasia"
cap label var EL_0GRTIL "Tilos Dodekanisou"
cap label var EL_0GRTIN "Tinos"
cap label var EL_0GRTLA "Tolo Argolidas"
cap label var EL_0GR838 "Trikeri Magnisias"
cap label var EL_0GRTRY "Trypiti Chalkidikis"
cap label var EL_0GRVSS "Vasiliki Lefkadas"
cap label var EL_0GRVTH "Vathy Samou"
cap label var EL_0GRVLC "Volissos (Limnia) Chiou"
cap label var EL_0GRVOL "Volos"
cap label var EL_0GR909 "Voreios Evvoikos"
cap label var EL_0GRHYD "Ydra"
cap label var EL_0GRZTH "Zakynthos"
cap label var EL_0GR88P "Greece (offshore installations) - other ports"
cap label var EL_0GR88Q "Greece (aggregates extraction areas) - other ports"
cap label var EL_0GR88R "Greece (ship to ship transfer)"
cap label var EL_0GR888 "Greece - other ports"
cap label var ES_2ESAGA "Agaete"
cap label var ES_2ESACA "Alcanar"
cap label var ES_2ESALG "Algeciras"
cap label var ES_2ESALC "Alicante"
cap label var ES_2ESLEI "Almería"
cap label var ES_1ESAVS "Avilés"
cap label var ES_2ESBBE "Barbate"
cap label var ES_2ESBCN "Barcelona"
cap label var ES_1ESBRM "Bermeo"
cap label var ES_1ESBIO "Bilbao"
cap label var ES_2ESCAD "Cádiz"
cap label var ES_2ESCHR "Caleta de Sebo"
cap label var ES_2ESCAR "Cartagena"
cap label var ES_2ESCAS "Castellón"
cap label var ES_3ESCEU "Ceuta"
cap label var ES_2ESQFU "Corralejo"
cap label var ES_1ESFRO "Ferrol"
cap label var ES_2ESGAR "Garrucha"
cap label var ES_1ESGIJ "Gijón"
cap label var ES_2ESHUV "Huelva"
cap label var ES_1ESLCG "La Coruña"
cap label var ES_2ESLPA "Las Palmas"
cap label var ES_2ESAGP "Málaga"
cap label var ES_1ESMPG "Marín-Pontevedra"
cap label var ES_4ESMLN "Melilla"
cap label var ES_2ESMOL "Molina de Segura"
cap label var ES_2ESMJB "Morro Jable"
cap label var ES_2ESMOT "Motril"
cap label var ES_2ESOZL "Orzola"
cap label var ES_2ESPAL "Palamós"
cap label var ES_2ESPMI "Palma Mallorca"
cap label var ES_1ESPAS "Pasajes"
cap label var ES_2ESQLY "Playa Blanca"
cap label var ES_2ESPPS "Playa Santiago"
cap label var ES_2ESSCR "San Carlos de la Rápita"
cap label var ES_2ESSCT "Santa Cruz de Tenerife"
cap label var ES_1ESSDR "Santander"
cap label var ES_2ESSVQ "Sevilla"
cap label var ES_2ESTRF "Tarifa"
cap label var ES_2ESTAR "Tarragona"
cap label var ES_2ESVLC "Valencia"
cap label var ES_2ESVCC "Vallcarca"
cap label var ES_2ESVGR "Valle Gran Rey"
cap label var ES_1ESVGO "Vigo"
cap label var ES_2ESVLG "Vilanova i la Geltrú"
cap label var ES_1ESVIL "Villagarcía (de Arosa)"
cap label var ES_2ES88M "Spain (Mediterranean and South Atlantic) - other ports"
cap label var ES_9ES888 "Spain (unknown maritime coastal area) - other ports"
cap label var FR_1FR001 "HAROPA (Le Havre and Rouen)"
cap label var FR_2FRAJA "Ajaccio"
cap label var FR_2FRBIA "Bastia"
cap label var FR_1FRBAY "Bayonne"
cap label var FR_2FRBON "Bonifacio"
cap label var FR_1FRBOD "Bordeaux"
cap label var FR_1FRBOL "Boulogne-sur-Mer"
cap label var FR_1FRBES "Brest"
cap label var FR_1FRCFR "Caen"
cap label var FR_1FRCQF "Calais"
cap label var FR_2FRCLY "Calvi"
cap label var FR_1FRCAM "Camaret"
cap label var FR_2FRCEQ "Cannes"
cap label var FR_1FRCRT "Carteret"
cap label var FR_3GFCAY "Cayenne"
cap label var FR_1FRCER "Cherbourg"
cap label var FR_1FRCOC "Concarneau"
cap label var FR_3GFDDC "Degrad-des Cannes (Guyane)"
cap label var FR_1FRDPE "Dieppe"
cap label var FR_1FRDRZ "Douarnenez"
cap label var FR_1FRDKK "Dunkerque"
cap label var FR_1FRFEC "Fécamp"
cap label var FR_4MQFDF "Fort-de France (Martinique)"
cap label var FR_1FRGFR "Granville"
cap label var FR_1FRGRV "Gravelines"
cap label var FR_1FRHET "Hennebont"
cap label var FR_1FRHON "Honfleur"
cap label var FR_3GFQKR "Kourou (Guyane)"
cap label var FR_2FRLCT "La Ciotat"
cap label var FR_1FRLRH "La Rochelle"
cap label var FR_1FRLDN "Landerneau"
cap label var FR_1FRLAI "Lannion"
cap label var FR_3GFLVT "Larivot (Guyane)"
cap label var FR_1FRLFR "Le Fret (Crozon)"
cap label var FR_1FRLGU "Le Guildo (Crehen)"
cap label var FR_1FRLEH "Le Havre"
cap label var FR_1FRLLG "Le Légué"
cap label var FR_1FRSBK "Le Legue (St Brieuc)"
cap label var FR_1FRLTR "Le Tréport"
cap label var FR_1FRLSO "Les Sables d'Olonne"
cap label var FR_1FRLEZ "Lézardrieux"
cap label var FR_2FRILR "L´Île Rousse"
cap label var FR_1FRLRT "Lorient"
cap label var FR_2FRMRS "Marseille"
cap label var FR_1FRMXN "Morlaix"
cap label var FR_1FRMSG "Mortagne-sur-Gironde"
cap label var FR_1FRNTE "Nantes Saint-Nazaire"
cap label var FR_2FRNCE "Nice"
cap label var FR_1FRPAI "Paimpol"
cap label var FR_4GPPTP "Pointe-à-Pitre (Guadeloupe)"
cap label var FR_1FRPOX "Pontrieux"
cap label var FR_5REPDG "Port Réunion (ex Pointe-des-Galets) (Réunion)"
cap label var FR_2FRPOV "Port Vendres"
cap label var FR_1FRPRJ "Port-Joinville (Île d´Yeu)"
cap label var FR_2FRNOU "Port-la-Nouvelle"
cap label var FR_2FRPVO "Porto Vecchio"
cap label var FR_2FRPRP "Propriano"
cap label var FR_1FRUIP "Quimper"
cap label var FR_1FRRDN "Redon"
cap label var FR_1FRRCO "Rochefort"
cap label var FR_1FRROS "Roscoff"
cap label var FR_1FRURO "Rouen"
cap label var FR_1FRRYN "Royan"
cap label var FR_2FRSET "Sète"
cap label var FR_3GFSLM "St Laurent du Maroni (Guyane)"
cap label var FR_1FRSML "St Malo"
cap label var FR_2FRSRL "St Raphaël"
cap label var FR_1FRSVS "St Valéry-sur-Somme"
cap label var FR_1FRTON "Tonnay Charente"
cap label var FR_2FRTLN "Toulon"
cap label var FR_1FRTRE "Tréguier"
cap label var FR_1FRVNE "Vannes"
cap label var FR_1FR888 "France (Atlantic / North Sea) - other ports"
cap label var FR_9FR888 "France (unknown maritime coastal area) - other ports"
cap label var HR_0HRBAK "Bakar"
cap label var HR_0HRBAS "Baska"
cap label var HR_0HRBNM "Biograd na Moru"
cap label var HR_0HRBOL "Bol"
cap label var HR_0HRBZA "Bozava"
cap label var HR_0HRCVT "Cavtat"
cap label var HR_0HRCRS "Cres"
cap label var HR_0HRCRA "Crikvenica"
cap label var HR_0HRDBV "Dubrovnik"
cap label var HR_0HRHVA "Hvar"
cap label var HR_0HRIST "Ist"
cap label var HR_0HRJAB "Jablanac"
cap label var HR_0HRJSA "Jelsa"
cap label var HR_0HRKAB "Karlobag"
cap label var HR_0HRKMZ "Komiza"
cap label var HR_0HRKOR "Korcula"
cap label var HR_0HRKRA "Kraljevica"
cap label var HR_0HRKRK "Krk"
cap label var HR_0HRLST "Lastovo"
cap label var HR_0HRMAK "Makarska"
cap label var HR_0HRLSZ "Mali Losinj"
cap label var HR_0HRMAL "Malinska"
cap label var HR_0HRMAS "Maslenica"
cap label var HR_0HRMET "Metkovic"
cap label var HR_0HRMIL "Milna"
cap label var HR_0HRMOD "Moscenicka Draga"
cap label var HR_0HRMUR "Murter"
cap label var HR_0HRNVL "Novalja"
cap label var HR_0HRNVD "Novi Vinodolski"
cap label var HR_0HRNVG "Novigrad"
cap label var HR_0HROMS "Omis"
cap label var HR_0HROMI "Omisalj"
cap label var HR_0HROPA "Opatija"
cap label var HR_0HRPAG "Pag"
cap label var HR_0HRPLE "Ploce"
cap label var HR_0HRPMN "Pomena"
cap label var HR_0HRPOR "Porec"
cap label var HR_0HRPRE "Preko"
cap label var HR_0HRPRI "Primosten"
cap label var HR_0HRPUY "Pula"
cap label var HR_0HRPNT "Punat"
cap label var HR_0HRRAB "Rab"
cap label var HR_0HRRBC "Rabac"
cap label var HR_0HRRAS "Rasa"
cap label var HR_0HRRJK "Rijeka"
cap label var HR_0HRRGC "Rogac"
cap label var HR_0HRRGN "Rogoznica"
cap label var HR_0HRROV "Rovinj"
cap label var HR_0HRSAL "Sali"
cap label var HR_0HRSEN "Senj"
cap label var HR_0HRSIB "Sibenik"
cap label var HR_0HRSIL "Silba"
cap label var HR_0HRSLO "Silo"
cap label var HR_0HRSLA "Slano"
cap label var HR_0HRSBR "Sobra"
cap label var HR_0HRSPU "Split"
cap label var HR_0HRSGD "Stari Grad"
cap label var HR_0HRSGR "Starigrad"
cap label var HR_0HRSTO "Ston"
cap label var HR_0HRSUC "Sucuraj"
cap label var HR_0HRSMN "Sumartin"
cap label var HR_0HRSUP "Supetar"
cap label var HR_0HRSSK "Susak"
cap label var HR_0HRSVJ "Sveti Juraj"
cap label var HR_0HRTNO "Tisno"
cap label var HR_0HRTRO "Trogir"
cap label var HR_0HRTRJ "Trpanj"
cap label var HR_0HRTRK "Trstenik"
cap label var HR_0HRUBL "Ubli"
cap label var HR_0HRUMG "Umag"
cap label var HR_0HRVLK "Vela Luka"
cap label var HR_0HRVIS "Vis"
cap label var HR_0HRVDC "Vodice"
cap label var HR_0HRZAD "Zadar"
cap label var IT_0ITAHO "Alghero"
cap label var IT_0ITALI "Alicudi"
cap label var IT_0ITAMA "Amalfi"
cap label var IT_0ITAOI "Ancona"
cap label var IT_0ITANZ "Anzio"
cap label var IT_0ITATX "Arbatax"
cap label var IT_0ITAUG "Augusta"
cap label var IT_0ITBLN "Bagnoli"
cap label var IT_0ITBAI "Baia"
cap label var IT_0ITBRI "Bari"
cap label var IT_0ITBLT "Barletta"
cap label var IT_0ITBDS "Brindisi"
cap label var IT_0ITCAG "Cagliari"
cap label var IT_0ITCLS "Calasetta"
cap label var IT_0ITCPA "Capraia"
cap label var IT_0ITPRJ "Capri"
cap label var IT_0ITCLF "Carloforte"
cap label var IT_0ITCML "Casamicciola"
cap label var IT_0ITCTR "Castellammare del Golfo"
cap label var IT_0ITCAS "Castellammare di Stabia"
cap label var IT_0ITCTA "Catania"
cap label var IT_0ITCVX "Cavo"
cap label var IT_0ITCHI "Chioggia"
cap label var IT_0ITCVV "Civitavecchia"
cap label var IT_0ITCGC "Corigliano Calabro"
cap label var IT_0ITCRV "Crotone"
cap label var IT_0IT003 "Egadi"
cap label var IT_0IT004 "Eolie"
cap label var IT_0ITFAL "Falconara Marittima"
cap label var IT_0ITFAV "Favignana"
cap label var IT_0ITFPO "Filicudi Porto"
cap label var IT_0ITFCO "Fiumicino"
cap label var IT_0ITFOM "Formia"
cap label var IT_0ITGAE "Gaeta"
cap label var IT_0ITGAL "Gallipoli"
cap label var IT_0ITGEA "Gela"
cap label var IT_0ITGOA "Genova"
cap label var IT_0ITGII "Giannutri"
cap label var IT_0ITGIA "Giardini di Naxos"
cap label var IT_0ITGIT "Gioia Tauro"
cap label var IT_0ITGAI "Golfo Aranci"
cap label var IT_0ITGOR "Gorgona"
cap label var IT_0ITGRD "Grado"
cap label var IT_0ITIMP "Imperia"
cap label var IT_0IT001 "Ischia"
cap label var IT_0IT002 "Isola d' Elba"
cap label var IT_0ITIDG "Isola del Giglio"
cap label var IT_0ITISS "Isola Santo Stefano"
cap label var IT_0ITMDA "La Maddalena"
cap label var IT_0ITSPE "La Spezia"
cap label var IT_0ITLMP "Lampedusa"
cap label var IT_0ITLEV "Levanzo"
cap label var IT_0ITLIC "Licata"
cap label var IT_0ITLIU "Linosa"
cap label var IT_0ITLIP "Lipari"
cap label var IT_0ITLIV "Livorno"
cap label var IT_0ITMFR "Manfredonia"
cap label var IT_0ITMMO "Marettimo"
cap label var IT_0ITMDC "Marina di Carrara"
cap label var IT_0ITMRA "Marsala"
cap label var IT_0ITMAZ "Mazara del Vallo"
cap label var IT_0ITMSN "Messina"
cap label var IT_0ITMLZ "Milazzo"
cap label var IT_0ITMOL "Molfetta"
cap label var IT_0ITMNF "Monfalcone"
cap label var IT_0ITMNP "Monopoli"
cap label var IT_0ITNAP "Napoli"
cap label var IT_0ITOLB "Olbia"
cap label var IT_0ITONE "Oneglia"
cap label var IT_0ITQOS "Oristano"
cap label var IT_0ITOTN "Ortona"
cap label var IT_0ITOTO "Otranto"
cap label var IT_0ITPAU "Palau"
cap label var IT_0ITPMO "Palermo"
cap label var IT_0ITPAN "Panarea"
cap label var IT_0ITPNL "Pantelleria"
cap label var IT_0ITPES "Pesaro"
cap label var IT_0ITPSR "Pescara"
cap label var IT_0ITPCH "Peschici"
cap label var IT_0ITPIA "Pianosa"
cap label var IT_0ITPIO "Piombino"
cap label var IT_0ITPNZ "Ponza"
cap label var IT_0ITPGL "Portiglioni"
cap label var IT_0ITPAZ "Porto Azzurro"
cap label var IT_0ITPCE "Porto Cervo"
cap label var IT_0ITPDI "Porto d'Ischia"
cap label var IT_0ITPEM "Porto Empedocle"
cap label var IT_0ITPFX "Porto Foxi"
cap label var IT_0ITPGA "Porto Garibaldi"
cap label var IT_0ITPFO "Porto Levante"
cap label var IT_0ITPLI "Porto Lignano"
cap label var IT_0ITPMZ "Porto Maurizio"
cap label var IT_0ITPNG "Porto Nogaro"
cap label var IT_0ITPSS "Porto Santo Stefano"
cap label var IT_0ITPTO "Porto Torres"
cap label var IT_0ITPFE "Portoferraio"
cap label var IT_0ITPTF "Portofino"
cap label var IT_0ITPVE "Portovesme"
cap label var IT_0ITPOS "Positano"
cap label var IT_0ITPZL "Pozzallo"
cap label var IT_0ITPOZ "Pozzuoli"
cap label var IT_0ITPRO "Procida"
cap label var IT_0ITRAN "Ravenna"
cap label var IT_0ITREG "Reggio di Calabria"
cap label var IT_0ITRMI "Rimini"
cap label var IT_0ITRMA "Rio Marina"
cap label var IT_0ITRPT "Riposto"
cap label var IT_0ITRGG "Rodi Garganico"
cap label var IT_0ITSDB "S. Benedetto del Tronto"
cap label var IT_0ITSAL "Salerno"
cap label var IT_0ITSLA "Salina"
cap label var IT_0ITSRE "Sanremo"
cap label var IT_0ITSML "Santa Margherita Ligure"
cap label var IT_0ITSPA "Santa Panagia"
cap label var IT_0ITSTE "Santa Teresa di Gallura"
cap label var IT_0ITSAT "Sant'Antioco"
cap label var IT_0ITSVC "Santo Vito Lo Capo"
cap label var IT_0ITSVN "Savona"
cap label var IT_0ITSIR "Siracusa"
cap label var IT_0ITRRO "Sorrento"
cap label var IT_0ITSTR "Stromboli"
cap label var IT_0ITTAL "Talamone"
cap label var IT_0ITTAR "Taranto"
cap label var IT_0ITTRI "Termini Imerese"
cap label var IT_0ITTMI "Termoli"
cap label var IT_0ITTRC "Terracina"
cap label var IT_0ITTOA "Torre Annunziata"
cap label var IT_0ITTGR "Torregrande"
cap label var IT_0ITTVC "Torviscosa"
cap label var IT_0ITTNI "Trani"
cap label var IT_0ITTPS "Trapani"
cap label var IT_0ITTMT "Tremiti"
cap label var IT_0ITTRS "Trieste"
cap label var IT_0ITUST "Ustica"
cap label var IT_0ITVDA "Vada"
cap label var IT_0ITVSO "Vasto"
cap label var IT_0ITVCE "Venezia"
cap label var IT_0ITVTT "Ventotene"
cap label var IT_0ITVIA "Viareggio"
cap label var IT_0ITVVA "Vibo Valentia"
cap label var IT_0ITVIE "Vieste"
cap label var IT_0ITVUL "Vulcano Porto"
cap label var IT_0IT88C "Italy - main ports (confidential data aggregated by Eurostat)"
cap label var IT_0IT88D "Italy - all ports (confidential data aggregated by Eurostat)"
cap label var IT_0IT88P "Italy (offshore installations) - other ports"
cap label var IT_0IT88Q "Italy (aggregates extraction areas) - other ports"
cap label var IT_0IT888 "Italy - other ports"
cap label var CY_0CYAKT "Akrotiri (oil terminal)"
cap label var CY_0CYDHK "Dekeleia"
cap label var CY_0CYLCA "Larnaka"
cap label var CY_0CY01M "Larnaka (oil terminal)"
cap label var CY_0CYLAT "Latsi"
cap label var CY_0CYLMS "Lemesos"
cap label var CY_0CYMOI "Moni"
cap label var CY_0CYVAS "Vasiliko"
cap label var CY_0CYZYY "Zygi"
cap label var CY_0CY888 "Cyprus - other ports"
cap label var LV_0LVLPX "Liepaja"
cap label var LV_0LVMRX "Mersrags"
cap label var LV_0LVRIX "Riga"
cap label var LV_0LVROJ "Roja"
cap label var LV_0LVSAL "Salacgriva"
cap label var LV_0LVSKU "Skulte"
cap label var LV_0LVVNT "Ventspils"
cap label var LV_0LV888 "Latvia - other ports"
cap label var LT_0LTBOT "Butinge"
cap label var LT_0LTKLJ "Klaipeda"
cap label var MT_0MTCKW "Cirkewwa"
cap label var MT_0MTMAR "Marsaxlokk"
cap label var MT_0MTMGZ "Mgarr, Gozo"
cap label var MT_0MTMLA "Valletta"
cap label var MT_0MT888 "Malta - other ports"
cap label var NL_0NLABL "Alblasserdam"
cap label var NL_0NLAML "Ameland"
cap label var NL_0NLAMS "Amsterdam"
cap label var NL_0NLBGB "Bergambacht"
cap label var NL_0NLBZM "Bergen op Zoom"
cap label var NL_0NLBEV "Beverwijk"
cap label var NL_0NLBOR "Borsele"
cap label var NL_0NLBRK "Brakel"
cap label var NL_0NLBRS "Breskens"
cap label var NL_0NLCPI "Capelle aan den Ijssel"
cap label var NL_0NLCUY "Cuijk"
cap label var NL_0NLDZL "Delfzijl"
cap label var NL_0NLDHR "Den Helder"
cap label var NL_0NLDEV "Deventer"
cap label var NL_0NLDIN "Dinteloord en Prinsenland"
cap label var NL_0NLDOI "Doetinchem"
cap label var NL_0NLDOK "Dokkum"
cap label var NL_0NLDOR "Dordrecht"
cap label var NL_0NLDRU "Druten"
cap label var NL_0NLFRK "Franekeradeel"
cap label var NL_0NLGTB "Geertruidenberg"
cap label var NL_0NLGNM "Genemuiden"
cap label var NL_0NLGEN "Gennep"
cap label var NL_0NLGDR "Goerdereede"
cap label var NL_0NLGOR "Gorinchem"
cap label var NL_0NLGRQ "Groningen"
cap label var NL_0NLHAN "Hansweert"
cap label var NL_0NLHRX "Hardinxveld-Giessendam"
cap label var NL_0NLHAR "Harlingen"
cap label var NL_0NLHAS "Hasselt"
cap label var NL_0NLHIA "Hendrik-Ido-Ambacht"
cap label var NL_0NLHGL "Hengelo"
cap label var NL_0NLHTN "Hontenisse"
cap label var NL_0NLKAM "Kampen"
cap label var NL_0NLKRP "Krimpen aan den Ijssel"
cap label var NL_0NLLAN "Lanwersoog"
cap label var NL_0NLLWR "Leeuwarden"
cap label var NL_0NLLCH "Lochem"
cap label var NL_0NLMSS "Maarssen"
cap label var NL_0NLMSB "Maasbracht"
cap label var NL_0NLMSL "Maassluis"
cap label var NL_0NLMST "Maastricht"
cap label var NL_0NLMEW "Meerlo-Wansum"
cap label var NL_0NLMEP "Meppel"
cap label var NL_0NLMID "Middelburg"
cap label var NL_0NLMIH "Middelharnis"
cap label var NL_0NLMOE "Moerdijk"
cap label var NL_0NLNLK "Nieuw-Lekkerland"
cap label var NL_0NLNIJ "Nijmegen"
cap label var NL_0NLOOS "Oosterhout"
cap label var NL_0NLOSS "Oss"
cap label var NL_0NLOUG "Oud en Nieuw Gastel"
cap label var NL_0NLOAI "Ouderkerk"
cap label var NL_0NLPAP "Papendrecht"
cap label var NL_0NLRAA "Raamsdonk"
cap label var NL_0NLRAS "Ravenstein"
cap label var NL_0NLREW "Reimerswaal"
cap label var NL_0NLRNK "Renkum"
cap label var NL_0NLRHE "Rhenen"
cap label var NL_0NLRID "Ridderkerk"
cap label var NL_0NLOMD "Roermond"
cap label var NL_0NLROO "Roosendaal"
cap label var NL_0NLRTM "Rotterdam"
cap label var NL_0NLROZ "Rozenburg"
cap label var NL_0NLSVG "Sas van Gent"
cap label var NL_0NLSCE "Scheveningen"
cap label var NL_0NLSCI "Schiedam"
cap label var NL_0NLGRA "S-Gravendeel"
cap label var NL_0NLHTB "S-Hertogenbosch"
cap label var NL_0NLSLD "Sliedrecht"
cap label var NL_0NLSLU "Sluiskil"
cap label var NL_0NLSML "Smallingerland"
cap label var NL_0NLSNK "Sneek"
cap label var NL_0NLSTE "Steenbergen"
cap label var NL_0NLTNZ "Terneuzen"
cap label var NL_0NLTEX "Texel"
cap label var NL_0NLTIE "Tiel"
cap label var NL_0NLUTC "Utrecht"
cap label var NL_0NLVEL "Velsen"
cap label var NL_0NLVEN "Venlo"
cap label var NL_0NLVIE "Vierlingsbeek"
cap label var NL_0NLVLA "Vlaardingen"
cap label var NL_0NLVLI "Vlissingen"
cap label var NL_0NLWGW "Wageningen"
cap label var NL_0NLWKD "Werkendam"
cap label var NL_0NLWTE "West-Terschelling"
cap label var NL_0NLWCM "Woudrichem"
cap label var NL_0NLZAA "Zaanstad"
cap label var NL_0NLZSP "Zeeland Seaports"
cap label var NL_0NLZWI "Zwijndrecht"
cap label var NL_0NLZWO "Zwolle"
cap label var NL_0NL887 "Netherlands (small inland waterways) - other ports"
cap label var NL_0NL888 "Netherlands - other ports"
cap label var PL_0PLDAR "Darlowo"
cap label var PL_0PLELB "Elblag"
cap label var PL_0PL011 "Frombork"
cap label var PL_0PLFBK "Frombork"
cap label var PL_0PLGDN "Gdansk"
cap label var PL_0PLGDY "Gdynia"
cap label var PL_0PLHEL "Hel"
cap label var PL_0PLKOL "Kolobrzeg"
cap label var PL_0PLKMR "Krynica Morska"
cap label var PL_0PL012 "Krynica Morska"
cap label var PL_0PLMID "Miedzyzdroje"
cap label var PL_0PLNWA "Nowe Warpno"
cap label var PL_0PLPLC "Police"
cap label var PL_0PLSOP "Sopot"
cap label var PL_0PLSPA "Stepnica"
cap label var PL_0PLSWI "Swinoujscie"
cap label var PL_0PLSZZ "Szczecin"
cap label var PL_0PLTBZ "Trzebiez"
cap label var PL_0PLUST "Ustka"
cap label var PL_0PLWLA "Wladyslawowo"
cap label var PT_0PTADH "Angra do Heroísmo (Ilha Terceira, Açores)"
cap label var PT_0PTAVE "Aveiro"
cap label var PT_0PTCDP "Cais do Pico (Ilha do Pico, Açores)"
cap label var PT_0PTCNL "Caniçal"
cap label var PT_0PTOPO "Douro (Oporto)"
cap label var PT_0PTFAO "Faro"
cap label var PT_0PTFDF "Figueira da Foz"
cap label var PT_0PTFNC "Funchal (Madeira)"
cap label var PT_0PTHOR "Horta (Ilha das Faial, Açores)"
cap label var PT_0PTLAJ "Lajes das Flores (Ilha das Flores, Açores)"
cap label var PT_0PTLEI "Leixões"
cap label var PT_0PTLIS "Lisboa"
cap label var PT_0PTMAD "Madalena (Ilha do Pico, Açores)"
cap label var PT_0PTPDL "Ponta Delgada (Ilha de S. Miguel, Açores)"
cap label var PT_0PTPRM "Portimão"
cap label var PT_0PTPXO "Porto Santo (Ilha de Porto Santo, Madeira)"
cap label var PT_0PTPRG "Praia da Graciosa (Ilha da Graciosa, Açores)"
cap label var PT_0PTPRV "Praia da Vitória (Ilha Terceira, Açores)"
cap label var PT_0PTSET "Setúbal"
cap label var PT_0PTSIE "Sines"
cap label var PT_0PTVEL "Velas (Ilha de São Jorge, Açores)"
cap label var PT_0PTVDC "Viana do Castelo"
cap label var PT_0PTVDP "Vila do Porto (Ilha de Sta Maria, Açores)"
cap label var PT_0PTVNC "Vila Nova do Corvo (Ilha do Corvo, Açores)"
cap label var RO_0ROBAB "Basarabi"
cap label var RO_0ROBRA "Braila"
cap label var RO_0ROCEV "Cernavoda"
cap label var RO_0ROCND "Constanta"
cap label var RO_0ROGAL "Galati"
cap label var RO_0ROLUM "Luminita"
cap label var RO_0ROMAG "Mangalia"
cap label var RO_0ROMED "Medgidia"
cap label var RO_0ROMID "Midia"
cap label var RO_0ROSUL "Sulina"
cap label var RO_0ROTCE "Tulcea"
cap label var RO_0RO888 "Romania - other ports"
cap label var SI_0SIIZO "Izola"
cap label var SI_0SIKOP "Koper"
cap label var SI_0SIPIR "Piran"
cap label var SI_0SI888 "Slovenia - other ports"
cap label var FI_0FIBRA "Brändö"
cap label var FI_0FIDRA "Dragsfjärd"
cap label var FI_0FIECK "Eckerö"
cap label var FI_0FIESP "Espoo"
cap label var FI_0FIEJO "Eurajoki"
cap label var FI_0FIFAR "Färjsund"
cap label var FI_0FIFOG "Föglö"
cap label var FI_0FIFOR "Förby"
cap label var FI_0FIGDB "Godby"
cap label var FI_0FIHMN "Hamina"
cap label var FI_0FI002 "HaminaKotka"
cap label var FI_0FIHKO "Hanko"
cap label var FI_0FIHEL "Helsinki"
cap label var FI_0FIHOU "Houtskär"
cap label var FI_0FIINI "Iniö"
cap label var FI_0FIINK "Inkoo"
cap label var FI_0FIISN "Isnäs"
cap label var FI_0FIKJO "Kalajoki"
cap label var FI_0FIKNT "Kantvik"
cap label var FI_0FIKAS "Kaskinen"
cap label var FI_0FIKEM "Kemi"
cap label var FI_0FIKIM "Kemiö"
cap label var FI_0FIKKR "Kökar"
cap label var FI_0FIKOK "Kokkola"
cap label var FI_0FIKOR "Korpoo"
cap label var FI_0FIKTK "Kotka"
cap label var FI_0FIKVH "Koverhar"
cap label var FI_0FIKRS "Kristinankaupunki"
cap label var FI_0FIKUM "Kumlinge"
cap label var FI_0FILAN "Langnäs"
cap label var FI_0FILAP "Lappohja"
cap label var FI_0FILOV "Loviisa"
cap label var FI_0FILUV "Luvia"
cap label var FI_0FIMHQ "Mariehamn"
cap label var FI_0FIMER "Merikarvia"
cap label var FI_0FINLI "Naantali"
cap label var FI_0FINAU "Nauvo"
cap label var FI_0FIOUL "Oulu"
cap label var FI_0FIPAR "Parainen"
cap label var FI_0FIPER "Pernaja"
cap label var FI_0FIPRS "Pietarsaari"
cap label var FI_0FIPOH "Pohjankuru"
cap label var FI_0FIPOR "Pori"
cap label var FI_0FIRAA "Raahe"
cap label var FI_0FIRAU "Rauma"
cap label var FI_0FIRTR "Rautaruukki"
cap label var FI_0FIRUO "Ruotsinpyhtää"
cap label var FI_0FIRYM "Rymättylä"
cap label var FI_0FISAL "Salo"
cap label var FI_0FISIP "Sipoonlahti"
cap label var FI_0FISKB "Skogby"
cap label var FI_0FISKV "Sköldvik"
cap label var FI_0FIDLS "Taalintehdas"
cap label var FI_0FITVS "Taivassalo"
cap label var FI_0FITAI "Tammisaari"
cap label var FI_0FITEI "Teijo"
cap label var FI_0FITOK "Tolkkinen"
cap label var FI_0FITOR "Tornio"
cap label var FI_0FITKU "Turku"
cap label var FI_0FIUKI "Uusikaupunki"
cap label var FI_0FIVAA "Vaasa"
cap label var FI_0FIVEL "Velkua"
cap label var FI_0FI001 "Finland - other inland ports"
cap label var FI_0FI888 "Finland - other ports"
cap label var SE_1SEAHU "Åhus"
cap label var SE_1SEALA "Ala"
cap label var SE_2SEALN "Älvenäs"
cap label var SE_2SEAMA "Åmål"
cap label var SE_1SEBLV "Bällstaviken"
cap label var SE_1SEBAA "Bålsta"
cap label var SE_1SEBEA "Bergkvara"
cap label var SE_1SEBER "Bergs Oljehamn"
cap label var SE_2SEBOH "Bohus"
cap label var SE_1SEBOL "Bollstabruk"
cap label var SE_1SEBVK "Braviken"
cap label var SE_2SEBRO "Brofjorden"
cap label var SE_1SEBYX "Byxelkrok"
cap label var SE_1SEDEG "Degerhamn"
cap label var SE_1SEDOM "Domsjö"
cap label var SE_1SEELL "Elleholm"
cap label var SE_1SEENK "Enköping"
cap label var SE_1SEFAK "Fagerviken"
cap label var SE_2SEFAG "Falkenberg"
cap label var SE_2SEFJA "Fjällbacka"
cap label var SE_1SEFLI "Flivik"
cap label var SE_1SEFOR "Forsmark"
cap label var SE_1SEGAM "Gamleby"
cap label var SE_1SEGVX "Gävle"
cap label var SE_2SEGOA "Göta"
cap label var SE_2SEGOT "Göteborg"
cap label var SE_1SEGKV "Grankullavik"
cap label var SE_2SEGRE "Grebbestad"
cap label var SE_1SEGRH "Grisslehamn"
cap label var SE_2SEGRU "Gruvön"
cap label var SE_1SEGUN "Gunnebo"
cap label var SE_1SEGUB "Gustavsberg"
cap label var SE_1SEHAK "Hallstavik"
cap label var SE_2SEHAD "Halmstad"
cap label var SE_1SEHAN "Hargshamn"
cap label var SE_1SEHND "Härnösand"
cap label var SE_1SEHEL "Helsingborg"
cap label var SE_2SEHOG "Höganäs"
cap label var SE_2SEHON "Hönsäter"
cap label var SE_1SEHUV "Hudiksvall"
cap label var SE_2SEHUN "Hunnebostrand"
cap label var SE_1SEHUS "Husum"
cap label var SE_1SEIGG "Iggesund"
cap label var SE_1SEJAT "Jätterssön"
cap label var SE_1SEKGG "Kagghamra"
cap label var SE_1SEKAX "Kalix"
cap label var SE_1SEKLR "Kalmar"
cap label var SE_1SEKAL "Kalmarsand"
cap label var SE_1SEKPH "Kappelshamn"
cap label var SE_1SEKPS "Kappelskär"
cap label var SE_1SEKXV "Karlsborg Axelvik"
cap label var SE_1SEKAN "Karlshamn"
cap label var SE_1SEKAA "Karlskrona"
cap label var SE_2SEKSD "Karlstad"
cap label var SE_1SEKLI "Klintehamn"
cap label var SE_1SEKOG "Köping"
cap label var SE_2SEKHN "Kristinehamn"
cap label var SE_1SEKUB "Kubikenborg"
cap label var SE_2SEKUN "Kungshamn"
cap label var SE_1SEKVA "Kvarnholmen"
cap label var SE_1SELAA "Landskrona"
cap label var SE_2SELDK "Lidköping"
cap label var SE_2SELED "Lilla Edet"
cap label var SE_1SELOM "Lomma"
cap label var SE_1SELOT "Löten"
cap label var SE_1SELUG "Lugnvik"
cap label var SE_1SELLA "Luleå"
cap label var SE_2SELYS "Lysekil"
cap label var SE_1SEMMA "Malmö"
cap label var SE_2SEMAD "Mariestad"
cap label var SE_1SEMOR "Mörbylånga"
cap label var SE_2SENOL "Nol (ports)"
cap label var SE_1SENOG "Nordmaling"
cap label var SE_1SENRK "Norrköping"
cap label var SE_1SENOT "Norrsundet"
cap label var SE_1SENOE "Norrtälje"
cap label var SE_1SENYO "Nyköping"
cap label var SE_1SENYN "Nynäshamn (ports)"
cap label var SE_1SEOER "Örnsköldsvik"
cap label var SE_1SEOSK "Oskarshamn"
cap label var SE_1SEOST "Östrand"
cap label var SE_2SEOTT "Otterbäcken"
cap label var SE_1SEOXE "Oxelösund (ports)"
cap label var SE_1SEPIT "Piteå"
cap label var SE_1SERNH "Ronehamn"
cap label var SE_1SERNB "Ronneby"
cap label var SE_1SERUV "Rundvik"
cap label var SE_2SESAF "Säffle"
cap label var SE_1SESIM "Simrishamn"
cap label var SE_2SESKT "Skattkärr"
cap label var SE_1SESFT "Skellefteå"
cap label var SE_2SESKO "Skoghall (ports)"
cap label var SE_1SESSR "Skutskär"
cap label var SE_1SESLI "Slite (ports)"
cap label var SE_1SESOO "Söderhamn"
cap label var SE_1SESOE "Södertälje"
cap label var SE_1SESOL "Sölvesborg"
cap label var SE_1SESOR "Söråker"
cap label var SE_2SESTE "Stenungsund (Ports)"
cap label var SE_1SESTA "Stocka"
cap label var SE_1SESTO "Stockholm"
cap label var SE_1SESTK "Stockvik"
cap label var SE_1SESTV "Stora Vika"
cap label var SE_1SESUS "Storugns"
cap label var SE_1SESTQ "Strängnäs"
cap label var SE_2SESMD "Strömstad"
cap label var SE_1SESDL "Sundsvall"
cap label var SE_2SESUR "Surte"
cap label var SE_1SETOE "Töre"
cap label var SE_1SETRG "Trelleborg"
cap label var SE_2SETHN "Trollhättan (Ports)"
cap label var SE_1SETUN "Tunadal"
cap label var SE_2SEUDD "Uddevalla"
cap label var SE_1SEUME "Umeå"
cap label var SE_1SEUND "Underås"
cap label var SE_1SEUPP "Uppsala"
cap label var SE_1SEUTA "Utansjö"
cap label var SE_1SEVAJ "Väja"
cap label var SE_1SEVAK "Valdemarsvik"
cap label var SE_1SEVAL "Vallvik"
cap label var SE_2SEVAN "Vänersborg"
cap label var SE_2SEVAG "Varberg"
cap label var SE_2SEVGN "Vargön"
cap label var SE_1SEVST "Västerås"
cap label var SE_1SEVVK "Västervik"
cap label var SE_1SEVER "Verkebäck"
cap label var SE_1SEVBY "Visby"
cap label var SE_1SEVIV "Vivstavarv"
cap label var SE_2SEWAL "Wallhamn"
cap label var SE_1SEYST "Ystad"
cap label var SE_1SE020 "Gotland - ports"
cap label var SE_1SE022 "Mälaren - ports"
cap label var SE_2SE021 "Halland - ports"
cap label var SE_2SE023 "Vänern - ports"
cap label var SE_1SE888 "Sweden (Baltic Sea) - other ports"
cap label var SE_1SE88B "Sweden (Baltic Sea) - other ports"
cap label var SE_2SE888 "Sweden (North Sea) - other ports"
cap label var SE_9SE88C "Sweden (confidential data aggregated by Eurostat)"
cap label var SE_9SE88D "Sweden - other ports"
cap label var SE_9SE888 "Sweden (unknown maritime coastal area) - other ports"
cap label var IS_0ISAKR "Akranes"
cap label var IS_0ISAKU "Akureyri"
cap label var IS_0ISASS "Árskógssandur"
cap label var IS_0ISBAK "Bakkafjörður"
cap label var IS_0ISBIL "Bíldudalur"
cap label var IS_0ISBLO "Blönduós"
cap label var IS_0ISBOL "Bolungarvík"
cap label var IS_0ISBGJ "Borgafjörður eystri"
cap label var IS_0ISBRE "Breiðdalsvík"
cap label var IS_0ISBRJ "Brjánslækur"
cap label var IS_0ISDAL "Dalvík"
cap label var IS_0ISDJU "Djúpivogur"
cap label var IS_0ISESK "Eskifjörður"
cap label var IS_0ISFAS "Fáskrúðsfjörður"
cap label var IS_0ISFLA "Flateyri"
cap label var IS_0ISGRD "Garður"
cap label var IS_0ISGRY "Grímsey"
cap label var IS_0ISGRI "Grindavík"
cap label var IS_0ISGRF "Grundarfjörður"
cap label var IS_0ISGRT "Grundartangi"
cap label var IS_0ISHAF "Hafnarfjörður"
cap label var IS_0ISHNR "Hafnir"
cap label var IS_0ISHFN "Höfn Hornafjörður"
cap label var IS_0ISHOF "Hofsós"
cap label var IS_0ISHVK "Hólmavík"
cap label var IS_0ISHRI "Hrísey"
cap label var IS_0ISHUS "Húsavík"
cap label var IS_0ISHVR "Hvalfjørdur-Litlisandur"
cap label var IS_0ISHVM "Hvammstangi"
cap label var IS_0ISISA "Ísafjörður"
cap label var IS_0ISKEF "Keflavík"
cap label var IS_0ISKOP "Kópasker"
cap label var IS_0ISKOV "Kópavogur"
cap label var IS_0ISLAN "Landeyjahofn"
cap label var IS_0IS016 "Litlisandur-Hvalfjordur"
cap label var IS_0ISNES "Neskaupstaður"
cap label var IS_0ISNOU "Norðurfjörður"
cap label var IS_0ISOLF "Ólafsfjörður"
cap label var IS_0ISOLV "Ólafsvík"
cap label var IS_0ISPAT "Patreksfjörður"
cap label var IS_0ISRAU "Raufarhöfn"
cap label var IS_0ISRFJ "Reyðarfjörður"
cap label var IS_0ISRHA "Reykhólar"
cap label var IS_0ISREY "Reykjavík"
cap label var IS_0ISRIF "Rif"
cap label var IS_0ISSAN "Sandgerði"
cap label var IS_0ISSAU "Sauðárkrókur"
cap label var IS_0ISSEY "Seyðisfjörður"
cap label var IS_0ISSIG "Siglufjörður"
cap label var IS_0ISSKA "Skagaströnd"
cap label var IS_0ISSTD "Stöðvarfjörður"
cap label var IS_0ISSTR "Straumsvík"
cap label var IS_0ISSTY "Stykkishólmur"
cap label var IS_0ISSUV "Súðavík"
cap label var IS_0ISSUD "Suðureyri"
cap label var IS_0ISTAL "Tálknafjörður"
cap label var IS_0ISTEY "Þingeyri (Thingeyri)"
cap label var IS_0ISTHH "Þorlákshöfn (Thorlakshofn)"
cap label var IS_0ISTHO "Þórshöfn (Thorshofn)"
cap label var IS_0ISVES "Vestmannaeyjar"
cap label var IS_0ISVOG "Vogar"
cap label var IS_0ISVPN "Vopnafjörður"
cap label var IS_0IS888 "Iceland - other ports"
cap label var NO_0NOAAF "Åfjord"
cap label var NO_0NOAFT "Agnefest"
cap label var NO_0NOAES "Ålesund"
cap label var NO_0NOALF "Alta"
cap label var NO_0NOADY "Andøy"
cap label var NO_0NOAAN "Årdal"
cap label var NO_0NOARE "Arendal"
cap label var NO_0NOASL "Askvoll"
cap label var NO_0NOAUL "Aurland"
cap label var NO_0NOASV "Austevoll"
cap label var NO_0NOBAR "Bærum/Sandvika/Lysaker"
cap label var NO_0NOBLL "Ballangen"
cap label var NO_0NOBJF "Båtsfjord"
cap label var NO_0NOBEJ "Beiarn"
cap label var NO_0NOBGO "Bergen"
cap label var NO_0NOBGN "Bergneset"
cap label var NO_0NOBVG "Berlevåg"
cap label var NO_0NOBJU "Bjugn/Lysøysund/Botngård"
cap label var NO_0NOBOX "Bø"
cap label var NO_0NOBOO "Bodø"
cap label var NO_0NOOYB "Bogoy"
cap label var NO_0NOBRG "Borg"
cap label var NO_0NOBRR "Borre"
cap label var NO_0NOBRE "Bremanger"
cap label var NO_0NOBRO "Brønnøy"
cap label var NO_0NOBNN "Bronnoysund"
cap label var NO_0NODRM "Drammen"
cap label var NO_0NODYL "Dyroyhamn"
cap label var NO_0NOEGE "Egersund"
cap label var NO_0NOEIL "Eidslandet"
cap label var NO_0NOEGD "Eigersund"
cap label var NO_0NOETN "Etne"
cap label var NO_0NOFAN "Farsund"
cap label var NO_0NOFAU "Fauske"
cap label var NO_0NOFIS "Fiska"
cap label var NO_0NOFKS "Flakstad"
cap label var NO_0NOFFD "Flekkefjord"
cap label var NO_0NOFRO "Florø/Flora"
cap label var NO_0NOFSN "Fosnes"
cap label var NO_0NOFRK "Fredrikstad"
cap label var NO_0NOFUS "Fusa"
cap label var NO_0NOKAF "Gaivuotna - Kåfjord"
cap label var NO_0NOGRV "Granvin"
cap label var NO_0NOGTD "Grimstad"
cap label var NO_0NOGUL "Gulen"
cap label var NO_0NOHAA "Hå"
cap label var NO_0NOHAD "Hadsel"
cap label var NO_0NOHAL "Halden"
cap label var NO_0NOHFT "Hammerfest"
cap label var NO_0NOHRI "Hareid"
cap label var NO_0NOHRD "Harstad"
cap label var NO_0NOHAU "Haugesund"
cap label var NO_0NOHOL "Holmestrand"
cap label var NO_0NOHVG "Honningsvåg"
cap label var NO_0NOHOR "Horten"
cap label var NO_0NOHYR "Høyanger"
cap label var NO_0NOHUS "Husnes"
cap label var NO_0NOIBE "Ibestad"
cap label var NO_0NOJON "Jondal"
cap label var NO_0NOKAY "Karlsoy"
cap label var NO_0NOKAS "Karmsund"
cap label var NO_0NOKIV "Kinsarvik"
cap label var NO_0NOKKN "Kirkenes"
cap label var NO_0NONTY "Kjøpmannskjær/Nøtterøy"
cap label var NO_0NOKRA "Kragerø"
cap label var NO_0NOKRS "Kristiansand S"
cap label var NO_0NOKSU "Kristiansund N/Grip"
cap label var NO_0NOKVN "Kvænangen"
cap label var NO_0NOKVM "Kvam"
cap label var NO_0NOKVD "Kvinesdal"
cap label var NO_0NOKVH "Kvinnherad"
cap label var NO_0NONZC "Larsnes"
cap label var NO_0NOLAR "Larvik"
cap label var NO_0NOLEB "Lebesby"
cap label var NO_0NOLEF "Leirfjord"
cap label var NO_0NOLKA "Leka"
cap label var NO_0NOLIL "Lillesand"
cap label var NO_0NOLOD "Lødingen"
cap label var NO_0NOLON "Lonevag"
cap label var NO_0SJLYR "Longyearbyen"
cap label var NO_0NOLOP "Loppa"
cap label var NO_0NOLUS "Luster"
cap label var NO_0NOLND "Lyngdal"
cap label var NO_0NOLYN "Lyngen"
cap label var NO_0NOLYD "Lyngseidet"
cap label var NO_0NOMAY "Måløy"
cap label var NO_0NOMAN "Mandal"
cap label var NO_0NOMSY "Måsøy"
cap label var NO_0NOMEY "Meløy/Glomfjord/Ørnes"
cap label var NO_0NOMOD "Modalen"
cap label var NO_0NOMQN "Mo i Rana"
cap label var NO_0NOMOL "Molde"
cap label var NO_0NOMJF "Mosjøen"
cap label var NO_0NOMSK "Moskenes"
cap label var NO_0NOMSS "Moss"
cap label var NO_0NOOSY "Namsos"
cap label var NO_0NONVK "Narvik"
cap label var NO_0NONSN "Nesna"
cap label var NO_0NOEID "Nordfjordeid/Eid"
cap label var NO_0NONFO "Nordfosen"
cap label var NO_0NOODD "Odda"
cap label var NO_0NOOKF "Oksfjord"
cap label var NO_0NOMYO "Øksnes/Myre"
cap label var NO_0NOOLL "Olderdalen"
cap label var NO_0NOOLN "Ølen"
cap label var NO_0NOORK "Orkanger"
cap label var NO_0NOOLA "Ørland/Brekstad"
cap label var NO_0NOORS "Ørsta"
cap label var NO_0NOOSN "Osen"
cap label var NO_0NOOSL "Oslo"
cap label var NO_0NOOST "Osterøy"
cap label var NO_0NOGVL "Porsgrunn, Rafnes, Herøya, Brevik, Skien, Langesund, Voldsfjorden"
cap label var NO_0NORMB "Ramberg"
cap label var NO_0NORNA "Rana"
cap label var NO_0NORIS "Risør"
cap label var NO_0NORSH "Risøyhamn"
cap label var NO_0NOROG "Rognan"
cap label var NO_0NORVK "Rorvik"
cap label var NO_0NOSAL "Salangen"
cap label var NO_0NOSDL "Saltdal/Rognan"
cap label var NO_0NOSAT "Salten"
cap label var NO_0NOSAX "Sand"
cap label var NO_0NOTRF "Sandefjord"
cap label var NO_0NOSAS "Sandnes"
cap label var NO_0NOSSJ "Sandnessjøen"
cap label var NO_0NOSAI "Sandviksberget"
cap label var NO_0NOSAU "Sauda"
cap label var NO_0NOSKY "Skjervøy"
cap label var NO_0NOSOG "Sogndal"
cap label var NO_0NOSNE "Søgne"
cap label var NO_0NOSOK "Sokndal"
cap label var NO_0NOSMN "Sømna"
cap label var NO_0NOSOF "Sorfold"
cap label var NO_0NOSRA "Sørreisa"
cap label var NO_0NOSLX "Sortland"
cap label var NO_0NOSUZ "Stamsund"
cap label var NO_0NOSVG "Stavanger"
cap label var NO_0NOSTG "Steigen"
cap label var NO_0NOSNS "Steinesjoen"
cap label var NO_0NOSTE "Steinkjer"
cap label var NO_0NOSTH "Steinshamn"
cap label var NO_0NOSTK "Stokke/Melsomvik"
cap label var NO_0NOSRP "Stord"
cap label var NO_0NOSTF "Storfjord"
cap label var NO_0NOSTD "Strand"
cap label var NO_0NOSRN "Stranda"
cap label var NO_0NOSUL "Suldal"
cap label var NO_0NOSUN "Sunndal/Sunndalsøra"
cap label var NO_0NO720 "Svalbard"
cap label var NO_0SJ888 "Svalbard and Jan Mayen"
cap label var NO_0SJSVE "Sveagruva (Svalbard)"
cap label var NO_0NOSVE "Svelgen"
cap label var NO_0NOSVJ "Svolvaer"
cap label var NO_0NOSYK "Sykkylven"
cap label var NO_0NOTON "Tønsberg"
cap label var NO_0NOTOS "Tromsø"
cap label var NO_0NOTRD "Trondheim/Flakk"
cap label var NO_0NOTYN "Tysnes"
cap label var NO_0NOVDS "Vadsø"
cap label var NO_0NOVEY "Værøy"
cap label var NO_0NOVGN "Vågan/Kabelvåg"
cap label var NO_0NOVAD "Valldal"
cap label var NO_0NOVAY "Vanylven"
cap label var NO_0NOVAO "Vardø"
cap label var NO_0NOVEG "Vega"
cap label var NO_0NOVER "Verdal"
cap label var NO_0NOVVY "Vestvågøy"
cap label var NO_0NOVKN "Vikna"
cap label var NO_0NO888 "Norway - other ports"
cap label var NO_0NO88N "Norway - other ports - northern"
cap label var NO_0NO88S "Norway - other ports - southern"
cap label var UK_1GBABD "Aberdeen"
cap label var UK_1GBAPP "Appledore"
cap label var UK_1GBASG "Ardrishaig"
cap label var UK_1GBAYR "Ayr"
cap label var UK_1GBBLR "Ballylumford"
cap label var UK_1GBBND "Barnstaple"
cap label var UK_1GBCBA "Barra Castlebay"
cap label var UK_1GBBIF "Barrow-In-Furness"
cap label var UK_1GBBAD "Barry"
cap label var UK_1GBBEL "Belfast"
cap label var UK_1GBBWK "Berwick-On-Tweed"
cap label var UK_1GBBID "Bideford"
cap label var UK_1GBBLY "Blyth"
cap label var UK_1GBBOS "Boston"
cap label var UK_1GBBRW "Bridgwater"
cap label var UK_1GBBLS "Brightlingsea"
cap label var UK_1GBBRS "Bristol"
cap label var UK_1GBBRX "Brixham"
cap label var UK_1GBBUC "Buckie"
cap label var UK_1GBBUH "Burghead"
cap label var UK_1GBBPT "Burry port"
cap label var UK_1GBCYN "Cairnryan"
cap label var UK_1GBCBT "Campbeltown"
cap label var UK_1GBCDF "Cardiff"
cap label var UK_1GBCHF "Charlestown"
cap label var UK_1GBCST "Chichester"
cap label var UK_1GBCYP "Clydeport"
cap label var UK_1GBCOL "Colchester"
cap label var UK_1GBCLR "Coleraine"
cap label var UK_1GBCOR "Corpach"
cap label var UK_1GBCOW "Cowes (Isle of Wight)"
cap label var UK_1GBCNU "Craignure"
cap label var UK_1GBCRN "Cromarty Firth"
cap label var UK_1GBDTM "Dartmouth"
cap label var UK_1GBDNQ "Dean Point Quarry"
cap label var UK_2IMDGS "Douglas (Isle of Man)"
cap label var UK_1GBDVR "Dover"
cap label var UK_1GBDUN "Dundee"
cap label var UK_1GB230 "Dutch River Wharf"
cap label var UK_1GBEXM "Exmouth"
cap label var UK_1GBFAL "Falmouth"
cap label var UK_1GBFHM "Fareham"
cap label var UK_1GBFXT "Felixstowe"
cap label var UK_1GBFIS "Fishguard"
cap label var UK_1GBFLE "Fleetwood"
cap label var UK_1GBFOL "Folkestone"
cap label var UK_1GBFOR "Forth"
cap label var UK_1GBFDK "Fosdyke"
cap label var UK_1GBFOY "Fowey"
cap label var UK_1GBFRB "Fraserburgh"
cap label var UK_1GBGTN "Garston"
cap label var UK_1GBILL "Gill's Bay Scotland"
cap label var UK_1GBGIR "Girvan"
cap label var UK_1GBGSA "Glensanda"
cap label var UK_1GBGOO "Goole"
cap label var UK_1GBGTY "Great Yarmouth"
cap label var UK_1GBHRW "Harwich"
cap label var UK_1GBHYM "Heysham"
cap label var UK_1GBHLY "Holyhead"
cap label var UK_1GBHWZ "Hugh Town"
cap label var UK_1GBHUL "Hull"
cap label var UK_1GBIMM "Immingham"
cap label var UK_1GBINK "Inverkeithing"
cap label var UK_1GBINV "Inverness"
cap label var UK_1GBIPS "Ipswich"
cap label var UK_1GBKLR "Kilroot"
cap label var UK_1GBKPS "Kilroot Power Station Jetty"
cap label var UK_1GBKLN "King's Lynn"
cap label var UK_1GBKWL "Kirkwall"
cap label var UK_1GBLAN "Lancaster"
cap label var UK_1GBLAR "Larne"
cap label var UK_1GBLER "Lerwick (Shetland Islands)"
cap label var UK_1GBLIT "Littlehampton"
cap label var UK_1GBLIV "Liverpool"
cap label var UK_1GBLDO "Llandudno"
cap label var UK_1GBLLD "Llandulas"
cap label var UK_1GB231 "Loch Carnan"
cap label var UK_1GBLOL "Lochaline"
cap label var UK_1GBLRP "Loch Ryan Pt"
cap label var UK_1GBLON "London"
cap label var UK_1GBLDY "Londonderry"
cap label var UK_1GBLOW "Lowestoft"
cap label var UK_1GBMCD "Macduff"
cap label var UK_1GBMGO "Magheramorne"
cap label var UK_1GBMAL "Maldon"
cap label var UK_1GBMNC "Manchester"
cap label var UK_1GBMED "Medway"
cap label var UK_1GBMLF "Milford Haven"
cap label var UK_1GBMIS "Mistley"
cap label var UK_1GBMON "Montrose"
cap label var UK_1GBCHE "Mostyn"
cap label var UK_1GBNEA "Neath"
cap label var UK_1GBNCL "Newcastle-Upon-Tyne"
cap label var UK_1GBNHV "Newhaven"
cap label var UK_1GBNPO "Newport (Isle of Wight)"
cap label var UK_1GBNPT "Newport, Gwent"
cap label var UK_1GBOBA "Oban"
cap label var UK_1GBPAD "Padstow"
cap label var UK_1GBPAR "Par"
cap label var UK_1GBPEM "Pembroke"
cap label var UK_1GBPEN "Penzance"
cap label var UK_1GBPER "Perth"
cap label var UK_1GBPHD "Peterhead"
cap label var UK_1GBPLY "Plymouth"
cap label var UK_1GBPOO "Poole"
cap label var UK_1GBPPE "Port Penrhyn"
cap label var UK_1GBPSB "Port Sutton Bridge"
cap label var UK_1GBPTB "Port Talbot"
cap label var UK_1GBPOH "Porthoustock England"
cap label var UK_1GBPTL "Portland"
cap label var UK_1GBPTR "Portrush"
cap label var UK_1GBPME "Portsmouth"
cap label var UK_1GBRMG "Ramsgate"
cap label var UK_1GB221 "River Hull & Humber"
cap label var UK_1GB222 "River Ouse"
cap label var UK_1GBRFD "Rochford"
cap label var UK_1GBRYE "Rye"
cap label var UK_1GBSWY "Scalloway (Shetland Islands)"
cap label var UK_1GBSCR "Scrabster"
cap label var UK_1GBSEA "Seaham"
cap label var UK_1GBSSS "Sharpness"
cap label var UK_1GBSHO "Shoreham"
cap label var UK_1GBSHT "Shotton"
cap label var UK_1GBSIL "Silloth"
cap label var UK_1GBSOU "Southampton"
cap label var UK_1GBSWD "Southwold"
cap label var UK_3JESTH "St Helier (Jersey)"
cap label var UK_3GGSPT "St Peter Port (Guernsey)"
cap label var UK_1GBSTO "Stornoway"
cap label var UK_1GBSTR "Stranraer"
cap label var UK_1GBSOY "Stronsay"
cap label var UK_1GBSUL "Sullom Voe"
cap label var UK_1GBSUN "Sunderland"
cap label var UK_1GBSWA "Swansea"
cap label var UK_1GBMME "Tees & Hartlepool"
cap label var UK_1GBTNM "Teignmouth"
cap label var UK_1GBTOR "Torquay"
cap label var UK_1GB203 "Trent River"
cap label var UK_1GBTRN "Troon"
cap label var UK_1GBTRU "Truro"
cap label var UK_1GBTYN "Tyne"
cap label var UK_1GBULL "Ullapool"
cap label var UK_1GBWLA "Wallasea"
cap label var UK_1GBWPT "Warrenpoint"
cap label var UK_1GBWEY "Weymouth"
cap label var UK_1GBWTB "Whitby"
cap label var UK_1GBWHV "Whitehaven"
cap label var UK_1GBWTS "Whitstable"
cap label var UK_1GBWIC "Wick"
cap label var UK_1GBWIS "Wisbech"
cap label var UK_1GBWOR "Workington"
cap label var UK_1GB888 "United Kingdom - other ports"
cap label var UK_2IM888 "United Kingdom (Isle of Man) - other ports"
cap label var UK_3GG888 "United Kingdom (Guernsey) - other ports"
cap label var UK_3JE888 "United Kingdom (Jersey) - other ports"
cap label var ME_0MEBAR "Bar"
cap label var ME_0MEKOT "Kotor"
cap label var ME_0MEZEL "Zelenika"
cap label var TR_2TRALA "Alanya"
cap label var TR_2TRALI "Aliaga"
cap label var TR_1TRAMA "Amasra"
cap label var TR_1TRAMB "Ambarli"
cap label var TR_2TRAMB "Ambarli"
cap label var TR_2TRANA "Anamur"
cap label var TR_2TRAYT "Antalya"
cap label var TR_2TRAYV "Ayvalik"
cap label var TR_2TRBDM "Bandirma"
cap label var TR_1TRBTN "Bartin"
cap label var TR_2TRBXN "Bodrum"
cap label var TR_2TRBOT "Botas"
cap label var TR_2TRBZC "Bozcaada"
cap label var TR_2TRCKZ "Canakkale"
cap label var TR_2TRCES "Cesme"
cap label var TR_2TRDAT "Datca"
cap label var TR_2TRDIK "Dikili, Izmir"
cap label var TR_2TREDO "Edremit"
cap label var TR_2TRENE "Enez"
cap label var TR_2TRERK "Erdek"
cap label var TR_1TRERE "Eregli"
cap label var TR_1TRFAS "Fatsa"
cap label var TR_2TRFET "Fethiye"
cap label var TR_2TRFIN "Finike"
cap label var TR_2TRFOC "Foca"
cap label var TR_2TRGEL "Gelibolu"
cap label var TR_2TRGEM "Gemlik"
cap label var TR_1TRGZE "Gerze"
cap label var TR_1TRGIR "Giresun"
cap label var TR_2TRGCK "Gocek"
cap label var TR_2TRGCA "Gokceada"
cap label var TR_1TRGOR "Gorele"
cap label var TR_2TRGUL "Gulluk"
cap label var TR_1TRHOP "Hopa"
cap label var TR_1TRIGN "Igneada"
cap label var TR_1TRINE "Inebolu"
cap label var TR_2TRISK "Iskenderun, Hatay"
cap label var TR_2TRIST "Istanbul"
cap label var TR_2TRIZM "Izmir"
cap label var TR_2TRIZT "Izmit"
cap label var TR_2TRKRB "Karabiga"
cap label var TR_2TRKAS "Kas"
cap label var TR_1TRKFK "Kefken"
cap label var TR_2TRKMR "Kemer"
cap label var TR_2TRKUS "Kusadasi"
cap label var TR_2TRMRA "Marmara Adasi"
cap label var TR_2TRMRM "Marmaris"
cap label var TR_2TRMER "Mersin"
cap label var TR_2TRMUD "Mudanya, Bursa"
cap label var TR_1TRORD "Ordu"
cap label var TR_1TRPZR "Pazar"
cap label var TR_1TRRIZ "Rize"
cap label var TR_1TRSSX "Samsun"
cap label var TR_1TRSLE "Sile"
cap label var TR_2TRSIL "Silivri"
cap label var TR_1TRSIC "Sinop"
cap label var TR_1TRSUR "Surmene"
cap label var TR_2TRTAS "Tasucu"
cap label var TR_2TRTEK "Tekirdag"
cap label var TR_1TRTIR "Tirebolu"
cap label var TR_1TRTZX "Trabzon"
cap label var TR_1TRUNY "Unye"
cap label var TR_1TRVAK "Vakfikebir"
cap label var TR_2TRYAL "Yalova"
cap label var TR_1TRZON "Zonguldak"
cap label var TR_9TR888 "Turkey (unknown maritime coastal area) - other ports"
cap label var TOP_20 "Top 20 ports"
cap label var TOP_5 "Top 5 ports"
cap label var PORT_EU "EU ports"
