cap label var TOTAL "All methods"
cap label var PON "Ponds"
cap label var TNK "Tanks and raceways"
cap label var ENC "Enclosures and pens"
cap label var CAG "Cages"
cap label var RES "Recirculation systems"
cap label var ONB "On bottom"
cap label var OFB "Off bottom"
cap label var OTH "Other methods"
cap label var NSP "Not specified"
