cap label var TOTAL "Total"
cap label var STM_BTURB "Steam - backpressure turbine"
cap label var STM_CTURB "Steam - condensing turbine (eff ≥ 80%)"
cap label var INCOMB "Internal combustion"
cap label var GTURB "Gas turbine"
cap label var CCYCLE "Combined cycle"
cap label var THCV "Conventional thermal"
cap label var THCV_STM "Steam"
cap label var THCV_INCOMB "Internal combustion"
cap label var THCV_GTURB "Gas turbine"
cap label var THCV_CCYCLE "Combined cycle"
cap label var THCV_OTH "Other type of generation"
cap label var SGLFF "Single fuel fired"
cap label var SGLFF_COAL "Single fuel fired - coal and coal products"
cap label var SGLFF_LIQF_RG "Single fuel fired - liquid fuels and refinery gas"
cap label var SGLFF_NG_GWG "Single fuel fired - natural gas and gas works gas"
cap label var SGLFF_PEAT "Single fuel fired - peat"
cap label var SGLFF_BIOF_WST "Single fuel fired - biofuels and wastes"
cap label var MLTFF_SLD_LIQ "Multifuel fired - solid and liquid"
cap label var MLTFF_LIQ_NG "Multifuel fired - liquid and natural gas"
cap label var MLTFF_SLD_NG "Multifuel fired - solid and natural gas"
cap label var MLTFF_SLD_LIQ_NG "Multifuel fired - solid, liquid and natural gas"
cap label var OTH "Other"
