cap label var TOTAL "All functions"
cap label var SICK "Sickness/Health care"
cap label var DISA "Disability"
cap label var OLD "Old age"
cap label var SURVIV "Survivors"
cap label var FAM "Family/Children"
cap label var UNEMPLOY "Unemployment"
cap label var HOUSE "Housing"
cap label var EXCLU "Social exclusion n.e.c."
